### ISSUE TITLE
bug: roadmap items shift to adjust for content on hover

### ISSUE THREAD

**Issue by ethikz** [gitcoinco/web#100]
#64  

Some blocks still shift and it shifts when content fits, see:
https://drive.google.com/open?id=1Oaj7HIMb9gt4PPbd6x0w06njsiicXf2v

**Comment by thelostone-mc** [comment]
@alx this would a good starting point ( if @ethikz hasn't gotten to it already ) :)

**Comment by ethikz** [comment]
I haven't gotten to this already. It is still available
