### ISSUE TITLE
Delete wallet connect in tabbed cart

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10005]
**User Story:**
As a grant donor
I want to see the Wallet Connect modal only when I need it
So that I don't have to go through unnecessary steps to donate

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/cart and have grants to checkout on multiple chains
WHEN I click to a different tab
THEN I do not see the Wallet Connect modal

**Product & Design Links:**
Figma — "[Ready for Story: Checkout](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=133%3A5208)" —> 3: Delete modal in tab

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
Note: The fix which is thrown into https://github.com/gitcoinco/web/issues/9991 would ideally fix this.
So do sync up with @gravityblast before taking this up

**Comment by thelostone-mc** [comment]
@gravityblast Yo doesn't https://github.com/gitcoinco/web/pull/10087 also take care of this ?

**Comment by EmHsiehGitcoin** [comment]
Looks good to me now!
