### ISSUE TITLE
Update cart design elements

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10004]
**User Story:**
As a grant donor
I want to see consistent UI elements on checkout
So that I intuitively know how the page works

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/cart
WHEN I look at the header of the grants cart section
THEN I see updated header design elements

GIVEN that I am on gitcoin.co/grants/cart
WHEN I look at the summary window
THEN I see the revised design elements

GIVEN that I am on gitcoin.co/grants/cart
WHEN I look at the list of grants in my cart
THEN I don't see the "Not in active round" text

**Product & Design Links:**
[Figma file](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=133%3A5208): "Ready for Story: Checkout" -> 1: UI Refresh

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by Jer-Sch** [comment]
I think we should point this higher than a 1. Initially it appeared that this ticket was just a matter of rearranging some UI elements, but there are a couple items that I think increase the point value of this task.

1. Adding a value input and moving the "apply to all" button to the top of page requires re-writing some of the existing JavaScript. The current implementation supports an "apply to all" feature by grabbing the `grant_donation_amount` from the first grant on the page and applying it to all other grants. The current function takes that first grant as an argument, and so capturing that value from the input field at the top of the page and applying it to all grants on the page is going to require some re-writing there.
2. The mobile designs had not been created when this ticket was pointed, and I think adding mobile designs for it increases the point value. Alternatively, I think it would make sense to make the mobile layout a separate ticket.

This ticket feels like it should be at least a 3 to me.

**Comment by nfrgosselin** [comment]
Hmm... I'm not seeing these new elements on staging (see below). I'm going to move this back to the backlog

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/15041635/156087566-dce9dace-8e65-4809-a401-94b77a236e37.png">

**Comment by EmHsiehGitcoin** [comment]
> Adding a value input and moving the "apply to all" button to the top of page requires re-writing some of the existing JavaScript. The current implementation supports an "apply to all" feature by grabbing the grant_donation_amount from the first grant on the page and applying it to all other grants. The current function takes that first grant as an argument, and so capturing that value from the input field at the top of the page and applying it to all grants on the page is going to require some re-writing there.

Happy to find a different way to avoid complications! Modified Figma file accordingly. Will discuss with the team at IPM for different options.

**Comment by EmHsiehGitcoin** [comment]
I think staging just refreshed and I see these updates now
<img width="1261" alt="Screen Shot 2022-03-01 at 8 08 04 AM" src="https://user-images.githubusercontent.com/96255151/156177659-6480d9a9-99ac-48df-b9be-06f75ff196cd.png">

This is what I see live (not on staging) 
<img width="1225" alt="Screen Shot 2022-03-01 at 8 50 13 AM" src="https://user-images.githubusercontent.com/96255151/156181546-3e7f2166-6592-423c-8032-ae5754142997.png">

Will comment further later

**Comment by EmHsiehGitcoin** [comment]
@schultztimothy 
Figma file: label '3.3.2022 Review' 
[https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=133%3A5208](url)

Task list:
- Adjust elements to align grid 
- Adjust vertical (listed) spacing
- Change the X icon to Trashcan for list items
- Move the banner to above title
- Shorten tab length*
- Bring up the summary element to align top w/ tab*
*changes in v.1 only

<img width="1773" alt="Screen Shot 2022-03-02 at 8 57 15 PM" src="https://user-images.githubusercontent.com/96255151/156481645-4123ff8e-803d-4168-8894-54f6c246918d.png">

**Comment by EmHsiehGitcoin** [comment]
![Screen Shot 2022-04-04 at 4 28 33 PM](https://user-images.githubusercontent.com/96255151/161626612-26f8407d-223a-44d3-a206-1317a4de0942.png)
