### ISSUE TITLE
Gitcoin explorer overwrites original bounty description with other user's arbitrary GitHub data

### ISSUE THREAD

**Issue by dolebas** [gitcoinco/web#1000]
### User Story

As an issue funder, I expect input to the "Issue Description" form field to be displayed somewhere after funding an issue.

### Description

*Type*: Bug

### Current Behavior

Submitted the Fund Issue form funding the issue linked below but can't find the data I put in the "Issue Description" field displayed anywhere.

![image](https://user-images.githubusercontent.com/27515901/39362061-53f40162-4a25-11e8-85f7-0d7586dd6514.png)

https://gitcoin.co/issue/uport-project/demo/42/314

### Reproduction

Fund a new issue similar to the linked issue and enter data in the Issue Description field.

### Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Wallet          | Metamask
| Browser          | Brave
| Operating System | macOS

**Comment by mbeacom** [comment]
This description?  
<img width="920" alt="screenshot 2018-04-27 08 50 07" src="https://user-images.githubusercontent.com/7315957/39363359-07dba172-49f8-11e8-93fd-3e35599e0142.png">

**Comment by dolebas** [comment]
No, that description was entered by the github issue creator, AlbertoElias, on Mar 12. I entered something like this below when funding the issue.

### Definition of Done

Any end-user of uport-project/demo should be able to login using with an android device, without the requirement of copy/pasting any url between browsers/tabs.

**Comment by mbeacom** [comment]
Was the issue already funded? I am confused as to what you were doing in order to produce this outcome.  What exactly were you funding? Do you see *your* bounty anywhere? Do you have a tx?
Apologies for the confusion.

**Comment by dolebas** [comment]
It wasn't previously funded. Simply followed the instructions. Can probably reproduce it by funding a new issue and take a screen shot of the exact form fields, if you are not able to reproduce it?

**Comment by dolebas** [comment]
Only thing I can think of is that I used markdown in the desc field.

**Comment by dolebas** [comment]
Also, my github has no write access to the repo.

**Comment by mbeacom** [comment]
Can you link me to the bounty you opened where you encountered this? The bounty description is populated with the Github issue description, but it is editable before submitting the bounty.  I am not sure what you're question is.  Which bounty of yours isn't displaying your provided description?

**Comment by dolebas** [comment]
Submitted few hours ago, the uPort demo one.

Is it assumed that the bounty creator = github issue creator?

**Comment by thelostone-mc** [comment]
@dolebas Don't hate me for this, but let me just revisit the steps you took in the same order

- Went to the fund bounty page
- Entered the github issue
- It got auto populate with what `AlbertoElias` had written 
- You over-wrote it with 
> Any end-user of uport-project/demo should be able to login using with an android device, without the requirement of copy/pasting any url between browsers/tabs.

- You clicked submit and the bounty on gitcoin still reflects what `AlbertoElias` had written

PS: Additionally I'm assuming since the description failed , you went ahead and manually pasted the comment [here](https://github.com/uport-project/demo/issues/42#issuecomment-384949608)

Did I get that right ?

**Comment by mbeacom** [comment]
@dolebas Anyone can open a bounty for an issue. The bounty description *should* retain the description you enter.  Could the data from GH have populated after you entered your description?  The page makes a request against the GH api for the GH url associated description, title, etc.

<img width="420" alt="screenshot 2018-04-27 10 13 19" src="https://user-images.githubusercontent.com/7315957/39367071-c2d6a836-4a03-11e8-98de-292127a2662f.png">

Did the description already display:

```
After signing in and confirming transaction from the uPort app, my browser opens the callback URL that has the access token, but the site doesn't log in using that information
```

Did you remove this description and add yours or was there nothing there when you entered your description?

Sorry for the confusion! 😛

**Comment by thelostone-mc** [comment]
> Is it assumed that the bounty creator = github issue creator?

Nope ! 

> Also, my github has no write access to the repo.

Yeah this should still be fine ! If you were to fund an issue created by me -> you could do it via gitcoin 
but the issue description section will be auto-filled from the github issue (and not from the comment posted by the bounty issuer )

**Comment by thelostone-mc** [comment]
@dolebas Ugh yeah !! You make a valid point ^_^
@PixelantDesign we need to give the description bigger. Everyone on github is used to a big box to list out the issue. This does seem cramped up

**Comment by mbeacom** [comment]
I agree we should probably expanding the size of the description text area.

**Comment by dolebas** [comment]
It seems like anything in the description field is automatically overwritten whenever the URL field is activated, regardless if the field is edited.

Maybe a prompt for a confirmation before edited fields automatically are overwritten would help? If the user has spent some time crafting a thought out description it could be a bummer if it is suddenly deleted because the URL field is mistakenly activated somehow?

No worries in my case tho, I just added the essentials as a comment to the issue, as you had already figured out @thelostone-mc :)

**Comment by owocki** [comment]
> It seems like anything in the description field is automatically overwritten whenever the URL field is activated, regardless if the field is edited.

This is good feedback.  We should probably make it clear that entering a github issue URL overwrites the desc text (or, per @dolebas 's suggestion, maybe ask for confirmation before we prefill if there is edited text there)

**Comment by dolebas** [comment]
If it helps, I noticed that there also seems to be some overwriting of the "Issue Title" field going on after the bounty is created as well.

Yesterday:
![image](https://user-images.githubusercontent.com/27515901/39396057-575f4d94-4ae7-11e8-9b65-6f318fc617c4.png)

Today:
![image](https://user-images.githubusercontent.com/27515901/39396063-71e2c484-4ae7-11e8-99cb-0894d16b7fda.png)

Maybe radio buttons in the bounty form for choosing custom or pulled title/desc would make it easier on the backend, and more clear on the frontend at the same time?

**Comment by thelostone-mc** [comment]
Hmm when I had checked on this yesterday I'd seen the same Not Working In Mobile 🤔 
need to check this out

**Comment by dolebas** [comment]
Check gitcoinbot on twitter

**Comment by owocki** [comment]
yeah we sync the github title to the gitcoin title.  cc @PixelantDesign maybe its worth making this a configurable option...

**Comment by dolebas** [comment]
interesting, original title is back!

![image](https://user-images.githubusercontent.com/27515901/39470886-763775c4-4d40-11e8-8796-e554ccd5cdd9.png)

**Comment by PixelantDesign** [comment]
Thanks for reporting this @dolebas! Will take a look at some ways to handle this.

**Comment by PixelantDesign** [comment]
If I understand correctly seems like if a user starts editing content prior to the content fully populating, the additional information entered is lost. 

Saptak and I discussed that a simple solution could be, we message that the information is loading and once that loads, we allow the user to edit the details (it’ll obviously need to get pushed back to Github along with the funded amount). 

What do you all think of this approach? 
@dolebas @owocki @mbeacom @thelostone-mc

**Comment by SaptakS** [comment]
> it’ll obviously need to get pushed back to Github 

@PixelantDesign most probably we won't be able to update the github description because of lack permission. Max we can do is maybe make a comment with the updated description. But maybe that doesn't exactly solve the problem.

**Comment by PixelantDesign** [comment]
Gotya. Allowing alternative descriptions could be confusing. I’ll see if we can do some quick tests with users next week.

**Comment by dolebas** [comment]
Thanks for picking up the discussion @PixelantDesign I believe the root cause for this issue is uncertain so any approach that simplifies synchronisation would help.

**Comment by dolebas** [comment]
If it helps, compare the description field on Bounties.network with the corresponding field on Gitcoin.

https://gitcoin.co/issue/uport-project/demo/42/314
https://beta.bounties.network/bounty/v1/314

**Comment by dolebas** [comment]
The steps to reproduce this issue would be:

1. Go to https://gitcoin.co/funding/new and fill out the form fields, in order
3. Edit the Title/Description field(s)
4. Take a screenshot and submit the form
5. Wait for ~24h
6. Compare the Gitcoin issue explorer with the screenshot (or the IPFS bounty contract data)

Feel free to reach out if anything is still unclear.

**Comment by kuhnchris** [comment]
@thelostone-mc / @dolebas can you still reproduce this bug?

**Comment by thelostone-mc** [comment]
Nah this was fixed
