### ISSUE TITLE
Pair with Emma on ad-hoc / UI bug cleanup

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10009]
**User Story:**
As a Gitcoin user
I want to see consistent button behavior
So that I intuitively know how to use the app

**Acceptance Criteria**
2-hr pair with Emma on cleaning up buggy UI components

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
Finish #10007 before picking up this task

**Comment by EmHsiehGitcoin** [comment]
I think we can close this ticket at the point. most issues had been move into individual tickets
