### ISSUE TITLE
Migrate current categories into tags

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10018]
**Background**
In preparation to have a new matching pools filter the internal team will be removing the categories filter. There will be a migration of 1-2 categories that currently are not represented as tags. We will add these categories to our existing tag list and deprecate our categories.

In this case, from before, matching pools = categories from a functional standpoint (coincidentally from previous rounds). We will remove "categories" from the filtering options in the grants explorer, but that is not the scope of this ticket, just the context provided.

To ensure users can still surface grants they care about regardless of match pool eligibility, we will ensure tags are available for everything that was previously offered in categories (since there was already a lot of redundancy here, there's only one additional tag to add). 

Moving to tags = keywords grant owners can select to aid in discoverability of their project.

**Acceptance Criteria**
GIVEN we have migrated the grant tags
WHEN I look at our tags
THEN they should contain the categories we previously had.

[Jira link](https://gitcoin.atlassian.net/browse/GITC-581?atlOrigin=eyJpIjoiMzZiMTU0OTAxNjM1NDM3MGI4ZjU2NzY2NDYzMzJiMjIiLCJwIjoiaiJ9)

**Comment by thelostone-mc** [comment]
This can be closed as we decided not to proceed with this task.
No progress was made beyond the query work I had done
