### ISSUE TITLE
Modify get_issue_timeline_events to use requests.links

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1001]
Github Timeline API responds to paged requests with an additional `Link` header specifying `rel="next"` if pages follow.  Python Requests automatically grabs this header data for you in `response.links`.  More information at:  http://docs.python-requests.org/en/master/user/advanced/#link-headers

You can access this via: `response.links['next']` and the url with all required params in `response.links['next']['url']`.

We're currently manually paging through timeline events via:

```python
    should_continue_loop = True
    all_actions = []
    page = 1
    while should_continue_loop:
        actions = get_issue_timeline_events(owner, repo, issue_num, page)
        should_continue_loop = len(actions) == 100
        all_actions = all_actions + actions
        page += 1
```
Which is calling the request and appending the results of the method until no pages are left.

The result should be a list of dictionary entries (the same as those returned from the method currently) while preserving order.

Related methods:

- `github/utils.py@get_issue_timeline_events ` - https://github.com/gitcoinco/web/blob/master/app/github/utils.py#L329-L353
- `github/utils.py@get_interested_actions` - https://github.com/gitcoinco/web/blob/master/app/github/utils.py#L365-L372

**Comment by kuhnchris** [comment]
@thelostone-mc could you check this one if it is still relevant / kill it if it is not relevant anymore? Thanks!
