### ISSUE TITLE
[spike] Investigate app support for generalized ERC20 payouts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10012]
**Background**
We want to enable grants payouts in any ERC20 token, so that we can allow matching pool sponsors to fund grants in their native tokens and expand our ability to support side rounds. 

This spike is aimed at understanding what needs to be done to our app to support this. It is separate from the work to generalize payout contract support (#10011).

Before taking this task , it helps to review [how payouts are triggered](https://www.notion.so/Grants-Payout-non-custodial-payout-b0b3242b9db24072b5e251f1808866bd).

**The work**
Timeboxed to 2 days:

Ensure that we can generate payouts in non-DAI ERC20 token and generate chunks which can be uploaded into the contract.  Right now all our entries in match payout have been in DAI (stablecoin), but doing a payout in a token like UNI would require us to convert the DAI to UNI token.

There are multiple ways we can do this. Easiest would be to see if while creating a round if we can   
- create a round with a token  
- capture the DAI amount  
- when the match payout table in generated in step 5 finalize ([check doc](https://www.notion.so/Grants-Payout-non-custodial-payout-b0b3242b9db24072b5e251f1808866bd)) to ensure the token amount is populated instead of the DAI amount.

**Comment by schultztimothy** [comment]
My notes were getting a little verbose so I created a notion page: https://www.notion.so/gitcoin/Matching-Payout-4a8cdf7c968b491abb80f6ac4a87f4fc

**Comment by nfrgosselin** [comment]
Thanks for capturing this @schultztimothy! I grabbed some time for you, Aditya, and I to discuss — moving this to done.
