### ISSUE TITLE
Cross chain sponsors don't want to see "ETH spent" on their org/tribe page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10020]
**Context**
I brought this up a while back when Celo complained about it, now Tezos has said the same thing. Cross chain sponsors don’t want to see “Eth spent” on their org/tribe page.

I’m unsure how the conversions are done, are the token or USD equivalent converted to ETH at time of payout, and then summed up and reflected on the orgs pages? We could convert it to Celo and XTZ and other native tokens for those orgs, but if it’s easier to use USD value for all orgs even that would be better, especially since ETH changes so much in price. Would need to collect all previous data on payouts or convert ETH to respective native token or USD first time around though at a certain timestamp.

**Solution**
Converting ETH spent to USD spent fixes this issue for the entire swath of cross chain sponsors. No design is necessary

**Acceptance Criteria**
Preferably changed to display spent amount in USD value

[Jira link](https://gitcoin.atlassian.net/browse/GITC-248?atlOrigin=eyJpIjoiYjBhYjM5MTRmZjE4NGQ3NWJlNzE2ZjAxYzg5ZWUyOWMiLCJwIjoiaiJ9)

**Screenshot**
![image](https://user-images.githubusercontent.com/15041635/151012870-b68fc682-667a-4935-aae1-e0f7cb45803e.png)

**Comment by thelostone-mc** [comment]
This is moved back to in progress as tests need be added (feedback from PR review)

**Comment by GTChase** [comment]
> This is moved back to in progress as tests need be added (feedback from PR review) I've also asked @GTChase to see and help evaluate priority

Coming back to this, i think if the fix is implemented for this and all that is left is Unit tests then lets take some time to get it across the finish line. Assuming unit test wont take more then a few hours? Correct me if im wrong there @thelostone-mc @chibie

**Comment by EmHsiehGitcoin** [comment]
I think this is already live so I'm moving it to Done
