### ISSUE TITLE
how do we want to handle issues that are severly underfunded?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1002]
https://gitcoin.co/issue/InfluenceIO/frontend/1/313

this is like $400-$500 worth of scope but is only funded to $50

i wonder if there was some sort of way to tactfully tell the submitter that if it would help

some sort of ‘needs more funding’ button

**Comment by owocki** [comment]
you know whats crazy? theres 2 devs who have started work already https://gitcoin.co/issue/InfluenceIO/frontend/1/313

**Comment by mbeacom** [comment]
Hopefully this doesn't become a trend.  Maybe we should explore being more suggestive with bounty funders as discussed in slack.  The last thing we want is for underfunded bounties to become the norm and ultimately the standard like many freelancing sites.

**Comment by owocki** [comment]
we recently merged a PR that anchors prices to hourly rates in the funding flow.. hopefully that helps normalize the hourly rates (can track this using the dataviz work I did)

**Comment by mkosowsk** [comment]
I like using a notification email per @eswarasai 👍🏻

**Comment by PixelantDesign** [comment]
I think notification email is a lightweight approach as well. Need to think through the parameters.

How would we know this?
Should it be based on # of people working on a task per bounty value? Maybe we look at the recommendes hourly and make sure it doesnt fall below a certain amount/ hr. But we might need to know how many hrs a funder thinks this will take. Just spit balling.

Also if the system realizes this, what do we do about it? Just notify and warn? Do we still allow the funder to list?

**Comment by mkosowsk** [comment]
@PixelantDesign I was thinking of basing it just on whether or not work has been started on an issue or not after a given timeframe of 3 days, which is a bit more reactive as opposed to proactive 🤔 Benefits of this approach are that it would be relatively easy to implement and would provide some feedback but downsides are that it wouldn't provide great guidelines for a Funder when first listing

**Comment by PixelantDesign** [comment]
@mkosowsk do you mean whether the contributor has posted any updates on the project since clicking 'start work'?

**Comment by mkosowsk** [comment]
I remember reading the stat that average issue was picked up within 6 hours, but that may be incorrect... @owocki did that stat fall out of the data viz stuff you've been up to? 🤔

**Comment by owocki** [comment]
yerp.

maybe we have a prominent 'give feedback' button on open issues which can accumulate feedback on the issue spec.  

perhaps the button opens up a modal, and a user can  enter freeform text and maybe also in a radio button select "needs better spec", or "underfunded" or "other"

after 3 days, if no one has claimed it, we deliver that feedback to the bounty hunter via email.

**Comment by dolebas** [comment]
Not sure if my 0.01 eth bounty triggered this thread but to my surprise that micro funded issue got picked up really quick and have a really good outcome already.

Maybe a low entry level puts less pressure on starting/stoping work, and provides a relaxed opportunity for new developers on the platform to give it a shot? If the progression is healthy funds can be added incrementally and tips can be used for milestones?

Love the discussions on this platform btw, very constructive!

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1002/626).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by kuhnchris** [comment]
This is superseeded by the "low-ball-preventation pr".
