### ISSUE TITLE
Enable one click to grants home from /fund

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10028]
[Jira link](https://gitcoin.atlassian.net/browse/GITC-722?atlOrigin=eyJpIjoiMjhkYTE2ZGM0YjI1NGRlYmIxOWY1MGRlYzBkZjNhM2QiLCJwIjoiaiJ9)

**Comment by nfrgosselin** [comment]
LGTM!

**Comment by EmHsiehGitcoin** [comment]
👀  👍  🙆  ✔
