### ISSUE TITLE
Cypress running locally

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10027]
**Description**
To help us adopt TDD work flow, we should all be able to run tests on our local machines.

**Acceptance Criteria**
Given I am a developer
And I have installed the gitcoin repo
When I run the make cypress-local command
Then Cypress tests should execute

[Jira link](https://gitcoin.atlassian.net/browse/GITC-688?atlOrigin=eyJpIjoiODNjODMwNGE3MmMxNDIwOGE0M2VlNGRmZWI5YWU1MTQiLCJwIjoiaiJ9)

**Comment by nutrina** [comment]
@ksolo the PR I have created with the Metamask stub, should already contain this. It is based on your branch, but I have squashed the commits.
Can you please check all that is required is included there? Then this task might already be covered.

https://github.com/gitcoinco/web/pull/10057

**Comment by ksolo** [comment]
@nutrina I think you have this covered in your PR now. I'll close this one out.
