### ISSUE TITLE
Kill offline SMS verification

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10025]
**Description**
As a user I dont need to see the SMS offline verification so that the requests arent going to a black hole and sit unresolved

**Acceptance Criteria**
GIVEN i am logged in to Gitcoin
WHEN i navigate to the trust bonus page
AND i click on the SMS verification card
THEN i should not see an option for Offline SMS verification

[Jira link](https://gitcoin.atlassian.net/browse/GITC-708?atlOrigin=eyJpIjoiYWUwYzc4OGE1YjlhNDllZmJhMTA4MWIwZjk2NWRhZmMiLCJwIjoiaiJ9)

**Comment by thelostone-mc** [comment]
Closing this out as status is done
