### ISSUE TITLE
Contribution CSV download timing out

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10021]
At least one of our users (Richard Moore from ethers.js) is having issues downloading their contributions as a CSV through the UI. According to Richard, the download seems to be timing out on both desktop and mobile.

Richard's grant: https://gitcoin.co/grants/13/ethersjs-complete-simple-and-tiny

Steps to reproduce:
1. Impersonate @ricmoo 
2. Go to My Account → Settings
3. Select Account tab
4. Scroll down to Account Financials
5. Click ‘Export’ in Export Earnings field

**Acceptance criteria**
GIVEN I am a Gitcoin grant owner with a contribution history
WHEN I click 'Export' on the Export Earnings section in Account Financials
THEN The CSV of contribution download doesn't time out
AND I see a modal informing me that the download is being prepared and I will receive it in my email

GIVEN I am a Gitcoin grant owner with a contribution history
WHEN I click 'Export' on the Export Earnings section in Account Financials
AND The download fails
THEN I receive an email directing me to contact support, with a link to submit a new support ticket

[Figma link](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=41%3A5126)
[Jira link](https://gitcoin.atlassian.net/browse/GITC-727?atlOrigin=eyJpIjoiMWI3NzJhYzQxMTc0NDYyNDk3MmRlNGEzMWU4ZDhhYjQiLCJwIjoiaiJ9)

**Comment by EmHsiehGitcoin** [comment]
Not sure how to test this. Can we get a screen-recording?

**Comment by nfrgosselin** [comment]
+1 — @thelostone-mc is that something you can help us with?

**Comment by thelostone-mc** [comment]
It should be the steps mentioned as in the ticket


Go to My Account → Settings
Select Account tab
Scroll down to Account Financials
Click ‘Export’ in Export Earnings field

**Comment by thelostone-mc** [comment]
It looks like the the  POST operation is not picking up the body of the request.
https://github.com/gitcoinco/web/blob/master/app/retail/templates/settings/account.html#L186-L187

This would have to be debugged and fixed

**Comment by thelostone-mc** [comment]
Fixed it up via https://github.com/gitcoinco/web/commit/07a15eefe79e82ecbafb13bf3d386a690716c027

**Comment by nfrgosselin** [comment]
LGTM — thanks @thelostone-mc 

@EmHsiehGitcoin this is ready for Done once you've reviewed
