### ISSUE TITLE
Returning from grants page to grants explorer is inconsistently broken

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10023]
**Quick Summary Description**

When Blockchain or Region tags are applied (only), the functionality is fine.

When only the category filter is applied, returning from grants page from grants explorer puts us on the right page but the grant selected is not shown.

When only the tag filter is applied returning from grants page from grants explorer puts us on the right/wrong page (sometimes its n+1), the grant selected is at the top (sometimes), and the scroll jumps down (sometimes).

**Reproduction Steps**

We’ve narrowed the problem down to a sort functionality that is disrupting the order of the grants when a user returns to the explorer.We originally thought that it was only weighted shuffle that would create the problem, but selecting a sort value (e.g newest), scrolling down, and clicking into a grant to access the grant details, and going back to the explorer does not land the user back to the grant they just clicked on within the explorer.

**Notes:**

During Grants Round 11 and Grants Round 12, we had problems with infinite scroll when backing out of a grant, in both the grants explorer and grant collections.

A short-fix was implemented to load additional grants in order to side-step the situation, but long-term, pagination still needs to be improved.

We have previously discussed using quick view in a modal (existing functionality that needs a little revamping) rather than fully navigating to the grants detail page as a solution to our pagination problem when navigating back and forth.

The short-fix mentioned above was not effective, so another short-fix was implemented to open the grants page in a new browser tab. Long-term, pagination still needs to be improved.

**(Old) Acceptance Criteria**
GIVEN I am on the grants explorer and have clicked into a grant details page
WHEN I hit "back to grants explorer" OR hit back on the browser
THEN I should see the grant I had previously clicked on in the explorer.

GIVEN I am on the grants explorer, sorted by a sort value that is not weighted shuffle and clicked into a grant details page
WHEN I hit "back to grants explorer" OR hit back on the browser
THEN I should see the grant I had previously clicked on in the explorer.

**Acceptance Criteria**

GIVEN I am on the grants explorer
WHEN I click into a grant details page
THEN I should see the grant details open in a new browser tab
[Jira link](https://gitcoin.atlassian.net/browse/GITC-501?atlOrigin=eyJpIjoiODcxNTQ5ZDBiM2MzNDBjMzlmNmI0M2I5OGRjMzAwZTMiLCJwIjoiaiJ9)

**Comment by nfrgosselin** [comment]
@Jer-Sch this doesn't seem to be working for me. I've tried both acceptance criteria on staging but when I hit "back to grants explorer" it brings me back to the top of the explorer.

**Comment by EmHsiehGitcoin** [comment]
It does open up the detail page in a new browser tab now. LGTM

**Comment by nfrgosselin** [comment]
LGTM too
