### ISSUE TITLE
Restrict merge to green builds

### ISSUE THREAD

**Issue by schultztimothy** [gitcoinco/web#10075]
**User Story:**
As a contributor/code owner
I want to ensure that all CI checks pass before a branch can be merged
So that code is verified before it is merged

**Acceptance Criteria**
GIVEN the CI Build and test check is successful
WHEN I create a PR
THEN the PR can be merged once approved

GIVEN the CI Build and test check is unsuccessful 
WHEN I create a PR
THEN the PR can not be merged once approved

**Notes/Assumptions:**
Whoever picks this ticket up will need to have enough permissions to update these settings

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by nfrgosselin** [comment]
Hey @thelostone-mc / @kevinrolsen — do either of you have the permissions to make this change?

**Comment by thelostone-mc** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/5358146/152772165-2162a715-19db-41d4-88fc-336ea94a392e.png">


<img width="776" alt="image" src="https://user-images.githubusercontent.com/5358146/152772264-7780a14c-893a-4526-903b-37da85fe3c8c.png">

This has been set up !
