### ISSUE TITLE
Hackathon and Bounty Alumni Sheet

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10073]
**User Story:**
As Leon
I want an autoamted list of hackathon and bounty winners
So that i can easily manage the builder band with minimal manual effort

**Acceptance Criteria**
GIVEN I am in metabase as an internal stakeholder
WHEN I view a list of queries
THEN I should have a query of any builder who has been paid out for a bounty on Gitcoin
AND the following data should be available:
- Gitcoin Handle
- Associated Email Addresss
- Time of first bounty/hackathon payment that profile received on Gitcoin

**Product & Design Links:**

**Tech Details:**

**Open Questions:**
- Do we need time and date?
Yes, we do

-What time frame should this query consider?
Weekly.. First time winners over the last week..

**Notes/Assumptions:**
- The query will query the postgres DB

**Comment by nutrina** [comment]
Have build the query: https://metabase.gitcoin.co/question/1157

**Comment by gdixon** [comment]
Query looks awesome! Great work @nutrina! 🚀
