### ISSUE TITLE
Investigate Merkle storage for payouts contracts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10083]
For each of the last two rounds, we've spent ~$8k in transaction fees deploying our payouts contracts. A large part of that is due to simple account-amount mapping that we store on chain. We want to explore a Merkle tree storage technique for our contract to see if we can reduce those fees. This spike is to understand the requirements for that work.

**Acceptance Criteria**
Time boxed to two days:
- Explore the technical implications of introducing Merkle tree storage to our contracts and app
- Sketch a rough technical design of the work
- Pair with @nfrgosselin to evaluate the path and (if possible) turn into stories

**Comment by thelostone-mc** [comment]
Will be drafting possible integrations over at: 
https://miro.com/welcomeonboard/Nm9ZT2JWQ0doMkFRTG45Q0VIUVhuR0J0NnRzZTRIS0RUZzc1U2pNYnFSY2hNZ0hyUDlKNVNWS3RNNU5IREV5b3wzMDc0NDU3MzYxNjgwODQwMTE1?invite_link_id=879253024891
