### ISSUE TITLE
as a project administrator, i want to distribute tokens to people who has done work for my project in the past, so i can balance intrinsic motiviation and extrinsic motivations

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1009]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a project administrator, i want to distribute tokens to people who has done work for my project in the past, so i can balance intrinsic motiviation and extrinsic motivations

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so that when a project adopts gitcoin, they dont have to worry about jipping contributors in the past who might think 'wtf, i didnt get tokens)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  feature

### Current Behavior
[comment]: # (Describe what actually happened.)
none

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
script that could analyze a git source repo and provide a distribution of tokens based upon merit, which can then be tweaked by a human operator

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
TODO

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
possible integration path with @dandelionmane / sourcecred here

**Comment by decentralion** [comment]
Yep, that's a big part of the vision for [SourceCred](https://github.com/sourcecred/sourcecred) :+1:

**Comment by owocki** [comment]
@decentralion can i get on your alpha list?  purdy please!

**Comment by mkosowsk** [comment]
@decentralion ditto! My gmail is mitchkosowski 🤠👍🏻great chatting with you yesterday!

**Comment by decentralion** [comment]
I created an official [alpha interest post at the SourceCred spectrum](https://spectrum.chat/?t=cd7a9672-c7aa-49b6-afd5-9d8f34ce5e2c). Please post there, and we'll keep you posted. :slightly_smiling_face:
