### ISSUE TITLE
Transaction Underpriced when you try to receive a tip

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#101]
When someone is going through the tip receive flow, they are not able to submit their receive transaction because the ethereum mainnet gas profile has changed so much.

They get the following error in theri console: 

```
tracker.js:13 Error: transaction underpriced
    at Object.InvalidResponse (inpage.js:14335)
    at inpage.js:14335
    at inpage.js:9909
    at completeRequest (inpage.js:9960)
    at inpage.js:683
    at replenish (inpage.js:1203)
    at iterateeCallback (inpage.js:1193)
    at inpage.js:1168
    at inpage.js:9837
    at inpage.js:9933
```

This is caused by the network conditions of the ethereum mainnet (and the popularity of cryptokitties).

# Proposed Fix

* Send some extra ETH to each ephemeral address associated with Tips
* Allow users to send tx's with higher gas prices through the receive flow

**Comment by owocki** [comment]
im about to head to dinner so i wonder be able to tackle etonight… but if you are affected rest assured your funds are safe and ill get the tip to you.

**Comment by owocki** [comment]
letting ppl know that this is a known issue on the receive flow rn

<img width="723" alt="screen shot 2017-12-08 at 5 12 17 pm" src="https://user-images.githubusercontent.com/513929/33790151-03e9c40c-dc3b-11e7-815d-bff6eb9bbc24.png">

**Comment by owocki** [comment]
kudos @ethikz for the report

**Comment by owocki** [comment]
i am working on a fix now @ethikz @thelostone-mc @tra38

**Comment by owocki** [comment]
9f277343f6027de90937589f2c87eabe5593eded should be the root cause fix on a go-forward basis.  let me go through and make sure each of you can redeem your tips @ethikz @thelostone-mc @tra38

**Comment by owocki** [comment]
@ethikz @thelostone-mc @tra38

ok yall,

i've put in a fix.  what this fix does is selects a dynamic gas price, when the tip is created.  and puts enough gas in the contract such that the receipient can avoid a `transaction underpriced` issue.  

here's how to redeem your tips:

1. go to the link that is in your tip email that you received
2. append `&gasPrice=10` to the end of the link and go to that URL
3. *hard refresh* the page to make sure you have the new javascript.
4. continue receiving your tip as per normal.

any questions, hit me back on slack or on this GH issue.  ill keep the GH issue open until you've confirmed your tips have been received.

**Comment by ernaneluis** [comment]
@owocki I believe still not working properly. 
I've followed all the steps above even using the hard reload still got an error but this time different from the one you post it. 

<img width="442" alt="screen shot 2017-12-18 at 18 59 03" src="https://user-images.githubusercontent.com/1398769/34120353-9f338988-e425-11e7-8721-6106e986ca1c.png">

**Comment by ernaneluis** [comment]
I fixed by not using `gasPrice=10` but `gasPrice=2`. I made several attempts on the `gasPrice` until finding the number that works.
