### ISSUE TITLE
Finalize documentation for Merkle payouts contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10109]
**User Story:**
As a Gitcoin engineer
I want to understand how the Merkle contract structure works
So that I can effectively work with it in the future

**Acceptance Criteria**
Appropriate documentation for the Merkle contract structure is complete, including:
- code documentation
- playbook for deploying
- reference guide for users (available functions, etc)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
The repo is set up over at : https://github.com/gitcoinco/merkle_payouts
