### ISSUE TITLE
Go back to explore grants page after creating a grant

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10102]
**Description**
This error happens when a user clicks on the back text link after they just created a new grant and is on the grant detail page. The back text link should take the user back to explore grants page but it takes the user back to their half-filled grant creation form right now. (dropdown selections are gone but text inputs are still there)

**Reproduction** 
1. Create a grant 
2. Fill the form + Click **Create Grant** button
3. You are on your new grant detail page now. Click **Back to Grants** text link

**Environment** 
None

**Acceptance Criteria**
GIVEN I am at the grant detail page after grant creation 
WHEN I click back to grants link 
THEN it takes me to gitcoin.co/grants/explorer

**Comment by EmHsiehGitcoin** [comment]
[🙆🏻‍♀️](https://emojipedia.org/woman-gesturing-ok-light-skin-tone/)[🙆🏻‍♀️](https://emojipedia.org/woman-gesturing-ok-light-skin-tone/)[🙆🏻‍♀️](https://emojipedia.org/woman-gesturing-ok-light-skin-tone/)

**Comment by nfrgosselin** [comment]
👍
