### ISSUE TITLE
Investigate feeding Merkle claims object into database

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10114]
**User Story:**
As a Gitcoin engineer
I want to investigate how we can feed a Merkle claims object back into our database
So that we can generate the correct claims keys for our users

**Acceptance Criteria**
Timeboxed to two days:
- Investigate what it would take to feed a claims object back into our GrantCLR match entry
- Pair with Nate/Aditya to generate follow-on stories

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
This has been researched over at https://github.com/gitcoinco/web/pull/10149.
It looks like a couple of things would need to be done 

- Add merkle_claim field to CLRMatch
- Introduce new endpoint in payout_noncustodial to allow udpate the CLRmatch entry with the claim entry 
- Introduct a new task in merkle contract to upload output to the th e newly created endpoint


Additional bonus work:
- clean up un-used modal + retire payout mgmt command (taken care of in https://github.com/gitcoinco/web/pull/10149/commits/1bb04ef6def33236f01e934cd158fac08978a06d)
