### ISSUE TITLE
Get 100% test coverage on Merkle payout contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10110]
**User Story:**
As a Gitcoin engineer
I want to have Solidity unit tests for the Merkle payout contract
So that I know it will run correctly

**Acceptance Criteria**
- Generate a testing report that outputs what percentage of Merkle payout contract code is covered by tests
- Get 100% of the Merkle payout contract covered by tests

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
This has been built over at https://github.com/pulls?q=is%3Apr+author%3Athelostone-mc+archived%3Afalse+is%3Aclosed

To generate the coverage report you can run `yarn coverage`

<img width="836" alt="image" src="https://user-images.githubusercontent.com/5358146/154043985-3a4cb744-ce52-49a9-8bac-a8eb10eab233.png">

html based reports are algo generated in `./coverage/` folder and that gives a UI view of which pieces of code don't have coverage
