### ISSUE TITLE
Fetch CLRmatch data for Merkle payout contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10113]
**User Story:**
As a Gitcoin engineer
I want to fetch properly formatted data from the CLRMatch table
So that I can deploy the Merkle payout contract

**Acceptance Criteria**
GIVEN that I am accessing the CLRmatch table in the Gitcoin database
WHEN I call a function
THEN I receive data that is properly formatted for the Merkle contract

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
#10109 needs to be finished before picking this up

**Comment by thelostone-mc** [comment]
This involves updating the `set_payouts` command in payout_non_custodial  to generate output in the format it can be fed into the merkle contract 

https://github.com/thelostone-mc/merkle_payouts/blob/main/scripts/input.ts
