### ISSUE TITLE
Explorer multiselect "Any" option doesn't behave as expected

### ISSUE THREAD

**Issue by joshmorel** [gitcoinco/web#1011]
### User Story

As an explorer, I want a multiselect "Any" control that selects all.

### Why Is this Needed?

This UI is confusing if intended, if not intended it's a bug
### Description

Bug

### Current Behavior

When clicking Any on the gitcoin explorer multiselect options, the only thing that happens is the page refresh.

### Expected Behavior

"Any" will be selected, page will refresh with all in that search category.

### Reproduction

1. Navigate to [gitcoin explorer(https://gitcoin.co/explorer) in Chrome or Firefox
2. Expand "NETWORK" option menu
3. Click "Any" button

### Solution

* [ ] Create design for Any button (*not* additional checkbox - more like a [button](https://docs.webix.com/desktop__multicombo.html))
* [ ] Update JS code so that clicking that button will select all options
* [ ] Add ability to clear select "all" with respect to above 2
* [ ] Test
* [ ] Gain acceptance

### Definition of Done
Multiselects in Explorer have All/Clear button which responds in an intuitive fashion

### Additional Information
I'm willing to take this on.

**Comment by thelostone-mc** [comment]
@joshmobley You mean you'd like a button where on click all the filters are removed? 

We've got a reset  -> which selects `Any` aka removes all filters 

<img width="244" alt="screen shot 2018-04-29 at 2 29 53 pm" src="https://user-images.githubusercontent.com/5358146/39404970-fd387330-4bb9-11e8-9848-911aae8ba22a.png">

**Comment by PixelantDesign** [comment]
Any should show all. Is this a bug @mbeacom?

**Comment by joshmorel** [comment]
Well, really a new design isn't needed, to be honest. The multiselect options just need to work like "PROJECT STATUS"

For example in "EXPERIENCE LEVEL" clicking "Any" does nothing except refresh the search result with the exact same filter as before.

**Comment by joshmorel** [comment]
![peek 2018-04-29 16-35](https://user-images.githubusercontent.com/10546720/39410776-6c12ef7c-4bcb-11e8-82c8-8f3f4f05a6dc.gif)
