### ISSUE TITLE
Create migration of GrantCLR with new fields

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10118]
**User Story:**
As a Gitcoin engineer
I want to add new fields to the GrantPayout and CLRMatch tables 
So that I can correctly capture payout data going forward

**Acceptance Criteria**
Create migration for the GrantPayout table with the following fields:
- Conversion Rate → IntegerField
- Conversion Date → DateTimeField

Create migration for CLRMatch table with the following fields:
- token(symbol or address) → fk to [Token table](https://gitcoin.co/_administrationeconomy/token/) - Useful to clarify the token amount field
- USD amount -> number - nullable
- Modify CLRmatch `Amount` field to include helper text under the input that reads `Token Amount`(Similar to how the grant field says `The associated Grant.`)
<img width="568" alt="Screen Shot 2022-02-14 at 11 30 01 AM" src="https://user-images.githubusercontent.com/6887938/153924546-cfcd6a7f-52fa-435b-85ad-e30599bacbaf.png">

**Product & Design Links:**
[Miro board](https://miro.com/app/board/uXjVOOp6Dzs=/?invite_link_id=10385067241)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by schultztimothy** [comment]
Sorry for the confusion here @gravityblast I originally came up with the requirements for this :) 

I updated the description just let me know if anything doesn't make sense

**Comment by schultztimothy** [comment]
Good call with the comments @gravityblast!

I originally came up with these requirements apologies for the confusion 😄. I updated the description. Just let me know if you have any questions.

We ended up going with a free form field for the conversion rate and conversion date so it wouldn't be linked to that gigantic conversion table and to add some more flexibility

**Comment by gravityblast** [comment]
thank you @schultztimothy ! I created this PR with these changes https://github.com/gitcoinco/web/pull/10158
