### ISSUE TITLE
Test Merkle payout contract on Rinkeby

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10112]
**User Story:**
As a Gitcoin engineer
I want to test the Merkle payout contract on the Rinkeby network
So that I can verify that all the functions work as expected

**Acceptance Criteria**
GIVEN I am on the Rinkeby test network
WHEN I deploy the Merkle payout contract
THEN I don't trigger any errors

GIVEN I am accessing the Merkle payout contract on Rinkeby
WHEN I call all of the functions individually
THEN I don't trigger any errors

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by gravityblast** [comment]
I successfully deployed the `MerklePayout` contract to rinkeby and claimed 1 test token.

TestERC20 deployed at https://rinkeby.etherscan.io/address/0xf7511cb1754bb9dd14534ffad7f6c68458a3ad6e
TX: https://rinkeby.etherscan.io/tx/0xea13175b24beccbab208452294dd9afc1b3a982684e72cdea9c367ee1dbb9c77

MerklePayout deployed at https://rinkeby.etherscan.io/address/0x7f2268d6839155c0ed21ffb3bb55abc1679e9d5e
TX: https://rinkeby.etherscan.io/tx/0x6159f82d76c7451e589d87cd03dfe8679a8f6ff4c75c7c14ad7943dfc5c60444

1 Test Token successfully claimed https://rinkeby.etherscan.io/tx/0xd8e2f9a207b58dd456634b8c503a19ef16a282c5aa04c272892a47d584099978

/cc @nfrgosselin @thelostone-mc
