### ISSUE TITLE
cannot send a tip on https://gitcoin.co/tip

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#10122]
**Steps To Reproduce**
1. open gitcoin.co/tip and connect your wallet
2. select gitcoin.co/l-kh and 0.35 ETH
3. click send
4. 

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.
metamask window is not opened.  system just hagns

**Expected behavior**
A clear and concise description of what you expected the system to do.
metamask window is not opened, no opportunity to tip user

**Screenshots**
<img width="1706" alt="Screen Shot 2022-02-08 at 12 30 50 PM" src="https://user-images.githubusercontent.com/513929/153061556-d20219fc-e477-4e5f-b195-f12927c90504.png">
<img width="1714" alt="Screen Shot 2022-02-08 at 12 30 47 PM" src="https://user-images.githubusercontent.com/513929/153061568-de1211fd-f31f-4e83-8f75-c987ce8010d9.png">
<img width="1709" alt="Screen Shot 2022-02-08 at 12 30 33 PM" src="https://user-images.githubusercontent.com/513929/153061574-bfc9565d-0516-47ff-9aa3-d7f630c9c3df.png">

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by owocki** [comment]
i'm using brave/metamask

**Comment by lthrift** [comment]
Closing per discord exchange
