### ISSUE TITLE
Remove Collection option from contribution thank you modal

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10125]
**User Story:**
As a Gitcoin donor
I want to remove the "Save this Collection" section from the "thank you for contributing" modal
So that I'm not driven to a new page while I'm completing multiple transactions

**Acceptance Criteria**
GIVEN that I'm on gitcoin.co/grants/cart
WHEN I'm looking at the "Thank you for contributing" modal (see attached screenshot)
THEN I don't see the "Save this Collection" section

**Product & Design Links:**
![image](https://user-images.githubusercontent.com/15041635/153092954-7c6f508c-3d6c-43dd-8536-0c14eb8e2cc9.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by sudhay23** [comment]
Hello @nfrgosselin . Can I try fixing this issue?

**Comment by nfrgosselin** [comment]
@chibie this is updated now
