### ISSUE TITLE
Update finalize script for ERC20 payouts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10120]
**User Story:**
As a Gitcoin engineer
I want to run a script when payouts are finalized
So that I can properly capture the ERC20 payout details

**Acceptance Criteria**
GIVEN that payouts are finalized
WHEN I run the [finalize script](https://gitcoin.notion.site/b0b3242b9db24072b5e251f1808866bd#7ffe8558d0be47f0b45b81e64b141983) - aka "payout non-custodial script"
THEN the **Conversation Rate** and **Conversion Rate Date** fields in the **GrantCLR table** are updated with the correct values

GIVEN that payouts are finalized
WHEN I run the [finalize script](https://gitcoin.notion.site/b0b3242b9db24072b5e251f1808866bd#7ffe8558d0be47f0b45b81e64b141983)
THEN the **USD Amount** and **Token Amount** fields in the **CLRMatch table** are updated with the correct values

**Product & Design Links:**
[Miro board](https://miro.com/app/board/uXjVOOp6Dzs=/?invite_link_id=10385067241)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
Requires #10119 to be finished first

**Comment by thelostone-mc** [comment]
Ensure this is built on top of https://github.com/gitcoinco/web/pull/10149 as that does a good chunk of cleanup
