### ISSUE TITLE
Update grant creation email

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10136]
**User Story:**
As a grant owner
I want to know where I can track my grant's approval status
So that I know when I can take action

**Acceptance Criteria**
Update the body copy of the "[new grant](https://gitcoin.co/_administration/email/new_grant)" email to say:

"You've created a new grant!

We are reviewing grants as we get closer to each grant round. You can check the status of your grant on [this Notion board](https://gitcoin.notion.site/fc5155ddb7804560a42387043bd805c1?v=937073ff11d149d29e08aa5901befc77). Please be patient while we review your grant.

In the mean time, get ready to buidl and push forward open source!"

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- the full list of email updates is available [here](https://docs.google.com/spreadsheets/d/1d4RToJQ9712rwI32ehKBLDT5cNn926tGT8M7QscFKNk/edit#gid=0)

**Comment by EmHsiehGitcoin** [comment]
@nfrgosselin @thelostone-mc How do I test this?

**Comment by EmHsiehGitcoin** [comment]
@nfrgosselin @gravityblast I did get the email w/ the updated message. 
[🔍](https://emojipedia.org/magnifying-glass-tilted-left/) All images are broken
[🔍](https://emojipedia.org/magnifying-glass-tilted-left/) typo: buidl 
[🔍](https://emojipedia.org/magnifying-glass-tilted-left/) It was unexpected getting an email from Gitcoin.co but w/ Octavio's profile picture. Maybe we can trigger the email w/ a different email that has Gitcoin logo as the profile pic?
![Screen Shot 2022-02-28 at 5 55 34 PM](https://user-images.githubusercontent.com/96255151/156072117-ce78be34-2b97-4cf8-8511-b0bbedcfee92.png)

**Comment by nfrgosselin** [comment]
I agree with Emma on a few of these:
- the images are broken for me
- it's weird to get the email from Octavio — I like the idea of sending from a generic Gitcoin address
- +1 to the comments on the "learn how..." button

The "buidl" actually isn't a typo, but this came up in a separate discussion and I'd like to hyperlink "buidl" to this definition: https://academy.binance.com/en/glossary/buidl

@gravityblast — I realize that these points are all outside the scope of the original acceptance criteria, so LMK if you think these changes are small enough to include as part of this ticket. I'm happy to drop new tickets if you think they need it!

**Comment by thelostone-mc** [comment]
> it's weird to get the email from Octavio — I like the idea of sending from a generic Gitcoin address

This is cause the staging uses his keys! This is not an issue 

> the images are broken for me

 This could be cause it's on staging

**Comment by gdixon** [comment]
> the images are broken for me

I suspect this is because those images are hosted on https://stage.gitcoin.co which is behind basic auth - gmail provides a proxy to those images (for me at least) and will be unable to serve those images without being authenticated. This is working on the email's live preview which @thelostone-mc links to above (https://stage.gitcoin.co/_administration/email/new_grant)

**Comment by gravityblast** [comment]
@nfrgosselin  I added the link to the BUIDL explation in this pr https://github.com/gitcoinco/web/pull/10226 + changed the green button.
@EmHsiehGitcoin I removed the green button styles, is it ok like you can see here in the screenshot?

![00000000000000-grants-email](https://user-images.githubusercontent.com/1059/156360197-3a5a5312-324c-4dab-ac6e-40827036281f.png)

**Comment by nfrgosselin** [comment]
LGTM — thanks @gravityblast!

@EmHsiehGitcoin feel free to move to done once you've had a chance to review
