### ISSUE TITLE
Prefill fields on a Tips page

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#1014]
### User Story

As a Github user, I want to leave a link to tip me on my Github page, so that people can tip me.

### Why Is this Needed?

Because people need tips.

### Current Behavior

Currently, to tip me, people need to fill out all details manually at https://gitcoin.co/tip They can make mistake.

### Expected Behavior

Process links like https://gitcoin.co/tip?user=abitrolly that make at least username prefilled.

Tips page currently mentions Github username.

![image](https://user-images.githubusercontent.com/8781107/39392083-abd27b56-4ab7-11e8-940c-4b65872024ee.png)

Should it be Gitcoin username?

**Comment by abitrolly** [comment]
I'd like also to prefill comment field to filter my project that people can tip for.

Also, nice if prefilled fields could be visible immediately even if hidden in `Advanced >>`

**Comment by abitrolly** [comment]
The goal is to track how much https://github.com/abitrolly/metamask-status generates, and which part it generates to meet a basic need from https://github.com/abitrolly/abitrolly.github.io/issues/4

**Comment by owocki** [comment]
https://gitcoin.co/tip?username=abitrolly will do this for you :) 

also check out the browser extension at http://gitcoin.co/extension !

**Comment by abitrolly** [comment]
> https://gitcoin.co/tip?username=abitrolly will do this for you :)

At first I thought that it doesn't work, because it took about 3 seconds to fill my name after clicking the link to get to https://gitcoin.co/tip/send/2/ page.

I'd like to prefill comments also, like https://gitcoin.co/tip?username=abitrolly&comments_public=for:metamask-status or being able to specify GitHub project and donate to it. But I am not sure how to claim funds in this case.
