### ISSUE TITLE
Create grant preview step

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10154]
**User Story:**
As a grant owner
I want to preview what my grant details will look like
So that I can be sure that my information is correct before I submit my grant for approval

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/new
WHEN I look at the top of the page
THEN I see a four-step progress bar

GIVEN that I am on step 3 of gitcoin.co/grants/new
WHEN I look at the body of the page
THEN I see enabled Back and Next buttons instead of the Edit / Confirm buttons

GIVEN that I am on step 3 of gitcoin.co/grants/new AND have entered in the required fields
WHEN I click on Next
THEN I am brought to step 4 of the grant creation flow

GIVEN that I am on step 3 of gitcoin.co/grants/new
WHEN I click on Back
THEN I am brought to step 2 of the grant creation flow

GIVEN that I am on step 4 of gitcoin.co/grants/new
WHEN I look at the body of the page
THEN I see a preview of my grant's detail page
AND I see the Edit / Confirm buttons

GIVEN that I am on step 4 of gitcoin.co/grants/new
WHEN I click the Confirm button
THEN my grant is submitted for approval
AND I am redirected to my grant's detail page

GIVEN that I am on step 4 of gitcoin.co/grants/new
WHEN I click the Edit button
THEN I am brought back to step 3

**Product & Design Links:**
Figma — [Ticketed: Create a Grant](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/?node-id=163%3A3717) Section 2

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
@nfrgosselin this is deployed on dynamic staging env.
Could you review this and let us know if this is good to ship ?

**Comment by nfrgosselin** [comment]
LGTM
