### ISSUE TITLE
Hide FAQ on gitcoin.co/grants/quickstart

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10155]
**User Story:**
As a Gitcoin admin
I want to delete the FAQs section on gitcoin.co/grants/quickstart
So that users don't see outdated info

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/quickstart
WHEN I look below the Fund a Grant button
THEN I do not see the FAQ section

**Product & Design Links:**
<img width="748" alt="image" src="https://user-images.githubusercontent.com/15041635/153938316-e9cbb907-393d-4429-869f-b156b5e8fbcb.png">

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
This is a temporary fix. Once the revised grant owner's page is ready we will deprecate this page. 

Please delete the FAQ content — we don't need it

**Comment by EmHsiehGitcoin** [comment]
Looks good!
