### ISSUE TITLE
Determining relation between Bounties & Grants

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10156]
**User Story:**
As a PM at Gitcoin
I want to see if there is any relation between contributors who have completed bounties and received a grant
So that I can determine if there is a flywheel effect of our products

**Acceptance Criteria**
GIVEN I have access to Metabase
WHEN I looked at queries in Metabase
THEN I expect to see a query that has the following:
- Profiles with 1+ bounty completed AND 1+ Grant funded
- Count of bounties funded + dollars earned through bounties
- Count of Grants + Dollars earned through Grants
- Nice to have: Parsing of which came first - bounty or grant

**Comment by gdixon** [comment]
This question is available here: https://metabase.gitcoin.co/question/1162
