### ISSUE TITLE
Update grant modal

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10152]
**User Story:**
As a grant owner
I want to know what happens after I submit my grant
So that I know what to expect during the approval process

**Acceptance Criteria**
GIVEN that I am on step 4 of gitcoin.co/grants/new
WHEN I click the Confirm button
THEN my grant is submitted for approval
AND I am redirected to my grant's detail page
AND I am shown the "Congratulations on your grant creation" modal

**Product & Design Links:**
Figma — [Ticketed: Create a Grant](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/?node-id=163%3A3717) Section 3

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
This looks good to me! @EmHsiehGitcoin feel free to kick this to Done once you've reviewed

**Comment by EmHsiehGitcoin** [comment]
@thelostone-mc 
I got two!
🔍 just some small tweaks to make the spacing even all around ([see same section in Figma File](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=163%3A3717))
🔍 link "Grant Round FAQs" to https://support.gitcoin.co/kb/section/3/
![Screen Shot 2022-02-28 at 5 05 05 PM](https://user-images.githubusercontent.com/96255151/156066286-637bb7df-fe60-4360-aa9c-7fa02af2b5a2.png)

**Comment by thelostone-mc** [comment]
![Untitled](https://user-images.githubusercontent.com/5358146/156114684-0e66ef1c-0864-4376-b4e0-b37e24fa8354.gif)

**Comment by nfrgosselin** [comment]
This LGTM — @EmHsiehGitcoin feel free to move this to done if it's good for you

**Comment by EmHsiehGitcoin** [comment]
Amazing!
