### ISSUE TITLE
Update grant status banner

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10153]
**User Story:**
As a grant owner with an inactive grant
I want to see my grant's inactive status alert in a different section than my owner tools
So that I don't think there's an action I can take to change my grant's status

**Acceptance Criteria**
GIVEN that I am on my grant's detail page
WHEN my grant is inactive
THEN I see the new inactive status alert above the title of my grant
AND I don't see the old alert on the right side of the page

**Product & Design Links:**
Figma — [Ticketed: Create a Grant](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/?node-id=163%3A3717) Section 4

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by chibie** [comment]
@nfrgosselin @EmHsiehGitcoin 

i need the following

* url for "Learn more" link
* what is the start date for a grant approval process?

**Comment by EmHsiehGitcoin** [comment]
@chibie the link is TBD at the moment. We'd probably link to either Owner's Guide or the new knowledge base and both are WIP.

**Comment by nfrgosselin** [comment]
LGTM — thanks @chibie!
