### ISSUE TITLE
Need my account trusted.

### ISSUE THREAD

**Issue by willisnutz** [gitcoinco/web#10168]
I need my account trusted somehow? Can someone please help me with this. I can’t receive my Kudos due to account too new?? Please help

**Comment by gdixon** [comment]
Hi there, 

You may visit https://gitcoin.co/profile/trust and complete the listed verification methods, you need to have a 100% trust bonus score to avoid this limitation (on quests).

Please note, your account is only considered too new for the first week of its existence.
