### ISSUE TITLE
Cosmos Integration for Grants

### ISSUE THREAD

**Issue by chibie** [gitcoinco/web#10176]
**User Story:**
As a grant owner
I want to be able to create grants for Cosmos blockchain
So that I can receive contributions to my ATOM address

As a grant donor
I want to be able to checkout grants using Keplr wallet
So that I can contribute to grants on Cosmos blockchain network

**Acceptance Criteria**
GIVEN I am on the grant creation page
WHEN I click on the "Select a blockchain" dropdown
THEN I see Cosmos as an option

GIVEN I am on the grants cart page
WHEN I click on "Cosmos" tab
THEN I see Cosmos grants in my cart

GIVEN I am on the "Cosmos" tab in my cart
WHEN I click on the currency select option of a grant
THEN I can select "ATOM" in the list of tokens

GIVEN I have selected "ATOM" as currency for a grant in Cosmos tab
WHEN I click on "Payout" button
THEN I see the Keplr wallet extension prompt to sign the transaction

GIVEN I have successfully signed the transaction with Keplr wallet extension
WHEN I am redirected to the grants explorer page
THEN I see the "Thank you for contributing" modal

GIVEN I have successfully contributed to grants
WHEN The contribution is still pending on-chain
THEN Then a background task checks the on-chain status of the transaction at intervals

**Product & Design Links:**

**Tech Details:**
Crosschain Integration document: https://docs.google.com/document/d/19wVbwJYGEgkkdeNj-IiTq-PmQ3a5kBOR66Lhf-vS-xQ

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
Hey @chibie — I was able to create a Cosmos grant, add it to my chart, and see the Cosmos checkout tab, but I wasn't able to finish testing the flow.

Looks like the cart won't let me select a token for the Cosmos chain:
![image](https://user-images.githubusercontent.com/15041635/166492280-dd8888b0-3397-4ee4-af76-0d7346b89a51.png)

Can you help me debug?
