### ISSUE TITLE
Create script to ingest Merkle Claim objects

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#10193]
Depends on https://github.com/gitcoinco/web/issues/10115 being completed 

**User Story:**
As a Gitcoin engineer who has deployed the merkle contract  
I want to be able to have a task to in the merkle_payout contract repo
So that I can ingest the claims object into the endpoint 

**Acceptance Criteria**

GIVEN the merkle contract is deployed 
WHEN the Claim objects are generated (after contract deploy)
THEN I can run a script in the merkle_contract repo to invoke the ingest_merkle_claim_to_clr_match endpoint to feed in merkle object 

- Also create tests for this work

**Tech Details**
Depends on https://github.com/gitcoinco/web/issues/10115 being complete

Once the new API to ingest claims object is created.
We would have to introduce a script in https://github.com/gitcoinco/merkle_payouts to allow the deployer to ingest the claims into the claims object.

We would additionally also need documentation to be added within the script file on how to invoke the endpoint 
**Method**: POST
**URL**: `grants/v1/api/ingest_merkle_claim_to_clr_match`
**HEADERS**: `token`:`MERKLE_CLAIM_UPLOAD`
**BODY**: the output generated after merkle deploy which is stored in output.json

**Comment by gravityblast** [comment]
Closed with https://github.com/gitcoinco/merkle_payouts/pull/3
