### ISSUE TITLE
Allow funders to disable Gitcoin idle warnings for assigned tasks

### ISSUE THREAD

**Issue by ghost** [gitcoinco/web#1021]
Long running tasks in which a team is collaborating and/or are somewhat open ended will drop the assigned task user off after a while. Funders should be able to tell Gitcoin Bot to not idle-drop the task users for these collaborative projects.

See https://github.com/ethgasstation/ethgasstation-api/issues/1#issuecomment-385300991 for more information per @owocki.

**Comment by owocki** [comment]
@10a7 do you think 'disable' is the right thing to do.. or maybe 'snooze' for x days, weeks, months ?

**Comment by owocki** [comment]
my hope was that by giving the funder control over how aggressive gitcoin bot is... we could enable the best of both worlds (gitcoin bot still removes people who dont respond, but becomes less agressive if the funder wants them to be)

**Comment by owocki** [comment]
>  Is there already a provision for Funders to remove the bounty hunter from the bounty? 

yes this is!  but i dont know how many funders are actually using it.  @vs77bb had a good idea to send the funders an email and let them know they could use it

**Comment by eswarasai** [comment]
@owocki -- Yeah. I'd agree on how aggressive the Gitcoin Bot is in making sure the bounty hunter is following through. I think a simple solution would be to allow the Funder to set the time period of non-responsive for each param like warning 1, warning 2 and auto-removal and also limit the number of days to be in between 3 - 30 days based on each param. We can have the default value as it is, this way. Let me know your thoughts on this. Thanks.

**Comment by owocki** [comment]
this outta do the trick https://github.com/gitcoinco/web/pull/1059

**Comment by thelostone-mc** [comment]
> yes this is! but i dont know how many funders are actually using it. @vs77bb had a good idea to send the funders an email and let them know they could use it

@PixelantDesign @Saptak7 should we maybe include this in our onboarding flow ?

**Comment by PixelantDesign** [comment]
This might belong in the Google doc guide - it's a little more edge case. We should probably adjust the gitcoin bot to me less aggressive, vs, creating fixes to solve for the agressiveness.

**Comment by owocki** [comment]
we just merged 'snooze' functionality for the idle warnings.. does that suffice?

**Comment by PixelantDesign** [comment]
Works for me.
