### ISSUE TITLE
Crowdfunded bounties?

### ISSUE THREAD

**Issue by dolebas** [gitcoinco/web#1023]
### User Story

As a bounty funder, I may have shared interests with other projects that would be willing to fund parts of the same bounty.

### Context

Several projects, independent from each other, may be reliant on resolving the same issue in another project X.

Each party is willing to contribute funds to a bounty but only one project 'A' takes the initiative to do so. Projects BCD.. aggrees with the terms of the bounty but doesn't really trust project A with all of their money.

Projects BCD.. considers funding their own bounties for the same issue but for different reasons, that doesn't happen.

Meanwhile, all projects trusts project X and everybody would like to see a solution.

### Solution

Enable delegation of work acceptance to the repo maintainers of project X?

By enabling project A to delegate work acceptance to project X, projects BCD.. can safely contribute funds to the bounty without knowing wether project A is trustworthy or not.

Project A who are already familiar with Gitcoin can reach out to project X, as well as BCD.., explain how Gitcoin works and ask them for a small contribution.

The easy-first-step of contributing to a bounty this way can hopefully also help with onboarding of new projects to the platform. If BCD is helped by the crowdfunded bounty they may see the potential and create their own bounties for unrelated issues, and reach out to projects EFG, HIJ and KLM, and so on.

### Discussion

Yes, hopefully!

**Comment by owocki** [comment]
https://github.com/Bounties-Network/StandardBounties/issues/40

this is something that the standardbounties team ( @will.villanueva and @mbeylin ) are working on
