### ISSUE TITLE
Add tags to GiveStation grant.

### ISSUE THREAD

**Issue by kowskicoder** [gitcoinco/web#10238]
Hi, I'm Micheal. Founder of GiveStation.org.
I'd like to make a request for our grant to be added under the Polygon category as our dap is currently in beta on Polygon network and Ethereum mainnet. 

Givestation.org/projects

Thanks a lot for your assistance. 
#

**Comment by lthrift** [comment]
If you are still trying to update the tags on your grant, please contact tags@gitcoin.co
