### ISSUE TITLE
Create eligibility/discovery tag designation in database

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10251]
**User Story:**
As a Gitcoin admin
I want to indicate which grant tags are for eligibility or discovery
So that we can have clearer UIs for our users on top of that metadata 

**Acceptance Criteria**
GIVEN that I am working with tags
WHEN I create or modify a tag
THEN I can designate it as an "eligibility" tag or a "discovery" tag 

**Product & Design Links:**
- Please include surfacing this option in the Django admin view

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
Built in over at acca73157caa711bf939ceb926499ad92117727f

**Comment by nfrgosselin** [comment]
LGTM
