### ISSUE TITLE
Show tag type in grant creation dropdown

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10252]
Requires finishing #10251 

**User Story:**
As a grant owner
I want to know which tags are for eligibility or discovery
So that I know how to have my grants considered for the appropriate rounds

**Acceptance Criteria**
GIVEN that I am on step 1 of creating a grant (https://gitcoin.co/grants/new)
WHEN I open the tags dropdown
THEN I see the tags organized into eligibility and discovery sections

**Product & Design Links:**
Figma: [Create a Grant](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/?node-id=163%3A3717), Section 5 — Tags

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
This backend for this has been wired in 
https://stage.gitcoin.co/_administrationgrants/granttag/

**Comment by EmHsiehGitcoin** [comment]
looks great!!
