### ISSUE TITLE
Show tag type on grant details page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10253]
**User Story:**
As a Gitcoin user
I want to know which grants tags are for eligibility or discovery
So that I can better understand how tags impact a grant

**Acceptance Criteria**
GIVEN that I am on a grant's detail page
WHEN I look at the tags below the grant's name
THEN I see eligibility tags in a different color than discovery tags

GIVEN that I am on a grant's detail page
WHEN I hover over a tag
THEN I see a hover text box that says which tag type it is

**Product & Design Links:**
Figma: [Create a Grant](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/?node-id=163%3A3717), Section 6

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
Commit which fixes this : 230a3d90560ee10580695e9a59039d1f57331249

**Comment by schultztimothy** [comment]
Looks like @thelostone-mc already did this! I found one little bug when creating an account and put a PR together for it here:  https://github.com/gitcoinco/web/pull/10255
