### ISSUE TITLE
Update 'Follow' to 'Favorites', 'Add to Favorites'

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#10266]
- Change label to Favorite in profile menu
- Change filter labels in explorer page 
- Add purple alert banner when star icon is clicked in grant explorer
- Add purple alert banner when star icon is clicked in grant detail page 

Figma file: [Follow -> Favorite](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=308%3A4891)

**Comment by nfrgosselin** [comment]
LGTM — all of the criteria above are in here

@EmHsiehGitcoin one note: I think there's a "Remove from favorites" alert shown in your Figma file, but that isn't on this ticket. LMK if you want one added
