### ISSUE TITLE
Update Collections Card View

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#10272]
### Description 

- Pull stats from user profile (screenshot below)
- Align collection card spacings
- Link components 

Annotation + Acceptance criteria: 
Lite GR13 version: adding links 
![Screen Shot 2022-03-07 at 11 28 57 PM](https://user-images.githubusercontent.com/96255151/157166273-53ce694e-db41-48ae-9610-310f274b313e.png)

If possible without pushing other priorities: adding user stats 
![Screen Shot 2022-03-07 at 2 20 04 PM](https://user-images.githubusercontent.com/96255151/157103008-c3e81291-55d4-4dab-b4f7-692ad0134e83.png)

Figma = [🥨 Ready for Dev: Collection [Collection Card] section](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=303%3A4870
)

---------
- Quick view user stat screenshot: 
![Screen Shot 2022-03-07 at 2 22 36 PM](https://user-images.githubusercontent.com/96255151/157103398-71fb1e95-46c5-4108-8045-3289de6a9e79.png)

**Comment by EmHsiehGitcoin** [comment]
Statically, looks good to me but I can't tell if all the links work

**Comment by EmHsiehGitcoin** [comment]
Hihi, @chibie a few things missing: 

- Profile pic should be clickable and link to: gitcoin.co/[username]
- Follower & Following stats (number + title) should be clickable and link to: gitcoin.co/[username]/people 
- Funded & Contributed (number + title) should be clickable and link to: gitcoin.co/[username]/grants
