### ISSUE TITLE
Code-cleanup Flake8

### ISSUE THREAD

**Issue by CuriousLearner** [gitcoinco/web#1028]
### User Story

As a developer, I want a clean code base where flake8 is followed.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Better code standard will promote readability and attract new contributors to the project.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: STYLING

### Current Behavior
[comment]: # (Describe what actually happened.)
flake8 currently fails on the codebase

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
flake8 should pass

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Fix linting errors

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- flake8 should pass the entire codebase
- integrate flake8 with Travis to take care in further builds

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by mbeacom** [comment]
I agree with this, but due to the amount of open work on the platform, we're intentionally not linting the whole codebase to avoid unnecessary stress for fellow community contributors.

We plan to slowly lint each app as the opportunity presents itself and specifically enforce linting on apps that have already been migrated.

**Comment by CuriousLearner** [comment]
Sure, that makes sense. I'd lint if I touch any files :)

**Comment by mbeacom** [comment]
I typically make minor adjustments as I'm changing things as well.  I just don't want to overwhelm would-be contributors if they have something they're working on in a PR/fork when they try to rebase with the linting changes.

**Comment by kuhnchris** [comment]
Did you ever send in a PR @CuriousLearner ?

**Comment by CuriousLearner** [comment]
@kuhnchris Nope. I feel maintainers are inclined towards incremental changes ( which makes sense) fixing these linting errors, so I do not wanted to work on a humongous PR which will be left hanging. 

So, I'm not sure if a single PR fixing all this would help 🤷‍♂

**Comment by kuhnchris** [comment]
Well, I guess we'll have to ask @danlipert or @owocki for a decision on that.

**Comment by CuriousLearner** [comment]
Cool, let me know if you need a helping hand ;)

**Comment by kuhnchris** [comment]
Guess that's a no, thanks for offering your help tho @CuriousLearner !
