### ISSUE TITLE
Add back button to Explorer and keep position when going back

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10291]
Context:
Right now when the user navigate from Grants Landing Page’s CLR Banners to Explorer page, they don’t have a way to go back. 
The back function on browser reloads the explorer page instead of going back to grants LP.
Therefore we are adding a Back to Grants link and it should remind position when going back. 

Acceptance Criteria: 
1. Add back text link + caret
2. When clicking on the back text link, it brings the user back to where they were and should remind in position

[Figma file: ◽ Add back button to Explorer](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=1040%3A30521)

![Screen Shot 2022-03-10 at 9 57 04 AM](https://user-images.githubusercontent.com/96255151/157688613-af40ea2c-67fb-4087-a2f2-d8ef62bc34d3.png)

**Comment by schultztimothy** [comment]
I wasn't able to get to this today with all of the support requests. Throwing it back in todo and will pick it up first thing tomorrow if no one else grabs it

**Comment by EmHsiehGitcoin** [comment]
Chatted with team, we will be fixing the back button function on browser instead of adding the < Back button. Closing this issue and opening a new one: https://github.com/gitcoinco/web/issues/10343
