### ISSUE TITLE
Remove Create a Grant form border in mobile

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10293]
Context:
Desktop looks great with the border but it's not as suitable for mobile
Removing the form border on mobile ONLY to increase the real-estate of the form

AC: 
- Remove form border 

![Screen Shot 2022-03-09 at 11 19 05 AM](https://user-images.githubusercontent.com/96255151/157483776-ed34b096-6fcd-444d-a6eb-11112c45bc72.png)

**Comment by thelostone-mc** [comment]
![Untitled](https://user-images.githubusercontent.com/5358146/157627307-496d2ada-411c-4e11-bb82-82af9241b90f.gif)


fixed via e61748278acf1e3d5a93de4f7c8ce0ea9c5fd3af

**Comment by EmHsiehGitcoin** [comment]
looks good!
