### ISSUE TITLE
Grant detail page mobile width broken due to links in About section

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10296]
[Jonas's original request ](https://www.notion.so/gitcoin/Page-width-issue-on-mobile-c881db454b654b218d77071aeefd148a)

I've paired with @thelostone-mc  on this and we found out that it's actually not the images that are breaking the width but the links in the About section. Weird, right? So we'd have to find out how to fix this since we can't just ask the owners to remove the links :P 

<img width="3168" alt="mobile detail width" src="https://user-images.githubusercontent.com/96255151/157518758-5aea3ad0-d09a-4e34-8f6f-0228c8d059ef.png">

**Comment by thelostone-mc** [comment]
Fixed via fa9424a3625fa1e84fe3b926c5743c104b7b54f4

**Comment by EmHsiehGitcoin** [comment]
Looks good!
