### ISSUE TITLE
Update Mobile GrantsLP

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10294]
The UI element order and the spacing isn't super ideal. Reducing unnecessary spacing and shuffled the order a little bit for optimized experience.

[Figma file link: #10294 Update Mobile Grants LP
](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=1040%3A31288) 

AC: 
1. Reduce spacing between title & body text 
2. Reduce spacing between body text & button 
3. Move GR13 image to the top above title 

<img width="2970" alt="Group 2" src="https://user-images.githubusercontent.com/96255151/157491102-1476e2be-46ca-4ad0-a8de-04c253ef466d.png">

**Comment by EmHsiehGitcoin** [comment]
@chibie I don't see the changes. is it reflecting correctly?
<img width="440" alt="Screen Shot 2022-03-11 at 11 58 00 AM" src="https://user-images.githubusercontent.com/96255151/157912688-ab505479-dff2-4473-9c53-f2cf3db89e76.png">

**Comment by chibie** [comment]
@EmHsiehGitcoin i just updated staging... it wasn't up to date

**Comment by EmHsiehGitcoin** [comment]
Looks good!
