### ISSUE TITLE
swap menu icon in mobile

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10290]
Acceptance criteria: 
- Remove og icons and outline
- Add updated icons

[Figma file: #10290 swap mobile menu icon](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=1040%3A30591)

![Screen Shot 2022-03-09 at 10 50 06 AM](https://user-images.githubusercontent.com/96255151/157477814-bf90a52f-e147-4abe-8443-0595d4399a97.png)

Here are the two assets:

close icon
![close_icon](https://user-images.githubusercontent.com/96255151/157477331-087c4b0a-a39a-4ec7-812a-06a0b946306e.svg)

menu icon
![menu_icon](https://user-images.githubusercontent.com/96255151/157477334-50821960-17f5-4f67-9558-07005db23598.svg)

**Comment by thelostone-mc** [comment]
Fixed via c41813e2ed34a354b487d38fe55869c6f122b0f4

**Comment by EmHsiehGitcoin** [comment]
looks great!
