### ISSUE TITLE
change grant owner

### ISSUE THREAD

**Issue by aliatiia** [gitcoinco/web#10304]
### Who

The yAcademy Grant: https://gitcoin.co/grants/5092/yacademy-scaling-ethereum-security

### What

Change the owner of the yAcademy Grant: https://gitcoin.co/grants/5092/yacademy-scaling-ethereum-security from team member "aliatiia" to the organization (github/gitcoin handle "yacademy")

### Why

The organization overall is the owner of this grant. It was created by our team member "aliatiia" assuming mistakingly the the 'owner' can be set later on, which is not the case, hence we are creating this issue.

**Comment by nfrgosselin** [comment]
Closing this issue as @YukiPL has taken care of it. Please re-open if you need us to look again!
