### ISSUE TITLE
Make gitcoin.co GR13 banner clickable

### ISSUE THREAD

**Issue by EmHsiehGitcoin** [gitcoinco/web#10302]
AC:
- when the user click anywhere else on the image it takes them to Grants' Landing Page (gitcoin.co/grants)

See [prototype](https://www.figma.com/proto/8QjqOzDBd4HiE37YqcocK7/GR13?page-id=311%3A12775&node-id=947%3A51896&viewport=273%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=947%3A51896&show-proto-sidebar=1)

**Comment by EmHsiehGitcoin** [comment]
I don't think staging is properly reflecting the change. it's not clickable still.

**Comment by nfrgosselin** [comment]
+1 — I'm not seeing the change on staging either

**Comment by nfrgosselin** [comment]
Staging's updated now — it looks good to me!

**Comment by EmHsiehGitcoin** [comment]
lg!
