### ISSUE TITLE
Gitcoin bot continuously reporting dropped transacation

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10317]
**Overview**
One of our users (selimerunkut) is receiving daily transaction status updates from the Gitcoin bot on a contribution he made in GR8 (~1 year ago).

**Steps to reproduce**
1. Impersonate user **selimerunkut**
2. Look at notifications for user

**Comment by schultztimothy** [comment]
<img width="1692" alt="Screen Shot 2022-03-14 at 9 43 24 AM" src="https://user-images.githubusercontent.com/6887938/158208508-76929bc5-7d31-477a-b1c1-5b5b24f6866d.png">
@nfrgosselin I can't seem to find this user?

**Comment by thelostone-mc** [comment]
This is the profile: https://gitcoin.co/selimerunkut

**Comment by nfrgosselin** [comment]
Thanks @thelostone-mc — what's the right way to fix this for him then? He's still getting those notifications, so do we just delete those contributions? 

cc: @schultztimothy

**Comment by nfrgosselin** [comment]
This is happening with another [user](https://gitcoin.co/ldlc2021) — @thelostone-mc / @schultztimothy is there a good way to reset this with them?

**Comment by nfrgosselin** [comment]
FYI another user has reported this: https://gitcoin.co/rel0aded 

According to Yuki:
he just registered yesterday and made his first donation, but as usual missing contribution and marked as failed. I quote the user, "I am getting non-stop continual notifications (currently at 263 since I signed up yesterday!) with these bot messages"

**Comment by chibie** [comment]
the user `rel0aded` has 5 contributions with empty `tx_id` - 1974172 1974174, 1974176, 1974179, & 1974181

**Comment by chibie** [comment]
i've been able to narrow this down to a change made in this commit https://github.com/gitcoinco/web/commit/539598eb676d8134b40a8abf2999f5c935d76e9d

the above change triggered the signal that creates the notification everytime a create happens. (update_or_create does same thing without triggering signal) cc: @gdixon 

i've also deleted the duplicate notifications in the affected account
