### ISSUE TITLE
Oasis Direct Widget 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1031]
_Needs Review_

### User Story

As a Funder, I want to be aware of an option to quickly transfer my ETH into a price-stable cryptocurrency which will likely hold value over the term of my bounty.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Embed the [Oasis Direct Widget](http://oasis.direct/) into the [Fund Issue](gitcoin.co/new) page. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Embed the Oasis Direct widget in the Fund Issue page. Need @PixelantDesign feedback on whether a) this is on brand and b) if so, where embedding it could be useful. Perhaps under 'Fund Issue', where an e-mail captcha currently sits? 

![screen shot 2018-04-30 at 2 09 30 pm](https://user-images.githubusercontent.com/23297747/39445321-528480e2-4c80-11e8-8867-820669f82eef.png)

### Additional Information
[See here](https://github.com/OasisDEX/oasis-direct-widget) for the code for the Oasis Direct Widget. 

![screen shot 2018-04-30 at 2 08 32 pm](https://user-images.githubusercontent.com/23297747/39445238-02a5ac86-4c80-11e8-9bbb-99dac030c0c7.png)

**Comment by kuhnchris** [comment]
Oasis.direct is dead.
