### ISSUE TITLE
Missing contributions

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10316]
Multiple donors are reporting that their contributions are missing — this issue was raised in discord [here](https://discord.com/channels/562828676480237578/920714502650077264/951572850463113286). 

The first batch seemed localized to zkSync, but we have started to see missing contributions on Polygon as well (Polygon specifically was raised in this [discord thread](https://discord.com/channels/562828676480237578/920714502650077264/951835038549426227)).

**Comment by jerryxue09** [comment]
waht about polygon donation? when fix

**Comment by nfrgosselin** [comment]
I've tested the zkSync checkout flow on Rinkeby and the Polygon checkout flow on Mumbai — both look good to me! Thanks guys.
