### ISSUE TITLE
Only show L2 guide if you have L2 contributions

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10310]
**User Story:**
As a grant owner
I want to **only** see the L2 Withdrawal Guide box when I actually have L2 contributions
So that I don't have unnecessary buttons

**Acceptance Criteria**
GIVEN that I **have not** received L2 contributions in the last 2 weeks
WHEN I look at my grant details page
THEN I **do not** see the "You've received L2 Contributions" box

GIVEN that I **have** received L2 contributions in the last 2 weeks
WHEN I look at my grant details page
THEN I **do** see the "You've received L2 Contributions" box
AND the "You've received L2" box is _below_ the "Keep your grant up to date" box

**Product & Design Links:**
![l2_guide](https://user-images.githubusercontent.com/15041635/157738093-d74f6411-0d87-4323-ab1c-918dfa2cadf0.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by EmHsiehGitcoin** [comment]
hmm, I'm not sure how to trigger this
