### ISSUE TITLE
Reduce number of Collections on main Grants page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10324]
**User Story:**
As a grant funder
I want to see a more manageable number of collections on the main grants page
So that I can efficiently figure out what's happening on the page

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/
WHEN I look at the collections section
THEN I only see four collections
AND I see a "View More" button below them

GIVEN that I am on gitcoin.co/grants/ and looking at the collections section
WHEN I click on the "View More" button
THEN I am taken to https://gitcoin.co/grants/explorer/?tab=collections

**Product & Design Links:**
![Screen Shot 2022-03-08 at 1 53 51 PM](https://user-images.githubusercontent.com/96255151/157305820-97cd4551-c6e9-4021-8668-edb2b5d008a5.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by EmHsiehGitcoin** [comment]
Let's keep the design the same as the mock here but instead of "Load more" CTA the copy would be "View more" and links to Collection tab on Explorer Page

**Comment by nfrgosselin** [comment]
LGTM!
