### ISSUE TITLE
Don't show Polygon wallet tag on multisigs

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10327]
**User Story:**
As a user
I _don't_ want to see the Polygon tag next to a multisig grants wallet address
So that I don't mistakenly think I can donate to it on Polygon

**Acceptance Criteria**
GIVEN that I am on the grant detail page for a grant with a multisig wallet
WHEN I look at the grant's wallet address
THEN I **do not** see the Polygon tag next to it

**Product & Design Links:**
[This grant](https://gitcoin.co/grants/4578/tan-dong-lun-xi) is an example
<img width="644" alt="image" src="https://user-images.githubusercontent.com/15041635/158190463-cba666aa-e577-4b4f-a0f1-092d446075e6.png">

**Tech Details:**
[10329](https://github.com/gitcoinco/web/pull/10329)

**Open Questions:**

**Notes/Assumptions:**

**Comment by EmHsiehGitcoin** [comment]
Are we able to see non-test grants on staging? not sure how to test this

**Comment by nfrgosselin** [comment]
I just looked at my multisig test grant and it's still showing the Polygon tag:
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/15041635/158876486-14298741-e528-44c0-9e72-10c0d6e8d7f7.png">

The address is definitely a multisig though:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/15041635/158876617-d947c8c9-4b20-4517-9071-22fcb9fcfbcf.png">

@thelostone-mc can you double-check this?

**Comment by thelostone-mc** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5358146/159209742-55f129a4-c36f-4afd-b4c4-fe60ff594105.png">

https://stage.gitcoin.co/grants/73/multisig-grant


Could you do a hard refresh and check @nfrgosselin 
I'm looking at the same grant and it seems to work as expected

**Comment by nfrgosselin** [comment]
Uh-oh — I've hard refreshed and cleared my cache but I'm still seeing the Polygon tag @thelostone-mc 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/15041635/159350936-fb1b59e8-1740-49e3-92a5-31c51cab4c47.png">
