### ISSUE TITLE
Change cross-chain tab UI design to match Etherum tab in cart

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10325]
**User Story:**
As a grant funder ready to checkout 
I want the checkout tabs to have consistent designs 
So that I feel that I can trust the Gitcoin checkout experience

**Acceptance Criteria**
GIVEN that I am on the cross-chain checkout tab
WHEN I look at the page design
THEN it has a similar design to the Eth checkout

**Product & Design Notes:**
The cross-chain tab currently has a completely different UI design — we just need to match it to look like the Eth tab.

Correct:
<img width="1440" alt="158478969-87bd4b89-f1c3-4f17-9d90-9d54cbfecfdd" src="https://user-images.githubusercontent.com/15041635/158492188-b2b52627-657d-44cf-99ba-8b4bfa1f06b4.png">

Current / Incorrect:
 <img width="1225" alt="Screen Shot 2022-03-01 at 8 59 17 AM" src="https://user-images.githubusercontent.com/96255151/156182855-3b089bb8-3b71-4ac0-9146-483db44bed64.png">
<img width="1239" alt="Screen Shot 2022-03-02 at 4 29 10 PM" src="https://user-images.githubusercontent.com/96255151/156454411-c2f56d98-d98d-4799-bb8c-6c7c9f40f76e.png">

**Comment by EmHsiehGitcoin** [comment]
@nfrgosselin updated mock
- removed % section 
- no dropdown on checkout button
<img width="1440" alt="Owner's Guide v 1" src="https://user-images.githubusercontent.com/96255151/158478969-87bd4b89-f1c3-4f17-9d90-9d54cbfecfdd.png">

**Comment by nfrgosselin** [comment]
Thanks @EmHsiehGitcoin! Updated the main story

**Comment by chibie** [comment]
@EmHsiehGitcoin @nfrgosselin i guess we can take out "Which option is best for me? " text since cross-chain tabs usually have one option integration for them

**Comment by nfrgosselin** [comment]
LGTM
