### ISSUE TITLE
only CEL and BNB are shown despite having active Metamask wallet with Matek on Polygon

### ISSUE THREAD

**Issue by antonkulaga** [gitcoinco/web#10346]
When I and a bunch of my friends tried to donate this evening we had either CEL and BNB or nothing in the token list despite having active Metamask browser extension as well as MATIC on the polygon wallets.
Here are the screenshots:
![alexandru_vode_error](https://user-images.githubusercontent.com/842436/158488273-4206b5cb-29a6-433b-a914-44543a92ae38.png)
![other_browser](https://user-images.githubusercontent.com/842436/158488277-f35a0508-caad-4ee0-a498-215718aae394.png)
 
the bug seems to be in both Chrome and Firefox browsers

**Comment by Devjohn12** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by antonkulaga** [comment]
Looks like it is working for me today. Was it a bug or polygon was simply overloaded?

**Comment by antonkulaga** [comment]
Looks like it is fixed, closing the issue
