### ISSUE TITLE
work scheme v2 brainstorming

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1035]
follow up to https://github.com/gitcoinco/web/issues/973

convo with @pipermerriam today:  for the `approved` scheme, we might want to allow auto-approvals of ppl who've done bounties before.  

we may also want to allow blacklisting

another idea: require users to stake some ETH in order to start work.  they lose it if they abandon it

from @kumavis: we may want to do some sort of “fractional reserve” security bounty fund

another idea: waitlist on traditional bounties

another idea: transitioning an approval-required issue to 'permissionless' when the funder is not responding to approvals

from @PixelantDesign : Not to bloat up the work schemes, but I wonder if it might makes sense to allow for a progressive input under Work Scheme: Traditional so that the funder can tag a contributor that they're reserving the issue for.

scope question: should we allow the ‘approval required’ permission type with the ‘contest’ type?  seems that doesnt make any sense from a use case to me

for cooperative bounties, be able to actually split the acceptance into paying out many payments (instead of just 100% to one person)

**Comment by PixelantDesign** [comment]
great idea!

**Comment by thelostone-mc** [comment]
Blacklist as in a ban period where they can't work on bounties ? 

Also what perks would have an approved candidate have over a new one ?

**Comment by owocki** [comment]
> Blacklist as in a ban period where they can't work on bounties ?

yes, configurable by the funder at their discretion

> Also what perks would have an approved candidate have over a new one ?

this can be up to the repo maintainer, according to whatever their standards are for contributors to their repos

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/973
