### ISSUE TITLE
Double-check CLR calcs

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10369]
**Details**
When spot checking the UI, Grant Ops discovered that there are a few rounds where we aren't close to distributing all of the matching funds, despite being approximately halfway through the round already. They pulled the data and the current saturation looks like this:

![](https://cdn.discordapp.com/attachments/953771373128450158/953771567551225867/unknown.png)

Where rounds in:
- green are perfectly saturated
- red are under saturated
- yellow are over saturated

Can someone look into the calcs and verify that they are calculating appropriately?

**Comment by schultztimothy** [comment]
I'm going to move this back into todo. @gravityblast and I looked into it this morning and learned a bit. We then got confirmation from @gdixon and @thelostone-mc confirmed that things should be working as expected.


https://discord.com/channels/562828676480237578/953771373128450158/954418235606982706

**Comment by nfrgosselin** [comment]
Closing this out — @thelostone-mc verified that calculations were working as expected.
