### ISSUE TITLE
Speed up explorer filters

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10374]
**User Story:**
As a user
I want grant explorer search results to load quickly
So that I can efficiently browse and donate to grants

**Acceptance Criteria**
Investigate slow load times and develop a plan to reduce

**Product & Design Links:**

**Tech Details:**
Notes from @thelostone-mc: 
Total requests to get_grants in last 24 hours : 30k
Avg duration is: 2s 

1st image & 2nd Image
----------------------
It looks like 10% of our requests take more than 5.42 seconds 

3rd Image
------------
On filtering requests, it looks like most of the time is taken in the django app (aka business logic code and not DB query) which makes it confusing to see what might be causing it

4th Image
--------------

Let's take an individual request which took 12s: 
https://app.datadoghq.com/apm/trace/17633664223658479660?colorBy=service&env=prod&graphType=span_list&shouldShowLegend=true&sort=time&spanID=250689562829975793&spanViewType=metadata&timeHint=1647436558239.5872

This validates that 60% of the time request time went for django code while the rest was for DB (and we this a lot)

5th Image & 6th Image
-------------
Looking at the DB calls, it looks like the 
- grants filter is heavy as we query against the entire DB  (5th image)
- query to fetch team members (6th image)

We could attempt to improve query but I'm curious to see what operation is it that we do which causes 60% of time to stay in django before returning a response 

![](https://cdn.discordapp.com/attachments/953709815291584554/953893534941995018/unknown.png)

![](https://cdn.discordapp.com/attachments/953709815291584554/953893535243960340/unknown.png)

![](https://cdn.discordapp.com/attachments/953709815291584554/953893535441121310/unknown.png)

![](https://cdn.discordapp.com/attachments/953709815291584554/953893535671799888/unknown.png)

![](https://cdn.discordapp.com/attachments/953709815291584554/953893535894110218/unknown.png)

![](https://cdn.discordapp.com/attachments/953709815291584554/953893536225452032/unknown.png)

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
@nfrgosselin How open are we to restrict the keyword seach to only titles and not title & description.
text based searches are expensive the way we have it setup and we might have to explore something like elasticsearch to make the search more efficient (which i don't know if is worth pursing given that the product is heading towards maintainance )
