### ISSUE TITLE
Support Request Follow Up

### ISSUE THREAD

**Issue by lkngtn** [gitcoinco/web#10377]
### Who

I'm currently the owner of the [Gardens grant on gitcoin](https://gitcoin.co/grants/899/1hive-gardens-1) and have made a request to change the ownership to [0xGabi](https://github.com/0xGabi)  who is the project lead and current maintainer of [the gardens project](https://github.com/1Hive/gardens). 

### What

We want to transfer ownership of the grant so that the team can continue to use the same grant rather than create new ones as it has created confusion with the old grant being easier to find but actually being inactive. 

### Why

I was told to submit an issue here so that there is a public record of this request before the support team can move forward with the request.

**Comment by nfrgosselin** [comment]
Hi @lkngtn! Sounds like our support team took care of this so I'm closing out. Please let support@gitcoin.co know if you need anything else.
