### ISSUE TITLE
Grant creation stuck without error

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10373]
**Overview**
Gerald found an issue with the grant creation flow, where if the user has a form error on the last step they cannot submit but don't receive an error message. There's a video of the flow [here](https://www.loom.com/share/005009d448ab44dbb067cb42897a4d3a). 

**Reproduction Steps:**
1. Go to create a grant
2. On the last step, enter "0x0" for the wallet address
3. Hit submit

**Comment by thelostone-mc** [comment]
![Untitled](https://user-images.githubusercontent.com/5358146/159213632-b89001e4-cd86-473f-95d1-b8a11508471a.gif)

commit: c4b2da0b5d8ccf3c30ab2ebd793ea9ebf7cf6ae1

**Comment by nfrgosselin** [comment]
LGTM!
