### ISSUE TITLE
Moving bounty with historical record

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#1038]
### User Story

As a funder, I want to move my bounty when upstream problem is broken down into more specific issues, so that bounty can stay relevant.

### Current Behavior
I need to kill bounty and create new one with new funds.

### Expected Behavior
I want to move existing funds to new issue with @gitcoinbot making notice about the move, and with bounty page reflecting move in a history.

### Additional Information
* #994 
* https://gitcoin.co/issue/ipld/js-cid/38/121 - issue moved to more specific problem

**Comment by owocki** [comment]
right now the bounty will sync the issue desc / title from github.  perhaps that can work for you as a stopgap until we provide edit functionality?

**Comment by abitrolly** [comment]
Would be nice to see diffs when upstream issues change. Right now the bounty from https://github.com/ipld/js-cid/issues/38 needs to be moved to https://github.com/ipfs/js-ipfs/issues/1321

**Comment by kuhnchris** [comment]
superseeded by #4870; basic idea is still not fully covered (replace bounty by next bounty) but at least the description update should be covered - closing.
