### ISSUE TITLE
Unable to post to Recent Activity 

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10381]
**Details**
Multiple users have reported that they receive an error when trying to post to a grant's Activity feed. When attempting to reproduce, I noticed that I didn't see the error when posting with my profile but was able to reproduce it when impersonating another user's. 

**Reproduction Steps**
1. Impersonate user [annikalewis](https://gitcoin.co/_administrationdashboard/profile/243173/change/?_changelist_filters=q%3Dannika)
2. Go to any grant
3. Attempt to post a comment on Recent Activity (see screenshot

![unknown (1)](https://user-images.githubusercontent.com/15041635/159349660-44e6a37e-a8a7-4e0e-87bd-f463d112f530.png)

**Notes**
One of the reporting users is an engineer and has offered to connect with whoever picks this up if needed

**Comment by thelostone-mc** [comment]
lol this is code working as intended. The profile annika has been squelched / marked sybil by the bsci script 
Until that is removed -> the profile will not be be able to login to it.
[Here is the link to that ](https://gitcoin.co/_administrationtownsquare/squelchprofile/10844/change/  )
