### ISSUE TITLE
BNB showing as currency on Ethereum

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10389]
**Overview**
The [Phaser grant](https://gitcoin.co/grants/4949/phaser) is claiming that they can't checkout using standard checkout when on the BNB chain (see screenshot below). 

**Steps To Reproduce**
1. Add the [Phaser grant](https://gitcoin.co/grants/4949/phaser) to your cart
2. Click to checkout
3. Select BNB as the currency
4. Select Standard checkout

**Observed  behavior**
The user is able to select BNB while on an Ethereum grant, and then sees an error when trying to use Standard Checkout.

**Expected behavior**
BNB should not be showing up as a currency option when on an Ethereum grant. 

**Screenshots**
<img width="892" alt="image" src="https://user-images.githubusercontent.com/15041635/159495125-a9fb4f51-f323-47da-bbee-fd08857c0ed5.png">

**Additional context**
Aditya has looked into this a bit — hit him up if you need some extra context

**Comment by thelostone-mc** [comment]
This was an incorrectly configured token https://gitcoin.co/_administrationeconomy/token/667/change
That entry has been disabled from the token table
The correct entry is at  https://gitcoin.co/_administrationeconomy/token/73
