### ISSUE TITLE
Unable to cancel the duplicate grant

### ISSUE THREAD

**Issue by Vai8hav** [gitcoinco/web#10401]
Hello,

I had created a grant a couple of days back and it automatically created a duplicate of it which I didn't intend to. Even after canceling it multiple times, it is still showing up. For your clarity, [grant 5531](https://gitcoin.co/grants/5531/the-product-house) needs to be deleted and [grant 5532](https://gitcoin.co/grants/5532/the-product-house) needs to be kept.

My username: Vai8hav

**Comment by nfrgosselin** [comment]
Thanks Vai8hav! If you send this to support@gitcoin.co they can definitely take care of this for you
