### ISSUE TITLE
Hi, Can I delete grant application 5525 and keep 5526?

### ISSUE THREAD

**Issue by trtwarrior** [gitcoinco/web#10423]
Hi team,

I created grant application 5525 which contains some mistake and I use my other account to create 5526 instead. Could you help me to remove 5525 and just keep 5526? 

It's my first time and really sorry for it. Fully understood you are very busy reviewing things and by this way you can save some time.

Thank you.
Yours, Jay

**Comment by nfrgosselin** [comment]
Hi Jay, thanks for the note! If you send this to [support@gitcoin.co](mailto:support@gitcoin.co) they can help you out.
