### ISSUE TITLE
Deploy GR13 payout contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10435]
**User Story:**
As a Gitcoin engineer
I want to configure the GR13 payouts contracts
So that they are ready to be deployed to Mainnet

**Acceptance Criteria**
GIVEN that the GR13 payout amounts are approved
WHEN I look at the three GR13 payout contracts (DAI, UNI, gOHM)
THEN they are properly configured for deployment to Mainnet

GIVEN that the GR13 payout amounts are approved
WHEN I look at the three GR13 payout contracts (DAI, UNI, gOHM)
THEN the account-amount mappings are correct

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
These are done and recorded over at https://discord.com/channels/562828676480237578/956258102263578684/963689587203530782
