### ISSUE TITLE
Remove Feedback email from Product@gitcoin

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10438]
**User Story:**
As a product manager
I want to remove the email asking for feedback due to inactivity
So that I can only have value add emails going out

**Acceptance Criteria**
The following email no longer sends to funders:

hi @owocki,

kyle, frank, and alisa from Gitcoin here — i see you haven't funded an issue in a few months.

in the spirit of making Gitcoin better + checking in:

> do you have any issues which might be bounty worthy or projects you're hoping to build?

> do you have any feedback for us on how we might improve the product to fit your needs?

> are you interested in hosting or partnering in one of our upcoming hackathons? this is often teh best way to get top talent working on your issues.

appreciate you being a part of the community + if you are intersted, you can use discount code product-feedback-is-a-gift for 50% off your order :)

~ kyle, frank & alisa (gitcoin product team)

**Comment by nutrina** [comment]
@GTChase I am checking this now. I do not yet know how these are triggered.

**Comment by nutrina** [comment]
@GTChase I have started removing the entire code related to this. Is this ok? Or shall I only remove the cronjob that triggers this.

**Comment by nutrina** [comment]
Cronjob has been deactivated.
