### ISSUE TITLE
Harmony grants integration

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10449]
**User Story:**
As a grant contributor 
I want to contribute to a grant which has harmony payout address via metamask 
So that the grant successfully receives the contributions 

**Acceptance Criteria**
GIVEN a harmony grant exists 
WHEN a user contributes to it using the ONE token via metamask 
THEN the grant successfully recieves the contribution 

**Tech Details:**

During the original integration , harmony had it's own web3 wallet (inspired from metamask)
Presently that wallet has been retired and instead harmony now encourages dApp to sign txn via metamask
The goal is here is to ensure contributors can contribute ONE tokens via metamask

The fix has been done for the bounties via https://github.com/gitcoinco/web/pull/10430
We can use this a code refrence and update the frontend to do the same for grants

Do reach out to @nutrina if questions arise and he'd be able to provide additional context (if needed)

**Comment by schultztimothy** [comment]
I wasn't quite able to finish this before my trip, so I'm going to put this back into todo just in case someone can pick it up while I'm out. I've pushed my changes up here: https://github.com/gitcoinco/web/pull/new/10449-harmony-update. Just let me know if you have any questions.

**Comment by nfrgosselin** [comment]
@chibie I just tried to test this out with my [Harmony test grant](https://stage.gitcoin.co/grants/98/harmony-testing-grant) but I got an error when I clicked to check out (see screenshot). Can you take a look?

![Image](https://user-images.githubusercontent.com/15041635/170708723-3d47768a-2207-42f8-a0eb-7c4632a8856a.png)

**Comment by nfrgosselin** [comment]
This looks good to me — I've created a quick follow-on story here #10641
