### ISSUE TITLE
Round 8 + 9 data in Metabase looks off

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10450]
**Overview**
something seems wrong for rounds 8 & 9 showing $0 matching pot + the crowdfund amounts are off. I think its maybe a database integrity issue?  some validator script gone wrong?

**Steps To Reproduce**

1. Go to https://metabase.gitcoin.co/question/828

**Observed  behavior**
rounds 8 & 9 showing $0 matching pot + the crowdfund amounts are off

**Comment by thelostone-mc** [comment]
This was something I had stumbled while fetching data for the phenoix project as well.
It looks like the data was cleared and since i wasn't sure how to get it back.
