### ISSUE TITLE
Ingest claim object into match table

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10452]
**User Story:**
As a Gitcoin engineer
I want to ingest the claim object into our CLRmatch table
So that grant owners can claim their matching funds

**Acceptance Criteria**
GIVEN that GR13 Claims objects have been generated
WHEN I look at the CLRMatch table
THEN I see that the relevant data has been updated

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
The claim object has been ingested from the merkle generator into the DB.
The logs are captured here:
https://discord.com/channels/562828676480237578/956258102263578684/963689587203530782
