### ISSUE TITLE
Deploy Merkle contracts to Mainnet

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10451]
**User Story:**
As a Gitcoin engineer
I want to deploy the GR13 payout contracts to Mainnet
So that GR13 matching amounts can be claimed

**Acceptance Criteria**
GIVEN that the three GR13 payout contracts are configured (DAI, UNI, gOHM)
WHEN I deploy them to Mainnet
THEN they function properly

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
Deploy are done and recorded here:
https://github.com/thelostone-mc/merkle_payouts#deploys

**Comment by thelostone-mc** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/5358146/163167310-14868e80-78e7-4603-b5b1-5f31dd2d737c.png">
