### ISSUE TITLE
can't search by freeform text anymore

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1046]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: bug

i can't search by freeform text anymore [screencap](http://bits.owocki.com/1D1F0j3D2w1P/Screen%20Recording%202018-05-01%20at%2007.50%20AM.mov)

i have to find a value via autocorrect and then select it.  

expected belaviour:  i should be able to search by any text i enter into the the search field

probably related to https://github.com/gitcoinco/web/pull/790

**Comment by owocki** [comment]
cc @eswarasai and @PixelantDesign

**Comment by eswarasai** [comment]
@owocki -- Oops! I've missed this scenario I guess. I can handle this by converting the text into filter `tag` upon clicking the `Search` button. Thanks for pointing this out :)

**Comment by owocki** [comment]
thanks @eswarasai

**Comment by PixelantDesign** [comment]
hmm yea, looks like a bug. Thanks @eswarasai
