### ISSUE TITLE
Pull list of GR13 contributor emails

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10471]
**Details:**
Jonas (MMM) is looking for a list of emails for all contributors who donated to a grant in GR13. That data is a little hard to pull out of metabase (there isn't a distinct user id column in the contributions table, but the user handle is part of a larger data blob), so we need some dev help to do this. 

**Acceptance Criteria**
- deliver a csv that shows the username + email address for all users who contributed during GR13 (3/9 - 3/24)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by schultztimothy** [comment]
Heres the query that can be ran in metabase to get the desired information

`SELECT dashboard_profile.email, dashboard_profile.handle, grants_contribution.id
       FROM dashboard_profile
       JOIN grants_contribution
            ON dashboard_profile.id = grants_contribution.profile_for_clr_id
       WHERE grants_contribution.created_on between '2022-03-11' and '2022-03-24'`

**Comment by thelostone-mc** [comment]
```python
from grants.models import Contribution

c = Contribution.objects.filter(created_on__range=['2022-03-11', '2022-03-24']).values(profile_for_clr__email).distinct()
emails = []

for _c in c:
    print(_c.get('profile_for_clr__email'))
```

List has been sent over to Jonas
