### ISSUE TITLE
Update relevance priority in global search results

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10481]
**Spike timebox: half day**

**User Story:**
As a Gitcoin user
I want to see the most relevant results first
So that I can more easily find what I'm looking for

**Acceptance Criteria**
GIVEN that I have entered a search term in global search
WHEN the results load
THEN I see exact matches first (if I type "ether" than I should see "ether grant"  before "ethereum grant") 
AND THEN I see matches that start with my term (if I type "ether" I should see "Ether grant" before "This is an Ether Grant")
AND THEN I see all other matches for my term

^ this is the desired behavior —> please pair with Nate after the spike timebox to figure out the additional stories that are needed

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by schultztimothy** [comment]
We should just need to update the ES [query](https://github.com/gitcoinco/web/blob/060c0912511e7a00ca47dd8612f7ed898b202b02/app/search/models.py#L54) used here. I have put some documentation below on the different query types.

FYI - we are currently searching across title and description. Not sure if that is captured in the AC

Term query seems like what we need
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-term-query.html

Some explanations of queries:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/term-level-queries.html

**Comment by nfrgosselin** [comment]
Follow-on story is created — closing out this spike
