### ISSUE TITLE
Gitcoin doesn't allow Polygon checkout on Coinbase

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10482]
**Overview**
Gitcoin throws an error when a user tries to go through Polygon checkout using the Coinbase Wallet dapp browser. Instead of prompting to switch the network to Polygon, Gitcoin shows an error that says “Polygon Checkout is not supported on this wallet. Select another checkout option or switch to MetaMask.”

**Steps To Reproduce**
1. Open up Coinbase Wallet
2. Navigate to gitcoin.co in the dapp browser
3. Add any campaign to cart and navigate to checkout
4. Tap “I’m Ready to Checkout” 
5. Tap “Polygon Checkout”

**Observed  behavior**
Gitcoin UI shows an error that Polygon checkout is not supported

**Expected behavior**
Gitcoin prompts wallet to switch network to Polygon

**Additional context**
The Coinbase team has drafted some thoughts and shared a video of this experience [here](https://docs.google.com/document/d/1uuJWaKFfXSwB9rlNlRdhxMsqSuTun0xITs_ziBCa1Dg/edit).

**Comment by chibie** [comment]
https://hackmd.io/JL4JN-r0TqW89khkc_Sgcw

**Comment by nfrgosselin** [comment]
Thanks @chibie —> opened a new story for the follow-on work here #10530
