### ISSUE TITLE
Revise Grant Explorer search bar behavior

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10488]
**User Story:**
As a Gitcoin user
I want to be able to see the Grant Explorer filters while I am working with the explorer search bar
So that I know what filters have already been enabled

**Acceptance Criteria**
GIVEN that I am on gitcoin.co/grants/explorer/ and the explorer search bar is empty
WHEN I click into the search bar
THEN the search bar expands to cover 2/3 of the page
AND does not cover up the Filter buttons
AND I do not see the '<' icon on the far left

GIVEN that I am on gitcoin.co/grants/explorer/ 
WHEN the explorer search bar has a search term inside
THEN the search bar covers 2/3 of the page
AND does not cover up the Filter buttons
AND I do not see the '<' icon on the far left

GIVEN that I am on gitcoin.co/grants/explorer
WHEN I clear the search terms in the explorer search bar
THEN the search bar contracts to its original size

GIVEN that I am on gitcoin.co/grants/explorer
WHEN the X icon is showing in the explorer search bar
THEN I see the updated X icon

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
The svg icon is the standard icon from boostrap and we use all of it's other icon + form input 
Do we really want to override that ?

https://bootstrap-vue.org/docs/components/form-input


<img width="911" alt="image" src="https://user-images.githubusercontent.com/5358146/163945631-3cee01b2-4261-4d2a-a41a-21548a2a71b5.png">

**Comment by nfrgosselin** [comment]
Hey @thelostone-mc — found a couple issues on staging:

The explorer bar should stay expanded when there is an active search term inside — right now it's contracting:
![image](https://user-images.githubusercontent.com/15041635/165100467-f15f716f-c38c-4807-b734-506de723d4f0.png)

also the magnifying glass icon floats way off to the left when the bar expands:
![image](https://user-images.githubusercontent.com/15041635/165100565-0e0e042a-5c01-4154-b5eb-4baf47075f27.png)

Can you take a look?

**Comment by thelostone-mc** [comment]
Updated 🙌🏼

**Comment by nfrgosselin** [comment]
😬 @thelostone-mc I've cleared my cache and hard refreshed but I'm still not seeing the correct behavior. Staging has the old UX (search bar expands to cover filters), and prod has the broken ux I described before. Can you take another look?

**Comment by nfrgosselin** [comment]
looks good! thanks @thelostone-mc
