### ISSUE TITLE
Upgrade to the latest web3.py and dependencies

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1049]
We're currently using the `web3==4.0.0b10` beta release, while [`4.2.0`](http://web3py.readthedocs.io/en/stable/releases.html#v4-2-0) is available.
We should attempt upgrading this dependency and removing the pinned `eth-utils` entry from `base.txt`.
Special attention should be paid to all of our backend `sync_web3` related methods.

**Comment by eswarasai** [comment]
@mbeacom -- You might wanna also add `COLO` + `EthOS` redemption to that list :)
