### ISSUE TITLE
/slack page content view does not fill page width on mobile

### ISSUE THREAD

**Issue by cheneveld** [gitcoinco/web#105]
iPhone 5s Simulator: https://screencast.com/t/ryfWqaZSH

iPhone 8+ Simulator: https://screencast.com/t/o7TGfVgldb9

Smells like the robo image needs to be hidden and the content columns needs 12 cols

**Comment by owocki** [comment]
30a1ef1dee739302639a6a6b08f59e3986af361d should fix this.  thanks for the report!
