### ISSUE TITLE
Add twitter unfurl image to Django

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10506]
**User Story:**
As a Grants Ops user
I want to enable and manage the twitter unfurl image in Django
So that I can keep our marketing content up to date

**Acceptance Criteria**
GIVEN that I am in the Django backend
WHEN I look at the Marketing section
THEN I see a link for "Twitter Unfurl Image Configuration"

GIVEN that I am on the "Twitter Unfurl Image Configuration"
WHEN I click "upload new image"
THEN I see a box to add a new image

GIVEN that I am on the "Twitter Unfurl Image Configuration" and have added a new image
WHEN I click "save new Twitter Unfurl image"
THEN the new image is enabled as the Twitter Unfurl image
AND the old image is deleted

**Product & Design Links:**

**Tech Details:**
You can see where this lives in PR #10498 

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
someone had switched over staging. should be back up now

**Comment by nfrgosselin** [comment]
Looks good! FYI that I added a follow-on story for showing the object name in the list: #10563
