### ISSUE TITLE
Contribution CSV not delivering

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10500]
**Overview**
User ricmoo is having issues exporting his transactions from the Contributions tab on his grant. 

**Steps To Reproduce**
1. Impersonate user [ricmoo](https://gitcoin.co/_administrationdashboard/profile/4907/change/?_changelist_filters=q%3Dricmoo)
2. Go to his grant [ethers.js](https://gitcoin.co/grants/13/ethersjs-complete-simple-and-tiny)
3. Scroll to "Activity" section, toggle to "Contributions" tab
4. Click "Export Transactions (OWNER ONLY)"

**Observed  behavior**
User sees the pop-up to expect an email, but then the email with the file never comes

**Expected behavior**
User sees the pop-up and an email is delivered a short time later

**Screenshots**

**Additional context**
The user's suggestion is that there are too many transactions and it's timing out

**Comment by thelostone-mc** [comment]
This didn't require a fix. The user did end up getting the email and @gravityblast verified this
