### ISSUE TITLE
Gas estimate errors during claim

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10511]
**Overview**
User [alexandruioanvoda](https://gitcoin.co/profile/alexandruioanvoda) is having an issue claiming his matching funds with Metamask. He's seeing an error that Metamask can't estimate gas —> when I try to reproduce it I see a very high gas fee (screenshots of both below)

**Steps To Reproduce**
1. Impersonate [alexandruioanvoda](https://gitcoin.co/profile/alexandruioanvoda)
2. Go to his [grant](https://gitcoin.co/grants/5042/cat-longevity-diagnostics) 
3. On grant detail page, click to claim funds
4. On claim page, click on Claim button
5. See Metamask error

**Observed  behavior**
Either Metamask is unable to estimate gas or gas is extremely high

**Expected behavior**
Metamask should show reasonable gas fees

**Screenshots**
*Can't estimate gas fee*
![image](https://user-images.githubusercontent.com/15041635/164245437-c284ec2d-22fd-4373-8199-0d32199c3239.png)

*High Gas fee*
![image](https://user-images.githubusercontent.com/15041635/164244929-c04b82c3-86f8-4bb8-b498-8a5e634c463e.png)

**Comment by thelostone-mc** [comment]
This is not an error on the code.
You can find steps on when this happens :
https://discord.com/channels/562828676480237578/966320211303219310/966339468636323892

and how to fix this :
https://discord.com/channels/562828676480237578/966320211303219310/966597044636635167
