### ISSUE TITLE
Incorrect claim emails for GR13

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10512]
**Overview**
There seem to be two (possibly related) issues with the claim emails that went for the DAI contract:

1. Some users saw incorrect clawback dates and copy on the GR13 email (March 1 instead of June 30 - see screenshot). Correct email format can be [seen here](https://stage.gitcoin.co/_administration/email/clr_match_claim)
2. Some users received calls to KYC with claim amounts well below the $5k threshold (see screenshot). These grants are also marked as "ready for payout" in admin

**Users who saw KYC email incorrectly**
https://gitcoin.co/grants/5119/manyverse
https://gitcoin.co/grants/4573/datalatte
https://gitcoin.co/grants/5205/uniswap-v3-calculator-simulator
https://gitcoin.co/grants/5009/change-lives-and-transform-the-system
https://gitcoin.co/grants/5164/enstools
https://gitcoin.co/grants/5400/defold

**Screenshots**
_Incorrect KYC_
![image](https://user-images.githubusercontent.com/15041635/164247616-3b44c5fc-ac10-4ce5-9393-5832544a745b.png)
![image](https://user-images.githubusercontent.com/15041635/164247671-7ed5a6de-9cbf-4229-8d25-e41ac6062c98.png)

_Incorrect dates/copy_
![image](https://user-images.githubusercontent.com/15041635/164247753-e41a0681-ef5a-4fdb-8e73-8a0b70eb3013.png)

**Comment by thelostone-mc** [comment]
I don't belive there is anything left to do here! Might be worth syncing up with @nfrgosselin before looking into this @chibie

**Comment by thelostone-mc** [comment]
more context: https://discord.com/channels/562828676480237578/956258102263578684/966350407481831524

**Comment by thelostone-mc** [comment]
synced up with @schultztimothy and he had the same conclusion that the emails were triggered without having the latest code present on the server. Closing this out as this requires no code changes
