### ISSUE TITLE
as a user, i want to be able to save my avatar to be my twitter and github profiles

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1052]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to be able to save my avatar to be my gitcoin profile

follow up to https://github.com/gitcoinco/web/issues/813 and as a user, i want to be able to save my avatar to be my twitter / github profile

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so that users can save their avatar to their profiles and show off their bad selves (and market gitcoin)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Introduce new backend python methods to:
  - [x] Output avatar SVG as PNG
  - [ ] Impose the Gitcoin watermark (asset provided) on any given svg or png asset
  - [ ] Request permissions from Twitter as the current user that allows us to update their profile picture with the avatar PNG
  - [ ] Upload PNG avatar asset directly from s3 storage backend to twitter
  - [ ] View to download the avatar png and provide instructions on manually updating the Github profile picture
- avatar is generated, with a watermark that says 'gitcoin' along the bottom, 
- avatar can be easily saved as a twitter/github profile picture (ideally in /settings, but if no API is available to do this.. then perhaps with instructions to save the image and upload it to those networks)

**Comment by owocki** [comment]
@pixelantdesign any objetions if i bounty this?

**Comment by PixelantDesign** [comment]
Sounds good. Is this a build task?

I have a watermarked avatar that I was testing, do you think we need Made with Gitcoin on it?

**Option 1**
![alisa_icons](https://user-images.githubusercontent.com/238235/41985600-a1c9be7a-79e8-11e8-9771-2f212d32a46e.png)

**Option 2**
![alisa_icon](https://user-images.githubusercontent.com/238235/41985610-aaf65e72-79e8-11e8-82ed-e15cf4b045af.png)

**Option 3**
<img width="467" alt="screen shot 2018-06-27 at 9 07 09 am" src="https://user-images.githubusercontent.com/238235/41985936-871f2d52-79e9-11e8-98a1-bd75d0707ba0.png">

**Option 4**
<img width="466" alt="screen shot 2018-06-27 at 9 09 12 am" src="https://user-images.githubusercontent.com/238235/41986036-d39184f0-79e9-11e8-80ed-36cfee3f34bf.png">

**Option 5**
<img width="466" alt="screen shot 2018-06-27 at 9 09 12 am" src="https://user-images.githubusercontent.com/238235/41986052-e0400776-79e9-11e8-9a1f-003c8d23f166.png">

**Comment by nemaniarjun** [comment]
Came here to file this issue! @PixelantDesign I, for one would love the larger avatars. :grin:

**Comment by nemaniarjun** [comment]
Also, I feel it would be better UX if the user is taken to his profile page on clicking the avatar on the top right.

**Comment by owocki** [comment]
@PixelantDesign  i like option 3

> Came here to file this issue! @PixelantDesign I, for one would love the larger avatars. 😁

@mbeacom would it be easy to reequest diff size avatars from the system so @nemaniarjun can get a bigger avatar upon request?

**Comment by mbeacom** [comment]
We can modify the view for that, yes. Ideally, we should migrate to the dynamic BE using templates before moving onto the other avatar issues.

In regards to bountying this... I'm fine with that.  However, I made adjustments to the original spec details for this issue due to technical requirements and restrictions:

- It will require building out authentication flows with Twitter
- GH doesn't support uploading avatars outside of their UI

**Comment by kuhnchris** [comment]
The bulk of this implementation is live - closing this ticket.
