### ISSUE TITLE
Update checkout page copy

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10532]
**User Story:**
As a grant donor
I want to see clearer directions on the checkout page
So that I know how to checkout successfully

**Acceptance Criteria**
GIVEN that I am on https://gitcoin.co/grants/cart
WHEN I look under the "I'm Ready to Checkout" button
THEN I do not see the "save % on gas fees..." section

GIVEN that I am on https://gitcoin.co/grants/cart and have clicked to checkout
WHEN I see the "waiting for transaction" modal
THEN I see a new modal headline: "Don’t close this tab!”
AND I see a new modal subhead: "Please keep this tab open until your transaction is recorded. This allows us to take your contribution into account for each grant’s matching funds.”

GIVEN that I am on gitcoin.co and have successfully donated
WHEN I see the "Thank you for contributing" modal
THEN I see the "Share on Twitter" section directly below the headline and above the "You've successfully contributed..." section

**Product & Design Links:**
Screenshots of the existing flow for reference:

Save % section
![image](https://user-images.githubusercontent.com/15041635/165117401-fbb14b37-327a-4271-bbb2-2ae36758b3b8.png)

Waiting for transaction modal
![image](https://user-images.githubusercontent.com/15041635/165118351-21a83e52-5209-41a9-b793-695f9a0d9edc.png)

Thank you modal
![image](https://user-images.githubusercontent.com/15041635/165117949-bbe6fa18-70e3-43e4-a680-c3893aa3022d.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
@thelostone-mc I think something's up with staging — I'm not seeing the updates. Can you take a look?

**save % section**
When I first got to this page I didn't see it, but now I'm seeing it after refreshes
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/15041635/166990996-3744feee-ae86-4bb7-a943-58e7dde4d66f.png">

**wait modal**
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/15041635/166991290-c94dd320-1529-43e0-b880-64a6feb4727d.png">

**Comment by thelostone-mc** [comment]
Looks like staging wasn't updated. Could you check again
![image](https://user-images.githubusercontent.com/5358146/167576617-cc8f7974-d608-40dc-af9c-1ccd910fdf94.png)

**Comment by nfrgosselin** [comment]
LGTM!
