### ISSUE TITLE
as a user, i want the ability to generate a random avatar, so i can generate random avatars to get inspiration

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1053]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want the ability to generate a random avatar, so i can generate random avatars to get inspiration

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
avatar must be built manually

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
there is an 'random avatar' button on the avatar builder which when clicks will generete a random avatar.

**Comment by CuriousLearner** [comment]
Let me know when there is more info on this :)

**Comment by owocki** [comment]
@CuriousLearner what more do you want to know

**Comment by thelostone-mc** [comment]
@mbeacom the avatar backend is still being wired up right ?

**Comment by owocki** [comment]
@Smona @CuriousLearner the avatar builder is in prod.  still interested in this ticket?
