### ISSUE TITLE
Enable Web3Modal on Polygon Checkout

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10530]
**User Story:**
As a grant donor
I want to checkout on Polygon with wallets other than Metamask
So that I am not tied to using one wallet

**Acceptance Criteria**
GIVEN that I am on /grants/cart AND have Polygon-eligible grants in my cart AND do not have a wallet connected
WHEN I click "Polygon checkout"
THEN I see the Web3Modal to select a wallet

GIVEN that I am on /grants/cart AND have Polygon-eligible grants in my cart AND have a Web3Modal-eligible wallet connected
WHEN I click "Polygon checkout"
THEN I am able to checkout 

**Product & Design Links:**

**Tech Details:**
@chibie has documented the required steps for this [here](https://hackmd.io/JL4JN-r0TqW89khkc_Sgcw)

**Open Questions:**

**Notes/Assumptions:**
Follow-on story from #10482

**Comment by nfrgosselin** [comment]
@chibie I was able to test Coinbase end-to-end and the integration worked successfully.

However, when I tried to use Portis,Fortmatic, and Wallet connect I could go through the login flow fine, then I would get this error:
![image](https://user-images.githubusercontent.com/15041635/167261170-852dd4cd-cd4f-4812-8c32-26911430c790.png)

Any ideas?

**Comment by chibie** [comment]
@nfrgosselin Coinbase changes aren't in this PR but here WIP here -> #10410. did you mean MetaMask?

for the other wallet types, were you on mainnet/rinkeby?

**Comment by chibie** [comment]
this pr fixes the bug -> https://github.com/gitcoinco/web/pull/10606
