### ISSUE TITLE
Validate Django wallet address updates

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10541]
**User Story:**
As a Gitcoin admin
I want wallet addresses that I update to be validated
So that I don't enter in a wallet address incorrectly

**Acceptance Criteria**
GIVEN that I am on https://gitcoin.co/_administrationgrants/grant/<grant_id_#>/change/
WHEN I change the grant's "Admin address" and click Save
THEN the system checks if the address is a valid checksum
AND autoconverts to a checksum address if it is not
OR throws an error if the address cannot be autoconverted (error text: "Admin address is not a valid checksum amount. Please review.")

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
@thelostone-mc This does the autoconversion successfully but if it's unable to be autoconverted it kicks to a 500 error —> is it possible to keep the admin on page and give them a friendlier message like in the acceptance criteria?

![image](https://user-images.githubusercontent.com/15041635/167260901-cb9c3bcc-d556-4892-a849-b140d922a9d3.png)

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/gitcoinco/web/pull/10604

**Comment by nfrgosselin** [comment]
LGTM!
