### ISSUE TITLE
as a user, i want different background images for my avatars, to give more variety

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1054]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want different background images for my avatars, to give more variety

non unicolor backgrounds (stripes, polka dots, etc)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
only unicolor backgrounds

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
non unicolor backgrounds (stripes, polka dots, etc)

**Comment by owocki** [comment]
@justpixel any intereset in this?  if not i will bounty it !

**Comment by justpixel** [comment]
@owocki Sure. Where can I find the the files with the illustrations?

**Comment by owocki** [comment]
@mbeacom are the backgrounds stored as svgs somewhere?  any guidelines for designers to use as they create new backgrounds?

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/1551

**Comment by mbeacom** [comment]
@owocki The backgrounds are currently only hex codes at the moment.  That's why I was thinking we were going to use a color picker versus a limited palette for those.

**Comment by kuhnchris** [comment]
Since we have running tickets now for these topics (at least there were quarter tickets) I'll close this one.
