### ISSUE TITLE
Delete Grants Explorer subhead

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10545]
**User Story:**
As a grant funder
I want to see clearer copy on the [Grant Explorer](https://gitcoin.co/grants/explorer/)
So that I know what my options are

**Acceptance Criteria**
GIVEN that I am on the Grant Explorer
WHEN I look at the heading
THEN I no longer see the “explore public goods projects for web3” subhead (see screenshot "delete this")

**Product & Design Links:**
delete this
<img width="324" alt="image" src="https://user-images.githubusercontent.com/15041635/167264920-1f3436a7-294b-4bb1-9b6a-16de46d82c61.png">

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
That banner is an image which can be updated via Grant Brand Routing Policy in django admin.
The design team should be able to update the image via [django admin ](https://gitcoin.co/_administrationgrants/grantbrandingroutingpolicy/1/)
