### ISSUE TITLE
Misalignment with arrows on new page

### ISSUE THREAD

**Issue by danieljoonlee** [gitcoinco/web#1056]
### Description
*bug*: Arrow misalignment on Experience level and Project length

### Current Behavior
See image below

### Expected Behavior
Aligned arrows

### Reproduction
https://gitcoin.co/new

<img width="430" alt="screen shot 2018-05-02 at 8 33 48 am" src="https://user-images.githubusercontent.com/13317855/39533452-f1dbcd4e-4de3-11e8-9e42-1a28fa173614.png">

**Comment by thelostone-mc** [comment]
Derp! Thanks for pointing this out @danieljoonlee ^_^
