### ISSUE TITLE
"indicateMetamaskPopup is not defined"

### ISSUE THREAD

**Issue by miguelmota** [gitcoinco/web#10573]
**Overview**

The checkout is not working. I get the error `indicateMetamaskPopup is not defined` even though my metamask wallet is connected and on the right network.

**Steps To Reproduce**
1. Go to cart
2. Click on "I'm Ready to Checkout"
3. Click on "Polygon Checkout"
4. See error banner

**Observed  behavior**
Can't send checkout tx

**Expected behavior**
Checkout and send tx without error

**Screenshots**

![Peek 2022-05-04 16-33](https://user-images.githubusercontent.com/168240/166841795-b659690a-1e3e-4fa4-b923-866687e05826.gif)

**Comment by nfrgosselin** [comment]
Hey @miguelmota — thanks for letting us know! I've tried this on my end but I haven't been able to recreate it. Are you still having this issue?

**Comment by miguelmota** [comment]
@nfrgosselin seems to work now. Thanks!

**Comment by nol13** [comment]
am getting this as well

**Comment by dab036** [comment]
> am getting this as well

me as well, how can we fix this?

**Comment by dab036** [comment]
oh i refreshed it and it's ok now
