### ISSUE TITLE
Incorrect follower counts on Collections explorer

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10584]
**Overview**
Some users are showing up on the Collections tab of the Grants Explorer with zeroed out stats, even though their profile page shows populated stats. 

**Steps To Reproduce**
1. Go to [Grants Explorer](https://gitcoin.co/grants/explorer/?page=1&limit=12&me=false&sort_option=weighted_shuffle&collection_id=false&network=mainnet&state=active&profile=false&round_num=0&customer_name=false&sub_round_slug=false&collections_page=1&grant_regions=&grant_types=&grant_tags=&tenants=&idle=true&featured=true&round_type=false&tab=collections)
2. Click on a user with all stats as zeroes
3. Click on the "people" tab of their profile
4. See actual stats for those counts

**Observed  behavior**
Users are showing zeroes in the collections explorer, but actual counts on their profile page

**Expected behavior**
The counts on the profile page should show up accurately on the collections explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/15041635/167138813-b576f4af-4411-4b71-a770-18642cd4b79c.png)
![image](https://user-images.githubusercontent.com/15041635/167138865-ff449220-1a41-4fe3-bfbc-ea18a7bed907.png)

![image](https://user-images.githubusercontent.com/15041635/167138898-282d156d-df7e-4032-829a-b74d1f23fe85.png)
![image](https://user-images.githubusercontent.com/15041635/167138917-3f63bd19-639c-42ba-8577-2220ccc393da.png)

**Comment by chibie** [comment]
this is cause the deploy note in the description in this PR https://github.com/gitcoinco/web/pull/10308 wasn't executed after deployment

cc: @thelostone-mc

**Comment by thelostone-mc** [comment]
Running it on screen on server 
[detached from 28823.pts-3.ip-172-31-23-200]
[detached from 29078.pts-3.ip-172-31-23-200]

**Comment by nfrgosselin** [comment]
LGTM
