### ISSUE TITLE
Delete copy on gitcoin.co/grants

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10646]
**Details**
Grants Ops wants to get rid of some unnecessary copy on gitcoin.co/grants —> please remove the text from the screenshot below

**Product & Design Links:**
![image](https://user-images.githubusercontent.com/15041635/171262218-29a6c1ec-2a7b-4d6c-a9ca-36b17468b920.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
That's actually not a simple text.
It does a countdown timer when 
- a round is about to start
- a round is about to end
- payout is about to start

removing that removes all that functionality

**Comment by nfrgosselin** [comment]
Just spoke with @thelostone-mc and we're okay to remove this functionality from this page.
