### ISSUE TITLE
Oakland tag not displaying correctly

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10649]
**Overview**
When a user selects the Oakland eligibility tag during grant creation, the UI displays the grant ID (59) instead of the grant name (*Oakland)

**Steps To Reproduce**
1. Go to step one of [grant creation](https://gitcoin.co/grants/new) 
2. Select the "*Oakland" tag
3. See error

**Observed  behavior**
The selected tag displays "59"

**Expected behavior**
The tag should display as "*Oakland"

**Screenshots**
<img width="567" alt="image" src="https://user-images.githubusercontent.com/15041635/171297752-d489f121-6d57-457b-a426-0fda28c2625f.png">

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by thelostone-mc** [comment]
The tag creator used some random character which was messing it up.
Recreating the tag fixed it.
No code change needed
<img width="793" alt="image" src="https://user-images.githubusercontent.com/5358146/171335875-066cd99b-9eb0-47d1-86f6-0bb97412a83b.png">
