### ISSUE TITLE
Local storage of explorer filter does not consistently load

### ISSUE THREAD

**Issue by joshmorel** [gitcoinco/web#1064]
### User Story

As a web bounty explorer using Chrome or Firefox, I want selected filters to persist *consistently* so that I can use my preferred searching method. 

### Why Is this Needed?

*Summary*: Local storage of explorer filter is not consistent.

### Description

*Type*: Bug

### Current Behavior

1. Select 3 options in NETWORK group
2. Refresh browser
3. Only 2 options selected

### Expected Behavior

The same options would persist between browser refresh in Chrome.

### Reproduction

1. In Chrome navigate to https://gitcoin.co/explorer
2. Select 3 option within `NETWORK` group - `Ropsten`, `Rinkeby`, `Mainnet`
3. Refresh browser (hold `SHIFT` if necessary to bypass cache) 
4. Inspect `NETWORK` group - only `Ropsten` and `Mainnet` are selected

### Solution
*Summary*: TBD - willing to take a look

### Definition of Done

Selected filters = loaded filters

**Comment by joshmorel** [comment]
Just an update looking into this more for all the different filters:

* Status (Radio): This is the only one that works as expected
* Experience Level, Project Length, Type, Network: Only once option is kept in localStorage, when refreshing however, sometimes two are selected
* Tech Stack: Multiple comma-delimited options are kept in localStorage, but on refresh the selected options are not populated

**Comment by thelostone-mc** [comment]
@joshmorel Ah thanks for pointing that out! ^_^
Can't believe we didn't see that ! -.-
