### ISSUE TITLE
Share Cart + I just donated links broken

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10669]
**Overview**
The link you're prompted to post on twitter after donating takes you to a profile setup page (if you're logged in) and if you're not logged in it takes you to a blank white page. 

**Steps To Reproduce**
For [example](https://gitcoin.co/grants/cart/bulk-add/5688;0.0006;3,5288;0.0006;3,5051;0.0006;3,5007;0.0006;3,4874;0.0006;3,3591;0.0006;3,1620;0.0006;3,:izzahgitcoin) 

You can [search on twitter](https://mobile.twitter.com/search?q=I%20just%20funded%20grants%20on%20%40gitcoin%20&src=typed_query&f=live) and try plenty of people's links, always the same bug

**Screenshots**
<img width="525" alt="image" src="https://user-images.githubusercontent.com/15041635/172855481-bc876512-c030-40f5-b656-f4259e630917.png">

**Comment by thelostone-mc** [comment]
Looks like this has been fixed and rolled out in production.Closing this out
