### ISSUE TITLE
Celo contribution tracking

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10664]
**Overview**
Celo contributions are being recorded incorrectly.

Connor entered 3 transactions via our checkout (2 were false, 1 was real) and all were recorded as Failed on the contribution feed (see screenshot) and in [Metabase](https://metabase.gitcoin.co/question/1194). The donation for .001 CELO is showing up as successful on the [block explorer though](https://explorer.celo.org/tx/0xa6e27473e3a200fbef5faa6d13855490c683e3d516ba70d25a9d60df2a7b37db/token-transfers). 

**Screenshots**
![image](https://user-images.githubusercontent.com/15041635/172660265-83779a75-7b48-490f-a289-df80454b44b7.png)

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by thelostone-mc** [comment]
Fixed via ae21b06b9b30f26684370ff6496577d45ea6cfd0
