### ISSUE TITLE
'Stop Work' button appears on someone else's work.

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#1067]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user (not issue funder), I should not be able to see the 'Stop Work' button on someone else's work.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
1. Go to Issue Explorer
2. Click on any 'Work Started' issue by anyone other than yourself
3. 'Stop Work' button appears on the Activity Feed

![screenshot 2018-05-04 20 51 20](https://user-images.githubusercontent.com/19514207/39628873-fbee1e18-4fdc-11e8-9c67-6b885491727f.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
The button should not appear at all since it might cause some confusion.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
• Might be related: https://github.com/gitcoinco/web/pull/675
• Clicking 'Stop Work' resulted in an error, but I guess it would be better if it doesn't show up to anyone other than the issue funder.

**Comment by TimVanMourik** [comment]
Maybe you just found back my 'Stop Work' button! I just wanted to start an issue that I get an error when I try to stop someone's work because of a week long inactivity:
![untitled](https://user-images.githubusercontent.com/6152205/39637066-45c10c0a-4fc2-11e8-939c-d5114483ef90.png)

I suspect underlying faulty behaviour is related.

**Comment by owocki** [comment]
thanks for the bug report @TimVanMourik -- thisi s fixed now!
