### ISSUE TITLE
Posting to contributors not working

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10683]
**Overview**
User [Jaazinn](https://gitcoin.co/jaazinn) is receiving an error when trying to message contributors to [his grant](https://gitcoin.co/grants/4268/zkrollupsxyz) via the cGrants form (see screenshots)

**Screenshots**
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/15041635/174192087-ffa08b11-dc34-4315-9959-2ad3937d8b4e.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/15041635/174192104-31d72463-82bb-4334-80af-8e4a0160b1f0.png">

**Comment by thelostone-mc** [comment]
This is not a bug in the platform but instead in the bsci script which has marked the user as [sybil](https://gitcoin.co/_administrationtownsquare/squelchprofile/18823/change/?_changelist_filters=q%3Djaazinn)
Would recommend reaching out to FDD team to figure out how to deal with this in the future.

i turned the squelch inactive

**Comment by nfrgosselin** [comment]
Good catch, thanks @thelostone-mc !
