### ISSUE TITLE
Transfer of Grant Ownership to Founder

### ISSUE THREAD

**Issue by StellarisMeta** [gitcoinco/web#10700]
Hello, I'm the current lead creative for this grant: https://gitcoin.co/grants/6225/the-tabletop-rpg-project-ai-dd-assistant.

I would like to transfer the ownership of our grant to one of our co-founders, as they are our public leader figures with their public GitHub portfolios. I would like to transfer ownership to https://gitcoin.co/lishaan.

Thank you.

**Comment by nfrgosselin** [comment]
This has been addressed — closing out
