### ISSUE TITLE
Turn off Product Feedback Emails

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10723]
**User Story:**
As Gitcoin
I want to have the product request feedback forms
So that i am not misleading our users

**Acceptance Criteria**
GIVEN gitcoin.co is up and running
THEN i do not want the following email to send:
hi @sichen1234,

kyle, frank, and alisa from Gitcoin here — i see you haven't funded an issue in a few months.

in the spirit of making Gitcoin better + checking in:

> do you have any issues which might be bounty worthy or projects you're hoping to build?

> do you have any feedback for us on how we might improve the product to fit your needs?

> are you interested in hosting or partnering in one of our upcoming hackathons? this is often teh best way to get top talent working on your issues.

appreciate you being a part of the community + if you are intersted, you can use discount code product-feedback-is-a-gift for 50% off your order :slight_smile:

~ kyle, frank & alisa (gitcoin product team)

**Notes/Assumptions:**

**Comment by nutrina** [comment]
Cronjob has been disable on gitcoin3.
