### ISSUE TITLE
Create runbook for Owocki's fix

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10738]
**Overview:**
[Owocki outlined a fix](https://discord.com/channels/562828676480237578/990199901633789962) for changing celery worker's jobs immediately instead of having to go through Redis. We want to create a runbook for that fix so we can use it if the queues get out of hand again. 

**XD Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by kevinrolsen** [comment]
This was actually made into a PR, and an ENV Variable can be set to drain the queues.
