### ISSUE TITLE
Change lifetime funding to estimate on explorer page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10752]
**User Story:**
As a grantee
I want to display an estimated lifetime funding amount (instead of an "exact" number)
So that contributors know how to contextualize the number

**Acceptance Criteria**
GIVEN that I am on the Grant Explorer
WHEN I look at the dollars raised on a grant's card
THEN the "total raised" copy is replaced with "Estimated total raised"

GIVEN that I am on the Grant Explorer and looking at a specific grant card
WHEN the grant has earned <$1,000
THEN the number displayed is "<$1,000"

GIVEN that I am on the Grant Explorer and looking at a specific grant card
WHEN the grant has earned >$1,000
THEN the display reads "~$N", where N is the amount rounded to the nearest thousand (instead of an exact dollar amount)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
This is on quick view from what i understand so working on #10751 automatically fixes this as they share the same code

**Comment by lthrift** [comment]
This is not implemented correctly per my comment on #10751

**Comment by thelostone-mc** [comment]
fixed via cc3256a26

**Comment by kevinrolsen** [comment]
![Image](https://user-images.githubusercontent.com/62433459/187916910-23d94347-25da-4078-bd84-9db310b924eb.png)

@thelostone-mc this is still up on production.gitcoin.co origin/master 94ec92248d112ae9a7ae6f1cb98dfe2643c29f11 2 hours ago

**Comment by kevinrolsen** [comment]
Please add commas to values > $1000

![Image](https://user-images.githubusercontent.com/62433459/188428847-bf386af4-d069-48e7-9c9a-88bb7530f900.png)

**Comment by kevinrolsen** [comment]
merged and deployed to production.gitcoin.co
