### ISSUE TITLE
Change lifetime funding to estimate on grants detail page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10751]
**User Story:**
As a grantee
I want to display an estimated lifetime funding amount (instead of an "exact" number)
So that contributors know how to contextualize the number

**Acceptance Criteria**
GIVEN that I am on the grant details page
WHEN I look at copy in the lifetime funding section
THEN I see a revised heading that reads "Estimated lifetime funding received"
AND the "raised from all contributors" is replaced by "This number should not be used for accounting purposes."

GIVEN that I am on the grant details page
WHEN the grant has earned >$1,000
THEN the display reads "~$N", where N is the amount rounded to the nearest thousand (instead of an exact dollar amount)

GIVEN that I am on the grant details page
WHEN the grant has earned <$1,000
THEN the page displays "Less than $1,000"

**Product & Design Links:**
Grant detail page with Lifetime Funding Section included for reference
![image](https://user-images.githubusercontent.com/15041635/184173912-24d558a9-83ec-49d3-80a8-9b056b808670.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by lthrift** [comment]
@nfrgosselin I didn't have a way to test the rounding elements of this A/C in staging. Accepting it for deployment and then we can spot check in production following.

**Comment by lthrift** [comment]
@thelostone-mc this seems to already be in production so I did the spot check. 

This acceptance criteria has not been implemented correctly:

GIVEN that I am on the grant details page
WHEN the grant has earned <$1,000
THEN the page displays "Less than $1,000"



![Image](https://user-images.githubusercontent.com/92401444/186536802-98098c02-50d0-44b4-99d3-d4170cfdda0b.png)

**Comment by thelostone-mc** [comment]
@lthrift fixed via cc3256a26

**Comment by nfrgosselin** [comment]
LGTM
