### ISSUE TITLE
Cart not loading / Polygon / IBAN error

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/web#10772]
Discord thread tracking issue: https://discord.com/channels/562828676480237578/1009744067887902772

Notion doc on review environments: https://www.notion.so/gitcoin/Review-Environment-How-to-453e1b62e2cb41a186707b1dee5cac54#5df740d7ce07459a8112b75bfcbc6515

**Comment by thelostone-mc** [comment]
Closed via #10776
