### ISSUE TITLE
Unable to claim matching funds

### ISSUE THREAD

**Issue by lthrift** [gitcoinco/web#10792]
Customer support issue: https://discord.com/channels/562828676480237578/1012610617242304572

grantee who keeps getting error when he clicked the claim button. Can someone help? He tried clearing caches and other browser, nothing works - he didnt arrive at the stage where he needs to connect wallet
Username: https://gitcoin.co/brian-lc
Grant: https://gitcoin.co/grants/5613/zk-locale-privacy-preserving-proof-of-presence

Screen recording of issue: https://drive.google.com/file/d/1qUpG7gyC1kIh1_PNVEGMh1j74QFeupLs/view

**Comment by kevinrolsen** [comment]
We think this is related to the web3.js / metamask issue.

**Comment by thelostone-mc** [comment]
@lthrift 
I've tried claiming on his behalf and it seems to go through fine without any issue.
Like @kevinrolsen mentioned -> this has been fixed already  🙌 

**On Chrome**

![Image](https://user-images.githubusercontent.com/5358146/187873819-bf7efdc3-337e-4121-8fd7-e8da03c496ce.gif)

**On Browser**

![Image](https://user-images.githubusercontent.com/5358146/187874367-5264c82d-f617-46cd-8d7b-c3a255aff94e.gif)
