### ISSUE TITLE
Can I change the owner of my gitcoin grant to a new user?

### ISSUE THREAD

**Issue by fswami** [gitcoinco/web#10819]
I need to change the owner of the grant I created from @fswami to @swamifantastic.

The grant in question: https://gitcoin.co/grants/6145/support-me-in-developing-an-iconic-composable-vil

I made the mistake of using personal accounts and wallets, instead of setting up separate business accounts for Swami Fantastic Ltd, and this has made receiving money alongside my salary quite complex. My accountant advises the accounts are set up properly for the next round since I am not personally working on it - Swami Fantastic Ltd is.

Thanks,
Fswami

**Comment by nfrgosselin** [comment]
Closing per direction from Support
