### ISSUE TITLE
Delete emails being sent from product@gitcoin.co by cplatform

### ISSUE THREAD

**Issue by lthrift** [gitcoinco/web#10813]

**Comment by lthrift** [comment]
We have multiple emails being sent from cplatform on behalf of product@gitcoin.co that have been shutdown multiple times and are back again. These need to be completely retired. 

For context to whomever picks this up - Gerald has worked on this previously.

![Image](https://user-images.githubusercontent.com/92401444/188021516-072a578f-2a61-4bed-819f-1e3283619b31.png)



![Image](https://user-images.githubusercontent.com/92401444/188021281-dab094e9-d04e-4d5a-8291-571f4a51b74b.png)

**Comment by kevinrolsen** [comment]
merged and deployed to production.gitcoin.co
