### ISSUE TITLE
Changing Grant Owner

### ISSUE THREAD

**Issue by garysheng** [gitcoinco/web#10824]
I would like to change the ownership of my Gitcoin grant, Dream DAO: https://gitcoin.co/grants/3816/the-dream-dao-by-civics-unplugged.

In the Discord, I was directed to this email to fulfill my request.

My Github is garysheng and the new owner is madisunadams.

REASON: I am no longer in a role managing this grant, the new owner is.

**Comment by nfrgosselin** [comment]
Closing per support
