### ISSUE TITLE
Grant missing from "Eligibility Status List"

### ISSUE THREAD

**Issue by ghost** [gitcoinco/web#10823]
Who: info@btheory.ventures

What: "Underground DAO" 7490 is not appearing in the grant eligibility status list. 

Why: I'm not sure.

**Comment by anansiy** [comment]
Look me

**Comment by YukiPL** [comment]
Hi there, 
Thank you for getting in touch. Can you please submit the tag request using this [form](https://docs.google.com/forms/d/e/1FAIpQLSeiaaPaYC2HkTvM_uXhlCeKSBVXX382rH4bEMDlyVynLCAeug/viewform)? Our team will review them. 
For future support, kindly send an email to [support@gitcoin.co](mailto:support@gitcoin.co) or create a ticket in our Discord channel. Our knowledge base support.gitcoin.co is also equipped with sufficient information, which we recommend you to read first before dropping us a line.
Thank you and all the best.
Yuki
