### ISSUE TITLE
update image directions on application page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#10826]
**Acceptance Criteria**
On step 2 of the grant creation flow (screenshot below), update copy to:
1. say "Project Banner" instead of "Project logo"
2. list recommended dimensions as 905 X 290

**Product & Design Links:**
![image](https://user-images.githubusercontent.com/15041635/188673837-4d443061-ab58-4f7c-852b-d2d3c7e05f16.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by prsndp** [comment]
Hi @nfrgosselin , Hope you're doing well. Could I take this issue? I would like to work on it.
