### ISSUE TITLE
Change Weekly Update Roundup Email from a Manual to a Scheduled Automatic Process

### ISSUE THREAD

**Issue by mkosowsk** [gitcoinco/web#1083]
### User Story

**As a** reader of Gitcoin weekly roundup emails
**I want to** have the emails comes at a regularly scheduled time before the Livestream time
**So that I** can plan to attend the livestream or not ahead of time 👍🏻

### Why Is this Needed?

I received the last weekly roundup email at 8:57 PM UTC which said that there was going to be no Gitcoin Livestream that week (scheduled weekly for 9:00 PM UTC). This was pretty short notice and as you can imagine my hopes and dreams were crushed 😢

Another perspective is that an automatic process will take a bit of work off the Gitcoin core team's plate, which is also nice.

### Current Behavior

Gitcoin weekly roundup emails are sent via a manual process.

### Solution

Automate the process and send the weekly roundup emails at the same time every week. Believe Gitcoin uses Sendgrid and that change should be relatively straightforward via https://sendgrid.com/docs/Classroom/Send/When_Emails_Are_Sent/how_can_i_schedule_emails_to_send_at_specific_times.html 

I think Mondays are a good option, gives time to have a post mortem for the previous week and also have people plan for stuff in the upcoming week. Could poll the community on this but not sure if it's warranted.

### Definition of Done

Weekly roundup emails are sent automatically at the same time every week to the Gitcoin community 😀

**Comment by kuhnchris** [comment]
@PixelantDesign you mind following up on this?

**Comment by asphyx1a** [comment]
sorry, now i'm here
