### ISSUE TITLE
I saw my grant still be `inactive` when `APPROVED`

### ISSUE THREAD

**Issue by xiyu1984** [gitcoinco/web#10835]
### What
Here is my grant application: https://gitcoin.co/grants/7400/punstar
I found it has been `APPROVED`  
![1662523812766](https://user-images.githubusercontent.com/83746881/188786905-3bc9fc2f-3bda-41c2-aa38-2f5121f76b92.png)

But I find the `inactive` information is still there, is there any mistake I made?  
![1662523897359](https://user-images.githubusercontent.com/83746881/188787101-99906e25-5bbb-4d2a-af99-766c3677f9a5.png)

**Comment by YukiPL** [comment]
@xiyu1984 Thank you for getting in touch. I have notified the team about this. Your grant should be active within 24hrs. Please get back to us if it does not with the support channels below. 
For future support, kindly send an email to [support@gitcoin.co](mailto:support@gitcoin.co) or create a ticket in our Discord channel. Our knowledge base support.gitcoin.co is also equipped with sufficient information, which we recommend you to read first before dropping us a line.
Thank you and all the best.
Yuki
