### ISSUE TITLE
I don't now how to get my grant active - I don't get any feedback

### ISSUE THREAD

**Issue by Shoelace-Jim** [gitcoinco/web#10847]

**Comment by YukiPL** [comment]
@Shoelace-Jim Thank you for getting in touch. The review will usually take between 48-72hrs. As your grant was created less than 24hrs, please be patience while our review team get to your grant. 
For future support, kindly send an email to support@gitcoin.co or create a ticket in our Discord channel. Our knowledge base support.gitcoin.co is also equipped with sufficient information, which we recommend you to read first before dropping us a line. 
Thank you and all the best.
Yuki
