### ISSUE TITLE
Minimum contribution logic bug

### ISSUE THREAD

**Issue by lthrift** [gitcoinco/web#10853]
Cart logic should allow user to checkout with a 1DAI contribution but it currently throws an error. 

![Image](https://user-images.githubusercontent.com/92401444/189460322-7e98be7d-9456-4a14-bede-65cb4dd2e93a.png)

**Comment by kevinrolsen** [comment]
https://discord.com/channels/562828676480237578/1018497349120704562

**Comment by thelostone-mc** [comment]
This is already resolved !
It is due to the prices in DAI failing a bit short in comparision USD

https://gitcoin.co/sync/get_amount?denomination=DAI

![Image](https://user-images.githubusercontent.com/5358146/190952527-e1af8096-55ff-470e-83d7-55b5d854e6c9.png)
