### ISSUE TITLE
Changing Gitcoin owner for Gitcoin Round

### ISSUE THREAD

**Issue by crowdfundedcures** [gitcoinco/web#10855]
Hi there,

My colleague Nick Fiorenza (nick@crowdfundedcures.org) had recently submitted the following Gitcoin grant applications on behalf of our DeSci project Crowd Funded Cures in his name as I was having internet issues:

https://gitcoin.co/grants/7518/medical-impact-dao-to-govern-retroactive-funding-o

https://gitcoin.co/grants/7516/open-source-medical-prize-fund-for-retroactive-fu

We need to change the owner of these grants from Nick (https://gitcoin.co/nicktheninjax) to our official Gitcoin profile (https://gitcoin.co/crowdfundedcures) which has the following ETH wallet address: 0x1Ab75FEA1f27A6dfAfF81b0371AB6d57E112906B (aka pfs.eth). 

Please let me know if you require any additional information. 

Thanks,

Savva Kerdemelidis 
savva@crowdfundedcures.org

**Comment by YukiPL** [comment]
@crowdfundedcures Hi Savva, As mentioned in my previous email, we will need [nicktheninjax](https://gitcoin.co/profile/nicktheninjax) to create a Github issue and send the email. Any other issue created or email sent from another account, I'm afraid is not sufficient. 
Thank you for your understanding. 
Yuki
