### ISSUE TITLE
e-mail should be optional

### ISSUE THREAD

**Issue by satoshi101** [gitcoinco/web#1088]
### User Story

As a project funder I want to be able to fund an issue without giving away my e-mail.

### Why Is this Needed?

As you can see in the image below, highly likely this was a prior requirement - just not implemented correctly. I think it's reasonable to want to be able to fund a project without having to connect a github identity / ethereum account with a particular e-mail.
<img width="502" alt="screen shot 2018-05-06 at 10 10 09 pm" src="https://user-images.githubusercontent.com/39014517/39681822-78f11430-517a-11e8-9703-8d78e0540fb0.png">

### Description

Type: Bug

### Current Behavior
e-mail is required and displayed in the project page.

<img width="531" alt="screen shot 2018-05-06 at 10 14 31 pm" src="https://user-images.githubusercontent.com/39014517/39681914-e1416cf6-517a-11e8-8444-3b823ec854cd.png">

### Expected Behavior
e-mail should be really optional. No need for email sounds even better.

### Reproduction
Straightforward

### Solution

The javascript form should be changed to make the field optional. Server-side validation should be ok with that field missing. The same change should propagate to the API as well - for example:

```
curl https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/ethereum/go-ethereum/issues/16688
```

shouldn't contain the e-mail.

### Definition of Done

* One can fund a project without putting e-mail. The *fund new issue* form should submit successfully
* The 'Funder' segment of the issue page should look ok, when the e-mail is missing

**Comment by owocki** [comment]
one other direction we coudl perhaps go.. give the user the ability to enter their information, but keep it private to everyone except the person who has started work.

**Comment by owocki** [comment]
@PixelantDesign any objections if i code/bought this up here?

**Comment by satoshi101** [comment]
I think that it shouldn't give any weaker privacy than github. If I can do work on github under a pseudonym and it would never reveal my actual email + it would ensure all communication goes through it, I believe that gitcoin should give that option too. gitcoin takes the e-mail from github so it could facilitate behind the scenes messaging in the platform. But that would be a whole new epic :D The simplest thing would be - hey - you wan to chat, go to github.

**Comment by owocki** [comment]
PR is in https://github.com/gitcoinco/web/pull/1096

**Comment by owocki** [comment]
another PR https://github.com/gitcoinco/web/pull/1097

**Comment by PixelantDesign** [comment]
@owocki I think this should be fine.
