### ISSUE TITLE
Clawbacks Data Script

### ISSUE THREAD

**Issue by lthrift** [gitcoinco/web#10893]
**User Story:**
As a PGF Contributor
I want the on-chain claims data synced with the cgrants database
So that I can clawback unclaimed funds from prior to GR15

**Acceptance Criteria**
details from @thelostone-mc here: https://discord.com/channels/562828676480237578/1024350213609115711/1024562728427343932 

**XD Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by thelostone-mc** [comment]
commands to be run : 

```
./manage.py sync_clr_match_payouts -n="mainnet" -c "0x2878883dD4345C7b35c13FefC5096dd400814D91"
./manage.py sync_clr_match_payouts -n="mainnet" -c "0x22fDA1F97F2fD078F4609AaF74914ddf436de8e8"
./manage.py sync_clr_match_payouts -n="mainnet" -c "0x62a5A2E85619c0922B32243165B9BAAB27Bc7E63"
./manage.py sync_clr_match_payouts -n="mainnet" -c "0xeFc138E4e0Fdcd7C9E616cC3E5c356C3ce23B1f2"
./manage.py sync_clr_match_payouts -n="mainnet" -c "0xa640830aFAa6455E198eDa49E085C4C377789ddd"
```

**Comment by thelostone-mc** [comment]
Looks like the event log script isn't right !
Running those commands error out

Throwing in a commit to fix that

**Comment by thelostone-mc** [comment]
Looks like the event log script isn't right !
Running those commands error out

Throwing in a commit to fix that

**Comment by thelostone-mc** [comment]
This is now completed
