### ISSUE TITLE
Unable to use the Avatar from Github

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/web#10901]
**User Impacted:**
https://gitcoin.co/bp20200

**Observed Results:**
User is not able to use the avatar from github.. Tried to delete the base avatar in django and try a force override, but neither worked.

**Expected Result**
User is able to use the avatar from github and it updates accordingly

**Discord Thread:**
https://discord.com/channels/562828676480237578/1023878529647116338

**Comment by thelostone-mc** [comment]
From Yuki

> I usually will go to the Base Avatar and delete everything from the profile. Once that is done, it will pull the Avatar from github when I impersonate the profile. It works everytime. But not this time.

**Comment by nutrina** [comment]
This is done.
The issue was a delete request for this account, that was preventing the correct avatar from being shown.
