### ISSUE TITLE
Bug [You must be authenticated via github to use this feature! ] on Bounty apply action 

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#10925]
**Overview**

Unable to apply for bountys.
<img width="1440" alt="Screenshot 2022-10-17 at 18 31 33" src="https://user-images.githubusercontent.com/57037080/196244709-c21158bf-2a8c-43fd-9b56-9d7473c77b10.png">

**Steps To Reproduce**
Go to bounty page and try apply for any bounty you see Then this red notification on top will appear

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by Soptq** [comment]
I can reproduce this issue as well.

**Comment by tse-lao** [comment]
I had the same issue but it seems to be resolved for me. Please check @molecula451  @developerfred

**Comment by developerfred** [comment]
> I had the same issue but it seems to be resolved for me. Please check @molecula451  @developerfred 

I will check now.

**Comment by molecula451** [comment]
Yeah working

**Comment by developerfred** [comment]
@tse-lao  thanks for the information! bounty application is working properly. I'm going to close this issue is it ok @molecula451?

**Comment by developerfred** [comment]
Thanks @molecula451 @Soptq @tse-lao
