### ISSUE TITLE
twitter posts about new funded issues do not unfurl correctly

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#110]
what a new funded issue is posted, the system tweets about it.  they should unfurl like this 

http://bits.owocki.com/1Q0g0y2P2K22/Screen%20Shot%202017-12-13%20at%209.19.51%20AM.png

but instead look like this

http://bits.owocki.com/1y1Y2u0U1D3C/Screen%20Shot%202017-12-13%20at%209.19.01%20AM.png

i think it either has to do with
* tinyurl
* some race condition with the bounty being posted and not yet properly populating the twitter card info

**Comment by owocki** [comment]
hmm this one just unfurled correctly

https://twitter.com/GetGitcoin/status/940979551038881792

i think this is a race condition of some sort because of the inconsistent results

**Comment by ian-cawood** [comment]
@owocki Can I take a look at this?

**Comment by owocki** [comment]
be my guest :)
