### ISSUE TITLE
Make Image a Thumbnail for Long Descriptions

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1105]
Issue Explorer Detail View:

For long issue descriptions, make images a thumbnail that expands when clicked.

See this issue: https://gitcoin.co/issue/gitcoinco/web/1104/380

**Comment by PixelantDesign** [comment]
@thelostone-mc you're already working on this ya?

**Comment by thelostone-mc** [comment]
@PixelantDesign yup
