### ISSUE TITLE
The big "Supply / Demand" imbalance thread.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1119]
Gitcoin is a double sided market for ppl who have a supply of work to be done to be matched with talent.

For the last two months we've had more devs than supply work work.

That is changing due to some really great work that @vs77bb is doing.  It's possible that we will see the *total* amount of work available on the platform MORE THAN DOUBLE in the next month.  From 65k to 150k 

This is a thread about how we can scale the developer side of the market as we scale up the 'supply of work' side

**Comment by owocki** [comment]
without doing a ton of research, i think that the new issues get gobbled up quite quickly… its the ones that get kicked back to open from started that i htink we need to remarket better

**Comment by owocki** [comment]
cc @PixelantDesign @vs77bb @mbeacom for more ideas since you all know our product well :)

**Comment by mkosowsk** [comment]
Do we have metrics for when issues are kicked back from started back to open? Think it would be interesting to measure

0. How much time it took for the issue to be kicked back and how this relates to the timeline of the ticket
1. How many comments the Contributor made on the ticket
2. How many comments the Funder made on the ticket. Was there a lot of `ticket jitter` of the ticket changing in flight like scope creep?
3. Was there a WIP PR submitted?
4. Was there an Action Plan submitted?
5. When the Contributor asked a question, how long did the Funder take to respond?
6. When the Funder asked a question, how long did the Contributor take to respond?

It would probably be interesting to look at a period of time and do a post mortem on both successful and unsuccessful bounties to see if there are any contributing differences

**Comment by PixelantDesign** [comment]
I like *ticket jitter* and  @mkosowsk approach to trying to understand what happened through data. 

* its the ones that get kicked back to open from started that i htink we need to remarket better * 

How fast are they getting gobbled up?

When the issues get moved back to OPEN, we could surface them at the top of the issue explorer with a visual treatment to indicate that it's new/recent until someone clicks start on them (see mockup)? Another thing we could do is send a daily email of reopened issues at the end of the day?

@owocki 

![Screen Shot 2018-05-10 at 9.22.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f36b7191a371f110294f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de14d54ad133361e1772431.png)

**Comment by owocki** [comment]
> When the issues get moved back to OPEN, we could surface them at the top of the issue explorer with a visual treatment to indicate that it's new/recent until someone clicks start on them (see mockup)?

i LOVE this idea.

>  Another thing we could do is send a daily email of reopened issues at the end of the day?

note that the daily 'there are xxx new bounties' emails include previously opened bounties below the newly opened ones.  i wonder if we'd give ppl email fatigue if we emailed them twice in the day.

**Comment by owocki** [comment]
one convo i had with @vs77bb at edcon:

supply/demand imbalance is different for each market.  so we might have an oversupply of python devs and an undersupply of c# devs

i built two new admin dashboards to show us how many bounties/users with each skill are avaialble:

https://gitcoin.co/_administration/stats/?filter=KPI&format=chart&rollup=daily&filter=user_skills
https://gitcoin.co/_administration/stats/?filter=user_skills&format=chart&rollup=daily&filter=bounty_skills

**Comment by owocki** [comment]
> When the issues get moved back to OPEN, we could surface them at the top of the issue explorer with a visual treatment to indicate that it's new/recent until someone clicks start on them (see mockup)?

the only thing about this is we'd have to change the default sort on the /explorer page.  i think its worth rolling this into its own ticket
