### ISSUE TITLE
[Design]: 'Good First Issue' Aggregator

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1123]
_Needs Review_

### User Story

As an open source developer interested in blockchain, I want to know all the options I have to contribute to top blockchain projects

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: An aggregator of issues marked 'Good First Issue' / 'Help Wanted' across top blockchain projects (and potentially a search navigation feature so developers can easily search for projects they are interested in working towards). 

### Additional Information
This could be an input mechanism for Gitcoin Requests (#1033), where we can encourage bounty-hunters to state the price at which they'd be willing to work on the issues across projects.

**Comment by thelostone-mc** [comment]
>  An aggregator of issues marked 'Good First Issue' / 'Help Wanted' across top blockchain projects 

This would mean every project having it's own dedicated view ?  (which I believe we don't have )
If that were the case -> we would have to add the `Good First issue` along with the issue on the issue explorer (need to make sure we don't overload it with data )

**Comment by PixelantDesign** [comment]
Wouldn't the user go to the issue explorer? What would be the criteria of evaluating what a good first issue is?

**Comment by vs77bb** [comment]
The "why" behind this (potential) feature is that the Issue Explorer is valuable not only because it shows tasks where someone can get paid, it also shows an aggregation of issues 'good for external contribution' across a variety of repo's. 

If I'm an OSS software developer browsing projects, I don't have one view across Github from where I can see how many / what issues are tagged 'Good First Issue' / 'Help Wanted' across repo's. 

Perhaps Gitcoin can step in with this view. This could be a good feeder into Gitcoin Requests. Here is an example flow. 

1) Gitcoin Core Team populates Potential Contributions with the 'Good First Issues' across three repo's which **have not** yet been funded (ex. [Ethereum's geth](https://github.com/ethereum/go-ethereum), [ipfs](https://github.com/ipfs/ipfs), and [Casper FFG](https://github.com/ethereum/casper/)). A Github link form is also available should the user want to add another repo to the view.  

2) A user, Alice, sees this view and notices something on Casper FFG that looks interesting. Alice makes a 'Gitcoin Request' for the issue to be funded with .3 ETH. 

3) Another user, Bob, comes by and doesn't see anything interesting on Casper FFG, geth, and ipfs. The user clicks a 'See New Projects' button and the page refreshes, fetching 'Good First Issues' from other repo's Gitcoin Core has saved as 'good potential repos'. MetaMask pops up, and Bob finds something he wants to do for .2 ETH. He makes a Gitcoin Request. 

4) Charlie clicks 'See New Projects' 3 times but doesn't like what he sees. He uses the Github Link searchbar to add a project he likes, jsbin, to see what 'Good First Issue' / 'Help Wanted' issues they have across their repositories. The aggregator brings back 34 issues across jsbin repo's and he's excited to check them out. 

I see @thelostone-mc's point about being careful not to overload with data.... curious if the color above helps or hurts the case for this 😄

**Comment by PixelantDesign** [comment]
It sounds like you want to be able to search by 'Good First Issue/Help Wanted' across specific repos (which ever a contributor is interested in), correct?

Seems like the need is a more robust search feature?

'Good First Issue' are terms that we use and know internally. I'm not sure if users will know to search by such specific words in order to surface what you're trying to achieve. Does this also have to do with beginner/intermediate level of work? Something that introduces a new contributor to the OSS project they're interested in?

@vs77bb

**Comment by vs77bb** [comment]
Closing as @jschiarizzi showed us a Github native feature that does this 🙂
