### ISSUE TITLE
Abstract Away Gas Price / Gas Limit

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1124]
child of #1131

_Needs Review_ 

### User Story

As a Gitcoin funder / developer, I don't want to think about gas price and gas limit at all, I just want my transaction to process.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Abstracting away gas price / gas limit is an easier on-ramp for people who may be new getting into blockchain and is generally a more elegant solution.

### Actual behavior
[comment]: # (Describe what actually happened.)
Gas Price / Gas Limit is shown on screens where developers / funders need to interact with Ethereum's bockchain. 

![screen shot 2018-05-09 at 10 49 45 pm](https://user-images.githubusercontent.com/23297747/39851224-5657c51e-53db-11e8-9d3f-1573ddb6e80f.png)
### Expected behavior
[comment]: # (Describe what you expected to happen.)
See great example from Balance below.

![screen shot 2018-05-09 at 10 47 55 pm](https://user-images.githubusercontent.com/23297747/39851270-8b790f64-53db-11e8-937a-1895d0305feb.png)

**Comment by mkosowsk** [comment]
Megalike this!!! 😍
