### ISSUE TITLE
Move Gitcoinbot Snooze Actions Out of Activity Feed

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1144]
https://d3vv6lp55qjaqc.cloudfront.net/items/1r2P2M0E2C1Y3o2p3O2D/Screen%20Shot%202018-05-08%20at%206.00.11%20PM.png

**Comment by kuhnchris** [comment]
Where exactly do you want to put it then?

**Comment by asphyx1a** [comment]
I think you know better
