### ISSUE TITLE
[Design] Post-Bounty Completion Flow [Funder]

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1152]
_Needs Review (@PixelantDesign)_

### User Story

[comment]: # As a funder, I want to have a method to provide feedback on my experience so that Gitcoin's platform can improve and I can provide feedback (and potentially **tips** to Gitcoin developers.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: An improvement upon the e-mail from @owocki which a) solicits feedback and b) provides an option for post-bounty tipping (an incentive technique to bring into the flow).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # Email from @owocki 

### Expected Behavior
[comment]: # In-line email from Gitcoin

### Additional Information
Child of #1136

**Comment by mbeacom** [comment]
We can add a poll or survey following bounty completion via Hotjar to address this if we're so inclined.

**Comment by PixelantDesign** [comment]
yes! a survey would be great! Are you able to send me an example survey from hotjar @mbeacom? Want to see how much we can customize. One thing I wondered is, do people respond to the current emails because they feel personal.

**Comment by vs77bb** [comment]
Dup of our #1490
