### ISSUE TITLE
Emoji Not Showing On Issue Explorer

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1157]
### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="1059" alt="screen shot 2018-05-14 at 6 31 29 am" src="https://user-images.githubusercontent.com/23297747/39995004-a0d8ba7c-5740-11e8-8e97-b8590c337223.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Issue Detail Page is working fine 👍 

<img width="517" alt="screen shot 2018-05-14 at 6 32 57 am" src="https://user-images.githubusercontent.com/23297747/39995016-af681d8a-5740-11e8-935d-3aacdde54fa3.png">

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Child of #1143

**Comment by thelostone-mc** [comment]
@vs77bb checked it out on chrome & firefox -> seems to be rendering fine!
Is it still persistent ?

![x1](https://user-images.githubusercontent.com/5358146/40037540-6e37c694-582b-11e8-8b1d-51d1926e0d95.gif)
