### ISSUE TITLE
Optimistic UI: Faster Bounty Confirmations

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1160]
### User Story

As a funder, I want to be able to fund a bounty quickly so that I can move on with the rest of my day.)

### Why Is this Needed?
*Summary*: To help funders move past the pending transaction screen, quickly. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Bounties are confirmed on the [Issue Explorer](gitcoin.co/explorer) after six block confirmations on the blockchain. Is this right @owocki?

### Expected Behavior
Move the user to a 'likely confirmed' status once one block is confirmed. Go back and let them know it didn't work out in the 1% edge cases that it doesn't work out. 

### Definition of Done
Needs Definition. 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Child of #1136.

**Comment by kuhnchris** [comment]
If it is already at 1 block, this ticket is moot, no? @owocki @vs77bb
