### ISSUE TITLE
Email notification to transfer funds back to funder

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1162]
Not ready to work on

if gitbub issue is closed, expired, or about to expire, i should get a few notification that my funds are still there and i should transfer the funds back. This could consist of new or modifying existing emails.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
Please specify a bit more @PixelantDesign  - this is also important for gitcoin itself since you guys keep having "old" bounties lying around which won't get any better over time ;-)
