### ISSUE TITLE
As an anonymous user, I would like to unsubscribe from email notifications.

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1165]
With the authentication flow changes introduced in the django auth PR, unauthenticated/anonymous users are unable to modify their email subscription settings until they authenticate with Github.
We should allow legacy ES users to update their email subscription settings.

**Comment by darkdarkdragon** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__This issue now has a funding of 0.05 ETH (34.61 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1165/682).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
