### ISSUE TITLE
Time to value KPIs  

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1166]
some KPIs we should start tracking

* median time from open to started
* median time from started to submitted
* median time from submitted to done

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1166/681).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by kuhnchris** [comment]
are those KPIs already being tracked? I sadly have no idea about the KPI stuff here.
