### ISSUE TITLE
Code As a Front-End Developer I want consistent CSS classes for buttons

### ISSUE THREAD

**Issue by michelgotta** [gitcoinco/web#1173]
### User Story

Code As a Front-End Developer I want consistent CSS classes for buttons while developing. There are different approaches throughout the code of the platform.

### Why Is this Needed?

The styling isn't very consistent and the classes can't be used universally. 

### Solution

Bootstrap CSS is used. Transform all buttons to proper Bootstrap button classes and check if the styling correct.

### Definition of Done

All buttons have classes like `btn`, `btn-lg`, `btn-primary`, `btn-block` and make use of `btn-group` for button-groups. Delete all other button styling from several files (e.g. buttons.css). Add additional styling for specific buttons to view css files (e.g. search_bar.css, dashboard.css)

**Comment by owocki** [comment]
i know that @SaptakS  @eswarasai @thelostone-mc @olaf and a few others probably agree iwth ya :)

**Comment by thelostone-mc** [comment]
Closing this out and following it up on https://github.com/gitcoinco/web/issues/2194
