### ISSUE TITLE
As an ENS user, I want Gitcoin's ENS subdomains to call the ENS SetOwner Function, so I can own my subdomain outright.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1186]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As an ENS user, I want Gitcoin's ENS subdomains to call the ENS SetOwner Function, so I can own my subdomain outright.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So ppl can 'own' their subdomains outright.

Follow up to https://github.com/gitcoinco/web/pull/509

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
When you submit a POST request on https://gitcoin.co/ens, we make two requests to the Ethereum mainnet. The first request is to the ENS registry and it sets the domain's resolver to the public resolver resolver.eth. The second request is to the public resolver, and it sets the domain's address to your address.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Same as current behaviour, but we will also call the `setOwner()` function which will transfer the subdomain to an address of the user's specification.

TODO: Work out if/how we can/should get the subdomain returned if the user's github username changes.

**Comment by kuhnchris** [comment]
This never got implemented, right?
