### ISSUE TITLE
api : explorer api insane load time

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#1188]
### User Story

<img width="1440" alt="screen shot 2018-05-19 at 10 22 37 pm" src="https://user-images.githubusercontent.com/5358146/40272601-ac8d4630-5bcd-11e8-9fa3-aaa9197eae83.png">

Occasionally the api load time gets ridiculously slow and firefox asks me if I want to kill the request as the page is taking too long to load

Browser: Firefox / Chrome
Firefox prompts to kill scripts
Occurance: Every once in a while (in the past 2 days )

cc @owocki @mbeacom

**Comment by mbeacom** [comment]
Thanks for raising this issue!

Current initiatives that will help reduce the latency:

- Django query/queryset caching in Redis
- General query optimizations (use of `prefetch_related` and `select_related` would go a long way).
- Bounty API refactor
- Serve API over it's own subdomain, i.e.: `api.gitcoin.co`

Beyond the current initiatives, we would probably benefit from researching/implementing any of the following:

- gRPC
- Websockets

**Comment by owocki** [comment]
interestingly.... i can't seem to reproduce this locally or on prod right now

[screenshot](http://bits.owocki.com/0B1K3d3G3K1O/Screen%20Shot%202018-05-21%20at%2012.03.06%20PM.png)

i wonder if theres some job that introduces a performance block at the application at DB layer

**Comment by mkosowsk** [comment]
Also confirmed on Production nice speed... Gitcoin Explorer taking the weekend off? 🤔

**Comment by mbeacom** [comment]
This might have occurred during a long running `sync` background job.

**Comment by thelostone-mc** [comment]
Sat 10:22pm, the day the issue was opened :P 
(Just saw the screenshot on the top )

I'll keep a lookout on this when it happens again
