### ISSUE TITLE
Clicking on the organization icon in the bounty page throws a 404

### ISSUE THREAD

**Issue by arku** [gitcoinco/web#1192]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a gitcoiner, I would like to view the gitcoin profile of an organization.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

I am not sure if we have profiles for organizations yet. If we don't, we shouldn't link the organization icon to the profile. Currently, clicking on the organization icon in the bounty page displays the 404 page.

My guess is that when someone visits `https://gitcoin.co/profile/gitcoinco`, the app is looking for a user object with the username `gitcoinco`. Maybe we need to create a new route `/org/:orgname`?

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

Visting https://gitcoin.co/profile/gitcoinco throws a 404

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Visting https://gitcoin.co/profile/gitcoinco should render the profile of gitcoinco instead.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Go to https://gitcoin.co/issue/gitcoinco/web/1013/320
2. Click on the Gitcoin icon to the left of the bounty title

**Comment by arun1595** [comment]
@mbeacom I also tried visiting the profile of a few other organizations, they all threw a 404 FYI.

**Comment by thelostone-mc** [comment]
Has this been fixed ? 😅 

<img width="1440" alt="screen shot 2018-05-21 at 11 39 35 am" src="https://user-images.githubusercontent.com/5358146/40292906-a97e206c-5ceb-11e8-899f-7c9de3bec732.png">

**Comment by mbeacom** [comment]
@thelostone-mc I went in and changed the gitcoinco `Profile.hide_profile` to `False`.
One possible solution would be to prompt users hitting an organization profile page that is actively hidden or missing to notify the organization owner/members to approve the profile public listing.

Moving forward, it might be beneficial for us to introduce an organization management section to settings.

**Comment by owocki** [comment]
> @mbeacom I also tried visiting the profiles of a few other organizations, they all threw a 404 FYI.

we're trying to figure out the best way to balance privacy / ux here.  itd be nice to be able to see each organization, but without a specific opt-in, we might run afoul of privacy best practices..

**Comment by mbeacom** [comment]
@owocki My initial idea to solve this is to:

- Add an `Organization` model to handle profiles that are an organization.
- Add `Profile` objects to `Organization.members` if they exist on gitcoin.
- Add an organization settings view where org owners can update members, perms, and general org details (description, website url, svn/gh profile url, avatar, keywords/tags, integration/notification settings, i.e. Slack, and view following members list, featured bounties, what to display, start/submit work hunter preferences/scheme settings, etc)
- Notify the organization owner (email/web?) about the pending authorization to list their org on GC with a link to approve/deny the org if the org doesn't already exist on GC or still needs approval.
- Add a view to display org specific "profile" pages.
- Add a CTA on the associated template to request approval from the owner/members if the org doesn't already exist. If the org exists, display related card details defined above.
