### ISSUE TITLE
Add granular caching for Django querysets and template rendering

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1199]
As a developer, I want to be able to specify queries, querysets, and view data to be cached in Redis to achieve faster response times and reduce database load.

Implement a library such as: `django-cacheops` or `django-cachalot` to cache querysets for high traffic models/views/etc.

Configure the newly introduced cache to use the elasticache instances deployed in: #1198

**Comment by kuhnchris** [comment]
cacheops is at least in the requirements.txt file - so I assume it's already in. closing.
