### ISSUE TITLE
Add all crontab jobs to job container

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1201]
As a technical asset, I would like the ability to run any legacy cron job as a single-run task via the job utility image.
Implement all crontab background tasks into the `job` docker image.

- BACKUPS
    - [x] gitcoin/coin; bash scripts/backup.bash >> /var/log/gitcoin/backup.log  2>&1
- GITCOIN WEB3 STUFF
    - [x] sync_geth mainnet 0 99999999999
    - [x] sync_geth rinkeby 0 99999999999
- TOOLING
    - [x] get_prices
    - [x] refresh_bounties
    - [x] refresh_bounties --remote
    - [x] sync_gas_prices
    - [x] sync_profiles
    - [x] cleanup_db_space
    - [x] sync_external_bounties.bash
    - [x] clearsessions
- REPORTING
    - [ ] activity_report $(date --date='-1 month' +%Y/%m/%d) $(date +%Y/%m/%d)
- GITCOIN MARKETING
    - [ ] sync_mail
    - [x] remarket_tweet
    - [x] expiration
    - [x] expiration_start_work
    - [x] sync_keywords
    - [x] sync_slack
    - [x] sync_github
    - [x] get_notifications
    - [x] bounty_feedback_email
    - [x] new_bounties_email
- MISC
    - [ ] expiration_tip
    - [ ] assemble_leaderboards
    - [ ] pull_stats
    - [ ] pull_github
    - [ ] post_to_craigslist 1

**Comment by thelostone-mc** [comment]
me helping out ! never done this before :P

**Comment by kuhnchris** [comment]
I think this idea is already on the brink of death since we also try to get this into the "on-demand execution" thing that you proposed, right @danlipert ? (e.a. the cronjobs being integrated to the admin side to be schedulable from there)
