### ISSUE TITLE
Target api.gitcoin.co for API requests

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1206]
Modify all references to `gitcoin.co/api/` to use `api.gitcoin.co/`

**Comment by abitrolly** [comment]
There is no such site yet - #1746

**Comment by kuhnchris** [comment]
Just as a quick reminder to me @danlipert - we killed the idea of moving to api.gitcoin.co, right?

**Comment by danlipert** [comment]
I don't know what the impetus was here

**Comment by abitrolly** [comment]
@danlipert so why you did decide to kill the idea of moving to api.gitcoin.co?
