### ISSUE TITLE
Add Integration model

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1213]
Add an `Integration` model subclassing `SuperModel` that will carry:

- config (json)
- integration_type (charfield)

Add `integrations` to `Profile` and `Organization`

The purpose for this new model is to act as a medium for *all* third-party integrations... i.e.: Slack, Disqus, Discord, Github, Twitter, Facebook, whatever.

Once we introduce this model, we'll be able to handle all integrations in a common flow and determine handling of notifications based on the integration type.

**Comment by thelostone-mc** [comment]
Purpose of `Integration` model  ?

**Comment by mbeacom** [comment]
@thelostone-mc Please see the updated description.
