### ISSUE TITLE
GDPR -- update privacy policy

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1232]
GDPR -- update privacy policy

Put Privacy Policy on a Gitcoin Page Template

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/1222

**Comment by owocki** [comment]
this is done

**Comment by vs77bb** [comment]
where is the link to it on the website @owocki? need it to close out the copy for the e-mail + modal

**Comment by owocki** [comment]
@vs77bb https://gitcoin.co/legal/privacy

**Comment by SaptakS** [comment]
> Put Privacy Policy on a Gitcoin Page Template

This part still seems to have been not done. Does this need to be done?

**Comment by mbeacom** [comment]
This is live. Closing.
