### ISSUE TITLE
GDPR -- Ask for re opt-in from all EU customers

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1233]
From Consensys Legal:

```
B. Ask for re-permission from existing contacts. Based on our discussion with the marketing team, the best practice is to ask for re-permission (opt-in) from contacts already saved in your MailChimp email list. MailChimp provides template language to help simplify the process of sending out a request to existing contacts asking them to actively consent (opt-in) to receiving future emails in a manner that is compliant with GDPR. Please note that the re-permission request would only need to go out to users whose information was collected from the EU (to the extent you are aware of this information). 


```

**Comment by owocki** [comment]
@mbeacom do we have any way of knowing which users are from the EU easily?  

ideally i'd want a `profile.is_EU()` that i could call from a mgmt command

**Comment by mkosowsk** [comment]
I don't think it matters if someone is from the EU because GDPR applies to everyone even passing through the EU. From what I understand, best practices are just to assume everyone is EU

**Comment by owocki** [comment]
Hmm..

This is what Consensys Legal says about this:

>  Please note that the re-permission request would only need to go out to users whose information was collected from the EU (to the extent you are aware of this information).

**Comment by mkosowsk** [comment]
Hmm I may have read an overly cautious report then

**Comment by mbeacom** [comment]
@owocki We should be able to use the geoip data.  Looking into this now.

**Comment by owocki** [comment]
fix is in https://github.com/gitcoinco/web/pull/1249

**Comment by owocki** [comment]
this copy is funny http://bits.owocki.com/1k0y411b2t2H/Screen%20Shot%202018-05-24%20at%208.52.30%20AM.png

maybe we could go in this direction?

**Comment by thelostone-mc** [comment]
My vote is yes

**Comment by mbeacom** [comment]
@owocki Are you thinking we would send this only when `emailsubscribers.is_eu` is `True` or *all* ES?

**Comment by owocki** [comment]
only EU

**Comment by owocki** [comment]
@mbeacom ^^

**Comment by SaptakS** [comment]
PR already merged. Closing this.
