### ISSUE TITLE
GDPR - check about checkbox prefills

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1234]
<img width="631" alt="screen_shot_2018-05-23_at_1 36 31_pm" src="https://user-images.githubusercontent.com/513929/40444094-949d4fe2-5e85-11e8-8bd4-67b726dc38cc.png">

on the new funder form, this checkbox is not prefilled UNLESS the user has previously agreed.  then we just remember their agreement from last time

is this ok?

**Comment by SaptakS** [comment]
Should be fixed by #1245
