### ISSUE TITLE
GDPR: Settings Content Updates

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1235]
<img width="1435" alt="screen shot 2018-05-23 at 12 35 18 pm" src="https://user-images.githubusercontent.com/513929/40444223-fecc7154-5e85-11e8-85fa-08c4116c1701.png">

* disclose The purposes for collecting the information and how it will be used (e.g., provide updates, marketing)
* add 'Notice that the user may withdraw consent at any time and instructions on how to do so (e.g., by clicking an unsubscribe link in the email or contacting the spoke directly)'
* our privacy contact info

**Comment by SaptakS** [comment]
I am taking this up.

**Comment by owocki** [comment]
our privacy contact info = privacy@gitcoin.co

@PixelantDesign what should we do for this?

> The purposes for collecting the information and how it will be used (e.g., provide updates, marketing)

Maybe something like.
* We collect your profile information to provide context on the bounties you submit to the gitcoin system, or to help bounty funders evaluate your fitness for performing their bounty.
* We collect your email address so that we can keep in touch about updates to bounties.
* We collect your email address so that we can keep in touch about important updates to Gitcoin's featureset.

For 

> add 'Notice that the user may withdraw consent at any time and instructions on how to do so (e.g., by clicking an unsubscribe link in the email or contacting the spoke directly)'

You may withdraw consent for profile related activities, by using the checkboxes above.
You may withdraw consent for any email related activities at /settings/email
You may remove your account altogether at LINK

**Comment by SaptakS** [comment]
@owocki should I mention these below the checkboxes? Also I think merging of PR #1246 will help me hyperlink to gitcoin's privacy policy and mention the privacy email as well.

**Comment by PixelantDesign** [comment]
All sounds good! 

For data collection...i would just add in there somewhere:

We aim to collect as little information from you as possible. Any information that you share is used to provide an experience that is relevant to you.

The bit about ‘bounty hunters and evaluation’, should we hold off on that? We dont have any features like that yet and when we do it might be best to try to frame it in a more positive light.

**Comment by PixelantDesign** [comment]
Hmm where does the Go button take me?

**Comment by SaptakS** [comment]
> Hmm where does the Go button take me?

It just saves the preference of the user and takes back to this very tab.

**Comment by vs77bb** [comment]
I made some slight copy edits to @owocki's initial pass. I'd also recommend that 'Go' is changed to 'Submit' or something more clear as to the fact that the changes are being processed on this page itself.

**Comment by mbeacom** [comment]
@vs77bb I agree with changing `Go` - We'll want to update this on all of our forms, though. I am fairly positive there are a few using that copy.
