### ISSUE TITLE
GDPR -- Cookie Consent

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1236]
From Consensys legal:

We encourage each spoke/circle to implement a tool for obtaining consent for the cookies used on your website and recommend a third-party tool like TrustArc for now.

https://www.trustarc.com/products/consent-manager/

**Comment by SaptakS** [comment]
We can maybe use the [TrustArc Cookie Consent Product ](https://www.trustarc.com/products/consent-manager/)as mentioned

**Comment by owocki** [comment]
who wants this one?

**Comment by thelostone-mc** [comment]
A few questions: 

- Do we integrate gitcoin with trustarc to help manage cookie consent 
- If yes, whom do we get in touch with to get it set up / do we request a demo for ourselves 
- Meanwhile do we notify users that we are setting this up (to keep them in the loop ? )

- Also, Google sign on seems to be failing when I try signing into trustarc

@SaptakS @mbeacom

**Comment by mbeacom** [comment]
I'm still waiting to hear back from TrustArc.

**Comment by owocki** [comment]
@PixelantDesign  @thelostone-mc @mbeacom maybe instead of integrating trustarc, we can just put the copy for this in https://github.com/gitcoinco/web/issues/1239 ?

**Comment by mbeacom** [comment]
@owocki That sounds like a solid solution for the time being!

**Comment by PixelantDesign** [comment]
Sounds good.

**Comment by owocki** [comment]
<img width="1440" alt="40481293-9905186e-5f6e-11e8-9eef-32eab29464b9" src="https://user-images.githubusercontent.com/513929/40494309-c770d9fa-5f31-11e8-8277-55670327dc4a.png">

Proposed changes to this modal:

Add 'Would you like to consent to using cookies?' at the bottom of the modal.
Change 'OK' to 'Agree'
Add a 'No thanks' link which causes the user to leave.

@PixelantDesign does that soudn ok?>

**Comment by thelostone-mc** [comment]
no thanks --> delete account or just logout ?

**Comment by PixelantDesign** [comment]
I think that would be okay.

We will need a brief summary on how we use cookies on the site or link to privacy to explain it there.
I've seen most sites explain it in context though.

**Comment by mbeacom** [comment]
Once we're done with the GDPR items we're currently working on, we'll move into addressing this with:  https://github.com/TyMaszWeb/django-cookie-law
