### ISSUE TITLE
GDPR -- Privacy Policy Updates Email

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1237]
We should send a privacy policy update email once the new PP is merged

**Comment by vs77bb** [comment]
[e-mail copy here](https://docs.google.com/document/d/1tr1W7LbrsQZ4SI5eH0anc9aAvRyrlan3wdRhfsiCgaE/edit) ... 

dup of #1242

**Comment by PixelantDesign** [comment]
ok i'll close this. Thanks!
