### ISSUE TITLE
GDPR: Show Message in Modal

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1239]
*Due: 5.25.18*

Show message in modal that we're aware and care about users privacy. 

Display to all authenticated users when they visit Gitcoin

Link to updated privacy policy.

Okay dismisses the modal and saves a localstorage setting such that it isnt shown again.

![Screen Shot 2018-05-23 at 3.00.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a37bf1122b4f5d585ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce04d57a4163667e0772431.png)

**Comment by SaptakS** [comment]
@PixelantDesign @owocki do we show this only to the countries complying to GDPR or to everyone? Also do we show the first time they open the website after this has been implemented?

**Comment by PixelantDesign** [comment]
I've read mixed things, I think we should just show to everyone. 

Yes, lets show on the first time after authenticated - after this is implemented.

**Comment by vs77bb** [comment]
+1 on showing to everyone 👍

**Comment by owocki** [comment]
@vs77bb @PixelantDesign do you have copy that you'd like to see in the modal?  the design just has Lorem ipsum in it.

**Comment by vs77bb** [comment]
Copy below (and at [bottom of this Google Doc](https://docs.google.com/document/d/1tr1W7LbrsQZ4SI5eH0anc9aAvRyrlan3wdRhfsiCgaE/edit))

**We Care About Your Privacy**

As a Web 3.0 company, we think carefully about user data and privacy and how the internet is evolving. We hope Web 3.0 will bring more control of data to users. With this ethos in mind, we are always careful about how we use your information. 

We recently reviewed our Privacy Policy to comply with requirements of General Data Protection Regulation (GDPR), improving our Terms of Use, Privacy Policy and Cookie Policy. These changes will go into effect on May 25, 2018, and your continued use of the Gitcoin after May 25, 2018 will be subject to our updated Terms of Use and Privacy Policy. 

**Read Our Updated Terms**

**Comment by PixelantDesign** [comment]
great!

**Comment by thelostone-mc** [comment]
@vs77bb @PixelantDesign could you gimme the link for the updated privacy policy.
Need to add that !

This is taken care of #1251
