### ISSUE TITLE
GDPR: Update Email Preferences

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1241]
*Due: 5.25.18*

Allow users to select or unselect which email they would like to receive

Examples in mockup are listed, please use full list available in database.

Add ability to save.

![Screen Shot 2018-05-23 at 3.09.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f06b7191a37bf112224f5f595ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce04d57a21b3567ee772431.png)

**Comment by owocki** [comment]
PR is in ^^
