### ISSUE TITLE
GDPR: Write Email To Gitcoin Community

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1242]
Write email to gitcoin community

**Comment by vs77bb** [comment]
[See e-mail draft here](https://docs.google.com/document/d/1tr1W7LbrsQZ4SI5eH0anc9aAvRyrlan3wdRhfsiCgaE/edit)!

**Comment by owocki** [comment]
@SaptakS can you code this as a management command?  

here's a nice example of an management command that sends an email to the entire userbase https://github.com/gitcoinco/web/blob/master/app/marketing/management/commands/roundup.py

**Comment by SaptakS** [comment]
@owocki on it.

**Comment by owocki** [comment]
@mbeacom @SaptakS i think we need to send this today, right?

**Comment by SaptakS** [comment]
@owocki @mbeacom I have updated the content with the link and also added the suppression check. Please have a look.
