### ISSUE TITLE
remove uppercase text from text description

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#125]
https://twitter.com/srl295/status/941362186982535168

**Comment by thelostone-mc** [comment]
Calling dibs on this ! I'll try and prettify it a bit

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/116

**Comment by owocki** [comment]
there is some convo in channel about the typeface too http://bits.owocki.com/2d2E1M0J1904/Screen%20Shot%202017-12-18%20at%2012.22.46%20PM.png
