### ISSUE TITLE
As a funder, I want abandonments to be public so I can know if someone is going to abandon work on my repo.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1253]
# Why 

chatted with FUNDERX tonight. He said he’s noticed a drop in quality on gitcoin for him. Mostly 1 people not following through or 2 enthusiastic ppl starting work but not having the skills.  He noted maybe he’s doing more bounties now and so that has led to a decrease in quality. But it could be something scaling related. 

I shilled work schemes to him. But I think we need to take a serious look at reputation once the new profiles launch.

# What

After new profiles are merged ( https://github.com/gitcoinco/web/pull/1099 ), I propose we do the following

* Everytime a user is removed from work by a mod, we record an 'abandonment' on their profile.
* We display "Num Abandonments" on their profile under 'contributor stats'
* After each abandonment, we send an email telling them they are in a cooldown period where they can't claim more work for X hours, where X is 48 for the first one, 7 days for the next one, and 3 months for the 3rd one, and a year for the fourth one.
* After the cooldown period is over, we email them to let them know they are in a cooldown period.
* We show the cooldown period on users profile

**Comment by derozic** [comment]
Point systems are great too, a function of work and also of general activity in the community.  Helps to carrot and stick involvement, and if the incentives are properly aligned it can both helpful to attract new contributors and reward loyalty and engagement.  Even better would be a token economy that does the same.

**Comment by PixelantDesign** [comment]
I think this is good idea to track abandonment to see if we can understand patterns as we think about v1 of reputation.

What about a follow up email asking why they abandoned? We could provide an incentive like: decrease the time you have left, by providing us with honest answers...it could be multiple choice with an option to explain. That way we can learn why this happens?

 I'd like to see us include tracking positive stats in v1 as well. I think a brainstorm is an order for June!

**Comment by owocki** [comment]
> What about a follow up email asking why they abandoned? We could provide an incentive like: decrease the time you have left, by providing us with honest answers...it could be multiple choice with an option to explain. That way we can learn why this happens?

good idea! perhaps in the cooldown notification email we can do this.
