### ISSUE TITLE
add saptak/aditya/scott to the team page on /about

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1257]
what the title says ^^

**Comment by owocki** [comment]
@scottmoore @SaptakS pls pass along

1. a headshot
2. your favorite gitcoin feature
3. favorite food
4. linkedin/twitter/github links (if you want them posted)

**Comment by thelostone-mc** [comment]
send it across and I'll add them ^_^

**Comment by PixelantDesign** [comment]
@SaptakS @thelostone-mc

**Comment by owocki** [comment]
whyd we close this? we still gotta add scott to team page

**Comment by scottmoore** [comment]
I’m not sure I need to be part of your GitHub team
Scott Moore
VP, Technical Services

Mobile	+1 (914) 844-3751
Email	scott.moore@orchestranetworks.com <mailto:scott.moore@orchestranetworks.com>
Website	www.orchestranetworks.com <http://www.orchestranetworks.com/>

Read <http://www.orchestranetworks.com/analysts/> the latest analyst research on Orchestra Networks

**Comment by mbeacom** [comment]
Updated original GH comment to ping our Scott xD - Apologies, scottmoore!

**Comment by thelostone-mc** [comment]
@owocki derp ! I thought he'd been added :P My bad 😂

**Comment by ceresstation** [comment]
Hey @scottmoore nice name. @thelostone-mc just sent over the information, not sure how I missed this issue!

**Comment by thelostone-mc** [comment]
Added ^_^
