### ISSUE TITLE
as a user, i want  an easy 'send tip' link on ppls profiles so i can send a tip easily

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1258]
as a user, i want  an easy 'send tip' link on ppls profiles so i can send a tip easily

success criteria
1. add a button that says 'send tip' on it that if the user clicks it will take them to the tip flow with the username prefilled
2. must look good responsive and regular desktop

**Comment by PixelantDesign** [comment]
Let's add once we merge the new profile

**Comment by thelostone-mc** [comment]
I'll throw in the code for that once profile is in 👍

**Comment by kuhnchris** [comment]
Did that get in?
