### ISSUE TITLE
Fix Settings Responsive View

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1261]
Hide marketing toaster if possible.

![7786516032](https://user-images.githubusercontent.com/238235/40522193-9e63a558-5f9d-11e8-8bda-21522ccaa40e.jpg)

**Comment by mbeacom** [comment]
Thanks for opening this - We'll definitely want to fix this.

I am not sure it's related to GDPR though - This is from 84babc30611c281c817582b4d677dda6366def83:

![screenshot_20180524-220143](https://user-images.githubusercontent.com/7315957/40522392-c1538ef6-5f9e-11e8-834b-a835e367d7ff.png)

**Comment by PixelantDesign** [comment]
Ahh I thought it might have been because we added stuff to this section today. @mbeacom
