### ISSUE TITLE
ENS Input Looks Disabled

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1262]
Ens input makes it look like a user needs to input information and click update. 

Clicking update button launches the register ens experience. We should change update copy to Get Started or Activate My ENS.

Would also be good to surface this feature on the profile page.

**Comment by thelostone-mc** [comment]
It's pretty evident that it's disabled -> but yeah you do have a point 
we could change it to just text, if that makes it clearer 🤔

**Comment by owocki** [comment]
good idea

**Comment by mbeacom** [comment]
Proposed spec:

- [ ] Update ENS settings page to no longer use a form.
- [ ] Modify input form fields to simple text
- [ ] Add CTA button/link to url reverse: `ens`
