### ISSUE TITLE
Profile Page V3

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1273]
* performane / gzip updates  per https://github.com/gitcoinco/web/pull/1099#issuecomment-391618094
* what else?  feedback?

Add Avatar Icon
Add secret project stats

Add ability to Tip User

Surface ENS

Surface Matching

**Comment by michelgotta** [comment]
Limitation/"Show more" for the activities per box
"Time passed since"/Date for activites

**Comment by nemaniarjun** [comment]
![image](https://user-images.githubusercontent.com/15715894/43622850-d7d54e32-96fb-11e8-8013-7621d09ba737.png)
- Show total earned (including tips) so that the contributor ranks and eth collected doesnt seem weird
- Clicking on the rank of contributor should redirect to leader board.

**Comment by nemaniarjun** [comment]
- http://gitcoin.co/profile/nemaniarjun/ should not give 404 but redirect to http://gitcoin.co/profile/nemaniarjun
