### ISSUE TITLE
windows variable error when submiting work?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1291]
from 
https://github.com/TimVanMourik/GiraffeTools/issues/51#issuecomment-392291538

![40580661-ab70bff0-6160-11e8-89d6-c601d6619bdc](https://user-images.githubusercontent.com/513929/40623004-bef93a64-6261-11e8-9da8-1394dd3c03f2.png)

see below screenshot

**Comment by owocki** [comment]
tried repro-ing on my mac but no luck

**Comment by owocki** [comment]
from @thelostone-mc 
```
Oh wait I sort of remember having a similar issue when accessing the ipfs from India ! 

I ended up using a VPN cause it was annoying ! 

It's possible that's whats happening ! Would you hate me if I asked you to give it another shot ( via a VPN if possible ?
```

**Comment by mbeacom** [comment]
Checking this out on my windows machine now... Will report back!

**Comment by mbeacom** [comment]
I can't confirm this issue is related to Windows fulfillments.  @owocki [This bounty]( https://gitcoin.co/issue/mbeacom/test-repo/37/711) was fulfilled via the latest chrome stable release on windows 10 pro.

I'm leaning towards @thelostone-mc's recommendation.

**Comment by thelostone-mc** [comment]
@mbeacom @owocki  Close this as this cannot be reproduced? 
If needed the next time I get the error -> I'll add more logs /  alert to make it clear that it's the IPFS connection which is failign ?

**Comment by nemaniarjun** [comment]
@owocki I am not on windows! I am on Ubuntu 16.04. 
This issue still occurs for me. I will try the VPN solution and report back :)

**Comment by nemaniarjun** [comment]
I tried to do this with a VPN, (Using AWS EC2, Mumbai).
This could be an issue regarding Indian IPs, or it could be about Proxy, as I am behind my Uni's proxy, when I am not connected to a VPN.

**Comment by thelostone-mc** [comment]
Haha it's annoying I know :P
Closing this ^_^
