### ISSUE TITLE
organization profiles

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1292]
https://gitcoin.co/profile/JoinColony
https://gitcoin.co/profile/gitcoinco

# What 

these should be representative of the organization, not individual users

# TODOs

* Remove 'tips' section
* add all bounties that have been posted on that organization
* remove contributor/funder section up top, and instead add org_stats

**Comment by owocki** [comment]
@thelostone-mc @mbeacom pls see PR at https://github.com/gitcoinco/web/pull/1310

**Comment by thelostone-mc** [comment]
Updating UI for this section along in https://github.com/gitcoinco/web/pull/1342
