### ISSUE TITLE
ENS Submission Completed?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1305]
As a user, I'm unsure if my ENS domain went through. After confirmation dialog, I still see the Register and accept terms checkbox....we should tell the user what to expect next, tell them they are done, or take the user to do something else.

![Screen Shot 2018-05-29 at 10.57.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456fa6b7191a379ef0c2e56415e4abc30254d58eeb9cb74fce36f34985619e8806b0e77906e15adbb831bea50ba208f1b85e7badf4496fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e64b55a11a3e67e474356e0a.png)

**Comment by owocki** [comment]
is this page before or after you confirm the signature in metamask?

**Comment by thelostone-mc** [comment]
It must be before confirming 🤔 
The UI updates once you confirm it on metamask

**Comment by PixelantDesign** [comment]
That screen showed after I submitted and After I received the confirmation dialog (which I thought was strange because I just went through that process).

**Comment by kuhnchris** [comment]
Is this still the case or did we fix it in the meantime?
