### ISSUE TITLE
Back button invisible in Receive Tip success page

### ISSUE THREAD

**Issue by arun1595** [gitcoinco/web#1313]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

In the 'Receive tip' success page, the 'Back to Gitcoin.co' button text is invisible.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Button text is invisible

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Button text is visible

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

![image](https://user-images.githubusercontent.com/7039523/40734422-079a47f2-63fe-11e8-8aee-ad62fe9344f9.png)

**Comment by mbeacom** [comment]
Which browser was this on? I was unable to reproduce this on the latest stable chrome and macos.

`Chrome: Version 67.0.3396.62 (Official Build) beta (64-bit)`
`macos: 10.13.4 (17E202)`

**Comment by thelostone-mc** [comment]
@mbeacom  Had this issue when I checked it out in firefox !

**Comment by SaptakS** [comment]
I think it wasn't actually invisible. It was there, not proper UI maybe. That seems fair to happen given the change in the PR.

@mbeacom to me it seems like a different page or button given the code in the PR. Because the button label and almost the entire innerHTML is different to the above screenshot. @thelostone-mc ?

**Comment by thelostone-mc** [comment]
The screenshot posted was for receiving tips , the text is different from what @mbeacom put up!
Assuming they are from different flows
