### ISSUE TITLE
As a funder, I want to be able to easily claim (or know when I can claim) the funds from an expired issue

### ISSUE THREAD

**Issue by knocte** [gitcoinco/web#1330]
### User Story

As a funder, I want to be able to easily claim (or know when I can claim) the funds from an expired issue, so that they don't end up in limbo.

### Reproduction
1. Fund an issue with 0.01 ETH.
2. Set it to expire in 24 hours.
3. Publish bounty, wait 24 hours.
4. Go to issue.

### Current Behavior
The web UI says the issue is "Soft expired", and shows a tooltip with the text "This issue is past its expiration date, but it is still active. Check with the submitter to see if they still want to see it fulfilled."

### Expected Behavior
The web UI should say what does "Soft expired" mean in a tooltip (e.g. how long will it be this way until it's "Hard expired?"). It should not show the tooltip (with the text "This issue is past its expiration date, but it is still active. Check with the submitter to see if they still want to see it fulfilled.") if the person logged in is the funder of the issue.

### Additional Information
An example of a current issue where this is happening: https://gitcoin.co/issue/knocte/gwallet/2/529

**Comment by owocki** [comment]
hi thanks for the ticket writeup!

there is a tooltip that explains what this means.... [screenshot](http://bits.owocki.com/2c3N0S3a3720/Screen%20Shot%202018-06-01%20at%209.22.11%20AM.png)

maybe we need a little info dialog and to adjust the copy to say what hard expired means too!  cc @PixelantDesign

**Comment by knocte** [comment]
@owocki : I had already mentioned that tooltip in this ticket, did you read the ticket entirely?

**Comment by owocki** [comment]
thanks i see it now

**Comment by PixelantDesign** [comment]
Hi Knocte --

Thanks for bringing this to our attention. The soft vs. hard expire is a little confusing, we will be simplifying to just expired [on this ticket ](https://github.com/gitcoinco/web/issues/1375)and showing the additional messaging separately on the ui layer. The messaging will be persistent once the issue has expired.

Let me know if you have any questions!

**Comment by knocte** [comment]
@PixelantDesign that seems like a piece of work that would close this issue.
In the meantime, can you tell me how long is the period to have an issue transition from SoftExpired to HardExpired at the moment? Thanks

**Comment by owocki** [comment]
> In the meantime, can you tell me how long is the period to have an issue transition from SoftExpired to HardExpired at the moment? Thanks

centuries.. long enough for it to be a non-issue

**Comment by knocte** [comment]
Not sure I understand; to me, being long is the issue, I want to get my ETH back.

**Comment by owocki** [comment]
you can cancel the bounty and reclaim your funds regardless of whether the bounty is excpired or not.  just look for the 'cancel bounty' button

i agree with the OP comments about updating the copy on the tooltip

**Comment by knocte** [comment]
> just look for the 'cancel bounty' button

I don't see that button. Where is it? Looking in https://gitcoin.co/issue/knocte/gwallet/2/529, even in the source of the page there's no "cancel" text, so it's not that the button is hidden or something.

**Comment by knocte** [comment]
>> just look for the 'cancel bounty' button
> I don't see that button

Is it because the funder appears with an empty field "gitcoin profile" somehow? it maps to my email address properly (same email address as my gitcoin profile has). Please help me cancel this bounty.

**Comment by owocki** [comment]
If you are logged into metamask on the mainnet with `0xdba22c88ed3a67328c56ac52dd606298393f2eed` as your coinbase, the cancel bounty button should appear.  could you please confirm you've tried that?

**Comment by knocte** [comment]
Oh, being logged in with metamask I can see the button, indeed.
(Still, it seems in https://gitcoin.co/profile/ it still says "0 bounties funded" which seems to suggest that still my account is not linked properly, but this might be a different issue.)
I'm going to try to click on "Cancel bounty" now and I'll report back.

**Comment by owocki** [comment]
thanks @knocte ! 

so the reason gitcoin hasn't connected your bounty to your profile is that it looks like you werent logged in when you submitted the bounty.  

sorry for all the confusion!
