### ISSUE TITLE
fontawesome : Revert to css

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#1331]
### User Story

Font awesome 5 js seems to be needing optimization.
Seeing lots of console warnings for violations where events take longer than expected.

<img width="1440" alt="screen shot 2018-06-01 at 1 07 51 pm" src="https://user-images.githubusercontent.com/5358146/40827950-df87a61a-659c-11e8-8de6-e55fee86467d.png">

Refs: https://github.com/chrisblakley/Nebula/issues/1582

Potential Fix: Revert back to the CSS method until js svg is optimized and proven worthy of migration

**Comment by thelostone-mc** [comment]
@SaptakS @mbeacom could you guys tell me if this happens at your end ?

**Comment by SaptakS** [comment]
@thelostone-mc I know this problem exactly and have faced it in many other open source projects I worked in. The JS as you mentioned does a whole lotta complicated work which ain't needed. And they actually have a CSS only module as well in the version 5. So we can just use that. The font classes and everything remains same. I have had experience in doing this migration, so let me know in case you need any kind of help. :)

**Comment by darkdarkdragon** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1331/744).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
