### ISSUE TITLE
empty user comments should be handled on gitcoinbot 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1336]
see https://github.com/gitcoinco/web/issues/797#issuecomment-393843833 -- its awkward when the user hasn't entered any text here (or if they used the ioS app)

**Comment by arun1595** [comment]
@owocki We've got a validation for the issue action plan but it isn't strict as it doesn't trim the whitespaces. I've submitted a [PR](https://github.com/gitcoinco/web/pull/1338) which will require a user to input a string for the action plan.

Let me know if it works.

Thanks!
