### ISSUE TITLE
Tell mobile users about Toshi (and other mobile clients)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1337]
add the attached button for mobile users that visit Gitcoin from a normal browser. If you only display MetaMask (as is now) mobile users won't be able to use the service, so best to direct to Toshi's app store link. Should be pretty seamless but to detect when a user is coming from a mobile browser, check out slide 4 of this deck.

![gettoshi 2x](https://user-images.githubusercontent.com/513929/40849508-5a8673fa-657f-11e8-8a23-9ab96b2fdf58.png)

**Comment by kuhnchris** [comment]
The Coinbase Wallet?
