### ISSUE TITLE
As a funder, I want to know the hourly rates I'm paying out, so I can know if I'm following best practices

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1344]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder, I want to know the hourly rates I'm paying out, so I can know if I'm following best practices

Ref https://medium.com/gitcoin/tutorial-how-to-price-work-on-gitcoin-49bafcdd201e

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
bc the higher the funding the more the sucess rate.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
This info isnt surfaced.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Find a place to surface this info in a private way (maybe funder dashboard, maybe private area on profile?

**Comment by kuhnchris** [comment]
Info is surfaced now - closing
