### ISSUE TITLE
BUG - Black circle on ENS page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1353]
http://bits.owocki.com/3I1C1603312N/Screen%20Shot%202018-06-03%20at%205.50.19%20PM.png

Waht is this thing?  looks like a regression

**Comment by arun1595** [comment]
@owocki Let me fix it.

**Comment by arun1595** [comment]
@owocki Submitted a [PR](https://github.com/gitcoinco/web/pull/1354/files). Check it out when you get a chance.

**Comment by owocki** [comment]
@arun1595 this seems to be back

**Comment by arun1595** [comment]
@owocki Can you share a screenshot?

**Comment by owocki** [comment]
<img width="873" alt="screen shot 2018-06-13 at 8 02 16 pm" src="https://user-images.githubusercontent.com/513929/41387546-ae423a00-6f44-11e8-8a79-c4f0487191c5.png">

**Comment by arun1595** [comment]
@owocki Weird, let me check and get back to you.

**Comment by arun1595** [comment]
@owocki The font awesome icon classnames are fine. I guess the font awesome css file isn't loaded in the ENS html page. Will confirm and submit a PR.

**Comment by arun1595** [comment]
@owocki That was the case, the font awesome css file was loaded in a conditional for some reason. I've submitted a [PR](https://github.com/gitcoinco/web/pull/1458) with a quickfix of moving the `link` tag outside the conditional. Check it out and let me know if I missed something.

Thanks.

**Comment by thelostone-mc** [comment]
Looks like it's working 

<img width="1440" alt="screen shot 2018-06-14 at 12 13 57 pm" src="https://user-images.githubusercontent.com/5358146/41395772-6fabe66e-6fcc-11e8-8281-4e7c42c1f199.png">
