### ISSUE TITLE
Require agreement on kill bounty

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1358]
### User Story

As a user, I want to ensure I can't submit a bounty cancelation request if I haven't agreed to the TOS.

### Why Is this Needed?

*Summary*: Legal

### Description

*Type*: Bug

### Current Behavior

<img width="1061" alt="screenshot 2018-06-04 10 20 11" src="https://user-images.githubusercontent.com/7315957/40922827-377d37e0-67e1-11e8-9f0f-9ccac533df6f.png">

### Expected Behavior

Disallow submitting the kill bounty form until the agreement has been checked.

### Reproduction

Cancel a bounty you own without checking the agreement box.

### Solution

*Summary*:  Add a check to ensure the checkbox is true.

### Definition of Done

The cancel bounty form requires accepting the agreement in order to kill the bounty.

**Comment by rtrunkhill** [comment]
I'd like to take a swing at this one please

**Comment by owocki** [comment]
@rtrunkhill be our guest!

**Comment by rtrunkhill** [comment]
So i can change the HTML but I have never used python before.  So set up may be a bit tricky, id you'd like to let someone else do this (sorry this issue came up in my JS issues search and i didnt double check it)
