### ISSUE TITLE
As a funder, I want to have a 'Powered by Gitcoin' button so that I can forward people to Gitcoin on my existing bounty page

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#1359]
It would be great to have a simple 'Powered by Gitcoin' button using the assets from the existing logo. @PixelantDesign are you open to taking this?

**Comment by owocki** [comment]
![built with gitcoin](https://user-images.githubusercontent.com/513929/40941059-edb51508-6806-11e8-89b1-e0bc362c97ca.jpg)
![gitcoinn](https://user-images.githubusercontent.com/513929/40941065-f0808970-6806-11e8-8d5a-4567e7dcc9b3.gif)


[.ai files](http://bits.owocki.com/3B3I3B2r0o3s/Archive%202018-06-04%20at%202.52.58%20PM.zip)

**Comment by PixelantDesign** [comment]
@ceresstation I made these a while back.... are you looking for the standard 88x31 size that lives in the footer? Let me know, happy to help.

<img width="1035" alt="screen shot 2018-06-04 at 10 32 21 pm" src="https://user-images.githubusercontent.com/238235/40951959-5a107090-6847-11e8-8c90-ec205fc09889.png">

@owocki we should align on which one of these to use (robot vs. logo) for consistency. Probably one with the actual Gitcoin logo is best.

**Comment by ceresstation** [comment]
Awesome, thanks guys!
