### ISSUE TITLE
on the new funder form, the design of the price estimation is wrong

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1361]
http://bits.owocki.com/2m0Q0J3h2Z0L/Screen%20Shot%202018-06-04%20at%209.54.44%20AM.png

this text should go across the entire length of the form.. not just the 2nd, rightmost div.

**Comment by owocki** [comment]
http://bits.owocki.com/1V3L2g0J1E1y/Screen%20Shot%202018-06-04%20at%209.55.46%20AM.png

**Comment by arun1595** [comment]
@owocki On it.

**Comment by arun1595** [comment]
@owocki Submitted a [PR](https://github.com/gitcoinco/web/pull/1362) fixing this issue. Take a look when you get a chance.

Thanks!
