### ISSUE TITLE
Link to Etherscan from Bounties Funded/Completed List on Profile

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1364]
### User Story

[comment]: # (As a <user>, I want to <a link to etherscan> so that <i can easily have a reference to bounties i've funded or completed>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Currently its difficult to reference bountied work to etherscan transactions

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
None

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

When I click the arrow icon in the list (right side), I should see the row expand and reveal the etherscan link. See below

The icon should expand and collapse.

<img width="1333" alt="screen shot 2018-06-04 at 12 57 54 pm" src="https://user-images.githubusercontent.com/238235/40931212-3d09b51e-67f8-11e8-84e3-6b97eae9a297.png">

**Comment by pinkiebell** [comment]
I take care of that 👍

**Comment by owocki** [comment]
note that the txhash isn't currently stored in the DB so theres some backend work associated with this.

**Comment by pinkiebell** [comment]
Should that be done with management/sync_listener or should I aim at other solutions?

**Comment by owocki** [comment]
i'm actually not sure what the best way is to connect a specific bounty's updates with a specific txid.  it can certainly be done in `sync_listener`, and via the `sync/web3`url route.. but I'm not sure the best way to string it through via `sync_geth`.  maybe @mbeacom  would have an idea?

**Comment by pinkiebell** [comment]
I could upgrade the sync_listener to use WebsocketProvider and event filters,
and then call web3_process_bounty(bounty, tx_hash)

**Comment by pinkiebell** [comment]
Btw, the above solution makes sync_geth unnecessary.

**Comment by owocki** [comment]
> Btw, the above solution makes sync_geth unnecessary.

sure, assuming that sync_listener catches everything (which we dont have confidence in right now) . sync_listener is about 1 week old

**Comment by pinkiebell** [comment]
@owocki 
Ready for review ;)

**Comment by owocki** [comment]
link me the PR?

**Comment by thelostone-mc** [comment]
@PixelantDesign do we need to display the txn hash on our page? Not sure if folks need to see the txn hash on this page.
Would it make sense to simply link it to etherscan and avoid the dropdown (aka more clicks)

@owocki @SaptakS @mbeacom

**Comment by owocki** [comment]
i defer to your and @PixelantDesign 's judgement on this

**Comment by pinkiebell** [comment]
@thelostone-mc We can limit the functionality of the dropdown to only to the same profile (/profile/).

**Comment by pinkiebell** [comment]
Here is a Screenshot of all transactions for this bounty.

![default](https://user-images.githubusercontent.com/40266861/42709443-d7e51c52-86e0-11e8-81d5-b470a80de261.png)

**Comment by owocki** [comment]
Thanks @pinkiebell this seems like really exciting progress!  (I wonder why that one has been bountykilled several times!)

@PixelantDesign taking into account that tthere are several ethereum tx's per bounty, does the design still look okay?

**Comment by thelostone-mc** [comment]
@pinkiebell gimme a heads up once this is good for final review, I'll add some css (if needed ) and we'll get this in once @PixelantDesign gives us the 👍

**Comment by pinkiebell** [comment]
@thelostone-mc, @owocki 
The Web3 Websocket part needs a mainnet battletest.
So far, I get sometimes a 'invalid event filter'- or something.
But that is infura related and handled by the code.

The other point is yours; I think we should display the dropdown only on our own profile.
But that is up to you guys ;)

Except for the points above, it is ready for review. 👍

**Comment by PixelantDesign** [comment]
Looks good, thank you @pinkiebell!

**Comment by pinkiebell** [comment]
@PixelantDesign 
It is (top)old to newest(down) for the same event (BountyKilled for example).

For example,

Event A: 0x... 2 minutes ago
Event A: 0x... 1 minute ago
Event B: 0x.. 6 minutes ago
Event B: 0x   5 minutes ago

**Comment by pinkiebell** [comment]
@PixelantDesign 
Oh wait, if we do a sync from the latest block and then we sync from a older block,
we might end up with the case that the transaction links are not sorted at all.

**Comment by kuhnchris** [comment]
@pinkiebell did you guys ever revisit this? Anyone got a state for me here? Seems to be progressed pretty far to simply die off...

**Comment by pinkiebell** [comment]
I think it stalled because of a problem with listening for events and infura.
Infura has done some work since then and it *maybe* should not be a problem anymore.

It's worth a try if anyone is up giving the PR a spin 🙂
