### ISSUE TITLE
BUG -- Cancelled Bounty on Gitcoin Did Not Return Funds

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1367]
### User Story

As a user I want to cancel a bounty and have the funds return to me.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Funds did not return

### Expected Behavior
Funds returned to funder

### Reproduction
Accidentally funded two bounties, cancelled the second one through profile tab, funds did not return.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See link here:
https://beta.bounties.network/?search=pixelant

<img width="645" alt="screen shot 2018-06-04 at 2 09 44 pm" src="https://user-images.githubusercontent.com/238235/40934043-8544fd80-6801-11e8-9ff2-efb69e70f488.png">

**Comment by owocki** [comment]
looks like the funds returned to me https://etherscan.io/tx/0x68f0272a2079e3fa36bc6dc1afdf5ef60335deb7c3f6f8b77bda29f76186dc79

**Comment by PixelantDesign** [comment]
yea one of them worked
