### ISSUE TITLE
Add Visual to Gitcoin Bot Status

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1374]
### User Story

# As a user I want visual cues so that I can see the status of Gitcoin Bot at a glance and immediately understand the current state.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Show visual on each Bot Status
- [Use this as a starting point ](https://github.com/ebidel/lighthouse-badge)
- This is applied for all bot messages

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Review with @PixelantDesign

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1374/783).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
