### ISSUE TITLE
List used contracts in the footer

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1382]
# User Story
As a ETH enthusiast, I want to see what contracts belong to gitcoin or what contracts it uses, so that I can ensure that I am using right interface.

# Why Is this Needed?
This can serve as onboarding experience for new contributors. Also as an indicator that Gitcoin is DAPP, and also while site is visible, it is not clear what public code in blockchain this deployment uses.

# Description
Type: Feature

# Current Behavior
I can't inspect actual contract versions that are used, can't check that they are security audited and by whom.

# Expected Behavior / Solution
List contracts used by Gitcoin (standard bounties, youvegoteth) in the footer of the site.

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.69 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/1382/781).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by PixelantDesign** [comment]
@owocki Any good examples we might want to borrow?

What do you think about the way metamask handles attributions in their footer?
https://metamask.io/

cc: @mbeacom @thelostone-mc

**Comment by owocki** [comment]
not that i'm aware of unfortunately.. i think just a standard footer link might be okay though
