### ISSUE TITLE
BUG Personal Information Display on Unselected Option

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1387]
### User Story

As a user I want my personal information to be hidden when i opt out.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: BUG

### Current Behavior
[comment]: # (Describe what actually happened.)
Personal info displays even if I unselect it during the funding process.

<img width="1290" alt="screen shot 2018-06-06 at 10 12 03 am" src="https://user-images.githubusercontent.com/238235/41043805-b7770132-6972-11e8-83af-a95cb8c10b22.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Hide personal information

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Fund a bounty and unselect display name and email, then view it on the issue details page
<img width="795" alt="screen shot 2018-06-06 at 10 10 10 am" src="https://user-images.githubusercontent.com/238235/41043719-88ae89c4-6972-11e8-85bd-b7f5d317df0a.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
bug is fixed, my personal info doesn't show when I opt out.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Review with Gitcoin core

See attached.

**Comment by thelostone-mc** [comment]
@PixelantDesign Do we just show the FunderETH address  ?

**Comment by PixelantDesign** [comment]
We would probably show an anonymous icon, instead of Pixelant Name it would say Anonymous, and the funded trans hash.

**Comment by thelostone-mc** [comment]
@PixelantDesign could you gimme the icon ? I'll add in the code post that

**Comment by owocki** [comment]
@thelostone-mc just use this one > https://gitcoin.co/static/avatar/Self/

**Comment by rahulpat** [comment]
@thelostone-mc any consensus on showing the FunderETH address?

**Comment by rahulpat** [comment]
Keeping it simple and displaying both name and email as Anonymous for now.
