### ISSUE TITLE
As a funder, I'd like to know how many times a developer has started a bounty but not finished it

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#1390]
Ideally this would be added as a feature on a user's page https://gitcoin.co/profile/ceresstation. 

### Why Is this Needed?

This will help projects make more informed decisions when starting work.

### Definition of Done

At the most basic level this could just be an additional field under 'contributor' that marks the number of bounties expired or abandoned.

**Comment by mbeacom** [comment]
@ceresstation We have a PR out that should address this.  It needs a minor adjustment before it can go live, but: https://github.com/gitcoinco/web/pull/1309

Is that what you're looking for?

**Comment by ceresstation** [comment]
@mbeacom Awesome, yep that's exactly what I was looking for.

**Comment by owocki** [comment]
@ceresstation this is live now.  here is a screenshot http://bits.owocki.com/091h2D3B1j1n/Screen%20Shot%202018-06-13%20at%203.20.43%20PM.png
