### ISSUE TITLE
Refresh KPI dashboard

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1402]
_administration/stats/?filter=Marketing&rollup=daily&filter=KPI

isnt really accurate any longer since it tracks a bunch of stuff that isnt KPIs.

Lets list out our KPIs and edit that dashboard to only show the actual KPIs

**Comment by frankchen07** [comment]
@owocki was exploring the KPI tickets - I believe this is the link you're looking for: https://github.com/gitcoinco/web/issues/692

**Comment by owocki** [comment]
thx
