### ISSUE TITLE
As an admin I want to triage the Landing Page Conversion Rate, which is way down since the new LP launched.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1408]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As an admin I want to triage the Landing Page Conversion Rate, which is way down since the new LP launched.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Conversion rates down from 35 email captures a day to 11 a day since the launch.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

* reintroduce the github login button in a prominent location on the landing page.
* reintroduce the email capture module above the fold (or closer to it)
* make sure the sumome module is showing up

**Comment by PixelantDesign** [comment]
We've added the login back up top. What is *Sumome module*?

cc @owocki

**Comment by owocki** [comment]
> What is Sumome module?

its the little popup in the bottom right that captures emails
