### ISSUE TITLE
Uncaught ReferenceError: Accounts is not defined

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#1418]
View details in Rollbar: [https://rollbar.com/gitcoin/gitcoin/items/1064/](https://rollbar.com/gitcoin/gitcoin/items/1064/)

```

ReferenceError: Accounts is not defined
  File "https://gitcoin.co/static/yge/youvegoteth/pre.d54a1fce2d25.js", line 59, in [anonymous]
```

**Comment by thelostone-mc** [comment]
@mbeacom  https://github.com/gitcoinco/web/blob/master/app/assets/yge/youvegoteth/pre.js#L50-L59

- Do we need the `console.log` ? 
- Can we place `document.Accounts = Accounts;` inside 
`if (typeof Accounts != 'undefined') ` ?

**Comment by mbeacom** [comment]
We should be able to remove the `console.log` and move that block.
