### ISSUE TITLE
Gitcoin Bot and Project Status

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1425]
### User Story

As a user, I want Gitcoin bot to provide clearer way to show the status of a project and also clean up the copy for each state.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently, there is a lot of competing information in Gitcoin Bot comments.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Provide messaging for all scenarios of Gitcoin Bot interactions
- Show project type and status in the Gitcoin bot message.
- Related to displaying work schemes.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Here is a WIP on what some of the scenarios might look like...[see the full flow in this PDF](url
[Gitcoin Bot Flow.pdf](https://github.com/gitcoinco/web/files/2090701/Gitcoin.Bot.Flow.pdf)
)

<img width="804" alt="screen shot 2018-06-11 at 11 33 40 am" src="https://user-images.githubusercontent.com/238235/41241733-bed0fabc-6d6b-11e8-848d-1cb422895730.png">

<img width="838" alt="screen shot 2018-06-11 at 11 33 56 am" src="https://user-images.githubusercontent.com/238235/41241741-c8bdcfc8-6d6b-11e8-82e7-fcb34bae435b.png">

<img width="815" alt="screen shot 2018-06-11 at 11 34 03 am" src="https://user-images.githubusercontent.com/238235/41241749-d22240da-6d6b-11e8-858a-b6cdd1e38d9e.png">

<img width="816" alt="screen shot 2018-06-11 at 11 34 12 am" src="https://user-images.githubusercontent.com/238235/41241755-d5102dfc-6d6b-11e8-99f7-b36adf7d0687.png">

<img width="801" alt="screen shot 2018-06-11 at 11 34 32 am" src="https://user-images.githubusercontent.com/238235/41241766-d8bea4d8-6d6b-11e8-9f34-866f2e502aa5.png">

<img width="798" alt="screen shot 2018-06-11 at 11 34 39 am" src="https://user-images.githubusercontent.com/238235/41241795-e0650c68-6d6b-11e8-9714-3619a4f604a9.png">

<img width="822" alt="screen shot 2018-06-11 at 11 35 27 am" src="https://user-images.githubusercontent.com/238235/41241807-e80ca2c8-6d6b-11e8-8c30-1461bbe8b042.png">

<img width="827" alt="screen shot 2018-06-11 at 11 35 42 am" src="https://user-images.githubusercontent.com/238235/41241821-eda7ec38-6d6b-11e8-9d55-f52a51f7387b.png">

**Comment by PixelantDesign** [comment]
@owocki @thelostone-mc @SaptakS @vs77bb, thoughts?

**Comment by owocki** [comment]
some thoughts

1. i'm not sure that 'project type' and 'approval' is important enough to take this much real estate on the bot comment
2. i worry that having super visual colorful icons will make it look like we're trying to hijack the github thread.  but im willing to test it and see if we get pushback.
3. love the cleaned up copy
4. i think that having a link to the gitcoin issue page on each and every comment will be important..  helps people find the source of truth for the funding.  would like to add this back in
5. i *like* how the current gitcoinbot shows me the status flow. 1. Open 2. Started 3. Submitted 4. Done.  It anchors me in the flow and lets me have situational awareness of where my work is relative to where it *could* be.

excited to be iterating this.  nice work!

**Comment by thelostone-mc** [comment]
I like it ! Might need to update the language a bit

@mbeacom @SaptakS can we add multiple shields / badges to comments on the same line ?
I assume shields are svg / images (from a bit of googling) and markdown language doesn't have an CSS equivalent to position them

Worst case:  we'd have to generate an svg strip for every combination
