### ISSUE TITLE
As a funder, id like the ability to extend the expiration date of a bounty, so i can keep it open

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1427]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder, id like the ability to extend the expiration date of a bounty, so i can keep it open

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So users can extend the expiry date

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Soft Expired and Hard Expired (99999 years out)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
User can extend the soft expiration date

### Definition of Done

- [ ] Use standard modal that exists.
- [ ] Update the modal with a new close icon.
- [ ] Add a standard navy blue button and call it 'Extend Expiration'. This button should be placed to the right of Cancel Bounty and before View on Github.
- [ ] The Front end UI is applied to look like attached mockups.
- [ ] User should be able to select the time frame (leverage what is being used on the funder form, but please adjust the width of the dropdown).
- [ ] The ouput of the current time frame + new time frame should display below in an area. This should also display the New Date (August, 13,2018) along with hours.
- [ ] Once user clicks Save, a standard confirmation notification should appear.
- [ ] The issue details screen should then update to the new expiration date.
- [ ] If user clicks cancel, nothing is saved. Please take user back to issue details screen.
- [ ] The implement functionality is tested and works.

![modal0](https://user-images.githubusercontent.com/238235/42791487-dcbf8e50-893e-11e8-8523-dea2ea8bfdc1.png)

![modal 1](https://user-images.githubusercontent.com/238235/42791490-df53b308-893e-11e8-893b-bf0a9c91deda.png)

![modal2](https://user-images.githubusercontent.com/238235/42791497-e7dbd532-893e-11e8-870d-4cbb7a890848.png)

### Reviewers
@pixelantdesign @owocki

**Comment by owocki** [comment]
@PixelantDesign got this feedback from @travisdmathis today!

**Comment by PixelantDesign** [comment]
Great! Seems to be a recurring theme!

**Comment by SaptakS** [comment]
@owocki As I understand, the data submitted in the blockchain will be the hard expiry(which is 99999 years) and then we update the soft expiry in the database, each time someone extends the data. But the data in the blockchain still says expiry as 9999 years. So will that be any problem for later? I understand that we are using something similar to soft delete and hard delete, just wanted to know if it's okay having a wrong data in the blockchain. Rather, can't we omit this data from the block?

**Comment by owocki** [comment]
@SaptakS i think that we shouldn't update the expiration date in the blockchain in this ticket, we should just update the `bounty.expires_date` in the DB

we will also have to make sure this line is updated; https://github.com/gitcoinco/web/blob/master/app/dashboard/helpers.py#L471-L473 such that when a new bounty is created from an old bounty, the updated expiration date transfers

**Comment by PixelantDesign** [comment]
Done!
