### ISSUE TITLE
as a worker, i'd like the ability to favorite certain funders, and get notifications when they post new work.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1428]
as a worker, i'd like the ability to favorite certain funders, and get notifications when they post new work.

(not ready t0 be worked on yet)

**Comment by owocki** [comment]
@travisdmathis 's idea!!

**Comment by kuhnchris** [comment]
Basically the "Favorites" that @usmanmuhd and @octavioamu are currently implementing... :-) Closing this one as it's being superseeded
