### ISSUE TITLE
New footer messsed up on https://gitcoin.co/ios

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1430]
https://gitcoin.co/ios

Just needs a little TLC from a CSS perspective

<img width="1434" alt="screen shot 2018-06-11 at 11 55 42 am" src="https://user-images.githubusercontent.com/513929/41248462-63e611d4-6d6e-11e8-9978-16dc1c38a1f4.png">

**Comment by thelostone-mc** [comment]
Gonna have to redo the entire page 😓

**Comment by owocki** [comment]
http://nooooooooooooooo.com/
