### ISSUE TITLE
Ability to Customize the Frequency of Gitcoin Bot

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1431]
Not Ready to be worked on

### User Story

As a funder, I'd like the ability to customize the frequency of gitcoin bot.
As a contributor, I don't want to keep being warned, when I'm diligently working through a project.

### Current Behavior
[comment]: # (Describe what actually happened.)

Gitcoin bot warns people too much.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

Add a setting to customize

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
does the current 'snooze' functionality accomplish this?

**Comment by PixelantDesign** [comment]
Hmm...the snooze is sort of a response to the Gitcoin Bot commenting too much. I was thinking more along the lines of how the funder have a more proactive control over the Gitcoin Bot custom, per issue.

The 1st use case is: 
I'm *Fanatic Funder Frank*, Project #1 I have a 14 day project, I know I'll be interacting with whomever takes the project a lot since its a shorter turn around time, I'll actively be monitoring this task. I might need Gitcoin Bot's involvement less on this issue.

The 2nd use case is:
I'm *Fanatic Funder Frank*, Project #2, I have a different issue that has a month long time frame, I know there are multiple parts to this, once I have a contributor I trust to work on this (maybe I've worked with them before/maybe not) but I feel good about this person based on their Github track record, once I've approved this person, I feel active and involved, and don't need Gitcoin bot checking in on my contributor every 3 days because I know *Confident Coder Carl* is starting the task, has a good tech approach, but has to go away to visit his aunt in between, but will be checking in (outside of Github - maybe just a text or slack) to provide updates on progress I don't want to have to be reactionary any keep clicking snooze on Gitcoin bot. 

Perhaps it *IS* the snooze feature, but framed differently, or perhaps placed elsewhere? Still thinking through this.

cc: @vs77bb

**Comment by owocki** [comment]
thanks. this is useful. happy to brainstorm sometime.

taking a step back -- one thing i really struggle with is deciding between providing interfaces that optimize for *convention* and *configurability*

convention -- dont bother me with all the details, just do whats best
configurability -- im a power user who wants to fine tune everything
