### ISSUE TITLE
Contributor Guidelines Around Coop and Contests - Best Practices

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1432]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a core team, we want to make sure that Coop and Contests Work Scheme is being used properly, and funders have an understanding of best practices.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

- To make sure that our open issues to work in progress has a good ratio.
- There is a high number of Coop issues open but users haven't taken them up.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Maybe a content piece or add guidelines to our documentation.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
@PixelantDesign do you have any values regarding this? Is it more in use? is it properly in use? Can we close this?
