### ISSUE TITLE
Relist/ Refresh Bounties Brainstorm

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1433]
*To solve for bounties with little or no movement....*

Idea I had end of last week:

Pixelant 
What do you all think about the ability to REFRESH or RELIST a Bounty - just like you do with a house. 

Owocki 
thats a really good idea

Pixelant 
How would that work though, we don't want funders to have to redo their blockchain transaction and pay more gas...

Owocki 
we could maybe just override some of the params on our side and not mutate anything on chain

Anyone want to investigate from a technical perspectivei how we might be able to do this?

**Comment by PixelantDesign** [comment]
@thelostone-mc @SaptakS @mbeacom thoughts here?

**Comment by kuhnchris** [comment]
replaced sapstak and mbeacom with @octavioamu and @danlipert  - maybe you guys got some ideas regarding this?
