### ISSUE TITLE
As a bounty hunter, I want a 'bounty as a glance' visual on the bounty page so I can score it easily in my brain as a 'go' or 'no -go'.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1441]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a bounty hunter, I want a 'bounty as a glance' visual on the bounty page so I can score it easily in my brain.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So users can see at a glance what the stats of the bounty are.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature 

### Current Behavior
[comment]: # (Describe what actually happened.)
None

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

The scorecard should go in the top right.
* It should contain all the info highlighted in blue below.
* It should contain visuals of the difficulty and the funding amount
* The visual of the funding amount should show hourly rate, and also if it's a token it should visually signify that.
* The funder rep should be shown, including their rating and how many bounties they've done the past.
* The funder scorecard should say whether or not the funder is known to be hiring right now.
* Since users don't decide on work just by how much money is involved, and really decide on a combination of value-alignment, impact, compensation, and network,   The funder should be given an opportunity to talk about their mission and why the users work will have a positive impact on the world.

![screencapture-gitcoin-co-issue-gitcoinco-web-1440-605-2018-06-11-21_37_56](https://user-images.githubusercontent.com/513929/41269211-3ff32b42-6dc1-11e8-83ec-fe96548a6a88.png)

**Comment by owocki** [comment]
@PixelantDesign thoughts on this?  I think theres a few big wins for bounty hunters here.

**Comment by PixelantDesign** [comment]
Yep, might be a good exercise to update and reprioritize the information on the top piece.

**Comment by kuhnchris** [comment]
already got updated. a new version of this is also already in the floats - superseeded x2
