### ISSUE TITLE
user cannot submit work

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1449]
User Mike Morris on Slack

For some reason the "Submit Work" page is not doing anything for me. All fields filled in, but the Submit button results in only the "busy wait" animation endlessly. Any ideas what's going on here?

![screenshot_20180612_162547](https://user-images.githubusercontent.com/513929/41357491-86b4f736-6ee3-11e8-88d7-15ee064f6d4d.png)

Once the Submit is triggered:
```TypeError: t is null[Learn More]
fulfill:14308:121149```

**Comment by mbeacom** [comment]
Associated Gitcoin bounty: https://gitcoin.co/issue/ethereum/solidity/1213/502

**Comment by mbeacom** [comment]
@owocki I tested creating a bounty and fulfilling it on prod:  https://gitcoin.co/issue/mbeacom/test-repo/45/830 - Everything seems to be working.  I will say, it took an exceptionally long time (~10 seconds) for the metamask confirmation popup to open.  Once it did, everything seemed to work, though.

**Comment by mikro2nd** [comment]
Stack trace:
```
	r
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:121149
encode
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:122530
c
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:16789
formatInputString
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:9063
[140]</</_dereq_<[14]</i.prototype.encode
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:13606
[140]</</_dereq_<[7]</d.prototype.encodeParams/r<
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:6006
map self-hosted:285:17 [140]</</_dereq_<[7]</d.prototype.encodeParams
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:5979
[140]</</_dereq_<[31]</c.prototype.toPayload
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:37526
[140]</</_dereq_<[31]</c.prototype.sendTransaction
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:38293
[140]</</_dereq_<[31]</c.prototype.execute
moz-extension://e558fa45-eb53-4f65-a6bf-bb1f4d2d8247/scripts/inpage.js:14308:39218
<anonymous> self-hosted:982:17 _callback/<
https://gitcoin.co/static/v2/js/pages/fulfill_bounty.c3b275ee8b68.js:157:17
i
https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js:2:28012
fireWith
https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js:2:28783
A
https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js:4:14033
c/<
https://gitcoin.co/static/v2/js/jquery.c9f5aeeca3ad.js:4:16323
r.prototype.wrap/t._rollbar_wrapped
https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.0/rollbar.min.js:1:5343
```

**Comment by owocki** [comment]
hmmm looks related to a chrome extension.. metamask maybe?

**Comment by mikro2nd** [comment]
Oooo -- my bad! I neglected to mention that this is in Firefox. Could well be (likely) some extension. I have NoScript (GC is whitelisted), uBlock-Origin, Privacy Badger (not blocking anything from GC that I can see) , Cookie Autodelete (GC whitelisted for cookies) and (obvs.) MetaMask 3.14.1.

hth

**Comment by kuhnchris** [comment]
If this still is a problem open up a new issue - thanks for reporting!
