### ISSUE TITLE
Pin python package versions?

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#145]
##### Description
We might want to pin all of our python module versions to avoid explosions in Travis (or live/staging/local for that matter) like #142.

##### Possible Implementation
Pin existing packages in `requirements.txt`, `requirements-dev.txt`, and `requirements-dev.txt`.

**Comment by PixelantDesign** [comment]
Need this issue @mbeacom ?

**Comment by danlipert** [comment]
dupe of https://github.com/gitcoinco/web/issues/4411
