### ISSUE TITLE
z-index issue on gitcoin.co/ens

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1457]
<img width="1439" alt="screen shot 2018-06-13 at 8 01 01 pm" src="https://user-images.githubusercontent.com/513929/41387519-8b08aa6a-6f44-11e8-8a17-f79cae7de576.png">

**Comment by premachb** [comment]
Hey! Just checking out this project and I have a fix for this. As well the page had a problem where the container would expand vertically because of the rain effect and I've fixed that too. I can include the fix for both in one PR or just make two separate PRs. Thoughts?

**Comment by thelostone-mc** [comment]
@premachb Nah just send it one PR with screenshots and referencing this issue ^_^
