### ISSUE TITLE
As a user of Gitcoin, I'd like to know who I'm working with on the platform (reputation)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1464]
### User Story

As a user of Gitcoin, I'd like to understand what kind of work other community members have done on the platform.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
we don't have one

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

Start some initial ideas on what reputation might look like on the platform.

Display on a user's profile.

Display Name of task
Link to ticket
Score: RATINGS  in stars (5)
Review comments

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Reputation works/displays properly, is clear and doesn't break anything.

**Comment by owocki** [comment]
> I'm guessing this means defaulting it to public ?

my gut says maybe we can default the star ratings to public and hide the specifics?  i dont want to preside over snickering about reviews... and we'll only have to do that if there is a dispute about someone's longform text review

**Comment by PixelantDesign** [comment]
Let's start with star ratings public.

**Comment by PixelantDesign** [comment]
Can we do the stars in Green? Orange has a warning connotation. @owocki

**Comment by PixelantDesign** [comment]
I think we should show reviews on profile.

**Comment by owocki** [comment]
@PixelantDesign if someone 'dings rep' by removing another from a bounty, what if we just represent that as a 1 star review in the UI

**Comment by PixelantDesign** [comment]
> @PixelantDesign if someone 'dings rep' by removing another from a bounty, what if we just represent that as a 1 star review in the UI

That works, is it 1 star per Funder Feedback?
If I abandon two projects, the system will automatically give me one star for each task. This means, I have 1 star regardless of how many times? Since there isn't a concept of average star ratings yet. Is this correct understanding?

**Comment by PixelantDesign** [comment]
yes, that sounds good to me. Let's keep it simple.

**Comment by frankchen07** [comment]
@PixelantDesign Some additional metrics about reputation to be displayed in a user profile (perhaps in a v2?):

* median time to completion for a bounty hunter
* median income per hour for a bounty hunter (any $ = they've done something, high $ = high worth)
* in the Gitcoin network graph, how many degrees of connection does a user have?

This will require some centralization of data, and pipelining it to the front-end.

**Comment by PixelantDesign** [comment]
@mbeacom could you tie your PR here?

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/pull/1490

**Comment by thelostone-mc** [comment]
Currently tracked at https://github.com/gitcoinco/web/pull/3709
