### ISSUE TITLE
Make ENS available for github organizations

### ISSUE THREAD

**Issue by unrealkaii** [gitcoinco/web#1475]
### User Story

[comment]: User can get an ENS for a github organization.

### Why Is this Needed?

[comment]: If developers can have an ENS, organizations need it more

### Description

[comment]: 
*Type*:  Feature

### Current Behavior
[comment]: Only user account has access to ENS

### Expected Behavior
[comment]: Option for organization account ENS

### Solution
[comment]: Make ENS available for github organizations

### Definition of Done
[comment]: When a github organization can have it's own ENS

**Comment by owocki** [comment]
i was thinking a hack for this might be allowing useres who are members of an organization to 'impersonate' that organization through the current auth structure @mbeacom
