### ISSUE TITLE
Bounty Detail page should show the txid of where the $$ went

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#148]
it would be nice if the screen confirms the recipient of the bounty.. and possible also the txid

**Comment by connorwarnock** [comment]
@owocki I can tackle this

**Comment by owocki** [comment]
👍

**Comment by CuriousLearner** [comment]
Hey @connorwarnock ! Are you still working on this?

**Comment by kuhnchris** [comment]
Was this before we got that "Transaction successful" screen?
