### ISSUE TITLE
repo maintainers control panel

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#149]
just got off a call with a well respected maintainer in the space.

open source is such a broad space to be playing in, there are many fiefdoms, islands of best practices and working norms, that gitcoin needs to support.

we will need to eventually provide a control panel that has configurable options allowing gitcoin to serve this broad community.

some things this control panel will need to manage

* can anyone submit a bounty on any feature, for any repo?  does it need to be approved by the repo maintainer first?
* when do bounties on this repo pay out?  
* sub point to hte above: enable integration with travis CI such that bounty is paid out when tests pass.
* are you hiring now?  if so, for what?
* would you like to show off your 'top gitcoin contributors' in your readme?

**Comment by owocki** [comment]
cc @pipermerriam in case there are any granular options he'd like to see configured for working norms in his repositories

cc @beylin @mbeacom in case there are any other configuration options they'd like to see manageable

**Comment by PAKISTANECN1** [comment]
Hi )
