### ISSUE TITLE
Disable Gitcoin Bot Responses 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1498]
### User Story

As a developer, I don't want to see Gitcoin Bot responses which state the inability to respond.

<img width="804" alt="screen shot 2018-06-18 at 2 28 11 pm" src="https://user-images.githubusercontent.com/23297747/41557679-0125ad48-7304-11e8-8359-43c2e02dced5.png">

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The 'heart' emoji from Gitcoin Bot is enough of a response // asking the repo maintainer to install Gitcoin Bot privileges has proven to be high maintenance. Have seen very few cases where more than the ❤️response is needed. 

### Definition of Done
Disable Gitcoin Bot comment response. Retain ❤️emoji 🙂

**Comment by arun1595** [comment]
@vs77bb I'm on it.

**Comment by arun1595** [comment]
@vs77bb Submitted a [PR](https://github.com/gitcoinco/web/pull/1500) fixing this.
