### ISSUE TITLE
Outstanding avatar issues

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1504]
Onboard Flow Changes (copied from Aditya's list)

Across all pages -> track buttons / links / video clicks

Metamask  
- [x] remove line breaks between first two para
- [x] hide video is user is logged in to metamsk
- [x] updated text to "Metamask is a wallet that enables your browser to be web3-enabled.  After you've installed Metamask, you can use web3 apps like Gitcoin!" - (from kevin) 

Avatar Page
- [x] Add two more skin colors (really light)
- [x] Rename Avatar has been saved -> Your Avatar Has Been Saved To your Gitcoin Profile.
- [x] Remove the text "Your avatar is complete" which appear when the avatar is saved
- [x] Hide Skip later button once Save has been clicked
- [x] Save avatar should come up on the botton right corner (above next and prev)
- [x] Hide alert when you move to next page
- [x] Reduce spacing between heading "Pick your xxx" and the avatar builder
- [x] When all the items in a category (like accessories ) are unchecked -> the left sidebar should reflect status as unchecked (should become a square instead of tick)
- [x] Fix mixpanel error
- [x] Fix Jquery not defined (CSRF. Can we remove this from `avatar.html` as it's already been defined in `onboard.html`)

Skills 
- [x] Rename suggest skills  -> suggest skills that apply
- [x] when skills autopopulates  -> change to plus icon to tick on highlighted skills

Welcomebot
- [x] Update welcome message to link to the FTUX.

On the explorer 
- [x] reduce the bullet size of tips section
- [x] link the Get Started here on the footer to the funder form
- [x] infinite load appears on explorer and final page of ftux , I think it's cause of the mixpanel errors (that's the only error console.log shows) 

Per https://github.com/gitcoinco/web/pull/967#issuecomment-398607889
- [x] Currently there are 4 buttons shown on staging, please update to 3 buttons as shown on the screenshot below.
- [x] Please remove drop shadow on buttons.
- [x] Please make buttons the same size and consistent with the rest of the ftux flow.
- [x] Color - Please Add #EEE3C1  AFTER  #F8D5C2
- [x] Color - Please remove Remove #3F2A18 from the skin palette (color on the far right) since the facial features don't show on this color.
- [x] Do this later button currently doesn't work. Clicking do this later should advance the user to the next step - skill selection.
- [x] On the last screen can we update this text from Getting Started Guide to Quickstart Guide

**Comment by PixelantDesign** [comment]
When my metamask is unlocked, I click the unlock button, the button takes me to the metamaks website. Is there a way to prompt me to unlock my seed phrase in the chrome extension?

**Comment by PixelantDesign** [comment]
On the last screen can we update this text from  Getting Started Guide to Quickstart Guide - 
<img width="1090" alt="screen shot 2018-06-20 at 9 50 55 am" src="https://user-images.githubusercontent.com/238235/41662661-987ea16a-746f-11e8-8594-70a276a9ca52.png">

**Comment by mbeacom** [comment]
@PixelantDesign We don't have `#EEE3C1` in the palette.  Which hex do you want moved after `#F8D5C2` ?

**Comment by PixelantDesign** [comment]
Please Add #EEE3C1 AFTER  #F8D5C2
