### ISSUE TITLE
Error in the Home link extracted from Github.

### ISSUE THREAD

**Issue by bockp** [gitcoinco/web#1505]
As a user who has registered using my Github account, I've encountered a small error in the link extraction for personal webpages from Github:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

Error in the Home link extracted from Github.

### Current Behavior
[comment]: # (Describe what actually happened.)

The Gitcoin Profile webpage has 2 links on it.
One is the link to the user's github repositories.
The second one is a link to the user's personal webpage, extracted from his Github profile.

When on my Gitcoin profile page and clicking on the House button under my username

![image](https://user-images.githubusercontent.com/10536344/41615849-ac52bd66-73fc-11e8-9008-f832702fc31e.png)

I am redirected to:

https://gitcoin.co/profile/steemit.com/@pbock

Which, given ti doesn't correspond to any real user or page, shows the 404 error page.

![image](https://user-images.githubusercontent.com/10536344/41615803-8b945ecc-73fc-11e8-8932-e8620a3d821d.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

I expected the House button underneath my profile name to redirect me to the correct address, as I entered it in my Github Profile:

steemit.com/@pbock

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Log in to your Gitcoin account using Github
2. Navigate to your profile page
3. Click the House icon underneath your username
~~4. Welcome to Dimension 404~~

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

I'm guessing the solution itself is relatively simple:

* Find the part of the code that deals with extracting the Github user information
* Find the place where it inserts the extracted information into the Home icon link
* fix it by removing "https://gitcoin.co/profile/" from wherever it's gotten itself stuck in the link.

### Done

The work is done once the Home icon correctly redirects to the web-page the Github user put as his Personal Web-page on Github.

**Comment by owocki** [comment]
@arun1595 any interst in this one?

**Comment by arun1595** [comment]
@owocki Let me fix it :slightly_smiling_face: 

I also noticed a weird issue yesterday - the funder's profile link on a bounty page was linking to https://gitcoin.co/profile

Couldn't find the bounty, will open a new issue once I encounter the issue again.

**Comment by arun1595** [comment]
@owocki I've submitted a [PR](https://github.com/gitcoinco/web/pull/1512) which should fix this issue. Please take a look when you get a chance.
