### ISSUE TITLE
Incorrect values (# bounties completed and $ rewarded) in the Leaderboards

### ISSUE THREAD

**Issue by bockp** [gitcoinco/web#1506]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

After completing 0 bounties ( 2 started, 2 submitted, 0 "accepted"), my Leaderboard position is listed as having completed 3, and the amount listed as earned is in conflict with the Collaborative contest having been cancelled.

Technically, I participated and completed 2 bounties, but one of them was listed as traditional ( then changed to Competition, which I didn't win) and the second remains listed as Traditional, though it was a collaborative bounty that was canceled (and the reward distributed as Tips to the participants) due to the absence of bulk payouts #1422 

There are two bugs associated with this, and after some study it appears both are linked, so I'll write a general description in this issue:

**Bug 1 : Number of completed bounties on Leaderboard is incorrect.**
**Bug 2 : Amount rewarded listed in leader-board is incorrect, resulting in a higher position.**

### Current Behavior
[comment]: # (Describe what actually happened.)

On my profile page, I am currently listed as having completed no bounties, and thus having received no reward. 

payout for my only completed bounty was done through a Google Form due to a lack of multi/bulk payouts at the time  (Ref: #1422) and the bounty was thus canceled.

I'd therefore assume that, as correctly listed on my profile page:

![image](https://user-images.githubusercontent.com/10536344/41617359-8f0bbd58-7400-11e8-90a3-31062ba25977.png)

My placement on the leaderboard would be *very* low.

Much to my surprise, when I checked the leaderboard, I was #12 !

![image](https://user-images.githubusercontent.com/10536344/41617427-bac7efe8-7400-11e8-9b87-d6891d743b38.png)

This looks like it's taken into account not only both bounties (the contest bounty I didn't win and the cancelled collaborative one) as completed, but also counted my Tip, and some more !

I made that calculation by looking at the $ value the Leaderboard believes I've amassed, and the number of bounties it believes I've completed:

* The Leaderboard lists 3 bounties, which I believe corresponds to how the Competition was at first listed as a Traditional project, which I _Started_ work on, then I _Stopped_ work once we realized the category was wrong. I then Started (and Submitted) work on the project after it was overwritten to count as a Competition project. these **2** submission + the work submitted on the second bounty == **3 total bounties**

* The amounts themselves were as follows -> 

0.04 Eth * 2 (two submission to the one Competition )  +  1.1 Eth (total bounty for the cancelled Collaborative bounty) + 0.1 Eth (What I actually was Tipped for payment for my share of the Collaborative bounty) = **1.28 Ether ~= 682$** 

Which is approx. equal to the amount listed in the Leaderboard, ~697$

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

The expected behavior, of course, would have been that my Leaderboard position listed me as having completed 0 bounties (at most 1 really, since the second was cancelled), earned ~58$ (if tips are counted, 0$ otherwise and thus my actual position on the leaderboard should be at the bottom somewhere.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

For reproduction, here's a tentative guide (I can't really test it without potentially annoying some bounty submitters by starting-stopping work ):

1. Check leaderboard status
2. Start work on a project marked as traditional
3. Stop work on said project
4. Start work again
5. Submit work.
6. Check leaderboard status

This would check if the bug happens no matter if there was a project category change or not. AKA., does it count in the leaderboard as 2 completed bounties (it is probably necessary to wait till the bounty is done / mark the bounty as done to see the results I'd assume)

1. check leaderboad $ amount
1. Start work on a project
2. Submit work on a project
3. Get owner of project to Cancel / award money to someone else.
4. Check leaderboard $ amount

It's probably a good idea to check if it's just when a project is cancelled with submitted work that it counts, or if it's also counted even though you weren't the one paid out to.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

I'd suggest going through the Leaderboard code, seeing how it counts completed bounties, $ amount earned... and checking to see if the logic used takes into account cancelled bounties, collaborative/competition type projects, etc... or just awards everything to everyone who so much as touched the bounty (AKA., _Started_ work on it).

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

When I am again classified as a 0.1 Eth earning Leaderboard Minnow ;)

More seriously, when the $ amount and number of bounties completed properly reflect the profile page and the actual work done, and is capable of taking into account Competition/Collaborative bounties that might split the Bounty Amount between participants.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

https://gitcoin.co/issue/gitcoinco/skunkworks/75/552
Collaborative project with the 1.1 Eth reward, of which only I Submitted the work before it was cancelled.
![image](https://user-images.githubusercontent.com/10536344/41619266-ec5dadfe-7405-11e8-93d3-358bb26d7d22.png)

https://gitcoin.co/issue/gitcoinco/gitcoinco/42/563
GIF contest, which I didn't win but still submitted work for once, but Started-Stopped in the middle
![image](https://user-images.githubusercontent.com/10536344/41619376-4dff0418-7406-11e8-98d2-2052bb139094.png)

This one also has Fenxxx encountering an error after sending several submission transactions, which I believe is already documented somewhere on the Issues page.

https://gitcoin.co/profile/bockp
my profile

https://gitcoin.co/leaderboard
The Leaderboard

**Comment by owocki** [comment]
good detective work!  you are correct that this bug has it's roots in the recently launched contest bounties and how it was paid out.

im going to try and find some cycles later to put in a root cause fix

**Comment by PixelantDesign** [comment]
Thanks for the **extremely thorough** bug report @bockp!

**Comment by owocki** [comment]
didn't forget about this one; just been AFK for a few days.. its on the TODO list

**Comment by mbeacom** [comment]
@bockp Thanks for the detailed bug report! I just wanted to ping you here and let you know we haven't forgotten about this issue.  We'll try to have a fix out shortly!

Thanks again!

**Comment by bockp** [comment]
@mbeacom No worries, I trust you're doing all you can :)
From what I've seen, you've got an excellent team :+1:

**Comment by owocki** [comment]
e6c75aa4e0abbc15d2258bdc776347cccdb0ccb6 should fix this

**Comment by owocki** [comment]
a7baae3c99e11c26991f973b0232560d5ba91752 too
