### ISSUE TITLE
States "please review questions" - but there are no questions

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1509]
pressed enter to early - wanted to upload this:

![selection_084](https://user-images.githubusercontent.com/111600/41623528-56ea647a-7413-11e8-9ea4-2ca03d59af8e.png)

here: https://github.com/walleth/walleth/issues/143#issuecomment-398536666

**Comment by owocki** [comment]
hat tip @ligi for the bug report

**Comment by ligi** [comment]
Had a good smile there - reminded me about this meme:

![](https://cdn.dopl3r.com/memes_files/gary-0-friends-wished-you-a-happy-birthday-want-to-look-back-on-past-birthday-see-birthday-memories-memories-VrNpr.jpg)

**Comment by owocki** [comment]
olololol

**Comment by PixelantDesign** [comment]
This will be adrressed in the Gitcoinbot update
