### ISSUE TITLE
typography cleanup after PR 116

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#151]
from https://github.com/gitcoinco/web/pull/116

# 1

https://gitcoin.co/tip

for consistency.. might be worth doing the same thing for the tips flow...

# 2

http://bits.owocki.com/3N2V1400343O/Screen%20Shot%202017-12-20%20at%203.49.00%20AM.png

one other small cleanup thing: we should probably have consistent capitalization on the bounty detail page

**Comment by bumi** [comment]
## 1
The /tip application is `yge` in the code? (https://github.com/gitcoinco/web/tree/7680fc5425ae3524981b4ca912640d7af13c705c/app/dashboard/templates/yge) - correct? sorry, I am just figuring out what goes where :) 
there was a global style, I will update that and make a PR. 

## 2
what is inconsistent?  (I'm blind)

**Comment by owocki** [comment]
1. yep.  its a fork of https://github.com/youvegoteth/youvegoteth.github.io/
2. status: activated is lower case vs Experience Level: Intermediate (among maybe other things too)

**Comment by bumi** [comment]
ok, thanks. will check it out during the weekend.

**Comment by D3RPZ1LLA** [comment]
@owocki Looks like something has been merged.
Is this issue resolved? Please clarify

**Comment by owocki** [comment]
yes it has.. thanks for the bump
