### ISSUE TITLE
Put Admin Controls on one line

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1511]
### User Story

As an admin, id like to clearly see my controls in an organized manner.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Currently the buttons look messy.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Admin controls are on one line

<img width="1438" alt="screen shot 2018-06-19 at 11 07 06 pm" src="https://user-images.githubusercontent.com/238235/41635268-d70598c6-7415-11e8-860b-c4a01d9d296f.png">

**Comment by owocki** [comment]
👍 it might be worth putting admin controls in a modal eventually
