### ISSUE TITLE
As a funder, I would like the Gitcoin bot bounty amount to update when I add a contribution

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#1515]
It would be great to either update the existing Gitcoin bot funding amount or to have the Gitcoin bot send a follow up message when new contributions are added. 

### Why Is this Needed?

In case users come across the issue through Github they will see the correct available bounty.

### Current Behavior

No updates are made to Gitcoin bot amounts. See for example: https://github.com/paritytech/parity/issues/8835

### Definition of Done

Gitcoin bot displays correct available bounty on Github when new contributions are added.

**Comment by owocki** [comment]
this is a really good idea.

**Comment by kuhnchris** [comment]
The bot is verbitim regarding adding tips and other fundings, so I'm closing this one.
