### ISSUE TITLE
Avatar Bug on Mobile

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1527]
From SeironWP [4:13 PM]
Hi. But report: when I use the direct link to avatar maker from medium post, the menu is empty on mobile and I can't save avatar or log in.

![screenshot_20180621-221344](https://user-images.githubusercontent.com/238235/41754357-0c90fa90-75a0-11e8-93e1-d8bc6a95005a.png)

**Comment by SaptakS** [comment]
I am unable to reproduce this. The menu does show me the entire nav bar. Also on scrolling, I get to see the avatar builder properly. @mbeacom @thelostone-mc can you reproduce?
