### ISSUE TITLE
explore the idea of a gas faucet

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#153]
per @jasonrhaas 

> It’s definitely a barrier to entry. It would be cool if there was a way to add a ” gas credit” to a contract. So basically you claim a gitcoin bounty, gas is loaned to you to get started, and then the gas is deducted once you get paid.

more ideas here: 

https://twitter.com/owocki/status/943465549740179456

**Comment by owocki** [comment]
https://github.com/gitcoinco/skunkworks/issues/10

**Comment by stellarmagnet** [comment]
with the ux enhancement of "expressing interest" for an issue, can't you make that off-chain interaction? then the bounty issuer will select the best person to begin the bounty from the list of people who have expressed interest. This way msg.sender is the issuer, hence you assume the bounty issuer will have gas, right?

what i'm trying to say is: does the claimant have to be msg.sender, or can you upgrade the contracts so it's always the issuer?

How many of the interactions in the current flow relate to the claimant needing gas?

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/173

**Comment by owocki** [comment]
> with the ux enhancement of "expressing interest" for an issue, can't you make that an off-chain interaction? then the bounty issuer will select the best person to begin the bounty from the list of people who have expressed interest. This way msg.sender is the issuer, hence you assume the bounty issuer will have gas, right?

this is a good idea.

> what i'm trying to say is: is it really necessary for the claimant to be msg.sender during the bounty flow, or can you upgrade the contracts so it's always the issuer [or some white list of mods, assuming you are some kind of reputation-based DAO]? they are the ones in control of managing the budget, after all.

i like this idea.. once we move over to https://github.com/ConsenSys/StandardBounties/ this will definitely be possible

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/173
