### ISSUE TITLE
Tracking Module for Gitcoin

### ISSUE THREAD

**Issue by SaptakS** [gitcoinco/web#1532]
### User Story
Create a tracking module to allow tracking of user actions throughout gitcoin platform.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
We would like to track the user actions for better usability testing and improving the UX

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

**Comment by mbeacom** [comment]
We have `UserAction` on the BE.  Is that what you're looking for?
