### ISSUE TITLE
Remove 'Dibs' from Gitcoin Bot comment on Github

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1535]
### User Story

As a funder, I'd like to remove all reference to 'dibs' in approve only bounties where work is started by approval. 

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
<img width="671" alt="screen shot 2018-06-24 at 10 43 49 pm" src="https://user-images.githubusercontent.com/23297747/41832283-378a38a8-7800-11e8-83b1-097b179efc17.png">

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently, the first person on an 'approved' bounty still sees '1st dibs', which isn't the case in this setting.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Remove 1st dibs, 2nd dibs, etc. from the wording in this scenario.

**Comment by vs77bb** [comment]
@thelostone-mc @SaptakS Just added this to triage, this would be a quick win if we can remove this language soon, still causes confusion to have 'dibs' written when it's really approval-only now (and the first person does not have dibs).

**Comment by vs77bb** [comment]
@thelostone-mc This is not the case... [here's a regular bounty](https://github.com/ethereum/solidity/issues/4891) where it's showing up. 

![screen shot 2018-09-06 at 8 44 44 am](https://user-images.githubusercontent.com/23297747/45161292-1ede1a00-b1b1-11e8-9ab5-ccfc881d92a0.png)

**Comment by vs77bb** [comment]
Even for 'Co-op' bounties, I don't think 'dibs' makes much sense anymore... really think it can be removed everywhere

**Comment by mbeacom** [comment]
@vs77bb Do you want `dibs` removed from **ALL** gitcoin comments then (including project type `traditional` / permission type `permissionless` ?

**Comment by lazaridiscom** [comment]
Possibly this helps you decide: I did not understood the `dibs` word/concept at all (still don't understand it).
