### ISSUE TITLE
[Bug] As a funder, I cannot approve a bounty hunter for work.

### ISSUE THREAD

**Issue by pelsasser** [gitcoinco/web#1537]
### User Story
As a funder, I cannot approve a bounty hunter for work.

### Why Is this Needed?

*Summary*: To allow work to progress.

### Description

*Type*: Bug
Recently when trying to approve workers on permissioned bounties, I am getting the error shown in the below screenshot.  Notice the `cancel bounty` button appears, I am logged into metamask with the funding account selected.

![image](https://user-images.githubusercontent.com/15096737/41851302-aa9af078-7844-11e8-9953-c9e601af2a0a.png)

### Current Behavior
Cannot approve a worker

### Expected Behavior
Can approve a worker

### Reproduction
See screenshot, seems to happen across all permissioned bounties when clicking the provided link in the github issues comment. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
ref: https://github.com/MARKETProtocol/MARKET.js/issues/39

**Comment by owocki** [comment]
@SaptakS @mbeacom 

this is not related to accepting work (which is baed on the users ETH address), it is based upon approving workers (which is based upon github login)

i believe this is related to this line of code https://github.com/gitcoinco/web/blob/master/app/dashboard/views.py#L777-L817

specifically

```
is_funder = bounty.is_funder(request.user.username.lower())
```

so the user must be logged into the system

**Comment by owocki** [comment]
@mbeacom @SaptakS i suggest the following two courses of action

IMMEDIATELY

1. Update the error message to tell the user to login.

SOON-ISH

2. If the user is not logged in, present them with a 'please login first' modal

**Comment by mbeacom** [comment]
@owocki Adding the message now.

**Comment by SaptakS** [comment]
> so the user must be logged into the system

@owocki Okay. I will update the message. But if the user isn't logged it, how does it pass [this if condition](https://github.com/gitcoinco/web/blob/master/app/dashboard/views.py#L782-L784)?

**Comment by mbeacom** [comment]
We pushed a change to alert unauthenticated users to login when attempting a worker mutation.  I have created a follow up issue to implement a login modal in #1790

Thanks for reporting this!
