### ISSUE TITLE
browser notifications for tips/boutnies

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#154]
from slack https://gitcoincommunity.slack.com/archives/C7A4F4UHK/p1513794930000156

Hello All. I have a suggestion related to the notifications when a bounty is added. We can send browser notifications alongside email notifications for new bounties to the Users who have subscribed. Let me know your thoughts around this. Thanks.

**Comment by stellarmagnet** [comment]
I would add some requirement to this, to allow the user to limit notifications to only the repos that they have starred via github, or only one notification per day? This would be very important as gitcoin becomes more active.

**Comment by kuhnchris** [comment]
I guess that was mitigated by the "notifications" implementation, correct?
