### ISSUE TITLE
Add the ability to attach *any* ERC20 token to a bug-bounty (starting with LPT - Livepeer Token)

### ISSUE THREAD

**Issue by chrishobcroft** [gitcoinco/web#1542]
### User Story

As a _holder of a budget of ERC20 tokens_, I want to **attach any ERC20 token to a bug bounty**, so that more people can `share in the value we create together`.

### Why Is this Needed?

The current state, as I understand it, is that bug bounties on gitcoin can be paid out using ETH (Ethereum), or using a token chosen from a limited set of options on the website.

This is a problem because it massively limits user adoption of gitcoin from Ethereum-based smart-contract projects, who are focussing on decentralising through widespread adoption of their project's own token.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

The existing implementation of gitcoin does not allow me to attach a token to a bug bounty _unless_ that token already has a published $ value.

This realisation gave me a reason to investigate how your system works in more detail, and I believe that the ability to easily add _any_ ERC20 token based on the tokens held in a user's MetaMask account would substantially ease the adoption of gitcoin into smart-contract based projects with their own token.

[comment]: # (Feature or Bug? i.e Type: Bug)
### Current Behavior

In order to use an ERC20 token for my project, as I understand it, I must:

1. Raise an issues for someone to add my token for both tipping and bounties.

2. Get someone to deliver these issues (probably paying them with Eth using gitcoin.co).

3. Add a token in my token settings

4. Even then it doesn't work, because my token doesn't have a $ value yet, and so it can't translate back into the greenback, so the website breaks :(

![image](https://user-images.githubusercontent.com/2212651/41868634-f3640c28-78b6-11e8-964e-fb11d5cbed13.png)

I understand that you are probably using this system to fund development of itself, and I applaud you for that.

And I understand that you are majoring on the community of holders of ETH - because this is where the $ value lies right now.

But for many developers, the most interesting work possibly lies in the most innovative projects - which might include some of the projects with fresh tokens, very early stage, no $-value yet (and no real need to have a $ value either _yet_).

There's also this anathema that in a decentralising eco-system you are still `"converting back into USD"` as though everyone in the world cares about USD. But I'm digressing a little now.

Bottom line: you are **not** making it _as easy as it could_ be for people with a budget of ERC20 tokens to share out this value, and fund the crowd on a project-basis.

### Expected Behavior

That I don't need to _enable this token_ in 
![image](https://user-images.githubusercontent.com/2212651/41869102-3d891b9e-78b8-11e8-8fe7-14ef254a9749.png).

![image](https://user-images.githubusercontent.com/2212651/41867973-f0928922-78b4-11e8-8167-3544d4d87436.png)

That I can just select automatically from a list of tokens that I own - e.g. in my account controlled by my MetaMask - and tie those "ChrisCoins" to literally *any* bug on GitHub / gitcoin.

### Reproduction

0. Go to https://gitcoin.co/settings/tokens

1. Add LPT and do the transaction thing in MetaMask

2. Go to https://gitcoin.co/funding/new

3. Under "pricing", select LPT as the denomination

4. Enter an amount of LPT to pay

5. Fill in the rest of the form and click "Fund Issue"

6. Get this error message:

![image](https://user-images.githubusercontent.com/2212651/41874893-83a8ba38-78c9-11e8-88f2-c6793afb2a53.png)

So it appears that _unless there is a published $ value to the currency_, then this system won't work.

### Solution

1. gitcoin could scan the user's MetaMask account for all tokens, and just let the user select from those.

2. Also, provide a button called "maximum amount", which can pull the token balances.

3. Allow attachment of any ERC20 token into a smart contract which performs a simple escrow system.

### Definition of Done

"Done" is when I can attach `any amount` of `any ERC20 token` _that I hold_ to a **gitcoin** bug-bounty.

[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information

See below for the sad state I am in right now.

My project's token - `Livepeer Token (LPT)` - _has actually been added to gitcoin already_ - **but only for "tipping", and not for payment**.

Or perhaps it's something to do with the fact that LPT has no $ value available to the system.

But either way, as someone holding funding from a decentralising project, it doesn't allow me to do what I want to do, which is to pay someone in any currency I hold, if they are willing to receive it.

![image](https://user-images.githubusercontent.com/2212651/41867400-55e4a244-78b3-11e8-8cab-94aa4f56a84b.png)

**Comment by owocki** [comment]
> The existing implementation of gitcoin does not allow me to attach a token to a bug bounty unless that token already has a published $ value.

@PixelantDesign @SaptakS this seems like an oversight with respect to the new funder form.  i think we should probably remove the USD greater than 0.01 validator for the time being,

and after that, then think a little more strategically about the some of the (amazing, thank you @chrishobcroft ) suggestions provided above

**Comment by chrishobcroft** [comment]
It's a real pleasure to be able to provide feedback, and for it to be gladly received!

If any of you guys mentioned above would like some LPT, please drop me an email with your Eth address (preferably in some kind of Web 3.0 enabled browser) chris at livepeer dot org

**Comment by chrishobcroft** [comment]
And yes, I would be interested to see whether this works if you remove the $ value validator...

And then (fingers crossed) we can start sharing stakes in Livepeer with video-tech development community.

Hooray!

**Comment by owocki** [comment]
d991c86d54c40916398abeed04a008d5057fd84f should fix this issue.  @chrishobcroft pls try at http://gitcoin.co/new 

@SaptakS let me know what you think of d991c86d54c40916398abeed04a008d5057fd84f

**Comment by PixelantDesign** [comment]
Thanks for the feedback and reporting this bug! @chrishobcroft

**Comment by SaptakS** [comment]
@owocki I had a look into the commit. Seems good as a quick fix. As of fixing it twice, I think we can hide the USD field and the informations that are not relevant for the ERC20 tokens. Thanks @chrishobcroft so much for pointing this out.

**Comment by chrishobcroft** [comment]
@owocki it worked!

https://forum.livepeer.org/t/transcoder-campaign-0x34555-livepeer-community-node-berlin/211/14
