### ISSUE TITLE
avatar UX thing -- bust cache upon avatar change

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1544]
if i 
1. go to my profile
2. go to avatar builder and update my avatar
3. go back to my profile

my avatar should update.

we should be busting the cloudfront cache upon updates to the avatar or the profile in general. 

# implementation path

one important key we can update is the `last_github_auth_mutation` cookie.   we could also add a more generalized cookie that can be updated whenever we need to bust the cache

**Comment by mbeacom** [comment]
@owocki Are you experiencing some issue viewing the latest avatar? The avatars are salted with a hash and shouldn't need busted.

**Comment by owocki** [comment]
yes, the avatar stays the same if you follow repro steps 1-3 above.

> Invalidating CF cache every time someone updates their avatar will probably surpass the 1000 invalidations monthly and get expensive

i dont think we should invalidate the entire cache.   we should just update the `last_github_auth_mutation` cookie, which will invalidate the cache for just the currently logged in user.
