### ISSUE TITLE
Scrolling on "home" lags or doesn't work with scroll wheel

### ISSUE THREAD

**Issue by michelgotta** [gitcoinco/web#1545]
### Why Is this Needed?

User should have a natural scrolling experience of the "home" landingpage even with a scroll wheel mouse.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
Bug: Scrolling on home landingpage lags or hangs with scroll wheel mouse. Using a old but gold Logitec scroll wheel mouse on Chrome.

### Expected Behavior
Should scroll.

### Solution

I think there are some flaws on the markup and css. `<div id="landing_page_wrapper"/>` has `overflow-y: scroll;` which should be avoided to be used on a whole content element. The whole `<body>` should be the element that scrolls. `<nav class="navbar …">` should be position fixed and should be wrapped like on "issue explorer" for example.

**Comment by michelgotta** [comment]
@owocki Current version of Chrome.

**Comment by owocki** [comment]
@mbeacom @SaptakS @thelostone-mc does anyone have a scroll wheel mouse to repro with?  i ahve one at home, but am traveling right now so cant attempt a repro
