### ISSUE TITLE
As a funder, I want to be able to put more granular estimates in my bounty size, so I can get more granular estimates of success rates right in the form.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1548]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder, I want to be able to put more granular estimates in my bounty size, so I can get more granular estimates of success rates.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

This is spurred by a convo on consensys slack and by https://twitter.com/GetGitcoin/status/1001915178928177152

We want this so that we can do interesting data science on thet data.  Also,  we should experiment with adding these benchmarks into the UI like we do for USD pricing 

> We have created anchor points in the UI to help guide you at $40/hr, $80/hr, and $120 per hour. In general, we’ve found that:

   if you offer $120 per hour, you will have a 95% success rate.
   if you offer $80 per hour, you will have a 83% success rate.
   if you offer $40 per hour, you will have a 69% success rate.
   if you offer $20 per hour, you will have a 54% success rate.

This information should just be built into the new funder form

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

**Comment by PixelantDesign** [comment]
yes! need to think through how to make this accurate!
