### ISSUE TITLE
As a user of Avatars, I'd like a a Gitcoin watermark so I don't have to tell people where the avatar came from (they just know)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1549]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user of Avatars, I'd like a a Gitcoin watermark so I don't have to tell people where the avatar came from (they just know)

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
For marketing / communications.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

**Comment by owocki** [comment]
@PixelantDesign any feedback on this?

**Comment by PixelantDesign** [comment]
I provided feedback and options on this ticket....https://github.com/gitcoinco/web/issues/1052
