### ISSUE TITLE
Request for new avatar attributes

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1550]
Is there a hair style, accessory, skin color, hair color, or something else you want to see on https://gitcoin.co/onboard/contributor/avatar?

Please describe the attribute you would like added in the comment thread below.

For the designers in the group, [here is a avatar creation guide](http://bits.owocki.com/1w3p2Q0w330u/gitcoin-avatarconstructionguide.pdf)

**Comment by owocki** [comment]
i'd like non unicolor backgrounds (stripes, polka dots, etc)

**Comment by mbeacom** [comment]
We'll want to modify the existing background handling in order to accommodate this.  Right now, it's simply using `svgutils.Line` and filling the dimensions of the avatar with the provided hex code.

**Comment by TimVanMourik** [comment]
I really love that you implemented this 😄 Hooray for non-essential gimmicks!

I'm looking a for a bit milder bearded (between 5 and 14 days of not shaving). And more colours of sweater (bordeaux red please)!

**Comment by BKDaugherty** [comment]
I'd love to see eye colors!

**Comment by pinkiebell** [comment]
Squirrels! I'm serious ;)

**Comment by pinkiebell** [comment]
Maybe we should ask the author of [1]. That would look nice.

[1] http://species-in-pieces.com/

**Comment by owocki** [comment]
spaceey looking shirts ... like youre a space cadet of some sort

**Comment by Luminessa** [comment]
More hairstyles, girly type choices, and clothing. Cute idea just needs a few more options. :)

**Comment by vikaskyadav** [comment]
@Luminessa  do check out #2028  :)

**Comment by owocki** [comment]
> More hairstyles, girly type choices, and clothing. Cute idea just needs a few more options. :)

plus one!

**Comment by owocki** [comment]
some ideas:
- burning man inspired outfits
- robes 
- space sci fi inspired stuff like [this](https://i.pinimg.com/236x/28/0d/53/280d5361074b7c47a61618fb2ca78e84--mace-windu-star-wars-jedi.jpg)

**Comment by ajayns** [comment]
Any examples to illustrate what exactly you mean by 'burning man inspired outfits'?

**Comment by owocki** [comment]
@ajayns 

for women:
http://conversationsabouther.net/wp-content/uploads/2017/09/20-marekmusil-burningman_faces.jpg
http://bits.owocki.com/3c1512c442e3/Screen%20Shot%202018-10-09%20at%202.56.28%20PM.png
https://i.pinimg.com/originals/97/64/5a/97645a94084c71751045ba5fb2f37f20.jpg

for men:
http://bits.owocki.com/d9e8e1da3eca/Screen%20Shot%202018-10-09%20at%202.56.49%20PM.png
http://bits.owocki.com/dca6554f1510/Screen%20Shot%202018-10-09%20at%202.57.03%20PM.png
http://bits.owocki.com/91239c56793c/Screen%20Shot%202018-10-09%20at%202.57.22%20PM.png

**Comment by owocki** [comment]
Some asks:

* items that celebrate Thanksgiving here in the US (Pilgram / Native American items)
* items that celebrate the holidays here in the US (Channukah / Christmas themed items)

**Comment by scottie** [comment]
Should be able to change colour of hair individually not linked to beard.
