### ISSUE TITLE
bug - issues on accept work page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1580]
![screen shot 2018-06-29 at 9 59 22 am](https://user-images.githubusercontent.com/513929/42104879-2d28a238-7b83-11e8-913a-da1011f6ef7c.png)

1. there is bleed on the left side of the 'gas amount' module into the right amount
2. the rounding issue .. it says $0 but should be rounded to the cent (0.00) amount

**Comment by SaptakS** [comment]
I am on it.
