### ISSUE TITLE
As a user, I want a tophat on the Gitcoin nav, so I can easily navigate between the major products.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1581]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want a tophat on the Gitcoin nav, so I can easily navigate between the major products.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Core products (Bounties, CodeFund, Secret Project, Grants) should be easy to nav to .

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No tophat

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Tophat on gitcoin.co/codefund.io

**Comment by owocki** [comment]
@StareIntoTheBeard @PixelantDesign @coderberry per our convo in the car.  how does this ticket look?  i move that we get this designed first then code it

**Comment by PixelantDesign** [comment]
I'll take a crack at this.

**Comment by owocki** [comment]
wooo looking forward to seeing a mock up.

**Comment by PixelantDesign** [comment]
Pending Tuesday's meeting.
