### ISSUE TITLE
As a potential paying customer, I want to see the pricing on the landing page updated, so I can more accurately think about my options

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1584]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a potential paying customer, I want to see the pricing on the landing page updated, so I can more accurately think about my options

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
The pricing on the landing page shows flat fees ($10k, $20k).  We should instead change this to reflect the fact that managed bounties are going to be monthly (or a monthly retainer).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Copy update

### Current Behavior
[comment]: # (Describe what actually happened.)
Total pricing

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Monthly pricing

**Comment by owocki** [comment]
cc @PixelantDesign @sprusr from the retreat

**Comment by PixelantDesign** [comment]
@sprusr when should we aim to update this?

**Comment by sprusr** [comment]
Hey @owocki @PixelantDesign I’m not sure why I’ve been tagged in this, and don’t know what it’s about! Wish I could have been part of a Gitcoin retreat though 😅 keep up the great work 💖

**Comment by PixelantDesign** [comment]
@ceresstation

Apologies @sprusr!

**Comment by kuhnchris** [comment]
@PixelantDesign I think we already updated this a couple of times on the front page - if this is still an open issue feel free to reopen this.
