### ISSUE TITLE
Disable Editing of Issue Description on Funder Form

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1588]
Happening with multiple projects...

Fr Nico: 
Our posting included an english description and then the same description translated to Chinese, however the posted offer only contains the English part
https://gitcoin.co/issue/decentraland/MANA-community-fund-learning-content/3/701
I addded three dashes --- separating both parts in the description...  maybe that unintentionally broke stuff?
Can we edit the content of the posting once posted? Or is the description in the blockchain?

And —->
https://github.com/gitcoinco/web/issues/1579
—-

Solution: 
Since we cannot sync edited information instantaneously to Github prior to funding an issue, we should display a read only of the issue details once a user has entered the github issue url.

We should also note that any edits to issue details need to be made on Github and will take 1 hour to sync with Gitcoin. Need to find appropriate placement of this info.

cc: @owocki @mbeacom

**Comment by owocki** [comment]
> we should display a read only of the issue details once a user has entered the github issue url.

this is a good idea.  easy fix too!

what if we also add a funder only 'sync title/desc from github' button?

**Comment by PixelantDesign** [comment]
@owocki That is interesting if we could make this work from a technical stand point.

As a funder, I would expect to see the button right below the Issue Description field. 
After I Edit my description on Gitcoin. Click the button to 'Sync to Github'. Get a checkmark next to the button I've just pressed. Continue completing the rest of the funder form.... Is this possible?
