### ISSUE TITLE
Contributor Landing Page QA

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1594]
- [x] All that's left is to do join Gitcoin ->  All that's left to do is to join Gitcoin

- [x] link to contributor page from landing page

- [x] **Update the green developer bar** to look like this (added learn more link that will take users to contributor landing page).
<img width="1432" alt="screen shot 2018-07-02 at 7 46 05 am" src="https://user-images.githubusercontent.com/238235/42163077-2024645c-7dcf-11e8-8de0-febcb94fa1cf.png">

- [x] **Add Testimonials**
Here is one we can use from CryptoMental.
"I think the great thing about GitCoin is how easy it is for projects to reach out to worldwide talent. GitCoin helps to find people who have time to contribute and increase speed of project development. Thanks to GitCoin a bunch of interesting OpenSource projects got my attention! "

- [x]  **Add header to this section** called *Repos Using Gitcoin*

- [x] Make two green buttons standard navy button with white text for easy legibility. Nice to have. Not a show stopper.
<img width="346" alt="screen shot 2018-07-02 at 7 51 09 am" src="https://user-images.githubusercontent.com/238235/42163085-27c9ea7e-7dcf-11e8-9175-d2972050ae67.png">
<img width="735" alt="screen shot 2018-07-02 at 7 51 22 am" src="https://user-images.githubusercontent.com/238235/42163087-2a9fc304-7dcf-11e8-9bd8-eb1827c6df92.png">

**UPDATE** : Navy blue makes it a lil hard to read -> updated the text color to white to address this

- [x] First line of each p was lined up. Nice to have. Not a show stopper.
<img width="1396" alt="screen shot 2018-07-02 at 8 04 32 am" src="https://user-images.githubusercontent.com/238235/42163010-e8c4946e-7dce-11e8-96b6-d57db74940b1.png">

- [ ] Link to the issues filtered by repo would be a nice to have. Not a show stopper.
<img width="1370" alt="screen shot 2018-07-02 at 7 51 31 am" src="https://user-images.githubusercontent.com/238235/42163036-fb2043ce-7dce-11e8-8fa5-05b9bd31cbde.png">

- [x] Update Testimonials

**Comment by owocki** [comment]
cc @arun1595 @SaptakS @thelostone-mc

**Comment by owocki** [comment]
/contributor does not seem to be linked anywhere

what are these random avatars? http://bits.owocki.com/1D3f1l001M0t/Screen%20Shot%202018-07-02%20at%209.38.05%20AM.png

> All that's left is to do join Gitcoin

Should read All that's left to do is to join Gitcoin

I just started a testimonials channel on the gitcoin community.  Check there for testimonials!

**Comment by owocki** [comment]
```
When I found Gitcoin I was gladly surprised that it took one thing and did it well.   IT took the Ethereum tech and used it as a bridge to technology with open source Jobs.  Even though Gitcoin is still in it's early stages, I think it's filled with potential to grow.

~ Daniel

==========================================================================================

Aditya

A lot of folks tell me that OSS doesnt pay the bills.  I think Gitcoin might be a solution to that.  Personally, I loev the Gitcoin community.  It's a platform for me to interact with really smart folks, learn from them, and collaborate.  I think Gitcoin is definitely pushing open source forward.

============================================================

The bounty process with Gitcoin is pretty amazing.  Just go on the website, find an issue you can work on, you claim it.  All you do then is submit your code to Github, get the code merged.  Once it's merged, the smart contract kicks in and sends the money to your Ethereum account.  The whole process is pretty smooth.  There's a giant slack community.  It puts the freelance market back in the hands of the communtiy!

Elan

===========================================================================

I really like Gitcoin because it's allowed me to get involved in some really interesting Open Source Projects.  I've written code for MyEtherWallet and Gitcoin itself.  I think Gitcoin is becoming a great asset for the Ethereum ecossytem.

Jack

===========================================================================

I came across Gitcoin 3 months ago.  I was hearing lots of ideas about projects involving cryptocurrencies, and I kept thinking "what about open source projects?".  I see Gitcoin as the next level of freelance, where you can not only help repos on Github, but get money out of it.  It is that simple and it works.

Miguel
```

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/1459
