### ISSUE TITLE
Running Tx out of gas will cause the bounty to infinitely refresh and never claim

### ISSUE THREAD

**Issue by ghost** [gitcoinco/web#160]
##### Description
Attempting to claim a Gitcoin bounty in which the transaction gas limit is truncated will use up the Tx gas, fail to claim the bounty, and then cause an infinite refresh loop in the browser in which there is no obvious error to the user as to what happened. There is no way to claim the bounty thereafter. Visiting the attempted claimed bounty will just cause the same refresh issue.

Steps to reproduce:
1. Attempt to claim a bounty on Gitcoin.
2. Change the MetaMask transaction to a lower gas limit than originally specified by MetaMask (e.g., cut to 100K instead of 170K).
3. Issue the transaction and wait for confirmation.

You will be taken to the Gitcoin page in which the blue "Your transaction has been posted to Web3" will exist, however, the Tx will eventually fail due to out-of-gas. The bounty will (rightly) not be claimed, and the claim page will refresh itself over and over again after the failed Tx is in the blockchain.

TxHash on mainnet:

https://etherscan.io/tx/0xb829ab12ee9cc0a61bec04db5e74c96f8329c613c26040d3ea21726a53e00055

##### Environment
* **Browser**: Firefox
* **Version**: 57.0
* **Subsystem**: Linux x64

**Comment by owocki** [comment]
thanks for the bug report!

hmm.. this line should catch the error.  wonder why its not working https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/pages/bounty_details.js#L219-L227

**Comment by 10a7** [comment]
`result[0]` is an object, not a number. 

![Screenshot of Firefox debugger](https://i.imgur.com/HOcFnJZ.png)

**Comment by owocki** [comment]
@10a7 happy to lend u some gas.  msg me on slack with a link to me saying this and also ur ETH address
