### ISSUE TITLE
Java/Javascript misunderstanding in Issue Explorer

### ISSUE THREAD

**Issue by IgorPerikov** [gitcoinco/web#1617]
### User Story

As a JVM-world developer, I don't want to see the javascript issues in explorer when the only checked box is `Java`

### Why Is this Needed?

Right now I have to check manually every issue to see whether it's java-based task or js

### Description

*Type*: Bug

### Current Behavior

Issue explorer shows Javascript and Java issues when label `Java` is chosen

### Expected Behavior

Issue explorer shows only `Java` labeled issues

### Reproduction

* https://gitcoin.co/explorer
* Tech stack -> tick `java`

### Solution

change `contains`-based logic with `equals`-based logic for labels search

**Comment by owocki** [comment]
Thanks for the bug report@  @mbeacom and i were just discussing the taxonomy of keywords and how were going to architect that on a go forward basis.  We'll make sure we solve this as part of that project

**Comment by vinny2020** [comment]
Agree that this really important. I am also a Java dev and scrolling though post after post of javascript jobs is not a good experience

**Comment by tedyoung** [comment]
FYI, I've had to turn off notifications, etc., because I keep getting notified of JavaScript bounties, which, as a Java developer, I'm not interested in.
