### ISSUE TITLE
View by Orgs Discussion

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1622]
**To be defined**

<img width="913" alt="screen shot 2018-07-10 at 1 47 44 am" src="https://user-images.githubusercontent.com/238235/42491557-49199390-83e3-11e8-886d-3bf651186bc5.png">

**Other Possible Ideas**

Nav
- Update adding the current issue explorer nav with the ability to choose between viewing by bounties or view by project.

Screen 1
- Clicking on a thumbnail takes a user to the profile of the org.
- Clicking on the View Bounties takes the user to the Issue Explorer view of the orgs

![orgview- copy 3](https://user-images.githubusercontent.com/238235/42656886-aac0e776-85ee-11e8-9de7-085ba7fc29ba.jpg)

Screen 2
- Reorganized top header, adding hiring link and the ability to follow along with stats.
- Hiring could be turned on in settings.
- Hiring badge could link to our jobs board or on the Org's site.

![orgview- copy 4](https://user-images.githubusercontent.com/238235/42656914-b9a1eb14-85ee-11e8-9b45-2eb6b513c15a.jpg)

Screen 3
- A mention on the upper left with a link to call out view by projects/orgs. This can link to the org thumbnails page.
![orgview-dropdown copy](https://user-images.githubusercontent.com/238235/42657080-376fca8e-85ef-11e8-832e-82b129b3dae8.jpg)

Screen 4
- Users get to this view by clicking View Bounties from the Org thumbnail page.
- Users can also select to see another project by clicking on the small thumbnail on the left rail.

![org view - inside](https://user-images.githubusercontent.com/238235/42657058-2e18576c-85ef-11e8-93cc-dbdf2bec041b.jpg)

**Comment by octavioamu** [comment]
Very nice @PixelantDesign 

Some ideas:

**screen 1**
Maybe the link to view bounties show the number of open ones
"view bounties (14)"  That can be some kind of activity endorsement.

maybe screen 2 and 4 can be in some way the same or show the same tasks/filters since what I want is work for that organizations 

Not sure, organizations and projects are different things, right? So a company can have different projects? If that true, should be a way to see the projects of that organization, like a general view of all open in all projects and if I get in the project, only see  that project description and tasks

Maybe a feature like "save search" but just for organizations/projects so if new tasks in that category I will be notified about it.

Another idea we already talked about is the direct link to contribution guides of the project.

**Comment by PixelantDesign** [comment]
> screen 1
Maybe the link to view bounties show the number of open ones "view bounties (14)" That can be some kind of activity endorsement.

Great Idea! I like that


> maybe screen 2 and 4 can be in some way the same or show the same tasks/filters since what I want is work for that organizations

Yea typically a profile page is just for viewing. Meant less for filtering, searching for work, etc.

> Not sure, organizations and projects are different things, right? So a company can have different projects? If that true, should be a way to see the projects of that organization, like a general view of all open in all projects and if I get in the project, only see that project description and tasks

Agree with this, need to align on taxonomy.

> Maybe a feature like "save search" but just for organizations/projects so if new tasks in that category I will be notified about it.

> Another idea we already talked about is the direct link to contribution guides of the project.
Yes! I've added it to the last screen, thanks!

**Comment by owocki** [comment]
comments

1. how is [this view](http://bits.owocki.com/1b1S2l2Y0Y1H/Screen%20Shot%202018-07-12%20at%204.49.07%20PM.png) diff from the org leaderboard?  more specifically, how can we dedupe the views?
2. how is [this view](http://bits.owocki.com/2k1Q293d1F2g/Screen%20Shot%202018-07-12%20at%204.51.31%20PM.png) diff from the current org profile view?

ideas on this ticket, in order of excitement level from me
1. screen 2
2. screen 4

it'd be good to see the 'edit profile' view for orgs where ppl can toggle things like 'were hiring'.  better yet, maybe we can build this into the current profile view

**Comment by owocki** [comment]
@mbeacom id like your opinion here since youre doing the backend profile stuff

@pelsasser mind taking 3 minutes to look this over and let us know if any of it excites you?

**Comment by PixelantDesign** [comment]
> how is this view diff from the org leaderboard? more specifically, how can we dedupe the views?
Maybe there is a way to elegantly combine these two.

Screen 2 is an updated view of [this](https://gitcoin.co/profile/gitcoinco)

> it'd be good to see the 'edit profile' view for orgs where ppl can toggle things like 'were hiring'. better yet, maybe we can build this into the current profile view

This should happen on Screen 2.
Hiring - easy to add an/on off toggle.
Org Bio - inline edit using pencil icon for those that have permission.
Org image and team member association - seems like these should be easy to pull in from GitHub.

Screen 3 and 4 are not exciting but user feedback has been consistent that searching the issue explorer to find work for a specific organization is the action they would take. Maybe it's a matter of adding this piece to the top to make it feel a little more personalized:

<img width="639" alt="screen shot 2018-07-12 at 7 48 40 pm" src="https://user-images.githubusercontent.com/238235/42665215-ad6e20ba-860c-11e8-8c2d-8e6818d212cf.png">

**Comment by PixelantDesign** [comment]
Viewing organizations and viewing a leaderboard serve two different purposes...

When a user is searching for an organization to collaborate with, they're wanting to learn about the mission of the project, who works there, evaluating how it aligns with their personal goals,etc. I'm not sure if a user would select working with an organization just because they've funded the. most bounties on our platform.

I could see leaderboard being a section/right rail part of the organizations view though.

**Comment by pelsasser** [comment]
@owocki - looking good!

**Comment by darkdarkdragon** [comment]
@PixelantDesign last variant is better
just one question - is screen #4 is still present in the last version?

**Comment by PixelantDesign** [comment]
@darkdarkdragon we aren't sure about screen 4 to avoid duplication of efforts but it seems like a natural place for users to look for work, thoughts?

**Comment by kuhnchris** [comment]
@PixelantDesign I guess Q1/2019 didn't really work out - do you have any status on this? (I think it's on the roadmap tbh)
