### ISSUE TITLE
V2 Metamask Connection State

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1625]
As a core team we'd like to clean up the UI for the metamask connection state to see if we can make it less obtrusive to the experience. This should clean up the screens and allow for more focus on core Gitcoin functionality.

https://github.com/gitcoinco/web/pull/1590

**Comment by PixelantDesign** [comment]
Seeing a bug here on the tooltip...
<img width="1739" alt="screen shot 2018-07-05 at 3 22 15 pm" src="https://user-images.githubusercontent.com/238235/42343744-0a155f04-8068-11e8-946b-c1a4ca507797.png">

cc: @thelostone-mc

**Comment by thelostone-mc** [comment]
Taken care of !
