### ISSUE TITLE
As a user, I want the cookie popup to not show up until the sumo popup is dismissed, so they don't overlap with each other?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1630]
**Describe the bug**
As a user, I want the cookie popup to not show up until the sumo popup is dismissed, so they don't overlap with each other?

**To Reproduce**
Go to homepage on mobile
1. wait for sumo popup and cookie popup to showup

**Expected behavior**
cookie popup shouldnt show up until after sumo popup comes up

**Screenshots**
[screenshot](http://bits.owocki.com/1D1i0v3B2k22/2018-07-05%2015.44.36.png)

**Comment by owocki** [comment]
@SaptakS is this an easy lift?  its stopping our facebook ads from going live

**Comment by owocki** [comment]
^^ this is stopping our facebook ads from going live

**Comment by owocki** [comment]
^^ this is stopping our facebook ads from going live

**Comment by PixelantDesign** [comment]
This seems to be working.
