### ISSUE TITLE
Make GitcoinBot Recognize Closed Issues.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1640]
As a user I'd like to interact with a smarter GitcoinBot that knows when an issue is closed.

Gitcoin Bot still comments after the issue is closed. Let's make GitcoinBot smarter.

<img width="1039" alt="screen shot 2018-07-06 at 12 46 53 pm" src="https://user-images.githubusercontent.com/238235/42390765-064447ba-811b-11e8-8778-811ec3e72643.png">

https://github.com/gitcoinco/web/issues/1386#issuecomment-403079718

**Comment by mbeacom** [comment]
Related:

https://github.com/gitcoinco/web/issues/1156
https://github.com/gitcoinco/web/issues/994
https://github.com/gitcoinco/web/issues/826 < I think you opened this one previously

**Comment by owocki** [comment]
i already put in a fix for this https://github.com/gitcoinco/web/commit/f04969afc78f3f93e63314c03c53afa581bf9155
