### ISSUE TITLE
metamask/mascara support

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#1646]
For users who can't/don't install the metamask extension,
we can point them to [1]; if the web browser has advanced service worker support.

See [2] for reference.

[1]https://wallet.metamask.io/
[2]https://github.com/MetaMask/mascara

**Comment by owocki** [comment]
thanks @pinkiebell -- we are also looking into using portis (see https://github.com/gitcoinco/web/pull/985 ) as a provider

**Comment by kuhnchris** [comment]
@owocki did you ever take a look at this or did we disregard this in favor of portis (which also went nowhere)?
