### ISSUE TITLE
Status of 'DoneOpened' on paid out issues that have had their statues manually changed prior to payout

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#1647]
**Describe the bug**

When a Gitcoin issue is manually marked as open by a moderator and then completed, it is marked as DoneOpen as in the screencap below.

**To Reproduce**

Manually modify the status of any Gitcoin issue and then attempt to accept a submission, changing the status to 'done'.

**Expected behavior**

A warning should occur that the issue will be paid out and the manual status will be replaced.

**Screenshots**

https://gyazo.com/05ac00b690f5a77c09fdf7d8b6da1422

**Desktop (please complete the following information):**

- OS: High Sierra
- Browser Chrome v. 67

**Comment by owocki** [comment]
thanks for the feedback.  this now seems to be fixed [screenshot](http://bits.owocki.com/203F0R1x3O3E/Screen%20Shot%202018-07-08%20at%206.11.55%20PM.png).  not sure if thats something you did @ceresstation ?

**Comment by thelostone-mc** [comment]
@ceresstation did you see this happen anywhere ?

**Comment by ceresstation** [comment]
@owocki Did you manually mark the issue as open before marking it as complete? This only occurs due to a conflict with override status changes + automatic status changes.

**Comment by owocki** [comment]
i didnt make any edits to fix this.  it was fixed when i showed up in my comment 10 days ago
