### ISSUE TITLE
Wrong profile in activities / messed up activity log

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#1659]
**Describe the bug**
Wrong profile on work_done, work_submitted activities.
Should be the 'fulfiller'.

For reference:
- https://gitcoin.co/issue/gitcoinco/web/1472/637
- https://gitcoin.co/issue/zeppelinos/zos-cli/122/622

I think the problem is in record_bounty_activity.

user_profile = Profile.objects.filter(handle__iexact=new_bounty.bounty_owner_github_username).first()
// if we have a fulfillment; we should use the handle from that fulfillment. right?

See work_done, work_submitted
https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/zeppelinos/zos-cli/issues/122&network=mainnet&standard_bounties_id=622&not_current=1

**Comment by pinkiebell** [comment]
Possible solution (Attention: not tested):

diff --git a/app/dashboard/helpers.py b/app/dashboard/helpers.py
index c1df6dab..beb14467 100644
--- a/app/dashboard/helpers.py
+++ b/app/dashboard/helpers.py
@@ -630,6 +630,10 @@ def record_bounty_activity(event_name, old_bounty, new_bounty, _fulfillment=None
             fulfillment = new_bounty.fulfillments.order_by('-pk').first()
             if event_name == 'work_done':
                 fulfillment = new_bounty.fulfillments.filter(accepted=True).latest('fulfillment_id')
+        if fulfillment:
+            maybe_user_profile = Profile.objects.filter(handle__iexact=fulfillment.fulfiller_github_username).first()
+            if maybe_user_profile:
+                user_profile = maybe_user_profile
 
     except Exception as e:
         logging.error(f'{e} during record_bounty_activity for {new_bounty}')

**Comment by owocki** [comment]
looking at this now

**Comment by owocki** [comment]
just ran migration in prod
