### ISSUE TITLE
dupe activities

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1661]
now i am seeing dupe ‘work started’ and an extra ‘new bounty’ event http://bits.owocki.com/2B2x3G1O0U3x/Screen%20Shot%202018-07-09%20at%2010.09.50%20AM.png

example issues:

1) https://gitcoin.co/issue/XLNT/gnarly/11/677
2) https://gitcoin.co/issue/raiden-network/raiden/1243/561
3) https://gitcoin.co/issue/zeppelinos/zos-cli/122/622

continuation of https://github.com/gitcoinco/web/issues/1659

**Comment by owocki** [comment]
@pinkiebell do you see any obvious place where in the mgmt command this could be caused?

**Comment by owocki** [comment]
here is the command i ran in prod

```
./manage.py create_activity_records --force
```

**Comment by pinkiebell** [comment]
if you run it with --force, it clears all activities.
Can you point me to a issue with duplicates?

**Comment by owocki** [comment]
> Can you point me to a issue with duplicates?

read the description of the ticket pls

**Comment by owocki** [comment]
if you set it with `@transaction.atomic()` it can be atomic, yes

**Comment by pinkiebell** [comment]
https://gitcoin.co/issue/zeppelinos/zos-cli/122/622
same here now.
But, API response is fine:
https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/zeppelinos/zos-cli/issues/122&network=mainnet&standard_bounties_id=622

**Comment by owocki** [comment]
i think i see the issue

one sec ill commit up a fix

**Comment by owocki** [comment]
looks like the frontend makes TWO API requests

http://bits.owocki.com/042q1G263q1i/Screen%20Shot%202018-07-09%20at%2010.34.37%20AM.png

one with `not_current=1` and one without that param.

what is the reason for making two API requests? i think we should only care about activites related to teh current bounty and we should migrate the actions to the `current_bounty=1` when we create a new current_bounty

**Comment by pinkiebell** [comment]
```js
const render_activity = function(result, all_results) {
  let all_activities = [];

  (all_results || []).forEach(result => {
    all_activities = all_activities.concat(result.activities);
  });

  let activities = process_activities(result, all_activities);

  activities = activities.slice().sort(function(a, b) {
//THIS ?    
return a['created_on'] < b['created_on'] ? -1 : 1;
  }).reverse();
  only_one_approve(activities);


```

**Comment by owocki** [comment]
here is my PR with a few fixes in it ( https://github.com/gitcoinco/web/pull/1662 ) and one outstanding question

**Comment by pinkiebell** [comment]
@owocki Nice catch!

**Comment by pinkiebell** [comment]
Next time I will give my network bar more room 😆

**Comment by owocki** [comment]
did some local testing.. merging soon

**Comment by owocki** [comment]
fix is in.. looks okay to me.  anyone else see an issue LMK
