### ISSUE TITLE
claim:  gas limit is set over limit

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#169]
##### Description

While claiming an issue, gitcoin sets the gas limit to value higher than the upper limit.
![limit](https://user-images.githubusercontent.com/5358146/34320824-bd005664-e7b6-11e7-94c3-ff93fc3af0e9.gif)

##### Environment

* **Browser**: firefox and chrome

**Comment by owocki** [comment]
invesitgation notes:

https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/168 was the issue being claimed 

gas value set was 10399964

**Comment by owocki** [comment]
interestingly, when i try to claim the issue the gas value that pops up for me is `171462`, which is roughly 1% of the gas value you were recommended @thelostone-mc

**Comment by thelostone-mc** [comment]
@owocki Just an hypothesis

What if there was a race condition situation where @eswarasai claimed it a few seconds before I claimed it before his was accepted.
I left the `calling dibs ^_^` message a few seconds after I tried claiming and it failed due to the hight gas value being set.

If you notice, both relatively happened around the same time: 

- gitcoin bot posted a msg @ `7:34AM`
- my comment @ `7:36AM`. 
I added this a few minutes after I had tried claiming it until which no one had claimed it which makes it safe to assume I had tried claiming it around the exact same time as __eswarasai__ claim was being accepted

<img width="1022" alt="screen shot 2017-12-26 at 4 16 40 pm" src="https://user-images.githubusercontent.com/5358146/34366957-38b719d4-ea58-11e7-9e5b-71f860fd3d4e.png">

**Comment by owocki** [comment]
woah, this is a really interesting thought..  youre right, they are close enough in time to possibly generate this type of condition.  i need to test this and handle the edge case if possible

**Comment by monokh** [comment]
To do the gas estimation, Metamask does a dry run of the contract method. I've seen that when the contract method causes an error, the gas estimation will be broken like this. Maybe this is intentional - so that you don't submit a transaction that would fail anyway. My guess is that in this case, the issue was already claimed and sending another transaction with the same parameters would error in the contract method.

**Comment by owocki** [comment]
5e55d46c165db1685e0fc985d3fabab91e6d1e88

perhaps this will help?!

**Comment by thelostone-mc** [comment]
@monokh makes sense
@owocki That oughta work! Closing this issue !!
