### ISSUE TITLE
IDEA --  Do we want to auto-translate visitors based upon IP addresses?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1695]
(not ready to be worked on ) 

 Do we want to auto-translate visitors experience based upon IP addresses?

**Comment by thelostone-mc** [comment]
Which means I would be served a hindi translated page cause my IP originates from India ? (if I'm a first time visitor )

**Comment by owocki** [comment]
upon further reflection, i think we would likely adhere to the users browser preferences

@mbeacom is that right? btw, when is this going live anyhow?
