### ISSUE TITLE
Add UI for work done by another party on a claimed bounty

### ISSUE THREAD

**Issue by mttmartin** [gitcoinco/web#1728]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, it is currently not clear what to do if someone starts work on a bounty which you've already claimed. I believe it would be useful to have some UI on the website which can lead users through this.

I recently claimed a bounty which someone else had afterwards completed while I was sleeping. I was more than happy to just transfer the bounty to this person, but it was not clear how I should do that. I was afraid that if I just stopped work, that someone else(i.e. not the person who had done the work) would claim it.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: It is currently not clear what one should do if this happens. Furthermore, as Gitcoin grows, we will need a scalable way to handle these situations. I believe that a feature like this could help automate some cases(such as when one party is happy to give up the bounty).

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
It's not clear what to do when this happens. I ended up reaching out to @vs77bb taking up some of his time. 

In the end I also ended up with a removed from bounty on my profile. This is not really appropriate in this case, because I had said I was happy to give up the bounty.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

It should be possible to have some UI which guides users through the situation resulting in either/both:
 1. Submitting request to Gitcoin staff to take a look at the issue
 2. Volunteer to transfer the issue to the person who has already done work

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: 
* Improve user experience for this use case while thinking about future scalability
 
### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

* Have a UI element(e.g.) button which the users can click from an issue
* Explanatory text on their current options
* Leads them to submit request to Gitcoin staff to help resolve issue or transfer issue to another person

@vs77bb any input you have on how this process might be improved from your perspective would be great

**Comment by owocki** [comment]
thanks for the thoughtful ticket.  i agree this part of the experince could use some firming up

**Comment by PixelantDesign** [comment]
Great suggestions. Thanks for reporting this @mttmartin.
