### ISSUE TITLE
Awaiting Decision Feature for Bounty Details Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1741]
Not ready to be worked on

### User Story

As a contributor I'd like to be able to notify the system that I'm waiting on a decision from the funder/repo owner on how to proceed.

https://github.com/balance-io/balance-manager/issues/318

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: No way to do this now

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Add an**Awaiting Decision** or **Pending Decision** button on the Issue details page.
- [ ] Once a contributor clicks this button, the github thread should be updated via Gitcoin Bot.
- [ ] When the funder has next steps, he/she should comment on the next steps. 
Once contributor understands how to proceed he can click **resume work**

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Thoughts @owocki @vs77bb?

**Comment by kuhnchris** [comment]
Do we no already have something like this now?
