### ISSUE TITLE
find a workaround for slow metamask/infura issues upstream

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#176]
https://twitter.com/metamask_io/status/951630806941749254

this happens on gitcoin all the time... (or.. all the time when infura is down it does)

we should find a workaround in which we just hardcode in the gas values... or we use our own geth node to run the estimategas

**Comment by kuhnchris** [comment]
I think we already finish this... I'll close it for now, please reopen if we still have gas issues.
