### ISSUE TITLE
BUG - emails to email_logger@gitcoin.co are cheiwng up our sendgrid credits

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1760]
email_logger@gitcoin.co

tjere are about 20k emails to this email address last month, and its chewing up our sendgrid credits.  i can't for the life of me figure out where they are coming from; we removed all refernce to this email address and `BCC_EMAIL` from our codebase.. but they still seem to be going out

**Comment by owocki** [comment]
@mbeacom do you think maybe stage server is the culprit?

im thikning about revoking our sendgrid key and creating a new one for prod if we can't figure this out

**Comment by mbeacom** [comment]
I agree that we should split off the keys for production/staging, if we opt to include a sendgrid key on staging that is.

Regarding `email_logger@gitcoin.co` - This exists in the prod env file it seems.

That's definitely the cause.  Removing from other repo now.

**Comment by owocki** [comment]
> In any case, that should resolve it now that BCC_EMAIL isn't set. We're not specifying that email anywhere else.

well. the problem is.. it doesnt..  i removed it and deployed on 7/11 and theres still emails going to that email address

**Comment by mbeacom** [comment]
🤔 I'll take a look through the logs and see if anything stands out.

**Comment by owocki** [comment]
i suspect that stage or some other environment is doing this.  i vote that we revoke the current sendgrid key and create a new production only one

**Comment by owocki** [comment]
derp ; https://app.sendgrid.com/settings/mail_settings was set to auto BCC this email address

i just turned it off
