### ISSUE TITLE
Show Cancelled Bounties Latest Activity in Profile 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1770]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Not shown now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Not shown in profile 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Show in profile

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Update Funded Bounties Module to be Bounties
- [ ] On the bounties tab add a filter using a drop down to show Cancelled Bounties (upper right)
- [ ] Test the functionality
- [ ] Link a PR to this ticket
- [ ] Review with a Gitcoin core tam member

**Comment by chiptus** [comment]
Can I start with this issue?

**Comment by chiptus** [comment]
Would love to get some pointers on where to look (my first issue). 
Will this be mostly changing the template, or also the `profile` endpoint? or class?

And how can I test this on my machine? I have the env running, I probably should enable the login (by adding the right values for a github app in the .env file, right?)

Can I make a fake profile with cancelled bounties and other types of bounties so I can see a full list on the profile page?

**Comment by PixelantDesign** [comment]
@SaptakS are you handling this in the profile rework?

**Comment by chiptus** [comment]
I'm not sure if I should continue (actually start, since I haven't done nothing but start the env)
I'm still trying to understand your codebase.
I see on `profile.html` that there are three sections - in-progress, funded, and completed.
Do you mean that we should have one section with ability to choose the right type of bounty? in-progress/funded/completed/cancelled?

**Comment by PixelantDesign** [comment]
@saptaks was this part of tge recent profile work?

**Comment by PixelantDesign** [comment]
@chiptus we have some other work if you’re interested!

**Comment by SaptakS** [comment]
@PixelantDesign Yes. This is already handled [here](https://github.com/gitcoinco/web/pull/2237)

**Comment by PixelantDesign** [comment]
thanks! closing!
