### ISSUE TITLE
Gitcoin Bot Bounty Value Missing on Github Issue 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1771]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

From Tim Van Mourik - @Owocki, @PixelantDesign this bounty's got funding and an approved worker @hubris but no @gitcoinbot message. This happened earlier and a Gitcoin issues was made in gitcoinco/web#1627

https://gitcoin.co/issue/TimVanMourik/GiraffeTools/78/801

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
See Above

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

Gitcoin Bot should display the value of the funded issue.

**Comment by owocki** [comment]
was due to github suspending gitcoinbot.  we've since gotten it unsuspended
