### ISSUE TITLE
Gas Price Showing as a Funded Issue?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1773]
**Describe the bug**

Gas price showing in issue explorer as a separate funded issue.

![image 12 12](https://user-images.githubusercontent.com/238235/42823075-a3073ae8-89aa-11e8-9785-5a1bc34a45eb.png)

**Expected behavior**

- [ ] Make it not show

**Comment by owocki** [comment]
i think this has to do with the issue with gas prices over the last several weeks and the tx's getting resubmitted

**Comment by owocki** [comment]
i can't find these bounties on the explorer? have they been hidden?

**Comment by SaptakS** [comment]
I can't reproduce it either.

**Comment by thelostone-mc** [comment]
Closing as unable to reproduce ! If it happens again -> we'll reopen it and dig into it
