### ISSUE TITLE
bug: need auto refresh on gitcoin submission pending page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#179]
# repro steps

1. submit a change (claim, new bounty) to the blockchain.
2. wait on issue page
3. transaction will confirm, but page will not auto refresh.

screenshot: http://bits.owocki.com/3g01182g000Q/Screen%20Shot%202017-12-27%20at%203.58.18%20PM.png

google chrome, latest version, on a mac

**Comment by EmanuelKuhn** [comment]
I didn't manage to reproduce this issue on the latest version of google chrome for mac on the ropsten test network.

Steps I took:
1. Submit a new bounty on the ropsten test network.
2. Wait on the issue page.
3. The page did auto refresh when the transaction confirmed.

Observation:
- The issue might only arise when not using the ropsten test network,
- or maybe it has already been fixed
