### ISSUE TITLE
Add Deep Link to Explorer Search

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1791]
### User Story

As a user I'd like to know the URL of what I've just entered into the search field and have a deep link for reference.

**Example:** When a user searches infura. User should see infura in the url to be able to later reference this.

<img width="1431" alt="screen shot 2018-07-19 at 7 02 12 am" src="https://user-images.githubusercontent.com/238235/42938907-e2df3116-8b21-11e8-805a-69c8b012da86.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Implement deep linking for when a user searches a term
- [ ] This implementation is tested

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Review with a core team member

**Comment by thelostone-mc** [comment]
This was the intended behavior to prevent the urls from being super long (atleast how I remember it)
cc @owocki @mbeacom @SaptakS 

- Should we not trim the URL ?
- If that happens -> should we also remove the localStorage filters so that when users share url , the ones who click on it don't get their  previous filters added on top of this ?

**Comment by PixelantDesign** [comment]
How big of a lift?

Perhaps getting back in the ability to reference what I've just searched is a first step. Then work towards the clean url in a later iteration.

Thoughts?

**Comment by owocki** [comment]
My 002 wei is that the functionality of having shareable URLs greatly outweighs the marginal aesthetic add of having short urls.

**Comment by frankchen07** [comment]
hey @thelostone-mc - I'm helping Alisa manage some check-ins on August bountied milestones. How does this ticket fit into your current workload, and is there anything unclear that's blocking you?

**Comment by thelostone-mc** [comment]
Hi @frankchen07 thanks for checking in :)
My only concern is that we've right now -> when a user applies a few filters and closes the browser and revisits the page -> the same filters remain applied (via localStorage) and the URI remains `gitcoin/explorer`

If I were to do this  -> i would have to remove localStorage which means we don't retain the selected filters. 

Either 
- add deep link -> to make URLs easier to share but compromise on ability to retain history. The URL may become super long
- stick to what we have thus retain filters a user selected previously
- add a share button or so which shows the url ( but the address remains the same )

What do you think ?

**Comment by frankchen07** [comment]
From my understanding (from just the conversation above) it sounds like the tradeoff is keeping vs removing localStorage filters which results in:

keeping localStorage filters
1. shorter URLs, but unshareable
2. retains user history
3. may cause an issue with previous filters being applied on top of a shared URL

removing localStorage filters + add deep link
1. potentially long URLs
2. does not retain user history
3. won't cause an issue with previous filters being applied on top of a shared URL

Following what @owocki said, shareable URLs importance > aesthetic importance. I think it makes sense to remove localStorage filters for now and add the deep link to get the sharing functionality. This way users can still have a deep linked URL to their search results in their browser, despite it being long. We can figure out how to help them save their searches in a more orderly fashion in a later iteration. 

That's my two wei without seeing the intricacies of `localStorage` @mbeacom & @owocki - thoughts?

**Comment by thelostone-mc** [comment]
This does mean users would see bounties from testnet as well if they were to visit `gitcoin.co/explorer` forcing them to go update the filters
 
@mbeacom this could be the perfect opportunity to burn out a lot of code and ensuring only mainnet bounties appear on live 😁🔥

Is everyone okay with it  ? 
@owocki @SaptakS @mbeacom

**Comment by owocki** [comment]
> This does mean users would see bounties from testnet as well if they were to visit gitcoin.co/explorer forcing them to go update the filters


in my mind, we wouldnt blow out all the filters.. we would set them to default filters (probably just 'network = mainnet' )

i do think that its important to be able to browse rinkeby bounties on the dapp, unfrotunately.  it allows users to get familiar with our product without using any of their ETH
