### ISSUE TITLE
Too Many Alerts

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1792]
**Describe the bug**
3 Alert Messages are displaying.

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

![pasted image at 2018_07_18 11_50 pm](https://user-images.githubusercontent.com/238235/42940142-6d7e26e8-8b26-11e8-9d7a-6b554cdedd0e.png)

**Definition of Done**
- [ ] Turn off very top banner

**Comment by pinkiebell** [comment]
Please review #1796
