### ISSUE TITLE
Include link to bounty in Gitcoin bot's post

### ISSUE THREAD

**Issue by bdresser** [gitcoinco/web#1794]
The gitcoin bot is super useful. It'd be even more useful if the initial post included a link to the bounty on gitcoin.co!

<img width="860" alt="screen shot 2018-07-19 at 10 44 58 am" src="https://user-images.githubusercontent.com/1016190/42960487-d2897726-8b40-11e8-8abf-58f504ab6f4d.png">

**Comment by mbeacom** [comment]
Updating this now - Thanks @bdresser

**Comment by mbeacom** [comment]
@bdresser Added in: #1795 
Thanks!

**Comment by bdresser** [comment]
Saw a bot post this morning, saw the link, thought maybe I had opened this without noticing it was already there.. but nah you're just on top of it! 

thanks 😺
