### ISSUE TITLE
View by Org V2

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1799]
### User Story

As a contributor I'd like to be able to learn more about an organization when I specifically search for issues by a certain project.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Add a section above filtered list of issues when user searches by specific project/repo.
- [ ] This page will link from org overview page
- [ ] Add repo thumbnail
- [ ] Hiring Info (activated via in profile)
- [ ] Github and web url link
- [ ] Members on this project (pull from profile)
- [ ] View contribution Guidelines
- [ ] User will get to this page by clicking org overview page or by searching for a project in the search box.
- [ ] Add ability to click on orgs in left rail to view info
- [ ] Build org overview page
- [ ] Ensure the search by repo works and creates a url that can be deep linked.
- [ ] All functionality is tested

### Additional Information
Leaderboard is out of scope.

![orgview-test](https://user-images.githubusercontent.com/238235/42981191-f95bd0ca-8ba8-11e8-9587-059cbced6765.jpg)

<img width="725" alt="screen shot 2018-07-19 at 11 09 35 pm" src="https://user-images.githubusercontent.com/238235/42981196-fce23d2e-8ba8-11e8-8791-12cdcb72fbea.png">

**Comment by owocki** [comment]
where do we source the desc for eaach org?

**Comment by thelostone-mc** [comment]
@PixelantDesign
- `Follow` button ? I don't believe this has been scoped out from the backend yet
- `View Contributing guidelines`. Where are we getting the input for this  ?

**Comment by kuhnchris** [comment]
Superseeded by #4576
