### ISSUE TITLE
Cannot fund issues

### ISSUE THREAD

**Issue by pelsasser** [gitcoinco/web#1801]
**Describe the bug**
After clicking `Fund Issue`, not meta mask approval shows up and there are errors in the console.

**To Reproduce**
Create a newly funded issues (or attempt to)

**Expected behavior**
Meta mask approval pop up

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/15096737/43015147-f0a05bc8-8c0b-11e8-9104-e0a819a77e07.png)

**Desktop (please complete the following information):**
Ubuntu 16.04
Chrome

Failed to load resource: the server responded with a status of 504 ()
new:1 Failed to load https://ipfs.infura.io:5001/api/v0/add: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gitcoin.co' is therefore not allowed access. The response had HTTP status code 504.
rollbar.min.js:1 Uncaught TypeError: Cannot read property 'length' of null
    at o (inpage.js:1)
    at Object.encode (inpage.js:1)
    at Object.u [as fromUtf8] (inpage.js:1)
    at i.formatInputString [as _inputFormatter] (inpage.js:1)
    at i.encode (inpage.js:1)
    at inpage.js:1
    at Array.map (<anonymous>)
    at d.encodeParams (inpage.js:1)
    at u.toPayload (inpage.js:1)
    at u.sendTransaction (inpage.js:1)

**Comment by owocki** [comment]
IPFS / infura is down right now

heres our announcement about thte same: https://twitter.com/GetGitcoin/status/1020355857454780416

working with infura to get it back up
