### ISSUE TITLE
Optimizing the docker setup

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#1803]
Discussion for optimizing the docker setup.

We can start by using the python:-*alpine instead of stretch,
because it's way more lean and better maintained.

What do you think?

**Comment by mbeacom** [comment]
We intentionally don't use alpine opting for sketch-slim (I love alpine, but I wouldn't claim alpine is better maintained than Deb) because alpine couldn't build `libsecp256k1` which was and is still required.

**Comment by pinkiebell** [comment]
I actually use alpine as a local dev container and only applied one hackery for the python cryptography package, which is solved upstream to compile with libressl (v2.3).
I have no problems until now, but I also don't know what else you are using in your environment,
that's why I opened this issue.

I can push my dockerfile, if you want to try this out.

**Comment by pinkiebell** [comment]
https://github.com/pinkiebell/web/commit/7a571fffb875513f76513400e01bc3041daa48d3

**Comment by pinkiebell** [comment]
Sorry, my bad rebase.
This one is better ;)
https://github.com/gitcoinco/web/commit/ad2d4421faf500ad2ae1be045a1c08c5dff20555

**Comment by mbeacom** [comment]
Exciting! I'll check it out tomorrow on my way back to the states.  It looks like the issues have been resolved upstream for `libsecp256k1` on alpine! Honestly, I haven't had much time to revisit migrating the image to alpine, so this definitely helps.
Thanks!

**Comment by oogetyboogety** [comment]
@mbeacom any luck with this? i'm going to try out pinkibell's commit myself...check out the following articles...the checklist mentions no time to get up and runnning  :stuck_out_tongue: 
Current size for me:
web_web                    latest                                          05276be9b716        6 days ago          **2.42GB**
https://github.com/gitcoinco/web/issues/1988
https://medium.com/c0d1um/building-django-docker-image-with-alpine-32de65d2706

**Comment by pinkiebell** [comment]
Just updated my branch, totally forgot about it.
https://github.com/pinkiebell/web/tree/docker

**Comment by kuhnchris** [comment]
we switched to python3.8-alpine for some while now, apparently... thanks tho! :-)
