### ISSUE TITLE
Add autotranslate base for Chinese

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1804]
Add autotranslate base for Chinese

to this PR https://github.com/gitcoinco/web/pull/971

This is requested by Decentraland and it'd be nice if we could ship it quickly

**Comment by mbeacom** [comment]
@owocki The autotranslate branch has `zh` translations added (https://github.com/gitcoinco/web/pull/971/files#diff-3f9737c05a00f8739afebff6239e18f4R147), but it was having problems so I disabled it.  I'll take a look at what was causing the error to throw.

**Comment by mbeacom** [comment]
Fixed. Traditional and simplified now added.
