### ISSUE TITLE
As a developer, i want fixture data so i can develop on real-looking data

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#182]
idea spurred per https://github.com/gitcoinco/web/issues/157#issuecomment-354308790

it'd be nice if there was a way to give community devs data that was 'prod-like'... but scrubbed of any PII info (emails, keys, etc).  

# implementation ideas

* postgres backups - right now the backup command `backup.bash` takes a full prod backup nightly.  perhaps we could augment it to remove all PII and post a nightly backup somewhere public
* django fixtures

**Comment by owocki** [comment]
@mbeacom curious your thoughts on this

**Comment by mbeacom** [comment]
@owocki Maybe we should consider using Django fixture data?
We can achieve this by building out initial data from a dump as described in the references below and redacting sensitive information.  We should only need a small sample for each model, but that should give developers using the local environment what they need.  Additionally, this will allow us to load the fixtures for future test cases.

### References

#### General / Implementation

* https://code.djangoproject.com/wiki/Fixtures

* https://docs.djangoproject.com/en/1.11/howto/initial-data/

#### Testing

* https://docs.djangoproject.com/en/1.11/topics/testing/tools/#fixture-loading

**Comment by owocki** [comment]
thats a good idea.

**Comment by owocki** [comment]
2a51f3215ed9e4bfca4872dfad9253b4baa659ff might hold us over for now

**Comment by amites** [comment]
given a db snapshot to work from I'd be happy to knock out something -- can post some regex to scrape basic data out manually before sharing

thinking a django generated json fixture with a given # of entries for each major db table in place

**Comment by owocki** [comment]
related: https://github.com/gitcoinco/web/pull/236#issuecomment-362011140

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/blob/master/docs/RUNNING_LOCALLY_DOCKER.md#optional-import-bounty-data-from-web3-to-your-database

i think this is a decent stopgap for now ^^

**Comment by danlipert** [comment]
Bounty ticket here -> https://github.com/gitcoinco/web/issues/4292
