### ISSUE TITLE
Frontend optimisation

### ISSUE THREAD

**Issue by olafghanizadeh** [gitcoinco/web#183]
GitCoin Frontend is in need of a cleanup and optimisation of frontend assets. Currently all images are in raster graphics, which does not scale well and is less performant than vector graphics (SVG). This depends a little on the complexity of the graphics, but most of the assets on the current website would be better in SVG. Currently 78% of the page size on the front page are images, it is actually as much as 11.27MB. 

Next there is 2.5MB of JS-files and 435Kb of CSS-files. Implementing a build tool and a build process for the compilation of the front-end would be very helpful here. There should also be some consideration to wether all the background animations are necessary and if their workload is worth the performance loss in terms of UI/UX.

**Comment by olafghanizadeh** [comment]
Suggestions to what should be done:

* Implement webpack (or other similar build tool)
 * install and compile bootstrap, animate.css and other CSS/JS dependencies with npm
*Optimise PNG/JPG/SVG assets in the build process (can be implemented with webpack)
*Utilize bootstrap variables and classes instead of overriding with custom css.

**Comment by KamesCG** [comment]
I am happy to contribute to this.

Unless @olafghanizadeh you want to setup the Webpack build process?

**Comment by thelostone-mc** [comment]
There is already an open PR with webpack integration, so you guys might wanna double check before starting

**Comment by olafghanizadeh** [comment]
Yeah. I saw now. So might be worth waiting for that to be merged before taking on this. :)

**Comment by developerfred** [comment]
What is the priority of this edition, can I send some work?
