### ISSUE TITLE
DAI FAQ

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1830]
FAQ we've seen from contributors when they receive a DAI bounty:

- how to add this token to metamask
- how to exchange it to ETH or USD. 

TODOs:
- add a DAI FAQ helpdesk article.  link to it whenever someone receives a DAI bounty

**Comment by nanspro** [comment]
![screenshot-2018-7-28 help](https://user-images.githubusercontent.com/24641089/43349689-3400ea18-921f-11e8-88ae-c40edd63b752.png)
Is this ok?
I thought about moving it to the middle.
