### ISSUE TITLE
crowdfunding v2

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1832]
not ready to be worked on yet

- show crowdfunding amount in explorer view
- cleanup the unused imports in tip_views (ad reapply mbeacom's doc changes from https://github.com/gitcoinco/web/pull/1810 )
- anything else?

ref: #1597

**Comment by PixelantDesign** [comment]
- Update crowdfunding amount treatment to use an icon since the word crowdfunding is so long.

- If I've just crowdfunded an expired issue, should I be able to extend the expiration date by doing so?
My instinct is yes. Thoughts?

@owocki @thelostone-mc @SaptakS @mbeacom

**Comment by owocki** [comment]
> If I've just crowdfunded an expired issue, should I be able to extend the expiration date by doing so?

Sure, but only IFF You're the funder should you have permissions to do so
