### ISSUE TITLE
For cooperative bounties, it is not clear if the bounty is to be split, or if each person gets the bounty

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1834]
We recently had a cooperative bounty which was $100 DAI, and there were 3 submissions for it.

I paid out $100 DAI to the first submission, and 35 each to the 2nd place submissions.

We got a complaint that the person though that their submissino should be paid out the full amount.

As a means of correcting this on a go forwad basis, I suggest asking bounty funders to make sure they are clear about whether their bounty is to be split, or paid out to each party, upon bounty creation.

**Comment by kuhnchris** [comment]
Did we add a modal/info? Cause I didn't see one yet...
