### ISSUE TITLE
t-architecture v4

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1837]
(not ready to be worked on yet)

# Tips 

1. do not store any references to shards on servers
2. send emails about new T's shards in frontend, via javascript, perhaps via https://smtpjs.com/
3. instead of direct Tsends, use smart contract which has methods `transfer(to_address)` and modifier `onlyIntermediary()` and `refund() and modifier `onlySender()`
4. expose refund ability via gitcoin UI

# Crowdfunding

5. make a smart contract that is pointed to the original standard bounty
6. smart contract only has a constructuor ( `init(std_bounties_id)` two methods `refund()` and `sendToBountyWinner()`.
7. this is used for crowdfunding

**Comment by owocki** [comment]
@mbeacom feedback?

**Comment by kuhnchris** [comment]
@owocki still relevant?
