### ISSUE TITLE
Repo Owner: Admin Privileges 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1850]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a repo owner, I'd like to have admin privileges over bounties which are funded on my behalf. 
### Why Is this Needed
When a bounty is funded by the Gitcoin team / someone who is not the repo maintainer, the repo maintainer still should still share ownership over the bounty, if granted by the funder. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
[Example here where this was needed. ](https://gitcoin.co/issue/rotkehlchenio/rotkehlchen/41/715) 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Funder should have the ability to give another Gitcoin profile access to approve bounty hunters on their behalf.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- A simple interface from which a funder can provide share administrative from the bounty details page. This could also perhaps be listed in the funder form as an optional field (something like 'Add Admin(s)')

**Comment by PixelantDesign** [comment]
Delegating starting work and approving work for the entire organization.

**Comment by kuhnchris** [comment]
@PixelantDesign was this ever done in orgs v2?
