### ISSUE TITLE
Stop Work displays on old Start Work activity feed entries

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1854]
**Describe the bug**

Previously stopped work in the bounty details page activity feed still displays admin buttons to stop work / ding users.  Additionally, the `stop work` activity entry doesn't seem to be present/visible.
The XHR response is:

`{errors: ["Party haven't expressed interest on this bounty."], success: false}`

**To Reproduce**
Hit https://gitcoin.co/issue/gitcoinco/web/1680/873 as an administrator/staff and attempt to "Stop work" against `PixelantDesign`.  You will be prompted with an error.  If you inspect the XHR request response, you'll see that the user isn't currently "interested" in the bounty.

**Expected behavior**
Staff users shouldn't be prompted with the option to `stop and ding / stop work` on standard `Activity` entries for `start_work` if they are no longer active.  Additionally, there should be an `Activity` entry displayed identifying that previously started work has been stopped.

**Screenshots**

<img width="1008" alt="screenshot 2018-07-30 15 28 37" src="https://user-images.githubusercontent.com/7315957/43418849-437c134c-940d-11e8-8c34-599ebc0bf3bb.png">

**Comment by owocki** [comment]
45c4dff68353379c50ed0521b429916ab1c0378d
