### ISSUE TITLE
Single Payout Bounty Broken

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1859]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

**To Reproduce**

Tried to pay this bounty:
https://gitcoin.co/issue/gitcoinco/web/1672/811

Bounty Submission dropdown showed black.

I tried to accept submission anyway, and showed Fulfillment ID missing.

See screenshots

**Expected behavior**

Expected it to work.

**Screenshots**

<img width="701" alt="screen shot 2018-07-31 at 12 12 22 am" src="https://user-images.githubusercontent.com/238235/43437417-f31e358e-9456-11e8-8b7e-2d26052ccf59.png">

<img width="1426" alt="screen shot 2018-07-31 at 12 12 37 am" src="https://user-images.githubusercontent.com/238235/43437419-f5eae9e2-9456-11e8-9b54-5e8eae37ec7d.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome

**Comment by thelostone-mc** [comment]
Seems to be working at my end 🤔 

> Bounty Submission dropdown showed black.

That happens on hover. It's been like that. But the fulfillment id should have been listed !

<img width="1440" alt="screen shot 2018-07-31 at 10 05 35 am" src="https://user-images.githubusercontent.com/5358146/43437947-4a7b87a8-94a9-11e8-8d6d-a30843fbde86.png">

**Comment by thelostone-mc** [comment]
Closing this out and it seems to working fine ^_^
