### ISSUE TITLE
Initial API proposal

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#1864]
This is an initial API proposal which I am most comfortable with.
I left out methods for interacting with bounties intentionally
because we need another form of authentication (API tokens) or we could accept Github's personal access tokens.

bounty status = open, closed, started, cancelled, expired

project types =
  traditional,
  contest,
  cooperative

permission types =
  permissionless,
  approval

profileHandle = username on gitcoin.co

resource = activity or object related resource/URL or description
```
BountyObject {
  'id': 101,
  'status': 'open',
  'title': 'foo',
  'description': 'bar',
  'created': '2018-05-29T00:00:00Z',
  'expires': '2018-10-29T00:00:00Z',
  'funds': [
    { 'symbol': 'ETH', amount: 0.1 , profileHandle: 'foo' },
    { 'symbol': 'DAI', amount: 300.0, profileHandle: 'bar' }
  ],
  'resource': '',
  'projectType': '',
  'permissionType': ''
}
```
activity types =
  workStarted,
  workStopped,
  workSubmitted,
  workAccepted,
  workRejected,
  fundContributed,
  fundWithdrawn
```
ActivityObject {
  'type': 'workSubmitted',
  'created': '2018-05-29T00:00:00Z',
  'profileHandle': 'foo',
  'resource': ''
}
```

tip status = claimed or unclaimed
```
TipObject {
  'id': (txid?),
  'status': '',
  'comment': 'bar',
  'created': '2018-05-29T00:00:00Z',
  'expires': '2018-10-29T00:00:00Z',
  'received': '2018-06-29T00:00:00Z',
  'senderHandle': '',
  'receiverHandle': '',
  'symbol': 'ETH',
  'amount': 0.1,
  'resource': ''
}
```
```
ProfileObject {
  'handle': 'profile handle',
  'name': '',
  'avatar', '[avatar url]',
  'social': [
    { type: 'github', resource: 'https://github.com/foobar' },
    { type: 'email', resource: 'foo@bar' }
  ]
}
```

GET v1/[network]/bounty/[id]
```
[
  BountyObject
]
```

GET v1/[network]/bounty/[id]/activities
```
[
  {
    (inherits BountyObject)
    'activities': [
      ActivityObject,
      ...
    ]
     
  }
]
```

// latest bounty
GET v1/[network]/bounty/-1

// bounty by id
GET v1/[network]/bounty/818

// bounties from newest to oldest. Up to 100.
// Last 'page' reached if length is less than 100.
// -1 = latest, Any other number returns that bounty + 99 bounties before (if applicable).
GET v1/[network]/bounties/[id]

// Same as above, but filter by bounty status
GET v1/[network]/bounties/[id]/[status]

// ProfileObject
GET v1/[network]/profile/[profile handle]

// bounties, filtered by profile (and status (optional))
GET v1/[network]/profile/[profile handle]/bounties/[bounty status]

// bounties, filtered by profile and bounty status
GET v1/[network]/profile/[profile handle]/bounties/[bounty status]

// Same as above, but with the additional 'activities' property.
GET v1/[network]/profile/[profile handle]/bounties/activities
OR
GET v1/[network]/profile/[profile handle]/bounties/[bounty status]/activities

// Tips for profile
GET v1/[network]/profile/[profile handle]/tips

// Same as above, but filter by tip status.
GET v1/[network]/profile/[profile handle]/tips/[status]

**Comment by PixelantDesign** [comment]
@mbeacom @owocki thoughts on this?

**Comment by owocki** [comment]
do we want to increment the version number? if so, i think it should be v0.2, not v1

im onboard with the spec for the tip and activity APIs, i dont see a need to evolve the bounty API forward at this point though.  i also dont think that the profile API needs to have the network param in the URL

**Comment by pinkiebell** [comment]
I wanted to keep the api design consistent, so an uniform bounty(ies) endpoint included.
For the profile endpoint, what if I play with the rinkeby network and want to use the profile endpoint?

I'm good with v0.2 👍

**Comment by owocki** [comment]
curious what @mbeacom thinks here

**Comment by kuhnchris** [comment]
did we ever reitterate over the API, or did this just fell apart @pinkiebell ?

Thanks!

**Comment by pinkiebell** [comment]
@kuhnchris This one never got fruits as far I remember 🙂

**Comment by kuhnchris** [comment]
You still interested in it, or is the usecase currently kind of moot?

**Comment by pinkiebell** [comment]
As long no one has issues with the existing API endpoints, I think it's not needed.
Can be closed 🙂
