### ISSUE TITLE
System Generated Awards V1 (Reputation)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1865]
### User Story

As a funder/contributor, I would like the Gitcoin platform to know what I'm doing and reward me for good behavior.

### Description
- these would essentially be a set of badges issued to users by gitcoin on completing predefined tasks
- would be listed on the profile under new section called Achievement 
- reason : Intrinsic motivation to go ahead and unlock more (pretty much like every video game )

**discuss**:  will this affect users reputation / should they just remain as badges and nothing more ?
 @PixelantDesign @owocki 

#### v1 Pass

- [ ] We define a set of predefined tasks ( completed X bounties,  funded Y bounties) which are set as the trigger points to reward a badge. 
Completed 1st Bounty
Completed 3rd Bounty
Completed 5th Bounty
Completed 10th Bounty
Completed 15th Bounty
Completed 20th Bounty
Completed 50th Bounty
Funded 1 Bounty...and so on

- badges are round or different shapes

**FrontEnd** 
- would be fit into profile as a subsection called Achievements

**Schema** 
- store the badges off chain 
- Table `Badges` (`name`,  `uri` ) and those are referenced in `badges` column within `Users` ? 

**Backend**
- define trigger point (unique for each scenario )
- update entry in `Users` when trigger point is activated

**discuss**: @mbeacom @SaptakS It would make sense to make the trigger instant but that would cause a lot more db lookups based on the scenario (which is meh )

<img width="629" alt="screen shot 2018-08-01 at 4 45 45 pm" src="https://user-images.githubusercontent.com/238235/43548079-1563d69e-95ab-11e8-96cb-eb353a7d6cc2.png">

**Comment by kuhnchris** [comment]
Was this kind of an automated "Achivement System" via Kudos? Kind of like steam does it for games, just for bounties. May be a motivator to keep comming back!
