### ISSUE TITLE
Plan for Contributor Dashboard 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1877]
### User Story

As a core team we'd like to have an approach for the contributor dashboard.

### Description

We've bountied the funder dashboard which is being built. We have designs for a contributor dashboard. Once the funder dashboard rolls out, we should decide if the contributor dashboard should be standalone, or be part of the funder dashboard that houses different information.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [x] Come up with a plan
- [x] Come up with a tech approach
- [x] Determine whether any design needs to change, if so, update the designs
- [x] User test the decision with 5 contributors for feedback prior to building.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Approach - reuse funder dashboard shell, and plug in contributor components.

**Comment by PixelantDesign** [comment]
Updated contributor dashboard @thelostone-mc @SaptakS, @owocki @mbeacom pls provide feedback.

This is largely what we discussed in last week's product sync, keeping the same modules as the funder dashboard (as much as possible) and providing a way at the top to select role (contributor/funder).

![gitcoin contributor dashboard](https://user-images.githubusercontent.com/238235/44374694-a0e5f780-a4bd-11e8-9909-87e73d3c9d04.jpg)

cc: @willsputra

**Comment by thelostone-mc** [comment]
My concerns 

- it feels like a lot of things in a cramped in
- the design is very off from what we already have -> like how amount is displayed + . dropdowns
- switching btwn the contributor & funder dashboard via the dropdown seems cryptic / hidden

**Comment by PixelantDesign** [comment]
Made updates based on user feedback. Awaiting completion of funder dashboard.
