### ISSUE TITLE
Create/modify "Grants Index" Page - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1889]
### User Story

As a Grants user, I want to see and search all possible grants so that I can contribute to projects that matter to me, as well as click into the different user flows of the Grants project.

### Why Is this Needed

Users need a central place to find active grants and choose different interactions to have with the grants process. 

### Description

*Type*: Feature

### Definition of Done

- [x] Page has a "Dev Grants" Title
- [x] Page has a short description of the Grants Product and its different user flows
- [x] Page has thumbnail versions of all live grants in the Gitcoin ecosystem and should be paginated and clickable
- [x] Grant thumbnails display the project title, description, owner, and a current vs. desired monthly funding progress bar
- [x] Page has a search bar for searching/sorting by title and topic
- [x] Page has a "Create Grant" button
- [ ] Page has a "My Grants" button 
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel as well

**Comment by justpixel** [comment]
Here is the wireframe, i've added some new elements besides what existed before. 
![dev grants index](https://user-images.githubusercontent.com/7627020/43575910-ab3b2f96-9650-11e8-91ec-6a01b5204f38.png)

**Comment by captnseagraves** [comment]
@justpixel I dont think we need the topic tabs. The search bar should be enough to search by project title or topic keyword.

@PixelantDesign Do we need a "My Grants" button on this page or should we add it to the account section in the top bar.

**Comment by justpixel** [comment]
I've done the design for this one, but I've inculded all the requested changes . Pixelant needed it for a presentation.
![dev grants index-design](https://user-images.githubusercontent.com/7627020/44089832-e09eef68-9fd0-11e8-9d7d-7df027559244.png)

**Comment by PixelantDesign** [comment]
Looks good. I shared a file with you on slack just updating the search area, since it seems to stand out more than the rest of the page.

**Comment by justpixel** [comment]
Here is the updated file.
![dev grants index](https://user-images.githubusercontent.com/7627020/44267323-6ae31200-a236-11e8-862b-809c016ea25b.png)

**Comment by octavioamu** [comment]
how I "create a new grant"? The create button is "found an issue"?

**Comment by captnseagraves** [comment]
@octavioamu @eswarasai  We probably dont need a new design for this, but should add pagination in implementation. Also, the "Browse Grants" button should be a "Create Grant" button. I think you brought this up in the last team call octavio. I what you were asking now!
