### ISSUE TITLE
Create/Modify "Create Grant" View - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1890]
### User Story

As a Grants user, I want to fill out relevant information about my project so I can create a grant and attract funders

- As a grant creator, I want to submit my completed form so that I can create my grant

### Why Is this Needed

The "Create Grant" page is needed to allow a grant creator to describe their project and deploy a grant which grant funders can contribute to. 

### Description

*Type*: Feature
### Definition of Done

- [x] Page has inputs for:

1. Name of Project
2. Description of project
3. Project URL
4. Team members
5. Total amount sought for grant
6. Milestones and projected timeline 
7. Project image

- [x] Page has a "Create Grant" button
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by justpixel** [comment]
I've added the new fields to the existing design.
![create grant](https://user-images.githubusercontent.com/7627020/43757789-a86e2c16-9a22-11e8-8e08-710d149cf0f1.png)

**Comment by captnseagraves** [comment]
@justpixel I like where this one is for the most part. Kevin O. mentioned in the call this morning that it doesn't need to be left aligned and would look better without all the extra white space to the right. Could you play around with that a little bit?

**Comment by PixelantDesign** [comment]
Agree let's reuse new bountyr form format here.

**Comment by justpixel** [comment]
Updated:
![create grant](https://user-images.githubusercontent.com/7627020/44090092-ab42aa02-9fd1-11e8-8c5c-a9927c4d3e21.png)

**Comment by justpixel** [comment]
@PixelantDesign you choose form a list of members. I think it should be an approve stage.

![create grant](https://user-images.githubusercontent.com/7627020/44267307-5dc62300-a236-11e8-8ae4-9886d7590fb6.png)

**Comment by justpixel** [comment]
Updated the milestone section. 
![create grant](https://user-images.githubusercontent.com/7627020/45360224-94921d80-b5d7-11e8-89d1-17a039954aee.png)

**Comment by PixelantDesign** [comment]
Hey @captnseagraves @justpixel 

If a someone is creating a grant, are they thinking about creating milestones or do they just want to get the project created and funded? Though, I guess I could see having milestones/a plan to help encourage funding.

Hard to know without getting some user feedback on this.

Could we use round circles instead of square for the avatars (we currently use round in the system)?

**Comment by captnseagraves** [comment]
Yes, the idea was to allow a user to create roadmap via milestones. This allows funders to measure progress, etc. I was just thinking this morning about the milestones though, I wouldn't want to recreate a Github feature. Seems like we could encourage users to manage their project through the github "milestones" and/or "projects" features.

We should use round circles for the avatars.

**Comment by captnseagraves** [comment]
@Owocki @PixelantDesign I'm seeing that we need to capture the grant creator's address somehow. It could be through their web3 instance, or we can ask them explicitly for an address. In which case we will need to add a field. My instinct is to ask them for an address in case they want funds sent somewhere other than their metamask. Do either of you have an opinion?

**Comment by owocki** [comment]
your suggestion makes sense to me

**Comment by PixelantDesign** [comment]
The form should be centered, that might just be a sketch export issue cc: @justpixel.

Should we allow funds to be sent to an address other than their metamask?

If we provided an input, should we verify that it's the correct address? 

What's the simplest/most secure implementation?

**Comment by justpixel** [comment]
Yes, that was the problem. Here is the correct version.
![create grant](https://user-images.githubusercontent.com/7627020/46006689-c7044600-c0c0-11e8-8e09-62a54308b98e.png)
