### ISSUE TITLE
Request for Adding Fund Branding to Gitcoin Pages and Gitcoinbot Messages

### ISSUE THREAD

**Issue by mkosowsk** [gitcoinco/web#1895]
### User Story

**As a** funder in the space (Ethereum Foundation, Ethereum Community Fund, ETHPrize, etc.)
**I want** to have my branding on Gitcoin issues that I fund for different projects in the space
**so that** Gitcoin users know where funds are being allocated from

### Why Is this Needed

Right now it's unclear where funds are being allocated from in the space on the Gitcoin platform, this issue addresses that 😀

### Solution

Definitely open to discussion (@owocki @vs77bb @PixelantDesign @thelostone-mc) but I think branding could be added in the following three areas and not disrupt the flow of the page:

0. On the Explorer Page:

![explorer fund branding](https://user-images.githubusercontent.com/7970539/43495526-9e9cec02-9506-11e8-8b35-4d3f9a5a12b5.png)

1. On the Gitcoin Issues Detail Page

![detail fund branding](https://user-images.githubusercontent.com/7970539/43495533-a605877e-9506-11e8-9a73-edf4c932e4b1.png)

2. On the Gitcoinbot message for the issue:

![gitcoinbot fund branding](https://user-images.githubusercontent.com/7970539/43495544-b01e65aa-9506-11e8-84f0-b5928d2df6c5.png)

0 and 1 may disrupt the flow so I defer to your team's Design expertise here, but I think adding the message to the Gitcoinbot is a low cost with a high payoff 👍 The "ECF Web 3.0 Infrastructure Fund" would be a link to an article that we're cooking up at the moment :)

From the ECF: @christopherlema @cassandrashi @hughlang

Thoughts from the Gitcoin team? Thoughts from the ECF team?

### Definition of Done

Needs to be hashed out still :)

**Comment by owocki** [comment]
@mkosowsk 

this is really good feedback!  i think we can pull something together;  

two questions:
- is there an ECF brand guide and/or any ECF visual assets we can leverage here?
- whats our timeline for this?

**Comment by PixelantDesign** [comment]
This is an interesting idea @mkosowsk . Could you share an EPS of the logo so that we can experiment?

**Comment by mkosowsk** [comment]
@owocki and @PixelantDesign great to hear! I am poking ECF now to get their perspective :)

**Comment by mkosowsk** [comment]
Timeline would be a couple weeks as this is when funds will start being deployed via the ECF Web 3.0 Infrastructure Fund but is relatively flexible imo, it's not mission critical this branding is live right at the start as long as it's done in a reasonable timeframe 👍 

From ECF's side, they would like the Gitcoin logo in a transparent background and would blend something together like what's shown [here](https://blog.foam.space/status-and-foam-announce-technology-partnership-9dd91a6253d4).

Could you please point me to the latest and greatest Gitcoin logo on a transparent background?

**Comment by owocki** [comment]
yes! https://gitcoin.co/presskit

**Comment by mkosowsk** [comment]
Thanks, passing along

**Comment by cassandrashi** [comment]
Agreed with @mkosowsk that solution 0 and 1 would disrupt the flow of users and cause confusion. The logo on the issue explorer and issue detailed page view probably should remain as it is, displaying the project's logo.

My vote goes to solution 2.

In addition, I would kindly ask the issue requester for the future web3 + ECF fund supported issues to insert a blurb about ECF in the issue description. Assuming it would be @mkosowsk?

**Comment by PixelantDesign** [comment]
I think solution 2 makes sense as well.

**Comment by mkosowsk** [comment]
@cassandrashi my current understanding is that the repo maintainer of each different repo would have to put the ECF blurb in as is for different issues. This introduced a bit of friction, think it would be best to have some type of option on the Details page to include this blurb as an Issue Funder? 🤔

**Comment by vs77bb** [comment]
I like the idea of starting with Solution 2 and then moving back into a potential Solution 1 down the road  👍

**Comment by owocki** [comment]
@mkosowsk how long do we have until the funding goes live?

@PixelantDesign @thelostone-mc @SaptakS this wasn't part of August priorities.. is it easy to knock out?  if so, might be worth spending 45 minutes on soon.  if not, we should bounty it

**Comment by PixelantDesign** [comment]
@thelostone-mc @SaptakS could we add in option 2 (updating Gitcoin Bot text)?

**Comment by christopherlema** [comment]
> @mkosowsk how long do we have until the funding goes live?
> @cassandrashi could you you please speak to this?

@mkosowsk Hopefully by the end of this week (next week at the latest). Maker has already started to disburse funds to the other grantees, but we are still waiting on the KYC check.

**Comment by owocki** [comment]
@SaptakS is on it!

**Comment by mkosowsk** [comment]
Great! We're in good hands :)

**Comment by owocki** [comment]
@mkosowsk were almost done with solution 2 and will ship that soon, are you still interested in solution 1?  

cc @SaptakS

**Comment by mkosowsk** [comment]
Great!

I'd defer to @cassandrashi @christopherlema @hughlang on Solution 1, I'd personally prefer it but it's up to them :)

Perhaps it might be interesting to do a quick mock-up to try to see how it would look? 🤔

**Comment by mkosowsk** [comment]
@owocki how do I go about implementing solution #2 when funding an issue for the ECF?

Wasn't immediately obvious to me (for instance, when funding https://github.com/ethereum-ts/TypeChain/issues/94)

Thanks!
