### ISSUE TITLE
Ensure all values passed from the issue url are cleaned or validated to be only str/int as required

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1899]
```
invalid literal for int() with base 10: '559)'
```

When a user hits an endpoint with something like: `https://gitcoin.co/issue/raiden-network/raiden/1408/559)`

The special characters should be cleaned from the associated value before attempting to query for the bounty or caught via regex in the `re_path` itself.

**Comment by rahulpat** [comment]
@mbeacom what's the status on this and what's the tip like ?

**Comment by rahulpat** [comment]
@mbeacom was unable to repro this locally. seems like it's been fixed ?
