### ISSUE TITLE
Custom error modal for limitations 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#1901]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user dev, I want to be prompted with an explanation of api limitations so we can have less "tickets" of users trying to understand what is happening.
 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Maybe we can have api messages for this situations of rules so error could have the error code, the general explanation and a paragraph explaining that error so we can do a generic modal for those scenarios with an explanation of what is happening from the api.  

Ex:
The message in the error answer of the api could be something like  "You have reached you issues limit"

![image](https://user-images.githubusercontent.com/1358093/43534977-1de42d1c-958f-11e8-8ca1-7cf1f7efbc87.png)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
i actually just put a fix in for this this morning!
