### ISSUE TITLE
Create/Modify "Grants Detail" Page - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1905]
### User Story

As a Grants user, I want to view the details of a grant so that I can know if I want to fund the project, know what the status and recent updates for the project, or know how many funders I have. 

### Why Is this Needed

The "Grant Detail" page is needed to display what the current state of a grant and its associated project is. It will display the information captured in the "Create Grant" page, the current funders, and an update feed. It will also allow different users to go down the withdraw, fund, and cancel backing flows depending on the users' role.

### Description

*Type*: Feature

### Definition of Done

- [ ] Page displays:

1. [x] Name of Project
2. [x] Description of project
3. [x] Project URL
4. [ ] Team members
5. [x] Total amount sought for grant
6. [x] Milestones and projected timeline 
7. [x] Project image

- [x] Page has a "fund" button that is displayed to users that are not associated with the project yet
- [ ] Page has a "cancel backing" button that is displayed to users that are current funders of the grant
- [x] Page displays current funders of the projects
- [ ] Page displays how much monthly funding the grant is receiving 
- [x] Page has an updates feed that displays recent happenings in the project. Likely these will be recent commits in github, articles written by the team, and updates written directly to the grant. 
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by justpixel** [comment]
I've updated the page with the new elements.
![grant detail](https://user-images.githubusercontent.com/7627020/43707092-d3b4652e-996f-11e8-88ae-f4c466ac1383.png)

**Comment by captnseagraves** [comment]
@justpixel I like where this one is. It might make more sense of the "All Updates" tab to be the leftmost option out of the four.

**Comment by owocki** [comment]
this looks really good to me

**Comment by PixelantDesign** [comment]
Looks good to me as well. Milestones looks like it could be V2.

**Comment by justpixel** [comment]
Updated.
![grant detail](https://user-images.githubusercontent.com/7627020/44089965-460c6812-9fd1-11e8-90b0-ebfd5eeae3a6.png)

**Comment by justpixel** [comment]
Design:
![grant detail](https://user-images.githubusercontent.com/7627020/44267222-163f9700-a236-11e8-9fad-1f35993b13d1.png)
