### ISSUE TITLE
Create "Fund Grant" Page - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1908]
### User Story

As a Grant funder, I want to contribute funds to a grant so I can support projects that are important to me.

### Why Is this Needed

The "Fund Grant" page is needed to allow users to contribute fund on a chosen recurring cycle

### Description

*Type*: Feature

### Definition of Done

- [ ] Page has an input field for the amount the user wishes to contribute per period. 
- [x] Page has an input field for the frequency of their contribution. This defines the "period" of the user's contribution. Should expect a numbered input measured in days. 
- [x] Page has a "Contribute" button
- [x] Page displays a Withdrawal History of previous withdrawal activity in the grant_
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by justpixel** [comment]
For the "frequency of their contribution" Do you think it will work better a select with day, week, month? 
![fund grant](https://user-images.githubusercontent.com/7627020/43717494-6fe492b4-9990-11e8-96e5-ce1b75eee706.png)

**Comment by captnseagraves** [comment]
@justpixel I think weekly or monthly would be best. 

As addressed on the team call this morning, it probably makes more sense for this view to be a page instead of a modal. Could you iterate on this idea, please?

Also, I think it might more sense for the user to type in the amount they are will to contribute, instead of having the slider. @PixelantDesign thoughts?

**Comment by captnseagraves** [comment]
Another thought, does this page need a withdrawal history. I'm sure it does, that might have been a copy/paste error from the withdraw page issue.

**Comment by owocki** [comment]
per meeting yesterday, we decide to move this to a page instead of modal.  other than that, LGTM

**Comment by PixelantDesign** [comment]
Sliders are cool but it will be frustrating to move it around, trying to get an exact value. Standard input field would be best there.

**Comment by justpixel** [comment]
The slider has also an text input, but if you think is not necessary I've removed it.
Page updated:
![fund grant](https://user-images.githubusercontent.com/7627020/44033151-247b1104-9f12-11e8-8f94-267112572d32.png)

**Comment by PixelantDesign** [comment]
Looks good!

**Comment by justpixel** [comment]
Design:
![fund grant](https://user-images.githubusercontent.com/7627020/44267212-0d4ec580-a236-11e8-8bb9-9ca1759f9412.png)
