### ISSUE TITLE
link profile in nav somewhere

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#191]
https://gitcoin.co/profile/pixelantdesign

no one can find these profile pages anywhere!  they shoudl be linked somewhere 

maybe once https://github.com/gitcoinco/web/pull/156 is merged..

**Comment by olafghanizadeh** [comment]
I think we should make a module at the bottom of each claimed issue that displays the claimers profile with emphasis on the gitcoin.co profile. Ideally we should route clicks through gitcoin.co before sending them to GitHub. 

I can try to come up with a mock-up of what I'm thinking of

**Comment by owocki** [comment]
could probably start with just linking this here to gitcoin instead of github http://bits.owocki.com/082w3I1G230i/Screen%20Shot%202017-12-29%20at%202.56.32%20PM.png

**Comment by owocki** [comment]
4db158518ffed9068d401956b68a9adf27ae682e is a start

**Comment by owocki** [comment]
> I can try to come up with a mock-up of what I'm thinking of

yes pls.. i could also bounty it if not

**Comment by owocki** [comment]
related to https://github.com/gitcoinco/web/pull/156

**Comment by mbeacom** [comment]
Can this be closed? @owocki ? Since the addition of the profile in the navbar, leaderboard, and  https://github.com/gitcoinco/web/commit/4db158518ffed9068d401956b68a9adf27ae682e, seems the profile isn't as hidden as it was previously.

**Comment by owocki** [comment]
yes i think so
