### ISSUE TITLE
Create "Cancel Funding" Page - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1910]
### User Story

As a Grant funder, I want to cancel my subscription to a grant project so I can end support whenever I want to. 

### Why Is this Needed

The "Fund Grant" page is needed to allow users to cancel support for a given project.

### Description

*Type*: Feature

### Definition of Done

- [x] Page has "Are you sure you want to cancel your support of the 'project title' project?"
- [x] Page has a "Cancel support" button
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
@justpixel Agreed, a modal does make more sense for this page and I like the nice illustration idea. I had a typo in the copy for the page though. I updated it in the original issue. Could you update it in the wireframe?

**Comment by PixelantDesign** [comment]
Yes lets make it a page.

We probably need the following info:

- Name of Grant to be cancelled
- Start date.
- Effective date of cancel (does this happen right away?)
- Describe to user what they need to do
- Terms checkbox if any @captnseagraves ?
- Message that team members of this grant will be notified (they should be).

What happens to the funds that are in that grant? Does it stay open until it's used up?

Should we use any behavioral techniques/guilt to stop users from cancelling?

**Comment by justpixel** [comment]
![cancel funds](https://user-images.githubusercontent.com/7627020/44090074-9994c54c-9fd1-11e8-92bf-d388767cf089.png)

**Comment by PixelantDesign** [comment]
looks good to me!

**Comment by justpixel** [comment]
Design:
![cancel funds](https://user-images.githubusercontent.com/7627020/44267259-366f5600-a236-11e8-9fc0-ccbf40ffaa99.png)

**Comment by captnseagraves** [comment]
@PixelantDesign I don't know that we need a terms checkbox on this page, but we might want one on the "Fund Grant" Page. Also, yes the smart contract will probably send funds that haven't been claimed yet to the Service Provider. This will prevent users from canceling their subscriptions and getting free services.
