### ISSUE TITLE
User Feedback/ Feature Requests

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1914]
- For handling scenarios such as bounty increase due to scope inflation, I think it could make sense to start with a utility that allows me to "estimate time" at the start of the work. Once that timer is up, present a dialog to 'request for more funding' as the option with a write-up as rationale. Challenge here would be to tackle work that is spread out over days. Maybe a time-logger tool can work here?

- A lot of freelancers log time / tasks etc. I think having these sort of tools in Gitcoin would make sense ( in the long run ). The general idea is that all the tools/utilities I would need as a freelancer could be integrated into the platform.

- For the funder as well there could be an option to add 'estimated effort' ( notice 'effort' here vs 'time' for hunter ). Essentially, both parties at the same time are speaking about the same thing using different constructs. Effort can be set in sized like XS, S, M, XL, Epic ( a bit of kanban/agile here ) or something like 1-3 hours, 3-6, 10-20 etc.

**Comment by PixelantDesign** [comment]
> for (1) i think that just allowing the user to request more $$$ when scope increases happen via the product would be a good move. writing/integrating a whole time tracker tool would be much more complex

@thelostone-mc what do you think about the above? What happens when a contributor requests more money than the funder is willing to pay? We'll need a plan on how to resolve.

**Comment by kuhnchris** [comment]
[X] hours can be entered
[X] Estimation for funders
[ ] Time logger
