### ISSUE TITLE
denote contributions to the community publicly with a creative asset

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#192]
i have a half-baked (at this point) idea… that eventually we can create scarce rewards for certain milestones… like being at the top of the leaderboard at end of month.. or fulilling your first issue.. etc

rewards == non-fungible token denoting your accomplishment, free schwag sent to you, etc.

tracking it here... in case anyone else has ideas

**Comment by owocki** [comment]
related https://github.com/gitcoinco/web/issues/230

**Comment by kuhnchris** [comment]
assuming this is the implemented leaderboard - closing.
