### ISSUE TITLE
interaction / distribution of funds between different levels of interest on an issue.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#193]
credit to @thelostone-mc for this idea:

>  If I’ve claimed an issue, it would be nice if there way a direct way for me to ask for help from the `watchers` and I could tip them for helping me out.

> ( yes one can argue saying it’s possible now, where I tag folks and and tip them once they help out and my I solve the issue , but if gitcoin encouraged me to tip the watcher who helped me out, it would encourage more folks to be involved -> network -> more fun. Not sure if this would actually work but yeah  )

# implementation 

this is maybe something that could be built upon @mbeacom’s work at https://github.com/gitcoinco/web/pull/156

**Comment by kuhnchris** [comment]
did anything happen with that idea?
