### ISSUE TITLE
UX for Follow an Org

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1932]
### User Story

As a contributor I'd like the ability to follow a repo that I care about.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
- [ ] Action to follow an Org
- [ ] Show confirmation that user has followed the org
- [ ] Identify where else this information should show up

**Comment by kuhnchris** [comment]
Superseeded by Favorites PR
