### ISSUE TITLE
Better State Management: "No result found" and "Results" are getting displayed at the same time

### ISSUE THREAD

**Issue by Rahul-Sagore** [gitcoinco/web#1938]
**Describe the bug**
Need to handle state in better way. If I randomly clicks on sidebar Radio button, without waiting for response then result of two API call gets displayed on page.
E.g if one radio button has no result for API call and second one had results, then I was able to see both things at same time:

**To Reproduce**
* Click "Fullfilled by me" under "My Projects", it will render "No result found"
* Click on "Any" will render results.
* If you click "Any", and if you click "Fullfilled by me" before "Any" gets any response, then it will render both "No result found" + Results from "Any".

**Expected behavior**
Need to Abort previous API call, only the latest API Call's result should be visible not the previous ones.

**Screenshots**
<img width="1440" alt="screen shot 2018-08-04 at 2 44 37 pm" src="https://user-images.githubusercontent.com/3587851/43674805-8f3d6d66-97f6-11e8-89bc-38721f03f2cd.png">

**Desktop (please complete the following information):**

- OS: MAC OS X : 10.11.2
- Browser:  Chrome
- Browser Version 67

**Additional context**
ScreenCast:
https://drive.google.com/file/d/1ms3XlDWWeLTLV_tvceNWonUEdThpnHZ-/view?usp=sharing

**Comment by thelostone-mc** [comment]
@Rahul-Sagore thanks for pointing that out ^_^
