### ISSUE TITLE
CloudFront: 504 Gateway Timeout on Website onLoad

### ISSUE THREAD

**Issue by Rahul-Sagore** [gitcoinco/web#1939]
**Describe the bug**
Website stopped working after sometime. Giving 504 gateway error, result view is empty.

**To Reproduce**
No idea, getting this error after using gitcoin web for sometime. Now continuously getting error.
Might happen if user frequently clicks on radio button on sidebar.

**Expected behavior**
Website should work. API call should be error free

**Screenshots**
<img width="1440" alt="screen shot 2018-08-04 at 2 59 18 pm" src="https://user-images.githubusercontent.com/3587851/43675013-8fe3bc30-97fa-11e8-9333-35792674252f.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Browser Version 67

**Comment by owocki** [comment]
Happy Monday!  @Rahul-Sagore i'm not able to get this reproduced right now.  Are you experiencing the issue right now?

**Comment by Rahul-Sagore** [comment]
Yes. 

Just created a screencast for the issue.
 
https://drive.google.com/file/d/1X6H6qZD4_uhg1hQBGCxaq_mTLY-HMov3/view?usp=sharing
