### ISSUE TITLE
Create baseof.html-template

### ISSUE THREAD

**Issue by olafghanizadeh** [gitcoinco/web#194]
I've been examining the codebase a bit and there seems to quite a bit of repetitive code in places. I suggest creating a baseof.html-template, similar to gohugo.io theming, if anyone is familiar with it:

Here is an example:
https://github.com/indigotree/atlas/blob/master/layouts/_default/baseof.html

**Comment by owocki** [comment]
this is a good idea

**Comment by chiptus** [comment]
anyone working on it? I started creating something, seems like a big issue, but will have a try

**Comment by owocki** [comment]
no one is working on it no.  still think its a good idea, but we've got a few branches in progress so i worry about the merge conflicts

**Comment by chiptus** [comment]
I'll start.
What do you think about separating it to PR based on modules? I can start with folders that are less worked on. I started the work on on `app/dashboard/templates/bounty` so I'll finish that. Each module will have its own `baseof.html` template. than the parent module can have a `baseof` template that all other modules will extend.

Does that sound good?

**Comment by thelostone-mc** [comment]
@chiptus Yeah I'd be okay with that ! 👍 
Smal PRs -> easier to review and less buggy

**Comment by chiptus** [comment]
Can anyone review this, just to say if it's the correct direction, so I can continue?

**Comment by chiptus** [comment]
Cool, so I will merge develop into my branch and will remove the WIP title.

Feel free to review for releasing to develop.

**Comment by pinkiebell** [comment]
@chiptus 
As long there are no conflicts, you can just remove the WIP title.
If there are conflicts, just rebase to master 👍

**Comment by kuhnchris** [comment]
I assume this was before the rehaul of the UX, correct? I assume since the connected PR is merged that we can close this issue.
