### ISSUE TITLE
Unable to see links on Footer, due to Lazy load of results

### ISSUE THREAD

**Issue by Rahul-Sagore** [gitcoinco/web#1940]
**Describe the bug**
On https://gitcoin.co/explorer page, when I scroll I see footer, but as soon as I read links, it jumps to bottom, because you are lazy loading the results list. Not a good UX. Either there should be pagination or "Load more" button.

**To Reproduce**
* Go to https://gitcoin.co/explorer
* Scroll down to footer
* After 1 - 2 second, results gets loaded footer pushed down to bottom. 

**Expected behavior**
User should be able to see Footer

**Comment by thelostone-mc** [comment]
@PixelantDesign @SaptakS It's a valid point
Folks from the community did like it when we did like that 

Hmm paginate / load ==  more clicks but a better UX !

**Comment by PixelantDesign** [comment]
Is there a way to load and not hide the footer? Should we allow for more items by default and per load?

**Comment by thelostone-mc** [comment]
@PixelantDesign So cause of lazy loading -> we automatically fetch more issues and populate them giving the feeling of infinite scroll 

While this is nice -> like @Rahul-Sagore pointed out it's impossible for the user to use the footer unless they've exhausted the scroll cause as they scroll to the footer -> infinite scroll kicks in -> more issues pop up and footer is pushed further down

**Comment by PixelantDesign** [comment]
So lets go back to click to load, and keep the footer at the bottom?

**Comment by kuhnchris** [comment]
apparently no.
