### ISSUE TITLE
new bounty : make it evident that edits are possible only via github issue

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#1942]
### User Story

Current flow ->
Funder creates an issue by pasting the github link on http://gitcoin.co/new which fetches and auto populates the form in a disabled text box 
On hover -> a tooltip appears stating we sync up github 
(So any update made there gets refelected when we sync on an hourly basis )

- Should we hide the details field on the issue creation page cause the user can't edit it anyways ?
- How do we make it more evident that issue update isn't possible on gitcoin directly?
- Once the issue has been created -> do we provide a button the funder to perform immediate sync so that if they enter something wrong -> they can fix it up with a quick sync 

### Why Is this Needed

```
tjayrush [Yesterday at 8:45 PM]
What happened is I made a bounty, canceled the bounty
(because I couldn't figure out how to edit it -- I should have just edited the 
issue on GitHub, I later figured out), then I re-created the same bounty.
There's probably some bug in your code there, 
because I was also re-directed at some point to the previously-canceled issue.


thelostone-mc [20 hours ago]
@tjayrush was it unclear ? :sweat_smile:
we had pushed in changes to make it evident that edits are allowed via 
github issue only

tjayrush [18 hours ago]
@thelostone-mc "Was it unclear?"  Yes. I think it was, but then I am one of
those users that literally  reads nothing on the screen, so maybe I didn't 
look close enough. I think if I would have seen an "Edit" button, and 
when I pressed it, and it then said "You can't edit here, but go to the
GitHub and edit the  issue there," it might have made more sense.


tjayrush [18 hours ago]
The fact that I couldn't find an edit button (maybe I missed it) made me 
think that delete and re-create  was the only way to edit. I later 
realized that you're syncing to the GitHub repo but only periodically
when I re-created the issue but was returned to the
previously-canceled bounty. So, yes, it was very unclear.


tjayrush [18 hours ago]
Perhaps a small header on the "copied from GitHub text" saying 
something like "Copied 20 minutes 
ago..." would have helped me better understand what was going on.


thelostone-mc [7 hours ago]
Ah that is good feedback! Makes sense
@Pixelant [Gitcoin] we should add this in

Thanks @tjayrush for the feedback

```

### Reproduction

- Create an issue on `gitcoin.co/new`

**Comment by PixelantDesign** [comment]
@thelostone-mc 

> Should we hide the details field on the issue creation page cause the user can't edit it anyways ?
- We can pull it in as a read only (not in a form field), displaying all of the content.

> How do we make it more evident that issue update isn't possible on gitcoin directly?
- We could add a note that says " Please edit the details on Github"

> Once the issue has been created -> do we provide a button the funder to perform immediate sync so that if they enter something wrong -> they can fix it up with a quick sync
- Resync button after editing is a good idea.

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/1943
