### ISSUE TITLE
Request to Increase Allowable # of Issues In Progress

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1944]
### Discussion

For the use case of - a contributor has submitted 2 PRs, is working on 1, and would like to pick up another issue...should we allow for the contributor to notify us that 2 PRs are pending maintainer approval and he has bandwidth?

<img width="665" alt="screen shot 2018-08-05 at 2 24 16 pm" src="https://user-images.githubusercontent.com/238235/43688679-50638d76-98bb-11e8-9cf3-cbed83c14165.png">

Currently we need to manually increase the number of issues taken on.

**Potential UX**
- Add a place in profile to allow a user to request to work on more than 3 issues at a time.
- Pop a dialog that displays the following:
We see these are the 3 issues you currently have open:
Show
1. Issue One
2. Issue Two
3. Issue Three
 
Please associate the PRs to these issues...maybe it asks for a link URL to each. But once we have the  PR detection working, it could help.

Add a disclaimer with checkbox
By requesting to take on additional issues, I intend to prioritize and complete the previously opened PRs if there are changes or feedback in order to respect project timelines.

Contributor clicks [Submit]

Email notification is sent that they can now take on additional work.

Notes for the group --
* The contributor must have two open PRs in order to take on an additional issue. 
* If Contributor satisfies the above, they're able to take on a 4th issue.
* Should this be a case by case or a one time (once you make a request, they'd always have the ablity to take on 4 issues)?

--------------------

We currently manually allow contributors to take on more tasks by case by case request.
How do we determine how many additional that can be taken on? 

Thoughts @owocki @thelostone-mc @SaptakS @mbeacom

**Comment by darkdarkdragon** [comment]
@PixelantDesign sounds good.
Some notes:
1. There is no point in asking for prs urls here. We have field for pr url in Submit form, but is optional. Probably we should check here if work was submitted with urls to prs
2. If contributor has to prs with urls I think it's ok to grant him 4th issue upon request automatically.

**Comment by PixelantDesign** [comment]
@darkdarkdragon 

> Probably we should check here if work was submitted with urls to prs.
Agreed on this.

> If contributor has to prs with urls I think it's ok to grant him 4th issue upon request automatically.

I think this could work
