### ISSUE TITLE
Make it Clear for Funders - How to Payout

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1950]
### User Story

As a funder, I want a reminder of the wallet address associated with an Issue and how to pay out the bounty. Make this clear for funders.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)

Funders aren't sure how to pay

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Show a persistent message on all funded issues for a month on all issues to see if this helps.
- [ ] Allow for ability to dismiss this message
- [ ] Display funder icon and their wallet address at the top of issue details
- [ ] Add a similar reminder on the bottom of Gitcoin Bot.
"Ready to Payout the Bounty? **Click payout** on the issue details page"

### Reference
<img width="1079" alt="43538000-d767f6fc-958e-11e8-9135-3fdb8bdc2e14" src="https://user-images.githubusercontent.com/238235/43731236-e21c8cb6-997b-11e8-933b-45baa80b7bc1.png">

Background Info [Here](https://github.com/gitcoinco/web/pull/1853)

[FunderPayout Banner2.zip](https://github.com/gitcoinco/web/files/2263498/FunderPayout.Banner2.zip)

**Comment by owocki** [comment]
in the 'funded by 0x0000000000000000000000000000' could we collapse the address to be '0x000...000' ?

**Comment by PixelantDesign** [comment]
Yep, we can try that. I initially had it that way since it's sort of a standard, but thought maybe best to not abstract anything.

**Comment by thelostone-mc** [comment]
@octavioamu any chance this function you wrote up is modular so that we can reuse it here ?

**Comment by octavioamu** [comment]
@thelostone-mc yes you can pass the like an attr to an html element with the hash 
```
<div data-truncatehash="3">1234567891233456789asd</div> // will be 000...000
or 
 <div data-truncatehash>1234567891233456789asd</div> // will be 0000...0000 

The file name is trunctate-hash.js

**Comment by owocki** [comment]
hows thsi going?  who is working on it?

**Comment by thelostone-mc** [comment]
@SaptakS is but he needed a function which @octavioamu had written up in the other repo !

**Comment by octavioamu** [comment]
@SaptakS @thelostone-mc I will post the link to the code in our private channel.

**Comment by PixelantDesign** [comment]
@SaptakS @thelostone-mc 
Let's proceed with just the banner as designed with the ability to dismiss.

**Comment by PixelantDesign** [comment]
Closing since this is merged
https://github.com/gitcoinco/web/pull/1853#issuecomment-413859256
