### ISSUE TITLE
Submit Work Prior To Approval

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1951]
**Expected behavior**
Users should not be able to 'Submit Work' on a bounty until they have been approved to work on the bounty.

**Screenshots**
[Example here.](https://github.com/OriginProtocol/origin-dapp/issues/329)

Individuals were not yet 'approved' this task. However, 3 submitted work. This should have not been the case. You should only be able to submit work if you've been chosen to work the bounty. 

**Thoughts**
The downside would be that someone is pending 'approval' before working, but it has the upside of ensuring that random submissions don't come across for a bounty which wasn't anticipating it.

**Comment by pinkiebell** [comment]
Is this free to grab? 😄

**Comment by PixelantDesign** [comment]
Yes! @pinkiebell 

cc: @thelostone-mc @SaptakS @mbeacom

**Comment by PixelantDesign** [comment]
Update from @thelostone-mc 
There are a few things that still need to be resolved from @pinkiebell from a PR perspective.
