### ISSUE TITLE
as a user, i want it to be clear that gitcoin was initially bootstrapped, so the not_a_token page doesnt come off as arrogant

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1953]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want it to be clear that gitcoin was initially bootstrapped, so the not_a_token page doesnt come off as arrogant
see reference convo: 
http://bits.owocki.com/2e310R1z0C0O/Screen%20Shot%202018-08-06%20at%204.09.30%20PM.png

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so we dont come off as super arrogant

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

This page should describe that we were bootstrapped originally and then found funding

**Comment by kuhnchris** [comment]
uh...
