### ISSUE TITLE
Create "Grants Detail - Admin" Page - Design

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#1960]
### User Story

As a Grant creator, I want to view and edit the details of my grant so that I can change details, withdraw funds, give updates, and know how many funders I have. 

### Why Is this Needed

The "Grant Detail - Admin" page is needed to allow a grant creator to edit their grant, withdraw funds, and update their supporters.

### Description

*Type*: Feature

### Definition of Done

- [ ] Page displays:

1. [x] Name of Project
2. [x] Description of project
3. [x] Project URL
4. [x] Team members
5. [x] Total amount sought for grant
6. [x] Milestones and projected timeline 
7. [x] Project image
- [x] Page has a "withdraw" button that is displayed to the grant's owner
- [x] Page displays current funders of the projects
- [ ] Page displays how much monthly funding the grant is receiving 
- [x] Page has an updates feed that displays recent happenings in the project. Likely these will be recent commits in github, articles written by the team, and updates written directly to the grant. 
- [x] ALL OF THE ABOVE INFORMATION SHOULD BE EDITABLE OR HAVE AN INPUT BOX TO PROVIDE CONTENT
- [x] Page has standard Gitcoin header and footer
- [x]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Existing assets can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by justpixel** [comment]
I've tried to keep al the edits inline. 
![grant detail admin](https://user-images.githubusercontent.com/7627020/44090119-c02fa636-9fd1-11e8-8ca5-eb77577e4138.png)

**Comment by justpixel** [comment]
Design:
![grant detail admin](https://user-images.githubusercontent.com/7627020/44267184-f7410500-a235-11e8-9467-a2c8c01d212c.png)

**Comment by captnseagraves** [comment]
@eswara I believe you have the implementatoin of this page assigned. Instead of a "Withdraw Funds" button, can we have a "Transaction Summary" page?
