### ISSUE TITLE
See More Than One PR on Staging at a Time

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1962]
### User Story

As a core team member, I'd like to be able to view more than one thing on staging at a time.

### Current Behavior
We have a lot of prs that need to get reviewed - work created from the internal team as well as the community. Currently we can only view one PR on staging at a time. This slows down and is sometimes a blocker in the workflow.

### Potential Solution

**Create a way to see multiple PRs at a time on staging.** 
- Currently I manually ask either Mark, Aditya, or Saptak to put things on staging, and what the cue looks like. Some members of the team do not have access to push things to staging.

- Would also be great to be able to create a short que - what is up next (pulling priorities from the entire list of PRs)

**Nice to have**
Not sure if it is possible to have dedicated place for contributor PRs and Internal PRs

### Definition of Done
Create solution to improve the above.

### Additional Information

Thoughts @owocki @mbeacom @SaptakS @thelostone-mc

**Comment by pinkiebell** [comment]
You could create a new branch, merge selected pull requests into that and use a continues integration platform.
I think codefresh has a github implementation and staging environments.

**Comment by PixelantDesign** [comment]
@mbeacom @owocki @SaptakS ?

**Comment by kuhnchris** [comment]
I think this should be combined with the "new" deployment strategy of @danlipert - rolling merge into master and (hourly or so) shove into staging for 6 days a week, on the 7th day (or on demand) we stop deployment and test the state that gets new "stable" and deployed. Closing this one as we open a new one for the new deployment strategy.
