### ISSUE TITLE
as a system administrator, i want KYC/AML on bounties, so that i know that no nefarious actors are using the system

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1967]
### User Story

as a system administrator, i want KYC/AML on bounties, so that i know that no nefarious actors are using the system

### Why Is this Needed

Implementing Wyre forms the foundation for two things to happen on Gitcoin: KYC AML and connection to fiat.

1. Bounty hunters can get paid out in fiat.
2. Bounty funders can pay their bounties in fiat and still end up with a bounty in DAI.
3. (Future) KYC / AML for grant payment.

**Who cares?**

1. _Enterprises_ don’t want to deal with the accounting for magic internet money.
2. _Foundations_ often have AML / KYC rules to follow around grants / donations.
3. _Developers_ outside of Web3 don’t necessarily believe in the ecosystem but still want to support OSS.

Also, legal recommends it.

### Description
as a system administrator, i want KYC/AML on bounties, so that i know that no nefarious actors are using the system

we will want to do KYC/AML for anyone who has created or fulfilled a bounty > $1k.

this will involve a name/address check, as well as a check that funders are not from a country with whom US citiziens are banned from doing business with. we will also check the funders against known terrorism and money laundering entities

These databases are all public: https://www.treasury.gov/resource-center/sanctions/SDN-List/Pages/fuzzy_logic.aspx. 

while gitcoin never touches any of the funds associated with usage of it's platform, we just want to do this as a good will gesture. this is to make sure that gitcoin's funder matching service is not used for any nefarious reasons. 

demo of the provider we may use https://idm-ico-demo.herokuapp.com/register/ ( identitymind.com )

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature
### Current Behavior
[comment]: # (Describe what actually happened.)
no KYC/AML
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
KYC/AML

**Comment by owocki** [comment]
todos q1 2018:
- add latest Wyre API docs
- should this be a premium feature that we charge for?
- should we add to gitcoin grants CLR as sybil resistence?

**Comment by ceresstation** [comment]
New documentation: 

https://wyre-beta.readme.io/docs/

And a basic demo:

https://s3-us-west-2.amazonaws.com/demo.sendwyre.com/index.html
