### ISSUE TITLE
No values in "Denomination" input

### ISSUE THREAD

**Issue by bdresser** [gitcoinco/web#1970]
Trying to post a bounty, but the "denomination" / currency field is empty. Tried typing in `ETH` but no luck.

I'm used to it just pre-filling ETH and I think it usually has other options like DAI too. Works fine on Brave, which is odd (but good, bc I still posted my bounty 😄)

<img width="345" alt="screen shot 2018-08-08 at 6 04 43 pm" src="https://user-images.githubusercontent.com/1016190/43872274-c4fd457e-9b35-11e8-8b65-11d102c1eb18.png">

seeing this in the console
```
Failed to load resource: the server responded with a status of 404 ()
/sync/get_amount?amount=0.001&denomination=:1
```

on Chrome 67

**Comment by owocki** [comment]
@bdresser what metamask network are you on?  this should only happen if you're on an unsupported network like ropsten or a custom local network

**Comment by vs77bb** [comment]
@owocki @bdresser There definitely is a latency issue here sometimes... if you wait a bit, the tokens show up, but it sometimes doesn't load as fast as the rest of the page. Thanks for raising an issue here.

cc @mbeacom @SaptakS

**Comment by bdresser** [comment]
Was on mainnet. Tried a bunch, but very possible I was being impatient. 

Worked for me today though, so feel free to close. 

Keep up the good work y'all!

**Comment by mbeacom** [comment]
Thanks for the heads up @bdresser !

**Comment by bdresser** [comment]
hey this is happening again

<img width="1437" alt="screen shot 2018-08-14 at 3 17 34 pm" src="https://user-images.githubusercontent.com/1016190/44121513-37ee1380-9fd5-11e8-9e56-439f47a3dab6.png">
