### ISSUE TITLE
Multi-Party Payout Recipients Not Showing in 'Work Done'

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#1983]
**Describe the bug**
Bounties paid our via multi-party payout don't show up in Issue Details. 

**To Reproduce**
[See this example](https://gitcoin.co/issue/Great-Hill-Corporation/quickBlocks/611/870) and [this one.](https://gitcoin.co/issue/OriginProtocol/origin-dapp/329/900)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
System acknowledges that multiple people completed work on this bounty and they are listed as work done, including the amount they were tipped as a part of their profile

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
![screen shot 2018-08-09 at 10 58 40 pm](https://user-images.githubusercontent.com/23297747/43938191-c802713e-9c27-11e8-8a51-b2bb83688781.png)

**Comment by owocki** [comment]
This is a good one.

I'm bountying it.

For anyone who works on this in the future.  You want to attach the `tip.username for tip in bounty.tips.filter(is_for_bounty_fulfiller=False)` in the 'work done' column on the UI

**Comment by owocki** [comment]
made a PR for this https://github.com/gitcoinco/web/pull/2040

**Comment by thelostone-mc** [comment]
Closing this as
