### ISSUE TITLE
Funder Unable to Approve Worker

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1985]
## **Describe the bug**
Funder is unable to approve a worker (using metamask account that issue was funded with).
The workers who applied also do not show up for core team members with admin privileges. 

**Link** https://github.com/Bounties-Network/bounties.network/issues/7

## **To Reproduce**

Create an issue without logging in.

## **Expected behavior**

Be able to pay out using correct MM account

Funder should be able to approve worker - even without being logged in.

We should maybe remove ability to fund issue without being logged in.

@owocki @thelostone-mc @SaptakS @mbeacom 

## **Screenshots**

**Email Received**
<img width="642" alt="screen shot 2018-08-10 at 12 47 58 pm" src="https://user-images.githubusercontent.com/238235/43970914-247990ee-9c9d-11e8-9bad-1892aa05f476.png">

**Screenshot from my Admin Account**
<img width="943" alt="screen shot 2018-08-10 at 12 50 33 pm" src="https://user-images.githubusercontent.com/238235/43970931-3720f354-9c9d-11e8-9d8b-7c605f765506.png">

**Comment by owocki** [comment]
http://bits.owocki.com/2f3Q1h1P342w/Screen%20Shot%202018-08-10%20at%2011.28.41%20AM.png

per convo with @PixelantDesign on gitcoin slack, this was a problem with the bounty submitter not being logged in at the time, so we can't authenticate that they're the funder when they go to approve the bounty hunter!
 
@mbeylin we just updated the bounty such that your github handle is the handle on the bounty. @mbeylin you should be able to approve workers now!

as a fix it twice, we're going to prevent users who aren't logged in from being able to submit bounties.

**Comment by mbeylin** [comment]
>we're going to prevent users who aren't logged in from being able to submit bounties.
Great work 👍
