### ISSUE TITLE
add troubleshooting to RUNNING_LOCALLY_DOCKER.md for "port is already allocated" error

### ISSUE THREAD

**Issue by zevaverbach** [gitcoinco/web#1987]
### Additional Information
Would you accept a PR implementing this?  It would be something along the lines of "look for the already-allocated port number in the output of `sudo lsof -i -P -n`, then do `kill -9 <PORT_NUM>`.  The app should start without an error now."

**Comment by owocki** [comment]
good idea!

@mbeacom what do you think?
