### ISSUE TITLE
Torrent of dev flow?

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#1989]
`Access Gitcoin's torrent of dev flow` is something worthy $10k but what's the price is for?

### Done

Show a tooltip next to menu item.

### Comments

It is been a while and I missed everything about monetization. ;) I would replace $10k with ETH flow though. It is more exciting to burn ETH than to deal with those ###.

**Comment by kuhnchris** [comment]
@abitrolly is this still on the current page?

**Comment by abitrolly** [comment]
I don't see anything. Don't even remember where it was. Will do screenshot next time.
