### ISSUE TITLE
Workers who are not approved to work on a task should not be warned for abandonment, the 3-day Gitcoin bot nudge should start from the point of approval, not the point of application

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#1996]
### User Story

Workers who are not approved to work on a task should not be warned for abandonment. If they are approved, their 3-day Gitcoin bot nudge should start from the point of approval, not when they applied. If they are not approved, the 3-day Gitcoin bot nudge should not happen at all.

### Why Is this Needed

Gitcoin bot is overzealous in warning non-approved workers for 3-day abandonment, despite the workers having not started work. Gitcoin bot also starts the countdown for 3-day abandonment at the workers application stage, not the approval stage, leading to a premature abandonment warning for workers. This may be irritating for workers and provides less time for them to show WIP.

### Description

[Issue Explorer Check-in Re: Issue Explorer Check-In (8/6/18 / 8/9/18 (Frank))](https://docs.google.com/document/d/184kZSHsB2enyUlzxKFEb8yUSr7o4g8eg1xPpUs11hSU/edit?ts=5b719d7b)
[Example 1 - Worker warned for abandonment but did not get approved, comment was deleted](https://github.com/gitcoinco/web/issues/1855)
[Example 2 - Gitcoin bot nudging despite workers still pending approval](https://gitcoin.co/issue/ethereum/solidity/4743/935)
[Example 3 - Gitcoin bot nudging despite the issue being closed](https://gitcoin.co/issue/XLNT/gnarly/3/928)

### Current Behavior

1. Workers who apply but are not approved are warned for 3-day abandonment by Gitcoin bot.
2. Workers who apply and are approved are warned for 3-day abandonment by Gitcoin bot 3 days from when they applied.

### Expected Behavior

1. Workers who apply but are not approved are not warned for 3-day abandonment by Gitcoin bot.
2. Workers who apply and are approved are warned for 3-day abandonment by Gitcoin bot 3 days from when the were approved.

**Comment by owocki** [comment]
fixed via https://github.com/gitcoinco/web/pull/1857
