### ISSUE TITLE
As a contributor, I would like the Gitcoin bot to tell me whether a bounty is cooperative or not

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2000]
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Some contributors are not aware that larger issues they're viewing are cooperative, for example in https://github.com/duaraghav8/Solium/issues/94, and shy away from taking on the whole task.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)

The Gitcoin bot could display some additional text depending on the type of bounty so that users finding it directly from Github have more context.

**Comment by PixelantDesign** [comment]
I actually had this in an earlier version of Gitcoin Bot updates.

**Comment by PixelantDesign** [comment]
bounty after Gitcoin Bot story is finished.

**Comment by kuhnchris** [comment]
Is the story finished?
