### ISSUE TITLE
Implement "My Grants" Page - Frontend

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2019]
### User Story

As a Grants user, I want to see all grants that I am contributing to or am an administrator of so that I can easily find grants I am involved in.

### Why Is this Needed

The "Fund Grant" page is needed to allow users easily find grants they are involved in.

### Description

Type: Feature

### Definition of Done

- [ ] Frontend implements designs at https://github.com/gitcoinco/web/issues/1909 on the https://github.com/gitcoinco/web/tree/grants branch

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

History of the project can be found at this PR: #674
More information about the Dev Grants project can be found here: #1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @eswarasai

**Comment by eswarasai** [comment]
Assigning this to @octavioamu

**Comment by captnseagraves** [comment]
@octavioamu can you handle this in the next week or over the weekend?

**Comment by octavioamu** [comment]
Yes I'm delayed, sorry for that but I will do it

**Comment by octavioamu** [comment]
I unassigned myself from this one, I believe is a good start point maybe @thelostone-mc want to take it. 
Also I think who take this one should do the index pagination too, mostly the same request without the owner id I believe

**Comment by captnseagraves** [comment]
@thelostone-mc @SaptakS Hey guys, do one of you have the bandwidth to take on this view? It is meant to provide a single point for a user to find grants they are involved with, instead of needing to search through all grants.

**Comment by captnseagraves** [comment]
@thelostone-mc @SaptakS This view and "Grants Admin" need to be priorities for the next bit of time. They are the last two view of the application that have not been created yet. This issue should be clear. We had some design work done today. I think it has settled, but I havent gotten a response from @willsputra via slack yet, and it hasnt been posted to the design issue. It would be awesome if we could begin inplementing what is designed in this image. other relevant issue is https://github.com/gitcoinco/web/issues/2325. This is where I expect final designs to be posted in addition to the creative repo. 
![my grants](https://user-images.githubusercontent.com/22862292/46898078-fdbdb880-ce43-11e8-9060-f4e25d088671.jpg)

**Comment by thelostone-mc** [comment]
@captnseagraves @willsputra.

Before I make out a base template (just to get the ball rolling)

- The grant card for my grants page and the grants landing page look very different? 
Was it done intentionally ? If yes could we ensure both look consistent ? 
If not -> which one do I use ?
- Why would we have an edit button within the card ? Where would it do redirect to?
(if i own a grant vs if i contribute to a grant )
- `grants/new` takes in an array of users. who is decided as the true owner of the grant (as I see only name in the design mockups)
- If I created a grant for myself and @SaptakS -> would it appear on both of ours my-grants page  ? 
- What if we have more than 3 grants ?  Would they be displayed as card one below the other ?
Does that take up too much screen space ?

**Comment by thelostone-mc** [comment]
update:  I've followed the new design for the card for grants and it seemed a lot cleaner

**Comment by thelostone-mc** [comment]
@captnseagraves 

1. I've stuck to what @willsputra design as that felt a lot cleaner
2. Will drop the `edit` button on the card for now.  
    Redirecting to grant-admin only makes sense if I own the grant. Won't make sense if I'm part of the team / contributing to it. Wouldn't that confuse the user in terms of behavior ? Might I suggest introducing two links one to take you to the details page and another to admin (latter is only visible to admin ) 
   PS: ( @eswarasai is the admin thing in yet ? )
3. In the create form -> we don't explicity ask for user ( I'm assuming we have a check in place to ensure grant creation is allowed only for logged in users )
4. Makes sense. cc @willsputra looks like we are good 
5. Hmm not sure how would the pagination would look only for that row 🤔 while we have the txn history listed below it. cc @SaptakS

**Comment by willsputra** [comment]
@captnseagraves @thelostone-mc 

Thanks for the feedback! 😄

2. `Edit` was added to make it clearer that you can click on that card to edit your grant.
For funders, editing might mean modifying their contribution.
For owners, editing might mean editing their grant, withdrawing fund, etc.
If an owner can also view the grant details from the admin page anyway (since admin page = details page but editable #2026 ), maybe we don't need two links?

5. If it becomes too long, maybe we could also consider having a `View All` button, which will reveal the rest of my grants?
<img width="1087" alt="screenshot 2018-10-16 23 03 10" src="https://user-images.githubusercontent.com/19514207/47027154-7ea8e700-d199-11e8-91ad-e117cbae7c9b.png">

@PixelantDesign would love your thought here too. 🙂

**Comment by captnseagraves** [comment]
@SaptakS @thelostone-mc can we add some copy for when a user does not have any subscription? Something like, "It looks like you are not supporting any grants yet. You can check out all of the projects seeking funding here (link to index page)"

**Comment by thelostone-mc** [comment]
@captnseagraves you mean like a placeholder ? 
I could throw in the robot prime logo and below that stating 

>It looks like you are not supporting any grants yet. You can check out all of the projects seeking funding here (link to index page)

unless @willsputra has something for this 🤔

**Comment by willsputra** [comment]
@thelostone-mc @captnseagraves Maybe we could use a layout similar to https://github.com/gitcoinco/web/issues/2508. What do you think?
![grants no subscriptions](https://user-images.githubusercontent.com/19514207/48269483-a4609d80-e472-11e8-9d9d-2f8bbbe13817.jpg)

**Comment by captnseagraves** [comment]
@willsputra Yes, that is great! @thelostone-mc is this something you have the bandwidth to implement in the next few days? If you're crunched for time we can go with the robot prime logo and copy above for the time being.

**Comment by thelostone-mc** [comment]
@captnseagraves consider it done :)
