### ISSUE TITLE
Implement "Grants Detail" Design - Frontend

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2021]
### User Story

As a Grants user, I want to view the details of a grant so that I can know if I want to fund the project, know what the status and recent updates for the project, or know how many funders I have. 

### Why Is this Needed

The "Grant Detail" page is needed to display what the current state of a grant and its associated project is. It will display the information captured in the "Create Grant" page, the current funders, and an update feed. It will also allow different users to go down the withdraw, fund, and cancel backing flows depending on the users' role.

### Description

*Type*: Feature

### Definition of Done

- [ ] Frontend implements designs at https://github.com/gitcoinco/web/issues/1905 on the https://github.com/gitcoinco/web/tree/grants branch

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

History of the project can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @eswarasai

**Comment by captnseagraves** [comment]
@eswarasai  do you have time to handle this over the weekend?

**Comment by captnseagraves** [comment]
@eswara Checking in on this. If you have any progress can you submit a WIP PR?

**Comment by thelostone-mc** [comment]
@captnseagraves what's the state on this  ?  
I know the milestones display is handled [here](https://github.com/gitcoinco/web/pull/2395)

Is the rest sort of built out / do we have PR ?

**Comment by captnseagraves** [comment]
@thelostone-mc Currently, we need the "Cancel This Grant" button to appear when in admin view. we also need to make the activity/update section dynamic, which I think @mark has on his todo list?
