### ISSUE TITLE
Implement "Grants Index" Page - Frontend

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2025]
### User Story

As a Grants user, I want to see and search all possible grants so that I can contribute to projects that matter to me, as well as click into the different user flows of the Grants project.

### Why Is this Needed

Users need a central place to find active grants and choose different interactions to have with the grants process. 

### Description

*Type*: Feature

### Definition of Done

- [ ] Frontend implements designs at https://github.com/gitcoinco/web/issues/1889 on the https://github.com/gitcoinco/web/tree/grants branch

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

History of the project can be found at this PR: https://github.com/gitcoinco/web/pull/674
More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @eswarasai

**Comment by eswarasai** [comment]
Assigning this to @octavioamu

**Comment by captnseagraves** [comment]
@octavioamu can you handle this in the next week?

**Comment by octavioamu** [comment]
Yes!

**Comment by octavioamu** [comment]
Pagination needed, related to #1889

**Comment by thelostone-mc** [comment]
Are we doing pagination / infinite scroll here? 
I believe the rest of it is taken care of 
@captnseagraves

**Comment by thelostone-mc** [comment]
Yup I'll add that in ! Pinged @willsputra if he needed to be done in a neater manner.
Once I get that , I'll add it 👍

**Comment by willsputra** [comment]
@thelostone-mc thoughts? took cues from Kudos Marketplace for the bottom part (the search field, card style...)

![grants index](https://user-images.githubusercontent.com/19514207/48426152-27e6fb00-e7a1-11e8-9bc7-ffd4602093d3.png)

**Comment by captnseagraves** [comment]
@PixelantDesign @thelostone-mc I'm all for it!

**Comment by owocki** [comment]
LGTM
