### ISSUE TITLE
Contributor Landing Page CSS Bug

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2041]
<img width="1091" alt="screen shot 2018-08-20 at 10 00 27 pm" src="https://user-images.githubusercontent.com/238235/44376028-9a0eb300-a4c4-11e8-8c36-458da0438964.png">

**Comment by thelostone-mc** [comment]
@SaptakS we've taken care of this right ?

**Comment by thelostone-mc** [comment]
@SaptakS already fixed this up

<img width="414" alt="screen shot 2018-08-29 at 7 41 11 pm" src="https://user-images.githubusercontent.com/5358146/44793280-826db380-abc3-11e8-9e8f-6d2c72c63c55.png">
