### ISSUE TITLE
Make Clearer How to Submit Work

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2042]
### Discussion

Feedback from ETH India

Users were struggling with the submit work and getting frustrated even though their metamask was locked and it clearly indicated on the screen.

Ideas: We could make this more guided.
@thelostone-mc are you able to provide anymore information on what you think they struggled with?

**Comment by thelostone-mc** [comment]
They had installed metamask but the user was logged out.
After a few seconds of confusion -> he opened metamask and then was confused when he still saw a alert box telling him he was on the wrong network.

The alert box was pretty clear. But i guess his focus was at the robot in the center of the page.

**Comment by PixelantDesign** [comment]
@willsputra any ideas here?

**Comment by willsputra** [comment]
pop up sounds good! I like how CryptoKitties does it 🤩

<img width="764" alt="screenshot 2018-09-27 18 13 53" src="https://user-images.githubusercontent.com/19514207/46139754-f7dfa900-c281-11e8-8005-fa610daa5739.png">

**Comment by willsputra** [comment]
Ours could look like this:

![metamaskpopup](https://user-images.githubusercontent.com/19514207/46154430-b7932180-c2a7-11e8-8e73-817e06643098.jpg)

**Comment by PixelantDesign** [comment]
That's cool @willsputra I like this direction. 
Could we add an X to close in the upper right?

I also like how crypto kitty does the kitty wallpaper on their browser background in the dialog...could we do something fun like that?

**Comment by willsputra** [comment]
Here's the latest popup design! @thelostone-mc @PixelantDesign 
![metamaskpopup](https://user-images.githubusercontent.com/19514207/46248020-46d63b80-c446-11e8-98b4-aab9f33c5711.jpg)

Sketch file: https://drive.google.com/open?id=1XZltilrWk5iI1rZ3RFc2coTzXYx9UAkI

**Comment by thelostone-mc** [comment]
Yo @willsputra  :D

UX question to you and @PixelantDesign  : 

- Which all pages do we show this &  upon what interaction does this modal appear ? 
- This means we'd end up retiring the metamask alert (orange strip) on the submit / create bounty page. Am I right @PixelantDesign 

<img width="1440" alt="screen shot 2018-10-01 at 1 44 59 am" src="https://user-images.githubusercontent.com/5358146/46262208-ad795900-c51b-11e8-8cda-f92264abed13.png">

If that is taken care -> we can take bounty this out :)

**Comment by PixelantDesign** [comment]
Hmmm...I'm not sure if belongs in a modal....from what you mentioned @thelostone-mc users at Eth India didn't know that they needed to unlock metamask. Maybe we show this screen and the orange banner together. Until users unlock it....thoughts? Can we see what this looks like @willsputra ?

**Comment by willsputra** [comment]
@PixelantDesign showing both the orange banner and modal would look like this

![metamask](https://user-images.githubusercontent.com/19514207/46569033-b1750300-c981-11e8-9836-2ddecab2d947.jpg)
