### ISSUE TITLE
as a user, i want gitcoin.co/inbox, so i can manage my notifications (and action items)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2050]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want gitcoin.co/inbox (or gitcoin.co/notifications), so i can manage my notifications

### Why Is this Needed
its easy to lose track of your notifications

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No inbox
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Inbox 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

User can go to gitcoin.co/inbox and see a list of notifications.

* notifications can be selected or unselected.  there will be 'select all' or 'deselect all' buttons on the top, and there will also be 'mark selected as read', 'delete selected' and 'mark selected all as unread' buttons'
* notifications will be sorted chronologically and paginated
* notifications can be marked as read, marked as unread, or deleted
* each notification has a 'go' button next to it which will allow the user to process the notification (whatever action is associated with it).. when a user clicks 'go' the notification will be marked as read.

This page will be linked in the top right nav, under my user profile.

Notifications will be generated each time a user needs to take action upon something (approve worker, disapprove worker, accept worker, receive tip, etc)

Suggested model for notifications

* pk
* created_on
* is_read (default = false)
* deleted (default = false)
* copy
* action url

**Comment by PixelantDesign** [comment]
Thanks for putting this ticket together @owocki @mbeacom 

A central place for notifications is a good idea. I think it makes sense to surface maybe top 5 recent actions on the dashboard and then direct users to the Inbox to see all and manage their notifications.

Dropping users on a dashboard (your area) also makes sense, vs. starting on the landing page which is more for marketing.

**Comment by owocki** [comment]
> @owocki We received feedback from Richard Burton during ETHIndia to implement something similar. Do you think it'd be worthwhile to include some visual queue in the nav under user to indicate new/unread notifications are available?

yes

> Also, it was conveyed that a central place to manage all of a user's gitcoin centric items would be ideal. Kind of like the dashboard, but ultimately, you'd always be dropped onto "Your area" if you're logged in, opposed to the standard gitcoin landing, similar to being logged into FB, etc. Any thoughts on this? @PixelantDesign @vs77bb

agree

> A central place for notifications is a good idea. I think it makes sense to surface maybe top 5 recent actions on the dashboard and then direct users to the Inbox to see all and manage their notifications.

agree

> Dropping users on a dashboard (your area) also makes sense, vs. starting on the landing page which is more for marketing.

agree.

should we bounty this @PixelantDesign @mbeacom  or should we put it on the core contrib's radar for sept?  assuming its a priority.. that is

**Comment by PixelantDesign** [comment]
This seems like a big feature, let's build this in-house, thoughts?  @owocki @mbeacom Is there any ground work that we can lay while we figure out the ux of the front end? Curious for planning purposes.

**Comment by owocki** [comment]
yes having the frontend built already would be really useful

**Comment by willsputra** [comment]
will help out on this cc @PixelantDesign 🙂

@owocki are we going to have different types of notifications?
for example:
• issue-specific notifications would look different from, say, a general announcement
• different types of notifications would have different icons (like Facebook)

these would help users to visually differentiate the notifications more easily.

if we're going to have different types, I guess listing down the possible types would be a great first step!

**Comment by owocki** [comment]
> @owocki are we going to have different types of notifications?
> for example:
> • issue-specific notifications would look different from, say, a general announcement
> • different types of notifications would have different icons (like Facebook)

@PixelantDesign what do you think of this idea?  my instinct is to keep it simple for v1

**Comment by vs77bb** [comment]
Agree with keeping it simple and having them all in one place for now, imho. Some notifications that come to mind:

**For Funders**
- You have workers to approve on this issue. 
- Your bounty hunters hasn't responded on this issue in a few days. Remove them if you haven't heard from them?
- There is a submission against your bounty. 

**For Hunters**
- You haven't responded to this issue in _x_ days 
- This issue has been remarketed and has your skillsets. Are you interested? 
- A funder seems to have left you a comment here

Anything else?

**Comment by vs77bb** [comment]
@willsputra Agree with these. Happy to provide feedback once you get something going here!

**Comment by willsputra** [comment]
Here's a draft for notifications:

![notifications](https://user-images.githubusercontent.com/19514207/46431461-7656b200-c77e-11e8-86f2-18bd85c90af6.gif)


higher-res jpg:

![notifications](https://user-images.githubusercontent.com/19514207/46431484-879fbe80-c77e-11e8-8431-36c611c4bde5.jpg)

thoughts? 🙂

**Comment by PixelantDesign** [comment]
Very exciting @willsputra!

If I've read a notification and acted upon it, my instinct is, it should not show in the list of 5 (in the drop down). Cleans it up so that only the newest show. Thoughts?


Adding the list of potential notifications we discussed:

**For Funders**

- You have workers to approve on this issue.
- Your bounty hunters haven't responded on this issue in a few days.
- Remove them if you haven't heard from them?
- There is a submission against your bounty.
- Your bounty hunter has stopped work
- Your bounty is expiring soonYour bounty has crowdfunding added to it.

**For Hunters**

- You haven't responded to this issue in x days.
- This issue has been remarketed and has your skill sets. Are you interested?
- You have been approved for a bounty
- You have been declined for a bounty
- You have been removed from a bounty due to no responseYou have received a tip.
- Your submission has been approved
- Your submission has been declined.
- Funding has increased on a bounty that you’re working on.

@owocki @mbeacom @thelostone-mc @vs77bb

**Comment by willsputra** [comment]
@PixelantDesign makes sense! what happens if you have so many unread messages though? maybe we could put a scrollbar to prevent it from becoming too tall?

![screenshot 2018-10-04 23 11 26](https://user-images.githubusercontent.com/19514207/46483722-e15dc280-c82a-11e8-9744-7bae662136ad.png)

**Comment by willsputra** [comment]
@PixelantDesign @owocki draft for mobile. thoughts?

![home_mobile](https://user-images.githubusercontent.com/19514207/46487325-4f59b800-c832-11e8-9769-70a1c70de009.jpg)

![notifications_mobile](https://user-images.githubusercontent.com/19514207/46487326-4f59b800-c832-11e8-8397-b9547b1a7e76.jpg)

**Comment by PixelantDesign** [comment]
@mbeacom @thelostone-mc @SaptakS will one of you guys review and provide any tech guidance before we bounty this?

**Comment by owocki** [comment]
i feel like it's fairly straight forward.. it should just be a new app named 'inbox' with one model `Notification` that has the following fields

- pk
- created_on
- to_user_id
- from_user_id
- CTA_URL
- CTA_Text
- message_html
- is_read (bool)

we will likely also want an easy helper function that can be used to create new `Notification`s

**Comment by PixelantDesign** [comment]
Closing this one and moving to a clean ticket #2404

**Comment by vs77bb** [comment]
👍
