### ISSUE TITLE
Watch issues and be notified 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2053]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a contributor, I want to be able to watch an issue that is being done by other contributor so if the contributor give up I will know it and I can click "start work". 
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Sometimes I find a task I would like to work and is already taken, but sometimes this tasks are left by the contributor and I only know If I get into this task again and check it. 
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
We've had requests to follow an issue for this reason.

**Comment by kuhnchris** [comment]
Is this still a feature that is frequently asked?

**Comment by octavioamu** [comment]
yes, is kind of the idea of having favorites . With that we can implement this feature for bounties and many others

**Comment by kuhnchris** [comment]
OK, so I assume we can close this in favor of the favorites / issue.
