### ISSUE TITLE
Update Issue Expiring Email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2061]
### User Story

As a funder I'd like to understand all of my options as it relates to an expired issue.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

### Current Behavior
[comment]: # (Describe what actually happened.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [x] Design is updated to account for extend expiration and cancel issue
- [ ] Updates are applied to the email template (code)

### Additional Information

<img width="1087" alt="screen shot 2018-08-22 at 9 27 07 am" src="https://user-images.githubusercontent.com/238235/44466526-79db1300-a5ee-11e8-87db-7263de7c0b4b.png">
<img width="1115" alt="screen shot 2018-08-22 at 9 27 17 am" src="https://user-images.githubusercontent.com/238235/44466540-7fd0f400-a5ee-11e8-85ca-410d79bb783e.png">

**Comment by PixelantDesign** [comment]
@SaptakS Here is the update for an expired bounty...
This design encourages extending of the expiration date since we don't want funders to cancel the issues. Would it be possible to take the user directly to the issue with the expiration dialog open once they click this bbutton?

If funders want to cancel the issue, they should go to the issue details page, as stated below the CTA.

Let me know if you have questions!

<img width="602" alt="screen shot 2018-08-22 at 11 03 07 pm" src="https://user-images.githubusercontent.com/238235/44502566-1ee20400-a660-11e8-99fa-756b643bbbce.png">

**Comment by SaptakS** [comment]
Should we completely strip off all the details about the bounty that we showed previously? That might help one decide, right? Also, should we provide a button to go to the issue details page?

**Comment by owocki** [comment]
issue details page button makes sense to me (though maybe its just below the fold under 'funded issue details' in the design)

@PixelantDesign i like how concise the design is for this!

**Comment by PixelantDesign** [comment]
@SaptakS  Funder needs the details to reference. I would leave it. You could shorten it up if you want to tidy up the email. I think we should prioritize extending the issue. In the text below we could LINK to issue details as a text link.
