### ISSUE TITLE
As a developer on Gitcoin developing for Gitcoin, I would like some direction on how to use the Rinkeby network to test out Gitcoin

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2065]
### User Story

As a developer on Gitcoin developing for Gitcoin, I would like some direction on how to use the Rinkeby network to test out Gitcoin.

### Why Is this Needed

If I'm a developer new to the space and don't actually have an issue to bounty or any ETH, I would still like to be able to see the the layout of the Gitcoin product and understand the bounty hunter / funder flow.

### Description

Instructions on how to use the Rinkeby network should be included on the Gitcoin help page (perhaps under Web3), and in the [contribution guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md).

### Current Behavior

There aren't any instructions under help or the contributing guidelines on how to use the Rinkeby network for development and testing purposes.

### Expected Behavior

Instructions on how to use the Rinkeby network for development and testing purposes should be included on the help page and contributing guidelines.

### Additional Information

1. https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md
2. https://gitcoin.co/help

![screen shot 2018-08-22 at 08 50 49](https://user-images.githubusercontent.com/7516920/44474929-a5f39580-a5e8-11e8-970c-ee0cf5b82404.png)

**Comment by frankchen07** [comment]
@PixelantDesign - I can document some of the copy necessary to close this issue once we go through the process of getting me set up to use Rinkeby. :)

**Comment by frankchen07** [comment]
@mbeacom - can you post the link where you updated this in the FAQ (the location of the text below), and I can close out this ticket. I didn't see it on the help page: https://gitcoin.co/help

```
#### On-chain activities

`Q: Which network should I be using for local testing?`

It is recommended to use the `Rinkeby` testnet for local development testing.  You can receive some testnet eth by visiting the [Rinkeby Faucet](https://faucet.rinkeby.io/)
Alternatively, you can use the local `ganache-cli` test rpc network that ships with the docker compose stack by switching to `Localhost 8545` in Metamask.
```

**Comment by thelostone-mc** [comment]
@frankchen07 we've got it in the readme files.
https://github.com/gitcoinco/web/blob/066f78ef4fb3d7a488a14e41f55c7c99faac4f41/docs/RUNNING_LOCALLY_DOCKER.md#on-chain-activities

^Folks who wanna test out gitcoin over rinkeby are the ones who are trying to set it up locally ! 
They go through the readme docs anyways which is why we left it on the `.md` files

**Comment by frankchen07** [comment]
@thelostone-mc thanks for the link! I can close the ticket out.
