### ISSUE TITLE
Design - Replace the Gitcoin "Simple Pricing" section with a simple CTA to reach out for custom plans

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2069]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a funder I want to be able to arrange custom bug bounty and managed bounty plans instead of agreeing to fixed pricing. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently we have three main pricing tiers, but often these tiers don't fit the exact needs of maintainers using our platform. It would be great to offer custom plans as we work towards robust bug bounty and managed bounty offerings.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior and Solution
[comment]: # (Describe what actually happened.)

 Currently users are presented with the following screen:

 ![Pricing Page](https://d3vv6lp55qjaqc.cloudfront.net/items/3N0a3S1T163439221X3e/Screen%20Shot%202018-08-22%20at%209.34.03%20AM.png) 

However, maintainers may be worried about committing up front to a $20k down payment. A solution to this could be to include a single 'managed plans' section detailing our core value-add for bug bounties and managed bounties along with a call to action to reach out to us directly to work together on a custom plan that better suits their needs. 

**Sample content**

> Managed Plans
> 
> Don't have time to manage your GitHub issues or bug bounty program? Get a maintainer as a service. With managed programs you can:
> 
> - Access Gitcoin's torrent of dev flow
> - We manage the project for you
> - We advise on pricing
> - We will monitor it for you
> - We scope and define the project
> 
> [Get in touch!]

**Comment by PixelantDesign** [comment]
Let's bounty this @ceresstation ?

**Comment by thelostone-mc** [comment]
@PixelantDesign If we've got a design ready -> I'd be happy to take care of it

**Comment by willsputra** [comment]
@ceresstation @PixelantDesign @thelostone-mc here's a draft! thoughts? :)

![pricing](https://user-images.githubusercontent.com/19514207/46676579-6b36d280-cc13-11e8-90a7-39dbd0fb5a3e.jpg)

**Comment by willsputra** [comment]
tagging @owocki too. lemme know if you have any feedback :)

**Comment by owocki** [comment]
this looks good to me... the only thing is that 'managed' sort of assumes its > 10k since its to the right of 'pro'..  

so in my mind, it still anchors the pricing mechanics > $10k.. 

what do you think @ceresstation ?  you submitted the original ticket

**Comment by vs77bb** [comment]
Should we replace Pro (and the associated anchoring) with some copy regarding bug bounties?

**Comment by willsputra** [comment]
@owocki @vs77bb 

thanks for the feedback! if we're going to replace Pro to 'Contact Us' (therefore eliminating $10k), maybe it makes sense to just have 'Free' and 'Pro'?

**Comment by kuhnchris** [comment]
@PixelantDesign that was what I was looking for a while ago.
@frankchen07 @willsputra did we add this in already or is this still dangling?
