### ISSUE TITLE
Fix how navbar background image is applied

### ISSUE THREAD

**Issue by SaptakS** [gitcoinco/web#2071]
### User Story
As a user, I want to see the dropdown in all the pages and also don't want a weird overflow only because of showing dropdown in the rain pages.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Description
The navbar is inside a `header` class which has the background image applied to it. In the rain page, allowing `overflow` to the `header` class will cause weird UI problem because of rain. In the remaining pages with narrower navbar, we need overflow to show the drop down. We are already using the `#gitcoin-background` id inside navbar which is not correctly styled for this navbar and hence doesn't show up. Improving that and removing the `header` class enclosure will fix the drop down and navbar issues.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Fix twice bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Right now we have something like this:
http://bits.owocki.com/1943f923e958/Screen%20Recording%202018-08-22%20at%2002.45%20PM.gif
Fixed it currently https://github.com/gitcoinco/web/pull/2070

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
To implement the above mentioned way in navbar.

**Comment by thelostone-mc** [comment]
Closing this via https://github.com/gitcoinco/web/pull/2070

**Comment by SaptakS** [comment]
@thelostone-mc This issue to fix it twice. That pull request was just an immediate solution given it was a critical bug.
