### ISSUE TITLE
As a contributor, I don't want to have to do math to understand the total amount of a funded bounty that has additional crowd funding.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2072]
### User Story

**Estimate 3**

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Don't Make Me Think.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

### Current Behavior
User has to scroll up and down to add funded amount + crowdfunded amount

### Expected Behavior
We should display a total funded amount so that users don't have to do math.

### Reproduction
See this page https://github.com/gitcoinco/web/issues/2045

<img width="898" alt="screen shot 2018-08-22 at 11 14 21 pm" src="https://user-images.githubusercontent.com/238235/44503795-3d4afe00-a666-11e8-9f51-5a650e589320.png">

<img width="876" alt="screen shot 2018-08-22 at 11 14 33 pm" src="https://user-images.githubusercontent.com/238235/44503798-4340df00-a666-11e8-92bf-28ee66eb19f3.png">

<img width="1022" alt="screen shot 2018-08-22 at 11 15 17 pm" src="https://user-images.githubusercontent.com/238235/44503805-49cf5680-a666-11e8-8b69-a5f9c9170c15.png">

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done

- [ ] Add the **total amount** to the crowd funding message on the Gitcoin Bot **after the crowdfunded amount**.
- [x] On the issue details, show crowd funding icon next to the amount when a bounty has been crowd funded.
- [x] Show details of the crowdfunding in a hover state as shown below.

<img width="736" alt="screen shot 2018-08-22 at 11 47 25 pm" src="https://user-images.githubusercontent.com/238235/44503781-23a9b680-a666-11e8-9fa9-5a58c2aed591.png">

cc: @owocki @SaptakS @thelostone-mc

**Comment by octavioamu** [comment]
not sure about the "initial" word, maybe is not needed and that box can be the without the need of hover.

**Comment by thelostone-mc** [comment]
@PixelantDesign could we update the hover design to match the tooltips design we use currently ?
@octavioamu Yup I agree we should not keep the world initial.  Just the total bounty makes sense to me. If people wanna see who contributed -> they can just scroll down to the activity section

**Comment by PixelantDesign** [comment]
@thelostone-mc lets use the current tooltip design (Since you already know what's in the code) - I was just showing a concept here.  :)

**Comment by thelostone-mc** [comment]
coolio

**Comment by SaptakS** [comment]
Thanks to @thelostone-mc we already have the first draft. For further improvement I think the idea proposed by @PixelantDesign [here is really good.](https://github.com/gitcoinco/web/pull/2109#issuecomment-418775922)

**Comment by SaptakS** [comment]
Closing this in reference to https://github.com/gitcoinco/web/issues/2164 and #2109
