### ISSUE TITLE
SEO - Update Meta Tag

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2074]
### User Story

Meta Tag updated needed, see tab named "Pages needing Metas and H1's."  Top phrase we want should be in Title, secondary ones in the Desciption. On many pages we can pull the first part of the page copy into Meta Description tags.  

How to Check
Crawl the site with ScreamingFrog, DeepCrawl or Website Auditor 

### Definition of Done

- [ ] The above is implemented and reviewed with a Gitcoin core team member.

**Comment by thelostone-mc** [comment]
@deanramadan Do we have an account with one of these services which I can use ?

**Comment by deanramadan** [comment]
@thelostone-mc we do have a ScreamingFrog account. i'll slack you my login details that you can use

**Comment by thelostone-mc** [comment]
@PixelantDesign closing this one out as we already have a bounty out at https://github.com/gitcoinco/web/issues/2147 on this one as discussed in the marketing channel.
