### ISSUE TITLE
Create Design - "Thank you for supporting "grant X" email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2082]
### User Story

As a Grant Supporter, I want to receive an email when I begin funding a grant so that I know my transaction went through and where to find more information.

### Why Is this Needed

The "Thank you for supporting "grant X" email is needed to that users can be sure that their subscription transaction went through, they can confirm the amount they're are giving and on what time interval, and so they know where to find information about the grant and how they can cancel their recurring support. 

### Description

*Type*: Feature

### Definition of Done

- [x] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html

- [x] Email should have copy similar to:

 "Thank you for supporting 'grant x'! The world of open source is a better place because of you. 

*image of a robot hugging a big heart*

You have agreed to give xx.xx ETH every "agreed upon time interval". You can see the transaction on etherscan here: *link to transaction on etherscan*

Updates about "grant x" will be given here: *link to grant detail page*

If you ever need to you can cancel your support here: *link to cancel funding page*"

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![thank you](https://user-images.githubusercontent.com/7627020/45029397-29819d80-b051-11e8-93be-757ee4208998.png)

**Comment by justpixel** [comment]
Updated with a new illustration.
![thank you](https://user-images.githubusercontent.com/7627020/45358488-429ac900-b5d2-11e8-9921-d01c8fc851ca.png)

**Comment by PixelantDesign** [comment]
cute!

**Comment by captnseagraves** [comment]
Love the robot! Probably a v2/stretch goal, but perhaps we should create emotive robots for other uses?

**Comment by owocki** [comment]
I <3 the robot with a heart in it!  there's just something that strikes a chord with me to teach a robot to love!  i bet there are other places we could use this artwork too :)
