### ISSUE TITLE
Create Design - "New Supporter" email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2083]
### User Story

As a Grant Creator, I want to know when a user has begun support of my project so that I know when more money is being contributed. 

### Why Is this Needed

The "New Supporter" email is needed because grant creators need to know when they have more money coming and so can plan for their plan. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "You have a new supporter! 'User' has begun contributing xx.xx ETH every 'agreed upon time interval' 

You can see a transaction history and withdraw funds here: 'link to withdraw page'"

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![new supporter](https://user-images.githubusercontent.com/7627020/45029388-2090cc00-b051-11e8-9757-8fe99bde9582.png)

**Comment by owocki** [comment]
should we make john doe's avatar circular to match other avatars in the system?

**Comment by PixelantDesign** [comment]
Agree with @owocki on making avatar circular.
Is the 1ETH Everyday clickable? It currently looks clickable.

Could we look at the vertical spacing on all the emails? Some things look tight, other things look fine.

**Comment by justpixel** [comment]
Fixed.

![new supporter](https://user-images.githubusercontent.com/7627020/45358670-d371a480-b5d2-11e8-9655-751adbf8da57.png)

**Comment by PixelantDesign** [comment]
looks good!
