### ISSUE TITLE
Create Design - "New Grant" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2084]
### User Story

As a Grant Creator, I want to know that my grant has been created so that I can share out the links and attract supporters. 

### Why Is this Needed

The "New Grant" Email is needed to that grant creator can have confirmation that their grant has been created to that they can share out the grant link and attract supporters. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "You've created a new grant! Get ready to buidl and push forward open source!

The details of your grant can be seen here: 'link to grants detail page'"

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
It would be awesome to have some links to different articles like, "How to run a successful open source project", "How to attract supporters to your project", etc.

**Comment by PixelantDesign** [comment]
Should we have basic info here? Name of grant, description, how much?

**Comment by PixelantDesign** [comment]
![new grants email](https://user-images.githubusercontent.com/238235/44741749-0775a180-aacc-11e8-8da9-b9a275c39ca5.png)
