### ISSUE TITLE
Create Design - "Support Ended" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2085]
### User Story

As a Grant Supporter, I want to have confirmation that my subscription has been canceled so that I can live peacefully knowing I'm not getting charged for something I no longer want to pay for. 

### Why Is this Needed

The "Support Ended" Email is needed so the grant supporters have confirmation that their subscription has been canceled. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "Your support for 'grant x' has been cancelled. Thank you for everything you have contributed!

You can see your cancellation transaction on etherscan here: 'link to transaction on etherscan' "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![support ended](https://user-images.githubusercontent.com/7627020/45029363-1242b000-b051-11e8-8a27-d802d693e9e4.png)

**Comment by PixelantDesign** [comment]
Could we make the heart and circle red?

**Comment by justpixel** [comment]
Updated.

![support ended](https://user-images.githubusercontent.com/7627020/45358702-f13f0980-b5d2-11e8-842e-3ad9d9862961.png)

**Comment by PixelantDesign** [comment]
What is the value of the red if the green bar is 10 Eth? Or am I reading it wrong?

**Comment by PixelantDesign** [comment]
ohh gotya, I missed the 344 Eth. That makes sense now. I like the idea of displaying monthly vs total. @captnseagraves
