### ISSUE TITLE
Create Design - "Funds Withdrawn" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2087]
### User Story

As a Grant Creator, I want confirmation when my withdraw transaction has gone through so I know when I have funds to distribute and spend. 

### Why Is this Needed

The "Funds Withdrawn" Email is needed so that a grant creator knows when she has funds available to spend or distribute.

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "Your withdraw transaction for 'grant x' has gone through and your funds are ready for allocation. 

You can see your withdraw transaction on etherscan here: 'link to transaction on etherscan' "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![funds withdrawn](https://user-images.githubusercontent.com/7627020/45029353-0c4ccf00-b051-11e8-82e8-5a341d15d369.png)

**Comment by PixelantDesign** [comment]
The H1 text seems long and wordy @captnseagraves any other ideas?

What about:
Your withdrawal has been approved or has processed.
Or
Your funds are ready to be withdrawn.

Something shorter/to the point?

**Comment by captnseagraves** [comment]
Closing ticket as "withdrawal" user flow is deprecated due to metatx architecture.
