### ISSUE TITLE
Create Design - "Update Notification" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2088]
### User Story

As a Grant Supporter, I want to know when updates for grants I support are posted so I can stay up to date with what is happening and feel good about how my money is being spent. 

### Why Is this Needed

The "Update Notification" Email is needed because grants supporters should know when things happen in projects that they care about so that they can feel good about their contribution, give more, or cancel their support. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "An update has been posted for 'grant x'!

'update post here'

'link to grant detail page' "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![update notification](https://user-images.githubusercontent.com/7627020/45029346-05be5780-b051-11e8-99fb-f006979f519e.png)

**Comment by PixelantDesign** [comment]
looks good!
