### ISSUE TITLE
Create Design - "Granted Ended" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2089]
### User Story

As a Grant Creator, I want to have confirmation that I have ended my grant so that I know there will be no more monetary transactions and nothing more expected of me from the community. 

### Why Is this Needed

The "Grant Ended" Email is needed because a grant creator needs to know that their project has officially stopped seeking funding from the community and does not have an obligation to continue work. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "'Grant x' has been canceled. Thank you for using Gitcoin, we hope you'll come back to build more open source software! "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![grant ended](https://user-images.githubusercontent.com/7627020/45029329-fa6b2c00-b050-11e8-8a2f-552ea2c9ed27.png)

**Comment by PixelantDesign** [comment]
Can we do the x and circle in red?

**Comment by PixelantDesign** [comment]
Should we say why it has been cancelled? @captnseagraves

**Comment by captnseagraves** [comment]
The circle should be in red. 

This email is meant to confirm to the grant creator that the grant has ended. So they would know why it is canceled. We should think about having the grant creator post an update on why they are canceling the grant so that supporters know. 

Also, do you think "canceled" is the right term? "Ended", "terminated", "Discontinued" are other possible options.

**Comment by PixelantDesign** [comment]
@captnseagraves 
Cancelled seems right to me. Having a reason why would be even better.
Ended could mean that it was completed/fullfilled but is over?

**Comment by captnseagraves** [comment]
Will the circle easily be changed to red though css or is this a static asset?

**Comment by captnseagraves** [comment]
Going to write a ticket for an input box in "Grant Admin" view so grant creators can give a reason for canceling their grant.  Also, going to close this issue.
