### ISSUE TITLE
Create Design - "Subscription Terminated" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2090]
### User Story

As a Grant Supporter, I want to know when a grant creator has ended a grant and that my subscription payments have been canceled so that I am aware that the project is no longer seeking funding from the community and I will no longer be charged. 

### Why Is this Needed

The "Subscription Terminated" Email is needed

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 "'Grant x' has been canceled. Your subscription for the project has been cancelled and you will no longer be charged. 

You can see the subscription cancelation transaction here: 'link to transaction on etherscan' "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by justpixel** [comment]
![grant canceled](https://user-images.githubusercontent.com/7627020/45029286-dad40380-b050-11e8-974b-cb66597de8d6.png)

**Comment by PixelantDesign** [comment]
looking good! Should the top line mention the subscription being terminated?

**Comment by captnseagraves** [comment]
Should we make the circle in this one read? I believe we already have an asset that is red?

**Comment by PixelantDesign** [comment]
Yes makes sense! @justpixel
