### ISSUE TITLE
Unable to login when running local server

### ISSUE THREAD

**Issue by ajayns** [gitcoinco/web#2098]
**Describe the bug**
Can't login when I run the app locally. Clicking on the login button leads to a Github 404 page.
I'd mentioned this issue in #2047 

**To Reproduce**
1. Use the commands to run locally using the docker setup
2. Go to localhost:8000
3. Try logging in

**Expected behavior**
Login with Github should happen

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser Chrome
- Browser Version Latest

**Comment by thelostone-mc** [comment]
@ajayns did you set the env variables as mentioned in the [guide](https://github.com/gitcoinco/web/blob/master/docs/THIRD_PARTY_SETUP.md) ?

**Comment by ajayns** [comment]
Oh I was unaware of this, I'll go through this, follow the steps mentioned and get back!

**Comment by ajayns** [comment]
@thelostone-mc Hey, I'm unable to find GITHUB_API_USER after getting the token, Github just shows me the secret token that's it. Is this field my username?

**Comment by ajayns** [comment]
Is that config even required for the avatar builder? With the OAuth setup I'm able to login but I still can't access the avatar builder, it just keeps loading. No logged messages also

**Comment by thelostone-mc** [comment]
> Hey, I'm unable to find GITHUB_API_USER after getting the token, Github just shows me the secret token that's it. Is this field my username?

That is your github user name

> Is that config even required for the avatar builder? 

Yup cause the avatar builder is visible only to logged in user and we login via github.

Are you able to successfully login and see the Avatar builder options on the screen ?
If you are online  -> could you DM on slack ?

**Comment by ajayns** [comment]
I've used the config as suggested and I did login. But it shows reauth required and then it lead to this:
![screenshot from 2018-08-29 00-12-40](https://user-images.githubusercontent.com/20743219/44743522-65cc6f80-ab20-11e8-9341-21863db21ceb.png)

Once I did manage to get pass that, it just keeps loading in the avatar builder route, no logs no response

**Comment by thelostone-mc** [comment]
Ugh i can't seem to recreate this 😓 
cc @owocki / @SaptakS

**Comment by JosephDunivan** [comment]
Im looking into this issue as well. Will report my findings and hopefully get approval for a Design Documentation Workflow in the docs. I think these issues and setup instructions are way too segregated .

**Comment by kuhnchris** [comment]
I assume you managed to fix this? Closing this.
