### ISSUE TITLE
Monthly Snapshot for Contributors

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2101]
### Discussion

Ideas for Monthly Update Email for contributors

Goal
Provide a monthly snapshop and encourage engagement...

Show
- Title: Monthly Snapshot August 2018
- Date Range
- All Tasks open
- Your progress
- Tasks Resolved

Behavioral Encouragement:
People with your skillset (show tags) are completing x bounties/month
or making X amount Eth/Dai per month by completing bounties on Gitcoin.

Thoughts @owocki?

We could also do something like this for funders to encourage funding on the platform.

**Comment by kuhnchris** [comment]
Did this ever move forward?
