### ISSUE TITLE
New Nav Structure

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2112]
### User Story

As a user I want an intuitive navigation so that I understand how Gitcoin's products fit together.

**Estimate:** 8

### Why Is this Needed

We are building more products into our platform, we need an interim solution for navigation.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Primary Gitcoin Nav

### Expected Behavior
New Nav structure that makes sense for funders and contributors.

### Definition of Done

- [ ] Come up with nav structure proposals
- [ ] Test with users

**Comment by mbeacom** [comment]
Any chance we could `test with users` using the hotjar user testing/validation integration so we can log and track the interactions and feedback?

**Comment by PixelantDesign** [comment]
**WIP Design**

<img width="776" alt="screen shot 2018-09-25 at 10 56 24 am" src="https://user-images.githubusercontent.com/238235/46023016-b7c9cc00-c0b1-11e8-9ef5-a86ffb7ec594.png">

**Comment by PixelantDesign** [comment]
See comment on https://github.com/mbeacom/gitcoin-erc721/issues/134
