### ISSUE TITLE
Discuss strategy to improvise i18nise contributions

### ISSUE THREAD

**Issue by SaptakS** [gitcoinco/web#2114]
### User Story
As an user of the platform, if I see mistakes in the translation in the website and want to improve it, they shouldn't need to edit the `*.po` files. Weblate allows them to do the translation using a proper UI and then we can integrate the files from there.

**Estimate**: 5
[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed
This will help in improving contribution in the translations and then indirectly improve the translation of gitcoin as a whole.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Properly integrated with Weblate so that all our translateable texts appear for the option of translations.

### Solution
https://weblate.org/en-gb/

**Comment by SaptakS** [comment]
In this issue, I and @mbeacom are checking out different options that can be used including weblate and how we can use and the tech behind.

**Comment by kuhnchris** [comment]
So, is this still a thing that is in scope and / or maintained?
