### ISSUE TITLE
Page Layout Testing

### ISSUE THREAD

**Issue by SaptakS** [gitcoinco/web#2115]
### User Story
Integrate Page Layout testings (or Screenshot Testings) to ensure that the frontends work in different resolutions and that any commit or pull request should critcally create screenshots for all the things that we think might be needed. (Might also be a step towards functional testing)

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed
So that frontends don't break very often.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: I am thinking Selenium. @mbeacom @thelostone-mc  what do you think?

**Comment by kuhnchris** [comment]
@thelostone-mc anything decided here?
