### ISSUE TITLE
Submitting Work Twice

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2118]
**Describe the bug**
As a bounty hunter, I shouldn't see the Submit Work button if I've already submitted work. 

**To Reproduce**
Have seen it in the past and as referenced by Arjun Nemani (Gitcoiner) here.

![image](https://user-images.githubusercontent.com/23297747/44788167-eca03d00-ab5e-11e8-8fe3-d6b0b7e6db41.png)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Submit Work button not available for the bounty hunter who already submitted work.

**Comment by PixelantDesign** [comment]
I think we should monitor to see if other users are confused by this. Technically it isn't broken or a bug. The activity list does let the user know that he has already submitted work.

**Comment by thelostone-mc** [comment]
This does ensure that newbies submit their work once!
Multiple submissions means I spend more gas which as a contributor I would not want to.
Users may get confused and may click on submit work if they don't scroll down to see the activity stream 🤔 

cc @vs77bb @SaptakS

**Comment by vs77bb** [comment]
If they've already submitted work, the user can only lose money by clicking submit work again. Thus, removing that button (and the possibility of user error) seems like a win!

**Comment by thelostone-mc** [comment]
@vs77bb merged 👍

**Comment by vs77bb** [comment]
@thelostone-mc Great work!
