### ISSUE TITLE
profile: ability to enable users to update github username

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#2129]
##### Discuss

When an existing user updates his github username `foo` -> `bar`. 
He ends up losing his history on gitcoin.
Aka they'd be treated as a new user `bar` on Gitcoin and all their progress is lost

At the same time -> if a new user takes up the old username `foo`
They'd end up with the existing profile of `foo` on Gitcoin as opposed to getting a new one 

Should we build out a feature -> to help users migrate their profile if and when they update their github username ?

**Comment by octavioamu** [comment]
Interesting discussion, here is some important answer from github https://help.github.com/articles/what-happens-when-i-change-my-username/

**Comment by kuhnchris** [comment]
Did we do anything regarding this? The error keeps popping up
