### ISSUE TITLE
Search by nickname doesn't work

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#213]
##### Description
When I start entering my nickname to search box, gitcoin.co correctly proposes autocompletion, then it generates link https://gitcoin.co/explorer?q=abitrolly, but there are no issue visible funded by me. As a funder I'd like to be able to quickly see issues that I support.

##### Possible Implementation
Right now it is " Open Funded Issues w. keyword abitrolly (0 worth 0.00 USD, 0.00 ETH) ".

Solution is to figure out when keyword matches profile, change query to match profile and use different header "5 Open Funded Issues by abitrolly (0 worth 0.00 USD, 0.00 ETH)"

**Comment by owocki** [comment]
i see a few funded issues when i search for you...

![screen shot 2018-01-08 at 5 37 53 pm](https://user-images.githubusercontent.com/513929/34699458-ae20513a-f49a-11e7-84b0-7b9036484bf4.png)

is it possible that the filters on the left hand side need to be adjusted?  pls make sure that all of them say 'Any'. 

looks like you're filtering only Open funded issues

> Open Funded Issues w. keyword abitrolly (0 worth 0.00 USD, 0.00 ETH)

**Comment by owocki** [comment]
@abitrolly

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/34726383-e5cccf44-f564-11e7-9e94-43c14d134da8.png)

Changed status to Any and they all appeared.

Maybe make "Open" word in search results a dropdown box with selection? Or make those selections also filter labels right under the search box?

**Comment by abitrolly** [comment]
Sort filter is misleading. It grabs attention instead of left nav bar.

**Comment by owocki** [comment]
> Sort filter is misleading. It grabs attention instead of left nav bar.

This is fair.. Thanks for creating another issue to track this
