### ISSUE TITLE
[Slack notifications] Bounty value to USD isn't right

### ISSUE THREAD

**Issue by arku** [gitcoinco/web#2137]
See the screenshot below:

![image](https://user-images.githubusercontent.com/7039523/44930827-2a4ec280-ad25-11e8-984e-2f8360c4139f.png)

The conversion from 0.15 ETH to USD is messed up.

Another weird issue is the second notification you see in the screenshot. Since the bounty has been delivered (the first notification), it doesn't make sense to find 'New Funded Issue' notification on the same bounty. I'm not really sure what happened on this bounty. If I am missing something, do let me know.

Bounty URL: https://gitcoin.co/issue/owlboy/greatpug-public/2/1062

**Comment by PixelantDesign** [comment]
Thanks for reporting @arun1595 !

**Comment by kuhnchris** [comment]
Is this still wrong?
