### ISSUE TITLE
how it works page QA

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2139]
great to see [this](https://github.com/gitcoinco/web/pull/2121) is live!

some QA from looking at it today:

1. 
the 'd' in paid is cut off on http://localhost:8000/how/funder#project-types

<img width="482" alt="screen shot 2018-09-02 at 4 39 11 am" src="https://user-images.githubusercontent.com/513929/44955054-29737900-ae6a-11e8-8f8c-7c4501a2951a.png">

2. 
under cooperative project can we change

"The amount paid for a cooperative is at the discretion of the funder." 

to 

" The amount paid for a cooperative *bounty* is at the discretion of the funder., *Please make sure you over-communicate your budget/intent to the bounty hunter -- It helps avoid misunderstandings in the future!*"

3. small responsive issue
<img width="597" alt="screen shot 2018-09-02 at 4 49 40 am" src="https://user-images.githubusercontent.com/513929/44955138-9e937e00-ae6b-11e8-8923-dec9682a7849.png">

@thelostone-mc

**Comment by thelostone-mc** [comment]
@owocki 

> the 'd' in paid is cut off on http://localhost:8000/how/funder#project-types

Hmm the svg didn't get copied right! Fixed it

> under cooperative project can we change

Done

> small responsive issue

Sorry about that ! Did this overnight and forgot to take into account half laptop screen-size while optimizing for mobile/ tablet


Review + merge ? ^_^
