### ISSUE TITLE
Detect profile from Metamask/Github

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#214]
##### Description
Is it possible to detect my nickname/profile from Metamask?

##### Possible Implementation
https://gitcoin.co/profile would redirect to https://gitcoin.co/profile/abitrolly and main interface would show my name somewhere in the headers or even in Web3 test box,

##### Environment

* **Browser**:
* **Version**:
* **Subsystem**:

**Comment by owocki** [comment]
its a good idea... id be into this

**Comment by owocki** [comment]
this could also detect your profile from your github login (which @mbeacom has helpefully coded up!) instead of just from metamask

**Comment by abitrolly** [comment]
What information does Metamask store/provide for current website? Is it only ETH address?
