### ISSUE TITLE
Approved Worker Not Showing Approved 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2143]
Approved Worker Not Showing Approved and Submit button is not showing up.

See the thread here:\
https://github.com/MARKETProtocol/website/issues/244#issuecomment-417964571

**Comment by PixelantDesign** [comment]
^ Very true, doesn't show that Arun applied for work on the activity stream, but shows on the Github thread.

**Comment by kuhnchris** [comment]
Is this error still occouring? Else if we cannot reproduce it and it doesn't show up it may have been a one-time issue.
