### ISSUE TITLE
As a user, I want to be able to filter Bounties in a 'dangling' state, so I can salvage them (or avoid them)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2155]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to be able to filter Bounties in a 'dangling' state, so I can salvage them (or avoid them)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Dangling state == no action in the last X days
Because bounties that are in a dangling state (which happens semi often, lets be honest), damage morale of users on the platform.. and reduce our success rate

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

In DB:
start tracking ‘days_since_last_action’ on the bounty model (last action == start work, stop work, github comment, pull request, etc)…. 

On Issue Explorer:
allow folks to filter on that in the issue explorer (under misc, add a 'stale bounties' option where no action in 5 days), 

On bounty detail page
Add an 'escalate to Gitcoin' button, visible only to the contributor/funder, that allows user to type comments in a modal about why they need to escalate the bounty to us.  When it's sent, an email will be sent to founders@gitcoin.co with the user's contact info, a link to the bounty, and their comments,.

Via crontab:
escalate the most stale ones (> 5 days) to Gitcoin Core via slack, every weekday

**Comment by thelostone-mc** [comment]
This might get confusing ! cause we need to ensure

- request bounties don't come into picture
- track activity + github comment + PR activity update to make it meaningful (else issues being actively worked falls under the list)
- `stale bounties` -> not too big fan of adding another filter -> But I'd be open to us giving it a shot and monitoring it's usage over hotjar

**Comment by PixelantDesign** [comment]
I also wonder if we should redefine Work Started and add an Expressed Interest or Apply to Work State. We have this in some cases. 

Users that have Yet to Begin Work, technically haven't started. Right now they're just bucketed in the Start Work state with people who have actually started work.

@thelostone-mc @owocki ?

**Comment by kuhnchris** [comment]
Did we add this filter to the explorer?
