### ISSUE TITLE
as a developer, i want the system to auto-generate new translation strings every night, so that any new translations are included in the dapp.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2159]
From the [docs](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/)
> Once the translators have filled in the message file, it must be compiled. This process relies on the GNU gettext toolset.

(hat tip @thelostone-mc for the above info)

ANytime we add new trans tags to the db, we need to re-run auto translate.  Per haps we can automate this and have the server that runs it auto-commit back to create a PR or commit to the master branch?

**Comment by SaptakS** [comment]
@owocki would it be wise to put it into CI? So what I am thinking is mostly a new trans tag or a modification comes via a Pull Request. So everytime in CI, when we merge it to master, if we run `make autotranslate` which makes a commit to the master (or maybe a different branch if we want reviewing), then this problem should be solved. @mbeacom what do you think?

**Comment by owocki** [comment]
that makes sense to me

**Comment by kuhnchris** [comment]
Did we add this to CI?
