### ISSUE TITLE
No 'Stop Work' / 'Stop Work & Ding Rep' 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2165]
## User Story
As an 'Admin', I'd like the ability to 'Stop Work' / 'Stop Work & Ding Rep' from the front-end. This was a feature available to me to easily remove stale workers from bounties. 

This is no longer available. I'd like this feature back so I can ding rep appropriately when hunters disappear. 

## Timeline
Triage - P2 (Minor Bug): A feature of Gitcoin fails to follow expected behavior. The issue is not high magnitude. 

![screen shot 2018-09-05 at 3 12 17 pm](https://user-images.githubusercontent.com/23297747/45118510-4cc64e80-b11e-11e8-9a88-47444cc34705.png)

**Comment by owocki** [comment]
@thelostone-mc  i wonder if this is related to https://github.com/gitcoinco/web/pull/2131 ?
