### ISSUE TITLE
[DESIGN] Building Gitcoin Requests Into App

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2166]
### User Story
As a funder, I want to know about [Gitcoin Requests](https://gitcoin.co/requests/) so that I can get support for my Web 3 repository.

As a developer, I want to know about Gitcoin Requests so that I can suggest 'good-first-issues' I'd work on for the right price. 

### Why Is this Needed
*Summary*: To increase the usage of Gitcoin Requests; thereby increasing the amount of open work on the Gitcoin platform

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Gitcoin Requests is a standalone feature at https://gitcoin.co/requests/

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Gitcoin Requests is represented in the app at appropriate places in the user flow. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: The appropriate solution will provide .sketch or .ai files showing updated marketing pages, including introduction of Gitcoin Requests in the right places. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

.ai and .sketch designs for the following two screens. 

- [ ] - A Gitcoin Requests modal which pops up after a 8 second delay on the Issue Explorer (https://gitcoin.co/explorer). The text can say: "Not finding an issue you can do? Make a request for any 'good-first-issue' on an Open Source repository, and the Gitcoin team will review the submission within 48 hours."  

- [ ] - A Gitcoin Requests section on the landing page (https://gitcoin.co/). I recommend finding an unbotrusive / in-brand way to include it somewhere here, but am also open to other places it could be. 

![screen shot 2018-09-11 at 2 13 06 pm](https://user-images.githubusercontent.com/23297747/45382086-d9fd1d80-b5cc-11e8-938a-162daa0a0c01.png)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
- Please expect at least 3 rounds of review with the Gitcoin Core team (@thelostone-mc @PixelantDesign) 
- If you have any other ideas on where we might include Gitcoin Requests in the flow, open to suggestions.

**Comment by PixelantDesign** [comment]
I definitely see multiple tickets, but like that you're thinking about it as an experience.

Can we make this longer than a 5 second delay?
Let's specify how many times will this pop up?
Let's also specify the ability to **dismiss** or **don't show me again** (this could be annoying for users).
Recommend ux/design and then getting some feedback from users before building.

**Comment by thelostone-mc** [comment]
> Gitcoin Requests is introduced in the e-mail drip campaign
> A Gitcoin Requests section on the landing page

YAY 

> A Gitcoin Requests modal pops up after a 5-second delay on the Issue Explorer? 

I would okay with this if it's a one-time thing cause it is very distracting.
I would, however, encourage adding it to `How it works section`

@vs77bb at some point -> I would love to discuss / debate whether we need short `how-to-videos` (a good professional) which folks may find a lot easier to understand as opposed to reading

@PixelantDesign could we bounty out the design / could you list out a design? I can code it up after that

**Comment by PixelantDesign** [comment]
I think we should wait for the real version before we do a video...what do u guys think?

**Comment by vs77bb** [comment]
> I would, however, encourage adding it to How it works section

Agree with this as well!

**Comment by thelostone-mc** [comment]
Coolio! @vs77bb / @PixelantDesign lemme know once we've got designs and we'll move ahead with execution :)

**Comment by vs77bb** [comment]
@PixelantDesign Is this another one to add to Will's design backlog, potentially?

**Comment by kuhnchris** [comment]
Is this still a backlog item?
