### ISSUE TITLE
[DATA] Profile gives wrong impression (false data)

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#2168]
## Problem

My profile on gitcoin.co contains mostly false data:

https://gitcoin.co/profile/lazaridiscom

Most importantly, the following 3 bounties were completed, but they are listed as "started" or "submitted" or even both:

Fix bad EthPM test
https://gitcoin.co/issue/trufflesuite/truffle-core/87/0

MetaMask web3 instance doesn't return events/logs
https://gitcoin.co/issue/MetaMask/metamask-extension/2393/31

Upgrade withdrawal functions
https://gitcoin.co/issue/GridPlus/cryptobridge-contracts/11/57

Please clean this up, thus my profile stops displaying that I start bounties without completing them.

**Comment by owocki** [comment]
@lazaridiscom  great to see you!   you're welcome to submit a PR with fixes, submit a bounty for someone else to look into it, or if you want we can disable your profile.

**Comment by lazaridiscom** [comment]
Are you aware that this translates to:

"Either you fix our fault yourself, pay someone to fix our fault or loose all your history, including all successfully completed bounties".

Is this your standard-procedure when gitcoin's database is corrupted?

**Comment by lazaridiscom** [comment]
"Free Gitcoin T-Shirt! Answer a few questions and help us improve our site.

We are looking for visitors to participate in a usability test. To qualify simply fill in the short form below. If you are selected, you will be contacted by a member of our team."

The usability was terrible, and it is still terrible.

Gitcoin is far to "centric" (as in non-trustless), and

**Comment by owocki** [comment]
> "Either you fix our fault yourself, pay someone to fix our fault or loose all your history, including all successfully completed bounties".

Excuse me, but have you done any sort of analysis to ascertain who is 'at fault' for the bug?  There are 100s of contributors to this project.

> I mean seriously: how should one focus on the tasks at hand?

Laz, you are welcome to begin contributing value to your project at any time.  

Please re-read the [contributor guide](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#code-of-conduct), and please stop voicing whatever negative thought pops into your head.    Complaints are cheap, actual value is scarce.
