### ISSUE TITLE
Gas history 3d video missing (Storage method change request)

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2170]
**Describe the bug**
The gas history video at:  https://gitcoin.co/gas?is_3d=1 doesn't exist.

**To Reproduce**
Visit the the above page - Video isn't available.

**Expected behavior**
Video is requested from c.gitcoin.co (media CF endpoint).  This includes the video being uploaded to S3 and probably stored on a historical snapshot model.

**Screenshots**

<img width="685" alt="screenshot 2018-09-06 09 53 51" src="https://user-images.githubusercontent.com/7315957/45161887-c6ac1580-b1ba-11e8-8ffb-018567fe9a40.png">

**Additional context**

We should be storing this video somewhere on S3 (probably media) and serving it from there, opposed to local FS.

**Comment by owocki** [comment]
This seems related to the transfer to cloudfront, as the video exists on the filesystem at `static/tmp/gas_price_viz.mp4` 

I just put an entry into the nginx config that allows https://gitcoin.co/static/tmp/gas_price_viz.mp4 to be served directly from the filesystem in the time being

**Comment by mbeacom** [comment]
@owocki That makes sense.  We'll want to maintain this issue to track migrating this local FS to S3, though since this will become problematic when we're serving the app across `n` containers all requiring generation of the same file and potentially differing results.
