### ISSUE TITLE
Inventory - UX improvements

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#2175]
We have good tips & guides on our retail pages, this [1] has also good paragraphs.
I want to propose that we incorporate these hints/tips directly into the UI where appropriate.
That also means what we should replace the tooltips on buttons with something like [2],
for better recognition/usability (just an example).

I don't want to clutter the interface but subtle hints at the right places helps first-timers quite a lot.

@SaptakS @PixelantDesign 

[1] https://opensource.guide/
[2] ![screenshot](https://user-images.githubusercontent.com/40266861/45192918-a11b1c80-b24b-11e8-98dd-196e2fb8659e.png)

**Comment by pinkiebell** [comment]
@PixelantDesign Ack, the best thing we can do first is an inventory list of all goodies :)

**Comment by pinkiebell** [comment]
### Hints

Keep an eye out for an
email with a Work Started
or Request to Work notice
Approve the request via
the email notification.

Once work has been completed
the contributor will
submit a PR for review.

Depending on the project
type, payment can be
made to one contributor
or to multiple contributors at one time.

Upon completion use the
accept submission button
on the issue details page to release funds!

### Things To Note

Funders Choose Workers
The funder reserves the right to accept or deny a worker in order to find the best fit for the project.

Iteration is Key
Expect a few rounds of revisions to complete the project.

Be on Time
Work that has not been completed and is past the expiration date is considered expired.

Cancel Anytime
A project can be cancelled by a bounty funder. The funds will then be reclaimed by the bounty owner.

Signal Your Intent
As a courtesy to other contributors and to ensure payment, use the start work button to notify all parties your intention to work.

Funders Choose Workers
The funder reserves the right to accept or deny a worker in order to find the best fit for the project.


### Project Types

Gitcoin supports 3 flexible ways to set up a project to ensure the best results

**Traditional Project**
Good For
Sourcing ideas, creative, searching for the best ways to solve a problem, bug hunt.

What to Know
A traditional project can be set up for contributors to be able to start work immediately without approval or can be set up as approval required.


**Cooperative Project**
Good For
Large projects (broken up into parts), augmenting team skillsets

What to Know
When funding a cooperative bounty, provide guidance on how the project can be broken up to allow additional contributors smooth onboarding.

The amount paid for a cooperative bounty is at the discretion of the funder. Please make sure you over-communicate your budget/intent to the bounty hunter -- It helps avoid misunderstandings in the future!


**Contest Project**
Good For
Sourcing ideas, creative, searching for the best ways to solve a problem, bug hunt.

What to Know
Be clear on the type of contest and how many winners will be provided a bounty.

The funder resrves the right to pay only one or more than one contributor for the contest at their discretion. This depends on the type of contest listed and the number of winners alloted.


**Project Permissions**
Gitcoin supports 2 types of permissions to allow flexibility for each project.

Permissions - Approval Required
A Permissions based project ensures that the contributor has necessary skillsets to complete the task. Contributors will request to work on a project by clicking start work to express interest. A short summary of a work approach will also be provided in the start work form.

What to Know
Gitcoin will send you an email notification when a worker has expressed interest.
The repo owner/funder has the right to approve or deny any request to work.
If there is no response from the funder/repo owner, Gitcoin will auto approve the contributor after 72 hours.


Permissionless - No Approval Required  permissionless
A permissionless project allows a contributor to begin work without permission or approval from the project owner. It is suggested that an approach and questions be raised prior the start of the project to ensure mutual understanding or the way forward.

What to Know
Although approval is not required to begin working on the project, ensure that the goals in the issue description are clear.


### Payment

Gitcoin supports 2 ways to make payments to support the flexibility of each project.

**Basic Payout (single-party)**

This feature allows a funder to easily pay one person for the work completed. This is typically used for the traditional project type.

**Advanced Payout (multi-party)**
Multi-party payout allows multiple people to be paid at one time. This can be used for cooperative or contest project types.


### Disputes

Sometimes disagreements occur, here are a some tips on how to handle them.

What to Know
Disputes very rarely occur given that we are mission driven in open source.

It’s natural for some scope to be misunderstood or not fully laid out -- so we shouldn't feel bad about that. software development is naturally iterative.

Plan for a extra tipping budget for after the fact, if there is extra scope.

Sometimes it just doesnt work out and we need to go our seperate ways. Leave a tip for the bounty hunter for any value that was provided towards the end scope and re-bounty the task.

As always feel free to contact the Gitcoin core team on slack with any questions.



### Steps

**Express Interest**
Interested on an issue?
Click Start Work to express
interest through a short form.

**Begin Work**
If the project requires approval,
keep an eye out for a notification
for a Request to Work confirmation
via email prior to begin working.
Otherwise, work away!

**Can’t Continue Your Work?**
Click Stop Work, and
someone else will pick it up.

**Submit Work**
Completed your work?
Click Submit Work to
send your PR to a repo maintainer
for review.
Otherwise, work away!

**Work Reviewed**
Submitted work is reviewed
and approved by a repo owner.

**Get Paid**
Once your work is approved
by the repo maintainer,
you’ll get paid!

**Comment by PixelantDesign** [comment]
@pinkiebell This is great!

**Comment by kuhnchris** [comment]
@PixelantDesign I think this was added to the page, right? Closing this, please reopen if I'm wrong!
