### ISSUE TITLE
UI issues with the nav on resizing

### ISSUE THREAD

**Issue by anshumanv** [gitcoinco/web#2177]
**Describe the bug**
* user avatar squeezes, different sized buttons on nav on resizing, text inside nav not centred.

**To Reproduce**
Checkout the navbar after resizing the page.

**Expected behavior**
* User image/avatar should stay as is, buttons should be of equal size? text inside them should be centred.

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/45200838-4fe14c00-b290-11e8-80c5-7850d2ff1fdb.png)
![image](https://user-images.githubusercontent.com/21009455/45200858-612a5880-b290-11e8-8271-1b98bf0f492b.png)

**Desktop (please complete the following information):**

- OS: Linux Mint 18
- Browser Firefox 
- Browser Version 62.0b

**Comment by thelostone-mc** [comment]
@PixelantDesign we should evaluate how to handle it! would it make sense using icons on smaller screens / do we ignore a few tabs and so on

cc @SaptakS

**Comment by vs77bb** [comment]
@anshumanv just sent you 10 DAI for reporting the issue! Thanks for taking the time 😄
