### ISSUE TITLE
Build - Sometimes, Issues in the 'Open' category are actually Expired

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2185]
**Describe the bug**
Sometimes, Issues in the 'Open' category are actually Expired

**To Reproduce**
Go to the issue explorer and find issues that are Open, but they are actually expired.

![screen shot 2018-09-10 at 11 53 37 am](https://user-images.githubusercontent.com/238235/45312610-87533100-b4fa-11e8-8be4-cf8c1241e965.png)

**Comment by owocki** [comment]
fwiw, you can still work on gitcoin issues after they expire.. so technically they *are* still open

**Comment by thelostone-mc** [comment]
@PixelantDesign They'd have to get in touch with the funder (so it would make sense to keep it open)
@owocki thanks for addressing that  ^_^

A few community folks have done that -> then the funder extends expiration and they start work on it

**Comment by thelostone-mc** [comment]
Though it is confusing to the end user but we do have a clear message on the bounty page

<img width="560" alt="screen shot 2018-09-13 at 2 11 47 pm" src="https://user-images.githubusercontent.com/5358146/45477340-02b51c80-b75f-11e8-8aeb-530af569c87b.png">

For clarity we could hide the `Expired` label on the explorer but a lot of folks find that useful
