### ISSUE TITLE
Wrong Message When Bounty Cancelled

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2187]
**Describe the bug**
Gitcoin Bot and Gitcoin's app did not capture cancelled status correctly when a funder went though 'Cancelled' flow. 

**To Reproduce**
[See here](https://gitcoin.co/issue/ethberlin-hackathon/ETHBerlin-Bounties/32/1121).

**Expected behavior**
Cancelled issue should show as cancelled (not 'Work Done') and the Github comment should state cancelled, not 'issued and approved'. 

**Screenshots**
![screen shot 2018-09-10 at 1 16 37 pm](https://user-images.githubusercontent.com/23297747/45316132-c766e380-b4fb-11e8-9a13-f4a9255eb598.png)

![screen shot 2018-09-10 at 1 17 05 pm](https://user-images.githubusercontent.com/23297747/45316143-d5b4ff80-b4fb-11e8-9847-c4caa66e6d24.png)

**Additional context**
Admin overrode status here to 'Work Started' prior to cancellation. Not sure if that had anything to do with the eventual bug, though?

**Comment by owocki** [comment]
i think this is likely because there are tips attached to the issue, so the bot thinks it was paid out via advanced payout

**Comment by kuhnchris** [comment]
still an issue?
