### ISSUE TITLE
bug - my profile shows my profile pic but it should show my avatar

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2189]
my profile shows my github picture but it should show my avatar

gitcoin.co/profile/owocki

http://bits.owocki.com/9dfbcae73986/Screen%20Shot%202018-09-10%20at%206.31.53%20PM.png

**Comment by mbeacom** [comment]
This was due to duplicate `Profile` objects 🤔 and has been resolved...  following up with an issue to investigate the duplicate `Profile` object occurrence.
