### ISSUE TITLE
Bug - Funded Issue Showing $0 USD

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2191]
**Describe the bug**
Funded Issue showing $0 but .17 ETH

**To Reproduce**
Fund an issue

**Expected behavior**
show correct usd amount

**Screenshots**
<img width="1062" alt="screen shot 2018-09-10 at 10 29 50 pm" src="https://user-images.githubusercontent.com/238235/45334550-37e82180-b549-11e8-9ca0-cab99de0dbd2.png">

https://gitcoin.co/issue/gitcoinco/web/2190/1184

Also not showing USD on Gitcoin Bot

<img width="898" alt="screen shot 2018-09-10 at 10 41 01 pm" src="https://user-images.githubusercontent.com/238235/45334884-c9a45e80-b54a-11e8-930f-87c3df003128.png">

**Comment by arun1595** [comment]
@PixelantDesign It shows up the right USD amount now. Weird

![image](https://user-images.githubusercontent.com/7039523/45335741-61537e00-b546-11e8-918d-9e415bf79b06.png)

**Comment by PixelantDesign** [comment]
yes very!
