### ISSUE TITLE
as a user, i want to request a funding limit increase via a webform, so i don't have to go through the information complexity of contacting support (and so anyone on gitcoin core team can to limit increases)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2199]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to request a funding limit increase via a webform, so i don't have to go through the information complexity of contacting support (and so anyone on gitcoin core team can to limit increases)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so anyone on gitcoin team can increase limits
so people know where to request limit increases

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
user is advised to contact support if they try to do a tx over their limit
<img width="961" alt="screen shot 2018-09-11 at 1 17 29 pm" src="https://user-images.githubusercontent.com/513929/45382371-38260280-b5c5-11e8-9b58-ce7534199e21.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

- when presented with an error message, user is linked to https://gitcoin.co/requestincrease
- https://gitcoin.co/requestincrease is a form that asks them how much of an increase they expect (denominated in per-tx limits and per-week limits).  they should also input a comment about why they want a limit increase. 
- user must be logged in to submit form
- when users submits form, it displays a success message and promises a 1 business day turnaround
- when user submits form, it emails founders@gitcoin.co with a link to the user's profile and all of the inputs they submitted.
- admin can either reject / approve the funding increase from there

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

you can copy the https://gitcoin.co/submittoken form to get scaffolding for this!

**Comment by PixelantDesign** [comment]
Looks good to me!

**Comment by pinkiebell** [comment]
Interested! I would use Django Forms, with the same flow like Gitcoin Requests V0 👍

**Comment by PixelantDesign** [comment]
This would be a good link to have in Tools

**Comment by owocki** [comment]
@pinkiebell wanna do this and ill tip you out?  would save us from having to bounty it to just have you work on it ! :)  let me know what amount is fair

**Comment by pinkiebell** [comment]
@owocki Fine, added to my list. I expect a turnaround in two days if nothing unexpected jumps in between. 👍

**Comment by pinkiebell** [comment]
@owocki 
Should the code go into `app/retail` or a new home like `app/request_increase` ?

**Comment by owocki** [comment]
defer to @thelostone-mc @SaptakS or @mbeacom on this

**Comment by mbeacom** [comment]
@pinkiebell You can toss it into `app/retail/`
