### ISSUE TITLE
Create Design - "Subscription Transaction" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2205]
### User Story

As a Grant Supporter, I want to know when a  subscription transaction has been taken out of my account so that I know when I have paid value to a project. 

### Why Is this Needed

The "Subscription Transaction" Email is needed so that grant supporters know when they have had value transferred from their account to the grant project. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should have copy similar to:

 " You've made another contribution to 'Project X'!

Your payment of XX.XX can be seen here: 'link to transaction on etherscan' "

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by captnseagraves** [comment]
@PixelantDesign @Justpixel  Has there been any movement on this? Is one of you able/willing to complete this work?

**Comment by willsputra** [comment]
@captnseagraves @PixelantDesign @justpixel

I'll give this a shot. 🙂

![grants subscription transaction](https://user-images.githubusercontent.com/19514207/47032796-d0f00500-d1a5-11e8-9027-12e83f0b2380.jpg)

**Comment by kuhnchris** [comment]
@willsputra and, any success?
