### ISSUE TITLE
Create Design - "Transaction Summary" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2206]
### User Story

As a Grant Creator, I want a summary of all transactions on days that I receive funding so that I know when I have funds to allocate toward my project. 

### Why Is this Needed

The "Transaction Summary" Email is needed so that grant creators know when they receive funding and how much funding they have received. If they have not received funding on a given day, they will not receive this email. If they receive multiple contributions on a given day they will only receive this one summary email. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should display a summary of all funds received to this point
[ ] Email should display all transactions that happened within the previous 24 hours and the values of each transaction
   - The design should look similar to the deprecated withdraw page design here: https://github.com/gitcoinco/web/issues/1907
[ ] Email should have a button link to the grant admin page
[ ] Email should have copy similar to:

 " 'Project X' has received more funding!"

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email design work can be found here: https://github.com/gitcoinco/creative/tree/master/Marketing/Email

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
Assigning @justpixel

**Comment by captnseagraves** [comment]
@PixelantDesign @justpixel Has there been any movement on this? Is one of you able/willing to complete this work?

**Comment by PixelantDesign** [comment]
Checking with @justpixel, will see if @willsputra has bandwidth as well.

**Comment by willsputra** [comment]
On it. :)

@PixelantDesign @owocki @captnseagraves here's a draft! lemme know if you have any feedback.

![grant transaction email](https://user-images.githubusercontent.com/19514207/46816228-192ab400-cdaf-11e8-96e1-d4b495673470.jpg)

**Comment by owocki** [comment]
i think this looks really good.. 👍 from me!  cc @PixelantDesign @captnseagraves in case any change requests

**Comment by PixelantDesign** [comment]
Looks good to me, I've reviewed! Thanks for the quick turn around @willsputra !

**Comment by owocki** [comment]
@captnseagraves do we need a "Code transaction summary email" task?  Can we link this design in there?

**Comment by captnseagraves** [comment]
@owocki What do you mean by a code transaction summary? As in, showing work thats been paid for via Gitcoin, or simply code that has been added to the project?

**Comment by captnseagraves** [comment]
Also, LGTM!

**Comment by owocki** [comment]
i mean code up the design above.  is there a coding ticket for it?

**Comment by PixelantDesign** [comment]
@willsputra could you attach the file here? Thx!

**Comment by captnseagraves** [comment]
I will create an implementation ticket.

**Comment by willsputra** [comment]
Sketch file here:
https://drive.google.com/open?id=1qVFZli7ctqsD9qXl8Uyh57jF_4XRgJzw

**Comment by kuhnchris** [comment]
Anish finished this, no?
