### ISSUE TITLE
Bounty informations

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2214]
### Discussion

Today is hard to understand the state of the issue, and that is a big effort and also we need to understand the issue description so all that process is needed to decide to start working or not in a bounty is big. 

I think some changes can help us to make a better process hunting issues:

### States
I see as a solution show the states in the explorer
1- Open : nobody has applied yet
2- **Worker waiting**: one or many workers has applied and are waiting aprovation to start working
3- Work started: one or many are approved to work and are working on this
4- work submitted: Anyone has submitted any work, waiting aprovation.
5- Done: work accepted and issue solved.
5- Cancelled: bounty was cancelled 

I think **Worker waiting** state is very important when looking what to apply and understanding "approval required" 

### Tags
Today tags are mixed with keywords, maybe having special tags for tech skills can be most easy to understand if I have that skills to work on that task. With that 2 kind of tags are created **keywords** and **skills**
keywords: companyname, blockchain, eth, ideas, community...
skills: css, js, python, ui, writer...

Reading the skills I have a real idea of what I need to accomplish the task and help answer the question "is that for me?"  So having skills tags in the explorer also help me deciding which issue on the list I  click to understand the task but knowing that I already have the skills.

[comment]: # (What conversation would you like to facilitate?)

**Comment by kuhnchris** [comment]
is this old, or did we change something here? @octavioamu

**Comment by octavioamu** [comment]
Ohh yes very old and think all was done, in diff ways but not an issue anymore
