### ISSUE TITLE
for grants deliver information to tom linderman about what consensys diligence needs for audit

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2216]
they need

* specs
* full test coverage
* a date when contracts can be locked and hashed
* expected deliverable date of audit report

From tom: 
we are basically looking for the specs and full test case coverage, a date when the contracts can be locked and hashed, and expected deliverable date of the audit report.  We need to do an assessment of the size and complexity in addition tot he readiness and then we can finalize the proposal and date.

diligence form: https://files.slack.com/files-pri/TAWFUGNQ2-FCTMFQHAS/download/diligence_client_engagement_form_july_2018.docx

**Comment by owocki** [comment]
@austintgriffith could use ur help on this too

**Comment by austintgriffith** [comment]
I believe this is the contract that will be used for the dev grants:
https://github.com/austintgriffith/tokensubscription.com/blob/master/Subscription/Subscription.sol

There are a few demos around how this works here:
https://github.com/austintgriffith/token-subscription
and here:
https://github.com/austintgriffith/tokensubscription.com

It is on the mainnet supporting: https://tokensubscription.com

**Comment by owocki** [comment]
nice :)  now we just need test coverage and to spend a few cycles writing up actual formal specs !

**Comment by kuhnchris** [comment]
So... did we do something with this?
