### ISSUE TITLE
Notify Funder That a Task Has Issues

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2219]
##### User Story

As a contributor, I'd like to be able to notify the funder that an issue doesn't meet my bounty criteria for various reasons. 

##### Definition of Done

**Step 1**
- [x] A user can click the **report** button on the issue details page and let the funder know that it's not up to their standard for various reasons.

<img width="1036" alt="screen shot 2018-09-14 at 7 16 11 am" src="https://user-images.githubusercontent.com/238235/45547533-15773200-b7ef-11e8-8d0c-c666bf3b5990.png">

**Step 2**
- [x] Reuse the Start Work Modal and Display the following options:
    
Modal Title: Notify the Funder of the Following Issues

Checkboxes:
- [x] This issue is underfunded
- [x] This issue is underscoped.
- [x] This bounty was taken from me.
- [x] This bounty seems abandoned.
- [x] This issue is considered spam or unethical

Display **Submit** Button

**Step 3**
- [x] Once user clicks submit, display a confirmation message:
Thank You for notifying Gitcoin and the funder of this issue.

Please reference start work dialog for the confirmation message treatment.

**Comment by pinkiebell** [comment]
I'm not sure. If the funding is not right or the definitions not clear,
I either leave it alone or I give feedback on the Github issue.
For unethical- or spam things the same, I just leave it alone.
For myself I think a better solution might be improving the explorer/ searching experience.
Or a more personal 'bounty stream' maybe? So that I can follow orgs/funders/repos I like and maybe a subscription-'let me know if a new bounty is funded for this repo' thing.

aka, Let us introduce a passive ranking system which serves as a trigger to mimic good 'bounty design'(lol) - sounds that about right?

**Comment by thelostone-mc** [comment]
> I give feedback on the Github issue.

A few folks would hesitate to do this in terms of increasing pricing  but this seems to be the right thing. I agree with @pinkiebell

**Comment by owocki** [comment]
reasons i think an issue could be escalated

1) mark it as underfunded
2) mark it was underscoped
3) mark it as spam, unethical, etc
4) the bounty was taken from me
5) the bounty seems abanandoned

**Comment by thelostone-mc** [comment]
@PixelantDesign 


> Once user clicks submit, display a confirmation message:
Thank You for notifying Gitcoin of this issue. Please expect 24-48 hrs for a Gitcoin core team member to respond.

- Is the email sent to gitcoin core also ?

> Funder should be sent a daily email
 
- It should be a one time mail as opposed to everyday 

> If more than one user reports the same thing....we should note this on the email.

- Would it be right to show the person's name who's notifying the funder ?
- The template attached does not accommodate scenarios where multiple folks select a common reason. Could you clarify on how to tackle this?

**Comment by mbeacom** [comment]
@PixelantDesign 
I think generating an email for every interaction regarding feedback might generate too much noise and ultimately lead funders to automatically disregard these emails.

If anything, maybe we implement this with a backend model to track bounty improvement requests and surface them in the funder dashboard and/or platform notifications (`/inbox`).  In the meantime, we could add the backend model, create the object on improvement submission and send out a weekly email regarding these requests for improvement (or better yet, include it in an existing weekly email to reduce noise).

Also, it seems there is a bit of a UX issue from my point of view.  Should we enable some kind of bidirectional communication in the form of bounty discussion threads? What if a user funder wants to respond to the user without updating the bounty?

**Comment by PixelantDesign** [comment]
Agree on a lot of what you're saying above.

The original idea was to generate one email daily /summary of feedback on each ticket.

> If anything, maybe we implement this with a backend model to track bounty improvement requests and surface them in the funder dashboard and/or platform notifications (/inbox). In the meantime, we could add the backend model, create the object on improvement submission and send out a weekly email regarding these requests for improvement (or better yet, include it in an existing weekly email to reduce noise).

Can we do what you're suggesting in the next two weeks? What kind of a lift would this be?

Also agree on bidirectional communication. @thelostone-mc suggested that for V2.

I'm open to suggestions on the best experience for V1. @mbeacom @thelostone-mc.

**Comment by pinkiebell** [comment]
What if we think from a tag/label point of view?
In a way that I can label a bounty underfunded and we dispatch notification emails if a new label was added to the bounty? Actually like Github Issues

**Comment by PixelantDesign** [comment]
@pinkiebell How would a contributor add a label to it?

**Comment by thelostone-mc** [comment]
@pinkiebell which means we would have the labels displayed on the issue only for the funder to be seen! 
which means 
- view labels only for funder
- provision for funder to dismiss labels
- tracking the audit history 

lol talk about feature creep :P 

@PixelantDesign @mbeacom should I put this on hold until we are clear ? 
the reporting bit is built out
next would be the mail which I have to code up (which would happen irrespective of which path we choose ). I don't wanna be in a situtaion where I have to redo it :P

**Comment by pinkiebell** [comment]
@PixelantDesign 
> How would a contributor add a label to it?

Via the user interface, maybe a little +label button with choices.

@thelostone-mc 
> lol talk about feature creep :P

Ya, that might be a little bit too much for V0 😆

**Comment by PixelantDesign** [comment]
@thelostone-mc could you outline what is left to do on this ticket or open a new ticket so that we can bounty the remainder?

**Comment by thelostone-mc** [comment]
What's left to do is simply integrating when the email should be triggered ^_^

**Comment by PixelantDesign** [comment]
@thelostone-mc could you write up the tech specs so  I can bounty?

**Comment by thelostone-mc** [comment]
@PixelantDesign As discussed offline ! What's left is wiring up when the email is triggered.
That bit can be bountied out but my PR would have be merged in for that !

**Comment by owocki** [comment]
@PixelantDesign @thelostone-mc we could perhaps bounty it as an add-on to your branch, instead of waiting until the branch is merged to bounty it.. would that work?
