### ISSUE TITLE
Bounty is paid out, but still shown as submitted - Expired Issue

### ISSUE THREAD

**Issue by troggy** [gitcoinco/web#2227]
**Describe the bug**
I've submitted the work and got paid for the bounty, but on the web bounty is still shown as "submitted". Link: https://gitcoin.co/issue/parsec-labs/solevm-truffle/2/793
Tx id: https://etherscan.io/tx/0x137a77466055686660b984ac3f839be62ba8aadfcbee345f62ee4f2a8da38571

**To Reproduce**
🤷‍♂️

**Expected behavior**
I expect the bounty to be marked as "Done" as usual

**Comment by PixelantDesign** [comment]
Thanks for reporting @troggy!

**Comment by kuhnchris** [comment]
Issue/Bounty is done now - I assume it was status-overwrtten?
