### ISSUE TITLE
Crowdfund contributions not being included in some bounty totals on issue explorer

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2228]
**P3 - Low**
Gitcoin’s platform is following expected behavior, but the expected behavior is resulting in sub-par user experience.
Timeline to fix: 1-7 days

### Describe the bug
I added contributions to the following bounty such that the total funding is 1 ETH but the issue explorer still only shows the initial amount of ~0.02 ETH. The amount on the bounty itself is correct.

Issue:
https://gitcoin.co/issue/genuinetools/audit/7/1213

Issue Explorer Screencap:

https://gyazo.com/75a18c936185919443633bc350791c30

### To Reproduce
🤷‍♂️

### Expected behavior
Tips should be included in the amount listed on the issue explorer

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2173

i think this should fix this

**Comment by ceresstation** [comment]
@owocki Awesome, thanks.

**Comment by owocki** [comment]
as long as by 'tips' you meant 'crowdfund contributions' ...

**Comment by thelostone-mc** [comment]
can we close this out ?

**Comment by owocki** [comment]
[confirmed fixed](http://bits.owocki.com/62264035ff06/Screen%20Shot%202018-10-11%20at%2010.04.44%20AM.png)

wow, and this looks good too!
