### ISSUE TITLE
Build - Advanced Pay  - Add User Auto Complete

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2240]
**Core Team
Estimate 3**

Add Auto Complete that @octavioamu built to Advanced Pay

If user is already identified, we will show the user icon and eth address.
If user is unverified, we will show an icon with a question mark and the user's name with unverified.

The functionality should stay the same in that the info of the contributor that worked on the task is automatically displayed. 

See mockup

<img width="550" alt="screen shot 2018-09-28 at 1 14 12 pm" src="https://user-images.githubusercontent.com/238235/46223135-7b4fd780-c320-11e8-86db-0efd4df1c600.png">

**Comment by PixelantDesign** [comment]
This looks good to me @thelostone-mc lets merge!

**Comment by thelostone-mc** [comment]
Closing this out as it has been merged at https://github.com/gitcoinco/web/pull/2296
