### ISSUE TITLE
Unable to submit work without ETH in Metamask

### ISSUE THREAD

**Issue by ChrisCates** [gitcoinco/web#2243]
**Describe the bug**
Unable to submit work with an empty Metamask wallet.

**To Reproduce**
Use an empty metamask wallet.

**Expected behavior**
For both Brave and Chrome Browser. You will not be able to submit work unless there is ETH in your wallet. It will take you to the faucet.

**Screenshots**
![screen shot 2018-09-18 at 1 27 14 pm](https://user-images.githubusercontent.com/1561091/45705329-4fc23580-bb47-11e8-92c2-a816010282ba.png)

**Desktop (please complete the following information):**

- OS: High Sierra

Browsers 
- Google Chrome 69.0.3497.92
- Brave v0.23.107

**Comment by ChrisCates** [comment]
@owocki, is it possible I can write a pull request to refactor this?
Seems like a good opportunity to try it out!

**Comment by mbeacom** [comment]
@ChrisCates I think we'd still want the submitter to sign the transaction.  We're tracking a few options to handle this at:  https://github.com/gitcoinco/web/issues/1823

**Comment by mbeacom** [comment]
@ChrisCates I think this is all subject to change.  We're discussing the possibility of using meta transactions similarly to @austintgriffith's bouncer-proxy.  See use case 3 here:  https://github.com/austintgriffith/bouncer-proxy/blob/61926aa560ab83151952d6bd8304c1c4c7ea78b7/BouncerProxy/BouncerProxy.sol#L39

Don't let that discourage you from trying to implement a stopgap as outlined, though!

**Comment by ChrisCates** [comment]
I'll probably see if I can setup a call with Austin later.
My confusion is how do we identify an etherless account as a valid account used with Gitcoin.

Anyway, let me look through the some of the Zeppelin source code and Austin's and see what the best plan of action for this.

**Comment by ChrisCates** [comment]
Closing this issue, as discussion on the Standard Bounties repository shows that another user can submit work on someone else's behalf.

https://github.com/Bounties-Network/StandardBounties/issues/49
