### ISSUE TITLE
DESIGN - What does the navigation look like when Kudos/Grants launches?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2244]
Open question: What does the navigation look like when Kudos/Grants launches?

**Comment by PixelantDesign** [comment]
Please see comment on https://github.com/mbeacom/gitcoin-erc721/issues/134

**Comment by captnseagraves** [comment]
@owocki @PixelantDesign I know theres been some movement on this for both Kudos and Grants. Could you either provide an update here or point me to the appropriate issue? I would like to write an implementation ticket for this as well.

**Comment by owocki** [comment]
@captnseagraves this is 90% implemented over at https://github.com/mbeacom/gitcoin-erc721/issues/134

**Comment by captnseagraves** [comment]
@owocki that link is broken. But that is great to hear. Two questions on it. 

1. Will the nav provide a clear path to grants from the main landing page of Gticoin?

2. Is there a ticket for implementing the nav across the different apps? Or should I write one up for grants?

**Comment by PixelantDesign** [comment]
1. Yes
2. I think @octavioamu is building it, and the different products will leverage. @captnseagraves will you circle up with @octavioamu to see the best path to integration?

cc @mbeacom on ideas here.

**Comment by octavioamu** [comment]
@captnseagraves  I had made the grants menu together, maybe some urls will need changes (I had used the currents url paths of grants) but all visually part is ready in Kudos. I think you don't have access to that issue.

**Comment by owocki** [comment]
the link isnt broken.. you just dont have perms on that repo.

**Comment by captnseagraves** [comment]
@PixelantDesign @octavioamu I just have one comment on the images that Octavio share in the proj-grants channel. Instead of "Active Grants" Could we have a Grants Explorer? or is that too confusing with the bounties explorer? I think it makes a nice consistency with Bounties.
