### ISSUE TITLE
bug - livepeer profile isnt showing the bounties it should

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2246]
:large_blue_circle:  this profile looks hella weird bc there are no bounties on it https://gitcoin.co/profile/livepeer

http://bits.owocki.com/c91916df9ae7/Screen%20Shot%202018-09-19%20at%208.42.37%20AM.png

whats esp weird is that they’ve had 15 bounties/tips according to leaderbaord https://gitcoin.co/leaderboard/quarterly_orgs

expected result: it should show the 15 bounties that have been done on livepeer. and if it doesnt.. it should show the body of hte profile and 'no bounties found' with some nice margin around it

Steps to resolution:

- Determine root cause of no bounties rendering on `livepeer` profile, since they have 15 bounties on the leaderboard, annotating whether or not this is a backend of frontend issue.
- Make necessary adjustments to frontend or backend based on the above findings.

Tracking `no bounties found` at: #2247

**Comment by mbeacom** [comment]
Checked the xhr occurring for this profile.  It appears https://gitcoin.co/api/v0.1/bounties/?network=mainnet&org=Livepeer is being hit and returning `[]` while https://gitcoin.co/api/v0.1/bounties/?network=mainnet&org=livepeer returns the appropriate results.

So, we should adjust the API handling for `org` param to be case insensitive.

**Comment by mbeacom** [comment]
<img width="1097" alt="screenshot 2018-09-19 12 53 59" src="https://user-images.githubusercontent.com/7315957/45768514-1ce17580-bc0b-11e8-9f58-9aa60849030f.png">

**Comment by owocki** [comment]
my hero!
