### ISSUE TITLE
Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2248]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/1032/

```
Error: Invalid number of arguments to Solidity function
  at InvalidNumberOfSolidityArgs (moz-extension://9813804d-ec6d-4e04-85a1-2ae0e897699b/inpage.js:1:165090)
  at [141]</</t<[31]</u.prototype.validateArgs (moz-extension://9813804d-ec6d-4e04-85a1-2ae0e897699b/inpage.js:1:174941)
  at [141]</</t<[31]</u.prototype.toPayload (moz-extension://9813804d-ec6d-4e04-85a1-2ae0e897699b/inpage.js:1:175103)
  at [141]</</t<[31]</u.prototype.getData (moz-extension://9813804d-ec6d-4e04-85a1-2ae0e897699b/inpage.js:1:176394)
  at None (/static/onepager/js/receive.433ad14f9888.js:149:22)
...
(41 additional frame(s) were not displayed)
```

We haven't been able to reproduce this on our end, but the error seems to be recurring.

@lastmjs is experiencing this issue with the following specs while attempting to claim a tip:

```
Browser: Chromium Version 68.0.3440.106 (Official Build) Arch Linux (64-bit)
OS: Arch Linux
Metamask: 4.9.3
```

Original rollbar issue:  #1453:

```
URL: https://gitcoin.co/funding/new
Message: Invalid number of arguments to Solidity function
Browser: Firefox
OS: OSX 10.13
```

Sentry issue encountered with:
```
Browser: Firefox 62.0
OS: Ubuntu Linux
```

**Comment by owocki** [comment]
@lastmjs sorry about the issue!  rest assured your funds are safe and secure! 

we unfortunately can't debug this as easily as other issues on the platform, because we don't have access to the private key associated with your github username, so i hope you'll tolerate some peer debugging with us!

whats strange about this is that tips receive doesnt even use solidity! 

can you go to the tip claim page and try again?  the first thing we want to try and rule out is an intermittent infura issue.

**Comment by lastmjs** [comment]
No problem. I just tried again, the same behavior occurs.

```javascript
raven.js:449 Uncaught Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (inpage.js:1)
    at u.validateArgs (inpage.js:1)
    at u.toPayload (inpage.js:1)
    at u.getData (inpage.js:1)
    at Object.callback (receive.433ad14f9888.js:149)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at inpage.js:1
    at He (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at t.value (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at d (raven.js:445)
```

**Comment by owocki** [comment]
@lastmjs two questions:

1. what version of metamask are you using?
2. the stacktrace you sent us looks like its within metamask (there is no inpage.js on gitcoin!) are you able to tell what line within receive.js this exception is generated?

**Comment by lastmjs** [comment]
1. The version is 4.9.3
2. From receive.js

```javascript
          // send ERC20
          var data = token_contract.transfer.getData(forwarding_address, amount_in_wei);

          rawTx = {
            nonce: web3.toHex(nonce),
            to: token_address,
            from: holding_address,
            value: '0x00',
            data: data
          };

          web3.eth.estimateGas(rawTx, function(err, gasLimit) {
            rawTx['gasPrice'] = gas_price_wei;
            rawTx['gas'] = gasLimit;
            rawTx['gasLimit'] = gasLimit;
            var will_fail_at_this_gas_price = (gas_price_wei * gasLimit) > balance;

            if (will_fail_at_this_gas_price) { // adjust if gas prices have increased since this tx was created
              rawTx['gasPrice'] = Math.floor(balance / gasLimit / 10 ** 9);
            }
            sign_and_send(rawTx, success_callback, document.priv_key);
          });
```

**Comment by lastmjs** [comment]
Is the `amount_in_wei` parameter sent to `getData` supposed to be an array? It looks like this: 

```javascript
c: [2250000]
e: 20
s: 1
```

**Comment by owocki** [comment]
@lastmjs looking into this now.. i think we might want to be passing `amount_in_wei.toString()` into the method

**Comment by owocki** [comment]
ahh yes that is it... @lastmjs i'm commititng a fix now!

**Comment by owocki** [comment]
@lastmjs i just put in a fix ( d63651338ef5934ca88ebd79f04210f15bb6e884 ) and am deploying it now.. can you pls hard-refresh and try again? 🙏 

curious that this didnt show up before.. we've done dozens of erc20 transfers through tips in the last weeks.. maybe a new metamask version broke this..

**Comment by lastmjs** [comment]
Making progress I suppose, but now I've got this:

```javascript
Uncaught Error: invalid type
    at Object.exports.toBuffer (tx.eeef7a6d1bb4.js:27462)
    at module.exports.setter [as gasPrice] (tx.eeef7a6d1bb4.js:27946)
    at Object.exports.defineProperties (tx.eeef7a6d1bb4.js:28006)
    at new module.exports (tx.eeef7a6d1bb4.js:27053)
    at sign_and_send (receive.0c6e460ad6ca.js:10)
    at Object.callback (receive.0c6e460ad6ca.js:167)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at inpage.js:1
    at He (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at t.value (inpage.js:1)
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at d (raven.js:445)
```

**Comment by lastmjs** [comment]
@owocki Any update on this? I'd love to get that DAI to ETH as soon as possible

**Comment by lastmjs** [comment]
Oh dear, I tried to hack it in my browser, have I lost my tip?

![screenshot from 2018-09-21 21-07-12](https://user-images.githubusercontent.com/7000719/45912702-0beb5c80-bde3-11e8-819f-0849d63bd0b4.png)

The transaction doesn't seem to show up on Etherscan

**Comment by owocki** [comment]
> Making progress I suppose, but now I've got this:

I wish I could see exactly where in the Gitcoin code it's erroring out (as opposed to the stack trace from the metamask plugin )... argh

> Oh dear, I tried to hack it in my browser, have I lost my tip?

@lastmjs i dont see the tx on ethereum mainnet either.  your funds are still *safely* in the temporary address.

i'm going on vacation this week so its unlikely i'll be able to get to root cause this week

DM me your ethereum address and a link to this issue on the gitcoin slack (or email it to kevin@gitcoin.co) and ill just send you some DAI until we figure out exactly whats going on.

**Comment by owocki** [comment]
36549d91714f20ba8cbe296ce0c512b5c7a06176
