### ISSUE TITLE
as a funder whose bounty is not started, id like an email with tips about what to do after 3 days, so i can fix the issues, so i can fix it

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2249]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder whose bounty is not started, id like an email with tips about what to do after 3 days, so i can fix the issues, so i can fix it

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

bc it sux when your bounty isnt turned around

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No email

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

If a bounty is open for 3 straight days with no started workers (or pending started workers), then an email should be sent to the funder from gitcoin (CC founders@gitcoin.co) with these tips about what to do: 

https://medium.com/gitcoin/your-gitcoin-bounty-isnt-getting-any-action-what-do-you-do-61bb278f6f54

**Comment by kuhnchris** [comment]
@PixelantDesign did we create/finish this?
