### ISSUE TITLE
Typo and missing period

### ISSUE THREAD

**Issue by john-light** [gitcoinco/web#2252]
**Describe the bug**

The graphic in the screenshot has a typo ("pai") and is missing a period at the end of the "Good For" sentence (the rest of the sentences on this page end in a period).

**To Reproduce**

Check out the Cooperative Project section of this page:

https://gitcoin.co/how/funder

**Screenshots**

![paid2](https://user-images.githubusercontent.com/9424721/45791350-220be800-bc3e-11e8-98ad-0ee36e913886.png)

**Comment by kuhnchris** [comment]
Fixed
