### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by john-light** [gitcoinco/web#2253]
**Describe the bug**
When I click "Start Work" on a bounty, I get an authentication error.

**To Reproduce**
- Log in with GitHub
- Click "Start Work" on a bounty
- See authentication error

**Expected behavior**
I expect to be able to start work on the bounty without an error.

**Screenshots**

![gitcoinerror](https://user-images.githubusercontent.com/9424721/45794693-ad8c7580-bc4c-11e8-8a94-390dbec51a4c.png)

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser Firefox
- Browser Version 62.0

**Additional context**
Specifically trying to work on this issue:

https://gitcoin.co/issue/aragon/aragon-monthly/197/1078

**Comment by kuhnchris** [comment]
Is still still reproducable?

**Comment by john-light** [comment]
@kuhnchris I can't tell, I ran into a different issue when trying to use Gitcoin again:

https://github.com/gitcoinco/web/issues/2815#issuecomment-524572936

**Comment by john-light** [comment]
Switched to metamask, seems to work now.
