### ISSUE TITLE
how/funder 502 bad gateway

### ISSUE THREAD

**Issue by rahulpat** [gitcoinco/web#2257]
**Describe the bug**
Going to https://gitcoin.co/how/funder returns a 502 bad gateway error

**To Reproduce**
Go to any browser and hit https://gitcoin.co/how/funder

**Expected behavior**
Should show the right page

![screen shot 2018-09-20 at 8 23 54 pm](https://user-images.githubusercontent.com/848036/45827092-61583880-bd13-11e8-9346-9b3cb6e87228.png)

- OS: macOS Sierra
- Browser Chrome
- Browser Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by mbeacom** [comment]
@rahulpat  Can you try a hard refresh on that page and see if that resolves it?  I can't seem to reproduce, but I will go through logs and see about getting to the bottom of these phantom 502s.

**Comment by rahulpat** [comment]
Weird, works now. Perhaps something to do with your nginx config ? Might be worth looking there.

**Comment by mbeacom** [comment]
@rahulpat Yeah, thanks. I'm checking out some nginx and cloudfront logs.  I'll report back once I make some adjustments.
