### ISSUE TITLE
bug - token approval emails not going out

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2266]
bug - token approval emails not going out

https://github.com/gitcoinco/web/blob/master/app/marketing/mails.py#L224

**Comment by owocki** [comment]
@mbeacom i wonder if this is related to the CSS prefetch we spoke about earlier stuff?

**Comment by owocki** [comment]
i havent gotten a token request email since 9/7

**Comment by mbeacom** [comment]
@owocki It shouldn't be since there isn't any templating going on.

**Comment by kuhnchris** [comment]
@owocki still an active issue?
