### ISSUE TITLE
Username is misaligned in the Send tip page

### ISSUE THREAD

**Issue by rossoskull** [gitcoinco/web#2269]
**Describe the bug**
The username field in the Send tip page (https://gitcoin.co/tip) is misaligned with the Avatar

**To Reproduce**
Go to https://gitcoin.co/tip

**Expected behaviour**
It should be aligned in the middle 

**Screenshots**
![screenshot from 2018-09-24 20-20-08](https://user-images.githubusercontent.com/27884543/45959561-cd021480-c037-11e8-8fc2-e4e1f1fc40d0.png)

**Desktop (please complete the following information):**

- OS: Ubuntu Linux 18.04
- Browser: Google Chrome
- Browser: Version 69.0.3497.100

**Comment by thelostone-mc** [comment]
@mbeacom should we evaluate unifying the navbar experience ? 
I'm on two minds here

cc @PixelantDesign

**Comment by PixelantDesign** [comment]
100% yes, lets tackle when we update the nav next week.

**Comment by mbeacom** [comment]
I would say so...  Realistically, we should have `1` base template with *all* minimal reqs that are used on all pages and extend it everywhere (or at least extend it in other templates meant to be extended for use with other common deps) except email templates xD

**Comment by PixelantDesign** [comment]
cc: @octavioamu

**Comment by octavioamu** [comment]
yes at least the same nav for send tips and kudos

**Comment by octavioamu** [comment]
The thing is, send tips needs to be cleaned, is not even using bootstrap as the others part of the sites (the kudos send is using it)  So to start using the same nave we should clean it first, because for example bootstrap will be style too the inputs and buttons there

**Comment by kuhnchris** [comment]
![image](https://user-images.githubusercontent.com/761911/63590355-dda26e00-c5ab-11e9-8e69-2f78988e11f9.png)
The text seems realigned - the unification of the bar is it's own issue, please! 🗳
