### ISSUE TITLE
Issue Explorer Usability tweak

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#227]
On issue explorer, if there are no results show a button that can 'clear' all the filters so that a user can see results

**Comment by olafghanizadeh** [comment]
There is already a clear filters button in there, but a bit hard to see. Would be cool to work with @pixelantdesign on making the issue explorer more user-friendly :)

**Comment by owocki** [comment]
yeah... maybe putting it on the 'no results found' page would be a good UX move.. http://bits.owocki.com/0w3f0A1S0p1F/Screen%20Shot%202018-01-11%20at%208.07.08%20AM.png

but yes, broadly defer to @pixelantdesign on this :)

**Comment by owocki** [comment]
this now exists!
