### ISSUE TITLE
Gitcoin Issue Details: Activity Tune-Ups 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2277]
**What Is The Problem**
Gitcoin's Activity Feed has a few bugs which could be worked out to make the experience cleaner for people who are looking to grok the history of a bounty.

_Severity:_ **P2 / P3 Bug**

**How can this be fixed?**
- [ ] Remove comma (",") in the 'Work Started' section, as it's only one name. 
- [ ] For Auto-Approvals, add an 'Activity' stating someone was auto-approved. 
- [ ] For Auto-Approvals, ensure Gitcoin Bot comment updates on Github to state the auto-approval (see 2nd screenshot below where this didn't happen). 
- [ ] For all approvals, explicitly state who is approved ([Minimal] design needed? @PixelantDesign @willsputra).

![screen shot 2018-09-24 at 10 33 15 pm](https://user-images.githubusercontent.com/23297747/46030828-dda89e00-c0bc-11e8-80bd-76f005b30b68.png)

<img width="814" alt="screen shot 2018-09-25 at 12 20 00 pm" src="https://user-images.githubusercontent.com/23297747/46031013-590a4f80-c0bd-11e8-8139-799cd9c94263.png">

**Comment by willsputra** [comment]
> For all approvals, explicitly state who is approved ([Minimal] design needed? @PixelantDesign @willsputra).

My $0.02:

**Existing layout**
![screenshot 2018-09-27 01 04 35](https://user-images.githubusercontent.com/19514207/46096362-940d9f80-c1f1-11e8-9dca-0d6ad595b352.png)
vs77bb is the funder who approved the worker, correct? However, at first glance I thought vs77bb is the approved worker. I guess for me the 'Worker Approved' card isn't so clear.



**Suggested layout**
![worker applied](https://user-images.githubusercontent.com/19514207/46096582-2a41c580-c1f2-11e8-95e9-79eb8f76c404.jpg)
Suggestion: provide more detail on the 'Worker Applied' card. This solves 2 things:
• It is clear which worker is approved (Anish-Agnihotri), and which is rejected (lordvader, being also grayed out).
• It is clear who approved who.
• Eliminates the need for the 'Worker Approved' card.

thoughts? @PixelantDesign

**Comment by vs77bb** [comment]
This is much better @willsputra! I would only recommend.

"Approved by @vs77bb on Sept 9" be one line, instead of two. 

@PixelantDesign are you good for me to bounty this from here?

**Comment by vs77bb** [comment]
@willsputra can you provide the `.sketch` and `.ai` files for this? We can bounty from there 🎉

**Comment by PixelantDesign** [comment]
The activity is based on time... oldest at the bottom—> newest at the top. I recommend adding *Who was approved* to Vs77bb block (otherwise we are adding new activity to old activity items).

**Comment by willsputra** [comment]
Worker Approved then.

![worker applied](https://user-images.githubusercontent.com/19514207/46219082-f9d86380-c378-11e8-98c0-213d7b51b721.jpg)

Sketch file here: https://drive.google.com/open?id=1p5xO52ZbE44wjZD7VOkW2Ibh-B1Uo16B

@PixelantDesign should I design the rejected workers email as well?

**Comment by PixelantDesign** [comment]
@willsputra Sure! That would be awesome!
Email template should be on the creative repo!

**Comment by PixelantDesign** [comment]
@vs77bb let's make a new ticket for the Build Bounty?

**Comment by PixelantDesign** [comment]
@willsputra is there a way to make the email more whimsical? Like an apologetic decline?

The goal is to let users know that they've been declined but also show empathy and suggest a few issues that might be similar or related to their skillset. How can we let contributors down easy and still be encouraging at the same time?

**Comment by vs77bb** [comment]
@PixelantDesign Did you make a build ticket here or should I for the Activity Feed Tune Up? 

I think the Declined E-Mail will be another ticket, but will make a comment here as well since we're discussing. Workers are *declined* some, but are more often simply ignored. 

For example, in the above screenshot, Github User 'ysjwd' was not declined, but was 'passively rejected' because the funder chose someone else to work the ticket. I think that e-mail might require slightly different copy, maybe like:

``` It looks like the funder went with another applicant for this ticket. You weren't declined outright, so be on the lookout for potentially being selected down the road. Furthermore, we hope there's other work for you on the Issue Explorer! 

If not, feel free to make a [Gitcoin Request](https://gitcoin.co/requests/) for another open source project you'd like to contribute towards. ``` 

@PixelantDesign Does this copy let folks down easier?

**Comment by willsputra** [comment]
@vs77bb I like the idea! Modified it a bit here:

![application declined](https://user-images.githubusercontent.com/19514207/47029096-460b0c80-d19d-11e8-9e26-b8e793ca3da7.jpg)

**Comment by PixelantDesign** [comment]
Looks great! I'll create a build ticket.

**Comment by kuhnchris** [comment]
I think this is done - closing.
