### ISSUE TITLE
When on the  /not_a_token page, text styling and size for the Gitcoin header toolbar is inconsistent. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2280]
**Description**

When on  https://gitcoin.co/not_a_token, the Gitcoin header toolbar text is in a different style and size. 

**To Reproduce**

Compare the header toolbar text and size when on https://gitcoin.co/not_a_token and https://gitcoin.co by clicking on the dropdowns and checking the text of the header.

![screen shot 2018-09-26 at 09 11 29](https://user-images.githubusercontent.com/7516920/46093543-73e7cd00-c16c-11e8-887d-6e10a06eb13a.png)

![screen shot 2018-09-26 at 09 11 51](https://user-images.githubusercontent.com/7516920/46093549-7813ea80-c16c-11e8-85ca-6682abbaad15.png)

**Desktop**

- OS: High Sierra 10.13.4
- Browser: Chrome 
- Browser Version: 69.0.3497.100 (Official Build) (64-bit)

**Comment by thelostone-mc** [comment]
@excalliburbd Awesome ! You'll probably just have to add `g-font-muli` to the page rendered with the muli font ^_^

**Comment by excalliburbd** [comment]
@thelostone-mc Adding that to the body tag seems to fix it. I noticed the same issue in the /missions page too. I'll up a PR

**Comment by frankchen07** [comment]
@excalliburbd - thanks for picking up this issue! :) I hadn't even set up a bounty for it yet, so I've sent you a Gitcoin tip for your work!

Also thanks to @thelostone-mc for doing code reviews and covering the engineering gap :)

**Comment by mbeacom** [comment]
:white_check_mark: the fix for this issue is now deployed to **Staging** in version [20180416.0.21](https://github.com/gitcoinco/web/releases/tag/v20180416.0.21)  and available [here](http://web.jx-staging.ci.gitcoin.co)
