### ISSUE TITLE
Tips race condition 

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/web#2281]
**Describe the bug**
This is a race condition bug that exists in Tips.

Its this line:

https://github.com/gitcoinco/web/blob/master/app/dashboard/tip_views.py#L133

In the case where the TX has already been mined before the page reloads, this bug will occur.

Its checking an account that is already been emptied because the tx has already gone through. I think this bug only occurs on the local testnet, because locally the transaction happens instantly, and on Rinkeby or Mainnet it takes more than a second.

**To Reproduce**
Try to send a Tip to another user on the local testrpc.

**Expected behavior**
The tip should go through as normal, and the confirmation page should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/7018237/46109817-4ff5ad00-c1a7-11e8-9f9c-904d4976d6f7.png)

**Proposed Fix**
Updating that line about to:

```
elif not_mined_yet and not request.GET.get('receive_txid'):
```

should do the trick.

Alternatively we could check that the transaction has been mined by using https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.getTransactionReceipt

**Desktop (please complete the following information):**

- OS: Mac OS 10.13.6
- Browser Chrome
- Browser Version 69.0.3497.100

**Comment by kuhnchris** [comment]
Could you open a PR for this if this is still relevant?
