### ISSUE TITLE
Implement Frontend - "Subscription Terminated" Email

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2291]
### User Story

As a Grant Supporter, I want to know when a grant creator has ended a grant and that my subscription payments have been canceled so that I am aware that the project is no longer seeking funding from the community and I will no longer be charged. 

### Why Is this Needed

The "Subscription Terminated" Email is needed so that grant supporters know when their subscriptions have been terminated by the grant creator and will not longer contributing funds. 

### Description

*Type*: Feature

### Definition of Done

- [ ] Email uses the template.html file found at gitcoinco/web/app/retail/emails

- [ ] Implement the designs found at https://github.com/gitcoinco/web/issues/2090
        -assets can be found at: 
[Gitcoin Email_Grants.sketch.zip](https://github.com/gitcoinco/web/files/2428786/Gitcoin.Email_Grants.sketch.zip)

- [ ] html file should be stored at gitcoinco/web/app/retail/emails/grants on the web/grants branch

### Additional Information

Please submit work as a PR to web/grants branch

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email implementation work can be found here: gitcoinco/web/app/retail/emails

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by Anish-Agnihotri** [comment]
This has been completed [here](https://github.com/Anish-Agnihotri/Gitcoin-Emails/blob/master/Templates/subscription_terminated.html). As mentioned previously, a single PR will be staged including all necessary files.

Example image of Live HTML: 
![Image](https://i.imgur.com/acDdhZk.png)

Thanks, Anish.
