### ISSUE TITLE
Worker status on issue page shows as Worker Applied even after accepted

### ISSUE THREAD

**Issue by montanaflynn** [gitcoinco/web#2292]
**Describe the bug**
I applied for an issue, got an accepted email but on the issue page it still shows "Worker Applied" under the "All Activity" section.

**To Reproduce**
Log in, apply for an issue, wait until your accepted, view the issue page.

**Expected behavior**
The activity to change or a new activity item to show up as Worker Approved.

**Screenshots**
<img width="1205" alt="screen shot 2018-09-28 at 10 19 27" src="https://user-images.githubusercontent.com/24260/46186410-a0d0e700-c308-11e8-9d59-955ffa5f1790.png">
<img width="1015" alt="screen shot 2018-09-28 at 10 23 36" src="https://user-images.githubusercontent.com/24260/46186414-ac241280-c308-11e8-8a22-78b4b5c5708b.png">

**Desktop (please complete the following information):**

- OS: Mac High Sierra
- Browser: Chrome
- Browser Version: 69

**Comment by kuhnchris** [comment]
The appropriate "Worker Approved" lines is available - it's shown for the bounty creator. If you think this is a bug, please let us know in a new ticket with the change suggestion.
