### ISSUE TITLE
Design a Refer a Friend Experience for Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2297]
**Not Ready to Be Worked On**

### User Story

As a user of Gitcoin, I'd like to be able to tell others about Gitcoin and invite them to join a great open source developer community through social media.

### Why Is this Needed

We'd like to grow the number of contributors on the Gitcoin platform.

### Description

Design an online virality experience to grow the Gitcoin community. 

Ideas:
**Refer a friend (Referral Program)**
Invite a friend to join
You get $20 if your friend completes a bounty.
You get extra privileges if you bring in X number of friends/contributors.

### Definition of Done

[ ] Design an experience detailing a direction that would be able to support the above use case.
[ ] Consider how success could be measured.

### Additional Information
Review with @PixelantDesign @vs77bb

**Comment by kuhnchris** [comment]
Did you ever go forward with the referal programs?
