### ISSUE TITLE
Reputation (and Risk Management) Engine

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#23]
Right now, as a hypothetical submitter, I don't really know who the counter-party is for a bounty, so I take the risk that they're a total jerk and take my code but don't pay out the bounty.  

What can we do to manage this risk?  Some ideas from my side:
* Reputation system:  Optionally link to your github identity, ability to browse the past bounties an address has generated.
* Extensible way to process bounties
* For example, Bounties that have arbitration process built in.  Bounties that automatically accept themselves when a certain set of tests pass on a PR.

**Comment by owocki** [comment]
this is what my designer put together for me for this: 

<img width="658" alt="slack-imgs" src="https://user-images.githubusercontent.com/513929/31136618-18e7f9d0-a826-11e7-8fe0-c5fddd435d3b.png">

but its just a rough rough rough first stab

ive been thinking that the closest parallel for me is the interface that airbnb provides to show reviews / stars of what working with someone is like

**Comment by owocki** [comment]
someone smart said this to me today:

> I believe this engine can be built in a way that makes open source development the equivalent of mining for other currencies.

at high liquidity, this is true and it's the endgame we may want to strive for!

**Comment by phal0r** [comment]
If thought about the reputation systems and want to contribute my loosely coupled thoughts. I tried to structure it, as good as I could :)

for establishing trust to people helping you solving issues, implementing features or discussing technologies and ideas
one would want to get an impression of their abilities and skills. That means a kind of reputation system must be established

let's start with typical tasks in a project:
- in later steps of the projects, gitcoin should provide tooling to reflect these tasks and the lifecycle of an it project

a)
- envision / solve a problem people are facing
- discuss the structure
- maybe market research which is a fundable step via gitcoin on its own

b)
- plan / roadmap
- description of the mission and the meaning of the project
- categorize the projects with tags, i.e. social project, infrastructure project, marketing, saas platform, ....
- gantt chart with structures
    -> structure templates for best practices
    -> could be the result of a gitcoin funded request
    -> free for open source and public projects
    -> maybe later fees for commercial projects with privacy features
    -> each step of the gantt chart is made visible as a fundable gitcoin task
- other technical documents (diagrams, data model) that is needed
- link project with VC, Crowdfunding other investment platforms to back it by prodiving more details
    
c)
- discuss technologies
    -> opinions from members with high reputation in its technological field are pretty valuable, since they are not personally affiliated with the project but highly skilled and thus have a objective view on this matter
	-> decisions on structure and architecture are long-lasting throughout the project, if these decisions do not meet the business requirements, refactoring will take up a lot of time
- fund steps
- enforce tests
d)
- neutral code reviews are fundable steps on its own
    -> a neutral person is to review the code and give feedback to help the owner assess the quality
- technical advisory for new features
    -> impact on code base
    -> refactoring needs
	
dimensions in reputation:
    - reputation in specific programming language
    - reputation in structuring/architecturing code
    - reputation in modelling data
    - reputation in technology choices / discussions
    - reputation if objective of the bounty is met  
        -> the solution could be technically perfect or a good design, but still worthless if it doesn't fit the requirements
    
when bug, important dimensions are:
    - reputation in specific programming language
    
when feature, important dimensions are:
    - reputation in specific programming language
    - reputation in structuring/architecturing code
    - reputation in modelling data
    - reputation in technology choices / discussions
    
when review, important dimensions are:  
    - reputation in specific programming language
    - reputation in structuring/architecturing code
    
when discussion, important dimensions are:
    - reputation in structuring/architecturing code
    - reputation in modelling data
    - reputation in technology choices / discussions
    
who and what should influence reputation?
    - reviewers should be able to influence reputation when reviewing current work
        -> how to prevent misuse?
        -> ability to add description and details on why current work is good or bad
    - higher ranked reviewers lead to more reputation when code is being reviewed
    - up- or downvote work in the given dimensions
    
    - group reviewers/developers/designers in reputation levels
    - ability to request reviewers with specific reputation level to review result of work 
    
    - does it fit the objectives
        -> decided by bounty owner
    
    - when creating a bounty the algorithm can suggest the reputation level that fits based on the money spent
    - there could be gitcoin (or other) forums, which suggest best practices for specific technologies
        -> this could be a base guideline for reviewers
	- incentivize giving reviews
    
in general
    - maybe reputation should be a growing number, not only a 1 to 5 star rating, so progress in the development of programming languages can be taken into account
        -> a 5 star rating in 2017 is probably not the same like a 5 star rating in 2020, since technology has advanced and it is unclear if the developer also has advanced to the same level
		
so a the managers of the project may want to see
	- new parts got funded
	- parts are completed
	- parts are under review
	- review of a part accepted     

a developer may want to see
	- new work that fits the profile (as you already mentioned)
	- progress on projects he/she took part
	- progress of projects he/she finds exciting, that are managed via gitcoin
