### ISSUE TITLE
as a site administrator, i want to reward those at the top of the leaderboard, so we can show our appreciation

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#230]
some ideas:

At end of month
- Digital 'Medals' for top 10 earners
- Email to them on first on month
- Roundup email giving them cred for being at the top!?
- historical leaderboards... so they can be at the top forever for that month

**Comment by mkosowsk** [comment]
I really like this, gives these top earners a sense of pride of accomplishment and also gets the word out... people will look at these leaderboards and say, "Wow, these developers earned this much in a month?!" 👍🏻

**Comment by owocki** [comment]
what you think @vs77bb @mbeylin ?

**Comment by mbeylin** [comment]
I like all of the above, along with first pick at new swag

**Comment by mkosowsk** [comment]
One quick thought, might be good for this to be opt-in (i.e. ask the top earners if they are cool with being on the leaderboards before putting leaderboards out). Some people are particular about their privacy 👍🏻

**Comment by thelostone-mc** [comment]
The wall of the fame :')
Mt vote is for all of them :D

**Comment by owocki** [comment]
i asked everyone on the leaderboard if they wanted some schwag... hopefully most of them respond ::)

**Comment by D3RPZ1LLA** [comment]
My 2 cents:
Award 'medals' / 'schwag' based on meeting a threshold of contributions measured by ETH earned or something. This will motivate contributors to meet that threshold of contributions instead of just outdoing others. You can scale or tier threshold rewards too if you want.
