### ISSUE TITLE
"submit work" button is greyed out

### ISSUE THREAD

**Issue by john-light** [gitcoinco/web#2308]
**Describe the bug**
I am attempting to submit work to claim a bounty and the button is greyed out and doesn't do anything when I click it.

**To Reproduce**
Start work on an issue. Then try to submit work to claim the bounty. Notice the "submit work" button is greyed out.

Additional detail about this case: I also funded the bounty in question. I do have MetaMask unlocked and loaded with enough ether.

**Expected behavior**
I expect to be able to click the button and submit work to claim the bounty.

**Screenshots**

![gitcoin-submiterror](https://user-images.githubusercontent.com/9424721/46251747-e8429a80-c410-11e8-975e-604365c02a73.png)

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser Firefox
- Browser Version 62.0

**Comment by thelostone-mc** [comment]
Hey @john-light so looks like you are the funder of the bounty.
We don't allow the funder to submit work -> Ideally we should disable `Start Work` for the funder too to prevent them for starting work funded on their own bounty

If you wanna get back the funds of your bounty -> you'll have to cancel the bounty
