### ISSUE TITLE
improvement - filtering bounties for repository

### ISSUE THREAD

**Issue by karsiwek** [gitcoinco/web#232]
right now chrome extension has to filter bounties for particular repository on client side, which is fine for now, but it won't be efficient in a future.

api allows us to get some bounties by supplying query with: github_url but i have to know the full url. 
for instance:

https://gitcoin.co/api/v0.1/bounties/?order_by=web3_created&network=mainnet&github_url=https://github.com/MyEtherWallet/MyEtherWallet/issues/775

In order to recieve all bounties we could:
a) introduce new parameter, like github_repository, ie.
https://gitcoin.co/api/v0.1/bounties/?order_by=web3_created&network=mainnet&github_repository=MyEtherWallet/MyEtherWallet
would return all bounties for MyEtherWallet
b) introduce astrix in github_url parameter. ie.:
 https://gitcoin.co/api/v0.1/bounties/?order_by=web3_created&network=mainnet&github_url=https://github.com/MyEtherWallet/MyEtherWallet/issues/*

both options should work for me, but i think a) looks cleaner.

**Comment by owocki** [comment]
i think this is a good idea

**Comment by connorwarnock** [comment]
@karsiwek I can tackle this.  I think [a] looks like a good way forward

**Comment by owocki** [comment]
@connorwarnock great! looking forward to having you work on this.   will look out for a PR.  how much of a tip do you think is fair?

**Comment by connorwarnock** [comment]
@owocki This seems like a pretty small task, will let you decide an appropriate amount :)

**Comment by connorwarnock** [comment]
@owocki For this PR, I'd like to add tests to verify my changes, both unit tests and request tests.  What are your thoughts on following the Django REST framework setup: http://www.django-rest-framework.org/api-guide/testing/?

**Comment by owocki** [comment]
seems pretty standard (which i like).  @mbeacom what do you think

**Comment by mbeacom** [comment]
@owocki @connorwarnock Absolutely! As far as DRF tests are concerned, that's the way to go.

**Comment by connorwarnock** [comment]
Awesome, I'll have it turned around shortly
