### ISSUE TITLE
improve the efficicacy of the 'new bountys that match your skillset' emails

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2320]
its interesting that while we have 10k email subscribers, we only send 3k ‘new bountie s that match your skillset’ emails

if we could close that gap, and send that daily email more often, we could perhaps capture much more engagement / retention

i havent written up a script to figure out why theres only 3k sent.. but im assuming its because we dont know the keywords that most of the users are interested in

# ideas

1. send that email to users who we dont know the keywords for (and accept a lower CTR)
2. try to auto-sync keywords that we think apply to that user, based upon their serach history, or theier github profile info

**Comment by owocki** [comment]
```
In [11]: EmailSubscriber.objects.filter(keywords=[]).count()
Out[11]: 6762

```

just what i thought!

**Comment by owocki** [comment]
i wonder if we could approximate the right keywords by pulling them from github

```

In [19]: for es in EmailSubscriber.objects.filter(keywords=[]):
    ...:     profile = Profile.objects.filter(email=es.email)
    ...:     if profile.exists():
    ...:         print(profile_keywords_helper(profile.first().handle))
```

**Comment by PixelantDesign** [comment]
I wonder if it would be too much to receive a daily email.

> send that email to users who we dont know the keywords for (and accept a lower CTR)
or send a link to just the one screen in the ftux to capture their skills and interest.

> try to auto-sync keywords that we think apply to that user, based upon their search history, or theier github profile info
I also like this approach if we can get this info from Github.

**Comment by owocki** [comment]
1c29525a08965a5e839f39d3dc55d8390605fb52 should help with this.. ill make a note to check on the data later in the week

**Comment by frankchen07** [comment]
Do we also want to make the distinct between emails that are potentially funders and emails that are potential contributors? I guess if all they've done is signed up, then they could go either way too.

**Comment by owocki** [comment]
> Do we also want to make the distinct between emails that are potentially funders and emails that are potential contributors?

this is a good idea.. we can add many tags to each email

**Comment by kuhnchris** [comment]
Did we ever implement this?
