### ISSUE TITLE
Desktop Miner integration

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2324]
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We need a miner to listen for metatx and to submit them onchain when appropriate time comes

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Work with Austin Griffith to import his desktop miner into Gitcoin. Will likely be in a docker container. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
When we can submit a metatx from the app and have the desktop miner process those transactions correctly

**Comment by owocki** [comment]
cc @austingriffith

**Comment by captnseagraves** [comment]
@mbeacom I think we should prioritize this issue. It will unblock work for @owocki on `sync-geth` stuff, and the web3 integration/test stuff for me.

**Comment by owocki** [comment]
https://github.com/austintgriffith/tokensubscription.com/blob/master/backend/tokensubminer.js is austin's subminer
