### ISSUE TITLE
Design "User Transaction History" View

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2325]
### User Story

As a Grants User, I want to be able to view my transaction history so I know when I have contributed to what grants

### Why Is this Needed
The User Transaction History view is needed so that users can see when they have spent money and track their contributions. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] View has standard Gitcoin nav bar and footer
- [ ] Displays list of all contributions a user has made to any grant
- [ ]  Design must be on brand, see creative repo for brand guide

### Additional Information

To be reviewed with @PixelantDesign @mbeacom @captnseagraves

Submissions should be made to the gitcoinco/creative repo. 
Examples of previous work can be found in the gitcoinco/creative repo as well. 

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by owocki** [comment]
@PixelantDesign @justpixel could we get a quick rev on the transaction history view on the grants project?  looks like we missed this initially, and providing a transaction history for the grant is a pretty important functionality to have.

**Comment by owocki** [comment]
i think this one is the most important of the transaction history tickets that seagraves just created..

**Comment by PixelantDesign** [comment]
Yep will do

**Comment by justpixel** [comment]
![transcation history](https://user-images.githubusercontent.com/7627020/46411666-108a0c00-c725-11e8-9b7f-5fd5d1a24b8c.png)

**Comment by owocki** [comment]
@justpixel this looks good but matches the old profile... i wonder if we should adhere to the new profile design ( gitcoin.co/profile/owocki )

**Comment by captnseagraves** [comment]
@justpixel @PixelantDesign @owocki Any movement on this? Is it ready to move to an implementation ticket?

**Comment by PixelantDesign** [comment]
We'll work on this tomorrow, it'll be ready early next week.

**Comment by willsputra** [comment]
@PixelantDesign @captnseagraves here ya go!

![my grants](https://user-images.githubusercontent.com/19514207/46899324-a01d8080-cec4-11e8-8652-b8541d507a11.jpg)

**Comment by thelostone-mc** [comment]
I'm assuming the my grants section would be displayed undet the profile section at any given point in time right ?

**Comment by willsputra** [comment]
Sketch file here:
https://drive.google.com/open?id=1UpR0jJowiFi2nO_5DTplNdky0BnCjUAk

**Comment by willsputra** [comment]
@thelostone-mc currently nope! although in the future I think it would be useful to somehow show what I've contributed to on my profile...

**Comment by captnseagraves** [comment]
@thelostone-mc Right now, "My Grants" will be clicked into via the `Grants` nav bar. @willsputra I agree that eventually, it might make sense to have some information about grants available via the profile page. We've discussed it, but are opting for the nav option for now.
