### ISSUE TITLE
Integrate Email templates with data

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2328]
### User Story

As a Grants User I want all my email to be populated with relevant information so that I know what is happening with grants that I support or that I am an administrator of. 

### Definition of Done
 - [ ] All emails are populated with relevant information via grants/views.py

### Additional Information

- Current emails are populated via "def" in dashboard/views.py, which then calls a "def" in marketing/mails.py, which then calls a "def" in retail/emails.py. The Grants email system may likely follow a similar architecture.

**Comment by captnseagraves** [comment]
Assigning @Anish-agnihotri

**Comment by captnseagraves** [comment]
@Anish-Agnihotri Any update on this or estimated timeline? Thanks!

**Comment by Anish-Agnihotri** [comment]
Hey, my apologies for the fallout on this. I'd propose that I can finish this over the next couple of days. To be generous, a deadline of before the 18th?

If that's a bit too long, do let me know and I'll re-prioritize accordingly to match.

**Comment by captnseagraves** [comment]
@Anish-Agnihotri That should be fine. We are coming into the main crunch time with two weeks left to deliver, so sooner is better, but dont want to put too much pressure on. Whatever works for you is good!

**Comment by thelostone-mc** [comment]
Moving this
