### ISSUE TITLE
as a user who has lost my tip, i want a deeplinked, public, tip page so i can find my tip

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2332]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who has lost my tip, i want a deeplinked, public, tip page so i can find my tip

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
users don't always know where to claim their tips.  

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
right now they see their tip in a 'claim tip' menu on the top right of the nav (and they get an email).
but they still sometimes doesnt know how to get their tip.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

we create a public facing view about the tip, and we link it in the bounty activity feed, on the users profile (both sender and receiver)

it should look like this:

![deeplinking_tips](https://user-images.githubusercontent.com/513929/46388413-1e8a4f00-c689-11e8-8247-1b58cddfbc32.gif)

**Comment by kuhnchris** [comment]
Was there ever a build ticket for this?
