### ISSUE TITLE
Local testing with IPFS does not work from browser

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/web#2335]
**Describe the bug**
We have a local version of IPFS in a docker container for local testing.  If works fine from the `web` docker container if you set the .env file to these values:

```
# IPFS setup
IPFS_HOST=ipfs
IPFS_API_PORT=5001
IPFS_API_SCHEME=http
```

With these settings, the `web` container can access the `ipfs` container just fine.  However, when trying to access IPFS from the localhost browser, it does not work.  There are a couple problems:

- Javascript will read the Django.settings `IPFS_HOST` as `ipfs`.  This works from docker, but from your browser this needs to be changed to `localhost`.
- IPFS will return a CORS error.  The configuration for IPFS needs to be changed to allow the connection from any host (arbitrary docker host IP).

**To Reproduce**
Try testing anything in the browser that requires IPFS, using the docker IPFS, with those .env settings.

**Expected behavior**
It should work the same with localhost IPFS as it does with ipfs.gitcoin.co or infura.

**Recommend fix**

- Translate `ipfs` to `localhost` in javascript
- Mount an `ipfsconfig.json` file in the docker-compose file for ipfs.

I have the fix for this in a private repo.  I can make the PR for this if you all approve.

**Desktop (please complete the following information):**

- OS: Mac Mojave
- Browser Newest Chrome

**Comment by mbeacom** [comment]
@jasonrhaas Can you just set `IPFS_HOST` to `localhost` ?

**Comment by mbeacom** [comment]
@jasonrhaas Whenever you get a minute, feel free to check out #2336
