### ISSUE TITLE
identity on the platform is kind of a mess

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#234]
right now identity lives on 

* metamask
* github
* slack
* email
* website

itd be great if we could unify these in some meaningful way such that we could track where a user spends most of there time and when/where they drop off

**Comment by vs77bb** [comment]
@owocki Does this need to be in to-do? Not sure it's spec'ed enough for us to prioritize over some other quick wins

**Comment by owocki** [comment]
i had hoped that by prioritizing it, @mbeacom and i could brainstorm some ways to fix it. to your point, it needs better specification

**Comment by mbeacom** [comment]
@owocki 👍 I think we could migrate `Profile` to inherit `User` or relate to it.  That'll give us all of the benefits of the standard django user.

**Comment by abitrolly** [comment]
@PixelantDesign and what is the resolution or common way to track identity accross multiple platforms?

**Comment by kuhnchris** [comment]
Do we still miss this data or do we already have something in place for this?

**Comment by owocki** [comment]
this task is stale..  i have an active task to rework reputatoin on the platform. closing now
