### ISSUE TITLE
usability problem on the new profile - its hard to read the activities

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2340]
https://gitcoin.co/profile/iamonuwa

it's very hard to read the action in these activity entries
 
<img width="901" alt="screen shot 2018-10-03 at 3 12 54 pm" src="https://user-images.githubusercontent.com/513929/46439841-d3bb1680-c71e-11e8-85cd-63c3d449131f.png">

i think the 'action' taken should be much more prominent on each of these entries

**Comment by owocki** [comment]
cc @PixelantDesign

**Comment by PixelantDesign** [comment]
Agree! This mirrors the explorer right now. We will need to determine if the display should mirror each other for the profile use case and the explorer use case.
