### ISSUE TITLE
grants -- put up a 'this is in alpha, dont put a lot of $$$ in it yet' warning

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2350]
grants -- put up a 'this is in alpha, dont put a lot of $$$ in it yet' warning on the grants contributor page

**Comment by owocki** [comment]
per @captnseagraves suggestion in the call today

**Comment by captnseagraves** [comment]
@owocki how should this be displayed? An alert is jarring enough to make people look at it. Also, should we have it on the "New Grant" view, so grant creators aren't expecting a ton of money in the beginning?

**Comment by owocki** [comment]
i think you'd be fine just using the same styles as the `<span id="network"></span>` on bounty/details.html  -- just some light red coloring.

**Comment by thelostone-mc** [comment]
@owocki / @captnseagraves  -  which all pages would this pop up in ? 
@willsputra got a design in mind?

**Comment by owocki** [comment]
@thelostone-mc on the 'create a grant' page and on the 'fund a grant' page

RE: design, this doesnt have to look great, so i dont know if we really need to pull in design yet.   pasting my comment from above: `i think you'd be fine just using the same styles as the <span id="network"></span> on bounty/details.html -- just some light red coloring.`
