### ISSUE TITLE
Advanced Payout - Default Names for Users Working On the Project

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2352]
### User Story

As a funder, I want Gitcoin to be smart and know who I should pay out when I use the advance pay feature.
To know more about check [here](https://gitcoin.co/how/funder#payment)

##### Steps : 

-  locally set up the app 
- Login as funder `/new` and create a new [co-op bounty](https://gitcoin.co/how/funder#project-types) 
- Login as contributor  -> navigate to bounty -> Click on `start work` followed by `submit work` button
- Login back as funder -> Click on Payout and select Advanced Payout and the contributors name should be auto-populated

### Why Is this Needed

Don't make me think!
Currently the contributors names are not defaulted into advance payout, forcing the funder to go back to the previous screen to remember who is working on the task or how to spell their github user name.

### Definition of Done

- [ ] The contributors names who have **started work** should be defaulted in.
- [ ] The implementation is tested.
Please expects a few round of revisions to get the PR merged.

### Related Issues

This ticket is part of a series of fixes for Advanced Pay
- **[Issue 2215](https://github.com/gitcoinco/web/issues/2215)** Display Tooltip **Where is My Money Going** (Bountied)
- **[Issue 2294](https://github.com/gitcoinco/web/issues/2294)** Default to Bountied Amount for Payment
- **[Issue 2240](https://github.com/gitcoinco/web/issues/2240)** Add Auto Complete & Make it clearer who I'm paying (verified/unverified)

### Screenshot of the current implementation

<img width="709" alt="screen shot 2018-10-04 at 12 55 12 pm" src="https://user-images.githubusercontent.com/238235/46491817-cf076880-c7d9-11e8-8e71-03182e9eaaea.png">

**Comment by kuhnchris** [comment]
Superseeded/Implemented by #2215
