### ISSUE TITLE
Basic Payout - Implement Display of User Icon and Address

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2354]
### User Story

As a funder, I'd like to see a recognizable icon and wallet address of the contributor that I'm making a payment to.

### Definition of Done

- [ ] Review how advanced payout handles displaying a user icon and wallet address.
- [ ] Implement just the display of the user's icon and wallet address. In the basic payout instance we will not need the typedown functionality.

### Reviewers
@PixelantDesign @thelostone-mc 

**See Current Implementation**
<img width="600" alt="screen shot 2018-10-04 at 2 07 43 pm" src="https://user-images.githubusercontent.com/238235/46493892-7a66ec00-c7df-11e8-906c-a0f71210ea61.png">

**See Advanced Payout Implementation**

<img width="519" alt="screen shot 2018-10-04 at 2 16 04 pm" src="https://user-images.githubusercontent.com/238235/46494128-13960280-c7e0-11e8-8f97-723ee5b20584.png">

cc @thelostone-mc feel free to edit

**Comment by sunilveera** [comment]
Can i work on this issue

**Comment by PixelantDesign** [comment]
Sure @sunilveera 
cc: @thelostone-mc to provide technical guidance.

**Comment by thelostone-mc** [comment]
To whoever picks this up you'd have  reuse [select2](https://select2.org) we have for advanced payout. Prepopulate only users who've submitted and enable the funder to serach and filter those

cc @sunilveera

**Comment by pinkiebell** [comment]
I'm also ready to pick this up.  Just leave me a Yay or Nay here 👍

**Comment by thelostone-mc** [comment]
@pinkiebell go for it
