### ISSUE TITLE
DESIGN - as a funder, i want a grant quickstart page, so i know how to make my grant successsful

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2355]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder, i want a grant quickstart page, so i know how to make my grant successsful

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Grant evaluation process is up to potential funders.  (1) does this deliver value to me?  (2) does this deliver value to the ecosystem?

Its up to the person pitching the grant to to deliver a compelling enough pitch !  Just like on patreon / kickstarter…

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Quickstart page

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
craete a grants quickstart guide, similar to this bounty guide… http://bits.owocki.com/0daf752ff4ad/Screen%20Shot%202018-10-04%20at%203.25.41%20PM.png

**Comment by willsputra** [comment]
@owocki cc @PixelantDesign First draft below! Came up with two possible views: tabs and one page. What do you think?

Let me know too if I should add anything to the copy. Thanks! 

**Tabs**

![fund](https://user-images.githubusercontent.com/19514207/47450537-1b056600-d7f8-11e8-9cfe-5500bd63320a.jpg)
![start](https://user-images.githubusercontent.com/19514207/47450541-1b9dfc80-d7f8-11e8-9d1a-f4c9ab182591.jpg)

**One Page**

![view2](https://user-images.githubusercontent.com/19514207/47450546-1d67c000-d7f8-11e8-8c13-52195744bdd0.jpg)

**Comment by frankchen07** [comment]
Frank likes the tabs too. :)

**Comment by owocki** [comment]
I like the tabs!  @PixelantDesign @willsputra any objections if we bounty the frontend coding of this?

**Comment by PixelantDesign** [comment]
We can certainly bounty @owocki, but curious if @thelostone-mc could pick this up since he's working on grants?

**Comment by owocki** [comment]
@willsputra can u post the sketch file pls?

**Comment by thelostone-mc** [comment]
> any objections if we bounty the frontend coding of this?

@owocki yes. Too late I've called dibs :P

**Comment by willsputra** [comment]
@thelostone-mc sketch file!
https://github.com/gitcoinco/creative/blob/91383e7b9c5eb853338a3bfdd8088e135d2ba698/00_Submissions/Grants%20Quickstart/Grants%20Quickstart.sketch

**Comment by owocki** [comment]
ok i wil cancel the bounty and assign you over at https://github.com/gitcoinco/web/issues/2732
