### ISSUE TITLE
Don't report bounty killed activity for bulk payouts

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2363]
### User Story

As a funder, I want to distribute funds with bulk payout without `killed_bounty` (Canceled Bounty)  activity appearing in my activity feed.

### Why Is this Needed

If a funder uses the bulk payout option to distribute funds, we initiate a bounty cancellation against the standard bounties contract to allow original funds to be released for refund to the funder.  We need to intelligently differentiate between legitimately cancelled bounties and bulk payout cancellations, so the funder doesn't have seemingly negative activity thrashing their feed.

### Description

*Type*:  enhancement

### Current Behavior

Funder uses bulk payout -> original bounty is temporarily transitioned to `cancelled` -> `Activity` object with `activity_type == 'killed_bounty'` is created in relation to the funder's profile.

### Expected Behavior

Funder uses bulk payout -> original bounty is temporarily transitioned to `cancelled` -> No cancellation activity created.

Note: We must maintain cancellation activity when it is a legitimate bounty cancellation.

### Reproduction

Use bulk payout -> complete bounty funds dispersement.

### Solution

Add a check to `dashboard/management/commands/create_activity_records.py@create_activities` to ensure bounties with `tips` due to bulk payout aren't reported as cancelled. 

### Definition of Done

- [ ] Follow contributor guidelines outlined in:  https://docs.gitcoin.co/mk_contributors/ and https://docs.gitcoin.co/mk_styleguide/
- [ ] Activity for cancellations report for legitimate `kill bounty` requests.  
- [ ] Activity for cancellations no longer created following `bulk payout`
- [ ] Doesn't **break** existing functionality
- [ ] Test it locally
- [ ] No decrease in test coverage
- [ ] Travis, Codecov, and Stickler CI are green/passing
- [ ] PR review completed and accepted by team
- [ ] PR is merged

### Additional Information

If you require further clarification, please inquiry on this Github issue and ping relevant team members:  @mbeacom @thelostone-mc @SaptakS

**Comment by thelostone-mc** [comment]
Yo @mbeacom so closing this out as 
- the UI already handles this as of now to show 
- we are migrating to v2 std bounties which has multipayout built in

**Comment by mbeacom** [comment]
@thelostone-mc No complaints here. 😄
