### ISSUE TITLE
i'd like the 'where is my eth going' modal to show up on gitcoin.co/tips

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2366]
i'd like the 'where is my eth going' modal to show up on gitcoin.co/tips

where it is now:

<img width="1894" alt="screen shot 2018-10-05 at 1 59 26 pm" src="https://user-images.githubusercontent.com/513929/46560047-2293b800-c8a7-11e8-96bf-35460fc8ea89.png">

where it should be added:

<img width="753" alt="screen shot 2018-10-05 at 2 00 03 pm" src="https://user-images.githubusercontent.com/513929/46560053-258ea880-c8a7-11e8-9601-f0a164ea5e6f.png">

**Comment by owocki** [comment]
@usmanmuhd any interest in this

**Comment by usmanmuhd** [comment]
Sure, i'll be doing this.
