### ISSUE TITLE
bug - padding on /explorer and bounty

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2367]
was the padding on these pages changed intentionally?

<img width="666" alt="screen shot 2018-10-05 at 1 57 39 pm" src="https://user-images.githubusercontent.com/513929/46560166-92a23e00-c8a7-11e8-8129-820470103564.png">
<img width="1905" alt="screen shot 2018-10-05 at 1 57 58 pm" src="https://user-images.githubusercontent.com/513929/46560167-933ad480-c8a7-11e8-8db2-8e6f1625e009.png">

looked much better before IMHO

for reference, this is what it looked like before (and still looks like in stage ) 
<img width="1920" alt="screen shot 2018-10-05 at 1 58 13 pm" src="https://user-images.githubusercontent.com/513929/46560183-9f269680-c8a7-11e8-9cb3-180fdc35e56a.png">

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/commit/14bda0d9b166dab73b75920826e02b340c6eec1e#diff-dd9b7cab0b87148c241a07260636478dL42

**Comment by mbeacom** [comment]
:white_check_mark: the fix for this issue is now deployed to **Staging** in version [20180416.0.21](https://github.com/gitcoinco/web/releases/tag/v20180416.0.21)  and available [here](http://web.jx-staging.ci.gitcoin.co)
