### ISSUE TITLE
Activity timeline visible at a glance for bounty hunters

### ISSUE THREAD

**Issue by Cygnusfear** [gitcoinco/web#2382]
### User Story

As a bounty hunter, I want the activity timeline to be on the search page and the fold of the issue page to see at a glance if I can contribute to the issue.

### Why Is this Needed

The Activity timeline is the most accurate representation of information available on an issue. It has somehow been placed at the bottom of the page. Other details on the fold issue do not clearly describe the state of the issue. An issue might be open, but unavailable due to being worked on. The bounty hunter now needs to click 1. to view the issue 2. scroll all the way down the page (3. if the issue has seen much activity, the user has to scroll down the activity history)

### Solution

Replace the vertical timeline component with a horizontal timeline component that is placed at the bottom of the issue and at the top of the issue fold.

Nodes on the timeline represent an action. Different timeline colors present different actions (work is ongoing, work has stopped). A tooltip on mouseover shows the title of the activity and the user's avatar. 

<img width="767" alt="screenshot 2018-10-08 20 08 45 copy" src="https://user-images.githubusercontent.com/2925132/46626374-73214480-cb37-11e8-8cc7-accf70433e8f.png">

**Comment by owocki** [comment]
thanks for the idea and especially for the mockup!

**Comment by Cygnusfear** [comment]
Thanks! Appreciate it, if you put out a bounty I might even consider building it myself 😉

**Comment by owocki** [comment]
i want to see what @PixelantDesign thinks first but its a possiblity :)
