### ISSUE TITLE
as a user, i want a 'sync this bounty' button, because sometimes i suspect gitcoin is not in sync with blockchain

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2388]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want a 'sync this bounty' button, because sometimes i suspect gitcoin is not in sync with blockchain

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
we get about a dozen support requests a month to the effect of ' i submitted my tx, but its not showing up on gitcoin.. what gives'.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Sync from Blockchain button

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Sync from Blockchain button next to the 'View Issue Details on Github'

**Comment by owocki** [comment]
@PixelantDesign feedback on this?

**Comment by PixelantDesign** [comment]
Makes sense! My question is, if a user clicks, how fast will this happen, do we need to message that it might take a bit?

**Comment by owocki** [comment]
@PixelantDesign it should be within 1 - 4 seconds, but sometimes more if infura is acting up.  we should have a loading indicator while the request is happening.

fix it twice for infura thing => https://github.com/gitcoinco/web/issues/2394
