### ISSUE TITLE
frontend onhover animation for grants logo

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2402]
as a user who appreciates attention to detail, i want to have the same experience of the gitcoin logo lighting up, when i visit grants and hover over the logo.

main site:

![screen recording 2018-10-09 at 04 35 pm](https://user-images.githubusercontent.com/513929/46702726-783ace00-cbe1-11e8-9c2e-f3ff09c0d6b6.gif)

grants assets: http://bits.owocki.com/7ff08c3c4cb5/Grants-white.gif
http://bits.owocki.com/394f1924664e/Grants.gif

scope of this task:  make it so that grants logo lights up when u hover it

[here is how this is done on the boynties site](https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/base.js#L53-L70)

**Comment by owocki** [comment]
this one should be easy i hoep

**Comment by Anish-Agnihotri** [comment]
I'll PR this within the next hour or so.

**Comment by owocki** [comment]
new art assets => http://bits.owocki.com/3cff00f3e2c5/Archive%202018-10-10%20at%2010.27.17%20AM.zip

**Comment by Anish-Agnihotri** [comment]
Might be missing something, but there doesn't seem to be a grants-white.svg included in those assets. Do you want me to just use the grants-black.gif as the default (non-hover) image instead?

**Comment by Anish-Agnihotri** [comment]
Quick and dirty way to do this can be done via: 

```
{% if request.path == '/ios' %}
      <a class="navbar-brand pt-0 pb-0" href="/">
        <img id="logo" class="logo1" src="{% static "v2/images/ios/gitcoin.svg" %}" data-hover="{% static "v2/images/ios/gitcoin_hover.gif" %}" height="50" />
      </a>
      <style>
        .logo2 {
          display: none;
        }
      </style>
    {% else %}
      <a class="navbar-brand pt-0 pb-0" href="/">
        <img id="logo" class="logo1" src="{% static "v2/images/logo_large.png" %}" data-hover="{% static "v2/images/logo_med_hover.gif" %}" width="150" height="50" />
      </a>
    {% endif %}
    {% if request.path|matches:"^\/((grants))" %}
      <a class="navbar-brand pt-0 pb-0" href="/grants">
        <img id="logo" class="logo2" src="{% static "v2/images/logo_large.png" %}" data-hover="{% static "v2/images/Grants-white.gif" %}" width="150" height="50" />
      </a>
      <style>
        .logo1 {
          display: none;
        }
      </style>

    {% endif %}
```

Where you essentially just make another if statement for the grants page, and hide the primary logo on the same page.

Should have a cleaner variant by EOD.

**Comment by owocki** [comment]
`grants-white.svg` logo should already be in the codebase on the grants branch i believe.

**Comment by Anish-Agnihotri** [comment]
I might be looking in the wrong place but I don't see a `grants-white.svg` in `app/assets/v2/images` on the `grants` branch (live link [here](https://github.com/gitcoinco/web/tree/grants/app/assets/v2/images)).

**Comment by owocki** [comment]
it might be named something else... @PixelantDesign @captnseagraves do you know or do you have a copy?

**Comment by captnseagraves** [comment]
I do not know where that .svg file lives :(

**Comment by Anish-Agnihotri** [comment]
Ah shoot.

If @PixelantDesign doesn't have the source file for it, worst-case scenario - I'm sure I could make an SVG out of the first frame of the GIF.

**Comment by owocki** [comment]
@Anish-Agnihotri here it is!  https://github.com/gitcoinco/creative/tree/master/Brand/Grants

courtesy of @PixelantDesign ?

**Comment by PixelantDesign** [comment]
Let's try the icon in the center spinning/rotating, and also spinning the N on grants, similar to the treatments on the Gitcoin logo.

**Comment by thelostone-mc** [comment]
@Anish-Agnihotri are you still on this ?

**Comment by Anish-Agnihotri** [comment]
Hey, sorry, didn’t complete this since I was working on other issues. It should only take 10-15 minutes so I’ll push today.
