### ISSUE TITLE
Explore UX Bounty Syncing with the Blockchain

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2403]
When funding an issue, sometimes the bounty doesn't properly sync on the blockchain but the etherscan transactions goes through.

There are a number of possible ideas floating around:

1) [Add a sync with blockchain button.](https://github.com/gitcoinco/web/issues/2403)
2) On page load - auto sync for the user, and display a message to set expectation that the page is resending with the blockchain and how long it would take.
3) Other ideas to solve for this.

This is a [related issue ](https://github.com/gitcoinco/web/issues/2394)that will help solve the problem.

### Definition of Done

- [ ] Explore some ideas and propose the best solution.
- [ ] Get feedback from users

**Comment by willsputra** [comment]
In addition to 'Sync with blockchain' button, I wonder if a 'Last sync: [timestamp]' text would help? At least the user knows that it wasn't syncing instantly.

**Comment by willsputra** [comment]
@PixelantDesign @owocki thoughts?

![2a](https://user-images.githubusercontent.com/19514207/48426556-fe7a9f00-e7a1-11e8-8cea-88ebaf3a96d2.png)
![2b](https://user-images.githubusercontent.com/19514207/48426557-fe7a9f00-e7a1-11e8-8078-23f3aa3f52ed.png)

Another alternative is also to show the last sync timestamp.

![1a](https://user-images.githubusercontent.com/19514207/48426621-1d793100-e7a2-11e8-8873-cd962989fc43.png)
![1b](https://user-images.githubusercontent.com/19514207/48426622-1d793100-e7a2-11e8-9fe5-47c2a744bfa0.png)

**Comment by thelostone-mc** [comment]
I like the second alternative

**Comment by willsputra** [comment]
@thelostone-mc @owocki thanks! guess we're going with these:

Issue Explorer
![1a](https://user-images.githubusercontent.com/19514207/48566510-ef2c5a80-e935-11e8-9cd8-4fd48d98bdda.png)

Issue Detail
![1b](https://user-images.githubusercontent.com/19514207/48566509-ee93c400-e935-11e8-8ce1-194fc7934d17.png)

I'll create two build tickets for these.
