### ISSUE TITLE
UI: Unaligned buttons on bounty page

### ISSUE THREAD

**Issue by anshumanv** [gitcoinco/web#2406]
**Describe the bug**
The buttons don't seem to be aligned horizontally, I'm not sure if this is intentional, please close this ticket in case it is.

**To Reproduce**
Visit - https://gitcoin.co/issue/aragon/aragon-cli/135/1266

**Expected behavior**
Buttons to be aligned horizontally

**Screenshots**
![gc_buttons](https://user-images.githubusercontent.com/21009455/46728549-b4813380-cca0-11e8-8cf0-e0935dc79736.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Firefox
- Browser Version  62.0.3

I'm wiling to work on it if it turns out to be a legit issue.

**Comment by anshumanv** [comment]
cc @owocki @vs77bb @PixelantDesign

**Comment by vs77bb** [comment]
@PixelantDesign @thelostone-mc Is this the intention?

**Comment by vs77bb** [comment]
Thanks @evgeniuz!
