### ISSUE TITLE
Increasing Funding Not Working

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2407]
**P2 - Medium**
A feature of Gitcoin fails to follow expected behavior. The issue is not high magnitude.
Timeline to fix: 5-7 days

**Describe the bug**
Tried to crowdfund this issue:
https://gitcoin.co/issue/gitcoinco/web/2404/1415

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

1. Try to crowdfund/contribute to any issue.
2. Select Fund this Bounty
3. Try to fund - does not work.

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

![increase funding issue](https://user-images.githubusercontent.com/238235/46737779-66e9d400-cc6a-11e8-8091-4d09dceb9240.gif)

<img width="558" alt="screen shot 2018-10-10 at 8 55 29 am" src="https://user-images.githubusercontent.com/238235/46737762-5cc7d580-cc6a-11e8-9607-c277b9280c22.png">

**Desktop (please complete the following information):**

- OS: High Sierra 10.13.6
- Browser Chrome Version 69.0.3497.100 (Official Build

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by owocki** [comment]
are you getting any JS errors?

**Comment by owocki** [comment]
<img width="1405" alt="screen shot 2018-10-10 at 11 26 02 am" src="https://user-images.githubusercontent.com/513929/46751523-12e5ec00-cc78-11e8-85c2-36b9a50e29fc.png">

**Comment by owocki** [comment]
@vs77bb a9c8d62a32623cb46e28f94ccccc5b9073233326 fixes this.. try now (er... in 3 minutes when the deploy is done)

**Comment by vs77bb** [comment]
@owocki it worked! I did get a funny 2nd tx confirmation which a) had the 12500000 DAI thing (i know that's a 🦊 bug) but also b) defaulted to asking me for a $15 gas fee. 

I manually reduced the gas to ~$1.72 fee, and it still went through... which makes me think the default was artificially really high.
