### ISSUE TITLE
Bug Priority Guide

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2408]
## **Gitcoin Bug Priority Guide**

**P0 - Critical**
This issue puts funds at risk for either a) Gitcoin funders or b) Gitcoin developers.
Timeline to fix: 24-48 hours

**P1 - High**
A feature of Gitcoin fails to follow expected behavior. The issue creates panic around a core feature on the Gitcoin platform.
Timeline to fix: 2-3 days

**P2 - Medium**
A feature of Gitcoin fails to follow expected behavior. The issue is not high magnitude.
Timeline to fix: 5-7 days

**P3 - Low**
Gitcoin’s platform is following expected behavior, but the expected behavior is resulting in sub-par user experience.
Timeline to fix: 1-7 days

**Comment by mbeacom** [comment]
Can we reevaluate the 24-48 hours for critical bugs? I'm not sure I would place much confidence in such a slow SLA for something that could potentially cause severe risk to users. 🤔

**Comment by PixelantDesign** [comment]
Yes, open to suggestions @mbeacom (feel free to update) but also want to be realistic on the time it might take to fix and issue and properly QA.

**Comment by mbeacom** [comment]
@PixelantDesign Definitely understandable.  I think it might be worth a discussion among the core team to establish SLO/SLAs around this.
