### ISSUE TITLE
remarket bounty button

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2420]
i would like to add a remarket bounty button to the bounty issue details page, visible only to a bounty funder.

when it is clicked, a user will be provided with a modal which will offer them the opportunity to pay 0.1 ETH to remarket their bounty to 11k users on our email list, but only the users on that email list that have opted in to a specific skillset.

**Comment by owocki** [comment]
or maybe pay us 0.001 ETH per person we can market it to.

**Comment by kuhnchris** [comment]
Did this ever get in? We do have a button "Ready for Remarketing" - is that the result out of this?
![image](https://user-images.githubusercontent.com/761911/63672122-84238480-c7e1-11e9-942c-629d774ae32a.png)
