### ISSUE TITLE
Sync-geth functionality for grants

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2424]
### Description

We need to sync data from the blockchain to make sure our db is correct. Currently, we are storing information in the db upon receiving a tx receipt. This will change to a system using IPFS, more similar to bounties, in v2. More importantly, we definitely need to know when the desktop miner successfully submits transactions on behalf of users, so we can provide a transaction history to our users. 

*This is dependent on the subminer integration.* @owocki @mbeacom 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

This issue is done when we receive data from the blockchain about each transaction in a subscription.

**Comment by owocki** [comment]
started on this this weekend; Information I need to know in order to be able to do this:

1. which contract version is deployed to the mainnet?  i dont see it in the [smart contracts repo](https://github.com/gitcoinco/smart_contracts/pull/20).  pegged hash source code pls.  Is it [this](https://github.com/austintgriffith/tokensubscription.com/blob/master/Subscription/Subscription.sol)?  Is `master` branch the right version?  
2. where is it deployed / where are the addresses for the deployed `SubscriptionContract` stored in the DB?  is it `Grant.contract_address` ? 
3. [assuming this is the right contract](https://github.com/austintgriffith/tokensubscription.com/blob/master/Subscription/Subscription.sol), i will need a way of getting all of the subscriptions that have ever existed on the contract,

for each subscription, i need
```
        address from, //the subscriber
        address to, //the publisher
        address tokenAddress, //the token address paid to the publisher
        uint256 tokenAmount, //the token amount paid to the publisher
        uint256 periodSeconds, //the period in seconds between payments
        uint256 gasPrice, //the amount of tokens or eth to pay relayer (0 for free)
        uint256 nonce, //to allow multiple subscriptions with the same parameters
        bytes signature //proof the subscriber signed the meta trasaction
```
4. a. is there any test contract data deployed on either mainnet or rinkeby that i can sync?  if so, do we have the above data available for it?

@captnseagraves @mbeacom

**Comment by captnseagraves** [comment]
@owocki 

1. We have not deployed to mainnet yet. 

2. When contract are deployed, regardless of network, the address is stored in `Grant.contract_address`

3. Each `Subscription` is related to the grant in the db and you should be able to querry all subs to a grant. All of the data you need is stored between `Grant` and `Subscription` except for `nonce`, which won't be a hard add if needed. I can give a 1-1 relation of names if needed as well. 

4. We do not yet have a test contract deployed on any testnet beyond ganache. 

What do you need from me next?  Working with @mark to get the subminer integration across the finish line.

**Comment by captnseagraves** [comment]
> I thought Austin already deployed his contract to mainnet? I guess we can deploy our own down the line.
He has, but none of his contracts relate to any grants in our database. If you can begin working off of just his contracts, we should reach out and see what the addresses are. @austintgriffith

> If you don't mind, that'd be helpful.. Just so I know what I'm working with.

`from = Subscription.contributor_address,
to = Grant.admin_address,
tokenAddress = Subscription.token_address,
tokenAmount = Subscription.amount_per_period,
periodSeconds = *Needs to be implemented for Subscriptions.* - is currently hardcoded within grants,
gasPrice = Subscription.gas_price,
nonce = *Needs to be saved during tx submission*,
signature = Subscription.contributor_signature`

> OK, once I learn what smart contract and what version we are using, I can deploy it to rinkeby and we can work off that.

This contract https://github.com/gitcoinco/grants1337/blob/master/Subscription/Subscription.sol at this commit hash `9e62a36f5a6fb8d82df0dfa44bb5a7425125a5d8` should be a good place to start.

**Comment by captnseagraves** [comment]
Although, on second thought, I dont know that `nonce` will be able to be saved for 
 each `Subscription`. That should live in each `Contribution` as it will change each time.

**Comment by austintgriffith** [comment]
The mainnet contract is live, public, audited, and completely unused so far :/ https://etherscan.io/address/0x9123a4b90E3a1F468102C08ee78fa2224d88F496

**Comment by captnseagraves** [comment]
@austintgriffith I am planning to put a bug bounty on the `Subscription` contract a little later today.  I know it's been audited, but I think a bounty is a _relatively_ cheap action with high upside and in general a good practice. Just FYI!

**Comment by owocki** [comment]
thank you @captnseagraves @austintgriffith this is exactly what i need.

@mbeacom when u get a chance,  would love to sync with you on this.. pasting from slack:

> @mark got a spec or sketch of how you want to architect it [the txminer]? knowing that its gonna live in the repo i wanna make sure what i do zigs where your stuff zags

**Comment by owocki** [comment]
> @owocki does this provide the information you need? I will work on implementing the needed data fields in grants/models.py

one last question:  @captnseagraves @mbeacom  what branch should i work off of? `grants`?  or is there a sub-branch with the latest & greatest DB model on it?

**Comment by captnseagraves** [comment]
@owocki If you could create a sub-branch or fork and submit a PR to `grants` that would be ideal. `Master` should have the most up to date model. I will submit the updates soon.

**Comment by owocki** [comment]
@captnseagraves i thought `master` didnt have any grants stuff in it... am i missing something?

so sounds like I should use the `grants` branch?

**Comment by owocki** [comment]
@mbeacom mind pointing me to the latest subminer implementation?  just want to make sure i have it handy for coding this in-air on the way to london

**Comment by owocki** [comment]
hi from the airport ✈️ !

updates: 
- i founder the [subminer implementation](https://github.com/gitcoinco/web/blob/grants-listener/app/grants/management/commands/sub_listener.py).
- initial design pass:

from looking at [the smart contract](https://github.com/gitcoinco/grants1337/blob/master/Subscription/Subscription.sol), i'm just not seeing a lot of information to sync from the blockchain back to the DB.

here are my initial design notes:

```
*public fields* to sync from blockchain to DB, directly from the contract, which are created in the constructor:

        requiredToAddress=_toAddress;
        requiredTokenAddress=_tokenAddress;
        requiredTokenAmount=_tokenAmount;
        requiredPeriodSeconds=_periodSeconds;
        requiredGasPrice=_gasPrice;
        author=msg.sender;

unless these are already on in the DB from the initial contract deploy.

here is dynamic data that updates continually, which i can sync:

getSubscriptionHash() -> store Hash in `Subscription` table in `hash` field
getisSubscriptionReady() -> store bool in `Subscription` table in `ready` field

*events* to sync from the blockchain to the DB:

    event ExecuteSubscription(
        address indexed from, //the subscriber
        address indexed to, //the publisher
        address tokenAddress, //the token address paid to the publisher
        uint256 tokenAmount, //the token amount paid to the publisher
        uint256 periodSeconds, //the period in seconds between payments
        uint256 gasPrice //the amount of tokens to pay relayer (0 for free)
    );

which should probably go to the `Contribution` table (though I dont see all of the fields they should go in.... many of them live upstream on the subscription.


```


@captnseagraves @mbeacom 
1. am i thinking about this in a directionally correct way?
2. @mbeacom anything i need to know about how the subminer works and overlap for this?  

from here, i think this should be pretty simple to code up.

**Comment by captnseagraves** [comment]
@owocki seems like you are in the right direction. The data that is given to the constructor is partially saved in creation, but we should be have it all saved. The listening for the ‘executeSubscription’ event is the most crucial piece and should be stored in Contribution. I will try and implement any needed fields on the plane today. 

We should also store any events emitted on cancelSubscription. Or at least use this event to trigger the cancelation on our end.

**Comment by owocki** [comment]
> We should also store any events emitted on cancelSubscription. Or at least use this event to trigger the cancelation on our end.

https://github.com/gitcoinco/grants1337/blob/master/Subscription/Subscription.sol#L55

@austintgriffith i dont see any events emittted upon `cancelSubscriptoins`.  do we want to add this as an event?

**Comment by austintgriffith** [comment]
Yes that's probably a good idea. I'll add that into my contract now.

**Comment by austintgriffith** [comment]
https://github.com/EthereumOpenSubscriptions/reference-client/blob/master/Subscription/Subscription.sol#L220

**Comment by owocki** [comment]
per convo yesterday on the call, @mbeacom is gonna build this into the subminer

**Comment by captnseagraves** [comment]
@owocki `real_period_seconds` in the Subscription model is the value you are looking. 

The `nonce` is stored in the Contribution model. It is not being saved yet, as all values in the Contribution model need to be populated by the `subminer` or by `sync_geth`. This can be found by calling `deployedSubscription.methods.extraNonce(accounts[0]).call(function(err, nonce)`. However, it may not actually be necessary as I have found that it introduces a bug around `approve()` and the cancelation of subscriptions. Let's use for it now, to support the code that it currently written and we can refactor at a later point. This is the approach that Austin and I have taken with the smart contract.

**Comment by owocki** [comment]
> This contract https://github.com/gitcoinco/grants1337/blob/master/Subscription/Subscription.sol at this commit hash 9e62a36f5a6fb8d82df0dfa44bb5a7425125a5d8 should be a good place to start.

hey @captnseagraves is there a new contract? i know we've made some changes WRT to contract versioning at the very least
