### ISSUE TITLE
Gitcoin Bot Not Showing All Workers That Have Applied

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2425]
**P2 - Medium**
A feature of Gitcoin fails to follow expected behavior. The issue is not high magnitude.
Timeline to fix: 5-7 days

**Describe the bug**
Gitcoin Bot Not Showing All Workers That Have Applied

**To Reproduce**
https://gitcoin.co/issue/trailofbits/not-so-smart-contracts/23/1446

<img width="962" alt="screen shot 2018-10-11 at 10 36 45 pm" src="https://user-images.githubusercontent.com/238235/46844691-2b542480-cda6-11e8-92cb-1b2a212469ec.png">

only showing 1 worker applied on GitHub
<img width="865" alt="screen shot 2018-10-11 at 10 37 20 pm" src="https://user-images.githubusercontent.com/238235/46844725-47f05c80-cda6-11e8-80ae-06685a2355d6.png">

**Additional Examples**
* https://gitcoin.co/issue/aragon/aragon-cli/99/1572 (Gitcoin Bot not consistent with Issue Details All Activity section)
* https://gitcoin.co/issue/oceanprotocol/ocean-bounties/3/1500 (Gitcoin Bot not consistent with Issue Details All Activity section)
* https://gitcoin.co/issue/ethereum/py_ecc/11/1532 (a worker starts work but Gitcoin Bot never reported that they applied, Issue Details All Activity section similarly did not report earlier workers who applied)
* https://gitcoin.co/issue/ethereum/py_ecc/11/1531 (All activity on Gitcoin shows multiple workers applied and approved, but only the earliest one shows up on the Github issue via Gitcoin bot.)
* https://gitcoin.co/issue/ethberlin-hackathon/ETHBerlin-Bounties/20/1176 (Gitcoin Bot completely unresponsive)

**Expected behavior**
Gitcoin Bot should be in sync with Gitcoin Issue Details

**Comment by thelostone-mc** [comment]
@PixelantDesign does this still happen ?

**Comment by pinkiebell** [comment]
@thelostone-mc 
Another one [https://github.com/trailofbits/slither/issues/24].
I will take a look today 👍

**Comment by pinkiebell** [comment]
@thelostone-mc 
Another one [https://github.com/trailofbits/slither/issues/24].
I will take a look today 👍

**Comment by pinkiebell** [comment]
Seems like we need a task queue to re-schedule such things as we don't handle api errors.
cc @mbeacom

**Comment by PixelantDesign** [comment]
Yes! @thelostone-mc this still happens. @vs77bb @ceresstation reported it the other day as well.

**Comment by frankchen07** [comment]
added additional examples that I found as well.

**Comment by kuhnchris** [comment]
is this still an issue to this day?
