### ISSUE TITLE
Display Issue Count and Bounty Values at the Issue Explorer

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2426]
Display Issue Count and Bounty Values at the Issue Explorer

**Comment by PixelantDesign** [comment]
looks nice! Where do you think is a good place for this on the issue explorer?

cc @willsputra

**Comment by Anish-Agnihotri** [comment]
I'd be open to input since I'm not exactly the best at UX, but I believe there could be some place where you integrate this directly into the new Issue Explorer layout possibly?

**Comment by frankchen07** [comment]
haha this is cute - and easy pickings in a marketing sense.

**Comment by willsputra** [comment]
One place I could think of is here... thoughts?

![displaycount](https://user-images.githubusercontent.com/19514207/47738419-0f111c80-dcae-11e8-8a16-26d324e1f70c.png)

@PixelantDesign if the purpose of this is to entice contributors, maybe we could also add more enticing stats like: X projects hiring, contributors are usually paid within X days, etc... just an idea.

**Comment by Anish-Agnihotri** [comment]
@willsputra 

You just took my idea to a whole new level! That looks incredible.

I could certainly see this being a great way to do it, especially with its intrusive nature (being close-able).

**Comment by kuhnchris** [comment]
should we create a build ticket for that @PixelantDesign ?
