### ISSUE TITLE
Umbrella Issue for Autumn Sweep

### ISSUE THREAD

**Issue by pinkiebell** [gitcoinco/web#2429]
### What 
This issue is here to keep track of all pull requests for the upcoming autumn sweep.
Autumn sweep basically means code cleanup and refactoring, unifying backend & frontend code and templates. 

### Why
Winter is coming!

**Comment by mbeacom** [comment]
I think it makes sense for us to track these in a project/milestone versus a running list in an issue that'll need constantly updated.

Also, the core team is planning for a lot of refractor and cleanup following devcon (November/December).

**Comment by pinkiebell** [comment]
@mbeacom 
Nice to know. I planned some refactoring in the coming days/weeks.
Should I wait or coordinate via Slack?
