### ISSUE TITLE
Implement "Transaction Summary" Email Frontend

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2431]
### User Story

As a Grant Creator, I want a summary of all transactions on days that I receive funding so that I know when I have funds to allocate toward my project. 

### Why Is this Needed

The "Transaction Summary" Email is needed so that grant creators know when they receive funding and how much funding they have received. If they have not received funding on a given day, they will not receive this email. If they receive multiple contributions on a given day they will only receive this one summary email. 

### Description

*Type*: Feature

### Definition of Done

[ ] Email implements designs at https://github.com/gitcoinco/web/issues/2206
[ ] Email uses the base.html file found at gitcoinco/web/app/retail/templates/base.html
[ ] Email should display a summary of all funds received to this point
[ ] Email should display all transactions that happened within the previous 24 hours and the values of each transaction
[ ] Email should have a button link to the grant admin page
[ ] Email should have copy similar to:

 " 'Project X' has received more funding!"

### Additional Information

To be reviewed with @PixelantDesign @owocki @captnseagraves

Examples of previous email implementatoin work can be found here: https://github.com/gitcoinco/web/pull/2331

More information about the Dev Grants project can be found here: https://github.com/gitcoinco/web/issues/1469

Please allow the core team a few rounds of revisions.

**Comment by captnseagraves** [comment]
@Anish-Agnihotri This is another email issue. Are you interested in taking this one on? Just checking in before looking for someone else.

**Comment by Anish-Agnihotri** [comment]
@captnseagraves For sure, I'd be glad to pick this up!

**Comment by captnseagraves** [comment]
@Anish-Agnihotri Fantastic! Thanks!

**Comment by kuhnchris** [comment]
Since the connected PR is closed I'll close this issue aswell.
