### ISSUE TITLE
Rewrite Copy on grants/index to reflect EIP1337 and hyping Grants

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2434]
### User Story

As a user I want to know about EIP1337 and get hyped on Grants so that I create and contribute to OSS project  grants

**Comment by owocki** [comment]
can you let me know where on the idex page this will go and about how long it should be?

**Comment by captnseagraves** [comment]
You a replacing this copy below. And it should be 2-3 sentences. 
![screen shot 2018-10-12 at 4 31 05 pm](https://user-images.githubusercontent.com/22862292/46896777-4a9d9100-ce3c-11e8-9393-9a2309d91a6a.png)

**Comment by owocki** [comment]
Copy rough draft:

> Want to provide sustainable funding for Open Source?  Creating a Gitcoin Dev Grant is a great way to do it!  Dev Grants, [powered by the EIP 1337 standard](http://1337alliance.com), are a fast, easy, & secure way to provide recurring token contributions to your favorite OSS maintainers.  Show your appreciation for maintainers in your dependancy tree with a Gitcoin Dev Grant today.


cc @PixelantDesign @vs77bb for feedback:

**Comment by captnseagraves** [comment]
I think we should remove the references to "Dev" grants

**Comment by owocki** [comment]
makes sense to me. updated
