### ISSUE TITLE
Banner image on grants/detail should be grant logo

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2437]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a grant creator, I want to see my grant logo on my grants detail page so that I can portray my project well and attracts contributors.

**Comment by mbeacom** [comment]
I already linked this up.

**Comment by thelostone-mc** [comment]
This works only if we ensure they upload a high res image else the page will look pretty shitty. Should we add a placeholder in the create grant form ?

**Comment by captnseagraves** [comment]
@thelostone-mc Yes, we should have a placeholder. I think the Penguins building rockets is a good image. It should already be the placeholder in the project. 

@mbeacom and I also discussed having a border on each side of the image in order to make poor images look better and fit into the window.
