### ISSUE TITLE
Progress bar on grants/detail should be dynamic based on funding received

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2438]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a grant supporter, I want the funding progress bar to display the current funds received accurately so I have a visual way to see how well the grant is doing and if I should contribute.

**Comment by thelostone-mc** [comment]
@captnseagraves Isn't this already done ? If so , can we close it out ?
