### ISSUE TITLE
Write copy on grants/new about creating grant and setting requirements of Subscription Contract

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2440]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a grant creator, I want concise copy that informs me about what I am doing on the page so I have the needed information and right expectations as I create and deploy a grant.

**Comment by owocki** [comment]
it'd help me when writing this copy to know (1) where it will live exactly (2) how long it should be .

**Comment by owocki** [comment]
Copy rough draft:

> Want to provide sustainable funding for Open Source?  Creating a Gitcoin Dev Grant is a great way to do it!  Dev Grants, [powered by the EIP 1337 standard](http://1337alliance.com), are a fast, easy, & secure way to provide recurring token contributions to your favorite OSS maintainers.  Show your appreciation for maintainers in your dependancy tree with a Gitcoin Dev Grant today.

> When you submit a new grant to Gitcoin, you're deploying a [EIP 1337 contract](http://1337alliance.com) to the blockchain, which others will be able to trustlessly contribute to. Got a question about EIP 1337?  [Checkout the working group on Github](https://github.com/EthereumOpenSubscriptions).  

> By creating a Gitcoin Grant, you're one step closer to sustainable funding for your project.  Thanks for being 1337!

> ~ [Gitcoin Core Team](mailto:founders@gitcoin.co]



cc @PixelantDesign @vs77bb for feedback:

**Comment by captnseagraves** [comment]
@owocki An important point to make in this copy is that as users create a grant they are setting requirements on the contract. E.g. By choosing DAI in the token drop down menu you are requiring users to contribute in DAI. If you choose "any" in the drop down users can contribute in any ERC20 token. 

Would you like me to take a stab at working this idea into the copy?

**Comment by owocki** [comment]
sure!
