### ISSUE TITLE
standardbounties: tx throws but the frontend thinks it succeeded anyway

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#246]
https://github.com/gitcoinco/web/pull/140#issuecomment-357752233

**Comment by jasonrhaas** [comment]
For reference

>i think we need to apply an .estimateGas() to the submission code on line 119 in fulfill_bounty.js

also, this tx 'throw()'ed and the frontend thought that it succeeded and updated the bounty anyway.

https://rinkeby.etherscan.io/tx/0x1a546bd7296113658b91d5b3badeb98cb11487fe9891eab3726a4c873117bb12

**Comment by jasonrhaas** [comment]
Right, I need to put the switch back in there to wait until the TX is confirmed before doing anything, fixing it.

Does bring up a broader point (not for this issue) about how we want to handle the "data in two places thing".  Bounties Network only uses the Blockchain as their database, we are using Postgres and the blockchain and IPFS.  There are certainly tradeoffs using either approach.  If we want to go all in with Standard Bounties we should _probably_ eventually ditch the Postgres database and just use IPFS for everything.  However, the blockchain is pretty slow.  Using the bounties factory application is pretty frustrating in terms of performance.

**Comment by owocki** [comment]
> Right, I need to put the switch back in there to wait until the TX is confirmed before doing anything, fixing it.

+1 on this ... this is a good resolution

**Comment by owocki** [comment]
@jasonrhaas are you doing this? if not, i may take a stab tonight

**Comment by jasonrhaas** [comment]
@owocki This is fixed.  Everything is going through the blockchain first, and then syncing to the database.
