### ISSUE TITLE
Broken typography CSS link in StyleGuide

### ISSUE THREAD

**Issue by davidkaufman** [gitcoinco/web#2460]
## Description of Bug
The link to the ```typography.css```  file on the StyleGuide page of the 	
Gitcoin Developer Documentation at https://docs.gitcoin.co/mk_styleguide/ leads to a 404 Not Found error

## Steps to Reproduce
1. Visit https://docs.gitcoin.co/mk_styleguide/
2. Click on the link to [typography.css](https://docs.gitcoin.co/app/assets/v2/css/typography.css) (which points to the URL https://docs.gitcoin.co/app/assets/v2/css/typography.css)

## Current behavior
The browser displays the dreaded 404 Not Found error page
> 404 Not Found
<img src="https://user-images.githubusercontent.com/2336122/46912575-1d89d500-cf47-11e8-825b-b9cfa37bfa4d.png" width="500">

## Expected behavior
It would be nice if the browser displayed the contents of the typography.css file or, even better, the file as represented in all its syntax-highlighted and version controlled goodness on GitHub, i.e. here: 
> https://github.com/gitcoinco/web/blob/master/app/assets/v2/css/lib/typography.css
<img src="https://user-images.githubusercontent.com/2336122/46912583-53c75480-cf47-11e8-8614-b48daf241dc7.png" width="500">

**Comment by mbeacom** [comment]
Nice catch! Thanks!
