### ISSUE TITLE
As a closed source funder, I want to post Screening Bounties, so I can still leverage Gitcoin's torrent of interested dev talent.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2462]
# Slack Context
```
My convo with him does give me an idea though. Why not have “screening bounties” which are just toy problems for the purposes of hiring, but have funders pay for people to screen with them. Its a sourcing mechanism for them to do a new kind of interviewing and hiring where you build trust via the bounty you work on together.

Pixelant [6:01 AM]
Hmmm...we have talked about supporting closed source.

Anything we can do to make hiring easier is always a good idea.

So a bank of problems that funders can select from and bounty to candidates...(if you want to hire for x skill, use y question in order to learn z) and leverage the community to review them?

In terms of reviewing, I would trust my internal team to review. But if they didn’t have the bandwidth I might use the bounty. My internal team member probably understands what i’m looking for more than a community member and having my team member be the liason - i’d get a better sense of the how the candidate thinks based on the types of questions that is asked.

Like the general concept though.

Owocki [11:08 AM]
> So a bank of problems that funders can select from and bounty to candidates...(if you want to hire for x skill, use y question in order to learn z) and leverage the community to review them?

yas.  probably you’d use your internal team to review them though.. as you noted below.
```

# What 

- An option in project type in post bounties that is 'screening bounties'.  
- User is given preselected options of different screening bounty types (e.g. FizzBuzz, multi player Tic Tac Toe game, A* search, data analysis, etc)
- Screening bounties must have a job description on them.
- Bounty is posted as a 'contest' type, where many ppl can submit.

**Comment by spiegeleixxl** [comment]
How about alternatively something like a "verified skill badge"? Kind of like the mTurk thing where people qualify with certain "bounties" to gain skill badges, and hide bounties that require a certain skill badge to work at. 
A skill badge could be anything from trust to a specific verified skill (javascript for example), or even a technology itself (django, node, ...). It would only make sense if it has a common base tho, else it will end up like mTurk where you have to take tests for every single minure thing and only have tasks left like "tag this picture" or "copy and google data for X"...

Just my 0.0002ETH.
-Chris
