### ISSUE TITLE
Advanced Payout Needs To Close Issue

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#2463]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
A bounty paid out via Advanced Payout is not closing the issues into a 'Work Done' state, as it should. It simply records the payouts as a `New Tip`, as opposed to calling it `Work Done`. 

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
See the following two issues. 

https://gitcoin.co/issue/ethereum/solidity/4066/891
https://gitcoin.co/issue/blockchain-etl/ethereum-etl/102/1390

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
When a bounty is paid out via Advanced Payout, the bounty state should change to `Work Done` and new tips should be created to pay out all the bounty hunters.

Ideally, these would not even be listed as a 'New Tip' by the funder, but would simply state 'Work Done' for each of the recipients of an Advanced Payout. 

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
<img width="992" alt="screen shot 2018-10-14 at 2 59 03 pm" src="https://user-images.githubusercontent.com/23297747/46920813-b5c4a000-cfc1-11e8-8730-518aa1a2971e.png">

**Additional context**
Review with @PixelantDesign @owocki

**Comment by owocki** [comment]
i think the solution here is probably to re - add the 'close this bounty' checkbox to this page but to make it like 10x more clear to the user what that checkbox does.

cc @ceresstation who prolly has some thoughts here too

**Comment by ghettodev** [comment]
This flow is pretty confusing. I escrowed 2000 Dai into the bounty, but paying out 666.66 Dai to 3 winners with the Advanced Payout causes it to be drawn it from my local wallet. It looks like using Tips here isn't just a semantics issue, they are handled outside the bounty flow.

In this model I have to cancel the bounty to get the funds returned to me. i.e. I need source double the amount of the total bounties for a hackathon. That can be tricky to explain to an accounting team...

**Comment by ceresstation** [comment]
Hey @owocki @vs77bb any updates that I can provide to some of the funders experiencing this issue?

**Comment by owocki** [comment]
@ceresstation checkout slack => https://gitcoincore.slack.com/archives/CAW05FUD7/p1540300113000100

**Comment by PixelantDesign** [comment]
Closing this since we are tracking on a different ticket.
