### ISSUE TITLE
standardbounties: gas limit set too high

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#247]
i get a 'gas limit set dangerously high' message when i try to fulfill a bounty..

http://bits.owocki.com/3A2t0R3j3m3D/Screen%20Shot%202018-01-15%20at%2010.52.57%20AM.png

i think we need to apply an .estimateGas() to the submission code on line 119 in fulfill_bounty.js

and probably for all other web3 interactions too..

**Comment by jasonrhaas** [comment]
I took our that part based letting MetaMask handle all that.  So the idea behind the `estimateGas()` call is that it will do a better job at estimating the gas than MetaMask?  Yea it would be nice if users didn't have to deal with worrying about all the gas stuff.

**Comment by owocki** [comment]
> I took our that part based letting MetaMask handle all that. 

I'm not sure what this means

> So the idea behind the estimateGas() call is that it will do a better job at estimating the gas than MetaMask? Yea it would be nice if users didn't have to deal with worrying about all the gas stuff.

Yes

**Comment by owocki** [comment]
@mbeylin if we don't call `.estimateGas()` then how will we know if the tx we're about to submit to the network is gonna `throw()`?

**Comment by mbeylin** [comment]
In the Bounties Network, the front-end doesn't currently check for this (does Gitcoin?)

In the UI I disable the ability to make actions I know will cause throwing (i.e. checking if the metamask provided account[0] is the same as the bounty issuer, to ensure it doesn't let them fulfill).

In this way the UI proactively prevents it, instead of letting them try and then failing when they hit the button.

**Comment by owocki** [comment]
i think the fix here is to copy what beylin did:  catch it upstream to the 'fulfill' button click

**Comment by owocki** [comment]
i think we can close this now.. metamask seems to now include some copy about this when the tx is likely to fail http://bits.owocki.com/0y0P3e0U3R1h/Screen%20Shot%202018-01-22%20at%202.36.53%20PM.png
