### ISSUE TITLE
bug - avatar is out of place on the backend generated svg

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2472]
frontend :
<img width="273" alt="screen shot 2018-10-15 at 11 21 45 am" src="https://user-images.githubusercontent.com/513929/46969965-9040a080-d06c-11e8-8a50-28bced4a1be1.png">

backend generated svg:

<img width="526" alt="screen shot 2018-10-15 at 11 21 30 am" src="https://user-images.githubusercontent.com/513929/46969966-9040a080-d06c-11e8-97ad-8fff04fb4141.png">

**Comment by owocki** [comment]
note to self: try this with the template that Damo posted here => https://github.com/gitcoinco/web/pull/2433#issuecomment-431397454

**Comment by thelostone-mc** [comment]
@owocki is this still happening / taken care of ?

**Comment by owocki** [comment]
@thelostone-mc yes its still happening.

@Dgilliams was nice enough to post some templates i could use to fix this... but i havent gotten to it.. links below

	https://github.com/gitcoinco/web/pull/2433#issuecomment-431397454
	https://github.com/gitcoinco/web/pull/2433/commits/8f25b6617a200ae59c8cbdfc4c29a95670d4382f#diff-3bbb5f9ab4121afb20e7cf559419b5f6

**Comment by owocki** [comment]
for posterity.. here is an artboard that can be used to fix this in the future => http://bits.owocki.com/966d6b977c53/Gitcoin-Artboard%20mk2.sketch

**Comment by owocki** [comment]
hmmm nevermind, i thought this would work but it didnt https://c.gitcoin.co/avatars/d62d38e7c4bee5b4df471e7003433297/owocki.svg
