### ISSUE TITLE
Request a Bounty Comment box, spontaneously jumping text cursor

### ISSUE THREAD

**Issue by Dgilliams** [gitcoinco/web#2481]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
As I was filling out a comment for a Request a Bounty, I found if needed to make an edit to already typed text that the cursor would jump to the bottom of the text box. 

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
- Write a detailed comment. 
- Decide that what you wrote wasn't good enough
- Use mouse to click somewhere in your text, begin typing to add a word
- Cursor may jump to the very last character in the text field
  - If not, try again on a different line. I experienced this sporadically. 

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Click somewhere to edit and the cursor stays there allowing you to edit.

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by kuhnchris** [comment]
Nowadays we're locked on github issues and that box is grayed out, i think?
