### ISSUE TITLE
bug - gitcoinbot double posting

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2488]
<img width="782" alt="screen shot 2018-10-18 at 9 39 39 am" src="https://user-images.githubusercontent.com/513929/47169984-cc1c7580-d2b9-11e8-9f89-a3a468618847.png">

https://github.com/ConsenSys/smart-contract-best-practices/issues/172#issuecomment-430474467

**Comment by owocki** [comment]
probably related to https://github.com/gitcoinco/web/issues/2394

**Comment by owocki** [comment]
i wonder if we, as a stopgap, could put some sort of semaphor on top of the `sync_bounty()` so that two threads cant sync_bounties at the same time...

maybe we could use redis to do this!

**Comment by owocki** [comment]
new pr https://github.com/gitcoinco/web/pull/2725

**Comment by abitrolly** [comment]
Double posting again

https://github.com/harmony-one/harmony/issues/390#issuecomment-466670257
https://github.com/harmony-one/harmony/issues/390#issuecomment-466670265

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/53329620-83c33300-38fd-11e9-88d0-1e92aac7abe9.png)

**Comment by kuhnchris** [comment]
Should be fixed at this point - if it keeps coming back please reopen a new issue so we can track it
