### ISSUE TITLE
standardbounties: figure out how to massage expressed interest PR in 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#249]
we will need to figure out how to massage the 'express interest' functionality into this PR.. is it better if we create one integration branch and merge them all together? im thinking itd be nice if we can all be committing to the same branch and very quickly turning around any and all issues

**Comment by owocki** [comment]
hey @mbeacom i dont see the express interest code on the integration branch.. has it been merged in?

**Comment by mbeacom** [comment]
@owocki Yes, it has. 
<img width="723" alt="screenshot 2018-01-16 18 41 19" src="https://user-images.githubusercontent.com/7315957/35017888-01678c5c-faed-11e7-8866-201557d0599a.png">
https://github.com/gitcoinco/web/pull/240/commits/2228278f3c0b3a3f62b70ea5e36f9ce17aab5ebf

Just making the requested changes.
