### ISSUE TITLE
as a user, i want codefund ads to go up about my bounty if it's not turned around in 2 days, so i get more publiclity about my bounties

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2491]
# story
as a user, i want codefund ads to go up about my bounty if it's not turned around in 2 days, so i get more publiclity about my bounties

# what

if a bounty is not turned around within 2 days of being posted, there should be an alert to the gitcoin core slack notifying us that we should consider posting a codefund ad about it

**Comment by owocki** [comment]
@coderberry @PixelantDesign @vs77bb hows this look?  anything to "ad" (see what i did there? :P )

**Comment by wandhy79** [comment]
#969 Integrate Portis as a web3.js provider

**Comment by spiegeleixxl** [comment]
*badum dish*
![image](http://www.reactiongifs.com/r/daduntsh.gif)

You want this to be triggered from the web app itself, or do you want to have the slack-bot spider the bounties and alert by itself?

**Comment by owocki** [comment]
just sending alerts to myself and eric is fine for now!

**Comment by kuhnchris** [comment]
Did we... ever define that in more detail? Is it still something you need?
