### ISSUE TITLE
In certain instances, when a user starts a bounty, Gitcoin Bot reports a "cancelled" status for starting work. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2493]
**Describe the bug**
As a user who starts a bounty, Gitcoin Bot reports a "cancelled" status for starting work.

**To Reproduce**
Reproduction of the bug can be seen in the Github comments for the examples below:

1. https://github.com/MetaMask/metamask-extension/issues/4771

![screen shot 2018-10-14 at 23 15 56](https://user-images.githubusercontent.com/7516920/47199245-7d0c2a00-d325-11e8-86f6-80ca31d336c4.png)

2. https://github.com/bondibox/tchotchkebots/issues/1

![screen shot 2018-10-14 at 23 17 52](https://user-images.githubusercontent.com/7516920/47199250-85646500-d325-11e8-876e-29f0f58f2319.png)

3. https://github.com/MARKETProtocol/dApp/issues/260

![screen shot 2018-10-16 at 21 42 47](https://user-images.githubusercontent.com/7516920/47199252-8ac1af80-d325-11e8-81d2-13c19283922d.png)

**Expected behavior**
When a user starts work on a bounty, Gitcoin Bot should report a "started work" status. 

**Related tickets**

* https://github.com/gitcoinco/web/issues/1528 currently is WIP, and fixes this issue

**Comment by Anish-Agnihotri** [comment]
Hey, just dropping an update. Actually working on fixing this in a revised Gitcoin bot PR altogether at #1528.

**Comment by frankchen07** [comment]
@Anish-Agnihotri - thanks for the helpful update! I'll make a quick edit in the description to reflect the linked ticket.
