### ISSUE TITLE
bug - Unable to approve workers on certain issues

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2496]
**P1 - High
A feature of Gitcoin fails to follow expected behavior. The issue creates panic around a core feature on the Gitcoin platform.
Timeline to fix: 2-3 days**

**Description**

I’m not able to approve workers for the following issue:

https://gitcoin.co/issue/ethereum/py-evm/1398/1506

I get the error ```This worker does not exist or is not in a pending state.```

Note that there is a mismatch between workers shown on the Gitcoin issue and on GitHub, which might be related. In this case workers I'm trying to approve do not appear on the Gitcoin issue itself, only in the GitHub thread (in the standard format within the Gitcoin bot comment as shown below).

https://gyazo.com/06bcd9adcb10cd865e1b9921ea7ba8c3?token=0f7dfcf94d6cd526ced80de62d100005

**Comment by nasehim7** [comment]
Hey! I would like to take on this issue and fix it. Consider me as someone little new to the codebase but  a quick learner so yes - let's fix this thing. :D 
I checked that this error is coming from the function helper_handle_approvals(request, bounty) in views.py.

**Comment by kuhnchris** [comment]
@nasehim7 you ever came around to fix this?
