### ISSUE TITLE
Make Language filter UI clearer in Bounties

### ISSUE THREAD

**Issue by gkrizek** [gitcoinco/web#25]
I'm digging what I see on gitcoin.co!   One request would be to add a filter for language into the bounties. I would love to work on bounties for Python and Javascript, but I don't know anything about Ruby or Go so I don't even care about those. Would be sweet to just wipe those out.

Thanks!

**Comment by owocki** [comment]
does the search bar up top suffice for this functionality?


<img width="1088" alt="image 2017-10-02 at 10 53 08 am" src="https://user-images.githubusercontent.com/513929/31089031-e8b147c4-a75f-11e7-8b5b-a85736cf45eb.png">

**Comment by gkrizek** [comment]
@owocki  I guess it does. If I search for languages it does filter.

I just can't really tell if it's accurate or what I want. When I open an issue, I guess I would expect a `language` field under the *ISSUE FUND INFO* header.

I'm sure just using the search bar would work. It's just not intuitive is what I'm getting at. I wouldn't really know if that works or not and even then, the results don't indicate the language.

So I guess this is a feature request for adding in language values somewhere.

**Comment by owocki** [comment]
👍 good thoughts.  i may get more organized later this week and fund this issue.

**Comment by owocki** [comment]
@gkrizek i just added an autocomplmete for languages on gitcoin.co/explorer -- does that help at all?

**Comment by owocki** [comment]
word; im closing this issue now.. .but if anyone has ideas for a better language UI, i'm all 👂 s

**Comment by thelostone-mc** [comment]
Closing as this has been addressed ^_^
