### ISSUE TITLE
standardbounties: if you try to fulfill a bounty that doesnt exist it spins forever

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#250]
on https://stage.gitcoin.co/funding/fulfill

if i try to fulfill a bounty that does not exist (ex: https://github.com/gitcoinco/web/pull/140/files ) ... it just spins forever.. we should handle this and present the user with an error

**Comment by jasonrhaas** [comment]
![image](https://user-images.githubusercontent.com/7018237/35056505-ab2a4538-fb77-11e7-80b1-c51f501aacc6.png)

**Comment by jasonrhaas** [comment]
So now if the REST API returns nothing from the database it will pop up that error and Unload the button.

**Comment by owocki** [comment]
mind linking the commit for this?

**Comment by jasonrhaas** [comment]
https://github.com/gitcoinco/web/pull/240/commits/27d4a0917a40ad18d21b8eaae8db3f3208aceb89
