### ISSUE TITLE
standard bounties: multiple bounties per issue URL

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#251]
how do we want to handle multiple bounties per github issue URL?

right now, via the current stdbounties UI... someone can submit mulitiple bounties on the same GH URL. this is confusing because while standardbounties supports it.. the gitcoin UI does not..

maybe we add a validation step if someone tries to enter a currently active bounty into funding/new, we tell them they can't (or solicit them adding funds to the bounty instead?)..

**Comment by jasonrhaas** [comment]
Right now once an issue is in the fulfilled state in Gitcoin, it doesn't allow people to add another fulfillment via the bounty details page.  I believe this can be manually overridden by going to the /fulfill page directly.

![image](https://user-images.githubusercontent.com/7018237/35057126-999092e4-fb79-11e7-95c4-06341da37094.png)

Currently it adds the latest bounty to the stack on the Blockchain, and the "Acceptance" part just takes the latest one.  It's non ideal but I was trying to go for somewhat parity features at first.

We can display in the UI somewhere that the bounty has been fulfilled by "John Smith" or whatever.  I think with the Oauth stuff that was added we can pull the Github Email Address.

I think the best solution is to just display the multiple bounties that have been submitted right in the webpage.  This requires an update to the database schema though, so this would require a migration so we have to be careful about how we do it.

**Comment by owocki** [comment]
i wasn't talking about multiple fulfillments per bounty... i was talking about multiple *bounties* per github issue.

might be easier to just chat about this on the phone?

**Comment by jasonrhaas** [comment]
Ah yes, I read that wrong.  Correct, should be a check in there to kick back if the github issue already exists.  That should be an easy fix.

**Comment by jasonrhaas** [comment]
Ok so now before kicking off the process it checks that database to see if that issue is already in there.  If it is, it pops up a banner.  We can probably do more in the future but I believe this is feature parity for the moment.

![image](https://user-images.githubusercontent.com/7018237/35068339-5dbf08ea-fb9c-11e7-9000-79c7ca209767.png)

**Comment by jasonrhaas** [comment]
https://github.com/gitcoinco/web/pull/240/commits/a2cf8c5d194ee902caf4f3702e4915f238cb8ce0
