### ISSUE TITLE
EPIC Verified Image on my profile to prove legitimacy

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2510]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user whos done several bounties successfully, i'd like a 'verified' image on my profile, so ppl know i'm legit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

so that you can easily visually distinguish which users that you may potentially work with are legit

inspiration from twitter:
![twitter-verify](https://user-images.githubusercontent.com/513929/47306331-5a119c80-d5e9-11e8-8c6d-a2eda6b2cd7e.jpg)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no verification image
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
verification image

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

1. users can request to be verified
2. email is sent to an admin asking for verfification
3. admin can check a checkbox on the profile to verify them
4. verification image shows up in their profile image, and also on their profile

### Additional Information

Once released, metrics that would be interesting to track is cohorting contributors by "verified status" - and taking a look at a variety of bounty related metrics (median bounties completed, median bounty size, retention and engagement). Not necessarily an airtight A/B test case, but it can be interesting to see the difference between the two populations.

**Comment by owocki** [comment]
cc @PixelantDesign who brainstormed this with me in SF :)

**Comment by spiegeleixxl** [comment]
I sadly cannot verify you are Taylor Swift, but what I can do is actually think about this:
* What limits should apply to "verify" a user? 
* Are there some requirements before an admin can actually verify a person?
* Can we actually garantee that the verification is correct or just that the person is cozy enough with an (hopefully unbiased) admin?
* Isn't there a way to actually verify identity within the blockchain? In a sense that would kind of kick the anonymity to the curb, but I get why you want to have something like that
* Shall the possibility for a user to request his verification be only available as soon as he reached a certain number of posted and/or completed bounties/jobs?
* Do you want to have this option within the Options menu in the top right, or it's own menu item?

Sorry for the many questions, but the task is very open to interpretation. ;-)

-Chris

**Comment by PixelantDesign** [comment]
All great questions @spiegeleixxl 

We need to come up with what being _**verified**_ on Gitcoin means.
We know who you are or you've completed x bounties with us, you're a trusted contributor, etc. I think there should definitely be some requirements. We will also need to think about the experience here.

From a ux perspective and to keep it things light, maybe there is a request to be verified button on a user's profile....and for approval any core team member can approve the verification through admin.

Do we want to be open about **how** we verify?  I don't think Twitter is open about how they verify.
Perhaps this could be another feature that encourages good behavior on our platform.

**Twitter** lets people know that an account of public interest is authentic
**Instagram** uses it for _authentic presence of the public figure, celebrity or global brand_

cc: @willsputra @frankchen07

**Comment by frankchen07** [comment]
Great discussion overall, and some good ideas thrown around here. 

Verification can occur at a bunch of levels. For Gitcoin, verification can check that the user

1. is real.
2. is not an asshole.
3. does good work.

"Is real" is fairly straightforward - we want to make sure that the user isn't just a bot. To my knowledge, no bot has passed the Turing test, finished Gitcoin bounties, submitted PRs and fooled the community.

"Is not an asshole" is more subjective. This is interaction between Gitcoin community members and also the Gitcoin core team as they work through several initial bounties.

"Does good work" can be witnessed through the number of bounties they complete with funders and projects, and the quality of work that is submitted.

My thinking for initiating verification is that it should only be allowed as an option to the user after a threshold of bounties completed, which hopefully gives just enough objective and subjective feedback as to the quality work, interaction with team members, and enthusiasm for contributing.

If we're looking to keep things UX light, another interesting idea is to incorporate this verification process into Kudos as an available NFT reward for when a user reaches verification status. This way, we're not building out anything crazy new, and instead, using our existing product to verify.

**Comment by kuhnchris** [comment]
Good ideas in general, but right now I think we are thinking about it from a different angle than the user and bounty owners. "verification" in this perspective is an additional burden that the user has to do and that the bounty owner needs to look at. To say it increases work on both sides of the working isle. 
What I personally think that would encourage people is the typical "reward" system. (think Steam)
Basically you hide the "verification" in "achievements". 
Take the bounty topic - nobody wants to verify over a person on a bounty.
But how about this:
You compelted a bounty? Achievement "Your first bounty!"
You got a positive rating/feedback on your work? Achievement!
Verify your mail address? Achievement!

Make the user actually "want" to do the work for you instead of have them do it as a burden, that encourages people and actually kind of pushes people to get even better to get even higher achievements.

Just my 0.02$. (also, I know there are backsides)

**Comment by willsputra** [comment]
I kinda like @frankchen07's idea on incorporating this into Kudos, like special kinds of Kudos that you could only get if you've passed certain requirements.

We could possibly weave in @kuhnchris' idea here too:
You completed a bounty? Kudos. You got a positive rating/feedback on your work? Kudos. Verify your mail address? Kudos.

**Comment by PixelantDesign** [comment]
So it's a button that admin's can press....
...and then the verified icon shows up on the users profile
...and they also receive a Kudos for being verified?

verified icon is nice for at a glance.

**Comment by willsputra** [comment]
first version
![verified](https://user-images.githubusercontent.com/19514207/53175207-74569800-3626-11e9-8445-1937c35f7420.jpg)
