### ISSUE TITLE
As a funder, I'd like to be able to view issues on my profile by status (e.g. work submitted)

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2515]
### Description

It would be great to be able to see at a glance which issues are ready to have work submitted and to separate out completed bounties from those currently in progress.

### Why Is this Needed

Especially for large funders, for example Embark, it may be confusing to navigate many completed issues when trying to check on only issues that need attention. For similar reasons it might be helpful to provide some kind of notification beside bounties if the status has recently changed.

### Current Behavior

Currently we split the interface into "bounties funded" and "bounties completed" but not by more granular metrics such as the status of the bounty.

### Definition of Done

The easiest solution that fits with the existing interface might be adding the ability to further filter the 'bounties funded' tab.

**Comment by spiegeleixxl** [comment]
Do you want to simply filter it like with the available bounties, or do you want to have predefined tabs to select between the various bounty statuses?

**Comment by ceresstation** [comment]
@spiegeleixxl I'm open to either approach personally, though a filter might be more concise, open to feedback!

**Comment by PixelantDesign** [comment]
@willsputra @frankchen07 what do yall think?

**Comment by frankchen07** [comment]
@PixelantDesign - doesn't the funder dashboard take care of this? 

https://github.com/gitcoinco/web/pull/2504 & https://www.youtube.com/watch?v=3KU4wfqlJvA

**Comment by willsputra** [comment]
@PixelantDesign I agree with @frankchen07 . The Notifications and the All Bounties section on the funder dashboard should take care of this.

Screenshot from the funder dashboard video:

<img width="1021" alt="screenshot 2018-10-31 01 31 20" src="https://user-images.githubusercontent.com/19514207/47737830-c86ef280-dcac-11e8-9e09-b806f833b32d.png">

**Comment by PixelantDesign** [comment]
Yes it will when we push it out! Also the weekly bounties email might help.
https://github.com/gitcoinco/web/issues/3013

**Comment by kuhnchris** [comment]
superseeded by dashboard
