### ISSUE TITLE
https://gitcoin.co/not_a_token 's most bottom medium.com link 404s

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2516]
Hi there.

The link behind "Read more" is broken, it leads to a 404 on Medium.
![image](https://user-images.githubusercontent.com/761911/47354739-c8289300-d6bf-11e8-9af6-9541e792b052.png)

- Chris

**Comment by kuhnchris** [comment]
@owocki  may I propose a link to https://github.com/FEMBusinessModelsRing/web3_revenue_primitives since it lists business models, or you want to keep it separate?

**Comment by owocki** [comment]
yes thank you @kuhnchris !
