### ISSUE TITLE
garbled text on gitcoin.co/new

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2521]
garbled text on gitcoin.co/new

chrome, latest, on a mac

![image 8](https://user-images.githubusercontent.com/513929/47388119-98cd5280-d6ce-11e8-9d54-33216a266e33.png)

to repro: clear cookies, go to gitcoin.co/new and login

**Comment by spiegeleixxl** [comment]
Weird - seems fine here.
Chrome - Mac - Latest Stable
![image](https://user-images.githubusercontent.com/761911/47393689-7e23c980-d720-11e8-9025-1e8f39f01b0d.png)
Can you try injecting the javascript itself from here ( https://github.com/gitcoinco/web/blob/c66cbc99218da191ef4ef0a67f742fe23b983e74/app/assets/v2/js/base.js) and see if this still looks garbled to you?

**Comment by owocki** [comment]
@cmditch anything else you can tell us about how to repro?

**Comment by cmditch** [comment]
Tried to reproduce it by clearing cookies and revoking oauth token in github, but haven't been able to get the modal to pop back up.

Is there something in the database tied to my account that can be flipped, and I'll try at it again.

**Comment by octavioamu** [comment]
The problem was in https://gitcoin.co/bounty/quickstart not /new  the problem is hard to reproduce because the redirect for quickstart (as part of the onboard) and the css messing was .quickstart .modal 
Pushing the fix
