### ISSUE TITLE
As a contributor, I'm having a trouble submitting my work, which ends up creating overhead for the funder, as they need to cancel the bounty and pay a tip. As a funder, I prematurely cancel my bounty after completion, and choose not to complete the Gitcoin stages to the "done" status. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2523]
### Discussion

As a contributor, I'm having a trouble submitting my work, which ends up creating overhead for the funder, as they need to cancel the bounty and pay a tip. This also has the negative effect of bounty tracking on the data side, as the status is now marked as "cancelled" when it really should be "done." 

Example : https://github.com/jschiarizzi/ost-evnt/issues/2

As a funder, I prematurely cancel my bounty after completion, and choose not to complete the Gitcoin stages to the "done" status. Why?

Example: https://github.com/MARKETProtocol/MARKET.js/issues/140
Example: https://github.com/MARKETProtocol/dApp/issues/314
Example: https://github.com/Bounties-Network/BountiesAPI/issues/39

### Open Questions

1. What portion of the submission is difficult and leads to dropoff?
2. Why do some funders decide to just cancel the bounty and not complete the Gitcoin flow all the way to the "done" stage?

**Comment by kuhnchris** [comment]
did you guys ever figure out the drop off points or reasons?
