### ISSUE TITLE
As a funder, when I'm on the funder form inputting a token amount to price an issue, the USD amount is automatically populated, however, when changing the USD amount, the token value is not re-populated or populated with an inexact integer.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2524]
**Describe the bug**
As a funder, when I'm on the funder form inputting a token amount to price an issue, the USD amount is automatically populated, however, when changing the USD amount, the token value is not re-populated or populated with an inexact integer.

**To Reproduce**

Token value is not re-populated:

1. https://gitcoin.co/funding/new
2. Scroll down to the pricing section. 
3. Enter 1 ETH.
4. The USD amount automatically populates.
5. Change the USD amount by + or - $50 (or smaller amount, delta is ETH price dependent).
6. ETH Token value doesn't change and still allows the funder to submit.
7. The funder will have to check the true $ equivalent in MetaMask before submitting. This can be confusing.

Token value is re-populated only at estimated integer intervals and is otherwise not re-populated, which does not lend an exact estimate. 

1. https://gitcoin.co/funding/new
2. Scroll down to the pricing section. 
3. Enter 1 ETH.
4. The USD amount automatically populates.
5. Change the USD amount by 2X.
6. ETH token value doubles.
7. Change the USD amount by + or - $50.
8. ETH token value does not change and still allows the funder to submit.
7. The funder will have to check the true ETH equivalent in MetaMask before submitting. This can be confusing.

**Expected behavior**

1. When changing the USD value, re-population of the token amount should be accurate in the tenths range. (conversion rate 1 ETH = $201.25, e.g $220 should register as 1.1 ETH)

**Comment by Anish-Agnihotri** [comment]
The pricing modal in `dashboard/templates/shared/pricing.html` has an ETH Value that is populated with a value filling the id of `amount`. This `amount` value is calculated by using an estimation on the inputted USD value with the following function: 

```
var usdToAmount = function(event) {
  var usdAmount = $('input[name=usd_amount').val();
  var denomination = $('#token option:selected').text();
  var estimate = getAmountEstimate(usdAmount, denomination, function(amountEstimate) {
    if (amountEstimate['value']) {
      $('#amount').val(amountEstimate['value']);
      $('#usd_amount_text').html(amountEstimate['rate_text']);
    }
  });
};
```
It seems that the issue is with the rounding of inputted USD values and then their subsequent conversion to ETH values. I'll take a look at this tomorrow  if no one else decides to hop onto it, and see what I can do.
