### ISSUE TITLE
Can't start new work even though I only have 2 active tasks

### ISSUE THREAD

**Issue by Destiner** [gitcoinco/web#2528]
**Describe the bug**
When I tried to start work, I received the message "You may only work on max of 3 issues at once". However, I have only 2 active tasks. 

**To Reproduce**
* Pick any open task that can be started
* Press "start work"
* Write plan & click "submit"

**Expected behavior**
It should allow to start a task.

**Screenshots**
Error message
<img width="1437" alt="screen shot 2018-10-25 at 15 16 49" src="https://user-images.githubusercontent.com/4247901/47499599-07461800-d869-11e8-8963-a93663a24d40.png">

Profile page
<img width="1438" alt="screen shot 2018-10-25 at 16 14 32" src="https://user-images.githubusercontent.com/4247901/47502706-25b01180-d871-11e8-93fd-c8d0fb4b4a00.png">

Projects started by me (issue explorer)
<img width="1194" alt="screen shot 2018-10-25 at 16 16 28" src="https://user-images.githubusercontent.com/4247901/47502840-64de6280-d871-11e8-91fe-e2caaa8317e1.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14
- Browser: Google Chrome
- Browser Version: 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Gitcoin profile: https://gitcoin.co/profile/Destiner

**Comment by Destiner** [comment]
Seems like [this](https://gitcoin.co/issue/ethereum-ts/TypeChain/94/1262) issue may contribute to this behavior. I finished this issue couple days ago, but it still shows as open both on Gitcoin and Github issue page.

<img width="875" alt="screen shot 2018-10-25 at 16 38 16" src="https://user-images.githubusercontent.com/4247901/47504201-6fe6c200-d874-11e8-9d13-a43dea47293e.png">
<img width="798" alt="screen shot 2018-10-25 at 16 38 26" src="https://user-images.githubusercontent.com/4247901/47504202-6fe6c200-d874-11e8-8c2e-0953117c8639.png">

**Comment by kuhnchris** [comment]
This is related to what issues are being counted as "being worked on". Does this error still occour to you @Destiner ?

**Comment by Destiner** [comment]
@kuhnchris can't tell you for sure because I haven't used GitCoin in a while, but it seems like the [issue](https://gitcoin.co/issue/ethereum-ts/TypeChain/94/1262) mentioned above is marked as "done" now and also it says that I don't have open issues anymore.

**Comment by kuhnchris** [comment]
Then I'll close this one for now and if it resurfaces please open a new ticket, okay? :-) Thanks!
