### ISSUE TITLE
Pull Request references invalid object

### ISSUE THREAD

**Issue by spiegeleixxl** [gitcoinco/web#2529]
**Describe the bug**
The link in the PR template (https://github.com/gitcoinco/web/blob/contributing/CONTRIBUTING.md) is invalid. The proper one is linked a bit below: https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md

**To Reproduce**
Make a PR.

**Expected behavior**
A valid link

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47511561-c820c280-d87a-11e8-97f9-ce1d8dd20f50.png)

**Desktop (please complete the following information):**

- OS: *
- Browser *
- Browser Version *

**Comment by PixelantDesign** [comment]
Thanks for reporting this @spiegeleixxl!
