### ISSUE TITLE
Design a cleaner tagging experience on the Gitcoin funder form

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2531]
### Background

The tagging experience on the funder form is not very intuitive. Let's design a new one. 

Design discussion below:

**Comment by willsputra** [comment]
@kuhnchris Thanks for your feedback! Yeah having a predefined set would be great. I was thinking of something like this. What do you think? cc @PixelantDesign 
![fund issue keyword](https://user-images.githubusercontent.com/19514207/47662201-73ac7880-dbd5-11e8-8feb-f498169bfefb.jpg)

**Comment by willsputra** [comment]
Took cues from GitHub repo topics :p 

<img width="1008" alt="screenshot 2018-10-31 23 37 38" src="https://user-images.githubusercontent.com/19514207/47799809-fa905b00-dd65-11e8-9bd4-74007a818486.png">

I guess the user should be free to use whatever he chooses, although I wonder if the new tag should be added to the list of our predefined set 🤔

**Comment by PixelantDesign** [comment]
@frankchen07 @owocki @mbeacom what do you think of the above?

**Comment by owocki** [comment]
looks really good

**Comment by thelostone-mc** [comment]
In case you didn't know @willsputra 
we have this a similar version at gitcoin.co/onboard/contributor

<img width="782" alt="screen shot 2018-11-15 at 12 17 39 am" src="https://user-images.githubusercontent.com/5358146/48504942-f424d780-e86b-11e8-9673-97d288f4e6b0.png">

**Comment by willsputra** [comment]
@thelostone-mc @PixelantDesign hmm the problem with that one is still the same though:
1. the use of commas to separate keywords isn't very intuitive, and
2. it's also hard to fit in preset keywords there

Another option I thought of is to use an 'improved' version of the Search bar on the Issue Explorer. That way we can reuse components. (Note that the preset keywords feature might be useful on the Issue Explorer too!) What do you all think? 🙂

![keyword2](https://user-images.githubusercontent.com/19514207/48626623-4fca9e80-e9ed-11e8-8a40-30823562fc38.jpg)

**Comment by thelostone-mc** [comment]
No no I'm all in for throwing out the old one ! 
I was just pointing out that we've got something like that at our end. :P

**Comment by willsputra** [comment]
I'm quite happy with the latest one I posted too haha.

That component could also potentially be reused on:
1. Issue Explorer
![screenshot 2018-11-20 22 24 46](https://user-images.githubusercontent.com/19514207/48779979-c203f180-ed13-11e8-947b-1514cc00f638.png)

2. Grants team member
![screenshot 2018-11-20 22 25 08](https://user-images.githubusercontent.com/19514207/48779991-c9c39600-ed13-11e8-83ea-ad6c1a045d9b.png)

3. onboard/contributor
![screenshot 2018-11-20 22 25 48](https://user-images.githubusercontent.com/19514207/48780014-d47e2b00-ed13-11e8-8194-cec63b4279df.png)

@thelostone-mc @PixelantDesign @frankchen07 thoughts/objections/concerns? if everything's okay I'll create the build ticket 😁

**Comment by frankchen07** [comment]
^ I definitely like the new non-comma'ed improvement of the search bar. Let's avoid scope creep and first implement it in the funder form. 

Once we see it in action, we can then figure out the timing and resources for upgrading the contributor onboarding tagging, and the issue explorer (although the new left hand bar implements most of the design and functionality here already, no?)

@willsputra - I updated the description here to reflect a build ticket, but I think it was mainly for design discussion - I can move the description to a separate build ticket.

**Comment by willsputra** [comment]
@frankchen07 I agree with implementing it in the funder form first. yep this is essentially the left hand bar with added dropdown keywords functionality.

Thanks for creating the build ticket! :)

**Comment by kuhnchris** [comment]
👍 let's give it a go and try it.
