### ISSUE TITLE
Issue Details Activity Stream Bug 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2534]
Worker applied, not shown in activity List.
Worker who was approved shows 3 times in the Work Start column.

![image 21](https://user-images.githubusercontent.com/238235/47525831-2e521900-d86c-11e8-9272-841cad092078.png)

<img width="964" alt="screen shot 2018-10-25 at 3 38 20 pm" src="https://user-images.githubusercontent.com/238235/47525789-2003fd00-d86c-11e8-9b19-180951c74927.png">

Also occurs here with work submitted: https://gitcoin.co/issue/Great-Hill-Corporation/quickBlocks/611/871

**Comment by thelostone-mc** [comment]
@PixelantDesign Can I get an example of this? 
The link you posted seems to be alright 🤔

**Comment by thelostone-mc** [comment]
It was probably a sync issue !
