### ISSUE TITLE
Landing Page Activity Feed - Visual Bug

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2535]
Different icons should be used instead of checks.

![image 22](https://user-images.githubusercontent.com/238235/47526187-01eacc80-d86d-11e8-846e-cb81f1957c8f.png)

**Comment by kuhnchris** [comment]
just checked - this is still the same.
![image](https://user-images.githubusercontent.com/761911/63673828-7b34b200-c7e5-11e9-8b23-9d4784d2c573.png)
