### ISSUE TITLE
Issues in the Issue Explorer with duplicate titles should not be allowed.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2537]
### User Story

As a contributor, I find it confusing that two issues have the same subject line, but are in different statuses.

### Why Is this Needed

Issues should only be in one status, therefore, issues with exact naming should not be allowed. Currently, there can be issues with the same subject line, different IDs and different statuses - this makes it confusing when a user specifically searches for an issue and finds one issue under open and one under expired.

Example:
https://gitcoin.co/issue/duaraghav8/Solium/94/779 (open & expired, same subject line)
https://gitcoin.co/issue/duaraghav8/Solium/94/722 (open, same subject line)

### Current Behavior
Duplicate titles on issues are allowed.

### Expected Behavior
Duplicate titles on issues should not be allowed, therefore ensuring that issues are only in one status. The point of origin for to prevent this from happening is the funder form. When a user submits funding for an issue, the subject line should be compared to existing subject lines in the Gitcoin Issue Explorer.

### Definition of Done
1. Duplicate titles on issues should not be allowed.
2. A descriptive warning and failure is triggered on the funder form if a duplicate subject line is submitted.
3. Current duplicate titles on issues should be resolved by follow up and deletion of the chronologically older or more expired issue.

**Comment by pinkiebell** [comment]
I agree with 2., in case this still happens; I would encourage grouping of issues with the same github issue url.
