### ISSUE TITLE
On certain Gitcoin Issue Details pages, there are empty activities by funders and contributors under the All Activity section.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2539]
**Describe the bug**
On certain Gitcoin Issue Details pages, there are empty activities by funders and contributors under the All Activity section.

**To Reproduce**
Example 1: https://gitcoin.co/issue/novnc/noVNC/944/1047

![screen shot 2018-10-24 at 14 32 15](https://user-images.githubusercontent.com/7516920/47536199-b8ea4680-d873-11e8-9b05-53dbca955696.png)

Example 2: https://gitcoin.co/issue/paritytech/polkadot/202/690

![screen shot 2018-10-25 at 16 33 46](https://user-images.githubusercontent.com/7516920/47536209-c69fcc00-d873-11e8-892b-e80e3d545a07.png)

**Expected behavior**
These should not exist if there were no actions. If there were actions, they shoudl be populated.

**Desktop:**
- OS: macOS High Sierra 10.13.4
- Browser: Google Chrome
- Browser Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by pinkiebell** [comment]
#2013

**Comment by octavioamu** [comment]
@mbeacom looks like that PR is waiting your review

**Comment by kuhnchris** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/761911/63674115-1f1e5d80-c7e6-11e9-8837-b3d5c56e4a0a.png)
