### ISSUE TITLE
www.gitcoin.co doesnt work

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#254]
fyi, https://gitcoin.co works, but https://www.gitcoin.co and http://www.gitcoin.co aren’t resolving

**Comment by thelostone-mc** [comment]
pinged you on slack cause of the hosting service questions I had! ^_^

**Comment by mbeacom** [comment]
@owocki Whoever tackles this will need access to AWS. We'll need to update the ACM certificate, CF, and r53 accordingly.

**Comment by owocki** [comment]
i just added an A entry for `www`... not sure if the SSL cert will resolve correctly... but its a start at least

**Comment by mbeacom** [comment]
@owocki You can pass `gitcoin.co` and `*.gitcoin.co` to the ACM cert request.

**Comment by mbeacom** [comment]
This is fixed.

Steps taken:

- Add route53 entry for www.gitcoin.co pointing to CF distribution. (via Kevin)
- Add ACM SNI certificate for:  `gitcoin.co` and `*.gitcoin.co`
- Add `www.gitcoin.co` to Additional CNAMEs on CloudFront distribution.
- Update certificate used by CF distribution to use the newly created certificate.
