### ISSUE TITLE
Slack Bot reports (and prolly assumes) Worker applied == WORK STARTED

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2542]
**Describe the bug**
Worker applied for issue in issue explorer - Slack Bot reports that work on the bounty has started. Yet, we cannot start on working on the bounty because the owner has to approve the worker first.

**To Reproduce**
Apply for Work on a Issue requiring worker approval

**Expected behavior**
No comment by Slack Bot and/or System OR change of message "WORKER APPLIED" by slack bot

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47561828-bee83200-d91c-11e8-8292-ecdd89b1666a.png)

**Desktop (please complete the following information):**

- OS: Mac OS X / Slack Client
- Browser Chrome
- Browser Version Latest Stable (69)

**Comment by willsputra** [comment]
@kuhnchris I wonder if this could be related to #3051?

**Comment by kuhnchris** [comment]
Command retóur, still fucked:
![image](https://user-images.githubusercontent.com/761911/51995561-377a0400-24b3-11e9-8092-a096d2938445.png)
