### ISSUE TITLE
Explore Design of Surface Open Bounties Via Flyout

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2546]
### User Story
As a contributor, I'd like an easy way to see more info on a bounty without going into the Issue Details page.

### Description
One idea we'd like to explore is by using a flyout.

### Definition of Done
- [ ] Mockup ways to solve for the above.
- [ ] Consider how to solve for responsiveness of the page.

**Comment by willsputra** [comment]
@PixelantDesign the flyout will provide the skillset tags and also the latest activity. skillset tags could be limited to only show 5.

![issueexplorer](https://user-images.githubusercontent.com/19514207/47584241-4d47cc80-d98c-11e8-8fd5-1a55819d4e5f.png)

**Comment by spiegeleixxl** [comment]
Sounds good, but I assume we need to ensure a maximum result amount, because we need to provide that extra data beforehand? Or do you want to load it on-demand?
