### ISSUE TITLE
KUDOS: C++ Scientist path busted - FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/gitcoin/coin/app/assets/v2/images/kudos/c%2B%2...

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2550]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-backend/issues/1596/

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/gitcoin/coin/app/assets/v2/images/kudos/c%2B%2B_scientist.svg'
  File "kudos/views.py", line 148, in image
    img = kudos.as_img
  File "kudos/models.py", line 180, in as_img
    with open(file_path, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/gitcoin/coin/app/assets/v2/images/kudos/c%2B%2B_scientist.svg'
```

**Comment by mbeacom** [comment]
@jasonrhaas

**Comment by jasonrhaas** [comment]
So encoding the URL does work in some environments, but not others.  In some cases with Django or the DOM tries to be "smart" and encode it back to `++`, which breaks it.  The best solution is to just not use `++` in the filename.  Which I think you have already implemented or are in the process of.

**Comment by mbeacom** [comment]
Yeah - This has already been updated: https://github.com/gitcoinco/web/commit/69b37c244101d5a5bad142dfd36a397540dd2805
