### ISSUE TITLE
HTTPError: 429 Client Error: Too Many Requests for url: https://api.opensea.io/api/v1/events/?asset_contract...

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2553]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-backend/issues/1598/

```
HTTPError: 429 Client Error: Too Many Requests for url: https://api.opensea.io/api/v1/events/?asset_contract_address=0x2aEa4Add166EBf38b63d09a75dE1a7b94Aa24163&token_id=163
(3 additional frame(s) were not displayed)
...
  File "kudos/management/commands/sync_kudos.py", line 222, in handle
    self.opensea_sync(kudos_contract, int(start_id))
  File "kudos/management/commands/sync_kudos.py", line 81, in opensea_sync
    r.raise_for_status()

HTTPError: 429 Client Error: Too Many Requests for url: https://api.opensea.io/api/v1/events/?asset_contract_address=0x2aEa4Add166EBf38b63d09a75dE1a7b94Aa24163&token_id=163
```

**Comment by jasonrhaas** [comment]
Bummer... that API key should more than support the number of requests that we are sending to it.  According to Alex they increased the limit to 60/second.

> There is still a limit, but I just raised it a ton, to 60/sec. love this idea!

It could be maybe its not accepting the API key.  Maybe doing the request with DEBUG turned up would help.  Here is the API reference.

https://docs.opensea.io/reference#getting-assets
