### ISSUE TITLE
"Work commit" eth transaction displayed as "Unknown Function"

### ISSUE THREAD

**Issue by spiegeleixxl** [gitcoinco/web#2555]
**Describe the bug**
Whenever a work is commited (or a issue is funded) you interact with the blockchain with a "unknown function".

**To Reproduce**
Commit work

**Expected behavior**
"Work commit"

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47616654-2985a300-dac0-11e8-84b1-5e7c112a9ac7.png)

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Chrome / MetaMask
- Browser Version Latest Stable

**Comment by mbeacom** [comment]
Upstream metamask issue with the new UI.  Closing.
