### ISSUE TITLE
KUDOS: Send Kudos stuck when MetaMask is locked

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2558]
**Describe the bug**
If MetaMask is locked, clicking Send on 'Send Kudos' page will get you stuck.

Video: https://drive.google.com/file/d/14AcEfICPDZ2ZfVEPF5DQDVmySiKU3KW_/view

**To Reproduce**
• Choose a Kudos from Kudos Marketplace
• Click Send Kudos
• Enter recipient name
• Click Send when MetaMask is locked

**Expected behavior**
There should be a prompt asking me to unlock MetaMask, so I don't get confused on what to do when I'm stuck.

**Comment by kuhnchris** [comment]
So you should actually get a redirect to https://github.com/gitcoinco/web/blob/879fa61e35e5d6f6fe2c85d20d4252e21b99be1e/app/dashboard/templates/shared/no_metamask_error.html before being able to go the checkout page IMHO.

Kind of like here: 
https://github.com/gitcoinco/web/blob/e349ace59b22c9f8d4917d0acf6066468e273021/app/assets/v2/js/shared.js#L696

Correct?

**Comment by willsputra** [comment]
@kuhnchris yea I think so.
@thelostone-mc thoughts? :)
