### ISSUE TITLE
Profiles (temporary) broken

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2580]
**Describe the bug**
Cannot open profile

**To Reproduce**
Go to your own profile

**Expected behavior**
See your own profile

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47753636-8b990080-dc98-11e8-8e6e-50eb023f2930.png)

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Chrome
- Browser Version Latest Stable

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris!

**Comment by thelostone-mc** [comment]
It's working now ^_^

<img width="1440" alt="screen shot 2018-10-31 at 1 00 42 pm" src="https://user-images.githubusercontent.com/5358146/47772578-1a476500-dd0d-11e8-9d77-a3cd23d9b1d6.png">

**Comment by kuhnchris** [comment]
Uh oh, sorry but no @thelostone-mc:

![image](https://user-images.githubusercontent.com/761911/47776882-b49aaf00-dcf3-11e8-95ec-bfa89f327f60.png)

**Comment by kuhnchris** [comment]
ayyyyy that fixes it, great, thanks! :-)
