### ISSUE TITLE
As a contributor, I'd like a reminder to not start work until approved, otherwise clashes and unnecessary work may proceed.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2583]
### User Story

As a contributor, I'd like a reminder to not start work until approved, otherwise clashes and unnecessary work may proceed.

### Why Is this Needed

Some workers begin work without approval, which causes headache down the line when others begin work as well. 

### Current Behavior

Workers apply to start work, and that's it.

### Expected Behavior

Workers apply to start work, and Gitcoin Bot reminds the worker to please not start work until getting approval.

### Definition of Done

Gitcoin Bot reminds a worker to please not start work until getting approval.

### Example

https://github.com/sigp/lighthouse/issues/52

**Comment by thelostone-mc** [comment]
We could leave update a generic update at https://github.com/sigp/lighthouse/issues/52#issuecomment-431418514 
If we were to remind every individual -> it mightend up feeling spammny 😓

**Comment by kuhnchris** [comment]
Maybe add it to "Start Work" like this?
![image](https://user-images.githubusercontent.com/761911/47777397-f24c0780-dcf4-11e8-9330-1682b1f3184f.png)
It also depends on the type if it's Permissionless or Approval Required...

**Comment by kuhnchris** [comment]
Also there's already an info:
![image](https://user-images.githubusercontent.com/761911/47777478-1b6c9800-dcf5-11e8-9535-f25e8db01b16.png)

**Comment by frankchen07** [comment]
^ hm looks like it doesn't stop them from doing so, but I guess if they try and complain, it's a point on the funder's side that he/she DID sign off on the process.
