### ISSUE TITLE
As a contributor, I don't want to see TEST issues on mainnet.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2584]
### User Story

As a contributor, I don't want to see test issues on mainnet.

### Why Is this Needed

These issues should be on Rinkeby, not mainnet.

### Current Behavior

Funders can test issues on mainnet, causing potential noise for contributors looking for work on the explorer.

### Expected Behavior

Test issues should only exist on Rinkeby.

### Definition of Done

Discuss what methods there are to prevent test issues from showing up on mainnet, and if we need to automate removal.

### Additional Information

https://gitcoin.co/issue/angelleye/sandbox/2/1438

**Comment by thelostone-mc** [comment]
It would be messy weeding these out from the mainnet  🤔 
We could prompt funders to create an issue on rinkeby as opposed to mainnet on the `/new` page

**Comment by kuhnchris** [comment]
How about we provide a 2nd server (like sandbox.gitcoin.co) giving the people the possiblity to test? Right now testing around in gitcoin is a bit of a pain, either you set up a local environment or try to hide your bounties...

**Comment by frankchen07** [comment]
Agree that it would be messy - it might have to be a manual process, but definitely low priority right now.
