### ISSUE TITLE
make lazy load kudos csrf work again

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2585]
4dd7af9509a98c2cc0f84e91fc6f140cfc9aacf3 reverts csrf protection for lazy loading of kudos

the scope of this task is to reintroduce csrf protection, and to take out the csrf_exempt tag i just added

**Comment by kuhnchris** [comment]
See https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet for best practice.
