### ISSUE TITLE
bug - kudos tx ran out of gas

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2586]
https://etherscan.io/tx/0x063b85c9e070e57ede8cfdd8f92cd8841c59d0ef0d6fecd8d58c64227ddc9228
kudos to username: TimDaub
original report: https://twitter.com/TimDaub/status/1057353311655993344

success criteria:
1. identify and fix the root cause of this issue.
2. communicate with user to let them know its fixed and to try again (you might have to send them more gas)

**Comment by octavioamu** [comment]
Not sure what happens but also the data of his kudo is messy
https://gitcoin.co/profile/TimDaub
![image](https://user-images.githubusercontent.com/1358093/47791580-c763b280-dcf8-11e8-942c-0143dc77c97b.png)

**Comment by kuhnchris** [comment]
I think that the gas calc is messed up to begin with, not just kudos.
my default gas was 2 on kudos, but I barely get anything verified with 2 anymore. 2.5wei seems to be the minimum right now. The calculator may simply be screwed.

**Comment by octavioamu** [comment]
#2570

**Comment by jasonrhaas** [comment]
Do we know if this is a Kudos Direct Send or Kudos Indirect Send?  Ie, if the Kudos needed to be "received".  The link on etherscan.io says the transaction is from https://etherscan.io/address/0xa5a3835689008041296d2cd3f94c307e05f82630

Looking at the transactions, it looks like it is probably the proxy account, which means Indirect Send.  Hard to be sure  without looking at the database directly though.

**Comment by jasonrhaas** [comment]
OK so I added a 10% ETH buffer for the proxy account to add some extra gas money for when the Kudos actually gets minted on the receiving end.

Before buffer:
<img width="359" alt="screen shot 2018-10-31 at 4 47 48 pm" src="https://user-images.githubusercontent.com/7018237/47820993-2b07d300-dd2d-11e8-8e78-d574089427b0.png">


After adding a 10% buffer:
<img width="358" alt="screen shot 2018-10-31 at 4 50 35 pm" src="https://user-images.githubusercontent.com/7018237/47820999-34913b00-dd2d-11e8-83eb-297116b3013d.png">

This means that the upfront cost for Kudos Indirect Send will be a bit higher.  We also need to make sure that in the *kudos_receive.js* that we are returning any leftover money to the original Kudos sender.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2656

**Comment by owocki** [comment]
sent a test transaction on the new system, with plenty of gas 🎉

**Comment by owocki** [comment]
https://etherscan.io/tx/0xd8da62d1b0b6b3bf40dd7cc3c6c271336a8e9c313f72ac91b6819da87214aeb4
