### ISSUE TITLE
as a user, i want kudos to show who sent it to me visually, so i can get an accurate view of the value of a kudos

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2587]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want kudos to show who sent it to me visually, so i can get an accurate view of the value of a kudos

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
you have kudos X is not the value marker for kudos.

the value marker is 

* what is the kudos
* who did it come from
* what was the context? (comments, github issue)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Profile shows only the image of the kudos.
<img width="1436" alt="screen shot 2018-10-31 at 2 16 57 pm" src="https://user-images.githubusercontent.com/513929/47790567-d27a0b00-dd17-11e8-935b-eb8adc0d6318.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Profile shows all of this information visually.

For bonus points, if someone sends a kudos to themselves, we should highlight this visually, and maybe be opionioned as such as to call it as social faux paus.

<img width="1172" alt="screen shot 2018-10-31 at 2 22 12 pm" src="https://user-images.githubusercontent.com/513929/47790800-651aaa00-dd18-11e8-91e2-b9e356f58363.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
SEe above

**Comment by PixelantDesign** [comment]
<img width="605" alt="screen shot 2018-11-08 at 3 56 54 pm" src="https://user-images.githubusercontent.com/238235/48227574-ae01dc80-e370-11e8-9541-d097c96256ec.png">

**Comment by octavioamu** [comment]
Updated with some others elements
![image](https://user-images.githubusercontent.com/1358093/48236455-65b2e080-e3a9-11e8-859c-72fb8f7a6ab8.png)

**Comment by owocki** [comment]
these look good to me.  can we get them coded up?

**Comment by octavioamu** [comment]
good point forgot to link the PR
