### ISSUE TITLE
Duplicated data in kudos profile

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2590]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

Duplicated data in kudos profile, maybe related to the sync command duplicating data. 

https://gitcoin.co/profile/TimDaub

![image](https://user-images.githubusercontent.com/1358093/47796216-a3a56a00-dd02-11e8-9f13-147bcec1aae2.png)

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by jasonrhaas** [comment]
If there are duplicated Kudos in the Profile, that could be a sync issue, or a database filtering issue.  If there are duplicated comment in the Kudos itself, that is probably a template issue.

**Comment by willsputra** [comment]
not sure if this is related, but I also got duplicated Kudos on the Profile, inside the 'Sent Kudos' tab. One is correct (with the recipient username, address, date), while the other one just shows the Kudos title.

<img width="658" alt="screenshot 2018-10-31 23 45 10" src="https://user-images.githubusercontent.com/19514207/47800498-5d362680-dd67-11e8-88bd-a457493de440.png">
<img width="621" alt="screenshot 2018-10-31 23 45 17" src="https://user-images.githubusercontent.com/19514207/47800503-60c9ad80-dd67-11e8-9c5a-5e3e267a4580.png">

**Comment by kuhnchris** [comment]
Encountering the same issue right now. 1 Kudos shows data, the other 3 none.

**Comment by jasonrhaas** [comment]
Copying my note from Slack:

> It looks like the issue with the duplicates in the Profile, is that its showing both the “Clone” and the “Gen0" Kudos.   It has something to do with how the logic was changed to display the Kudos in the profile.  I’ll looking at the code now.

> It has to be this — https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py#L1572-L1577 (edited)
The only Kudos that are valid to show in the profile have `num_clones_allowed == 0`.  If that number is not 0, its means its a “Gen0” or “Clonable” token, and not a “clone”. (edited)
For convenience, we can add an `@property` method to the model, called `is_clone()` that checks for the above.  And only ones with `is_clone() == True` should show up in the profile.

**Comment by octavioamu** [comment]
fixed by #2662
