### ISSUE TITLE
Duplicated Kudos badges in the Profile section

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2592]
**Describe the bug**
This is different from https://github.com/gitcoinco/web/issues/2590. There seems to be duplicates of the Kudos I've sent to members of the Gitcoin team. When hovering over, one instance has details, and in another, none. 

For the "Out of this World Programmer" Kudos I sent to Mark, the duplicate instance with details is completely missing. 

**To Reproduce**
1. Send a kudos to a Gitcoin team member. 
2. Check your profile page.
3. Hover over duplicates.

**Expected behavior**
There should only be one instance of the Kudos I send to others, with details on the hover-over.

**Screenshots**

![screen shot 2018-10-31 at 11 43 57](https://user-images.githubusercontent.com/7516920/47811484-1c0c2b00-dd03-11e8-84e1-6ed3c761e227.png)

**Live**

![kudos_bug](https://user-images.githubusercontent.com/7516920/47811562-465de880-dd03-11e8-8e27-560516ada139.gif)

**Desktop:**
- OS: macOS High Sierra 10.13.4
- Browser: Google Chrome
- Browser Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by jasonrhaas** [comment]
I think this one can be closed with the latest code in master.  There are no duplicates, but there are still problems with the profile.

**Comment by octavioamu** [comment]
This one is fixed
