### ISSUE TITLE
as a user, i want to be able to send 100 kudos at a time, because marketing.

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2598]
_From @owocki on October 28, 2018 23:51_

as a user, i want to be able to send 100 kudos at a time, because marketing.

example: send a devcon kudos at the end of my devcon preso

what:
- a page, based upon the current receive page, called bulk_receive that accepts a receive web3 address,
and transfers the specified kudos to it
- since we cannot do this securely in the current architecture of receive (because of the private key being exposed on the frontend, and if we put too much ETH in the private key / account, then ppl will steal it), we must built a new architecture.
- i suggest this new architecture be based in web3py.  the kudos will be sent if/when someone submits a POST request on the form 

other specifications:
- user must be logged in to receive a kudos.
- form submission will fail if there aren't enough clones available
- form submission will fail (silently) if you try to get more than one kudos (sybyll vectors we should close: ip address AND web3 address)

_Copied from original issue: gitcoinco/gitcoin-erc721#209_

**Comment by owocki** [comment]
@mbeacom @octavioamu can you post your WIP code pls? i want to hack on it on the plane ride back from devcon

**Comment by octavioamu** [comment]
@owocki here is a very very start #2665
