### ISSUE TITLE
bootstrap a pricing engine by setting the scales manually

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#26]
we could code up a little javascript interface where you slide a few things back and forth and it tells you what a fair bounty is

maybe on top of that, make it so that you enter a issue URL and we suggest values based upon NLP or the languages involved or wahtever

**Comment by gamwe6** [comment]
Did you decide which sliders to use?

**Comment by owocki** [comment]
i think issue type, complexity, scope, deadline (how quick you need it?) and reputation are the obvious places to start.  anyone strongly disagree?

**Comment by gamwe6** [comment]
A quick bare draft with just level, time and type. For time, maybe use input text instead. https://codepen.io/anon/pen/NaaZPZ

**Comment by owocki** [comment]
@mbeylin what do you think of this?
