### ISSUE TITLE
the big production deploy ticket

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2605]
_From @owocki on October 15, 2018 2:27_

1. mint all tokens in kudos.yaml that aren't in kudos_mainnet.yaml to 0x56c72cda0b04fc39a25d0b6a64fa258fad46d664 mainnet contract. MAKE SURE THE tokenURI info is correct first!!
2. set the tokenURI's of all the kudos_status.yaml tokens to point to gitcoin.co instead of kudosdemo.gitcoin.co [reference slack convo](https://gitcoincore.slack.com/archives/CAXCZR8K0/p1539570122000100)
3. deploy `kudos-v1` branch to master, then deploy to prod
4. test end to end 
5. anything else?

_Copied from original issue: gitcoinco/gitcoin-erc721#182_

**Comment by octavioamu** [comment]
_From @owocki on October 15, 2018 2:28_

@mbeacom @jasonrhaas this reminds me, we should get the `kudos-v1` build passing and also get code review going

**Comment by octavioamu** [comment]
_From @jasonrhaas on October 15, 2018 3:47_

So just realized that the `_setTokenURI` function is an internal method.  Bummer.  So there is no way to modify the existing tokens on that address.  Would need to make a contract update to allow this functionality to be exposed.  In the mean time I just minted some new tokens so that Status can demo with them.  

For the "real" production deploy we will probably just want to use a new address.  I image we will want the ability to change update the token metadata in the future as the contract owner.

**Comment by octavioamu** [comment]
_From @owocki on October 15, 2018 12:4_

> For the "real" production deploy we will probably just want to use a new address. 

This is problematic because we need to thread in the 'contract address' everywhere in the send/receive flow for Kudos...  Is that a heavy lift @jasonrhaas ?

**Comment by octavioamu** [comment]
_From @jasonrhaas on October 15, 2018 14:1_

Oh I just meant doing another contract deploy to a different address on mainnet.

**Comment by octavioamu** [comment]
_From @owocki on October 15, 2018 16:56_

yes i know what you meant.. the tricky part of this is getting the app to talk to multiple mainnet contracts

**Comment by mbeacom** [comment]
Live! :tada:
