### ISSUE TITLE
Add ability to send a Kudos using only Eth address

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2606]
_From @jasonrhaas on October 14, 2018 23:50_

> It seems that there is a use case for sending cloned kudos to people that are not on the gitcoin platform. Currently the Kudos Send requires a Gitcoin or Github username.  But we have a case here where I need to send Kudos to someone and only have the address:

https://github.com/mbeacom/gitcoin-erc721/issues/172#issuecomment-429448305

We would like to have a UI that allows this rather than relying on a management command.

_Copied from original issue: gitcoinco/gitcoin-erc721#181_

**Comment by octavioamu** [comment]
_From @owocki on October 15, 2018 23:53_

https://github.com/mbeacom/kudos/pull/45

addresses this

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2685

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2791
