### ISSUE TITLE
Adjust deploy script to check whether or not current instance is job node

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2607]
Before updating crontab, running migrations, collectstatic, and what not, we need to verify the deploy.bash script is being executed on the appropriate instance.

**Comment by owocki** [comment]
``------------------------
(gitcoin-37) ubuntu@ip-172-31-1-57:~/gitcoin/coin$ echo $JOBS_NODE
(gitcoin-37) ubuntu@ip-172-31-1-57:~/gitcoin/coin$
```

none of the existing servers have `JOBS_NODE == 1`
