### ISSUE TITLE
Add Artist Bio on Kudos Homepage

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2609]
_From @PixelantDesign on October 11, 2018 17:16_

## Add Artist Bio on Kudos Homepage

- [ ] Update Artist Bio with the following Information:

Octavian Todiruț
ConsenSys Product Designer @ Cellarius

I am a long time graphic designer, art director and product designer. A fancy way of saying "I am moving the mouse or pencil around, playing with shapes and colors." I like getting lost in everything art, photography, design and architecture and their history. When I don't do any of the above, I walk, travel or sometimes play a game.

- [ ] Include bio image inside of a Kudos shape

![me](https://user-images.githubusercontent.com/238235/46821782-b22de080-cd57-11e8-8d07-b40aaa5807c2.jpg)

_Copied from original issue: gitcoinco/gitcoin-erc721#178_

**Comment by octavioamu** [comment]
_From @owocki on October 11, 2018 17:51_

@PixelantDesign i wonder if we should be speccing out an artist explorer / profiles for kudos?  typically an artists story is a huge part of the purchase or art.

more near term, i wonder if Mladen wants to have his bio up on the site too.. since he did a lot of these!

**Comment by octavioamu** [comment]
_From @PixelantDesign on October 12, 2018 5:14_

I agree we should have an artist section. Maybe for v1.5/v2? 
Yes! We should feature all of the artists eventually.

**Comment by octavioamu** [comment]
_From @owocki on October 12, 2018 21:40_

agree its a v1.5 thing

**Comment by kuhnchris** [comment]
Maybe if you click on the Kudos Badge (right now it just jumps and sparkles) it could actually turn around and give some information about the Badge Creator?
