### ISSUE TITLE
QA demo site with status browser

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2611]
_From @owocki on October 10, 2018 23:11_

mobile: https://chat.status.im/#/room/!TSECabqXwnmkYVTfdX:status.im/$15391237399673aewOP:status.im

desktop: https://status-im.github.io/nightly/

_Copied from original issue: gitcoinco/gitcoin-erc721#174_

**Comment by octavioamu** [comment]
_From @owocki on October 10, 2018 23:15_

I can't seem to click this button in the mobile browser for some reason

![2018-10-10 17 14 19](https://user-images.githubusercontent.com/513929/46771284-17c69200-ccb0-11e8-9fd2-d79282009095.png)


and downloading status desktop just does not work

<img width="402" alt="screen shot 2018-10-10 at 11 56 47 am" src="https://user-images.githubusercontent.com/513929/46771208-bb637280-ccaf-11e8-94f1-bdf8154f62db.png">

**Comment by octavioamu** [comment]
_From @owocki on October 10, 2018 23:16_

@mbeacom can you add @StatusSceptre and @andytudhope to this repo and this thread pls?

**Comment by octavioamu** [comment]
_From @owocki on October 11, 2018 15:18_

@mbeacom can u add @rachelhamlin and @jeluard  too?

**Comment by jeluard** [comment]
Can you detail a bit more the issue? What exactly can’t be clicked and what should happen then?

**Comment by octavioamu** [comment]
Ohh this comes from and older repo, actually was solved and was a general mobile bug not only status.
