### ISSUE TITLE
Static handling and cache invalidation

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#262]
##### Description
Gitcoin currently uses CDN invalidation for asset changes.
We might want to consider switching static handling over to use the S3 or Whitenoise static storage backends for serving static with the `ManifestFilesMixin` to automatically hash static files.

##### Possible Implementation

- Decide on static serving strategy (S3, Whitenoise, or something like nginx)
- Create a custom static storage backend (mashup of `ManifestFilesMixin` and the parent storage backend)
- Add `STATICFILES_STORAGE` in settings.
- Modify existing static references from `{{ STATIC_URL }}` to: `{% static '<file>' %}`
- Modify deployment strategy to automatically collectstatic
- Remove CloudFront invalidation scripts

###### General implementation

- https://docs.djangoproject.com/en/2.0/howto/static-files/
- https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/

###### Possible strategies

- https://django-storages.readthedocs.io/en/latest/ (S3 support)
- http://whitenoise.evans.io/en/stable/ (Whitenoise)
- http://whitenoise.evans.io/en/stable/django.html
- https://github.com/antonagestam/collectfast (Alternative collectstatic handler)

**Comment by owocki** [comment]
i think this is mostly done..
