### ISSUE TITLE
Add ability for users to transfer already existing Kudos clones

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2624]
_From @jasonrhaas on September 26, 2018 18:18_

New use case:  We may want to give existing Gitcoin users already pre-minted Kudos clones that they can give out to the people working on their projects.

So this is a different flow than the regular "Send Kudos from Marketplace", since we (Gitcoin) are paying for the cost of the Kudos clone.

One possible scenario:
- Gitcoin "pre clones" a bunch of Kudos, and the Repo maintainer receives an email telling them that they have "Kudos available to send"
- The Kudos sit in a "voucher" type state, possibly in the marketplace, waiting for the Repo Maintainer to send the Kudos to someone.
- Once they have decided that they want to use the Kudos to send to someone, at that point it gets cloned and send to the final destination.

Technical notes:
- Transfer of kudos objects is straightforward in the Solidity Contract
- This is a new UX flow for the Gitcoin App
- Will have to do something similar to the "Indirect" send method, since we don't want the Repo Maintainer to have to pay for gas or the cost of the Kudos.  It will need to be a rawTransaction.
- Maybe we just have a Gitcoin Kudos "slush fund" that is filled with some Ether, that gets used to pay for these Kudos?  Ultimately if we own the Gen0 Kudos the money comes back to us anyway.

_Copied from original issue: gitcoinco/gitcoin-erc721#128_

**Comment by octavioamu** [comment]
_From @PixelantDesign on September 26, 2018 19:58_

This is what discussed yesterday on the call:

![kudosmarketing1](https://user-images.githubusercontent.com/238235/46105829-0f952f80-c1a5-11e8-8a00-2bf1bb58553f.png)

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 26, 2018 20:2_

Notes from Slack and possibly better way to implement this:

Pixelant [1:58 PM]
why do we have to pay for their gas?
to transfer once they want to use
I was talking with Joseph the other day about this...his suggestion was

mint the NFT, have it sitting in our wallet until preselected people can claim them (repo maintainers we like), and then when the NFT is claimed send it to maintainer address

**Note: The problem with minting the NFT before hand is that we need to pay the gas to do this.  Even though we don't need to pay the artificial "price of the Kudos" (since we own it), we would still have to pay gas.**

cc: @Joseph
Is this the same as your technical approach Jason?
@Scott Moore
Actually one thing we talked about was not minting them right away incase they dont redeem them.

jhaas [2:16 PM]
Similar, yea we could mint them all beforehand, and then only transfer it once they claim it.   And they would pay the gas to transfer.  In fact this might be more simple than our current method of Indirect Send.  I think we could mint them, they sit in “Gitcoin’s wallet”, and we “approve” the transfer to the repo maintainer

Pixelant [2:28 PM]
yes lets do simpler
But would we have to pay if its not redeemed?
@octavioamu on the kudos detail, the kudos seem much bigger for some reason

jhaas [2:33 PM]
Well the good thing is that if we own the original Kudos, we are essentially paying ourselves :slightly_smiling_face:
So when the clone happens, the money gets transferred to the original Kudos owner, which is us.
So its free for us essentially.  If someone _else_ clones a Gen0 Kudos that we own, the money goes into our account.

**Comment by octavioamu** [comment]
_From @jasonrhaas on October 2, 2018 1:17_

So this is pretty easy to do on Open Sea.

https://rinkeby.opensea.io/assets/0x3c147acf80b01d08dcb05038a7d9537adc12b39d/101/transfer

Can we just rely on Open Sea for handling the asset transfers?  We just need to make sure we are keeping the data trail in Gitcoin.  Related to https://github.com/mbeacom/gitcoin-erc721/issues/131

**Comment by octavioamu** [comment]
_From @PixelantDesign on October 8, 2018 20:20_

@owocki for feedback

**Comment by octavioamu** [comment]
_From @owocki on October 8, 2018 21:14_

@PixelantDesign i'm presuming this isnt going into the devcon launch, so we don't need to do feedback on this now.. am i mistaken?

**Comment by octavioamu** [comment]
_From @PixelantDesign on October 12, 2018 6:21_

agree, perhaps v1.1 since it'll encourage sending.

**Comment by PixelantDesign** [comment]
An alternate idea (maybe simpler) could be sending the email with pre selected Kudos, and once clicked directing the user to a tab where we show the 5 kudos we've granted them. 

Thoughts @owocki @octavioamu ?
