### ISSUE TITLE
if someone has more than one of the same kudos, it should 'stack'  on the profile to save space

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2633]
_From @owocki on September 20, 2018 18:15_

like how uber does it
![image_from_ios](https://user-images.githubusercontent.com/513929/45838375-d2293180-bcce-11e8-8b7f-8732e5c40e02.png)

_Copied from original issue: gitcoinco/gitcoin-erc721#91_

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 20, 2018 20:0_

@octavioamu How hard do you think this one is?  I've already had a scenario where this would super nice to have.

![image](https://user-images.githubusercontent.com/7018237/45843698-e3316d00-bce5-11e8-9421-60801d055e2b.png)

**Comment by octavioamu** [comment]
Technically is a fun thing to do. But I had commented in slack the problem is about the public comments, in the example comments are separated, here we need to be able to read comments behind each kudos, so we can group kudos images but not the comments. We need an UX solution for that.

**Comment by octavioamu** [comment]
another problem of grouping is we need to change also the pagination behavior to group it together and not in diff pages.

**Comment by octavioamu** [comment]
@owocki @PixelantDesign is this v1 ?

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 29, 2018 16:44_

The good news is that since its purely a front-end effect, its an easy change to make in the future without affecting any core functionality.

Might have to do something fancy like a flyout or modal, because there might be information that the user wants to see on each Kudos, like the comments for example.

**Comment by octavioamu** [comment]
_From @owocki on October 1, 2018 23:51_

i dont feel super strongly about it being v1.  if its an easy lift (less than an hour or two), and we have time..  then its fine to include it

**Comment by PixelantDesign** [comment]
<img width="605" alt="screen shot 2018-11-08 at 3 56 54 pm" src="https://user-images.githubusercontent.com/238235/48227536-988cb280-e370-11e8-96e5-f8bae814db9e.png">

**Comment by owocki** [comment]
these look really good!
