### ISSUE TITLE
Integrate Kudos Into Bounties - V1

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2635]
_From @PixelantDesign on September 11, 2018 12:28_

**Integration Points**
- Profile drop down below Send Tips --"Send Kudos"
- Single Payout Screen below tips

**Proposal**
- Implement typedown to find Kudos as seen in the flow below.
- Implement alert to notify users that there will be 3 separate transactions if tip and kudos are also included in bounty payout.

![integrate kudos](https://user-images.githubusercontent.com/238235/45360066-6ba06700-b59c-11e8-997f-a446c207dbb1.png)

**Alternate Ideas**
A simple link to the Kudos market place is the lowest lift option but not a seamless and a less ideal user experience.

@jasonrhaas @owocki @octavioamu 

[Kudos Integration Final.zip](https://github.com/mbeacom/gitcoin-erc721/files/2443432/Kudos.Integration.Final.zip)

![kudos integration_final](https://user-images.githubusercontent.com/238235/46433073-eb45cf80-c71d-11e8-8cdd-ec2b8c16f05c.jpg)

_Copied from original issue: gitcoinco/gitcoin-erc721#81_

**Comment by octavioamu** [comment]
This is great @PixelantDesign should be able to send more than one kudos maybe?

**Comment by octavioamu** [comment]
_From @owocki on September 11, 2018 18:42_

looks good to me!  i'd add that it might be helpful to see a preview of the kudos badge in the 'type down' area before you select it.

also that you might want to detach your kudos (so maybe it's worth adding an (X)  next to the kudos on 'return search' and 'display alert'

**Comment by octavioamu** [comment]
_From @PixelantDesign on September 11, 2018 18:56_

yes very true on the ^ @owocki . I'll clean up the design and repost this. @jasonrhaas anything from your end?

@octavioamu yes sending more than one kudos would be cool for v2.

**Comment by octavioamu** [comment]
Use as base the component we are using select2
https://select2.org/data-sources/ajax

![image](https://user-images.githubusercontent.com/1358093/45382210-f190d200-b5dd-11e8-8fac-6293d84cba80.png)

So we can do things like the autocomplete users. and the search input shouldn't disappears when something is found.

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 11, 2018 19:17_

We might need to display more info about the Kudos to help the user make a decision about if they want to send it.

For example, might want to also show rarity and how many kudos are still available for cloning.  As far as the "Clones Available" limitation, that would have to be a check on the backend before sending to make sure that we are able to send the Kudos.  Would rather have it fail immediately and display a message to the user than have the contract transaction fail.

**Comment by octavioamu** [comment]
@jasonrhaas Maybe just show the clonables ones in that search box

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 11, 2018 19:52_

@octavioamu Yea that can be a backend query, just exclude the ones where `num_clones_available == 0`

**Comment by octavioamu** [comment]
_From @jasonrhaas on September 25, 2018 0:35_

Bringing over Kevin's comments from the duplicate ticket:

```
in order to get more traffic into kudos, we need to integrate inline sending of kudos on

tips
bounty basic payout
bounty advanced payout
```

**Comment by octavioamu** [comment]
I want to bring this here to discussion to have an idea about the best approach.
 
Right now we have the need to make the kudos into bounties, so payout forms will have the option to add kudos to the payment.

I was discussing this with @thelostone-mc  and he told me that in product side there are 2 tasks related to payout https://github.com/gitcoinco/web/issues/2240 and https://github.com/gitcoinco/web/issues/2294 

**Should we wait until that is deliver or we should do  this task now and then fix/change whatever is needed ?**

**Comment by octavioamu** [comment]
WIP PR needed for this task https://github.com/gitcoinco/web/pull/2296

**Comment by octavioamu** [comment]
_From @owocki on October 1, 2018 19:14_

i dont understand what the technical dependancies are between https://github.com/gitcoinco/web/issues/2240 , https://github.com/gitcoinco/web/issues/2294 , and this task... but my instinct says that, given the tight timeline to get to a MVP of kudos, that they should be decoupled .

my hope had been that we could have a relatively independent kudos_inline_send django template + css /js that could be included into a new payout template, but please push back on me if this is not possible.

note: all i need is the HTML/CSS, plus some javascript for selecting a kudos to attach to a basic payout, and i believe i can do the rest.

**Comment by octavioamu** [comment]
_From @owocki on October 1, 2018 19:15_

note: i'd also be more than happy to just integrate kudos_inline_send with basic payout / tips if that reduces the complexity of having gto integrate it with advanced payout (which... to your point, is in flux right now)

**Comment by octavioamu** [comment]
That feature is very integrated with the whole payment, the changes are messing up with the choice of the person being pay, the total price so Kudos will mess with all that things too. So the point is going to be rework but anyway I will do it in the best way possible to avoid big rework. 
My principal point is not avoid doing it now, just make sure everyone knows is not going to be just a merge work, is going to be a rework to take again the user from the select2 autocomplete and that kind of stuff.

**Comment by octavioamu** [comment]
_From @owocki on October 1, 2018 19:57_

i'm happy to handle the merge work.. i really just need the module spliced and the basic JS select functionality working.

**Comment by octavioamu** [comment]
Bounties are not working on Kudos project because of this https://github.com/gitcoinco/web/issues/2339 until then this task is blocked :(

**Comment by Anish-Agnihotri** [comment]
Hey, I'm the developer behind #2294. Apologies, didn't notice that you had referenced it until today. Hope I am not late. 

If you have any concerns, questions, ideas - feel free to let me know and let's have a chat :)!

**Comment by octavioamu** [comment]
Hey @Anish-Agnihotri thanks to report, don't worry this issue was imported from the old private kudos  repo, is already done I will close it. 
Thanks for your attention.
