### ISSUE TITLE
Team Alignment on Taxonomy

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2649]
_From @PixelantDesign on May 29, 2018 3:5_

As a core team, we should understand and use the same terms as it relates to the erc-721 project.

Minted
Token
Avatar

Define any commonly used terms for this project

_Copied from original issue: gitcoinco/gitcoin-erc721#28_

**Comment by octavioamu** [comment]
_From @owocki on May 29, 2018 21:25_

token = kudos.  lets start calling them kudos since thats what they are gonna be called
minted -- creation of new kudos from thin air
avatar -- from the avatar flow

**Comment by octavioamu** [comment]
_From @owocki on May 29, 2018 21:26_

lets deprecate 'artifact' and 'token' and start calling them kudos

other terms:
send 
receive

**Comment by octavioamu** [comment]
_From @owocki on May 29, 2018 21:30_

what do we like more.  commissioned or minted?

**Comment by PixelantDesign** [comment]
Commissioned makes sense for new kudos.
