### ISSUE TITLE
As a user, I want to 'equip' my artifact on my avatar, so I can show it off in my avatar.

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2651]
_From @owocki on May 22, 2018 15:8_

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to 'equip' my artifact on my avatar, so I can show it off in my avatar.

### How it Works

In this view of the world, artifacts have two visual assets associated with them.

* badge -- shown on their profile
* equipped_asset -- shown on their avatar and in their avatar builder.

We would have to augment the artifact creation flow, and the artifact listings to update for these two visual assets.

We would also have to update the avatar builder to allow users to equip these assets.

### Example Use Case

For example, if I got a badge called "ruby knight", it could come with a knight suit that I could them equip on my gitcoin avatar.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

_Copied from original issue: gitcoinco/gitcoin-erc721#23_

**Comment by octavioamu** [comment]
_From @thelostone-mc on May 29, 2018 12:22_

You mean this would change the avatar rather than simply appending the badge to the avatar ?

**Comment by octavioamu** [comment]
_From @owocki on May 29, 2018 21:29_

>You mean this would change the avatar rather than simply appending the badge to the avatar ?

yes change.  but not *just* change... make it BADASS

**Comment by octavioamu** [comment]
@owocki @PixelantDesign "equipped_asset -- shown on their avatar and in their avatar builder." sounds really nice to have.

**Comment by thelostone-mc** [comment]
@octavioamu YAY

**Comment by PixelantDesign** [comment]
hmmm we have kudos on the page already...not sure im following.

**Comment by owocki** [comment]
hmm this seems related to https://github.com/gitcoinco/web/issues/3032

i like this => <img src='https://user-images.githubusercontent.com/1358093/48108293-b996bb80-e229-11e8-88b7-ac2bd0ccff4a.png'> -- it'd be interesting to have avatars across the site have their kudos shown in this capacity (so you can see ppls skills at a glance without having to click through).. but maybe its too much and we should add a tooltip on hover that allows you to preview someones skills/profiles before clicking through.  (similar to what we have on the current issue explorer

as for [this](https://user-images.githubusercontent.com/1358093/48108039-c6ff7600-e228-11e8-92b3-4c9a65e0de3f.png) mockup , the kudos' look a little awkward right there.  when i originally shared the idea, i was thinking about the kudos badge having an 'attachmenet' to it.  

to my mind, what that means, is if i gave @octavioamu a "knight" kudos, he would get the traditional hex sticker.  but he would also get a special avatar asset, a suit of shining armour, that *only ppl who have the kudos* have.  

again, none of this is priority right now.. just sharing ideas bc i think kudos/avatars are going to be profit centers for us IFF virtual goods become a business model for us.  and the integration of kudos/avatars could be a powerful hook.

**Comment by PixelantDesign** [comment]
I like the idea behind it. I think I just saw this on another ticket.
What if we displayed a flyout on hover of any avatar? This could contain Kudos.

**Comment by owocki** [comment]
> What if we displayed a flyout on hover of any avatar? This could contain Kudos.

I really like this idea

**Comment by PixelantDesign** [comment]
![kudosflyout](https://user-images.githubusercontent.com/238235/49321172-d1cdc380-f4d3-11e8-9441-2b2358ae08ce.png)
