### ISSUE TITLE
Design - Find out why a contributor stopped work, or why a funder cancelled a bounty

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2668]
It would be great if we could encourage contributors/funders to provide a reason why they stopped work/cancelled a bounty, so that we could find ways to solve the problems and improve.

One idea is to have a simple prompt that pops up whenever a contributor clicks on 'Stop Work' or whenever a funder cancels a bounty.

Contributor stopping work:
![extra large- desktops - 12 col](https://user-images.githubusercontent.com/19514207/47867158-abb4f500-de3b-11e8-84c3-423f90a5416b.png)

Funder cancelling bounty:
![extra large- desktops - 12 col copy](https://user-images.githubusercontent.com/19514207/47867145-a48de700-de3b-11e8-9654-318969d6b635.png)

Notes:
- It should be non-intrusive, maybe make it optional?
- Maybe it would also be useful to send the reasons to the respective parties (send the reason why contributor stops work to the funder, send the reason why funder cancels a bounty to the approved worker). Maybe through email? or on the dashboard?

**Comment by frankchen07** [comment]
I believe there's an automatic email that's send to funders who cancel bounties, and the responses are sent to @owocki - but I might be recalling incorrectly.

**Comment by owocki** [comment]
there is an email sent when someone cancels a bounty, but not when someone stops work

**Comment by PixelantDesign** [comment]
I think it's a great idea and will help us understand why work is stopped/abandoned.

**Comment by PixelantDesign** [comment]
@willsputra should we explore a handful of drop down options as well as provide a field for free writing? 

Thoughts @frankchen07 ?

**Comment by willsputra** [comment]
@PixelantDesign a dropdown with a list of common abandonment reasons sounds good.

it could be something like:
*Stop Work*
( ) I no longer have time to do the work
( ) There was no response from the funder
( ) I mistakenly started work
( ) Others [Free text]

*Cancel Bounty*
( ) The scope of work changed
( ) It is actually done but not marked a so
( ) I found an alternative solution
( ) It has been abandoned by a contributor
( ) No one applied for work
( ) Others [Free text]

@frankchen07 Do let me know if I can improve the above list of reasons 😁Also, as Alisa mentioned, any recommendation on where to store the responses?

**Comment by frankchen07** [comment]
Under cancelled bounties, the ones on the sheet came to be by data analysis and then individually checking cancelled bounties. I shuttled some under more broad categories to keep the analysis a bit simpler, but below is the wording and specificity that I would use.

I paid out the developer for his/her work and want to close the issue on Gitcoin.
The scope of work changed.
An alternative solution (merged commit/patch) solved the issue.
I decided to bring the issue to our internal team.
I am unable to change certain details on the bounty I want changed.
The bounty had no workers / was consistently abandoned. 
The bounty was available only under special circumstances (e.g hackathon).
The quality of the submitted work was not up to par.
Other (free text)

For capturing the responses in the admin panel, what do you mean by that (what might that look like?)

**Comment by frankchen07** [comment]
Basically, the way I see it working is:

1. a bounty is cancelled: 

![screen shot 2018-11-20 at 00 21 45](https://user-images.githubusercontent.com/7516920/48760423-c6200880-ec5a-11e8-9460-c9f1ea0e8643.png)

2. The radio buttons for cancellation reasons pops up, the answers selected end up triggering POST requests that populate the administration area (perhaps in json format) and updating the data model, that looks like this:

![screen shot 2018-11-20 at 00 21 51](https://user-images.githubusercontent.com/7516920/48760275-5873dc80-ec5a-11e8-8c7d-b45c933f5374.png)

which would also reflect in our data:

![screen shot 2018-11-20 at 00 27 07](https://user-images.githubusercontent.com/7516920/48760511-097a7700-ec5b-11e8-87ec-b7d5c1d4353e.png)

3. Basically the user sees something, interacts, and sends data to update the existing data model, so there's interaction between `views.py` and `models.py`. This is based on my rudimentary understanding of Django / engineering - would love for a real engineer (please stand up) to clear up anything confusing. (@mbeacom, @thelostone-mc)

**Comment by willsputra** [comment]
Adding Stop Work reasons from the community to the list

I reached the limit of open bounties and wanted to work on another bounty
The scope of work deviated from the initial bounty
There was no response from the funder
I no longer have time to do the work
Someone else was approved / reserved for the bounty
I had technical issues while doing the work (e.g. issues setting up env, incomplete docs, etc.)
I saw other applicants had better solutions
I mistakenly started work
Others [Free text]

@frankchen07 maybe we could start with this? lemme know if the wordings could be improved too 🙂

**Comment by willsputra** [comment]
Build ticket: #2895

**Comment by PixelantDesign** [comment]
Thanks @frankchen07 !

**Comment by PixelantDesign** [comment]
@willsputra will you add the source files on #2948?
