### ISSUE TITLE
Month over month stats on gitcoin.co/results don't add up to total platform value

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2669]
**Describe the bug**

1. The month over month stats on gitcoin.co/results don't add up to the total platform value.
2. There are negative bar values for the months of May, July, and September (all 2018).
3. 2018 May is mislabeled as 2018 June.

**To Reproduce**
See gitcoin.co/results

**Expected behavior**

![screen shot 2018-10-31 at 14 39 12](https://user-images.githubusercontent.com/7516920/47820759-b24c4b00-dd1b-11e8-8646-1b53a4d5db8e.png)

I input the values in to a table for easier reading and math.

| Date | Tips | Open | Started | Completed | Cancelled | Row Totals |
| --- | --- | --- | --- | --- | --- | --- |
| 17-Dec | 2011 | 903 | 2329 | 5534 | 1203 | 11980 |
| 18-Jan | 3082 | 387 | 0 | 10396 | 600 | 14465 |
| 18-Feb | 4309 | 6516 | 4801 | 5906 | 1790 | 23322 |
| 18-Mar | 3993 | 0 | 402 | 20484 | 1363 | 26242 |
| 18-Apr | 6116 | 7869 | 3888 | 16858 | 2918 | 37649 |
| 18-May | 5984 | 2994 | 0 | 29135 | 1419 | 39532 |
| 18-Jun | 7554 | 24629 | 5786 | 31884 | 6059 | 75912 |
| 18-Jul | 24189 | 4607 | 3065 | 55209 | 11030 | 98100 |
| 18-Aug | 18366 | 16940 | 4820 | 53645 | 10869 | 104640 |
| 18-Sep | 35840 | 5114 | 5795 | 113692 | 35780 | 196221 |
| 18-Oct | 31658 | 40213 | 13019 | 94903 | 26152 | 205945 |
| Column Totals | 143102 | 110172 | 43905 | 437646 | 99183 | 834008 | 

Month over month bar chart broken down by issue status should add up to ~$375,337.41 (as of 2018-10-31). By looking at the bar chart, it seems the bars are the non-cumulative values for each month (since October is MTD, month to date). If we take the sum of just the completed work, tips, and cancelled bounty amounts from the bar chart, we come up with a sum of $680k. 

I take completed, cancelled, and tips only because they are static statuses (if they happened in that month, that's it, they happened in that month, versus the example where something can be opened in June and counted in June, but get completed in July, where it would then be counted as complete but no longer open).

I entertained the thought that the bars were cumulative, but that doesn't make sense either, since completed value amounts shouldn't decrease month over month. 

**Desktop:**
- OS: macOS High Sierra 10.13.4
- Browser: Google Chrome
- Browser Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by owocki** [comment]
Thanks for bug report!  We should do some data sleuthing here.

> The month over month stats on gitcoin.co/results don't add up to the total platform value.

FWIW, the 'total platform' value is all of the open, started, completed, submitted work, summed over time.

> There are negative bar values for the months of May, July, and September (all 2018).

This is expected, if there is negative open work for a month (ie. at the end of month X there is 10k in open work, and at the end of the month there is 7k open work, then the net for that month is -3k.
