### ISSUE TITLE
create the tip badge tool for user to embed the tip badge into their project

### ISSUE THREAD

**Issue by gasolin** [gitcoinco/web#267]
As a User I want to embed a badge into my project so user could donate me some cryptocurrency via click the badge.

##### Description

Create a page to help user embed tip badge into their github project.

##### Possible Implementation

The possible outputs are

[![](https://img.shields.io/badge/⚡️-Tip_Me-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin)

[![](https://img.shields.io/badge/💵-Tip_Me-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin)

[![](https://img.shields.io/badge/☕️-Buy_Me_Some_Coffee-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin)

[![](https://img.shields.io/badge/🍺-Buy_Me_Some_Beer-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin)

User enter their github username, select preffered badge and slogan, and we generate the following code for them
```
[![](https://img.shields.io/badge/⚡️-Tip_Me-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin)
```

**Comment by owocki** [comment]
@coderberry what do you think of this?

**Comment by gasolin** [comment]
It might work like https://docs.travis-ci.com/user/status-images/

For MVP we can putting a single badge, like: 


# Get cryptocurrency donation by 2 steps!

You can easily get a variety of cryptocurrencies donation in you open source project by embedding a Gitcoin Tip badge into your project.

## Steps

  1. Enter your github user name here to generate the badge 
[Input filed] (with variable `username`)

  2. Copy the follwing text and paste into your project's `Readme.md` file

```
[![](https://img.shields.io/badge/⚡️-Tip_Me-brightgreen.svg)](https://gitcoin.co/tip?username=${username})
```

## Preview:

 [![](https://img.shields.io/badge/⚡️-Tip_Me-brightgreen.svg)](https://gitcoin.co/tip?username=gasolin) 

[More tools >>](https://gitcoin.co/tools)

**Comment by owocki** [comment]
this is a really good idea.. i think we just need to build the `username` (and maybe `amount`) fields into the /tip flow

**Comment by owocki** [comment]
and then figure out how to market it

**Comment by owocki** [comment]
moreso than actually creating this badge... i think is getting the community to adopt it and start using it in their readmes.. probably worth doing a little thinking about that soon...

cc @pixelantdesign

**Comment by JeremiGendron** [comment]
I'm not able to get select2 to perform a default ajax search for the passed username in `user-search.js`. Currently, the setup is to send requests to `/tip` containing `?username=something` to `send2.html` (with optional param `&amount`. I haven't found a clean way to get the select2 element to natively fetch the `username` value, which would be passed via DOM querying.
