### ISSUE TITLE
Design - Improvements for Welcome to Gitcoin page (the first time users open the Issue Explorer)

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2680]
Currently, the first time users open the Issue Explorer, they are greeted with this Welcome to Gitcoin page, showing how it works, tips & tricks, and three recommended bounties.

![artboard](https://user-images.githubusercontent.com/19514207/47952046-4a5c6580-dfa4-11e8-992f-2192b6f88685.jpg)

A couple of problems:
1. The top CTA is not that obvious
2. Users might think that there are only three issues available, because (a) it's not clear that these are just recommended bounties and not all, (b) no indication that more bounties exist, (c) no clear CTA for me to view more bounties

**Proposed Solution**

![artboard copy](https://user-images.githubusercontent.com/19514207/47952093-3a915100-dfa5-11e8-9975-6f592750b366.jpg)

1. Align the top CTA to the left so it's easier to spot
2. (a) Add 'Here are some bounties matching...' title, to make it clear that these are just recommended bounties
(b) Add 'X more bounties worth $Y are available', to indicate that more bounties exist
(c) Add 'View more bounties' CTA. 'View more bounties' and 'Got It' could both link to the same url (Issue Explorer)

**Comment by kuhnchris** [comment]
Hey ya @willsputra !
This is a little bit problematic. Right now this is just an included page within explorer, so the changes at the top are OK - but the ones at the bottom are rather problematic. We would need to create a "own" page for the "View more Bounties" + more information and redirect everything there. Or are you trying to go to another page I'm not aware of? I'm coming from "/onboard/contributor".
![image](https://user-images.githubusercontent.com/761911/47958574-01210b80-dfce-11e8-9633-19ddac4b6075.png)

Thanks!
-Chris

**Comment by willsputra** [comment]
Hey @kuhnchris thanks for looking into this! :)

Nope, that's the page I was talking about, coming from "/onboard/contributor".

So when that ftux "Welcome to Gitcoin" page appears, we're currently hiding the search or filters and also limiting the results to 3?

**Comment by PixelantDesign** [comment]
I like the suggested improvement @willsputra. The header makes it clear that it's recommended. We did keep it short intentionally so that after the user sees 3 possible issues, they could see more on the issue explorer.
