### ISSUE TITLE
Ability to edit tags after issue creation

### ISSUE THREAD

**Issue by adamskrodzki** [gitcoinco/web#2692]
### User Story

As owner I wanto to be able to edit tags in bounty on gitcoin.co so i can fix my mistake during bounty creation

### Why Is this Needed

It is very easy to make mistake or forget some tags and therefore make bounty hard to find in search

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:FEATURE

### Current Behavior

There is no option to edit tags in once created bounty

### Expected Behavior

 option to edit tags in once created bounty

**Comment by willsputra** [comment]
I guess we could put it under 'Edit Issue Details'

![edit1](https://user-images.githubusercontent.com/19514207/48012233-89351b80-e15c-11e8-8f9c-978574f4487f.png)
![edit2](https://user-images.githubusercontent.com/19514207/48012386-d618f200-e15c-11e8-94e7-827ca2521a2b.png)

What do you think? @adamskrodzki @PixelantDesign 

somewhat related: https://github.com/gitcoinco/web/issues/2531

**Comment by PixelantDesign** [comment]
Thanks for opening this @adamskrodzki! That works @willsputra!

What do you think @frankchen07 ?

**Comment by frankchen07** [comment]
Yes, I think having the ability to edit the skillset keywords is important, especially since that is a form of marketing to the contributor. 

Great catch, and I like using the copy from the existing funder form keywords field.

**Comment by PixelantDesign** [comment]
Current Edit Issue Details does not allow me to edit tags.
<img width="1029" alt="Screen Shot 2019-06-11 at 6 25 44 AM" src="https://user-images.githubusercontent.com/238235/59264763-d3f6a480-8c11-11e9-96e9-7ac2e3686d2a.png">

Solution - Add tags field from the fund issue form
<img width="1024" alt="Screen Shot 2019-06-11 at 6 27 18 AM" src="https://user-images.githubusercontent.com/238235/59264838-ff798f00-8c11-11e9-80d6-c4fd22808977.png">

**Comment by rafalkowalski** [comment]
@PixelantDesign I can work on it
