### ISSUE TITLE
Auto-generate categories & colored variants of SVGs

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2693]
### User Story

As a developer and artist, I want to free myself from the burden to edit utils.py and the javascript files whenever a new category and/or avatar item is added to the list, so that I can actually do some proper work, instead of wasting my time in the avatar builder-builder.

### Why Is this Needed

Currently loads of files need to be edited/found if we add a new category or item and/or color variant.

### Definition of Done

- [ ] Create or recycle a script to generate colored SVGs from "template" SVGs (see August/September Bounty for reference)
- [ ] Create automated step within migration and/or deployment process to automatically generate new SVGs (either on the fly or periodic or on a github hook)
- [ ] Data is properly loaded and saved into storage
- [ ] 100% linter
- [ ] not breaking anything important

**Comment by owocki** [comment]
is it better to create all these scripts / steps in the build process, or should we just serve these assets out of the DB instead of the filesystem? https://github.com/gitcoinco/web/issues/2781

**Comment by kuhnchris** [comment]
Preferably from the filesystem, just caching it in redis for a while and invalidate it with a crontab to regenerate it to get "new" assets (so we wouldn't even need to restart to get new assets).
