### ISSUE TITLE
Profile has an identity crisis

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2694]
**Describe the bug**
My profile pretends to be someone else

**To Reproduce**
Be me

**Expected behavior**
Be myself

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48015860-638f1e80-e12a-11e8-9e8c-45f89eb27b1d.png)

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Chrome
- Browser Version Latest Stable

cc @owocki

**Comment by PixelantDesign** [comment]
Weird! So we're pulling someone else image @kuhnchris ?

**Comment by owocki** [comment]
looks like it's an old avatar

**Comment by mbeacom** [comment]
I'll check this out and shoot out a fix shortly.

Thanks for reporting @kuhnchris

**Comment by kuhnchris** [comment]
yeah, seems like an old or a different avatar. Thanks for looking at it @mbeacom

**Comment by owocki** [comment]
looks to me like https://gitcoin.co/dynamic/avatar/owocki/ is returning the first avatar i ever made... 

in the top right, my avatar points directly to S3 => https://c.gitcoin.co/avatars/7f3038d3cea9c3e9b09350ad97442fe3/owocki.svg

@mbeacom is there an easy fix for this?

**Comment by owocki** [comment]
looks to me like the PNG is not being updated when there is a new avatar saved 

http://bits.owocki.com/b5115070f021/Screen%20Shot%202018-11-07%20at%203.31.25%20PM.png

**Comment by owocki** [comment]
```
In [6]: avvy.convert_custom_svg()
ERROR 2018-11-07 22:34:38,196 models 11203 140071821223680 Avatar conversion error while converting SVG!

```

i think its related to this line https://github.com/gitcoinco/web/blob/master/app/avatar/models.py#L81-L88

**Comment by kuhnchris** [comment]
I think that the entire avatar system is a bit bugged and bothersome right now (to maintain and seems to have a couple of bugs). Is there a reason why some avatars are on S3 and some dynamically generated? The easiest would be to generate the avatar directly on the fly without storing the file inbetween (it's basically just a couple of SVG layers anyways...), that would also solve a couple of cache issues between old/new avatars and display states in bounties.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2734/files should fix this

**Comment by kuhnchris** [comment]
Will check when I return home, thanks!

**Comment by thelostone-mc** [comment]
Closing this out as it the profile avatar matches the one in the activity aka it's fixed ^_^
https://gitcoin.co/issue/AlexHartford/AlexHartford.github.io/2/1686

**Comment by kuhnchris** [comment]
Can confirm, is fixed now. :-)
