### ISSUE TITLE
ENS feedback - make it more clear what ENS does

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2699]
Yesterday at Devcon's ENS session they promoted

https://gitcoin.co/ens/

Where you can link your github name (e.g., REDACTED) to an ethereum address

e.g.,

REDACTED.gitcoin.eth is now resolving to
0xREDACTED

It might be my stupidity, but there should be a warning that

"hey, your github name XXX will now be linked to this metamask address YYY,
so people can easily know how much ETH you have and what things
you have done. This might be a privacy issue. Are your really OK?"

In fact, now my account is linked and now I regret it. Is there a way for me
to change so that REDACTED.gitcoin.eth resolves to some other address?
(the history will still be in blockchain, but still I don't want it to be the current
resolved address)

**Comment by kuhnchris** [comment]
That... kind of depends. If people are stupid enough to tatoo the name of their crush onto their butt they also cannot blame the tatoo artist if things do not turn out the way one expected them to turn out... 
You could put up a extra warning window before confirming ála:
"WARNING! This will INDEFINITLY link this name (your name here) to this address (your address here). This may be a privacy concern if you want your account and/or identity hidden! Please make sure you know what you are doing by entering your username below:"

or something like that. (_OK that may be a bit extreme_)
