### ISSUE TITLE
homepage glitch on ipad -- scrolljacking makes scrolling on ipad feel unnatural

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2701]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
scrolljacking makes scrolling on ipad feel unnatural

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
get an ipad and go to gitcoin.co, try to scroll on it

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
scroll is natural

**Comment by thelostone-mc** [comment]
Haha @SaptakS do you have an ipad ? :P
