### ISSUE TITLE
Kudos - Add Proper Function Name for Metamask Display

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2706]
### User Story

As a user I want to see that my Kudos transactions in metamasks are not **unknown functions**.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Currently sucessful Kudos transactions in Metamask show as **Unknown Function** - which gives an uneasy error like feeling. We need to add a line of code so that this language is customized to Kudos Sent or similar.

<img width="338" alt="screen shot 2018-11-06 at 8 45 30 am" src="https://user-images.githubusercontent.com/238235/48068254-5b71c600-e1a0-11e8-8c7f-ad8b0cf2d81e.png">

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
Send a Kudos and check your metamask to see the text displayed as unknown function.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
A user would probably expect something more descriptive and related to the action like, Kudos Sent.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Add a line of code so that this description is updated.
- [ ] Add additional code for failure cases.
- [ ] Review with Kudos core team.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
<img width="323" alt="screen shot 2018-11-06 at 8 42 20 am" src="https://user-images.githubusercontent.com/238235/48068102-e8684f80-e19f-11e8-987d-ce54c267dc07.png">

**Comment by kuhnchris** [comment]
Hi there. I tried to Verify the code in Etherscan, but sadly, the version I came up with doesn't relate to the currently deployed Kudos contract. Basically the same contract that was deployed needs to be verified on Etherscan. Then you could actually go ahead and do it. Also, we would need to register the function at a certain contract. See answer on this discussion: 
https://ethereum.stackexchange.com/questions/59678/metamask-shows-unknown-function-when-calling-method-send-function
