### ISSUE TITLE
Kudos - Display Image Associated to Owner Address 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2707]
### User Story

As someone looking at Kudos, it's hard to tell who the address belongs to.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Feedback from Andres (Kauri). It was hard to tell if a Kudos was minted by Kauri or minted by a Gitcoin team member.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)

<img width="462" alt="screen shot 2018-11-06 at 8 49 04 am" src="https://user-images.githubusercontent.com/238235/48068579-2ade5c00-e1a1-11e8-8330-e317265eed65.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Display an avatar/icon in front of the address.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Add 16x16 avatar icon in front of the address
- [ ] Ensure that anytime an address is displayed in other places, there is a 16x16 icon in this format.
- [ ] Review with a Kudos core team member

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
not 100% sure on this one: you want to see if this one is a new one or a regifted one, or you generally want to see the owner address avatar (if on file)?

**Comment by PixelantDesign** [comment]
Just showing the associated avatar to the owner address @kuhnchris

**Comment by octavioamu** [comment]
Yes as @Anish-Agnihotri said we don't have that association or even that wallet address belongs to a user.
