### ISSUE TITLE
Kudos - Stretched Email Image 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2708]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
View Kudos Received email in Gmail browser

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

Expect to see an image that is proportioned.

**Desktop (please complete the following information):**

- OS: Mojave
- Browser Safari

**Definition of Done**

- [ ] Fix visual bug
- [ ] Double check responsive
- [ ] Review with core team member

**Additional context**
<img width="924" alt="screen shot 2018-11-06 at 9 03 05 am" src="https://user-images.githubusercontent.com/238235/48070404-d25d8d80-e1a5-11e8-95ad-be2869ce872a.png">

**Comment by kuhnchris** [comment]
https://github.com/gitcoinco/web/blob/931aea7218cefa2938604c0e34032776ab703595/app/retail/templates/emails/new_kudos.html#L127 here should be the culpit!
But... is there a way to try this out via command line to actually send the mail?
cc @mbeacom because he's knows da wey.
