### ISSUE TITLE
Issue status not updating on profile page

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2709]
**Describe the bug**

In some cases the status of a given issue is different on the profile versus issue page.

*Profile Page*: https://gyazo.com/2bf0bb7c856b80d66b7c786961d878d0 

*Issue Page*: https://gyazo.com/5584b7ae5ae2ad108cb23cc87e93f4e5

**Expected behavior**

The status should be the same :p

**Comment by kuhnchris** [comment]
Wait, that's intended, isn't it?
The profile page shows your *activity*, which is, work submitted. The *issue page* shows the status of the *issue*. What may be missing is that it doesn't show that you received payout for that bounty.
