### ISSUE TITLE
Abandonment activities with empty price tags

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#2711]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

https://gitcoin.co/activity some of the activities are without price.
We should omit price/denomination for these abandonment activities.

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
https://gitcoin.co/activity

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Tags contain prices or don't show tags.

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/1358093/48082418-b542b200-e1d9-11e8-8fd6-60135128849e.png)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by kuhnchris** [comment]
Awww, not filling out the template properly? :-(

https://github.com/gitcoinco/web/blob/3a9514f48ec3d6dbbe1d46a659dfd5f613be0680/app/retail/templates/shared/activity.html#L65

Here is the pain point to fix. basically the div tag token should be capsulated and not displayed when there is no data for it.

**Comment by octavioamu** [comment]
Not really, abandonment doesn't have value so is getting into the else 
```
{% else %}
            <span>{{row.metadata.value_in_token_old}}  - {{row.metadata.value_in_token}}  {{row.metadata.token_name}}</span>
            {% endif %}
```
But also doesn't have any value so is just showing the `-`

**Comment by kuhnchris** [comment]
Still doesn't change the fact that "- " (because all the values are empty) and USD (below) will be displayed.

**Comment by kuhnchris** [comment]
I agree, we should not show the tags. We could show the "action" color-coded (like red for Abandonded, Green of completed, accepted, submitted, and gray for applied or funded) instead of the bounty value. Especially since the bounty value can change it doesn't make that much sense to put it in there anyways, IMHO.

![image](https://user-images.githubusercontent.com/761911/48092038-d7552800-e20b-11e8-8ff7-dfdd6ff86215.png)
