### ISSUE TITLE
redesign the 'you have a kudos' email to be more flashy

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2712]
redesign the 'you have a kudos' email

here is an inspiration email

<img width="921" alt="slack-imgs" src="https://user-images.githubusercontent.com/513929/48084452-012f3000-e1b5-11e8-9870-ed7fd03916ac.png">

here is the existing kudos email

![screencapture-gitcoin-co-_administration-email-new_kudos-2018-11-06-11_13_50](https://user-images.githubusercontent.com/513929/48084485-160bc380-e1b5-11e8-98fc-b07f4f7e2f7f.png)

**Comment by PixelantDesign** [comment]
@kuhnchris 
I like the idea of sending one in return. Right now we just direct the user to **learn more** on the kudos landing page

**Comment by PixelantDesign** [comment]
![received kudos](https://user-images.githubusercontent.com/238235/48352312-6e7e0d80-e65a-11e8-8d82-f04abbd21a03.png)

**Comment by kuhnchris** [comment]
That looks more awesome!
Actually we should also include something like "Return the favor to <username who sent kudos> by sending him one too!", but aside from that, we looks good to me. @owocki any suggestions?

**Comment by kuhnchris** [comment]
Yeah that makes sense.

**Comment by owocki** [comment]
this looks good to me.  i agree with @thelostone-mc we could use a section for the comments that the sender attached to the kudos

**Comment by owocki** [comment]
does anyone wanna code it up or should we bounty the coding?

**Comment by kuhnchris** [comment]
If I get the mock-up files I can get to it.

**Comment by thelostone-mc** [comment]
@PixelantDesign mind sharing the sketch to my man @kuhnchris  ^_^

**Comment by PixelantDesign** [comment]
Updated with comments @kuhnchris 
![received kudos_final](https://user-images.githubusercontent.com/238235/48511008-79d06500-e823-11e8-94e0-30090aeca13c.png)

My recommendation is in the responsive view, we center everything. Let me know if you have any questions!

[RecdKudosEmail1114.zip](https://github.com/gitcoinco/web/files/2582584/RecdKudosEmail1114.zip)

**Comment by PixelantDesign** [comment]
Build ticket is here https://github.com/gitcoinco/web/issues/2841 @kuhnchris, closing this design ticket.
