### ISSUE TITLE
GitCoinBot reports 0 day inactivity

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2714]
**Describe the bug**
GitCoinBot reports inactivity for 0 day inactivity.

**To Reproduce**
Be unlucky.

**Expected behavior**
Not being reported

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48084757-d9fa5200-e1f8-11e8-89ba-e465beddefa3.png)

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris !
