### ISSUE TITLE
Build - New design and flyover for Gitcoin Issue Explorer entries

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2719]
### User Story

As a contributor, when exploring issues on the Issue Explorer, I'd like a more complete view as to which issues are ready to be worked on, what the latest activity update is for an issue, and a preview of the issue details directly in the Explorer, without needing to click on the issue itself. 

### Current Implementation & Reasoning for Change

The Gitcoin team has received feedback from contributors about confusion on which issues were actually ready to be worked on. Many contributors have had to click on an issue in the Explorer to view the issue details, only to find out that there were already active applicants, or the work had been taken by another contributor. 

![screen shot 2018-11-06 at 15 01 45](https://user-images.githubusercontent.com/7516920/48099583-eb316780-e1d4-11e8-838c-d7a64ff5decf.png)

For example, above is a screenshot of the currentl Issue Explorer. If we're just glancing at some of the "open" options, there's no direct indication of:

1. the last activity on the issue
2. how many applicants there are on the issue
3. whether or not the issue is truly open and ready for work
4. skills necessary to complete the issue

unless the contributor actually clicks on the issue and views the issue details page. 

### Expected Output

We'd like to take these drawbacks and introduce a new design on the Issue Explorer. This involves several changes, with the addition of a flyover.

New design on the rows of the Issue Explorer:

![screen shot 2018-11-06 at 14 30 04](https://user-images.githubusercontent.com/7516920/48099791-a0fcb600-e1d5-11e8-8d2d-11e34062905a.png)

As you can see, most of the original information about the Issue is retained and presented on each row, with the addition of the "ready for work" signal and the number of applicants. This is to provide additional information on the status of the issue directly in the Issue Explorer, and addresses concerns 2 and 3. 

When hovering over an issue, a flyover appears:

![screen shot 2018-11-06 at 14 30 13](https://user-images.githubusercontent.com/7516920/48099797-a4903d00-e1d5-11e8-9899-2c53b4058fa5.png)

The flyover exposes information one level deeper, which is the last activity/status on the issue, and also displays the skills necessary to complete the bounty, which addresses concerns 1 and 4. There is also the information about ready for work status, and the organization name + mini avatar that is hosting the issue on the flyover as well.

Clicking anywhere on the flout takes the user to the issue details view.

### Definition of Done
1. A new issue explorer row should contain:

- [ ] the organization avatar
- [ ] issue name
- [ ] the ready for work signal
- [ ] project type
- [ ] expiration date
- [ ] number of Github comments
- [ ] number of applicants
- [ ] issue open time
- [ ] token amount
- [ ] USD amount 

<img width="1154" alt="screen shot 2018-11-06 at 15 16 01" src="https://user-images.githubusercontent.com/7516920/48100156-fab1b000-e1d6-11e8-9856-49c7282a2aa2.png">

2. The flyover should contain:

- [ ] the ready for work signal
- [ ]  a mini-avatar
- [ ] organization name in plain text or use repo name
- [ ] issue title
- [ ] skills necessary
- [ ] the latest activity on the issue

![screen shot 2018-11-06 at 14 30 13](https://user-images.githubusercontent.com/7516920/48100181-08ffcc00-e1d7-11e8-8f25-9de91ac81fb5.png)

3. Ensure that this new design is responsive.

**Comment by kuhnchris** [comment]
This... kind of depends on the data model a little bit.  I know we can fetch these datapoints from the database itself, but the question is how performance will impact the user experience if we have to join those data up.
@mbeacom any suggestion how to prevent this to be a performance disaster?
Aside from that, seems like a straight forward task.
But, just to be sure: you want the filters to be gone, or is this just a "snippet" of the middle part of the page where we currently have the issue explorer search results?

**Comment by PixelantDesign** [comment]
**QA with @octavioamu @willsputra ** 

- Time stamp - we will not have 2 hrs ago time stamp @willsputra 
- Applicants - show 0 Applicants when there are no applicants, also show when there is at least 1 applicant.
- Flyout - show one line of Title of Bounty with ellipses.
