### ISSUE TITLE
Build featured bounties section on the Gitcoin Issue Explorer 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2720]
### User Story

As a funder on the Gitcoin platform, I would like the option of "promoting" one of my funded issues so that it appears in a banner on the top of the Gitcoin Issue Explorer, for a price.

As a contributor of Gitcoin, I would like to see a featured area so that I know which bounties are top priority for funders/projects. I can know that this bounty will be followed carefully by repo owners and response times will be quick.

### Why Is this Needed

Create a way for funders to highlight urgent or important bounties.

As Gitcoin grows, we're testing possible monetization strategies, one of which is allowing funders the option of paying a little extra to have their issues featured at the top of the Explorer. 

### Current Implementation

There is currently no "featured bounties" area.

### Expected Behavior

![screen shot 2018-11-06 at 14 29 56](https://user-images.githubusercontent.com/7516920/48100730-4f562a80-e1d9-11e8-982c-a8789c9a0984.png)

### Definition of Done

- [ ] Build a carousel
- [ ] Limit featured bounties count to 25
- [ ] The implementation should match the mockup
- [ ] Once work has started, the featured banner disappears 
- [ ] Add a place for funders to opt into this feature on the funder form for X amount of Eth (tbd)

### Additional Information

This change will be accompanied by requisite changes on the Gitcoin Funder Form and backend changes to reflect a featured bounty. Tickets TBD.

**Comment by kuhnchris** [comment]
Well, do we want to really prominently stick them out? 

Alternatively we could just blend them into the "regular" issue explorer and just give them a gray, silver or "gold" backing, depending on what package they book.

**Comment by PixelantDesign** [comment]
Already built. Closing
