### ISSUE TITLE
As a Gitcoin admin, I'd like have better data on the job preferences of those who are joining Gitcoin

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2721]
### User Story

As a Gitcoin admin, I'd like have better data on the job preferences of those who are joining Gitcoin. 

### Why Is this Needed

As we explore monetization strategies, Gitcoin may be invaluable for providing qualified candidates to job postings (outside of the Issue Explorer). In order for this to be successful, we need a more complete understanding (objective and subjective) of the job preferences for the Gitcoin community. 

### Current Behavior

Currently, there is a spot to input skills during the FTUX onboarding process, and a #community-jobs slack where people can state their intention, but none of the Slack data is captured and tagged to the corresponding profile ID. This is data that is potentially useful, and is lost.

We can cohort our Gitcoin user base by active bounty hunters, country, code/language preferences, and other relevant bounty characteristics, but don't have a full picture in the types, descriptions, and locations (or other characteristics) of positions that they are looking for. 

### Additional Information

We will go through the first manual cohort with Dave from Technical Integrity, and then further discuss viability for engineering support on jobs-related data collection.

**Comment by kuhnchris** [comment]
In theory we can actually gather a bit of user-related data (watch out for european folks with their DSVGO/european data protection laws) based on the following subjects:
- Received Kudos (if in any relevance to their tasks)
- Visited (interest), Applied (bigger interest), Started (same), Submitted (potential) and Finished (interest; if finished by current profile - potential) Bounties
- Gitcoin already collects a bit of data in that behaviour by asking "hey, we noticed you clicked on this bounty, mind telling us why?" in the bottom right corner for first-time visitors.
- See issue #2692 - by having more objective and subjective data on the bounties and users we can easier profile them for certain offerings.
