### ISSUE TITLE
bug - comments in kudos email is off-center

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2726]
<img width="1658" alt="screen shot 2018-11-07 at 11 00 50 am" src="https://user-images.githubusercontent.com/513929/48150627-7285e600-e27c-11e8-914c-0721b1ea2b03.png">

**Comment by PixelantDesign** [comment]
maybe just center, but not spend too much time since we're redesigning this email? @octavioamu ?

**Comment by octavioamu** [comment]
sure I will be fix that here https://github.com/gitcoinco/web/pull/2723

**Comment by owocki** [comment]
+1 to both comments
