### ISSUE TITLE
css : Media queries to fix up the landing page

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#273]
##### Description

- Media-Queries needed to prettify the landing page  (the photo is says it all )

<img width="1440" alt="screen shot 2018-01-24 at 5 03 36 pm" src="https://user-images.githubusercontent.com/5358146/35365292-a79b118e-0128-11e8-95b5-4bda8d5d9c47.png">

##### Environment

* **Browser**: Chrome
* **Version**: NA
* **Subsystem**: NA

**Comment by MarcioPorto** [comment]
@thelostone-mc I can tackle this if you're not working on it.

**Comment by thelostone-mc** [comment]
@MarcioPorto Sure go ahead!! ^_^
