### ISSUE TITLE
as a org user, i want gitcoinbot to label issues on my repo, so that it can keep things organized

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2730]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a org user, i want gitcoinbot to label issues on my repo, so that it can keep things organized

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

when you run a lot of bounties on your repo, its hard to keep track of them all.

if gitcoinbot could apply/remove labels to github issues.. it would vastly improve the UX for repo maintainers / org users

one piece of complexity is that we need to prompt repo maintainers to give gitcoinbot these perms

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no labeling

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
auto-labeling, or if not, failing gracefully

**Comment by kuhnchris** [comment]
Well, either prompt the repo owner, or provide some functionality for bounty owners in the bounty itself, like "synchronize bounty", "tag github issue", "clean up gitcoin bot messages", etc.
You could integrate those buttons in the top bar, kind of like administrative functions, for example like this:
![image](https://user-images.githubusercontent.com/761911/48169045-ee6e4580-e2f1-11e8-99e4-90be37bd5096.png)

**Comment by holgerd77** [comment]
Just had the same idea (just thinking about how to properly label Gitcoin - or generally bounty - issues on the [ethereumjs](https://github.com/ethereumjs/) org) and thought if I would find an associated issue here (found it 😄), so I would be very much in support for this!

I would also find it optimal, if Gitcoin bot would just (eventually with one opt-in on bounty creation) do the labelling itself and label along the status changes occured, so:

- ``Gitcoin Open``
- ``Gitcoin Started``
- ``Gitcoin Submitted``
- ``Gitcoin Done``

(am I missing something?)

Not sure if you have such already, but then it would probably also make sense to have a standard for the pre-state label, not sure if this even has to be Gitcoin specific, maybe ``Good Bounty`` would the most appropriate one. This could then (probably in mid-term) be used the otherway around, with Gitcoin web listing all these issues where one can the create a concrete bounty from.

**Comment by owocki** [comment]
i think the problem is that gitcoinbot needs write permissions in order to label issues on the repo

from [github docs](https://help.github.com/articles/creating-a-label/):

> In repositories where you have write access, you can create labels to organize issues and pull requests.


gitcoinbot wont have write access on 99.999% of github projects..

**Comment by kuhnchris** [comment]
But wouldn't that be solved if we actually have gitcoinbot be permissioned when someone opens a new bounty with a link to a issue? basically they hit send, pay the fee/commision, ask for gitcoinbot permission and bam, good to go.
The only issue would be if the person is not permitted to label the issues themselves. Then, OK, that would cause an issue.
