### ISSUE TITLE
Kudos - Ux to include Kudos at Payout is not enticing

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2735]
Kudos - Ux to include Kudos at Payout is not enticing

Consider ways to make it more visual surface suggestions based on kudos tags?

**Current**
<img width="603" alt="screen shot 2018-11-08 at 10 14 17 am" src="https://user-images.githubusercontent.com/238235/48207670-20f25f80-e33f-11e8-8b58-9dc6512a6d69.png">

<img width="549" alt="screen shot 2018-11-08 at 10 14 26 am" src="https://user-images.githubusercontent.com/238235/48207679-25b71380-e33f-11e8-9490-acfce075d4f0.png">

**Proposed**

<img width="578" alt="screen shot 2018-11-08 at 11 48 43 am" src="https://user-images.githubusercontent.com/238235/48214172-64ec6100-e34d-11e8-906f-2e952a7b0826.png">

**Comment by kuhnchris** [comment]
Only for Basic Payout, or Advanced aswell?

**Comment by PixelantDesign** [comment]
@kuhnchris yes, we haven't integrated it into advanced payout yet. It gets a little tricky when you're sending payment to multiple people.

**Comment by octavioamu** [comment]
what should be the parameter to relationate the kudos? I mean how I decide what kudos are related to that bounty?

**Comment by PixelantDesign** [comment]
If we could surface based on tags from the bounty, that would be great.

**Comment by kuhnchris** [comment]
@PixelantDesign should we make a own board? Because this would ALSO relate to the tags topic. We got a couple of things that tie those together now, may makes sense to collect them together.

**Comment by PixelantDesign** [comment]
Reminder! We had a thread on slack about the plus icons seeming like a select multiple feature. Could we build it so that if a user selects another kudos it unselevts the previous?

Also wondering if we should keep this to suggestion of 3 kudos. If there are too many recommendations it becomes choice overload. The payout flow already has a lot to think about. Let’s make this easy and as smart as we can and surface the top 3 most relevant kudos.

@octavioamu
