### ISSUE TITLE
As a contributor on the new Issue Explorer, I'd like to be able to filter issues by the number of applicants.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2741]
### User Story

As a contributor on the new Issue Explorer, I'd like to be able to filter issues by the number of applicants.

Dependent on completion of: https://github.com/gitcoinco/web/issues/2719

### Why Is this Needed

As a contributor, I want to be able to search for issues that I can claim first dibs on. 

### Current Behavior

Currently there isn't a way to filter on the number of applicants.

### Expected Behavior

Be able to filter the issue explorer based on the number of applicants.

### Definition of Done

- [ ] Sort function by number of applicants, ascending and descending

**Comment by thelostone-mc** [comment]
So technically would just searching for Open Issues meet this?
If it's a traditional bounty -> it's open as long as no one has called dibs on it
If it's a permission bounty -> it's open until a bounty hunter has been approved by the funder
if it's a contest -> it's always open

So is number of applicant really needed ? 🤔

**Comment by octavioamu** [comment]
I agree maybe we need a pristine search checkbox, to solve this problem instead of sear by applicants

**Comment by frankchen07** [comment]
Good point on the type of bounty making this ask a little more complicated as it seems. It's not super high priority right now and currently is un-groomed so perhaps we can visit this later.

**Comment by PixelantDesign** [comment]
What about something like this to surface open issues 
![No Applicants](https://user-images.githubusercontent.com/238235/58762352-5817a080-851d-11e9-8008-5576085943d8.png)

**Comment by owocki** [comment]
why make it a special tab on the explorer?  why not just add it to the filters on the side?

**Comment by frankchen07** [comment]
I like the idea of having the filters stay in the section on the left. Without over engineering another status, perhaps there's a way to "mark" a bounty like an "unread" message if no applicants have currently applied to it yet, and for that signal to not be there if there are already applicants who have applied.
