### ISSUE TITLE
Issues with Gitcoin Reauthorization

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2743]
**Problem**

**User locked out of Gitcoin account and unable to reauthorize Gitcoin.**

https://gitcoin.co/profile/anukul

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

Be able to reauthorize without loops.

**Screenshots**
<img width="646" alt="screen shot 2018-11-09 at 7 01 18 am" src="https://user-images.githubusercontent.com/238235/48261502-55bcf000-e3ed-11e8-8c86-1c44fd0303a3.png">

**Comment by octavioamu** [comment]
Solved
