### ISSUE TITLE
Contribution sent directly to the contract is not caught up

### ISSUE THREAD

**Issue by troggy** [gitcoinco/web#2745]
**Describe the bug**
We at LeapDAO use MultiSig wallet (by Gnosis) and would like to fund bounties directly from that wallet. As a test, I've sent a small`contribute` transaction from the multisig. Transaction went through just fine, but the contribution did not appear on Gitcoin UI. Is it just slow sync or something might be wrong?

Transaction: https://etherscan.io/tx/0x227fea7fa83b4911813c64ca12f022eb309cb459b760255e0a411847c1be91cf
Called method `contribute` on contract at `0x2af47a65da8CD66729b4209C22017d6A5C2d2400` with params: `1606` (bountyId), `1e17` (value, 0.1 ETH).
Bounty I've contributed to: https://gitcoin.co/issue/parsec-labs/parsec-contracts/32/1606

**To Reproduce**
Send `contribute` transaction directly through your wallet, not using Gitcoin UI.

**Expected behavior**
I expect the contribution to appear on the bounty page

**Comment by owocki** [comment]
hey @mbeylin @villanuevawill see above -- its for standardbounty # 1606 .. do you know if theres a way to recover the 0.1 ETH?

looks like its sent directly from the gnosis multi sig to the standardbounties contract , but doesnt seem to be reflected on the bounty on gitcoin.

**Comment by owocki** [comment]
perhaps the funder needs to recover the funds directly at https://explorer.bounties.network/bounty/1606 ?

**Comment by troggy** [comment]
@johannbarbie can you check if you are able to recover the funds here? https://explorer.bounties.network/bounty/1606 (I guess you need to login with 0x8db.. address)

**Comment by johannbarbie** [comment]
i see 0.1, but no way to "recover" them.
<img width="271" alt="screen shot 2018-11-26 at 6 42 11 pm" src="https://user-images.githubusercontent.com/659301/49031707-062b4200-f1ab-11e8-9b1d-3b9c7911ccb2.png">

**Comment by owocki** [comment]
i think 'deactivate bounty' should do it

**Comment by johannbarbie** [comment]
done and received the 0.1 to my wallet.
