### ISSUE TITLE
Remove the "full name" entry and the option to hide it on the Gitcoin funder form.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2748]
### User Story

As a funder in the open source community, true anonymity is not really possible. When funding an issue, I want as few decision points as possible from start to successfully funding an issue. 

On an Issue Details page, "Anonymous" is shown under the Funder section, but if the funder interacts on the Github issue, they eventually have their information exposed in the all activity section.

![screen shot 2018-11-09 at 10 54 04](https://user-images.githubusercontent.com/7516920/48282184-d7247a80-e40d-11e8-89bb-cfde0c37b053.png)

Anonymity only works if it's completely carried throughout the "All Activity" section and throughout Github (which isn't possible). It doesn't make sense to be in open source, funding issues, and remain anonymous - that's part of the "reputation" of open source.

### Why Is this Needed

This issue was brought up by a community member: https://github.com/gitcoinco/web/issues/2579

In order to tidy up the Issue Details all activity section, using Github usernames by default is more consistent, and follows the fact that true anonymity (in this case) is difficult, especially on Github and in open source. 

What logically follows is to remove the decision point to enter funder full names and just use their Github handle to indicate who is funding the bounty. The decision to enter and hide their email will remain.

This has the added benefit of not having difficulties following up with funders as necessary.

### Current Behavior

On the funder form, one can enter their full name and decide whether or not they want to remain anonymous. 

### Expected Behavior

A funder's Github handle will be shown by default.

### Definition of Done

1. Remove on the funder form:

![screen shot 2018-11-09 at 10 43 35](https://user-images.githubusercontent.com/7516920/48282557-e22bda80-e40e-11e8-80d4-abb13de5fd6a.png)

**Comment by Anish-Agnihotri** [comment]
I'll PR this tonight. 

Simple issue involving removal of invoke to `shared/name.html` and changing `bounty_owner_name` to default to `githubUsername`.

**Comment by Anish-Agnihotri** [comment]
Completed and pushed out in above PR. Feel free to let me know if you'd like me to remove some of the now redundant code related to the `bounty_owner_name` variable.

**Comment by thelostone-mc** [comment]
@Anish-Agnihotri left a few feedback comments!
