### ISSUE TITLE
Grants "How it works"

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#2749]
Add a "How It Works" drop down in the Grants Nav like in Bounties. It should have options for Grants Creators and Funders. 

We also need to implement showing a user the quickstart guide whenever it is their first time visiting grants/new or grants/X/fund, as is done in bounties.

**Comment by owocki** [comment]
cc @PixelantDesign to decide if/when its a priority

**Comment by thelostone-mc** [comment]
> We also need to implement showing a user the quickstart guide whenever it is their first time visiting grants/new or grants/X/fund, as is done in bounties.

https://github.com/gitcoinco/web/pull/2747 takes care of that when user visits `grants/new`  and `grants/profile/xxx` (when they have no grant activity )

Is how it works the same as the quickstart / different view all together? 
If it's the former I can just throw it in there
@owocki

**Comment by captnseagraves** [comment]
@thelostone-mc I believe so, yes, it will work the same as the quickstart. The difference is that the quick start will only fire on the first visit, where as the placeholder should show regardless of how many times they have visited and always show if there are no grants or subscriptions.

**Comment by owocki** [comment]
what @captnseagraves said makes sense to me

whats the idea behind having a seperate profile for `grants/` .. why not just fold the grants profile into the regular profile?  maybe add a tab next to 'all activity' and 'bounties completed' that is for grants...

**Comment by owocki** [comment]
ref: a broken grants profile :) https://grants.gitcoin.co/grants/profile/mbeacom

**Comment by thelostone-mc** [comment]
> @thelostone-mc I believe so, yes, it will work the same as the quickstart.

coolio I'll add it to the navbar and it will be accesible at `/how/grants/` ^_^

> it says 'my grants' on the top, but its mbeacom's profile.. strange

lol cause we hardcoded it 😂 
will fix it up

> whats the idea behind having a seperate profile for grants/ .. why not just fold the grants profile into the regular profile? maybe add a tab next to 'all activity' and 'bounties completed' that is for grants...

makes sense to me

**Comment by PixelantDesign** [comment]
@captnseagraves could you define the content and we can put it into a design cycle? Thanks!

**Comment by thelostone-mc** [comment]
@owocki @captnseagraves so are we folding thy my grants to gitcoin profile ?

**Comment by captnseagraves** [comment]
Pixelant and I have had some discussions about this in the past. it makes sense to folds 'Grants' into the profile, but we had decided not to for v1. what is imagined is a nav bar with "How it Works" (which brings you to the quick start), "Active Grants" (which brings you to index.html), and "Your Grants" (brings you to what is now the "my grants" view).

**Comment by captnseagraves** [comment]
@owocki There was never an intetntion to have a grants/profile page. I think that name came through as Octavio created the foundation and named the route "profile". It should be "grants/yourGrants/captnseagraves"  or similar
