### ISSUE TITLE
Rename "warning" to "reminder"

### ISSUE THREAD

**Issue by christianbundy** [gitcoinco/web#2758]
Sorry, none of the issue templates looked right for this issue, but I wanted to recommend changing the text on the gitcoinbot warning to replace "warning" with "reminder". I'm not sure whether the :warning: :warning: :warning: vibes are necessary, but if they *aren't* then I think the message would sound friendlier as:

>Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
>
> - [x] reminder (3 days)
> - [ ]  escalation to mods (6 days)

**Comment by thelostone-mc** [comment]
@frankchen07 I like this 👍 
What do you think ?

**Comment by PixelantDesign** [comment]
Thanks for the suggestion @christianbundy! 
I think this is a great idea. More friendly for sure.

**Comment by christianbundy** [comment]
Thanks all! That was quick.
