### ISSUE TITLE
When attempting to sign up for gitcoin slack I get a CSRF Failure

### ISSUE THREAD

**Issue by benjamincburns** [gitcoinco/web#276]
##### Description
Per the title, when I go to https://gitcoin.co/slack and enter my email address to sign up, I'm met with an error page telling me that there's been a CSRF failure.

It does seem that the invite goes through, however.

**Comment by owocki** [comment]
thanks for the bug report.. looking into this now

**Comment by owocki** [comment]
Weird, I get an 'already_invited' error for whatever input I give.. http://bits.owocki.com/3s3f282X3u0Q/Screen%20Shot%202018-01-25%20at%205.35.10%20PM.png

I think maybe something changed with cloudfront that is causing this issue.

**Comment by benjamincburns** [comment]
Yeah, that error was what I saw just before the email popped up, but that was the third try with the same email, so I figured maybe one of the attempts went through

**Comment by mbeacom** [comment]
Resolved in #314
