### ISSUE TITLE
Local GitHub integration triggers rate limiting

### ISSUE THREAD

**Issue by Ricky-N** [gitcoinco/web#2761]
**Describe the bug**
Local development for GitHub integration on master causes errors regarding "too many redirects" and rate limiting from GitHub-side during regular usage. From the network panel, it seems to spam too excessive numbers of login attempts, even following login. Initial login and app approval was spotty but seems possible. After initial login, visiting the "Avatar Builder" triggers rate limiting responses every time. 

**To Reproduce**
Follow the steps to run dev locally with `docker-compose`, then the [Third Party Integration](https://docs.gitcoin.co/mk_third_party_integrations/) steps for both GitHub OAuth2 and GitHub User Integration. It may be significant to allow only user level scope access. Log into GitHub from local Gitcoin and then attempt to visit the Avatar Builder page. 

**Expected behavior**
You can test the Avatar Builder locally

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**
- Browser Chrome

**Comment by PixelantDesign** [comment]
Thanks for reporting this @Ricky-N !
