### ISSUE TITLE
Null address when trying to pull account address from Metamask

### ISSUE THREAD

**Issue by santteegt** [gitcoinco/web#2763]
**Describe the bug**

I'm getting a `null` value when trying to pull my ETH account address form Metamask.

**To Reproduce**

This happens in the `Manage Settings/Account` option as well as in the `Add Account` button in the Kudos section within my profile

**Expected behavior**

Metamask active account address should be placed.

**Desktop:**

- OS: macOS High Sierra 10.13.6
- Browser: Google Chrome
- Browser Version 70.0.3538.77
- Metamask Version 5.0.2

**Comment by PixelantDesign** [comment]
Thanks for reporting this @santteegt !

**Comment by owocki** [comment]
this is a metamask thing, its been fixed and will be in the next build https://github.com/MetaMask/metamask-extension/issues/5716

**Comment by owocki** [comment]
fixed upstream!
