### ISSUE TITLE
Canceling "started" bounties shows wrong error message

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2764]
**Describe the bug**
When a started bounty needs to be cancelled, the wrong error message appears.
This issue is in here:
https://github.com/gitcoinco/web/blob/a52adc187cee91df3ffd6a80d743d13de760ce8e/app/assets/v2/js/pages/kill_bounty.js#L68
Basically we need a split between "is_open" and "is_started".

**To Reproduce**
Fund issue, have someone start it, try to cancel it

**Expected behavior**
Error message: "You cannot cancel a bounty that has a worker working on it".

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48318230-2f6d9f00-e5fd-11e8-9631-72f46c6e322c.png)
![image](https://user-images.githubusercontent.com/761911/48318231-34325300-e5fd-11e8-8a7f-084956c466b9.png)
![image](https://user-images.githubusercontent.com/761911/48318226-267ccd80-e5fd-11e8-8e53-e085cdd46fbe.png)

reported by RichatMakerDAO on Slack.

**Comment by PixelantDesign** [comment]
Thanks for creating this ticket @kuhnchris !

**Comment by owocki** [comment]
ahh shoot, yeah [this looks wrong](http://bits.owocki.com/2c9c9de6105f/Screen%20Shot%202018-11-12%20at%2010.44.43%20AM.png)

**Comment by kuhnchris** [comment]
We even anaylzed the structure we received - it's definitly because is_open is not true anymore. Result does not contain a "is_started", we would need to add that to the python and then additionally check against that in that block, so the proper error is shown.

**Comment by owocki** [comment]
i posted about this on the gitcoin slack

pasting details now

```
# on the triage call:

this issue has already been paid

its admin override status is ‘started’ thats why its showing as not paid in the frontend.

# to the team :

team, there have been an increasing number of support requests from people whose bounties have an override status on them

for example, this one above has been paid out already and its override status is ‘started’.  the funder has for months been really confused about why they can’t pay it out.

for a fix it twice, we need to either
1) be more responsible with our usage of override statuses and remember individually to check back on them and remove them when the override is not needed anymore
2) or, we need to make it so that overrides expire after a few days / weeks
3) or we need to remove them altogther
```

**Comment by kuhnchris** [comment]
oh, interesting! didn't hear about that one, my bad for making assumptions.

**Comment by frankchen07** [comment]
@kuhnchris - are you still working on this? checked out the PR, it looks like you were looking for some feedback?

**Comment by kuhnchris** [comment]
@frankchen07 as stated in the PR i'm waiting for mbeacom if I should do the backend side aswell, or if that's a own ticket.
