### ISSUE TITLE
Kudos Marketing - Encourage Sending Experience

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2765]
### Discussion

In order to encourage sending of Kudos we've discussed selecting active funders to send a handful of Kudos to in order to get them to try it out.

Here are a few ways we can do this. Note that in both options, we're providing free Kudos but asking senders to cover the gas cost.

**Option 1**
Adding the free kudos to the top of the marketplace section, and directing email to the marketplace.
Get the funder to a place where they'd likely go to purchase Kudos surfacing the free Kudos at the top.
![46105829-0f952f80-c1a5-11e8-8a00-2bf1bb58553f](https://user-images.githubusercontent.com/238235/48352628-32977800-e65b-11e8-8750-1e7bdc975e99.png)

**Option 2**
Adding the free kudos to a new tab on the profile labeled **Free**. Clicking from the email directs funder to this tab to see the available free Kudos. This path requires us to rename the tabs in the profile and distinguish between received and free kudos.
![kudos profile seed](https://user-images.githubusercontent.com/238235/48352743-99b52c80-e65b-11e8-961d-20a184cf7ac4.png)

Also open to other ways to handle the experience if it can be simplified.

@frankchen07 @owocki @octavioamu @mbeacom

**Comment by octavioamu** [comment]
I wonder, should be interesting to have this free kudos inside bounty creation / payout?

**Comment by PixelantDesign** [comment]
If we could build a smart system that is a nice to have.

**Comment by owocki** [comment]
I'm a big fan of option 1.

**Comment by owocki** [comment]
Option 2: I think that profile is an awkward place for the free kudos.  Are they 'my kudos' ?  if not, then why are they on my profile. I think a funder dashboard is a better place for the option 2 kudos than the profile

**Comment by frankchen07** [comment]
I think option 1 makes sense, since it leverages the existing marketplace for a "limited time" section. Adds a sense of urgency without the confusing free kudos in the profile section. However, if they access the Kudos Marketplace from their profile, it should still show free Kudos in the marketplace. 
The email and cohorting active funders is most likely low lift, but I'm unsure on how much lift the engineering work will take.
