### ISSUE TITLE
Unfurl to movie is nice, but I want them clicking into the issues

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#2770]
**Describe the bug**
When I post a link to twitter or chat because I want people to click in and veiw a set of issues like this:
https://gitcoin.co/explorer?network=mainnet&keywords=burner-wallet&order_by=-web3_created
(All burner wallet issues)
It unfurls a movie. Totally cool for introducing Gitcoin, but the happy path is the person actually clicking in and looking at the issues. The movie ends up being more distracting than helpful IMO. 

**To Reproduce**
paste this into chat:
https://gitcoin.co/explorer?network=mainnet&keywords=burner-wallet

**Expected behavior**
It would be rad if this unfurled something about gitcoin bounties but clicking on it brought you to the issues instead of distracting you with a movie. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2653167/48363776-f3b9f000-e663-11e8-916c-2f84bb5ff447.png)

**Comment by kuhnchris** [comment]
So basically you want to have the proper "twitter-card meta tags" set for the page, correct?
see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup
