### ISSUE TITLE
DESIGN - As a potential worker, I would like to know the reason why I was rejected for a bounty, so I can improve myself

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2773]
### User Story
As a potential worker, I would like to know the reason why I was rejected for a bounty, so I can improve myself

### Why Is this Needed
*Summary*: I want to know why I was rejected

### Description
*Type*: Feature

### Current Behavior
- Worker was canceled without any information

### Expected Behavior
- Receive reason for rejection

### Definition of Done
- User has to enter reason for rejection
- Rejection is sent to the worker

### Additional Information
![image](https://user-images.githubusercontent.com/761911/48366560-91d2a800-e6ae-11e8-8c48-7f8f95d05e46.png)

**Comment by PixelantDesign** [comment]
Good point @kuhnchris.
Curious what you would have expected to see in addition to the rejected notification (short canned answer that a funder could select from or a detailed explanation)?

**Comment by PixelantDesign** [comment]
Gotya. That makes sense. 

@willsputra something to think about along with asking why contributor's stop work or funders cancel a bounty #2668. Perhaps there is a reusable pattern that can be applied here as well.

cc @frankchen07

**Comment by willsputra** [comment]
@kuhnchris @PixelantDesign Good point!

One question: for traditional bounties, applicants who are not approved are automatically rejected right? I'd love to have a rejection reason for each applicant but I wonder how we can make this scalable. For example, if there are 20 applicants or even hundreds (in the future), it might be overwhelming for the funder to give reasons for each one.

I'll explore this a lil bit more (there could be some inspiration from good hiring sites) but if yall have any ideas lemme know! 😁

**Comment by kuhnchris** [comment]
Right now the same issue would be viable if we have 20 or more applicant already, right? Or is there a mass-canceling of bounty-applicants? If there is, it makes sense to have them *there* as dropdown field.

**Comment by willsputra** [comment]
If the funder clicks on 'Reject Worker', yes I agree the dropdown should be there.

I guess I'm just wondering for cases where the funder approves someone for a traditional bounty and the rest of the applicants are automatically rejected (or not approved).

**Comment by kuhnchris** [comment]
Then I'd send them a standard response ála "A different worker was approved for the task you applied", which is a valid reason to me.

**Comment by willsputra** [comment]
Thanks for the suggestion! Maybe we could put it in our email. Will create a ticket for it.

As for the explicit rejection reasons, here are some points I could think of:
• The applicant did not meet the desired qualifications.
• The applicant did not meet the desired timeline.
• The applicant did not provide sufficient information on the action plan.
• The applicant was not willing to work for the bounty amount.
• The bounty was available only under special circumstances (e.g hackathon).
• The bounty was reserved for another person.
• The bounty was cancelled.
• Others.

(Ideas [from](https://help.smartrecruiters.com/Configuration/Hiring_Process/Withdrawal_and_Rejection_reasons) [here](https://support.greenhouse.io/hc/en-us/articles/207305363-Strategic-Rejection-Reasons))

I'll ask some of our funders for suggestions, too. Thoughts? @kuhnchris @PixelantDesign

**Comment by willsputra** [comment]
@kuhnchris @frankchen07 @PixelantDesign what do you all think?
![work rejected](https://user-images.githubusercontent.com/19514207/49682416-ac9e0e00-faee-11e8-91c9-13749ab28108.png)

**Comment by frankchen07** [comment]
^ They have the capability to X out of the modal though, which is the the equivalent of "cancel" or "no".

**Comment by kuhnchris** [comment]
As a dev that's intuitive yes, but, think about the regular user who is not really keen on using stuff like that (or apps in general). 
It's your call, but I would "KISS" it.

**Comment by willsputra** [comment]
Thanks for the suggestion @kuhnchris! Yeah I think it would be better if we make it more obvious.

![work rejected](https://user-images.githubusercontent.com/19514207/49739534-1542e180-fccd-11e8-8a85-4395e38b2ac5.png)

**Comment by PixelantDesign** [comment]
Hey @willsputra looking good! It might be possible that two reasons are the reason why the funder wants to reject. Will you put this in front of some funders to get feedback? I'm wondering if these should be check boxes?

@frankchen07 what do you think?

**Comment by frankchen07** [comment]
My thought was that the reasons were different enough that even if there were two responses, one would be the dominating one. 

Would love to see the outcome of user testing though. If it's something we leave for now and find out later that many people are selecting "other" and writing multiple reasons, that would be evidence to re-take a look.

**Comment by kuhnchris** [comment]
Agreed, usually there's a "main reason" and the other reasons usually only contribute to the factor that causes the main reason to trigger. I'd also go ahead with @frankchen07 's suggestion - implement it with radiobuttons and if the real-life environment shows that users are using it differently we can always revamp it (changing this is not really a big hassle)

**Comment by PixelantDesign** [comment]
yes sounds good!

**Comment by willsputra** [comment]
Yeah I agree. The funders I've asked have given me mostly one main reason so I think we can start with this :)

@PixelantDesign as for the email, maybe we can use our regular template?

![application declined](https://user-images.githubusercontent.com/19514207/50004623-b50cb200-ffe2-11e8-994f-c716c446a4f8.jpg)

**Comment by kuhnchris** [comment]
That looks great.
Do you split it into 2 BUILD tickets or just 1 entailing the UI + the mail part?

**Comment by willsputra** [comment]
@kuhnchris I think I'll split into 2

**Comment by PixelantDesign** [comment]
Thanks @willsputra!
