### ISSUE TITLE
DESIGN - As a Gitcoin founder, I want storytelling about how all the products fit together, so I can articule how Bounties and CodeFund and Kudos and Grants and Research Fit together.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2778]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin founder, I want storytelling about how all the products fit together.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

From our RAC panel feedback doc:
> Need a stronger storytelling component/connecting thread across the four primary projects; need stronger sense of priority and product roadmap. All of the products may compete with each other versus enhance the overall mission of serving/enhancing/sustaining the OpenSource Community. Need to lead with that messaging and let the products take a back seat. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

No good storytelling about how the products fit together.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Links in the nav that point to a new page well call 'Gitcoin's Products' that links to `gitcoin.co/products`
1. Link in the black nav that currently reads 'Grow Open Source' will now point to `gitcoin.co/products`.
2. add a link in the `why gitcoin` nav dropdown to read 'Products' and point it to `gitcoin.co/products`

On this new page, I want the following elements.

H1. Our mission is to Grow Open Source.

P - Here's how we're going to do it, and what the world will look like when we do.

H2 - Here's how we see the problem

H3 - Open Source Value Creation is Broken

* Maintainers and Contributors to OSS create immense value.
* They are not properly compensated or appreciated, which leads to burnout.
* Burnout leads to subpar support for Open Source.

H3 - The funnel problem:

![1_rdnuacb17tzr49x2nemtsw](https://user-images.githubusercontent.com/513929/48461748-6f19bf80-e792-11e8-9d5a-052768177e6f.png)

OSS Lifecycle:
1. User of open source (99.9% of actors)
2. Contributor to open source (0.09% of actors)
3. Maintainer of open source (0.01% of actors)

H2 - Here's how we see the solution. 

H3 -  Our mission is to accelerate whats working along this funnel (green), and to stop whats not working (red).

Each of our products helps us optimize the OSS Lifecycle so that things can look more like this 

OSS Lifecycle:
1. User of open source (*99%* of actors)
2. Contributor to open source (*0.9%* of actors)
3. Maintainer of open source (*0.1%* of actors)

![1_z-_zlj_o8gnvvqmemu7ivq](https://user-images.githubusercontent.com/513929/48461751-7771fa80-e792-11e8-88ea-1bb65c2e9649.png)

H3 - its important that coders can code.

<img width="269" alt="screen shot 2018-11-12 at 5 44 42 pm" src="https://user-images.githubusercontent.com/513929/48383374-af017980-e6a2-11e8-8e35-6860bc969cca.png">

H3 - Here's how it works.

* *Bounties* accelerates finding contributors for your repo.  
* *Kudos* helps you build relationships.
* *CodeFund* makes finding passive income for maintainers, easy.
* *Grants* makes finding passive income for maintainers, easy.

(Each of these could be visualized in [the funnel](https://github.com/gitcoinco/creative/blob/master/Marketing/OSSLifecycle-white.sketch))

Important Note that all of these are tools that make money by integrating into your coding workflow NOT pulling you away from coding.

H2 - results

H3 - Some Stats:

* Maintainers who add CodeFund to their platform make $XK/mo
* Maintainers who integrate with Grants see $XXK/mo in passive income.
* Maintainers who add Gitcoin Bounties to their platform, see a Zx increase in contributors.
* Maintainers who send Kudos see a Y percent increase in repeat contributors.

H3 - Get in Touch

CTA - Email Gitcoin Founders
CTA - Checkout our Products (one for each product)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Please allow for 2-3 iterations of design.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
You rock for reading this far.

Checkout this medium draft that discusses the very same topics as this page does: https://medium.com/gitcoin/community-roadmap-to-open-source-financial-freedom-8d852cbb6247

See also, @coderberry 's slides on Incentivizing Open Source: https://speakerdeck.com/coderberry/incentivizing-and-sustaining-open-source

Artwork https://github.com/gitcoinco/creative/blob/master/Marketing/OSSLifecycle-white.sketch

**Comment by willsputra** [comment]
First draft. Separated stuff into tabs so we don't cram too much info in one page:

Our Mission: this page
Our Products: https://github.com/gitcoinco/Marketing/issues/8 (upcoming)
Our Values: existing mission page (https://gitcoin.co/mission)
Our Results: https://gitcoin.co/results

![storytelling](https://user-images.githubusercontent.com/19514207/48658522-50f7dc00-ea7e-11e8-8327-846574767684.jpg)

Thoughts? @owocki @PixelantDesign

**Comment by thelostone-mc** [comment]
> or 'Our Token' if we want to be slightly cheeky :p

lol ❤️
this is gonna be fun to build out

**Comment by willsputra** [comment]
a bit of tidying up + added the videos

![storytelling](https://user-images.githubusercontent.com/19514207/48795602-64ce6700-ed38-11e8-81d9-21ec15beeb75.jpg)

**Comment by willsputra** [comment]
@owocki Thanks for the feedback. Here's another pass!

![storytelling1](https://user-images.githubusercontent.com/19514207/48852773-07462300-ede9-11e8-95e2-e08198ea8b2b.jpg)

**Comment by owocki** [comment]
looking good

are there any other options for the funnel (the three green bars)?  im not super crazy about the way it looks aesthetically
