### ISSUE TITLE
DESIGN - As a user, I want to be able to upload Kudos instead of add them to the YAML file / codebase, so Kudos are easier to deploy.  As  a Gitcoin founder, I want there to be an easy way for new artists to contribute to the platform to enable more liquidity and therefore revenue.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2779]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to be able to upload Kudos instead of add them to the YAML file / codebase, so Kudos are easier to deploy.  

As  a Gitcoin founder, I want there to be an easy way for new artists to contribute to the platform to enable more liquidity and therefore revenue.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Its a cumbersome 8 step process to add a new Kudos to the system right now.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

You must 

1. Commit a kudos to the git repo [example]
2. Push it to master; push it live.
3. Run the command `python manage.py mint_all_kudos mainnet ~/gitcoin/coin/app/kudos/kudos.yaml --gitcoin_account --filter=GREP_EXPRESSION --live` to mint the kudos to the blockchain.
4. Run `bash scripts/run_management_command_if_not_already_running.bash sync_kudos mainnet opensea --start 1` or wait for it to run automatically.

To get a new kudos on the system.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

1. User goes to 
https://gitcoin.co/mint/kudos
2. User uploads all of this information to the system:

```
- name: Kauri Pioneer
  description: Cheers to you, one of the first Kauri contributors!
  priceFinney: 3
  numClonesAllowed: 100
  tags: 
    - web3
    - kauri
    - ethereum
    - documentation
    - knowledge
  image: kauri_1.svg
  to_address: 0xF8aE578d5d4e570De6c31F26D42eF369C320aE0b
```
3. Uploads the SVG artwork.
4. Form sends an email to founders@gitcoin.co asking them to approve the Kudos.
5. Upon approval, It is minted to the blockchain and added to the DB after the form is submitted.
6. Upon failure, an error message is shown that specifies why the failure.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above specification.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
This will enable us to one day, decentralize the artwork generation away from just Gitcoin / Mladen, and receive artwork submissions from around the world.

This is the Kudos flywheel, which will power Kudos growth:

1. When we are doing 100s of Kudos transactions per day, artists are GOING TO WANT to be able to add *liquidity* to the Kudos platform.
2. When there is a lot of *liquidity*, then people are going to want to send more Kudos.
3. Go back to step 1.  Flywheel spins faster!
4. Flywheel spins off revenue for Gitcoin.

**Comment by thelostone-mc** [comment]
Revenue: 

A lil wacky and this might need an update in the contract but evaluate returning kudos / sending those to others.
Can I send a kudos rewarded to me back into the market / send it to someone else for an additional fee  to gitcoin.
Creates a history of who all owned a kudos -> which makes every individual kudo have a diff value.
Me sending `Django-God` kudo which was sent to from @mbeacom is more valuable than a fresh `Django-God` kudo.

**Comment by owocki** [comment]
> Can I send a kudos rewarded to me back into the market / send it to someone else for an additional fee to gitcoin.

I like this idea from a UX standpoint; donno if ppl would be willing to pay for it tho
