### ISSUE TITLE
DESIGN - As a user, I want to be able to upload an avatar asset, so I don't have to spend time/effort downloading docker, testing them, PRing them, and waiting for deployment.  As a Gitcoin Founder, I want to enable a revenue opportunity for Gitcoin to sell premium avatar items.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2781]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to be able to upload an avatar asset, so I don't have to spend time/effort downloading docker, testing them, PRing them, and waiting for deployment.

 As a Gitcoin Founder, I want to enable a revenue opportunity for Gitcoin to sell premium avatar items.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Example https://github.com/gitcoinco/web/issues/2684
Right now it's very cumbersome to add a new item to the avatar.  

Without lowering the barriers to submitting artwork to the avatar builder, we need much higher crypto-economic incentives to create liquidity in the avatar marketplace.  

Investing in making it easy to do avatar uploading would mean that we could create a decentralized avatar art marketplace.  

Once we have high liquidity in the art marketplace, we will be able to [sell them to users as part of their web3 identity](https://github.com/gitcoinco/skunkworks/issues/82).  Our target users: millennial developer internet users who need a cool way to express themselves online.

This is the Avatar marketplace flywheel, which will power Avatar creation and sales of premium virtual goods:

1. When we have the best avatar builder with the best liquidity of attributes, people are going to use it to create an identity for themselves,  [and upload it to their favorite web3 identity provider](https://github.com/gitcoinco/skunkworks/issues/82)
2. When there is a lot of *liquidity* of avatar parts, then people are going to make more avatars and upload them in more places.
2. When there is a lot of *liquidity* of avatar parts, Gitcoin can sell premium avatar attributes to our adoring users.
3. Go back to step 1.  Flywheel spins faster!
4. Flywheel spins off revenue for Gitcoin.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

1. [Kevin creates a bounty for more avatar assets](https://gitcoin.co/issue/gitcoinco/web/2684/1673).
2. People start work on the bounty.
3. People clone the repo.
4. People get the docker stuff setup.
5. People figure out how to do an avatar PR. [example PR](https://github.com/gitcoinco/web/pull/2356)
6. Code Review
7. Merge
8. Ship
9. Deploy
10. Test

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

1. User goes to 
https://gitcoin.co/mint/avatar_item
2. User uploads all of this information to the system:

```
- name:
  priceFinney: 0
  cateogory:  accessory
  subcateogory:  hats
  image: mullet.svg
  to_address: 0xF8aE578d5d4e570De6c31F26D42eF369C320aE0b
```
3. User Uploads the SVG artwork.
4. Form sends an email to founders@gitcoin.co asking them to approve the Avatar.
5. Admins can 'preview' a specific avatar item, or only make it available to a specific set of super users.
6. Upon approval, it is visible to everyone.
7. Upon failure, an error message is shown that specifies why the failure.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above spec.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Recommended Reading:

[<img width="946" alt="screen shot 2018-11-12 at 5 19 20 pm" src="https://user-images.githubusercontent.com/513929/48382625-2208f100-e69f-11e8-8999-c899ca71db2f.png">](https://medium.com/@alonbonder/virtual-goods-the-next-big-gold-rush-8b85d893c3b8)

**Comment by kuhnchris** [comment]
See https://github.com/gitcoinco/web/issues/2693
