### ISSUE TITLE
CODE JOB BOARD - As a user, I want a Blockchain Job Board so I can find professional work in the space .  As a Gitcoin Founder, I want a job board for revenue.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2782]
As a Gitcoin Founder, I want a job board for revenue.

As a user, I want a Blockchain Job Board so I can find professional work in the space .
# What

Gitcoin should host a Blockchain Job Board which allows anyone to post a blockchain job for free.

Three pages

1. Index of Jobs
2. Job Detail Page
3. Post Job

# Attributes of Jobs

`Job` Database object, ideally in a new `job` django app

* Title,
* Desc (markdown formatted),
* where to apply (email or url)
* linked to a gitcoin/github profile
* active (bool - yes/n)
* skills (list of strings)
* company
* github profile
* expiry date (default = 30 days in future)
* apply_location (url or mailto:)
* amount
* paid TXid 

# Design 

[Gitcoin_Job.Board.zip](https://github.com/gitcoinco/web/files/1943984/Gitcoin_Job.Board.zip)
![39128115-9b64b226-470f-11e8-81d5-1a2541a5d79f](https://user-images.githubusercontent.com/513929/39205226-558b34de-47b7-11e8-9841-d292e60d676a.png)
![39128116-9b7e07da-470f-11e8-9f17-0b2c621069b6](https://user-images.githubusercontent.com/513929/39205227-559de188-47b7-11e8-9bed-9d9d45bae393.png)
![39167802-ab39f726-4799-11e8-92ae-d93007466c8f](https://user-images.githubusercontent.com/513929/39205228-55b02e06-47b7-11e8-8633-8cf6fdc6e697.png)

# User Flows

# Index Page
* Shows jobs
* Is Resopnsive
* Filters on the left work

## Submit Job

* User navigates to `/jobs/new` and enters in all information on the form.
* github profile can be prefilled by logging in to gitcoin
* validation is performed inline upon submit.
* User must pay 0.1 ETH per job posting or 25 DAI per job posting.  These tokens will be sent to `0x00De4B13153673BCAE2616b67bf822500d325Fc3`.
* if validation passes, a new DB object is created (with active == N)
* upon save, each field is scraped for [script injection attacks](http://www.itprotoday.com/software-development/script-injection-attacks) and any javascript is removed.
* an email is sent to admin `settings.CONTACT_EMAIL` requesting admin to approve the job ( see `processed_faucet_request` for a parallel of how emails are done)
* when admin approves the job in the django admin, then an email is sent to the user who submitted it letting them know it's live
* the job is listed on the `jobs/` page

# View Job

* User sees a list of jobs at `/jobs`
* Page is responsive (tablet, mobile, desktop)
* There is a list of filters on the left, and search/sort on top that are updated upon click
* if > 25 jobs are visible, pagination is enabled
* When they click on a job they are taken to that page (job desc is markdown rendered)
* the 'apply' button takes user to the `job.apply_location`
* clicking on 'github profile' takes user to the posters github profile
* clicking on a keyword takes one back to the job board page with that keyword prefilled
* clicking 'back to job board' takes user back to their previous search

# Acceptance Criteria

* Keep it Simple.  Nothing Complicated
* Works in Responsive Design
* Expect 3-5 rounds of comments / turnaround on code review.
* Can't do JS Injection when creating a Job

**Comment by thelostone-mc** [comment]
Should we revisit the design mock-ups whenever we decide to prioritize it?

**Comment by thelostone-mc** [comment]
Revenue Idea : 
- Each Job Posting requires a fee to gitcoin. (Also prevents spamming )
- Job posting are linked to bounties ( gitcoin team manages those bounties to help secure potential candidates )
- We charge x% of an employee's salary from the recruiter
