### ISSUE TITLE
Worker should not be able to submit work without clicking start work

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2795]
See this issue.
https://gitcoin.co/issue/spacemeshos/app/4/1388

## Definition of Done

- [ ] If worker submits work without clicking start work, display an error that asks them to click start work.

<img width="541" alt="screen shot 2018-11-13 at 7 54 23 am" src="https://user-images.githubusercontent.com/238235/48415176-a3519980-e71a-11e8-9c2f-97622bb09b1d.png">

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/2799
