### ISSUE TITLE
Metamask connection message is too vage

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2802]
**Describe the bug**
User does not really feel the need to use the "connect to metamask" to connect MetaMask to Gitcoin.

**To Reproduce**
Be unconnected from gitcoin, try to access gitcoin

**Expected behavior**
User understands he has to press the icon to connect MetaMask

**Additional context**
Mulili [18:01]
ohh wait, its now displaying mainnet bounties and i can see the submit page too :smile:
i simply clicked on the button `click here to connect to metamask` and metamask popped up and ask me to confirm whether gitcoin should connect
and on refreshing everything was back to normal
@owocki this error msg is a bit misleading then, because i was already connected to metamask and on the `mainnet`.
![image](https://user-images.githubusercontent.com/761911/48430661-1e916a80-e770-11e8-9967-dd18808b95ed.png)
Mulili [18:07]
perharps it should say `click on this button to authorize gitcoin to work with metamask` or something along those  lines :slightly_smiling_face:

**Comment by usmanmuhd** [comment]
Actually in this case the user has not explicitly enabled the privacy mode, thereby it justifies the fact that he does not know about eip 1102.
The more appropriate bug would be to not need the user to connect to metamask unless the user has enabled privacy mode.

**Comment by usmanmuhd** [comment]
@kuhnchris we might just add a link to the metamask page explaining eip 1102 or a tooltip might also work. I prefer using the same **connect to metamask** as the metamask team has used it in their blog and numerous other places.
