### ISSUE TITLE
20181113 -- Grants QA on Weekly Grants Team Call

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2803]
holistically:
- [x] black tophat does not show up across the site, and also the nav is the bounties nav
- [x] we should have a link to quickstart in the top nav

grants detail page:
- [x] on grants view, what to do about update posting?

fund a grant view:
- [x] on funding view, create view, cancel view, add eip 1102 support
- [x] new default image
- [x] remove ETH as an option for this (and maybe enable WETH)
- [x] Token Approval Limit - [ ] Alisa has a ticket for this ... Maybe we can make it a hidden var and approve for 99999?
- [x] on payment period in the fund view, shouldnt have 'any', and we should probably remove 'minute' and 'hours'.
- [x] MetaTx Gas Price in Payment Token - [ ] provide some sort of sane default here
- [x] BN.js issue on fund grant page http://bits.owocki.com/248bb1236b9f/Screen%20Shot%202018-11-13%20at%2010.54.50%20AM.png
- [ ] unfurl image / title / desc should use the grant logo.

index page:
- [x] grants search does not work, 'search' button is missing.. (in PR and ready for review)
- [ ] show NUM subscriptoins on the card
- [x] if you click on any part of the card you are taken to the grant

my grants
- [x] tx history is hardcoded
- [x] ui is clunky on the 'i have no grants' -- [ ] can we co-opt the 'no bounty' imagery here?

create a grant 
- [x] get rid of total amount, focus on monthly amount
- [x] make funding targets in DAI, not in ETH.   or better yet, allow them to choose which token their targets are in.
- [x] Required subscription amount in ETH / Required Token For Subscription --> for now, lets hardcode this to zero and then re-enable IFF people demand.
- [ ] down the line: figure out how to handle the attack vector where user can set a very low ETH amount.
- [x] Admin Wallet Address => Recipient Wallet Address
- [x] Frequency of payments => abstract it away for now, just like 'required subscription amount and required token'

- [x] grants admin page, QAing
https://grants.gitcoin.co/grants/5
- [x] logo dimensions -- [ ] they should be able to adjust what is centered or we should provide guidelines on dimensions. perhaps kevins janky CSS can help: https://gist.github.com/gitcointestuser2/2b471dc47fbc0eeca9452fc49074259e
- [x] just one save button is sufficient

grant milestone page
- [x] we need a 'back button'
- [x] complete / delete buttons need color http://bits.owocki.com/014ebc0c64b0/Screen%20Shot%202018-11-13%20at%2011.14.03%20AM.png
- [x] information architecture of 'create milestone' and current milestones -- [ ] figure out where current milestones go (shouldnt be under 'create milestones')
- [ ] when you complete a milestone, an activity/update should show up

TODO: QA emails
TODO: QA cancel grant
TODO: QA cancel contributions page

**Comment by captnseagraves** [comment]
@PixelantDesign Can you share the new default image you would like to use for grants?

**Comment by captnseagraves** [comment]
Another QA Issue here: https://github.com/gitcoinco/web/issues/2862#event-1972438367

**Comment by thelostone-mc** [comment]
Open issues are captured here https://github.com/gitcoinco/web/issues/2949
