### ISSUE TITLE
Contributor unable to submit work

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#2814]
**Describe the bug**

A contributor who has been approved to start work in the issue below isn't able to submit their work for review.

https://gitcoin.co/issue/ethereum/py_ecc/11/1531

**To Reproduce**

Currently unclear. Will update as more information is available.

**Comment by owocki** [comment]
5791d5ffc8b33ecf6632344544872f623100a6dd

**Comment by kuhnchris** [comment]
This alone sadly does not solve it. Side-note: 831 is also f'ed. (no toLowerCase)

**Comment by owocki** [comment]
@ceresstation  can you ask them to try again?  i just put in another fix 0823e65f5da310475ed451eaf931e4be52bf59c3 (among others)

**Comment by ceresstation** [comment]
Fixed now, thanks @owocki!
