### ISSUE TITLE
got an error. please try again, or contact support@gitcoin.co

### ISSUE THREAD

**Issue by adamskrodzki** [gitcoinco/web#2815]
**Describe the bug**
I see followin error:
got an error. please try again, or contact support@gitcoin.co

when I access link 
https://gitcoin.co/issue/PwayGames/PWay.Contracts/1/1678

with new version of metamask

**To Reproduce**
1) Insstall latest metamask
1) login to metamask and set on mainNet
2) enter https://gitcoin.co/issue/PwayGames/PWay.Contracts/1/1678

**Expected behavior**
Web3 properly loaded

**Screenshots**

![image](https://user-images.githubusercontent.com/10146412/48464362-9d71bc00-e7df-11e8-8c91-f7054d158597.png)

**Desktop (please complete the following information):**

- OS: Windows 8.1
- Browser Chrome, Latest
- Browser Version  70.0.3538.77

**Additional context**

Most probabli error is connectedd to new privacy mode in metamask

the exception is thrown in following code

web3.eth.getBalance(web3.eth.coinbase, function(errors, result) {
      if (typeof result != 'undefined') {
        document.balance = result.toNumber();
      }
    });

**Comment by john-light** [comment]
I am also getting this error when trying to use [Frame](https://frame.sh) 0.1.2

Normally I would expect Frame to pop up and ask for permission so Gitcoin can view my account. Instead I receive this error:

>  got an error. please try again, or contact support@gitcoin.co

**Comment by thelostone-mc** [comment]
Hmm so I can't reproduce this 
- incognito without metamask installed
- with metamask installed and permissions given

It could be cause of this 🤔 


<img width="406" alt="Screenshot 2019-08-19 at 5 23 17 PM" src="https://user-images.githubusercontent.com/5358146/63653593-860f2880-c78c-11e9-9528-d0fb959fc89e.png">
