### ISSUE TITLE
Gitcoin Nominations - November Edition

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2816]
![gitcoinnom](https://user-images.githubusercontent.com/238235/48480469-8da2a980-e7d8-11e8-9eb6-2cc129db061a.png)

**Comment by owocki** [comment]
there's too many nominations to list.. but off the top of my head; i always appreciate @kuhnchris commenting.. and @Anish-Agnihotri and @NedelescuVlad @jvmaia  for their persistence pushing PRs.

@pinkiebell rocks also.  as does @Dgilliams @jakerockland @usmanmuhd @nanspro

**Comment by tcoulter** [comment]
@gnidan with EthPM

**Comment by anshumanv** [comment]
Always there - (@vs77bb @ceresstation @mkosowsk @ryan-shea) :sparkles: :pray:

**Comment by SaptakS** [comment]
@kushaldas for projects in freedomofpress, cpython and tor and helping the community.
@sayanchowdhury for his contribution to fedora and python community
@chkumar246 for his contribution to RDO and openstack
@nerdyvaishali for her contribution to Linux Kernel
@perfinion for his contribution to Gentoo, SELinux and tensorflow

**Comment by itsN1X** [comment]
@owocki for [...].

**Comment by frankchen07** [comment]
@PixelantDesign and @willsputra for great designs
@Anish-Agnihotri for making front-end killings
@kuhnchris for checking in on almost every issue in the past couple weeks
@ryan-shea for community mastery

**Comment by milesmatthias** [comment]
@chrislovecnm

**Comment by kdenhartog** [comment]
@ashcherbakov @vimmerru @jovfer and the rest of the team helping you all are doing an excellent job

**Comment by jschiarizzi** [comment]
@blockchainbuddha Patrick because he build one click dapp, OSS making ethereum development easier and more accessible. https://www.producthunt.com/posts/one-click-dapp

**Comment by WizardOfAus** [comment]
@bokkypoobah does many great things for the community!
