### ISSUE TITLE
Investigate anime.js for animated SVG (avatar; mail)

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2818]
### User Story
As a user I want to have fancy stuff.

### Why Is this Needed
Because I'm a user and I like fancy stuff.

### Description
Analyze a use for anime js
Doc: http://animejs.com/documentation/#svgAttributes
Example: Kudos Hexagons blend in, flashy stars in the Kudos mails, etc.

### Current Behavior
Moderatly fancy

### Expected Behavior
Super fancy

### Definition of Done
- [ ] Being super fancy

**Comment by owocki** [comment]
these animations are cool.. i'd love to see an idea or two of where/how they can be used

**Comment by mbeacom** [comment]
Last we spoke about this, @thelostone-mc, @SaptakS, and @octavioamu were opting to use svg and css sorcery to handle animations. 🤔 I'm not opposed to the idea, but we will probably want their input on this.

**Comment by kuhnchris** [comment]
Sure, not going to try to overrun anyone with a decision on here, just throwing out possibilities since this seems to be a quick win. If you guys already investigated some other possibilities it's fine as well. Maybe we need a common place where we can put infos like that?

**Comment by octavioamu** [comment]
I like the idea, there are a few libs of svg manipulation/animation, right now we have a few animations with css only, I think we can do some fancy things in the receibe pages and some other places, but emails doesn't support js, even svg render or complex css.

**Comment by owocki** [comment]
![screen recording 2018-11-18 at 07 54 am](https://user-images.githubusercontent.com/513929/48674236-3158c600-eb07-11e8-8ac4-5395f364945f.gif)
playing with this today => https://github.com/gitcoinco/web/pull/2875

**Comment by kuhnchris** [comment]
sweet

**Comment by owocki** [comment]
i think it might be too much

**Comment by owocki** [comment]
spin upon form submit
![screen recording 2018-11-18 at 08 49 am](https://user-images.githubusercontent.com/513929/48674911-e2af2a00-eb0e-11e8-8809-f7dd19a66229.gif)
bounty details loading page

![screen recording 2018-11-18 at 08 14 am](https://user-images.githubusercontent.com/513929/48674912-e2af2a00-eb0e-11e8-94dc-db231fce0a6b.gif)

**Comment by owocki** [comment]
rotate on hover in marketplace
![screen recording 2018-11-18 at 09 31 am](https://user-images.githubusercontent.com/513929/48675331-cf9f5880-eb14-11e8-9343-ac3f677f661b.gif)

**Comment by kuhnchris** [comment]
You seem to enjoy playing with that... ;-)

**Comment by octavioamu** [comment]
I was playing with [lottie](https://airbnb.design/lottie/) and is amazing you can convert after effects animations into svg animations checkout the result: 
https://codepen.io/octavioamu/pen/WYJYrr

**Comment by owocki** [comment]
I like the codepen that @octavioamu submitted. 

i think that the most plausible one that i coded up, to actually use, is this one:

<img src='https://user-images.githubusercontent.com/513929/48674912-e2af2a00-eb0e-11e8-94dc-db231fce0a6b.gif'>
