### ISSUE TITLE
standardbounties cleanup: Github claim work comment/interest comment updating seems to fail

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#282]
Github claim work comment/interest comment updating seems to fail

**Comment by mbeacom** [comment]
Resolved.

Example:
<img width="782" alt="screenshot 2018-01-29 11 25 24" src="https://user-images.githubusercontent.com/7315957/35521219-2f6b8910-04e7-11e8-9a7f-b11b992913c7.png">
https://github.com/btcsuite/btcd/issues/1089
