### ISSUE TITLE
Bounties in progress shows stopped and completed bounties also

### ISSUE THREAD

**Issue by usmanmuhd** [gitcoinco/web#2820]
It shows all the bounties that I started work on, irrespective of whether I stopped it later or completed them.
![screenshot from 2018-11-14 21-26-42](https://user-images.githubusercontent.com/26684281/48494528-16aaf680-e854-11e8-9139-793342a42352.png)

**Comment by PixelantDesign** [comment]
Thanks for the report @usmanmuhd !
