### ISSUE TITLE
DESIGN - as a user, i'd like to have a gitcoin labs homepage, so i can understand the why/who/what easily, and have a portal to al of the interesting research

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2821]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i'd like to have a gitcoin labs homepage, so i can understand the why/who/what easily, and have a portal to al of the interesting research

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature 

### Current Behavior
[comment]: # (Describe what actually happened.)
No Labs Landing Page

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Labs Landing Page 

H1 - Tools for Busy Developers
P - Gitcoin Labs' mission is to make Ethereum dapps fast, usable, and secure.

H2 - Meet the team.
P - TODO: Austin Griffith intro and bio

H2 - View the Research
Grid that of modules, each module has embedded screencast that Austin has done on it.

H2 - View the Portfolio
CTA -- Link to `/tools` page.

Other details:
- This page should be linked in the black nav (pending PR for this : https://github.com/gitcoinco/web/pull/2801 )
- in the sub-nav, it should be linked as "About Labs"
 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

Please allow 2-3 iterations on your design.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
See also:

- labs in nav: https://github.com/gitcoinco/web/pull/2801
- announcement post: https://medium.com/gitcoin/announcing-gitcoin-labs-ba400522d697
- logo: https://github.com/gitcoinco/creative/blob/master/Brand/Labs/gitcoin_labs.svg

**Comment by octavioamu** [comment]
Yes I was thinking on this when I was working with the nav, also a place to capture some people ideas or to get in contact with Austin to talk about.

**Comment by owocki** [comment]
I 😍 this.  this page is awesome! -- only two comments:

1. we should perhaps show the labs research roadmap (which right now is only a collection of buzzwords or one-line descriptions of scope) in the page desc
2.  is that the 'get in touch' options feel lopsided on the left hand side.

i've also gotten some feedback from the community that theydon't get how they're suppose to work with labs.  

maybe we can solve BOTH problems by adding a header / paragraph text next to 'get in touch' that designates how community-driven the research is, and the community can work with us

i'd love to get comments from @PixelantDesign and @austingriffith though

**Comment by owocki** [comment]
comments from @austintgriffith:

```
Austin Griffith [8:20 AM]
I would just consolidate tools and research into on set of posts, but maybe we could separate too. open to ideas

Owocki [8:31 AM]
i think that research will be link to medium posts.. whereas tools is probably what gitcoin.co/tools is now (a list of live apps that gitcoin / gitcoinlabs has produced)
```

@willsputra let us know what you need from us to do another rev of the design..

**Comment by willsputra** [comment]
@owocki @austintgriffith thanks for the feedback!

here's an updated draft:
1. added 'Roadmap' below 'Latest Research'
2. changed 'Get in Touch' to 'Community' since I think it would be clearer, and added more explanation on contributing as a community member.

![gitcoinlabs](https://user-images.githubusercontent.com/19514207/48855371-e1bc1800-edee-11e8-9fce-3ab8b88a4ae4.jpg)

**Comment by owocki** [comment]
@austintgriffith this looks good to me.. does it look okay to you?

anyone interested in coding this?

**Comment by owocki** [comment]
@willsputra can you post the designs?

**Comment by willsputra** [comment]
@owocki Sketch file here:
https://drive.google.com/open?id=1R3jBr4in1rLnw5UmRmlfyopVwct0hmIy

**Comment by owocki** [comment]
code task => https://github.com/gitcoinco/web/issues/2947
