### ISSUE TITLE
About Page Refresh -- 2019

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2825]
https://gitcoin.co/about

The about page could use a refresh to show the 2019 positioning.

2019 positioning => https://docs.google.com/presentation/d/1fIhBvF13IzKDLx_siX-NmfXilXJcFA9oeR7mILv8FyQ/edit#slide=id.g47fb3d8c3d_3_2642

**Comment by kuhnchris** [comment]
![image](https://user-images.githubusercontent.com/761911/48506638-27566f00-e84a-11e8-8561-899d2a063385.png)
