### ISSUE TITLE
As a core team member, i want gitcoin-only kudos so they can be exclusively sent.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2830]
### User Story

As a core team member, i want gitcoin-only kudos so they can be exclusively sent to by us for different purposes than the peer to peer use case.

### Why Is this Needed

Current implementation exposes all kudos to the public.

### Definition of Done

- [ ] Explore whether it makes sense to mint them and hide them from the marketplace.
- [ ] Implement a way for core team members to see and send this the kudos (like the attached)
- [ ] Consider adding a ‘only gc staff can send’ flag and disable sending in the frontend?

example gitcoin-only kudos

![untitled_720](https://user-images.githubusercontent.com/513929/48505711-f4d65300-e804-11e8-96ef-85c049a00a59.png)

**Comment by kuhnchris** [comment]
Well, just thinking loud here:
Coins are being minted by the contract anyways from a central address, right? If so, we could have a flag on the kudos coin that set it like "unique to gitcoin", and check in the send function, if that flag is set, and the "sender" is not a special gitcoin address, then it cannot be sent. (e.a. it can only be transfered to a special gitcoin address that can only send it forward to other addresses, like a subcontract)

**Comment by PixelantDesign** [comment]
@octavioamu what do you think?
