### ISSUE TITLE
tip/kudos extension scope

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2834]
this is an extension of https://github.com/gitcoinco/web/pull/2673

Further things we want to do with txid data.

* show the 'tx complete date' and 'receive tx complete date' of a tip
* If a Tip/Kudos drops/fails, We should notify the sender
* Perhaps we only trigger 'you have a new X' emails after the tx clears?

**Comment by kuhnchris** [comment]
so basically you want to add a layer to monitor geth to see the transaction confirmed and THEN trigger an event that basically sends the mail?
Gotta check how we handle that currently.

**Comment by owocki** [comment]
implementation is in a pending PR => https://github.com/gitcoinco/web/pull/2673
