### ISSUE TITLE
High-Level Documentation for GitcoinCo/Web

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2835]
### User Story
As a developer, I need very much time to understand the basic gist of the django application that is deployed here, and find the responsive positions to work at. This may be a result of a growing codebase. But at some point we either need to rebase the codebase and split the several projects (gitcoinbot, mail integration, eth-monitoring, slackintegration, github integration) into physical projects/repositories themselves, OR, as this ticket is proposing, create a overarching documentation joining the existing docs and extending them for each "folder"/application in the app/ folder.

### Why Is this Needed
To provide a sofisticated turn-around time for changes and involve new (OSS) people we need to provide a easy way to jump straight into the meat of the tool instead of navigating around. Having a huge effort to find where what is (for example avatar stuff is in dashboard, what's the folder retail for, etc.) is a big turn-off for most volunteers.

### Definition of Done
- [ ] create "starter" bounty (good-first-bounties)
- [ ] interview workers after completing the job to see how they felt about the doc
- [ ] rework feedback into the documentation
- [ ] try to keep at least a... moderate level of documentation (either via bounty itself as a requirement, or by doing separate documentation rounds after big project steps, like Kudos V1/2/..., Grant, etc.)

### Additional
cc @mbeacom and @owocki since you guys do most of the merge/dev work apparently.
also cc @thelostone-mc and @willsputra as you guys usually have good input aswell!

**Comment by mbeacom** [comment]
Have you seen: https://docs.gitcoin.co ?

**Comment by kuhnchris** [comment]
Yes, for a "extreme" highlevel approach this may work, but as soon as you try to find, for example, kudos, or anything "more recent" you'll probably fall flat.

**Comment by mbeacom** [comment]
@kuhnchris 
- **Current documentation is too high level**: Have you looked at the docstring generated documentation?  https://docs.gitcoin.co/kudos/admin/ and the like..?  We automatically generate documentation from all .md documentation and docstrings in python files.
If anything, we should be emphasizing proper python PEP-257 docstrings as specified in the contributor documentation to continue building out this documentation.

- **splitting repositories**...  have you heard of the single repository concept?  This pattern is in use throughout many organizations...  Google worked out of one repository for hundreds of projects for quite some time.  You can read about the numerous benefits to this publications like [the devops handbook](https://www.amazon.com/DevOps-Handbook-World-Class-Reliability-Organizations-ebook/dp/B01M9ASFQ3) - extremely short summary without associated case studies:  [Create Our Single Repository of Truth for the Entire System](https://caylent.com/devops-handbook-part-3-continuous-delivery/) - That said, I'm not married to anything... but this is primarily the strategy we've adopted for anything that is involved with the actual stack.  API clients are split off as well as secondary projects, like ethavatar/js|python clients, and what not are all split off already.

- **good-first-issue**:  We recently discussed this internally and are planning on allocating some time to well-scoped first issues to familiarize new contributors with the codebase.

- **Interview workers after completing jobs**:  We are actively doing this and plan on continuing the trend.

- **rework feedback into the documentation**:  We attempt to do this as regularly as possible.  I'd be open to suggestions on how to scale this whether it's with a slack integration/suggestions box/whatever else, as it currently relies on someone on the engineering or supporting teams updating this documentation.  Another thing to note here is that we're planning on rolling out a dynamic FAQ for just this (and there is already a PR out).

**try to keep at least a... moderate level of documentation**:  All of this documentation **should** be automatically generated from well-formed docstrings in my opinion, so manual intervention isn't necessary unless the documentation is specifically an addition to FAQs or the numerous other guides we already maintain.
