### ISSUE TITLE
standardbounties cleanup: state issues

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#284]
Potential bug in the current deployed code.  Has to do with the legacy issues.  The issues that are currently in the “fulfilled” state, should really be in the “accepted” state.  And the issues that are currently in the “claimed” state, should be in the “fulfilled” state. (edited)
Also, currently there is no way to filter on “claimed” because that is not a valid state in the new version.

thanks @jasonrhaas for the bug report

**Comment by jasonrhaas** [comment]
I think this can be fixed by simply updating the `def status()` function in the models.py

**Comment by jasonrhaas** [comment]
Although might need a database update also to get it to update the `idx_status` column.

**Comment by owocki** [comment]
> I think this can be fixed by simply updating the def status() function in the models.py

this.. plus a grep of the entire codebase to see where the status' we are going to deprecate are referenced too
