### ISSUE TITLE
Asking for not needed value on multiple payout

### ISSUE THREAD

**Issue by AugustoL** [gitcoinco/web#2840]
I created an to bounty with 25 ETH to be paid between multiple users. When I go to pay out the bounty it asks for more value but it shouldn't, gitcoin already has the 25 ETH that I sent, the value in the tx should be 0 but instead, it is the amount of ETH that I want to pay to the contributors.

Bounty creation tx: https://etherscan.io/tx/0x478cd20788099c05168363fa1bc55e28a707eb359a6d82579a5afee8148fdede

Bounty: https://gitcoin.co/issue/windingtree/wt-hackathon/13/1608

**Describe the bug**
See above.

**To Reproduce**
I go to advance payout of my bounty, select the contributors and click payout bounty.

**Expected behavior**
The value requested by metamask on the tx should be 0, if not I am spending ETH that I already paid, it should be using the ETH that was sent to the bounty, not request more.

**Screenshots**
![image](https://user-images.githubusercontent.com/7763867/48536280-27dd1d00-e8bf-11e8-9fa7-9a815466aec2.png)

**Desktop **

- OS: Ubuntu 28
- Browser Chrome
- Browser Version Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by usmanmuhd** [comment]
Currently Advanced payout pays directly from your wallet and not the amount already sent to the bounty. Once you payout the bounty, you can cancel it to get back your first paid amount.

**Comment by AugustoL** [comment]
@usmanmuhd thanks for the quick response! That's weird. It should use the ETH already held by gitcoin. I wonder why they are not doing it.. I'm going to try that.

I think I should leave the issue open anyways, for someone for the team to close it, having to use ETH from outside gitcoin to pay ETH that is already held by them makes no sense, I hope they change this soon.

**Comment by usmanmuhd** [comment]
It used to be that way. It was disabled for solving a potential bug in the flow. They are already working on fixing it.

**Comment by PixelantDesign** [comment]
Thanks for reporting this @AugustoL, yes we are currently working to fix this!
Thanks for helping out here @usmanmuhd!

We're hoping to have this fixed soon. There is work happening on this PR if yall are interested in following along! https://github.com/gitcoinco/web/pull/2675
