### ISSUE TITLE
Build - Gitcoin should set my expectations of what is happening to my crowdfunding.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2850]
### User Problem

As a funder I’ve opened two bounties earlier today, both txs were confirmed, but only one bounty was actually created and i can see it on my profile page. How can I know what happened to the second one?

### Why Is this Needed

Crowdfund tips can take up to 8 hours to go out (see `send_tips_for_bounty_fulfiller` mgmt command)

### Description

Make the syncing time shorter and make a few other ux improvements to set expectations for users.

### Current Behavior

Takes 8 hrs or more to send out crowdfunded tips.

### Expected Behavior

Users expect their payout now, if a bounty has been paid out.

### Definition of Done

To improve the experience we should:
- up this to every half hour or even up to 5 minutes
- add some copy to the payout IFF there is a crowdfund to let them know they’ll be sent it within X amount of time
- make it so that the crowdfund payout generates an activitty feed item so that ppl publicly can see when it happens

**Comment by kuhnchris** [comment]
actually a clean way would be to spin up that mgmt command filtered on that bounty to issue previous tips and in the rare case some post-completion tips are executed, a mgmt run every x hour to issue outstanding solved and not distributed tips.
