### ISSUE TITLE
Weird "See All" and "X USD" buttons when switching status on the Issue Explorer

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2857]
**Describe the bug**
Weird "See All and "X USD" buttons appear on the top of Issue Explorer when switching status

![screenshot 2018-11-17 01 16 38](https://user-images.githubusercontent.com/19514207/48636736-b1e3cd80-ea06-11e8-9e6d-903c126f6457.png)

**To Reproduce**
Click on different statuses when you're on the Issue Explorer
Video showing behavior: https://drive.google.com/open?id=1BKxRIh1yLp-oZs3hnq82POSWCoI4XKGU

**Expected behavior**
Those buttons should not appear

Tested it on Chrome, Firefox, Safari MacOS

**Comment by willsputra** [comment]
@kuhnchris okay I think it might be related to the crowdfunding labels

There's this issue with crowdfunding in 'Open'
![screenshot 2018-11-17 11 27 31](https://user-images.githubusercontent.com/19514207/48656139-e635a900-ea5b-11e8-9b57-adb64bd1f988.png)

When I switched to 'Work Started', the See All and 434.74 USD labels persisted and they're somehow on the top of Issue Explorer now
![screenshot 2018-11-17 11 27 36](https://user-images.githubusercontent.com/19514207/48656148-049ba480-ea5c-11e8-9814-b0de109f121a.png)

**Comment by willsputra** [comment]
added another ticket for the styling of crowdfunded issues #2863

**Comment by thelostone-mc** [comment]
Fix is already in https://github.com/gitcoinco/web/pull/2861 ^_^
