### ISSUE TITLE
Fix styling of crowdfunded issues on Issue Explorer

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2863]
**Describe the bug**
Issues with crowdfunding look weird on the Issue Explorer
![1](https://user-images.githubusercontent.com/19514207/48656270-c1dacc00-ea5d-11e8-8418-50122b808db9.jpg)

The labels go into a new line and "See All" is not clickable.

**To Reproduce**
Look at issues with crowdfunding on the Issue Explorer

**Expected behavior**
1. The ETH and USD labels should be on the same line, with the 'See All' button below
![2](https://user-images.githubusercontent.com/19514207/48656290-05353a80-ea5e-11e8-8da9-89b1e8b2c52b.jpg)

2. Clicking 'See All' should reveal the crowdfunded amounts
![3](https://user-images.githubusercontent.com/19514207/48656296-1b42fb00-ea5e-11e8-8740-04ac364d41bb.jpg)

*Related issue*: #2857

**Comment by octavioamu** [comment]
Is already a fix in  #2861
