### ISSUE TITLE
Community discussion -- What should live on https://gitcoin.co/

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2867]
what does the community think of changing our landing page at https://gitcoin.co/ to be an index of products, like https://occipital.com/ has ?

reason: it’s misleading to put the bounty product front and center when the gitcoin brand is really a suite of products.

we  could namespace everything for bounties under a `/bounties` path.

i’d even go so far as to say that `https://github.com/gitcoinco/web/issues/2778` could become the new `gitcoin.co` landing page, and we could move the facebook marketing targets to a new path namespaced under `/bounties`

**Comment by owocki** [comment]
@pinkiebell  @kuhnchris @Anish-Agnihotri @nanspro would love ur feedback on this

**Comment by kuhnchris** [comment]
It depends. You want to separate the "project" from a specific product? Let's make it even better and give them their dedicated subdomain. So gitcoin.co and www.gitcoin.co redirect to the landing page you proposed (and the old links still forward to the new bounties.gitcoin.co subdomain, so we do not break existing links), and the other "products" get their own subdomain. 
That'd currently be:
grants.gitcoin.co
bounties.gitcoin.co
kudos.gitcoin.co

AFAIK.
That would have multiple effect as in: gitcoin.co links still work and are valid, the user can be redirected after a period of "transition time" to the main page on gitcoin,co after we assume that most people switched over and the other "old" links would be dead anyways, we have a natural split between operation and project(s), and we do have the possibility to deploy parts of project(s) separatly and can update and enable/disable them on demand if there is some bug or issue or problem. (right now everything is one giant mass)

**Comment by pinkiebell** [comment]
Hah, I actually waited for something like that.
So yes, a product overview as the landing page sounds good 👍

**Comment by Anish-Agnihotri** [comment]
That certainly sounds like something I could see happening!

From a user perspective, the simplification of product-suite on one landing page, along with sub-domains if possible, as suggested by @kuhnchris, would be fantastic, and make the platform far more concise. 

From a developers perspective, I already only focus on the Issue Explorer to begin with + the black bar at the top to switch to and from Kudos, so I doubt it would disrupt my (or others) workflow as much. 

All in all it would certainly enhance the Gitcoin image/brand promise upon landing.

Might be worth looking at your heatmapping tools though (to see what the home-page is being most used for), so that you can plan ahead to divert that traffic - although I'm confident you and the team have already discussed that :).

Sounds good to me!

**Comment by owocki** [comment]
@Anish-Agnihotri @kuhnchris @pinkiebell checkout this gem from @willsputra https://github.com/gitcoinco/Marketing/issues/8#issuecomment-441078275

**Comment by kuhnchris** [comment]
Looks sweet 💯. As commented there, maybe still a bit too much bounty-focused, but aside from that, nice.

**Comment by kuhnchris** [comment]
One thing to point out tho is: how would we manage this software-side?
Does django work with vhost redirections?
Do we need to (and I can already hear @mbeacom sending space wizards in my neck) split the app to support a real split? Or would we just change the main page and leave everything else as-is?

**Comment by willsputra** [comment]
Just an update (also related to https://github.com/gitcoinco/Marketing/issues/8 + #2778), we're currently mapping the flow of the pages to see how the pages and nav relate to each other.

Will probably also do some user tests before changing the homepage, so both new and repeat users can still access their usual stuff (issue explorer, fund bounties etc.) easily without being confused. 🙂

**Comment by owocki** [comment]
I just submitted what I think the brand architecture / navigation structure should be https://github.com/gitcoinco/web/pull/3303
