### ISSUE TITLE
Organizational Identity

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#288]
Per @razordaze idea on the livestream ... we should build in some sort of organization identity into the platform.

i.e. the ability to manage/ share work and manage issues with others in your github organization. (as well as manage your organization-wide gitcoin profiel)

**Comment by owocki** [comment]
Need to do customer development before continuing on with this..

**Comment by razordaze** [comment]
Can you elaborate?

**Comment by kuhnchris** [comment]
@owocki @PixelantDesign I suppose this is the "original" github org ticket.
