### ISSUE TITLE
email templates are not optimized for empty elements

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2886]
**Describe the bug**
Trying to preview kudos or tip mails without having kudos or tips in the system will result in 500

**To Reproduce**
deploy standard docker image, add superuser with docker-compose exec web app/manage.py createsuperuser, access: 
- http://kuhnchris.eu:8000/_administration/email/new_tip
- http://kuhnchris.eu:8000/_administration/email/new_kudos

**Expected behavior**
e-mail preview

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48724792-788ba780-ec2a-11e8-9fdb-88b55301d140.png)

**Comment by kuhnchris** [comment]
Also, for the "working" ones there seem to be a hardcoded reference against "localhost" (nothing set up) 

![image](https://user-images.githubusercontent.com/761911/48724865-b2f54480-ec2a-11e8-97dd-57d6572d5bb9.png)

**Comment by SaptakS** [comment]
@kuhnchris I believe the link is not hardcoded but you need to update your `BASE_URL` environment variable. Else it defaults to `http://localhost:8000`. Hence the link.

**Comment by kuhnchris** [comment]
Yeah, saw it, closing this issue.
