### ISSUE TITLE
Website is non designated for older monitors

### ISSUE THREAD

**Issue by filips123** [gitcoinco/web#2890]
**Expected behavior;**

Items in menu bar should be smaller depending on window and monitor size, so they will fit into one row.

**Actual behavior;**

Website is non designated for older (4:3) PC monitors. Items in menu bar are too big and sometimes split into two files. This is specially noticeable in arrows of items.

**Reproducing:**

Open issue explorer on some old 4:3 monitor.

**Screenshots:**

Firefox:
![firefox-screenshot](https://user-images.githubusercontent.com/16626308/48731218-dcb76700-ec3c-11e8-9134-b7597cebd17a.png)

Chrome:
![chrome-screenshot](https://user-images.githubusercontent.com/16626308/48731261-f062cd80-ec3c-11e8-87bb-16aace2aa95f.png)

Normal:

![normal-screenshots](https://user-images.githubusercontent.com/16626308/48731321-11c3b980-ec3d-11e8-9c3b-a731da938503.png)

**Environment:**

- OS: Windows 10
- Browser Firefox and Chrome

**Comment by thelostone-mc** [comment]
@filips123 Is it just the navbar ?

**Comment by filips123** [comment]
@thelostone-mc I find out this on navbar, but maybe some other similar elements also have this problem.
