### ISSUE TITLE
Github Usernames should be auto populated

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#2892]
This field should be auto populated with anyone that contributed so the funder doesn't have to go looking for github usernames:

![image](https://user-images.githubusercontent.com/2653167/48737717-05733880-ec0c-11e8-92f9-279fbb7cbdf0.png)

I know it's a small thing, but every little thing you can do to make the experience smoother for the user is important.

**Comment by thelostone-mc** [comment]
Ah yeah we've been meaning to that 😅 
we can get that in post https://github.com/gitcoinco/web/pull/2675

**Comment by Anish-Agnihotri** [comment]
Just saw this! Can take a look into it and get a PR pushed out within the next 24-48hrs if that sounds good.

**Comment by thelostone-mc** [comment]
@Anish-Agnihotri yeah go for it ^_^
