### ISSUE TITLE
Contribution hasn't been payed out

### ISSUE THREAD

**Issue by troggy** [gitcoinco/web#2893]
There is a bounty https://gitcoin.co/issue/parsec-labs/parsec-contracts/32/1606.
It was created with Ξ0.21 of funding. Then there was a Ξ1 contribution made via Gitcoin web page and Ξ0.1 contribution sent directly to the contract (see #2745).

Work on the bounty was completed and payment released. However, the worker received only Ξ0.21.

**Comment by owocki** [comment]
@troggy you should have gotten an email to `m**************er@gmail.com` with instructions on how to claim this payment.. and if you login to gitcoin and click in the top right you will see a 'claim tip' option in there..  

let me know if this helps.  did you get the original email?  if not, i can resend it

**Comment by troggy** [comment]
@eezcjkr is the one who didn't receive the payment. @eezcjkr can you check pls?

**Comment by eezcjkr** [comment]
So I have received the 1ETH bounty, but not the 0.1ETH that was send via the multisig.

**Comment by owocki** [comment]
@eezcjkr according to the bounty ,the amount of the tx was 0.21 not 0.1 ETH..  the TX was paid out 10 days ago, here is a link => https://etherscan.io/tx/0xab38922d3747022b522cb67f7620221a42dbbe05986a264f20dd0ef96f932671

**Comment by owocki** [comment]
and looks like the crowdfund was paid via 0x94b68921e2900c31f22d340246c723d5906149d0837daf0212b58e1279089b82

let me know if you are still having issues. ... if not i will close this issue

**Comment by owocki** [comment]
Let me ask Mark Beylin, who wrote standard bounties.. I've never seen a use of the system quite like this.

**Comment by owocki** [comment]
just commented over on #2745

**Comment by troggy** [comment]
all good now. @owocki thanks a lot for your help!
