### ISSUE TITLE
Kevins Grants QA 20181120

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2897]
- [x] hover animation doesnt exist for grants logo (screencast: http://bits.owocki.com/fd6f3949ae6f/Screen%20Recording%202018-11-20%20at%2010.49%20AM.gif )

Fund page
- [x] 'please unlock metamask to continue' doesnt work with EIP 1102
( screenshot http://bits.owocki.com/ac9f6e29a840/Screen%20Shot%202018-11-20%20at%2010.47.05%20AM.png )
we'll need to integrate the 'connect to metamask' button that exists elsewhere on the app.
- [x] Lorem ipsum needs removed http://bits.owocki.com/c95e1b789d9a/Screen%20Shot%202018-11-20%20at%2011.06.40%20AM.png
- [x] There still too much cognitive overhead to the "Value Of Payment Per Period" form element.  Can we change "Value Of Payment Per Period" to "Tokens Per Period"
- [x] There still too much cognitive overhead to the "token approval limit" form element. Can we change "Token Approval Limit" to be a select box with the options "1 period", "2 periods", "3 periods" up to 25 periods.  There should also be a "No Limit" option that sets the limit to be 9999999999999999999999999999.
- [ ] [This link](http://bits.owocki.com/b63654545bb8/Screen%20Shot%202018-11-20%20at%2011.12.43%20AM.png) goes to the external URL, not to the actual grant URL
- [x] ETH is in the dropdown everywhere, but ETH isnt supported (WETH is) per @thelostone-mc comment [here](https://gitcoincore.slack.com/archives/CBDTKB59A/p1542797686088500) SHOWSTOPPER

Grant Detail page
- [ ] [This grant](https://grants.gitcoin.co/grants/5) has no Team members.  Should we allow a grant with no team members?  My gut says no.. At the very least, the pereson who posted the grant should be on the team.

Create grant page
- [ ] [Results could not be loaded](http://bits.owocki.com/1ec8fa16a567/Screen%20Shot%202018-11-20%20at%2011.15.15%20AM.png) on 'team members' input.  I assume this is GH API rate limit issue?

Loading page
- [ ] Why is my 'external URL' shown on the loading page? [screenshot](http://bits.owocki.com/b7c975bb1f06/Screen%20Shot%202018-11-20%20at%2011.16.39%20AM.png)
- [ ] integrity error upon insert [screenshot](http://bits.owocki.com/68aba02543d6/Screen%20Shot%202018-11-20%20at%2011.17.22%20AM.png) - SHOWSTOPPER

Edit Grant Page
- [x] What is [this module](http://bits.owocki.com/4e5cdcb98cb1/Screen%20Shot%202018-11-20%20at%2011.19.07%20AM.png) and why does it not have a label on it?
- [ ] "Post Update" button doesnt work.. No updates are posted.
- [ ] Updates are all still lorem ipsum - SHOWSTOPPER

Create Milestone
- [x] No way to get back to the main grant page from the 'create milestone' page.

Grant Details Page
- [x] can we add a SLUG to the grant URL? `https://grants.gitcoin.co/grants/8` coudl become `https://grants.gitcoin.co/grants/8/foo-bar`

**Comment by mbeacom** [comment]
> * [ ]  hover animation doesnt exist for grants logo (screencast: http://bits.owocki.com/fd6f3949ae6f/Screen%20Recording%202018-11-20%20at%2010.49%20AM.gif )

This will be resolved once we resolve file conflicts/rebase.

> * [ ]  Lorem ipsum needs removed http://bits.owocki.com/c95e1b789d9a/Screen%20Shot%202018-11-20%20at%2011.06.40%20AM.png

This was set by @willsputra - `Grant.description`

> * [ ] This grant has no Team members. Should we allow a grant with no team members? My gut says no.. At the very least, the pereson who posted the grant should be on the team.

Agreed.  I'll update it to automatically add the admin to the team list.

> * [ ] Results could not be loaded on 'team members' input. I assume this is GH API rate limit issue?

Yes.  Fixing it now.

> * [ ]  [This link](http://bits.owocki.com/b63654545bb8/Screen%20Shot%202018-11-20%20at%2011.12.43%20AM.png) goes to the external URL, not to the actual grant URL

This link directs to the `Grant.reference_url` that was provided during the creation process.
This [grant](https://grants.gitcoin.co/grants/5) has `http://github.com/` provided as the reference URL.

Do you think it'd be helpful to link back to gitcoin grant details versus the external url or omit it entirely?

> * [ ] integrity error upon insert screenshot - SHOWSTOPPER

I'll look into this shortly! Should be a simple fix.

> * [ ] can we add a SLUG to the grant URL? https://grants.gitcoin.co/grants/8 coudl become https://grants.gitcoin.co/grants/8/foo-bar

🙌 Sounds good.

**Comment by owocki** [comment]
> This was set by @willsputra - Grant.description

oh so it's not dynamic?  nice!

> I'll look into this shortly! Should be a simple fix.

let me know how this goes so i can continue QA :)

**Comment by thelostone-mc** [comment]
Open issues are captured here #2949
