### ISSUE TITLE
bounty creation / github issue field doesn't need to be a github issue

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2909]
**Describe the bug**
any url works

**To Reproduce**
enter a url

**Expected behavior**
check for ^http(s)://(www.)?github.com/.*/issue/[0-9]*$

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48826996-2fdc0780-ed6c-11e8-8691-ea217c0fa92a.png)

**Comment by Anish-Agnihotri** [comment]
Should be an easy issue using regex. 

Just a lint for `https://github.com`, so something along the lines of: `pattern="https?:\/\/(www\.)?[github.com]\[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)"`. This wouldn't work in certain scenarios though, so I'll work on it tonight. Or, we simply check for instances of github.com in JQuery and only allow those inputs.
