### ISSUE TITLE
>5 kudos recipients looks weird

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2911]
**Describe the bug**
If more than 5 people receive a kudos, the display gets wonky.

**To Reproduce**
Send kudos to more than 5 people

**Expected behavior**
proper alignment

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48851712-08a52a80-edac-11e8-9a60-0f885b112e06.png)

**Comment by thelostone-mc** [comment]
Fixed up over at https://github.com/gitcoinco/web/commit/1e393c613408cd77a918e0246d9f2f6071a35342#diff-f1b95d391d9b7bf1f3d062c3480d46c1

Thanks @kuhnchris for the report :D
