### ISSUE TITLE
confetti-rain is limited :-(

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2913]
**Describe the bug**
The confetti rain when sending (or receiving) a Kudos is only partly partying.

**To Reproduce**
Send a kudos

**Expected behavior**
party all over the page

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48851895-77828380-edac-11e8-9a72-2722fe558540.png)

**Comment by Anish-Agnihotri** [comment]
Looks like the confetti rain is working for me across displays. Was there a specific resolution you used so I can test?

**Comment by kuhnchris** [comment]
1262x865 - latest chrome - mac os x

**Comment by Anish-Agnihotri** [comment]
Seems to be working for me at that resolution. I do see the confetti-rain. Is the issue that you can't see the confetti-rain, or did I misunderstand by chance?

**Comment by kuhnchris** [comment]
it's cut off if you scroll down

**Comment by Anish-Agnihotri** [comment]
Yikes, still can't see it. I'll test tonight when I get home and re-check. Should be an easy issue to fix.

**Comment by owocki** [comment]
i think the canvas (DOM element where the rain plays) just needs to be positioned absolutely
