### ISSUE TITLE
Invoice logo is broken

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2919]
**Describe the bug**
When trying to print an invoice, you see a missing image icon

**To Reproduce**
Be bounty starter, start bounty, check invoice

**Expected behavior**
Not sure tbh

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48916360-45dbec00-ee82-11e8-9f53-05ab1d5f1cc1.png)

**Comment by octavioamu** [comment]
Couldn't reproduce in my local, I will check if I have some invoice online to check it

![image](https://user-images.githubusercontent.com/1358093/48917246-f0e1ab00-ee6c-11e8-9193-ee2b24f83ae8.png)

**Comment by kuhnchris** [comment]
Thanks for checking @octavioamu !
Where does it redirect you locally?
I get this URL in the invoice: https://gitcoin.co/issue/v2/images/presskit/GitCoinLogoText.svg
This one doesn't exist. Maybe it's another one of those missing images that just need pulling from GIT?

**Comment by octavioamu** [comment]
@kuhnchris thanks for that info was a problem with the name (we shouldn't be using camel case in images names)  correct link is https://s.gitcoin.co/static/v2/images/presskit/GitcoinLogoText.svg

**Comment by thelostone-mc** [comment]
thanks @kuhnchris \m/
