### ISSUE TITLE
Avatar / still mismatching avatar images

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2920]
**Describe the bug**
After @owocki  and @mbeacom 's last fix we thought my avatar was unified. It wasn't.

**To Reproduce**
???

**Expected behavior**
Avatar-Builder Avatar == Gitcoin used avatar

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48916836-2ba30d80-ee84-11e8-9b56-c26bc4a6095e.png)

**Comment by owocki** [comment]
just pushed up a fix i thikn shoudl help with this

**Comment by kuhnchris** [comment]
Great, that got fixed! Thank you!
