### ISSUE TITLE
In Progress Tab on Profile shows "Done" bounties

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2927]
**Describe the bug**
There is a issue that is "done" in my "in progress" tab

**To Reproduce**
???
https://gitcoin.co/profile/kuhnchris

**Expected behavior**
Gitcoin Bounties done are in "done"

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/48940716-f1d01680-ef18-11e8-8a37-a23a53b85bc3.png)
![image](https://user-images.githubusercontent.com/761911/48940737-03192300-ef19-11e8-913c-64fec19be2e1.png)

**Comment by owocki** [comment]
hmm.... it probably is picking up the activities from when they *were* in progress.  i guess the question is : is the activity feed a feed of historical reference? or only of current activities?

**Comment by kuhnchris** [comment]
The basic activity feed? Yes that is a historical reference.
But "In Progress"? No.
