### ISSUE TITLE
as a user, i want to know when my tip/kudos fails, so i can take appropriate action

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2937]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to know when my tip/kudos fails, so i can take appropriate action

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)

sometimes a tx fails on the ethereum network.  and our app should be smart about that

*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no handling of failure states

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

use the code that was created in https://github.com/gitcoinco/web/issues/2663 : to program the following user facing functionality

* If a Tip/Kudos drops/fails, or takes more than 12 hours to clear, we should notify the sender with an email that tells them so.   If pending, send them [this article](https://github.com/gitcoinco/gitcoinco/issues/50) and ask them to speed up the transaction.  If dropped/failed ask them to resend the tip and [send them here to debug](https://www.reddit.com/r/ethereum/comments/7so0vx/my_eth_transaction_failed_what_happens_next/)
* We only trigger 'you have a new tip/kudos' emails to recipients (and the 'claim xx' button in the nav will only appear) after the tx clears. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Above scope is implemented.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@vs77bb @PixelantDesign hopefully this will ward off some support requests.. any feedback?

**Comment by PixelantDesign** [comment]
Good idea. The only thing I'm not sure about is 12 hrs to clear. It's a good starting point though. We can adjust after we see how it's working.
