### ISSUE TITLE
small layout bugs on tips

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2940]
robbiebent [5:59 PM]
Noticed a small bug on Gitcoin Tips ...
https://www.dropbox.com/s/q1f26xg1884xftx/Screenshot%202018-11-19%2019.56.59.png?dl=0
When I hovered on "where are my tokens going" -- couldnt scroll up to read the box.
Using chrome
On a mac

**Comment by Anish-Agnihotri** [comment]
I'll check this out, since I rewrote the tooltip in the last PR.
