### ISSUE TITLE
As an admin of Gitcoin, if one cancels a bounty as a funder, I want to know the reason why.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2948]
### User Story

As an admin of Gitcoin, if one cancels a bounty as a funder, I want to know the reason why.

### Why Is this Needed

We're always looking to improve the Gitcoin experience. We'd like to have data regarding why bounties were cancelled. 

### Current Behavior

When a bounty is cancelled, an email is sent, but that doesn't offer a high probability of funders providing reasons for cancellation.

### Expected Behavior

**Cancelled Bounty**

When a funder cancels a bounty on the bounty issue detail page, a modal pops up with these options. You should only be able to select one option. If "Other" is selected, the free text is required:

* An alternative commit, patch, or solution solved the issue.
* The scope of work changed.
* The bounty was brought to our internal team.
* The bounty had no workers and/or was consistently abandoned.
* The quality of submitted work was not up to par.
* The bounty was not needed anymore.
* Other (free text box)

It should look something like this:

![47867145-a48de700-de3b-11e8-9654-318969d6b635](https://user-images.githubusercontent.com/7516920/49032151-bcb60500-f160-11e8-8527-4457565fcff3.png)

For the cancellation reasons flow:

1. click “cancel bounty” up in admin bar area
2. which takes us to the cancellation page
3. add cancellation reasons on the cancellation page (design example IP).
  4. the user inputs reasoning, hits "cancel bounty", the transaction processes, and redirects us to bounty detail (edited)

For the data model: 

1. Update the [data model](https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py) so that the Django administration reflects an area for `cancelled_bounty_reason`.
2. Ensure that the user response is recorded (POST).
3. New data model is updated to Postgres. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] "cancelled" reasons built into the cancellation page (design example IP)
- [ ] "cancelled" reasons recorded and updated in the data model

**Comment by frankchen07** [comment]
@octavioamu - if the data model portion is unclear, let me know, I'll see if I can dig up a clearer understanding of it, see if the community has someone who understands Django better than me.

**Comment by hatgit** [comment]
Perhaps add this reason for cancellation too (happened to me): "Bounty was posted twice in error (duplicate)."
(note: I didn't distinguish whether it was user error or system, that could be a sub-option if the above is selected.)

**Comment by octavioamu** [comment]
@frankchen07 I think the images need to be updated with the options layout right?

**Comment by octavioamu** [comment]
@hatgit in that case I think you will click the "other" and fill with that reason.

**Comment by octavioamu** [comment]
@frankchen07 this works for the admin side? 
![image](https://user-images.githubusercontent.com/1358093/49053493-718b0900-f1d7-11e8-8371-2d057a37660f.png)

**Comment by willsputra** [comment]
@octavioamu @frankchen07 Thanks for creating the build ticket!

Sketch file for Cancelled Bounty
https://drive.google.com/open?id=1oiJnHRyeQKGDPzylcLfu0u9stbRAWYk7

Will upload the one for Stop Work later today!

**Comment by frankchen07** [comment]
split the ticket, this one is cancellation, the other will be for stop work. 

@octavioamu - just a nit fix to change "Cancelation reason" -> "Cancellation reason" above for the admin side.

**Comment by octavioamu** [comment]
Updated design by @willsputra 
![image](https://user-images.githubusercontent.com/1358093/50246630-0e972700-03bd-11e9-918e-5d5b30c3dcab.png)

**Comment by thelostone-mc** [comment]
Is this up for grabs? :P Mesa like the design. Mesa want to code 
@frankchen07 @willsputra @octavioamu

**Comment by octavioamu** [comment]
@thelostone-mc this one is ready, just making some small things and submitting a PR today but #2895 is free and I think is ready to code.
