### ISSUE TITLE
Invalid users in the "Who got this kudos" section?!

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2954]
**Describe the bug**
Users on the "Kudos received" page do not exist or lead to 404.
May be connected to not accepting the kudos tho.
![image](https://user-images.githubusercontent.com/761911/49047184-e6117800-f1d6-11e8-881d-a298da50808d.png)

**To Reproduce**
Check Product Wizard Kudos, click receivers

**Expected behavior**
Get at least a screen that says "This Kudos has not been claimed by it's owner." instead of flat out 404ing or showing a page without kudos.

**Screenshots**
see above

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris !
