### ISSUE TITLE
starfall bug

### ISSUE THREAD

**Issue by aquiladev** [gitcoinco/web#2958]
**Describe the bug**
When I open website screen with starfall and scroll to bottom while star is falling, screen size increases, then screen starts jumping

**To Reproduce**
see description

**Expected behavior**
Screen size should remains static, no jumping

**Screencast**
[(_..) Issue Details _ Gitcoin - Google Chrome 11_27_2018 9_33_38 AM.zip](https://github.com/gitcoinco/web/files/2619016/_.Issue.Details._.Gitcoin.-.Google.Chrome.11_27_2018.9_33_38.AM.zip)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Browser Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by PixelantDesign** [comment]
Thanks for reporting @aquiladev!
