### ISSUE TITLE
Displaying "more" kudos on profile loads wrong/double/weird kudos

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2960]
**Describe the bug**
Kudos are displayed double or weirdly sorted when clicking on "more"

**To Reproduce**
Click "more" on a profile >10 Kudos

**Expected behavior**
Show other kudos than the 10 already displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/49094273-2c61e800-f266-11e8-8737-7447efc33791.png)

@octavioamu

**Comment by owocki** [comment]
79b19ea59a8a69a62dc07b960f28d5f837d74814 should fix this
