### ISSUE TITLE
Nav: Change icon of 'Send Kudos' and 'My Grants' on nav dropdown

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#2961]
### Current Behavior

Icons of 'Send Kudos' and 'My Grants' on nav dropdown do not represent the branding of the feature
<img width="270" alt="screenshot 2018-11-28 01 17 30" src="https://user-images.githubusercontent.com/19514207/49099129-a8325380-f2ab-11e8-9d6b-b23d4f60ba98.png">

### Expected Behavior
Change the icons of 'Send Kudos' and 'My Grants' following the screenshot below:
<img width="433" alt="screenshot 2018-11-28 01 16 26" src="https://user-images.githubusercontent.com/19514207/49099132-a9fc1700-f2ab-11e8-9248-2e4cf4ef0256.png">

Sketch files (new icons inside):
https://drive.google.com/open?id=1JLMtaFe3ul7nyWgH4q_1cxCIFOImUUEV

**Comment by Anish-Agnihotri** [comment]
Hey!

Couldn't access the icons from the sketch file (seems to be a recurring issue for me, which means my Sketch is probably broken, haha). 

If you can export the two icons and share a link, I'd be glad to knock this out tomorrow.

Thanks,

Anish

**Comment by usmanmuhd** [comment]
@Anish-Agnihotri Shall I take this up if you are okay with that?

**Comment by Anish-Agnihotri** [comment]
@usmanmuhd 

For sure!

**Comment by willsputra** [comment]
@usmanmuhd @Anish-Agnihotri thank you! here are the two icons .svg
https://drive.google.com/open?id=1_z42vS_ri8sF3iVLDSfBXjTqIdcDkA98

**Comment by usmanmuhd** [comment]
I cannot see the grants option on master branch. So should I make the grants change on `grants` branch?

**Comment by thelostone-mc** [comment]
@usmanmuhd on `grantz` branch

**Comment by thelostone-mc** [comment]
Thanks @usmanmuhd  ^_^

**Comment by thelostone-mc** [comment]
@usmanmuhd So we've got a bug for both the logos on hover!
Could you throw in a PR to ensure on hover we show the white svg ? 

<img width="268" alt="screen shot 2018-11-29 at 7 31 36 pm" src="https://user-images.githubusercontent.com/5358146/49226769-84871e80-f40d-11e8-9e23-02c4c9b47747.png">

I've already added the white svg file in `grantz` for grant !
The wiring + same for master (kudos) will have to be done

**Comment by thelostone-mc** [comment]
>  It's the white svg for icon that is needed (not the white logo).

Yup I meant the very same ^_^
