### ISSUE TITLE
As an admin of Gitcoin, if one stops work as a contributor, I want to know the reason why.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#2963]
### User Story

As an admin of Gitcoin, if one stops work as a contributor, I want to know the reason why.

### Why Is this Needed

We're always looking to improve the Gitcoin experience. We'd like to have data regarding why work was stopped. 

### Current Behavior

Currently when work is stopped, no reasons are given, and the user is not prompted to tell Gitcoin why they stopped work.

### Expected Behavior

**Stop Work**

When a user clicks stop work on the bounty issue detail page, a modal pops up with these options. You should only be able to select one option. If "Other" is selected, the free text is required:

* There was no response from the funder.
* Someone else was approved / reserved for the bounty.
* The scope of work deviated from the initial bounty.
* There were technical blockers that prevented the bounty from being completed.
* I was unable to finish the bounty with my current skillset.
* I no longer have time to do the bounty.
* I reached the max cap of allowable bounties and wanted to work on something else.
* Other (free text box)

It should look something like this: 

![47867158-abb4f500-de3b-11e8-84c3-423f90a5416b](https://user-images.githubusercontent.com/7516920/49032148-baec4180-f160-11e8-97b0-254344fa25fd.png)

1. Update the [data model](https://github.com/gitcoinco/web/blob/master/app/dashboard/models.py) so that the Django administration reflects an area for `work_stopped_reason`.
2. Ensure that the user response is recorded (POST).
3. New data model is updated to Postgres.

**Comment by kuhnchris** [comment]
https://github.com/gitcoinco/web/issues/2668

**Comment by willsputra** [comment]
![stop work](https://user-images.githubusercontent.com/19514207/49172101-1265f980-f37b-11e8-87c3-acd4edb17bc0.png)

Sketch file:
https://drive.google.com/open?id=1hCHT2vAsPJu9x6fZnnonSzZUcAcrZntL

**Comment by octavioamu** [comment]
Where in the admin we should show the reason? Im trying to figure out that because can be more than 1 work stopped.
