### ISSUE TITLE
Option being hid on hover in /grants

### ISSUE THREAD

**Issue by usmanmuhd** [gitcoinco/web#2975]
In the navbar option is being hidden on hover at https://gitcoin.co/grants/
![screencast from wednesday 28 november 2018 07_54_47 ist](https://user-images.githubusercontent.com/26684281/49158314-de251580-f347-11e8-9552-516d148b3f7f.gif)

**Comment by PixelantDesign** [comment]
Thanks for the report @usmanmuhd !
