### ISSUE TITLE
ETH value entered for bounty is changed after hitting Tab button

### ISSUE THREAD

**Issue by dereksilva** [gitcoinco/web#2983]
**Describe the bug**
When creating a new bounty, if you hit the `Tab` button on your keyboard after entering an ETH value to fund, the ETH value is automatically changed.

**To Reproduce**

1. Visit https://gitcoin.co/funding/new
2. Enter a GitHub issue URL
3. Completed the Project Type, Permissions, Issue Details, Expired In, GitHub Username, and Notification Email fields
4. Choose `ETH` for Denomination, enter `1` for Amount, then hit the `Tab` button on your keyboard

Result: `1` changes to `0.999`

**Expected behavior**
The value entered should remain. 

**Screenshots**
You can view a video here: https://drive.google.com/file/d/1LQ8qIvZWUckwaPDti7nrdg4WSik-_pFx/view?usp=sharing

**Desktop:**

- OS: Windows 10 Home, 64-bit
- Browser: Firefox Quantum
- Browser Version: 63.0.3 (64-bit)

**Additional context**

If I use my mouse/trackpad to click elsewhere and remove focus from the field, the value entered does **not** change.

**Comment by PixelantDesign** [comment]
Thanks for the report @dereksilva !
