### ISSUE TITLE
Message posted was delayed.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2989]
## Message posted was not timely. Should have been sent when worker started work.

https://github.com/foxer666/node-stratum-pool/issues/32

**Notes**
In my case particularly I've offered a developer working environment with everything installed and configured to save him some time.
That's why I was thinking live chat would be good idea, to send him credentials.

However, if his message was posted to github immediately when he started the job, I'd try to contact him via email.
But, the problem (bug?) was that his message was posted after he already finished the job.

 https://github.com/foxer666/node-stratum-pool/issues/32#issuecomment-430313510

Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**
The message should be sent when
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done

**Comment by kuhnchris** [comment]
I noticed a big number of github calls, maybe check sentry if there are any prod errors regarding github? (maybe exceed api call limit)
