### ISSUE TITLE
fix docker default redis configuration to avoid error on bgsave

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2993]
**Describe the bug**
After a while of running the web docker redis starts to hang and take the instance with it

**To Reproduce**
run web docker for an hour or so

**Expected behavior**
website still worken

**Proposed solution**
disable stop-writes-on-bgsave-error

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/49205884-a605ed00-f3b0-11e8-9798-8b82a572b5cc.png)

**Comment by mbeacom** [comment]
How long was Redis running? I haven't encountered this running on the standard `docker-compose.yml` configuration spanning days. 🤔 
Are you running with the standard compose configuration when this occurs or a modified environment? Have you modified any caching/redis settings?

**Comment by kuhnchris** [comment]
usually after an hour or two. Running the default docker-compose.

**Comment by kuhnchris** [comment]
```
redis_1    | 2230:C 29 Nov 15:20:15.058 # Failed opening the RDB file root (in server root dir /etc/crontabs) for saving: Permission denied
redis_1    | 1:M 29 Nov 15:20:15.158 # Background saving error
redis_1    | 1:M 29 Nov 15:20:21.040 * 1 changes in 3600 seconds. Saving...
redis_1    | 1:M 29 Nov 15:20:21.040 * Background saving started by pid 2231
```
