### ISSUE TITLE
Mentors

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#30]
Idea that came out of Ethereum Denver meetup last night:
* It'd be interesting to assign a mentor/mentee relationship to a bounty.  Basically, if developer decides to make a go to a bounty, they can ask another project member with more experience to mentor them on details where they'd add value, in exchange for some amount of the final payout.

**Comment by phal0r** [comment]
I like the idea and I would suggest the same for the other site - the funder should be able to look for a developer implementing the bugfix/feature and to look for another (senior) developer to review the implementation.

**Comment by owocki** [comment]
moved to https://github.com/gitcoinco/skunkworks/issues/46
