### ISSUE TITLE
DESIGN - as a new gitcoin community member, i want gitcoin.co/contribute, so i know how i can contribute to the network

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3007]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a new gitcoin community member, i want gitcoin.co/contribute, so i know how i can contribute to the network

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
it's overwhelming to join our community and not know where to start. 56% of developers who join OSS communities dont know where to start.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no contributet page 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

a page that shows off different ways one can contribute to the gitcoin community.  this page shoudl be linked in the nav. and also in the gitcoin welcome slackbot initial message

calls to action we'll want to have.

Contribute Code
- Check out GitHub issues with the tags Good first issue or Help needed
- Write code examples for documentation
- Report a bug and work on resolving it
- Collaborate with others on building new features
CTA: Link to gitcoinco/web or gitcoinco/codefund

Contribute Support
- Fix typos in documentation
- Translate documentation to your local language
- Write tutorials and blog posts
- Answer questions on the Gitcoin Community Slack or Github issues
CTA: Link to community slack , Link to Gitcoin amabassador application

Contribute Artwork
- Create Gitcoin-themed artwork
- Make money for the creation of Gitcoin art
CTA: Link to gitcoinco/creative, latest Avatar asset contest, or gitcoin.co/kudos

Contribute Research
- Work with some of the top minds in the space.
- Work on bleeding edge web3 technology
- Get to see the latest & greatest Gitcoin Labs research before anyone else.
CTA: Link to gitcoinco/labs

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
make repsonsive.
allow 2-3 iterations of design

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
inspiration
https://rasa.com/community/contribute/

**Comment by owocki** [comment]
hey @vs77bb @PixelantDesign @willsputra any feedback on this?

also @coderberry -- youre a pro at galvanizing OSS communities.. is this a good idea?

**Comment by PixelantDesign** [comment]
I like the idea, and it's definitely needed.
I was thinking #1672 and #1860 could house this type of info.

It's not as sexy but I wonder if we could add a section in the developer guide for now?
https://gitcoin.co/help  Could spruce up the guide with some images/formatting.

cc @pinkiebell

**Comment by pinkiebell** [comment]
Yes, the funder/developer guides would be a good fit for this.
@owocki If you check the wagtail pull request again, you should be able to preview the pages.
If you want to publish them you to copy & paste the existing content to a new page. (Bug due to wagtail internals)

**Comment by owocki** [comment]
wagtail is live https://gitcoin.co/cms/
