### ISSUE TITLE
BUILD - As a Gitcoiner, I'd like to have a weekly recap on how my bounties are doing

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3013]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder, I'd like to have a weekly recap on how my bounties are doing.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: If a funder has multiple bounties being worked on, it's hard to see the status of his/her bounties at a glance.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Build an email for weekly recap emails
- [ ] This email should have a title
- [ ] The user name should be dynamic
- [ ] Please display all of the information in the mockup
- [ ] View Bounty links to the appropriate bounty
- [ ] Email must be responsive
- [ ] Review with core team members

### Reference

Please see #2544 

![48913556-b2bbaa00-eeb3-11e8-8333-ce2957339d08](https://user-images.githubusercontent.com/238235/49252924-54cb1d00-f3f3-11e8-9209-7fe52a09e366.jpg)

@willsputra could you provide the sketch file?

**Comment by willsputra** [comment]
@PixelantDesign edited your original post to fix the link under 'References'.

Sketch file here!
https://drive.google.com/open?id=1aKejF0wEmBXk6ezjT6DpJBOB0j1sx9Wc

**Comment by PixelantDesign** [comment]
@kuhnchris as we chatted earlier lets focus on bounties first and then if we have some time at the end add in kudos sent/received below that.

**Comment by kuhnchris** [comment]
Hi there @owocki @mbeacom helped me fixed everything up, so I already managed to get enough bounties in:

![image](https://user-images.githubusercontent.com/761911/49834479-c8c6d700-fd9c-11e8-9a90-99019f18e646.png)

So those are already live data, (rinkeby), Links work, titles work, the / new_bounty is for me, since I am currently categorizing them. 

One more thing: the picture on the left, do you want it to be the default profile picture, or your own (e.a. the bounty's image) or the activity person's image? If so then we also should put in (for example for apply work or drop work or whatever) the name of the person doing the change, don't you think so too @PixelantDesign ?

**Comment by PixelantDesign** [comment]
Wow looking great @kuhnchris!

I know it currently shows the project icon, but what seems the most useful is the person's image, Github user name, and Github issue number and part of the description which you already have.

What do you think @willsputra ?

**Comment by willsputra** [comment]
@PixelantDesign @kuhnchris yeah if we could put the activity person's image and username that would be great!

**Comment by kuhnchris** [comment]
Hey there @willsputra  and @PixelantDesign 
What you guys think about this?

![image](https://user-images.githubusercontent.com/761911/49940965-780cc680-fee1-11e8-9e8c-2c4da8751d33.png)

**Comment by kuhnchris** [comment]
Another nightly update:
![image](https://user-images.githubusercontent.com/761911/49975080-6d334f80-ff3c-11e8-83bf-10564a90ec49.png)

@willsputra is there a reason why you added such a big margin/border to the entire page? we have a standard size in the base template, which I used, If you need it really that small let me know!

**Comment by willsputra** [comment]
Looking good @kuhnchris! I like that you've added the timestamp too 👍

Yeah I think we can stick with the standard base template. Just a couple of little tweaks:
1. Since the timestamp is less important compared to the bounty title, I'd separate them and also make the timestamp gray
2. Add a bit more padding between each bounty

<img width="933" alt="screenshot 2018-12-14 21 02 13" src="https://user-images.githubusercontent.com/19514207/50004950-a1ae1680-ffe3-11e8-843c-01067663f74f.png">

**Comment by kuhnchris** [comment]
Better?
![image](https://user-images.githubusercontent.com/761911/50008661-30576f00-ffb5-11e8-8370-e001f8cba21b.png)

**Comment by willsputra** [comment]
@kuhnchris Yesss that looks great!

Good idea. Maybe we can put it with opening text (would be great if we can make the timestamp format consistent too):

"Hi mbeacom,
Here are the latest activities on your bounties
(Dec 1, 2018 - Dec 12, 2018)"

What do you think?

**Comment by willsputra** [comment]
@kuhnchris @PixelantDesign here ya go!
<img width="699" alt="screenshot 2018-12-17 22 43 20" src="https://user-images.githubusercontent.com/19514207/50094044-32d3f600-024d-11e9-84e8-474efb2a9a01.png">

**Comment by willsputra** [comment]
@kuhnchris how's it goin? :)

**Comment by kuhnchris** [comment]
My bad, currently in a bit of a transistion period. I'll add the changes tonight or tomorrow.

**Comment by PixelantDesign** [comment]
Looks good! Excited to see this!

**Comment by kuhnchris** [comment]
Hey there @willsputra and @PixelantDesign 
sorry for the long delay!
![image](https://user-images.githubusercontent.com/761911/50455654-c5f8e400-094f-11e9-9d5e-4a2feae109ba.png)
does that look like it would fit?

Header change:
![image](https://user-images.githubusercontent.com/761911/50455666-ea54c080-094f-11e9-91d4-1dd1b9e75d7d.png)

@PixelantDesign as we discussed, "Review" when there's a action required.
![image](https://user-images.githubusercontent.com/761911/50455676-fe002700-094f-11e9-86c6-b1a7412bed2e.png)

**Comment by willsputra** [comment]
@kuhnchris looks good to me!

**Comment by kuhnchris** [comment]
Thanks for checking in @willsputra!
@PixelantDesign the only thing I am not entirely sure is: is the "email sending" part of the BUILD ticket?

Or, differently asked: 
- is creating the mail sending job (= administrative task) also part of the ticket?

Thanks
Chris

**Comment by PixelantDesign** [comment]
Checking on this for you @kuhnchris, could I give you an image to add to the top of the email? I know I'm scope creeping here....

**Comment by kuhnchris** [comment]
sure, no probs

**Comment by PixelantDesign** [comment]
Hey @kuhnchris please use this image above the Weekly Bounties Recap H1 

![weekly_robot](https://user-images.githubusercontent.com/238235/50520497-b633e980-0a8e-11e9-8934-ce1d4423ee35.png)

**Comment by kuhnchris** [comment]
Above the H1? Well, sure, here you go:
![image](https://user-images.githubusercontent.com/761911/50521746-6de4ed80-0ac7-11e9-8026-f67582dd91d3.png)

**Comment by PixelantDesign** [comment]
Great work!

**Comment by kuhnchris** [comment]
As I said, it's still not done, but thanks for the tip, we'll finish it up as soon as we have some test data on stage and/or live, depending on where we can use it to work with. ;-)
