### ISSUE TITLE
Weird class names on new in-dapp purchasing objects on avatar builder

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#3016]
**Describe the bug**
(asthetic bug)

**To Reproduce**
check source of avatar builder

**Expected behavior**
classes properly named

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/49256345-fe7bcf80-f42e-11e8-9f14-9ceabd48b136.png)

**Comment by PixelantDesign** [comment]
Do you have any suggestions @kuhnchris ?

**Comment by kuhnchris** [comment]
Not really a suggestion (except for cleaning up the code, I guess), just making sure this is not something that breaks anything display-wise, especially the class "[]" and the many empty lines between the class options.
