### ISSUE TITLE
Payout->Advanced->naming issue (right hand side)

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#3018]
**Describe the bug**
By entering different names into the box during advanced payouts you pay the tip to an amalgamation of names.

**To Reproduce**
enter different names

**Expected behavior**
the entered name should appear on the right

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/49258433-bf04b180-f435-11e8-8a25-9170151617df.png)

**Comment by PixelantDesign** [comment]
Names are there now 
<img width="344" alt="screen shot 2019-01-11 at 3 02 33 pm" src="https://user-images.githubusercontent.com/238235/51056859-f5dff280-15b1-11e9-9945-f6642bebf905.png">
