### ISSUE TITLE
As Gitcoiners I'd like to receive Kudos for being at the top of the leaderboard.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3021]
### User Story

As a **contributor**, I'd like to be recognized on Gitcoin for being in one of he top 5 spots on the leaderboard.

As a **funder**, when I browse a profile, I'd like to know who is at the top of the leaderboard, and for how long.

### What 
Take these beautiful Kudos and code them up so that they're sent to our top 5 leaderboard members.

### Why
We want to send Kudos to our top leaderboard Gitcoiners!

### Definition of Done

**Mechanics**
- [ ] Write a management command that will distribute top leaderboard Kudos automatically via email.
We will later wire it up with notifications once this features is out.
- [ ] User should **Not be able to transfer leaderboard Kudos** to another Gitcoiner.
- [ ] Build this so that user does not receive the same NFT week over week

**Kudos Profile**
- [ ] Note the streak on the user's profile on the back of the card. "Streak: 4 weeks"
- [ ] Display range of dates on the back of the Kudos card

**Notifications**
- [ ] User should be notified via email of the initial leaderboard position.
- [ ] User should be notified via email when there is a change in leaderboard position.
- [ ] User should also be notified via Gitcoin slack on Fridays.

**Leaderboard Display**
- [ ] Replace the medal icons with Kudos overplayed on the user icon.

### Reference

![untitled 16](https://user-images.githubusercontent.com/238235/49269813-e909a400-f434-11e8-8daf-0d424dbecd95.png)

**Comment by owocki** [comment]
very excited for this!

**Comment by owocki** [comment]
@PixelantDesign do we want to send these kudos both to the top funders AND top coders?  or just one or the other?

**Comment by owocki** [comment]
just sent these kudos to the top contributors  on this weeks leaderboard to leanly test  https://github.com/gitcoinco/web/issues/3021

**Comment by PixelantDesign** [comment]
> @PixelantDesign do we want to send these kudos both to the top funders AND top coders? or just one or the other?

If we did top Funders - I think the Kudos should be different, dont you? 

Lean test is a great idea.

**Comment by owocki** [comment]
yeah they should be different prob
