### ISSUE TITLE
once wagtail is merged, migrate over medium.com/gitcoin content to gitcoin.co

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3040]
once wagtail is merged, migrate over medium.com/gitcoin content to gitcoin.co

https://github.com/gitcoinco/web/issues/3039

**Comment by mbeharry** [comment]
Hi All,

A few SEO considerations to maximize this migration...

1. URL structure: if they will be changing from what they were on Medium, then we must 301 redirect them.  I can help define these redirects, taxonomy, and whatever else so please let me know.  
2. Canonical tags can be added to the top 50 Medium articles so the pass SEO equity to our newly migrated pages.  I can help but we cant define these til the new site is in staging with final urls.  


SEO Notes:
Taxonomy needed for url structure moving forward. ie: /category/date/title/
301s needed
Canonical Tags into Medium articles
Crawl staging site
Create categories & tags
XML and Yoast

**Comment by owocki** [comment]
wagtail is live so this is unblocked @PixelantDesign https://gitcoin.co/cms/

**Comment by vs77bb** [comment]
@mbeharry @owocki Is the intention to wind down the Medium, or to support both simultaneously? Are there SEO implications in either scenario? Trying to determine whether it's worth supporting both as the Medium page has ~900 followers right now, too 

Best,
V

**Comment by owocki** [comment]
@mbeharry said he wants to do a call before this happens to make sure it goes okay.

some things to do:
- taxonomy of articles
- canonical urls
- ???

@vs77bb volunteered to play a part in migrating this over.

**Comment by owocki** [comment]
doc on seo best practices https://docs.google.com/presentation/d/1J3rg6dAd8PFdjQPbY0TY8zBRkjTR9ks6ODudIUFjaug/edit#slide=id.p

**Comment by mbeharry** [comment]
We need to define Categories & Sub-Categories for each article and then include those in the URL Structure.  I highlighted an example in green in the first row here: https://docs.google.com/spreadsheets/d/1t6QN4wU8af3PjGXWEmftke2ex2gzS4L1joM6HvAaJl4/edit#gid=0
