### ISSUE TITLE
Tip button along with other issue buttons

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#3043]
As a funder I want to have a button that takes me to the tips page so I can give a tip. 

I stared at these options for a while and then I had to go google "How do I send a tip on Gitcoin":
![image](https://user-images.githubusercontent.com/2653167/49326896-40337580-f516-11e8-8905-c28be83e49b6.png)

I found https://gitcoin.co/tip/send/2 but it seems like that should but a button with the others?

**Comment by thelostone-mc** [comment]
Ah that makes a lot of sense! Why didn't I do that already 🤦‍♂️ 

@octavioamu @willsputra should we evaluate if we can evaluate them into a bunch of dropdowns as the list looks pretty huge :P

**Comment by octavioamu** [comment]
Yes today that option is inside the advanced payment I think.
