### ISSUE TITLE
Broken Kudos Loader for Basic Payout

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#3044]
I'm getting a weird broken loader for suggested Kudos on the basic payout page:

![image](https://user-images.githubusercontent.com/2653167/49327114-09f7f500-f51a-11e8-987a-017340537714.png)

**Comment by owocki** [comment]
@octavioamu is this perhaps related to your work with the scrollable kudos?

**Comment by octavioamu** [comment]
🤔 is using `{% static '/v2/images/loading_v2.gif' %}` maybe the image was removed? Is loading in local.

![image](https://user-images.githubusercontent.com/1358093/49382774-6c114f80-f6fe-11e8-8eec-b583f552b7fb.png)

**Comment by austintgriffith** [comment]
not sure. I can get to that image now :) I wouldn't worry about it then

**Comment by owocki** [comment]
this happened to me today.. i am at the office with high speed internet right now

the img points to `https://gitcoin.co/v2/images/loading_v2.gif` , not the missing `static/` part of the link

**Comment by octavioamu** [comment]
The call in the template is `{% static '/v2/images/loading_v2.gif' %}` how it should be to point to the right url?

**Comment by owocki** [comment]
two theories

1. it should be `{% static 'v2/images/loading_v2.gif' %}` ( no preceding slash) 
2. its a collectstatic issue

but im on a call and can't focus on testing it now

**Comment by octavioamu** [comment]
hummm that make sense, the slash should be going to root directory.
