### ISSUE TITLE
Gitcoin says transactions failed when they succeeded

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3049]
**Describe the bug**

From one of our funders: ```I accidentally submitted a bounty 4 times. Ledger & the most recent metamask extension somehow don't play well together and it kept saying the transaction failed when it apparently must have succeeded. The Gitcoin UI however doesn't let me cancel the bounties because I only see one active one.```

*Issue:* 
https://github.com/centrifuge/precise-proofs/issues/23

*Transactions:* https://etherscan.io/address/0x52ec80600642cedde9de1f570335481c348be74c#tokentxns

**Comment by owocki** [comment]
@ceresstation let the user know they can cancel the other bounties on bounties.network with their metamask

https://explorer.bounties.network/bounty/1885
https://explorer.bounties.network/bounty/1886
https://explorer.bounties.network/bounty/1887
https://explorer.bounties.network/bounty/1888

if they wish to consolidate their bounties on gitcoin after they do this, ask them to please leave one of them open and i will consolidate the applied workers (and other info) there.

**Comment by lucasvo** [comment]
I'll close them on bounties network. Let me know if you need any more details on how they were accidentally created.

**Comment by owocki** [comment]
Thanks. I think I understand the OP how it happened .. 

We are brainstorming ways internally to make the UI a little more anti-fragile here on a call on Thursday, but if you have any suggestions @lucasvo let us know!
