### ISSUE TITLE
Worker shows up in 'Work Started' even though he/she has only applied and has not been approved

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3051]
**Describe the bug**
Worker shows up in 'Work Started' even though he/she has only applied and has not yet been approved.
<img width="974" alt="screen shot 2018-12-03 at 10 18 04 am" src="https://user-images.githubusercontent.com/19514207/49383096-f2f01780-f752-11e8-9848-6ed7e7d4e66a.png">

**To Reproduce**
1. Funder creates a traditional, approval-required bounty
2. Worker applies for work
3. Worker shows up under 'Work Started'

**Expected behavior**
Worker shouldn't show up in 'Work Started'

cc @PixelantDesign

**Comment by thelostone-mc** [comment]
@willsputra Could you throw in the bounty url?

**Comment by kuhnchris** [comment]
Did this ever get solved?

**Comment by thelostone-mc** [comment]
I could not reproduce it 😅
