### ISSUE TITLE
Grants Email QA

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3057]
As a grants user, I'd like to be notified of major actions that I take on the Gitcoin grants platform (create grant, edit grant, fund grant, and the like).
 
This is a QA Ticket for the following links:
captnseagraves [12:53 PM]
https://grants.gitcoin.co/_administration/email/thank_you_for_supporting,
https://grants.gitcoin.co/_administration/email/new_supporter, https://grants.gitcoin.co/_administration/email/new_grant, https://grants.gitcoin.co/_administration/email/grant_cancellation,

These two are currently broken:
https://grants.gitcoin.co/_administration/email/support_cancellation, https://grants.gitcoin.co/_administration/email/subscription_terminated (edited)

### Thank You for Supporting Grants

- [x] Fix image overlap. Shrinking Robot might fix this. Use same size as top graphic on all other emails.
<img width="990" alt="screen shot 2018-12-03 at 3 36 15 pm" src="https://user-images.githubusercontent.com/238235/49400158-6d984300-f711-11e8-9faa-0b0cf555358a.png">

- [x] Some images are not displaying
- [x] Get an error when clicked cancel support (might not have been wired up).

### New Grant Created
- [x] Grant Logo not displaying
- [x] View Grant Button is (smaller) not same size as other templates

### Cancelled Grant
- [x] Display navy button "View Inactive Grant" and link to the inactive grant
- [x] Etherscan link not working

### New Grant Created - Looks Good

**Comment by thelostone-mc** [comment]
@captnseagraves the etherscan link , is that wired right ? 
I've taken care of the rest
