### ISSUE TITLE
grants - migrate from 4 gwei to dynamic gas prices 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3067]
grants - migrate from 4 gwei to dynamic gas prices (ideally, driven by the same logic as bounties, displayed below)

<img width="791" alt="screen shot 2018-12-04 at 11 36 29 am" src="https://user-images.githubusercontent.com/513929/49464697-dbe41080-f7b8-11e8-8807-947bc1327490.png">

**Comment by thelostone-mc** [comment]
Todo - add dynamic gas widget on cancel grant popup
