### ISSUE TITLE
add grants to activity_report.py

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3071]
report all the grant contributions in activity_report.py similar to tips/bounties/kudos

**Comment by kuhnchris** [comment]
Mmmh, do you mean activity_report.py as in the dashboard/management/command one? If so, I do not see any references to tips or kudos there... (yes for activities there is something), is that missing aswell and included in this task?

**Comment by owocki** [comment]
yes thats the file i mean

here is the part that adds tips/kudos https://github.com/gitcoinco/web/blob/master/app/dashboard/management/commands/activity_report.py#L200-L208

**Comment by kuhnchris** [comment]
What fields shall be reported? anything special? or simply all we have available?
That's what the model currently offers: 
```
    active = models.BooleanField(default=True, help_text=_('Whether or not the Grant is active.'))
    title = models.CharField(default='', max_length=255, help_text=_('The title of the Grant.'))
    slug = AutoSlugField(populate_from='title')
    description = models.TextField(default='', blank=True, help_text=_('The description of the Grant.'))
    reference_url = models.URLField(blank=True, help_text=_('The associated reference URL of the Grant.'))
    logo = models.ImageField(
    logo_svg = models.FileField(
    admin_address = models.CharField(
    amount_goal = models.DecimalField(
    amount_received = models.DecimalField(
    token_address = models.CharField(
    token_symbol = models.CharField(
    contract_address = models.CharField(
    contract_version = models.DecimalField(
    transaction_hash = models.CharField(
    metadata = JSONField(
    network = models.CharField(
    required_gas_price = models.DecimalField(
    admin_profile = models.ForeignKey(
    team_members = models.ManyToManyField(
    def percentage_done(self):
    def abi(self):
    def contract(self):
```

**Comment by owocki** [comment]
contributions pls !  i have it on my TODO list to map the fields later today

**Comment by kuhnchris** [comment]
Aight, I'll make you a intermediate PR and we can refine the fields as needed, mkay?

**Comment by owocki** [comment]
Awesome!  Thank you so much

**Comment by owocki** [comment]
that seems sane to me - commenting on PR now

**Comment by owocki** [comment]
@kuhnchris woah cool graphic -- howd you make it

**Comment by kuhnchris** [comment]
that's a django_extension default thing. you need to install graphviz and a font and then can run 
```
app/manage.py graph_models <appname> -o <output>.png
```

that maps your data model into a picture
