### ISSUE TITLE
grants - when you sign in metamsk, it looks all scrambled.  we need to make it so you can see what youre signing

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3073]
when you sign in metamsk, it looks all scrambled.  we need to make it so you can see what youre signing

edit:

this is when you make a new contribution to an exsiting subscription, via metamask. Ideally we'd like the contributor to see the details of what they're signing. 

@danlipert says it's most likely from the signature method within the contract, and and Kevin Seagraves said it would involve updating the contract itself, which is quite high lift for relative benefit.

**Comment by captnseagraves** [comment]
![screen shot 2019-01-07 at 4 56 22 pm](https://user-images.githubusercontent.com/22862292/50800378-33d0d400-129d-11e9-98df-d6bdca6eb2b3.png)

**Comment by thelostone-mc** [comment]
@frankchen07 should we bump this up ?

**Comment by captnseagraves** [comment]
@frankchen07 @thelostone-mc Agreed to bump this

**Comment by captnseagraves** [comment]
Happy to take it on

**Comment by frankchen07** [comment]
@captnseagraves - I'll move it to the blue board sprint backlog, but I'm trying to not overtask us. If you can, estimate the task, and we can appropriately move it into the sprint if you start finishing up alot of your current stuff.
