### ISSUE TITLE
my created grants has dupes

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3077]
http://bits.owocki.com/3d9f4ea0cf0e/Screen%20Shot%202018-12-04%20at%201.26.58%20PM.png

**Comment by thelostone-mc** [comment]
@owocki does this still happen? Mesa can't reproduce

**Comment by owocki** [comment]
@thelostone-mc yes it does (screenshot: http://bits.owocki.com/3d4d9ac6b241/Screen%20Shot%202018-12-06%20at%2010.59.03%20AM.png ) -- you have to tab over to the 'created' tab.

also whats Mesa?

**Comment by thelostone-mc** [comment]
mesa -> jar jar binks from star wars 😞 

Oh damn it still looks alright at my end 😓 
![untitled](https://user-images.githubusercontent.com/5358146/49603245-bf122d80-f9b0-11e8-84bb-c6d850f6bcaf.gif)

**Comment by owocki** [comment]
i repro'd on my local and am committing a fix
