### ISSUE TITLE
standardbounties cleanup: multiple fulfillments

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#308]
https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/278

some rando submitted a fulfillment for this bounty — in the legacy gitcoin version of the world, iu'd just 'reject' the fulfillemnt, but that doesnt seem to be an available function for standardbounties

on standardbounties, fulfillments is n:1 with bounties.. so we we'll need to build this capability into the UI.

# todo list:

1. build in n:1 fulfillments <> bounties to the UI (both on the issue detail page, and on the acceptance page).
2. don't update the issue status to 'fulfilled'... just make it 'open' until the fulfillment is accepted.

**Comment by owocki** [comment]
update: @jasonrhaas gonna start on this tonight with with the goal of 1: supporting multiple fulfillments, 2: not using the fulfilled state, so that even if fulfilled people can submit to it

**Comment by jasonrhaas** [comment]
This has been merged in 🚀
