### ISSUE TITLE
as a user, i want to get technical mentorship on demand, so i can solve whatever coding problem i'm having in the moment.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3080]
# story

as a user, i want to get technical mentorship on demand, so i can solve whatever coding problem i'm having in the moment.

# inspiration

1 of my pet theories is that to creative value in the internet of money, we’ll have to come up with core primitives that can be used to construct next-generation financial services.  each of these financial services will creative value by creating p2p financial relationships between people.

the core primitives thus far

- ERC20 - Tokens
- ERC721 - NFTS
- ERC1081 - Bounties
- ERC1337 - Subscriptions

together, these can be used to construct some really dope business models.  but they’re only the start, i think that one core primitive that’s missing is

*Realtime Streaming Money*

basically, how do stream any token from one address to another in a way that’s performant, cheap, usable, and i can trust?

the *streaming-ness* is the important part.  think about what youtube did for the web2.0 internet.  streaming information ( video / audio ) suddenly became easy when youtube (and its clones) launched, and it upended lots of shit (and still is upending things)

the obvious analogue is “what does realtime look like for the internet of value?”

theres an old cliche that “people dont want to pay for software until they have a immediate problem; then they’ll pay anything”.  realtime streaming money plugged into a network of 20k coders has the immediacy that could drive big value!

here are some use cases i would build if i had something out of the box to plug into gitcoin that made streaming money easy:

- MentorMatch (site where I can, on demand, pay for x minute interviews with more senior members of the community)
- CodeHelp (site where i can, on demand, pay for a coding mentor who can pair code with me on whatever i’m stuck on)
- ArchitectureConsultations (site where I can run my software architecture plans for a new feature off an architect who meets my specificadtions)

i’m sure theres lots more that could be done with a primitive like this.  obviously spankchain is built on this entire premise.    one  could build a speed dating site where you pay per minute of your date.  there’s *lots* of possibilities!

# what

I'm thinking that an MVP of a livestreaming application would

1. extend gitcoinco/web 
2. create a new page that allows once to look for a hacker on demand (perhaps filtering by skillset).
3. when the form on page (2) is submitted, the user is taken to a loading page. an email is sent to everyone in the gitcoin userbase that matches their criteria.
4. when the user from (3) gets online, they are paired up to video chat with the OP (original poster)
5. to initiate the chat, the OP must sign a message agreeing to stream DAI to the other user..  once they do, they are placed into chat.
6. they can video chat as long as they want, until either party clicks 'end chat' then the payment channel is closed.

# Judgement criteria

- purdy design which matches gitcoin's style guide ( [see one](https://gitcoin.co/presskit) [and two](https://github.com/gitcoinco/creative)
- intuitive UI
- integrated into the gitcoin webapp (this repo)
- it works
- secure

as such, we belive a successful team should have at least one designer + one dev.

# Milestones

We believe that the following milestones will be important for you to sync with us on during the hackathon process.

1. Application
2. mockup
3. design
2. Prototype

# Reference material

		https://repl.it/site/blog/multi
		https://twitter.com/owocki/status/1079541894286196736
		https://www.reddit.com/r/ethereum/comments/a1vl2f/erc1620_money_streaming/
		https://gitcoincore.slack.com/archives/CD93M06BG/p1543700235016800

**Comment by owocki** [comment]
https://repl.it/site/blog/multi

could be a useful tool to pair with this

**Comment by usmanmuhd** [comment]
@owocki I am interested in working on this as a part of Ethreal hackathon. I will come up with a more detailed spec as the way I understand it.
PS: I am looking for a team mate.

**Comment by pbteja1998** [comment]
@usmanmuhd I want to work on this too. So, shall we team up?

**Comment by usmanmuhd** [comment]
Yeah sure.

**Comment by pbteja1998** [comment]
Ok. I will message u on slack.

**Comment by owocki** [comment]
awesome.. hit me up on slack/discord/here as you all get things together

**Comment by KirkBallou** [comment]
@owocki I tried submitting through Gitcoin but it says 'no active bounty' 
Here is the dApp: https://kirkballou.github.io/reactongit/

**Comment by KirkBallou** [comment]
@owocki  latest build here:  https://kirkballou.github.io/reactongit/
