### ISSUE TITLE
Confirm Wallet Address When User Applies for Work

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3084]
**The Issue:**
Brief Summary: When submitting a request to Start Work on a bounty, the Gitcoin system does not indicate where the funds will be sent if your work is approved. Furthermore during this process, if you have an existing ETH address on file, the system A) fails to inform you that you do, B) does not specify what this address is, and C) does not inform you that funds will be automatically deposited to that ETH address upon approval. 

### Steps to replicate:

On a Github issue w/ a Gitcoin bounty (like this one), click on the 'Gitcoin Issue Details page' link in the first bullet of the gitcoinbot comment.
The link brings you directly to the issue details page on Gitcoin. Notice that on this page, there is no indication of whether you have an ETH address associated with your account or what that ETH address is.

Click the Start Work button, fill out the form, and press submit. Once approved, notice there is no indication of how the funds will be sent to you upon acceptance of your work. Neither on the web app, nor via email.

Throughout the process of requesting to start work, starting work, submitting your work, and having your work submission approved, there is no information provided to you on how the system will pay out the award. The only way to know that you have an ETH address associated with Gitcoin is to proactively navigate to your profile page. 

**Proposed Solution:**
Part 1
After one's 'Start Work' request is approved, the email notification they receive should have the current method of payment included in it. 
If there is an ETH address associated with the account, include that ETH address in the email, and indicate that the funds will be automatically sent to that address upon work approval.
If there is no ETH address associated with the account, indicate that in the email, and explain that they will have the opportunity to claim the ETH to their desired ETH address upon work approval.

Part 2 (Up for debate)
Require each user to 'claim' their award after their bounty is accepted. Instead of automatically depositing the award into the ETH address associated with that account, let the user confirm that the ETH address on file is correct and that they want their bounty reward to be sent there.

Other Ideas:

When a contributor submits work, we ask the user to validate the wallet address on record and update it if needed. We enforce them to check this option as verified so that they are forced to validate it.

We update the email stating that funds have been sent to `X` address  (if we have the address on record ) and if we don't we tell them how they can claim it.

Update marketing materials

**Comment by kuhnchris** [comment]
Well, we could basically not store the eth address (or not use the on file one) until a user clicks on a link in an email.
For example: per default you get the "you got unclaimed funds" mail after finishing work. 
Either, if you only use this once, you click on the claim link and get the funds (and confirm the used address is the receiver address), and if he does that he can use a checkbox "remember my address for future use" or "deposit tips/funds directly into this address from now on" + the ability to change that in his User Profile (Settings).

This way every user has to permit the deposit of the funds once and ensures the address in use is the one the funds should be distributed to. We could also let them sign a message to ensure this is the right account (also, that would probably verify they have access to that account)

Maybe someone else got a better idea, yours seem fine too.
