### ISSUE TITLE
Grants QA 12/5/18

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3086]
- [ ] Date box not working, user will expect to be able to click into it to edit mm-dd-yy.
<img width="801" alt="screen shot 2018-12-05 at 12 24 21 pm" src="https://user-images.githubusercontent.com/238235/49532318-3ac58a80-f88a-11e8-9f55-c97d39bc170c.png">
<img width="783" alt="screen shot 2018-12-05 at 12 24 29 pm" src="https://user-images.githubusercontent.com/238235/49532338-44e78900-f88a-11e8-9ec7-aede261139ea.png">

After create milestone I don’t get a confirmation that it has been created, but dropped back on a blank form. 
- [x] Once a milestone is created, move created milestones above the milestone form. (see mockup)

- [x] Move Back button to the upper left hand corner of create grant page after use has created at least one grant. (see mockup)

- [x] Update link to reflect name of grant created (see mockup)

- [x] Add title **Current Milestones** (see mockup)

<img width="418" alt="screen shot 2018-12-05 at 12 50 25 pm" src="https://user-images.githubusercontent.com/238235/49533197-634e8400-f88c-11e8-8b7a-5c5ba6d44e9a.png">

**Comment by thelostone-mc** [comment]
Addressed in https://github.com/gitcoinco/web/pull/3137
