### ISSUE TITLE
email bug

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3088]
hey all.. good news.. i’ve got a new grant supporter!  bad news ==> bad copy / bad image

http://bits.owocki.com/19bdeb45da8e/Screen%20Shot%202018-12-05%20at%2010.37.57%20AM.png

**Comment by PixelantDesign** [comment]
Suggestion:
2 [token name] every [time period]

**Comment by kuhnchris** [comment]
Well, 2 Token every second seems hardcore... must be a hell of a therapy you're getting.
Anyways, looks like someone got confused when trying to add 'token name' to the translation ;-)
https://github.com/gitcoinco/web/blob/b6a3f05b90278b5686ecf6819226f92f0de7bdc2/app/retail/templates/emails/grants/new_supporter.html#L82

**Comment by thelostone-mc** [comment]
Addressed in https://github.com/gitcoinco/web/pull/3117
