### ISSUE TITLE
Error on DB restore

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#309]
Using the restore database script:

```
ERROR:  invalid input syntax for type json
DETAIL:  Token ""https://api.github.com/users/asp2insp" is invalid.
CONTEXT:  JSON data, line 1: ...81, "url": "https://api.github.com/users/asp2insp
COPY dashboard_profile, line 1588, column repos_data: "[{"id": 26566746, "url": "https://api.github.com/repos/asp2insp/cuckoofilter", "fork": false, "name"..."
```

**Comment by owocki** [comment]
if i just remove this line (the one with `asp2insp` in it)... it works

**Comment by mbeacom** [comment]
@owocki Is this while running `restore_backup.bash` ?

**Comment by owocki** [comment]
off of the AWS backups

**Comment by mbeacom** [comment]
Eh. We're running 10.1 in the docker stack 😁 - We should try to get everything on the same version for parity.

The above issue shouldn't have to do with the version difference, though.  We could implement a function on PSQL and call it to validate the json, if not, `to_json` it or default to null or something?

**Comment by owocki** [comment]
tried deleting that row.. now getting an error:

```
ERROR:  invalid input syntax for type json
DETAIL:  The input string ended unexpectedly.
CONTEXT:  JSON data, line 1: ...ttps://api.github.com/repos/arzynik/ccxt", "fork"
COPY dashboard_profile, line 1561, column repos_data: "[{"id": 15012260, "url": "https://api.github.com/repos/arzynik/cheryl", "fork": false, "name": "cher..."
```

**Comment by owocki** [comment]
i suspect that the JSON data in the DB dump is just too long and that is somehow choking the restore script...

**Comment by owocki** [comment]
ah you know what.. i think this is the issue:

from the output logs:
 
```
pg_dump: [archiver] could not write to output file: No space left on device
```

We need monitoring on these servers to warn of things like this!

**Comment by owocki** [comment]
1c8e47b3006e115c70eafad031f396c3c15f0e54 is a workaround here 

see also https://github.com/gitcoinco/web/issues/310
