### ISSUE TITLE
add grants pages to sitemap

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3090]
add grants pages to sitemap

**Comment by kuhnchris** [comment]
So basically over here (app/app/sitemaps), or do you want something special (like with the Issues and Bounties, e.a. listing the grants)? 
https://github.com/gitcoinco/web/blob/69fa1b5424f5f62f9ed04b38c4c87f41807d9714/app/app/sitemaps.py#L9-L23

**Comment by owocki** [comment]
we need both -- the code you linked is good for static pages, but for the dyanmic ones we'll need something that looks like the `BountiesSitemap`

**Comment by kuhnchris** [comment]
any specific restrictions? Like active = true?

**Comment by owocki** [comment]
nope. `.all()` should be fine

**Comment by kuhnchris** [comment]
Added a PR. 
![image](https://user-images.githubusercontent.com/761911/49687169-8e8cd980-faff-11e8-9ba7-aeea350cecfc.png)

**Comment by captnseagraves** [comment]
@kuhnchris @owocki What is the status of this issue?
