### ISSUE TITLE
As a grants user, when I want to contribute to a grant, there's no searchable tokens

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3091]
### User Story

As a grants user, when I want to contribute to a grant, there's no searchable tokens.

### Why Is this Needed

What denomination should I contribute in? Let me select or type in thar.

### Current Behavior

<img width="918" alt="screen shot 2018-12-05 at 12 31 42" src="https://user-images.githubusercontent.com/7516920/49532923-9c3a2900-f88b-11e8-8834-e02361ea270e.png">

Unsure if this is happening because the grant is in DAI, and I currently have no DAI in my Rinkeby wallet. Technically we should be able to contribute in the denomination we want though, and I have ETH.

### Expected Behavior

Have tokens to select or type in.

### Definition of Done
- [ ] have tokens to select or type in

**Comment by thelostone-mc** [comment]
This works as expected over at https://gitcoin.co/grants/3/lets-check-if-the-subminer-works/fund

![untitled](https://user-images.githubusercontent.com/5358146/49602682-0dbec800-f9af-11e8-895b-0858806d2169.gif)
