### ISSUE TITLE
monitoring for when server runs out of disk space

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#310]
see https://github.com/gitcoinco/web/issues/309#issuecomment-361297106

**Comment by PixelantDesign** [comment]
@mbeacom ok to close?

**Comment by kuhnchris** [comment]
@danlipert is there any monitoring for this in place?

**Comment by danlipert** [comment]
@kuhnchris yup - we have monitoring in place for system metrics like disk space, IO, CPU, memory, etc.

**Comment by owocki** [comment]
i wrote 'monitoring' in the ticket title, but i think what we might really need is alerting when a threshold is reached (cron server is above 85% disk utilization)..
