### ISSUE TITLE
All tokens must convert to USDT or not be supported by Grants

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3102]
All tokens must convert to USDT or not be supported by Grants. If not than the backend will throw an error and not save the contribution.

**Comment by owocki** [comment]
increasing the number of tokens we support as convertable to ETH is out of scope.  i strongly prefer the latter approach

**Comment by captnseagraves** [comment]
This PR addresses the breaking portion of the issue. Tokens that are not convertible to usdt will no longer be added to grant.amont_goal.

We still need to implement either displaying only convertible tokens or saving all tokens in JSON blob and showing contributions in each token.

**Comment by thelostone-mc** [comment]
@captnseagraves This is taken care of right ?
