### ISSUE TITLE
TxRelay idea

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#311]
Have you seen the the "TxRelay" smart contract docs by uPort? It's a way to provide unfunded wallets with the ability to sign transactions and send them to a smart contract using a "RelayEntity" to add gas to the transaction in transit - great concept for allowing people to interact with GitCoin smart contract, who don't have ether yet.

https://github.com/uport-project/uport-identity/blob/develop/docs/txRelay.md

Thanks @kamescg for pointing this out ^^

**Comment by mbeacom** [comment]
💯 This would be handy!

**Comment by KamesCG** [comment]
It's quite clever, even though it relies on a "central" authority to "transport" the transactions.

Any receiving smart contract is required to rewrite smart contract function parameters to include a "sender" parameter. You also have to designate the contract to only receive communication via the "relay" entity via a modifier, which is not ideal, but.... it is what it is.

But as far as I can tell you could include 2 functions (which generate the same result) in the smart contract to accommodate a TxRelay and normal calls - 1 to receive a relayed message and 1 to handle the default "msg.sender" functionality.
