### ISSUE TITLE
Admin Approval / Hide Grants Option for Admin's? 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#3111]
Should we have an 'Admin approval' for Grants to begin, to make sure that the quality of the initial grants is extremely high? 

This could be associated with a loading screen down the road // for now, perhaps a pop-up modal stating:

"Thanks for submitting a Gitcoin Grant. Expect a review of your grant in 48 hours with a coinciding email on whether it meets the requirements." 

Alternatively, could we have a Hide Grants button, which removes the Grant from the main page, but keeps the grant live at the original URL? 

Third option: a 'reprioritize grant button' / way for us to manually order the grants default displaying on https://gitcoin.co/grants/. This is my preference to ensure the highest quality grants get the most viewership from the community. 

Not sure if this makes sense for hard launch so leaving in 'Backburner' for now.

**Comment by owocki** [comment]
the problem with the third option is that sort dropdown on /grants

second option has my vote.  this allows us to wait and see if ppl abuse the functionality and then take action then
