### ISSUE TITLE
Profile should make use of the django user framework

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#312]
##### Description
Currently, we're using `Profile` for all things user-specific.  We should conform to Django standard user auth by making use of the `User` framework.

##### Possible Implementation
We should consider one of the following:
- OneToOne from `Profile` to `User` 
- Making `Profile` extend `User`/`AbstractUser` or add a relation to it.

**Comment by owocki** [comment]
could maybe be folded into https://github.com/gitcoinco/web/issues/234 also

**Comment by PixelantDesign** [comment]
@mbeacom @owocki Not sure where things are on this task but wondering if we should should prioritize this higher now that a profile design is in the works?
