### ISSUE TITLE
Funder unable to payout issue despite work being submitted

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3120]
**Describe the bug**

Only advanced payout is available despite work being submitted on the following issue:

https://gitcoin.co/issue/centrifuge/precise-proofs/29/1868

https://github.com/centrifuge/precise-proofs/issues/29

**Expected behavior**

Basic payout should be triggered upon work submission.

**Comment by thelostone-mc** [comment]
@ceresstation could we get more details on this

- Is he on mainnet + using the right metamask address ?
- can he see the payout button / or where does it fail ?
- screenshot of the issue

**Comment by owocki** [comment]
looks to me like this was paid out 8 hours ago.. did i miss something?

**Comment by owocki** [comment]
https://etherscan.io/tx/0x9bf9165e9a124d2457ec813b69f8da15e79930cfe622f13d4de81e4fb09dd225
