### ISSUE TITLE
Developer & Funder Pages Not Displaying Properly on Safari

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3122]
**Describe the bug**
Developer & Funder Pages Not Displaying Properly on Safari

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

Go to these urls: https://gitcoin.co/funder-guide/  and https://gitcoin.co/developer-guide/
<img width="396" alt="screen shot 2018-12-07 at 8 39 12 am" src="https://user-images.githubusercontent.com/238235/49651040-1ee1f600-f9fc-11e8-84af-e62c0cbb03a0.png">

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Display properly, no overlaps

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

<img width="1274" alt="screen shot 2018-12-07 at 8 38 48 am" src="https://user-images.githubusercontent.com/238235/49651058-2dc8a880-f9fc-11e8-99a9-d3c1883bc3c1.png">
<img width="1270" alt="screen shot 2018-12-07 at 8 39 02 am" src="https://user-images.githubusercontent.com/238235/49651062-2f926c00-f9fc-11e8-8a98-edec9a85177b.png">
<img width="1265" alt="screen shot 2018-12-07 at 8 41 43 am" src="https://user-images.githubusercontent.com/238235/49651069-34572000-f9fc-11e8-9eac-120ee44ef6ec.png">
<img width="1273" alt="screen shot 2018-12-07 at 8 41 52 am" src="https://user-images.githubusercontent.com/238235/49651072-37eaa700-f9fc-11e8-954b-2c14b72f55a2.png">
<img width="1270" alt="screen shot 2018-12-07 at 8 42 01 am" src="https://user-images.githubusercontent.com/238235/49651076-3a4d0100-f9fc-11e8-8cc7-152140698158.png">

**Desktop (please complete the following information):**

<img width="221" alt="screen shot 2018-12-07 at 8 44 11 am" src="https://user-images.githubusercontent.com/238235/49651092-4b960d80-f9fc-11e8-9a01-a8c3b8421a8b.png">

**Additional context**

Refer to this issue https://github.com/gitcoinco/web/issues/1672
cc @pinkiebell

**Comment by pinkiebell** [comment]
Checking....

**Comment by kuhnchris** [comment]
#toc guide.css sticky needs to be changed to position: -webkit-sticky; position: sticky;

**Comment by kuhnchris** [comment]
hahaha guess we both had the same idea @pinkiebell  :-)

Sorry 'bout that.

**Comment by pinkiebell** [comment]
@kuhnchris 😆 . No problem. You are the first 👍
