### ISSUE TITLE
grants/email walkthrough

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#3125]
### Discussion

Visit all templates and ensure the data mapping is done right

- [x] `new_grant`
- [x] `thank_you_for_supporting`
- [x] `succesfull_contribution`
- [x] `grant-cancellation`
- [x] `new_supporter`
- [ ] `support-cancellation` // TODO: percentage_removed logic @captnseagraves 
- [ ] `subscription-terminated` // TODO: percentage_removed logic @captnseagraves 

The templates which are yet to be tested :
- [ ] `transaction_summary`
- [ ] `update_notification`

special attention needs to ensure we are mapping the right etherscan link

**Comment by PixelantDesign** [comment]
On the terminated grant - the header says cancellation, could we be more clear and say that it has been terminated?

**Comment by willsputra** [comment]
@thelostone-mc just got my thank_you_for_supporting email. it says 2 'token name' per seconds which is weird 😅

<img width="843" alt="screenshot 2018-12-14 02 08 33" src="https://user-images.githubusercontent.com/19514207/49958257-33b31200-ff45-11e8-8deb-9d711dfbeabb.png">

**Comment by thelostone-mc** [comment]
@willsputra looks like this is from live ! The image has weird rounded corners and stuff.
Our changes are now not merged into `master` yet. It's in `gitcoin-grantz`

Tagging you on the grant channel to get you some context
This issue along with a bunch of others have been addressed ^_^

**Comment by captnseagraves** [comment]
Sorry for the depay on this issue. I wired up the email with transaction data last week. I believe in this PR https://github.com/gitcoinco/web/pull/3192 

@thelostone-mc I know you took a look and added some commits to that PR. How much of this issue was addressed?

I left to percentage removed logic unchecked since it is dependent on https://github.com/gitcoinco/web/issues/3242.

**Comment by thelostone-mc** [comment]
@captnseagraves I believe that and `transaction_summary` & `update_notification` are left.
wasn't able to get the latter two as it was missing data. 
Are we using those two mail templates ? 
If so what would I need to do be able to populate that data to view it
