### ISSUE TITLE
grants enablement shoudl be based off of django permissions / groups, not based upon is_staff

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3128]
grants enablement shoudl be based off of django permissions / groups, not based upon is_staff

**Comment by owocki** [comment]
@mbeacom @captnseagraves im not sure if theres already a ticket for this, but given that we're going to do a gradual rollout i thought it was important to log

**Comment by mbeacom** [comment]
@owocki Permission based checks are live.
