### ISSUE TITLE
Top-bar symbols not properly sized

### ISSUE THREAD

**Issue by aashutoshrathi** [gitcoinco/web#3131]
**Describe the bug**

The top bar symbols are not of adequate size.
Precisely, Gitcoin symbol and Codefund symbol are being cropped.

![image](https://user-images.githubusercontent.com/21199234/49682355-c5032e00-fad8-11e8-8d21-60acadee811d.png)

**To Reproduce**

Just open gitcoin.co on any mobile device.

**Expected behavior**

![image](https://user-images.githubusercontent.com/21199234/49682363-dc421b80-fad8-11e8-9376-ff7bfb1f9105.png)

**Screenshots**
Provided above

**Desktop (please complete the following information):**

None.

**Smartphone (please complete the following information):**

All devices.

**Additional Context**

I would love to work on this issue.
I have attached expected behavior by fixing this on my branch for #3048 that's why we see Labs there too.

**Comment by aashutoshrathi** [comment]
cc @owocki @PixelantDesign

**Comment by aashutoshrathi** [comment]
cc: @owocki @PixelantDesign @thelostone-mc @mbeacom 
Please check this.

**Comment by thelostone-mc** [comment]
@aashutoshrathi  was this addressed in the PR you had open ?

**Comment by aashutoshrathi** [comment]
No, but I can send quick one.
