### ISSUE TITLE
Transaction FAIL :-D Trying to make a bounty but no dice

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#3132]
**Describe the bug**
Trying to post a bounty with DAI for 1250 DAI, and everything was cool but the transaction failed... I have tried it several times, tweaking things. 

**Expected behavior**
The Transaction should succeed :-D

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Browser Version Newest

**Additional context**
Failed TX
https://etherscan.io/tx/0x49c3967a860bf85d21326234f3c5dcf7d64c3fae5159866606ee8aff3c2ecaad
Issue

**Comment by GriffGreen** [comment]
i'm using the main network via metamask, with address 0x839395e20bbB182fa440d08F850E6c7A8f6F0780

The issue i'm trying to do is: 
https://github.com/ethglobal/ethsingapore-bounties/issues/3

<img width="1062" alt="screen shot 2018-12-08 at 6 50 29 am" src="https://user-images.githubusercontent.com/14945613/49682505-99bb1780-fab5-11e8-9a33-d327313aed02.png">

**Comment by kuhnchris** [comment]
Ah there may be a maximum limit of how much money a contract may involve! I have to check back with @owocki  and @PixelantDesign . Maybe we need to raise that limit on your account on gitcoin. ;-)

**Comment by owocki** [comment]
Just seeing this now.  

On our slack @SaptakS said "Seems like Griff had 5 dai as his funding limit."

I'm going to look into why you only had 5 dai approved as your funding limit.  https://gitcoin.co/settings/tokens should request more than that.

**Comment by PixelantDesign** [comment]
Taken care on site! Go team!
