### ISSUE TITLE
Gitcoin page embedded inside profile page

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#3148]
**Describe the bug**
Profile headers are unreadable in certain situations

**To Reproduce**
Go to https://gitcoin.co/profile/, scroll down and go back to top. Profile headers background is white.

**Expected behavior**
Profile headers background color is not changed.

**Screenshots**
![profile_headers_problem](https://user-images.githubusercontent.com/1838338/49696687-ed109100-fbad-11e8-9c9a-24f2bb499789.png)

**Comment by kuhnchris** [comment]
Are you mouse-over something specific?
What browser and OS does this occur on? (I can't reproduce it on Chrome/Mac OS)

**Comment by kuhnchris** [comment]
Hmm, tried to do this with https://gitcoin.co/profile/owocki . I need to grab myself a copy of Opera to check tho. Does opera have support for MetaMask (or a similar wallet)?

**Comment by kziemianek** [comment]
It seems like its gitcoin embedded inside profile page:
 
![opera](https://user-images.githubusercontent.com/1838338/49699108-59e75380-fbcd-11e8-918d-30b0223378e6.png)

**Comment by kuhnchris** [comment]
That looks really strange, I'll try to check and get back at you when I got a fix, OK? 
Thanks for reporting.

**Comment by kziemianek** [comment]
I tried also with chromium 59.0.3071.109 and problem exists.

**Comment by kziemianek** [comment]
Also it's worth a note there is a difference between https://gitcoin.co/profile/kziemianek and https://gitcoin.co/profile while being logged as kziemianek.

The problem only occours on https://gitcoin.co/profile .

**Comment by kziemianek** [comment]
profile?p=2&a=all returns response with redirect but I have no idea why.
![profile_302](https://user-images.githubusercontent.com/1838338/49719768-6962ad00-fc5e-11e8-8606-60f2dc4bd6d6.png)

**Comment by kziemianek** [comment]
Seems like request is missing few important cookies.
![missing_cookies](https://user-images.githubusercontent.com/1838338/49926147-336e3480-febb-11e8-9398-3b015e4ababd.png)

Redirect to home happens when I'm logged out so it might be the reason.

I have no idea why request is missing cookies but I suggest checking that response with additional data has status code 200 and only then insert html, otherwise display error.
