### ISSUE TITLE
standardbounties: integrate more of the standardbounties functionality

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#315]
per https://github.com/ConsenSys/StandardBounties/

# When in draft 

as issuer:

* changeBountyDeadline() [ONLY ISSUER]
* changeBountyData() [ONLY ISSUER]
* changeBountyFulfillmentAmount() [ONLY ISSUER]
* changeBountyArbiter() [ONLY ISSUER]
* extendDeadline() [ONLY ISSUER]
* transferIssuer() [ONLY ISSUER]
* increasePayout() [ONLY ISSUER]

as anyone:
* contribute() [ANYONE]

# When in active status 

fulfillBounty() [ANYONE BUT ISSUER OR ARBITER]:
updateFulfillment() [ONLY FULFILLER]
acceptFulfillment() [ONLY ISSUER OR ARBITER]:
increasePayout() [ONLY ISSUER]:
transferIssuer() [ONLY ISSUER]
extendDeadline() [ONLY ISSUER]
killBounty() [ONLY ISSUER]:

In this state, the only functions which can be called are:

extendDeadline() [ONLY ISSUER]
contribute() [ANYONE]
activateBounty() [ONLY ISSUER]

**Comment by owocki** [comment]
note: some of these (fulfillBounty) have already been implemented

**Comment by kuhnchris** [comment]
Is that already implemented as part of the standardbounties overhaul?

**Comment by owocki** [comment]
i think that integrating with standard bounties 2 is more of a priority than this.  i know that @danlipert has a ticket for that
