### ISSUE TITLE
premium advertising (maybe using harbringer taxes)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3160]
What if we sell advertising in the weekly newsletter via harbringer taxes https://twitter.com/vitalikbuterin/status/1071181945021710337?s=21

There are other interesting uses of a harberger tax at gitcoin 
- premium spot on a job board
- premium bounties 
- premium grants / kudos

**Comment by owocki** [comment]
That could be interesting. @Owocki if you want to pursue that have you seen Billy Rennekamp's ETHSF hack? Figure you probably have but just in case https://github.com/okwme/harberger-ads-contracts (edited)

**Comment by kuhnchris** [comment]
did...you just @ yourself...?
