### ISSUE TITLE
Kevins Grants QA 2018/12/10

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3171]
Show Stoppers

- [x] When I try to fund [a grant](https://grants.gitcoin.co/grants/9/foo-the-bar-now-2/fund) with a bunch of OWOCKIcoin, I get this BN.js error [screenshot](http://bits.owocki.com/5dfebf171b26/Screen%20Shot%202018-12-10%20at%204.29.00%20PM.png) *note: it works if i use 1/100th of the amount)
- [x] when i try to cancel a grant, i submit two tx's.  the first goes through fine, but the second 'throws a contract error' [screenshot]
(http://bits.owocki.com/269094f9e1ce/Screen%20Shot%202018-12-10%20at%204.34.20%20PM.png)
      - This Error is most likely because you are using a different wallet to sign this message then you used to create the subscription. - KS
- [x] the `approve()` amount when contributing to a grant should be `(cost of contribution PLUS subminer gas costs) * (num payments`.  instead its `(cost of contribution) * (num payments)`, which will cause the last payment to fail because not enough tokens have been approved.
- [x] subminer doesnt seem to actually be processing my txs per https://grants.gitcoin.co/_administrationgrants/contribution/

Major 
- [x] I can set ANYONE to be my grant owner.  this seems kind of strange, i wonder if you could dox someone .. maybe ill create a grant by @vitalikbuterin 
- [x] I should probably be sent an email when someone makes me an owner / team member for a grant.  And I should have permissions to edit the grant.

UX Nitpicks

These might need to become their own tickets:

- [x] None of my grants contributions show up on [my profile](https://grants.gitcoin.co/profile/) 
- [x] or in the [activity feed](https://grants.gitcoin.co/activity) -- Wah!
- [x] Where do I see the contribution history of a grant?    maybe we should take milestoines / 
       - You can see the history contributions to the grants you are associated with in `my grants`, 
        but it should probably be in the grant details/admin page. 
- [x] On a grant, I can't click on the team members' gitcoin profiles. 
- [x]  The 'Supported By' / Team Members sections should have tooltips on each profile so i can see who it is when i hover / before i click.

Minor

Other than that, looks really good.. Kudos team!

**Comment by owocki** [comment]
@captnseagraves @mbeacom @thelostone-mc i just prioritized this in the grants kanban board

**Comment by thelostone-mc** [comment]
@owocki 

> I can set ANYONE to be my grant owner. this seems kind of strange, i wonder if you could dox someone .. maybe ill create a grant by @VitalikButerin
  I should probably be sent an email when someone makes me an owner / team member for a grant. And I should have permissions to edit the grant.

So ideally the grant owner would have the ability to edit the grant !
An email makes sense. That should be ideally sent out to all contributors + new admin + team members 🤔 cc @PixelantDesign  @willsputra 


>  On a grant, I can't click on the team members' gitcoin profiles.
The 'Supported By' / Team Members sections should have tooltips on each profile so i can see who it is when i hover / before i click.

<img width="188" alt="screen shot 2018-12-13 at 4 29 03 pm" src="https://user-images.githubusercontent.com/5358146/49934682-10f90d00-fef5-11e8-945b-7c1b10187504.png">

@SaptakS is throwin in a PR to make the image clickable.
@owocki do you need a tooltip when the username is just below the photo ?  seems like an overkill

**Comment by captnseagraves** [comment]
>  I can set ANYONE to be my grant owner. this seems kind of strange, i wonder if you could dox someone .. maybe ill create a grant by @VitalikButerin

Should we limit new admin to previous team members who have been team members for at least a day? So we can email people when they have become team members and notify them?

**Comment by owocki** [comment]
an email that allows the funder to renounce being owner of the grant makes sense to me.

> Should we limit new admin to previous team members who have been team members for at least a day? 

makes sense to me. 

maybe this should be v1.1.... not sure how many ppl will abuse this upfront

**Comment by owocki** [comment]
any luck on the two showstoppers on this thread

**Comment by captnseagraves** [comment]
@owocki Havent started on them yet. First thing on the agenda tomorrow is getting recurring payments to actually work. I smoothed out most things in the miner, but now getting a revert from the contract. I suspect the nonce or timestamp. Then I will tackle the remaining showstoppers.
