### ISSUE TITLE
As a Contributor of Gitcoin, I'd like to know Which how/where my issue counts are allocated.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3173]
### User Story

As a Contributor of Gitcoin, I'd like to know Which how/where my issue counts are allocated.
https://github.com/gitcoinco/web/issues/3157

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

- [ ] Document what counts towards bounty project limit
- [ ] Design where we should show it on the profile adding explanation.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Nothing communicated/displayed. User must sift through Bounties section below Kudos

### Expected Behavior
Display at the top

### Definition of Done
This idea is ux/designed out in a flow.

**Comment by kuhnchris** [comment]
How about here:
![image](https://user-images.githubusercontent.com/761911/49964468-ddc97480-ff1a-11e8-86c5-a219f2ad810a.png)

And for the listing of the one that count we could add a new tab "Bounties in Work" here:
![image](https://user-images.githubusercontent.com/761911/49964523-005b8d80-ff1b-11e8-91ec-cb6910da60ef.png)
