### ISSUE TITLE
What does the 'Add Account' button on profile do?

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3175]
**Describe the bug**
What does this 'Add Account' button do? Tried clicking it, clicking add, clicking on the text field but nothing happens.

![addaccount](https://user-images.githubusercontent.com/19514207/49811343-0d06a700-fd9e-11e8-9691-5ab0ade43fa1.gif)

**To Reproduce**
Go to your profile and click on the 'Add Account' button

**Comment by octavioamu** [comment]
So this one was part of Kudos v1, Kudos was shown only if the owner address was added there. So if you change your address in metamask you will able to change you account address.
Then we changed the logic of kudos and they are also attached to your profile, so changing address will keep showing the kudos even is that not the kudos owner address.

**Comment by willsputra** [comment]
@octavioamu ah okay got it. didn't realise I need to (1) switch to my new address on MetaMask, (2) click Add, (3) new address is reflected under the profile picture.

at first glance I thought I could just click Add and paste the new address to the text field 😛

I'll see how we can make this clearer. not urgent though.

**Comment by octavioamu** [comment]
Yes this really doesn't need to be there anymore I think, we plan to have multiple address (that module there is prepared to that also) 
The idea of not letting people write their addresses is to avoid any error.
