### ISSUE TITLE
if you put a gitcoin link in a tip github url, gitcoin should be smart enough to 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3189]
this happened here 
https://gitcoin.co/_administrationdashboard/tip/883/change/

see https://gitcoincore.slack.com/archives/CD93M06BG/p1544625940001100 for root cause analysis

**Comment by octavioamu** [comment]
Maybe an easy solution could be to validate the url looking for a github url

**Comment by Anish-Agnihotri** [comment]
Seems similar to #2909 where validation needs to be introduced to the inputs?
