### ISSUE TITLE
Basic Pay Taking longer than 6 minutes to Load Recommended Kudos

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3203]
### BUG
URL I'm trying to pay is tagged html, css:
https://github.com/gitcoinco/web/issues/2841

This is what I see:
<img width="697" alt="screen shot 2018-12-13 at 9 01 03 am" src="https://user-images.githubusercontent.com/238235/49943468-f5224680-feb5-11e8-93aa-29e8f0f2e663.png">

Can we investigate? @octavioamu

**Comment by octavioamu** [comment]
Solved by #3205
