### ISSUE TITLE
Grants landing page links stale

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#3210]
**Describe the bug**
stale page:
- links
- "Gitcoin Grants are coming in November of 2018."

**To Reproduce**
https://gitcoin.co/grants/

**Expected behavior**
links to active / completed grants link to info page

**Comment by kuhnchris** [comment]
@PixelantDesign *cough*

**Comment by thelostone-mc** [comment]
@NukeManDan we haven't made it public yet cause we doing a slow rollout. 
what you see at the moment is a stub page which would be retired pretty soon
