### ISSUE TITLE
Rebuild migrations throughout the app

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#3215]
Currently, our migrations are mushrooming - we should start with a clean slate and drop all migrations down to 001_ for each app.

cc @thelostone-mc

**Comment by kuhnchris** [comment]
Yeah, I wondered. There are like about 100 migrations now if I'm not wrong. 
You guys want to do it yourself or want me to try to figure this out?

Thanks,
Chris

**Comment by thelostone-mc** [comment]
@kuhnchris Ah this I'd like us to take it in if it's alright cause we need to ensure this gets done right even if it's simple.
A lil paranoid about these kinda things. 😅 

Would love your help in reviewing it though 🙌

**Comment by kuhnchris** [comment]
sure no probs, hence my question.

**Comment by owocki** [comment]
does https://github.com/gitcoinco/web/pull/3309/ solve this?  what do i have to do on my local to become compliant?

**Comment by kuhnchris** [comment]
As that one is referenced in the PR/commit message and the migration dir looks extremly cleaned up...
![image](https://user-images.githubusercontent.com/761911/50495154-a3d29500-0a27-11e9-9044-97526801a341.png)

I assume: yes, #3309 should at least clean migrations up, not sure if it's entirely done (or if this should be a reoccouring issue/ticket every 1/2 year or so).

To be compliant I assume you gotta kick the postgresql database and re-migrate.
Alternatively you could try to ```app/manage.py migrate``` and see on which spectrum of the good-to-broke-my-operation-system scale your system makes a stop. :-)

Thou, I'm not sure. @mbeacom did you squashmigrations ?
https://docs.djangoproject.com/en/dev/topics/migrations/#migration-squashing

**Comment by mbeacom** [comment]
The migrations have been reset, yes.  This issue can be closed.

@kuhnchris I did not use that, however, it *can* be used.
I think it'd be ideal for us to keep a pulse on the number of migrations and raise squashing PRs every so often to keep the migrations ideally below `n` across all apps. 🤔

**Comment by kuhnchris** [comment]
No problem, sure, may I still ask tho: how did you manage the migration on live after the squash?
I had to throw away our local db to be "on par" with the migrations again, is there a way to migrate?
Especially if we intend to do the "radical" way later on continuesly (instead of the official squashing).

Thanks
