### ISSUE TITLE
in activity_report management command, add a `from_address` and `to_address` field

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#322]
# what

in activity_report management command, add a `from_address` and `to_address` field.  both should be ETH addresses

**Comment by thelostone-mc** [comment]
would these be two new commands or a single command ? or would it be updating an existing command to include these two fields ?

**Comment by owocki** [comment]
> would these be two new commands or a single command ? or would it be updating an existing command to include these two fields ?

very likely the latter; also: i dont think we store that data anywhere.. we'd have to either (1) start storing it during the tip creation/redemption flows, or (2) go out to `web3py` using the `txids` to get the to/from adderesses later.
