### ISSUE TITLE
Create a "kill transaction" command for the subminer

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3220]
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We need to a way kill a hanging transaction on the subminer wallet. Akin to the metamask command that allows you to cancel a pending transactoin.

**Comment by owocki** [comment]
should be fairly easy to send a noop transaction with the same nonce as the existing tx you want to kill
