### ISSUE TITLE
value-add services for labs

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3226]
we could/should sell training from the gitcoin labs brand
we could/should sell custom research reports from the gitcoin labs brand, a la what miaden labs is doing

first step would be to put a CTA on this page
https://gitcoin.co/labs

**Comment by owocki** [comment]
@austintgriffith something to discuss this week in the context of C2.0

**Comment by kuhnchris** [comment]
Trainings in term of what subject?
As in a learning platform (ala BitDegree or Chainshot?), or as in "how to use Gitcoin" (áka tutorial/mentorship) or even lower as in "how to setup your own gitcoin"?


-Chris

**Comment by owocki** [comment]
> Trainings in term of what subject?

we'll have to do customer development to know for sure, but im thinking that theres a market for basic 'what is ethereum and how do i use it' type of stuff... leading to more specialized stuff like 'counter factuals for fund and profit'

**Comment by kuhnchris** [comment]
So more like market economics and ethereum classes? Fair enough.
