### ISSUE TITLE
BUILD - As an admin of Gitcoin, if a funder rejects an applicant, I want to know the reason why.

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3231]
### User Story

As an admin of Gitcoin, if a funder rejects an applicant, I want to know the reason why.
### Why Is this Needed

We're always looking to improve the Gitcoin experience. We'd like to have data regarding why an applicant is rejected. The data will be useful for the rejected applicant too so they can improve.

### Current Behavior
Currently when an applicant is rejected, no reasons are given, and the funder is not prompted to tell Gitcoin why they rejected the applicant.

### Expected Behavior
**Reject Worker**

![reject worker](https://user-images.githubusercontent.com/19514207/50099357-decf0e80-0258-11e9-8d27-836a2f4a69d0.png)

When a funder clicks Reject Worker on the bounty issue detail page, a modal pops up with these options. You should only be able to select one option. If "Other" is selected, a free text is required:

The applicant did not meet the desired qualifications.
The applicant did not provide sufficient information on the action plan.
The bounty was available only under special circumstances (e.g. hackathon).
The bounty was reserved for another person.
The bounty was cancelled.
Other (free text box)

It should look something like this:
![work rejected](https://user-images.githubusercontent.com/19514207/50099484-340b2000-0259-11e9-8065-2ace32cc39b7.png)

We also need a way to track and see the data of what is inputted by funders. Please work with @frankchen07 

### Additional Information

- Ensure you use boostrap modal as opposed to jquery-ui
- Modal should be responsive

Design ticket: #2773 
Sketch file: https://drive.google.com/open?id=1HjWgE1kKgB2-0TjwFCSPecCejWAXTeK3

**Comment by willsputra** [comment]
@frankchen07 Could you advise on how we should store the responses? Thanks!

**Comment by PixelantDesign** [comment]
@willsputra is there an email that goes along with this so the contributor is notified?

**Comment by willsputra** [comment]
@PixelantDesign yeah it was on the design ticket here
https://github.com/gitcoinco/web/issues/2773#issuecomment-447317386
