### ISSUE TITLE
BUILD - As a potential worker, I would like to know the reason why I was rejected for a bounty, so I can improve myself

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3232]
### User Story

As a potential worker, I would like to know the reason why I was rejected for a bounty, so I can improve myself
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: I want to know why I was rejected

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
When a funder rejects a potential worker on a bounty, there is currently no information provided.

### Expected Behavior

[comment]: # (Describe what you expected to happen.)
When a funder rejects a potential worker on a bounty, a modal should pop up (#3231), and an email should be sent to the rejected worker describing the reason.

It should look something like this: 

![work rejected email](https://user-images.githubusercontent.com/19514207/50100202-d4157900-025a-11e9-8af6-ee1babbdce9f.jpg)

- [ ] The email should be sent to the specific rejected worker.
- [ ] The email should show the issue logo and title.
- [ ] The email should provide one of the reasons below:

- You did not meet the desired qualifications.
- You did not provide sufficient information on the action plan.
- The bounty was available only under special circumstances (e.g. hackathon).
- The bounty was reserved for another person.
- The bounty was cancelled.
- (If 'Other' is selected on the modal, the free text provided by the funder should be displayed)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
This build ticket is only for the **email** part. The modal itself is taken care of in #3231 .

Design ticket: #2773 
Sketch file: https://drive.google.com/open?id=14CpcEhilvDWlXG9lBuYSggaOe9zBNcdM

**Comment by kuhnchris** [comment]
If nobody wants, I can design that mail. Could you please export the Sketch file as HTML, PDF, PNG, PSD, or any other format? My trial for Sketch expired so I cannot open your file @willsputra  :-(

Thanks,
Chris

**Comment by willsputra** [comment]
@kuhnchris would this .png work? if you prefer other format, lemme know :)
 
![work rejected email](https://user-images.githubusercontent.com/19514207/50166533-3c7b5d80-0322-11e9-9dca-a1196a81c31a.png)

**Comment by kuhnchris** [comment]
Ah that works fine. The only thing(s) I'd need are art/resources, like the bell, the rest should be in the assets/v2/images already.

**Comment by willsputra** [comment]
@kuhnchris here's the bell
https://drive.google.com/open?id=1THSiPKO0ucMNaTAY43vgIENOPW4YuJWP

**Comment by kuhnchris** [comment]
Thanks @willsputra i'll get to it ASAP. Is just designing the mail itself OK or you want me to include the backend works for this aswell?

Thanks

**Comment by willsputra** [comment]
@kuhnchris awesome thanks!
regarding the backend, @octavioamu what do you think? since it's also kinda related to #3231
