### ISSUE TITLE
Cancelled issue on Gitcoin not updated status and GitHub issue

### ISSUE THREAD

**Issue by LiorRabin** [gitcoinco/web#3236]
**Describe the bug**
I've cancelled this bounty https://gitcoin.co/issue/ColuLocalNetwork/inventory-manager/29/1766

My transaction was confirmed as can be seen here: https://etherscan.io/tx/0x62e14fdc661e74ec7bc60a128ce1cfe3e11c472fcac183cee2cea5e90932c158. 

I also got the CLN back to my account, but for some reason the bounty itself still looks like it is on `WORK STARTED` status and also didn't see an update on the GitHub issue https://github.com/ColuLocalNetwork/inventory-manager/issues/29

**To Reproduce**
See description

**Expected behavior**
The bounty on gitcoin should be cancelled and the issue on GitHub updated with a suitable comment.

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser Chrome
- Browser Version Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by owocki** [comment]
i know im like 3 days late to the party but looks like its updated now

@frankchen07 i think adding the 'sync from blockchain' button would really help here
