### ISSUE TITLE
Session hijacking

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#3237]
Eventuall Hello there. ) For some reason I am logged in as this guy.

![image](https://user-images.githubusercontent.com/8781107/50149053-28f0d800-02cb-11e9-8114-64660baf35de.png)

What's going on? It is on https://gitcoin.co/about and then I can go to and edit his profile https://gitcoin.co/settings/email/c5188e7cd0fa086a7b724897d278a  - add +1 to the -1 hash digit. Since PHP it is a bad idea to pass session ID in URL.

**Comment by SaptakS** [comment]
@abitrolly thanks for the issue. Can you please help me understand it better? 

> For some reason I am logged in as this guy.

Are you seeing the website logged in to someone else's profile in your personal computer? How exactly did you log in to someone else's profile or was it already logged?

> add +1 to the -1 hash digit.

Can you please elaborate where you are doing this and what exactly is the outcome?

> Since PHP it is a bad idea to pass session ID in URL.

We don't use PHP, so I am not sure what you mean here.

**Comment by abitrolly** [comment]
> Are you seeing the website logged in to someone else's profile in your personal computer? How exactly did you log in to someone else's profile or was it already logged?

My computer. It was already logged. 

> Can you please elaborate where you are doing this and what exactly is the outcome?

Just follow the link https://gitcoin.co/settings/email/c5188e7cd0fa086a7b724897d279a to edit another user.

> We don't use PHP, so I am not sure what you mean here.

In PHP you can hijack another user session by knowing session id, and developers quite often was leakin it in URL. Looks like Gitcoin not only allows to hijack session, but its generation / check is logic is very weak. @owocki

**Comment by owocki** [comment]
> add +1 to the -1 hash digit.

i dont seem to be able to reproduce by doing this

> Just follow the link https://gitcoin.co/settings/email/c5188e7cd0fa086a7b724897d279a to edit another user.

Yes this link is a secret link thats only exposed to users who have access. IF you share it, then people will be able to access your private info.

We do this so that people don't have to login, when they click an email, to edit their email settings.

**Comment by owocki** [comment]
> My computer. It was already logged.

This is what i'm most baffled about.. its like there was a session ID collision or something.
