### ISSUE TITLE
CodeCov dangerously low (<=30%)

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#3238]
**Describe the bug**
CodeCov coverage report below 30%

**To Reproduce**
Commit

**Expected behavior**
Have good CodeCov (>=50%)

**Comment by mbeacom** [comment]
We have numerous code coverage bug bounty issues at the moment.  Please follow up on one of those or feel free to fulfill one! 😄

**Comment by kuhnchris** [comment]
Ah, pardon, I was under the impression that the latest ones were already "improved", and hence closed.
