### ISSUE TITLE
Refactor Grants amount_received

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3242]
Refactor Grant amount received to address this comment: https://gitcoincore.slack.com/archives/CBDTKB59A/p1544642804120400

**Comment by kuhnchris** [comment]
Just as a note here, in general for all links to gitcoincore: 
You artifactually (or on purpose) limit the people who can contribute on those bounties to the core team only, as nobody else who's not registered there cannot open this link. Not sure if you are aware of that.

Thanks

**Comment by captnseagraves** [comment]
To address this issue I plan to:
- create `monthly_amount_subscribed` in the Grant model
    - this will represent the sum of all `amount_per_period` values in subscriptions
- do conversion math for periods other than 30 days
- point progress bars `current` value to `monthly_amount_subscribed`
- display `total amount received` in grant details
- when a subscription is canceled or when `num_tx_processed` = `num_tx_approved` the `amount_per_period` will be removed from `monthly_amount_subscribed`
