### ISSUE TITLE
Add ability to change `amount_goal`

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3246]
As a user I want to be able to change the amount I have set for my monthly `amount_goal` so that I can adjust my grant based on the needs of my project. 

This funtionality should be added to the `grant/detail - edit` functionality. We will need to add an input `grant/detail.html - admin/edit`, hide/show functionality to `grants/detail.js`, and make sure the data is being passed to the correct function in the `grant_detail` view to be saved.

**Comment by thelostone-mc** [comment]
@willsputra mind helping figuring out how to add this neatly into the UI ? If you design it -> we can code it up. I know if I add it in randomly -> it will ruin the look and feel :P

**Comment by willsputra** [comment]
We can probably add another field when you click on Edit Grant. Just make sure the title is consistent with what we have on the create grant form ('Monthly sought amount in DAI')

![monthlyamount](https://user-images.githubusercontent.com/19514207/50523361-5545f900-0b02-11e9-8074-d118d7973581.jpg)

**Comment by thelostone-mc** [comment]
Coooolio! will code it up
