### ISSUE TITLE
Kudos - Carousel broken on https://gitcoin.co/kudos/

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#3250]
**Describe the bug**
Kudos images are not being loaded in carousel

**To Reproduce**
go to https://gitcoin.co/kudos/, wait a couple of seconds until the carousel auto-forwards, see broken images

**Expected behavior**
see kudos images

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/50204488-58542300-0365-11e9-9ee6-43df5aa32cd8.png)

**Comment by owocki** [comment]
try now?

**Comment by kuhnchris** [comment]
Far better, if you use it "normally" it doesn't break now. only if you really fast click on the right button for a couple of times you see it jumping as it's loading the next images.
So, for me it's OK! thanks. :-)
