### ISSUE TITLE
Grants ENS support

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3256]
Users are already wanting to use ENS addresses. We need to support this in Grants.

**Comment by kuhnchris** [comment]
Any ideas? Want to create a custom ENS subdomain? kind of like <normalized-grant-name>.grants.gitcoin.ens ?

**Comment by captnseagraves** [comment]
@kuhnchris Thanks for checking in on this. Sorry I haven't been very descriptive in the issues I've posted recently. It's been more of a way to save ideas as we move to an alpha+ launch than anything else. 

For this issue though, someone wants to use an ENS address that they already have (e.g. kevinseagraves.ens) and our system does not support this functionality. At least, that's my understanding, I dont think web3 auto-resolves ens addresses, yet haha.  Honestly, I haven't built anything that supports ens addresses yet so I'm not sure the steps are needed to implement. I assume the bounties product supports ens so it is likely we can lift some code from there to meet the need.
