### ISSUE TITLE
Create opt-in experience for changing Grant owner

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3257]
Right now, I can change the Grant owner to be any existing Gitcoin/GitHub user. There should be an opt-in process for the new potential Owner.

**Comment by captnseagraves** [comment]
@thelostone-mc I know you have a PR out for this, and I think the current status is that @mbeacom is looking to wire up the data and emails. 

Can you link to the PR or other open issue here and confirm status? 

Thanks!

**Comment by thelostone-mc** [comment]
emails are already wired up!

The PR is good to go! The only thing I need help is [here](https://github.com/gitcoinco/web/pull/3252/files#diff-9c83a1892e5b433bc22483a941276b94R135) which is used by the html page to show an alert to user saying their request for change has been sent

**Comment by captnseagraves** [comment]
@thelostone-mc Good to close? I believe you PR got merged yeah?
