### ISSUE TITLE
Grants - Fund page refreshes instead of redirecting to detaills

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3259]
Sometimes when I fund a grant the page reloads instead of redirects to details. Not sure what the cause is, but need to iron out the bug. 
![screen shot 2018-12-19 at 12 10 46 pm](https://user-images.githubusercontent.com/22862292/50243572-ba734f00-038a-11e9-94a9-26cff2e4c994.png)

**Comment by captnseagraves** [comment]
@thelostone-mc Yeah, it doesnt seem to be consistent. Not sure what causes it. I'll keep an eye out and will use this issue to provide any insight.

**Comment by thelostone-mc** [comment]
If it happens again ! we'll reopen this and dig into it. Closing it out for now ^_^
