### ISSUE TITLE
Increase funding tx failed with out of gas

### ISSUE THREAD

**Issue by troggy** [gitcoinco/web#3264]
**Describe the bug**
I've tried to increase funding for existing bounty and tx failed with "out gas" error. Seems like that gasLimit wasn't accurately estimated.
Tx: https://etherscan.io/tx/0xab34b4520b658876d62155a3f63208489db616899b2a5279e4cd060a78a0545c
Bounty: https://gitcoin.co/issue/leapdao/solEVM-enforcer/21/1961

**Comment by troggy** [comment]
I've increased gasLimit manually and it went through just fine: https://etherscan.io/tx/0xcddf0c4779a8eb0ced3a0861eef513f77e3f2f50b8ffaeed215b2df452d9e7da

Estimated gas limit: ~56k
Real gas usage: ~65k

**Comment by owocki** [comment]
e77f670fa2cb2e22ad36428fc47e58ee5850ab0b
