### ISSUE TITLE
Form Persistence through reloads and no reloading on MetaMask updates

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#3272]
### User Story

As a user filling out a form I often have the page refresh because of metamask or other interactions and I lose all of the content I had typed up. 

### Why Is this Needed

It makes me want to rage quit when I lose content

### Expected Behavior

The page reloads and my form content is still there.

**Comment by kuhnchris** [comment]
well - wouldn't that basically mean that we need to change the ENTIRE system to ajax and/or either load the form data back in django/the view or reload a separate included frame for metamask?
How do other tools handle metamask changes like that? (radar, 3box, ...)

**Comment by PixelantDesign** [comment]
Yes, that would be great if we could temporarily save on the page so the user doesn't lose information already entered.

**Comment by austintgriffith** [comment]
I'm not sure which one I was using at the time but all Gitcoin forms do this. I would start with the most popular ones and work backwards. There have been multiple times where I'm creating a bounty, sending a kudos, or sending a tip where I got it all filled out and then MetaMask reloaded the page and I lost everything. Normally when that happens using a product in the wild I rage quit. I honestly think little tweaks to the UX like this will increase our usage.
