### ISSUE TITLE
Grants - Add Contribution History to `grants/details - admin` view

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3275]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Grant Admin/team-member, I want to see my grant's contribution history on the `grants/details - admin` view so that I have an easy way to see who has contributed, how much, and when. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: This makes it easier to see the contribution history of a grant. Right now a Grant Admin has to navigate to the `Your Grants` tab in the profile dropdown. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
This issue will be considered done when a grant's contribution history is visible in the `grants/detail - admin` view

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
- before beginning work, we will need a design mock-up from @willsputra

**Comment by thelostone-mc** [comment]
Can't we reuse what I had hardcoded way back and update that design or did we weed out that code ?

**Comment by owocki** [comment]
yesterday, i added a bunch of fields to the admin so you can eyeball the contribution status in the admin.

checkout the admin grants index, and then the list of subscriptions / grants for each at the bottom of each grant in detail view

**Comment by owocki** [comment]
point us to what you hardcoded aditya?

**Comment by captnseagraves** [comment]
@thelostone-mc yes, we are using that code in grants/profile.html. @owocki we can reuse this code in grants/detail.html. Does that describe where it is well enough?

**Comment by owocki** [comment]
yes that makes sense for me to re-use.

one question.. why are we only showing the contribution history to grant admins (btw i dislike the term admin, since admin == django admin already.. can we call them grant owners?)...  on https://github.com/gitcoinco/web/issues/3301 i was hoping that we could show it for all users

**Comment by captnseagraves** [comment]
There isnt a good reason. We can show publicly. 

We can call them Grant Owners. The only reason admin was used was because they could control and edit the grant, much like a django admin with a website. But we dont have to keep that naming convention.

**Comment by captnseagraves** [comment]
@thelostone-mc This issue is addressed in your recent PR yeah?

**Comment by thelostone-mc** [comment]
Yup :P ( I'm just replying yup to a lot of your questions today 😂 )
