### ISSUE TITLE
aesthetic bug -- blue text on blue 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3277]
http://bits.owocki.com/a614fd70a55b/Screen%20Shot%202018-12-21%20at%2012.59.21%20PM.png
http://bits.owocki.com/55f5b563e072/Screen%20Shot%202018-12-21%20at%2012.59.42%20PM.png

https://gitcoin.co/contributor
IMHO this text on /contributor looks funny

is this by design?  if not, it should be a quick fix

**Comment by owocki** [comment]
@PixelantDesign would know if its by design or not

**Comment by PixelantDesign** [comment]
Yep should be white. Blue on blue is hard to read.
