### ISSUE TITLE
"Stop Work" showing even if "Start Work" request returns an error

### ISSUE THREAD

**Issue by JeremiGendron** [gitcoinco/web#3281]
**Describe the bug**
Annoying visual bug where an error breaks normal behaviour.

**To Reproduce**
1. Go on any issue for which you can apply
2. Click start work
3. Fill in the details, press submit
4. Get notified of an error for max number of jobs
5. See that the "Stop Work" button is clickable, as if the application was auto-accepted

**Expected behavior**
Ideally, for "Start Work" to be greyed out if already maxed out.
Otherwise, probably just fix the bug (res.error, canStopWork = false)

**Screenshots**
Click start work on an issue with a bounty
![image](https://user-images.githubusercontent.com/23587429/50385470-367bd880-06a4-11e9-9a7b-df1d95f21c2b.png)

Fill in the paperwork, press submit
![image](https://user-images.githubusercontent.com/23587429/50385478-51e6e380-06a4-11e9-94db-a171ec50dfa7.png)

See an error (max work of 3 issues), but the "Stop Work" button is clickable
![image](https://user-images.githubusercontent.com/23587429/50385489-6dea8500-06a4-11e9-9a16-859fd6a811bb.png)

Clicking on the button gives a popup
![image](https://user-images.githubusercontent.com/23587429/50385503-a8542200-06a4-11e9-96b4-ce9b4983bc79.png)

**Desktop (please complete the following information):**

- OS: Lubuntu
- Browser chromium
- Browser Version 71.0.3578.80

**Comment by PixelantDesign** [comment]
Thanks for reporting this bug @JeremiGendron!

**Comment by JeremiGendron** [comment]
I might be able to fix this, I have the repo clone and ready to work on. I'm by no means an experienced python developer though. Might give it a shot, since this is in the backlog.
