### ISSUE TITLE
re-think the server architectecture

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#329]
# problem

right now, were just running gitcoin on one server.. we may want to break it out into multiple servers in order to manage the scale a little more 

#  my ideas

* we may want to specout an architecture plan that breaks out the db server and the app / api servers
* and also thinks a little more granularly about the sizing of servers
* monitoring infrastructure

# @mbeacom ideas

* We can do that. I'm up to move the DB to RDS. From there, I'd say we consider two ec2 instances running under ECS and just use docker containers.  That'll also allows us to do blue-green deployments with little to no effort.

**Comment by mbeacom** [comment]
## Initial thoughts

- Move PSQL to RDS
  - Schedule automatic DB backups in RDS
- Add IAM role for ecs instances to remove need for AWS key/secret in code or agent configs
- Add cloudwatch log streams to be used by the new instances
- Spin up an ECS cluster running at least 1-2 ec2 instances
  - Create a standard AMI with packer.io (hashicorp) with a base setup
  - Handle additional provisioning via user-data and launch scripts
  - Ensure the EC2 instances are provisioned in an autoscaling group
- Add additional metric reporting for ram/disk usages/etc via something like `go-aws-mon`
- Add alarms for ECS instance launch group and scale cluster accordingly
- Add a bastion/jump box for SSH gating
- Deploy initial gitcoin services to ECS cluster
  - Add task definition for gitcoin web app
  - Add Service for gitcoin web app under an ALB with automatic scale-in/out
- Update Route53 entries to target ALB vs ELB
- Implement mechanism in CI to automatically deploy new task definition

## Additional considerations

- Move to environment variable based settings for easy docker deployment
- Move static assets to S3 and use `Manifest` backend mixin for automatic hashing of assets (this should eliminate the need to invalidate CF on deployment).
- AWS KMS for secrets?

**Comment by kuhnchris** [comment]
that already happened, no? @danlipert
