### ISSUE TITLE
bug - new tip email is misaligned

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3299]
this is on google apps / gmail on chrome

![screencapture-mail-google-mail-u-0-2018-12-24-16_45_41](https://user-images.githubusercontent.com/513929/50407789-6c4fb880-079b-11e9-9d4c-6849e6361f11.png)

**Comment by owocki** [comment]
this is from prod; fyi @kuhnchris idk if you saw this when testing at all

**Comment by owocki** [comment]
okie dokie... let me know.. fwiw i think its something gmail related bc it renders fine in my browser just not gmail

**Comment by kuhnchris** [comment]
I think it may be releated with some width setting, I had a similar issue with Spark (mac OS mail client).
I'll test around to see if I can get something to work
