### ISSUE TITLE
as a user of grants, i want to see past contributors to my grant, so i can know who has contributored to my grant in the past

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3301]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user of grants, i want to see past contributors to my grant, so i can know who has contributored to my grant in the past

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
because if someone was a past contributor, currently they get no credit

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no past contributors module 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
add a past contributor module to the grants detail page .  design should match the 'supported by' module, and ideally be DRY'd so the code isnt copy pasted

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
ref https://gitcoincore.slack.com/archives/CBDTKB59A/p1545832838003000

**Comment by owocki** [comment]
dupe with https://github.com/gitcoinco/web/issues/3286 ?

**Comment by owocki** [comment]
also related to https://github.com/gitcoinco/web/issues/3275

**Comment by captnseagraves** [comment]
@thelostone-mc This issue is addressed in your recent PR as well yeah?

**Comment by thelostone-mc** [comment]
Yup :P
