### ISSUE TITLE
grant email avatar images still broken

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3305]
http://bits.owocki.com/4ac54af8512d/Screen%20Shot%202018-12-26%20at%208.53.34%20AM.png

**Comment by kuhnchris** [comment]
For easier debugging: is it just the "/..." path for the img? as in: is the gitcoin.co part missing?
if yes you may need to use the avatar_url templatetag.
https://github.com/gitcoinco/web/blob/1a42ae0553753f047243423f5860f9cef58f1017/app/retail/templates/emails/grants/new_supporter.html#L58

**Comment by thelostone-mc** [comment]
It works in a few situations like [here](https://gitcoin.co/_administration/email/new_supporter)

@SaptakS  / @mbeacom any idea on why this happens ?

**Comment by kuhnchris** [comment]
@thelostone-mc could you check on some of those where it's broken in /admin what avatar_url is pointing at?

**Comment by thelostone-mc** [comment]
It just points at `https://gitcoin.co/` 😓

**Comment by kuhnchris** [comment]
that... seems wrong, at best. and how does it look for someone who's "working"? is it something special, just a URL or the same? (e.a. compare broken to un-broken)

**Comment by owocki** [comment]
seems fixed at https://gitcoin.co/_administration/email/new_supporter now

**Comment by thelostone-mc** [comment]
This is very weird :P
Closing this out and it's magically resolved 🤷‍♂️ (did @SaptakS / @captnseagraves unless throw in a fix I'm not aware of :P )

**Comment by kuhnchris** [comment]
![image](http://www.reactiongifs.com/r/mgc.gif)
