### ISSUE TITLE
Gitcoin Labs tools page with 404 assets

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#3312]
The Gitcoin Labs landing currently has broken assets

Live:
<img width="261" alt="screenshot 2018-12-26 14 41 27" src="https://user-images.githubusercontent.com/7315957/50455523-7fd65d00-091c-11e9-9b2f-df423dc70eee.png">

Local:

<img width="265" alt="screenshot 2018-12-26 14 43 03" src="https://user-images.githubusercontent.com/7315957/50455530-967cb400-091c-11e9-8851-c382205b6a5c.png">

**Comment by thelostone-mc** [comment]
Has been taken care ^_^
