### ISSUE TITLE
as a grant funder, i want to see my contribution immediately, so i dont wonder where it is

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3314]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grant funder, i want to see my contribution immediately, so i dont wonder where it is

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
people subscribe to grants, then they wonder where their grant contribution is immediately after

example: https://gitcoincore.slack.com/archives/CBDTKB59A/p1545855358014400

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)

no expectation management

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

either manage users expectations that their contribution will take a couple minutes to show up
OR 
make it show up immediately

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
convo on slack 
https://gitcoincore.slack.com/archives/CBDTKB59A/p1545855358014400

**Comment by owocki** [comment]
per convo with @captnseagraves on slack.. thers two elements to this

1. contribution should show up immediately on grant profile
2. tx being debitted immediately from ethernets

**Comment by owocki** [comment]
maybe we could run the subminer on an HTTP request, AFTER the response is sent to the user, but before the gunicorn thread closes

the only thing is we’d have to harden that endpoint against abuse

**Comment by captnseagraves** [comment]
Part of this Issue was addressed with PR https://github.com/gitcoinco/web/pull/3313. A users subscription is now displayed immediately in the grant progress bar. The second part of this issue will be to manage user's expectations that their contributions will take 5-10 minutes to be reflected in the "Total Funding Received" ticker. Currently, the subminer runs every 5 min. We may want to adjust this.

**Comment by frankchen07** [comment]
closed via https://github.com/gitcoinco/web/issues/4169
