### ISSUE TITLE
as a user, i want  chain abstraction layer on gitcoin, so i can pay in bitcoin/EOS, etc

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3317]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want  chain abstraction layer on gitcoin, so i can pay in bitcoin/EOS, etc

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
ethereum is great but its not the only game in town

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
only ETH
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
bitcoin/EOS too
### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above
### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
we could perhaps use https://arkane.network/ or the chain abstraction layer that joe chow is working on ( btcrelay )

**Comment by kuhnchris** [comment]
Well, not entirely sure about the BTC environment (Bitcoin, Bitcoin Cash, AltCoins, etc.) but as far as I remember there are no real "VMs" with contracts as in our little eth world. hence if we would use intermediate addresses to store the <insert coin name here> then we would be the intermediate trader and would need to charge "double tx fees" to start with. (once for receiving, once for sending, either back to the creator or to the receiver/hunter)

I kind of crafted/blueprinted something like that years ago for automatic alt-coin trading and miners, we might be able to look into that, or, as mentioned, use arkane (requires investigation).
OR, just to be really "edgy", implement shapeshift.io directly in the submit form so it automatically *->ETH->Contract->Target Receiver (intermediate generated address)->ShapeShift->BTC Wallet.

Would still cause the same issues regarding double-fees.

**Comment by owocki** [comment]
> OR, just to be really "edgy", implement shapeshift.io directly in the submit form

oooh this is an idea i hadn't thought of!
