### ISSUE TITLE
as a content marketer, i want to create quizzes that entertainingly engage our audience, to reduce CPA & learn about our audience

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3322]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a content marketer, i want to create quizzes that entertainingly engage our audience, to reduce CPA

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
* easy way to acquire users
* easy way to learn about users preferences (what programming languages they love, what are their preferences on OSS)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no quiz app

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
quiz app that can be used for user acquisition

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
needs to be specced

some sample quizzes we could do:
* which OSS legend are you most closely aligned with? (possible answers: richard stallman, eric raymand, bill gates)
* what type of programmer are you?
* how well were you paying attention in operating systems class?
* the network architecture refresher quiz

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
worth reading
* https://medium.com/@justinbrooke/ultimate-guide-to-using-quizzes-to-build-your-list-e4598e1de8f2
* https://blog.aweber.com/digital-marketing-2/how-to-create-use-and-promote-quizzes-to-grow-your-email-list.htm

some software we can leverage
* https://github.com/sswapnil2/django-quiz-app
* [many others](https://www.google.com/search?q=django+quiz+app+github&oq=django+quiz&aqs=chrome.3.69i57j0l5.3542j0j7&sourceid=chrome&ie=UTF-8)

**Comment by PixelantDesign** [comment]
I like the spirit of getting to know our users and entertaining them...also think the following could be useful for marketing campaigns.

A quiz to help someone determine whether they'd be best as a contributor vs. OSS maintainer that eventually guides them to respective products?

A quiz to help us learn about funders pain points and provide combination of solutions that might help their business need (without being too salesy)?

**Comment by kuhnchris** [comment]
Maybe combine it as a little task. "Hey, I saw you did X on our platform - want to earn a special kudos? Help us improve gitcoin and answer a couple of questions and at the end you'll receive a kudos. Let us know if you got any questions, won't take more than 10 min, promise!"
