### ISSUE TITLE
Gitcoin.co Homepage 2019 Revamp

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3327]
Capturing Ideas Here
![new home page010419](https://user-images.githubusercontent.com/238235/50675138-1c9e9780-0fba-11e9-8c9f-f568e188b4f2.jpg)

![nav changes](https://user-images.githubusercontent.com/238235/50486043-f11e1a80-09c5-11e9-9fe3-01b363542fa9.jpg)

**Comment by owocki** [comment]
some video collateral we c ould leverage

https://youtu.be/i2JKN_6iuiw
https://youtu.be/Y5Ef-fse23Y
https://youtu.be/b6LSf-zQnlI
https://youtu.be/oe7oD8ThKx8

**Comment by frankchen07** [comment]
some thoughts:

1. user -> contribute -> maintain, should it be user -> contributor -> maintainer, if we want to keep a noun the whole way through?
2. under the “company” dropdown, “career” should be “careers”
3. can we center the our products / our mission to line up with the top header?
4. Do we want any new copy for the “do more work faster” portion?

also added some copy to the Google doc.

**Comment by thelostone-mc** [comment]
feel a lil crowded. White space can be a good thing.
Would it make sense to push the cards a lil down ?

<img width="746" alt="screen shot 2019-01-01 at 10 23 09 pm" src="https://user-images.githubusercontent.com/5358146/50574710-e58e8180-0e13-11e9-8eb4-c6f4bdb915f7.png">

**Comment by owocki** [comment]
i agree with @thelostone-mc -- it does seem a little bit crowded.

also i realize now that the user > contribute > maintain funnel doesnt make a lot of sense the way it is now.  we need a way to show the funnel 'before gitcoin' and 'after gitcoin'.  otherwise its just a funnel without context

would it make sense to have a testimonial module under 'what people are saying'? maybe even the video? https://www.youtube.com/watch?v=hpqHJCiqXzA

**Comment by PixelantDesign** [comment]
Updated design at the top @owocki @vs77bb @frankchen07 

I addressed most of the feedback, but think it's too much to show all of the products on the home page. there are number of sections where a user can click to go to the product section that has been built.

**Comment by PixelantDesign** [comment]
Great questions/concerns.....

One thing to note is that this isn't meant to replace the mission page, but give a high level overview.

Crowding - I gave it some more space....maybe removing a tree or two might make it look less busy. 

Big green funnel - I was thinking that as the user scrolls, we could do a parallax animation where the funnel scrolls down but displays the 10x info above the blue section that introduces the products.

Added the video modules and comments from @frankchen07 and @vs77bb. I'll also share with Marc (marketing) to get his thoughts.

![new home page 010319](https://user-images.githubusercontent.com/238235/50675347-87040780-0fbb-11e9-85e2-67d410f62094.jpg)

**Comment by owocki** [comment]
this landing page looks great!

**Comment by PixelantDesign** [comment]
@vs77bb please add info you'd like on Gitcoin Requests on this thread. 
@thelostone-mc @SaptakS looking to you both on a recommendation on bounty vs building in house given this has some navigation changes. Please let me know by end of day Thursday 1/17 Thanks!

**Comment by SaptakS** [comment]
I would be up for bountying since this has mostly frontend changes and doesn't affect other pages.
