### ISSUE TITLE
as a grant owner, i'd like to be given a set of best practices that i can use to promote my grant and make it successful

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3329]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grant owner, i'd like to be given a set of best practices that i can use to promote my grant

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
success / failure of individual grants depends heavily upon whether the grant owner is involved in actively promoting it

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no best practices

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
document that outlines some best practices + case studies which we can deliver to each grant funder when they sign up.

we should also probalby send it to them once very few months automatically for a tune up.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
@ceresstation @vs77bb @austintgriffith can list some of the best practices that should go in this guide

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
should this be a google doc or CMS article?

**Comment by owocki** [comment]
related to https://github.com/gitcoinco/web/issues/3331

**Comment by owocki** [comment]
Thanks Scott. Some comments below:

updates -- is it worth calling out the 'update' functionality which can be used to send updates to each of your grant funders?

milestones -- what is this feature useful for?  i think that setting specific milestones might be a good way to publicly committing to things that you're going to do with the capital.

i'd love to see some examples of ppl doing it well.  what grants are especially well put together?  some people like to just copy other peoples work instead of reading docs.

i also propose a 'every month' section.  we could even say that most of the 'after grant creation' stuff is continual upkeep that funders will have to do over time.

**Comment by owocki** [comment]
@austintgriffith any other best practices you can think of?

@vs77bb @PixelantDesign too!

**Comment by PixelantDesign** [comment]
Great thoughts yall!

I had this convo with Meeka (Mekyle), pointed him to Austin’s example and he found it helpful.

I agree with all of @ceresstation comments above. 

Have a really good plan. We can link to 1 example template to help get juices flowing.

To add to that - emphasis on why the idea is important.

Tooltips on each section to help understand what it does is a good idea too. More importantly explaining why funding contributors would want to see this.

**Comment by owocki** [comment]
next step, i think we need to put this on the gitcoin CMS (gitcoin.co/cms if youre an admin) or into a google doc we can give to new grant creators
