### ISSUE TITLE
cleanup prod db size

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3340]
prod db is up to about 800 MB. well need a way to prune the DB size.. starting with these tables

<img width="359" alt="screen shot 2018-12-28 at 12 39 06 pm" src="https://user-images.githubusercontent.com/513929/50526189-a2dc4a80-0a9d-11e9-9c89-779d0b2f3a0d.png">

not listed is the emailevent table, which clocked in at 1 GB..

**Comment by mbeacom** [comment]
The first four could probably use some rework - should we evaluate something more time series specific for these kinds of datasets?  We could probably truncate some of these tables 🤔

**Comment by owocki** [comment]
not listed is the emailevent table, which clocked in at 1 GB..

agree with all of the above..  we'll have to revisit at some point in the future.   4382808351a45d098fb81747db8f3fd48ecf79d7 is a stopgap that makes restoring to our locals less painful in the meantime.
