### ISSUE TITLE
AWS Cost Management

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3342]
Our AWS Bill is currently $1.3k / mo.  We should schedule some time to analyze where the spend is and try to get it down closer to $500.

**Comment by mbeacom** [comment]
This is definitely something I've wanted to focus on...  Now that I have billing access, running billing and cost analysis reports is possible and I can start to hammer on this.

To move this forward, would you mind adding the secrets for the other instances hosted on our account that aren't gitcoin related to the company shared 1password or some other medium, so I can start migrating them to k8s/serverless/static/whatever makes sense?

**Comment by owocki** [comment]
i was just listing this ticket so we can track it; i'm not certain its a Q1 2019 priority.  lets get aligned on that before we start thinking about operationalizing it!

**Comment by kuhnchris** [comment]
well, there has been a previous ticket that the s3 costs were exploding, so it would be a rather short term cost saving solution?

**Comment by JeremiGendron** [comment]
Is there some reference with the basic outline of the current infrastructure? Would like to think about this.

**Comment by kuhnchris** [comment]
I assume the following ones are connected:
#2877 
#329 
So some really old ones there...

**Comment by owocki** [comment]
interesting thread on how to save $$$ on your AWS bill => https://threadreaderapp.com/thread/1091041507342086144.html
