### ISSUE TITLE
login ToU popup tense 

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#3344]
**Describe the bug**
Just wording: changes *are in effect* now for the new ToU

**To Reproduce**
fresh login

**Expected behavior**
correct tense

**Screenshots**
![screenshot at 2018-12-28 19-54-16](https://user-images.githubusercontent.com/35669742/50532751-25372f80-0adb-11e9-9d56-89e9605b2cfd.png)

**Comment by thelostone-mc** [comment]
Thanks for the report @NukeManDan ! Would you be up for submitting a PR ?

**Comment by NukeManDan** [comment]
searching through the repo: 
`~/web/app/dashboard/templates/legal/privacy.html` has `May 23rd` time stamp. 
`app/locale/de/LC_MESSAGES/django.po` and `app/locale/es/LC_MESSAGES/django.po` as the 24th

I don't know anything but english :sweat_smile:  - thus a native speaker will need to update:
`app/locale/<region>/LC_MESSAGES/djangojs.po`

**Comment by thelostone-mc** [comment]
Thanks @NukeManDan ! Left a comment on PR ^_^
