### ISSUE TITLE
Bounty API 500 response

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#3348]
**Describe the bug**
Week or two ago there was no problem with accessing single bounty through endpoint `https://gitcoin.co/api/v0.1/bounties/<bounty_pk>/`, today I noticed that api returns http code 500 for every request.

`{"active": "error", "code": 500, "title": "Error 500"}`

**To Reproduce**
curl -v https://gitcoin.co/api/v0.1/bounties/9/

**Expected behavior**
response 200 with bounty json

**Comment by JeremiGendron** [comment]
I will check the logs

**Comment by kuhnchris** [comment]
Guess that's an issue with the router string, I'll check for you in a bit.
