### ISSUE TITLE
Add Discourse to Gitcoin Toolbox, fix xdai.io typo, move Grants.

### ISSUE THREAD

**Issue by Anish-Agnihotri** [gitcoinco/web#3355]
**Describe the bug**
The Gitcoin Toolbox doesn't have the community Discourse under the `Community` header. There is also a typo under the `Tools in Alpha` header where the xdai.io is incorrectly spelled.

**To Reproduce**
Visit https://gitcoin.co/tools. 

**Expected behavior**
Community discourse should be added, and typo corrected.

**Screenshots**
Lack of community discourse: 
![nodiscourse](https://user-images.githubusercontent.com/4398624/50550305-1caa3a80-0c3c-11e9-9994-eb9044b9e3af.JPG)

Typo:
![xdaio](https://user-images.githubusercontent.com/4398624/50550306-203dc180-0c3c-11e9-9d2c-ae43b889d4e1.JPG)

I'll be cleaning toolbox up in a PR if cool with team.

**Comment by Anish-Agnihotri** [comment]
Might be a good idea to move Grants from `Tools Coming Soon` to `Tools in Alpha` or `Basics`.

**Comment by kuhnchris** [comment]
This has to be changed on the database, read @owocki @mbeacom or @PixelantDesign .
The objects in question is "Tool", the "actors", as the template calls them, are hardcoded.
See app/dashboard/views.py method toolbox:
![image](https://user-images.githubusercontent.com/761911/50566284-17cab100-0d38-11e9-8599-4badad8c5871.png)
