### ISSUE TITLE
As a founder, I want to execute Marc Beharrys' SEO roadmap, so I can lower CAC

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3372]

**Comment by owocki** [comment]
TODO: get the roadmap from marc

**Comment by owocki** [comment]
From Marc
```
Marc Beharry [2:17 PM]
SEO Guide for Articles (On-Page SEO) https://docs.google.com/presentation/d/1J3rg6dAd8PFdjQPbY0TY8zBRkjTR9ks6ODudIUFjaug/edit#slide=id.p

I attached this Google Analytics dashboard you may be interested in to get a quick handle on the major metrics in one screen.  You can change the timeframe if you view it with this link: https://analytics.google.com/analytics/web/template?uid=FPOvnis7Q9WAHY8VTMP49w

CodeFund SEO recos have begun, there are a few easy items we can address quickly like broken links and redirects: https://docs.google.com/spreadsheets/d/1r7D0MP81ZVV_ifjKnh4gg4JxnigMXo-rCgSo0tKqQ6o/edit#gid=0

```

**Comment by owocki** [comment]
TODO: make child tickets for this

**Comment by frankchen07** [comment]
seo tickets & roadmap 
    https://github.com/gitcoinco/web/issues/3511 (green squad backlog)
    https://github.com/gitcoinco/web/issues/3512 (green squad backlog)
    https://github.com/gitcoinco/web/issues/3513 (green squad backlog)
    https://github.com/gitcoinco/web/issues/3514 (green squad backlog)
    https://github.com/gitcoinco/web/issues/2898 (bountied)
    https://github.com/gitcoinco/web/issues/2899 (bountied)

additional meeting with Marc to be set in the week of 1/14 to hash out details and prioritize

**Comment by PixelantDesign** [comment]
great!
