### ISSUE TITLE
as a user, i want a 1099 from gitcoin, if i am in the US, so i can pay my taxes

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3381]
as a user, i want a 1099 from gitcoin, if i am in the US, so i can pay my taxes

**Comment by kuhnchris** [comment]
Soooooooo, which one?
https://en.wikipedia.org/wiki/Form_1099

**Comment by MannyCho** [comment]
@kuhnchris I can help you with this issue. Contractors in the US are required to report income to the IRS and pay taxes on the reported income. Companies that engage contractors are required to complete and provide a [1099-Misc](https://www.irs.gov/forms-pubs/about-form-1099-misc) to each contractor it engaged during the year. Companies are also required to submit a copy of the 1099-Misc forms to the IRS.

Given the anonymity of contractors and organizations, completing a 1099-Misc becomes difficult. We at [First State Fintech Lab](https://www.firststatefintech.org/) are assisting companies such as yours to address this kind of issue. We are helping Aragon address this issue through its grants program that operates similar to Gitcoin. Here's the [link](https://github.com/aragon/nest/issues/48) that explains in detail.

Please let me know if you'd like to chat.

**Comment by owocki** [comment]
for this; i've generated a list of 1099s for finance to send out for 2019..

**Comment by kuhnchris** [comment]
So is this task solved or did you create the 1099s by hand and want an automated solution?
In theory we could pre-fill a form with the required data, if available, and store those in a database table and upon executing a job (or a command or a cron, or whatevs) it fires out the "unprocessed" 1099s,fills in the PDF/DOC, prints the output into another PDF, maybe digitally signs it? not sure if that's a requirement, and then sends it to the end-user, aye? :shipit:

**Comment by owocki** [comment]
i gave a list of names, addresses, + SSNs to consensys Finance.  they then generated the 1099s, and i emailed them to our customers.

i like the architecture u proposed for next year tho!

**Comment by kuhnchris** [comment]
Well, if you could provide an example 1099 + what data you gave then we could see what's possible ;-)

**Comment by MannyCho** [comment]
Glad to see this is being addressed. Traditionally, a contractor in the US will provide a W-9 that has most of the relevant information to populate a 1099 with. You can automate this by having a standard template that's compiled and digitally signed by the contractor when a proposal is awarded. HR platforms like Gusto have contractor self-onboarding functionality.

Please do take caution when providing PII (personally identifiable information), such as SSN's, names and addresses, to other parties. Permission must be obtained before sharing this info.

**Comment by ceresstation** [comment]
@owocki what does the architecture look like here for this year?

**Comment by owocki** [comment]
same as last year, unless we prioritize something different https://github.com/gitcoinco/web/issues/3381#issuecomment-458730399

**Comment by owocki** [comment]
this ticket actually has a spec on it; any feedback? https://github.com/gitcoinco/web/issues/4806
