### ISSUE TITLE
bug - create recurring payment currency drop-down

### ISSUE THREAD

**Issue by djosey** [gitcoinco/web#3388]
##### 12 Jan 2k19

@djosey I'm gonna reopen cause you have a valid point here

> Retried with trust wallet and got past this issue, but the drop-down wouldn't show any of the tokens in my wallet, including eth(?). Marking on this page that you have to complete signup with a web3 browser probably wouldn't hurt!

This is needed on the fund & cancel page.

> Closing the issue but still wasn't yet able to make a contribution with trust wallet.

I personally haven't funded a grant it over trust wallet. I'll double check on this

------

##### 2 Jan 2k19

Attempted to create subscription payment on prysmatic labs subscription object in mobile. Input monthly payment period, amount per period, number of recurring payments, all successfully.

when I attempted to input the currency that the monthly subscription amount was to be tendered in (dai), I clicked the drop down menu and the pop-up came up with 'no results found.' Attempted to key in dai, eth, etc, but no results were found. 

I'm guessing there's a list of currency values which this drop-down box references, and for some reason it wasn't pulling those values for me. Puzzling because others have successfully submitted subscriptions without being blocked by this issue. Possibly a mobile problem? Drop-down box should suggest currencies to user for selection so user can complete the subscription process in their currency of choice. 

I was so close, the project I was looking at gets my subscription when this issue is resolved, I promise! Unless there's another blocker!

**Comment by owocki** [comment]
thanks @djosey -- what mobile device were you using? which web3 browser were you using?

**Comment by thelostone-mc** [comment]
@djosey so the list of tokens gets updated based on the network you are in!
could you double check the network

I checked it on chrome browser on my laptop and trust wallet on mobile and it loaded fine

<img width="1403" alt="screen shot 2019-01-11 at 1 36 47 pm" src="https://user-images.githubusercontent.com/5358146/51021133-a942ea00-15a6-11e9-8dda-1a6fe650908e.png">

**Comment by djosey** [comment]
Oh I see... My assumption may have been that I would have to do whatever to sign up and do the web3 part next, but I wasn't thinking... I was just using chrome. 

Retried with trust wallet and got past this issue, but the drop-down wouldn't show any of the tokens in my wallet, including eth(?). Marking on this page that you have to complete signup with a web3 browser probably wouldn't hurt! 

Closing the issue but still wasn't yet able to make a contribution with trust wallet.

**Comment by thelostone-mc** [comment]
@djosey we've added the checks in & have a PR out for it ^_^

<img width="1440" alt="screen shot 2019-01-13 at 3 45 50 pm" src="https://user-images.githubusercontent.com/5358146/51084102-bbf62400-174a-11e9-8289-be78229c274d.png">

**Comment by owocki** [comment]
we dont support ETH as it is not an ERC20 token and we need ERC20 support for EIP 1337.

the workaround is using WETH https://github.com/gitcoinco/web/issues/3412

**Comment by djosey** [comment]
Oh ok I see.
