### ISSUE TITLE
get everyone onboarded to 1Password

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3390]

**Comment by kuhnchris** [comment]
https://github.com/1Password/1password-teams-open-source *hint hint*

**Comment by thelostone-mc** [comment]
Eveyones

**Comment by octavioamu** [comment]
I still need to see what happened with the email I didn't received :/

**Comment by thelostone-mc** [comment]
Oh damn I thought that was sorted out  ! Ping IT and they should be able to take care of it 🙌
