### ISSUE TITLE
Grants - TypeError: web3 is undefined

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#3395]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/2443/

```
TypeError: web3 is undefined
  at listen_web3_1_changes (/static/v2/js/grants/shared.502ea7291830.js:39:5)
```

https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/2735/

```
ReferenceError: Undefined variable: Web3
  at None (/grants/:1782)
```

**Comment by kuhnchris** [comment]
Wait, why are there javascript errors reported at sentry? Isn't that a frontend issue on the user side (for example no meta mask installed)?
