### ISSUE TITLE
bug - tooltip not showing on basic payout

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3396]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
bug - tooltip not showing on basic payout

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
go to https://gitcoin.co/issue/accept?pk=7882&network=mainnet or any basic payout
hover over the tooltip ( http://bits.owocki.com/3541b5ba8bde/Screen%20Shot%202019-01-03%20at%2011.26.43%20AM.png ) 
it wont show up

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
tooltip shows up

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
http://bits.owocki.com/3541b5ba8bde/Screen%20Shot%202019-01-03%20at%2011.26.43%20AM.png

**Desktop (please complete the following information):**

- OS: OSX
- Browser  Chrome
- Browser Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by thelostone-mc** [comment]
Closing this out as @owocki already pushed in the fix !
