### ISSUE TITLE
as a grants creator, i want my grants updates to go out to users inboxes, so my updates have the widest possible reach

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3400]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grants creator, i want my grants updates to go out to users inboxes, so my updates have the widest possible reach

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
users are asking for it; see https://twitter.com/owocki/status/1080882913011552256 " I want to get content and updates about all the awesome things that are happening with the money that I am donating. Otherwise I think this is a great idea."

receiving updates on your grant increases the chances you'll not churn (continue to support it)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
features

### Current Behavior
[comment]: # (Describe what actually happened.)
updates dont go to inboxes

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- when posting your updates, checkbox that allows you to send them to ppls inbox
- email settings allows u to manage grant updates
- beautifully designed update email

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by Anish-Agnihotri** [comment]
This is a good idea to make sure outreach is maximized. I believe there already is an update notification email, correct?

https://github.com/gitcoinco/web/blob/master/app/retail/templates/emails/grants/update_notification.html

**Comment by owocki** [comment]
it doesnt seem to be wired into anything

```
Searching 19145 files for "update_notification.html"

0 matches
```
