### ISSUE TITLE
Grants - SyntaxError: Invalid character: '`'

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#3410]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/166/

```
SyntaxError: Invalid character: '`'
  at None (/static/v2/js/shared.a60c28e5430f.js:218)
```

**Comment by thelostone-mc** [comment]
@octavioamu can't seem to figure this out ! [This is ](https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/shared.js#L218) legit usage -.-
