### ISSUE TITLE
As a user setting up a Gitcoin Grant, I couldn't find a wrapped Ether (WETH) option out of the many supported tokens, so I ended up going for DAI

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3412]
### User Story

As a user setting up a Gitcoin Grant, I couldn't find a wrapped Ether (WETH) option out of the many supported tokens, so I ended up going for DAI.

### Why Is this Needed

DAI is a stable-coin aiming to track the US dollar, which is great, but the user didn't have any. He had to look up an exchange to find a cost-effective way to exchange Ether for DAI.

### Description

The reason for this is that Gitcoin seeks to support the ERC-1337 standard for recurring subscriptions on the blockchain. This seems to rely on ERC20's `approve()` method to pre-approve future payments.

### Current Behavior

There is not WETH option to set up a Gitcoin Grant.

### Expected Behavior

There should be a WETH option to set up a Gitcoin Grant, so the user doesn't have to go digging on exchanges to get DAI and open a Gitcoin Grant.

### Definition of Done

TBD once prioritized

**Comment by kuhnchris** [comment]
could we simply "pin" a couple of options that are popular? maybe customizable via _admin so it can be changed later

**Comment by owocki** [comment]
related to https://github.com/gitcoinco/web/issues/3389
