### ISSUE TITLE
As a user setting up a Gitcoin Grant, the lag time between hitting "contribute to grant" and the first payment is confusing.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3414]
### User Story

As a user setting up a Gitcoin Grant, the lag time between hitting "contribute to grant" and the first payment is confusing.

### Why Is this Needed

As a user, seeing the effect of contributing to a grant makes sense when they've received confirmation in two ways - the money is taken, and the progress bar shows progress.

### Description

The instructions say that, "The first payment will happen immediately after you click Contribute to Grant." However, no DAI has left my account yet after clicking "Contribute to Grant". And grant contributions still show as zero. 

### Current Behavior

There is lag time (~10 minutes) between contributing to a grant, the first payment, and the grant contributions progress bar.

### Expected Behavior

This is less lag time between contributing to a grant, the first payment, and the grant contributions progress bar.

### Definition of Done

TBD once prioritized

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/3314
