### ISSUE TITLE
Grants - decimal_places in Subscription Model need to be raised

### ISSUE THREAD

**Issue by captnseagraves** [gitcoinco/web#3419]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Grants User I want to be able to submit a Subscription amount to 18 decimals since the ecosystem uses this as its standard, so that I can always submit values that are processed by the subminer. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently, if a user submits a value with more than 4 decimal places that value is rounded and saved to four decimal places by our backend which results in failing transactoin when submitted by the subminer. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
When the decimal places on the `amount_per_period` is raised to 18 and any frontend displays 4 decimals. 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
So you want to subscribe in WEI-range? Wouldn't... that be eaten by the gas costs?
Or do you mean non-ETH tokens, like some random token that works in a reaaaaaaaaly low fractional range?
Anyways, should be rather trival, app/grants/models.py --> go to amount_per_period, raise decimal_places, python app/manage.py makemigrations && python app/manage.py migrate

![image](https://user-images.githubusercontent.com/761911/50712807-233d1580-1073-11e9-8a9d-5320261ad9a0.png)
