### ISSUE TITLE
as a user playing the ETHDenver set completion game, I want this nalgene water bottom design, so I can show off my kudos while i  drink fresh colorado water

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3432]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user playing the ETHDenver set completion game, I want this nalgene water bottom design, so I can show off my kudos while i  drink fresh colorado wateras a user playing the ETHDenver set completion game, I want this nalgene water bottom design, so I can show off my kudos while i  drink fresh colorado water

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No water bottle

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

I can drink fresh fresh colorado water bottle as I hack away at ETHDenver, and I can show off my badass Gitcoin Kudos when I do it.

<img width="894" alt="screen shot 2019-01-07 at 7 48 01 am" src="https://user-images.githubusercontent.com/513929/50774481-c9924200-1250-11e9-85a7-db1c208bcd9d.png">

Expectations from the customer:

<img width="1147" alt="screen shot 2019-01-07 at 7 50 06 am" src="https://user-images.githubusercontent.com/513929/50774519-e0d12f80-1250-11e9-8bbf-6fd99a899f5a.png">

Nalgene template from the vendor: http://bits.owocki.com/265f2d21a0b2/Nalgene%20Tritan%2032%20oz%20.PDF

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

It may take 2-3 revs to get right with John Paller.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
https://github.com/gitcoinco/web/issues/3197

**Comment by owocki** [comment]
this ticket is the physical component of digital one => https://github.com/gitcoinco/web/issues/3197

**Comment by owocki** [comment]
cc @PixelantDesign @kuhnchris @vs77bb @ceresstation  for review .  should i bounty this or assign it internally?

i view ETHDenver as a time when we can introduce some new messaging / marketing.  it fits into the OKRs in that it will reduce our CAC

**Comment by kuhnchris** [comment]
they wrote they sent a mock-up with that? (...the dimensions of the bufficorn are included in the mock-up)
If they got something, please provide, else I'll throw up something real quick. Do we have the sponsor logos etc. availble?

**Comment by owocki** [comment]
sponsor logos => http://bits.owocki.com/065be8437a0e/ethdenver%20sponsor%20logos.zip

bufficorn => http://bits.owocki.com/985a7024057f/Archive%202019-01-07%20at%2012.32.00%20PM.zip

ethdenver logo => https://www.ethdenver.com/wp-content/themes/understrap/img/logo-large.svg

**Comment by kuhnchris** [comment]
Throw up a bounty for that, I suck too much for this ,sorry.

**Comment by owocki** [comment]
np, we'll have our internal designer owrk on this

**Comment by owocki** [comment]
yes.  we sent the design over to the ETHDenver folks.  closing this task now
