### ISSUE TITLE
As a user, I want to push a big red button at Gitcoin.co/easybutton because I know I need coders, but I dont know how to navigate Gitcoin's product suite.  This gives me an easy big button to push to help me figure it out.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3436]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want to push a big red button at Gitcoin.co/easybutton because I know I need coders, but I dont know how to navigate Gitcoin's product suite.  This gives me an easy big button to push to help me figure it out.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Data is the new gold.  Everyone needs better data, better software.  Software is eating hte world.

Because everyone needs these new systems, everyone needs software engineers.

If you have access to software engineers, and can provide access to them to businesses in a way that manages expectations / trust all around, then you are selling pixaxes to the gold miners.

We are testing the value proposition of "Push a button, get a Coder".     "Push a button get a coder" is the most concisely expressed value prop, to funders, of Gitcoin to date.  (For coders our value prop remains that we grow/sustain open source).

As expressed in our Q1 pitch deck.  Before Gitcoin I had to do a whole bunch of bullshit in order to find a coder.

<img width="751" alt="screen shot 2019-01-07 at 8 07 23 am" src="https://user-images.githubusercontent.com/513929/50775414-5e963a80-1253-11e9-85bd-2145148e3a20.png">

After Gitcoin, I don't anymore.

This is a lean test of that marketing message.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Expression of this value prop

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Landing page at Gitcoin.co/ that expresses this value prop.

Here is what the user journey will look like:
<img width="954" alt="screen shot 2019-01-07 at 8 09 01 am" src="https://user-images.githubusercontent.com/513929/50775502-92716000-1253-11e9-80b1-29c117c25740.png">

The landing page gitcoin.co/easybutton => will contain the following

H1. Coders, at your fingertips
P: Gitcoin is a network of coder superheroes that are ready to work for you.

Call to Action -- Get Coders

Next module should be our some testimonial module 
Next module should be our some stats module to show that were serious.

Last module:

H1: What are you waiting for?
P: Get Coders, at your fingertips
CTA: Get a Coder

(It'd be cool if the "Get a Coder" CTA could follow you up and down the page too. )

### Conversion Module

When a user clicks the 'get a coder' button, we will capture their email address.
We will also allow them to put in freeform comments about what they want.
There will be a H1 that says "Get a free consultation with Gitcoin team".

### Backend Management of the Leads

I would like the leads to be stored in the DB under a new model called 'EasyButtonLeads'.  This model will have the following fields.

profile pk
email
stage (todo, doing, done)
comments
admin_comments

Upon the creation of a new EasyButtonLeads, an email will be sent to Alessandro Voto <alex.voto@consensys.net>, Scott Moore <scott.moore@consensys.net> letting them know they need to triage this lead.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
[Proposed Value Prop Slide, on this, from Internal 'Crypto Winter War Plan'](http://bits.owocki.com/fa834214d807/Screen%20Shot%202019-01-07%20at%208.09.51%20AM.png)

**Comment by owocki** [comment]
@PixelantDesign @vs77bb @ceresstation @alexvotofuture take a look at the above and lmk if nay feedback

**Comment by kuhnchris** [comment]
Well i'd like to investigate how you differenciate between "yes" and "fuck yes". Does it include any level of bodily fluids?

**Comment by owocki** [comment]
fuck yes == they are within the blockchain niche / are a HUGE brand name or partnership oppy / can pay a decent amount of $$$
yes == they can pay $$$
no == they can't pay

**Comment by PixelantDesign** [comment]
Ideas so far are : 
1) Push a button get a coder
2) Rub a lamp get a genie
3) On the pricing page we have robot super heroes packages/tiers

I wonder if people might get confused with all of the metaphors.

If we can someway align on the metaphor and get it to work throughout it would be ideal. It’s a stronger messaging and less confusing if we can tie it all together.

Thoughts @vs77bb @ceresstation

**Comment by kuhnchris** [comment]
"Button->Coder" prolly could work via ServiceDesk/HelpDesk as first level (e.a. evaluating Kevins Range from No to Fuck yes), and from there either branch to Slack/Discord (No-path), known devs directly (Yes) or Core-Team/selected high value members (Fuck yes).
