### ISSUE TITLE
Austin Griffith ETHDenver Talk

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3438]

**Comment by owocki** [comment]
@austintgriffith whats your talk at ETHDen gonna be about ? 

i am trakcing our prep for ETHDen at https://github.com/gitcoinco/web/projects/27#card-16251197

**Comment by austintgriffith** [comment]
I think I moved myself to a panel and pulled in a couple other meta tx people. I'll talk with Coury a little more this afternoon. Is there something specifically you'd like me to hit?

**Comment by owocki** [comment]
nope; just wrote this up to track everything were doing for ethden

**Comment by austintgriffith** [comment]
Meta Transactions Panel! You know I'll shill colorado, 1337, and the burner passively, but I think this one is for meta tx UX etc.
