### ISSUE TITLE
As a community member, I want to understand Slack Free Plan Limit so I know that the community can keep growing.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#344]
http://www.businessinsider.com/slack-free-unlimited-plan-has-limits-2015-6
https://davechen.net/2017/01/slack-user-limit/

We may have to stop growing the slack community when we get to 8500 users... At least thats what word on the street is..

TODOS:
* Decide our strategy for dealing with this.. Do we want to continue investing in slack?  Move somewhere elsee?  Delete inactive users?

**Comment by razordaze** [comment]
You may want to look into migrating to [Discord](https://www.reddit.com/r/discordapp/comments/4ymh13/discord_user_limit/). It was designed more for pleasure than business, but AFAIK it's a better option to free Slack in every way.

I'd not really noticed [Gitter](https://gitter.zendesk.com/hc/en-us/articles/201311981-How-much-does-it-cost-) before reading that BI article. Seems like if it was worth migrating to Slack from, though, that might put Discord at the top of the heap anyways?

BTW, is it just me, or is it kinda fucked that anyone with access to the team can poke their head into billing stuff like this? 
![image](https://user-images.githubusercontent.com/487308/35705037-20059ada-0756-11e8-9ade-0ce6d968cacc.png)

**Comment by lazaridiscom** [comment]
@owocki , personally, I do not like slack. It annoys me with "upgrade to search" kind of messages, and i generally do not like communication tools which are proprietary.

I suggest to simply make an evaluation of possible communication tools. "Back to the Roots" could do it, too.

**Comment by jasonrhaas** [comment]
I believe Slack will only change you for users that are Active.  On another Slack team I am on, they give credits for users that are inactive.  I think Slack is great for inter-team work and communication.  As far as a community center, something like Gitter or Discord may be more cost effective.
