### ISSUE TITLE
as a contributor, i think that the new pull request template is too bureacratic, and i'd like to have it simplified

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3442]
as a contributor, i think that the new pull request template is too bureacratic, and i'd like to have it simplified

fast iteration is the new moat, its what keeps us alive.  why are we making users fill out 20 checkboxes to submit a single PR?  this will massively slow down the amount of contributions we get.

i expressed this here too => https://github.com/gitcoinco/web/commit/088d209fe3230379fe0da8e27ab763f0c416cb19#diff-195a635ad245ded9076330e31134bd80

**Comment by owocki** [comment]
@octavioamu @thelostone-mc @SaptakS i'm willing to be outnumbered on this and stand down... tell me what you really think pls.

**Comment by owocki** [comment]
cc @kuhnchris too since he's made a few edits to this file

**Comment by kuhnchris** [comment]
Well it's very broadly very generic.
It also assumes you only do a PR if it's payed (payee section).
Maybe cut down on some sections, or relay them to the docs.gitcoin.co for certain sections?
