### ISSUE TITLE
BUILD - As a funder, how can we best promote recurring funding (Gitcoin Grants) to contributors?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3445]
### User Story

As a funder, how can we best promote recurring funding (Gitcoin Grants) to contributors?

### Why Is this Needed

With the release of Gitcoin Grants, how do we best expose funders to a recurrent source of funding that can help push forward open source? This directly impacts our 2019 Q1 OKRs wrt Gitcoin Grants.

### Problem Description

Getting recurring funding is good for all three sides. Contributors get steady payment, funders get stuff done, and Gitcoin gets MPV. Issues that funders put up can be part of a larger open source project. Is there a way to take advantage of that fact and keep the funding loop going?  (See the engagement loop below at the "brand promise fulfilled" step.)

Engagement loop: https://app.mural.co/t/consensys3989/m/consensys3989/1546862521032/a0795c8d2ba4e432240feb51ec512b085d4d0b79

Flow diagram:

![screen shot 2019-01-09 at 11 58 37](https://user-images.githubusercontent.com/7516920/50924988-ea4fc880-1405-11e9-9c2e-af944830e1db.png)

* funder funds issue A
* hunter completes issue A
* funder pays out hunter
* https://github.com/gitcoinco/web/issues/3469 & https://github.com/gitcoinco/web/issues/3445 - can we re-engage the funder here to suggest that the contributor open a grant based on their past work?

### Ideas

1. At the end of a successful bounty completion, send an email or surface a modal asking if the funder would be interested in suggesting a grant or surfacing additional related work on the same project to the contributor on Grants after paying out the contributor.

2. When a funder is funding an issue, have a type of ad module that pops up depending on the size of the bounty. If the bounty is very large, perhaps we have an "appearing" section that recommends the funder set up a Gitcoin Grant or contribute to one. (update: this is not possible).

### Definition of Done

1.  Built to the specifications of the design ticket: https://github.com/gitcoinco/web/issues/3469

### Test Results

1. Increase X% of grants MPV per participant over time.
2. % of active funders before & after.
3. Reactivation rate of funders.

**Comment by owocki** [comment]
seems like an upsell of a gitcoin bounty.. after you've done a successful bounty with someone, maybe ull want to set them up on a grant

**Comment by frankchen07** [comment]
[Grants Virality Sketches.zip](https://github.com/gitcoinco/web/files/2795022/Grants.Virality.Sketches.zip)

**Comment by PixelantDesign** [comment]
The suggest a contributor screen Octavio hasn't built. Might be best to leverage what has been built after this sprint? Unless they can work together at the same time this sprint. Up to you all @octavioamu @thelostone-mc
