### ISSUE TITLE
EPIC Fund an Issue from a Private Repo

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3449]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo maintainer, i want to be able to fund an issue from a private repo, so i can have contributors work on private stuff

### Why Is this Needed

Even though there is a macro trend towards OSS, there is much more closed sourced software out there than open source software still.

Like how Netflix started with DVDs as a means of creating a giant internet video streaming service, so too, will we support closed source repos on Gitcoin.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No support for Closed Source Software

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

When a user submits a bounty that is closed source on the current gitcoin.co/new flow...
The system will detect that it is from a private repo.  When it detects that, it will
1. toggle on a tooltip that says "this is a private repo.   learn more about gitcoin's support for private repos, [click here](https://link/to/cms/page/describing/private/repo_support)
2. the system will set the permission type to be 'approval required'
3. the user will be prompted to give gitcoinbot access to their private codebase.  if the user follows our intstructions for doing so, we will prefill the bounty title / desc.  if not, they will be asked to enter their own bounty / title desc.
4. the bounty hunter will be given the option to NDA any applicants.  gitcoin will have many NDAs available for funders to use.  some will be available to everyone, some will be available only to specific users.  all of them can be managed via an `NDA` model in the admin, which will have the following fields: name, description, PDF_link, available_to_users.  The NDAs can also be uploaded / managed in the Gitcoin settings page, under a new tab called 'advanced'.

user presses submit.  bounty is posted as per normal.

on the bounty explorer page
1. there will be a 'private repo' tag for this bounty on it's row on the explorer page

on the bounty detail page
1. there will be a 'private repo' tag in the header for the bounty.
2. when a user applies to start work, they will have to sign an NDA.  if they do not sign the NDA, they cannot apply.
3. when a user is approved to start work, their access to a private repo will be granted (if gitcoin bot has access to manage their perms). if gitcoinbot does not have access to add/remove them, an email will be sent to the funder reminding them to add access.
4. when a user stops work, their access to a private repo will be removed (if gitcoin bot has access to manage their perms). if gitcoinbot does not have access to add/remove them, an email will be sent to the funder reminding them to remove access.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above ^^

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
We will need to source the NDA copy from legal.
We will need to write a CMS page about how private repos work.

If there is a dispute, how does someone arbitrate without looking at the IP / public PR?  We will have to keep a close eye on this and handle it in a v2.

### Metric
- MPV, active funders, & bounty hunters on private repos as compared to public ones
- LTV on public repo bounties vs private repo bounties

**Comment by PixelantDesign** [comment]
Engineers review Kevin's proposal and provide feedback. @SaptakS @octavioamu 
Come up with a tech approach on how to address in the next sprint.

**Comment by owocki** [comment]
Notes from call with Solutions: 

    - Most NDAs would have to be client approved (so having the ability to manage / upload multiple NDAs is key).
    Two parties sign off any candidate before they have access. They’d need client sign off for each candidate.. Jon was saying we should use a multi-sig, but that sounds a little complicated to me..

**Comment by octavioamu** [comment]
could be a v1 just manual approval? so people just send the doc and when everything is ok the funder let the user access?

**Comment by Nnooo** [comment]
Hey @owocki and @PixelantDesign I am about to start looking at this issue that ok?

**Comment by Nnooo** [comment]
![gitcoin_3449_wireframes_fundissue_create_spacingissues](https://user-images.githubusercontent.com/3150525/51453315-a8197600-1d79-11e9-8894-31c14b154b60.png)

I have started mocking this up today. 

Firstly I would like to recommend that I spend some time fixing up the spacing of the existing sign up page (see enclosed image). As you can see there are a lot of inconsistent spaces which makes the sign up sheet use a lot more space than necessary.

I already have a design and idea for how to integrate this request and don't imagine it to drastically alter the current flows. However I would like to discuss the funding for this before I continue. @PixelantDesign quoted $150 work for this. However it is likely to be at least 2 days and my daily rate is usually US$860.00.

So for US$1720.00 I would provide you with wireframes, to the fidelity shown of the Create a new Funded Issue screen, the Bounty Explorer, the Bounty Explorer with popup overlay, the Bounty Detail page. NOTE: the enclosed image is a wireframe done in illustrator.

Please let me know how you would like to proceed.

**Comment by Nnooo** [comment]
![gitcoin_3449_wireframes_fundissue_create_spacingcomparison_01](https://user-images.githubusercontent.com/3150525/51454849-c71c0600-1d81-11e9-8eea-a2602a46241e.png)
![gitcoin_3449_wireframes_fundissue_create_spacingcomparison_02](https://user-images.githubusercontent.com/3150525/51454850-c71c0600-1d81-11e9-99bb-a16a47fdc8f0.png)

These two images demonstrate the difference. You can see in the left image that the boxes are a more consistent size and deliniate the same type of content with similar spacing. I have also made all the dropdowns and cells the same height and spaced them so the right hand edges of these line up with the right hand margin.

I imagine that this type of layout would make it easier to add future content too as the formatting is already taken care of by using a templated structure?

Let me know your thoughts and how you would like to proceed.

**Comment by Nnooo** [comment]
@PixelantDesign and @owocki I have now completed the wireframe design of this. Once you assign me the bounty and price it I can upload what I have done and provide a pdf detailing the logic.

Thanks and I look forward to completing this issue with you both.

**Comment by octavioamu** [comment]
@nnooo thanks for the work.
This is not a design task as I know, is just to discuss the technical approach we will do for handle privates repos. Not sure if you already discussed something with Alisa and Kevin and I'm not aware.
Anyway I recommend you to take a look for our issues tagged as "design"

**Comment by abitrolly** [comment]
Doesn't that shift the focus from supporting open source to supporting gig economy?

**Comment by Nnooo** [comment]
> Doesn't that shift the focus from supporting open source to supporting gig economy?

Is that in reply to me or @octavioamu ?

**Comment by octavioamu** [comment]
Some docs for technical approach 
https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
https://developer.github.com/v3/repos/invitations/#invite-a-user-to-a-repository

**Comment by octavioamu** [comment]
@abitrolly to be able to support OSS we also need to be profitable as company, in this way we can do a better work with the open source community and also bring more bounties for contributors not only from open source projects.

**Comment by owocki** [comment]
> Doesn't that shift the focus from supporting open source to supporting gig economy?

I'd add that we see the two as mutually reinforcing, not mutually exclusive.  Our mission is, and always will be, to Grow and sustain open source.

**Comment by PixelantDesign** [comment]
From @octavioamu 
cc: @thelostone-mc @SaptakS @owocki 

Private repos FLOW

FUNDER NEED TO HAVE ADMIN PERMISSIONS of the gh repo

Funder authorise gitcoin to be able to see issues, 
Autocompleted issues search box
User pick the issue 
We take the details of the issue
we can show in the explorer without issue link or just reserve for some user

Contributor applies 
Funder receive an email and approves 
An email is fired to the contributor with  NDA docs to signed and sent to the funder
Funder receive the email and go to gitcoin to grant repo access 


STOP WORK / SUBMITTED WORK

Permissions for contributor removed. 


PROBLEMS 
We are not able to arbitrate the PR discussion (we need to put that in some legal way)

Gitcoin Bot 
We want gitcoin bot to be able to publish in the issue?

**Comment by Nnooo** [comment]
@pixelantdesign. Pretty much what I have mocked up ;)

**Comment by Nnooo** [comment]
[PrivateRepos.zip](https://github.com/gitcoinco/web/files/2819607/PrivateRepos.zip)
![privaterepo_fundissue_noissueselected](https://user-images.githubusercontent.com/3150525/52095009-817afb00-2615-11e9-820a-37248dc9400a.png)
![privaterepo_fundissue_issueselected](https://user-images.githubusercontent.com/3150525/52095015-8475eb80-2615-11e9-9f47-14ad2fd7753e.png)
![privaterepo_bountyviewer](https://user-images.githubusercontent.com/3150525/52095016-86d84580-2615-11e9-8066-7e7a7eaacaf2.png)
![Uploading PrivateRepo_BountyViewer_PopUp.png…]()
![privaterepo_bountyviewer_bountydetail](https://user-images.githubusercontent.com/3150525/52095022-8b9cf980-2615-11e9-86d4-a7a4f57c350b.png)

Hey @PixelantDesign here is the work I did on this issue. You asked me to submit them so you could tip me. Good luck with this!

Note this is two full days of work (16 hours).
