### ISSUE TITLE
EPIC Encourage Sharing and Joining Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3450]
### User Story

As a contributor, how can I encourage other great developers to join Gitcoin and help grow open source?

### Why Is this Needed
To grow the Gitcoin platform with qualified contributors/developers. how do we best do this? 

### Problem Description

There are a lot of ways to tackle virality. How do we approach this so that we aren't having to pay as much as we would pay for google ads when our goal is to get CAC down?

### Ideas

1. Use Kudos as the reward and set up tiers for success. Ex: If contributor invites 1 friend - upon work completion, give a kudos, invite 5 friends get a super kudos - invite 50 friends get a master kudos. Kudos for us are cents on the dollar, with a $100 budget we can give out quite a few. 

![image from ios 4](https://user-images.githubusercontent.com/238235/50837008-9622e680-1328-11e9-8a84-d0ef88fe615c.jpg)

### Workshopping

1. Alternative solutions to the problem description.
2. Where in the flow should sharing/inviting take place?
3. What does success look like?
4. Messaging

### Definition of Done

1. pure absolute number of friends who complete a bounty by those invites
2. value of Kudos given out
3. retention % of those profiles who refer and get a kudos
4. for those who joined by a friend invite, do they retain better than just organics who find Gitcoin?
5. User test idea with contributors
6. Make adjustments based on feedback.

### References

[Building Content Loops]( https://firstround.com/review/pinterest-and-grubhubs-former-growth-lead-on-building-content-loops/)

**Comment by vs77bb** [comment]
I love this ticket and I'm all for it - I think it's very high priority to get live and see what it can do for us in practice. 

I wonder if we should tell people they *will* get Kudos, or simply build in the functionality to invite friends, first. The levels to me are: 

1) Just build the functionality to easily invite your friends (other Github users, or e-mail accounts). 
2) Test how it works when we offer custom Kudos 
3) Test how it works when we offer $5  

[From Andrew Chen's guide](https://andrewchen.co/investor-metrics-deck/)

<img width="580" alt="screen shot 2019-01-09 at 3 17 15 pm" src="https://user-images.githubusercontent.com/23297747/50929069-f77ab080-1421-11e9-9356-de42375760fe.png">

**Comment by owocki** [comment]
note that there is an existing 'share' button after you click the 'contribute' button on the issue explorer page

**Comment by willsputra** [comment]
@owocki ah wasn't aware of that. noted thanks @owocki!

**Comment by PixelantDesign** [comment]
Team Review
Will to look at Kudos Share.

**Comment by owocki** [comment]
> Outstanding questions: which Kudos are we going to give? if I invite a friend, are we both going to get a Kudos, or just me?

I like the idea of giving out the bot kudos.  Alternatively we could just make a special kudos for people who have invited friends.

> Issue Details page

I like this!  CTA buttons on the right makes intuitive sense to me :)

**Comment by PixelantDesign** [comment]
<img width="997" alt="screen shot 2019-01-23 at 3 13 57 pm" src="https://user-images.githubusercontent.com/238235/51675806-c31afe80-1fa2-11e9-9435-04b33b9341fd.png">

**Comment by willsputra** [comment]
Sprint 2 (without Kudos): https://sketch.cloud/s/RVRPz
Sprint 3 (with Kudos or other incentives): https://sketch.cloud/s/KnDKe
