### ISSUE TITLE
New funded issue form does not automatically add the URL from the querystring

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/web#346]
<img width="1544" alt="sharing_frame_window" src="https://user-images.githubusercontent.com/12481/35645512-48f1aba0-0689-11e8-8e42-04466d0f305e.png">

##### Description
When I go to the new funding form, it does not pre-populate the issue URL with what's in the query string.

##### Possible Implementation
Likely a missing assignment in the view.py

##### Environment
Mac / Chrome

**Comment by mbeacom** [comment]
Which action item directed you to: `https://gitcoin.co/funding/new/?url=https://github.com/codesponsor/codesponsor/issues/59` ?

We are checking for the GET param: `source` on that view.  So, `https://gitcoin.co/funding/new/?source=https://github.com/codesponsor/codesponsor/issues/59` should work to pre-populate this.

Once I know where we're directing to this view with `url` versus `source`, I'll update it.

**Comment by coderberry** [comment]
My expected experience is if the URL contains ?url=___ISSUE_URL__, I should not need to type in the issue URL in the form below.
