### ISSUE TITLE
DESIGN - As a funder, how can we best promote recurring funding (Gitcoin Grants) to contributors?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3469]
### User Story

As a funder, how can we best promote recurring funding (Gitcoin Grants) to contributors?

### Why Is this Needed

With the release of Gitcoin Grants, how do we best expose funders to a recurrent source of funding that can help push forward open source? This directly impacts our 2019 Q1 OKRs wrt Gitcoin Grants.

### Problem Description

Getting recurring funding is good for all three sides. Contributors get steady payment, funders get stuff done, and Gitcoin gets MPV. Issues that funders put up can be part of a larger open source project. Is there a way to take advantage of that fact and keep the funding loop going?  (See the engagement loop below at the "brand promise fulfilled" step.)

Engagement loop: https://app.mural.co/t/consensys3989/m/consensys3989/1546862521032/a0795c8d2ba4e432240feb51ec512b085d4d0b79

Flow diagram:

![screen shot 2019-01-09 at 11 58 37](https://user-images.githubusercontent.com/7516920/50924988-ea4fc880-1405-11e9-9c2e-af944830e1db.png)

* funder funds issue A
* hunter completes issue A
* funder pays out hunter
* https://github.com/gitcoinco/web/issues/3469 & https://github.com/gitcoinco/web/issues/3445 - can we re-engage the funder here to suggest that the contributor open a grant based on their past work?

### Ideas

1. At the end of a successful bounty completion, send an email or surface a modal asking if the funder would be interested in suggesting a grant or surfacing additional related work on the same project to the contributor on Grants after paying out the contributor.

2. When a funder is funding an issue, have a type of ad module that pops up depending on the size of the bounty. If the bounty is very large, perhaps we have an "appearing" section that recommends the funder set up a Gitcoin Grant or contribute to one. (update: this is not possible).

### Workshopping Details

1. Alternative solutions to the problem description?
2. Where in the funder flow should this take place? (funding an issue, or at the end of payment, or both?
3. Email or modal, or built into the funder page, or both?
4. Messaging

### Definition of Done

1. Decision point on where in the funder flow it should take place. 
2. Design templates for the agreed upon solution.

**Comment by PixelantDesign** [comment]
@frankchen07 
@thelostone-mc and I looked at the description and this part is unclear:

At the end of a successful bounty completion, send an email or surface a modal asking if the funder would be interested in funding additional related work on the same project on Grants after paying out the contributor who most recently helped them with that project.

**Comment by owocki** [comment]
damn i <3 dat line art

**Comment by PixelantDesign** [comment]
yes belongs on payout screen!

**Comment by owocki** [comment]
i worry that the blue bar looks to visually similar to the 'payout bounty' button ... and the user might mistake it as a button

**Comment by frankchen07** [comment]
One more point of discussion @PixelantDesign & @thelostone-mc  - should the "suggest a grant" be a checkbox (where the second iteration of "I have read and understand the terms" area, or should it be a clickable link under the banner? 

Depending on the decision above, the final flow will be different, and a additional confirmation screen might be necessary: 

**Checkbox:** funder -> payout screen -> funder checks suggest a grant" -> payout > pays out and sends a suggestion to the contributor to open a grant -> suggest grant design sent in an email 

**Banner click:** funder -> payout screen -> funder sees the Gitcoin Grants banner -> clicks "suggest a grant" -> page to CTA to send -> confirmation of suggestion sent to contributor (needs design, similar to "transaction processing" pages > suggest grant design sent in an email.

Checkbox seems kind of awkward to me, but it's easier on the design side. I'd personally prefer the CTA from banner, but that's alot of steps. Am I overthinking this?

**Comment by PixelantDesign** [comment]
I also prefer the CTA. It feels unnatural to have a checkbox at that point. Though I understand how it might be easier to use that as a trigger point from an engineering perspective.

Clean up Basic and Advanced Pay would be nice since it is a form that is used often. Would that be considered tech debt form clean up? Ultimately up to @frankchen07 though.

**Comment by PixelantDesign** [comment]
Updated below

**Payout Screens**
<img width="1032" alt="screen shot 2019-01-24 at 5 49 09 am" src="https://user-images.githubusercontent.com/238235/51673379-e5f5e480-1f9b-11e9-8f4c-525dfa064a06.png">

**Modal**
<img width="752" alt="screen shot 2019-01-24 at 5 49 24 am" src="https://user-images.githubusercontent.com/238235/51673402-f60dc400-1f9b-11e9-87d2-af26b5ac62d4.png">

**Email Confirmation**
We could repurpose this template for the funder receipt as well.
<img width="557" alt="screen shot 2019-01-24 at 5 49 34 am" src="https://user-images.githubusercontent.com/238235/51673434-09b92a80-1f9c-11e9-928f-f57ceb3e557d.png">
