### ISSUE TITLE
As a funder, I want to see the total monthly subscriptions a campaign is set to receive each month

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3470]
### Why Is this Needed

I want to know how close a project is to reaching its goal / know how much the community supports a given campaign to help me make a more informed decision about where my money will have the most impact.

### Current Behavior

The funding bar only displays subscriptions created in a given month.

### Expected Behavior

The funding bar displays all active ongoing subscriptions.

### Definition of Done

- [ ] Bar displays all current active subscriptions 
- [ ] Any delinquent subscriptions that are not brought into good standing in an X day time period are removed from the total until they are up to speed
- [ ] Any completed subscriptions are removed from the total

**Comment by owocki** [comment]
https://twitter.com/GetGitcoin/status/1083099687001804800

**Comment by frankchen07** [comment]
closed via https://github.com/gitcoinco/web/issues/4169
