### ISSUE TITLE
EPIC Move Metamask - Only Require Github to Auth

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#3476]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I'd like to authorize with Github (only) and provide a MetaMask account / ETH address when I 'Submit Work', so I don't have an extra barrier to creating an account until I'm ready to complete a bounty.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to make it as easy as possible for individuals to join Gitcoin. Let's allow folks to 'Start Work' without needed a MetaMask account. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Require a MetaMask account to create a Gitcoin profile. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Do not require a MetaMask account. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- User should be able to create a Gitcoin profile simply via Github auth
- User can 'Skip This Step' for MetaMask account on user on-boarding (i.e) Step 2 is optional. 
- Perhaps, move MetaMask step to Step 3? 
- Ensure Gitcoin users can 'Start Work', even if they don't yet have MetaMask accounts
- Ensure Gitcoin users are rerouted to add a MetaMask account, if they don't have one when they try to 'Submit Work'.
- Anything else? 

### Metrics To Track
- Add new funnels to HotJar and compare with old funnels pre-post change
- Does this meaningfully increase our user acquisition / CAC? 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
- User should be able to create a Gitcoin profile simply via Github auth
- User can 'Skip This Step' for MetaMask account on user on-boarding (i.e) Step 2 is optional. (1pt)
- Perhaps, move MetaMask step to Step 3? (alternative 1pt)
- Ensure Gitcoin users can 'Start Work', even if they don't yet have MetaMask accounts (3pt)
- Ensure Gitcoin users are rerouted to add a MetaMask account, if they don't have one when they try to 'Submit Work'. (8pts)

**Comment by PixelantDesign** [comment]
![metamask flow](https://user-images.githubusercontent.com/238235/51606275-73bfca00-1edf-11e9-8d56-23e4ae2d3538.jpg)
