### ISSUE TITLE
grants - should the monthly progress bar track only monthly recurring donations, or should it track one off donations?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3479]
should the monthly progress bar track only monthly recurring donations, or should it track one off donations?

options
1. it should track only recurrring donations
2. it should track any donations and reset every month
3. we can have two progress bars . one that shows (1) and one that shows (2) 

additional discussion:

> That works, separate bars might be simplest. I don’t know if we’re really haggling about the bar though / if this deviates from previous discussions. IIRC the discussion back when this came up with seagraves was that as a hacky workaround (to make sure grants seem as full as possible) we could display individual contributions and `not` remove them from the bar (ever) but that long term we would want a way to display individual contributions only in the month that they’re given. So if a grant has $1000 in monthly contributions for 6 months and someone in Month 1 makes a $500 donation, the bar would be at $1500 and then drop back down to $1000 for Month 2.

**Comment by danlipert** [comment]
I think the recent confusion regarding the bars supports #2 - I believe funders will expect to have a Patreon-like metric that counts any donations in a given month, regardless of if they are one-off or recurring.

**Comment by frankchen07** [comment]
closed via https://github.com/gitcoinco/web/issues/4169
