### ISSUE TITLE
grants -- we should make `monthly_amount_subscribed` dyanmic

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3484]
per convo with @captnseagraves today in office, the current implementation of monthly_amount_subscribed is totally stateful -- therethere it is prone to error if we forget to update it some where

we want to make it so that it tracks the `add_monthly_amount_subscribed` method in the grants.migrations.0005 file

**Comment by frankchen07** [comment]
closed via https://github.com/gitcoinco/web/issues/4169
