### ISSUE TITLE
CSS CLEANUP - As a receiver of the weekly email, I'd like to be able to easily read the email.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3488]
**Describe the bug**
CSS CLEANUP - As a receiver of the weekly email, I"d like to be able to easily read the email.

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: MAC
- Browser Safari

**Additional context**

<img width="770" alt="screen shot 2019-01-09 at 11 37 23 pm" src="https://user-images.githubusercontent.com/238235/50946512-b73e2100-1467-11e9-8b2e-2c9c4c0affb7.png">

<img width="641" alt="screen shot 2019-01-09 at 11 37 30 pm" src="https://user-images.githubusercontent.com/238235/50946514-b9a07b00-1467-11e9-92ba-6241dbf2ee7b.png">

**Comment by Anish-Agnihotri** [comment]
Knocking this out now. ETA tonight.
