### ISSUE TITLE
grants -- brand image is stretched on /fund page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3489]
![screencapture-gitcoin-co-grants-24-prysm-by-prysmatic-labs-fund-2019-01-10-08_18_48](https://user-images.githubusercontent.com/513929/50977860-6272c880-14b0-11e9-84f7-8e9da6968ffe.png)

we probably dont want to screw up our funders logos :)

**Comment by thelostone-mc** [comment]
Hmm I can't seem to reproduce it :P 

<img width="1440" alt="screen shot 2019-01-10 at 10 04 10 pm" src="https://user-images.githubusercontent.com/5358146/50982709-ca162b80-1523-11e9-9078-ad7ce0686cf6.png">

**Comment by owocki** [comment]
1800x1200 is my reso.. 

try going to the `/fund` page to repro it @thelostone-mc !

**Comment by owocki** [comment]
not page, not grant detail page
