### ISSUE TITLE
as a user, i want the values refresh to reflect our 2019 values, so i know what the cultural norms at gitcoin are 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3490]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want the values refresh to reflect our 2019 values, so i know what the cultural norms at gitcoin are 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
lets refresh /mission page to reflect our values we created as a team in 2019.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
2018 norms / values are listed on /mission

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
2019 norms / values are listed on /mission

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
refresh of mission page.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
cc @vs77bb @PixelantDesign

**Comment by PixelantDesign** [comment]
Great idea. @vs77bb could you share the synthesis?

**Comment by owocki** [comment]
note for when we get time for this: should probably have something about the "golden rule" on this page too.  thats prettymuch the rule that governs almost all interactions on the network
