### ISSUE TITLE
As a funder who is posting a bounty, I would like to be upsold to CodeFund ads, so I can get a broader reach for my bounty.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3496]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder who is posting a bounty, I would like to be upsold to CodeFund ads, so I can get a broader reach for my bounty.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Gitcoin wants revenue.
Funder wants broader reach for your bounties.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Features

### Current Behavior
[comment]: # (Describe what actually happened.)
No upsell ability

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Ability to pay 0.1 ETH for CodeFund ads to promote our bounty.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@PixelantDesign @frankchen07 @coderberry - eric and i think this might be a path to revenue for both projects.

**Comment by PixelantDesign** [comment]
like this idea. we could incorporate on the funder form. I’ll add to green board.
