### ISSUE TITLE
bug - reserved bounties should not show up in the daily new bounties email, unless they are reserved for me

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3497]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
this bounty ( https://gitcoin.co/issue/gitcoinco/web/3447/2098 ) showed up in my daily email ( http://bits.owocki.com/8591b5ad5be0/Screen%20Shot%202019-01-10%20at%202.25.46%20PM.png ) today.

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
reserved bounties should not show up in the daily new bounties email, unless they are reserved for me

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
this bounty ( https://gitcoin.co/issue/gitcoinco/web/3447/2098 ) showed up in my daily email ( http://bits.owocki.com/8591b5ad5be0/Screen%20Shot%202019-01-10%20at%202.25.46%20PM.png ) today.

**Comment by thelostone-mc** [comment]
@owocki this is being tracked here https://github.com/gitcoinco/web/issues/3502
