### ISSUE TITLE
discuss: reserve bounties

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#3502]
##### Description 

13 Jan 2k19

Steps:
- create a new state `reserved`
- update front end & email template to ensure reserved bounty show up only for the reserved user 

-----
11 Jan 2k19
Reserve bounties are now live. 
Testing it out with @vs77bb , the follow suggestions came up

> A mail should be triggered when reserved person starts work to notify funder.
 
My concerns:  
Normally when a user starts work -> an email is triggered anyways, so would be need to build another email on top of that? would we be spamming the funder?

> When a bounty is reserved for a user. The bounty should not be in Open state

- Leaving it open state is confusing as the issue is techinally open only for the reserved user 
- If we were to shift it to work started -> it would essentially give the freedom to the funder to force a task upon a reserved bounty hunter. The hunter needs the freedom to deny the request and work on what ever he pleases (consider scenario if he's working on 2 issues . and the 3rd issue is reserved for him , he won't be able to start work on another issue which he is keen on )

In my head We can leave it as it is / we can create a new state.

**Comment by mul1sh** [comment]
> ##### Description
> Reserve bounties are now live.
> Testing it out with @vs77bb , the follow suggestions came up
> 
> > A mail should be triggered when reserved person starts work to notify funder.
> 
> My concerns:
> Normally when a user starts work -> an email is triggered anyways, so would be need to build another email on top of that? would we be spamming the funder?
> 
> > When a bounty is reserved for a user. The bounty should not be in Open state
> 
> * Leaving it open state is confusing as the issue is techinally open only for the reserved user
> * If we were to shift it to work started -> it would essentially give the freedom to the funder to force a task upon a reserved bounty hunter. The hunter needs the freedom to deny the request and work on what ever he pleases (consider scenario if he's working on 2 issues . and the 3rd issue is reserved for him , he won't be able to start work on another issue which he is keen on )
> 
> In my head We can leave it as it is / we can create a new state.

@thelostone-mc @vs77bb I think we should work on moving a bounty from the `open` state to `started` if a bounty is reserved and then after 72 hours, if the reserved for user hasn't started working on the bounty, then it can be moved back to the `open` state. We can do this by auto-starting the bounty once the web3 transaction has reflected so that the funder also gets a notification email about it.

Also I agree no need to send another email `when reserved person starts work to notify funder.` the one email they get once the bounty has been auto-started should be enough.

**Comment by thelostone-mc** [comment]
@mul1sh 

```
vivek [15 hours ago]

my first impressions:

- since it’s reserved, it should be in ‘Work Started’ - not ‘Open’


thelostone-mc [15 hours ago]
Work hasn't been started yet !
Cause it's only been reserved ! What if I never accept it cause I find something more attractive ? 

Assume I'm working on 2 issues and you force this upon me this preventing me from taking up a 3rd issue ( for the 72 hours ) :P


vivek [14 hours ago]
> Assume I’m working on 2 issues and you force this upon me this preventing me from taking up a 3rd issue :P

agree it shouldn’t count to your issue limit. but I don’t think it should be in ‘open’, because other gitcoiner’s technically can’t click start work on it until you make a decision
```

The downside of this is that I can create three bounties and reserve them for you and you won't be able to start work on other bounties you want cause I've forced you to start work on this (cause of the bounty limit). You could go and click stop work but in the activity feed it would like you started an issue and backed out of it (aka creating a bad impression of a funder who happens to check out the issue )

**Comment by mul1sh** [comment]
@thelostone-mc makes sense, how about if the reserved bounty is left in open but then hidden from other bounty hunters and anyone else who is not logged in the `issue explorer`. So that on logging into gitcoin only the `reserved for` user will be able to see it along with other bounties. But if they don't start work in 72 hours they are automatically removed from the bounty and then it's made open to other gitcoin users

**Comment by thelostone-mc** [comment]
Seems a lil hacky but that would work :P 
cc @SaptakS / @octavioamu / @vs77bb

**Comment by octavioamu** [comment]
I also thought about the idea of just show the bounty to the one/ones is reserved for. This is good to private repos (future feature)  
For other side maybe we need to add a state "reserved" and having an option to show to everyone or just for the reserved hunters. Anyway I think having the a new state "reserved" also to handle in the front end side will be the best. 
What you guys think?

**Comment by thelostone-mc** [comment]
@mul1sh / @pinkiebell  would you be up for, I'd be happy to set up a bounty

More info over at https://github.com/gitcoinco/web/issues/3497

Steps: 
- create a new state reserved
- update front end and email template to show reserved bounty to the reserved user only 

cc @owocki
