### ISSUE TITLE
SUBTASK #3114: UX A User Adding/Editing Job Related Information to Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3506]
### Subtask of 3114: UX A User Adding/Editing Job Related Information to Gitcoin

Please see original ticket.
https://github.com/gitcoinco/web/issues/3114
https://github.com/gitcoinco/web/issues/3382

### Definition of Done

- [ ] Designs are created for the necessary experience in the above linked tickets.
- [ ] Review with Green squad and finalize designs before sprint end.

**Comment by willsputra** [comment]
Adding job-related information on contributor onboarding:

Default:
![jobs_default](https://user-images.githubusercontent.com/19514207/51220223-4fa83a00-196f-11e9-977b-f9300214bc29.png)

Dropdown expanded:
![jobs_dropdownexpanded](https://user-images.githubusercontent.com/19514207/51220224-5171fd80-196f-11e9-8016-a9c930699498.png)

Thoughts? @PixelantDesign @octavioamu @SaptakS 

I’ll explore where I can put the other details (type of work, region, compensation) and also where to fit it in the profile today.

**Comment by SaptakS** [comment]
@willsputra looks good to me.

**Comment by willsputra** [comment]
how it looks like in Manage Settings...

![jobs-edit](https://user-images.githubusercontent.com/19514207/51324648-39e96080-1aa6-11e9-8d49-d38c2671852d.png)

and in Profile

![job-profile](https://user-images.githubusercontent.com/19514207/51324646-3950ca00-1aa6-11e9-8b66-e71a09856140.png)

question: should we put type of work, region, and compensation in the onboarding flow too? @PixelantDesign

**Comment by owocki** [comment]
Yes those requirements are captured in these tickets

https://github.com/gitcoinco/web/issues/3382
https://github.com/gitcoinco/web/issues/3525

Maybe we should fold them into one UI?
