### ISSUE TITLE
As a Gitcoin admin, Google Search Console is indexing gitcoin.co, but there are still some unresolved errors. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3511]
### User Story

As a Gitcoin admin, Google Search Console is indexing gitcoin.co, but there are still some unresolved errors. 

### Why Is this Needed

This will improve Gitcoin's SEO and searchability.

### Description

https://search.google.com/search-console/index?resource_id=https%3A%2F%2Fgitcoin.co%2F&hl=en 

The Google Search Console (formerly Google Webmaster Tools) offers the best diagnostics and performance data from Google about gitcoin.co. The problem is, there are still website errors that appear and we would like to triage these issues and see if there is an automated way to reduce the errors.

Marc Beharry has stated to "not go crazy" trying to reduce the absolute number of errors to 0 because gitcoin.co has _alot_ of pages. It's normal to have some errors.

@frankchen07 to define sub-tasks for this ticket and sit down with the search console, will need to grant access to search console?

### Error Priorities
1. Click on red error category - 5xx server level errors
2. Click on red error category - 404 level errors
3. Google is having an issue with the sitemap.
4. All the pages its excluding (35k) - pretty much have to click into them and figure out why each one is causing errors (private profiles)
5. Once 1-3 have been dealt with, adding keywords and adding paragraphs in certain areas of the site to improve SEO can help.

### Expected Behavior

1. Better SEO for gitcoin.co

### Definition of Done

1. Marc Beharry to better inform what quantitative moves in metrics would mean "better SEO."

**Comment by mbeharry** [comment]
It may not be possible to eliminate all errors but should try to kill some of them.
