### ISSUE TITLE
DESIGN - As a Gitcoin Core member, I want funder feedback and impressions on the Gitcoin pricing sheet.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3516]
Sub-task of https://github.com/gitcoinco/web/issues/3471

### User Story

As a Gitcoin Core member, I want funder feedback and impressions on the Gitcoin pricing sheet. As it stands, the current pricing sheet is being updated by @PixelantDesign.

### Why Is this Needed

As we test our revenue options, we would like an initial read on what funders think about a Gitcoin pricing scheme, and how that fits into their usage of Gitcoin.

### Description

The old pricing sheet: ![group 3](https://user-images.githubusercontent.com/513929/50389018-5aa9da80-06e1-11e9-8e6f-fa62d04888e0.png)

The new pricing sheet is currently in progress with updates.

### Current Behavior

Old pricing sheet design. 

### Expected Behavior

New pricing sheet design.

### Definition of Done

1. Design of the prototype for user testing
2. Script is written for both new and current customers.

**Comment by PixelantDesign** [comment]
*Pricing Flow Prototype*
- Please note this is not final visual design. This will be used to accompany the pricing interview.
- There are two flows, a path where a funder uses form fields for payment and the other option has no form fields. Please click the big blue buttons to get started on each flow and follow the hot spots.
- Only the GREEN Middle path is wired up.
- There are a few tour points and comments already, to see those go to comment view.
https://invis.io/F9PXH5BUHWB#/340389019_Gitcoin_Pricing_Flows

*Pricing Interview Script - DRAFT*
https://docs.google.com/document/d/1MyNh1-jgq-GVNNVXxjjRnw9idzrSEjRgg-Db2lkw0HI/edit?usp=sharing
