### ISSUE TITLE
Gitcoin Grants Vetted by Gitcoin Badge

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3520]
As a grantee I want a cool badge that I can display on my site that says to potential contributors that my project ior idea is legit and has been vetted by the Gitcoin core team.

This will encourage funding of projects on the gitcoin grants site.

Badge will be displayed on the grant itself on gitcoin grants site.

Badge can also be displayed on the grant owners site —- driving traffic to gitcoin grants. 

This means core team will need a checklist and ambassadors could help review grants.

will flesh out more when at computer

**Comment by thelostone-mc** [comment]
I like this

**Comment by captnseagraves** [comment]
@PixelantDesign I like this idea. It sounds like it will introduce a 'review' flow. Basically anyone can create a grant, but only they and the Gitcoin team will be able to see it until Gitcoin reviews and either approves, rejects, or asks for modifications. Was this part of what you were envisioning?

**Comment by frankchen07** [comment]
I think it's a great revenue test. It also may address an issue of "not enough documentation or guidance" that we've been hearing from contributors. The concept reminds me of LinkedIn examples of "100% profile complete = more people seeing your profile," so if you have Gitcoin vetting your projects, it gets more visibility.

My concerns is that this introduces us into a consulting / review (like seagraves said) role, which is a side-off? slightly different? indirect? to "push a button get a coder." Also, does that mean Gitcoin is deep diving into the technical details to ensure tasks are clear, or is it more at high level? Maybe it gets rolled up into a service, but still worth discussing how to set up an initial test on this to gauge interest.
