### ISSUE TITLE
Private Grant Funding

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#3530]
We should allow people to drop in private funding for a grant without their github or any other profile being publically visible. 

I think if we could add a new button next to "Fund the Grant" that is "Privately Contribute" or something like that we could increase funding!

**Comment by owocki** [comment]
@austintgriffith you said this customer would want to have their grant be anonymous right?  how much in funding is attached to this request? (this will help us prioritize)  would it be acceptable if they disclosed their identity to us, and we just hid the info?  or does it need to be actually anonymous to gitcoin?

cc @PixelantDesign @frankchen07

**Comment by bmann** [comment]
Yes, +1 to this. I would write it another way -- how can I, as a grant owner, give contributors an address where one time grants or direct grants that don't go through the Gitcoin front end appear?

Right now -- I can give people the multisig wallet address where the funds are flowing to, but then it doesn't show on the front end. 

I want to use Gitcoin Grants as my turnkey "fund this project" front end.
