### ISSUE TITLE
discuss: grant home page [ filtering ]

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#3539]
#### Description

When we open grant to public, we may have individuals coming over and creating a grant for themselves. If we end up having a lot of grants being created , would the A grade grants be pushed down?

#### Potential solutions 

- Create tagging experience for grants. This would make it easier to search 
- Do we classify grants into buckets? ( Based on org/individual, verified/unverfied )
- On the grant homepage -> show diff sections to display diff kinds of grants 
  a. New Grants 
  b. Most popular
  c. Grants which have almost met their goal ( Just a few more DAI and you can help them stay alive )
- Evaluate multiseg wallet (not relevant but just putting it out there )

cc @ceresstation  @owocki @captnseagraves @PixelantDesign

**Comment by owocki** [comment]
i like the tagging direction

**Comment by ceresstation** [comment]
+1 on the tagging direction, can the idea of categorizing grants by 'grant manager' (e.g. consensys grants) live here?
