### ISSUE TITLE
sitemaps upgrade 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3543]
**Describe the bug**

Add missing urls to sitemap
- grants (each) #3090
- labs each link
- wagtail #3268

**Comment by thelostone-mc** [comment]
Fixed at https://github.com/gitcoinco/web/pull/3541

**Comment by octavioamu** [comment]
@thelostone-mc notice I just fixed somethings and created this task for the missings things we need to do in the sitemaps . I will reopen it maybe good for bounty.

**Comment by thelostone-mc** [comment]
Part of this is addressed https://github.com/gitcoinco/web/pull/3138
@kuhnchris would you up for adding the sitemap for labs + wagtail into your PR ?
