### ISSUE TITLE
BUILD New Gitcoin.co  Home Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3545]
### User Story
As a current or potential funder, I'd like to have an understanding of Gitcoin's product offerings and how it can help my workflow.

As a current or potential contributor, I'd like to have an understanding of Gitcoin's product offereings and see where I can contribute or find work on this platform.

### Problem to be Solved
Our current homepage isn't representative of our product offerings. We'd like to replace the Gitcoin.co  homepage with one that talks about our entire product suite.

### Definition of Done

- [ ] Build new homepage as designed
- [ ] The page is responsive
- [ ] Videos should display in standard modal used on the site, please check with @thelostone-mc or @SaptakS on appropriate style reference.
- [ ] Work with @PixelantDesign on parallax funnel animation:
         Parallax animation starts at the top and as user scrolls down but it stops at the 10x info above the  
         blue section that introduces the products.
- [ ] Test the page across different browsers
- [ ] Pass all tests prior to merge to codebase

### Metric
- Increase X% of MPV per participant over time.
- % of active funders before & after
- Brand awareness

### Reference
Sketch file will be provided.
![new- home page](https://user-images.githubusercontent.com/238235/52418515-369d2f80-2abc-11e9-8302-f21399556c15.jpg)

from https://github.com/gitcoinco/web/issues/3327, some leveragable video collateral:

https://youtu.be/i2JKN_6iuiw - how do you define sustainability?
https://youtu.be/Y5Ef-fse23Y - how do you define sustainability?
https://youtu.be/b6LSf-zQnlI - what's currently broken about open source sustainability?
https://youtu.be/oe7oD8ThKx8 - what does a world with open source sustainability look like?

**Comment by frankchen07** [comment]
Two items of clarification needed on this ticket: 

1. @PixelantDesign - what should go in place of the `Loreum Ipsum` on the beginning of the homepage?
2. Added some video collateral to be used in the build at the bottom.

**Comment by thelostone-mc** [comment]
Clarifications from my side 

1. Sketch file
2. Where does `Get in touch` lead to ?
3. Where does `Our Values` lead to ?
4. Where does `more about press` lead to ?
5. Where does `See how our products are growing open source` to? 
6. Realign open source incentive: where does the link `Learn More` lead to ?
7. Link to gitcoin medium article

Preferably link to all the clickable elements on the screen so that there is not confusion

**Comment by thelostone-mc** [comment]
Calling out steps I'd be taking while building this out iteratively which could span more than a sprint

- create base homepage (sketch needed)
- create nav bar (sketch needed)
- talk it out with core team + marketing on how SEO would take a hit if we were to shift the bounties URL to `gitcoin
- update the URLs

**Comment by frankchen07** [comment]
[Homepage_Revamp_012519.zip](https://github.com/gitcoinco/web/files/2796890/Homepage_Revamp_012519.zip)

**Comment by PixelantDesign** [comment]
@thelostone-mc 

Where does Get in touch lead to ? Founders email
Where does Our Values lead to ? Current Mission Page
Where does more about press lead to?
a page with press info...you can remove the link for right now if you want since we dont have a design.
Where does See how our products are growing open source to? Products page
Realign open source incentive: where does the link Learn More lead to ? Results page
Link to gitcoin medium article

**Comment by PixelantDesign** [comment]
Yes @thelostone-mc has the file.

So on the green funnel at the top it'll stay the same, when user scrolls towards the bottom we'd change up the numbers to show how Gitcoin addresses the funnel....did I miss a comment @owocki ?
