### ISSUE TITLE
BUILD Update Gitcoin.co Nav

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3546]
### User Story
As a funder I want to have simple navigation choices presented so that I can find what I'm looking for on Gitcoin.

As a contributor, I want to be able to navigate my way around the site without feeling overwhelmed at the options.

### Problem to be Solved
Currently there are a lot of nav items, wed like to group them and provide less choices for a user navigating their way through our site.

### Definition of Done

- [ ] Build the navigation
- [ ] Ensure it is responsive
- [ ] Review with Gitcoin core team

### Reference
![nav changes](https://user-images.githubusercontent.com/238235/50486043-f11e1a80-09c5-11e9-9fe3-01b363542fa9.jpg)

**Comment by Anish-Agnihotri** [comment]
Are we keeping the same design for the mobile menu (since responsiveness is important)? Just wondering since there wasn't a revised/attached design for that.

![mobile](https://user-images.githubusercontent.com/4398624/51295347-3346e480-19e5-11e9-9843-e6e2e01220b6.JPG)
