### ISSUE TITLE
bug: crowdfund contribution not received

### ISSUE THREAD

**Issue by usmanmuhd** [gitcoinco/web#3556]
There were 2 crowdfunding on the bounty. The error in first crowdfunding was pointed out in #3549 . @PixelantDesign paid out the bounty. I did not receive the 2nd crowdfunding as well.
Gitcoin Issue: https://gitcoin.co/issue/gitcoinco/web/2404/1415

**Comment by owocki** [comment]
looking at our backend, crowdfund distributions are sent out every 8 hours. let me run this job real quick

**Comment by usmanmuhd** [comment]
Yes, thanks for the payout. I did not know that crowdfunds were paid out every 8 hours. @PixelantDesign told me to open an issue, so I did :)
