### ISSUE TITLE
As a founder, I'd like to fork StandardBoutnies and add revenue features, so I can make $$, so I can sustain Gitcoin

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3557]
### Outstanding Questions / Strategy

btw the fees involves 3 steps  - 
1. enabling Gitcoin to support multiple contracts (Aditya)
2. getting the new contract
3. wiring it up (Aditya)

@frankchen07 to confirm strategic discussion.

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a founder, I'd like to fork StandardBoutnies and add revenue features, so I can make $$ , so I can sustain Gitcoin

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Integrating Platform fees into Standard Bounties allows us to make revenue.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Premium Features available on Gitcoin

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
When a user posts a bounty, depending upon their configuration, they will have
- Pay Gitcoin a 10% fee (this fee percentage should be configurable)
- If they are a subscriber, pay Gitcoin no Fee.
- If they are posting a bounty that is for a private repo, pay Gitcoin a fee. (fee amount should be configurable) - if lean test plays out (oracle setup will be needed to check on private repo status).
- If they are posting a featured bounty, pay Gitcoin a fee. (fee amount should be configurable)

The user should only have to submit ONE tx to metamask in order to pay these fee amounts.

Technical considerations:
- Update Standardbounties to support new fee architecture
- Update Standardbounties tests to support new fee architecture
- Throughout the frontend/backend, we will have to support *n* standard bounties smart contracts, instead of just the 1 we support now.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above

### Additional Information
related: https://github.com/gitcoinco/web/issues/959

**Comment by owocki** [comment]
Related to https://github.com/gitcoinco/web/issues/3510

**Comment by thelostone-mc** [comment]
Closing this out and we ended up going with another metamask popup 
as discussed [here](https://gist.github.com/thelostone-mc/dd89b2824f1c5243fd256a902bb2b29b)
