### ISSUE TITLE
Issuing Kudos without unlocked metamask

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#3568]
**Describe the bug**
I have a very soft warning on the top bar that indicates I need to unlock metamask. As a user I missed this and filled out all fields, then on unlocking I loose all entered data. 

**To Reproduce**
https://gitcoin.co/kudos/send/ 
Just don't unlock metamask

**Expected behavior**
Before I can do anything, I should be strongly prompted to unlock metamask
OR
On unlock the fields populated remain.

**Comment by NukeManDan** [comment]
Other pages that need a submission might also have this? I have not tried yet.

**Comment by octavioamu** [comment]
In general I would recommend just don't refresh the page, metamask have listener so when access is given check the eth address and all needed data without reload the page.

**Comment by NukeManDan** [comment]
The page automatically reloads. I am using Brave Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit) on Ubuntu.
