### ISSUE TITLE
Sent Kudos to github user not on gitcoin, now it is not shown.

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#3569]
**Describe the bug**
Sent a kuos in tx: https://etherscan.io/tx/0xe4a93002937a30a905b00698fc7cc400caa31a2f750f0764f0a98f56120c7b09

**Screenshots**
Sent from me (https://gitcoin.co/profile/@nukemandan) to https://gitcoin.co/profile/@csillabrimer

![image](https://user-images.githubusercontent.com/35669742/51420123-e8e07780-1b4c-11e9-86fa-736d2e6f01d4.png)

But her profile does _not_ show the kudos. She has received no notification. 

I did not put in the optional email under `advanced options`

**Desktop (please complete the following information):**

- OS: Linux MATE 
- Browser Brave
- Browser Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by NukeManDan** [comment]
She signed up on gitcoin after I set it.

**Comment by octavioamu** [comment]
@csillabrimer please check if you got "claim kudos" button in the dropdown
![image](https://user-images.githubusercontent.com/1358093/51430373-b5abf000-1c01-11e9-86c9-d666d5db6375.png)

**Comment by NukeManDan** [comment]
@csillabrimer Looks like it worked!

**Comment by NukeManDan** [comment]
I don't see it on your profile actually @csillabrimer

**Comment by owocki** [comment]
https://gitcoin.co/profile/csillabrimer

try now!

**Comment by owocki** [comment]
we should keep this issue open tho; need to fix the root cause
