### ISSUE TITLE
Some images not uploading for Gitcoin Grants

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3570]
**Describe the bug**

In some cases image uploads are failing on Gitcoin Grants. For example, POA tried to upload an image for this grant https://gitcoin.co/grants/35/blockscout-blockchain-explorer-for-inspecting-and but the default image still displays.

**To Reproduce**

Create a grant and upload any jpg image, in the case above it was a ~450 x 350 image as shown below.

https://gyazo.com/9bf4c0260434b7a93d8e0280b6ba224d

**Expected behavior**

Images upload and are displayed on each grant unless the max file size is exceeded (and are ideally adjusted to fit into the space available).

**Comment by thelostone-mc** [comment]
Unable to add Grant logos during creaation :

```
usecase : `grant/new`
issue: when you add a grant image and submit -> the logo doesn't get saved
why : cause we haven't added it to the ajax request 

@captnseagraves since we are sending a file -> we'll  have to convert it to form data and send it via ajax but I had some issues with it when I gave it a shot

Input field in html : https://github.com/gitcoinco/web/blob/master/app/grants/templates/grants/new.html#L112

Where is it to be added while submitting the form
https://github.com/gitcoinco/web/blob/master/app/assets/v2/js/grants/new.js#L85-L99

the server logic : https://github.com/gitcoinco/web/blob/master/app/grants/views.py#L203
```
