### ISSUE TITLE
As a Gitcoin admin, there are parts of the Wyre documentation that need clarification in preparation for the integration workshopping session.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3580]
### User Story

As a Gitcoin admin, there are parts of the Wyre documentation that need clarification in preparation for the integration workshopping session.

### Why Is this Needed

Getting a deeper

Implementing Wyre forms the foundation for two things to happen on Gitcoin: KYC AML and connection to fiat.

1. Bounty hunters can get paid out in fiat.
2. Bounty funders can pay their bounties in fiat and still end up with a bounty in DAI.
3. (Future) KYC / AML for grant payment.

**Who cares?**

1. _Enterprises_ don’t want to deal with the accounting for magic internet money.
2. _Foundations_ often have AML / KYC rules to follow around grants / donations.
3. _Developers_ outside of Web3 don’t necessarily believe in the ecosystem but still want to support OSS.

Also, legal recommends it.

### Description

Gitcoin has QQs about Wyre integration.

New documentation: https://wyre-beta.readme.io/docs/

And a basic demo: https://s3-us-west-2.amazonaws.com/demo.sendwyre.com/index.html

### Current Behavior

Open questions about the documentation.

### Expected Behavior

Understanding the documentation.

### Definition of Done

- [ ] be able to intelligently discuss the advantages and drawbacks from a technical perspective on a Wyre integration into Gitcoin's product suite

**Comment by thelostone-mc** [comment]
###### Overview 

Wyre  (what it can do )
- wire transfer 
- mass international payout
- virtual banking service 


###### Flow 

- Gitcoin would register themselves on WYRE
- Gitcoin maintains USD float on Wyre (which is topped on a weekly basis based on txn )

<img width="605" alt="screen shot 2019-01-25 at 12 41 29 pm" src="https://user-images.githubusercontent.com/5358146/51730725-98ae6b80-209e-11e9-8326-d123f866ed6e.png">


A lifecycle with our integration would typically look like
 
![whatsapp image 2019-01-25 at 12 37 30 pm](https://user-images.githubusercontent.com/5358146/51730694-803e5100-209e-11e9-97f2-9188f6e9fa94.jpeg)

**Comment by danlipert** [comment]
Looks like the `/v2/bankinfo/:country` is only for China and Brazil. US and AUS look like any bank is supported. 

Note that some US states are not supported: [https://support.sendwyre.com/security/non-operational-states-in-us-and-countries](https://support.sendwyre.com/security/non-operational-states-in-us-and-countries).

All in all, the Wyre v2 API looks very nice and easy to work with. What sort of questions do folks have regarding this integration?

**Comment by thelostone-mc** [comment]
@danlipert 
- Is the id returned from `/v2/transfers` the same as `transferId` ?
- I'm still unclear on how KYC fits into this picture. (as mentioned in the ticket )
Like would only gitcoin have to KYC verfied / every user on gitcoin using this service (would they would have to create an account ) ?


@frankchen07 @ceresstation 
Not relevant but curious 
- At any point would they also add changing tokens to fiat?

**Comment by danlipert** [comment]
@thelostone-mc Yes, each person who wants to either use the onramp or offramp has to go through Wyre's KYC process. It's not too bad actually, probably the nicest I've seen in all the KYC products I've worked with in terms of UX, but it is still KYC so there are many steps (scanning IDs, entering sensitive social security info, etc.) Thankfully, the end result is that Wyre sends the user's address a token that identifies them as having gone through the KYC approval process so we don't need to store any of that information, we can just check to see if they are a token holder (I think this is adequate, we're not getting becoming an MSB or anything...) The banking integration is actually done by Stripe.

The `transferId` returned in the `POST` to `/v2/transfers/` is the ID we'll use in all the other requests :+1:
