### ISSUE TITLE
SUBTASK #3476 Move Metamask UX New Metamask Placement

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3584]
https://github.com/gitcoinco/web/issues/3476

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I'd like to authorize with Github (only) and provide a MetaMask account / ETH address when I 'Submit Work', so I don't have an extra barrier to creating an account until I'm ready to complete a bounty.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We want to make it as easy as possible for individuals to join Gitcoin. Let's allow folks to 'Start Work' without needed a MetaMask account. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Require a MetaMask account to create a Gitcoin profile. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Do not require a MetaMask account. 

### Definition of Done

- [ ] Ux take content from metamask step and move to submit step. (2pt)

### Metrics To Track
- Does this meaningful increase our user acquisition / CAC?

**Comment by willsputra** [comment]
adding this here too from #3476
![move metamask flow](https://user-images.githubusercontent.com/238235/51606275-73bfca00-1edf-11e9-8d56-23e4ae2d3538.jpg)

todo: adjust the content of submit step to match flow

**Comment by willsputra** [comment]
If you click on 'Submit Work' without MetaMask installed, this would pop up.
@PixelantDesign thoughts?

![metamask on submit](https://user-images.githubusercontent.com/19514207/51750717-e0101880-20ed-11e9-9e92-8bafa5837541.jpg)
