### ISSUE TITLE
Contributor plan in the "request to work" email

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3589]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a founder I want to know the contributor plan in the request email so I don't need to go to the issue comments to find it

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Because is hard to go to the issue comments and find the text the contributor wrote, sometimes if the bot fails you can't read it (https://github.com/gitcoinco/web/issues/3014 here I will never know what the second contributor wrote). And also funders not necessary will know this "plan" exist and maybe don't read it in the bot comments.  

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

![image](https://user-images.githubusercontent.com/1358093/51558009-8d243000-1e65-11e9-86bb-5b60b4869b6b.png)

### Current Behavior
[comment]: # (Describe what actually happened.)
I don't receive the plan in the email and I need to go find it in the issue.

![image](https://user-images.githubusercontent.com/1358093/51558099-c0ff5580-1e65-11e9-9a0f-023ac80e367f.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Have an area in the email with the text the user wrote.

**Comment by kziemianek** [comment]
![image](https://user-images.githubusercontent.com/1838338/51990756-fe896180-24a9-11e9-9626-b5bb31186c38.png)

**Comment by octavioamu** [comment]
@kziemianek you rock!
