### ISSUE TITLE
BUILD - As a Gitcoin user, I want a pricing sheet, so I can see how to take full advantage of Gitcoin.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3593]
### User Story

As a Gitcoin user, I want a pricing sheet, so I can see how to take full advantage of Gitcoin.

### Why Is this Needed

This page explains all our revenue options in one place. 

### Description

We can build the initial design right now as a skeleton start, and modify it in the future with incoming funder feedback. This way, we iterate proactively, and not wait until we have perfect information to start the pricing page.

### Current Behavior

No pricing sheet.

### Expected Behavior

1. Remove existing pricing sheet from gitcoin.co.
2. Have the new pricing sheet on a development branch (NO PROD LAUNCH) at gitcoin.co/pricing:

Invision link: https://projects.invisionapp.com/share/42PZCI9CUXB#/340972484_User_Test_-_Home

![pricing_am](https://user-images.githubusercontent.com/238235/50674652-481f8300-0fb6-11e9-865f-32bbedb87c3e.png)

3. Design discussion will continue on https://github.com/gitcoinco/web/issues/3289

### Definition of Done

* Main pricing page on a development branch of `/pricing`.
* Page works and is responsive.
* Selection of a plan leads to a grant payment page for plan payment with information about plan pricing pre-filled. (scope reverted back to full pricing flow, before backend changes 2019-02-05)

**Comment by PixelantDesign** [comment]
Should we build just the one page or the entire experience?

**Comment by thelostone-mc** [comment]
@frankchen07 + @PixelantDesign moving forward could we ensure the sketch file is attached wherever applicable

**Comment by frankchen07** [comment]
> moving forward could we ensure the sketch file is attached wherever applicable 

yes definitely - thanks for the callout!

> Also, I'm moving forward under the assumption that this task has only thing page to be built and nothing else

yes, the task is to build the pages based on the sketches, but no deployment yet. Pricing is part of a larger epic, but having the foundation for the page laid out will reduce future cycles and holdups.

**Comment by PixelantDesign** [comment]
I'll be updating this design

**Comment by owocki** [comment]
> I'll be updating this design based on feedback received.

excited for the next rev on this :) do you have any idea of what youre doing for the new pricing page?  my biggest asks for the next rev of the page:

1. it should be simpler to understand
2. it should be compelling (if i'm in the target user flow, it should be a no brainer, i should want to "pull out my credit card" )

 happy to jam.

**Comment by frankchen07** [comment]
@thelostone-mc [Gitcoin.PRicing_02012019.zip](https://github.com/gitcoinco/web/files/2823447/Gitcoin.PRicing_02012019.zip)

Designs are also at: https://github.com/gitcoinco/web/issues/3289

**Comment by danlipert** [comment]
@frankchen07 @PixelantDesign Just wanted to drop a note here about our brief discussion in our sprint planning call regarding potential "per-seat" pricing for enterprise, and how that can tie into future development of organizations and having multiple employees from the same team manage a bounty together.

**Comment by thelostone-mc** [comment]
Closing this out as the PR has been merged in for the frontend for the page 🙌
