### ISSUE TITLE
Error when accessing with Mist 0.9.2

### ISSUE THREAD

**Issue by phal0r** [gitcoinco/web#36]
When authorizing gitcoin.co with Mist I get the following errors:

```
Uncaught Error: TrackJS Caught: Cannot read property 'coinbase' of undefined
at get_search_URI (dashboard.js:64)
```

```
Uncaught Error: TrackJS Caught: Cannot read property 'accounts' of undefined
 at shared.js:296
```

Gitcoin wants to access the eth object in web3, but it is undefined. This is due to the way web3 is provided. Mist offers a basic web3 object with the currentProvider set to Ethereum Provider.

According to the Ethereum wiki (https://github.com/ethereum/wiki/wiki/JavaScript-API) this is the recommended way to init web3:

```javascript
if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
}
```

I would expect gitcoin to include a packaged version of web3.js and instanciate it in the above mentioned way to support Mist.

**Comment by owocki** [comment]
i mostly use chrome / metamask.  i need to add geth to the regression testing list.

**Comment by PixelantDesign** [comment]
@mbeacom do we still need this issue?
