### ISSUE TITLE
Bounty extension event is shown as unknown type in recent activity section

### ISSUE THREAD

**Issue by anshumanv** [gitcoinco/web#3600]
**Describe the bug**
Bounty extension event is shown as unknown type in the recent activity on gitcoin section.

**To Reproduce**
Checkout recent activity section, if there's an event of bounty extension

**Expected behavior**
It should display bounty deadline extended.

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/51629685-3e15f200-1f6e-11e9-8249-c5d7f6d671da.png)
![image](https://user-images.githubusercontent.com/21009455/51629713-4cfca480-1f6e-11e9-8ce8-125bf88b6180.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.2 18C54 x86_64
- Browser Chrome
- Browser Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by owocki** [comment]
thanks -- i may bounty this :)
