### ISSUE TITLE
as a founder, i want all digital good purchases to be captured in the `revenue.digitalgoodpurchase` table, so i can account for htem

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3607]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a founder, i want all digital good purchases to be captured in the `revenue.digitalgoodpurchase` table, so i can account for htem

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
because we need to book this as revenue

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
not tracked

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
track
- kudos purchases (but only if they are minted by gitcoin)
- premium bounty purchases
- all other digital good purchases

in `revenue.digitalgoodpurchase`

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Is this still needed @SaptakS ?
