### ISSUE TITLE
performance issue -- activity.view_props takes too long to load

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3610]
there is a performance issue in kudos/views.py -- activity.view_props takes too long to load.

cb762195ef6aa00213f074f88830c5241554aab8 is a stopgap.  

but i propose that that we put in a long term fix in which `view_props` is stored in the DB as a `JSONField`.  and it should be loaded on save / update.  not on read.

**Comment by owocki** [comment]
anyone object if i bounty this?

**Comment by frankchen07** [comment]
@owocki did you get around to bounty-ing this? if not, I can help do it for you, just wanted to make sure there's enough to go off of on the ticket

**Comment by owocki** [comment]
i actually coded it last deep work day :) https://github.com/gitcoinco/web/pull/3640
