### ISSUE TITLE
Gitcoin Grant images don't display properly

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3614]
**Describe the bug**

The image in most grants e.g. https://gitcoin.co/grants/36/molochdao displays as intended in the thumbnail but not in the main image.

**To Reproduce**

Upload an image of any size to a grant.

**Expected behavior**

Images are fit to the window size or users are given the option to adjust images on the fly within a grant edit view (as suggested by @austingriffith)

Note that this is slightly different than #3570, images are uploading but just not displaying correctly.

**Comment by owocki** [comment]
three options i see.
1. make it so we only support images of a certain aspect ratio
2. build into the admin an ability to modify the CSS of the grant image such that background-size can be cover,contain, etc.
3. build in support for some sort of cropping mechanism

@thelostone-mc @PixelantDesign

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/commit/df3ccbf47db19f29f2e5667eabe5ffddf92ce6a8
https://github.com/gitcoinco/web/commit/c56844495a4ff61df41b4d0103531788d8597750
https://github.com/gitcoinco/web/commit/b0f6dab051273d5cb164f27c5356573e74139e37

should help
