### ISSUE TITLE
UX: when work has been submitted and I have reviewed the work on github there should be a big RELEASE FUNDS call-to-action button 

### ISSUE THREAD

**Issue by SCBuergel** [gitcoinco/web#3625]
As a novice funder for an issue, it is currently easy to get lost in the UI. I recommend that you show me a big call-to-action button for the most relevant flow (happy path) of releasing the funds. There are currently about 6 or more buttons which I have to choose from.

**Comment by PixelantDesign** [comment]
Thanks for reporting @SCBuergel ! We're in the process of cleaning up the buttons!
