### ISSUE TITLE
bug - daily emails dont actually match keywords in profile

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3629]
https://gitcoin.co/profile/zherring

This user has reported that the daily emails he gets giving him bug bounties to work on do not actually fit his profile.

**Comment by owocki** [comment]
@zherring mind screencapping the email and describing whats wrong pls?

**Comment by zherring** [comment]
1. Current profile
![screen shot 2019-01-30 at 11 38 43 am](https://user-images.githubusercontent.com/2172549/52004140-adff0d80-2483-11e9-8bcd-f9d4f08b0c84.png)

Most Recent Email re: Bounties that Match My Profile
![screen shot 2019-01-30 at 11 35 56 am](https://user-images.githubusercontent.com/2172549/52004164-b9523900-2483-11e9-98a7-ad1b964107a4.png)
![screen shot 2019-01-30 at 11 35 27 am](https://user-images.githubusercontent.com/2172549/52004172-c1aa7400-2483-11e9-9993-95c93e6dd0f1.png)
![screen shot 2019-01-30 at 11 35 24 am](https://user-images.githubusercontent.com/2172549/52004184-c707be80-2483-11e9-9fc0-518f5d52bbf9.png)

¯\_(ツ)_/¯

**Comment by owocki** [comment]
9db7c23f781e8d7adbd62908f7db9190efc1c9f2
