### ISSUE TITLE
Submit button still active for done task

### ISSUE THREAD

**Issue by iamonuwa** [gitcoinco/web#3630]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.) A task I submitted was marked as done but the task submit button is still available for me.

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
See https://gitcoin.co/issue/ethsociety/learn-plasma/125/2099 and https://github.com/ethsociety/learn-plasma/issues/125#issuecomment-455521576

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.) The submit button should not be available for done tasks

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/6551094/51870299-709b6280-2353-11e9-9f3a-0e766be6dfb5.png)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by PixelantDesign** [comment]
thanks for the report @iamonuwa !
