### ISSUE TITLE
User's issueLimit is decreasing

### ISSUE THREAD

**Issue by nanspro** [gitcoinco/web#3631]
**Describe the bug**
[comment]: # (Funder marked the issue on gitcoin as done after paying worker but worker forgot to "Stop Work" so the issue will still be counted in ongoing issues for user. For contributors who have initial limit as 3 get affected hugely by this bug)

**To Reproduce**
[comment]: # (Do not click on "Stop Work" after submitting work and wait for the funder to mark as done, issueLimit decreased.)

**Expected behavior**
[comment]: # (Either when a funder marks the issue as done then the issue should get removed from ongoing issues of user **OR** we can just keep the stop work button on the issue even after it is showing work done.)

**Screenshots**
[comment]: # 
![screenshot from 2019-01-29 04-31-28](https://user-images.githubusercontent.com/24641089/51872274-dbae5e80-237e-11e9-860e-f3d9a8dc4af6.png)
 

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by PixelantDesign** [comment]
thanks for the report @nanspro !
