### ISSUE TITLE
after i fund a gitcoin grant, i want to tweet about it, so i can show off my support of OSS

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3634]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
after i fund (or create) a gitcoin grant, i want to tweet about it, so i can show off my support of OSS

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
virality, showing off

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no tweeting of kudos

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
after i fund (or create) a gitcoin grant, i can tweet about it

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Could we reuse the sharing modal that @octavioamu built last sprint?
