### ISSUE TITLE
Aesthetic for bounty hunter confirmations

### ISSUE THREAD

**Issue by FirefighterBlu3** [gitcoinco/web#3641]
**Describe the bug**
During the starting work page on a bounty, the bounty hunter is asked to check off some things such as 'i understand that this bounty is ...' and 'i agree to keep the funder informed ...'. The current CSS style for checkboxes allows them to be functionally invisible under certain circumstances. This can lead to frustration from being unable to continue as there don't appear to be any boxes needing checked.

In the below images there is one that is a direct screenshot from a utility and one from my phone showing the invisibility as viewed at an angle. The only graphic postprocessing has been cropping for size. I've checked the lower box to show the complete difference. Faint grey colors of things are stylistically minimal but the caveat is that they blend away very easily with polarized screens.

I recommend a box shadow of a slightly different color or darker gray shade so that the minimalist grey theme can be retained however the polarization blend will still give a visual indication for the checkbox element. The CSS should also make the checkboxes to be fixed width dimensions.

**To Reproduce**
*Start Work* on a bounty and tilt or look at your screen at an angle (vertical or horizontal shifts) such as if you might be avoiding reflections or glare from sunlight or bright lights.

The light gray of the confirmation checkboxes becomes invisible due to the refraction incidence with your screen's polarization filter making the very thin light grey border blend into the hue of the screen.
Additionally, when not checked, the boxes become very thin.

**Expected behavior**
The checkboxes ought to a) always be recognizable and b) of static dimensions

**Screenshots**
![image](https://user-images.githubusercontent.com/3165044/52015695-87a39700-24b0-11e9-9dec-6e40d8e86f71.png)
![image](https://user-images.githubusercontent.com/3165044/52016112-b5d5a680-24b1-11e9-89fe-89f805ce58ee.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Chrome
- Browser Version 72.0.3626.53 official build 64b

**Smartphone (please complete the following information):**
n/a

**Comment by PixelantDesign** [comment]
Thanks for the report @FirefighterBlu3 !
