### ISSUE TITLE
As a designer making avatar contributions, I dont want to repeatedly resolve conflicts with app/avatar/utils.py

### ISSUE THREAD

**Issue by emiwatanabe422** [gitcoinco/web#3645]
### User Story

As a designer making avatar contributions, I dont want to repeatedly resolve conflicts with app/avatar/utils.py. The configuration in utils.py needs to be removed and cleaned up, so that there is one item per line, and submissions should conform to a consistent and predefined formatting.

### Why Is this Needed

Lower friction to avatar submissions means more high quality avatars

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature.  Clean up app/avatars/utils.py

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
hmm maybe the solution here is moving the avatar builder to be DB-backed.

i know that @kuhnchris was excited about this for a bit.. but id ont know where we landed!

**Comment by kuhnchris** [comment]
hey there kevin! Actually I analyzed the current state and the avatar-history guy did a pretty good job regarding cleaning up all of the avatar stuff. The only thing we ought to change is add front/back colors and recoloring, then it should work. We could also then offer to create the avatars on db, which would also reduce the need to deploy every time we add new avatars.
