### ISSUE TITLE
It's too easy to accidentally create two bounties for the same issue

### ISSUE THREAD

**Issue by lucasvo** [gitcoinco/web#3646]
It's too easy to accidentally create two bounties with the same github issue. I don't remember the precise steps to reproduce as I wasn't even aware of this until I went to our gitcoin profile today to see that there suddenly were two. Unfortunately I have no other information but I am 100% certain that I only filled out the form once, I might have hit submit twice after an error occurred or I let ledger prompt timeout.

https://gitcoin.co/issue/centrifuge/go-centrifuge/438/2234
https://gitcoin.co/issue/centrifuge/go-centrifuge/438/2235

**Comment by PixelantDesign** [comment]
Thanks for letting us know @lucasvo. Any ideas you'd like to see to help prevent this?
