### ISSUE TITLE
29 Person Bounty Remittance Kinda just fell apart at person 18

### ISSUE THREAD

**Issue by lrgeoemtry** [gitcoinco/web#3655]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
I had this bounty <https://gitcoin.co/issue/HERCone/HIPR/6/2116> 
29 people joined and i wanted to remit at the end of it 
i had to type in all the names individually (no big deal but UX could be better) 
and then calculate the split % of all of them (no big deal but UX could be better)

I got to about 15th person (30 txs)  and then it kinda just stopped serving me txs to sign 
it showed me where in the list i was which was cool, but i couldn't remove the people I already paid cuz the list box covered the x's 
so i just put 0s

i then was able to start going back down the list by pressing the Pay Bounty button (now the second time) and got through 6 tx (now the 18th person) before Metamask just kicked me out (i had to reinput my password) 

the 6 new transactions were pending for awhile so i decided to refresh the page and the bounty remittance 404'd 

I went back to the bounty explorer and it said the Work was done and i couldn't pay out the bounty. 

I think this has something to do with trying to "spam" my MM client with what was then 36 transactions in a matter of 4ish minutes. 

theres about 480 HERC tokens locked in the contract now from what i can tell. 

Quick UX fix would to not allow more than 15 people to join a bounty. 
Long term fix is an airdrop contract for many parties (which i thought was going to happen) this will reduce gas and provide a better UX. 

I've added photos to show my struggle.  
**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
do a bounty with 15+ people 
try and pay them

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
do a bounty with 15+ people 
pay them with no problems

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)
https://ton.twitter.com/1.1/ton/data/dm/1091133009875619844/1091133003160530950/7R1TR_RV.jpg:large
https://ton.twitter.com/1.1/ton/data/dm/1091133519219355652/1091133509903835137/FOl_CNEE.jpg:large

https://ton.twitter.com/1.1/ton/data/dm/1091135114216652805/1091135106037755904/IDZehHgY.jpg:large
https://ton.twitter.com/1.1/ton/data/dm/1091135144365342724/1091135135406280706/QQi2Psot.jpg:large
https://ton.twitter.com/1.1/ton/data/dm/1091135387408519177/1091135379930054661/qu1vgOOq.jpg:large

https://ton.twitter.com/1.1/ton/data/dm/1091135891316322309/1091135882458030080/CnAiMSCd.jpg:large
**Desktop (please complete the following information):**

- OS: macosx mojave
- Browser chrome w metamask
- Browser Version uptodate chrome & mm 

hope this helps @owocki  <3 we do have an airdrop to multiple parties contract we're working on. its not perfect but it could be the solution. ill let you know when its finished.

**Comment by owocki** [comment]
thanks for letting us know @lrgeoemtry  

i have noticed that metamask will stop serving popup windows after you create a couple, and you need to click in the top right to find the metamask confirmation window.  do you know if this is what happened, or if it just stopped sending confirmation windows altogether?

note: that issue is tracked here https://github.com/MetaMask/metamask-extension/issues/3759

**Comment by lrgeoemtry** [comment]
stopped sending confirmation windows all together 
def tho the UX for 15+ bounty hunters needs to be worked on
like i said quick fix would to just not let more than 15 accept while the long term fix is tinkered with. 

we're working on an ENS EIP for PGP style metadata privacy on chain at ethdenver but maybe this could be something to build out?

**Comment by kuhnchris** [comment]
Well, one possibility is that we make "5-confirmation-blocks", e.a. confirm 5 at a time and then have the user click "confirm next payouts", as a 'quick and dirty fix'
