### ISSUE TITLE
500 error when trying to fund vipnode grant

### ISSUE THREAD

**Issue by john-light** [gitcoinco/web#3658]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

I am trying to fund the vipnode grant and get this error message:

```
Error 500.

Even the bots aren't sure what happened, but we'll look into it.
```

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

1. Go to vipnode grant page https://gitcoin.co/grants/32/vipnode/fund
2. Try to fund grant, 5 DAI per 30 days repeating 6 times
3. Notice error message after clicking "Contribute to grant"

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

I expect to sign transactions, completing my subscription to the grant.

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser: Firefox
- Browser Version: 65.0

**Comment by john-light** [comment]
>  5 DAI per 30 days repeating 6 times

Those exact values. I entered the exact same for a couple of other grants and it worked, it's only on the vipnode grant page that I had an issue.

**Comment by owocki** [comment]
@john-light i just put in a fix.  pls try now! 

for any future maintaineres who are interested in my spelunking.. what happened was that the grant deployment tx was dropped and replaced.. so the contract address that was in the database (which resulted from the deploy tx) was in valid.
