### ISSUE TITLE
grants - if deploy tx is dropped and replaced, then the grants.contraact_address is null, and this causes funding of a grant to fail

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3665]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
grants - if deploy tx is dropped and replaced, then the grants.contraact_address is null, and this causes funding of a grant to fail

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
1. deploy a grant
2. tx that deploys it should be dropped and replaced
3. smart contract gets created, but the system can't find it
4. 500 when you try to fund the grant

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
when you deploy a grant with a tx that is replaced, the system should recognize this, and find the correct contract address

**Additional context**
**Smartphone (Add any other context about the problem here.)
https://github.com/gitcoinco/web/issues/3658
this happened with both this grant
https://gitcoin.co/_administrationgrants/grant/32/change/
and this grant
https://gitcoin.co/_administrationgrants/grant/40/change/

**Comment by kuhnchris** [comment]
Well, do we get those informations when we have our own geth? I sadly have no idea how the "dropped & replace" workflow works within ethereum, so I cannot tell you if this helps in any ways. What I do know is that we use infura for all blockchain communications, so I assume there were some drawbacks like having to host your own geth, which wouldn't really be that bad tbh. especially if we write ourselves a thin-layer that simply stores away the events from the blockchain if they are "within our vicinity", e.a. contracts with certain metadata, txid that affect standradbounty contract, and stuff like that. You think that may be a viable option for a thin-node + middle layer?

**Comment by danlipert** [comment]
We might get that info from our own node - it depends on if the dropped transaction ever makes it to our node or not. If the replacement txn is issued quickly thereafter, other nodes may not pass it to us. I suppose even etherscan may have an incomplete history depending on how the replaced transaction propagates (I'm 80% confident thats how the txn replacement mechanism works). Definitely running our own Ethereum node + caching service can help with this, as we can tune it to look for specific contracts/addresses/transactions.

**Comment by owocki** [comment]
this happened to  https://gitcoin.co/_administrationgrants/grant/47/change/ also 

> Well, I'm just thinking forward - if the deployment TX is dropped, how do we ever find out what the contract ID is

inspect the payload back from web3 when checking for the tx result.  if there is a replacement tx, then recursively inspect that payload for that tx result

**Comment by owocki** [comment]
for my future self: here is how to query for these grants

```
from grants.models import Grant
In [7]: Grant.objects.filter(contract_address='0x0')
```

**Comment by kuhnchris** [comment]
> for my future self: here is how to query for these grants
> 
> ```
> from grants.models import Grant
> In [7]: Grant.objects.filter(contract_address='0x0')
> ```

As a quick workaround: create a mail template that checks for that daily/hourly and send you a mail if a contract_address=0x0 grant is created?

**Comment by danlipert** [comment]
This issue will be fixed by this PR: https://github.com/gitcoinco/web/pull/3735 which tracks the re-issuance of grant contract creation transactions correctly.
