### ISSUE TITLE
Featured bounties have wrong bounty value

### ISSUE THREAD

**Issue by anshumanv** [gitcoinco/web#3667]
**Describe the bug**
Ether value of featured bounties is less.

**To Reproduce**
Goto explorer and see featured bounties

**Expected behavior**
Correct ether value as shown in the bounty page

**Screenshots**
Wrong value in ether
![image](https://user-images.githubusercontent.com/21009455/52192899-550fea80-2872-11e9-9533-97ddb0eb2088.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser Chrome
- Browser Version 71.0.3578.98

**Comment by anshumanv** [comment]
Hardcoded here - https://github.com/gitcoinco/web/blob/127eee1adceddda0350e495f049bc756ffb83e68/app/retail/templates/shared/featured_bounty_cards.html#L9

I should be able to fix it. 🎉

**Comment by PixelantDesign** [comment]
Thanks for the report! I'll tip for the fix!

**Comment by PixelantDesign** [comment]
@octavioamu please review!

**Comment by anshumanv** [comment]
Sending a fix for it!

**Comment by octavioamu** [comment]
Sorry @anshumanv I didn't know you were working on this.

**Comment by anshumanv** [comment]
Ah! No worries @octavioamu 😄

**Comment by octavioamu** [comment]
Anyway, good catch @anshumanv ! we missed that

**Comment by anshumanv** [comment]
Fixed in https://github.com/gitcoinco/web/pull/3669 🎉
