### ISSUE TITLE
As a developer, I want to remove unused Javascript libraries so that software erosion and vulnerabilities don't slow down development

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#3668]
### User Story

As a developer, I want to remove unused Javascript libraries so that software erosion and vulnerabilities don't slow down development.)

### Why Is this Needed

*Summary*: The current repo contains a large amount of Javascript libraries, which will trigger things like automated CVE alerts on github. These Javascript libraries are generally not used, as they were part of a previously done attempted webpack integration. While leaving these in doesn't necessarily hurt the application, it does slow down developers in terms of focus, especially new developers.

### Description

*Type*: Feature

### Current Behavior
Many extraneous JS libraries referenced in repo

### Expected Behavior
Only JS libraries that are actually used in the project should be referenced

### Definition of Done
All references to unused JS libraries should be removed

### Additional Information
Here's a potential list of extra unused libraries:
```
"devDependencies": {
    "babel": "^6.23.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.6",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-html": "^4.0.6",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "stylelint": "^8.4.0",
    "stylelint-config-recommended": "^2.1.0",
    "stylelint-webpack-plugin": "^0.9.0",
    "webpack": "^3.12.0",
    "webpack-bundle-tracker": "^0.3.0",
    "webpack-dev-server": "^2.11.3"
  } 
```

The above list has not been confirmed as extraneous, as we do use linting tools as part of our test process. The person that tackles this issue should determine which of these dependencies are actually required for our processes.

**Comment by kuhnchris** [comment]
I think those dependencies are pretty much dead, also, they are just dev dependencies. I suspect these are due to minifying the javascript, but I have no idea if it is in the current workflow embedded.
Maybe check the Makefile?

**Comment by octavioamu** [comment]
The only time I found that we run `npm install` is in `.travis` and after that looks like only 2 of that list are used :
```
"eslint": "^4.19.1",
"stylelint": "^8.4.0",
```
So I think we can just remove the others without issues. 
extract from travis:
```
      # Install Node and Python dependencies.
        - npm install
        - pip install -r requirements/test.txt
        - npm run eslint
        - npm run stylelint
        - pytest -p no:ethereum
```
