### ISSUE TITLE
as a grants user, i want an embedded way to transfer my ETH into DAI/WETH/other so i can easily donate to a grant

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3673]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grants user, i want an embedded way to transfer my ETH into DAI/WETH/other so i can easily donate to a grant

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
beylin requested it

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
must go to oasis dex to trasnfer to DAI 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
can inline trasnfer my tokens to DAI / WETH / other

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
https://github.com/gitcoinco/web/issues/3412
https://github.com/gitcoinco/web/issues/3389

**Comment by kuhnchris** [comment]
OasisDex is dead, I think you mean Eth2Dai?

https://medium.com/makerdao/a-new-oasis-5b9539a64adf
