### ISSUE TITLE
Guide into web3

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3688]
Design a page to explain in a beauty and easy way to users how to get started with web3 in gitcoin.
Use this issue as guide of contents https://github.com/gitcoinco/gitcoinco/issues/4 in a simple way for users experiencing their first time in a Dapp. 

Focus in primary informations (start fast)  but also give the user the option of obtain more informations about web3 world (etherscan, why blockchain, gas, etc)

The objective of this page is to be a simple guide for those starting into gitcoin with not previous idea what is metamask. Needs to answer HOW, WHAT and WHY  and mean to be focus in both funders and contributors.

**Comment by kuhnchris** [comment]
So... maybe a video? or a gif? or a webm animation?
That may also tie in to the ShapeShift/FIAT integration, as this would make the flow easier for new-comers. 
Basically something like this? http://ethdocs.org/en/latest/introduction/web3.html

**Comment by thelostone-mc** [comment]
@octavioamu -> could we evaluate if this can fit into an existing page as opposed to spawning new pages for everything
