### ISSUE TITLE
Optimize dynamic avatar service

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#3691]
### Who

Dynamic avatar service.

Is unreliable.

1. gives 503 errors
2. returns full size images instead of downscaled icons
3. not monitored 

Error rate would look unixporn on gitcoin.co pages. Service could be a fork of shields.io backend.

### What 

https://gitcoin.co/profile/gitcoinco

![image](https://user-images.githubusercontent.com/8781107/52319109-003ab400-29d9-11e9-885f-c35359e25a53.png)

### Why

#3685

**Comment by kuhnchris** [comment]
well, that comes from the fact that we actually have a @ratelimit in place for avatars, d'oh. 
actually-actually those avatars should be generated once and then be served from S3, but I suppose something is fucked once again. @danlipert can we create a tech-debt ticket to check all the S3 assets that are currently in use by gitcoin and/or take a look at it?
I think @owocki had a ticket open that the s3 costs were exploding, maybe that's connected?
A short-term solution would be to increase the rate limit, or to check sentry. 
@owocki / @PixelantDesign did someone take over the Sentry logging checking that Mark was doing previously?

**Comment by abitrolly** [comment]
Gitcoin should have a doc like this - https://github.com/badges/shields/blob/master/doc/production-hosting.md - explaining how various parts are connected and how to deploy them.

**Comment by owocki** [comment]
try now https://gitcoin.co/profile/gitcoinco -- i just tweaked the rate limit

i agree we should explain the production host better.  both to the community and to the rest of the team :)

**Comment by abitrolly** [comment]
`shields.io` is in public domain and can be copied as a template.

https://gitcoin.co/profile/gitcoinco loads slow - it needs caching or offload to CDN.
