### ISSUE TITLE
(test issue) as a user, i want to foo the bar, so i can have success in business and in life.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3695]
THIS IS A TEST ISSUE! You may start work on it, just for fun, but don't expect to actually work on it!

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to foo the bar, so i can have success in business and in life.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
to have success in life and business.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no fooing of the bar

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
fooing of the bar

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
the bar is able to be foo'd

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
this is a test issue.  don't expect to actually work on it!

**Comment by kuhnchris** [comment]
any particular reason why you not create a separate repository for that?

**Comment by owocki** [comment]
good call next time i will
