### ISSUE TITLE
as an engineer, i'd like to move our infrastructure off kubernetes, because there's no one internally who has the desire/skills to manage it, and there is risk to that part of our infrastructre being unmanaged

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3711]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as an engineer, i'd like to move our infrastructure off kubernetes, because there's no one internally who has the desire/skills to manage it, and there is risk to that part of our infrastructre being unmanaged

### Why Is this Needed

IPFS.gitcoin.co went down yesterday, and since there hadn't been a knoweldge transfer about BOTH kube clusters... no one was able to manage it.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
we're on kube

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
1. migrate IPFS
2. migrate sentry
3. migrate metabase

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
http://discourse.metabase.com/t/copy-dashboards-and-questions-from-one-server-to-another/2739

**Comment by kuhnchris** [comment]
Well, it depends on what you guys use the kubenets for.
You could use a docker swarm, especially if you have multiple server.
It's kind of a religion question, I guess. Mark really loved helm-charts and kubernetes, but I think noone in the team currently has the knowledge using that, correct?

It also depends on what 'servers' you use, are those full boxes or just k8-nodes, etc.
if they are normal AWS instances, you can go with docker swarm aswell.

short read reference:
https://thenewstack.io/kubernetes-vs-docker-swarm-whats-the-difference/

would require either side-by-side deployment and cut-over, or, some down time. I suspect side-by-side and cut-over seems to be the way to go, if you want a seemless transition. Preferably at weekend.

**Comment by owocki** [comment]
> It's kind of a religion question, I guess. Mark really loved helm-charts and kubernetes, but I think noone in the team currently has the knowledge using that, correct?

right

**Comment by kuhnchris** [comment]
Well, as I said, we CAN rewrite it to docker swarm, but it would also need to change the productive servers.
Currently I have *no* clue how the current prod environment is setup. As far as I know, at least k8, correct?
