### ISSUE TITLE
Clicking "Submit" multiple times quickly while applying for a bounty will make multiple entries appear in the activity list

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#3715]
**Describe the bug**
Clicking the Submit button quickly when submitting an action plan for a bounty results in multiple entries in the activity list.

**To Reproduce**
Quickly click submit when applying for a bounty

**Expected behavior**
It shouldn't be possible to apply for the same bounty multiple times.

**Screenshots**
![screen shot 2019-02-10 at 11 58 09 pm](https://user-images.githubusercontent.com/869266/52535308-186f5200-2d90-11e9-8b5e-549746ca8ec6.png)
<img width="896" alt="screen shot 2019-02-10 at 2 04 23 pm" src="https://user-images.githubusercontent.com/869266/52535310-21f8ba00-2d90-11e9-8a9c-764028fa3a7c.png">

**Additional context**
First noticed by Animesh Gaitonde in the community slack, was able to replicate on local installation.

**Comment by wanseob** [comment]
@danlipert How do you think about adding a `unique_together` option into the Meta class of the "Interest" model?? 

https://docs.djangoproject.com/en/2.1/ref/models/options/#unique-together

**Comment by danlipert** [comment]
@wanseob nice! probably a good solution, thanks for the tip!
