### ISSUE TITLE
As a contributor, I don't want 'applying for work' to be counted towards my Issue Limit

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3729]
### User Story

As a contributor, I don't want 'applying for work' to be counted towards my Issue Limit

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently, applying for work (or expressing interest) on a Permissioned ('Approval Required') bounty is counted towards the Issue Limit. This means if the issue funder never approves the contributor or chooses another contributor, it's still counted towards the Issue Limit unless the contributor explicitly clicks on 'Stop Work'.

### Current Behavior
[comment]: # (Describe what actually happened.)
Applying for work on a Permissioned ('Approval Required') bounty is counted towards the Issue Limit.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Applying for work on a Permissioned ('Approval Required') bounty should not be counted towards the Issue Limit.

A contributor should be able to apply to as many bounties, but once they've been approved for 3, they shouldn’t be able to get approved for more.

### Definition of Done

• Applying for work on a Permissioned ('Approval Required') bounty should not be counted towards the Issue Limit. Contributor should be allowed to apply to more than 3 bounties.
• Once the contributor has been approved for 3 bounties, they shouldn’t be able to get approved for more.
• Review with core team

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Related: https://github.com/gitcoinco/web/issues/3157

**Comment by kuhnchris** [comment]
well, that only would shift the responsibility to the bounty creator, instead of the guy expressing interest. 

If the guy who wants to apply gets the message he can't since he has more than 3, then only that guy is disappointed. But what happens if someone is despiratly looking for someone working on their bounty, just to see someone apply, hitting "approve" and then get the info "that guy currently has too many bounties he's working on, try later"...
