### ISSUE TITLE
Grant subscription creation costs slightly more than the amount shown to pay for metatx

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#3736]
### Outstanding Questions

@frankchen07 to set up a discussion with austin + dan + aditya + owocki related to security on this issue. Who is funding the subminer?

### User Story

As a grant subscriber, I want to pay the exact amount I'm contributing (continuation of temporary fix for issue #3653)

### Why Is this Needed

The metatx relayer requires a small amount of additional tokens to relay the transaction (I think...)

### Description

- right now, when it fails, owocki drops 0.1 dai into wallet (line of defense 1)
- right now, owocki made it so that one-time transactions, it bypasses the subminer (superfluous b/c subminer is subscriptions, defense 2)
- solutions
    + subminer fee can be configurable, and the fee is taken out of the subscription
    + the attack vector already exists (charge a small percentage fee on grant contributions)
    + in the subminer, we can make it so that anyone who is not a admin that submits a fee below a threshold or a minute/hour cadence, we just error out
- next course of action for dan is
    + set gas price to 0
    + run a check on cadence
- longer-term fix will be coupled with revenue options
    + fix most likely will solutionize the configurable subminer fee, where the fee is taken out of the subscription

### Current Behavior
Example: a 50 DAI subscription costs 50.000001

### Expected Behavior
A 50 DAI subscription should cost 50 DAI

### Definition of Done
The amount entered by the user is the amount shown in the transaction

### Additional Information
I believe we can just configure the metatx relayer to charge 0? @owocki @austintgriffith

**Comment by kuhnchris** [comment]
alternative: instead of having to pay that fee (which essentially it is), you could ask for 1 DAI or 0.5 DAI when the user funds his first grant, so we have enough 'spare dai' to push those metatx?
