### ISSUE TITLE
Contributor Landing Page Updates

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3749]
### User Story

As a marketer, I'd like to have the ability to customize certain sections fo the contributor landing page so that it is more robust and has enough info to engage/entice that audience.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Contributor landing pages are limited now.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Dean to come up with draft update of contributor landing pages.
- [ ] Design the updates
- [ ] Update/add on to contributor landing pages with recommendations from Dean
- [ ] Review with the marketing team

### Reference
[Dean's Google Doc](https://docs.google.com/document/d/1UvG4uJIUrTRkeDXVvaTkq_bVO3ZoccaQIH-19bxrZCg/edit?usp=sharing)

**Comment by willsputra** [comment]
draft. yellow boxes = placeholders for illustrations.
![contributor landing page](https://user-images.githubusercontent.com/19514207/53742418-8ad8db00-3ed3-11e9-95ff-0cba020446f5.jpg)

**Comment by mbeharry** [comment]
I am loving it.  Just made a quick update to Dean's doc.  Want to make the major sub-titles H2 or H3:

<h2>Available Python Freelance Programming Jobs - Click One to Start Contributing!
(List of open bounties)


<h2>Recent Activity on Our Python Programming Issues
(list of activities) but make them smaller



<h2>How It Works - Python Contributors / Coders Seeking Jobs
(keep the same format)

**Comment by deanramadan** [comment]
Looks great! In addition to what Marc wrote, the only thing I'd change is the Open Python Bounties button, change to "Browse Python Bounties", and I'd get rid of the How it Works so the Browse Python Bounties is the only CTA button

**Comment by willsputra** [comment]
@mbeharry @deanramadan updated! added the illustrations too
cc @PixelantDesign 

![contributor landing page](https://user-images.githubusercontent.com/19514207/53750733-8f0df400-3ee5-11e9-94ae-cc0c616468ac.jpg)

**Comment by deanramadan** [comment]
Love it!

**Comment by mbeharry** [comment]
Hi All,

I added a final batch of tags to the doc.  

First are the meta tags which should change depending on the bounty type:
Title Tags: Freelance <Python> Development Jobs & Bug Bounties. Complete Remotely & Get Paid in Crypto - Gitcoin
Meta Description Tags: Open bug bounties & software development jobs in <Python> for remote workers. Get paid in Crypto immediately. Make money while building our resume and GitHub profile. Work on top projects with  industry experts.   

Then made some comments in the doc about text that should be used for IMG ALT's.  Let me know if you have any questions: https://docs.google.com/document/d/1UvG4uJIUrTRkeDXVvaTkq_bVO3ZoccaQIH-19bxrZCg/edit

**Comment by mbeharry** [comment]
<"Python"> should be replaced for the other similar pages.

**Comment by PixelantDesign** [comment]
Looks great @willsputra ! Thanks for the input @deanramadan and @mbeharry !
