### ISSUE TITLE
Design -Press Page to Gitcoin.co

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3750]
### User Story

As a prospect, I'd like to be able to see in a central location all the press that Gitcion has.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We currently have a press bar on the home page with links.
If we had a page on the site it would be better for SEO.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Determine where Press page would live in the new nav
- [ ] Get content /confirm IA with Marc Beharry
- [ ] Design a Press Page
- [ ] Build Press Page
- [ ] Review with the Marketing team

**Comment by mbeharry** [comment]
Here is the format I was thinking of....

<Press Page Template>
H1: Press & Media Coverage

H2: Recent Press
Interview with Kevin Owocki at Software Engineering Daily: https://softwareengineeringdaily.com/2018/04/03/gitcoin-open-source-bounties-with-kevin-owocki/

H2: Press Releases
<link to any press releases we did>

H2: Social Mentions
<embed or link to tweets from Vitalik>

H2: Recent Videos
<embed recent YouTube vids>


<CTA Button 1>Join the Newsletter
<CTA Button 1>Find Freelance Coders
<CTA Button 1>Find Freelance Bug Bounties


For design inspiration check out;
https://app.crayon.co/f/press-page/
http://liveeditorcms.com/inside/playbook/press-pages/
