### ISSUE TITLE
Make it Clear When Bounty is Cancelled Crowdfunding Turns Into a Tip

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3753]
**Describe the problem**
Funder cancelled a bounty. When Eth is returned. Crowdfunding turns into a Tip.

**To Reproduce**
Create a Bounty and add crowdfunding. Cancel the bounty and see that a claim tip menu item shows up in your profile.

**Expected behavior**
User is noted that any Crowdfunded amount is returned via Tip and that they'll need to go to a drop down menu to claim it.

**Issue**
https://gitcoin.co/issue/saurfang/spark-sas7bdat/38/1394

**Workshopping**
- What is a more clear way to handle/message this?
- Users expect some communication as to where the rest of the crowdfunding is sent.
- Users do not expect it to be changed to a Tip.
- This also needs to be documented somewhere
- A notificatio/emailn would also be helpful per user comment below.

### Definition of Done

- [ ] Propose a ux/message that explains that is happening to users crowdfunding.
- [ ] Review with core team

### Metric

- For bounties in cancelled status with a crowdfund (ensure that there are no complaints from funders via emails/slack).

**Comment by owocki** [comment]
@PixelantDesign when @saurfang logs in, they will see a claim tip link in the top right to get the returned crowdfund amount

**Comment by saurfang** [comment]
Ooooh! I never noticed that. It's in my profile dropdown. Nice. I recovered all the funding. Thanks for the quick turnaround.

**Comment by PixelantDesign** [comment]
Thanks @owocki!

Glad you recovered the funds @saurfang. Yes! I've updated this ticket to make it more clear what happens to the funds. We will also need to document this somewhere.

**Comment by willsputra** [comment]
first place to inform the funder would probably be the Cancel Bounty form. what do you think? @PixelantDesign 

![cancel bounty crowdfund tip](https://user-images.githubusercontent.com/19514207/53181243-2c3d7280-3632-11e9-85ed-8be3960cdc3a.jpg)

**Comment by Anish-Agnihotri** [comment]
@willsputra That looks incredible actually. If you've got the SVG of the image (the purple image to the right side), or a sketch/xd/design file, I'd be happy to add it in right now to the cancellation form.

**Comment by willsputra** [comment]
@Anish-Agnihotri here ya go!
https://github.com/gitcoinco/creative/commit/db5616fcae243104cf0c6e43171a048a4fe40ef9

**Comment by Anish-Agnihotri** [comment]
Will knock this out tonight.

**Comment by Anish-Agnihotri** [comment]
^ Just pushed out the changes!

**Comment by PixelantDesign** [comment]
Thank you this looks great! Could we review @octavioamu @SaptakS ?

**Comment by PixelantDesign** [comment]
Is there anyway to reword that text in the drop down menu to not call it a tip? @Anish-Agnihotri @willsputra

**Comment by Anish-Agnihotri** [comment]
I have the sketch file from @willsputra so I should be able to do it. What do you want it to say?

**Comment by PixelantDesign** [comment]
For Refunds to crowdfunding, in the profile menu,  could you change the language of Claim Tip to Claim Refund?
I think in general it's weird that it goes into the profile menu....it should go to the notifications so users know that they have a refund to claim. What do you think?

**Comment by Anish-Agnihotri** [comment]
Yeah, I think it is a bit weird that the notification goes to the profile menu instead of the notifications menu. 

Just to clarify, do you want me to change the text of the image on the cancel bounty page to 'Claim Refund' and the text copy to 'Claim Refund', or do you want me to literally change the profile menu dropdown to read Claim Refund when killing a bounty?

**Comment by willsputra** [comment]
@Anish-Agnihotri cc @PixelantDesign 

It would be great if we could change the profile menu to read Claim Refund too, although that might cause some confusion if people are also using the menu to actually claim a tip...

I wonder if it's possible to separate claim tip and claim refund functionalities? 🧐

**Comment by Anish-Agnihotri** [comment]
Sure, I can take a look and see if there is a way to separate the functionalities, although I'm not positive that it's possible.

If it is though, I'll throw it in. Otherwise, I'll change the SVG text, unless, you have any additional ideas?

**Comment by willsputra** [comment]
@Anish-Agnihotri if it's not possible to separate the functionalities, we can keep the SVG text "Claim Tip" since we won't have a "Claim Refund" button yet 🙂
