### ISSUE TITLE
Gitcoin.co/how/contributor "good for" duplicated or does't make sense 

### ISSUE THREAD

**Issue by joshmorel** [gitcoinco/web#3756]
**Describe the bug**

"Good for" is the same for "Traditional Project" and "Contest Project". I'm pretty sure the description fits with the "Contest Project" not the "Traditional Project". 

Side note: inclusion of "creative," in list on its own doesn't quite read right. Perhaps just get rid of it "Sourcing ideas, searching for the best ways to solve a problem, bug hunt." 

> Traditional Project
> Good For
> 
> Sourcing ideas, creative, searching for the best ways to solve a problem, bug hunt.
> What to Know
> 
> Contest Project
> Good For
> 
> Sourcing ideas, creative, searching for the best ways to solve a problem, bug hunt.

**To Reproduce**
https://gitcoin.co/how/contributor

**Expected behavior**
A description that makes sense for "Traditional Project"

**Comment by PixelantDesign** [comment]
Thanks for the report @joshmorel !
