### ISSUE TITLE
UX Capture Star Ratings for Previously Completed Bounties

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3759]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on previous bounties that they've collaborated on so that we can understand their experience.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Define a Ux and design to solve for the above problem
- [ ] Review with Core team
- [ ] Annotate user experience. 

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
once you rate a bounty, we’ll display a thank you modal and disappear.
![star rating](https://user-images.githubusercontent.com/19514207/53813057-b624fe00-3f97-11e9-89b9-4dd338c4d29c.jpg)
