### ISSUE TITLE
Some Links in Profile Work and Some Don't

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3767]
<img width="554" alt="screen shot 2019-02-18 at 9 26 04 am" src="https://user-images.githubusercontent.com/238235/52957364-80f59a80-335f-11e9-9349-d63d407ae632.png">

![image 30](https://user-images.githubusercontent.com/238235/52957580-fe210f80-335f-11e9-8862-4d9a13b444f5.png)

### Current Behavior
Not all links work

### Expected Behavior
All links are working (see below)

Hello! Just a heads up, the profile links don't work specifically for the contributors (whereas 'Active Subscriptions' and 'Cancelled Subscriptions' profile links do work).
https://gitcoin.co/grants/38/zero-knowledge-podcast (edited) 

### Definition of Done

- [ ] Ensure all links work and link to the relevant information.

**Comment by owocki** [comment]
e19c9bd7fe9371b88a2e52c4d15bcd345f0289b4 fixes this; will be deployed next deployment

**Comment by thelostone-mc** [comment]
@owocki Ah that doesn't fix it up! The handle is not wrapped within a `<a>` tag.
#3828 fixes that
