### ISSUE TITLE
Input field in Send Tip feature should not be colored red

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3768]
**Describe the bug**
Input field and primary color in Send Tip feature is red, which is not consistent with the rest of the site and is normally associated with an error.

<img width="509" alt="screenshot 2019-02-18 at 10 56 49 pm" src="https://user-images.githubusercontent.com/19514207/52959200-9b1b9100-33d0-11e9-9949-a58d10446840.png">

**To Reproduce**
https://gitcoin.co/tip
click Send Ether

**Expected behavior**
Input field and primary color should be blue, consistent with the other pages on the site

**Comment by PixelantDesign** [comment]
@thelostone-mc @SaptakS @octavioamu does this make sense as part of form clean up?

**Comment by Anish-Agnihotri** [comment]
^ I'll submit a PR for this if this is not a part of the form clean up.
