### ISSUE TITLE
DESIGN - Clearer separation of information display

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3770]
### User Story
As different types of users (new vs experienced), I want to see clearer separation between information.

### Current Behavior
Currently, marketing information is interspersed with features, this will distract experienced users. 

Generally, in order to drive the best possible UX experience we strive to separate new users from experienced users and separate features that are frequently used from items that have informational purpose and are only used in the beginning or intermittently.

![screenshot 2019-02-18 23 09 40](https://user-images.githubusercontent.com/19514207/52959860-4d078d00-33d2-11e9-9d30-2328a61744a9.png)

### Expected Behavior
Separation between items should be clearer for:
• new vs experienced users
• frequently used features vs informational, useful for first time only features

### Definition of Done
* [ ]   Explore different ways of separating information and choices to the users
* [ ]  Review with team

**Comment by PixelantDesign** [comment]
@thelostone-mc we have removed the Why Gitcoin when users are authenticated, correct?
I still think How it works is relevant.

**Comment by thelostone-mc** [comment]
Yes but that code hasn't been deployed it but @octavioamu + @owocki had legit concerns about it
