### ISSUE TITLE
DESIGN - Make the illustrations on the Mission page more impactful

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#3771]
### User Story
https://gitcoin.co/mission
As a user, I want the understand Gitcoin's mission clearly through good use of illustrations.

### Current Behavior
Informational blocks are low impact per unit of space occupied.

The sizing of images and illustrations does not correspond well to the size of text. This will likely cause the user to skip the sections altogether and to mistrust the cognitive usefulness of the site as a whole.
 
![screenshot 2019-02-18 23 12 18](https://user-images.githubusercontent.com/19514207/52960158-1d0cb980-33d3-11e9-89b4-7f118fc76a37.png)

### Expected Behavior
Make the illustrations on the Mission page more impactful by figuring out the optimal size of illustrations vs text, and making full use of the available space.

### Definition of Done
* [ ]    Explore different ways of displaying illustrations and text on Mission page
* [ ]   Review with team

**Comment by PixelantDesign** [comment]
@vs77bb we should update this based the last team exercise results around mission.

**Comment by thelostone-mc** [comment]
@willsputra I had thrown in some code to clean up the mission page a lil 
Not sure if it helps but this is how it looks right now. It's still meh but a lil cleaner 

![screencapture-localhost-8000-mission-2019-02-21-15_23_54](https://user-images.githubusercontent.com/5358146/53159893-ced30280-35ec-11e9-9555-b5c7e085576a.png)

**Comment by willsputra** [comment]
@thelostone-mc looks better! :)
