### ISSUE TITLE
Search errors out with locked Metamask

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#3776]
Got an error while trying to open the page with my bounties.

https://gitcoin.co/explorer?bounty_filter=startedByMe&network=mainnet&order_by=-web3_created

![image](https://user-images.githubusercontent.com/8781107/52996959-25471200-3430-11e9-81f4-f38c064150b6.png)

Desktop.

**Comment by thelostone-mc** [comment]
I'm not able to reproduce this.
I tried as a logged in + logged out user and it seemed to work fine. 

<img width="1440" alt="screen shot 2019-02-20 at 12 12 21 am" src="https://user-images.githubusercontent.com/5358146/53039133-709b0800-34a4-11e9-940d-a15a270db81f.png">

**Comment by abitrolly** [comment]
Have you tried adding some pending bounties to your setup? Because I do
have some.
