### ISSUE TITLE
Use Historical Exchange Rate on Invoice

### ISSUE THREAD

**Issue by friedger** [gitcoinco/web#3777]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder, I want to see the exchange rate of ETH (or so) to USD at the date of the invoice, not at the date of printing/viewing the invoice so that I can put the invoice into my financial books.

### Why Is this Needed
Currently, it is unclear which exchange rate for cryptocurrrency to fiat is used.

### Description

*Feature*:

### Current Behavior
As a funder, I have a printed copy of the invoice, when I view the invoice again on the web site the amount differs. It is not clear which exchange rate is used.

### Expected Behavior
As a funder, when I print or view an invoice, I would like to see which exchange rate is used. In particular the rate of which date. The date should be the date of the invoice.

### Definition of Done
This is done when the invoice contains information about the date of the exchange rate.

### Additional Information
In the list of  **Bounties funded** the same rate should be shown.

**Comment by PixelantDesign** [comment]
Agreed! Thanks for opening this ticket!

**Comment by willsputra** [comment]
Hi @friedger, thanks for opening the ticket! Would something like this work? 🙂

![gitcoin invoice](https://user-images.githubusercontent.com/19514207/53355651-71c8ab00-3964-11e9-89c6-6309ec84da61.jpg)

**Comment by PixelantDesign** [comment]
Would something like this work @friedger ?
![53355651-71c8ab00-3964-11e9-89c6-6309ec84da61](https://user-images.githubusercontent.com/238235/54053898-b7804180-41b6-11e9-8eac-6f51fab0a8be.png)

**Comment by friedger** [comment]
Looks good!
