### ISSUE TITLE
As a Gitcoin operator, the way we are counting bounty limits is inaccurate.

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#3782]
### User Story

As a Gitcoin operator, the way we are counting bounty limits is inaccurate.

### Description

Right now, we are limiting number of applications to work to 3 but we're not actually limiting the number of bounties a contributor is actually working on. The idea is to limit the number of bounties a contributor is actively working on and not limit the interest / applications to work.

We can add a new state "start to work" that the contributor needs to press after being approved to work, indicating he or she is really starting to work right now. This gives the contributor the last action to denote to the funder they've actually started work, instead of the funder approving them and "hoping" they get started on it

Contributor: "Declare interest to work"
Funder: "Approves"
Contributor: "Start to work" (_new action_, limit to 3)
_If the contributor tries to start to work the 4th time, they will be presented with a "limited to three tasks" type of warning._

This way, the contributor has the power to control what they work on, and the funder gets a positive response that someone they approved has started work (and didn't just ghost them or come back to them 4 days later and say, "well I haven't started"). Stuck bounties get free faster, contributors won't get approved if they don't really have time to work, and there'll be a tighter feedback loop for the task at hand.

### Definition of Done (stop gap)
- [ ] a design/ui change to handle this

### Definition of Done 
- [ ] ideally, this would be handled with a data model change, as outlined in https://github.com/gitcoinco/web/issues/5102, the tasks are presented below
- [ ] update the data model to include "interested to work" as well as "start to work ("I have started on this work"). "interested to work" and "submitted work" should not count towards the limit of "I have started on this work"
- [ ] contributors will be capped at 3 instances of "start to work", unless the contributor has demonstrated enhanced ability and experience with handling more than 3 instances
- [ ] "interested to work" and "submitted work" will subsequently be uncapped (or have a higher limit than "start to work") to allow bounty hunters to sample an array of issues
- [ ] update the email triggers to reflect the correct email state

### Additional Information
https://gitcoincore.slack.com/archives/CAW05FUD7/p1549979415007000?thread_ts=1549918178.002200&cid=CAW05FUD7

**Comment by octavioamu** [comment]
@danlipert we need some help thinking on the architecture of this so we can estimate.

**Comment by octavioamu** [comment]
Just capturing here a funder complains about current behaviour https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1568389456098900

**Comment by owocki** [comment]
lgtm
