### ISSUE TITLE
As a grants funder, I want to have an aggregate grant I can contribute to, so I can support all OSS.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3784]
### User Story
As a grants funder, I want to have an aggregate grant I can contribute to, so I can support all OSS.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

Because I get decision fatigue when I go to gitcoin.co/grants deciding what OSS to support.

### Description

This is a request from @pipermerriam at ETHDenver.  He wants to contribute XYZ DAI per month to support OSS, and have us automatically distribute amongst all the grantees.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No aggregate funding option

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Aggregate funding option

**Comment by pipermerriam** [comment]
> have us automatically distribute amongst all the grantees.

Or some subset that you or some other decider deems worthy.
