### ISSUE TITLE
As a user, I want a more clear explanation of how data is stored, so I don't get surprised that my email address is out there.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3802]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want a more clear explanation of how data is stored, so I don't get surprised that my email address is out there.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

see convo from community slack:
- http://bits.owocki.com/2b5403f7c5a9/Screen%20Shot%202019-02-21%20at%208.49.31%20AM.png
- http://bits.owocki.com/e82d34dc1b18/Screen%20Shot%202019-02-21%20at%208.49.43%20AM.png
- http://bits.owocki.com/8d37a058750b/Screen%20Shot%202019-02-21%20at%208.49.50%20AM.png

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="1203" alt="slack-imgs" src="https://user-images.githubusercontent.com/513929/53181899-b267a380-35b5-11e9-998e-58938c1f60f5.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Checkbox should 
- make clear that the data is stored in plaintext
- link out to a medium article that is written, as part of this ticket, to explain the history of why we choose to use standard bounties and why interoperability is important.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

**Comment by Anish-Agnihotri** [comment]
Sounds like this could be resolved with some change in copy, potentially a tool-tip, and the medium article to better inform individuals of how their data is being stored?

The copy of the checkbox could change to: 
`
I understand that this information is being submitted as plain text to a public, immutable blockchain. No one, including Gitcoin Core, will be able to take my funds or change this information.
`

We could add a little tool-tip next to the checkbox as well that on hover reveals: 
![interoperability](https://user-images.githubusercontent.com/4398624/53289809-e9ca8180-3768-11e9-9e0f-edb29f68e7dc.JPG)

And the Find out More link could then open the Medium article in a new tab.

If this sounds like what you were thinking, I can go ahead and draft a Medium article about the history of Standard Bounties and the importance of interoperability @Gitcoin and drop it here for review.
