### ISSUE TITLE
bug - grant deploy does not correctly pass txhash to backend, causing blank screen upon grant creation

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3812]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
bug - grant deploy does not correctly pass txhash to backend, causing blank screen upon grant creation

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
we dont know the repro steps, but this happened to a user on windows 10

![image 16](https://user-images.githubusercontent.com/513929/53255832-b6fa8d80-3683-11e9-864e-3f005b892d7c.png)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Grant is deployed and user is taken to that grant.

tracing through the code i think that maybe his grant deployment failed, so we were never able to a transaction id… and it’s just not handling the error case correctly. on line 110 of grants/new.js and on line 38

I also think that grants.views.py:244 should not perform a lookup on the tx_hash if there is no txhash.  thats why he's getting the wrong grant returned (eth2.0 implementers notes)

**Comment by danlipert** [comment]
I tested this on my windows 10 machine and wasn't able to replicate - but I did notice that if you reject the initial transaction and then try it again, this transaction never gets picked up by the page's JS and so the grant is never finalized with the contract address.
