### ISSUE TITLE
The view on github button looks messed up!

### ISSUE THREAD

**Issue by aesthytik** [gitcoinco/web#3815]
![write a comprehensive readme that describes the widgetbot platform widgetbot io funded issue detail gitcoin gitcoin](https://user-images.githubusercontent.com/26917061/53258296-4c346b00-36f2-11e9-91cd-27998adc0a6b.png)

**Describe the bug**
The View on github btn is not flexed

**To Reproduce**
It just visit the bounty page. If comments are more, it will distort

**Expected behavior**
It should be in same line

**Screenshots**
![write a comprehensive readme that describes the widgetbot platform widgetbot io funded issue detail gitcoin gitcoin](https://user-images.githubusercontent.com/26917061/53258478-b9480080-36f2-11e9-94a5-8307e311113b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser Chrome
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by thelostone-mc** [comment]
It has been addressed and the [PR changes](https://github.com/gitcoinco/web/pull/3821) have been thrown in!
Will be fixed once we deploy the greatest and latest.

Thanks for the report man @aesthytik  ^_^
