### ISSUE TITLE
[UI] - Comments count box is breaking at instances 

### ISSUE THREAD

**Issue by anshumanv** [gitcoinco/web#3832]
**Describe the bug**
The GitHub comments count button is breaking at instances.

**To Reproduce**
https://gitcoin.co/issue/Giveth/giveth-dapp/342/2419

**Expected behavior**
It should stay aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/53295347-3bcdde80-381f-11e9-8282-ca912a5dc1b9.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser Chrome
- Browser Version 72.0

**Comment by thelostone-mc** [comment]
@anshumanv thanks for the report ^_^

This has been fixed over at https://github.com/gitcoinco/web/pull/3821.
will be resolved once deploy these changes :)
