### ISSUE TITLE
Unable to add github users who are not signed up to gitcoin as grant team members

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3838]
**Describe the bug**

It's currently only possible to add Gitcoin users to Gitcoin Grant teams

**To Reproduce**

Try adding an arbitrary Github profile to a grant team.

**Expected behavior**

Any github user should be able to join a Gitcoin Grant team as in many cases one team member is responsible for setting up the grant while others may have little to no interaction with Gitcoin.

**Comment by owocki** [comment]
system was not designed to have non-gitcoin users as team memeberes. i think we need to take a deeper look at the DB schema here.

can we safely assume that all team members are at least *github* users?

**Comment by ceresstation** [comment]
Yes we can definitely assume Github users, the challenge is that often only one person from the team will actually handle the process via Gitcoin and the others wouldn't have any reason to create an account. It's not that big a deal for teams with 1-2 people but for teams with 4+ people the coordination cost of getting everyone to sign up can be high.
