### ISSUE TITLE
Text formatting options for Gitcoin Grants pages

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3839]
### User Story

As a funder I would like to be able to add spacing, bolding, and otherwise be able to format text on my Gitcoin Grant page.

### Why Is this Needed

Currently text on Gitcoin Grant pages must be kept to a minimum to avoid creating an unreadable block. Adding spacing and bolding options would make it possible to add more robust descriptions to a given grant.

### Definition of Done

Spacing, bolding, and ideally full markdown support would be available within the Gitcoin Grants description boxes.

**Comment by owocki** [comment]
i vote we use markdown here.  what do you think @danlipert @thelostone-mc @SaptakS @PixelantDesign  ?

**Comment by danlipert** [comment]
Definitely markdown, we can re-use code and keep the input experience unified across the site.

**Comment by ceresstation** [comment]
@PixelantDesign can we prioritize this one? It's relatively low lift right?
