### ISSUE TITLE
DESIGN - As a network operator, I want to properly communicate charging a % fee on a funder for funding a bounty.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3842]
### User Story

DESIGN - As a network operator, I want to properly communicate charging a % fee on a funder for funding a bounty.

### Why Is this Needed

As we roll out revenue tests and charging funders a percentage fee for posting bounties, the messaging and story arc behind this change is very important and should be carefully worded.

This ticket is a placeholder to figure out the content, details, and front-end layout for the messaging.

### Current Behavior

No messaging or storytelling exists. 

### Expected Behavior

Messaging as to how the % fee works, and the Gitcoin story behind it. 

### Workshopping

There needs to be discussion and ideas on two main implementations of the fee message. One, the location of the % fee message on the funder page, and second, the implementation of the actual message itself. There are generally three goals we want to accomplish with the percentage fee.

For location:

![screen shot 2019-02-25 at 09 46 42](https://user-images.githubusercontent.com/7516920/53357252-4e5d1c00-38e2-11e9-9e18-9857d3150f52.png)

1. There could be a pop-up box with the messaging after entering a bounty price, which automatically gets a fee added, along with an explanation of why we're doing that. 

Goals for messaging:

1. Why is this fee being implemented ("As Gitcoin grows in 2019, we've been thinking of ways to sustain our operation costs. When a funding a bounty, we've decided to ask the funder for a small percentage fee to help feed Gitcoin. We've prided ourselves on never being a middleman and taking a cut of the contributor's contributions and we intend to honor that commitment, as per open source ethos. This way, the contributor is still rewarded the full bounty amount, and Gitcoin continues to be able to help you bounty issues.") something like that.

2. The fee is not coming off of the bounty amount, therefore, the contributor is not "billed."

3. The fee is in addition to the bounty amount, so the funder must be made aware that the price to post a bounty is X + XY, where X is the price of the bounty to be paid to a contributor, and Y is the percentage fee. As an example, if I post a $100 bounty, and the fee is 5%, then the amount to post is $105. 

4. If point 3 is true, we may want to automatically add the fee once the they've nailed down the bounty price. I say recommend automatic (unless it's done at the contract level), because if the funder just sees a message and decides not to pay the fee, and we collect it, then the fee will still be taken out of the bounty. 

### Definition of Done

1. Designs on where placement should be.
2. Messaging included in the designs. 
3. Ensure we have a process for automatically adding the fee to the bounty amount (I believe this is contract level).

### Data Requirements

1. Ensure that the bounty value still exists in the data model.
2. Add the fee value taken for the bounty in the data model.
3. Look at a long and short term retention for funders post fee-release.
4. Look at absolute and relative number of bounties and MPV flowing through Gitcoin post fee-release.

**Comment by PixelantDesign** [comment]
<img width="1017" alt="screen shot 2019-02-27 at 4 11 23 pm" src="https://user-images.githubusercontent.com/238235/53523514-04736200-3aab-11e9-9e97-634f204013d9.png">

**Comment by PixelantDesign** [comment]
<img width="925" alt="screen shot 2019-02-27 at 4 17 45 pm" src="https://user-images.githubusercontent.com/238235/53523668-692ebc80-3aab-11e9-85f6-17512e117377.png">

**Comment by PixelantDesign** [comment]
<img width="918" alt="screen shot 2019-02-27 at 4 24 27 pm" src="https://user-images.githubusercontent.com/238235/53524031-65e80080-3aac-11e9-855a-642ac0495cfa.png">

**Comment by octavioamu** [comment]
I just think the 10% have to be just from the bounty value not the featured bounty. 
bounty 2eth
fee 0,2 eth
featured bountu .05 eth

**Comment by PixelantDesign** [comment]
yes agree, bounty value of 2eth

**Comment by frankchen07** [comment]
> Simply pay the bounty amount (plus a standard 10% Gitcoin platform fee). This covers our costs for...

I'd just change "We cover" to "This covers", it makes more sense to me.

I like the overall design, and how it starts with "no surprises", and it's after the gas limit. However, let's say the example above, they put in 2.50 ETH in the form, does this mean they have to go back up and change 2.50 to 2.55, or does the "payment due" at the bottom of the design automatically add it and take care of it?

**Comment by PixelantDesign** [comment]
They shouldn't have to back to the top to make any changes.

**Comment by PixelantDesign** [comment]
<img width="900" alt="screen shot 2019-03-05 at 12 23 12 pm" src="https://user-images.githubusercontent.com/238235/53824331-b4c8e680-3f41-11e9-99fd-132b347bd074.png">

Updated text attached.

I also shrunk the size of the gas area and the fonts in that section as well as updated Hiring header.
cc: @thelostone-mc has the sketch file already.
