### ISSUE TITLE
(unknown): 구문 오류

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#385]
View details in Rollbar: [https://rollbar.com/mbeacom/gitcoin/items/188/](https://rollbar.com/mbeacom/gitcoin/items/188/)

```

(unknown): Erreur de syntaxe
  File "https://gitcoin.co/static/v2/js/shared.5545e99b0ca7.js", line 33, in [anonymous]
```

**Comment by mkosowsk** [comment]
This Korean is easy, that's a syntax error 👍🏻
