### ISSUE TITLE
Issue with claim tip button in email notification

### ISSUE THREAD

**Issue by eswarasai** [gitcoinco/web#3853]
**Describe the bug**
`Claim tip` button in the email notification doesn't take the user to the claim tip page. Instead it redirects to `gitcoin.co`. Had to claim the tip from user profile menu.

**Expected behavior**
Should be able to claim tip directly from the email notification

**Comment by PixelantDesign** [comment]
Thanks for the report @eswarasai! Want to help us fix this one?
