### ISSUE TITLE
UX Capture Star Ratings in Advanced Payout

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3873]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on bounties that need to be paid using advanced pay so that we can understand their experience with tasks that require multiple contributors to complete.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Define a Ux and design to solve for the above problem
- [ ] Review with Core team
- [ ] Annotate user experience. 

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
What do you think? @PixelantDesign @octavioamu @SaptakS 
![Star Ratings Advanced Payout](https://user-images.githubusercontent.com/19514207/54219044-aa05e700-4529-11e9-8d16-d6275ba4f90c.jpg)

**Comment by willsputra** [comment]
Updated with latest modal
![Advanced Payout](https://user-images.githubusercontent.com/19514207/54612882-bc85a080-4a94-11e9-92f7-0a9a56bd73e1.jpg)
