### ISSUE TITLE
Build Front-End Capture Previous Star Ratings

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3879]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on previous bounties that they've collaborated on so that we can understand their experience.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Build Front-End
- [ ] Ensure the experience is responsive
- [ ] Review with Core team

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
![star rating](https://user-images.githubusercontent.com/19514207/53814341-6bf14c00-3f9a-11e9-9efe-b10926856398.jpg)

**Comment by SaptakS** [comment]
Done in #3967
