### ISSUE TITLE
Build Backend Capture Previous Star Ratings 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3880]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on previous bounties that they've collaborated on so that we can understand their experience.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Build Back-End
- [ ] Ensure all data is captured in admin
- [ ] Ensure there is tracking per @frankchen07 needs
- [ ] Review with Core team

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
![star rating 1](https://user-images.githubusercontent.com/19514207/53816814-3d29a480-3f9f-11e9-8546-0bb9b403d9a7.jpg)

**Comment by PixelantDesign** [comment]
8

**Comment by SaptakS** [comment]
Done in #3967
