### ISSUE TITLE
UX - Prompt to Capture Star Ratings (Email or Modal)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3886]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on bounties that need to be paid using advanced pay so that we can understand their experience with tasks that require multiple contributors to complete.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Define a Ux and design to prompt for capturing previous star ratings (email or modal)
- [ ] Review with Core team
- [ ] Annotate the end to end user experience. 

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
Email and modal. Thoughts? @PixelantDesign @SaptakS @octavioamu 
![Funds Paid Email](https://user-images.githubusercontent.com/19514207/54367130-d5650f00-46ac-11e9-9da6-9dac1326226b.jpg)
![Star Rating Modal](https://user-images.githubusercontent.com/19514207/54367135-d72ed280-46ac-11e9-8878-b7b373790f22.png)

**Comment by willsputra** [comment]
Updated with clearer CTA

![Star Rating Modal](https://user-images.githubusercontent.com/19514207/54613446-acba8c00-4a95-11e9-8543-9c4659c81252.jpg)
![Star Rating in Funds Paid Email](https://user-images.githubusercontent.com/19514207/54613450-ad532280-4a95-11e9-95a9-4804d556ae4a.jpg)
