### ISSUE TITLE
Sentry upgrades - review and deployment

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3887]
### User Story

Sentry broke a couple weeks ago, @danlipert has made changes and this ticket is a placeholder to ensure that timely review and testing happens so he can push it out.

### Why Is this Needed

Sentry helps us catch errors.

### Current Behavior

Sentry fixes that need review and attention.

### Expected Behavior

Completed Sentry fixes.

### Definition of Done

- [ ] review & test 
- [ ] deploy

**Comment by danlipert** [comment]
Just to add some context, sentry is currently working but the setup and configuration is a bit wonky - I've got a PR here to fix that I'll finish up and test: https://github.com/gitcoinco/web/pull/3837
