### ISSUE TITLE
BUIDL - As a Gitcoin operator, I want to properly communicate charging a % fee on a funder for funding a bounty. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3891]
### User Story

BUIDL - As a Gitcoin operator, I want to properly communicate charging a % fee on a funder for funding a bounty. 

### Why Is this Needed

As we roll out revenue tests and charging funders a percentage fee for posting bounties, the messaging and story arc behind this change is very important. This ticket is the build out of that.

### Description

@thelostone-mc should have the sketch files for the build.

As discussed (2019-03-14):

1. We're keeping the featured bounty fee and the platform fee separate because if we combine those to keep the Metamask popups to a minimum the denomination of different currencies will make that difficult, if not impossible. We'll keep them separate and add messaging in two ways: 
    - messaging under the summary
    - utilizing the blue alert shade at the top
    - Metamask confirmation bot (https://github.com/gitcoinco/web/issues/3910)

This allows ETH or ERC-20 tokens for the fee, ETH only for the featured bounty fee, and ETH or ERC-20 tokens for the bounty.

2. Eventually, we'll want to add currency support for featured bounties which may help the Metamask UX issue, but that's not in scope this round, as if we did end up allowing currency switching, it would add alot of work for this sprint. 

@danlipert & @thelostone-mc - ^ please correct me if I'm wrong or if there are any modifications, or clarifications you guys need. 

### Current Behavior

No messaging or build-out on the funder page.

### Expected Behavior

Fee-description and logic on the funder page.

Design ticket here: https://github.com/gitcoinco/web/issues/3842

### Definition of Done

- [x] messaging on fee is clear
- [x] front-end funder form messaging and elements added
- [x] front-end logic and math for adding the fee is implemented

### Data Requirements
- [ ] bounty amount and any associated fees are stored in the DB by bounty

**Comment by frankchen07** [comment]
Adding Aditya's work preview here - this is when the bounty is funded in ETH:

![Untitled](https://user-images.githubusercontent.com/7516920/54375001-74eab900-463d-11e9-9972-d39e8ed7d95d.gif)

Successful creation: 

<img width="1164" alt="Screen Shot 2019-03-09 at 11 58 09 PM" src="https://user-images.githubusercontent.com/7516920/54375052-8cc23d00-463d-11e9-94c7-ddc895eb8253.png">

When the user rejects the bounty fee:

![Untitled (1)](https://user-images.githubusercontent.com/7516920/54375065-9481e180-463d-11e9-8618-77171f3a16c9.gif)

Previous discussion about the bubble: the bubble should be a calculation of the fee (big number is the fee that they’re going to pay, and the little % number is the percentage. This is the messaging. 

@thelostone-mc, when you get the chance, can I see the current work as it stands at some point to see the copy and messaging?

**Comment by thelostone-mc** [comment]
@fronk would the gist suffice ?
