### ISSUE TITLE
Bug - User reports that when using Firefox, Gitcoin refreshes infinitely.a

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3895]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
how much effort do you see this proto-spoke direction taking? what end game are you thinking? % equity in the startups?

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
(asking contributor for repro steps now)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
no infinite refreshes

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by janus** [comment]
Desktop (please complete the following information):

    OS: Ubuntu 18.04
    Browser  Fire Fox
    Browser Version 65.0(64 bit)


Just noticed that it starts off refreshing continuously once I connect to Met
aMask.
