### ISSUE TITLE
bug - contrab is malformatted

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3896]
when trying to install crontab on prod

```
- updating crontab
"scripts/crontab":56: bad command
errors in crontab file, can't install.
```

**Comment by owocki** [comment]
cc @danlipert so he knows to watch for this next time! 

fixed in https://github.com/gitcoinco/web/issues/3896

**Comment by danlipert** [comment]
Thanks @owocki will keep an eye out for this in the future 👍
