### ISSUE TITLE
404 Error after opening the "Open Source opportunities" page. 

### ISSUE THREAD

**Issue by pandyamarut** [gitcoinco/web#3899]
https://gitcoin.co/contributor 
This URL Shows 404 error Most of the times

**Comment by owocki** [comment]
where is this URL linked?

https://gitcoin.co/how/contributor is the correct link

**Comment by pandyamarut** [comment]
![screenshot from 2019-03-07 14-22-04](https://user-images.githubusercontent.com/28846178/53944176-d1515400-40e4-11e9-8d40-2c64a9464354.png)

**Comment by pandyamarut** [comment]
@owocki  Just Got an error while Going through it , Else it's your choice. 
Thank you!

**Comment by owocki** [comment]
@pandyamarut thanks for the screenshot, and sorry for being overly dense -- where is that screenshot from?

**Comment by pandyamarut** [comment]
![screenshot from 2019-03-07 14-22-04](https://user-images.githubusercontent.com/28846178/53979439-dc7fa080-4133-11e9-90aa-e6c8f7e25994.png)
@owocki

**Comment by pandyamarut** [comment]
![screenshot from 2019-03-07 14-22-04 1](https://user-images.githubusercontent.com/28846178/53980453-6597d700-4136-11e9-8333-85e575a0da33.png)

@owocki Please Check it.
