### ISSUE TITLE
Build Front End Hackathon Experience

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3901]
Reference
https://github.com/gitcoinco/web/pull/2267

### User Story

As a funder I'd like to be able to create hackathons on Gitcoin.

As a hackathon participant I'd like to be able to see all of the prizes that are available on Gitcoin.

As a remote contributor I'd like to not see hackathon issues in the issue explorer since I cannot participate on these issues.

### Current Behavior
No Hackathon feature

### Expected Behavior
Separate experience.

### Solution

Create Hackathon page using contest bounties.
Hide hackathon bounties from the issue explorer and put hackathon bounties into a separate tab.
All issues created for hackathons should be tagged "hackathon name".
All hackathon users should be directed to a specific URL (basically filtered search with the name)
Nice to have: Add a hackathon link to that view from the issue explorer.

- A core team member should be able to create a hackathon link in the admin panel.
Example: gitcoin.co/hackathons/hackathonname
- There should be an area to upload a logo
- 3 fields to display prizes and value of each prize (1st, 2nd, 3rd)

### Definition of Done

- [ ] Hide hackathon bounties from the issue explorer 
- [ ] Put hackathon bounties into a new view based on the issue explorer (see mockup)
- [ ] Create a custom url for hackathons that only core team members can see but are able to share.
- [ ] create admin capabilities that allow:
- A core team member should be able to create a hackathon link in the admin panel.
Example: gitcoin.co/hackathons/hackathonname
- [ ] Add a hackathon logo 
- [ ] - 3 fields to display prizes and value of each prize (1st, 2nd, 3rd)
- [ ] All of the above must be tested.

### Additional Information

![hackathon_v0](https://user-images.githubusercontent.com/238235/45846685-7a9ebc00-bcf6-11e8-909c-d5dab0616e32.png)

**ESTIMATES**

**Front End** **5**
- Build the Hackathon Page layout
- Add a field to Fund Issue Form (tagging Hackathon name)
- Display prize list for contest bounty
- Display image uploaded from admin
- Ensure the page is responsive

**Comment by SaptakS** [comment]
Done in #3942
