### ISSUE TITLE
Build Hackathon Landing Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3903]
Content coming from @alexvotofuture 

Build a landing page with the following content for Ethereal Hackathon.

<h1> ETHEREAL VIRTUAL BOUNTYTHON </h1>
<h3>Powered by Gitcoin</h3>
<h2 b> April 1-30th </h2>

<p>Join Gitcoin for a pre-Ethereal NY virtual hackathon this April!

Hackathon challenges will be posted as bounties, with the best hacks receiving prizes in ETH & ERC-20 tokens. Main track winners will receive free tickets to Ethereal NY to present their project live on stage. </p>

<h2>Organizing Sponsors</h2>
<Large Microsoft logo>

<h2>Challenge sponsors</h2>
<MythX logo><Rhombus Logo><uPort Logo> <ConsenSys Labs logo>

<h3> REGISTER </h3>
Register by <b>April 1st</b> for updates on key dates, prizes, teams, and instructions on how to start bounty hunting.
<”REGISTER” button leading to Typeform> [note: getting this link to existing registration form from Matthew Groff]

<h3> JOIN THE COMMUNITY </h3>
Meet fellow BIDLers, form teams, and share your ideas. Join us in the #ethereal-hacks channel on Gitcoin’s Community Slack.
<”JOIN” linking to #ethereal-hacks channel on Gitcoin Community Slack>

<h3> FUND A PRIZE BOUNTY </h3>
Have an epic challenge you want to see the community tackle? Want to see how bounty hunters from around the world use your tools? Reach out to us to sponsor and post a prize bounty!
<link to typeform for sponsors> [to be created]

### Definition of Done

- [ ] A page is built with the above info
- [ ] Review with core team and @alexvotofuture 
- [ ] Page must be responsive

**Comment by PixelantDesign** [comment]
@alexvotofuture how will users get to this landing page?

**Comment by alexvotofuture** [comment]
@PixelantDesign We are going to have sponsors, media, etc. link to the landing page. It will also be posted on CodeFund. Through April we could have a banner on the main Gitcoin page somewhere saying the hackathon is live, leading to the landing page as well.

**Comment by alexvotofuture** [comment]
The main purpose for this is to provide information on the hackathon so people know how/when to join, drive developer signups ahead of the hackathon, and to feature prize bounty sponsors to drive sponsor interest.

**Comment by owocki** [comment]
is this replaced by https://github.com/gitcoinco/web/issues/3958 ?

**Comment by PixelantDesign** [comment]
Done!
