### ISSUE TITLE
BUIDL - As a Gitcoin operator, I want to create a dispute resolution faucet to facilitate funder fee refunds.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3909]
### User Story

BUIDL - As a Gitcoin operator, I want to create a dispute resolution faucet to facilitate funder fee refunds.

### Why Is this Needed

Context: https://gist.github.com/thelostone-mc/dd89b2824f1c5243fd256a902bb2b29b#gistcomment-2855545

This is the place where funders can get the fee refunded. for posting a bounty (once the % fee is implemented)

### Description 

1. The funder fee is charged upfront immediately after posting a bounty.
2. If the funder decides to cancel, they will be redirected to the dispute resolution "faucet" in order to get their funds back (for now, reviewed by the Gitcoin team).

We can repurpose gitcoin.co/faucet designs.

### Current Behavior

No faucet or dispute resolution page.

### Expected Behavior

A faucet / dispute resolution page.

### Definition of Done
- [ ] if a funder cancels, the flow should direct them to the refund / dispute resolution faucet.
- [x] sufficient details shoudl be provided to the Gitcoin team (amount to be refunded, bounty issue, cancellation reason, free text reasoning)

### Data Requirements
- [x] ensure that successful and failed refunds are tracked in the db

**Comment by thelostone-mc** [comment]
A few clarifications :
- Can requests be submitted only on cancellation ?
- Should we force users to redirect on cancel bounty / leave a button on cancelled bounty page making it optional? 
- Should the button also be on the bounty details page ?


^ If so could we get mocksups for it ?

**Comment by frankchen07** [comment]
> Can requests be submitted only on cancellation? 

I think requests can be submitted freely as well, and there are two situations that I can see where that's appropriate. This means that the refund page should be accessible on the issue details page as well as on the redirect after cancellation.

1. After cancelling, the funder accidentally closes the fee refund page. They can still access it through the issue details page. 

2. The funder would like a refund on part of the fee (e.g featured bounties fee but not the platform fee).

> Should we force users to redirect on cancel bounty / leave a button on cancelled bounty page making it optional?

I would say it's only fair that we notify them after they cancel a bounty that there is the option to have the fee refunded. To me that's just platform honesty. I am a yes on redirecting a user to the request bounty fee refund page after cancellation.

> Should the button also be on the bounty details page?

Yes, in my opinion, if the two scenarios described above make sense. Are there any other scenarios that make sense in this situation?

I would add some changes to the copy below:

<img width="1173" alt="Screen Shot 2019-03-14 at 8 35 05 PM" src="https://user-images.githubusercontent.com/7516920/54379774-47a30880-4647-11e9-9fbe-51084f66e7a2.png">

> Request Bounty Fee Refund -> Refund Request 

> remove "(Funder only)", only funders can get access to it anyway

> "If Gitcoin has charged you fee which shouldn't have been charged. Let us know and we'll look in it." -> I'd say remove this and combine the "let us know about it" into the reason line below.

> do we need the "back to bounty" link? or can they just use the back button if they need it?

> Issue URL, Funder, Funder Address -> looks fine to me

> Remove "reason" and just have the question: "Why are you requesting a refund? Please let us know and we'll look into it!"

> "Explain how the charges were extra" -> "Refund details" (maybe there's a better phrase than this)
