### ISSUE TITLE
DESIGN - Design a "nice bot" svg that is situated in the top left corner asking the user to check the Metamask popup when double transactions are necessary.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3910]
### User Story

DESIGN - Design a "nice bot" svg that is situated in the top left corner asking the user to check the metamask popup when double transactions are necessary.

### Why Is this Needed

Context: https://gist.github.com/thelostone-mc/dd89b2824f1c5243fd256a902bb2b29b#gistcomment-2855545

For certain Metamask transactions (Grants, and also the contract % fee), two transactions will be necessary for the user to proceed. Although this UX tradeoff is undesired, it is currently better than heavily modifying the contract (high LOE).

The purpose of the nice bot svg is to prompt the user to look out for that second transaction.

### Current Behavior

No way to notify the user that there's a second Metamask transaction that often doesn't pop up (remains in the top right hand corner in the browser).

### Expected Behavior

Nice bot SVG that directs the user to accept the second transaction.

### Definition of Done

- [ ] Nice bot SVG design that can be added to the appropriate pages while the user is waiting to click on Metamask.

### Data Requirements
- [ ] Google analytics tracking for dropoff once the % fee is released.

### Additional Information
Previous work: https://github.com/gitcoinco/web/pull/3599
@PixelantDesign / @willsputra can you attach the design collateral to this ticket? Depending on Alisa's sign off, this design could already be done!

**Comment by owocki** [comment]
does what @willsputra did on https://gitcoincore.slack.com/archives/CCZFZDT9V/p1551894024002400 count?

**Comment by frankchen07** [comment]
@owocki - yes it does look like what we're looking for.

Ideally, I'd like this up this sprint, but that's contingent on hooking everything up. Generally looks like good progress though.

**Comment by PixelantDesign** [comment]
Can we try something a little more explicit?

<img width="615" alt="Screen Shot 2019-03-13 at 4 10 13 PM" src="https://user-images.githubusercontent.com/238235/54311351-ca29ba80-45aa-11e9-84e5-adab086be27f.png">
[Web3 CalloutAM.zip](https://github.com/gitcoinco/web/files/2963471/Web3.CalloutAM.zip)

**Comment by frankchen07** [comment]
@PixelantDesign I like the wording better on the second (lower) design. It's more succinct. The sentence on the first one (upper) is not a complete sentence, so it didn't make sense to me.

I'd add two things, a comma after "network" and Ethereum should be capitalized.

**Comment by PixelantDesign** [comment]
Sounds good. I'm fine with either...
