### ISSUE TITLE
PR Review: % Fee Funder Page

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3923]
Please review Aditya's % fee funder page work: https://github.com/gitcoinco/web/issues/3891

**Comment by thelostone-mc** [comment]
who would be doing this btw?  @danlipert / green squad ?

**Comment by frankchen07** [comment]
I would say green squad since @danlipert and @thelostone-mc - you guys were the ones who were working on it.

@PixelantDesign
