### ISSUE TITLE
PR Review: Kubes Migration

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3925]
Please review Dan's Kubes Migration work: https://github.com/gitcoinco/web/issues/3711

**Comment by owocki** [comment]
@frankchen07 how do i review?

**Comment by owocki** [comment]
oh wait herp derp; this is just a ticket so that we remember to put star points on PR review

**Comment by PixelantDesign** [comment]
@frankchen07 do we still need this ticket?

**Comment by frankchen07** [comment]
@danlipert - I believe this was already pushed, is there further review necessary? If not I can close.

**Comment by danlipert** [comment]
@frankchen07 Still need to switchover to the new IPFS node in production which I want to do this week, then we've got the process of tearing down the old infrastructure which should be a new ticket 👍 so I'm fine with taking it down
