### ISSUE TITLE
DESIGN - As a job hunter, I want to have a Gitcoin /jobs page, so I can see what kind of jobs Gitcoin's network has to offer

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3931]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
DESIGN - As a job hunter, I want to have a Gitcoin /jobs page, so I can see what kind of jobs Gitcoin's network has to offer.

### Why Is this Needed

Right now our jobs page is fug.

Also, people come to us with an expectation that if they simply apply, that we're going to find time for them to have a half hour call. with them, etc.

Instead, we need to explain to people that we hire mostly through our community and product.  The best way to stand out to us, is to stand out on the platform.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
http://localhost:8000/about#jobs

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Remove existing Jobs section from about page.
- Add a link to `/jobs` on footer.
- A landing page that explains:

* We are built by & for coders.  
* Gitcoin is built with Gitcoin (we dogfood). 
* We believe in try-before you buy hiring (click to see our values => /mission )
* We believe in remote work. (click to see our values => /mission )
* We believe in open source. (click to see our values => /mission )
* Here is a link to our issue explorer.  
* Already done a few bounties?  The best way to apply is below:
* A list of our open Jobs (title, desc)
 *  click on any job and the job desc / application link full details appears.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- 2 -3 revisions
- must follow our brand guidelines (gitcoin.co/presskit)
- must look good on responsivedesign too.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Please include a link to your portfolio in your application.

**Comment by owocki** [comment]
@emiwatanabe422 any interest in picking this up?

**Comment by emiwatanabe422** [comment]
@owocki I'd rather do this or the ERC 1789 landing page first and see how it goes. Is this one more pressing?

**Comment by owocki** [comment]
@emiwatanabe422 the ERC 1789 landing page is higher priority

happy to hold this for you though.  what kind of timeline are we talking about?

**Comment by emiwatanabe422** [comment]
@owocki I think I could get started on this next week.

**Comment by owocki** [comment]
cool lets do it

**Comment by owocki** [comment]
hey @emiwatanabe422 did you still want to work on this?  given that we've been stalled on the EFI stuff.. was wondering if we could get started here.

**Comment by emiwatanabe422** [comment]
@owocki Yes! started yesterday. Did a quick mock up of the layout.
Should I add more text/explanations or is this sufficient? 
Are there existing job postings you want me to put in? 
Did you want a separate page that goes into detail about the job postings?

![image](https://user-images.githubusercontent.com/46271233/55028122-2dace280-4fc4-11e9-8ed7-307459242395.png)

**Comment by owocki** [comment]
@emiwatanabe422 no need for a seperate page with job descs on it. 

i think the layout is a good start!  I'd maybe put some of the "built by and for coders" and " try before you buy" stuff side by side to reduce the length of the page.  other than that i think we're good to begin the design process here.

**Comment by emiwatanabe422** [comment]
@owocki 
https://github.com/gitcoinco/web/pull/4079
