### ISSUE TITLE
Gitcoin & Bounties Network show different amounts of funding

### ISSUE THREAD

**Issue by lucasvo** [gitcoinco/web#3950]
Gitcoin's funding amount I believe is incorrect. For the following bounty:
* https://gitcoin.co/issue/centrifuge/go-centrifuge/438/2235
* https://explorer.bounties.network/bounty/2235

I believe what happened is that when creating the bounty initially due to a chrome bug I signed the transaction and created two bounties for the same issue. I later cancelled the bounty so Gitcoin might show the funding for both?

**Comment by PixelantDesign** [comment]
Thanks for the repot @lucasvo! We will take a look.
