### ISSUE TITLE
Change Dropdown to User Search for Verified in Admin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3963]
As a Gitcoin Core team member, I'd like to be able to search for users when verifying vs. growing through a dropdown.

#Definition of Done

- [ ] Change the dropdown to a search

<img width="870" alt="Screen Shot 2019-03-13 at 5 48 52 PM" src="https://user-images.githubusercontent.com/238235/54317197-e5032b80-45b8-11e9-9ab9-38dba826201b.png">

**Comment by SaptakS** [comment]
Done in #3965
