### ISSUE TITLE
BUILD Update Basic Payout to include tooltip and pop modal on Star Ratings

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3964]
As a funder/contributor I'd like to be able to provide details in the star ratings.

#Definition of Done

- [ ] Implement ability to pop modal to complete details within star ratings
- [ ] Tooltip should show when user hovers over each star
- [ ] This module should work the same everywhere

#Tech Specs
- Update the component from advanced pay
- Change backend to accept.

#Data Tracking
- No change from what we're currently tracking

**Comment by willsputra** [comment]
Star Ratings on Basic Payout:
![Star Ratings on Basic Payout](https://user-images.githubusercontent.com/19514207/54614403-4e8ea880-4a97-11e9-87c5-1a463e6e6ddb.jpg)

**Comment by SaptakS** [comment]
Done in #3967
