### ISSUE TITLE
Demystifying Recipient and Owner / Admin Addresses [Gitcoin Grants]

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#3966]
Some users have expressed confusion as to what each respective address represents. Describing these in the grant creation process using an information icon could be a helpful way to resolve this.

**Comment by owocki** [comment]
Owner / Admin Addresses - This is the address that "owns" the grant on chain and can make changes to the grant or cancel it.

Recipient - This is the address that the funds will go to whenever the subscription activates.

**Comment by owocki** [comment]
@PixelantDesign i'd happily add a bounty for someone to create an info tooltip with the above info if that works for you and @ceresstation

**Comment by ceresstation** [comment]
That sounds great, per our conversation we should also add a line in red letters stating that the recipient address cannot be changed and should be chosen carefully.
