### ISSUE TITLE
DESIGN - As a funder who submitted a refund request, I want email confirmation that my refund request is being processed, and confirmation of the action on the Gitcoin admin side.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3969]
### User Story

DESIGN - As a funder who submitted a refund request, I want email confirmation that my refund request is being processed, and confirmation of the action on the Gitcoin admin side.

### Why Is this Needed

When a funder funds a bounty and pays a fee, they are eligible for a fee refund if they cancel their bounty. The funder should receive confirmation after submitting a refund request from the dispute page (https://github.com/gitcoinco/web/issues/3909) and then another confirmation email stating the result of that refund request.

### Description

We can use an existing email template, but basically after submitting the refund request, we send an email confirming:

1. the bounty it was for
2. the funder's address
3. the refund details and message the funder input
4. a message saying "You've requested a refund on <bounty link>. A Gitcoin team member will reach out to you shortly. Business requests usually have a turnaround of 24-48 hours."
5. the relevant Gitcoin branding in the email.

For the second email (the decision email), is it possible to have just the Gitcoin admin (one of us) reply to the first email, or do we need a template for that one as well? Either way, for now, it will be a manual process.

### Current Behavior

No confirmation email for the refund request. 

### Expected Behavior

Confirmation email that Gitcoin has received a refund request, and another email outlining the result of the bounty fee.

### Definition of Done

1. Design for email number 1 (under description)
2. Design for email number 2 (pending quick discussion)

**Comment by thelostone-mc** [comment]
The email number 2 can also be triggered when the admin accepts / rejects a request IMO but defer to product 🙌

**Comment by PixelantDesign** [comment]
[Refund Email.zip](https://github.com/gitcoinco/web/files/2989222/Refund.Email.zip)


![Refund Email](https://user-images.githubusercontent.com/238235/54702767-e4fdb100-4b0d-11e9-95f3-236a9f60527d.jpg)

**Comment by frankchen07** [comment]
https://github.com/gitcoinco/web/pull/3961#issuecomment-474965633

**Comment by owocki** [comment]
> a Gitcoin team member will reach out.

pedantic copy point; but should we start to normalize how we talk about the core team.  I've been using Gitcoin Core == the core team; Gitcoin == the network & OSS software that powers it.

so in this case I recommend 

> a Gitcoin *Core* team member will reach out.

**Comment by PixelantDesign** [comment]
yep we could do that
