### ISSUE TITLE
Work Submitted Not Displaying

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3978]
https://gitcoin.co/issue/gitcoinco/web/3958/2596

<img width="1031" alt="Screen Shot 2019-03-15 at 4 48 11 PM" src="https://user-images.githubusercontent.com/238235/54461267-7d78e780-4742-11e9-9f82-f4d29d5f1b70.png">

**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by rafalkowalski** [comment]
@PixelantDesign Currently we can see two contributors who submited work.
