### ISSUE TITLE
UX - Suggesting Verified Contributor profiles for review, or contributors you've worked with in the past

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3987]
UX - Suggesting Verified Contributor profiles for review, or contributors you've worked with in the past

### User Story

As a funder, when I'm completing the funder form, I'd like Gitcoin to recommend to me workers for my Bounty. These could be verified contributors or contributors I've worked with in the past.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently we don't have this feature.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Brainstorm with engineers an approach and discuss limitations/constraints.
- [ ] Create a task flow of all of the touchpoints into this experience.
- [ ] Create designs that detail the experience steps.
- [ ] Review with 3-5 Funders for feedback
- [ ] Review with core team members

### Data Requirements

- [ ] long term retention should increase
- [ ] feature usage, of the bounties that were opened, which ones had suggestions, x days out from release
- [ ] for each bounty, who was suggested

**Comment by willsputra** [comment]
![Recommend Contributor (1)](https://user-images.githubusercontent.com/19514207/55421691-06e24380-55a4-11e9-93f2-6352a506e855.jpg)

**Comment by PixelantDesign** [comment]
**Front End**
- Implement new design
- Implement select behavior
- Implement on click actions
- Implement modal data
- request data for select

**Estimate** 8

**Back End**
- send first 5 data for contributors
- find all recommended contributors and send them on click
- send all other contributors
- add new field in backend
- fire an email after fund issue is successful.

**Estimate**  8

**Comment by willsputra** [comment]
updated the wording on the header
![recommendcontributor](https://user-images.githubusercontent.com/19514207/55564010-34083080-5721-11e9-9327-136db32e3292.jpg)
