### ISSUE TITLE
Data - User Engagement Analysis - As Gitcoin, we'd like to understand our users behavior and come up with ideas on how to engage with them.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#3988]
Data - Pull Github handles - people that signed up and haven’t done anything. Who has a lot of open source contributions.
Cross reference current bounties on platform with current skillets on platform.

**Comment by frankchen07** [comment]
In a nutshell, the Github API is not sufficient to be pulling large amounts of data from, and it exceeds the ability on my local machine.

Looking at GH Archive and Big Query options, but they seem to only have data that is not up to date (2012 and before).
