### ISSUE TITLE
HTML/CSS Touch ups on Bounty Details Page

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/web#399]
Tweak the details page a bit so that the columns and headers line up nicely and its easier to read.

**Comment by owocki** [comment]
might be able to fold this in with https://github.com/gitcoinco/web/pull/323

**Comment by jasonrhaas** [comment]
@owocki ah yes I think I can probably merge those changes in with the new stuff for multiple fulfillments if you are happy with the design.  Looks like an improvement.

**Comment by owocki** [comment]
i... dont love the design on that issue but maybe im marred by staring at the old one too much.  maybe @pixelantdesign will have more developed thoughts than i do :P

**Comment by jasonrhaas** [comment]
ok well lets keep the new design discussion in that PR, this issue is just to fix a coupe allignment things.  That one seems like more of a slight re-design.  Will get this taken care of and close out this issue.

**Comment by owocki** [comment]
ok cool

**Comment by jasonrhaas** [comment]
ok so this one is complete with the exception that we need to fix a bug that is occurring on the bounty fulfillment.  Currently the API/Database is not updating the `bountyfulfillment` table properly which a fulfillment gets accepted.  I have some code in there that displays which fulfillment was accepted, but it won't work unless the database is updated.  Opening a new Issue for this bug.
