### ISSUE TITLE
bug - unclosed div on profile 404 page bug 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3991]
When you trying hitting an invalid profile URL ->  the UI screen breaks.
Identity the missing and ensure valid profile + hidden profile page render as expected

<img width="709" alt="Screen Shot 2019-03-18 at 11 57 24 AM" src="https://user-images.githubusercontent.com/513929/54552149-08d9bf00-4975-11e9-865f-12b4d589846a.png">

the footer should go across the entire bottom of the screen.  like it does on the regular profile

![screencapture-gitcoin-co-profile-thelostone-mc-2019-03-18-11_58_09](https://user-images.githubusercontent.com/513929/54552194-29097e00-4975-11e9-8685-2c668d87896e.png)

**Comment by agwisniewska** [comment]
Can I check it ?

**Comment by thelostone-mc** [comment]
@agwisniewska Yup go ahead! Check out how to run locally via Docker section and raise a PR  ^_^

**Comment by thelostone-mc** [comment]
@agwisniewska we got a PR in for this! Would you be open to throwing in a fix for https://github.com/gitcoinco/web/issues/3715 ?
