### ISSUE TITLE
As a Gitcoin funder, users from the same organization who open bounties find it difficult to manage bounties within the team, as payout and funder actions are tied to a specific funder's account.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3993]
### User Story

As a Gitcoin funder, users from the same organization who open bounties find it difficult to manage bounties within the team, as payout and funder actions are tied to a specific funder's account.

### Why Is this Needed

For Gitcoin Bounties, users from the same organization who open bounties find it difficult to manage bounties within the team, as payout and funder actions are tied to a specific funder's account.

### Description

Shared management and multi-sig occurs on multiple levels:

discussion here: https://gist.github.com/frankchen07/1ade6a819e89962dfcda1cd61c5d0e96

summary from discussion:

1. shared management is a peer-to-peer approval to help manage a bounty (think funder approves a gitcoin ambassador in the multi-signature contract wallet to help them manage and payout a bounty)

2. shared management in an organization sense (think one organization with multiple funders who post bounties using a multi-signature contract wallet, where there are rules for payout and/or each funder part of that organization can choose to pay out)

3. all cases above require the ability to integrate multi-signature contract wallets into the bounty workflow.

additional assumption: use case for multi-signature doesn't necessarily increase ease of use, it increases the complexity to increase security, while at the same time, allows additional grouping operations under bounties

possible solutions:

1. lower engineering lift solution is to research how to integrate gnosis-multi-sig wallets into the currently bounty flow, which would involve figuring out the `ifelse` fork for javascript calls on the contract (to determine if it's a multi-sig or normal wallet case). Approval will occur in two locations, which is a UX consideration @danlipert to inform Frank to help break this into a sub-task if necessary

2. partial solution is bounties contract modification ("enter other member's you'd like to help manage" option). 

3. other unexplored options

### Current Behavior

Currently, we have no multi-signature capabilities.

### Expected Behavior

Research into the viability of solution option 1.

### Definition of Done

- [ ] hard estimates on engineering lift and implementation
- [ ] decision points on consequences of UX changes

### Data Requirements

- [ ] funders who would be willing to test a v1 of this feature

**Comment by danlipert** [comment]
@frankchen07 Here's the summary of my research and my recommendations regarding multi-sig: https://gist.github.com/danlipert/7c976627c42e877678b0d3a447b547ab

Let me know your thoughts on my recommendations - and lets keep the discussion here on this issue so I get alerted to your comments :)
