### ISSUE TITLE
Bounty activity feed doesn't specify who is receiving tip, worker approved, and work done

### ISSUE THREAD

**Issue by emiwatanabe422** [gitcoinco/web#3997]
In a bounty's activity feed, the events "tip sent", "worker approved" and "work done" only show the user(funder) sending the tip and accepting the worker. We should be able to see which worker is receiving the events.

Here it shows the funder sending a tip and paying out a worker, it does not show which worker received payment.
https://gitcoin.co/issue/gitcoinco/web/3714/2294
![image](https://user-images.githubusercontent.com/46271233/54562936-3d557700-4985-11e9-881e-ae191d058520.png)

Here it shows the funder approving a worker but does not specify which one.
https://gitcoin.co/issue/MyBitFoundation/MyBit-Will.app/7/2432
![image](https://user-images.githubusercontent.com/46271233/54563086-8f969800-4985-11e9-9aec-6d597703e66d.png)

**Comment by thelostone-mc** [comment]
cc @PixelantDesign @willsputra @frankchen07
