### ISSUE TITLE
UX - As a Funder I'd like to be able to co-manage my bounties with my team members.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4000]
### User Story

As a funder I'd like to be able to co manage a bounty with my team members.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Market validated customer need. Currently there is no ability to share/co manage bounties at this time.

### Description

**New Feature: Shared Management**

This feature should allow for a user to but may not be limited to:
- Create an issue for an org - github
- Be able to manage permissions for bounties: review, approve, accept a contributor for a task
- If i’m an owner of an org, i can specify an address, regular or multisig
- This does not include paying

### Definition of Done

- [ ] Brainstorm with engineering feasibility and constraints to consider.
- [ ] A task flow is created for how this feature would work
- [ ] Screen designs are created to detail the experience steps.
- [ ] Review with 3-5 funders for feedback
- [ ] Review with green squad core team

### Data Requirements
- [ ] data metrics tbd based on the experience created
- [ ] decrease in customer complains about this particular issue

**Comment by frankchen07** [comment]
@PixelantDesign - would this help with your ticket writing on shared management for sprint 7? Moved back to Green board but let me know if that's incorrect.
