### ISSUE TITLE
Build - Backend Prompt to Capture Previous Star Ratings

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4002]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on bounties that need to be paid using advanced pay so that we can understand their experience with tasks that require multiple contributors to complete.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Build a defined Ux approach to prompt for capturing previous star ratings (email or modal)
- [ ] Review with Core team
- [ ] Annotate the end to end user experience. 

**Email Backend **

Backend
- When funder pays out send this email
- Use this email for both funder and contributor

**Modal Backend** 5
- Check to see if user has bounties to rate
- Show it first time on issue explorer 

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by willsputra** [comment]
Email:
![54613450-ad532280-4a95-11e9-95a9-4804d556ae4a](https://user-images.githubusercontent.com/19514207/54614226-053e5900-4a97-11e9-8ac2-8789be4969a5.jpg)

Modal:
![54613446-acba8c00-4a95-11e9-8543-9c4659c81252](https://user-images.githubusercontent.com/19514207/54614243-0a9ba380-4a97-11e9-8517-c5150868a04e.jpg)

**Comment by SaptakS** [comment]
Solved in #4092
