### ISSUE TITLE
Your Funded Bounty Is Fulfilled email issues

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4004]
padding on this email could use a little love 

<img width="1287" alt="Screen Shot 2019-03-19 at 12 57 53 PM" src="https://user-images.githubusercontent.com/513929/54633923-bcf74a80-4a46-11e9-85fe-762ca33e0fbe.png">

and the ‘view work’ button just takes me to `gitcoin.co`

**Comment by rafalkowalski** [comment]
You can check changes here: https://github.com/gitcoinco/web/pull/4010

**Comment by rafalkowalski** [comment]
@PixelantDesign It's already resolved. Could you close it?
