### ISSUE TITLE
As a funder, if I decide to increase the bounty amount, the % fee should still apply

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4009]
### User Story

Gitcoin Bounties % fee, if a funder decides to increase the bounty amount, the % fee still applies

### Why Is this Needed

If the % fee only applies to when a funder first opens a bounty, then a potential way to sidestep the flat rate fee would be to post a infinitesimally small $ bounty and then change the bounty amount post-funding in order to avoid the fee. 

### Description

We want to ensure that any increases in the bounty funding should be proportionally accounted for in terms of fees. 

The scope of this ticket does not include crowdfunding contributions.

### Current Behavior

@thelostone-mc - can you inform me of the current functionality to deal with this (or perhaps it doesn't exist). 

@thelostone-mc does there need to be sub-tasks, for example:

1. front-end designs on the increase bounty funding page that need to be spec'ed out?

2. confirmation email after funding increase informing them on fees charged?

### Expected Behavior

If a funder decides to increase a bounty's funding, a 10% fee applies to the additional amount that they add. 

### Data Requirements
- [ ] % fee tracked in the DB

### Definition of Done
- [x] 10% fee is triggered when the funder increases 
- [x] metamask popup is triggered for the appropriate double metamask confirmations.

**Comment by PixelantDesign** [comment]
Is this a design task or build?

**Comment by frankchen07** [comment]
design first, then build, but may de-prioritize for now as it's an edge case that people will game the system.

https://github.com/gitcoinco/web/pull/3961#issuecomment-474965633

**Comment by thelostone-mc** [comment]
@frankchen07 design is already done ! The code is more or less wrapped up :P

**Comment by thelostone-mc** [comment]
Built + Deployed
