### ISSUE TITLE
Build Front End - Prompt to Capture Previous Star Ratings Email & Modal

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4018]
### User Story

As Gitcoin, we'd like funder's and contributors to be able to provide feedback on bounties that need to be paid using advanced pay so that we can understand their experience with tasks that require multiple contributors to complete.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Does not exist now

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Build a defined Ux approach to prompt for capturing previous star ratings (email or modal)
- [ ] Review with Core team
- [ ] Annotate the end to end user experience. 

**Email  Frontend**
Front End
- Create section inside the funds paid email with a conditional.
- Remove text custom to contributor.
- Bounty information style changes

**Modal Frontend** 
Frontend 5
- Build Modal

### Metric 

- % of previous bounties (pre-release) that have backfilled ratings.
- subjective feedback from hunters and funders that they are using the ratings.

**Comment by SaptakS** [comment]
Solved in #4092
