### ISSUE TITLE
WORKSHOP - As a Gitcoin funder, users from the same organization who open bounties find it difficult to manage bounties within the team, as payout and funder actions are tied to a specific funder's account.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4022]
### User Story

WORKSHOP - As a Gitcoin funder, users from the same organization who open bounties find it difficult to manage bounties within the team, as payout and funder actions are tied to a specific funder's account.

### Why Is this Needed

This ticket is specifically to workshop shared management front-end user experience. 

UX ticket here: https://github.com/gitcoinco/web/issues/4000

Multi-signature contract wallets are being researched and discussed here: https://github.com/gitcoinco/web/issues/3993

### Description

When a funder has a bounty open and requires help to manage it, how should the experience work on the front-end? 

### Current Behavior

No method to share management of a bounty.

### Expected Behavior

A fluid way for a funder share management of a bounty to either a person within their organization or outside their organization

**Comment by thelostone-mc** [comment]
I'm assuming 
- for any payments would this heavily rely whether we update the contract or use something like gnosis wallet
- for non wallet interactions (aka funder actions) can be done indenpendent on which path we take

**Comment by thelostone-mc** [comment]
I've documted what's in my head over [here](https://gist.github.com/thelostone-mc/494fd6ffc3395de6185f96a766d4c1ee) ^_^
