### ISSUE TITLE
Filter Hackathon Prize Issues by Sponsor/Funder

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4035]
### User Story

As a hackathon participant I want to filter prize issues by sponsor/funder.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Hackers want to see all issues posted by companies they are interested in. Sponsors want to be sure that their prizes can be found if people look for them.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No way to filter issues by sponsor on the hackathon issue explorer.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Two ways to filter, which should have the same effect: a)Sidebar on hackathon issue explorer with names of all sponsors/funders b)Sponsor logos at the top of the page that can be clicked to filter.

Once filtered, only prizes posted by that sponsor should appear, and there should be some way of unfiltering that is easily accessible (so that hackers know there are other prizes available and can get back to the full list). This can involve unchecking a box on the sidebar, or clicking a link that says "See all prizes" somewhere.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- A way of clicking to filter by sponsor/funder
- Logos at the top of the hackathon page that can be clicked to filter
- A way of returning to an unfiltered view (see all prizes)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by willsputra** [comment]
first draft
![hackathon](https://user-images.githubusercontent.com/19514207/55421724-18c3e680-55a4-11e9-8926-c5046f0eb47f.jpg)

**Comment by PixelantDesign** [comment]
**Front End**
- Place logos on top
- Fetch Organization to build filter
- Send request when filter is clicked
- Logos will be manually added in the html page
- Check to hide top nav items: how it works, issue explorer, fund issue


**Estimate: 5**

**Comment by willsputra** [comment]
adjusted the size of the icons

![ethereal](https://user-images.githubusercontent.com/19514207/55563823-d247c680-5720-11e9-8f84-ca8ed1bf7bcd.jpg)

**Comment by PixelantDesign** [comment]
@willsputra could you also add to the build ticket?
