### ISSUE TITLE
as a user, i want a twitter bot to tweet when i contribute to a gitcoin grant, so i can get credit for it

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4041]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want a twitter bot to tweet when i contribute to a gitcoin grant, so i can get credit for it

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)
no tweets

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
tweets from @gitcoinfeed 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
would this be an immediate thing / weekly thing ?
Former might make it feel spammy but an easier lift
