### ISSUE TITLE
as a user, i want to share a bounty with a friend and get some ETH when they complete it.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4044]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to share a bounty with a friend and get some ETH when they complete it.

### Why Is this Needed
to increase the viral coefficient on gitcoin.
because users know their friends skillsets

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no referral reward

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
we use part of our % fee to share bounties with people and pay them for doing it

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- referral rewards advertised on site and in emails
- we can track when a referral is done and pay it out

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@vs77bb this is an idea from the r/s meeting last night

**Comment by ceresstation** [comment]
@PixelantDesign using this issue rather than making a new one for the idea of bounty referrals
