### ISSUE TITLE
Bounty didnt show up on Gitcoin.co, nor did gitcoinbot post, after transaction is confirmed

### ISSUE THREAD

**Issue by jschiarizzi** [gitcoinco/web#4052]
**Describe the bug**
[comment]: No bounty shows up in gitcoin website nor posts from gitcoinbot on the issue.

I made it in Storj tokens (which i have successfully used in bounties before) and also payed ~.08 ETH to have the bounty promoted.

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
I made a bounty:
https://github.com/jschiarizzi/storj-ipfs-gateway/issues/9
https://etherscan.io/tx/0xa5f11f4d68382ea88c42e3e2b14df78956d6105b3d2a2c2c0164ce653e61ebb7

**Expected behavior**
[comment]: # I expect to see my bounty in gitcoin.co and have gitcoinbot post on the issue page.
![Screenshot (199)](https://user-images.githubusercontent.com/9449596/55101964-bd719000-509b-11e9-97a3-90f6203661fb.png)

**Screenshots**
[comment]: # No bounty for the issue I just paid to have a bounty added to. Also couldnt find it via issue explorer.

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: Brave
- Browser Version: Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)
this is up to date.

**Comment by owocki** [comment]
@jschiarizzi are you sure that https://etherscan.io/tx/0xa5f11f4d68382ea88c42e3e2b14df78956d6105b3d2a2c2c0164ce653e61ebb7 is the correct tx?  I dont see any [input data](http://bits.owocki.com/f65049ef77ad/Image%202019-03-27%20at%2012.45.55%20PM.png) on it.  Perhaps this was a tx that you used to feature a bounty?

I dont see any transactions for `issueandactivatebounty` on [your tx history](https://etherscan.io/address/0xe4b420f15d6d878dcd0df7120ac0fc1509ee9cab)

**Comment by jschiarizzi** [comment]
It needs multiple transactions to feature it?

yes there isnt any input data, I didnt notice that. Perhaps there _should_ be?

It looks like the trx to bounties network contract failed at the same time https://etherscan.io/tx/0x0ccf14f5663420fc0c95f8663d11e7f9538dcd77a6596541632ca5e26248dfc8

**Comment by owocki** [comment]
> It needs multiple transactions to feature it?

yeah, you should get two metamask popups.  were gonna probably add a little orange dialogue ([preview](http://bits.owocki.com/b8b34e97432b/Image%202019-03-27%20at%2012.53.30%20PM.png)) soon since sometimes metamask popups don't reliably show up

the weird thing is that tx is an 'increasepayout' tx, not an `issueandactivatebounty` transaction http://bits.owocki.com/e1273d13a686/Image%202019-03-27%20at%2012.52.47%20PM.png

**Comment by jschiarizzi** [comment]
Hmmm maybe I was doing too many things at once and made a mistake. I submitted the bounty again and its live https://gitcoin.co/issue/jschiarizzi/storj-ipfs-gateway/9/2684

However, I'm not seeing it in the featured bar in the issue explorer. I'm going to leave this issue open for now, and see if it maybe it takes a while to sync that.

**Comment by thelostone-mc** [comment]
Ah we'll be rolling out the popup when there are multiple txn confirmations popup just to ensure the user doesn't end up missing it.

And sweet -> your issue now turns up on the featured bar in the explorer 

<img width="773" alt="Screen Shot 2019-03-28 at 5 34 49 PM" src="https://user-images.githubusercontent.com/5358146/55156473-0438b600-5180-11e9-9c64-19a7fd56bbea.png">

Closing this out ^_^

**Comment by jschiarizzi** [comment]
Perfect, thank you @thelostone-mc
