### ISSUE TITLE
As a funder, I want to be able to allow hunters with a specified minimum star rating to express interest in my bounties, so I can work with high quality developers

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4066]
### User Story

As a funder, I want to be able to allow hunters with a specified minimum star rating to express interest in my bounties, so I can work with high quality developers

### Why Is this Needed

Currently, funders express frustration that bounties they fund sometimes go unfinished or are not completed well. With our new star ratings feature we can gather feedback on the quality of developers. Adding a minimum star-rating filter to a bounty will ensure that a certain quality of developer is maintained, and it will incentivize hunters to complete work quickly and completely so as to maintain a high star rating.
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
When creating a bounty, there should be an option to set a minimum star rating. When browsing the issue explorer as a hunter, bounties that have a minimum star rating cannot be applied to unless my star rating is high enough.

### Definition of Done
- Add additional optional field to bounty creation to specify minimum rating and store in our database
- Disable express interest button on issue detail page with messaging if a hunter views it who's star rating is not high enough

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

I expect this to result in more completed bounties, more posted bounties, and higher star ratings for hunters.

**Comment by owocki** [comment]
i think this is somewhat attached to https://github.com/gitcoinco/web/issues/4019 -- basically how can we take contributor search and specify the criteria for users we want to work with on our bounties

**Comment by PixelantDesign** [comment]
I like the idea. My concern is it excludes new users who may be qualified but have not built up their star ratings.

cc: @frankchen07
