### ISSUE TITLE
As a network operator, let's help Codefund build their landing page.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4070]
### User Story

As a network operator, let's help Codefund build their landing page.

### Why Is this Needed

Codefund needs help. They also need a landing page.

### Description

![Codefund Landing](https://user-images.githubusercontent.com/7516920/55243106-cd07ea80-51fb-11e9-88d2-06de2d1e2d05.png)

### Current Behavior

No landing page.

### Expected Behavior

A Codefund landing page.

### Definition of Done
- [ ] Codefund landing page built out to sketch specifications

**Comment by thelostone-mc** [comment]
@coderberry / @hopsoft I assume this would be in `code_fund_ads` repo ? 

cc @frankchen07

**Comment by coderberry** [comment]
@thelostone-mc no, it’s for our Wordpress site
