### ISSUE TITLE
Kudos suggestions not working 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4071]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
Kudos suggestion request is getting an error in payout (I think was 503)  and not getting any suggestion

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
Use basic Payout in a bounty

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Suggest kudos (it was working in the past) 
**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by owocki** [comment]
hmmm seems to be working 4 me http://bits.owocki.com/c1513414bb5d/Image%202019-03-29%20at%2011.12.39%20AM.png

**Comment by octavioamu** [comment]
Thanks. I will try to reproduce again to see what are the bug conditions.

**Comment by PierrickGT** [comment]
Working for me too after trying to reproduce the bug.

<img width="555" alt="Capture d’écran 2019-03-29 à 22 03 50" src="https://user-images.githubusercontent.com/2401738/55262594-8f907500-526e-11e9-8b16-725a88c1cbff.png">

**Comment by octavioamu** [comment]
maybe is the condition when nothing is found, the one I saw it was CSS keyword, I will recheck and edit the ticket or close it.

**Comment by PierrickGT** [comment]
Yes cause a 503 error is when the server can't be reached so maybe that's what happened.
