### ISSUE TITLE
Build - Add Logos to Hackathon Landing Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4075]
### User Story

As a hackathon participant I want see logos of sponsors/funders.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Hackers want to see who is sponsoring the prizes. Sponsors want to be sure that their logos can be found if people look for them.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Display logos in two sizes on the hackathon bounties list page

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Build in two rows of logos on the bounties list page (one row of small, one row of larger)
- Upload logos in admin is okay, engineering to advise on simplest solution

### Data Requirements
TBD

Review with @PixelantDesign @alexvotofuture

**Comment by PixelantDesign** [comment]
Front end
- add logos on landing. (need all images by x date)
- add platinum and gold labels

**Estimate: 1**

**Comment by willsputra** [comment]
![hackathonlandingpage](https://user-images.githubusercontent.com/19514207/55564367-f35ce700-5721-11e9-940f-bffbc279db73.jpg)
