### ISSUE TITLE
As a Gitcoin user, my avatar is showing up as random in certain areas of the Gitcoin site.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4085]
**Describe the bug**
As a Gitcoin user, my avatar is showing up as random in certain areas of the Gitcoin site.

**To Reproduce**

Scott Moore [12:24]
Correct yeah
Go to the explorer and scroll you'll see like 20 that pop up that way

Scott Moore [21:30]
I feel like it’s probably not a huge deal but at the same time it kind of violates the consent of the user (I’m not sure how many users actually know that the randomized avatar that was generated for them is showing up in all these places) 

**Expected behavior**

Was this part of the avatar rollback that occurred a couple weeks ago? We want to make sure the randomly generated avatars aren't appearing in other parts of the site (essentially ensure that all avatars are consistent).

**Screenshots**

<img width="1263" alt="ba9b7d0d8b72b5f2faec5651b1b84d5c" src="https://user-images.githubusercontent.com/7516920/55343415-e4471200-545f-11e9-807a-78a5eb84bd68.png">

**Comment by owocki** [comment]
right now the site still creates a purple (is that whats meant as 'random'?) avatar for new signups.  i thought we only agreed not to backfill random avatars?

**Comment by ceresstation** [comment]
I do worry about creating random avatars that users haven't necessarily agreed to especially since it will be how all of their bounties show to potential hunters.

**Comment by owocki** [comment]
defer to @PixelantDesign on this one

**Comment by owocki** [comment]
15d360e20bb01f614f04d5fd24b6628f0347fbac fixes this

**Comment by owocki** [comment]
i can delete all the other purple / procedurally generated avatars if you all want

**Comment by ceresstation** [comment]
@owocki I would prefer this if possible @PixelantDesign let me know your thoughts

**Comment by ceresstation** [comment]
As an example, consider if the ethereal hackathon sponsors all had random avatars instead.

**Comment by owocki** [comment]
@PixelantDesign ^^
