### ISSUE TITLE
As a user, I want Gitcoin Grants to have different project types, so I can provide a better shot at my projects getting funded

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4090]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want Gitcoin Grants to have different project types, so I can provide a better shot at my projects getting funded

### Why Is this Needed

Right now, Gitcoin Grants is a decentralized Patreon.  As such, it works really well for projects that are already off the ground / have enough funding.

We could capture additional market share by adding additional project types to Gitcoin Grants; namely:

1. [Dominance Assurance Contracts](https://en.wikipedia.org/wiki/Assurance_contract#Dominant_assurance_contracts) -- Used to help guarantee projects get off the ground by providing a mathematically optimal crypto incentive for someone to get a project off the ground.
2 [Curved Bonding Scheme based project investments](https://medium.com/giveth/the-future-of-giving-is-crowdfunding-the-commons-ac265e3010b8) - Leverages Curved Bonding to get projects off the ground. Basically whomever donates first is issued ProjectTokens + rewarded for being early.

Similar to how [when we added Project Types to Gitcoin](https://medium.com/gitcoin/we-listened-announcing-project-types-965a02603559) we saw an explosion in different use cases, I expect that doing so for Gitcoin Grants will provide additional value for users, and possibly lead to revenue opportunities in the future.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Only 1337 Grants are allowed.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
When a grant creator funds a new grant, they will have an option to choose a project type for their grant.  The project type input field will have a tooltip that explains the different project types.

On the grant details page, a user will be able to view the different project types for this grant.  All legacy grants will be "Traditional" Grants.

For the 'Dominance Assurance contract' grant, both the grant profile + card will show how close it is to reaching its goal.

For the 'Curved Bonding' grant type, details about the Curved Bonding Token will be displayed (whats the supply -- whats the existing conversion rate, etc).

On the cancel/funding form, no changes are needed.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

The above design is implemented, allow 2-3 revisions on the designs.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
How many new grants by project type are created / funded?
How many 'lives changed' are there?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
I know it can sound daunting to see these crazy complex ideas being thrown about, but know that these ideas are hott and have a lot of momentum in the community.  Many of them remain theoretical in a lot of ways.  We can extend our lead on other projects by implementing them first + proving them out.  We can also extend our reach over the ecosystem by being a decentralized Kickstarter (not just decentralized Patreon) by integrating these project types!

**Comment by owocki** [comment]
@vs77bb @ceresstation i'd be curious for your feedback here.  since we were at RadXChange / know people from RadX.

**Comment by ceresstation** [comment]
I do think these are interesting but I personally don't think these are priority items. To me the highest priority items are finding ways to increase vitality / encourage people to share their grants more actively / give grantees more tools to interact with grantors. These suggestions have been echoed by Boris and others in the community and I can work on building them into more concrete features.

**Comment by owocki** [comment]
> to me the highest priority items are finding ways to increase vitality / encourage people to share their grants more actively / give grantees more tools to interact with grantors. These suggestions have been echoed by Boris and others in the community and I can work on building them into more concrete features.

@ceresstation got any tickets for this goal we should be prioritizing?  suggestions are good, but tickets we can prioritize are even better!  this is one i wrote yesterday https://github.com/gitcoinco/web/issues/4091
