### ISSUE TITLE
[WORKSHOP] - As a Gitcoin user, my grant contributions will go through a splitter contract and I will be charged a fee, which will be properly communicated to me.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4099]
### User Story

[WORKSHOP] - As a Gitcoin user, my grant contributions will go through a splitter contract and I will be charged a fee, which will be properly communicated to me.

### Why Is this Needed

Once the splitter contract (https://github.com/gitcoinco/web/issues/4064) is implemented, we will have to communicate the Grants fee on the front-end when a contributor is making a contribution.

The splitter contract can be expressed in a variety of ways from least to most incentivized.

1. % fee on each and every contribution.
2. minimum donation tax to Gitcoin.
3. minimum donation tax to Gitcoin, anything above a threshold will be CLR.

### Description

This is to workshop the UX and design on that communication (possible donation sliders, and designs on the story for the Grants fee.

### Current Behavior

No story and designs for how the fee with manifest on the UX, design, and front-end.

### Definition of Done
- [ ] designs for front-end engineers on what to build to properly communicate the % fee on grants

**Comment by danlipert** [comment]
Here's the new repo for the splitter contract: https://github.com/gitcoinco/Splitter

**Comment by PixelantDesign** [comment]
NOTE: The Thank you bubble appears once user has clicked on a % to contribute. If they click off of a preselected button or clears the input then the bubble is hidden.

**NO DATA**

<img width="660" alt="Screen Shot 2019-04-17 at 4 01 25 PM" src="https://user-images.githubusercontent.com/238235/56317402-a8cc6900-612a-11e9-8585-ae66bf0b0fdb.png">

**CUSTOM AMOUNT**
<img width="734" alt="Screen Shot 2019-04-17 at 4 01 36 PM" src="https://user-images.githubusercontent.com/238235/56317414-b2ee6780-612a-11e9-989e-8e896d54eae8.png">

**PRE SELECTED** 
<img width="687" alt="Screen Shot 2019-04-17 at 4 02 01 PM" src="https://user-images.githubusercontent.com/238235/56317492-e3ce9c80-612a-11e9-8c19-6b525aab8419.png">

NOTE: IF user clicks a preselected button, we also display the value in the custom input box as a confirmation.

**Comment by PixelantDesign** [comment]
Summary at the end should contain fee summary
Gitcoin bot broken heart and custom message
