### ISSUE TITLE
Clear and concise tooltips

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#410]
As a user, I'd like to see clear and concise tooltips so that I can understand exactly what each button does.
* Content scrub across the app
* Potential design to unify tooltips

# Description
Review tooltips on Explorer view > Issue and across the app.
Make the tooltip copy more concise.

# Definition of Done
- Update copy

# Reviewers
Review with @PixelantDesign

**Comment by PixelantDesign** [comment]
@vs77bb

**Comment by thelostone-mc** [comment]
Just throwing our random tooltip designs which I came across.. just to get the ball rolling

I know these are heavy but it has to be resuited for gitcoin but just laying it out there :)

- https://dribbble.com/shots/3852186-Popover-Explorations
- https://dribbble.com/shots/3778557-Seating-plan-Tooltips (This is one i like )

**Comment by vs77bb** [comment]
Here are some initial tooltip descriptions...

- **Open**: Bounty is funded and available for a new developer to come tackle
- **Work Started**: At least one developer is working on this bounty, right now
- **Work Submitted**: Code has been submitted for this bounty. Pending acceptance from the repo-maintainer
- **Work Done**: The funder has accepted the bounty submission. The staked funds have been paid
- **Expired**: Bounty was not completed by the expiration date, and is no longer valid
- **Cancelled**: Bounty was not completed and was cancelled by the bounty funder

**Comment by vs77bb** [comment]
Related... by calling it 'Cancelled' instead of 'Killed' we risk some potential confusion with Standard Bounties (where it is referenced as 'Killed')... but 'Cancelled' is clearly better from a UX persepctive

**Comment by vs77bb** [comment]
@PixelantDesign Can you define the five 'button scenarios' here and what tooltip copy you're expecting? I understand directionally where you're headed but want to be sure I understand!

**Comment by mbeacom** [comment]
@vs77bb Here's a copy of the latest tooltip merged in #585

<img width="409" alt="screenshot 2018-03-20 00 06 56" src="https://user-images.githubusercontent.com/7315957/37635600-e67de0b4-2bd2-11e8-9e50-cfc486250db2.png">

I think we might be able to close this.  @PixelantDesign ?

**Comment by PixelantDesign** [comment]
@vs77bb 

<img width="535" alt="screen shot 2018-03-20 at 1 44 41 am" src="https://user-images.githubusercontent.com/238235/37637921-b4da4dd2-2be0-11e8-9ccc-d4dd8d5923aa.png">

<img width="671" alt="screen shot 2018-03-20 at 1 45 08 am" src="https://user-images.githubusercontent.com/238235/37637927-be87260c-2be0-11e8-8310-f8e92d93824b.png">

<img width="640" alt="screen shot 2018-03-20 at 1 45 16 am" src="https://user-images.githubusercontent.com/238235/37637936-c724805c-2be0-11e8-8d4b-28c6ada8be78.png">

<img width="670" alt="screen shot 2018-03-20 at 1 46 23 am" src="https://user-images.githubusercontent.com/238235/37637940-ce2ede60-2be0-11e8-9a0d-e21697d652a4.png">

**Comment by PixelantDesign** [comment]
@mbeacom @vs77bb I've already scrubbed the flyout descriptions.

**Comment by PixelantDesign** [comment]
@vs77bb agree on Kill Bounty.
