### ISSUE TITLE
Update Pricing Section on Gitcoin.co/Funder with correct platform pricing

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4101]
### As a funder on the Gitcoin platform, I'd like to see accurate pricing reflected on the pricing section. 

https://gitcoin.co/bounties/funder

### Current
<img width="1208" alt="Screen Shot 2019-04-03 at 9 25 10 AM" src="https://user-images.githubusercontent.com/238235/55482582-d7a6f300-55f2-11e9-9460-76ce8247551b.png">

### Definition of Done

- Update pricing here since we've rolled out the 10% fee.
- This should still work in responsive mode
- Review with team

**Comment by frankchen07** [comment]
> easiest would be to hide it, and re-roll out the idea of larger communications about a fee once we’ve nailed down multiple avenues of revenue (% fee, grants fee, subscriptions, managed bounties, etc). Otherwise, I feel we’d be updating this section alot.

> if we were to communicate the fee, I would make a small section about sustainability for us (the sob story) and also the benefits of doing bounties with us (get access to our developer network). ( _if_ we were to do it though)

> Right now that pricing is completely incorrect though, my vote is to hide it, easy lift, gives us room to make changes, and removes erroneous information.
