### ISSUE TITLE
As a Gitcoin visitor, I want an easy way to get to Bounties product via the top nav.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4102]
### As a Gitcoin visitor, I want an easy way to get to Bounties product via the top nav.

Currently when you click on the Gitcoin logo, it refreshes and the user stays on the homepage.

<img width="1009" alt="Screen Shot 2019-04-03 at 11 16 47 AM" src="https://user-images.githubusercontent.com/238235/55490961-a46c6000-5602-11e9-9290-b8f54e0c79f6.png">

Expected behavior - take user to bounties page.

<img width="846" alt="Screenshot 2019-04-03 22 06 09" src="https://user-images.githubusercontent.com/238235/55491068-d7165880-5602-11e9-8d7f-d13769448a5d.png">

### Definition of Done

- [ ] Swap out the Gitcoin logo with the new Bounties logo (attached)
- [ ] Ensure logo works in responsive view

**Comment by willsputra** [comment]
svg files:
https://drive.google.com/drive/folders/1pExohyyzEF9Ijp_GdHlOjAUWEpd4F9JJ
