### ISSUE TITLE
Build - Invite to work on a bounty email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4103]
### As a user being invited to work on a bounty, I'd like to see a Gitcoin branded email so that I know that I can trust this email.

**Current**
<img width="1077" alt="Screen Shot 2019-04-02 at 1 55 04 PM" src="https://user-images.githubusercontent.com/238235/55491494-8fdc9780-5603-11e9-839e-d881b1b36f65.png">

**Expected**
![Email](https://user-images.githubusercontent.com/238235/55491685-f2359800-5603-11e9-8a80-c47b5906e3bf.png)

### Definition of Done
- Build Designed  email
- Ensure it works responsive
- Reuse existing templates
- Review with core team

Front End 2
- Build Email

Backend 3
- Send email based on which page we are promoting (invite for kudos or invite from funder)
- Make it conditional to show kudos or not

**Comment by owocki** [comment]
seems like a good a/b test candidate!  the reason we did plaintext emails is they look less marketing-ey

**Comment by PixelantDesign** [comment]
Will to provide a design without the kudos.....decide I we need that section at the bottom with a bunch of logos

**Comment by PixelantDesign** [comment]
@SaptakS please post screenshots of both version so that we can review. Thanks!
