### ISSUE TITLE
As a Gitcoin user, my grant contributions will go through a splitter contract which needs to be integrated with one-time donations (frontend only, no subminer).

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4106]
### User Story

BUIDL - As a Gitcoin user, my grant contributions will go through a splitter contract and I will be charged a fee.

### Why Is this Needed

Once the splitter contract (https://github.com/gitcoinco/web/issues/4064) is implemented, we will have to communicate the Grants fee on the front-end when a contributor is making a contribution.

Sub-task of https://github.com/gitcoinco/web/issues/4064. This is part of getting splitter contract to do what we want it to do.

### Description

**The design looks like this:**

![Screen Shot 2019-04-15 at 13 35 30](https://user-images.githubusercontent.com/7516920/56163535-66b4f300-5f83-11e9-9707-ba7ebc02cdac.png)

- hover over on the "i" button reveals our sustainability messaging
- selecting preset percentages fills in the custom box on the right hand side, which the user can change
- calculation of the DAI amount is done on the frontend
- per period will show up or not depending on the recurring option above
- sum will be updated in the text below

@PixelantDesign for any additional comments

**Sustainability messaging:**

"Building sustainable systems costs money! As Gitcoin grows we're finding new ways to help offset our team's burn. Your contribution is ultimately important to not only the ecosystem, but to Gitcoin's long term sustainability. Thanks for being with us on this journey!"

**Additional question:**

@danlipert - is the way the grant's contract is set up allow for fee return or delayed fee collection? (e.g, we "collect" the relayer fee, but only truly take it when the grant reaches a monthly contribution, otherwise we return it or some other action). This doesn't affect front-end, just hookup and implementation.

### Current Behavior

No front-end implementation on a fee for Gitcoin Grants.

### Definition of Done
- [ ] front-end design built to the specifications listed under the description

### Data Requirement
- [ ] will need to have revenue tracking set up in Metabase

**Comment by frankchen07** [comment]
@thelostone-mc designs finalized here: https://github.com/gitcoinco/web/issues/4099#issuecomment-484241638

**Comment by thelostone-mc** [comment]
Only frontend -> https://github.com/gitcoinco/web/pull/4324

#### TODO:

- wire in subminer
- double check that the right values are picked up while invoking the subminer 
- integrating subminer would happen in the same PR when blue squad takes that up

cc @danlipert
