### ISSUE TITLE
As a Gitcoin operator, I wrote a nifty splitter contract, which is OSS, so let's make a repo and have some official documentation.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4108]
### User Story

As a Gitcoin operator, I wrote a nifty splitter contract, which is OSS, so let's make a repo and have some official documentation.

### Why Is this Needed

Sub-task of https://github.com/gitcoinco/web/issues/4064.

### Description

Add documentation and make the splitter contract its own repo so others can contribute to it.

### Current Behavior

No OSS repo or documentation for the splitter contract

### Expected Behavior

Documentation and its own repo for the splitter contract.

### Definition of Done
- [x] splitter contract repo
- [x] splitter contract documentation

**Comment by thelostone-mc** [comment]
Closed out in https://github.com/gitcoinco/Splitter/pull/2
