### ISSUE TITLE
UX - Improve User Discoverability 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4120]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Funder I want to have an easy way to search and filter users so it's easy to find the best workers for my task.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done

- [ ] Ux an experience that takes into consideration the broader goal of discoverability and takes into account the work that Octavio has done on the user directory, leveraging the work that Max has done on the design side.
- [ ] Review with Core team
- [ ] User Test

Potential 
V1

- [ ] Decide where this will live (how will users get to this page?)
- [ ] X Filters by skills is Implemented
- [ ] X Pagination is Implemented
- [ ] X Add a Search Bar at the top (pull from Kudos)
- [ ] X - ability to quickly see quality rating at a glance
- [ ] X - ability to invite to my bounty inline

Post V1
- get data from the leaderboard into the cards 
- autocomplete filters from an github issue (that can be reused to improve fund form)
- geo filters
- sort by newest, quality, alphabetical
- Filter by job status
- Leaderboard fields filter 

### Data Requirements
- [ ] before we discuss success of the feature, I think there are some data elements that are important to discuss in terms of what kinds of metrics funders would like to see on bounty hunters, and what they would find useful (avg time to start, work on, and complete bounties, as an example)

**Comment by willsputra** [comment]
for reference

Max's design
https://github.com/gitcoinco/web/issues/3956#issuecomment-478737507

**Comment by willsputra** [comment]
draft
https://sketch.cloud/s/ww0Kl/PGVK1b8/play

**Comment by willsputra** [comment]
flow:
![Discoverability-Invite](https://user-images.githubusercontent.com/19514207/56294347-6ff9b780-615d-11e9-868b-1ab849e7c6f4.jpg)

if the user has no issue funded:
![no issues](https://user-images.githubusercontent.com/19514207/56294381-80aa2d80-615d-11e9-9b1d-caed9e9341ea.jpg)

if the user is not logged in:
![not logged in](https://user-images.githubusercontent.com/19514207/56294399-87d13b80-615d-11e9-9554-0bd1a4cde948.jpg)

**Comment by PixelantDesign** [comment]
- Remove second progressive step
- add link to list view
- remove invite buttons for users that have 0 issues funded
- if user is not logged in, we hide the button

**Comment by willsputra** [comment]
latest flow based on discussion.
• truncate names if they're too long
• skillset tags can be in two rows
• if there's no real name, use their username

![Discoverability-Invite](https://user-images.githubusercontent.com/19514207/56307308-21591700-6177-11e9-83ab-4df71bcb6bed.jpg)

**Comment by willsputra** [comment]
Sketch file
https://github.com/gitcoinco/creative/blob/b39eddf942cfefd66b45a70d46d4092900e42d4f/Product/User%20Explorer/UserExplorer-InviteNoFilter.sketch
