### ISSUE TITLE
as a funder, i want to pay a subscription instead of a 10% fee, so i can be rewarded for coming back

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4148]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder, i want to pay a subscription instead of a 10% fee, so i can be rewarded for coming back

### Why Is this Needed
see #product-feedback channel

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
10% fee

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

if a user subscribes to https://gitcoin.co/grants/86/gitcoin-sustainability-fund , then they will pay a lesser fee.

proposed initial levels:
10 DAI / mo => 7% fee
30 DAI / mo => 5% fee
50 DAI / mo => 3% fee
75 DAI / mo => 1% fee
100 DAI / mo => 0% fee

plan name: Gitcoin promote

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

MRR -- monthly recurring revenue

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
@owocki @PixelantDesign @frankchen07 @vs77bb The PR here: https://github.com/gitcoinco/web/pull/3878 , combined with Aditya's frontend PR provides a minimal UI for users to pay for a monthly subscription. Please check my notes in that PR for next steps to launch this feature as well as the shortcomings and additional design and coding work to make this feature more usuable. Beyond that, it would be a matter of checking the users subscription information to determine their fee. Right now, this would only support a binary fee, so a user is either a) a free user, pays a 10% fee or b) a paid user, pays a x% fee (to be determined)

**Comment by owocki** [comment]
what if we call this subscription plan "Gitcoin Promote", after [Twitter Promote](https://business.twitter.com/en/solutions/twitter-promote-mode.html) -- concisely describes the value of having a gitcoin subscription -- promotion to devs

**Comment by danlipert** [comment]
@owocki Interesting, I had not seen this Twitter feature before but I like it - could bundle some promotional features in as well? (roundup placement, bounty alert placement, etc.?)

**Comment by owocki** [comment]
yes i think we could / should.  its super useful for not having to pick/manage individual tweets (bounties) to promote, it just amplifies them all  curious what @PixelantDesign thinks

i've been testing it on my twitter account just to understand it better and maybe amplify our presence.  here's what their dashboard looks like => 
![image](https://user-images.githubusercontent.com/513929/56139090-6271e100-5f55-11e9-9c25-555e61860bf3.png)

as an aside, it doesnt look like promote works well for me on twitter :P

**Comment by ceresstation** [comment]
I would add to this that it might be nice to frontload bounty payments via the subscription model, allowing someone to pay for up to `$x` of bounties in DAI without having to sign a MetaMask transaction at all. Instead, we'd store the funds provided in an account we control and 'pay them out' to the bounty when the user desires. This may be a high LOE initiative versus the expected benefit though.
