### ISSUE TITLE
Add Flag to Leaderboard

### ISSUE THREAD

**Issue by aashutoshrathi** [gitcoinco/web#4152]
### What 

The current leaderboard just has country names with their respective bounties count.
We can make it more user-friendly by adding a flag of the country ahead of their name.

![image](https://user-images.githubusercontent.com/21199234/55767457-a3ba4a80-5a96-11e9-8a29-7b1da9e1e30e.png)

### Why

It will be convenient for the user to search for the country and will give better UX.

**Comment by hydr063n** [comment]
@thelostone-mc  Hi. I want to point out some issues I found while testing on live site.

1. I saw it working a few week back but some of the country names are not mapped correctly in the data file. I figured we could extend to a new PR so as to fine tune the render. All that's needed to is to match the country names that gitcoin uses to a country abbreviation in the data file.

2. I think another commit may have changed the frontend code during a loop so its currently not rendering the flag. I zipped the flags with the items list as I needed a parallel list but now only the items list is being traversed in the loop. I think the name may have been confused. Might be better to rename the list to much more understandable name like `items_and_flags`
![zipped list not used in loop] (https://i.imgur.com/JoEX93A.png "zipped list not used in loop")
![zipped list not used in loop] (https://i.imgur.com/JoEX93A.png "zipped list not used in loop")

I will be happy to extend the extra work into a new PR. Anyway, the pull request has been merged, will I receive a tip for this PR?
