### ISSUE TITLE
As a user, I want gitcoin.co/dashboard to exist, so I can have a homebase for all my Gitcoin activities, so I can know how to take actions on Gitcoin, with limited time / attention.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4153]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want gitcoin.co/dashboard to exist, so I can have a homebase for all my Gitcoin activities.

## hypothesis

If __users have an "at a glance" way of watching their 
items of interest on gitcoin then they will be more engaged / have higher retention bc there is higher ROI of viewing things at 100k ft .

### Why Is this Needed

As we've grown and evolved, I've become increasingly concerned with the follow questions: 
	- How do we go from bounties => all products
	- How do we put funder / user relationship at center stage?
	- How do hold peoples hands until we get there?
	- Why is there no central place to track all your Gitcoin activities?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No Dashboard

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
A page at Gitcoin.co/dashboard that is the center of your existence on Gitcoin.  It will have 

0. A BIG input box up top, which will allow you to view funder view or coder view.  Once (0) is processed, any outstanding actions that you must take will be displayed up top.  A link to your unread notifications will be here too.
1. Profile completeness info, per https://github.com/gitcoinco/web/issues/3954
2. All of [these](http://bits.owocki.com/a2fce0e30f68/Image%202019-04-08%20at%208.12.51%20PM.png) navigation items should be listed here, in a consolidated view.
3. A referral code that you can use to earn free bounties.
4. A bounties section, with a link to bounties that match to you (if coder). Or a link to your bounties if you're a funder.
5. A grants section, with links to your grants, or grants that match your interests
6. A link to your most recent kudos (or if you have none, a link to suggested kudos).  The most recent "free kudos friday" will also be displayed here.
7. Once we launch subscriptions, a link to which plan you're on.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

Also, special care should be taken to make sure that the dashboard is performant.

### Data Requirements
Increased LTV
Increased short and long term funder/contributor retention

### Reach
All funders or contributors that have actions to take on the platform

### Impact
High Impact 

### Confidence 
80%

**Comment by owocki** [comment]
binance dashboard for inspiration http://bits.owocki.com/5391bea66892/Image%202019-04-10%20at%202.43.58%20PM.png

**Comment by willsputra** [comment]
@PixelantDesign thoughts?
![Dashboard2](https://user-images.githubusercontent.com/19514207/57627483-a98dd900-75ca-11e9-9191-2cad5fb5523b.png)

**Comment by octavioamu** [comment]
nice! 
I have some points to discuss/ask are we going to do a call about this feature?

**Comment by willsputra** [comment]
yeah I think we can discuss this tomorrow!

**Comment by willsputra** [comment]
Different tabs:

Bounties/Contributor
![Artboard Copy 5](https://user-images.githubusercontent.com/19514207/58640933-b9c4e880-832c-11e9-83ea-d923544211d4.png)

Bounties/Funder
![Artboard Copy 6](https://user-images.githubusercontent.com/19514207/58640940-bf223300-832c-11e9-9beb-27f26dfe7338.png)

Kudos
![Artboard Copy 7](https://user-images.githubusercontent.com/19514207/58640950-c8ab9b00-832c-11e9-95c8-d2ad3ae248df.png)

Grants/Contributor
![Artboard Copy 9](https://user-images.githubusercontent.com/19514207/58640959-cf3a1280-832c-11e9-9269-7f44eb171482.png)

Grants/Owner
![Artboard Copy 10](https://user-images.githubusercontent.com/19514207/58640974-d5c88a00-832c-11e9-9782-b3f73221b9b3.png)

**Comment by octavioamu** [comment]
@willsputra can you post the document?

**Comment by willsputra** [comment]
@octavioamu here you go!
https://github.com/gitcoinco/creative/blob/de2c62e75331f3f2bfe1191226abc056b7e9ad63/Product/Dashboard/Dashboard%20v2.sketch

**Comment by octavioamu** [comment]
@willsputra oh I mean the document with the ideas we discussed.

**Comment by willsputra** [comment]
@octavioamu here you go!
https://docs.google.com/spreadsheets/d/107RHPexhs33DiV3SV3KubaX68wTG2LDaWUA3CJ12ftE/edit?usp=sharing

**Comment by frankchen07** [comment]
some comments as they come:

for the notifications section, I think should be a mark as read option, so they don't necessarily have to click through all of them in order to "mark all as read"

clicking anything on the dashboard should open a new window

the notifications area should be larger

the "bounties in progress" section in different looking sections looks a little bit awkward

users matching your bounties & matching your skills > rate your bounties, I would change the order

**Comment by PixelantDesign** [comment]
![Bounties-Funder](https://user-images.githubusercontent.com/238235/59191007-469d4c80-8b4c-11e9-9edc-3be940548d44.jpg)

![Bounties-Contributor](https://user-images.githubusercontent.com/238235/59191011-48ffa680-8b4c-11e9-8aab-95ae616157ac.jpg)

**Comment by owocki** [comment]
we should perhaps take another pass at this with more of a lense on what funders WANT out of a dashboard (and contributors, for their dashboards..).  ..   

# funders
have we showed these to any funders?  what do the yorke rhodes of the world want out of the dashboard?  what do we want new funders to see?  existing funders?

# contributors
what contributors on the platform can we show this to?  what do new contributors, existing contributors want to see?

i'll take ownership of not having a good sense of this when i wrote the ticket.    given that the high level strategy is becoming more funder-focused... we'll want to ask some of the questions here in terms of funder activation (and the new ideas around that within)

**Comment by PixelantDesign** [comment]
We have a lot of feedback from the community slack from contributors. We started capturing feedback from Katie/labs funder last week, and will continue getting feedback from funders this next sprint.

**Comment by willsputra** [comment]
latest iteration of funder dashboard
![Bounties-Funder Copy 3](https://user-images.githubusercontent.com/19514207/59443638-843cf680-8e26-11e9-9a4f-5424efdcc83d.jpg)

**Comment by owocki** [comment]
whats with the whitespace on the right?  seems like 'complete your profile' is just missing now + the whitespace looks weird.  why not extend the main module to be the full width of the screen if we consciously removed all of the items in the right side...

why is there an expired bounty under 'active bounties'?

is there another rev of the contirbutor module?

**Comment by kuhnchris** [comment]
On the right i think there were ideas to put "hot topics" like stuff that needs intermediate action - aside from that looks good to me already. I just hope the data model can handle all of this... else we'd need to add some views.

**Comment by willsputra** [comment]
Another rev on the funder dashboard:

Collapsed
![Dropdown-Collapse](https://user-images.githubusercontent.com/19514207/59703499-2f352200-9224-11e9-9e60-23013a737c96.jpg)

Loading (maybe we could use the same loading animation from the Issue Explorer?)
![Dropdown-Loading](https://user-images.githubusercontent.com/19514207/59703529-3d833e00-9224-11e9-81d0-771e6ac149d5.jpg)

Revealed
![Dropdown-Reveal](https://user-images.githubusercontent.com/19514207/59703538-4116c500-9224-11e9-8cbd-fb39c8351533.jpg)

Some considerations for putting Expired bounties as active: 1) There are still actions that contributors can do on expired bounties, and 2) Funders are sometimes not aware if their bounties are expired.

@PixelantDesign what do you think?

**Comment by willsputra** [comment]
Some points from funder feedback:
• Funders should land on dashboard everytime after login
• Sort by actions needed, and recent below that
• Expired belongs in inactive session
• Reminder that no applicants or increase funds on a bounty would be helpful

**Comment by ceresstation** [comment]
Have we considered also allowing users to view bounty hunters they've favourited on their dashboard cc @PixelantDesign? 

If I come across an issue with no active applicants it might be nice for me to look through contributors I like and invite them. This could also be done via the bounty page.

**Comment by PixelantDesign** [comment]
Good idea! @ceresstation we could put it in as a concept to test.
