### ISSUE TITLE
As a user, I want the bounties nav decoupled from the broader Gitcoin nav, because Gitcoin != bounties.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4154]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want the bounties nav decoupled from the broader Gitcoin nav, because Gitcoin != bounties.

### Why Is this Needed
Gitcoin != bounties

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
As a user, I want the bounties nav decoupled from the broader Gitcoin nav, because Gitcoin != bounties.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Gitcoin on the nav leads to bounties.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Bounties logo (see below) is where the existing Gitcoin logo is.
- Gitcoin on the nav leads to a 'neutral ground', where pages that are non-product specific (homepage, products page, dashboard page, can live)
- Remove labs logo and put it under said 'neutral ground'.  This will make more room on nav

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
bounties logo http://bits.owocki.com/7cf20f2e6fb4/Group.svg

**Comment by PixelantDesign** [comment]
We have in the works - swapping the logo this sprint.

**Comment by owocki** [comment]
by 'neutral ground' i meant that pages that are gitcoin-wide like 'products' ‘mission’ and ‘about’ should be on gitcoin logo / nav territory, not "bounties" territory.  i actually just made this change last night on master.
