### ISSUE TITLE
As a user, I want Gitcoin Grants to have different project types, so I can provide a better shot at my projects getting funded

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4158]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I want Gitcoin Grants to have different project types, so I can provide a better shot at my projects getting funded

### Why Is this Needed

Right now, Gitcoin Grants is a decentralized Patreon.  As such, it works really well for projects that are already off the ground / have enough funding.

We could capture additional market share by adding additional project types to Gitcoin Grants; namely:

1. [Dominance Assurance Contracts](https://en.wikipedia.org/wiki/Assurance_contract#Dominant_assurance_contracts) -- Used to help guarantee projects get off the ground by providing a mathematically optimal crypto incentive for someone to get a project off the ground.
2. [Curved Bonding Scheme based project investments](https://medium.com/giveth/the-future-of-giving-is-crowdfunding-the-commons-ac265e3010b8) - Leverages Curved Bonding to get projects off the ground. Basically whomever donates first is issued ProjectTokens + rewarded for being early.
3. [cDAI token staking](https://twitter.com/DustinTownsend/status/1148248629691453441)

Similar to how [when we added Project Types to Gitcoin](https://medium.com/gitcoin/we-listened-announcing-project-types-965a02603559) we saw an explosion in different use cases, I expect that doing so for Gitcoin Grants will provide additional value for users, and possibly lead to revenue opportunities in the future.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Only 1337 Grants are allowed.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
When a grant creator funds a new grant, they will have an option to choose a project type for their grant.  The project type input field will have a tooltip that explains the different project types.

On the grant details page, a user will be able to view the different project types for this grant.  All legacy grants will be "Traditional" Grants.

For the 'Dominance Assurance contract' grant, both the grant profile + card will show how close it is to reaching its goal.

For the 'Curved Bonding' grant type, details about the Curved Bonding Token will be displayed (whats the supply -- whats the existing conversion rate, etc).

On the cancel/funding form, no changes are needed.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- The above functionality is put into the gitcoin co dapp.
- A dominance assurance smart contract is created and integrated into the dapp.
- A curved bonding smart contract is created and integrated into the dapp (this is bonus points -- dominance assuance contracts is MVP)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
How many new grants by project type are created / funded?
How many 'lives changed' are there?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
I know it can sound daunting to see these crazy complex ideas being thrown about, but know that these ideas are hott and have a lot of momentum in the community.  Many of them remain theoretical in a lot of ways.  We can extend our lead on other projects by implementing them first + proving them out.  We can also extend our reach over the ecosystem by being a decentralized Kickstarter (not just decentralized Patreon) by integrating these project types!

# Judgement criteria

- purdy design which matches gitcoin's style guide ( [see one](https://gitcoin.co/presskit) [and two](https://github.com/gitcoinco/creative)
- intuitive UI
- integrated into the gitcoin webapp (this repo)
- responsiveness
- secure (or note where you think the security holes might be)

as such, we belive a successful team should have at least one designer + one dev.

# Milestones

We believe that the following milestones will be important for you to sync with us on during the hackathon process.

1. Application
2. Mock up
3. Designs
4. Prototype

**Comment by cmditch** [comment]
👍
