### ISSUE TITLE
[View signed NDA] opens file save dialog with wrong file name generated

### ISSUE THREAD

**Issue by aahutsal** [gitcoinco/web#4163]
**Wrong file name**
[FileName]: # (File name generated contains *false,false,false.html*.)

**To Reproduce**
[1]: # (On any bounty with NDA requested click [View Signed NDA] button)
[2]: # (See ;))

**Expected behavior**
Correctly generated file name

**Screenshots**
![image](https://user-images.githubusercontent.com/1643117/55812256-528c7400-5af3-11e9-9780-0d97806e5bce.png)

**Desktop (please complete the following information):**

- OS: Gentoo Linux, 4.19.27-gentoo-r1 #4 SMP Fri Apr 5 19:36:52 EEST 2019 x86_64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz GenuineIntel GNU/Linux
- Browser Google Chrome Stable 
- Browser Version 73.0.3683.86

**Comment by octavioamu** [comment]
Thanks @gutsal-arsen can you post the bounty link?

**Comment by gutsal-arsen** [comment]
@octavioamu [sure](https://gitcoin.co/issue/Giveth/giveth-dapp/740/2765)

**Comment by octavioamu** [comment]
I believe this will be fixed with #4151 deployment, should happen in a couple of days

**Comment by gutsal-arsen** [comment]
@octavioamu how to proceed with current bounty? seems it will stuck for couple of days for everyone.

**Comment by octavioamu** [comment]
With https://gitcoin.co/issue/Giveth/giveth-dapp/740/2765 ? this bug is not interfering with this, looks like the funder  just didn't approve nobody yet.

**Comment by gutsal-arsen** [comment]
@octavioamu well, shouldn't we sign and NDA? If so, should we download it?

**Comment by thelostone-mc** [comment]
Ah @gutsal-arsen you are right ! The NDA file seems to be corrupted.
The team is looking into it. Will ping you with an update! Thanks for raising this :)

Parallely we'll ping the bounty owner and give them a heads up too

**Comment by octavioamu** [comment]
> @octavioamu well, shouldn't we sign the NDA? If so, should we download it?

No, there is not nda, that is just for private repos

**Comment by thelostone-mc** [comment]
Fix is over at https://github.com/gitcoinco/web/pull/4151 which is merged in ! 

Sorry about the confusion. 
I assumed this was a private repo bounty
