### ISSUE TITLE
Trying to cancel an expired bounty results in error "No active funded issue found at this address. Are you sure this is an active funded issue?"

### ISSUE THREAD

**Issue by knocte** [gitcoinco/web#4171]
This 2.3 ETH bounty has expired:

https://gitcoin.co/issue/diginex/geewallet/15/1676

(Even though it's still shows up as "OPEN ISSUE", somehow.)

As you can see there are some submissions. One of them was fake probably because it didn't include any link to any PR. Other work submitted had incomplete work. Other worker started and stopped work without submitting anything IIRC.

Now if I try to cancel it, I get the error message: "No active funded issue found at this address. Are you sure this is an active funded issue?"

Please help me cancel this bounty. If this bounty is kept open it might be picked up by devs.
Thanks

**Comment by PixelantDesign** [comment]
thanks for the report!

**Comment by thelostone-mc** [comment]
@knocte Ah so we just tweaked the UI a bit an hour ago.

<img width="970" alt="Screen Shot 2019-04-12 at 2 23 22 AM" src="https://user-images.githubusercontent.com/5358146/55992435-2d9e2980-5cca-11e9-99a5-bb7437ed69dd.png">
 
The reason why you can't cancel :

- Bounty expiration is stored on the blockchain, when you try canceling an expired bounty, the check kicks in and prevents bounty creator from canceling it
- Could you try extending the expiration date and then try canceling it? 
- PR links were made optional cause a few times we do end up bounties which is beyond coding (aka there is no PR in existence )

**Comment by owocki** [comment]
this bounty was marked as 'open' because someone set the override status to 'open'

http://bits.owocki.com/e5d6246a8b5a/Image%202019-04-11%20at%204.44.22%20PM.png

i just removed the override status and its back to 'canceled' now

**Comment by owocki** [comment]
@knocte can you confirm you got your ETH back when it was canceled?  looks like the bounty has been canceled and the ETH was returend to you at https://etherscan.io/tx/0x1f98c2c82fe2f6c8282f012e116a01377da8318d19c4825413754b9da721dd8d
