### ISSUE TITLE
Contributor landing pages urls are broken

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4172]
### Problem
Contributor Landing Page URLS broken

### Definition of Done
Old versions need to be redirected to new versions (google still finding old ones)   https://gitcoin.co/contributor/python/ ----takes user to 404

Marc needs links to all the versions 
And the Meta Data for those new contributor pages needs updating according to this doc

**Comment by thelostone-mc** [comment]
Has been addressed !

**Comment by marc-at-consensys** [comment]
Also, just found references to the old broken links in the xml sitemap (https://gitcoin.co/sitemap.xml) . Can we update that file within the same ticket? 
https://gitcoin.co/contributor/
https://gitcoin.co/contributor/design
https://gitcoin.co/contributor/html
https://gitcoin.co/contributor/rust
https://gitcoin.co/contributor/ruby
https://gitcoin.co/contributor/javascript
https://gitcoin.co/contributor/python
https://gitcoin.co/contributor/solidity
https://gitcoin.co/contributor/css

**Comment by thelostone-mc** [comment]
@marc-at-consensys Ah it's already been pushed live ^_^ 
All those redirect successfully
