### ISSUE TITLE
Update Gitcoin.co Homepage Title

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4174]
Update Gitcoin.co Homepage Title

**Current**
<img width="550" alt="Screen Shot 2019-04-10 at 9 43 32 AM" src="https://user-images.githubusercontent.com/238235/55959019-eff0c080-5c37-11e9-8bbd-46392290bd09.png">

**Recommended**

Title: Open Source Dev Tools, Bug Bounties & Community Resources

Sub Copy: Gitcoin lets you get paid for working on open source software. Build new skills, make new relationships, earn kudos, and get paid for the work you already love.

CTA Button: Fund an issue
CTA Button: See our products

### Definition of Done

- Homepage H1 header and sub copy is updated
- CTAs are updated
- Review with marketing core team

Refer to this doc:
https://docs.google.com/document/d/1EAjRYbJt7J26oQcBGhyXRSMouA6h4m8zWeOFfFj252s/edit?usp=sharing

**Comment by thelostone-mc** [comment]
<img width="1367" alt="Screen Shot 2019-04-11 at 7 43 00 PM" src="https://user-images.githubusercontent.com/5358146/55964258-0af01e80-5c92-11e9-8f20-619f857e614e.png">
