### ISSUE TITLE
rounding issue on the new bounty page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4181]
http://bits.owocki.com/8535b307b32f/Image%202019-04-11%20at%2010.56.35%20AM.png

**Comment by owocki** [comment]
fix this rounding issue.  maybe round to 3 decimal places

**Comment by pandyamarut** [comment]
@owocki Please assign.

**Comment by owocki** [comment]
@pandyamarut i cant assign u since ur not on the repo. but feel free to start work! anyone else seeing this, pls check with @pandyamarut before u start

**Comment by thelostone-mc** [comment]
@pandyamarut / @owocki I'd recommend round them to 4 decimal places using `.toFixed(4)` as that's what we are rounding off the other amounts !
Ensure this change gets added to both `increase_bounty.js` & `new_bounty.js`

Do attach screenshot of the change and we'll get it in ^_^

**Comment by pandyamarut** [comment]
@thelostone-mc  got it. :+1:

**Comment by pandyamarut** [comment]
@thelostone-mc ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint web_redis_1 (8ee787512e5a28ff3cf4b6d8fd9d0e420963e7927d63b1edcb04a2cdba6bf437): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use
ERROR: Encountered errors while bringing up the project.
^^^ I repeatedly tried killing the process but still it throws the same error. 
Can you help me encounter this error?"" @owocki @thelostone-mc

**Comment by thelostone-mc** [comment]
Hmm I've not this seen this !
I'm assuming you've double checked nothing is running on that right ? 

Could you purge the containers & run `docker-compose down --build` 
cc @SaptakS have you seen this ?

**Comment by pandyamarut** [comment]
@thelostone-mc Yes I checked multiple times.

**Comment by pandyamarut** [comment]
@SaptakS @thelostone-mc Can you help me encounter this error?

**Comment by thelostone-mc** [comment]
Hmm I'm not able to reproduce this 😓 
@danlipert / @owocki

**Comment by danlipert** [comment]
@pandyamarut Uppercase P in the command - but basically I'm trying to figure out whats bound on your system to 6379

**Comment by thelostone-mc** [comment]
Btw this issue of rounding the numbers has been resolved ! It was popping up and folks were reporting it so had to throw in the fix a while back 😓
