### ISSUE TITLE
bug - incorrect wording in grant "thank you" email

### ISSUE THREAD

**Issue by cmditch** [gitcoinco/web#4184]
Upon making a **one time, non reoccurring grant**, I received two emails. The "Your Gitcoin Grants contribution was successful!" email worded the grant amount correctly, but the "Thank you for supporting Grants on Gitcoin!" email did not, as it said my one time grant would happen every 30 days. See below:

-------

**"Success" email**
![image](https://user-images.githubusercontent.com/15849320/55997707-b42a1b00-5c78-11e9-910e-b9a2ac895550.png)

-------

**"Thank you" email**
![image](https://user-images.githubusercontent.com/15849320/55997669-8b098a80-5c78-11e9-985a-6d185acb6c30.png)

-------

**Gitcoin Profile**
![image](https://user-images.githubusercontent.com/15849320/55997681-98267980-5c78-11e9-9092-8f56ef14485a.png)

Cheers!

#shillcolorado #shilllouisville #shillthehottesttowninblockchain

**Comment by Solexplorer** [comment]
@thelostone-mc I tried to replicate this issue but it seems that it has been already solved
