### ISSUE TITLE
Segment Email List (Funders & Contributors)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4190]
**User Story**
As a Gitcoin team we'd like to segment our population between funders and contributors.

*Why*
We'd like to be able to send target marketing messages based on your role.

**Definition of Done**
- [ ] Decide Data approach on segmenting email list @frankchen07 
- [ ] Segment the list based on data approach (engineering)
       Create two email lists

- [ ] Provide the list to Dean

**Comment by frankchen07** [comment]
seems like I already did it for Dean

https://metabase.gitcoin.co/question/272

active bounty hunter (did a bounty in the last 90 days)
not active bounty hunter (started work at some point, but didn’t complete a bounty in the past 90 days

funders (those who have funded bounties)

users (those who have done nothing except give us their email)

**Comment by owocki** [comment]
we should preload this data into the database so each user is explicitly tagged as a coder or funder.. then allow users to switch back and forth in their settings (and/or in their emails)
