### ISSUE TITLE
Design - Empty State for kudos on profile page

### ISSUE THREAD

**Issue by MaxStalker** [gitcoinco/web#4191]
**Describe the bug**
SVG images inside empty kudos state have incorrect text alignment and incorrect font. Besides it doesn't allow option for translation.

**To Reproduce**
You can check profile page of any user who haven't sent or received kudos (let's say https://gitcoin.co/profile/maxstalker )

**Expected behavior**
Text inside hex containers is center aligned, font face "Muli" or sans-serif as a fallback

**Screenshots**
![current-profile-kudos](https://user-images.githubusercontent.com/3136647/56047691-a8a92380-5d4e-11e9-891c-3899a786fc0e.jpg)

**Desktop (please complete the following information):**

- OS: Windows10
- Browser Chrome
- Browser Version 73.0.3683.103

**Comment by PixelantDesign** [comment]
Thanks @MaxStalker want to help us fix?

**Comment by MaxStalker** [comment]
@PixelantDesign this one is covered in my PR:
https://github.com/gitcoinco/web/pull/4192
