### ISSUE TITLE
As Gitcoin, we want to direct organic traffic to our blog instead of medium. 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4196]
### User Story

As Gitcoin we'd like to take all of articles on medium and summarize them down to 2-3 paragraphs.

### Why Is this Needed

In order to grow our organic traffic, we want to link these articles to the Gitcoin blog.

### Description

*Type*: Enhancement

### Current Behavior
Full Articles Posted

### Expected Behavior
Each article should be shortened and summarized in 2-3 paragraphs with links to appropriate article on the Gitcoin.co blog.

### Definition of Done
- [ ] Shorten all blog posts from and link to our internal blog.
- [ ] Review with Marc Beharry

### Data Measurements
Increased top of funnel contributors and funders
Decreased amount of engineering support required for email campaigns
Enable testing on email campaigns (activation/retention)

### Reach
potentially unlimited

### Impact
medium impact

### Confidence 
75%

**Comment by marc-at-consensys** [comment]
Note, we also have to link back to the full article on the internal Gitcoin blog from the articles on medium we are cutting.
