### ISSUE TITLE
"Share" Link Broken

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4197]
**Describe the bug**
The link that is being shared with the "Share" function is invalid.

**To Reproduce**
Go to a bounty, for example:
https://gitcoin.co/issue/gitcoinco/skunkworks/97/2807
Click the "Share" button:
![grafik](https://user-images.githubusercontent.com/761911/56063265-1a916500-5d6f-11e9-8284-909c183c2bf9.png)
Check out the weird link:
![grafik](https://user-images.githubusercontent.com/761911/56063286-2e3ccb80-5d6f-11e9-8921-f90acbc33e82.png)
Example:
https://gitcoin.co/issue/WDk2Z1JBVnZ3eDUydVM2dzRRWUNVSFJmUjNPYW9CMTE4NzU= 
This one sends you straight back to /explorer. :-(

**Expected behavior**
Link to the bounty

**Screenshots**
see above

**Desktop (please complete the following information):**
- Windows, Chrome, latest-stable

**Comment by Skyge** [comment]
Obviously this is a problem caused by redirection address, but as for the reasons, it may be related with the type of bounty.

**Comment by SaptakS** [comment]
You are supposed to get that "weird" link because it is an invitation link. As of why it takes it where it takes it, need to check.

**Comment by kuhnchris** [comment]
I kind of got a lead on this: it's really picky about having to add a space and where not. So maybe there is a rouge blank space somewhere. Also, it seems to sometimes adds a " #refferer" and sometimes not. It's really weird. It's also connected to the dashboard/utils.py

**Comment by Skyge** [comment]
I am not sure yet, but I think `refferer` is a keyword in some measure.
```
{% for keyword in bounty.keywords_list %} #{{keyword}}{% endfor %}
```
in 
```
<textarea>Check out this bounty that pays out 
    {{bounty.get_value_true}}
     {{bounty.token_name}} 
    {{invite_url}} 
    {% for keyword in bounty.keywords_list %} #{{keyword}}{% endfor %}
</textarea>
```

**Comment by Skyge** [comment]
I find that this kind of bounty is not generated by `Fund Issue`, so it will not show at `https://gitcoin.co/explorer`, so how can I make such kind of bounty?

**Comment by kuhnchris** [comment]
Ah, that may be because it is a special "hackathon" issue. For that we may need support from @owocki or whomever implemented that special case.
