### ISSUE TITLE
To see only open issues

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#420]
As a user I'd like to see only open issues that have nobody currently working them, so that I can clearly see the work that is available to me.

# Description
Make interim improvements on how to make it clear for users that work is available.

https://docs.google.com/document/d/184kZSHsB2enyUlzxKFEb8yUSr7o4g8eg1xPpUs11hSU/edit?usp=sharing

# Definition of Done
Design is created and revision is implemented in code.

# Reviewers
Review with @owocki @PixelantDesign

**Comment by vs77bb** [comment]
Truly ***Open Issues*** currently in ***Work Started*** 

Example in 'Work Started': Gitcoin Security Bounties [#38]

### Recommendation
After a 48 hour period, if there is no comment on the Github thread from the developer, return the issue to an 'Open' status on Gitcoin.

**Comment by vs77bb** [comment]
@owocki Does this one make sense to you? We think it's high priority...

**Comment by owocki** [comment]
i strongly agree that this is a high priority to figure out.  

two comments about implementation:

1. i think that 48 hours might be a little aggressive.  should we let the user know that we expect a comment from them?  where?   if another 48 hours passes after their first comment and we don't hear from them after that, do we take action then too?  or only for the first comment
2. https://github.com/gitcoinco/web/issues/455 is very important, and i think that it should probably go in with the above change.

**Comment by mkosowsk** [comment]
@owocki at the risk of being bold, I think 48 hours is not aggressive enough and would recommend 24 hours or having a plan to move to 24 hours.

If a developer starts work I think posting a quick comment talking about their approach/plan of attack in the first 24 hours will (1) provide a focus to their work if they have to put their thoughts down on paper, (2) allow them to receive feedback on their approach, and (3) weed out people that aren't as serious in starting work that they won't finish.

I think this check would be best for the first comment, and then perhaps leaving it up to the funder to check in after that.

**Comment by PixelantDesign** [comment]
I think 48 hrs seems reasonable and also agree with the points @mkosowsk has outlined.

**Comment by owocki** [comment]
ok; i see your point.  but how do we communicate to them that they MUST comment back and start work that quickly?   note: that the current 'start work' gitcoinbot comment asks them to do this, but many don't follow this instruction

**Comment by vs77bb** [comment]
Recommended restructure of initial Gitcoin Bot comment to something like the below: 

> Work has been started on the 0.03 ETH (28.14 USD) funding by:
> 
> 1. @Gitcoiner
> 
> If you are on the top of the above list, please comment ***within 24 hours*** to coordinate delivery of the issue scope with the funder (@GitcoinFunder). As a general rule; if you start work first, you'll be at the top of the above list, and should have 'dibs' as long as you follow through. If you do not either comment or start work within 24 hours, Gitcoin Bot will remove you from the list and either re-open the issue or assign it to the next Gitcoiner in line. 
> 
> On the above list, but not first? Stick around to let the funder (@pelsasser) and the other parties involved what you're thinking. If the issue opens up or collaboration opportunities arise, you'll be amongst the first to know.  
> 
> Learn more on the Gitcoin Issue Page
> Questions? Get help on the Gitcoin Slack
> $12954.25 more Funded OSS Work Available at: https://gitcoin.co/explorer
>

**Comment by owocki** [comment]
ok.. this makes sense to me.  though i'm not going to have time to start developing it.. might make sense to bounty it?  or we can continue to wait for internal resources to clear up.

figure its worth having the above conversation since this issue is one of the most persistence pieces of feedback we get.

**Comment by owocki** [comment]
its too bad we lost steam on this one.. i know this was a high priority a few weeks ago.. but maybe we didnt align on a spec in order to actually solve it.  i'd happily fund a series of bounties associated with each of the suggestions in the google doc if someone wants to take a moment and spec those up

**Comment by mkosowsk** [comment]
@owocki not sure if you want to keep this to Gitcoin Core, but I'd be happy to break this out in tickets per the Google Doc over the next couple days. Only issue is I need permission on the Doc to do so 👍

**Comment by owocki** [comment]
from looking at the doc, i think one would need the context of some of our internal conversations to correctly bounty it.  thanks for the offer tho

**Comment by PixelantDesign** [comment]
Closing this for now since we have new functionality being built (start work form) that will address some of these concerns.
