### ISSUE TITLE
Design - Video preview blocks on Home page

### ISSUE THREAD

**Issue by MaxStalker** [gitcoinco/web#4204]
**Describe the bug**
Text inside video preview blocks is using serif font and not center aligned. Also gap between blocks is too big.

**To Reproduce**
Go to https://gitcoin.co scroll down to "Realign open source incentives" block

**Expected behavior**
Text should be in sans-serif Muli font and center aligned. Or this block should be redesigned.

**Screenshots**
![current-video-blocks](https://user-images.githubusercontent.com/3136647/56146750-75190400-5faf-11e9-8880-b5383788eac5.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Browser Version 73.0.3683.103

**Comment by PixelantDesign** [comment]
Thanks @MaxStalker, want to help us fix this?

**Comment by MaxStalker** [comment]
@PixelantDesign I already did. Just need someone to review my PR ^__^
https://github.com/gitcoinco/web/pull/4205
