### ISSUE TITLE
As a Gitcoin operator, an email followup to funders and contributors we haven't seen in a while could increase re-engagement.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4212]
### User Story

As a Gitcoin operator, an email followup to funders and contributors we haven't seen in a while could increase re-engagement.

### Why Is this Needed

if we can detect a session visit and identify an email, having a friendly, well worded funder product followup as a gentle reminder on how to extract the most value out of gitcoin would be useful.

Possible virality and re-engagement for Gitcoin.

closed https://github.com/gitcoinco/web/issues/4564 and moved it here

### Description

"Will you help us improve?"

"You recently signed up for Gitcoin but have not been back in a while. We would love to know why so we can be better. Mind taking the time to fill out a two minute survey?"

AND/OR

"wanted to follow up on your recent registration on Gitcoin and ensure you have everything you need for a successful first experience on the platform. I would love to set up some time to help you get started.

Would you have any availability this week or next week to schedule a call? Book a meeting with [Gitcoin Team Member]"

AND/OR

"Recruiters are looking for you. Update your profile."

[UNLOCK YOUR PROFILE]

[MAKE THE MOST OF YOUR GITHUB PROFILE]

[GITCOIN ACTION 1]

[GITCOIN ACTION 2]

AND/OR

SUCCESSFUL FUNDER TESTIMONIALS

AND/OR

GREAT CONTRIBUTORS TESTIMONIALS

### Current Behavior

No such email exists.

### Expected Behavior

Re-engagement email.

**Comment by PixelantDesign** [comment]
Plain text or designed? @frankchen07 what were you thinking?

**Comment by frankchen07** [comment]
I was thinking designed, but nothing crazy, simple is better, with minimal but effective wording.
