### ISSUE TITLE
Design - SEO Links in Footer

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4218]
User Story
As Gitcoin we'd like to improve our SEO so that we can grow organically.

Definition of Done
- Work with @octavioamu  on a solution
- Design how links would display on Gitcoin.co landing page footer
- Must work in responsive view
- Please post a mockup for @octavioamu once design is complete
- Tag @octavioamu and @PixelantDesign for review.

https://docs.google.com/spreadsheets/d/1JklC0fG6U8gF0Nbhoh9otvxpopn26NobXujxLvRUxnQ/edit?usp=sharing

https://gitcoin.co/bounties/contributor/python |   | Important on these pages | Python Bug Bounties: Open Freelance Programming Jobs \| Gitcoin |   | Find open Python coding jobs or bug bounties. Rewards paid fast in Crypto and done remotely. Funds held in escrow.
-- | -- | -- | -- | -- | --
https://gitcoin.co/bounties/contributor/ |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/design |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/html |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/rust |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/ruby |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/javascript |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/solidity |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above
https://gitcoin.co/bounties/contributor/css |   |   | Use the same formula as python above | Use the same formula as python above | Use the same formula as python above

**Comment by willsputra** [comment]
thoughts? @octavioamu @PixelantDesign 

![SEO Footer](https://user-images.githubusercontent.com/19514207/56378196-e15d6700-623e-11e9-9cc0-ff353c763477.jpg)

**Comment by octavioamu** [comment]
This was done time ago
