### ISSUE TITLE
Build Backend - Filters - User Discoverability Tool

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4220]
As a funder I'd like the ability to filter by various criteria so that I can find the right contributors to work on my bounty.

**# Definition of Done**

Build Filters:

- [x] Skills make it drop down select box (work with users or skills)
- [x] Bounties Completed - range
- [x] Leaderboard Rank  - range
- [ ] Get code reviewed prior to PR Merge

* Please refer to mockup or work with @willsputra 

https://github.com/gitcoinco/web/issues/4120

**Comment by willsputra** [comment]
filters
![Discoverability-InviteFilter](https://user-images.githubusercontent.com/19514207/56307419-62512b80-6177-11e9-960b-25a03dacf26f.jpg)
