### ISSUE TITLE
UX Prompt Funder to Work with Contributor Again

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4225]
# User Story

As a funder I'd like to be asked to work with a contributor again.

As a contributor I'd like to be notified if a funder has other issues I can work on, on his repo. 

# Why is this important?
We want to build a loop where funders engage with contributors to increase funding of bounties/platform revenue.

# Definition of Done
- [ ] Brainstorm with the core team
- [ ] Propose ways and points where funders can be prompted to work with contributors again
- [ ] Task flow this experience
- [ ] Create a design for this experience
- [ ] Review with team
- [ ] Post final file and mockup here

# Ideas
- Prompt Funder after payout screen at bounty acceptance
- Do you want to work with this contributor again?
- Show next 5 Github issues on the repo in a list.
- If funder clicks this, it opens a fund issue form with this link pre-populated.
- If issue is successfully funded, the bounty is reserved for that particular contributor
- contributor is notified of this re collaboration opportunity.

- If funder doesn't see/click the prompt in app - send follow up email after 24 hrs taking a funder into the above flow.

**Comment by willsputra** [comment]
@PixelantDesign 

Basic Payout:
![Work with Contributor Again](https://user-images.githubusercontent.com/19514207/56821997-fc9d2780-6879-11e9-9274-29ecdcc42de8.jpg)

Advanced Payout:
![Work with Contributor Again (Advanced)](https://user-images.githubusercontent.com/19514207/56822079-35d59780-687a-11e9-9ff0-446c2289e711.jpg)
