### ISSUE TITLE
UX - Display Star Ratings on Profile

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4226]
# User Story
As a funder on the Gitcoin platform, I'd like to see how contributors have been rated by other funders.

As a contributor on the Gitcoin platform, I'd like to see how funders have been rated by other contributors.

# Definition of Done
- [ ] Design placement for star ratings on the user profile page
- [ ] Consider how to display the detailed ratings 
- [ ] Share with contributors and funders for feedback (3-4 each)
- [ ] Review with core team
- [ ] Post final mockup and file on this ticket

# Data
- Increase in quality on the platform

**Comment by willsputra** [comment]
@PixelantDesign thoughts?

![profile](https://user-images.githubusercontent.com/19514207/57027670-9e07ed00-6c6f-11e9-867e-e42177b2ec8b.png)
