### ISSUE TITLE
Existential questions - Gitcoin bussiness logic works as intended? 

### ISSUE THREAD

**Issue by kwikiel** [gitcoinco/web#4236]
### Why

1. What's the point of depositing money to escrow account if I can cancel the bounty on a whim ( even after bounty hunter provided solution? )

Example in Fiverr: If I cancel the bounty I should be required to provide detailed explanation why and system should ask If I want to still continue but maybe with different bounty hunter or something. 

2. How to prevent people from circumventing the fee by posting $0.01 bounties with another amount in description ( since payout depends on funder goodwill it's related to 1 ) 

3. How to deal with the PR's not getting integrated / reviewed? 

Maybe bounty should be somehow split between bounty hunter and maintainer? 
Maintainers are currently have to deal with larger quantity of PR's to review without any additional enumeration while somebody else is getting paid 

4. It seems that Gitcoin works despite those flaws as a social platform - yet direct communication / commenting on stuff is hard and everything has to be under "issue" - this style isn't best for longer epics with smaller tasks - gitcoin makes discussion splintered into telegram group / slack and github issues

**Comment by owocki** [comment]
1. i think the 'stake' shows youre serious about pursuing the bounty.  to your point, you can cancel the bounty.. but you've not only staked your financial value but you've also kind of staked your reputation.  reputation follows you.
2. we have a few tickets written up to deal with this.  i agree its a problem.
3. this is a problem right now.  i like the idea of splitting between bounty hunter and maintainer.
4. agree with you.
