### ISSUE TITLE
Ethereal Hackathon Support

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4245]
Refer to this doc for more context: https://docs.google.com/document/d/15xJSjaxDy0zzfD5y53XdmBNJ5R7JpViAo54AZiP2prs/edit

##  *P0**

- [x] **Problem**
When you open a bounty, then click “Return to Explorer”, it doesn’t take you back to the Hackathon Explorer (takes you to the general issue explorer instead).
**Solution**
Return to Explorer change to Go to back to hackathon explorer

- [x] **Problem**
Microsoft logo is round in flyout
**Solution** Remove round mask
<img width="459" alt="Screen Shot 2019-04-22 at 1 12 04 PM" src="https://user-images.githubusercontent.com/238235/56516366-44355380-6508-11e9-9613-3b851f81093e.png">

- [x] **Problem**
Pay back 10% fee!
Need to pay back all the sponsors, need a list and then we can pay back. Name, 10% fee amount, wallet address.
No need to do for microsoft.

- [ ] **Problem**
Any way to override Github org logo so that Quorum and Kauri can get their logos on there?
ENS funded issue by Kauri pulls ENS Logo in sidebar, can we override?
Can we have options: pull from org logo or upload an image - Admin.
Quorum - Same issue

- [x] **Problem**
Mythx is under Consenys Repo and consensys is not showing in left rail.
**Solution**: PR 4243

- [x] **Problem**
Delete Fluence logo from hackathon
Delete their logos from landing page or hackathon list page
Find out why did they drop out?

## **P1** 

- [ ] **Problem**
Prize title changes not syncing with title changes on Github.
When you click update issue details on the gitcoin Edit bounty details, it might update from github ticket.

- [ ] **Problem**
AV to accept submissions and confirm best way to pay out successful submissions (Advanced payout vs “tip” vs direct payment)
MSFT can’t use DAI/ETH, they will pay with FIAT later
MSFT under understanding that they could pay us later (30 days)
Some work has been submitted/ judged need to accept within 48 hrs
When we get payment, what is the easist way to payout a bounty? 
Use tips/normal pay?
Want to show that the bounty has completed and submission no longer.

- [ ] **Problem**
DAI amounts in prize explorer revert to true amount in smart contract once work is applied for/started (any kind of user activity) despite being changed in admin
Once user activity/submitted work, the Dai amount went back to the initial Dai amount.

- [ ] **Problem**
JPM is concerned about their logo showing, despite the fact that they made us host their prizes from our repo, which we warned them about. Still, worth exploring whether we can do the logo override, which will also help Kauri

**Comment by danlipert** [comment]
"DAI amounts in prize explorer revert to true amount in smart contract once work is applied for/started (any kind of user activity) despite being changed in admin
Once user activity/submitted work, the Dai amount went back to the initial Dai amount." 

Regarding this issue, it won't be a quick fix to make sure that we can set a bounty to not resync it's value from the blockchain. Also, it may cause issues down the line with payouts, etc. I don't think we can get this done before the end of the hackathon unless we delay some of our current sprint tasks. @alexvotofuture @PixelantDesign

**Comment by danlipert** [comment]
Just added a PR to hide the low DAI values: https://github.com/gitcoinco/web/pull/4290 @alexvotofuture @PixelantDesign
