### ISSUE TITLE
Feature Request: Option to Disable Gitcoin Bot on Bounties

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4248]
### User Story

As a funder I don't necessarily want the Gitcoin bot showing up on my repo. Instead, I would prefer to choose whether it shows up.

### Why Is this Needed

Some maintainers have expressed that the bot posting in their repos is intrusive. Since we still want to work with these maintainers we should think about how we can build a flow that works for them, and allowing them to enable / disable the bot on issues as desired is a good first step in this direction. Future work may involve building in a more Bountysource 

### Description

On the Fund Issue page we should have a checkbox similar to the `Is this Bounty part of a Hackathon or Special Event?` check box that states whether the Gitcoin Bot is enabled or not on the issue to be funded.

### Current Behavior

No option to toggle Gitcoin Bot on issue creation.

### Expected Behavior

Option to toggle Gitcoin Bot on issue creation.

### Definition of Done

See above, adding a simple checkbox should be a good start.

**Comment by thelostone-mc** [comment]
Seems do-able ! 
Would be worth revisiting shrinking the form as opposed to make the form even longer!
It's getting to a point where filling out a form is becoming cumbersome  

cc @willsputra / @frankchen07

**Comment by kuhnchris** [comment]
what about possibilities to store "templates"? e.a. you fill out the form once and then can use the data of your previous form to fill out the new one?

Aside from that, for the core of this issue: this would simply work by setting the gitcoinbot snooze to 999 days, and deal with it, right?

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/4312 does this in a barebones way
