### ISSUE TITLE
bug - grant contribution email does not match expectaions

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4249]
**Describe the bug**
[comment]: # (A clear and concise description of what the bug is.)
I selected the option "One time", and now I receive an email with the description of the project in an unreadable way btw and a message that reads:
"You have agreed to give 200.0000 DAI every 30 days".

https://twitter.com/mattaereal/status/1118993928559255552?s=12

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)
See above ^^

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)
Email should match the expectations in the UI

**Screenshots**
[comment]: # (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS: xxxx
- Browser xxxx
- Browser Version xxxx

**Smartphone (please complete the following information):**

- Device: xxxx
- OS: xxxx
- Browser [xxxx
- Version xxxx

**Additional context**
**Smartphone (Add any other context about the problem here.)

**Comment by kuhnchris** [comment]
Do you happen to have the database entry for that (and could share it)? Just to make sure the data isn't accidently saved wrongly as 30 days, for example.

**Comment by owocki** [comment]
its just a subscription object where num_tx_approved = 1

**Comment by owocki** [comment]
1457a090f3511ccd026367971929d1c4bccd51d3
