### ISSUE TITLE
Funder Email Summary - Workers Applied

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4251]
### User Story
As a Funder on the Gitcoin platform I'd like a condensed email that encapsulates the contributors who have applied for my bounty.

### What
Email to funders summary of who has applied - combined vs 1 at a time…..
Show leaderboard rank
Cumulative email

### Defintion of Done
- [ ] Design an email with these 3 conditions
- 1st contributor
- You now have two contributors 
- You now have three contributors
- [ ] Show leaderboard rank
- [ ] Design Responsive view
- [ ] Review with core team
- [ ] Provide 3 mockups for build and source file

**Comment by kuhnchris** [comment]
Define "show leaderboard rank" and "summary of who has applied" - you mean as in user "punch cards" as in how many bounties they solved v.s. applied and stuff like that, or do you simply mean "summarize what gitcoinbot is already posting on the github"?
