### ISSUE TITLE
Error upon creating grant

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4260]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/761911/56596659-3dced680-65f1-11e9-9a16-71acae8121b6.png)

**To Reproduce**
- Create grant

**Expected behavior**
- No error

**Screenshots**
see above

**Desktop (please complete the following information):**
- Win10
- Firefox latest stable

**Comment by thelostone-mc** [comment]
Did you change your metamask address during the grant creation process ?

**Comment by kuhnchris** [comment]
yes, once to transfer funds.

**Comment by thelostone-mc** [comment]
hmm 🤔 i have a feeling things got messed up there ! will have to check it

**Comment by kuhnchris** [comment]
I wonder, since last time I tried the whole process broke, so I was rather confident that it worked this time, hmm...
I can still interact with it and change the grant and everything, it's just the message above appearing.
