### ISSUE TITLE
as a grants creator, i want to be able to record funding from other places so ppl can use gitcoin grants as the one single source of truth for how a project is funded

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4272]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grants creator, i want to be able to record funding from other places so ppl can use gitcoin grants as the one single source of truth for how a project is funded

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so ppl can use gitcoin grants as the one single source of truth for how a project is funded

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
can't record external funding

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
grant creators or team members can go to their grant and record funding they received outside of gitcoin

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
thx @bmann for the idea in berlin!

**Comment by bmann** [comment]
Manual Record is good — logging “direct” transactions to the target address would be good, too.

**Comment by kuhnchris** [comment]
well, do we need some kind of verification-mechanism? e.a. do we need to check against the blockchain that the tx (or money amount entered) is to the grant?
Else, if people donate to the GRANT CONTRACT we could do automatic logging, if they just do tx to wallets it's just white noise.

Alternatively: add a "+" button in the Grant administration and a section called "External (non-verifiable) Funding" and display them in the grant with a 2nd color (like green and dark green), so people can easily distinguish between them.
