### ISSUE TITLE
as a kudos holer, i want the kudos artwork to show the sequence number shown on the kudos art, so i can show off how i got the first kudos of a limited edition set

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4274]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a kudos holer, i want the kudos artwork to show the sequence number shown on the kudos art, so i can show off how i got the first kudos of a limited edition set

### Why Is this Needed
for bragging rights

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
![ONjiSXXB](https://user-images.githubusercontent.com/513929/56698839-8600fe00-66b0-11e9-97e5-8bed38a22ccb.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

![ONjiSXXB](https://user-images.githubusercontent.com/513929/56698884-b183e880-66b0-11e9-9109-96163e4844e5.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
well, that's certainly a problem to implement, as the number would have to be included into the SVG... do you have any alternative ideas where to put the number(s)? else we may need to dynamically generate the SVG Kudos with the number inside (and create the Kudos templates with #####/##### templates to fill later)

**Comment by owocki** [comment]
i was going to go down the 'dynamically generate the SVG kudos' route
