### ISSUE TITLE
DESIGN - add a section to the /results page that says "my bounty wasnt turned around, why"

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4275]
### Who
/results page

### What 
add a section to the /results page that says "my bounty wasnt turned around, why".  put it below this ( http://bits.owocki.com/82e4bf395206/Image%202019-04-24%20at%205.17.03%20PM.png ) section

### Why
why don’t some tasks get turned around?  the results page should breakdown why the '87%' number is only after start work.  the reason is that
- your task might be underpriced
- youre not "selling" your tasks / mission in a good way
- you dont have documentation on your repo

this section will be a lede into the following blog posts
https://medium.com/gitcoin/hiring-with-gitcoin-d58679de37ac
https://medium.com/gitcoin/setting-your-oss-repos-monetary-policy-9c493118cd34
https://medium.com/gitcoin/how-to-build-a-contributor-friendly-project-927037f528d9
https://medium.com/gitcoin/tutorial-how-to-price-work-on-gitcoin-49bafcdd201e

**Comment by thelostone-mc** [comment]
Note: PR for this to be merged only after https://github.com/gitcoinco/web/pull/4167 gets in

**Comment by kuhnchris** [comment]
but... it is? 
![grafik](https://user-images.githubusercontent.com/761911/56732160-be5e1600-675c-11e9-93b5-39db8dd72c6a.png)

**Comment by thelostone-mc** [comment]
lol that got in after I posted that comment -> so yup it's up for grabs

**Comment by kuhnchris** [comment]
If it's up for grabs: How do we evaulate the reason for rejection? Do we have a new field on the Bounty Object for that, or is part of this PR/Request to also implement a feedback system for that?

Thanks

**Comment by owocki** [comment]
for now, id just like to have some qualitative storytelling about why bounties are not turned around in the design. for the purposes of designing this, you can assume the numbers will be provided for you.

i will pull the numbers for you guys.

**Comment by kuhnchris** [comment]
OK, so for now just plain hardcoded, that's fine. 
Anything fancy like staked bars or pie charts for that?

**Comment by owocki** [comment]
thats up to the designer :)

**Comment by nealmcb** [comment]
First, as I noted in slack, the right link is now https://gitcoin.co/blog/tutorial-how-to-price-work-on-gitcoin/

For bonus points, refactor the code so the same URL doesn't get hardcoded in multiple places. It is now in 3 places: views.py, amounts.js, results.html (https://github.com/search?q=org%3Agitcoinco+49bafcdd201e&type=Code)
