### ISSUE TITLE
Flyout Bug - Project icons overflowing out of card

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4280]
### Issue

https://gitcoin.co/issue/fortmatic/edcon2019-hackathon/1/2760

- Icons running beyond flyout (see screenshot)

### Browser
Google Chrome Version 73.0.3683.103
Mac Mojave

### Screencap
<img width="1018" alt="Screen Shot 2019-04-25 at 8 20 09 AM" src="https://user-images.githubusercontent.com/238235/56735308-1a13a980-6733-11e9-9f37-2edb7aa071f6.png">

**Comment by kuhnchris** [comment]
ok, that overflow bug is easily fixable, i'm more worried about the "undefined"
![grafik](https://user-images.githubusercontent.com/761911/56736740-3599a700-6769-11e9-9293-1dc31c40adf1.png)

Overflow: hidden; fixes this issue. But, I rather ask, what's with the "," in the middle?
![grafik](https://user-images.githubusercontent.com/761911/56737037-d38d7180-6769-11e9-8a95-d2c681ddb279.png)

**Comment by thelostone-mc** [comment]
Also, specialty should be hidden when no data is available

<img width="588" alt="Screenshot 2019-04-25 at 6 31 38 PM" src="https://user-images.githubusercontent.com/5358146/56737583-63daaf00-6788-11e9-924b-f876e8958162.png">

@iamonuwa would you be able to get around to fixing all the 3 mentioned above as this was introduced in https://github.com/gitcoinco/web/pull/3915

cc @octavioamu

**Comment by kuhnchris** [comment]
also the spacing between Gitcoin Contributor and the stats is weird. + Contributor also overflows.
If @iamonuwa is on it i won't touch it, else let me know and I'll send a PR in.

**Comment by iamonuwa** [comment]
Sure

**Comment by thelostone-mc** [comment]
PS: @iamonuwa cleanest thing would probably be to limit the number of orgs (maybe 4) and replace the rest with the count of the remaining number of orgs 

Kinda like what do we in profile
<img width="512" alt="Screenshot 2019-04-25 at 6 42 48 PM" src="https://user-images.githubusercontent.com/5358146/56738347-0cd5d980-678a-11e9-9ea0-96d3342f93de.png">

ignore the hover part cause hover inside in over is crazy talk 😂
