### ISSUE TITLE
As an enterprise director of open source, I want a turnkey solution so I can amplify my organization's open source efforts

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4300]
### User Story

As an enterprise director of open source, I want a turnkey solution, so I can amplify my organization's open source efforts

### Why Is this Needed

Currently, its very difficult for larger organizations to adopt Gitcoin, as there are no organization management features, nor intra-organization functionality

### Description

*Type*: Feature (EPIC)

### Current Behavior
Right now, our product is focused on interfacing with (usually smaller) organizations through one or two Gitcoin account holders, or multiple people utilizing a shared account. Multi-user management of bounties is difficult, due to the need to share private keys.

### Expected Behavior
Accounts should be able to be deployed for an organization's employees under the direction of a director or manager. Gitcoin should interface with current identity management software (Okta, Active Directory, etc.). Users should be able to collaboratively manage all aspects of the Gitcoin suite of products. Intra-organization features should be enabled (private/my organization only repos, easy user selection for intra-organization Kudos & Grants, etc.)

### Definition of Done
Difficult to say, as per-customer agreements will often require bespoke addons. A good starting point for "done" would be utilizing Github organizations to enable the above functionality. 

### Data Requirements
How many enterprises can we sign up for how many seats?

**Comment by owocki** [comment]
this is a good idea!  cc @alexvotofuture  @ceresstation to comment on how much customer demand there is for these features
