### ISSUE TITLE
As a gitcoiner I’d like to have a badge /something to display on my site to show that I’m an active Gitcoiner 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4301]
## User Story
As a gitcoiner I’d like to have a badge /something to display on my site to show that I’m an active Gitcoiner 

## Why
Sometimes the things you work on are private or not captured and the github squares are not representative of your work.

## What
Take the basic user stats and display in some sort of badge.
Allow ability to generate/display on medium and other sites to show a proven expertise.

## Contributor Comments
“From my recent experience:
employer asked for github link
checked my LinkedIn, asked if he can contact my coworkers/previous employers for references
asked if I have any other source of info about my skills - codepen, condesandbox, code wars
and my portfoilio on dribble 

It would be awesome if I could simply pass it to him as single entry, which will hold all that and more.

Could be made up of bounties, kudos, and recommendations.

## Revenue Opportunity
What would users pay for this?
 $5-30

**Comment by kuhnchris** [comment]
So basically extending the "profile" into it's own application where we can add loads of other references?
