### ISSUE TITLE
As a Gitcoin core team we'd like users to come back /keep Kudos top of mind

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4303]
## User Story
As a Gitcoin core team we'd like more visibility on Kudos and get users to come back /keep Kudos top of mind. 

## Why
Sometimes the things you work on are private or not captured and the github squares are not representative of your work.

## What
Building off of the idea of air dropping that Kevin just created a PR for…https://github.com/gitcoinco/web/pull/4295

Idea 1: What if we create collectable sets of Kudos
To engage people daily

Ex: neon mob daily free packs
If we gave some free packs daily or a daily Kudos, would this encourage sending/usage of kudos?

Put a new kudos in the users profile - it only shows up for that one day.
If they user doesn't unlock, it’s gone. The only way they get to keep this collectible is if they send one. When you send one, you get one. We create them but users would pay small amount 1 Dai (processing fee) to send to each other plus gas.

There is always a random reason for things like national doughnut day, national hot dog day…https://nationaldaycalendar.com/may/  How can we make something like this on our platform but related to devs and make it fun?

## Revenue Opportunity
- Amount per send

**Comment by kuhnchris** [comment]
Maybe integrate Kudos into some other apps or things so they gain secondary values? Like card games or other ETH/ERC related collectables?
Also, maybe making interacting with them easier, so people can trade them, show them, evalute them, etc.
