### ISSUE TITLE
Build Front End - Filter - User Discoverability Tool

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4305]
As a funder I'd like the ability to filter by various criteria so that I can find the right contributors to work on my bounty.

**Definition of Done**

Build Front End of Filters:

- [ ] Front display to Bounties Completed - range
- [ ] Front end display to Leaderboard Rank  - range
- [ ] Get code reviewed prior to PR Merge

Do This later
- [ ] Front end display to Skills make it drop down select box (work with users or skills)

* Please refer to mockup or work with @willsputra 

https://github.com/gitcoinco/web/issues/4120

**Comment by kuhnchris** [comment]
Any ways for the user to signalify that he wants to receive mails like that in his settings?
Else I see people abusing it...
Else I'm up for it. Shall this be a extra menu point for funders or something separate alltogether in it's own menu?
