### ISSUE TITLE
Consolidated Contributor Applications Email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4306]
### User Story

As a Funder, I'd like to consolidated emails after the first email has been sent to me after I've been notified of a funder application on my bounty.

### Definition of Done
Email summary to funders summary of who has applied - combined vs 1 at a time…..

Show leaderboard rank

- 1st contributor
- You now have two contributors 
- You now have three contributors

Stop sending emails when they pick someone.
Focus on anything that requires approval.

### Data Measurements
Decreased median time to bounty pickup
Decreased median time to bounty completion
Increased number of successful working relationships between funder and contributor
Increased LTV

### Reach
All funders that fund an issue

### Impact
High Impact 

### Confidence 
90%

**Comment by kuhnchris** [comment]
Well, how do you want to consolidate this?
- Time-wise? (as in, sent every hour) 
- Topic-wise? (just all approval requireds, all new contriubtion, ...) 
- User-wise? (User X applied for a b c, User Y applied for d a c)

**Comment by willsputra** [comment]
something like this? ![application email](https://user-images.githubusercontent.com/19514207/58302571-76471780-7e1e-11e9-8815-e2e18c972a58.jpg)

**Comment by kuhnchris** [comment]
5 is already pretty long... also write somewhere what the sorting criteria is, else people will get offended because "I want to me at the top" and stuff like that. (Like, Applicatants ordered by avg. rating of the community)

**Comment by willsputra** [comment]
@kuhnchris good points! thanks for the feedback. :) how about limiting it to 3? I've also added some explanation about the sorting criteria.

![applications](https://user-images.githubusercontent.com/19514207/58330754-2b52f180-7e6a-11e9-9a91-5d1b8e802533.jpg)

**Comment by kuhnchris** [comment]
perfect, that looks really nice to me, any other comments @PixelantDesign  ?

**Comment by PixelantDesign** [comment]
Looks good. The Bounty with few applicants are placeholders right? IT should probably say the name of the bounty and value? @willsputra 

cc: @vs77bb @frankchen07 for feedback

**Comment by PixelantDesign** [comment]
@willsputra could you break this up into 3 emails so we can see how it'll really look?

**Comment by willsputra** [comment]
@PixelantDesign yep those are just placeholders, should be the title of the bounty. good point maybe the bounty value should be there too.

are we going to have one email for each bounty? so if you have 3 bounties you'll have 3 emails?

**Comment by frankchen07** [comment]
Questions from @thelostone-mc 

> how often is this email sent?

@PixelantDesign, I believe this is one summary email sent to the funder instructing them that they have applicants waiting their review.

> Is it for a single bounty / multiple bounty?

The sketch looks like it's for multiple bounties that a funder opened, and the email has the capacity to show at most three bounties and applicant options, however, let's confirm this? @willsputra 

I'll add my note here that there should be one email for one bounty, not combined. That would be confusing, but am open to pushback here.

> what happens when a new applicants applies but someone is already approved?

The summary of applicants for an already approved bounty should not show up in the summary email.

> it still seem will and alisa aren't done with the final design based on the last comment in the thread?

@willsputra or @PixelantDesign, can we get the final design and confirmation of one email one bounty, not one email multiple bounties? Also, agree with adding bounty title and value as well.

**Comment by willsputra** [comment]
> The sketch looks like it's for multiple bounties that a funder opened, and the email has the capacity to show at most three bounties and applicant options, however, let's confirm this? @willsputra

The idea was to show all open bounties and at most three applicant options. Open to suggestions too.

> I'll add my note here that there should be one email for one bounty, not combined. That would be confusing, but am open to pushback here.

My only concern is that if you have a lot of bounties, you'll receive a lot of emails which could feel kinda spammy. @PixelantDesign what do you think?

If we decide to have one email per bounty I'll modify the mockup :)

> The summary of applicants for an already approved bounty should not show up in the summary email.

I agree.

> @willsputra or @PixelantDesign, can we get the final design and confirmation of one email one bounty, not one email multiple bounties? Also, agree with adding bounty title and value as well.

Agree with adding bounty title and value.

**Comment by frankchen07** [comment]
Another question, is the email sent immediately or after several days? What happens if the email is sent on day 1 (as an example), and two applicants applied on day 0 and another two applicants applied on day 2? Will the email send again? 

Or, will an email be sent every time an applicant applies? That would be clutter-esque for the funder.

**Comment by willsputra** [comment]
cc @PixelantDesign 

It'll be something like this:
• 1st applicant - I get an email right away
• at end of day 1: if I get more applicants, I get an email. if I didn’t get more applicants, no email.
• at end of day 2: if I get more applicants, I get an email. if I didn’t get more applicants, no email.
• repeat daily

**Example**
As a funder, I have two open bounties with 0 applicant: 'Implement WYSIWYG' and 'Fix Bug'.

1. 1st applicant applies to 'Implement WYSIWYG' - send email right away
![Users Directory Copy 2](https://user-images.githubusercontent.com/19514207/58651015-cce2b300-8342-11e9-8f71-69382607a15b.jpg)

2. 1st applicant applies to 'Fix Bug' - send email right away
![Users Directory Copy 3](https://user-images.githubusercontent.com/19514207/58651037-db30cf00-8342-11e9-97fa-2aa61400d369.jpg)

3. At end of day 1, check if there are more applicants for both bounties. If there are more applicants, send email at end of day 1
![Users Directory Copy 4](https://user-images.githubusercontent.com/19514207/58651095-fdc2e800-8342-11e9-9d35-cb736f922f8f.jpg)

3. At end of day 2, check if there are more applicants for both bounties. If there are more applicants, send email at end of day 2
![Users Directory Copy 5](https://user-images.githubusercontent.com/19514207/58651177-2945d280-8343-11e9-9307-cb4ebd35818f.jpg)

4. Repeat for day 3, day 4...

**Comment by frankchen07** [comment]
Hm, I feel like this is ALOT of emails per bounty - it has the frequency of "live" updates, which could be somewhat disruptive.

I wonder if sending with the first applicant, and then another one 1-2 days later with an update with new or without new applicants (and that's it) would be beter?

@PixelantDesign what do you think?

**Comment by kuhnchris** [comment]
alternatively - you do know how google uses those desktop notifications?
Maybe we should go into that direction and reduce the number of mails?
But for this task, I think it's OK, since those are applicants and the user/bounty creator wants to get his bounty solved ASAP.

**Comment by kuhnchris** [comment]
alternatively - you do know how google uses those desktop notifications?
Maybe we should go into that direction and reduce the number of mails?
But for this task, I think it's OK, since those are applicants and the user/bounty creator wants to get his bounty solved ASAP.

**Comment by PixelantDesign** [comment]
General flow from Will seems right. I might not send multiple emails in one day though.

It’s hard to know the exact frequency without user feedback. 

In this day and age people do expect not to be notified within a certain time time frame. If we notify too late the contributor may not be interested or may have picked up other tasks. If we notify the funder too late, this issue is not as top of mind for him/her. We need to catch them as close to when they’ve funded as possible.

I’m curious to know the sucess or completion rates of bounties as time passes. My instinct based on what we’ve seem in issue explorer check-in as time passes, liklihood of completion becomes lower.

**Comment by willsputra** [comment]
I’m guessing we can still follow the general flow, but limit each day to only max one email?

**Comment by kuhnchris** [comment]
Or track the reading of the mail (1x1 graphic include)? If he reads the mail => reset email sent flag, if he doesnt => he only get up to 1 mail

**Comment by PixelantDesign** [comment]
- Need to build task scheduler to do it right.

**Comment by PixelantDesign** [comment]
Maybe schedule for everyone at 9am on Mondays? @danlipert 
cc @vs77bb

**Comment by PixelantDesign** [comment]
Come back after v1 of dashboard.
