### ISSUE TITLE
As a bounty hunter, i want the opportunity to tell the system when bounties are not relevant to me, so I dont tune out the new bounty emails

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4308]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a bounty hunter, i want the opportunity to tell the system when bounties are not relevant to me, so I dont tune out the new bounty emails

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

No ability to opt out of bounties.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Buttons that allow you to change your matching preferences.

<img width="722" alt="Screen Shot 2019-04-29 at 4 13 01 PM" src="https://user-images.githubusercontent.com/513929/56930403-c76f2000-6a99-11e9-9e6d-f2ce423e2f7e.png">

These buttons will all go to https://gitcoin.co/settings/matching ; which should be extended to allow:
1. user to subscribe / unsubscribe to matching emails 
2. to receive bounties for any programming language in a list of programming languages 
3. to receive bounties only within a certain price range.
4. to whitelist / blacklist repositories.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
Increased short and long term open / click rate on the new bounty emails

### Reach
All contributors that see this email

### Impact
Increase accuracy of match, High Impact 

### Confidence 
80%

**Comment by owocki** [comment]
@danlipert @thelostone-mc @PixelantDesign i wrote this after our planning session today.

**Comment by willsputra** [comment]
Thoughts? @PixelantDesign 

Email with new buttons
![email](https://user-images.githubusercontent.com/19514207/58721214-88b4e880-83fe-11e9-9e50-b496e919e55b.jpg)

Matching settings
![matching](https://user-images.githubusercontent.com/19514207/58721231-98ccc800-83fe-11e9-82aa-05ab61ba7e7e.png)

**Comment by octavioamu** [comment]
@owocki what should be the action when you click "not interested" ? Because can be the user is not interested in some particular keywords, or organization/repo bounties.

**Comment by PixelantDesign** [comment]
@thelostone-mc thoughts on this? ^^

**Comment by willsputra** [comment]
![not relevant](https://user-images.githubusercontent.com/19514207/59280454-d0a1fe00-8c8f-11e9-9aec-48899df1a664.jpg)

**Comment by danlipert** [comment]
@willsputra Dope! looks very nice!

**Comment by ceresstation** [comment]
@willsputra this is great!
