### ISSUE TITLE
As a user who isn't always sure how to use Gitcoin or who has found a bug, I want a super prominent "HELP" button available.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4309]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a user who isn't always sure how to use Gitcoin or who has found a bug, I want a super prominent "HELP" button available.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Our UX is sometimes confusing, and people think they have found a bug.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Help button is rather hidden in footer.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
There should be a super prominent HELP button in the nav.

<img width="1299" alt="Screen Shot 2019-04-29 at 4 20 05 PM" src="https://user-images.githubusercontent.com/513929/56930663-afe46700-6a9a-11e9-8072-244a2f95e276.png">

This button should take the user to gitcoin.co/help 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
Less people complaining about how buggy Gitcoin is.

See also https://github.com/gitcoinco/web/issues/4310

**Comment by ceresstation** [comment]
I think this would be super helpful, I don't think I've heard of anyone using the help button perhaps largely because it's so hidden. Is the content on the help page up to date by the way?
