### ISSUE TITLE
As a user browsing https://gitcoin.co/labs , I want to see all of the priced services that Gitcoin Labs offers, so I can know how to get the most out of Labs.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4313]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user browsing https://gitcoin.co/labs , I want to see all of the priced services that Gitcoin Labs offers, so I can know how to get the most out of Labs.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Right now people don't know how to engage with Gitcoin Labs

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No pricing / intake form on Gitcoin Labs

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

I would like a section up top that says "Services Gitcoin Labs offers".  Under it we should list:
1. Custom Research Reports
2. Custom Web3 Experiences
3. Fractional CTO Consultations

When someone clicks on any of the products, they should be taken to a typeform which will intake their information and email it to Austin + (Scott or Vivek)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
Funnel:
1. Visitors to /labs
2. Clicks on the products
3. Filled out typeforms
4. Purchases of Labs packages

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
Will the Typeform be provided to us or is creating those part of the task?
