### ISSUE TITLE
(bounty) if the reserved person applies for the bounty, it's free to grab for everyone

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4318]
**Describe the bug**
After trying to take a look at https://github.com/b-mueller/sabre/issues/52 it was resevered for someone 1 or 2 days ago.
He applied for the bounty just now, and as he did I was able to "Express interest" e.a. grab the bounty.

**To Reproduce**
Not sure, neet to reproduce myself first, but I guess: Create bounty with reservation, have the reserved person apply, have someone else apply

**Expected behavior**
As long as the bounty is reserved noone else should be able to apply

**Comment by kuhnchris** [comment]
Follow-up: this may has something to do with the reservation being dropped after 3 days.

**Comment by PixelantDesign** [comment]
Thanks for the report! want to help us fix this?

**Comment by kuhnchris** [comment]
Well, the question is - how should it work, is it working as intended or is it broken? If it is as the follow-up indicated it may aswell work as intended if the reservation time is up.
