### ISSUE TITLE
Marketing - Update Links on Contributor Landing Pages

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4321]
Add the links to contributor pages in this paragraph "There are open issues in our Issues Explorer for all Python, JavaScript, Rust, Go, Solidity, Node.js, and many more developers. " 

https://gitcoin.co/bounties/contributor/

**Comment by kuhnchris** [comment]
You mean links to the filtered search results?

**Comment by mbeharry** [comment]
Replace this paragraph;
"There are open issues in our Issues Explorer for all Python, JavaScript, Rust, Go, Solidity, Node.js, and many more developers."

With this one;
There are open issues & bug bounties in our <a href="https://gitcoin.co/explorer">Issue Explorer</a> for <a href="https://gitcoin.co/contributor/python">Python</a>, <a href="https://gitcoin.co/contributor/javascript">JavaScript</a>, <a href="https://gitcoin.co/contributor/rust">Rust</a>, <a href="https://gitcoin.co/contributor/solidity">Solidity</a>, <a href="https://gitcoin.co/contributor/design">Design</a>, <a href="https://gitcoin.co/contributor/html">html</a>, <a href="https://gitcoin.co/contributor/ruby">Ruby</a>, <a href="https://gitcoin.co/contributor/css">CSS</a> and much more.

**Comment by kuhnchris** [comment]
[Easy enough.](https://github.com/gitcoinco/web/pull/4341)

**Comment by kuhnchris** [comment]
👍  thanks for the pull!

**Comment by octavioamu** [comment]
Thanks for the work @kuhnchris

**Comment by octavioamu** [comment]
Your pr got merged is that why it got it closed here, not that we are ungrateful

**Comment by kuhnchris** [comment]
I know, i'm doing this long enough now with you guys. ;-)
