### ISSUE TITLE
Add User Directory to Top Nav

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4322]
Collaborative Task
UX & Build Surface User Directory in Top Nav

**Comment by kuhnchris** [comment]
So... basically a reskinned Leaderboard without restrictions and a sorting by A-Z?

**Comment by owocki** [comment]
before we put the user directory public, should we give people a way to opt out of being serachable?

**Comment by PixelantDesign** [comment]
Good point... maybe a new tab in settings with a simple check box to opt out?

**Comment by PixelantDesign** [comment]
Sketch file here @owocki 
[Bounties_Nav_Update.zip](https://github.com/gitcoinco/web/files/3143176/Bounties_Nav_Update.zip)

**Comment by kuhnchris** [comment]
Short shared/nav.html edit for Option 3:
![grafik](https://user-images.githubusercontent.com/761911/57159457-3d4ef080-6de6-11e9-9e14-b60864ccf747.png)

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/4360 implements #2

**Comment by kuhnchris** [comment]
Either is fine by me, but #2 seemed the most less intuitive for me. We can always try and see how people react to it.
