### ISSUE TITLE
User Directory QA Ticket

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4323]
- [ ] We need a no results found on user directory search -
@octavioamu Is there any text we can include now? 
"You searched xyz, No Results were found." Alisa to write ticket for full design.
- [ ] can we find a permanent home for show filters (so it doesn't jump)? @willsputra what do you think?
- [ ] Why does no results button show hwen this happens? i clicked it an my filter left rail all dissapear.
- [ ] search at the top, when I type in a language like css, I expected it to show in the skills section on left rail as well. Thoughts?
- [ ] should we exclude core team members from the search result?
- [ ] Stars look big, could we shrink it by 3/4 teh size?
- [ ] Why does the colmun for skills get wider when i add 4+ skills? (minor)
- [ ] line up bounty values (right align)

<img width="558" alt="Screen Shot 2019-04-30 at 8 44 52 AM" src="https://user-images.githubusercontent.com/238235/56962736-46f60100-6b25-11e9-9eaa-e9052bb42f14.png">

- [ ] my icon on second bounty is an oval (see above)?

- [ ] show filters jumps when I click it

- [ ] make left rail filter headers match (smaller style looks good!)

- [ ]

**Comment by owocki** [comment]
- wonky CSS on wider monitors (seems like the filters should be smaller relative to the user directory) http://bits.owocki.com/b5dbfa3b52de/Image%202019-04-30%20at%208.18.44%20AM.png
- everyone has 0 star ratings.  is that correct?
- show filters should be come 'hide filters' when its clicked and visa versa.
- there isn't a 'no results found' page. its just blank
- no results for anything 5+ bounties completed
- can we preload the autocomplete with a list of programming languages ([screenshot](http://bits.owocki.com/819b2b6f25af/Image%202019-04-30%20at%208.21.42%20AM.png)) i dont know why theres usernames in there but there likely shouldnt be. get a list of programming languages from `from retail.utils import programming_languages`

**Comment by owocki** [comment]
- can we have a 'loading' indicator when fetching from the API?  just in case the API gets slow in some circumstances...

**Comment by owocki** [comment]
- how do i get the 'invite useres to bounty' modal?  i dont see it at all ([except in the screenshot @PixelantDesign opsted here](http://bits.owocki.com/cd7efa71ce6d/Image%202019-04-30%20at%208.37.58%20AM.png))

**Comment by PixelantDesign** [comment]
invite by clicking invite to bounty (big blue button) @owocki

**Comment by PixelantDesign** [comment]
@octavioamu this is a good idea if we think it might be slow...I haven't felt any slowness when I tested.

>can we have a 'loading' indicator when fetching from the API? just in case the API gets slow in some circumstances...

**Comment by owocki** [comment]
hmmm i dont see any big blue button on the results.. screenshot: http://bits.owocki.com/c265912549bd/Image%202019-04-30%20at%205.03.03%20PM.png

**Comment by octavioamu** [comment]
Ok now I think everything from the list was addressed, can be tested in my staging.

- To be able to see the modal you need to have at least one bounty funded, so them you can invite someone to work on your bounty.
- There is not much data so there is not leaderboard ( I think Saptak only)
- rating is not filtering yet I believe later saptak will update the backend part.
