### ISSUE TITLE
[WORKSHOP] - As a Gitcoin operator, let's move forward with Wyre integration for fiat on-ramps.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4327]
### User Story

As a Gitcoin operator, let's move forward with Wyre integration for fiat on-ramps.

### Why Is this Needed

Multiple market asks for this type of feature - @ceresstation beating the drum for quite some time now.

### Description

Earliest ticket: https://github.com/gitcoinco/web/issues/1967
Documentation ticket: https://github.com/gitcoinco/web/issues/3580

There may be some custom integration on the Wyre side, but primary use case needs to be determined in a workshop session. 

This workshop will address: 

What is the next most effective step that Gitcoin can do to integrate Wyre and what are the primary use cases?

1. fiat on-ramps as the lowest lift start ($$ -> ETH DAI)

2. For the integration, what are the backend components that need upgrading, and how will that be represented in the frontend - will it have it's own page, or will new elements be necessary for our existing UX?

eventually,

1. will be cross platform? can users fund grants, open bounties, and payout bounties using only fiat?

2. will it only remain a fiat on-ramp, and be found only on the funder form and payout pages?

3. fiat off-ramp and cash out in native currency?

### Current Behavior

no wyre integration of any sort

### Expected Behavior

fiat on-ramp where users can exchange currency for DAI and ETH and quickly ramp up on Gitcoin

### Definition of Done
- [ ] determine primary use case
- [ ] specifications on integration

**Comment by kuhnchris** [comment]
AFAIK there was also Shapeshifter in the talks - did you guys decide on Wyre? Also, any API documentation or rather, do you have any python interface using this? (e.a. you want to use it fore-ground only so people have to figure out problems with the vendor, or want to do it on the backend side and possible have people complaining your ears off whenever there are fund-issues?)
