### ISSUE TITLE
As a Gitcoin operator, let's completely get off Kubes.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4328]
### User Story

As a Gitcoin operator, let's completely get off Kubes.

### Why Is this Needed

Backend migration off Kubes, however, the servers are still up. Let's finish de-commissioning them.

### Description

Dan will have to pull the Kubes plugs and ensure that we still have full functionality (electricity, running water, hot water, food, snacks) for Gitcoin so we can fully de-commission Kubernetes. This requires some testing time.

### Current Behavior

Servers may implode Gitcoin if not tested to ensure that we're not turning off any essential backend items.

### Expected Behavior

completely de-commissioned Kubes.

### Definition of Done
- [ ] complete de-commissioned Kubes

**Comment by kuhnchris** [comment]
The question is: getting away from kubes to where? Do you have a scalable orchestration system?
I believe you are now in a size category where you would prolly need at least 2 or 3 frontend servers running to handle the load, so how is that managed? Manually? Docker Swarms?

**Comment by frankchen07** [comment]
@danlipert is best suited to answer this question. On the edge of my seat too to learn a little bit.

**Comment by kuhnchris** [comment]
@danlipert there seem to be a couple of issues now, Derek (Bloom) got some issue now with new Bounties to show up, the Bounties are stuck at "Draft" on StandardBounties, seems like the processing step is now broken. Can you please reevaluate?
Also, I hate to be "that" person, but would you mind (either in some internal devop repository or in the devops dir) creating some chart(s) that show how the servers and services are connected to each others? You can naturally blank out the important details like server names etc, but just to get a feel about what range of servers or size of infrastructure we're dealing with here.

Thanks
