### ISSUE TITLE
As a Gitcoin operator, Grant details UI refactor.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4329]
### User Story

As a Gitcoin operator, prettify the Grant details page.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

Web view:
![Grants Detail](https://user-images.githubusercontent.com/7516920/56980559-f7432400-6b7c-11e9-834e-a34b2959162e.jpg)

Mobile view: 
![Grants Details v2 Mobile](https://user-images.githubusercontent.com/7516920/56980566-f9a57e00-6b7c-11e9-8f5c-56c00d65bd3d.jpg)

### Current Behavior

example: https://gitcoin.co/grants/100/eth-based-games

### Expected Behavior

frontend specifications built to the design

### Definition of Done
- [x] frontend specifications build to the design sketches above
- [x] reactive and tested

### Data Requirements
- [ ] hook up hotjar and GA funnels to check user activity

**Comment by PixelantDesign** [comment]
@willsputra could you attach the sketch?

**Comment by willsputra** [comment]
@PixelantDesign sketch file
https://github.com/gitcoinco/creative/pull/79/commits/69842a9e521a1a95006d8dfaf2526242fd59672e#diff-c0a171beed1c22d08b37fd55467e16bd
