### ISSUE TITLE
As a Gitcoin admin, I want to be able to suggest related grants to users when they make a contribution, so we can make contributors aware of the different projects on Gitcoin grants

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4330]
### User Story

As a Gitcoin admin, I want to be able to suggest related grants to users when they make a contribution, so we can make contributors aware of the different projects on Gitcoin grants

### Why Is this Needed

We'd like to increase the variety and number of contributions that contributors make to Gitcoin grants programs, based on a suggestion that the greater the number of contributions (note: not necessarily total value), the better our signals will be for CLR matching, and the less effect collusion and fraud will have (increasing sybil resistance). 

### Description

*Type*: Feature

### Current Behavior
Currently, after contributing to a grant, a user receives an email informing them of their contribution.

### Expected Behavior
In the post-contribution email, we'll show at least 2 other related grants that may be of interest to the contributor. These 2 grants will be selected by Gitcoin admins through the Django admin interface. 

### Definition of Done
In the post-grant contribution email, at least 2 other grants will be shown as a suggestion for the user to evaluate. These other 2+ grants can be specified in the Django admin by a Gitcoin administrator on each grant's object detail page. Note that this is an additional section for the already existing email sent to each contributor after they contribute to a grant.

### Data Requirements
This feature will increase the total number of contributions made.

**Comment by danlipert** [comment]
@frankchen07 @PixelantDesign shall I bounty this out? Looks pretty simple and we have some community members with good experience working with our emails.

**Comment by PixelantDesign** [comment]
Thanks for the write up! What fields will be displayed in the admin that I can pull from? Should we make it more clear that the contributor is not expected to make the email (expected behavior and definition of done are kinda confusing)?

**Comment by danlipert** [comment]
@PixelantDesign the fields in the admin should be a multiselect drop which lists each grant and allows you to select multiple items. For each grant, lets show the title of the grant. Also I'll update the issue to better explain the email - should we get a design going for this?

**Comment by frankchen07** [comment]
Yes, let's workshop this quickly in the upcoming week, see if can get some designs out and bounty this.
