### ISSUE TITLE
Include Abandoned Bounties in daily bounty email -

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4335]
Dean Ramadan [1:30 PM]
would be great if we can set up an automatic email to go out to the active contributors segment every time a bounty is abandoned letting them know that there is a new open bounty ready to claim

- [ ] include those bounties in the daily “new bounties” email

**Comment by Skyge** [comment]
It seems like what have been doing in our slack channel `#notif-gitcoin`, maybe we can provide a choice for them, if they would like to be notified when there is a new bounty.
