### ISSUE TITLE
Design - No Results for User Directory

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4336]
Create design for user directory when no results are found.

- [ ] Check to see how we do this on kudos
- [ ] Check to see how other products do this
- [ ] When no results return then display message that says "Looks like you searched for the for these criteria xyzzy and nothing was found"
- [ ] Show fun illustration, maybe (borrow from one of our other pages that show no results).
- [ ] Review with team
- [ ] Provide sketch file

**Comment by owocki** [comment]
for inspiration, checkout the kudos 'none found' page https://gitcoin.co/kudos/marketplace/?q=dsfdsdsfds

**Comment by willsputra** [comment]
@PixelantDesign we can do something like this. have a cute, simple animation and give 4 random users when someone clicks on the lever. sounds like a fun thing to do.
![Users Directory No Results](https://user-images.githubusercontent.com/19514207/57707450-3f446980-769a-11e9-81be-48795b1cc978.png)

animation example: https://dribbble.com/shots/5802142-Your-Data-Your-Way
