### ISSUE TITLE
BUG - After Completing Ratings - Next set of cards don't appear.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4342]
**Describe the bug**
BUG - After Completing Ratings - Next set of cards don't appear.

**To Reproduce**
Rate 5 cards, save them, click refresh page. The same 5 cards stay (without my ratings saved!).

**Expected behavior**
New set of unrated cards appear

**Screenshots**
<img width="1158" alt="Screen Shot 2019-05-01 at 9 57 42 AM" src="https://user-images.githubusercontent.com/238235/57020669-00250b80-6bf8-11e9-8038-f2c16c1c0eee.png">

<img width="1122" alt="Screen Shot 2019-05-01 at 9 56 08 AM" src="https://user-images.githubusercontent.com/238235/57020672-03b89280-6bf8-11e9-95d4-e00e4882ce2b.png">

**Desktop (please complete the following information):**

- OS:MAC
- Browser: CHROME
- Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

**Comment by kuhnchris** [comment]
Taking a look.
