### ISSUE TITLE
Update Day 2 Email to mention permissionless projects

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4345]
**User Feedback** - Day 2 email doesn't mention project types.

**Suggestion:** 
Changing the "Day 2: Using Gitcoin's Issue Explorer" automated email to mention permissionless projects. As I received on the 12th, it reads:

Click ‘Express Interest’ to provide a brief message to the repo-maintainer that you’re interested in the issue.

From here, you’ll receive an email and a notification when the issue is ready for you to work.

**Comment by kuhnchris** [comment]
You mean this one?
https://github.com/gitcoinco/web/blob/b1eeee921dcaf1d1f217e04fa0095cb26ab922b0/app/retail/templates/emails/campaigns/email_campaign_day_2.txt
