### ISSUE TITLE
gitcoin.co/explorer should allow you to serach by funder username

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4346]
gitcoin.co/explorer should allow you to serach by funder username

if you search statussceptre you will not see bounties funded by @statussceptre ; this should be fixed

**Comment by Skyge** [comment]
Does that mean when we search for everything, we should make it to be case sensitive?

**Comment by Skyge** [comment]
I would like to fix this issue, if possible, please keep this for me.

**Comment by owocki** [comment]
case insensitive pls
