### ISSUE TITLE
users directory filters with issues

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4353]
**Describe the bug**

Bounties completed is showing wrong results
![image](https://user-images.githubusercontent.com/1358093/57097972-5de84f00-6cef-11e9-8119-b2c32f65a79c.png)

Leaderboard data is creating dupes and showing wrong data 
![image](https://user-images.githubusercontent.com/1358093/57098006-76586980-6cef-11e9-83b2-b20e763bda08.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
i can bounty it if u guys want
