### ISSUE TITLE
rate your bounties in profile showing rinkeby and repeated bounties

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4354]
**Describe the bug**

**To Reproduce**

Query in profile "rate your bounties" is showing repeated bounties and rinkeby bounties 

#4343 #4342

**Expected behavior**

filters should be .distrinct(pk) to show one time per bounty and should show only mainnet bounties in production

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by kuhnchris** [comment]
see #4344 for WIP pull request, cannot test so WIP. :-(

**Comment by PixelantDesign** [comment]
@kuhnchris how come you arent able to test?

**Comment by kuhnchris** [comment]
@PixelantDesign because I was not able to build the platform since I had troubles with my PC back in may. The PR is already closed and stale so this one can be closed as well, since octavio's PR is already merged since june.
