### ISSUE TITLE
Creating Sub-Pools in Gitcoin Grants

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4364]
### User Story

As a funder I want to fund only a select pool of projects.

### Description

To date there has been one single CLR matching pool. It could be helpful (especially as we seek to work with projects that do not benefit one particular chain and funders who wish to only fund projects that benefit one particular chain) to split our CLR matching into sub-pools (i.e. pools where only a subset of all projects are matched). 

To make this less confusing to users, we should split projects into different sub-pools into different 'tabs' on the UI. All projects should appear in only one tab. For the purpose of Round 3, the tabs we're considering using are: 1.x, Ethereum (General), P2P Infrastructure.

### Definition of Done

Exact requirements still need to be defined.

**Comment by owocki** [comment]
what are the product impilcations of this @ceresstation @vs77bb @PixelantDesign ?

here's what i think it should be

1. the tabs on the /grants explorer should reflect which grant is in which sub-pool.  (we need a list of which grants are in which pool upfront)
2. the banner on the /grants explorer and grants detail page should show which sub pool each is in.
3. when you agree to contribute to matching funds you can choose which pool it goes to.

anything else?
