### ISSUE TITLE
"Submit" Button in modals allow double commits, causing GitcoinBot to double-post.

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4365]
**Example**
https://github.com/polkadot-js/apps/issues/940#issuecomment-489439253

**Describe the bug**
gitcoinbot double posts on github

**To Reproduce**
Pressing the "Submit" button in "Express Interest" twice, according to @kshitij98

**Comment by kshitij98** [comment]
The reason why gitcoinbot is posting twice in this case is because the Submit button inside `Express Interest` modal was clicked twice before the page being reloaded and the user was able to apply twice on the same bounty.

**Comment by kuhnchris** [comment]
Oh, thanks for tuning in, I guess in this case I'll need to rework this issue to avoid multiple modal handlings.

**Comment by owocki** [comment]
we could also de-dupe it in the expiration_start_work mgmt command
