### ISSUE TITLE
Collusion Resistance: Capping Contributions by Gitcoin Grants Security Rating Tiers

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4369]
### User Story

Related to #3520, as a grantee I would like to ensure the system isn't being gamed and I have a fair shot of receiving a reasonable amount of matching funding. 

### Assumption
Human - Without a collusion resistance mechanism, the probability of someone gaming the system is higher.
Business - If we did this, CLR contributions should be much more fair. 
Tech - We can find and obtain a 3rd party provider that is willing to work with a crypto company that isn't really doing KYC (phone). Lessen these types of issues but no way to eliminate.

### Description

One way to achieve this is to limit the total amount that individuals can contribute based on a 'security rating'. Similar to the idea of profile completion, a user would gain more privileges the more 'complete' their security rating. 

### Current Behavior

There is no limit to how much a given funder can donate to a given project.
People are creating multiple accounts to get more match (game the system).

### Expected Behavior

There is a limit, in tiers, defined by set security ratings. We could begin by implementing #3520 style verification as a way to create one additional tier of security. A second option could be to implement a more formal request for phone numbers or other PIA.

### Definition of Done
- [ ] Mechanism to set a maximum grant contribution limit
- [ ] Verification of user profiles according to #3520
- [ ] Phone number as a hidden option of user profiles 
- [ ] A 'bar' on each user profile that describes how high their 'security rating' is

Estimate: XL
Split between overal surfacing and calculation of security rating on something simple.
Intergrate account age.
Intergrate Platforma activity
Intergrate Phone nUmber.

### Data (requirement)

Measurement

**Comment by kuhnchris** [comment]
Hmm, isn't that basically similar to that the 3Box guys are doing with their verification project? 
We need to make it clear that this doesn't turn into a KYC-type of deal, that scares away people faster than anything else in the ETH community.

Maybe make a short meeting with the 3box guys regarding their verification process, I think they basically started with similar ideas to yours.

**Comment by michaelsena** [comment]
Thanks for the ping @kuhnchris. @ceresstation and @owocki, at [3Box](https://github.com/3box/3box) we built a way to publicly verify user's github and twitter accounts, as well as privately verify their email address. It can be found here at [3box-verifications](https://github.com/3box/3box-verifications). @kamescg from ConsenSys has implemented our APIs for this into the MeshHub DAO he's working on. Let me know how I can help, would be happy to get you guys set up with this.

**Comment by danlipert** [comment]
As an 80/20 type solution I think we'll just go with Github account age and have a cutoff for CLR matching of either 3 or 6 months or so

**Comment by kuhnchris** [comment]
are we syncing this information already on the login process? if yes you could filter on the database for that attribute, else we may need to fetch the account creation date from the github api.
According to the github api @ https://developer.github.com/v3/users/ that would be "created_at"

**Comment by PixelantDesign** [comment]
@danlipert  to add admin override in case of a complaint.

**Comment by vs77bb** [comment]
Recommend a lowest tier for CLR matching: If the Github account was created after March 2019, likely cannot contribute to the round (unless they meet other parameters which makes us think they are real people).
