### ISSUE TITLE
Create Gitcoin UI Kit

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#437]
As a Gitcoin commnity participant, I want design assets that I can use when working on a task, so that I can design consistent with the brand and work efficiently.

# Description
Define ui elements for Gitcoin ( typography, color, buttons, forms, links,  lists, etc)

# Assumptions
Use existing brand but update to meet current ux/ui needs.

# Definition of Done
A sketch file is created and posted in the Gitcoin creative repository.

# Reviewers
@owocki @vs77bb

**Comment by PixelantDesign** [comment]
![Screen Shot 2018-02-27 at 12.07.44 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f46b7191a379ed0c2b56415b4abc30254d58eeb9cb74fce36f34985619e8806b0e77906e15adbb831bea50ba208f1b85e7badf4496fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae84a55ac123460ee7f356e0a.png)
[Gitcoin Sticker Sheet.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46cf9d8e208d8aa7cfdaab4aa756f58669752f762c10e1673295f127b54778154d555ca9105e0e47aaaa8d2aa5b73825db5c0be9856d0e72933547bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e46391e0d198df95f34a38b06.zip)

Done for now. Will continue to build out as we make other updates to the app.
@owocki @vs77bb @coderberry

**Comment by owocki** [comment]
just added a few comments about this over at https://github.com/gitcoinco/web/issues/421#issuecomment-368977775 ( which was the first time i saw the artifact)
