### ISSUE TITLE
Make it clear that there is a $500 bounty limit

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4374]
### User Story

As a funder I want to know that that there is a $500 bounty limit. I also want to know how much over the limot my bounty will be, and what I can do about it. Otherwise the transaction fails.

### What
Fix this issue

### Why
It’s not intuitive UX

**Comment by kuhnchris** [comment]
Define "500$ bounty limit". 
Per Bounty?
Per User?
Per Day?
And Limit as in: receiving or sending or providing?

Should it read: "Please be aware that you cannot fund your issue past $500.00 due to security reasons and technical limits." ?

**Comment by PixelantDesign** [comment]
- Make memo required (note on why)
- Make linking to bounty issue required
- Only allow tips to users of Gitcoin Bounties platform

**Comment by PixelantDesign** [comment]
@ceresstation anything else we're missing from the legal call?

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/4551 updates tip limits
