### ISSUE TITLE
Can't claim my bouty

### ISSUE THREAD

**Issue by MikaelLazarev** [gitcoinco/web#4377]
### Can't claim my prize
Hi, I participated in Ethereum hackahthon and get a prize of 7.44ETH. I received an email with instructions, but for this moment I could not withdraw it. Please check this video: https://youtu.be/6VRVfkCdOJQ

**Comment by thelostone-mc** [comment]
Hey @MikaelLazarev !
Ah, that's cause the transaction has not been written to the blockchain yet! (cause of low gas fees).
Check the red alert at the end of the recording 
Once the transaction goes through , you should be able to redeem it

@alexvotofuture / @willsputra/  @PixelantDesign 
We could make the message a lot more clearer ?

**Comment by owocki** [comment]
The error message reads "You must wait until the senders transaction confirm before claiming this tip."  

Looks like the tx just cleared ( https://etherscan.io/address/0x6faf06c29ece06579597842c80e2c39326e2e3e5 )

Can you try again @MikaelLazarev ?

Also can you paste the address you were trying to use to transfer funds?  If you can't get it, I'd be happy to try it for you, but I need your payout address first :)

**Comment by MikaelLazarev** [comment]
I tried, the same result

**Comment by MikaelLazarev** [comment]
Should I have gas to do this transaction? It seems that I have 0.008ETH on this account

**Comment by thelostone-mc** [comment]
You don't need to ! It should work 🤔 
Could you provide your payout  address (public address ) and we can try to process it for you  ? ^_^

**Comment by MikaelLazarev** [comment]
0x9BB3e5788a7786da32F2575e171CC412f83A9b64
Please!

**Comment by owocki** [comment]
hmm i can't reproduce the issue.  what browser are you on?

I was able to get the funds over to you to your desired payout address ( 0x9BB3e5788a7786da32F2575e171CC412f83A9b64 ) via https://etherscan.io/tx/0x5824da1386670e9de2e92de36f940df88f618ea319224e3f5671bc666201f7c6

**Comment by MikaelLazarev** [comment]
Thanks, guys! My browser is Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
