### ISSUE TITLE
Action's Required 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#4378]
### User Story
[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder / contributor, I want a section dedicated to 'actions required' of me. This could be the following. 

- You need to approve someone for bounty. 
- You need to pay out a bounty
- You may want to cancel a bounty

### Why Is this Needed
Notifications are nice, but they get lost in the shuffle. So do e-mails. If there is a list of 'actions' I need to take, they should all be in one place, prioritized, so I can knock them all out at once. 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: I've posted lots of bounties. There are probably 10+ bounties where action is required of me (some urgent, some non-urgent) and I don't have the cognitive capacity to remember them all. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Meander through my profile, my emails, or my notifications to try to figure out where I'm needed.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
A section which tells me all the things I need to do. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
How quickly urgent actions (worker approval, issue payment, etc.) are taken. Right now, the difference between 'Work Submitted' ---> 'Work Paid' may be high because funders forget to pay out. Can we reduce this time? Does this encourage them to do more bounties if they can keep more in their head organized at one time? 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Dashboard should solve this cc @willsputra
