### ISSUE TITLE
Better Matching 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4379]
### Why
- better matching of funders and contributors
- easy to find bounties
- make it easy to do automatic crossing between users
- more accurate recommendations

### User Stories
1) Funder Form - Create categories of bounties to do  a better matching:
- Add categories checkboxes to fund form 
[ ] FE
[ ] BE
[ ] DESIGN
[ ] DOC
[ ] OTHER

- make keywords and category should be "required"

_Task Breakdown_
- Display front end to funder form
- Add checkboxes
- Follow styles already set
- Send datâ to back end
- Create the categories in the backend
- Add table entry

FE 2, BE 3

2) should be editable in the "edit bounty""
- Add keywords to "edit bounty"

_Task Breakdown_
- Add keywords on front end
- Save on backend

FE 3, BE 2

3) Add this categories of interest in users settings
Prompt for users to complete info in settings (weekly email, daily bounty email)

_Task Breakdown_
- Add fields
- Add same data
- Saving info in the fields
- Retrieve the data when profile request is made

FE 3, BE 3

4) Add this categories of interest in onboard 

_Task Breakdown_
- Add fields
- Add same data
- Saving info in the fields
- Retrieve the data when profile request is made

FE 3, BE 3

5) Add to issue details and card

_Task Breakdown_
- display in explorer and on each card
- Provide data to display on front-end

FE 3, BE 3
Design - Display on Cards 2

**Questions**
What is the default for past already created bounties?
What happens with current funded bounties - what categories do we give them?
Ambssador/issue explorer check-in do it...need to do it before it's deployed.

**V2**

3) Add this categories of interest in users setting + onboard 
Prompt for users to complete info in settings (email, other ideas: notification, dashboard, profile completion, kudos).
Adding a category filter in explorer, 
Adding category filter to users directory.
Adding matching to user dashboard (for contributors as suggested bounties and for funders for suggest people to invite to work on each bounty they have open)

**Comment by kuhnchris** [comment]
Wouldn't that be just a "tag" tho?
Or you really want something separate for that?

**Comment by octavioamu** [comment]
we want it separate because we already have keywords that can be anything but we want categories to better matching between the interest from hunters and the issue category.

**Comment by octavioamu** [comment]
Also there is a lot of bounties with keywords that doesn't reflect for real what skills the worked need, for example is a backend task? is a front end?  if the keyword css and html are there can be confusing.

**Comment by kuhnchris** [comment]
OK but do you want to reference those categories from tags or keywords, or is it yet another thing a funder has to fill in order to submit his bounty? 
I just wonder if it makes sense to have the funder basically fill out a tax returns' paper amount worth of data to submit a bounty.

**Comment by PixelantDesign** [comment]
I chatted iwth Bounties network - this is something they're considering as well.
