### ISSUE TITLE
As a Gitcoin user, my avatar is still showing up as random in certain areas of the Gitcoin site.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4382]
**Describe the bug**
As a Gitcoin user, my avatar is still showing up as random in certain areas of the Gitcoin site.

**To Reproduce**

Scott Moore [12:24]
Correct yeah
Go to the explorer and scroll you'll see like 20 that pop up that way

Scott Moore [21:30]
I feel like it’s probably not a huge deal but at the same time it kind of violates the consent of the user (I’m not sure how many users actually know that the randomized avatar that was generated for them is showing up in all these places) 

**Expected behavior**

Was this part of the avatar rollback that occurred a couple weeks ago? We want to make sure the randomly generated avatars aren't appearing in other parts of the site (essentially ensure that all avatars are consistent).

**Screenshots**

<img width="1263" alt="ba9b7d0d8b72b5f2faec5651b1b84d5c" src="https://user-images.githubusercontent.com/7516920/55343415-e4471200-545f-11e9-807a-78a5eb84bd68.png">

**Related Issue**
https://github.com/gitcoinco/web/issues/4085

**Comment by kuhnchris** [comment]
Could we simply... clean up this entire mess regarding avatars? We already did some start proposals, but stuff like the 3box.io integration and others are depending on a final decision on the avatars. It kind of died after Mark left, who did some incredible work previously to rework the avatar system (+ color wheel to individualize every part of your avatar) and to unify the avatar system. Right now you can access it various ways ,via Users, via Avatar via Profile, and some of them lead to different results.

**Comment by owocki** [comment]
@frankchen07 which users avatar is random and can i have a link to their profile?

**Comment by frankchen07** [comment]
@owocki I don't see it too often, but there are still some purple avatars (unless they're able to make a purple avatar on their own). Two examples:

@axelios
@trinhvv

They're also duplicated in the user directory, but that's a different story.

**Comment by owocki** [comment]
i'd happily clean them up, i was waiting to hear back on https://github.com/gitcoinco/web/issues/4085#issuecomment-483099985 tho -- should i just go for it?

**Comment by frankchen07** [comment]
yeah go for it, I think the decision to remove randomly generated avatars has at least 3 backers.

**Comment by owocki** [comment]
ok deleting them now.  should take < 15 minutes to delete them all

**Comment by PixelantDesign** [comment]
was this completed @owocki ?

**Comment by owocki** [comment]
yes
