### ISSUE TITLE
Unable to claim bounty

### ISSUE THREAD

**Issue by TheBlockchainDeveloper** [gitcoinco/web#4384]
**Describe the bug**

I received "New Tip Alert", however when I try to redeem I receive the following error message "You must wait until the senders transaction confirm before claiming this tip."

Appears to be the same or similar to this bug: https://github.com/gitcoinco/web/issues/4377

**To Reproduce**

1) click on link on New Tip Alert email "Redeem Tip" button.
2) MetaMask fill automatically the Ethereum address.
3) Check "I understand & agree to the terms of service."
4) Press "Claim DAI" button.

**Expected behavior**

DAI transferred to the Ethereum account.

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)
<img width="850" alt="Screenshot 2019-05-14 at 00 29 06" src="https://user-images.githubusercontent.com/139483/57671884-475ec380-761e-11e9-8863-ffb2b09b698e.png">

**Desktop (please complete the following information):**

- OS: MacOS 10.14.4
- Browser: Chrome
- Browser Version:  74.0.3729.131 

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
Thanks @TheBlockchainDeveloper -- what address would you like your tip to go to?  

you are using Chrome right?  What version?

**Comment by TheBlockchainDeveloper** [comment]
Yes, I am using chrome version 74.0.3729.131. Thank you. 0x9D329842b5c5eECe3b094E7B4643a081cC6525CC

**Comment by owocki** [comment]
i was able to get it claimed and sent directly to you https://etherscan.io/tx/0xe0434f46075c0ba1775405a830700d9db7377134e006f34728cd4d76fecc2df7

hmmm i wonder why ican't seem to repro it tho.   i'm using chrome Version 74.0.3729.131 (Official Build) (64-bit)
Automatically update Chrome for all users Learn more
