### ISSUE TITLE
Applications On Gitcoin

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#4386]
To see a worker application, I have to 'View on Github'.

Should there be a place on the Issue Details page (maybe a rollover) where I can see all the applications and make a decision without the extra click? 

https://imgur.com/a/G0Ex5Um

Furthermore, once I get to Github, if I want to know how many Github contributions an applicant has, I have to click 1) *back* into their Gitcoin profile and then 2) click their Github profile and then 3) click 'Overview' to finally see how many contributions they have made. 

It'd be great to have a place for applications on Gitcoin, where I can approve or deny workers, without having to go to the Github thread.

**Comment by willsputra** [comment]
Maybe we can display each user's application detail in the flyout? The flyout shouldn't cover the Accept/Reject buttons though.
![Application](https://user-images.githubusercontent.com/19514207/57940843-8da27400-78f7-11e9-844b-64811aa38fab.jpg)

**Comment by octavioamu** [comment]
@willsputra can we put next to the username? since this other label change depending on the state
