### ISSUE TITLE
As a gitcoin user, when I create a grant, I do not want to see duplicate contributors

### ISSUE THREAD

**Issue by Skyge** [gitcoinco/web#4389]
### User Story

As a gitcoin user, I want to get the correct number of a grant contributors.

### Why Is this Needed

There are some duplications in the grant contributors, so sometimes it misleads me.

*Summary*:

### Description

*Type*:Feature

### Current Behavior

![image](https://user-images.githubusercontent.com/27282380/57713920-fabecb00-76a5-11e9-97c1-026b773c8f40.png)

As you can above, it will display five contributors, but as a matter of fact, it is just some extra donations, and it is two people.

### Expected Behavior
Remove duplicate contributors.

**Comment by Skyge** [comment]
What a pity! when I have done this, I find I am too naive, there are some more problem about this.
![image](https://user-images.githubusercontent.com/27282380/57714706-a9174000-76a7-11e9-9f53-39adcfc23779.png)
these donations are pending, so we should not count these contributors until the status becomes completed, it should also be corrected at here:
![image](https://user-images.githubusercontent.com/27282380/57715034-63a74280-76a8-11e9-99e2-78f4c5fd8dea.png)

**Comment by Skyge** [comment]
So if there is a necessary, I will continue doing it.

**Comment by PixelantDesign** [comment]
Great ideas! Thanks for the suggestions! Want to help us build it out?

**Comment by Skyge** [comment]
@PixelantDesign Yeah, of course. I am doing on it.

**Comment by Skyge** [comment]
@PixelantDesign I have done, so the result may be look like this:

![image](https://user-images.githubusercontent.com/27282380/57783820-64e87600-7761-11e9-95bd-0f6abf130db7.png)

![image](https://user-images.githubusercontent.com/27282380/57783831-6a45c080-7761-11e9-84aa-6fbfab0250ed.png)

![image](https://user-images.githubusercontent.com/27282380/57783839-6e71de00-7761-11e9-8f96-c2cf3fabc2cd.png)

Just like showing above, you can see there are some contributions at the `ACTIVITY` in the second screenshot, but because they are still at the stage of `pending`, so we will not count them at the `CONTRIBUTIONS` in the first screenshot, and at the same time, it will also be no contribution at the third screenshot.

**Comment by Skyge** [comment]
@PixelantDesign What do you think about this change? should it behave like this? or is there something else to modify?
