### ISSUE TITLE
Funder Form - UX Display Contributor Details in Invite to Bounty

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4396]
### User Story
As a funder, I'd like more reminders on the recommended contributors I've worked with before.

### Current Implementation
<img width="850" alt="Screen Shot 2019-05-15 at 4 55 09 AM" src="https://user-images.githubusercontent.com/238235/57762538-ab8c9080-76cd-11e9-9a7c-f3ed30239be4.png">

When a contributor is selected, the contributor should be removed from the list
<img width="859" alt="Screen Shot 2019-05-15 at 4 54 54 AM" src="https://user-images.githubusercontent.com/238235/57762544-b0514480-76cd-11e9-99e3-35873e92977d.png">

<img width="875" alt="Screen Shot 2019-05-15 at 4 53 56 AM" src="https://user-images.githubusercontent.com/238235/57762416-7a13c500-76cd-11e9-85bb-a5f7f8f3ed59.png">

### Definition of Done
- Refer to funder feedback notes on Notion
- Create UX recommendations for what we should display to make this more useful
- Consider happy and failure paths
- Consult with engineering team on tech approach
- Share with funders for feedback
- Provide final design and source file on this ticket

### Possible Solutions
- Popover/flyout detailing when you last worked with the contributor
- What you worked with the contributor on
- Star Ratings

### Data Measurements
Increased successful working relationships between funders and contributors
Increased short and long term retention of funders
Decreased median time to bounty completion

### Reach
All funders that fund an issue

### Impact
High Impact 

### Confidence 
80%

**Comment by kuhnchris** [comment]
Maybe add some data, as you mentioned already, either in the list add the stars rating and "last time active".
For the selected one you could use the Profile-Card/Flyout.

Maybe also rename it from "Invite" to something else, it gives a facebook-y game invite-y kind of vibe, so people may not use it in fear to anger contributors. 
Maybe "Suggest your bounty to hunters directly:"

**Comment by PixelantDesign** [comment]
@vs77bb @ceresstation ?

**Comment by vs77bb** [comment]
Some things that would help me (as a funder):

- Job Completion % on Gitcoin (Bounties Done / Bounties Started) 
- # of Github Contributions This Year
- Eventually, star ratings (right now, as a funder, I don't know how much to trust these)

As @kuhnchris mentioned, it'd also be nice to organize these by 'active' hunters -- i.e. folks who have contributed to bounties in the last 3 months -- as this will increase the likelihood they apply.

**Comment by willsputra** [comment]
Maybe we could also put how many relevant bounties (bounties containing the same skill tags) that they've done?

![recommend](https://user-images.githubusercontent.com/19514207/58429950-18465880-80da-11e9-85b9-cad8547938b5.jpg)

**Comment by willsputra** [comment]
@vs77bb @ceresstation what do you think of the mockup above? is it enough to make a decision on who to pick?

> As @kuhnchris mentioned, it'd also be nice to organize these by 'active' hunters -- i.e. folks who have contributed to bounties in the last 3 months -- as this will increase the likelihood they apply.

@octavioamu what do you think of having an 'Active' status? maybe something like 'Last active 3d ago'?

**Comment by PixelantDesign** [comment]
We dont have data for success rate and we can't do languages because it's not that accurate. @willsputra

**Comment by PixelantDesign** [comment]
@octavioamu to look at what makes sense from user directory

**Comment by kuhnchris** [comment]
Well, if we rank by languages it actually enforces and encourages users to interact with the platform to get ranked higher if they fill out their profile... which in turn helps for the user directory.

Regarding "success rate" - you do have that data. Completed Bounties divided by accepted bounties.
