### ISSUE TITLE
User Directory - UX Add Ability for Funders to Favorite Contributors

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4397]
### User Story
As a funder, I'd like to be able to favorite/save a list of go to contributors in the User Directory.

Idea
https://github.com/gitcoinco/web/issues/4361

### Definition of Done
- Ux what this would look like
- Consider happy and failure paths
- Share with funders and core team for feedback
- Provide final design and final source file on this ticket

### Why
- Help funders find /remember good contributors 
- show value in user directory
- create reasons for funders to come back and use the user directory

**Comment by kuhnchris** [comment]
Wouldn't it be sufficient to provide a "Star" symbol ☆ --> ★ in the User Directory and/or the Bounty page, so the funder can 'bookmark' those people? And after that, simply pre-sort them on /users by applying an additional filter (for example: is_favorite__eq=true)

... basically you'd create User Favorite Directories with that.

**Comment by vs77bb** [comment]
I like the star idea! We could also use this information to help surface these contributors to *other* funders. 

I.e. Onuwa has 7 stars -- so he gets recommended to more funders, as a result.

**Comment by PixelantDesign** [comment]
Follow on ticket - add opt in on submit work to follow/favorite this funder and stay up to date on their bounties.

**Comment by willsputra** [comment]
How about a heart? We're already using stars for the ratings, might confuse people if it shows up for two different use cases.

I agree with @kuhnchris' idea of having an additional filter! We can display it on the sidebar as 'Favorites' filter.

![heart](https://user-images.githubusercontent.com/19514207/58111506-269cfc00-7c24-11e9-9805-5311155ea98d.png)

**Comment by kuhnchris** [comment]
help me out - aren't we using the heart already somewhere on the bounties?
If no - fine by me
If yes - no, confusing.

**Comment by PixelantDesign** [comment]
We aren't using the heart anywhere else in the system.

**Comment by octavioamu** [comment]
I believe the favorite option should be with the others options in the dropdown 
![image](https://user-images.githubusercontent.com/1358093/59928071-4a668400-9414-11e9-82d9-51ae45d3c91d.png)

**Comment by octavioamu** [comment]
Related to #4706 a ticket to do the backend

**Comment by PixelantDesign** [comment]
@octavioamu do we need teh backend completed first?

**Comment by PixelantDesign** [comment]
If we put it in the drop down, it's very hidden @octavioamu, I prefer @willsputra propolsal
