### ISSUE TITLE
A New Front End Framework

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#440]
*For Discussion*

As a user I want a fast, modern, functional and consistent UI experience across the Gitcoin App

# Description
- Tech approach to a new front end frame work

# Definition of Done
- Hold meetings with outcomes
- Align on tech approach for the front end & document

# Reviewers
@owocki  @PixelantDesign @mbeacom

**Comment by sethmcleod** [comment]
I'd love to help out with this one! See my work on the [ideas page](https://github.com/gitcoinco/web/issues/198#issuecomment-365790730)

**Comment by owocki** [comment]
@mbeacom @saptaks @thelostone-mc its certainly worth having this convo on a team call soon :P
