### ISSUE TITLE
User Directory - Email - Design Remind Funder to Use User Directory if Contributor has not been selected

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4401]
### User Story
As a Funder I'd like a reminded to checkout the user directory if a  contributor has not been accepted to work on my Bounty after 24 hours.

### Definition of Done
- Design an email that reminds funders to search for a user after 24 hours.
- Consider interesting subject line - Increase your chances of success!
- Consider including this in other emails that Funder's currently get.
- Share with team for feedback
- Post final design and source file on this ticket

### Why
- We'd like to help funders find good contributors to work with

**Comment by kuhnchris** [comment]
* Add an option to opt-out in the user settings
* Add an option to the signal there isn't anyone with the required skill-set i'd like to suggest
[X] I did not see/want anyone suggested in this list with the skill set I need.
* Report to see which tagged bounties have that flag set the most (skill-based analysis)

**Comment by PixelantDesign** [comment]
Include in current funded bounty email.

**Comment by willsputra** [comment]
@kuhnchris @PixelantDesign thoughts?

I'd love to show a list of suggested users right inside the email, but I think asking funders to check out the Users Directory should be enough for the first version.

![Weekly Recap](https://user-images.githubusercontent.com/19514207/58110414-0d934b80-7c22-11e9-9da5-54f1cde701a9.jpg)

**Comment by kuhnchris** [comment]
Maybe throw in 2 or 3 suggestions in the "Seems like you haven't picked an applicant" block, not sure if I want to have it above or below the entries. I think above would make the most sense to me.

Aside from that, LG2M
