### ISSUE TITLE
User Directory - Build No Results Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4407]
#### User Story

As a user of the user directory, I'd like to have recommendations on what to do when there are no relevant results. 

#### Definition of Done

- Build a delightful experience to decrease frustration when a user doesn't find the result they're looking for.
- Build simple animation and give 4 random users when someone clicks on the lever. sounds like a fun thing to do.
- Leverage bootstrap classes + existing and avoid redefining css. 
- Post a screenshot or video
-  Ensure design is responsive

animation example: https://dribbble.com/shots/5802142-Your-Data-Your-Way

![Users Directory No Results](https://user-images.githubusercontent.com/19514207/57707450-3f446980-769a-11e9-81be-48795b1cc978.png)

Review with core team @willsputra

**Comment by thelostone-mc** [comment]
@PixelantDesign / @octavioamu I don't think this would be an easy task 
Would it make more sense to do the same without the animation 
On clicking lever -> the list just refreshes? 
It's a no results page so probably keeping it simple makes more sense in my head

**Comment by willsputra** [comment]
@thelostone-mc I think we can start even without the animation :)
@PixelantDesign what do you think?

**Comment by Skyge** [comment]
> Build a delightful experience to decrease frustration when a user doesn't find the result they're looking for.

Maybe we can return some similar users, such as when I search user: `skyg`, maybe it could return `The user you were looking for isn't here, do you mean you want to look for user named skyge?`, but there will be another question, if I just input `s`, it will return many users whose name contains `s`, so maybe we can use a drop list.

> Build simple animation and give 4 random users when someone clicks on the lever. sounds like a fun thing to do.

Yeah, this is really fun enough.
