### ISSUE TITLE
Add Email Capture to Gitcoin.co Landing Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4413]
### User Story
As Gitcoin we'd like to capture emails from contributors and funders and send relevant emails so that they immediately get value out of Gitcoin.

### Definition of Done
- Build Front end of email capture with toggle
- Add this below the Before and After Graphic on the Gitcoin.co homepage
- Build backend to capture emails (these email lists should be able to export to Mailchimp)
- Review with Dean Ramadan

<img width="949" alt="Screen Shot 2019-05-15 at 12 47 56 PM" src="https://user-images.githubusercontent.com/238235/57793606-bd8f2300-770f-11e9-8edd-e862a5029ef1.png">

**Comment by octavioamu** [comment]
I believe mailchimp needs name and surname fields
https://mailchimp.com/help/add-a-signup-form-to-your-website/

**Comment by octavioamu** [comment]
We need to decide where (which account) are we going to host the lists so I can put the right codes in the forms
