### ISSUE TITLE
As a Gitcoin operator, I want to finish up and release the Wyre on-ramp.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4414]
### User Story

As a Gitcoin operator, I want to finish up discussion and options around Wyre and release the on-ramp.

### Why Is this Needed

Fiat on-ramp has the potential to lower onboarding blockers and potentially reach out to a new market.

### Description

https://gist.github.com/thelostone-mc/506d2e3aae997ebdf5f5226df7d1fb2e

1. ACH vs debit, additional quick discussion on which would be better for our users? (debit seems better)

2. differences between individual and business accounts, would the option be confusing? what additional overheads if we want to pursue that path (sounds like business would be tough)?

3. what does the widget versus dashboard look like?

### Current Behavior

demo here: https://gist.github.com/thelostone-mc/506d2e3aae997ebdf5f5226df7d1fb2e

### Expected Behavior
TBD

### Definition of Done
TBD

### Data Requirements
TBD

**Comment by thelostone-mc** [comment]
^ I'll give a walkthrough tom. I just got some basic integration 'wyred' up

**Comment by frankchen07** [comment]
ba-dum-ching

**Comment by thelostone-mc** [comment]
update:  won't be pursuing integrating wyre given the friction.
We'd be exploring cross-chain availabilities. 
Will explore fiat -> non-fiat exchanges when the ecosystem matures
