### ISSUE TITLE
BE - Divide Gitcoin Users List into two separate personas for designation

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4415]
### User Story

As Gitcoin, we'd like to be able to divide our users list into two separate personas: funders & contributors.

### Why Is this Needed
We want to be able to be more targeted about our experiences and messaging.

### Definition of Done

- Work with Frank - figure out the logic - what defines bounty hunger, funder active/inactive
- Translate into Django code
- Write migration to set these values for each user.
- Write a cron job that will run every day or so to recalculate whether logic still applies to them.
- Review with @frankchen07 @PixelantDesign @danlipert 

### Data Requirements
TBD

### Additional Information

https://metabase.gitcoin.co/question/272

**Comment by owocki** [comment]
@willsputra has done some great work on a dashboard design that allows uesrs to toggle between funder mode and coder mode..
