### ISSUE TITLE
As a user, I want to add an 'apply' step to the bounty process, so I can accept the best applicants

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#442]
This would probably be between open and work started
![screen shot 2018-02-14 at 7 38 37 am](https://user-images.githubusercontent.com/513929/36209840-189358a6-115a-11e8-831e-a97b8a722c9b.png)

**Comment by lazaridiscom** [comment]
"Code has been completed" => "work has been completed" (more general, e.g. design bounties, brain-storming bounties, etc.).

I personally do not like the "apply" step. It should be clarified what the goals of gitcoin are:

- Serving open-source / open-work
- Serving the funders

See, in "wild-west" no rules: bring in, get bounty. Results count, results rule.

**Comment by lazaridiscom** [comment]
Going to the other extreme:

 **Mecha-Bounty**: A bounty which follows a mechanic process:

Funders:
- no quests, no talk
- provide concise task, concise test-cases
- set bounty

Hunters:
- no questions, no talk
- just provide the result, so the test-cases pass
=> get your bounty
