### ISSUE TITLE
Matching - Keyword not updated on Users Profile and Directory

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#4424]
**Describe the bug**

I've updated my skills keywords on Manage Settings > Matching, but it's not updated on Users Directory

**To Reproduce**

1. Go to Manage Settings > Matching and update keyword (e.g. 'design')
![Screenshot 2019-05-17 00 48 07](https://user-images.githubusercontent.com/19514207/57872160-a8b0ad80-783d-11e9-980f-672e5af131a1.png)

2. Search for the keyword on Users Directory(e.g. 'design'). Not found.
![Screenshot 2019-05-17 00 48 14](https://user-images.githubusercontent.com/19514207/57872194-bf570480-783d-11e9-93a0-a06e1c52b45c.png)

3. If I search for my username, it still displays old keywords (e.g. 'Shell', 'CSS', etc.)
![Screenshot 2019-05-17 00 48 42](https://user-images.githubusercontent.com/19514207/57872238-d8f84c00-783d-11e9-8b74-b76660ae9b4f.png)

(octavio edit)
Also onboard keywords seems not saved anywhere 
![image](https://user-images.githubusercontent.com/1358093/63597873-c73ce800-c594-11e9-9356-4109b9925b74.png)

**Expected behavior**
Keywords should be updated on Users Directory.

**Comment by Skyge** [comment]
It seems like they use different ways to show, that is, you use this way to change keywords, but the code does not use that to show, it uses another way, so no matter what you change, it will not display.

**Comment by owocki** [comment]
Matching SEttings updates the `EmailSubscriber` object not the `Profile` object.  It should probably update both, and we should perhaps have some other way of making sure that those two objects keywrods are kept in sync.

**Comment by Skyge** [comment]
@owocki  Is it necessary to keep both same fields at the same time? Since they represent the same meaning, why not just keep one? If keeping one, which one? `Profile` or `EmailSubscriber`?

**Comment by owocki** [comment]
not every emailsubscriber has a profile, but other than that.. thats a valid fix path too IMHO

**Comment by owocki** [comment]
just submitted a PR to fix this ^^

**Comment by PixelantDesign** [comment]
settings matches automatic email - when changes are made, it's not reflected in the user directory.
Need to unify everything and fix filters in user directory.
