### ISSUE TITLE
Split dashboard app into multiple Django apps

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#443]
# Split Dashboard App

### Steps

- [ ] Add new django apps (`docker-compose exec web app/manage.py startapp <app_name>`)
- [ ] Move classes and methods to the relevant app
- [ ] Update references to methods/classes throughout the project
- [ ] Add `urls.py` for each new app
- [ ] Import and `include()` the new `urls.py` in `app/urls.py`
- [ ] Migrate relevant Django models and data

### Possible apps:

- `account`
- `network`
- `dashboard`
- `...`

**Comment by owocki** [comment]
i just worry about that file getting too big.. not sure if thats a legit concern though
