### ISSUE TITLE
As a Gitcoin operator, I want to patch up security issues related to uploading.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4432]
### User Story

As a Gitcoin operator, I want to patch up security issues related to uploading.

### Why Is this Needed

Unrestricted file uploads are a security risk.

### Current Behavior

Unrestricted file uploads
### Expected Behavior

Restricted file uploads using `libmagic`

### Definition of Done
- [ ] restricted file uploads

**Comment by kuhnchris** [comment]
Uh, differently asked: where the F are files uploaded and reused? Avatar? CV?

**Comment by frankchen07** [comment]
@kuhnchris - this ticket was deliberately left vague as to not explicitly let the public know of the vulnerability itself (maybe overly cautious, but better safe than sorry). It's a core ticket that has been brought to @danlipert - feel free to reach out to him directly on Slack if you'd like to the lowdown!
