### ISSUE TITLE
Grants monthly recurring showing negative amount

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#4433]
**Describe the bug**
https://gitcoin.co/grants/12/gitcoin-open-source-support-fund shows negative amount in Monthly Recurring

<img width="368" alt="Screenshot 2019-05-17 23 39 52" src="https://user-images.githubusercontent.com/19514207/57943024-2ab3db80-78fd-11e9-90e9-63883f6f2abd.png">
<img width="1500" alt="Screenshot 2019-05-17 23 41 45" src="https://user-images.githubusercontent.com/19514207/57943094-62bb1e80-78fd-11e9-8323-94b178cc53e7.png">

**Comment by PixelantDesign** [comment]
Thanks @willsputra !

**Comment by kuhnchris** [comment]
uuuuuuh, how does one have negative fundings? is it a contract bug?

**Comment by owocki** [comment]
i put a fix in for this a couple weeks ago :)
