### ISSUE TITLE
Funder FTUX Enhancements

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4436]
### User Story

Funder FTUX Enhancements

### Why Is this Needed

Gitcoin is looking at areas to improve in terms of user activation on the funder (supply side) side of the marketplace. We've noticed through user journey mapping that our FTUX onboarding experience can be improved. 

### Description

This ticket encompasses several changes:

<img width="1673" alt="Screen Shot 2019-05-17 at 15 52 05" src="https://user-images.githubusercontent.com/7516920/57960148-17cce700-78bc-11e9-938a-439d9cc56461.png">

> new user

someone who does not have a gitcoin/github profile hooked up / has not yet gone through the funder onboarding flow.

> returning user

a user that does have a gitcoin/github profile hooked up (aka, they have gone through the funder onboarding flow if they're using an incognito window, they should experience the new user ftux flow.

- [x] 1a. If one is a new user, A should deposit them at the beginning of the funder flow (https://gitcoin.co/onboard/funder/).
- [x] 1b. If one is a returning user, A should deposit them at (https://gitcoin.co/bounty/quickstart).

- [x] 2. On https://gitcoin.co/bounty/quickstart, "Developer Guide" should be changed to "Funder Guide".

- [x] 3. The case that should **NEVER** occur is a new or returning funder ends up on https://gitcoin.co/funding/new without being logged into Github, which is possible at the time of this ticket.

- [x] keep the button "fund an issue" as is, regardless of user

### Current Behavior

1. The funder can access the funding page without logging into Github.

2. The funder onboarding flow is not captured well on HotJar - redirecting all existing funder elements for first time users and returning users to the right pages will make it more clear.

### Expected Behavior

new users should be redirected to the correct onboarding flow

returning users should be redirected to the funder guide / funder page

### Definition of Done
- [ ] 1a and 1b works as expected, with the updated definitions of new/returning user
- [x] 2 works as expected
- [x] 3 is working and is a non-negotiable condition
- [x] the "fund an issue" button should stay regardless of user

### Data Requirements
- [ ] data tracking for hotjar

### Additional Information
@frankchen07 to review with @thelostone-mc for additional edge cases and get his expert opinion

**Comment by thelostone-mc** [comment]
@frankchen07 what qualifies as a new user / returning user ?

Is a new user one who's never
- never visited the site OR
- who's never created a bounty OR
- who's never created a bounty but has worked on bounties ?

Is a returning user one who's never 
- created / worked on a bounty OR
- created a bounty?

**Comment by frankchen07** [comment]
> new user

someone who does not have a gitcoin/github profile hooked up

> returning user

a user that does have a gitcoin/github profile hooked up - if they're using an incognito window, they should experience the new user ftux flow.

does that answer your qq?
