### ISSUE TITLE
Can not click a grant project card.

### ISSUE THREAD

**Issue by Skyge** [gitcoinco/web#4437]
I am not sure whether this is right. when we look through at the page: https://gitcoin.co/grants/  we can see some open source projects, like this: 

![image](https://user-images.githubusercontent.com/27282380/57969617-93599180-79ab-11e9-9b94-1d7c0cbd3c92.png)

As before, we can click a project card, and it will reverse, like this: 

![image](https://user-images.githubusercontent.com/27282380/57969771-9903a700-79ac-11e9-8fb3-7703b545aa22.png)

but now, it seems like that will not happen, that is, when I click it, nothing will happen, so do we remove this motion? or there is something wrong with it?

**Comment by thelostone-mc** [comment]
Fixed over at https://github.com/gitcoinco/web/pull/4438 ^_^

**Comment by Skyge** [comment]
@thelostone-mc So I can close this issue now?

**Comment by thelostone-mc** [comment]
Ah you can't leave it open ! It'll get closed when we merge and deploy
Thanks for the raising the issue mate 🙌
