### ISSUE TITLE
as a developer, i want stage server to always have a fresh prod backup on it, so i can stage latest data

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#444]
requirements:
- stage server should download / restore backup from prod on it nightly

**Comment by mbeacom** [comment]
I'm going to add this as a subtask to the multi-QA environment project.  Seems like it'd be easier to:

- Fetch the latest prod backup from S3
- Import DB dump into the QA db
- Run migrations
- Run job to update all media asset fields entries for staging (avatar assets are stored in a different bucket and subdomain on staging).

**Comment by danlipert** [comment]
This would be nice - maybe we can organize an epic/project board for staging resurrection and improvements? what do you think @kuhnchris would you be interested in organizing it?

**Comment by kuhnchris** [comment]
@danlipert sure, interested yes - it only makes sense for "big" changes tho, or for test cycles (e.a. either on demand or during the test cycles before deployment) - anything particular you need me to think this through?

**Comment by owocki** [comment]
if we do this, we need to harden the stage servers to prevent prod data leaks.  (put the web interface behind a password is probably the first step)

**Comment by kuhnchris** [comment]
yes, either that - or use a system like Guacamole for remote access, or require a VPN (openVPN + docker is so easily set up, it's a crime)
