### ISSUE TITLE
[Profile/Flyover/Card] Allow pinning of kudos

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4440]
### User Story
As a gitcoin contributor and user I want to show off my swag and pin a number of kudos I received to show that I'm a big catch around here.

### Why Is this Needed
Currently there is no way to show my swag.

### Description
*Type*: Feature

### Current Behavior
Cannot swag

### Expected Behavior
Swag

### Definition of Done
Showing (small) Kudos icons on the profile flyout.

### Additional Information
(shameless self-promotion) I already kind of did something similar with a custom dapp, but it makes more sense, since it's directly on the platform, to integrate it, and also to help promote the kudos NFT a bit more.

**Comment by PixelantDesign** [comment]
Cool idea @kuhnchris ! Want to help us mockup where this could go?
