### ISSUE TITLE
[Kudos] Ambo Launch Kudos' Lambo SVG is broken

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4441]
Seems like the SVG bolted.

![grafik](https://user-images.githubusercontent.com/761911/57983786-0ae3fb00-7a56-11e9-8f55-3ab5e4b1c2bd.png)

https://gitcoin.co/kudos/2619/ambo_launch_kudos

**Comment by PixelantDesign** [comment]
Thanks @kuhnchris !

**Comment by octavioamu** [comment]
What browser is? Seems to me that is working fine in chrome. 
![image](https://user-images.githubusercontent.com/1358093/58025089-0d903000-7aea-11e9-953b-c4e8a5eb03c3.png)

**Comment by kuhnchris** [comment]
Firefox
