### ISSUE TITLE
[Kudos/Contract] ipfs(.gitcoin.co) is retired, breaks contract URIs

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4442]
**Describe the bug**
According to @danlipert the ipfs.gitcoin.co server is retired in favor of ipfs-2.gitcoin.co
If you query the kudos contract and ask for the TokenURI you still get ipfs.gitcoin.co.
This could cause external applications to lose functionality for the ERC721 Token!

**To Reproduce**
Query Kudos Contract, for example Token 364, try to open resulting URL

**Expected behavior**
Not broken, at least a redirection

**Screenshots**
user 0x28f4a17f8a99ab90c1a401b85d694b2c0ea40c4b, tokenId 364, URI: https://ipfs.gitcoin.co:443/api/v0/cat/QmZierphNFWnhJATVPvc6kTbgXpiMq7LJNDUTyZsJa2MYN 
( this one fails )

user 0x28f4a17f8a99ab90c1a401b85d694b2c0ea40c4b, tokenId 3288, URI: https://ipfs-2.gitcoin.co:443/api/v0/cat/QmaWrvGGX1oMDQtxG87Sx2yfEihamSnKYWz8WrL1b7SZyQ utilities.ts:87
( this one works )

![grafik](https://user-images.githubusercontent.com/761911/57983830-82b22580-7a56-11e9-954b-705e34d34156.png)

**Comment by PixelantDesign** [comment]
Thanks for the report @kuhnchris!

**Comment by danlipert** [comment]
Should be an easy fix, just need to add an ipfs.gitcoin.co DNS entry and update the nginx config on ipfs-2. Quick question on this though, what is the tokenURI used for, and why does it point to a specific domain rather than just the IPFS CID? @owocki

**Comment by kuhnchris** [comment]
From the EIP:
    /// @notice A distinct Uniform Resource Identifier (URI) for a given asset.
    /// @dev Throws if `_tokenId` is not a valid NFT. URIs are defined in RFC
    ///  3986. The URI may point to a JSON file that conforms to the "ERC721
    ///  Metadata JSON Schema".
    function tokenURI(uint256 _tokenId) external view returns (string);

The RFC in question:
https://tools.ietf.org/html/rfc3986

Well, I assume we could use IPFS addresses. According to the RFC:

![grafik](https://user-images.githubusercontent.com/761911/58026023-ef402980-7b15-11e9-95e8-31f50603382c.png)

   scheme        = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
   absolute-URI  = scheme ":" hier-part [ "?" query ]

Maybe @owocki has some enlightenment?

**Comment by danlipert** [comment]
Fixed! ipfs.gitcoin.co now works 👍
