### ISSUE TITLE
Grants Error When Trying to Edit

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4443]
**Describe the bug**

I have started this grant:  https://gitcoin.co/grants/103/tradescope-investigating-market-manipulation

When I visit the grant page and try to edit, I get this message: "Looks like your grant has been created with 0xFE222247735B3C7Ef099BA761F9477450f5256fE. Switch to take action on your grant."

However, this is the address I'm currently logged in with metamask.

**Desktop (please complete the following information):**
Windows 10 + Chrome 74.0.3729.157 64bit

**Additional context**

For questions please slack Vasilis Mavroudis  on Gitcoin community slack.

https://gitcoin.co/grants/103/tradescope-investigating-market-manipulation

**Comment by kuhnchris** [comment]
I'll try to contact him to get this fixed ASAP

**Comment by kuhnchris** [comment]
FYI I also get the same issue (albeit without the address) on my grant:
![grafik](https://user-images.githubusercontent.com/761911/58026907-d8023b80-7b17-11e9-9fd5-5befdf0553e7.png)
