### ISSUE TITLE
[Kudos, Profile] Broken "Sent Kudos" page (Firefox)

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4444]
**Describe the bug**
Various problems, see attached screenshot

**To Reproduce**
go to my profile (gitcoin.co/profile/kuhnchris)

**Expected behavior**
not broken

**Screenshots**
![grafik](https://user-images.githubusercontent.com/761911/58026574-0e8b8680-7b17-11e9-8613-864ab0f10935.png)

**Desktop (please complete the following information):**
- OS: Win10
- Browser: Firefox
- Browser Version: Latest stable

**Comment by PixelantDesign** [comment]
Thanks @kuhnchris !
