### ISSUE TITLE
as a funder, if a bounty doesn’t work then frame it as ”lessons learned” not “the product doesn’t work” - give lessons learned to funders at this moment so i can learn how to do better bounties

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4468]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder, if a bounty doesn’t work then frame it as”lessons learned” not “the product doesn’t work” - give lessons learned to funders at this moment so i can learn how to do better bounties

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

software development is inherently abstract.  because of this, someone might post something to the platform that is suboptimal, and then it doesnt get done, and they blame the platform.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
none

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
when a bounty is cancelled, or hasn't been picked up for 14 days, send the funder an notification and email with tips on how to 
* [price your bounty](https://medium.com/gitcoin/tutorial-how-to-price-work-on-gitcoin-49bafcdd201e)
* spec your bounty
* [increase action on your bounty](https://medium.com/gitcoin/increasing-action-on-your-gitcoin-bounty-61bb278f6f54)
* [what types of work are good / bad to use for bounties ](https://gitcoin.co/bounty/quickstart)
* find talent on the gitcoin network

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
retention is improved

### Reach
All Funders who fund a bounty

### Confidence

**Comment by Kweiss** [comment]
Cleaning up errant issues that likely will not be immediately prioritized
