### ISSUE TITLE
As a site admin, I want a Gitcoin Drip Marketing Campaign that explains our vision (and how to use Gitcoin) over time, so we can enable our users to be successful.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#448]
# day by day marketing campaign

1. welcome to gitcoin, heres everything you need to know
2. here are some case studies of how gitcoin's been used in the past / here are the open bounties on the platform
3. why open source is important /  here's our vision of the world in 10 years

if people haven't engaged in several weeks
1. send them an email asking them to come back to slack

endgame:
1. help familiarize users with our vision
2. help them learn how to be successful using our tools

# tooling

upload the emails we get back up to mailchimp

**Comment by owocki** [comment]
@PixelantDesign @vs77bb what do we think of the overall idea of having a drip marketing campaign to explain the what/why/how to new users?

**Comment by PixelantDesign** [comment]
@owocki Love it! Here is a great article that lays out sort of a formula on various campaigns types.  https://medium.com/@myxys/how-to-design-lead-nurturing-lead-scoring-and-drip-email-campaigns-9961024f6605.

**Comment by owocki** [comment]
@vs77bb you field a lot of questions from newcomers to the platform.  any topics you feel like should be in the drip marketing campaign?

**Comment by mkosowsk** [comment]
I have a topic that seems to come up when talking with new people about GitCoin!

"Why blockchain for the project?"

My answer is that blockchain removes a lot of intermediaries (per Lubin 😂) and simplifies the process compared to traditional methods. This makes it faster, cheaper, more secure, and easier to resolve conflicts (built into the contract!).

I had a friend counter with, "I can send you $1 right now with Venmo instantly."

My response was 

1. Could you do that to a person not on Venmo/unbanked?
2. Venmo makes money via CC transactions (I think?), so they have a big time back-end built up to make that tx painless but there are a lot of things going on under the hood to make that happen... blockchain simplifies that

I'm still not super satisfied with my response and am definitely open to input 👍

**Comment by owocki** [comment]
here is my answer to the above question : https://github.com/gitcoinco/gitcoinco/issues/13

i think as a community we need to get better at articulating the end-user value to fat protocols and to blockchain.  right now i can articulate from a economic theory perspective why blockchain is better, but the average consumer doesn't give two shits about that

**Comment by mkosowsk** [comment]
I like your answer 👍🏻 

I want to chew on it and see if anything comes out that is a nice one or two sentence answer that the average consumer will give a shit about... a slogan that is snappy but still has truth to it. Nothing comes to mind at the moment 🤔

**Comment by owocki** [comment]
i've got it:

> END THE FED!!!!1!!1!!

ok, i was kidding.  i kid because i <3 to heckle bitcoin maximalists :)

**Comment by mkosowsk** [comment]
😂🤣😂🤣

**Comment by owocki** [comment]
one way to get past the impasse here might be to set up the backend rails for the drip campaign (crontabs, data layer, email templates)... and then i can pick up the content once all that stuff is in place...

**Comment by owocki** [comment]
@PixelantDesign i wonder if we'll want to slot this in with the new onboarding flow that you showed us today on the wireframe review call

**Comment by PixelantDesign** [comment]
@owocki all great ideas!

I love the idea of educating and helping people understand the features available to them within Gitcoin.

As far as the series, a background on eopen source and ethereum is great (we could also recycle content vivek writes and link to medium depending on the topic. 

I could also see... a combo of read x and do y...  sone ideas could be a series of emails around getting started (overview of features, github repositories structure, hot slack channels to be apart of, anything to help people understand how to get started quickly), your first bounty (ettiquette/ best practice), beyond your first bounty, ideas on augmenting workflow, funding a bounty, pro tips, price estimation of tasks, etc. 

If people are getting educational value they’ll likely stick around. 

Daily emails could be overwhelming, we’d need to figure out frequency. The emails/tasks need to be broken up in a way where users feel like they are done/ have learned something after each email so there is a sense of accomplishment.

Yes to above question on coordinating this effort with the Ftux.

**Comment by owocki** [comment]
> Daily emails could be overwhelming, we’d need to figure out frequency. The emails/tasks need to be broken up in a way where users feel like they are done/ have learned something after each email so there is a sense of accomplishment.

strongly agree here.. i think one of the challenges is peoples different learning velocities.  some will want to consume the content all at once.. others will want a day or two breather in between

**Comment by vs77bb** [comment]
@owocki @PixelantDesign I'm going to up the priority on getting a draft GDoc of a plan together...ideally before SXSW, for review. Think it's crucial for us to make sure those who hop on the Slack are giving us feedback in the early days....

**Comment by vs77bb** [comment]
@owocki sorry I missed some of your earlier questions on this flow. My thoughts:

We are 'experts’ in the following key areas: 
- Open Source Software
- Blockchain and web3 

Our audience pain points include: 
- Finding work in Open Source
- Open Source Sustainability
- People looking to get into blockchain 

Our content strategy (and by reference, our drip campaign) should aim to explain how open source software sustainability is being solved through Gitcoin and through blockchain based open source platforms.

**Comment by owocki** [comment]
100% agree

i wish we could get started on this sooner rather than later.. maybe the first starting point should be defining a 7 day, once per day, FTUX email campaign on the above pain points?  maybe we start with copy, and then move into design, and then get them coded? 

does that seem like a fair way to chunk up the work?

**Comment by PixelantDesign** [comment]
@vs77bb could you take a first pass at the copy?

**Comment by owocki** [comment]
from vivek: https://docs.google.com/document/d/1XNrwQE17tRU82vAQcBvNy3ondcgcFDuIP7fbYCfEKA8/edit?ts=5abae9d1

**Comment by owocki** [comment]
@vs77bb i just took a few more passes at the copy doc

**Comment by owocki** [comment]
@PixelantDesign got any comments on the copy?  i move that we take the google doc and make it into a spec for implementation this week

**Comment by owocki** [comment]
as for what tech we use to build it, im not sure mailchimp is the right direction given that they’ve been removing crypto projects
we c ould build it with sendgrid templates maybe if its important that you and vivek can edit it

**Comment by owocki** [comment]
hey @PixelantDesign days 4 5 and 6 just seemed really rough so i went in and took a pass at writing full emails for those.  check them out [here](https://docs.google.com/document/d/1XNrwQE17tRU82vAQcBvNy3ondcgcFDuIP7fbYCfEKA8/edit?ts=5abae9d1)
