### ISSUE TITLE
Funder Form - Display Default settings in collapsed accordian

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4480]
### User Story
As a funder of a Gitcoin bounty, I'd like to know what the defaults are of the collapsed fields - specifically the Project type. Or we should have a link to prompt completing the field if we need this to complete funding an issue.

### Why
Collapsed fields are unclear

### Definition of Done

- Consider how information would display
- Provide mockup with updated text
- Review with core team

**Comment by octavioamu** [comment]
a good solution could be to add near the bottom a summarize data of the bounty. In that way we can keep the sections collapsed but inform the user what is being to be created.

**Comment by willsputra** [comment]
I like @octavioamu 's idea! Will mock this up :)

**Comment by willsputra** [comment]
@octavioamu @PixelantDesign what do you think? if you click 'Change Settings', the page should be scrolled to the expanded 'Project Settings' section
![summary](https://user-images.githubusercontent.com/19514207/58564121-f5917c80-825e-11e9-8549-7f86d0db98c5.jpg)

**Comment by PixelantDesign** [comment]
Looks good, I think this will be helpful. What do you think about also displaying it at the top as a hint under each of those accordion sections. @willsputra 

cc @frankchen07 @thelostone-mc thoughts?

**Comment by frankchen07** [comment]
Maybe the bulletpoints aren't needed? Kind of looks like a Word document - otherwise I think the concept is helpful!

**Comment by willsputra** [comment]
> Looks good, I think this will be helpful. What do you think about also displaying it at the top as a hint under each of those accordion sections.

something like this?
![bounty settings](https://user-images.githubusercontent.com/19514207/59704053-74a61f00-9225-11e9-8c11-93a84df2021d.png)
