### ISSUE TITLE
Grant description formatted while logged in, lacking newlines when logged out.

### ISSUE THREAD

**Issue by Swader** [gitcoinco/web#4482]
**Describe the bug**

When I'm logged in:

![image](https://user-images.githubusercontent.com/1430603/58358145-f781c700-7e7d-11e9-92c1-d0d7ea3b47e9.png)

When I'm logged out:

![image](https://user-images.githubusercontent.com/1430603/58358162-07011000-7e7e-11e9-8393-c522e6a6a922.png)

**To Reproduce**

Visit https://gitcoin.co/grants/102/nimbus when logged in vs logged out

**Expected behavior**

Website should look the same, preferably with newlines.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Opera, Brave, Chrome
- Browser Version: latest

**Comment by kuhnchris** [comment]
Can confirm on firefox aswell.

**Comment by kuhnchris** [comment]
The reason for this is that the description field for admins and people who are owner of the grant is displayed as "textfield", which makes correct use of the "\n" in the text, but for everyone else it's just a <p> container that cannot handle the line breaks, they must be converted to <BR>s, or everyone gets a textbox that is disabled, as you do with the "you are not owner" message.

https://github.com/gitcoinco/web/blob/211979dc56b81d6ec55cf418a61f61f6327369e4/app/grants/templates/grants/detail/tabs.html#L46-L54

**Comment by Anupam-dagar** [comment]
@swader @owocki can I take this issue to work on?
