### ISSUE TITLE
double check the burner grant -- is the amount exactly correct?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4491]
https://twitter.com/odyssyautomaton/status/1132030669465350145?s=12

i think the amounts need to be compared to the amounts onf hte blockchain.

ideally we can compute them deterministically via looking at the blockchain (at any time), instead of having to add / subtract in a non deterministic way (when a new contribution is saved).

**Comment by Anish-Agnihotri** [comment]
It looks like 371 DAI was sent to the recipient funding address in the last month, which is no where near the 4,276 monthly recurring amount that shows in the front-end. I can definitely understand why that looks confusing to a user just looking at the interface at a glance.

We could potentially just add up the internal DAI transactions received to the recipient funding address from the Gitcoin Grants contract dating up to 1 month from the current date and display that out. So on load, the info is pulled?
