### ISSUE TITLE
Consolidate "Basic Payout" and "Advanced Payout"

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4496]
### User Story
As a funder, I would like to pay out bounties using a consolidated form so that "advanced" payouts aren't treated as "tips" and paying a bounty to multiple people is simpler.

### Why Is this Needed
*Summary*: A single form for paying one or more contributors will be more streamlined than two form options. Funders are experiencing bugs with advanced payout due to "tip" limits, when they just want to pay out using the bounty funds they already have in escrow.  

### Description
*Type*: Feature

### Current Behavior
Two forms: Basic Payout and Advanced Payout, as well as a "Tips" function. Advanced payouts are registered as tips, causing errors.

### Expected Behavior
Create a single form called "Pay Out Bounty". Would look like Advanced Payout with just one contributor selected by default (first contributor to submit work, receiving 100% of bounty with star rating option). But, like current Advanced Payout form, allow funder to add additional contributors who worked on the solution and determine what percent of the bounty each contributor gets. 

Add option to send kudos for multiple contributors (not currently the case in advanced payout). Create an "increase bounty" button so funders can add funds via Standard Bounties contract right before paying contributors out, in case they need more funds to pay out all the contributors (rather than "tipping" to cover the difference). "Increase bounty" funds will be added via Metamask tx to the Standard Bounties contract before the total funds (original + added) are finally released to the contributors through a subsequent Metamask tx.

### Definition of Done
Single form that allows payout [+ star rating and kudos] to multiple contributors using the Standard Bounties contract.

### Data Measurements
Increased payout funnel conversion rate
Decreased complaints about payout

### Reach
All funders that payout an issue

### Impact
Medium Impact

### Confidence
80%

**Comment by owocki** [comment]
> when they just want to pay out using the bounty funds they already have in escrow.

If the funders want to just pay with funds in escrow, why not just use Basic Payout?

> Create a single form called "Pay Out Bounty"

I like the elegance of having just one form.. but I worry a bit about all the stuff we'll have to pile into one page to make this work.

1. Bounty Pay out
2. Additional Tips
3. Kudos

The UI might get quite complicated.

**Comment by willsputra** [comment]
first draft
![Artboard](https://user-images.githubusercontent.com/19514207/59201157-fbbf1b80-8bc3-11e9-9d3e-ac3b914e1a08.png)
![Artboard Copy](https://user-images.githubusercontent.com/19514207/59201161-fcf04880-8bc3-11e9-9830-3a46b4eb1bbd.png)

**Comment by willsputra** [comment]
updated with Summary
![Payout](https://user-images.githubusercontent.com/19514207/59434879-9878f780-8e16-11e9-9d66-089f7bf3da06.png)

**Comment by owocki** [comment]
> Single form that allows payout [+ star rating and kudos] to multiple contributors using the Standard Bounties contract.

Heads up - changing the design around on this page isn't going to change the technical architecture of how the payouts work

**Comment by kuhnchris** [comment]
Aye, the standard bounty does not work like the proposed solution. You'd be required to write a cover/proxy contract for that, not sure if that's in the current scope...
Aside from that i'd transpose the Payee Section(s), scrollbar and scrollable left<->right instead of up/down, as it uses up far too much vertical space.

**Comment by alexvotofuture** [comment]
@owocki the motivation for this design was two-fold: 1) Consolidate forms to simplify payout choices for the user in the short term, and 2) Set up a front-end in anticipation of architectural shifts that would allow payout to multiple parties from escrow and eliminate tips as a payout method over the medium/long-term. We understood the architecture would have to shift, but given the legal, auditing, and worker-funder trust limitations (without escrow) of tips as a payout mechanism I'd argue we should push toward this eventually.

**Comment by alexvotofuture** [comment]
@willsputra: Wonder if we could use visual elements to reflect numerical information so that it takes up less space and is easier to understand.

- Gas selection could be a slider (slow<->fast)
- "Remaining funds in escrow" and "total payout" could be consolidated and made into some kind of gradient bar showing proposed payout vs funds remaining
-- Could populate a visual percentage total as you type in the payout to each individual contributor, then go into a red zone if you exceed escrow and would need to "crowdfund" more funds from your wallet or others' to cover the total

ETH/ERC-20 could have an "add more" button similar to adding an additional payee, so that if there's a complex set of tokens associated with a bounty they can continue adding them in a scalable way, but if it's just a single currency it's clean.

There's some dead space next to the contributor's handle - maybe the star rating could go right next to the handle, with payout amount under that to save space?

Maybe we could fold Kudos if it takes too much space to show visually, and just add a small "add kudos" button that reveals the designs if clicked.

**Comment by willsputra** [comment]
@alexvotofuture Thanks for the great feedback! 🙂

> Gas selection could be a slider (slow<->fast)

Agreed.

> "Remaining funds in escrow" and "total payout" could be consolidated and made into some kind of gradient bar showing proposed payout vs funds remaining

Considered this but for bounties with different tokens, it would be hard to show the multiple tokens on a single gradient bar (e.g. what if I want to give 50% of the total ETH and 30% DAI?)

> ETH/ERC-20 could have an "add more" button similar to adding an additional payee, so that if there's a complex set of tokens associated with a bounty they can continue adding them in a scalable way, but if it's just a single currency it's clean.

> There's some dead space next to the contributor's handle - maybe the star rating could go right next to the handle, with payout amount under that to save space?

> Maybe we could fold Kudos if it takes too much space to show visually, and just add a small "add kudos" button that reveals the designs if clicked.

Love these. Will put incorporate them into the design!
