### ISSUE TITLE
Fee Discount Codes

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4497]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin team member I want send a code to funders that will reduce or eliminate their 10% fee when necessary.

### Why Is this Needed
For special events like hackathons where sponsorship is paid upfront in full, we want to waive the cost of posting bounties so funders aren't double-charged. For business development it is often useful to provide discounts to strategic partners trying out the system. If a funder experiences a bug and needs to re-post a bounty we don't want them to have to pay the fee again.

### Description
*Type*: Feature

### Current Behavior
10% fee cannot be waived or reduced. No coupon code field.

### Expected Behavior
Ability for Gitcoin team members to securely generate one-time use codes that can be pasted into the funder form to lower or eliminate the fees taken by Gitcoin. Ability to audit who got discounts and who created the discount.

### Definition of Done
Simple discount code generator, field for typing in a discount code, code to reduce the fee.

### Data Measurements
Increased long term retention of funders
Decreased operational effort on the Gitcoin Core team to manually track exceptions
Increased services revenue
Better UX for services clients

### Reach
All funders that fund an issue

### Impact
High Impact 

### Confidence 
100%

**Comment by PixelantDesign** [comment]
No exposing the field

**Comment by frankchen07** [comment]
Related PR: https://github.com/gitcoinco/web/pull/4074

**Comment by frankchen07** [comment]
Do we also want a time lock on the generated URL, so that the funder link generated expires after the hackathon dates? Otherwise in the future we'll have generated tons of links that could increase holes in our revenue nets.

**Comment by frankchen07** [comment]
> would it make more sense to set the fee to 0 when a bounty is associated with hackathon as opposed to building out the whole invite system?

Alternative solution, perhaps. this would make use of the dynamic fee system in the PR above @PixelantDesign 

> I'm assuming this involves allowing the admin to create a new coupon code and give it a discount value and probably a UI to trigger the email? how would this work?

Commented here: https://github.com/gitcoinco/web/issues/4497#issuecomment-496637817 it makes sense that it would be an admin tool that generates a URL for the funder. I think hooking it up to an email would be alot of additional lift.

> Also I see this task has also been taken up from green squad ?  would we be working together ?https://gitcoincore.slack.com/archives/CF9FSDR8V/p1559104020005200

Hm, let me sync with @PixelantDesign

**Comment by thelostone-mc** [comment]
@octavioamu 

- Creating a model to create code + discount % + invalid
- Admin can view + add + edit  + delete entry
- Navigating to bounty new page with the link should update the fee accordingly 
- On funding we set the invalid field to true

This would be the flow @frankchen07 

- Admin creates a code + entry with discount %
- Admins physically copies codes & sends out mail to the funder
- Funder clicks on link and the gets discount

**Comment by frankchen07** [comment]
@thelostone-mc 

three things to set:

coupon code name
manual % discount
expiry date

**Comment by thelostone-mc** [comment]
@frankchen07 re-estimating this as 3 cause a few things had already been built out from my earlier PR
