### ISSUE TITLE
Gitcoin Funder Loyalty Program

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4499]
### User Story
As an operator of Gitcoin, we'd like to find meaningful ways to engage through a loyalty program to get funders to come back to work with us. 

### Inspiration
https://blog.hubspot.com/service/customer-loyalty-program

### Why
Increase Retention & Activation of Bounty Usage

**Comment by Kweiss** [comment]
Recorded this idea. Cleaning up errant issues that likely will not be immediately prioritized
