### ISSUE TITLE
Admin override for organization's logo and name

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4500]
### User Story

As a Gitcoin team member I want to be able to change a funder's logo and organization name as it appears on their Gitcoin bounty, so that they don't have to change these on their Github repository itself.

### Why Is this Needed

Branding is crucial for sponsors during special events. For legal reasons, enterprises sometimes cannot change their repository org name or logo. We still need a way to change the way the logo and name appears on Gitcoin so that contributors can effectively discover their bounties.

### Description
*Type*: Feature

### Current Behavior
Must hard-code changes to logo/org name

### Expected Behavior
A simple admin tool for Gitcoin team members to override logo and org name for a bounty.

### Definition of Done
Admin tool lets you adjust branding and org name for a bounty without interrupting proper functioning of the bounty. Must not revert back to syncing with Github unless specifically undone by the administrator.

**Comment by owocki** [comment]
‘branding override’ is already in the product i thought. . is the ‘funding organization’ field on the new bounty form

**Comment by PixelantDesign** [comment]
Per Alex - we don't want org or image override to be accessible by everyone. Admin would be best.

**Comment by PixelantDesign** [comment]
Approach 1 in Admin - create new field to override for each bounty.
