### ISSUE TITLE
As a hackathon sponsor, I'd like a helpful error message when doing a payout where I've hit my transaction limit, so that I can better understand what is happening

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4501]
### User Story

As a hackathon sponsor, I'd like a helpful error message when doing a payout where I've hit my transaction limit, so that I can better understand what is happening.

### Why Is this Needed

During the hackathon, some sponsors/hackathon bounty creators had issues paying out their hackathon prizes because the value was so large. We have internal checks that add a limit to each payout, and the hackathon bounties ran into these limits. Unfortunately, there was not any helpful information for the funder.

### Description

Half Feature / Half Bug

### Current Behavior

Currently, a nondescript error is shown. In addition, it was reported that the bounty got set to cancelled.

### Expected Behavior

A helpful message should be shown, with information on who to contact to raise the limit. The status of the bounty should not change.

### Definition of Done
The issue where the bounty is closed is fixed, and the better error message is displaye.

**Comment by PixelantDesign** [comment]
Dup of this https://github.com/gitcoinco/web/issues/4374

**Comment by PixelantDesign** [comment]
We will increase the limit per discussion with legal. Closing for now.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/4551 updates tip limits
