### ISSUE TITLE
staking to increase maintainers for a project

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4505]
staking to increase maintainers for a project
idea from @danlipert 
- if someone reviews a PR, then they have to stake 1 ETH
- if the person running the PR thinks it's good, then they get their stake + some return
- if the person runnings the PR thinkgs its bad, they loose their stake.

**Comment by danlipert** [comment]
Would love to dogfood this for our own project as well :)

**Comment by owocki** [comment]
whats a lightweight way to test this?  maybe just have ppl apply to be PR reviewers via typeform?  then do a manual stake / return / profit process, which we can then automate?

**Comment by danlipert** [comment]
Sounds good to me - we just need to be very explicit on what the process
is, how it works, terms and conditions, etc.

**Comment by PixelantDesign** [comment]
It think staking would help with contributors ghosting on tasks too.
