### ISSUE TITLE
As a Gitcoin operator, we want reusable hackathon services resources, so let's create a hackathon template landing page.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4508]
### User Story

As a Gitcoin operator, we want reusable hackathon services resources, so let's create a hackathon template landing page.

### Why Is this Needed

Repurpose our previous hackathon pages to create a template hackathon landing page.

### Description

Remove Microsoft branding on https://gitcoin.co/hackathon/ethhack2019 and create a generalizable hackathon landing page format.

### Current Behavior

non-reusable landing page

### Expected Behavior

reusable landing page

### Definition of Done
- [ ] hackathon landing page reusable template, debranded

### Data Measurements
Decreased amount of dev time to create new hackathon landing pages
Increased amount of time to promote hackathons

### Reach
All funders and contributors that navigate using the hackathon page

### Impact
High Impact 

### Confidence 
100%

**Comment by frankchen07** [comment]
@thelostone-mc 

> do we have a design we can use or do I just roll with it?

is https://gitcoin.co/hackathon/ethhack2019 as the template enough, or did you need a sketch file?

> I would need the bunch of sponsor logos and stuff

I think we're still sponsor-searching. We can leave space for them, but the purpose of template is so we can easily add sponsor logos in later. I'll leave that up to you on how you think it's best to keep an open space to easily add them in.

**Comment by thelostone-mc** [comment]
I'll update it same design and clean it up a bit ^_^

**Comment by thelostone-mc** [comment]
update: synced up with @willsputra to establish a skeleton.
will use this as base 🙌
