### ISSUE TITLE
As a Gitcoin operator, our FTUX flows are a bit leaky and unclear.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4511]
### User Story

As a Gitcoin operator, our FTUX flows are a bit leaky and unclear.

### Why Is this Needed

Our FTUX funnels are a bit leaky, and we want to shore them up.

### Description

related ticket: https://github.com/gitcoinco/web/issues/4665

1. homepage ("fund an issue")

clicking on "fund an issue" as a new user should lead you to the Github connect gate ->
data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal ->
if funder selected, funder onboarding or fund issue form 

2. bounties homepage with funder carousel ("fund issue" or "get started")

new or existing user clicks login (Github connect) ->
data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal ->
if funder selected, funder onboarding (new) or fund issue form (existing)

3. bounties homepage with contributor carousel ("fund issue" or "get started")
data check to see if designation is set ->

new or existing user clicks login (Github connect) ->
data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal ->
if conributor selected, contributor onboarding (new) or issue explorer (existing)

4. duplicate the carousel on the homepage with the same functionality, keeping in mind good design etiquette (lowest priority)

Questions for engineers:

1. is the data check to see if the designation is set the difficult part / the part that product is misunderstanding?

### Current Behavior

We currently do not segment users / and past users 

### Expected Behavior
Segmented, and designated not-leaky onboarding experience for funder and contributors.

### Definition of Done

- [ ] log funder & contributor designation for all flows
- [ ] the flow should always be github connect -> data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal -> depositing them to the correct place (funder / contributor onboarding if new user, else funder page / explorer if existing user)

### Data Measurements
- [ ] Distribution of users / number of contributors and number of funders on the platform.
- [ ] HotJar complete capture of conversion rates
- [ ] engineering to provide urls to track potential dropoffs with new flows, frank to track

**Reach**
All potential funders
All potential contributors

**Impact**
High Impact

**Confidence**
100%

**Comment by owocki** [comment]
id love to see a 'funder / coder' toggle in the nav bar.  so that way we can (1) know who is who and (2) make the entire UI opinionated about who it is talking to

**Comment by PixelantDesign** [comment]
If you're a hackathon participant , we want everyone to click start work.

**Comment by PixelantDesign** [comment]
Dependent upon #4665
