### ISSUE TITLE
[low prio] Grants - you contribute... 0k?

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4523]
**Describe the bug**
The OSS contribution value is prefilled with 0

**To Reproduce**
Deploy docker

**Expected behavior**
Some... value.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/761911/58698303-532ae380-839b-11e9-9a31-31e151b52dd5.png)

**Comment by owocki** [comment]
looks ok in prod http://bits.owocki.com/d32e52d944fd/Image%202019-05-31%20at%209.53.57%20AM.png
