### ISSUE TITLE
We need a single weekly notification email that lists all of the expired bounties that a funder has.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4525]

**Comment by kuhnchris** [comment]
Preferably one that tell the funder "hey, the following bounties will expire in (expire date - 1 week)" and then "hey, the following bounties have expired, please consider canceling them if nobody is working on them".

**Comment by kuhnchris** [comment]
maybe @willsputra can come up with a quick design for that? should be implementable easily enough.

**Comment by PixelantDesign** [comment]
or something to put on the dashboard @willsputra
