### ISSUE TITLE
Gitcoin bot is not showing that this issue was funded, but it shows funded on our platform

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4527]
https://gitcoin.co/issue/paritytech/polkadot/202/690

**Comment by kuhnchris** [comment]
this issue is 6 month overdue and opened 11 months ago - and by vivek. So I assume this may be one of those 'really old' issues. Also it links to a Pull Request - So I assume that may cause issues for the bot.

@vs77bb any input?
