### ISSUE TITLE
Should we come up with a rule of thumb and explicitly put it into our terms for funding an issue that, if your bounty isn't completed /actively being worked on within 6 months, we reserve the right to close it and put the funds in the purse to donate to grant projects? Can we do this?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4529]

**Comment by kuhnchris** [comment]
check with legal first, sounds fishy. Also put it kind of a "last effort" thing in there, that you first try to contact the holder, and, if by some time limit, nobody reacts, it goes into a kind of "lost & found" state and will be redistributeable, or, at the very least, cancelable. 

Also, check with the standardbounty contract - I doubt we can interact with it as we do not implement the "intermediate" guy in the contract. @owocki or @vs77bb talked about this a while ago on slack community, maybe check with them

**Comment by owocki** [comment]
i don't believe standard bounties works this way, unless we start making the 'arbiter address' our own .  but even then we sort of lose the whole "we will never have custody of your bounty funds" argument.
