### ISSUE TITLE
Is funding on behalf of an org bad? Does it make the org feel like they don't need to be hands on?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4530]
https://gitcoin.co/issue/ConsenSys/Linnia-Smart-Contracts/35/599

**Comment by kuhnchris** [comment]
"Funding on behalf of an org" depends. If you are from condensys and fund an issue in the name of condensys it's fine IMHO, it provides insight in the working of a company if they agree to hire freelancers to work on topics, and seem like integrating into communities.

If "Condensys" funds an issue "for a different company" things could go hairy pretty quickly, check with legal, this sheds a bad light on the company. 
It depends on the usecase tho.
If Microsoft sponsors some funds on an issue that they "need work on, but it's not company critical" it seems fine, but if some small company funds work for a bigger company and provides the solution under the company name then it may cause some issues regarding "buying yourself into the company" and cross-company issues.
