### ISSUE TITLE
Basic Payout Not Working & Should Tell User How Much Is Being Paid

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4535]
### What
Basic Payout Not Paying Out Bounty AND Should Tell User How Much Is Being Paid Out

Paid out a bounty a few days ago and the payment didn't go through but the Kudos was sent.

<img width="955" alt="Screen Shot 2019-06-01 at 6 18 35 AM" src="https://user-images.githubusercontent.com/238235/58747348-0e08bf00-8438-11e9-8cef-25f9651d9437.png">

### To Reproduce
Pay out a Bounty via Basic Payout - the flow looks like this:
![Artboard1](https://user-images.githubusercontent.com/238235/58747320-a18dc000-8437-11e9-8aee-42e5c4d2facf.png)

https://gitcoin.co/issue/gitcoinco/web/4515/3065

### Expected Behavior 

Payout works & Confirmation of what user is paying is displayed

![Artboard2](https://user-images.githubusercontent.com/238235/58747328-b5d1bd00-8437-11e9-89c1-3ab6e681ca2c.png)

### BROWSER

Chrome Version 74.0.3729.169
Mac Mojave

**Comment by kuhnchris** [comment]
Displayed from my side:

![grafik](https://user-images.githubusercontent.com/761911/58748488-d91d5c00-8479-11e9-8e72-27f09224e632.png)

According to etherscan I received the Kudos, but nothing else.

![grafik](https://user-images.githubusercontent.com/761911/58748491-ec302c00-8479-11e9-9adb-60939ce4f24d.png)

https://etherscan.io/address/0x28f4a17f8a99ab90c1a401b85d694b2c0ea40c4b

**Comment by owocki** [comment]
looks like the payment tx is still pending  https://etherscan.io/tx/0x951c0b8b9401d395b416bf2052d6fd6fb976c563ce9a60b12b488a9ed21bbb09

**Comment by kuhnchris** [comment]
OK, your assumtion was correct - it was a pending tx:
![grafik](https://user-images.githubusercontent.com/761911/58754200-a439f500-84cb-11e9-8563-7fd7631cbbaa.png)

Still, it does not show any payment in the activity pane. 
I do show up on "Work paid" tho.
![grafik](https://user-images.githubusercontent.com/761911/58754204-b61b9800-84cb-11e9-83e1-7925e8812280.png)

An indicator that there is a pending payment, or a payment processing would be helpful in a case like this.

**Comment by kuhnchris** [comment]
Also, what does "Accepted: 4 hours ago" mean in that context? 
is this prehaps the date the tx got confirmed? 
Accepted as in "the solution was accepted"?
