### ISSUE TITLE
Duplicate Contributors on Default View of User Directory

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4556]
**Describe the bug**
Duplicate Contributors on Default View of User Directory

**To Reproduce**
Go to user directory, dont put in a search term

**Expected behavior**
Show contributors in leaderboard ranked order

**Screenshots**

<img width="1010" alt="Screen Shot 2019-05-31 at 8 51 09 PM" src="https://user-images.githubusercontent.com/238235/58741391-24862a80-83e6-11e9-9106-320d2831942f.png">

Entering a search term also returns duplicate contributors

<img width="1233" alt="Screen Shot 2019-05-31 at 9 01 28 PM" src="https://user-images.githubusercontent.com/238235/58741492-58ae1b00-83e7-11e9-8853-f94cb9ff2693.png">

**Desktop (please complete the following information):**

- OS: Mac Mojave
- Browser: Chrome
- Browser Version: Version 74.0.3729.169

**Comment by owocki** [comment]
66218a3a0c81347983e05616750b6062f06349d5
