### ISSUE TITLE
As a Contributor I'd like to know how long it'll take for me to get a faucet request fulfilled.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4561]
### User Story
As a Contributor I'd like to know how long it'll take for me to get a faucet request fulfilled.

**To Reproduce**
Currently there isn't a public statistic for the user to know when they'll get it fulfilled

**Expected behavior**
User expects to be notified of how long it'll take to get a faucet

**Additional context**

From product feedback email

 It took a while using a faucet, so it was unclear whether I should try again. No "faucet processing time" statistics is publicly available.

**Comment by owocki** [comment]
24 hours on weekdays, next business day on weekends
