### ISSUE TITLE
as a new funder, have a ultra-fast one click fund (gitcoin quick fund + gitcoin requests) and a followup email stating we'll get you matched in no time

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4563]
### User Story

as a new funder, have a ultra-fast one click fund (gitcoin quick fund + gitcoin requests) and a followup email stating we'll get you matched in no time

### Why Is this Needed

first time funding, gitcoin does it for you - one click link to github, we'll put it up, and find a reliable contributor, and send you an email when work has been started

### Current Behavior
our regular onboarding

### Expected Behavior
seamless no-risk onboarding

**Comment by owocki** [comment]
also; if we DONT match you.. the product should save face and send you tips / lessons learned about how they could approach the product better (better scope, more verifiability, better pricing, better scoping, etc)
