### ISSUE TITLE
as a new funder, if I visit the funder page but don't fund an issue, I'll get a product shill email

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4564]
### User Story

as a new funder, if I visit the funder page but don't fund an issue, I'll get a product shill email

### Why Is this Needed

if we can detect a session visit and identify an email, having a friendly, well worded funder product followup as a gentle reminder on how to extract the most value out of gitcoin would be useful.

### Current Behavior
no product shill email

### Expected Behavior
funder product shill email

### Additional Information

**Comment by kuhnchris** [comment]
wouldn't it be easier if we basically check if he ticked that funder intro... thing (splash page? info page) that we show on the first time he wants to fund a bounty, and the amount of founded bounties <= 0 and we did not already send a mail --> send mail / incensitise to post a bounty

**Comment by frankchen07** [comment]
hey kuhnchris, thanks for the comment, these tickets were opened as a trail of ideas for a funder retention epic. We're investigating and prioritizing which ones would have the highest impact in the EPIC ticket linked above.

**Comment by kuhnchris** [comment]
Hi there @frankchen07 - no problem, @PixelantDesign asked me to take a look around those, so I'm just throwing in random ideas that may give a bit of insight about how easy/hard it would be to implement some of the ideas. ;-)

**Comment by willsputra** [comment]
@kuhnchris thanks for the suggestion! that's the one that shows up when you open the Fund Issue form the first time, right?

@frankchen07 what do you envision the content should be? maybe it could be a combination of important data points from https://gitcoin.co/results (like turnover time, value transfer, how many funders we've helped etc.) + a quickstart guide?

**Comment by frankchen07** [comment]
closing this ticket and combining it with https://github.com/gitcoinco/web/issues/4212 - @willsputra will answer your question there
