### ISSUE TITLE
as a funder, hearing stories of other successful funders in a testimonial email drip campaign will communicate that gitcoin has and will provide value to funders

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4565]
### User Story

as a funder, hearing stories of other successful funders in a testimonial email drip campaign will communicate that gitcoin has successfully provided value to funders

### Why Is this Needed

storytelling for funders to communicate gitcoin value

### Current Behavior
no email drip campaigns with testimonials

### Expected Behavior
email drip campaigns with funder testimonials

**Comment by kuhnchris** [comment]
IF we got more testimonials than the 10 endless ones scrolling during bounty processing, then yes. Else we send them the same testimonials every couple weeks...

**Comment by frankchen07** [comment]
yes this is a consideration to make when we send testimonials - currently slated in the roadmap, but has less impact than some of the other items on our map.

**Comment by frankchen07** [comment]
combining this ticket with https://github.com/gitcoinco/web/issues/4212
