### ISSUE TITLE
as a user, i want to see a funder rank / coder rank everywhere... so i know how to find someone who's active.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4566]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want to see a funder rank / coder rank everywhere... so i know how to find someone who's active.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

its hard to tell at a glance how active someone is on the platform.

and to gauge how active / important i am to the ecosystem

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no funder/coder rank displayed everytwhere.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
funder/coder rank displayed everytwhere.

![Screen Recording 2019-06-02 at 10 12 PM](https://user-images.githubusercontent.com/513929/58775605-8203ae00-8583-11e9-99d8-09b792d18fde.gif)

<img width="1220" alt="Screen Shot 2019-06-02 at 10 10 10 PM" src="https://user-images.githubusercontent.com/513929/58775541-38b35e80-8583-11e9-9fe5-6f17fe8ded4a.png">

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above, funder rank = number of bounties/ads/kudos/grants that have been funded
coder rank = number of bounties/ads/kudos/grants that have been coded

user can switch between funder mode / coder mode, and that info is stored in the DB.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
higher stickiness

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
so basically you want to turn this into an RPG or "steam for bounties" with achivements?
