### ISSUE TITLE
As Gitcoin we'd like to create a series of webinars to help Funders get the most out of the Gitcoin platform so that they can have successful bounty experiences

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4567]
### User Story

As Gitcoin we'd like to create a series of webinars to help Funders get the most out of the Gitcoin platform so that they can have successful bounty experiences.

### Why Is this Needed

*Summary*: To retain funders

### Description

Create a Gitcoin webinar similar to this:

https://pages.consensys.net/block-11-improve-the-ux-of-your-dapp?utm_campaign=BlockTO&utm_medium=email&_hsenc=p2ANqtz-8tIWcW_R9694C5S2KVbmYaKvMFvjbuaC81pQ5GhiGxnVpi0mVoxbnEi9SDAhhJ9dXLWEr3qRhDLt66q6RkYalmz287Sw&_hsmi=72489062&utm_content=72489062&utm_source=hs_email&hsCtaTracking=4a005247-7810-49ce-8064-1f4b9f572997%7C9a453390-4aad-4958-bce8-dde40321e375

### Current Behavior
[comment]: # No webinar

### Expected Behavior
[comment]: # Create webinar to test this idea and reuse for drip campaign

### Definition of Done

- Come up with a webinar topic to test with
- Select a tool to have the webinar
- Plan for how to invite/sign up/marketing
- Hold Webinar
- Create feedback survey
- Review results

### Data Requirements
- Track webinar signups/attendance

### Reach
- All Funders

### Impact
- Medium-High

### Confidence
80%

**Comment by kuhnchris** [comment]
Wouldn't that basically be one of those "gitcoin talks" that are held weekly, just about gitcoin itself?
Or would it rather be something like an actual show and tell with accompanied Q&A session?
