### ISSUE TITLE
Make it clear where contributors can update tags for accuracy

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4568]
### What 
Make it clear where contributors can update tags for accuracy:
- Onboarding - maybe note that we will provide a match if at least 3 tags are matching, and make this changeable?
- Settings
- Note in the match emails
- Allow contributors to notify us that the issue is not accurate (this is in progress)

### Why
- So that contributors don't get randomly matched emails for skills that they don't have.

<img width="1137" alt="Screen Shot 2019-06-03 at 7 39 15 AM" src="https://user-images.githubusercontent.com/238235/58802464-3ed52980-85db-11e9-9618-18c1e0a64c7e.png">

**Comment by kuhnchris** [comment]
an additional possibility would be to extend that mail a bit:
- Add the tags of the bounty
- Mark the tags of the bounty that match your tags
- Display your tags at the top somewhere
- Put a link in there to the preferences where they could change their tags.
