### ISSUE TITLE
Filters failing in user directory

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4569]
**Describe the bug**

Filter by "bounties completed" "stars rating" are giving error 500 

**To Reproduce**

https://gitcoin.co/users

**Expected behavior**

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by kuhnchris** [comment]
Do you have a sentry log for that?

**Comment by kuhnchris** [comment]
FYI: It works on a local test instance:   
   
![image](https://user-images.githubusercontent.com/761911/58825155-14688800-863e-11e9-861f-b2b38c730aee.png)

**Comment by octavioamu** [comment]
@kuhnchris https://sentry.io/share/issue/95f8060799de461dbe540688fbd6ba8d/

**Comment by kuhnchris** [comment]
Page not found. :-(

**Comment by octavioamu** [comment]
@kuhnchris try again, don't know why was unshared

**Comment by kuhnchris** [comment]
@owocki @danlipert did you guys move the rating stuff somewhere? according to sentry and the log it seems like the "average_rating" field disappeared. Any ideas?

**Comment by danlipert** [comment]
@kuhnchris @octavioamu Average rating isn't a model field, its a property - I think this has always been the case. Do you have a average rating field in your database?

**Comment by owocki** [comment]
54b572360522b07d9f1a645a5f639cd09fcb0de1
