### ISSUE TITLE
as a funder,  i want expectations set for bounty funding so i have reasonable expectations for what the bounty product can do

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4570]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder,  i want expectations set for bounty funding so i have reasonable expectations for what the bounty product can do

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

because p[eople dont know what gitcoin is good at and what it isnt, and what is needed from them when they post a bounty.

people also dont read documentation

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no expectaiton setting (or very light expectaion setting on gitcoin.co/new and https://gitcoin.co/bounty/quickstart )

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

```
multi page expectations setting flow before a bounty is posted
- pricing correctly
- focusing on iteration (keep budget in your back pocket)
- what gitcoin can / can't do

start small
- focus on verifiable tasks
- focus on small tasks
- keep a tight iteration loop with a dev.
- use our exemplars

recommended tasks to start with:
- performance bounties
- security bounties
- design ideation bounties
- testing bounties

```

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
higher percentage of started bounties, done bounties

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
So basically what you want is a "slide-show flyer" (slideshare?) that you could send to a potential client/funder, that show-cases what Gitcoin.co can do?

**Comment by PixelantDesign** [comment]
Combine with faux task

**Comment by willsputra** [comment]
maybe we could combine them with this page?
![devguide](https://user-images.githubusercontent.com/19514207/59704424-4aa12c80-9226-11e9-84a9-0e64f884af37.jpg)

**Comment by willsputra** [comment]
@owocki @PixelantDesign something like this?
![Funder Guide](https://user-images.githubusercontent.com/19514207/59852557-3e89ac00-9399-11e9-8461-e79a813d3513.jpg)

**Comment by vs77bb** [comment]
Can we add some language about 'Good First Issues' or 'Help Wanted' issues on Github usually being good bounty candidates?

**Comment by PixelantDesign** [comment]
>I still am bullish on the idea of pulling Github issues from funder repo's to ask if they want to bounty them... but I bet that takes a lot of engineering effort.

This seems like a different ticket. @octavioamu this was similar to your idea.

**Comment by owocki** [comment]
i think its a good start.  i'll probably want to edit some of hte copy once it's coded up. 

one question i have is.. how often do we show this to funders?  many will click past it without reading it.

also.. maybe we should have a spot for a 90 second youtube video here to increase chances of success.  some people will want to watch something instead of read something.  i can record the video.

**Comment by willsputra** [comment]
@PixelantDesign @octavioamu @owocki  shorter version
![Funder Guide](https://user-images.githubusercontent.com/19514207/60608856-9d641200-9dea-11e9-8c62-33ea0bdd7b65.jpg)

**Comment by willsputra** [comment]
Latest funder guide
![funderguide](https://user-images.githubusercontent.com/19514207/61060946-8f834200-a425-11e9-8c63-8a60d5a4f718.jpg)

**Comment by kuhnchris** [comment]
Can we change the first part too? it looks too much like the "regular" one, so I fear people will just scroll past it / click it away

**Comment by willsputra** [comment]
@PixelantDesign sketch file
https://github.com/gitcoinco/creative/blob/ae99c583a32b8b072fe2e6425fab85f8fa504379/Product/Funder%20Guide/Funder%20Guide.sketch

**Comment by willsputra** [comment]
shorter with activity
![funderguide](https://user-images.githubusercontent.com/19514207/61477222-53ba2080-a9c1-11e9-9cfd-1ddbdb9cc3eb.jpg)

**Comment by PixelantDesign** [comment]
[Funder Guide.sketch.zip](https://github.com/gitcoinco/web/files/3419975/Funder.Guide.sketch.zip)

**Comment by Kweiss** [comment]
Closing this as this will not see immediate prioritization.
