### ISSUE TITLE
as a funder who posted a bounty that has no action for 3 days, i want an email telling me what to do so i can salvage the bounty.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4571]
# User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder who posted a bounty that has no action for 3 days, i want an email telling me what to do so i can salvage the bounty.

# Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
to set expectations correctly / salvage a bounty

# Assumptions
Human
Business
Tech

# Current Behavior
[comment]: # (Describe what actually happened.)
no follow ups if bounty isnt getting any action

# Expected Behavior
[comment]: # (Describe what you expected to happen.)
if bounty is created and no action for 2 - 3 days, then an email is sent to funders from the product / BD team... with info about how to salvagae your bounty (info is on https://github.com/gitcoinco/web/issues/4570 and https://gitcoin.co/help ) 

# Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

# Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
more bounties completed 
### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
so basically you want a retail/marketing mail that gets triggered after the following requirement:
- bounty age > 3d
- bounty.activities.filter(created_on=today-3d).count <= 0
and send out an email with a link to gitcoin.co/help, or you want to provide a mail template?
