### ISSUE TITLE
Autocomplete issues in funder form

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4572]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder I want to be able to write the issue name and autocomplete from the repo Im a owner. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

With this Im don't need to keep switching tabs to copy paste issues urls
Also give us the ability to know the owners of each repo. 
The gh api provide us the permissions a user have for diff organizations repos.
Give list of org issues to contributors ask to an issue be funded. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
Excuse me what?
Do you want to auto-sync the github repos of the users and store them in DB? what if the user creates a new repo? 
Also, isn't the main use-case that the funder copies the issue link into the url bar and the rest gets fetched automatically?

**Comment by octavioamu** [comment]
Kind of. Is not only about autocomplete when you start writing, also you will be able to copy paste if you want. but the thing is having a list of open issues from a repo can be nice to contributors request to an issue be bountied. "suggest bounties from an organisation repo"

**Comment by kuhnchris** [comment]
Hmm do we need to watch out for the github api restrictions then? Do you want to have it client-side (e.a. user quota) or server-side? (e.a. gitcoin.co API quota)

**Comment by octavioamu** [comment]
For now is just an idea to brainstorm, but anyway in that point the user api keys can be used instead. But only if is done in backend way to don't expose the user keys.  
Anyway is not a very big request (will depend in the number of repositories)  maybe we need to determine in one way just with repository we want to fetch the issues. 
Really will be nice the funder have the ability to setup this in their settings, the repos they want to use with us and with that we will know also if the users is the owner of that repo.
