### ISSUE TITLE
bounty: re-write update bounty flow

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#4573]
##### Current Flow

Funder funds a bounty -> new entry in the db
Any time the funder interacts with the blockchain with the associated bounty
a duplicate entry is created in the db with the flag set to Latest Bounty and un-setting the flag in the older entry. 
Occasionally the flag setting doesn't work as expected and we end up with duplicates which confuse users 

#### Updated Flow
Funder funds bounty -> new entry in the db
Any time the funder interacts with the blockchain with the associated bounty, the same bounty gets updated

Cleaner Code  + Avoid weird duplicated popping up every now and then

**Comment by owocki** [comment]
note that `cleanup_dupe_bounties` is the duct-tape fix for this

**Comment by kuhnchris** [comment]
How about we generally rewrite this logic to be bounty based?
e.a. we sync standardbounties, if they confirm to our format => entry in DB, the entry keeps getting updated, changes will be recorded, and can be evaluated via, for example, simple-history.
https://django-simple-history.readthedocs.io/en/2.7.2/admin.html
So we only keep 1 entry per standardbounty entry. (which is consistently written into, and syncable from, the blockchain without any intermediate service)

For on-site activity we simply link those to the standardbounty as foreign key.

It may be worth to investigate the data model in general. If you export the model as a graph with django-extensions it starts to look like a terrible mess. 
And especially now with integrating more systems like Grants and User Directory and Kudos we should make sure we separate them properly.


... or short: :+1: this motion to clean up

**Comment by frankchen07** [comment]
so from a data perspective, my concern is that every time a funder updates the bounty, we lose out on information on what happened before, since the model "updates" and overwrites the previous action. 

if a bounty is done, we won't have information on what/when it was submitted/started, etc

**Comment by kuhnchris** [comment]
Hence my example with simple-history, to keep the history of the bounty at least persistent on the system, also for possible intrudor check or manipulation checks, if those are required by legal (since we are handling finance)
