### ISSUE TITLE
Reject contributors in a bounty

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4574]
### User Story
As a funder I want to be able to reject contributors interested in my bounty so non of us got stuck. 
[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed
So the problem is I create a bounty, 3 people start working, but I don't want them. New people don't apply because the bounty has appliers already and then the people also get into the limit to apply to others bounties because the limit.
So both, the bounty and the contributors got stuck.
SOLUTION :  give the funder the ability/obligation to reject/approve applicants

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Have a button to reject applicants and the number of applicants in that bounty decrease
Keep the data in activity and show rejected.
### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
isn't there already a "Reject worker" button? As far as I remember there's an "Approve Worker" and "Reject worker" button. @PixelantDesign could you check to make sure?

**Comment by octavioamu** [comment]
You are right @kuhnchris my mistake, Did you ever used the reject button ? What do you think about it?

**Comment by kuhnchris** [comment]
it's even on the gitcoinbot... ;-)
![image](https://user-images.githubusercontent.com/761911/58828679-441b8e00-8646-11e9-860a-6f644528fa0b.png)

I think I used it before once for testing, not sure if there already is a modal, but maybe ask "hey there, we saw you rejected a worker, would you mind telling us why?"

**Comment by octavioamu** [comment]
yep, I will check the usage data I want to find  a way to avoid issues with a lot of contributors waiting to work forever.

**Comment by frankchen07** [comment]
is this if the bounty is permissionless?

**Comment by PixelantDesign** [comment]
anything that requires approval @frankchen07
