### ISSUE TITLE
DESIGN - As a contributor, I want an easy way to view all info about an organization

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#4576]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a contributor, I want an easy way to view all about an organization

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
There's currently no central place where I can find out everything relating to an organization: important links, new bounties, activities, contributors, etc. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

1. Our current 'org profile' page shows some of these info, but could be improved
https://gitcoin.co/profile/MetaMask
2. There have been attempts to create an org page, but are currently being somewhat deprioritised
https://github.com/gitcoinco/web/issues/1798
https://github.com/gitcoinco/web/issues/1799
This ticket is a continuation of these two above.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Proposed design draft (still a very rough draft, can be improved!)
![org view - inside copy](https://user-images.githubusercontent.com/19514207/58880537-b5247980-870a-11e9-887e-b8659edd7a6c.jpg)

Some of the features:
1. Different tabs showing different info about the org:
Bounties: the org's current bounties sorted by Status (Open Bounties should be on top)
Activity: we could use the same Activity component of the current profile
Core Team: who are the core team members of that org?
Contributors: who have contributed (completed bounties) to this org?
Jobs: job openings of that org, if hiring
Stats: some stats that might be important for funders or contributors (e.g. monthly funds paid out, how active the repo is, etc.)

2. Follow
Allow contributors to Follow an org, after which they'll be informed via email or notifications whenever the org posts new bounties.

3. Top Contributors For This Org
A mini-leaderboard that rank contributors based on the number/value of that org's bounties completed. May be useful for contributors because:
• Encourages contributors to participate in more bounties by gamification
• Top contributors will be able to signal to the org that they're worthy candidates for hiring
• Top contributors will be able to be discovered by other orgs with similar codebase/language

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Explore design and features of org page that will be useful for both funders and contributors

### Data Requirements
• How many Follows, see if Follows = Retention
• See if having a leaderboard affects how active contributors are

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by willsputra** [comment]
@octavioamu we can brainstorm org page here! :)

**Comment by owocki** [comment]
@willsputra is the plan for this design to subsume the existing user profile ( https://gitcoin.co/profile/owocki https://gitcoin.co/profile/metamask etc) or just orgs?

im thinking that profiles are newly important for us, as it helps people build their professional reputation.. allowing gitcoin profile customizations == people building their identity on top of gitcoin ==  staked identity =  moat for us

**Comment by willsputra** [comment]
@owocki originally thought of this only for orgs. hopefully makes it easier to differentiate between user profiles and orgs at a glance too. still early WIP tho so will probably iterate this further with @PixelantDesign

**Comment by owocki** [comment]
thanks.  ill CC you on my profile work go forward

**Comment by owocki** [comment]
there are some ideas posted on https://github.com/gitcoinco/web/issues/4832 that may be worth folding in ...

@willsputra are we going to create a completely new design for this, or re-use the profile design?  id strongly strongly prefer that the individual profile and org profile use the same general design / architecture (although i think we can explore what to put in the tabs and top hero)

there is some priori art for individual profiles that could be useful to re-use for orgs.

**Comment by thelostone-mc** [comment]
@willsputra would it make sense to combine a few of those tabs ? Core team + job stats etc don't take much space and the same probably for contributors. Would be want waste that much space ? 

+1 of unifying the design for new profile + org page 

I know we have activity data but is this something we would want to show? If so, why ? Me curious

**Comment by danlipert** [comment]
Are there any crossovers into the other products we offer that would be worth adding here? This seems very bounty focused, but I think it would definitely be worth adding Hackathons and kudos as well. Also, how will this change with the GC concept?

**Comment by willsputra** [comment]
@owocki @thelostone-mc @danlipert thanks for the feedback! will give this a first pass today :)

**Comment by owocki** [comment]
hey @willsputra heads up that i did an interview with a funder/org owner that said he'd be willing to pay us to shill his OSS rep ... notes here; there might be some ideas for the profile https://github.com/gitcoinco/web/issues/4832

**Comment by frankchen07** [comment]
@willsputra - don't forget to check slack for additional comments and make sure the fonts are the right weights, and the spacing is top notch!

@frankchen07 and @PixelantDesign to lock down what's exactly in the first version of the organizations page

**Comment by willsputra** [comment]
another pass based on feedback

@owocki @PixelantDesign 
> how will people edit their organizations profile? just on-hover right inline when its your profile?

which parts of the profile can be edited on gitcoin, and which parts are synced with github? not too sure.

> what will go on the jobs page? or shoud that be a v2 thing?
> maybe job's tab could say coming soon or make it v2

definitely could be in v2.

![orgs](https://user-images.githubusercontent.com/19514207/64976141-303d2480-d8e3-11e9-9775-c172c659005a.jpg)

**Comment by owocki** [comment]
lets maybe kick editing to a v2

**Comment by frankchen07** [comment]
@willsputra 

> editing to a v2

means the "action" of editing an organizations profile

with our current priorities I see this being built out in sprint 20

**Comment by owocki** [comment]
coded up
![screencapture-localhost-8000-profile-consensys-people-2019-09-18-15_49_01](https://user-images.githubusercontent.com/513929/65188536-e3189a00-da2b-11e9-8d4e-4f1ed2d33a10.png)
