### ISSUE TITLE
Gitcoin Grants not summing individual contributions

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4577]
### User Story

As a contributor I want to see my individual contribution listed in the Total Funded section of the Gitcoin Grant I funded.

### Current Behavior

Individual contributions are not counted.

### Expected Behavior

They are counted.

### Definition of Done

- [ ] Method to check whether individual contributions went through
- [ ] Interface change to display this count

**Comment by kuhnchris** [comment]
You mean one-time contributions (e.a. without subscription)?

**Comment by owocki** [comment]
i dont seem to be able to reproduce this.  are you saying it's not counted IMMEDIATELY after you sign the signature?  there is an info message that pops up and says "itll take 5 minutes"

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/4580 may help also
