### ISSUE TITLE
As a person having their own programming/hacking company, I would like to be able to have my own organization for contribution

### ISSUE THREAD

**Issue by ririen** [gitcoinco/web#4589]
### User Story
As a person having their own programming / hacking company, I would like to be able to have my own organization on the gitcoin website that would have its own payment addresses. Also the ability to choose by the user whether he works on his own behalf or on behalf of the organization to which he belongs.  The organization would include employees of my company and if any of them would have completed the issue (on behalf of the company) and received the payment, the amount would have been transferred to the company's address. The organization's website would also group the issue that we have performed and have employee statistics.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Without such a division, a bit of a mess is created in the company's documentation and the activities of the employees because it is not known what to consider as what.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently, when dealing with the issue I am treated as an individual, this is how my documentation is also created. As an employee of a given organization, it is not known whether the given issue was done individually (for yourself and your own income) or for the company I work with (for example, to make a profit for the company). If there are organizations for contributors when reporting to the issue, it will be possible to choose whether I work on my behalf (individually) or on behalf of my organization (for its reputation / profits and other benefits).

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
The ability to create an organization for contributors and when submitting to the issue of the choice whether you work on your behalf or on behalf of the organization.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Organizations for contributors
- [ ] Opportunity to choose a job for yourself or on behalf of the organization

**Comment by thelostone-mc** [comment]
We do support this and this is called tribes. If you have a github org -> you can ping support@gitcoin.co and we can get it setup
