### ISSUE TITLE
As a funder I'd like to provide a reason to the contributor who applies for my tasks on why they were rejected for my project.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4593]
### User Story
As a funder I'd like to provide a reason to the contributor who applies for my tasks on why they were rejected for my project.

As a contributor, I'd like a definitive answer on whether or not my application has been accepted to work on a bounty.

### What 
When a funder rejects a worker there should be a dropdown asking for reason. The contributor that applies should also receive an email on why they were rejected.

Rejection Reasons:
- I already have a contributor for this project
- Not the right skill fit
- A PR has already been submitted
- other ideas

This could be a drop down off of the reject button or modal
The email should also have a link to the issue explorer to find new work.

### Why
We want to be clear why a contributor was rejected

<img width="1235" alt="Screen Shot 2019-06-07 at 1 05 52 PM" src="https://user-images.githubusercontent.com/238235/59121278-a7970b80-8925-11e9-9cca-10aca09a6cec.png">

**Comment by kuhnchris** [comment]
Hmm wasn't there already a modal for that? I thought it was since this idea keeps popping up every new moon or so.
Anyways, since last time this idea was revisited we actually got that "rate your bounties" thing in, maybe we can recycle that for this?

**Comment by PixelantDesign** [comment]
No modal. Just rate your bounties.

We were going to send an email why the contributor was rejected but we need a place to capture why the person was rejected.

cc @willsputra

**Comment by willsputra** [comment]
the related ticket: https://github.com/gitcoinco/web/issues/3232

I think there's already a PR on that ticket.
