### ISSUE TITLE
Add Gitcoin Footer to Gitcoin.co/blog

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4595]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: no footer

### Expected Behavior
[comment]: blog has a footer

### Definition of Done

- Add our entire footer to all of the blog pages.
- Post a screenshot or video link
- Review with @PixelantDesign 
- Update to new template

### Data Requirements
Organic traffic grows

### Additional Information
This footer

<img width="1656" alt="Screen Shot 2019-06-08 at 7 49 08 AM" src="https://user-images.githubusercontent.com/238235/59146919-52f59e00-89c2-11e9-8e81-10825ea6c748.png">

**Comment by octavioamu** [comment]
From slack: 
To make the blog changes first I need to proper configure wordpress, right now urls are failing and using the admin you get continuously redirected to gitcoin site
