### ISSUE TITLE
Bounty Detail: Clear text email vulnerable to spammers?

### ISSUE THREAD

**Issue by cheneveld** [gitcoinco/web#46]
FUNDER INFO: contains plain text email.

Is there some magic going on to prevent spammers or no?

**Comment by owocki** [comment]
not presently.

**Comment by tra38** [comment]
[Here's a guide](https://www.projecthoneypot.org/how_to_avoid_spambots.php) to help protect emails from being harvested by spammers. I don't know how old the guide is though, so maybe spammers might be able to defeat most of the techniques listed.

**Comment by owocki** [comment]
1d353ae5df039bd5269f114b2a0632fc0d1143e2 and e968a25fcf85a14d201dcac2ec7a17d15a4ed5b7 should move us in the right direction
