### ISSUE TITLE
Dark patterns

### ISSUE THREAD

**Issue by miguelmota** [gitcoinco/web#4603]
As a user, requiring to enable a checkbox for an action to not occur is misleading and is considered a [dark pattern](https://en.wikipedia.org/wiki/Dark_pattern) (it has confused me a number of times)

<img width="619" alt="Screen Shot 2019-06-09 at 9 48 48 PM" src="https://user-images.githubusercontent.com/168240/59173159-732b7700-8b00-11e9-8195-21cbd8c9c99f.png">

proposing that the checkboxes be inverted so that checking to enable means that you do receive the selected emails.

**Comment by kuhnchris** [comment]
So basically "[ ] Send me Weclome Mails"  ?
Sound easy enough for me, shouldn't be *that* hard to change.
https://github.com/gitcoinco/web/blob/master/app/retail/templates/settings/email.html
Sadly it looks like this was created within the settings table of gitcoin like that, so they'd have to change those in the database and migrate the existing entries.
@danlipert your opinion?

**Comment by miguelmota** [comment]
> So basically
 -[ ] Send me Welcome Mails
?

yea that's perfect, basically how most other sites have it

> Sadly it looks like this was created within the settings table of gitcoin like that

dang thought it would of just been a fix on the frontend but seems like more work

**Comment by danlipert** [comment]
Yeah I agree its confusing @miguelmota - I think this can just be a frontend change, just invert the checkboxes' boolean in the display and change the wording @kuhnchris

**Comment by kuhnchris** [comment]
@danlipert afaik it's in the config table, check _administration please.

**Comment by Kweiss** [comment]
Though we agree with the value, this is likely not going to be worked on.
