### ISSUE TITLE
Sort Hackathon Bounties by Highest Value First

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4615]
### User Story

Sort Hackathon Bounties by Highest Value First

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Doesn't exist

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
- Sort bounties by highest value first.
- Denote the sorting logic

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
Chainlink posted prizes early, some people never saw their bounties at the bottom and got no submissions because bounties sort by date created.

**Comment by octavioamu** [comment]
There is already a select to select the order and that keeps saved in the localstorage to remember the user choice.
