### ISSUE TITLE
Metamask requests fee payment when funds aren't available

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4618]
**Describe the bug**

If a user doesn't have enough funds in their account to pay for the bounty, the user is still prompted to pay the fee associated with posting.

https://gyazo.com/80f9acc058a4348aca9eea296664a597

**Expected behavior**

If a user does not have enough funds in their account Metamask should not prompt the user and they should instead be asked only to refill their account, to avoid users paying fees for failed bounties.

**Comment by kuhnchris** [comment]
again, the only "real way" to get around this and all the other issues is to have a proxy contract...
