### ISSUE TITLE
Gitcoin Applicant Auto-Filtering System

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#4619]
### Why Is this Needed

As a funder I'd like to have the option to auto-decline applicants if they don't meet certain criteria.

### Description

We should consider tiers of approval that funders can define in their profile settings. For example, I may not want to accept anyone whose proposal is less than 10 characters, who has never completed a bounty on the platform, or whose stated skills don't match the skills required for the task.

### Current Behavior

There is no auto-rejection feature.

### Expected Behavior

- There is an auto-rejection feature as defined in `Description`.
- The contributor should be notified via email on why they were rejected (based on what criteria). Add to current rejection email.
- Determine how/what messaging is displayed in the activity details and GitHub thread.

**Comment by kuhnchris** [comment]
2 approaches to that:
- during bounty creation create the possibility to restrict to qualifications --> creates a amazon MTurk Esque issue where you need to do 200 tasks before you can apply for something
- auto-reject may do the same, just time delayed.
- have a button "Reject applicants based on..." and then select certain criteria (time applied, length of description, avg. rating, ...) --> more humane solution to me

it's a balance between people with the neccessary skills apply and you can cherrypick v.s. people with "nearly" the matching skill-set applying and noone fitting, but you can try them.

**Comment by thelostone-mc** [comment]
Closing this out ! Will reopen if we decide to pursue this
