### ISSUE TITLE
ability to update github username

### ISSUE THREAD

**Issue by renaynay** [gitcoinco/web#4621]
I updated my github username and i'd like for the option to update my github username in the app as well -- otherwise, gitcoin is linked to my old username which results in a 404

**Comment by PixelantDesign** [comment]
Thanks for the report @renaynay!

**Comment by owocki** [comment]
thanks.  whats your old github username?  we can merge it on the backend

**Comment by renaynay** [comment]
I already deleted my old account and recreated it, but it should definitely be a feature that lets you sync usernames
