### ISSUE TITLE
As a Gitcoin administrator, I want to move our infrastructure to modern instances, so we can save money and have increased performance.

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4622]
### User Story

As a Gitcoin administrator, I want to move our infrastructure to modern instances, so we can save money and have increased performance.

As a ConsenSys infrastructure admin, I want our spokes to use modern instances, so we can save money and have increased performance.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The ConsenSys AWS admin has requested that all spokes use the modern versions of instances instead of past versions since they give better performance as well as cost less. In addition, ConsenSys has purchased T3/M5 reserved instances, so utilizing these instance types is even cheaper.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: The site works

### Expected Behavior
[comment]: The site works faster and costs less to run

### Definition of Done
[comment]: Each instance we use is a T3 class instance or M5 class instance

### Data Requirements
[comment]: # Infrastructure cost goes down, performance goes up

### Additional Information
[comment]: Requested by Ming Fang

**Comment by owocki** [comment]
how much will we save and how much time will this take us?  the numbers matter quite a bit here given that dev time is more constrained than $$$ at this time
 :)

**Comment by danlipert** [comment]
@owocki They are about 10% cheaper baseline, and use more modern CPUs. In addition, ConsenSys is paying for reserved instances here, which I think are 30-40% cheaper. Should take about 8 points, less if there are no issues but I bake in some points to fix anything unexpected.
