### ISSUE TITLE
Cannot submit work 

### ISSUE THREAD

**Issue by pawanjay176** [gitcoinco/web#4626]
**Describe the bug**
Submitting work gives me the following error after a while
```
Action Pending
In order to use features of the Gitcoin network we must confirm transactions on the ethereum blockchain. Please check the pending action on your secure wallet
```

**To Reproduce**
Fill the details in the submit work page and click on Submit work button. For bounty https://gitcoin.co/issue/poanetwork/hbbft/309/2727

**Expected behavior**
Work should get submitted for approval to funder.

**Screenshots**
![image](https://user-images.githubusercontent.com/9890508/59369479-2513af00-8d5e-11e9-9611-67f97a7b8fa2.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser: Brave
- Browser Version: Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)

**Comment by owocki** [comment]
can you please fill out the info in the bug report template? https://github.com/gitcoinco/web/issues/new?template=bug_report.md

**Comment by pawanjay176** [comment]
@owocki updated the info

**Comment by pawanjay176** [comment]
Its similar to the issue in #4558 . I'm using metamask without ledger though.
Tried with Brave and Chrome on Ubuntu and Mac. Still metamask doesn't open.

**Comment by owocki** [comment]
Thanks pawan.  Is there any error info in the chrome console ?

**Comment by pawanjay176** [comment]
It worked now. Was able to submit. Didn't do anything different!
