### ISSUE TITLE
[Grants] Failed Contributions are counted into Total

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4640]
**Describe the bug**
Failed contribution is counted towards Total.

**To Reproduce**
???

**Expected behavior**
1 DAI

**Screenshots**
![grafik](https://user-images.githubusercontent.com/761911/59464308-5d7fbf80-8e28-11e9-99ea-e1b495847755.png)

**Comment by owocki** [comment]
i think if we mark a grant contrb as failed, we just need to call `grant.save()` on the obj in order to update the 'total funded' amount
