### ISSUE TITLE
As a Gitcoin operator, a "squeeze page" may drastically simplify the onboarding experience.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4649]
### User Story

As a Gitcoin operator, a "squeeze page" may drastically simplify the onboarding experience.

### Why Is this Needed

This is an idea for activation strategy.

### Description

Instead of bombarding a new user with the entire Gitcoin product suite, we:

1. do not provide access without signup
2. new signup page has no nav bars, no hyperlinks
3. instead has a clear value proposition with information that is direct and clear
4. has large images
5. embedded sign up forms

### Current Behavior

no squeeze page 

### Expected Behavior

evaluate if this idea is worth pursuing

### Definition of Done

TBD

### Data Requirements

TBD 

### Additional Information

TBD

**Comment by PixelantDesign** [comment]
hmm what is the flow?
