### ISSUE TITLE
As a developer or funder, I would not like to have my emails exposed to the world via Gitcoin

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4661]
**Describe the bug**
After the recent mailblast actually revealed the mail address of at least 500 contributors against each others (by using the To: field)...
![image](https://user-images.githubusercontent.com/761911/59837988-79b2bd80-934e-11e9-8056-778ed9a5623e.png)
... we do not want to do this.
Some people hide their email addresses on purpose, some people do not want to be in a global mail list. There is even a way to hide your mail from github if you want this:
![image](https://user-images.githubusercontent.com/761911/59838157-c5656700-934e-11e9-83ea-0031b4ff6c78.png)
We definitly need to respect people's privacy more.
See also the discussion on github with @Harry.
Same problem with gitcoin API being exposed here.

Also note: There may be legal issues here - please ask internally at Consensys Legal regarding the implication on possibly GDPL / EU Data Protection Law

**Expected behavior**
Not promoting and distributing mails via API or platform or mail blasts

**Screenshots**
see above

**Desktop (please complete the following information):**
any.

**Comment by owocki** [comment]
@vs77bb can you confirm that you guys will use the BCC field from now on?

**Comment by ryan-shea** [comment]
fixes were implemented here, we are now using a new mail platform that obfuscates email addresses.

**Comment by thelostone-mc** [comment]
Closing this out
