### ISSUE TITLE
Burner Wallet Gitcoin Grant progress bar

### ISSUE THREAD

**Issue by austintgriffith** [gitcoinco/web#4663]
The “progress bar” for the Burner Wallet Gitcoin Grant doesn’t make sense to me. 
https://gitcoin.co/grants/20/burner-wallet

![image](https://user-images.githubusercontent.com/2653167/59864508-29366280-9344-11e9-9fab-6a42aac28727.png)

Is it full? Is it empty? Is it broken?

**Comment by kuhnchris** [comment]
I guess it's full due to the total funded... was that already a couple of months ago?

**Comment by kuhnchris** [comment]
Here we got the solution: apparently it's 116.2% fulfilled.
![grafik](https://user-images.githubusercontent.com/761911/59878221-09388a80-93a8-11e9-9f64-790ab989fc5f.png)
it's taking the total funded amount (6974) and divides that by the goal amount (6000).
No CLR or the monthly recurring taking into account.

**Comment by owocki** [comment]
looks like it divides the total funding amount by the monthly goal.  it should probably only use the monthly recurring for the percetnage.  i can update the code now if thats what we think is correct @austintgriffith @pixelantdesign

**Comment by kuhnchris** [comment]
I think we may need 2 bars - a "total bar" which gets updated per month ((monthly recurring * months running)/total) and a monthly bar (monthly curr / monthly goal).

**Comment by owocki** [comment]
im going to remove the bar altogether until someone has the cycles to pick this up. 4eef558431aef2e8b0d1ac7af248f2e441befdb4

i agree that the 2 bar direction could be a fit.

**Comment by kuhnchris** [comment]
Well, a bar isn't that big of a problem, but rather the rules:
Is the CLR already in the total funded? Do we need to add it extra? Do we need to spit it on monthly payments? Or do we simply add 2 bars ála:
Bar 1: After "goal" as previously, calculated as: This Monthly Recurring divided by this month's goal.
Bar 2: After CLR (if avail), Total Funded + CLR devided by Monthly Goal * months(today-grant created on date)
