### ISSUE TITLE
As a Gitcoin User, I'd like Gitcoin to know what my role is (funder/contributor).

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4665]
### User Story

As a Gitcoin User, I'd like Gitcoin to know what my role is (funder/contributor).

### Why Is this Needed

Right now, we are not logging new users as contributors or funders, and we can't tailor the flow based on a user's role.

### Description

We want to build this for the primary use case of funders and contributors.

1. if a new user clicks "log in" in the top right hand corner, before we send them to the onboarding flow, we need a page after the Github connect asking if they're a contributor or funder. This designation should be logged in our database for that user. Depending on what the designation is, the user is sent to the correct onboarding flow.

flow: 
new user clicks login (Github connect) -> 
data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal ->
user clicks one -> 
data about them being a contributor or funder is saved in our model & DB -> 
contributor or funder onboarding flow

2. if an existing user clicks "log in" in the top right hand corner, before we send them to the homepage, we need a page after the Github connect asking if they're a contributor or funder. This designation should be logged in our database for that user. 

flow:
existing user clicks login (Github connect) ->
data check to see if designation is set ->
funder or contributor modal if designation is not set, else no modal ->
user clicks one -> 
data about them being a contributor or funder is saved in our model & DB -> 
homepage

3. we will have to data check whether or not someone has answered the funder or contributor question so we know whether or not to pop the question, hence this step: (data check to see if designation is set)

### Current Behavior

when clicking login to github, we have no idea if its a funder or contributor after they sign in because we don't put them through the onboarding flow

### Expected Behavior

see flows above 

### Definition of Done
- [ ] flow 1 (popup for new users)
- [ ] flow 2 (popup for existing users)
- [ ] add a place in settings to change their designation toggle (funder/contributor) and ensure that it is updated in the data

### Data Requirements
- [ ] any signups or non-designated existing individuals should result in designation

**Reach**
All potential funders
All potential contributors

**Impact**
High Impact

**Confidence**
100%

**Comment by willsputra** [comment]
@PixelantDesign something like this?
![Contributor Funder Prompt](https://user-images.githubusercontent.com/19514207/60107015-59d92a80-9790-11e9-89c9-32ea7821f963.jpg)

**Comment by willsputra** [comment]
@octavioamu @PixelantDesign sketch file
https://github.com/willsputra/creative/blob/97080a24c0cb927c5ee009b3fb33498504582e15/Product/Contributor%20Funder%20Role%20Prompt/Contributor%20Funder%20Role%20Prompt.sketch

**Comment by PixelantDesign** [comment]
@octavioamu what is left to do on this task?

**Comment by octavioamu** [comment]
I think this was deployed time ago
