### ISSUE TITLE
As a Gitcoin Core, I'd like to understand how funders would perceive/ find value in requiring X number of Github contributions in order to apply to work for an issue on Gitcoin.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4670]
### User Story

As a Gitcoin Core, I'd like to understand how funders would perceive/ find value in requiring X number of Github contributions in order to apply for an issue on Gitcoin.

### Why Is this Needed

- Right now, anyone can apply for a task, requiring time for funder to do more homework to understand if a contributor is the right fit.
- Suss out contributors that have not contributed to any open source work (or have less experience). 
- We want to increase the number of quality contributors on the platform.

### Description

Concept test and get user feedback on the idea outlined above.

We would like to learn: 
**Funder**
- What they think about this idea?
- Does it make things simpler when sussing out potential candidates?
- What else would be helpful when evaluating contributors?
- How do they think about vetting in general (we know they normally look on Github, linked In, Bounties completed, and kudos received).
- How do they view # of Github contributions as a baseline? Appropriate number range? Preferred/customnized setting?
- How they might expect to interact with the display.

### Current Behavior
Anyone can click start work to apply for a task. Sometimes there are good applications on how to approach a task, and other times there is spam or not enough information. 

### Expected Behavior
An experience where  funders can easily suss out the quality of a contributor.

### Definition of Done
- Research & understand how Gitcoin funders think about this idea
- Concept test an idea or a few ideas
- Review with core team

### Data Requirements
- [ ] qualitative data on effectiveness of this idea

**Reach**
All potential funders
All potential contributors

**Impact**
High Impact

**Confidence**
80%

**Comment by kuhnchris** [comment]
Mmmh it may be a good idea to check if we could approach some regular funders directly, like Bloom's Derik or other poeple who post bounties on a regular basis. 

Idea for the proceeding:
- get an basic idea (rating based, star based, 'work'-based, ...) to implement
- implement very rough prototype
- ask people to use it (maybe via a mailblast to funders) and give feedback - maybe give some goodie for helping, like a coupon for -50% on a promoted bounty, or some small incencitives like that
- reiterate on prototype

Possibilities for people to select upon (+ pros/cons):
- skills in profile (ex. javascript) -> this leads to people adding any skill to their profile, regardless of knowledge
- amount of work on platform -> does work started count? submit work? finished?
- avg. rating on platform -> this probabbly leads to people creating new accounts to get a clean rating, also: show "joined on" in the card hover.
- no. of contributions on github -> API strain, also misleading if they are working mostly on private repos
-..
