### ISSUE TITLE
As a funder on the Gitcoin platform, I'd like a central place to check-in to see how my bounties are doing, and know the actions I need to take next.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4674]
### User Story

As a funder on the Gitcoin platform, I'd like a central place to check-in to see how my bounties are doing, and know the actions I need to take next.

### Why Is this Needed

No Dashboard APIs in Gitcoin

### Description

_This task is to set up the backend only._

- Set up the dashboard api
- Set up a per-bounty api that gives the applicant details shown In mockup
- Pull in Contributor Icon and github name
- Pull in high level bounty stats up top
- Break up page in 3 sections
- Open Bounties, Submitted Bounties, Expired Bounties (see mockup)

**Bounties Section**
- Provide data end points for elements that are displayed
- _Bounty:_ order by most recent applicants
- _Applicants:_ order by the time each applied
- Pull in data for all open bounties. 
- Allow ability to accept/reject
- Display all bounties
- Allow clicking to user directory in case the right contributors don’t apply.

**Submission Section**
-  _Bounty:_ Order by most recent applicant submission
- _Applicants:_ order by the time each contributor submitted, recent first.
- Provide User name eth address, pr info, commit count
- Allow ability to accept and reject

**Expired bounty**
- Pull in relevant information
- Order based on recently expired bounty
- Clicking extend expiration takes user to issue details with expiration date modal open.

### Current Behavior
No Dashboard APIs

### Expected Behavior
Dashboard APIs outlined above are set up and working

### Definition of Done

- Dashboard APIs outlined above are set up and working

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[See the Latest design ](https://consensys.invisionapp.com/share/NYSOGHX2D8R#/371051245_Dashboard_-1-)

**Comment by owocki** [comment]
latest design => https://consensys.invisionapp.com/share/NYSOGHX2D8R#/screens/370588236_Funder_Dashboard_Spec

**Comment by PixelantDesign** [comment]
[See the Latest design ](https://consensys.invisionapp.com/share/NYSOGHX2D8R#/371051245_Dashboard_-1-)
