### ISSUE TITLE
Beyond Blockchain: Link to prize explorer on landing page

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4675]
### User Story

As a user I want a button on the Beyond Blockchain landing page that links to the prize explorer so I can see the prizes and start getting involved.

### Description
*Type*: Feature

### Current Behavior
No button

### Expected Behavior
Clickable graphic button that leads to the prize explorer, with button text "View Prizes" as before on the Ethereal Hackathon.

### Definition of Done
Clickable link deployed to landing page

**Comment by thelostone-mc** [comment]
Fixed over at https://github.com/gitcoinco/web/pull/4677
