### ISSUE TITLE
Set up Zen Desk Integration on Funder Form

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4676]
### Why
No Zen Desk Integration

**Comment by owocki** [comment]
interesting... we should perhaps deprecate `gitcoin.co/help` and migrate the content over to zendesk at some point, to make it more findable

**Comment by kuhnchris** [comment]
OK, could you (@owocki ) and @PixelantDesign please sit together for an hour and discuss this? We already did exactly that. Please align each other with the current direction regarding this. Thanks.

**Comment by owocki** [comment]
thanks.. great to know it's in flight :)
