### ISSUE TITLE
I see that I have completed the bounty but I can't find anything in my address

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#4687]
**Describe the bug**

I've submitted a work for a bounty( [Arweave](https://gitcoin.co/issue/ArweaveTeam/Bounties/1/3152), I see in my profile that I've completed the bounty but I didn't receive the tip in my Account.
![image](https://user-images.githubusercontent.com/50027175/60125188-92c2d080-978b-11e9-9f74-e2b5005577ab.png)
Another weird thing is that the Gitcoin Bot didn't add my name [here](https://github.com/ArweaveTeam/Bounties/issues/1#issuecomment-505529510).

Another thing, is the fact that I didn't add my ETH address in my bio, so that might be the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
hmmm looks to me that you've submitted work, but haven't been paid yet.  

@danlipert @octavioamu @thelostone-mc looking at the code, i think we need to edit the stats up top to only show `accepted=True` fulfillments

**Comment by Solexplorer** [comment]
Perfect @owocki.

Thanks!
