### ISSUE TITLE
As a funder on the Gitcoin platform, I'd like a no data state to so that I understand the value of the dashboard  even though I haven't funded any bounties.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4703]
### User Story

As a funder on the Gitcoin platform, I'd like a no data state to so that I understand the value of funding an issue/gitcoin even though I haven't funded any bounties.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Introduce funders to what's on the dashboard.

### Description
Create a concept and get feedback on a no data state for the dashboard.

### Current Behavior
no dashboard or data state

### Expected Behavior
No data state for dashboard that prompts fundign/ communicates how we deliver value.

### Definition of Done

- Create a concept prototype
- Test with funders

### Data Requirements
How many funders understand the concept and know what we deliver /what to do next.

### Additional Information

[See the Latest design ](https://consensys.invisionapp.com/share/NYSOGHX2D8R#/371051245_Dashboard_-1-)

**Comment by willsputra** [comment]
Thoughts?
![Dashboard-No Data](https://user-images.githubusercontent.com/19514207/60732503-6457a900-9f74-11e9-9b4a-72359c31fb9a.jpg)

**Comment by willsputra** [comment]
@PixelantDesign Sketch file:
https://github.com/gitcoinco/creative/blob/3eddfc78c2c2c2cae40ae8df01dee42a533c88f3/Product/Dashboard/No%20Data%20State/Dashboard%20-%20No%20Data%20State.sketch

**Comment by willsputra** [comment]
latest:
![Dashboard-No Data](https://user-images.githubusercontent.com/19514207/61391857-38331500-a8f0-11e9-946a-accff9e36d75.jpg)
