### ISSUE TITLE
Old grants migration did not run

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4709]
**Describe the bug**
During the most recent deploy, a migration for PR https://github.com/gitcoinco/web/pull/4317 threw exceptions because the profile model contained fields that were not yet migrated. This is because the migrations access the profile objects directly, and so when the code tries to run, it sees the database schema does not match the expected model and fails.

**To Reproduce**
Run the custom migration `forwards_func` for app/dashboard/migrations/0034_data_for_old_grants.py

**Expected behavior**
Migration runs successfully

**Additional context**
To fix this, the custom forwards function needs to be moved into a custom script that can be run manually on production outside of the migration flow.

**Comment by owocki** [comment]
https://gist.github.com/owocki/4dbc1d2aee2e91c497aca4e398b0bdef

@danlipert hows this look?  i just took the mgmt command and made it into something we can paste into `./manage.py shell`.

**Comment by kuhnchris** [comment]
How about we squash the migrations again, so we would not need to do this? every step additionally to the one-step process would cause issues for devs and testers...

**Comment by danlipert** [comment]
> https://gist.github.com/owocki/4dbc1d2aee2e91c497aca4e398b0bdef
> 
> @danlipert hows this look? i just took the mgmt command and made it into something we can paste into `./manage.py shell`.
Nice! Thanks for this!

**Comment by owocki** [comment]
ok cool so i can run those commands now @danlipert ?

@kuhnchris we could just disable this migration for local environments..

**Comment by danlipert** [comment]
@owocki go for it and let me know how it goes - if you don't have time I can run it, just let me know. @kuhnchris The migration is now disabled in master

**Comment by owocki** [comment]
go for it! i tested on my local and it looked ok. 🤞

**Comment by danlipert** [comment]
Great - will roll it out today!
