### ISSUE TITLE
gitcoin grant contribution fails 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4710]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)
1. go to https://gitcoin.co/grants/121/gas-stations-network
2. fund a grant with a 1 time contribution with NO gitcoin contribution
3. you approve *two* transactions, of which both are not needed.
4. transaction loading page shows an error message
<img width="959" alt="Screen Shot 2019-06-28 at 10 18 13 AM" src="https://user-images.githubusercontent.com/513929/60356564-8d81a380-998e-11e9-80fd-ad44d65e8f65.png">
5
. transaction clears, user is forwarded to the gitcoin grant page, which seems to indicate success.
<img width="962" alt="Screen Shot 2019-06-28 at 10 18 45 AM" src="https://user-images.githubusercontent.com/513929/60356583-983c3880-998e-11e9-83cc-3a5618b1b2d9.png">
6. email is sent noting success [screenshot](http://bits.owocki.com/e6b2dac0830f/Image%202019-06-28%20at%2010.25.34%20AM.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
1. go to https://gitcoin.co/grants/121/gas-stations-network
2. fund a grant with a 1 time contribution with NO gitcoin contribution
3. you approve *one* transaction, since you only need to approve one `transferFrom()`, not two transactions.
4. transaction clears, user is forwarded to the gitcoin grant page.
5. subscription worked, no 'subscription failed' message
6. email is sent noting success [screenshot](http://bits.owocki.com/e6b2dac0830f/Image%202019-06-28%20at%2010.25.34%20AM.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by kuhnchris** [comment]
Uhhh I GUESS this is a side effect occouring in /activities aswell:
![grafik](https://user-images.githubusercontent.com/761911/60362633-bda66200-99e1-11e9-8db6-1665992ae8ed.png)

**Comment by owocki** [comment]
the dash (or negative) on the /activites?

**Comment by kuhnchris** [comment]
yes + broken action item on the right + the weird conversion rate of -1 DAI = 1 USD

**Comment by danlipert** [comment]
@owocki - what address were you using to make the contribution? Also, you say that it asked you to do two `approve` transactions - not one `approve` and then the splitter contract call? Can you paste the txids of the transactions from your metamask?

**Comment by owocki** [comment]
from addr: 0x00De4B13153673BCAE2616b67bf822500d325Fc3 , 

txids: https://etherscan.io/tx/0xc2902e551722c6a3e090d85f5cc14653adf8f1633d2df5ad297f54531db1e697
https://etherscan.io/tx/0x98e2083c991c3d0fe5e2fc3ade5492bbeb4726c4971f0668b705efc38f4328f7 

hmmm.. i can't recall if metamask said both were `approve` or if one said "contract interaction" and i just through it was an approve.d  i guess youre saying the splitter contract requires two tx's?

**Comment by danlipert** [comment]
Yup the splitter an `approve` call first and then the splitter contract is called which uses 2x `transferFrom` calls.
