### ISSUE TITLE
'Currently working' showing wrong data in profiles 

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#4714]
**Describe the bug**

"currently working" is not showing the right data, is showing bounties people applied to work but wasn't approved yet. 
![image](https://user-images.githubusercontent.com/1358093/60368001-1962f200-99c6-11e9-83ab-8226107216f1.png)

**To Reproduce**

Go to https://gitcoin.co/profile/davidkaufman
click "currently working" tab and you will see 2 times "Bounty Request If Nothing Is Found" but this user wasn't approved to work on that bounty, he just asked to start working.

**Expected behavior**

"currently working" should only show the bounties Im already approved to work (if is a "Approval Required" bounty) so need to check for "worker_approved" instead of "worker_applied" 

PLUS:  the query should look for .current() to show the last bounty and avoid repetition and showing duplicates. 
**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by davidkaufman** [comment]
FYI: This bug also affected me today when I tried to apply to work on an issue.  After pressing the "Express Interest" button on a new bounty, it gave me the error "Sorry. You can only WORK ON 3 bounties at a time" but, while I had expressed interest in 3 bounties, i have only been *approved* to work on one.  So I had to go into one of the others I had expressed interest in, and press the "Stop Work" button to get it to allow me to apply to (press "express interest" on) a new one

**Comment by Man-Jain** [comment]
Hey, I am trying to solve this issue so I tried reproducing it in my local gitcoin deployment. But there it is working as intended and I am not able to reproduce it. Is there anything else going on in the backend which is making this error.

**Comment by owocki** [comment]
@davidkaufman i just updated your max number of concurrent issues to 6 instead of 3.

@Man-Jain to reproduce it, try setting an 'approval required' bounty and applying to it.  you need to have a bounty where the pending=1

**Comment by MaxStalker** [comment]
Have exactly the same issue here:
![gitcoin-currently-working](https://user-images.githubusercontent.com/3136647/60600964-e0f25800-9db9-11e9-9dff-7444c325db74.jpg)

To reporduce - go to my profile page: https://gitcoin.co/profile/maxstalker
