### ISSUE TITLE
Add missing tokens in bounty explorer 

### ISSUE THREAD

**Issue by rafalkowalski** [gitcoinco/web#4715]
### User Story
As a hunter I would like to see all missing tokens in bounty explorer.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
To be consistent with current profile behaviour
![image](https://user-images.githubusercontent.com/2479753/60373308-fa815180-99ff-11e9-9c4f-e4904d6c8da7.png)

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently user can see only ETH calculated to dollars. 
![image](https://user-images.githubusercontent.com/2479753/60374359-5e0d7e00-9a04-11e9-85d5-e07014464387.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
I would like to see other tokens.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Missing tokens should be visible in bounty explorer

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
You can use similar implementation which was used in https://gitcoin.co/issue/gitcoinco/web/4590/3093

**Comment by octavioamu** [comment]
There use to be showed in the explorer with a small dropdown 🤔  
cc: @PixelantDesign
