### ISSUE TITLE
As a Gitcoin operator, I'd like to know how the new and legacy grant experiments are going

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4724]
### User Story

As a Gitcoin operator, I'd like to know how the new and legacy grant experiments are going

### Why Is this Needed

Get data to figure out how the grant experiments are doing

### Description

vital information necessary:

```
donation date
from address
to address
from github handle?
to github handle?
token
token amount
token_amount_usdt
```

on legacy and new grant donations

### Current Behavior

no data in our db on how it's performing

### Expected Behavior

run analyses on aggregate grant donation numbers

### Definition of Done
- [ ] data specifications built out in postgres to the above

**Comment by danlipert** [comment]
@frankchen07 When you say "grant donations" - are you talking about the optional donations (5%, 10%, etc.) that are being sent to us? Or is this additional information for the main grant subscriptions?

**Comment by frankchen07** [comment]
@danlipert

> grant donations

thanks for the clarifying question. I'm talking about the optional donations sent to us for both the new grants created (first solution), and the legacy grants (second add on solution)
