### ISSUE TITLE
Wrong COD value displays in bounty explorer

### ISSUE THREAD

**Issue by rafalkowalski** [gitcoinco/web#4730]
**Describe the bug**
The value of COD in bounties explorer is unreadable for user

**To Reproduce**
I've fetched data using below command:
```docker-compose exec web python3 app/manage.py sync_geth rinkeby -20 99999999999 in local environment```

**Expected behavior**
The float value should be visible instead of 1e-14

**Screenshots**
![image](https://user-images.githubusercontent.com/2479753/60531360-1ab05980-9cfb-11e9-9992-9ac5a7996430.png)

**Comment by PixelantDesign** [comment]
@rafalkowalski this is a won't fix according to Dan since COD is a test token. Thanks for the report though!
