### ISSUE TITLE
Ability to subscribe to issues

### ISSUE THREAD

**Issue by SBhojani** [gitcoinco/web#4733]
### User Story

As a bounty hunter, I want to be notified (via email) when an issue's status (like availability) changes so that I can timely respond to such events like apply to an issue that just got abandoned by the last hunter it was assigned to.

### Why Is this Needed

As an example, I am currently interested in working on https://gitcoin.co/issue/gitcoinco/web/4706/3193 but it is currently assigned to someone. If they abandon it, I want to apply to it ASAP. For that, I need to be notified when that happens rather than having to continually monitor that page.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

**Comment by PixelantDesign** [comment]
Hi @SBhojani thanks for the request!
