### ISSUE TITLE
Gitcoin Issue funding timeout

### ISSUE THREAD

**Issue by Benefx** [gitcoinco/web#4746]
Hello, 

I recently began the process of funding an issue on Gitcoin. For whatever reason the initial transaction (10%) did not have any gas so never completed, holding back the transaction of 1.5ETH funding the issue. 

By the time I realised this, the message on the Gitcoin page saying effectively 'Transaction in process - you can close this page' disappeared, however, I had toped up the gas on the fee transaction and it was successful. Due to this, there is no longer enough ETH in the wallet to finish off the second transaction which has now cancelled. 

I am topping it up to complete it but just want to confirm that this will still work? In my account, I can see no record of this issue being funded or funding for it has begun with the fee or any history of it whatsoever. Wondering if I will need to go over the process again from the top or what I need to do from here? 

Thanks

**Comment by owocki** [comment]
got a txid i can checkout?

i wonder if this is related to https://github.com/MetaMask/metamask-extension/issues/6772

**Comment by Benefx** [comment]
I feel like it could be - MM has generally been playing up for me today. 

Here's the transaction for the 10% fee amount: https://etherscan.io/tx/0xbaea31a12eb409c98f98780dacbdc954b829c5c413b91dd31f2cff0d4adc591f 

And here's the failed transaction for the funding amount: https://etherscan.io/tx/0x9590b351ec337f8ef5e3185d86cc94c4ca4dfb3d0e50d4b13c4477053f457732 (I went on to cancel this: https://etherscan.io/tx/0x808065846c527da25dc807ab0d6420f5a91936cd219a9c04a2086472530d14ad) 

Thanks for your help

**Comment by Benefx** [comment]
Hey @owocki - wondering if there was any update on this?

**Comment by Benefx** [comment]
I've created the bounty from the beginning again as we had to get it out but I am wondering if/how I can go about either utilising or getting a refund on the 0.15 ETH I paid? Thanks!

**Comment by owocki** [comment]
@Benefx heres a refudn tx => 0xf54c157cfd41cb4ac15485de4ebfe14a9511de3db06a45a9db88fc001d0dd295

thanks for your patience

**Comment by Benefx** [comment]
Awesome and no problem - thanks a lot for your help
