### ISSUE TITLE
"Send kudos" complains about wrong network when coming from details

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4748]
**Describe the bug**
"Send Kudos" tells me I'm on the wrong net, despite being on the correct net.
Error disappears if you reload page

**To Reproduce**
Go to https://gitcoin.co/kudos/4027/summer_beach_bot
Click Send Kudos
Click on the Kudos
Click on Send Kudos

**Expected behavior**
No error

**Screenshots**
![aaaaaah](https://user-images.githubusercontent.com/761911/60770504-93d4f580-a0db-11e9-970e-6923585b88ad.gif)

**Comment by owocki** [comment]
hmm i dont seem to be able to reproduce.  if i had to hazard a guess, i think its probably
1. metamask is locked
OR
2. theres some sort of race condition in the code.

**Comment by kuhnchris** [comment]
Metamask is and was unlocked.
I thought i may be connected to clicking "Send Kudos" before the price value (0.02 ETH) has loaded, but was proven wrong.
I can keep reproducing it when I come from Send (without an ID), to a kudos, to send kudos, back to the kudos, back to send kudos.
