### ISSUE TITLE
Build Dashboard Front-End 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4754]
### User Story

As a funder on the Gitcoin platform, I'd like a central place to check-in to see how my bounties are doing, and know the actions I need to take next.

### Why Is this Needed

No Dashboard in Gitcoin

### Description

_This task is to set up the front end of backend work created on sprint 13._

- Use information from per-bounty api that to show applicant details shown In mockup
- Display in Contributor Icon and github name
- Display high level bounty stats up top
- Break up page in 3 sections
- Open Bounties, Submitted Bounties, Expired Bounties (see mockup)

**Bounties Section**
- Display data end points for elements that are displayed
- Display _Bounty:_ order by most recent applicants
- Display_Applicants:_ order by the time each applied
- Display pulled in data for all open bounties. 
- Allow ability to accept/reject on the front-end
- Display all bounties
- Allow clicking to user directory in case the right contributors don’t apply.

**Submission Section**
- Display according to design, _Bounty:_ Order by most recent applicant submission
- Display_Applicants:_ order by the time each contributor submitted, recent first.
- Display user name eth address, pr info, commit count
- Allow ability to accept and reject

**Expired bounty**
- Display the relevant information
- Order based on recently expired bounty
- Clicking extend expiration takes user to issue details with expiration date modal open.

### Current Behavior
No Front-End

### Definition of Done
Front-end is built as shown in design

* Depending on how much we get done in sprint 14, product team to decide when to release this feature.
* Also depends on feedback from continued dashboard research that is happening.

### Data Requirements
- Number of click actions taken on the dashboard

### See Design Here
[See the Latest design ](https://consensys.invisionapp.com/share/NYSOGHX2D8R#/371051245_Dashboard_-1-)

**Comment by willsputra** [comment]
![Dashboard-Expanded](https://user-images.githubusercontent.com/19514207/60900893-2d94d200-a297-11e9-9ed3-b889b5a7b919.jpg)

**Comment by willsputra** [comment]
Sketch file:
https://github.com/gitcoinco/creative/blob/c3eef82d6dbfae4acc5372c33daf194d881901d9/Product/Dashboard/Funder%20Dashboard.sketch
