### ISSUE TITLE
Add H1 to Issue Explorer for SEO

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4758]
### User Story
As a Gitcoin operator, I want to add an H1 to Issue Explorer for SEO, so that our site can rank high when users search these terms in order to bring in more traffic (contributors and funders).

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Need an H1 that ranks high on Google searches

### Description

Add an H1 on Issue explorer that says - **Issue Explorer - Freelance Code Bounties**

### Current Behavior
not a high ranking H1

### Expected Behavior
add H1 as defined above

### Definition of Done

- H1 is added
- Review with Marc B

### Data Requirements
Seo will improve

**Comment by kuhnchris** [comment]
Could be added here as an invisible H1:
https://github.com/gitcoinco/web/blob/bc68c7a70c13e62289c845e8bfe6546760c5f7dd/app/dashboard/templates/dashboard/index.html#L31

**Comment by danlipert** [comment]
@kuhnchris it can't be invisible or else google will give us an SEO penalty

**Comment by kuhnchris** [comment]
really? well, the problem is that the H1 doesn't really integrate 'that' well, especially if it should be on top of the page aswell...
