### ISSUE TITLE
Provide "Discuss" to keep Bounty Assignment Discussion out of Issues

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#476]
Issues are sometimes overloaded with gitcoincobot messages and messages of the gitcoin-team.

In order to avoid github users going mad (https://github.com/MetaMask/metamask-extension/issues/3249#issuecomment-367470641), bounty-assignment talk should be relayed to gitcoin.

This could be easily achieved by adding e.g. Discuss (e.g. during extension of this task #469 )

**Comment by owocki** [comment]
this is an interesting idea to put on the roadmap @PixelantDesign

**Comment by lazaridiscom** [comment]
Follow-up #479 (will contain Disquss)
