### ISSUE TITLE
Trying to fund with ERC20 token but failing

### ISSUE THREAD

**Issue by njmurarka** [gitcoinco/web#4765]
I am having trouble funding a new bounty with BLZ token. This token was approved in the last 24 hrs by the administrators as it was not listed as an available ERC20 token before. Now, it does appear as an option.

I also went through the step of "approving" this token on my own account on GitCoin, so that I can use it to fund a bounty. I assume this is necessary. It cost me some gas to do so -- no biggie.

I went ahead and tried to create the bounty and it appears I get two MetaMask transactions that I have to approve. The first seems to be for 10% of the total bounty award, which I believe is the "fee" for using GitCoin. The second one, I do not understand, but I approved both on MetaMask.

As you can see here:

https://etherscan.io/tx/0xa453373016bf87f856aa0e63c885261d85c9f21377516d76ceb5bd06a295bdfc

The second one is repeatedly failing. I have no idea why. What am I doing wrong now? I have tried this 2-3 times. I thought it might be some bug with me re-using the same Github issue link so I went and did it all over with a new link, but no success.

I would like to start placing bounties but I am totally stuck here. Please help.

**Comment by kuhnchris** [comment]
Hi there.

This is weird, the TX that fails is the standard bounty contract - which is weird by itself.
Additionally I tried to check the metadata of your bounty...
![grafik](https://user-images.githubusercontent.com/761911/60923065-684e3880-a29e-11e9-88d4-05e511b1de08.png)
But I cannot access the IPFS link. I'm pinging the higherups, there may be something going on.

I'll try to keep you posted on this - thanks for reporting!

**Comment by njmurarka** [comment]
I was helped quite quickly by Kevin. I had "approved" the token with a different address. I had not realized that token approvals are not on a per-GitCoin account basis but on a per-ETH address basis.

**Comment by kuhnchris** [comment]
Ah, OK. Can I assume this one is fixed then? If yes, please close it, thanks. :-)

**Comment by njmurarka** [comment]
For sure. Done!
