### ISSUE TITLE
As a hackathon sponsor/organizer I want "express interest" work plans to appear on the Issue Detail page.

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#4771]
### User Story
As a hackathon sponsor/organizer I want "express interest" work plans to appear on the Issue Detail page.

### Why Is this Needed
Hackathon sponsors and organizers both want to keep track of people/teams working on a given prize during the hackathon. Having an at-a-glance view of which people are working on a prize is helpful to take action when engagement is low or high.

Currently the best metric for engagement is the number of people who have "expressed interest" or "applied to work" on a prize. However, once they start work, there is no way for the sponsor or organizer to see the work plan and figure out which team they belong to, so that we can check in with that team along the way.

### Description
Displaying the hacker's work plan alongside the "started work" note in the activity feed on the prize page would let us ask the hackers to share their proposed team's Gitcoin handles, proposed project, a link where we can follow up with them, Metamask addresses for team members, Discord usernames, etc. All of this can be done by just making the work plan visible. 

Having a way to update/edit the work plan after the fact would be even more useful (as the team forms and project pivots they can keep us posted).

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Work plan is not shown on issue details

### Expected Behavior
- Allow workplans to be shown as part of applicant request to work...keep ability to accepting/rejecting workers.

### Definition of Done

- [ ] Add an APPLICANTS section on the issue details that display all pending applicants to be approved along with workplan statements under each user.
- [ ] Add the ability to accept/reject the worker.
- [ ] APPROVED section - display approved workers and allow ability to expand/collapse to view the workplan submitted.
- [ ] We will also need a module to appear when work is submitted , displayed in the same format as the above to modules. Display just the name and Reiview/Accept Work Button

Note: Activity stream update is out of scope, unless engineering has extra bandwidth.

**Comment by PixelantDesign** [comment]
![IssueDetails (1)](https://user-images.githubusercontent.com/238235/61057468-63cf7000-a3c3-11e9-8f6a-0be6e0c3c159.jpg)

**Comment by willsputra** [comment]
if no contributor is working on the bounty:
![activitylist](https://user-images.githubusercontent.com/19514207/61477177-400eba00-a9c1-11e9-8619-f4110fe4aacb.jpg)

**Comment by PixelantDesign** [comment]
@willsputra where is the work submitted view?
