### ISSUE TITLE
As a Gitcoin operator we'd like to upgrade our Amazon databases to the new version to prevent  security issues 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4772]
### User Story
As a Gitcoin operator we'd like to upgrade our Amazon databases to the new version to prevent  security issues 

### What 
Upgrade our databases to the new version.

### Definition of Done

- [ ] Upgrade Amazon databases
- [ ] Review with engineers

**Comment by kuhnchris** [comment]
no idea which kind of database you guys use, but are you not using a cluster? If you do, just temporarily boot up another old cluster instance, take one down, upgrade it, bring it up, and repeat that until you upgraded all of them, no?

**Comment by owocki** [comment]
is this done?  i seem to still be able to connect to the old database at the old address ...

**Comment by owocki** [comment]
maybe the address just didnt change?

**Comment by thelostone-mc** [comment]
^ @danlipert

**Comment by danlipert** [comment]
@owocki The new database is up 👍 same info as the previous one

**Comment by owocki** [comment]
oh nice i didnt know you could keep the same RDS instance.  awesome
