### ISSUE TITLE
Profile shows collected bounties amount allthou it wasn't collected

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#4777]
**Describe the bug**
Reported by grimgor on Discord:
He was part of the previous hackathon, didn't win a price, but the profile shows that the amount of price money was collected. (he didn't get it)
This is wrong.

**To Reproduce**
Complete a contest-type bounty and do not get the full payout.

**Expected behavior**
Correct corresponding amount of paid bounty

**Screenshots**
![screenshot](https://cdn.discordapp.com/attachments/598894328500191232/598896017852727356/Screenshot_from_2019-07-11_17-14-03.png)

**Comment by owocki** [comment]
i think that just filtering on accepted=True on line 2607 in dashboard.models.py will do the trick here..
