### ISSUE TITLE
Avatar alternative 

### ISSUE THREAD

**Issue by Orami** [gitcoinco/web#4778]
### I really like the decentraland Avatars i want to like to have a list of providers added so that user get to select their own avatar 

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed
So users can have a sense of ownership and proper representation in their usage of eth account.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
Having at minimum of one avatar provider. that one being decentraland or having a list of providers to chose from in avatar representation

**Comment by owocki** [comment]
thanks for the feedback.. in the meantime, if you update your github picture your gitcoin profile will update too
