### ISSUE TITLE
Duplicate activity data shown in bounty page

### ISSUE THREAD

**Issue by Man-Jain** [gitcoinco/web#4779]
**Describe the bug**
Repeated data is shown in activity section of the bounty page. For eg:- if I have applied to work then it appears twice.

**To Reproduce**
Apply to any bounty.

**Expected behavior**
The activity should appear only once.

**Screenshots**
![Screenshot_2019-07-12 Export Printer to JSON crytic Funded Issue Detail Gitcoin](https://user-images.githubusercontent.com/12700384/61086367-50b6b180-a450-11e9-9158-6736398fac83.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Mozilla Firefox
- Browser Version: 67.0.4

**Comment by PixelantDesign** [comment]
Thanks for the report!

**Comment by danlipert** [comment]
I wasn't able to replicate this, and seems to happen intermittently (doesn't affect all users or happen all the time)

**Comment by Abhimanyu121** [comment]
I think it is issue-specific, like it is there on the issue he applied for but not on other issues.
![image](https://user-images.githubusercontent.com/16034874/61142969-a93c8c00-a4ee-11e9-9668-aa1c925027b9.png)

**Comment by owocki** [comment]
perhaps we could add a post-save trigger on the activity.save() that checks for dupes and destroys itself if a dupe is found...  and be done with it
