### ISSUE TITLE
The route "gitcoin.co/profile/?" embeds another profile page within activities

### ISSUE THREAD

**Issue by edsonayllon** [gitcoinco/web#4782]
**Describe the bug**

Embeds profile page within activities inside profile page, only on route /profile/?. See screenshot below. 

**To Reproduce**

- Login to Gitcoin. 
- Visit gitcoin.co/profile/?

Or. 

- Recieve Kudos, be redirected to gitcoin.co/profile/?.

**Expected behavior**

1. Upon receiving kudos, be redirected to /profile, not /profile/?
2. /profile/? shows the same functionality as /profile I suppose, or do a redirect to /profile

**Screenshots**

<img width="1251" alt="Screen Shot 2019-07-11 at 9 40 37 PM" src="https://user-images.githubusercontent.com/34966228/61096365-4206d500-a425-11e9-9188-b96f596d6c52.png" />

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 
- Browser Version: 75.0.3770.100
 
**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

Bug encountered after receiving first Kudo.

**Comment by owocki** [comment]
hmm for some reason i can't reproduce. 

anyone got a link that reproduces the issue no matter where you're logged in from?

**Comment by edsonayllon** [comment]
I ran into the issue following this link https://gitcoin.co/kudos/redeem/beyondblockchain

**Comment by owocki** [comment]
4b9c79cedb656f20272f0fa684e26fe257b97cf8
