### ISSUE TITLE
'new work' comments appear twice on github issue from gitcoincobot

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#480]
https://gitcoin.co/funding/details?url=https://github.com/Distense/distense-ui/issues/197&slack=1

this bounty was submitted at about the time that `sync_geth` runs.. i think that both the web-centric process and the cronjob (sync_geth), tripped over each other.. 

todo - put a semaphor on insertion of bounties.  each standard bounty id / network combo should have its own semaphor.

**Comment by owocki** [comment]
looks like the tx was submitted twice? 

from https://github.com/Distense/distense-ui/issues/197 that thread:
> I submitted the same tx twice accidentally (not sure what happened). I don't know if this is two separate tasks now or what. I do know the first one will work as normal.

**Comment by owocki** [comment]
https://etherscan.io/tx/0xa6ece7525a155bc1664f90cd36720137f466cf559c6837205c769ea0d06afa33
https://etherscan.io/tx/0xff0643f7a5417bb178f907645f73c8c9341844df86b67d4138efd357a6da7365

speaking with @JohnAllen it looks like there were actually two tx's for the same github url

**Comment by JohnAllen** [comment]
I may have done it twice --  I assumed it was my fault and not a bug, so I'm not 100% sure either way.  Is mine the only one that happened twice?

**Comment by JohnAllen** [comment]
My two task creation txs were submitted/created 3 minutes apart if that helps at all.
