### ISSUE TITLE
As a funder with Dai in my wallet, I should be prompted - in a more prominent way - to turn on DAI or other currency when I select this option in the funder form.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4804]
### User Story

As a funder with Dai in my wallet, I should be prompted - in a more prominent way- to turn on DAI or other currency when I select this option in the funder form.

### Why Is this Needed

Need a prompt that is more visibile/prominent for on turning on DAI/any other currency that isn't activated.
10% fee is processed but bounty does not go through.

### Description

the problem is when people try to fund a bounty with DAI the first time, has happened ~5 times now. how it goes is:

0) person wants to fund a bounty in DAI — doesn’t get prompted with any issues when they choose it in the drop-down
1) the fee transaction goes through without a hitch (they pay the 10%)
2) the std bounties tx doesn’t work bc they don’t have DAI enabled

so they lose their fee. there isn’t a prompt *before* they pay the fee that says you need to have DAI enabled to use it

### Definition of Done

- [ ] Propose a design to solve for the above
- [ ] Review with squad
- [ ] Get user feedback
- [ ] Post final files

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
> No prompt on turning on DAI/any other currency that isn't activated.

this isnt true.  this exists already, just people ignore it.  heres a screencap => http://bits.owocki.com/666340017e8e/Image%202019-07-17%20at%209.18.11%20AM.png

**Comment by PixelantDesign** [comment]
@owocki couldn't see the screenshot. Seems like people are missing it, so we'll take a look how  to prompt in a more visible way.

**Comment by owocki** [comment]
screenshot:
<img width="959" alt="Image 2019-07-17 at 9 18 11 AM" src="https://user-images.githubusercontent.com/513929/61725648-032a2680-ad25-11e9-968a-5987e32ae993.png">

**Comment by owocki** [comment]
i think a blocking modal will do the trick likely

**Comment by octavioamu** [comment]
I think in this tickets are 2 things, one is people trying to use a token not approved and other is people without funds in the wallet just paying out the fees and the getting the message of "out of coins"

So both issues where solved in [Gitcoin v.1.22.0](https://github.com/gitcoinco/web/releases/tag/20190718master-2) we got any error after that?

- token warnings https://github.com/gitcoinco/web/pull/4639
- Check funds before popup metamask https://github.com/gitcoinco/web/pull/4742

**Comment by willsputra** [comment]
How about this for the modal? @PixelantDesign 
![token activate modal](https://user-images.githubusercontent.com/19514207/62471169-acb1f300-b7ce-11e9-8261-d0b0d7170432.jpg)

**Comment by owocki** [comment]
😍

**Comment by willsputra** [comment]
> How about this for the modal? @PixelantDesign
> ![token activate modal](https://user-images.githubusercontent.com/19514207/62471169-acb1f300-b7ce-11e9-8261-d0b0d7170432.jpg)

further outline of the experience:
• the modal should appear when a funder selects a token that has not been enabled yet.
• clicking 'Enable Token' should open the [Token Settings](https://gitcoin.co/settings/tokens) page in a new tab, so the funder doesn't lose all the data you've put on the funder form.
• clicking 'X' should dismiss the modal. however, if the token is still not enabled, the modal should appear again when a funder tries to proceed.

**Comment by PixelantDesign** [comment]
Thanks @willsputra !

**Comment by willsputra** [comment]
sketch file:
https://github.com/gitcoinco/creative/blob/96e0bc62bb22a7415124ca5cd2d234bf15c8c371/Product/Token%20Activate%20Modal/Token%20Activate%20Modal.sketch
