### ISSUE TITLE
Too many alerts show at once

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4814]
**Describe the bug**
When multiple alerts occur, they stack on the screen making it difficult to use

**To Reproduce**
Generate a lot of alerts (like reviewing contributors, etc.)

**Expected behavior**
Only a few alerts should show, or alerts should disappear after some time? Open to suggestions.

**Screenshots**
https://gyazo.com/8ca0ac8c150b9d2b41d5889251740ce5

**Comment by owocki** [comment]
from slack:

```
Owocki  [10 hours ago]
maybe it should close the info dialogue after a new one is surfaced?

Pixelant  [2 hours ago]
yes totally

Owocki  [9 minutes ago]
@Dan Lipert the laziest way to do this would be to make sure `_alert()` closes any other alerts already on the screen… maybe we could add a kwarg flag to the method so that can be toggled but default it to true?

Dan Lipert  [7 minutes ago]
hmm yeah its probably okay to default to true, I'm trying to think if there are cases where we have two boxes commonly
```

**Comment by kuhnchris** [comment]
Mmmh usually you'd simply overlay them and then have the user click them off one after the other, I think. Still a stupid design, but better than having 20 lines on top, or just the latest (or any random) message.

**Comment by danlipert** [comment]
I really like the toasts! And @kuhnchris 's suggestion as well

**Comment by kuhnchris** [comment]
Yeah - toasts seem a good way to go - but wouldn't that also result into a torrent of toasts popping up?

**Comment by octavioamu** [comment]
@thelostone-mc @danlipert @kuhnchris remember we already have toasts we just don't use it https://getbootstrap.com/docs/4.3/components/toasts/
