### ISSUE TITLE
update gitcoin.co/about#team to include connor/joseph/alex

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4821]
update gitcoin.co/about#team to include connor o'day and joseph chen and alex voto

**Comment by owocki** [comment]
@alexvotofuture and connor and alex, can you comment with the following info: whats your 'favorite gitcoin feature' and 'favorite food'?

**Comment by connoroday** [comment]
Feature: Avatars and swag
Food: Filet mignon
