### ISSUE TITLE
As a hackathon organizer, I want to easily see that work has been submitted for me to review.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4822]
# User Story
As a hackathon organizer, I want to easily see that work has been submitted for me to review on the issue details page.

# Why Is this Needed
Hackathon sponsors and organizers both want a quick view of people who are submitting work.

# Assumptions

1. We are assuming that this is a need from many hackathon funders, and that they will use the issue details page to see the overview of work.

2. We are assuming this will positively affect hackathon funder retention

3. _tech assumptions?_

# Description
Display a list of hackers that have submitted work in a module, similar to accept/reject applicants.

# Definition of Done

- [ ] Add an SUBMISSIONS section on the issue details that display all applicants work to be approved 
- [ ] Add the ability to accept/reject the work. 
- [ ] Accept would take the user to the payout flow.
- [ ] Reject could pop a modal and allow funder to input reasons for reject, and post it on github.

# Data

# Additional

![discoverability](https://user-images.githubusercontent.com/238235/63281755-6606d300-c27b-11e9-80ee-dc6e85c03337.jpg)

**Comment by willsputra** [comment]
sketch file:
https://github.com/gitcoinco/creative/blob/f1169a3cae17b23618c20f4b273b39de88f67003/Product/Activity%20List/Activity%20List%20with%20Submissions.sketch

**Comment by octavioamu** [comment]
Submissions area have an accept reject options but that is not how the system works

**Comment by octavioamu** [comment]
I think we need to invest some time thinking and researching on the diff type of bounties, because they have some diff 
permissionless vs approval required
traditional, contest, compet
Another thing is if worst making this changes right now or waiting until teams are ready because I don't see teams contemplated in this new design.

**Comment by octavioamu** [comment]
@willsputra @PixelantDesign ^

**Comment by PixelantDesign** [comment]
@octavioamu please see build ticket in sprint 17 per discussion with @danlipert
