### ISSUE TITLE
Reserved issues included in weekly roundup email

### ISSUE THREAD

**Issue by acolytec3** [gitcoinco/web#4828]
**Describe the bug**
Reserved bounty was included in "top open issues" in Weekly Roundup email sent on 7/19.

**To Reproduce**
Check weekly roundup email sent on 7/19/19.

**Expected behavior**
Only open issues that anyone can work should be included in top open issues section of email.

**Screenshots**
![reserved bounty in roundup](https://user-images.githubusercontent.com/17355484/61531598-49197e80-a9f5-11e9-8c32-44be0ac6c283.png)

**Additional context**
Doesn't look like there is a programmatic fix for this since it's part of the hand-coded section of the ["render_new_bounty_roundup" function](https://github.com/gitcoinco/web/blob/d84717274cc8fda6a00365cc887ee5b072b53b9a/app/retail/emails.py#L1006) in the retail/emails.py (unless I'm reading the codebase wrong)

**Comment by danlipert** [comment]
@ryan-shea @vs77bb something to look out for here - we have to make sure not to have reserved bounties in the weekly roundup.

Thanks @acolytec3 !

**Comment by acolytec3** [comment]
Cool, my work here is done.  Thanks all!
