### ISSUE TITLE
as a company owner who uses gitcoin, i'd like a presence for my usage of gitcoin, so i can (many reasons).  i'm willing to pay!

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4832]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a company owner who uses gitcoin, i'd like a presence for my usage of gitcoin, so i can (many reasons).  i'm willing to pay!

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

as a funder, i want to have a home for my company's OSS sustainability rep because: 
- its my identity in open source sustainability
- its our responsiblity to put that money back into the community.  i can reduce that heat by actively giving back.  its not charity, then we get value out of it.
	 - proves legitimacy to the community.
- its not charity, it helps me scale as a business.  actually help me operationally: get shit done that you dont have the resources to do.
- if you are a for profit company, youre not legit unless youre contributing on gitcoin.

"id pay $10/mo for this", and then we should co-market it + should pilot it with legit companies in the space.  i will say "gitcoin has saved me $$$" in his marketing message

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
organizatoin profile

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
a place where
- it's editable by me.
- i can show off my bounties, past, present, and future.
- color scheme is customizable, so it doesnt feel like a jarring change when users click over from https://whiteblock.io/
- perhaps it should be on a custom subdomain.  gitcoin.whiteblock.io or whiteblock.gitcoin.co
- it's something i'd pay for

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
more users finding gitcoin bounties by funders linking their rep on the site.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@0xzak did i get close to the spec at all? what would u add?

**Comment by owocki** [comment]
assuming we use profiles as the basis for this... i started playing with what org editing would look like here => https://github.com/gitcoinco/web/pull/4833

**Comment by owocki** [comment]
what this could look like, per https://github.com/gitcoinco/web/issues/4576 :

![58880537-b5247980-870a-11e9-887e-b8659edd7a6c](https://user-images.githubusercontent.com/513929/61594636-55dfd300-abab-11e9-980f-a29417a2e77f.jpg)

**Comment by zscole** [comment]
> @0xzak did i get close to the spec at all? what would u add?

hello! (0xzak is my twitter)

yeah, everything you shared is on point. 

just to clarify, what i would find ideal is a dedicated page that i can edit to match the branding and design of my website. i'd like to add a tab to our company website that says BOUNTIES. when a user clicks on it, it leads them to the gitcoin page. this allows us to provide a more unified user experience when directing traffic to gitcoin.

**Comment by owocki** [comment]
thanks @zscole -- does that mean that you'll want something in the nav that points back to whiteblock's website?

did you want this hosted at gitcoin.whiteblock.io or whiteblock.gitcoin.co or http://gitcoin.co/profile/whiteblock ? or either is ok?
