### ISSUE TITLE
As a funder I'd like to be able to co manage bounties and - payment - of a bounty with my team members.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4843]
### User Story

As a funder, I'd like to be able to co manage **payment** of a bounty with my team members.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*: Market validated customer need. Currently there is no ability to co manage the payout of bounties with team members at this time.

### Description

**New Feature: Shared Payment**

This feature addresses only one of two parts to allow funders to share bounty permissions and share bounty payment.

- Mockup  a how to use shared management and shared payment intro screen
- Work with engineering to understand how shared payment and shared management will work together.

### Definition of Done

- [ ] - Mockup  a how to use shared payment intro screen

### Data Requirements
- [ ] data metrics tbd based on the experience created
- [ ] funder retention could increase since this was a highly requested feature.

**Comment by willsputra** [comment]
![shared_management](https://user-images.githubusercontent.com/19514207/63775590-db247900-c909-11e9-9b8e-1667bcac5731.jpg)

**Comment by willsputra** [comment]
added repo view. @danlipert @PixelantDesign let me know if I missed anything or if you all have any feedback!
![shared](https://user-images.githubusercontent.com/19514207/63878618-2a46d880-c9f4-11e9-806b-e3b27af58af8.jpg)

**Comment by PixelantDesign** [comment]
@willsputra could we show updated nav here?

**Comment by willsputra** [comment]
updated nav as discussed. should we surface Organizations here?

![newnav](https://user-images.githubusercontent.com/19514207/64271269-3dfbbd00-cf67-11e9-85f8-59de0abdd86c.jpg)
