### ISSUE TITLE
As a Funder of a Hackathon, I'd like to be able set a specific end date when I fund an issue.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4844]
### User Story

As a Funder of a Hackathon, I'd like to be able set a specific end date when I fund an issue.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Only range of dates by week, month, year are allowed now.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature, Enhancement

### Current Behavior
No ability to set specific end date

### Expected Behavior
Be able to set specific end date

### Definition of Done
- Workshop approach with @alexvotofuture @willsputra and engineer assigned.
- Propose a solution that allows funders to set specific end dates on their bounties.
- Consider how this impacts the rest of the app (other places that the issue details are displayed).
- Consider what happens to the expiration date link that appears on all issue details now that are expired. Do we still honor this?
- Consider how to handle expiration date across all of gitcoin? Or is this specific to hackathon form?
- Share approach with squad
- Document approved solution

### Data Requirements
How many contributors complete the work by the end date

### Additional Information

**Comment by thelostone-mc** [comment]
might need @octavioamu to also weigh in on this
