### ISSUE TITLE
Build - Update Funder Guide - as a funder,  i want expectations set for bounty funding so i have reasonable expectations for what the bounty product can do

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4845]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a funder,  i want expectations set for bounty funding so i have reasonable expectations for what the bounty product can do

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

because p[eople dont know what gitcoin is good at and what it isnt, and what is needed from them when they post a bounty.

people also dont read documentation

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no expectation setting (or very light expectaion setting on gitcoin.co/new and https://gitcoin.co/bounty/quickstart )

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

```
multi page expectations setting flow before a bounty is posted
- pricing correctly
- focusing on iteration (keep budget in your back pocket)
- what gitcoin can / can't do

start small
- focus on verifiable tasks
- focus on small tasks
- keep a tight iteration loop with a dev.
- use our exemplars

recommended tasks to start with:
- performance bounties
- security bounties
- design ideation bounties
- testing bounties

```

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
higher percentage of started bounties, done bounties

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

![funderguide](https://user-images.githubusercontent.com/19514207/61477222-53ba2080-a9c1-11e9-9cfd-1ddbdb9cc3eb.jpg)

**Comment by PixelantDesign** [comment]
@willsputra could you update copy with the following?

start small
- focus on verifiable tasks
- focus on small tasks
- keep a tight iteration loop with a dev.
- use our exemplars

recommended tasks to start with:
- performance bounties
- security bounties
- design ideation bounties
- testing bounties

**Comment by owocki** [comment]
this page is awesome.. i 'd also be happy to record a video or two that walks people through this (on the assumption that video is more engaging than text!)

**Comment by thelostone-mc** [comment]
moving this to blocked until I get the sketch with the latest updates !

**Comment by owocki** [comment]
@willsputra can you attach the sketch pls?

**Comment by willsputra** [comment]
@thelostone-mc sketch file
https://github.com/gitcoinco/creative/blob/6a1ddd0f576f6a17ca505d3f98ca89f36d3d8690/Product/Funder%20Guide/Funder%20Guide.sketch

sorry for the delay!

**Comment by thelostone-mc** [comment]
@willsputra thanks mate ^_^
