### ISSUE TITLE
Team Management - Milestone I - Use Github repo level permissions to determine which other users can take action.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4850]
### User Story

As a funder I'd like to be able to manage permissions with my team members.

### What 

Milestone I

- The Gitcoin platform syncs repo data from Github related to collaborators and team members, mirroring their permissions model. TBD: what level of access will allow users to be added as "Issuers", who have full control, and "Approvers", who can accept submissions and issue payout.

Use Github repo level permissions to determine which other users can take action.
1:1 to github repos

### Why

https://github.com/gitcoinco/web/issues/4756

**Comment by thelostone-mc** [comment]
**Pros** 
- Time to market 

**Cons**
- Adding + removing members would happen via GitHub (pain-point)
- Tight coupling means adding new features like sub-groups hard
 ( if you wanted to have only 2 folks out of the whole team to handle things) 
^ Same for any new feature we might wanna build on top of this
