### ISSUE TITLE
Team Payout - Explore Contract Changes to support team payout

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4852]
### User Story
As a Funder of Gitcoin, I'd like to be able to manage payment of a bounty with my team members.

### What 
 
- [ ] Investigate the contract changes that need to be made.
- [ ]  Spec changes in preparation for implementation the following sprint.

### Why
No ability to do this now.
It is a highly requested feature.

**Comment by owocki** [comment]
you can just use the arbiter address of the existing standardbounties v1 to allow someone else (one person) to manage the payout.

**Comment by owocki** [comment]
unless we want to re-architect the entire system to allow the use a different smart contract (and in that case, we should probably look at standard bounties v2 instead of v1)

**Comment by danlipert** [comment]
Unfortunately we'll want more than one person, but thanks for the tip on the arbiter. Maybe there is a way to to have a separate contract set as the arbiter that multiple addresses can access... 🤔

**Comment by danlipert** [comment]
Posted writeup in slack
