### ISSUE TITLE
Only show open bounties on Explorer as default

### ISSUE THREAD

**Issue by Sm00g15** [gitcoinco/web#4858]
### User Story

[comment]: # As a user I want to only see open Bounties as default.

### Why Is this Needed

[comment]: # 

*Summary*: This is needed b/c the Explorer gets clogged w/ bounties that aren't available to be worked on

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # Bounties explorer gets clogged with Bounties that aren't available to be worked on unless you change the settings.

### Expected Behavior
[comment]: # Bounties explorer to produce a list of only open jobs as default

### Definition of Done
[comment]: # Explorer defaults to only showing open jobs

### Data Requirements
[comment]: # Success is hard to measure in this case, but maybe increased interaction with bounties?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
Thanks for the report!

**Comment by PixelantDesign** [comment]
@Sm00g15 have you tried using the filters on the left? See screenshot below:

<img width="256" alt="Screen Shot 2019-07-24 at 3 28 01 PM" src="https://user-images.githubusercontent.com/238235/61822526-b54a1700-ae27-11e9-9ad5-94e4dc205d0d.png">

**Comment by octavioamu** [comment]
The default is "open" bounties but if you changed the filter it get saved into your local storage and persist on reload. If that the case you can just go down the filter and press reset.

**Comment by thelostone-mc** [comment]
Thanks for reporting the issue @Sm00g15 
Like @octavioamu stated if you haven't selected filters -> it will default to open bounties on the mainnet.

You can either
- Clear the `localStorage` of the browser 
- Add the right filters to update the localStorage + results

Link to show it shows open bounties  : https://embed.vidyard.com/share/xZ9EdgV2qESjbM8dQWT4r7?

**Comment by Sm00g15** [comment]
Awesome that's great thank you @octavioamu and @thelostone-mc
