### ISSUE TITLE
As a Gitcoin operator, there a couple FTUX fixes that need patching up.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#4863]
### User Story

As a Gitcoin operator, there a couple FTUX fixes that need patching up.

### Why Is this Needed

Follow up on FTUX flows

### Description

1. the funder or contributor? image is broken

![Screen Shot 2019-07-24 at 11 57 17](https://user-images.githubusercontent.com/7516920/61828090-c5a7c500-ae1a-11e9-9574-5969f3802caa.png)

2. save button in settings for the funder/contributor designation is not clear that it saves for the address as well as the funder/contributor setting.

![Screen Shot 2019-07-24 at 11 58 38](https://user-images.githubusercontent.com/7516920/61828102-ce000000-ae1a-11e9-96f4-9b1222d13b8d.png)

3. if one doesn't select a designation and instead Xs out, and then attempts to logout, logout doesn't occur - and the modal keeps showing up, it's quite disruptive.

4. can we make all the scenarios like scenario 4B? for certain scenarios (3B, 5B, or 6B) the link sends the first time user to the onboarding page, then they sign in, select contributor or funder, and then it drops them again in the onboarding flow. This will cause double data counts and still isn't accurate enough for metric tracking. This was my bad, for not realizing a similar path through all of them.

scenario 4B
1. login or fund issue homepage or fund issue nav bar or get started funder / contributor ->
2. github sso page -> 
3. back to whichever page they clicked from + funder/contributor modal ->
4. funder or contributor onboarding

this ensures that the onboarding flow is only hit ONCE, after they selected funder or contributor

### Current Behavior
1-4 are broken/less accurate than I initially thought

### Expected Behavior
fix 1-4

### Definition of Done
- [ ] no broken image
- [ ] clearer saving settings
- [ ] funder/contributor modal doesn't interfere with logout
- [ ] correct linking for ftux flows

**Comment by octavioamu** [comment]
1. fixed here #4865 
2. is following the same pattern of the others settings tabs, all looks pretty similar
3. Couldn't reproduce https://embed.vidyard.com/share/CYKJMRFCx64E3caRb2GjJk?
4. Didn't get the idea, can you mock up with prints or something like that Frank?

**Comment by PixelantDesign** [comment]
Frank to set up flows in hot jar!
