### ISSUE TITLE
Job Status tab bugs bugs

### ISSUE THREAD

**Issue by ririen** [gitcoinco/web#4867]
**Describe the bug**

A little honestly saying these bugs made me laugh, act quite specifically. It is about bugs related to the "Job Status" tab and its updating. They have quite an interesting logic of action.

- Bug 1. After exceeding the number 999 in "Compensation expectation (monthly / USD)" the error "undefined" is displayed and the information about the work does not save. It means that entering 1000 there will be a bug in the screenshot.

- Bug 2. You can not save job information without uploading a PDF file. This means that even if you have already added a PDF file and it is saved in the work profile, you still have to choose it from the computer again and add to want to save the profile. Otherwise, the "No file found" error will be displayed. Also another screen in the screenshots section.

- Bug 3. Can't remove resume file and can't save profile without it.

**To Reproduce**

1. Go to "Manage Settings" and "Job Status" tab.

- Bug 1: In the "Compensation expectation (monthly / USD)" field, enter 1000 or more choose pdf file and save.

- Bug 2: In the "Compensation expectation (monthly / USD)" field, enter 999 or less and save without choose pdf file.

- Bug 3: You can't delete resume and can't save profile without it.

**Expected behavior**

- Bug 1: Ability to save amounts greater than 1000.
- Bug 2: Ability to save a profile if you have already added a resume without having to re-select it.
- Bug 3: The ability to remove resume and write without it.

**Screenshots**

![Zrzut ekranu z 2019-07-25 10-16-49](https://user-images.githubusercontent.com/18102267/61858566-9babdc80-aec6-11e9-919d-5eb4b545f176.png)

![Zrzut ekranu z 2019-07-25 10-29-31](https://user-images.githubusercontent.com/18102267/61858748-01986400-aec7-11e9-8c9b-8091af64ca9d.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox Developer Edition
- Browser Version:  69.0b7

**Comment by Adamits** [comment]
Hi @ririen 

I could not reproduce Bug 1. Had you added any other data to fields not displayed in the screenshot, that could be causing the issue? I am looking into bugs 2 and 3.

Adam

**Comment by ririen** [comment]
@adamits I have checked several browsers. It turns out that only in some of them the BUG 1 occurs.

- Firefox Developer Edition – BUG
- Firefox Normal – BUG
- Chromium – BUG
- Brave Dev Channel – Work
- Google Chrome – Work
- Opera Developer – Work

What the problem then? From what I noticed, the mentioned browsers that have a bug change the numbers above one thousand to those with a space or other special character. That is, the field is automatically converted 1000 to 1 000 - which causes a server-side problem and write error. I know that this is a problem with these special characters because by intercepting the request and removing the gap between 1 and zeros, everything has been written correctly.

**Comment by Adamits** [comment]
@ririen Thanks a lot for looking into that. I will look into fixing this one when I have a chance. It looks like in chrome there is some feature that forces the value entered into the field to conform to a specification, so I think the best solution is to look into making it compatible with other browsers.

**Comment by Adamits** [comment]
Could not reproduce yet on my mac (will try linux), but note that in safari I get the following error when I navigate to the job status page immediately when I navigate to it (it should have the Compensation field already populated):

<img width="1413" alt="Screen Shot 2019-07-29 at 10 14 55 PM" src="https://user-images.githubusercontent.com/5308618/62095399-57199b80-b24e-11e9-82dd-e61894d0af1e.png">

**Comment by Adamits** [comment]
Ah - this is not browser specific, but rather because this javascript autoupdated the value to 'NaN', which saved. 

I guess there are two issues here related to BUG 1: 
1. there should be some back-end validation so that a string cannot be saved to `Profile.job_salary`, 2. this front-end feature needs to work cross-browser
