### ISSUE TITLE
Logic bug related to display of job profile

### ISSUE THREAD

**Issue by ririen** [gitcoinco/web#4868]
**Describe the bug**

For a moment I was wondering whether to report this bug privately to the founders or put it here. However, due to the fact that it is not critical, I decided to create this issue.

I based this issue at some point in writing this: https://github.com/gitcoinco/web/issues/38

After unchecking "It's okay to show this information publicly in Gitcoin." in the "Job Status" tab, my data should not be shown anywhere. I believe that the platform and its creator respect the privacy policy and respect that I do not want to make some data was displayed.

HOWEVER, the system has not been thoroughly tested and has gaps that allow the leak of data that the user does not want to show in public.

After unchecking the above checkbox, my job data disappears from the profile, list of users and other places (ui) but only seemingly. Even when I do not agree, they are still displayed in the endpoint of the api.

**Impact**

Severity: Medium

Incompliance with GDPR rules and violating user privacy. Displaying data without its consent. Especially in resume documents in which personal data are most often found.

**To Reproduce**

1. Go to "Manage Settings" and "Job Status" tab.
2. Fill out the fields with your own information and add your own resume as a PDF file.
3. Uncheck "It's okay to show this information publicly in Gitcoin." 
4. Information and resume have stopped displaying at the site's interface, but are still available using the API endpoint.

Example: https://gitcoin.co/api/v0.1/users_fetch/?page=1&search=ririen

**Expected behavior**

Hide information that the user does not want to display from all places where they are available - also in the API.

**Screenshots**

![Zrzut ekranu z 2019-07-25 10-37-50](https://user-images.githubusercontent.com/18102267/61859298-280acf00-aec8-11e9-91e5-b78f5ea5fcf3.png)

**Comment by androolloyd** [comment]
Fixed the test issue
