### ISSUE TITLE
As a Gitcoin Funder I'd like to see increased applications from contributors so that I'll know that my bounty is gaining interest and will have a good outcome.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4882]
# User Story
As a Gitcoin Funder I'd like to see increased applications from contributors so that I'll know that my bounty is gaining interest and will have a good outcome at the end of the hackathon.

# Why
Funder Feedback: I don’t have enough (quality) inbound applications on my issues 

# Assumptions

Human - Based on funder research, seeing increase applications is a step that occurs before the funder actually goes to select contributors, and seeing increased applications signals to the funder that the Gitcoin platform is doing its job of exposing bounties to a wide developer base. We assume that the funder wants the hard work of finding enough and the right contributors to be done for them.

Business - Increased contributors per bounty = "one less thing the funder has to worry about", which makes it easy for the funder to come back and post more bounties, since they don't have to do much work aside from reviewing and paying out.

Tech - tech assumptions?_

# Description / Ideas

1. Do we have sufficient bounty coverage through our Gitcoin bounty emails? ("$X on Gitcoin found for you!") Are we sure that every bounty finds its way into a contributor's inbox? If not, why not?

a. Keywords edition on profiles (currently doesn't update when a user goes to settings - does it affect our matching?)

2. We should have an option to filter for ONLY open bounties, but does it encompass only open bounties _with_ no applicants?

3. How can we measure the accuracy and precision of how we're matching contributors with bounties right now? Where are the gaps?

4. Aside from email, how else can a contributor get notified of new bounties? How about bounties that are still open but have no applicants? 

5. Should we consider a timelock where if the bounty is open for a certain period of time it would accumulate in price to raise the incentive?

5. We've received reports of the funder email going wrong (people receiving them when they shouldn't have. Can we check to make sure we have this buttoned down? What's the logic behind it?

6. Potential contributor research - ask them to open the app and recall an experience when they went looking for work. How exactly do they find their work? Through notifications? Custom filtered searching? Our emails?

# Definition of Done

- [ ] How will we get more contributors to apply?
- [ ] How do we make sure all contributors know about each hackathon issue/bounty?
- [ ] What experience changes do we need to make to the product?

Ideas:
Make sharing within Gitcoin/outside of Gitcoin more prominent on issue details. 
Improve referral program incentive

# Data

**Comment by willsputra** [comment]
from a data perspective, maybe it would help to see at which part of the funnel contributors drop off?

like:
• do contributors not open our emails at all?
• do contributors open our emails, but don't click through?
• do contributors open the issue explorer, but don't click on any issue? 
• do contributors open an issue detail, but don't apply for work?
etc.
