### ISSUE TITLE
As a Funder,  I'd like Gitcoin to tell me who I should choose for my bounties and surface appropriate information so that I can decide for myself

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4888]
# User Story
As a Funder,  I'd like Gitcoin to tell me who I should choose for my bounties or surface appropriate information so that I can decide for myself

# Why
It’s too hard for me to invite quality applicants to my bounties because I don’t know who are good people to work on my bounties 

# Assumptions

1. We are assuming that funders actually want to look for and select their contributors.

2. We are assuming that having the appropriate information to select contributors will keep our funders satisfied and therefore, positively affect retention through an enhanced user experience.

3. _tech assumptions_?

# Definition of Done 
- [ ] UX MVP Discoverability based on what we learned in Sprint 15
        Where should we surface this information?
- [ ] Check against goals/assumptions
- [ ] Outline full ux flow for each
- [ ] Share with squad
- [ ] Provide final design

# Data
* ideally the data tracked should be which contributors were surfaced
* which contributors they selected to invite
* cross comparison methods will tell us a metric that lets us know how trustworthy gitcoin's recommendation is (does the funder actually select the provided contributors?)

# Additional Notes

**- Explore placement on:**

_Dashboard_
See concepts tested and feedback

_Funder Form_
- See concepts tested and feedback

**_Email_** 
Hey we noticed you dont have any contributors on your bounty. Or You have 0 applicants on your bounty.
CTA - Go to user directory (show recommendation for the bounty on dashboard).
Triggers: 0 applicants for 3 days, 7 days

**Need a new task to open user directory with pre filter query.**
- Fix tags on user directory (worked with you)
- Edit keywords in profile

**Comment by PixelantDesign** [comment]
![discoverability_idea1](https://user-images.githubusercontent.com/238235/62953644-e335d200-bdbb-11e9-89e1-0ba1b28255cc.jpg)

**Comment by PixelantDesign** [comment]
Idea 1 - Funder Form
<img width="1347" alt="Screen Shot 2019-08-13 at 11 37 57 AM" src="https://user-images.githubusercontent.com/238235/62955477-2180c080-bdbf-11e9-86cf-241af7af0b74.png">

Idea 2 - Funder Form
<img width="1199" alt="Screen Shot 2019-08-13 at 11 38 11 AM" src="https://user-images.githubusercontent.com/238235/62955505-2d6c8280-bdbf-11e9-8424-06e39dc87830.png">
 
Idea 2 - Hover State
<img width="1232" alt="Screen Shot 2019-08-13 at 11 38 23 AM" src="https://user-images.githubusercontent.com/238235/62955523-35c4bd80-bdbf-11e9-84af-252f844226f7.png">

**Comment by PixelantDesign** [comment]
Details Page
<img width="1643" alt="Screen Shot 2019-08-13 at 12 00 14 PM" src="https://user-images.githubusercontent.com/238235/62957121-26933f00-bdc2-11e9-8d68-4e4947950180.png">

<img width="1638" alt="Screen Shot 2019-08-13 at 12 01 16 PM" src="https://user-images.githubusercontent.com/238235/62957129-285d0280-bdc2-11e9-839d-9e846ab56793.png">

**Comment by PixelantDesign** [comment]
- How do we make sure all bounties get a lot of applicants? Mass apply? what are the rules?
- Move detailed info to vetting stage
- Fix matching

**Comment by willsputra** [comment]
> Move detailed applicant info to vetting stage - issue details page, maybe modular/popover (Will)

this is how it might look like
![discoverability](https://user-images.githubusercontent.com/19514207/62963510-b4f3d900-be33-11e9-87eb-8de57433d470.jpg)

**Comment by willsputra** [comment]
or inline
![discoverability](https://user-images.githubusercontent.com/19514207/62965407-8f68ce80-be37-11e9-87c7-db4703987d5d.jpg)

**Comment by willsputra** [comment]
@PixelantDesign thoughts for the email?
![discoverability email](https://user-images.githubusercontent.com/19514207/63269777-60d07500-c2c9-11e9-87e3-0b23a22eb88b.jpg)
