### ISSUE TITLE
Cannot edit milestone

### ISSUE THREAD

**Issue by vrde** [gitcoinco/web#4895]
**Describe the bug**
I'm the admin of a grant and I cannot edit a milestone.

**To Reproduce**
Go on the _Grant Milestones_ page as the grant admin. No edit button there.

**Expected behavior**
I expect to see an edit button that I can click to edit my milestone.

**Desktop (please complete the following information):**

- OS: GNU/Linux
- Browser: Firefox
- Browser Version: 68

**Additional context**
Some might argue this is a feature request, not a bug report. To me, this is part of the basic features that the service must provide. If it's missing I consider this a bug.

**Comment by danlipert** [comment]
@PixelantDesign @frankchen07 this originated from a message in the community-help slack

**Comment by PixelantDesign** [comment]
Hi @vrde Thanks for reporting/requesting this.

In addition to MIlestones. Are there other things that you expect to be able to edit if we had an edit button?

**Comment by vrde** [comment]
> In addition to MIlestones. Are there other things that you expect to be able to edit if we had an edit button?

I'm quite new to the service, but everything I post should be editable. Since we are talking about grants, updates, and milestones, to maximize transparency there should be an *edit history*, like GitHub (and other services) does, e.g.:

![image](https://user-images.githubusercontent.com/134680/62211578-314fdc00-b39f-11e9-90e1-e71efd0538bf.png)

**Comment by thelostone-mc** [comment]
Steps in locally to reproduce this :

- ensure you have all permission via django admin
- create a grant 
- navigate to created grant and add milestone 
- once added cannot be removed / edited. This is a needed feature
