### ISSUE TITLE
UX & BUILD - As a Gitcoin funder I'd like to be tastefully routed to the dashboard after a login event via a "new dashboard" dynamic modal.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4896]
# User Story
UX - As a Gitcoin funder I'd like to be tastefully routed to the dashboard after a login event via a "new dashboard" dynamic modal.

# Why
Funder Feedback Example:
" I'd be happy for that to be my landing page after I log in.
That's what I need most."

# Assumptions
Human - Funders want to go to the dashboard when they come to Gitcoin
Business - We assume that redirecting them at every login enhances their exprience.
Tech - Only going to apply this to people set as a funder. 

# Description

1. dynamic modal admin section (keep it simple)
2. one entry when we need it, with a scroll
3. marked if a user will see it or not

# Definition of Done
- [ ] Route all funders to the dashboard post log-in
- [ ] Come up with rules on scenario where funder returns, already logged in.

Estimate: **small**

# Data (requirements)
Url tracking , google analytics
Where do people go after dashboard - behavioral flows
Whats the most common action?
Need tracking on modules.

Metrics
Unique page views
Most commonly executed flow
Increased retention!

**Comment by PixelantDesign** [comment]
This is waiting on a design, cc @willsputra

**Comment by octavioamu** [comment]
The content of this updates comes from this issue description, what ever we put there, will be the content of the modal 
https://github.com/gitcoinco/web/issues/5057
