### ISSUE TITLE
as a coder, i want a way to get paid by recruiters to see my resume, since data is labour

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4900]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a coder, i want a way to get paid by recruiters to see my resume, since data is labour
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

right now linkedin sells $99/mo subscription services and in return you can spam as many ppl as you want.  and developers started ignoring these messages because they get them from all sides.
what if we sold a similar subscription service to recruters, but we gave developers some wei everytime a recruiter messaged them and they read it.  kind of like the earn.com model but for 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no way to get $$$ for uploading your resume.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
a way to get $$$ for uploading your resume.
- when u upload your resume in settings/onboard flow you can select 'pay me to give recruiters access
- a resume board where recruiters can access profiles and get the contact info of each dev.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by Solexplorer** [comment]
Just putting my thoughts here.
So my idea is this: you can tell recruiters that they will have to pay X amount per month and can spam only a limited number of users and if they go over that limit they will have to pay X$ each new contact. You can also use the gitcoin chat to put them in contact.
After all Gitcoin is offering the possibility to hire quality engineers and you can also track their performances in the platform to see how reliable they are and how is their approach with every bounty funder.

IMO, if done correctly this would be a win-win scenario for every party.

**Comment by owocki** [comment]
thanks for the feedback @Solexplorer :)
