### ISSUE TITLE
asks me to switch to mainnet - but I am already there

### ISSUE THREAD

**Issue by ligi** [gitcoinco/web#4903]
![image](https://user-images.githubusercontent.com/111600/62137834-e96d7e00-b2e6-11e9-95cf-a3e53be743d0.png)

**Comment by PixelantDesign** [comment]
Thanks @ligi Could you share your system and browser information?

**Comment by ligi** [comment]
Brave Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit) on Ubuntu 18.04.2 LTS
