### ISSUE TITLE
Mail tells me my grant contribution is successful but tx is still pending

### ISSUE THREAD

**Issue by ligi** [gitcoinco/web#4904]
I got this mail:

![Selection_183](https://user-images.githubusercontent.com/111600/62138871-b0cea400-b2e8-11e9-88e7-c052dbd7a6ef.png)

but my tx is still pending

**Comment by PixelantDesign** [comment]
Hi @ligi Thanks for the report. Could you link us to your grant? Thanks!

**Comment by ligi** [comment]
It's not my grant - It's a grant I wanted to support: https://gitcoin.co/grants/127/planet-a
