### ISSUE TITLE
As a user, I want profile v2 so that I can make my gitcoin profile into my professional identity.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4908]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.) As a user, I want profile v2 so that I can make my gitcoin profile into my professional identity.
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

My gut theory is that profile usefulness is a rising tide that lifts all boats.  The more people are able to understand each others activity left / skills on the platform, the more they will be able to understand each other quickly.
Another gut theory is that profiles will be a moat for Gitcoin.  The more people are passing around their gitcoin profile as a center of their professional identiy, the more entrenched Gitcoin will be in the mind of developers.
Ways we'll know were on the right track:
1. Users "look in the mirror" when customizing their profile.  Treating their profile as a reflection of them.
2. Users pass around their gitcoin profile when applying for jobs -- whether on Gitcoin or not.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Profile v1

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Profile V2 will be a tab-based profile system.

![ddd](https://user-images.githubusercontent.com/513929/62170464-b0360d80-b2e8-11e9-9dfb-8106013334a1.png)
1. We will remove the fudner/contributor section and instead only show one section based upon the users persona.
2. There will be tabs on this profile.
3. Users will be able to update their avatar, header, and profile color scheme using this interface.

Tab 1 - Summary
![ddd](https://user-images.githubusercontent.com/513929/62170577-191d8580-b2e9-11e9-9376-674f923acb9b.png)

1. This will be the default tab on the profile.
2. This tab will allow the user to visually see how much activity (in the form of a grid) the profile's user has tken.
3. The grid will have a dropdown that will allow the user to show all activity, bounty work done, or tip/kudos/grant activity.
4. Users will be able to update the front of their profile's summary tab with custom text via WYSIWIG editor.
5. If they don't want to write custom text about themselves on their profile, they will have the option to upload a resume and display that as their overview tab.

tab 2 - activity tab
![sdfsdf](https://user-images.githubusercontent.com/513929/62170683-89c4a200-b2e9-11e9-9929-fea7a22668b7.png)

1. this tab will surface the most recent information about a gitcoin user.
2. this tab is already implemented on gitcoin profiles, but with the following exception:
3. users may do a 'status update' on their profile, which will show on gitcoin.co/activity and on their profile.  i am excited to see what users use this for.  will they use it to just socialize?  will they use it to signal they need help with something?  will they use it to say they are looking for work?

tab 3 - details
![Group 4](https://user-images.githubusercontent.com/513929/62170743-c55f6c00-b2e9-11e9-9bda-966f9afec764.png)

1. this tab will surface detailed information about a gitcoin user.
2. this tab is already implemented on gitcoin profiles, but with the following exception:
3. this tab will list all hackathons that a user has worked on, and whether they won or not.

tab 4 - relationships

![Group 5](https://user-images.githubusercontent.com/513929/62170789-ee7ffc80-b2e9-11e9-906d-5d1687f45171.png)

1. this tab will surface relationship information about a gitcoin user.
2. you will be able to see users past relationships on this tab.  if no relationships, then a nice message will show saying so.  
3. for each relationship, you can see the review of that relationship.  if no review, then there will be whitespace there.
4. users will be able to see who viewed their profile on this view.  this could be used as an indicator of future relationships.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
- Smaller bounce rate when visiting profiles
- Higher sense of 'quality' on the platform.
- People using their Gitcoin profiles for new and novel ways.

[Sketch file](http://bits.owocki.com/4696ddde4239/Profile%20Tabs2.sketch)

**Comment by ohsix1** [comment]
Maybe profile v2 could use blockstack? Starting with profiles and login for implementing blockstack would GItcoin get on the road towards qualifying for app mining solving the revenue issue: #5028
