### ISSUE TITLE
ETH Contribution Amount Not Showing

### ISSUE THREAD

**Issue by edsonayllon** [gitcoinco/web#4909]
**Description**

A past contribution is listed, but the ETH rewarded is not. 

**To Reproduce**

Go to https://gitcoin.co/profile/edsonayllon

**Expected behavior**

ETH receive from https://gitcoin.co/issue/ArweaveTeam/Bounties/1/3152 should be listed.

**Screenshots**

<img width="1247" alt="Screen Shot 2019-07-30 at 10 24 40 PM" src="https://user-images.githubusercontent.com/34966228/62179054-20f51e00-b319-11e9-94ea-b8ec093ac312.png">

**Desktop (please complete the following information):**

- OS: MacOS and Windows 
- Browser: Brave and Chrome
- Browser Version: 75.0.3770.142 (Official Build) (64-bit) for Chrome

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by danlipert** [comment]
Looks like the issue stems from here: https://github.com/gitcoinco/web/blame/master/app/dashboard/models.py#L2698 `bounty` should be `bounties` I think unless I'm missing something @owocki PR is here: https://github.com/gitcoinco/web/pull/4915

**Comment by owocki** [comment]
hmm it says `bounties` unless im mistaken.  let me look at the old commit history; if i messsed it up i want to know so i dont do it again.

**Comment by danlipert** [comment]
@owocki yup I fixed it in my PR https://github.com/gitcoinco/web/pull/4915/files

**Comment by edsonayllon** [comment]
Great, it's showing correctly. I'll close this issue.

**Comment by edsonayllon** [comment]
It seems this issue returned. On receiving a second payment, the first payment was removed from ETH contribution balance. The ETH missing is from the bounty listed in the bug description. 


<img width="1243" alt="Screen Shot 2019-08-02 at 5 13 55 PM" src="https://user-images.githubusercontent.com/34966228/62399223-0bfed180-b549-11e9-8c66-d3866dcb10eb.png">

**Comment by edsonayllon** [comment]
Actually, nevermind, let me close this issue. This is a different bug.
