### ISSUE TITLE
bug - the invoice button doesn't show that i paid for featured bounty

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4927]
**Describe the bug**

bug - the invoice button doesn't show that i paid for featured bounty

**To Reproduce**

buy featured bounty
go to invoice on the bounty
no featured bonty line item

**Expected behavior**

buy featured bounty
go to invoice on the bounty
THERE IS a featured bonty line item

**Comment by GregTheGreek** [comment]
Reference bounty: https://gitcoin.co/issue/ethereum/EIPs/2221/3296
