### ISSUE TITLE
Issue explorer on mobile needs a quick cleanup

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#494]
As a user I want to be able to access and use Gitcoin via mobile regardless of device.

# Description
Show breakpoints in updated issue explorer design.

# Reference
![2018-02-25 20 13 36](https://user-images.githubusercontent.com/513929/36651892-710e66e4-1a68-11e8-96fd-4872de4a91c4.png)

**Comment by thelostone-mc** [comment]
I was getting to that :P

**Comment by owocki** [comment]
hi @thelostone-mc :) 

@PixelantDesign has some new issue explorer designs in the works.  we may want to prioritize those soon.. i will let you know

**Comment by PixelantDesign** [comment]
@owocki @thelostone-mc Should we hold off on this or work on it at the same time as the new issue explorer? I should have that ready in a day or so, Just finalizing one more thing.

**Comment by thelostone-mc** [comment]
@owocki how many % folks use this on mobile ? If it's negligible , we can put it off for now

Then again first impression matters , new users who open this via mobile would not be impressed :/

**Comment by owocki** [comment]
> @owocki @thelostone-mc Should we hold off on this or work on it at the same time as the new issue explorer? I should have that ready in a day or so, Just finalizing one more thing.

i think so, yes. cc @thelostone-mc in case he wants to work on the new issue explorer :)

**Comment by owocki** [comment]
![2018-03-06 14 58 04](https://user-images.githubusercontent.com/513929/37064308-b2644198-2159-11e8-8cee-3d36c17c4a78.jpg)

anotther report that the issue explorer doesnt work on mobile (this is using the trust app browser)

**Comment by thelostone-mc** [comment]
@owocki All this is taken care of in #523 ^_^

**Comment by owocki** [comment]
related https://github.com/gitcoinco/web/issues/496

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/561

**Comment by PixelantDesign** [comment]
Should we close this then? @owocki
