### ISSUE TITLE
As a Gitcoin administrator, I'd like to record the consent information when people agree to our cookies, to comply with various regulations

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4940]
### User Story

As a Gitcoin administrator, I'd like to record the consent information when people agree to our cookies, to comply with various regulations

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Our legal team has advised us that we need to track when people agree to our use of cookies. The following information must be recorded:

- The identity of the user giving consent;
- When they consented;
- What disclosures were made (what they were told) at the time they consented (i.e. what we displayed in the cookie consent banner);
- Methods used for obtaining consent (i.e. the "Accept" button);
- Whether they have withdrawn consent or not. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
This data is tracked in our database

**Comment by octavioamu** [comment]
how we can track identity of cookies if people is not logged? Is not the idea of that cookies like google analytics not being related to de identity of the users?

**Comment by danlipert** [comment]
@octavioamu IP address is acceptable for identity
