### ISSUE TITLE
As a gitcoin user, I'd like to have information about third-party integrations, so I know if my anonymized data is being used for analytics

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4941]
### User Story

As a gitcoin user, I'd like to have information about third-party integrations, so I know if my anonymized data is being used for analytics

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: For legal purposes, we should change our cookie disclosure to the following text: 

"By using this site, you agree to our use of cookies, which we use to analyse our traffic in accordance with our Privacy Policy [link to Privacy Policy]. We also share information about your use of our site with our analytics and marketing partners." [Accept]

**Comment by octavioamu** [comment]
should't be "also share *anonymous* information about your ..." ?

**Comment by danlipert** [comment]
@octavioamu the language came from the lawyers so I'm inclined to go with what they've written verbatim - if you think otherwise though I can put you in touch with them

**Comment by Sirlupinwatson1** [comment]
> 
> 
> should't be "also share _anonymous_ information about your ..." ?

@octavioamu  I think so also, i think that the goal of our mission here no ?

**Comment by octavioamu** [comment]
> @octavioamu the language came from the lawyers so I'm inclined to go with what they've written verbatim - if you think otherwise though I can put you in touch with them

But the lawyers know we don't send personal data? I mean there is no identification of the analytic data.
I'm just bringing this because hunters on hour ecosystem are very cautious about sharing personal data and that message can easy scare them.

**Comment by danlipert** [comment]
@octavioamu hmm yeah you might be right maybe we should close it - alternatively if you'd like to propose the text change I can direct you to the appropriate folks at consensys
