### ISSUE TITLE
As Gitcoin Core, we'd like to increase developer flow into bounties and hackathons so that funders have a higher success rate on their bounties since they'll receive more contributor applications on a bounty --by leveraging CodeFund Ads.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4942]
# User Story
As Gitcoin Core, we'd like to increase developer flow into bounties and hackathons so that funders have a higher success rate on their bounties since they'll receive more contributor applications on a bounty.

# Why Is this Needed
- Increase developer flow into Gitcoin Bounties
- Grow the Gitcoin Community
- Dogfood other products within our product suite. CodeFund will be able to sell this to other customers.
- Grow Revenue
- Increase quality on the platform

# Assumptions
Human - Increase developer quality, increase the retention of funders since there will be more developers to choose from. We also assume that the developers that apply will be of all skill level vs. the current.
Business - This will drive up growth of the platform and we'll be marketing to a larger pool of the developer market than current.
Tech - Ability to create ads via API, ability to get bounties via API

### Description

CodeFund <--> Gitcoin Realtime Ads Integration

For every Gitcoin Bounty that is posted on the Gitcoin platform, we will advertise the bounty through codefund. 

What needs to happen:
- Codefund builds a way to broadcast specific bounites to developers (1week estimate fr Eric).
- Gitcoin needs to build an integration into Codefund.

# Definition of Done
- CodeFund builds Real-Time Ads support for Gitcion.
- Gitcoin team to scope level of effort to integrate with CodeFund.

**Comment by owocki** [comment]
I think we need to think through the economics of this.  Are we subsidizing it with our 10% fee?  Are CodeFund publishers just going to do this for free as a ride-along when there is no sold inventory?  Are Gitcoin customers going to pay extra for it?
