### ISSUE TITLE
When selecting a text in a code block, the line spacing is set at 1.5x

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#4950]
**Describe the bug**

When I try to select text in a code block, it takes more space than needed, see the photo below:
![image](https://user-images.githubusercontent.com/50027175/62464450-e95cfa80-b78c-11e9-9b23-b8ebe14bcac6.png)

**To Reproduce**

Go [here](https://gitcoin.co/issue/bZxNetwork/Bounties/1/3295) and select some text in the code block
**Expected behavior**

I expected it to select the text without taking extra space

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows/Mac
- Browser: Chrome
- Browser Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
This has now been fixed ^_^
