### ISSUE TITLE
[Celery Integration] As a Gitcoin user, I want invite-to-bounty requests to respond quickly, so I can work efficiently.

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#4976]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin user, I want invite-to-bounty requests to respond quickly, so I can work efficiently.
As a Gitcoin dev, I want to have a Celery task queue to use, so that asynchronous tasks can be performed outside the request-response cycle.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: There are many places in the app where long-running processes take place inside of a request-response cycle. Also, there are many long-running processes that sync things with the blockchain and external services, tally leaderboards, etc. These processes are currently ran inside of cron, which is not very scalable.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No task queue.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Sending bounty invite emails uses the task queue.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Celery is set up in the app, and as the first upgrade, bounty invite emails are sent via celery tasks. A Celery task-runner (and Redis) are also booted as part of our local docker development containers so these features can run locally.

### Data Requirements
Response time for this specific endpoint goes down. In the future, response times will go down for many other endpoints, and our "cronbox" gets replaced with a more scalable queue/worker setup.

**Comment by thelostone-mc** [comment]
Mark had done the initial setup over at https://github.com/gitcoinco/web/pull/668. Sadly we didn't get that in :| might be worth checking that PR out @androolloyd

**Comment by owocki** [comment]
excite for this!  can we find time to do the infra work for it in prod this sprint @danlipert @frankchen07

**Comment by androolloyd** [comment]
On the celery server, I setup a systemd service as per `https://docs.celeryproject.org/en/latest/userguide/daemonizing.html#init-script-celeryd`

**Comment by owocki** [comment]
@androolloyd whats left to get celery 100% live?

**Comment by androolloyd** [comment]
I started a review, there is one thing I would add before shipping this, and thats a fallback on the delaying of emails, should the queue append fail, send them normally.

**Comment by owocki** [comment]
@danlipert @androolloyd lets do it!  if this and chat get into the release weds then it'll be like christmas for me
