### ISSUE TITLE
Build Dashboard Promotion Email in Mailchimp

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4978]
### User Story
As a Gitcoin operator, we'd like to promote the dashboard to funders and contributors so they'll know where their bounties stand on Gitcoin.

### Assumptions
Human -  We are assuming that funders need a notification / email / messaging to understand the new dashboard. We're also assuming that this messaging will direct them to the dashboard when in actuality, it should redirect them automatically upon login.

Business -  Assuming that upon login they are directed to the new dashboard, we assume that retention for funders will increase. 

Tech - Use mailchimp

### What 
- [ ] Build the two templates in mailchimp and designate each to appropriate audience.
- [ ] Send a test email to Gitcoin core team for review.
- [ ] Finalize and prep for when we announce the dashboard with a blog post.

### Why
We want users to know about this feature.

### Assets

https://user-images.githubusercontent.com/19514207/62313586-b16f6200-b4c3-11e9-8c2a-e12460d39b22.jpg

https://user-images.githubusercontent.com/19514207/62382280-d2958880-b57f-11e9-8d51-9cef6eee2664.jpg

**Comment by PixelantDesign** [comment]
@willsputra could you attach the final file?

**Comment by willsputra** [comment]
@PixelantDesign 
https://github.com/gitcoinco/creative/blob/e085b9522c910fee56fc8c7c0fd9253a3c431a0f/Product/Dashboard/Intro%20Email/Dashboard%20Intro%20Email.sketch
