### ISSUE TITLE
How Might We Come Up with a More Democratic Way to Decide What We Work On?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#4995]
### Discussion

From Retro Today:
**How do we have a more democratic way to decide what we work on?**

**Comment by owocki** [comment]
a couple thoughts:

1. what is the evidence that pure democracy yields better results towards our OKRs?  what if democracy results in gridlock or the tyranny of the structurelessness?  (i ask this not to "lead the witness", but just to make sure that we are deliberate about what were doing here).
2. katie johnson sent us some really good decision making framework info on august 1.  we should make sure we leverage that prior art.
3. do we still have *focus factor*s built into the sprint planning cycle?  it seems that time outside of sprint assigned work is being spent on triage, tech debt, etc -- this work is not driven from a top down perspective.
4. clearly bottoms up how can we empower individual contributors to achieve consensus on whats important and to solve important problems without a ton of process overhead?

**Comment by kuhnchris** [comment]
Asked a little bit more differently: What are the core goals? From there you can probabbly decide "what is important". If a low turn-over of devs is important (or a high turn-over on small tasks) it may make sense to priorities bugs with engineering - on the contrast if the core goal is to generate revenue/substainability then it may makes sense to priorities "features" that improve on that, e.a. take the ideas bucket and shake it until you find something that could increase platform value.
