### ISSUE TITLE
Longer titles are profile page overflow their bounds

### ISSUE THREAD

**Issue by KennethAshley** [gitcoinco/web#501]
##### Description
Per title, issues with longer titles overflow their bounds into the next title.

##### Possible Implementation
Possible fixes are truncating text, or just making sure the title bounds expand.

##### Example
![image 1](https://user-images.githubusercontent.com/1138619/36689379-d1f28d3c-1af4-11e8-80f0-189951e8d9e5.png)

##### Environment
* **Chrome**:
* **64**:
* **Mac**:

**Comment by owocki** [comment]
lets do this after https://github.com/gitcoinco/web/issues/503

**Comment by owocki** [comment]
seems much better in the new explorer https://gitcoin.co/explorer?q=bounties%20from
