### ISSUE TITLE
Shared Payment Milestone II  - As a funder I'd like to be able to co manage payment and permission with my team.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5010]
### User Story

As a funder I'd like to be abale to co manage payment and permission with my team.

# User Story

As a funder I'd like to be able to manage permissions with my team members.

# Why
- Overwhelming number of funders requesting this feature.
- Make funder workflow easier
- We can package and sell in a subscription

# Assumptions
Human - Teams will be more than two people. 
Business - If we build this funders will improve our platform experience for funders.
Tech - Team members will not share private keys with each other. We will use modified version of standard bounties v2 (we currently use v1). Payout is what we are focusing on here. Other options like management are less important (extend, cancellation - later). 

### Definition of Done

Milestone II
- The Gitcoin platform displays the information from Milestone I synced from Github in the user's settings/profile. Optionally, the user may be able to manually override this data to either add or remove access to specific users and specific repos.

**Comment by PixelantDesign** [comment]
@danlipert would it be simpler to direct users to update this information on Github?

**Comment by danlipert** [comment]
Yes definitely - I think adding manual override to this greatly increases the hours required

**Comment by PixelantDesign** [comment]
Great! Let's limit to updates on Github only cc @willsputra
