### ISSUE TITLE
Consistent fonts across the Gitcoin site

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#502]
As a user I'd like to see consistent fonts across the Gitcoin site.

# Description
Unify font styles across the site.
- Apply new H1-H6, Muli google font
- Test

# Assumptions
No change to content

# Definition of Done
New type strategy is applied and is consistent once coded.

# Reviewers
@PixelantDesign

# Reference Material
https://fonts.google.com/specimen/Muli
[Gitcoin Sticker Sheet.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46cf9d8e208d8aa7cfdaab4aa756f58669752f762c10e1673295f127b54778154d555ca9105e0e47aaaa8d2aa5b73825db5c0be9856d0e72933547bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8e46391e0c118ef95531a68b06.zip)

**Comment by thelostone-mc** [comment]
Just tagging myself as a reminder to help with the review!

**Comment by thelostone-mc** [comment]
@PixelantDesign Give me heads up once this done, I'll help with the review

**Comment by PixelantDesign** [comment]
@thelostone-mc closing this one!
