### ISSUE TITLE
502 bad gateways keep appearing on the blog

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5030]
**Describe the bug**

502 bad gateways keep appearing on the blog

**To Reproduce**

go to the blog
see 502 bad gateway; screenshot: http://bits.owocki.com/4135d837e6d1/Screen%20Shot%202019-08-18%20at%2010.32.07%20AM.png

**Expected behavior**

blog content appears.
502 only appears if i keep hammering the blog

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem.)
502 bad gateways keep appearing on the blog

**Comment by kuhnchris** [comment]
As mentioned on core slack - only happens.. occationally. Please use this issue if you experience it again, thanks.
