### ISSUE TITLE
UX As a Contributor I'd like Gitcoin to Display Matches for new bounties after the submit work step

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5034]
### User Story

As a funder of a Gitcoin bounty or Hackathon, I'd like to have more contributors apply to my bounties.

As a Contributor I'd like Gitcoin to Display Matches for new bounties after the submit work step

### Assumptions
Human - We assume Contributors want this feature
Business - We assume that by adding this feature, more contributors will apply for work.
Tech - 

### Definition of Done

- [ ] Create a ux to solve for surfacing matched bounties to contributors who have just submitted work.
- [ ] Share with robot squad

### Data Tracking
- Track number of clicks/start works from this experience

**Comment by willsputra** [comment]
@PixelantDesign @frankchen07 maybe we can surface this on an email once a contributor submits work? also combined with https://github.com/gitcoinco/web/issues/4308

![submitworkmatching](https://user-images.githubusercontent.com/19514207/63964313-03a2a380-cac1-11e9-88fa-8f3373f68c6c.jpg)

**Comment by frankchen07** [comment]
@willsputra 

I see several pros doing it on the gitcoin site instead of email

1. the way you have it above, it's actually quite interesting with the (non-relevant / view) - this allows us to collect even more information on a hunter's preferences, which will loop back into a positive cycle for matching (whenever we have a matching algo)

2. waiting for email = another point which they can drop off, rather than quickly click and give Gitcoin more data to help augment their preferences

**Comment by willsputra** [comment]
@frankchen07 thanks for the feedback! will explore how we can put the matches on the site

For reference, the existing submit work flow:
![flow](https://user-images.githubusercontent.com/19514207/64058355-1eb20800-cbd4-11e9-8c0c-d3bb59b616f2.jpg)

We most likely won't be able to put stuff on the Transaction Processing page, maybe we display matches when contributors are redirected back to the Issue Explorer?

**Comment by willsputra** [comment]
another idea we can explore
![submit](https://user-images.githubusercontent.com/19514207/64058588-83229680-cbd7-11e9-8d8b-6d8b0ad0a67f.jpg)

**Comment by PixelantDesign** [comment]
Interesting putting it on a bar like that @willsputra! Is there a way to take the bar and put it in a modal that overlays the issue explorer? Or it could be on a screen?

I know there are issues of putting this type of stuff after the submit work step because of the transaction processing screen.

Thoughts @octavioamu @frankchen07 @vs77bb

**Comment by PixelantDesign** [comment]
I like having the email that leads into the app - perhaps the email could be more generic (applies to everyone) and lead to the contributor dashboard @willsputra what do you think?

https://github.com/gitcoinco/web/issues/5034#issuecomment-526295293

**Comment by octavioamu** [comment]
As our email open rate is low I was thinking we can create the dashboard area with matching bounties and point them with a link or even a redirect.

Another point, after submitting work I believe the redirect is to the bounty detail not the explorer.

**Comment by PixelantDesign** [comment]
I think the main point of this task is to have the bounties display after submit work step. 

We have another task that displays bounties on contributor dashboard, see here: https://github.com/gitcoinco/web/issues/5075

**Comment by frankchen07** [comment]
I made the call here to do https://github.com/gitcoinco/web/issues/5075 first, before we pursue it after submit work, since the logistics of where it would pop up doesn't lend us very good options, as it'll either be on issue details or the issue explorer, neither of which are ideal.
