### ISSUE TITLE
As a Funder, I'd like Gitcoin to tell me when I don't have contributors on my bounty, so that I can take action and invite contributors from the users directory

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5035]
### User Story

As a Funder, I'd like Gitcoin to tell me when I don't have contributors on my bounty, so that I can take action and invite contributors from the users directory

### Assumptions
Human - We assume that funders would want to be notified when there are no applicants on the email.
Business - We assume that building this would help funders be more active on their bounties, and increase the number of bounties that get submitted.
Tech - 

### Definition of Done
- [x] Build this email that triggers and sends out daily when a funder doesn't have a contributor on a bounty.
- [x] Follow content described in email mockup below
Hey we noticed you dont have any contributors on your bounty. Or You have 0 applicants on your bounty.
CTA - Go to user directory (show recommendation for the bounty on dashboard).
- [ ] Set Triggers: 0 applicants for 3 days, 7 days

![discoverability email](https://user-images.githubusercontent.com/19514207/63269777-60d07500-c2c9-11e9-87e3-0b23a22eb88b.jpg)

**Comment by PixelantDesign** [comment]
@willsputra could you attach the source file please? Thanks!

**Comment by PixelantDesign** [comment]
Front End Sprint 17
Chron Job Sprint 18

**Comment by willsputra** [comment]
sketch file:
https://github.com/gitcoinco/creative/blob/188e4785587cbae36f47c6a1f3284724ad2bfa0d/Product/Discoverability%20Email/Discoverability%20Email.sketch

**Comment by thelostone-mc** [comment]
@octavioamu I'll build out the email template and hand it off over the weekend  🙌
