### ISSUE TITLE
As an operator of Gitcoin, we'd like to direct hackathon participants from registration right into the Gitcoin onboarding flow.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5039]
### User Story
As an operator of Gitcoin, we'd like to direct hackathon participants from registration right into the Gitcoin onboarding flow.

### What 
We want people to register and then immediately see the prizes and get started.

### Why
Reduce friction. And provide better tracking, as having their Gitcoin profile and other associated info in a usable format (ie not separate from other platform info) will help us target people and track their progress through the hackathon flow so we can diagnose where engagement and drop-offs happen for future improvements.

### Assumptions
Human - We assume that hackers will go through this flow.
Business -We assume that directing hackers into one experience vs. multiple experiences (mailchimp, Discord, Gitcoin, etc) will decrease chance of drop off and provide better tracking.
Tech - Use current onboarding flow

### Definition of Done

- [ ] Create a hackathon flow that follows the flow outlined below
- [ ] This flow is to only apply to hackers that come in from the Hackathon landing page.
- [ ] Review with @alexvotofuture @PixelantDesign 

### Data Tracking
- [ ] Add tracking along each step of the funnel based on clicks to the next screen.

### Additional Information
<img width="1301" alt="Screen Shot 2019-08-19 at 4 26 43 PM" src="https://user-images.githubusercontent.com/238235/63297581-bbed7200-c29f-11e9-8a93-f4a273d7e6a4.png">

**Comment by octavioamu** [comment]
- Where they should write about why they are participating? Are we going to create a form? where that data will be saved? 
- How we will know from where they come from?
- How we know what is the current prize explorer?

As a suggestion is having a new url with just the login so we can use it as a diff link for hackers coming form the landing page ex:  
Landing CTA 
gitcoin.co/signup/Name-of-hackathon 
 - Auth github + explaining about discord and hackathon guide (action button connect gh and goes back to the guide so they can join discord or what ever they need to do) and when ready press "finish"
 - Finish button >  Goes to hackathon/Name-of-hackathon  (prize hackathon)

**Comment by octavioamu** [comment]
About the "why they are participating" I think is out of scope unless we are thinking to point it to a form outside of gitcoin.

**Comment by alexvotofuture** [comment]
This approach looks great to me, Octavio.

If creating a form and storing the info somewhere is difficult we can just do a hacker survey separately. @vs77bb is working on hacker surveys now, and can provide a second opinion on this.

**Comment by danlipert** [comment]
Nice overview @octavioamu !! How many points do you think this will be?

**Comment by PixelantDesign** [comment]
@alexvotofuture to provide content:
- [ ] explaining about discord and hackathon guide (action button connect gh and goes back to the guide so they can join discord or what ever they need to do
