### ISSUE TITLE
Remove Subscribe to Funded Issues at top of Issue Detail Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#504]
As a user, I don't need a persistent area for subscribing to new funded issues. 

# Description
- Remove new funded issues box, since we will now have a popup to capture email at the bottom right hand corner of the site.

# Done Means
- Widget is removed

# Reviewers
@pixelantdesign @owocki

# Reference
![Screen Shot 2018-02-27 at 1.14.42 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f46b7191a379f1132f4f5b5d5edd3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19141c95df742e64c57a7143e63e6772431.png)

**Comment by thelostone-mc** [comment]
@PixelantDesign I've sort of handled this in https://github.com/gitcoinco/web/pull/323#issuecomment-367690843
This is pending merge but yeah just bringing it to your attention :)
