### ISSUE TITLE
Bulk Invite on User Directory

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5045]
### User Story
As a funder of Gitcoin I'd like to be able to invite many contributors at once from the user directory.
As an operator of Gitcoin I'd like to be able to invite many contributors at once from the user directory.

### Assumptions
Human - Funders want this feature for instances where they have no applicants or applicants drop from their bounty.
Business - We assume that implementing this will increase task success on the platform
Tech - We assume that we will look for the lightest lift way to implement to solve the above problem.

### Definition of Done
- [ ] ~~add a check or filter to mass invite contributors only~~
- [ ] add a check to prohibit mass inviting all of gitcoin
- [ ] This feature should allow funder/admins to select all contributors and do a bulk invite.
- [ ] ~~If user unchecks a certain number, then the system should assume that the user wants to select their own contributors from the list, and bulk invite will be deactivated.~~
- [ ] Please refer to the ux that is being worked on in sprint 17

**Comment by danlipert** [comment]
We will probably need to make the "select all" admin only at first, and then have some sort of UX that prevents spam from happening (why wouldn't a funder select all for every bounty they create and invite everyone). Maybe we limit that as a potential paid feature, limit how many uses per month, etc.

**Comment by willsputra** [comment]
If it's admin only, based on yesterday's discussion, we might not need the checkboxes. We can also build the 'Description' part on the modal at a later stage to make things simpler for now.

![bulk](https://user-images.githubusercontent.com/19514207/63878326-96750c80-c9f3-11e9-8cc2-533e9bf0f892.jpg)

**Comment by PixelantDesign** [comment]
- Allow Gitcoin Admins to do use this feature.
- Do not include the description field (for mvp).
