### ISSUE TITLE
Invite Groups of Contributors Based on Skills

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5048]
### User Story
As a Gitcoin Funder I'd like to invite groups of contributors to my bounty so that I have a lot of candidates to choose from.

### What 
Add form field to allow ability to invite groups of users based on skill required on this bounty

### Assumptions
Human - We assume that funders wnat to invite by groups/skills
Business- We assume that if we build this the number of contributor applications woould increase  maybe 3x and would satisfy funders.
Tech - We assume minimal changes too the backend.

### Definition of Done
- [ ] On the funder form add the ability to invite contributors based on skills in groups.
- [ ] Update Invite email subject line to include name of person that invited
- [ ] Update copy as outlined below
- [ ] Open the Invite section of the form by default

### Design

![image](https://user-images.githubusercontent.com/238235/63379955-6da1a700-c363-11e9-9abf-2450af19eedb.png)

![image](https://user-images.githubusercontent.com/238235/63379968-772b0f00-c363-11e9-8e52-46ff67a231ab.png)
Update the above text to:

Hi Guys!
I'm looking for some help on this new bounty! Give it a look and see if you're interested.

Thanks,
@github user

Bounty Name
Value
View Bounty

**Comment by danlipert** [comment]
@thelostone-mc what do you think of this as a start for the backend https://github.com/gitcoinco/web/pull/5060

**Comment by thelostone-mc** [comment]
@danlipert I think we can actually use what we already have from the backend !
So if a funder selects skills as HTML + CSS
Ideally we can hit https://gitcoin.co/api/v0.1/users_fetch/?skills=html%2Ccss and get the results and populate the Invite Contributor field!

The logic to fetch all names from that field on funding an issue is already in place so I believe we can do away without it !

cc @octavioamu

**Comment by danlipert** [comment]
@thelostone-mc Thats good but then won't we need to do a ton of requests to actually send each invite? I think its better to submit the skills to the backend to fire the email rather than submit each user_id to fire each email.
