### ISSUE TITLE
Build - As a funder, I want to see active bounties that don't fit the existing dashboard groups on the dashboard

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#5061]
### User Story
As a funder, I want to see active bounties that don't fit the existing dashboard groups on the dashboard.

### What 
The funder dashboard currently only shows three groups: Open Bounties, Work Submitted, Expired Bounties. However, there are cases where the bounties are still active but no actions are needed so they're not shown, for example:
• Bounties where people started work but have not submitted
• Abandoned bounties

### Why
Funders are confused that some of their bounties are not displayed on the dashboard.

### Definition of Done

- [ ] Create a new section on the funder dashboard that shows bounties that don't fit the existing dashboard groups
- [ ] Review with @octavioamu  @PixelantDesign  @willsputra

**Comment by octavioamu** [comment]
Adding also the invite button to go to user directory with the bounties skills filter

**Comment by PixelantDesign** [comment]
Need to look at how we calculate when actions need to be taken...

**Comment by frankchen07** [comment]
marking this as done, as 5080 continues the issues discussed today in estimation

**Comment by frankchen07** [comment]
this issue is closed, the original issue we've discussed is here: https://github.com/gitcoinco/web/issues/5138
