### ISSUE TITLE
Ethberlin reserved bounties available to all 

### ISSUE THREAD

**Issue by acolytec3** [gitcoinco/web#5064]
**Describe the bug**
Some bounties that were supposed to be reserved for Ethberlin attendees were open for anyone to participate on.  The page displayed an error message stating this bounty is reserved for someone else but still let me start work.  Seems like this should be a bug if it's reserved for someone else.

**To Reproduce**
Apply to work on [this bounty](https://gitcoin.co/issue/ethresearch/eth-wiki/11/3357) or [this one](https://gitcoin.co/issue/ethresearch/eth-wiki/7/3361)

**Expected behavior**
Presumably this shouldn't have let me start work if it's reserved for someone else.

**Screenshots**
![Reserved bounty message](https://user-images.githubusercontent.com/17355484/63629966-270eaf80-c5e4-11e9-96f6-be0639c134c4.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Brave
- Browser Version: Version 0.69.107 Chromium: 76.0.3809.100 (Official Build) beta (64-bit)

**Additional context**
The bounty funder informed me this was supposed to be reserved for Ethberlin attendees.

**Comment by kuhnchris** [comment]
Technically we currently do not have any way to tell if someone is part of an event.
We may be able to add a "requiring certain kudos to participate" which would require you to track down @owocki and shake him until he drops a kudos, but for now - no way to do so, sorry!

The bounty funder reacted correctly since he was able to determine if you were part of ethberlin or not. :-)

**Comment by acolytec3** [comment]
That all makes sense and I'd definitely volunteer to test out that feature
of you ever deploy it. They said, why is the page displaying a "reserved
for someone else" error message but still letting me stay work on the
bounty. Standard rather issues don't even give you an option to start work.
Seems like something is amiss.
