### ISSUE TITLE
Sync Github and Gitcoin Issue Details

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#507]
As a user I want to see the most updated issue details from Github on Gitcoin.co

# Description
Once a funder completes the bounty creation flow. Any edits made to the details of the task on the Github issue page do not sync back to the issue page on Gitcoin.co. It would be great if this was synced at some interval of time.

# Definition of Done
- From a technical perspective explore improvement approaches to solve for the above.
- Review approach with Gitcoin core dev team
- Propose any ux changes to messaging if required (may not be needed).
- Build proposed/reviewed solution

# Reviewers
@owocki or @mbeacom 

# Materials
This is the page that should be up to date.
![Screen Shot 2018-02-27 at 10.59.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f46b7191a379ef0c2e58415f46bc30254d58eeb9cb74fce36f34985619e8806b0e77906e15adbb831bea50ba208f1b85e7badf4496fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae84a53a614356be27f366e0a.png)

**Comment by owocki** [comment]
this is a good idea 👌

**Comment by mbeacom** [comment]
@PixelantDesign @owocki We update all current bounties at an interval of: `1 */5 * * *` being `:01` of every fifth hour.
We execute `refresh_bounties` Django management command which updates comment counts and issue description.  We can add `bounty.fetch_issue_item('title') to additionally update the title, if that's what you're referring to not being updated.

**Comment by owocki** [comment]
> We can add `bounty.fetch_issue_item('title') to additionally update the title, if that's what you're referring to not being updated.

i think @pixelantdesign is referring to the issue desc, not the title

**Comment by owocki** [comment]
>W e update all current bounties at an interval of: 1 */5 * * * being :01 of every fifth hour.

i just worry that if we increase this amount… then once we have enough bounties in the system the jobs will start to overlap with each other and crash the server..
this is somewhere it’d be great to have a message queue to manage these tasks..

**Comment by mbeacom** [comment]
Agreed.  I'd love to frontload the `celery` integration, but I think https://github.com/gitcoinco/web/issues/477 is fairly close.  I don't want to overlap on @g33klord's efforts.  I only brought up `title`, because that's the only thing we're not already syncing on interval.  So, how'd you all like to proceed with this open issue?  Syncing of bounty details is being performed already, but not quite as often as one would like.  If we're in agreement that updating the `title` is irrelevant and we shouldn't decrease the time between refreshing bounties, we're a bit hobbled until we implement `celery`.

**Comment by owocki** [comment]
i think syncing title is the right move.. and well need to come up with a larger gameplan to make it sync more often on another ticket (probably this one https://github.com/gitcoinco/web/issues/520 )

**Comment by vs77bb** [comment]
@owocki @PixelantDesign @mbeacom A countercase to consider... if a repo maintainer is lazy with their titles / we'd like it to be a bit more descriptive, would we want it to be tightly coupled?

IMHO the functionality should be that Gitcoin syncs with Github, but a manual override is possible on Gitcoin (for cases where issue titles aren't visually appealing).

**Comment by mbeacom** [comment]
@vs77bb That makes sense!  With the previous and current flows, we're changing the bounty details regardless of the description entered during initial creation of the bounty during syncs and now with titles.  We should probably rework the way we handle these fields following initial creation. With the mentioned changes, we could consider mutable title/description fields for bounty funders on the details page.

**Comment by owocki** [comment]
perhaps this is too engineer-ey... but could we just have a checkbox that dictates whether or not the issue metadata is synced with github or not?

**Comment by PixelantDesign** [comment]
@owocki @vs77bb If we can't sync it, we should at least make it clear to users when it was last synced, so they are aware that it's outdated information.

**Comment by PixelantDesign** [comment]
I also think a lazy repo maintainer is a random edge case.
