### ISSUE TITLE
As a Gitcoin funder, I can't see bounty submissions for contest bounties because they remain in open status despite having work started or submitted.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5080]
### User Story

As a Gitcoin funder, I can't see bounty submissions for contest bounties because they remain in open status despite having work started or submitted.

### Why Is this Needed

Contest bounties will not show up correctly on the dashboard when submissions arise, which makes it confusing for funders. 

### Description

On the dashboard, there are groups for open, submitted, and expired bounties that the funder can check. For contest bounties, the business logic is such that work started or work submitted on them still equates to an "open" status. This makes checking to see if there are any new submissions on a contest bounty difficult.

### Current Behavior

Contest bounties will remain the "open" group despite "work started" and "work submitted". If this business logic persists, then work submitted options will be taken care of in the "open" section of the dashboard, which doesn't make sense, since there is a "work submitted" section.

### Expected Behavior

For any new submitted work for a contest bounty, there should be a clear indication on the dashboard under the "submitted" bounties section that the funder has to check the submitted work. However, based on business logic, the contest bounty will still technically be open for more submissions, and should be surfaced as "open" to a bounty hunter.

### Definition of Done
TBD

### Data Requirements
TBD

**Comment by sarawut8128** [comment]
ผมจะแก้ไขกับปัญหานี้ไดอย่างไร
