### ISSUE TITLE
invite contributors not working

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5090]
**Describe the bug**

invite contributors not working on /new bounty

**To Reproduce**

go to new bounty
try to invite a contributor

**Expected behavior**

contributors show up when u search

**Screenshots**

http://bits.owocki.com/7dfe3fd0994c/Screen%20Recording%202019-08-28%20at%2011.50%20AM.gif

**Desktop (please complete the following information):**

Mac OS , Chrome

**Comment by octavioamu** [comment]
Now fixed on https://github.com/gitcoinco/web/issues/5048

**Comment by owocki** [comment]
hmmm still not working for  me...  i wonder why... http://bits.owocki.com/fe0af4bfd8a4/Screen%20Shot%202019-09-04%20at%201.33.53%20PM.png

**Comment by octavioamu** [comment]
looks like there is a js error, but just saying about jquery not the actual code, weird. 
![image](https://user-images.githubusercontent.com/1358093/64286620-4555a300-cf34-11e9-918e-3f634331231b.png)

**Comment by octavioamu** [comment]
seems that doesn't happens on local

**Comment by owocki** [comment]
maybe if you impersonate my account ? i have a lot more work history on the platform than anyone else..

**Comment by octavioamu** [comment]
Ohh no no I have the same problem my print is from localhost, My point is working perfect on local but failing on production (also with my user). Trying to guess what is happening.

**Comment by octavioamu** [comment]
sentry ref https://sentry.io/organizations/gitcoin/issues/1068107871/?project=1398424&referrer=slack

**Comment by octavioamu** [comment]
![image](https://user-images.githubusercontent.com/1358093/64290935-6f5f9300-cf3d-11e9-8463-9239bc74ffce.png)
Ok looking at the internet I found the possible reason, related at some data being null, and as I see there is one user null
