### ISSUE TITLE
The Join Community modal not rendering properly.

### ISSUE THREAD

**Issue by vikaskyadav** [gitcoinco/web#510]
##### Description
The modal window for joining community is not rendering properly, may be the issue with image on it.
![issue_gitcoin1](https://user-images.githubusercontent.com/12607959/36772272-8ddd5c12-1c7a-11e8-90dc-9a9efd7381da.png)

##### Environment
Linux- Ubuntu 17.10 64 bit

* **Browser**: Firefox Quantum
* **Version**: 58.0.2 
* **Subsystem**:

**Comment by owocki** [comment]
thanks @vikaskyadav we are looking into this

**Comment by owocki** [comment]
hey @vikaskyadav do you still have an issue here?  we put in a fix on friday

**Comment by vikaskyadav** [comment]
I can't see it. Where does that popover comes?

**Comment by mbeacom** [comment]
@vikaskyadav Go to:  https://gitcoin.co/explorer and scroll down towards the bottom of the page.
<img width="1084" alt="screenshot 2018-03-20 12 40 28" src="https://user-images.githubusercontent.com/7315957/37668888-e3836e2e-2c3b-11e8-8e4a-bf84e723527d.png">

**Comment by vikaskyadav** [comment]
@mbeacom I can't see anything bro. I checked while logged in and also without being loggedin.

**Comment by mbeacom** [comment]
@vikaskyadav Interesting... 😅 I checked on Firefox Developer Edition `60.0b5 (64-bit)` and Firefox Quantum `59.0.1 (64-bit)` - Both are rendering...  This was testing on macos high sierra `10.13.3` though.  I'll load up an ubuntu instance with a wm and see if it occurs.
