### ISSUE TITLE
Please remove the pop-up

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#511]
pops up at each and every page I try to read:

![image](https://user-images.githubusercontent.com/35095758/36782363-64a6bd1e-1c81-11e8-854d-a883320929f9.png)

how can someone focus this way?

**Comment by owocki** [comment]
if you dismiss it does it show up again on the next page you browse?  

i think we may just want to show this on the landing page

**Comment by owocki** [comment]
Chatting with a member of the consensys growth team now:

> hmm it should only show up on the first page they see and then if they enter their email it shouldnt happen again. ill see if i can play around wiht the settings more
> k just made it so it only shows on the first page view

**Comment by lazaridiscom** [comment]
Would I write **[SEVERE]** if it was just one time thing?

Popups are bad, this is a work site, you come back again and again.

Additionally, I have an account.

If I decide to want notifications, I go there (standard behavior of sites).

Don't treat me like I have no brain.

(writing as a user here... and smileys are out of stock)

**Comment by owocki** [comment]
let me know what you think of the fix i posted above @lazaridiscom ^^

**Comment by lazaridiscom** [comment]
>  just made it so it only shows on the first page view

fine for me, @owocki . I usually don't visit landing page (and i guess others users, too).

**Comment by lazaridiscom** [comment]
All good (popup disappeared even in landing page)
