### ISSUE TITLE
code up the new profile tab designs

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5119]
code up the new profile tab designs to the `kevin/profile-v2` branch

![profile_coder](https://user-images.githubusercontent.com/513929/64128391-9b2f1d00-cd73-11e9-8e54-79a9c153ebf0.jpg)
![profile_coder_ratings](https://user-images.githubusercontent.com/513929/64128392-9b2f1d00-cd73-11e9-8b9f-d99930f6a35e.jpg)

**Comment by owocki** [comment]
@iamonuwa u want?

**Comment by iamonuwa** [comment]
@iamonuwa is very much interested

**Comment by owocki** [comment]
cool @iamonuwa can you turnaround by tuesday or weds?  how much ETH is it worth to ya?

**Comment by iamonuwa** [comment]
> cool @iamonuwa can you turnaround by tuesday or weds? how much ETH is it worth to ya?

Thursday

**Comment by owocki** [comment]
@willsputra can u post sketch files?

**Comment by owocki** [comment]
ok

**Comment by owocki** [comment]
![profile-ratings](https://user-images.githubusercontent.com/513929/64272951-9d24e780-cefd-11e9-9695-8e1222815fcd.jpg)

@iamonuwa heads up; new new tab design / ratings tab design... looks like you havent started on this yet, so hopefully im not too late..

**Comment by willsputra** [comment]
@owocki @iamonuwa sketch file:
https://github.com/gitcoinco/creative/blob/master/Product/Profile%20v2/Profile%20v2%20-%20Rating%20and%20Portfolio.sketch

**Comment by iamonuwa** [comment]
This looks good. I'll jump on it once I send in code fixes for this https://github.com/gitcoinco/web/pull/4653 in 20 minutes.

**Comment by iamonuwa** [comment]
@willsputra thanks, will work on it this night

**Comment by iamonuwa** [comment]
Am building this inside the `kevin/profile-v2-refactor` branch
