### ISSUE TITLE
cohort analysis

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#512]
blockers: https://github.com/gitcoinco/web/issues/234

once the identity piece is solved, i'd love to build a reusable cohort analysis that starts with email capture, and shows every involvement with the system over time for a specific cohort (day, week, month)

example cohort analysis 
<img width="1393" alt="screen shot 2018-02-28 at 2 42 24 pm" src="https://user-images.githubusercontent.com/513929/36814712-a480b41c-1c95-11e8-81fa-93699c68ccd2.png">

**Comment by owocki** [comment]
this could be useful => https://github.com/gitcoinco/web/pull/568/

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/commit/d9255ff254209d8d5b839a1a12c24ac60f76ee7c could help too

**Comment by owocki** [comment]
7893833a761c3a1fc528680639522a19fc82725f will help with github cohort analysis

**Comment by owocki** [comment]
e1d3c57c08738ec8dbabe67c144123c938998659

**Comment by owocki** [comment]
just sent the MVP cohort analysis to the team on slack

**Comment by kuhnchris** [comment]
@owocki are you still using this for analysis?
