### ISSUE TITLE
Unable to see or receive tip after github username change.

### ISSUE THREAD

**Issue by aokisok** [gitcoinco/web#5120]
### Who 

aokisok, just a new gitcoin.co user who messed up his account 

### What

@owocki on slack asked me to open an issue here to get this resolved. 

1. Registered on gitcoin.co when my github username was `therealaok` , so I got the profile `gitcoin.co/therealaok` 
2. Changed my github username to `aokisok`
3. Received tip to `@aokisok` on gitcoin.co 
4. Could not collect tip, not showing in the menu, gitcoin.co still showing my old username.
5. Asked on slack for some help, @owocki tried assigning the tip to my account last Friday, still not showing. 
6. Posted here 

### Why

I just want to collect the tip :)  I'm happy enough to delete my account and re-register so it picks up my correct github username. 

### Additional 

This is probably not important for resolving the issue but for completeness: 
I did register a 2nd account on github.com, used my *old* username ('therealaok') which I then logged into gitcoin with. This resulted in a broken account with the gitcoin.co username of `therealaok4444ee15d7f54ba1` .  Perhaps the tip was assigned to this account? I can't do anything on that account it just throws 500 unexpected errors on login. 

Thanks!

**Comment by owocki** [comment]
hey man, thanks for your patience.

i just merged your profile to the new username with `migrate_dupe_profile.py` helhper script.

please logout / log back in;you should now see the claim tip button in the top right when you login as @aokisok ( screenshot http://bits.owocki.com/208cb1dc215d/Image%202019-09-02%20at%201.16.48%20PM.png )

**Comment by aokisok** [comment]
That did the trick, tip recieved and claimed ok. Thanks for your help !  Will close this.
