### ISSUE TITLE
Build Profile Navigation Update

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5124]
### User Story
As a Gitcoin User I'd like to easily find what I need to in the profile nav so that I can focus on doing the most important things related to me.

### Assumptions
Human - We assume that users want an easier more concise way to navigate and get to the appropriate items in their profile. Easy ux will result in retention/ improved experience.
Business -We assume that if we make this update, users will be able to find and do what they need to do, resulting in increased usage and roi.
Tech - Update nav items only, no redoing of the nav dropdown itself.

### What 
- [x] Update profile nav based on this mural
https://app.mural.co/t/consensys3989/m/consensys3989/1566580928153/27a8d8e5aedb6defcf0869f8ea9010b8534c6ad8
- [x] Make sure it works in responsive views

<img width="962" alt="Screen Shot 2019-09-03 at 11 43 45 AM" src="https://user-images.githubusercontent.com/238235/64188333-37265a80-ce40-11e9-8007-283602540918.png">

### Why
There are too many options in the profile nav currently.

**Comment by thelostone-mc** [comment]
Clarifications : 
- This would show up only when the user is logged in
- would need access to mural (unless the task is nothing more than updating the list  )
- Why would My Profile redirect to my Avatar. That is just confusing, isn't it? 
- Dashboard right now doesn't contain info related to Grants. Are we okay on removing it?

Currently what we have 

<img width="278" alt="Screenshot 2019-09-09 at 8 09 40 AM" src="https://user-images.githubusercontent.com/5358146/64500032-362a7880-d2d9-11e9-810b-26345dcf6571.png">

cc @frankchen07 @willsputra @PixelantDesign

**Comment by willsputra** [comment]
> Clarifications :
> 
> * This would show up only when the user is logged in

Yep! Same behavior as the current dropdown.
> * would need access to mural (unless the task is nothing more than updating the list  )

I can't seem to share the mural. @frankchen07 could you help? 
> * Why would My Profile redirect to my Avatar. That is just confusing, isn't it?

nope My Profile would still redirect to the profile. since there's now an Edit Avatar button in the profile, we might not need an extra button for avatar in the dropdown.

> * Dashboard right now doesn't contain info related to Grants. Are we okay on removing it?

@frankchen07 @PixelantDesign I think we discussed this. should we keep My Grants until we integrate it to the dashboard?

> Currently what we have
> 
> <img alt="Screenshot 2019-09-09 at 8 09 40 AM" width="278" src="https://user-images.githubusercontent.com/5358146/64500032-362a7880-d2d9-11e9-810b-26345dcf6571.png">
> 
> cc @frankchen07 @willsputra @PixelantDesign
