### ISSUE TITLE
As a Gitcoin funder, there are some dashboard improvements to be made.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5138]
### User Story

As a Gitcoin funder, there are some dashboard improvements to be made.

### Why Is this Needed

Discussion / bug hunt between Alisa, Octavio, & Frank.

### Description

1. Messaging on open bounties should be changed to something more general ("You don't have any open issues right now!")

![Screen Shot 2019-09-05 at 12 31 24](https://user-images.githubusercontent.com/7516920/64374647-23fac280-cfd9-11e9-88c3-86267bfa1d53.png)

2. The expired bounties group at the bottom is erroring out, therefore an expired and open bounty (https://gitcoin.co/issue/gitcoinco/web/3876/2648) doesn't show up at the bottom, nor does it show up in the open section, and it also isn't counted at the top under the "expired" counter. Technically, as an open and expired bounty, it should only show up under the "expired" section, and once the expiration date has been extended, it should move to the "open" section.

![Screen Shot 2019-09-05 at 12 34 19](https://user-images.githubusercontent.com/7516920/64374852-8227a580-cfd9-11e9-822f-71d2e364a3ed.png)

3. The extend expiration date on (https://gitcoin.co/issue/gitcoinco/web/3876/2648) is not present.

4. Copy scrub and update:
    a. under the submitted bounties section, when there are no bounties, "submittions" should be "submissions"
    b. "If you want to check also your finished and cancel bounties you can find them here:" should be "If you also want to check your finished and cancelled bounties, you can find them here:"
    c. A similar button and message should appear at the bottom of the contributor dashboard to mirror the funder dashboard. This is a stopgap solution while we move attention towards the profile and dashboard. We will eventually remove this stopgap.

![Screen Shot 2019-09-05 at 12 40 21](https://user-images.githubusercontent.com/7516920/64375257-5b1da380-cfda-11e9-8a18-bbe6aa32132c.png)

### Current Behavior

Issues 1-4 exist.

### Expected Behavior

Resolution of issues 1-4.

### Definition of Done
- [x] 1
- [ ] 2
- [ ] 3
- [x] 4

**Comment by octavioamu** [comment]
I don't understand this, someone can put a print of what is happening?

**Comment by octavioamu** [comment]
2. is a server issue not actually related to the development, related to some devops @danlipert fixed this in the past not sure why is this back.
![image](https://user-images.githubusercontent.com/1358093/64657254-f82c7200-d408-11e9-8a43-3786f24dee06.png)

3. Not related to dashboard actually but seems Alisa was able to press the extend since now is no more expired. https://gitcoin.co/issue/gitcoinco/web/3876/2648
