### ISSUE TITLE
as  a user who forgot his preferred payout address private key, i want a way to avoid having this happen again

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5140]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as  a user who forgot his preferred payout address private key, i want a way to avoid having this happen again

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
someone told got paid a few ETH and then forgot which wallet they did it for.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
people set their preferred payout address they set

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- remind them repeatedly what their preferred payout address is
- tell them the seriousness of setting their prefrred payout address and make  sure they understand not to set that private
- keep an audit trail on people setting their preferred payout address

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above ^^
### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by androolloyd** [comment]
A flag in the system that allows for users to be "reminded" after a period about their wallet and to confirm they have access to it before processing a payout, if the user can't verify it, they are prompted to add a new wallet.
