### ISSUE TITLE
Data Protection & Privacy on Gitcoin

### ISSUE THREAD

**Issue by sergejmueller** [gitcoinco/web#5147]
Gitcoin promises privacy and says: "We will never share your email with anyone else". Now I'm surprised that our email addresses are transferred to a third party provider (in this case [Sentry](https://sentry.io/)). Gitcoin uses Sentry to log JavaScript errors.

Would it be possible to track errors anonymously? Just using the user ID?

https://github.com/gitcoinco/web/blob/dd077ec64bb09f53590eb10b32228fb163858b33/app/app/templates/shared/sentry.html#L66

**Comment by owocki** [comment]
yes i agree; just sharing user id upon error would be better

**Comment by sergejmueller** [comment]
Merged.
