### ISSUE TITLE
Gas Limit Set Dangerously High

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#515]
Transaction Error. Exception thrown in contract code.
![image](https://user-images.githubusercontent.com/35095758/36868807-2870474e-1da2-11e8-98ee-9b9b9c316f9e.png)

When i manually correct this gas limit price, and send tx, after a few seconds page is there again (as usual), but the submission is not gone through.

One went through, it seems:

https://etherscan.io/tx/0x2fcf942120b13a3607a04d5a5850fcf4e7094248fbdb73bbd3a9775129eedff7

issue

https://gitcoin.co/funding/details?url=https://github.com/GridPlus/cryptobridge-contracts/issues/11

**Comment by owocki** [comment]
related to https://github.com/ConsenSys/StandardBounties/issues/25
https://github.com/gitcoinco/web/issues/445

for https://github.com/GridPlus/cryptobridge-contracts/issues/11 you cannot do a submission bc the bounty has expired.. will need to have the submitter kill the bounty and then pay out your ETH address directly if they agree that the submission is ready to accepted and they don't mind that it's expired

**Comment by lazaridiscom** [comment]
possibly a quick workaround would be to set default expiration to 1 month ( I mean for new bounties).

Thanks for the quick reply.

**Comment by lazaridiscom** [comment]
and if possible, a descriptive error-message should be shown.

**Comment by mkosowsk** [comment]
@lazaridiscom have anything in mind for what the error message should be?

If I'm understanding this right, something like:

"Error: Cannot submit bounty as it has expired. Please contact bounty submitter directly to resolve."

**Comment by lazaridiscom** [comment]
> "Error: Cannot submit bounty as it has expired. Please contact bounty submitter directly to resolve."

perfect!

**Comment by owocki** [comment]
i just updated https://github.com/gitcoinco/web/issues/445 with this information.. cc @KennethAshley who i think mentioned he was gonna tackle it at some point

**Comment by lazaridiscom** [comment]
Follow-up: #445
