### ISSUE TITLE
How to Get Started (Developer)

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#516]
*This ticket is not fully defined, or ready to be started*

As a first time user, I want a quick overview on how to get started.

Description:
Get started button takes user to a lightbox and drops them on explorer page with no continuation of the flow.

**Comment by owocki** [comment]
https://gitcoin.co/help/dev is a starting point here

**Comment by PixelantDesign** [comment]
Closing in favor of 633
