### ISSUE TITLE
As a Gitcoin operator, I want the issue activity log to be as accurate as possible in accordance to the actions that have been taken.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5173]
### User Story

As a Gitcoin operator, I want the issue activity log to be as accurate as possible in accordance to the actions that have been taken.

### Why Is this Needed

An issue activity log should be an accurate display of history, not a confusing, incorrect, and misleading history.

### Description

There have been multiple bugs and issues reported for the activity log on the issue details page. These include:

- repeated actions
- missing fulfillments that are not rendered in the UI
- wrong order of the applicants

some of these tickets have been logged previously:
https://github.com/gitcoinco/web/issues/2425
https://github.com/gitcoinco/web/issues/4282

### Current Behavior

Today there are many checkers of different elements to understand the state of a user application on a bounty. We use a combination of activity and "interest" to display different actions.

As an example, if someone stops work, the "interest" is removed, and with that, the "work started" reference doesn't exist anymore. If the user applies again, there's no relationship between the action and the interest, which complicates that user's application. 

Another example is "pending" is used for 2 different actions depending on the bounty type. 
So, we need to check if pending is false and bounty type rules, if there are others applicants, and if there is a fulfillment on that bounty. If the fulfillment is from the same user, then there should be a match to the right activity and action buttons. This process is expensive and can easily introduce bugs on the UI.

### Expected Behavior

- activity should be created only when the interest is successful
- activity need to be referenced by an interest id so we can have a more stable way to display the information
- If the user "stops work", we shouldn't delete the interest
- work plans need to be related with the right activity or better, interests need to have the current action "work plan" and we can stop using the activity to manage the logic in the UI

### Solutions

Design/UI fixes:

Long-term fix: https://github.com/gitcoinco/web/issues/5102

### Additional Information

**Comment by frankchen07** [comment]
added some of the previous old tickets that outlined issues

**Comment by octavioamu** [comment]
User having hard time to get what happened with his "work plan" https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1568354747094400

**Comment by owocki** [comment]
looks good
