### ISSUE TITLE
As a Gitcoin operator, when filtering issue explorer and hackathon issues, the relevant contest and cooperative issues should show up

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5174]
### User Story

As a Gitcoin operator, when filtering issue explorer and hackathon issues, the relevant contest and cooperative issues should show up.

### Why Is this Needed

The filters, despite their overhaul, are still not accurate enough.

### Description

"Open" bounty states are translated to "ready to work" on the issue explorer, however this doesn't necessarily ring true for contest and cooperative bounties. Others may have already started and submitted work, which leads to frustration when the contributor has supposedly looked for "ready to work" issues on our explorer.

### Current Behavior
 
The bounty states and the issue explorer states have information asymmetry and it's not helping contributors.

### Expected Behavior

The bounty state should be accurately reflected in and filtered on in the issue explorer.

### Solutions

Design/UI fixes:

-  have both "ready to work" and "submitted" in a cooperative/contest bounty where people already submitted work

- be more direct on the actions waiting from the both sides personas "accepting submissions" is more clear of what I can do on that bounty if Im a contributor, where as "submitted" is more clear to a funder

Long-term fix: https://github.com/gitcoinco/web/issues/5102

### Additional Information

**Comment by owocki** [comment]
solutions look good to me...i think the key will be making sure the UI is easy to understand for the user.
