### ISSUE TITLE
DESIGN - Gitcoin Grants live CLR calculations

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5186]
### User Story

DESIGN - Gitcoin Grants live CLR calculations

### Why Is this Needed

Funders want to know....If I donate to this grant - how much potential scale/match so i know their contribution is counted some how.

### Description

<img width="1308" alt="Screen Shot 2019-08-07 at 2 47 03 PM" src="https://user-images.githubusercontent.com/238235/62652650-d7fd2500-b929-11e9-9d55-7ae9ebc7f34f.png">

<img width="1285" alt="Screen Shot 2019-08-07 at 2 47 12 PM" src="https://user-images.githubusercontent.com/238235/62652655-dc294280-b929-11e9-82d0-72ee1fded55d.png">

### Current Behavior

paint-drawn mockups

### Expected Behavior

beautiful designs

### Definition of Done
- [ ] one design on the grants page (in the mockup)
- [ ] one design on the fund grant page (in the mockup)

**Comment by willsputra** [comment]
@frankchen07 @PixelantDesign thoughts?
![Artboard Copy](https://user-images.githubusercontent.com/19514207/64960597-2c4ed980-d8c6-11e9-9826-e0aeabb6de92.jpg)
![Artboard](https://user-images.githubusercontent.com/19514207/64960598-2ce77000-d8c6-11e9-97f1-ac1eff9bf436.jpg)

**Comment by owocki** [comment]
this is purdy cool!

**Comment by owocki** [comment]
coding this up since CLR starts today

**Comment by frankchen07** [comment]
I'm into it - nice work. @PixelantDesign any last thoughts?

the only change that there might be is the copy and what that might say given the output. I recall Dan talking about a potential "range" (or perhaps it was cached in the backend) for the match number since doing a 100% accurate exact match every time we enter a number might not be great for performance.

**Comment by owocki** [comment]
i just coded this up; i moved the location of it on the phantom fund screen so that it looks like the little bot is telling you the match amount http://bits.owocki.com/ca9ef5ac45fe/Screen%20Shot%202019-09-16%20at%2012.31.15%20PM.png

**Comment by owocki** [comment]
on normal funding pane its where will designed it tho http://bits.owocki.com/b34405c90c42/Screen%20Shot%202019-09-16%20at%2012.34.54%20PM.png

**Comment by owocki** [comment]
note that i didnt code the grant index module.. just the fund estimate module
