### ISSUE TITLE
DESIGN - As a grant donator, I want custom messaging if I am not eligible for CLR due to account age, so I can take action if I think this is in error

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5187]
### User Story

As a grant donator, I want custom messaging if I am not eligible for CLR due to account age, so I can take action if I think this is in error.

### Why Is this Needed

In CLR round 2, a simple method of collusion resistance was to investigate the account age of the contributors towards particular CLR grants. If the account was created day of or only has been open for less than a week (as an example), the CLR contribution would not be counted since this could potentially result in "fake" account behavior.

### Description

1. If your account is below a certain age threshold, you will be unable to fund the grant.
2. A custom message should appear if the user attempts to "contribute to grant"

The custom message should contain:

1. The reason why they are unable to contribute (github account age is below a certain threshold).
2. An ability to quickly contact the Gitcoin team if they would like to be on the exception list.
3. tooltip / understanding how age is calculated

### Current Behavior

this modal does not exist

### Expected Behavior

this exception messaging exists and gates contributions based on the threshold

### Definition of Done
- [ ] design for custom messaging

**Comment by willsputra** [comment]
would be great to know how the account age is calculated!

**Comment by frankchen07** [comment]
@willsputra - for this ticket, we're holding off on making a design. We were thinking in order to get it out by the the deadline (since CLR has already been released), we can use your current CLR pop up design and change the copy. 

We'll do a build right away and do a visual scrub afterwards.
