### ISSUE TITLE
As a hackathon sponsor, I don't know exactly how my performance in the past hack was, so I don't know how to improve

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5188]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a hackathon funder; i want a beautiful/informative "report card" after each hackathon that tells me about engagement for my tasks, so i can be informed about how much value gitcoin has given me and learn how to do even better nextt time 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
hackathon funders dont always see the value we give them; and when things go off the rails they dont know why..

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no report card

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
report card with
- impressions for your bounties (inclusive of explorer/detail page views)
- started work
- submissions
- comments/testimonials/feedback from people who found your bounty
- suggestions for what to do next time (text)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
generative from https://gitcoincore.slack.com/archives/CBWA6A75M/p1567717681028000

**Comment by willsputra** [comment]
we can put it in the orgs profile
![hackathonreport](https://user-images.githubusercontent.com/19514207/66568338-d1926000-eb9b-11e9-8278-2e85d1cf1a3d.jpg)

**Comment by owocki** [comment]
awesome.. curious what @alexvotofuture thinks about this

**Comment by octavioamu** [comment]
this looks amazing @willsputra but I wonder if this information is public and if not if we can move it to dashboard.

**Comment by alexvotofuture** [comment]
We now have a low-fi Metabase report that we send to sponsors so they can track prize performance and other metrics in real time, along with a sponsor "report card" email template sent to them at the conclusion of a hackathon telling them how everything went and asking for feedback. Would be great to design an in-app report card UI instead of Metabase, but we can revisit that at a later time.
