### ISSUE TITLE
Is there still a problem with 'start work' carrying over from bounty to bounty?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#519]
https://github.com/TrustWallet/trust-wallet-ios/issues/367
https://gitcoin.co/funding/details?url=https://github.com/TrustWallet/trust-wallet-ios/issues/367

This user started work 3 days ago (and i presume they didnt stop work because the comment is still there) and then submitted 17 hours ago

<img width="854" alt="screen shot 2018-03-02 at 10 35 50 am" src="https://user-images.githubusercontent.com/513929/36912929-8c0d1166-1e05-11e8-943a-35d7d1933a43.png">

but the issue details page still shows 'no one has started work'

<img width="648" alt="screen shot 2018-03-02 at 10 35 55 am" src="https://user-images.githubusercontent.com/513929/36912921-86073d28-1e05-11e8-8878-8f9f02ef12f0.png">

**Comment by mbeacom** [comment]
Tested on https://stage.gitcoin.co/funding/details/?url=https://github.com/mbeacom/test-repo/issues/19
