### ISSUE TITLE
Django admin permission not working

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#5190]
**Describe the bug**

User permission are not working only the last one is saved, also happening on group permissions

**To Reproduce**

Go to /_administration/user select a user and try to add more than one permission
Go to http://localhost:8000/_administrationauth/group create a new group with many permissions
![image](https://user-images.githubusercontent.com/1358093/64814436-d8688b80-d579-11e9-9306-99a2255884f5.png)
Just last is saved 
![image](https://user-images.githubusercontent.com/1358093/64814478-eb7b5b80-d579-11e9-8bf7-8e7b2b67fa69.png)

**Expected behavior**

permissions are saved

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Duplicate issue : https://github.com/gitcoinco/web/issues/4893

**Comment by owocki** [comment]
iirc this was a django upstream issue? maybe we find/create an issue there?

**Comment by octavioamu** [comment]
Im working in the bulk invite by skills and I think this bug is also there trying to use request.POST.getlist I just get the last one

**Comment by octavioamu** [comment]
maybe django bug related https://code.djangoproject.com/ticket/30381
