### ISSUE TITLE
DESIGN - on the Gitcoin hackathon prizes page, create a get started design logo

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5194]
### User Story

DESIGN - on the Gitcoin hackathon prizes page, create a get started design logo

### Why Is this Needed

designs for onboarding

### Description

https://github.com/gitcoinco/web/issues/5171 - onboarding changes to make the prize explorer page less distracting

### Mockup

<img width="1674" alt="prizes 2" src="https://user-images.githubusercontent.com/7516920/64881168-e9afa780-d60e-11e9-9128-60dffc907887.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
- [ ] design a get started guide logo and text as shown in the mockup
- [ ] attach finished design on https://github.com/gitcoinco/web/issues/5171

**Comment by willsputra** [comment]
@frankchen07 @PixelantDesign something like this?
![getstarted](https://user-images.githubusercontent.com/19514207/64957778-3a99f700-d8c0-11e9-8655-464b319cfcc6.jpg)

**Comment by frankchen07** [comment]
My gut instinct is

1. I feel like it's a little big, and the CTA seems out of place (comments below)

2. the CTA feels wrong (they've already "gotten started") the CTA should be the "hackathon guide" or "guide" or something indicates they can go back to the article / onboarding to re-read instructions

3. ideally it's not necessarily a CTA but it's an action / reference point they understand that takes them back to the onboard page to look at the instructions.

**Comment by willsputra** [comment]
@frankchen07 thanks for the feedback! made it look less like a button:

![hackathonguide](https://user-images.githubusercontent.com/19514207/65050483-08f55e80-d99a-11e9-94cc-ab1703c019a7.png)
