### ISSUE TITLE
special characters messed up in title of grant updates 

### ISSUE THREAD

**Issue by SCBuergel** [gitcoinco/web#5195]
The title in the grant updates don't render simple special characters such as `&` correctly.
Example:
https://gitcoin.co/grants/89/hopr-decentralized-privacy-preserving-messaging-2?tab=updates
On that page you see the title of a an update that is rendered as:
>Improved P2P comms &amp; NAT traversal

**Describe the bug**
Special characters such as `&` should not be rendered in escaped form `&amp;`.

**To Reproduce**
1. Navigate to your grant page
2. Open the UPDATES tab
3. Enter a new update with `&` in the title (potentially other special characters are also rendered wrong)

**Expected behavior**
I expected the title to read: 
>Improved P2P comms & NAT traversal

**Desktop (please complete the following information):**
- Browser: This is browser independent but confirmed on both latest Brave and Firefox

**Comment by thelostone-mc** [comment]
@SCBuergel this got fixed up in another PR and is already live
tested it out locally 
https://share.vidyard.com/watch/xctw4odQjYkpsRZDmnn54Q?
