### ISSUE TITLE
As a Grant owner would like to change my Grant address

### ISSUE THREAD

**Issue by SCBuergel** [gitcoinco/web#5196]
There is currently no way to change a grant address. This would be important especially if grants runs for a longer period of time and wallets should be updated. I'm fine if this is a manual support process but I'd like to update the wallet of [my grant](https://gitcoin.co/grants/89/hopr-decentralized-privacy-preserving-messaging-2?tab=updates) "somehow".

**Comment by thelostone-mc** [comment]
@SCBuergel 
An update on this is that the contract itself doesn't support updating address change at the moment! 
This feature is needed but would require an update on the contract itself

**Comment by SCBuergel** [comment]
Makes sense - I would suggest to add this change for future versions as it's important from an OpSec perspective to not be forced to use one wallet (that might become insecure at some point in the future) for all eternity.
