### ISSUE TITLE
As an admin, I want to be able to queue background tasks to execute outside of the Django app

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#520]
##### Description
The gitcoin service currently doesn't utilize a messaging queue to be schedule jobs in the background or via workers.  For example:  `maybe_market_to_email` at https://github.com/gitcoinco/web/blob/master/app/dashboard/notifications.py#L406

##### Possible Implementation
Implement something like Celery or Tasker making use of SQS, AMQP, etc.

This would allow us to designate methods like marketing notifications to be executed from a decoupled service that doesn't impact the performance or load of the primary web service or it's available resources.

**Comment by owocki** [comment]
this is a great idea.

cc @g33klord who is maybe working on a celery implementation as part of https://github.com/gitcoinco/web/issues/477

**Comment by mbeacom** [comment]
Fulfilled in: #668

**Comment by thelostone-mc** [comment]
Closing it out cause it doesn't look like we are going ahead with this . 😓
