### ISSUE TITLE
Making dinosaur-baby SVG for avatar builder MVP

### ISSUE THREAD

**Issue by agutsal** [gitcoinco/web#5200]
### User Story

As a developer, I want to be able dynamically show/hide some groups (layers) on SVG using javascript.  

### Why Is this Needed
For new 3D avatar builder

*Summary*:
Just create 2nd layer contains another type of object for every of these objects
- head shape
- eyes 
- nose
- mouth
- ears
- clothing 
- hair style
- facial hair
- accessories
- background
### Description
Once you do it for `head shape` stop, deliver the result to me and buzz me

*Type*:
Feature
### Current Behavior
1 layer

### Expected Behavior
2 layers

**Comment by owocki** [comment]
@mladenpetronijevic

**Comment by agutsal** [comment]
Good job!
