### ISSUE TITLE
DESIGN & BUILD - As a Gitcoin operator, add hackathons to the homepage nav bar

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5204]
### User Story

DESIGN & BUILD - As a Gitcoin operator, add hackathons to the homepage nav bar

### Why Is this Needed

As Gitcoin has grown, hackathons have proven to be a well of value and revenue. It's a product. Let's add it to the top nav bar.

### Description

Design icon could be a trophy.

### Current Behavior

hackathons is not currently in the nav bar

### Expected Behavior

hackathons in the nav bar

### Definition of Done
- [ ] design by will
- [ ] add design and link to https://hackathons.gitcoin.co
- [ ] built to gitcoin specifications

### Design

to be attached

**Comment by octavioamu** [comment]
But we are linking to the hackathon list already 
![image](https://user-images.githubusercontent.com/1358093/65271480-a0ba9000-daf3-11e9-8318-3b4de29cc9d5.png)

**Comment by kuhnchris** [comment]
Maybe he means up here?
![grafik](https://user-images.githubusercontent.com/761911/65449168-b0f7a580-de3a-11e9-8014-4a7fc3c935f8.png)

**Comment by frankchen07** [comment]
I think Octavio meant it's already in the dropdown, but not the top nav bar yet (since it is becoming a core product / already a core product)

Either way, it's lower priority right now!

**Comment by willsputra** [comment]
had a few ideas. curious what people think! 🙂
![hackathon](https://user-images.githubusercontent.com/19514207/66330387-dfa96c00-e962-11e9-9f1e-a60d2ebe9a0c.png)
![mobile](https://user-images.githubusercontent.com/19514207/66330376-d91af480-e962-11e9-96fc-b07a941f0809.png)

**Comment by kuhnchris** [comment]
I like the lightblub one.

**Comment by alexvotofuture** [comment]
@frankchen07 I think this one has been implemented, and should be good to close.
