### ISSUE TITLE
As a potential user of Gitcoin, I want to see Gitcoin blog posts on the homepage.

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#5217]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a potential user of Gitcoin, I want to see Gitcoin blog posts on the homepage.

### Current Behavior
[comment]: # (Describe what actually happened.)
[gitcoin.co](https://gitcoin.co/) homepage still shows 'Gitcoin on Medium'
![Screenshot 2019-09-18 at 10 31 15 PM](https://user-images.githubusercontent.com/19514207/65157911-11b26700-da64-11e9-9d56-1eaf7e65309e.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Since our latest blog posts are now in [gitcoin.co/blog](https://gitcoin.co/blog/), it should show posts from gitcoin.co/blog instead

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
*Gitcoin on Medium* is changed to *Gitcoin Blog*, with articles coming from gitcoin.co/blog

**Comment by kuhnchris** [comment]
did we migrate off medium completly or do we want to have an additional section "Gitcoin Blog" before "Gitcoin on Medium"?
