### ISSUE TITLE
As a potential user of Gitcoin, I want to see Hackathons as a product offering

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#5218]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a potential user of Gitcoin, I want to see Hackathons as a product offering

### Current Behavior
[comment]: # (Describe what actually happened.)
No 'Hackathons' on 'Our Products' section in gitcoin.co homepage.
![Screenshot 2019-09-18 at 10 34 37 PM](https://user-images.githubusercontent.com/19514207/65158345-bdf44d80-da64-11e9-8a79-213bb27ecf56.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Add Hackathons to 'Our Products' section

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Hackathons is added to 'Our Products' section

**Comment by kuhnchris** [comment]
Is it already finalized what it does entail as "product"? as in, pricing, offering, etc.?
If so, we can add it fairly easy. Give me the wording and an icon and I'll throw it on
