### ISSUE TITLE
BUILD - Display Match on Contributor Dashboard

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5220]
### User Story

BUILD - Display Match on Contributor Dashboard 

As a Gitcoin Contributor I'd like my matched bounties to be displayed on the dashboard to surface interesting projects that I could potentially work on.

As a funder I'd like contributors to see my bounties that match their skills on the dashboard so that I can automatically have developer flow into my bounties.

### Assumptions
Human - We assume contributors would want this feature on the dashboard
Business - We assume that if we build this, funders would have more dev flow into their bounties
Tech - We assume that we will need to build a new view or filter by skills on issue explorer.

### What 
Build Display Match on Contributor Dashboard

### Definition of Done
- [ ] Build display of bounty matches on the contributor dashboard
- [ ] Refer to mockup to be provided

### Design
https://github.com/gitcoinco/web/issues/5075

![image](https://user-images.githubusercontent.com/1358093/65276954-41627d00-daff-11e9-8dde-96d5cdf7e309.png)

![image](https://user-images.githubusercontent.com/1358093/65276945-3b6c9c00-daff-11e9-9675-d2e425bc133c.png)

**Comment by octavioamu** [comment]
@willsputra Im almost ready with this task but I have some questions
Should we show just open bounties, or we can show others also and add the status? 
Do we want to show the number of applicants as the explorer?
Im using the same endpoint of explorer for this, so this is de data I have:

```
avatar_url: "http://localhost:8000/dynamic/avatar/gitcoinco"
bounty_owner_address: "0xd386793f1db5f21609571c0164841e5ea2d33ad8"
canceled_on: null
event: null
experience_level: "Beginner"
expires_date: "2019-10-13T02:59:59Z"
fulfillment_accepted_on: "2019-09-12T17:51:53.626050Z"
fulfillment_started_on: "2019-09-12T17:38:11.432288Z"
fulfillment_submitted_on: "2019-09-12T17:48:29.300217Z"
github_org_name: "gitcoinco"
interested: Array(1)
0:
created: "2019-09-12T17:38:11.432288Z"
issue_message: "Im doing it the best as I can do it Im doing it the best as I can do it Im doing it the best as I can do it"
pending: false
profile:
avatar_url: "/media/avatars/72f4f6d365732c50762730b1bc630379/octavioamu.png"
github_url: "https://github.com/octavioamu"
handle: "octavioamu"
id: 13
keywords: (4) ["CSS", "JavaScript", "HTML", "PHP"]
organizations: {gitcoinco: 4}
position: 1
total_earned: 0
url: "/profile/octavioamu"
__proto__: Object
signed_nda: null
__proto__: Object
length: 1
__proto__: Array(0)
is_open: false
keywords: "JavaScript,Python"
latest_activity:
activity_type: "work_done"
bounty: 44
created: "2019-09-12T17:51:53.736261Z"
kudos: null
metadata:
fulfillment: {id: 20, accepted: true, accepted_on: "2019-09-12 17:51:53.626050+00:00", fulfiller_name: "", fulfillment_id: 0, …}
new_bounty: {id: 44, title: "DESIGN - Gitcoin Grants live CLR calculations", token_name: "ETH", value_in_eth: "0.1", value_in_token: "100000000000000000", …}
old_bounty: {id: 43, title: "DESIGN - Gitcoin Grants live CLR calculations", token_name: "ETH", value_in_eth: "0.10", value_in_token: "100000000000000000.00", …}
__proto__: Object
profile:
avatar_url: "/media/avatars/72f4f6d365732c50762730b1bc630379/octavioamu.png"
github_url: "https://github.com/octavioamu"
handle: "octavioamu"
id: 13
keywords: (4) ["CSS", "JavaScript", "HTML", "PHP"]
organizations: {gitcoinco: 4}
position: 1
total_earned: 0
url: "/profile/octavioamu"
__proto__: Object
tip: null
__proto__: Object
network: "rinkeby"
pk: 44
project_type: "traditional"
standard_bounties_id: 2405
status: "done"
title: "DESIGN - Gitcoin Grants live CLR calculations"
token_address: "0x0000000000000000000000000000000000000000"
token_name: "ETH"
url: "http://localhost:8000/issue/gitcoinco/web/5186/2405"
value_in_token: "100000000000000000.00"
value_in_usdt: "18.07"
web3_created: "2019-09-12T17:26:25Z"
```

**Comment by octavioamu** [comment]
No skills:
![image](https://user-images.githubusercontent.com/1358093/65291115-57386800-db28-11e9-88c7-6658443b54df.png)

No bounties with my skills 
![image](https://user-images.githubusercontent.com/1358093/65291151-7505cd00-db28-11e9-8df6-d1c79b999841.png)

With match
![image](https://user-images.githubusercontent.com/1358093/65291374-77b4f200-db29-11e9-98c6-7efd2550657f.png)
