### ISSUE TITLE
BUILD - As a hackathon participant, I want a simple, easy "how to" for how hackathons work

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5221]
### User Story

Build - As a hackathon participant, I want a simple, easy "how to" for how hackathons work

### Why Is this Needed

There needs to be an easy instructions page that informs how people "get started" on a hackathon.

### Description

The new onboard page will be a simple, intuitive design that is modeled off of a version of @alexvotofuture's onboarding blog post, with words simplified to a flow diagram. (https://gitcoin.co/blog/hackathon-guide/)

### Current Behavior

The current page has too many CTAs that open other windows under (how to participate) and leads them away from the onboarding process. We want this to be less distracting, and get them to login and get to the prize explorer as soon as possible.

<img width="1673" alt="hack-onboard-log" src="https://user-images.githubusercontent.com/7516920/64719325-e684b200-d47c-11e9-86bc-181d3ffed580.png">

### Expected Behavior

1. simple diagram of the flow they're about to proceed through
2. design here: 

### Definition of Done
- [ ] design diagram for alex's blog post 
- [ ] build of the page to gitcoin standards

### Design
https://github.com/gitcoinco/web/issues/5170

![image](https://user-images.githubusercontent.com/1358093/65276795-ea5ca800-dafe-11e9-8b8a-8e30f5aa3083.png)

**Comment by octavioamu** [comment]
@willsputra can I have the sketch file?

**Comment by frankchen07** [comment]
There's a design update on this one. Will ping @willsputra to help out on this one, and then we'll post the sketch file.

**Comment by willsputra** [comment]
@frankchen07 updated design.

changes:
• removed step 3 (create/find teams on github)
• edited the copy of step 2 (join discord):
"Chat with other hackers, ask sponsors and the Gitcoin team questions, find or create a team, and communicate real-time on the Gitcoin Events Discord."

will upload the Sketch file if everything's fine!

![hackathonhowto](https://user-images.githubusercontent.com/19514207/65515297-9e9c6b00-df11-11e9-96cc-cf55001ec9ff.jpg)

**Comment by octavioamu** [comment]
@willsputra upload the file so I can start working then if there is something to change I can make the needed changes
