### ISSUE TITLE
Gitcoin Grants CLR Round 3 v2 Improvements

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5223]
### User Story

Gitcoin Grants CLR Round 3 v2 Improvements

### Why Is this Needed

Product experiment asks from Vitalik, v2 improvements post v1 launch.

### Description

1. CLR live pop-up design update (@willsputra / @PixelantDesign stated that using a navy colored background would be better)

<img width="610" alt="Screen Shot 2019-09-19 at 11 25 35 AM" src="https://user-images.githubusercontent.com/7516920/65276890-9a211e00-dadd-11e9-9667-01a5a92d8b0a.png">

Is it possible to make it pop up only when there's a number entered in amount field?

2. How are we calculating non-pairs? Currently it makes sense that if a grant only has one contribution, it would be paired by itself, resulting in a CLR contribution that is either equal to the contribution itself or the threshold. (@thelostone-mc to check). This will also fix the 0 DAI matching for those grants that don't have a matching CLR pair yet.

3. Add phantom funding to the CLR estimate (@thelostone-mc & @danlipert)

4. Ensure that dropped txns make its way into the formula. As of 2019-09-24, contribution IDs (1207, 1208, 1209, 1210, 1211, 1212, 1213) were dropped and replaced due to gas issues

### Current Behavior

v1 grants clr

### Expected Behavior

add v2 improvements

### Definition of Done
- [x] update design
- [x] ensure grant non-pairs calculation makes sense
- [x] add phantom funding to the CLR estimate

**Comment by thelostone-mc** [comment]
<img width="310" alt="Screenshot 2019-09-26 at 8 54 59 PM" src="https://user-images.githubusercontent.com/5358146/65702016-ec46de00-e09f-11e9-818d-d540349c392b.png">

made it a lil cleaner like in the landing page
