### ISSUE TITLE
Feature request: Faucet request status in dashboard

### ISSUE THREAD

**Issue by sebastiantf** [gitcoinco/web#5232]
### User Story

As a Gitcoin user, I want to be able to see the status of my faucet request in my dashboard for better clarity.

### Description
Currently there is no option or method of checking the status of my faucet request. There isn't even an option to check whether I've already submitted a request. The option is to submit a request again and only then would I be told that the same wallet has a pending request.

I would like to have an option in the dashboard that lists my faucet requests and it's status to have better clarity and visibility of the requests. It also helps to identify whether the request was successful and would clear any ambiguity.

*Type*: Feature

I think this would be a good feature to add.

**Comment by kuhnchris** [comment]
seems to easy enough to implement. Anyone may want to try that?

**Comment by ashish10677** [comment]
I would love to try it. Can you assign it to me?
