### ISSUE TITLE
Funding failed half-way through. Funds stuck / lost?

### ISSUE THREAD

**Issue by gonchs** [gitcoinco/web#5235]
I was trying to fund this issue:

https://github.com/stablecoinswap/meta/issues/1 - https://imgur.com/a/6OOINNK

The first two transactions were sent:

- https://etherscan.io/tx/0xb00400340ad0d7462d44ad0f0508d7baba733b792c09b7f994f40be9ec919231
- https://etherscan.io/tx/0x6d745bf73a7d4607e157db74941606a13437b0916e7c0e7d66b510ad3f53af27

And the third one failed.

Now the issue is still not funded but I have already sent $62 worth of DAI / ETH to you. How do I initiate the third transactions again?

**Comment by jschiarizzi** [comment]
@kuhnchris i dont think this is a Grants issue. Looks like funding a bounty issue

**Comment by owocki** [comment]
unfortunately theres not a wayto initiate the third tx again. i can refund the fees and you can resubmit the whole thing.. does that work?

this assumes the third one is not salvageable .. can you resubmit it with metamask at a higher gas price (this is what metamasks UI calls 'speed up')

**Comment by gonchs** [comment]
A refund would work. And then I'll resubmit it again. Third transaction is not pending, it wasn't sent.

**Comment by gonchs** [comment]
Any estimate on when will the refund be sent? Please send it to the original sender address: `0x053b7f29bc6d95182f0e54efc86549938878647e`

**Comment by owocki** [comment]
sorry; was heads down yday building https://github.com/gitcoinco/web/pull/5257

just sent the refunds

https://etherscan.io/tx/0x844be0d76c69463a95f8da5bbde4c29790885d5e2cbf09e49a3c39f2c2807035
https://etherscan.io/tx/0xc19b8b80dc1f0d624270385f925743a0a4b67d28e21e505d537f36da930e346f
