### ISSUE TITLE
As a hackathon participant, 0.001 ETH on all of our prizes is inaccurate and misleading

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5238]
### User Story

As a hackathon participant, 0.001 ETH on all of our prizes is inaccurate and misleading

### Problem

Previously, the 0.001 ETH display on all of our hackathon prizes was because the sponsor didn't necessary have the actual funds, the incorrect currency was being used, or Gitcoin  didn't support the correct currency at the time. As we tighten up our hackathon experience, it doesn't make sense to see all the prizes being an insignificant amount of ETH, as it subtracts from the experience.

### Description

![image](https://user-images.githubusercontent.com/7516920/65455231-a8cc4580-ddfb-11e9-808f-d06479e58948.png)

### Current Behavior
prizes are all 0.001 ETH when they shouldn't be

### Expected Behavior
hackathon participants should be able to see what the prize is, straight up.

### Solutions
1. longer solution: restrict sponsors to using DAI or ETH so the issues can be posted correctly
2. stop gap solution: override amount numbers without syncing from the blockchain
3. stop gap solution: administrative controls on what to sync to the blockchain

### Definition of Done
TBD

**Comment by kuhnchris** [comment]
wouldn't 2.) shoot ourselves in the foot if by the time the hackathon finishes and the funds are not in we try to resolve a contract with the wrong amount of money that isn't in there?
3.) would be a general nice thing to have, as mentioned previously, but would need to be usable only with caution.

I think the main solution to this would simply be that the sponsors either directly fund themselves, provide a multi-sig wallet with the funds or simply "pay before using". I know it's not "sponsor friendly" but you cannot book an onsite event with no money and then pay the location later either...

**Comment by owocki** [comment]
maybe we could have a `bounty.prize_override` which can be displayed on the bounty explorer and details page in place of the normal stdbounties funded amounts...

**Comment by kuhnchris** [comment]
still, wouldn't that cause a race condition as the person can only be payed as much as the stdcontract has been funded with?
If finance is quick enough i see no problem, I just fear that we will get ourselves into (very) hot water if we artificially 'display or promise' prices that will only later be in full effect with the possible outcome that someone may back off or the funding run short or the conversion rate is different, etc.

Else, I think we reference bountry.prize far too often to have a prize_override function properly.

**Comment by frankchen07** [comment]
I'll reiterate that the problems we're solving for are two-fold.

1. we want the correct amount displayed
2. ideally the correct amount should be locked in the contract, this enables payout to go smoothly.

@vs77bb / @alexvotofuture - for most of the payout issues, was it confusion about the advanced payout tips system or was it because the amounts were not correct, and therefore they had to pay off the Gitcoin app? If its mostly the former, then I see a stopgap solution working better here since number 1 would be the real issue.

**Comment by octavioamu** [comment]
As a easiest solution if the value is 0.001 then the button will show "see prizes"

**Comment by octavioamu** [comment]
"see prize" is a stop gap for now. 
The cases I have seen:
- Needs to overwrite the value (microsoft)
- Coins not supported by the platform
- Bounties with more than 1 prize inside (1st 2nd 3rd prizes)
- Prize is not only tokens/coin had other benefits
cc @vs77bb @alexvotofuture @ceresstation

**Comment by frankchen07** [comment]
what was the reason for overwriting the value re: microsoft?

> coins not supported by the platform

is it difficult to spin up a placeholder token so we can add it and display it by placeholder token? similar to ocean protocol? I think we asked harmony to do this too

> 1st/2nd/3rd prizes 

what makes sense here is what most marketing tactics follow: we would just list 1st as the amount and have the details in the bounty details (like win the lottery, only if you get all the numbers otherwise taco monies only)

> other benefits 

are these non-coin benefits? if so, I feel like putting those in the issue details makes sense.
