### ISSUE TITLE
Gitcoin Quadratic Funding UI bug

### ISSUE THREAD

**Issue by Sm00g15** [gitcoinco/web#5244]
**Describe the bug**
Quadratic funding grant cards have overlapping text

**To Reproduce**
go to https://gitcoin.co/grants/ and look inside the grant cards

**Expected behavior**
non-overlapping text

**Screenshots**
<img width="945" alt="Screen Shot 2019-09-24 at 4 36 20 PM" src="https://user-images.githubusercontent.com/14209806/65481507-bb24ad00-dee9-11e9-90d7-b0dbdb6b723c.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: latest

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Thanks @Sm00g15 for the report ! 
We rolled out the fix after we saw it on twitter 

<img width="389" alt="Screenshot 2019-09-26 at 4 22 47 PM" src="https://user-images.githubusercontent.com/5358146/65683047-f229c880-e079-11e9-9436-3e870499dc14.png">

This is how it looks right now in live !

Closing this out ^_^
