### ISSUE TITLE
Changing issue details to 'permissionless' does not auto-approve pending applicants

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#5246]
**Describe the bug**

When updating an issue to be permissionless rather than permissioned users who are already in a pending state waiting to be approved must still be manually approved.

**To Reproduce**

Create a traditional + approval required issue, wait for people to apply, and then change both categories in issue details.

**Expected behavior**

Any user in a pending state is automatically approved for work when the issue is changed to permissionless.

**Screenshots**

https://gyazo.com/f9dfe340ab9ffb620516279775e401b7

**Comment by ashish10677** [comment]
Is this issue open? I would like to take up this issue
