### ISSUE TITLE
Increase payout transaction reverted

### ISSUE THREAD

**Issue by ghost** [gitcoinco/web#5253]
Tried to increase the payout for https://gitcoin.co/issue/austintgriffith/burner-wallet/234/3499.

One tx passed: 

https://etherscan.io/tx/0xb186685f8f211f27f2b2c3b8c8c4060a023d8fb795f58dd592d08af2afe3f658

the second one was reverted:

https://etherscan.io/tx/0x41c8eed63cadc9f082e9dcd4791ebe5a18358188b6b4ab3ae369ac69b910a6c8

resulting in a loss for me of $0.1 (value of the confirmed transaction).

**Comment by owocki** [comment]
can send  a refund if u want... i think at current gas prices itll cost more in gas than the value to send it tho :/

**Comment by gonchs** [comment]
No need, I just wanted to report it.
