### ISSUE TITLE
As a funder of a bounty I cannot see my bounties

### ISSUE THREAD

**Issue by SCBuergel** [gitcoinco/web#5259]
As a funder of a bounty I cannot see my bounties. I navigate to https://gitcoin.co/dashboard/ and click on `Funder` and I see
`OPEN BOUNTIES 0`, `IN PROGRESS 0`, `BOUNTY SUBMISSIONS 0`, `EXPIRED BOUNTIES 0`
despite the fact that I have one ongoing bounty, various completed bounties.

My username is SCBuergel, I tried from various browsers with the same outcome.

**Comment by octavioamu** [comment]
Are you able to see https://gitcoin.co/issue/hoprnet/hopr-website/13/3500  on "in progress"?
That one should be there, regard to the completed bounties are not showed in the dashboard we provide a link on the bottom to see the "Done" ones https://gitcoin.co/explorer?bounty_filter=createdByMe&network=mainnet&order_by=-web3_created

**Comment by owocki** [comment]
@thelostone-mc you can see their current active bounties on their profile... https://gitcoin.co/profile/statussceptre

**Comment by SCBuergel** [comment]
Bump. This is a major issue that makes the usage of Gitcoin severely annoying for bounty funders. I need to scroll through my mailbox and notifications in order to keep track of what bounties are currently ongoing.

**Comment by owocki** [comment]
let me bump this internally

**Comment by owocki** [comment]
@SCBuergel try now

**Comment by SCBuergel** [comment]
Wow that was super fast from bump to fix! Thanks this seems to fix it for me, wonderful!

![Screenshot_20191104-105541](https://user-images.githubusercontent.com/11379673/68148911-c4923380-fef1-11e9-9375-b976c928e807.png)

**Comment by octavioamu** [comment]
Sorry I wasn't able to reproduce the first time and got stuck.
@SCBuergel happy to know how dashboard work for you and how we can do it better.
@StatusSceptre curious to know if now is working for you.

**Comment by StatusSceptre** [comment]
Can confirm that our dashboard is now working. Sorry I missed your comments, but thanks for the fix, guys! This view is helpful.
