### ISSUE TITLE
As a funder of a bounty I cannot pay out the bounty, button disabled and no info

### ISSUE THREAD

**Issue by SCBuergel** [gitcoinco/web#5260]
I was funding the following bounty which has been successfully completed by the bounty hunter:
https://gitcoin.co/issue/hoprnet/hopr-website/8/3463
Now I click on `Pay out` and get to the page `Let's Get This Bounty Paid Out` which has two buttons: `BASIC` and `ADVANCED` - unfortunately the first button is disabled so that I cannot pay out the bounty. The other button works.

**Comment by owocki** [comment]
there are no submissions. thats why u can't do a basic payout.

@thelostone-mc @willsputra looks like we may not making that clear to uses on the basic vs advanced payout page

**Comment by thelostone-mc** [comment]
Solution: On the payout page -> right now we show 2 options 
Basic + Advanced Payout 
The former is disabled with the message stating it has no submissions 

A neater solution would be : hide the basic payout section itself 
and leave a message below the advanced payout stating basic payout will be available once contributior make a submission

To see what we are talking about Flow: 

- Create bounty `/new`
- Click on Payout button on the issue 
- See the basic + advanced payout page (this is where the changes need to be made)
