### ISSUE TITLE
discuss: tip for code review

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#527]
##### Description

I've seen @mbeacom single handedly review stuff (sort of makes me debate if he's human / machine )
Would we consider offering mini tips to folks to do code review right ?
More eyes looking at code == less chances of bugs + better code quality 
and it eases the pressure when we've got too many PRs 

(We could create a label -> will tip for review )

@vs77bb @coderberry @mkosowsk

**Comment by mkosowsk** [comment]
I give a super duper 👍 to this idea! At my work, we instituted a policy where even the smallest PR's must have two reviewers (even one-liners!) and larger PRs must have at least 3 reviewers. I think this has been really beneficial in (1) spreading knowledge across the team and (2) upping code quality. Think having multiple reviewers has a lot of positive effects :)

My team at ETHDenver explored something somewhat similar with our project of MentorCoin 😍

"MentorCoin allows users to connect through GitHub and post pull requests for code they need help on, and offer a small ETH bounty as a reward. Mentors can browse through a list of requests to see where they can offer their expertise. The ETH reward is disbursed through the StandardBounties system."

@thelostone-mc I really like your approach of creating a label of "Will tip for review" as an MVP that we could possibly build on 🤔

I think a possible addition to this could be integrating the Code Review requests into the Gitcoin explorer itself as something like "Funded Code Reviews/Pull Requests" but this might make the Explorer a bit too busy. @PixelantDesign thoughts?

**Comment by PixelantDesign** [comment]
@thelostone-mc
I like this idea a lot! it is also how we talk about one of the ways Gitcoin can be used to augment workflow. It’ll help us build up case studies! Great suggestion.

@mkosowsk 
Hmmm...I think explorer is the right place to show this not sure how different it should be from other tickets, as mvp anyway. I think thete is value in diffetentiating down the road.

**Comment by owocki** [comment]
agree RE: your comments about @mbeacom.  he's reviewing a lot of stuff!

one alternative way we could work through this is giving a pct of the bounty (if there is a bounty) to the reviewer.. or otherwise giving the fulfiller the option to divide up their bounty at the time they submit it.

**Comment by mbeacom** [comment]
I'm always up to have an extra set of eyes to help review PRs.  I like the idea of allocating some amount of the bounty to the community reviewer.  I've been looking at: https://stickler-ci.com/ to help catch linter and pattern specific issues against submitted PRs as well.  Considering it's a free service for OSS, I think it might be worth exploring in addition to peer reviews.
