### ISSUE TITLE
As a hackathon participant, I'd like the prize bounty end date ("time left") to match the actual state of affairs. 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5273]
### User Story

As a hackathon participant, I'd like the prize bounty end date ("time left") to match the actual state of affairs. 

### Problem

From the contributor perspective:

The bounty end date on the Gitcoin issue details "time left: 1 month" doesn't match with what we have in the issue details description "All bounty submissions must be received no later than 11:59 PM EDT on October 4th, 2019 to be considered." 

The end time should match everywhere on the bounty, so it's obvious when my deadline is. 

### Description

At the top of the bounty: 
<img width="1248" alt="Screen Shot 2019-09-26 at 15 05 51" src="https://user-images.githubusercontent.com/7516920/65728285-454a4e00-e06f-11e9-802e-ac895c3a7bd3.png">

In the issue description: 
<img width="832" alt="Screen Shot 2019-09-26 at 15 05 59" src="https://user-images.githubusercontent.com/7516920/65728286-454a4e00-e06f-11e9-9de3-0b551f92308c.png">

### Current Behavior

time left != actual end date of the hackathon

### Expected Behavior

the prize bounty end date should be absolutely clear in all locations

### Solution

Time left should display how much time is left, but when hovering over, it should display the actual expiration end date and time. 

Simply having a countdown timer is not the same as seeing what the end date is. 

Design and UX approved by Will 

### Definition of Done

- [ ] add hover popup over "time left" that displays the expiration date and time

**Comment by alexvotofuture** [comment]
Critical (but n00b-level) question to determine if we need to do anything with this: Can a funder pay out a bounty using advanced payout _after_ a bounty has passed its expiration date?

**Comment by alexvotofuture** [comment]
Rationale is this: We want to cut off "submit work" instances after the bounty expiration date, but we still want to allow the funder to pay out the winning submission days afterward, once they've had time to review the submissions and select a winner.

**Comment by alexvotofuture** [comment]
With granular date selection (which has already been implemented) this should be as easy as selecting the correct submission deadline date (assuming we always end the hackathon at just before midnight, otherwise we'll need a time selector as well).

See this other ticket for the issue with selecting a submission deadline/expiration date (Tl;Dr need to make sure funders can still use advanced payout after the expiration date passes, so they have time to judge and pay out after submissions are all in).

**Comment by frankchen07** [comment]
this has been implemented, and the granular date selection exists
