### ISSUE TITLE
As a hackathon funder, when my prize bounty reaches the deadline, how can I be assured that no more submissions are allowed after the deadline, and that payout can begin?

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5274]
### User Story

As a hackathon funder, when my prize bounty reaches the deadline, how can I be assured that no more submissions are allowed after the deadline, and that payout can begin?

### Why Is this Needed

When you're a sponsor for a hackathon and you're opening issues, it makes sense that the issues you open follows the end date of a hackathon.

A deadline means if you didn't submit your project on my prize before the deadline, then I won't be judging your project. I won't see the project, because you were unable to submit it.

Gitcoin should allow me to pay out my prize to the projects easily and quickly.

### Description

From the funder perspective:

1. When opening a bounty, I can set a granular date, but what happens if I set it incorrectly and it doesn't follow the hackathon end date?

2. Contributors should not be able to submit prizes after the end date. A deadline is a deadline.

2. After the end date (when the bounty is expired), am I still able to payout using advanced payout?

### Assumptions

1. We are assuming that it's extra effort for the funder to make sure they set the end date exactly right.

2. We are assuming that funders want a hard cut-off with no more submissions when the hackathon ends.

3. We are assuming that the way our bounties are currently set up, we're unable to do advanced payout after an issue has expired.

### Current Behavior

1. funder sets the end date
2. submissions can still come in after the end date
3. payout can't happen when the issue has expired

### Expected Behavior
TBD

### Definition of Done

TBD

**Comment by alexvotofuture** [comment]
Critical (but n00b-level) question to determine if we need to do anything with this: Can a funder pay out a bounty using advanced payout after a bounty has passed its expiration date?

Rationale is this: We want to cut off "submit work" instances after the bounty expiration date, but we still want to allow the funder to pay out a contributor for the winning submission days afterward, once they've had time to review the submissions and select a winner.

**Comment by danlipert** [comment]
We can set the end date of the bounty to the hackathon's end date when they select the hackathon from the create bounty form to simplify the UX - is there a case where we would want to allow the funder to set it to something different than the hackathon end date?

**Comment by owocki** [comment]
the original gitcoin system set the gitcoin bounty expiration date as the stdbounties expiration date and we got lots of complaints from funders who were annoyed they couldnt pay out after expiration date..

not saying this ticket is invalid; just adding a data point.

**Comment by frankchen07** [comment]
problem is inability to payout if there are no submissions - post expiration date, you can still submit a PR but you can't "submit work"

@thelostone-mc to confirm pre & post expiration date ability to submit / payout 

is this ticket necessary given the current marketing on bounties?

**Comment by frankchen07** [comment]
closed - the current functionality solves the problem - keeping the possible actions flexible for a funder, regardless of expiration date
