### ISSUE TITLE
As a potential hackathon hacker I want a way to navigate to hackathons from the Gitcoin homepage

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5283]
### User Story

As a potential hackathon hacker I want a way to navigate to all hackathons from the Gitcoin homepage.

### Why Is this Needed

There is currently no way to navigate to [past hackathons Gitcoin has hosted](https://hackathons.gitcoin.co) from the Gitcoin homepage, and only one way to see the current hackathon: a banner at the top that must be manually updated.

As Gitcoin moves toward holding consistent hackathons and, soon, multiple concurrent hackathons, we need a way for hackers to find hackathons they are interested in easily from the homepage.

Administrators and sponsors also don't have a simple way to access the hackathon pages, and must either search for the pages, keep them bookmarked, or find the original link to the pages posted elsewhere.

### Description

*Type*: Feature

### Current Behavior
Banner at the top of Gitcoin homepage leads to the current hackathon's landing page (which is hosted on a separate hackathon-specific WordPress site). The hackathon-specific WordPress site has a list of all hackathons past and present, along with links to results and blog post summaries, but there's no way to navigate to this site without editing the url directly.

### Expected Behavior
A "Hackathons" button next to the rest of Gitcoin's products with it's own unique icon on the top of the Gitcoin homepage, here:
![image](https://user-images.githubusercontent.com/8337893/65923107-8195eb00-e39c-11e9-8aab-471d83d0f627.png)

Should lead to the [hackathon WordPress page](https://hackathons.gitcoin.co/) for now, which will allow users to click into active and past hackathons and the results for each.

### Definition of Done

- [ ] Logo design for hackathons
- [ ] Button at the top of the Gitcoin page that leads to the hackathons WordPress site

### Data Requirements
Would be ideal to track who we convert to being a registered hackathon participant through the homepage. But may not be possible given the jump between Gitcoin main domain and the Gitcoin Hackathons WordPress domain.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@willsputra could maybe help here

**Comment by willsputra** [comment]
I think this is captured here too https://github.com/gitcoinco/web/issues/5204

**Comment by alexvotofuture** [comment]
@frankchen07 I think this one has been implemented, and should be good to close.
