### ISSUE TITLE
Leaderboard link broken on profile pages

### ISSUE THREAD

**Issue by sergejmueller** [gitcoinco/web#5289]
**Describe the bug**
A profile page has a link to the leaderboard (below `OrganizationRank`). Clicking on the link ends on a 404 page: https://gitcoin.co/leaderboard/%5B%5D

**To Reproduce**
* https://gitcoin.co/profile/polkadot-js
* Click the link _View_ on the line `#44 On Leaderboard`

**Expected behavior**
The Leaderboard page.

**Comment by thelostone-mc** [comment]
This has been resolved with the latest deploy ! Could you double check ?

**Comment by sergejmueller** [comment]
Not fixed.
```
<li>
<b>#44</b>
On Leaderboard
<a style="font-size: 12px; color: black; text-decoration: underline;" 
href="/leaderboard/%5B%5D">(View)</a>
</li>
```

**Comment by thelostone-mc** [comment]
Fixed ! Deploying
