### ISSUE TITLE
Fund an Issue Suggestion/FTUX

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#529]
As a funder when funding an issues, I'd like to be prompted and educated on the types of issues I can fund in Gitcoin.

I would also like to see only relevant information/fields based on the option that I select.

Ideas: 
New Feature, feature improvement, bug, testing, design, or code review.

**Comment by owocki** [comment]
this would be a nice improvement of https://gitcoin.co/onboard

**Comment by owocki** [comment]
i'd add that maybe a short overview video (say, recorded by me) might do teh trick

**Comment by PixelantDesign** [comment]
![Screen Shot 2018-04-25 at 3.50.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a37bf1172b4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44fe74553a5133761e77e2431.png)

Opening a new build ticket for this.
