### ISSUE TITLE
chore: fix css for profile/active

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#5291]
#### Description

- Navigate to https://gitcoin.co/profile/gitcoinco/active

The list looks like this at the moment 

<img width="1145" alt="Screenshot 2019-10-02 at 8 47 37 PM" src="https://user-images.githubusercontent.com/5358146/66057348-2dcf0180-e556-11e9-8f15-930d4407a599.png">

Reuse the css from https://gitcoin.co/explorer to make it look neater 

<img width="1387" alt="Screenshot 2019-10-02 at 8 50 30 PM" src="https://user-images.githubusercontent.com/5358146/66057421-4c34fd00-e556-11e9-9ffc-b1007dc8a055.png">

**Comment by Ian-Yy** [comment]
Hi @thelostone-mc , can I give it a try on this issue?

**Comment by thelostone-mc** [comment]
@Ian-Yy go for it mate ^_^

**Comment by HenriqueFadoni** [comment]
Can I get this issue? If it still open assign to me!
