### ISSUE TITLE
Funding tx failed but displayed in the grant

### ISSUE THREAD

**Issue by emilianobonassi** [gitcoinco/web#5300]
**Describe the bug**
I've tried to fund this grant https://gitcoin.co/grants/141/metamoneymarket?tab=activity but only the last one had success, in the first ones I've set the wrong amount only the approve tx was successful.

**To Reproduce**
Fund any project without having the amount you have, you just need ETH to pay gas for the approve tx.

**Expected behavior**
Fund successful should not be displayed if second tx (the ones who move funds to the grant and give the commission) fails.

**Screenshots**

<img width="830" alt="Screenshot 2019-10-04 at 21 59 56" src="https://user-images.githubusercontent.com/8052911/66236307-73283600-e6f2-11e9-808e-6a28d7296747.png">

<img width="887" alt="Screenshot 2019-10-04 at 22 00 17" src="https://user-images.githubusercontent.com/8052911/66236312-76bbbd00-e6f2-11e9-9b77-77af453df3b1.png">

**Desktop (please complete the following information):**

- OS: Mac OS X 10.14.6
- Browser: Chrome
- Browser Version: 77.0.3865.90 (Official Build) (64-bit)

**Comment by emilianobonassi** [comment]
Tested with a more big one

<img width="1385" alt="Screenshot 2019-10-04 at 22 04 21" src="https://user-images.githubusercontent.com/8052911/66236540-08c3c580-e6f3-11e9-99fb-0f75a7312a29.png">

**Comment by kuhnchris** [comment]
Hey there - thanks for reporting - we keep having issues with "failed" and "replaced TXIDs. As soon as I know more we'll keep you posted. Thanks.

**Comment by kingjacob** [comment]
This is still displaying as if we had $3k donated. Would it be possible to get it cleared?

**Comment by owocki** [comment]
just marked it as failed.. thanks for the bump!
