### ISSUE TITLE
Gitcoin API throws error 500 on bounties/<bountyId>/ endpoint

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5307]
**Describe the bug**

When trying to get data using a bounty id, it returns error 500:
![immagine](https://user-images.githubusercontent.com/50027175/66403955-d1e9fa00-e9e7-11e9-8be3-05d83ccb34fe.png)

**To Reproduce**

Use the gitcoin endpoint: https://gitcoin.co/api/v0.1/bounties/3538 where 3538 is the last bounty as of the time of writing, I have tried with other bounties but the result is still the same.

**Expected behavior**

I expect to get bounty details given a bountyId

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Browser: 
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
```
AssertionError: Cannot filter a query once a slice has been taken.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 56, in retrieve
    instance = self.get_object()
  File "rest_framework/generics.py", line 98, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "rest_framework/generics.py", line 21, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "cacheops/query.py", line 354, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "django/db/models/query.py", line 399, in get
    clone = self.filter(*args, **kwargs)
  File "django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "django/db/models/query.py", line 904, in _filter_or_exclude
    "Cannot filter a query once a slice has been taken."

```

i took a look this morning + couldnt figure how how to fix it without breaking the offset/limit functionality of the API..
might have to plumb the internals of DRF

is this API route advertised somewhere? its not one that the app uses to my knowledge

**Comment by Solexplorer** [comment]
Hey Kevin,

I found it in the [Gitcoin API documentation](https://docs.gitcoin.co/mk_rest_api/): 
![immagine](https://user-images.githubusercontent.com/50027175/67208232-6a836f80-f415-11e9-8d67-535cf211c04c.png)

I was trying to get bounty info given an ID

**Comment by owocki** [comment]
got it; pls use https://gitcoin.co/api/v0.1/bounties/?pk=3538 in the meantime as a workaround

**Comment by Solexplorer** [comment]
Hey @owocki,

I was looking at why my script wasn't working and I found out that the api is not returining the details of the bounty even with the workaround you gave me. If I call it like this: `bounties/?pk=3538/`

**Comment by owocki** [comment]
got an example URL? looks like its working for me https://gitcoin.co/api/v0.1/bounties/?pk=3538

**Comment by Solexplorer** [comment]
Maybe I didn't explain myself.
I am trying to fetch the details of a certain bounty given an ID. If you test this: https://gitcoin.co/api/v0.1/bounties/?pk=3589&network=mainnet, you are giving me back the last 5 bounties and not the bounty `3589`

**Comment by owocki** [comment]
oh ur right; here this will help: cce953d1900918d7d4573a909b3460208bff604d 

will go out in our next deploy..

**Comment by Solexplorer** [comment]
Thank you!

**Comment by Solexplorer** [comment]
It's not returning anything back after the deploy 😅 . I tested it like this: https://gitcoin.co/api/v0.1/bounties/?pk=3538

**Comment by owocki** [comment]
@Solexplorer 3538 is not a current bounty.  try this instead http://gitcoin.co/api/v0.1/bounties/?pk=9781

**Comment by owocki** [comment]
we could change this by exempting the 'pk' key at https://github.com/gitcoinco/web/blob/master/app/dashboard/router.py#L235 if ppl feel strongly about that

**Comment by Solexplorer** [comment]
Opsie my bad. Thanks for checking in
