### ISSUE TITLE
As a hackathon sponsor I want performance metrics for my prizes

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5308]
### User Story

As a hackathon sponsor I want performance metrics for my prizes so that I can intervene if prizes are under-performing during the hackathon and validate my sponsorship investment after the hackathon.

### Why Is this Needed

There is no easy way to provide metrics to sponsors and administrators to help them understand the "health" of a hackathon prize and decide what can be done to make sure the prizes are successful.

The criteria for prize "success" varies, but usually includes impressions (number of times users view a prize), engagement (number of users working on a prize, especially those that have the skills and reputation necessary to complete their work), and, most importantly, meaningful contributions ("Submit[ted] Work" that was acceptable enough to pay out the contributor).

Gitcoin administrators also use these metrics to determine their own intervention strategy during a hackathon, pushing targeted messaging and product features that encourage views, started work, and submissions until participation is satisfactory.

### Description

*Type*: Feature

### Current Behavior
Gitcoin administrators manually count "Start Work" and "Submit Work" instances from the hackathon prize explorer, then update the sum on a spreadsheet. This is then shared with sponsors upon request.

There are no easily queryable metrics on prize page impressions, demographics/skills for users that engage with a prize, lists of hackathon submissions, etc.

### Expected Behavior
A dashboard that allows access to metrics on each hackathon prize and all prizes combined.

The dashboard must be accessible to individual Gitcoin team members so they can pull reports for sponsors and the Gitcoin team at will. We may eventually wish to provide a real-time dashboard to sponsors directly so they can assess performance at any time, but this is not currently necessary.

The dashboard shouldn't just provide summary metrics - it should allow a user to see the data that led to the summary statistic (so that users can take action on specific problems/opportunities), and enable further filtering by sponsor, status, etc. to help users gain context on the prize's/hackathon's performance.

We should have the ability to pull from all relevant sources of qualitative and quantitative data necessary for querying (Google Analytics, Metabase, etc.). However, it's not yet important to have those sources filter into a unified dashboard; we just need to be able to access both bodies of data when necessary.

ASAP queries: 

Overall Hackathon Questions
- [x] total prize money per hackathon
- [x] number of sponsors
- [x] number of bounties per sponsor (low, median, average, high)
- [x] distribution of money per bounty (low, median, average, high)

Community Engagement
- [x] total number of participants (start/submit work?)
- [ ] number of returning sign ups
- [ ] how were they reactivated?

Per-Hackathon Per-Bounty
- [x] cost per entry by sponsor
- [x] number of entries per bounty (start work)

DevCon Specific
- [x] export of all hacker emails marked working on a sponsor/hackathon to add to mailing list

---

Frank to organize this section:
```
Breakouts of ## of new Sign-Ups
CPA for Market Spend
CPA for $$$ spent on Bounty
Inbound Performance by Marketing Channel
Is there a way to track conversions by types of bounties? ie. Is CodeFund good at converting all leads, or just hardcore devs?
%% Conversion 
→ Inbound to Sign-Up
→ Sign-Up to Discord/Work Started
→ Work-Started to Work Completed
NOTE: any missing steps in the GitCoin funnel would be helpful here
Optimum $$ to Hacker/Submission Ratio
The question I’m trying to answer - is there diminishing returns for the size of prize money past a certain point. Are we spending 4k when 3k would the same results? 

Per-Hackathon Per-Bounty

Average entry per bounty
Breakouts for Previous Request of "## of Entries Per Bounty"
## of First-Time Bounty Entries (never used GC or was in a Hackathon)
## First time Hackathoners (have used GC before, have not entered a hackathon)
## Hackathoners (have entered a Hackathon previously)
```

Queries the dashboard should help us answer:
**Hackathon-wide queries**
- [ ] How many users registered for the hackathon? 
- [ ] How many new users registered, who haven't participated in a hackathon before?
- [x] How many users started work across all prizes? 
- [x] How many submitted work
- [x] For those who submitted work, where can we get a link to their project and profile?
- [x] What is a given user's Discord name, as provided on the start work form?
- [ ] Which web sources are driving the most traffic to our hackathon sites (CodeFund, external sites, Gitcoin homepage, etc.), and how can we better market hackathons to drive more traffic to the site?
- [ ] How do we optimize our hackathon flow to reduce drop-off and increase engagement (as measured by registered hackers and projects successfully submitted and paid out through Gitcoin)?
- [x] Which sponsors have the fewest total "Start Work" instances?
- [x] How many hackers list a given skill on their Github profile? (ex: Rust, JS, UX, Token Design, etc.)

**Prize/Sponsor-Specific Queries**
- [x] How many unique impressions did a prize get?
- [x] How many users started/submitted work? 
- [x] Where can we find their submissions?
- [x] How many users with a given skill started work?
- [x] Which prizes have been paid out?

### Definition of Done
We should be able to perform all queries above through Metabase/Google Analytics. Queries can be made as we go, but data should be formatted in such a way that these queries are possible.

### Data Requirements
See above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by alexvotofuture** [comment]
@frankchen07 Let me know if these queries are all possible given the current data structure. I can help prioritize which queries are most important so we can begin coding them up if they don't already exist.

**Comment by alexvotofuture** [comment]
From Zach @ Labs: Determining the effect of prize funds on participation, as well as participation by time of year would be helpful.

**Comment by frankchen07** [comment]
@alexvotofuture thanks ill be working on this tomorrow during deep work, and I'll take a pre-look today. Thanks for putting together the ticket.

**Comment by owocki** [comment]
this seems related to what @willsputra did design wise on https://github.com/gitcoinco/web/issues/5188#issuecomment-540547031
