### ISSUE TITLE
As a Gitcoin admin, email communications to hackathon sponsors and hackers is a manual, operationally laborious process

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5311]
### User Story

As a Gitcoin hackathon administrator I want to send out automated emails to hackers and sponsors so that I can reduce operational labor and ensure timely communication of key info.

### Why Is this Needed
*Summary*:
Gitcoin hackathon administrators send emails to hackers and sponsors at various points during the hackathon to share administrative updates, provide tips on how to use the platform, and encourage engagement by featuring sponsors/prizes.

Some of the emails include the following:
- Next hackathon announcement
- Registration open
- Pre-launch team formation
- Launch and encourage "Start Work"
- Mid-hackathon check in
- Submission deadline reminder and encourage "Submit Work"
- Post-deadline wrap-up and hacker survey

Each of these emails takes time to manually write and send to the appropriate audience. Although manually writing offers an opportunity to customize the email, making communications for a given hackathon more meaningful and fun, we often just need to send a basic email and ensure the information gets to the audience quickly.

### Description

*Type*: Feature

### Current Behavior
Hackathon emails are manually composed and sent via Mailchimp.

### Expected Behavior
Hackathon emails should be automatically sent at key points in the hackathon. We should be able to pull hackathon-specific information (start/end date, hackathon logo, sponsors, total prize amount, etc.) for each email. Would be great to optionally customize emails with manually-input information for a given hackathon before they are sent, but have the emails default to sending boilerplate content at the very least.

The system should be able to send to a pre-defined audience (all hackers, hackers registered for a specific hackathon, hackers who have registered but who have not yet hit "Start Work") so that we can reach out with targeted messaging to the right groups to provide support.

@connoroday has produced a full set of hackathon emails that we can make into templates with variables in key spots where data is needed.

### Definition of Done
- [ ] consolidate hackathon interest/hackathon hackers mailchimp lists
- [ ] an email system capable of sending hackathon emails upon key trigger events, which we define when first setting up a hackathon.

### Data Requirements
Will need to pull hackathon-specific admin information to populate the variables in the email campaign.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by octavioamu** [comment]
Is not the reason why we setup mailchimp? I think this need to be managed in the mailchimp side giving managers the ability to setup each layout. 
We don't have currently a system to give managers the ability to visually create a template for an email. 
Mailchimp have tools for this, also for the automation part, just need to setup the rules for each mailing list and people will receive this emails. 
Most of the suggested situation in the ticket are not really automatic, each one need a layout/text different and depends on timing.
