### ISSUE TITLE
Bounty Invite email is broken

### ISSUE THREAD

**Issue by acolytec3** [gitcoinco/web#5314]
**Describe the bug**
Bounty invite email seems to have 2 bugs
1) Email says I have no payout address but clicking on "set payout address" link takes me to my profile where a payout address is clearly defined.  I do not see this issue on the Gitcoin weekly email.
2) Bounty link opens 404.  I've been invited to several bounties over the past several months and it always opens to a gitcoin 404

**To Reproduce**
Click on either "Set payout address" or "View Bounty" link to see described errors

**Expected behavior**
Bounty Invite email should tell me my payout address attached to my Gitcoin profile and View Bounty links should work.

**Screenshots**

![404](https://user-images.githubusercontent.com/17355484/66700979-c71fb580-ecc4-11e9-8aed-7bd0c84b1555.png)
![No payout address](https://user-images.githubusercontent.com/17355484/66700986-cc7d0000-ecc4-11e9-8333-9f924669b717.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Brave
- Browser Version: Version 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)

**Comment by acolytec3** [comment]
Just an fyi but this is still happening.

**Comment by owocki** [comment]
ok; do u want to PR a fix?  or should i bounty it and have someone else from the community fix it

**Comment by acolytec3** [comment]
Sorry for slow response. It just happened again with an invite I got. I had the dev tools open on Brave and didn't see any obvious errors but I'm getting the same 404 on Brave desktop/mobile and Chrome on Android.  So, not sure I have an instinct on what the issue is exactly. Am I the only one who's reported it? Bounty invites always generate a 404 for me.
