### ISSUE TITLE
Link Broken when trying to go back from bounty page.

### ISSUE THREAD

**Issue by sagarchoudhary96** [gitcoinco/web#5315]
**Describe the bug**
When i try to go back from the bounty page to the dashboard by pressing the back button in the browser, it throws an error.

**To Reproduce**
open https://gitcoin.co/dashboard/, click any bounty. once opened click the back button of the browser.

**Expected behavior**
It should redirect to the dashboard but it's throwing an error for now.

**Screenshots**
![Oct-13-2019 09-00-19](https://user-images.githubusercontent.com/16102594/66710540-606bcc00-ed98-11e9-95dd-9c3e3b38d847.gif)

**Desktop (please complete the following information):**

- OS: Mac OS Catalina 
- Browser: Chrome
- Browser Version: 77.0.3865.90

**Comment by kuhnchris** [comment]
This sounds like rate-limiting. @danlipert could you check?

Thanks

**Comment by danlipert** [comment]
I can't reproduce - can you @kuhnchris ?

**Comment by kuhnchris** [comment]
big 'ol nope from my side. @sagarchoudhary96 can you reproduce it?
