### ISSUE TITLE
As a hackathon sponsor, payout to multiple winners & users is a confusing & nerve-racking experience.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5321]
### User Story

As a hackathon sponsor, payout to multiple winners & users is a confusing & nerve-racking experience.

### Why Is this Needed

Payout is the ultimate conclusion to a hackathon experience, which allows sponsors to payout to multiple or a single winner, globally. This is a powerful feature, and of course, people want assurance and peace of mind when it comes to paying out large amounts.

### Description

Problems that have been brought to our attention:

✅ 1. It's not clear which bounty is being paid during advanced payout, since the bounty title is not shown, only the bounty url is shown.

will & octavio solution - 2. Paying out beyond the available bounty funds should trigger a visual warning. The difference would be paid out from your wallet. The bounty funded amount message does exist (above), but the problem is that the message's proximity might lead to confusion. Possible solutions include bordering the amount in red to indicate that they are paying from their own wallet, and that it exceeds the amount.

will & octavio solution - 3. The payout preview table could be more obvious. Zach didn't realize that the table existed.

✅ 4. To add contributors the "[add+]" button wasn't obvious. Consensys Labs feedback revealed that the "[add+]" was assumed to be "adding to rating", so it wasn't entirely clear. The position and meaning of the button can most likely be made more clear.

5. The  #/% toggle could be more obvious - Zach didn't realize it existed until Alex informed that the % button was a toggle.

6. It's not clear you can add contributors by clicking on the username on the submitted work section

7. There are no transaction addresses displayed on the payout page, nor on the invoices. A possible solution is to simply add the transaction address on the invoice.

### Current Behavior

The payout experience as it exists is confusing & nerve wracking, and has the problems listed in the experience above. 

### Expected Behavior

Fixes so that the sponsor is not confused or anxious during the payout process
### Definition of Done

TBD

### Additional Information

**Which of these improvements overlaps with the standard bounties v2 upgrades?**

This will be fixed by standard bounties v2:
When paying out using advanced payout, "cancelled bounty” shows up before tips go through, which adds to the confusion. If you use bounty funds, the status is cancelled - if you don't use bounty funds and only tip, the status will be done.

pay using bounty funds - refund, then tips
pay not using bounty funds - difference is tipped

Standard bounties v2 upgrade anticipated mid sprint Q4

**Lower in priority:**

* The gas recommendations (high, medium, low) were all the same, which is confusing.

* There is a $2,500 tip limit for advanced payout, which may not be high enough for certain sponsors.

**Comment by owocki** [comment]
ill be curious to see if v1 of team payout solves this.. at 100k ft the story makes sense, but that should be validated at 10k feet once the code is ready..
