### ISSUE TITLE
As a hackathon sponsor, I don't have a place to see live, ongoing projects, which makes me think the hackathon is not as active.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5322]
### User Story

As a hackathon sponsor, I don't have a place to see live, ongoing projects, which makes me think the hackathon is not as active.

### Why Is this Needed

While sponsors can catch up on their issues via Github, having a central location where they can see the ideas and workplans of their own projects and other projects brings forth a feeling of energy about the hackathon.

### Description

Currently, the release is: https://hackathons.gitcoin.co/grow-ethereum/results/, in order to show the status of submitted projects.

Are there other ideas to increase the liveliness of hackathons?

### Current Behavior

The template exists, but we want to ensure that the results page is updated with projects that have been submitted, and sponsors can easily find out and access the results page.

### Expected Behavior

The results page of every hackathon is the central location that sponsors go to see the results of each hackathon, for their issues and other issues.

### Definition of Done
TBD

### Data Requirements
- [ ] regular GA analytics on the results page

### Additional Information

**Comment by owocki** [comment]
idea mentioned on the call: embed gitcoin.co/actvity (but only hackathon activity) in the site

**Comment by alexvotofuture** [comment]
This also affects onboarding for new hackers. When they join a hackathon they often ask how to get involved in a team. Having projects all visible in one place, with contact info to get in touch with the team lead can help people jump in and get involved more quickly, which I hope will help lead to more submissions and participation from registrants.

**Comment by alexvotofuture** [comment]
In addition to helping sponsors see all projects underway this view additionally provides a way for hackers to find each other to form teams and collaborate during the hackathon.

The view can also showcase final submissions, as the "results page" currently does, and can feature winning submissions.

Some related tickets:
- #5038 (start/submit work form, with additional info on a project, ideally editable)
- #5321 (sponsors have had issues paying out because they don't know who is on a project's team, and there's no way to formally add team members when submitting so they will be paid out as well. The shared payout issue will be solved by Bounties v2 but teammates who work/submit together should also be reflected on project pages in this view. Question for this - who decides who is on the team and gets a cut of payout? The submitter?)

Sponsors should be able to filter by their org to see all project underway for their prizes. This will help them get information at a glance, rather than view submissions within each prize individually, and will provide more info than the activity feed within a prize bounty's page currently provides.

**Comment by frankchen07** [comment]
Thanks for the additional detail. I just wanted to jump in and make sure that we're solving for the minimal viable solution to one specific problem. While having members of the hackathon get started faster is a good thing, for this round, I'd like to focus us on making sure that the problem we're solving is on the sponsor side first. 

Octavio had some very good questions:

1. Where would this page physically exist and how would they get there?

2. Because it looks like someone actually has to "submit" their project on the page, how does that change the user journey? Does that mean in the beginning of the hackathon, things seem more dead?

3. What details do we have on our end to provide on the layout?

4. Octavio also mentioned UX / design on the page is necessary.

I'll address each of the points:

My approach is what's currently up is sufficient for an minimal viable solution for sponsors plus a few tweaks (filtering by their organization or something). This lets us get a minimal solution out to funders and start getting some validation testing (we find out if this is something that solves their problem) - this is point 4, and it answers:

* are sponsors pleased with having a central location to see their projects?
* does it help them in reviewing submissions and payout?

For point 2 &3 above, this may mean somehow finding an automatic way from the information that the contributor gives us to populate the project board. It may mean we have to submit them manually for the time being to have the information populated for the sponsor. This is where engineering will have slightly more constraints, but as long as we keep in mind that we're doing this as an iteration and as long as we have real information populated, the more important step is asking the sponsors for the right information.

For point 1, we could create a link to view the page, and only provide that link to sponsors. 

@alexvotofuture - octavio agrees with this MVP approach, and we wanted to get your thoughts on it as well. I think it's a tradeoff on moving forward with just enough data along with keeping an eye on solving the right problem.

**Comment by frankchen07** [comment]
The current implementation (in progress is similar to https://hackathons.gitcoin.co/grow-ethereum/results/)

This will be a different data model, but can easily connect to the bounty model and profiles model. 

The results page will be on a different data model, but it will be serviceable in admin. v1 will include the results page, and admin serviceability so we can populate the page as the hackathon proceeds and being to get feedback from sponsors.

People add to this page when they:

1. Start work (when they don't have all the data) - for the time being, because we have admin serviceability, we can add in information from the workplan and also the information on the bounty in order to populate the data.information from the modal, separate from the workplan

2. Submit work (when they have more data) - same as the above, just a different timepoint.

The second stage is to have modal popups asking for hackathon project information when users start and submit work in order to capture the additional information automatically with as little manual intervention on the admin side.

With regards to these modal popups, they are to be discussed and designed with @willsputra to figure out the correct journey and user experience.

Because this will be it's own data model, @frankchen07 can set up views to capture which fields are empty and which need updating for easier manual testing in its first stages.

3. Last question to think about - where do we want to link this page? Under the hackathons tab?

thanks to @octavioamu for the hard work on this!

**Comment by octavioamu** [comment]
closing as solved
