### ISSUE TITLE
As a user of Gitcoin, the top nav on hackathons.gitcoin.co doesn't match the top nav on gitcoin.co, which is an inconsistent experience

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5323]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user of gitcoin, i want the top nav to be updated on hackathons.gitcoin.co to match gitcoin.co top nav so i have a consistent experience

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
consistent experience

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
no black top nav on hackathons.gitcoin.co

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
this top nav is replicated over there http://bits.owocki.com/4ed95941eba5/Screen%20Shot%202019-10-16%20at%202.52.13%20AM.png
and it works on mobile as well

**Comment by alexvotofuture** [comment]
We've been aiming to reduce the need for the hackathons.gitcoin domain, eventually moving everything to the hackathon product (currently the "prize explorer") on the gitcoin.co domain. If we succeed in doing this we can delete the hackathons.gitcoin domain and won't need to match nav bars.

**Comment by owocki** [comment]
> We've been aiming to reduce the need for the hackathons.gitcoin domain, eventually moving everything to the hackathon product (currently the "prize explorer") on the gitcoin.co domain for UX, tracking, and SEO purposes.

i am concerned that this course of action will lead to the engineering team being a blocker for simple content/copy updates.. self reliance is one of our stated values ( gitcoin.co/mission ) after all.. is there a plan to avoid that?

to be clear; im not veto-ing or anything... just wondering if this was a consideration made..

**Comment by octavioamu** [comment]
Closing this as there is not nav today for general users as they just are able to see landing pages.
