### ISSUE TITLE
Grant Creation has not worked

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#5340]
**Describe the bug**
Hey guys. I have created/applied for a Gitcoin Grant concerning [Rotki](https://github.com/rotkehlchenio/rotkehlchen/) before Devcon 5. I was told by Gitcoin people both in Twitter and in Devcon that the Grant is approved but I don't see it in "My Grants" or in the available Grants at all.

**To Reproduce**
I don't know if this is reproducible. I could try to apply again but then this would not hep with figuring out what is wrong. In the original case of what I did is simply applied for a Grant, was told it's approved but it's nowhere to be seen.

**Expected behavior**
See the grant in the "My Created Grants" page

**Screenshots**
![2019-10-16-182403_410x153_scrot](https://user-images.githubusercontent.com/1658405/67139407-301ca580-f250-11e9-8e8c-f07ad71a43ad.png)

**Desktop (please complete the following information):**

- OS: Archlinux
- Browser: Brave
- Browser Version: Version 0.67.124 Chromium: 76.0.3809.100 (Official Build) unknown (64-bit)

**Comment by owocki** [comment]
do you have a txid for the grant you created? do you recall the title @LefterisJP ?

**Comment by LefterisJP** [comment]
The title included "Rotki" but not sure exactly what it was. It was quite some time ago. How can I see a txid?

**Comment by owocki** [comment]
txid is usually in your browser wallet (metamask)...

**Comment by LefterisJP** [comment]
Aha so an on-chain transaction happens even for a grant creation? I was under the impression that it first got approved by you guys.

That's strange. I recall no transaction being sent from metamask when I applied for the grant.

Perhaps at this point it's best if I try again from scratch.

**Comment by LefterisJP** [comment]
Strange ... this time it seems to have worked fine: https://gitcoin.co/grants/149/rotki

It could have had something to do with me using Brave with shields up back then. That could have somehow messed with metamask and made me see no pop-up and assume you guys check the grants manually.
