### ISSUE TITLE
Unable to submit faucet request

### ISSUE THREAD

**Issue by Oraxle** [gitcoinco/web#5341]
Whenever I try to file a faucet request it comes back saying "Something went wrong submitting your request "

Regards

**Comment by thelostone-mc** [comment]
Seems to be working fine !
Could you provide more context + screenshot of what you did ?

<img width="611" alt="Screenshot 2019-10-20 at 3 39 30 AM" src="https://user-images.githubusercontent.com/5358146/67156982-3e6bcf80-f2eb-11e9-8bff-edb90e4c97c8.png">

**Comment by owocki** [comment]
@Oraxle please fill out the issue in the bug report template https://github.com/gitcoinco/web/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by youdra** [comment]
HI, I'm coming across the same issue, can you please help? ty!
