### ISSUE TITLE
As a hackathon sponsor, the administrative actions on the issue details page aren't completely clear.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5347]
### User Story

As a hackathon sponsor, the administrative actions on the issue details page aren't completely clear.

### Why Is this Needed

Zach from Consensys Labs found the information hierarchy on the  administrative section of Gitcoin Issue details on the hackathon bounty a bit confusing.

### Description

1. Under funder actions, the red "cancel bounty" button shows first and stands out, the sponsors almost clicked it by accident. There should be a more obvious information hierarchy here (most desirable action as the first option and least desirable option the last option)

2. Sponsors who are signed in to different metamask addresses that are not the funding address can’t see their issues or funder buttons even when logged in to the correct Gitcoin account. It's not clear they need to switch wallets. Currently, theres a ‘switch to xyz metamask address’ module on the bounty detail page, however, it wasn't entirely clear. Possible solution, maybe just add to the existing message "switch to [address] to payout and access admin controls"

### Current Behavior

information hierarchy and MM switching isn't clear

![issuedetailscurrent](https://user-images.githubusercontent.com/19514207/67684482-3b00d400-f9ce-11e9-9108-4f88d5edee08.jpg)

### Expected Behavior

proper information hierarchy for admin buttons, and clear-er MM switching

### Definition of Done
- [ ] information hierarchy for admin buttons
- [ ] clear-er MM switching

**Comment by willsputra** [comment]
> Under funder actions, the red "cancel bounty" button shows first and stands out, the sponsors almost clicked it by accident. There should be a more obvious information hierarchy here (most desirable action as the first option and least desirable option the last option)

The current issue details is crowded with buttons, I wonder if we could put less-often-used bounty settings stuff under a 'Bounty Settings' dropdown.

and as a funder, I probably won't need the 'Contribute' button since I can edit the bounty details directly.


![issuedetailsadmin](https://user-images.githubusercontent.com/19514207/67684210-b4e48d80-f9cd-11e9-87e5-2e37db8a6f25.jpg)

**Comment by willsputra** [comment]
> 2. Sponsors who are signed in to different metamask addresses that are not the funding address can’t see their issues or funder buttons even when logged in to the correct Gitcoin account. It's not clear they need to switch wallets. Currently, theres a ‘switch to xyz metamask address’ module on the bounty detail page, however, it wasn't entirely clear. Possible solution, maybe just add to the existing message "switch to [address] to payout and access admin controls"

The current message ("Ready to Pay? Set your MetaMask to this address!") seems pretty clear. Maybe we could move it nearer to the admin buttons to make it more obvious.

![issuedetailsadmin](https://user-images.githubusercontent.com/19514207/67687968-11e34200-f9d4-11e9-9dfb-a9aa91de9410.jpg)

**Comment by frankchen07** [comment]
like the condensed view - only feedback here is making sure that "bounty settings" conveys it well vs "bounty options" or "more options"

easy move for the admin address could work as a useful stopgap. what's your opinion on disallowing the button to go anywhere until the address is set, or does that complicate the technical complexity?

**Comment by frankchen07** [comment]
@willsputra 

1. to think about whether or not to reveal extend expiration 

2. are there changes to the contributor view for the github issue details? (shall we change the button layout to match the funder's view?)

3. clean up the three "states" of login and which buttons are shown

4. do we want another button type (greyed out payout?)

**Comment by willsputra** [comment]
@thelostone-mc @frankchen07 

three states:
![3states](https://user-images.githubusercontent.com/19514207/68641385-9fcb3b00-0545-11ea-8ae5-60ae648a16e6.jpg)

decided to make our button styles consistent too while we're at it:
![button](https://user-images.githubusercontent.com/19514207/68641400-b07bb100-0545-11ea-9dad-f2f394db6f8b.jpg)
