### ISSUE TITLE
When clicking a referred user on Gitcoin quests, it redirects to a wrong path

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5350]
**Describe the bug**

When you try to click on a profile of a referred user it redirects to gitcoin.co/quests/<Profile_name> instead of https://gitcoin.co/profile/<Profile_Name> thus you get a 404 error

**To Reproduce**

Click on a referred user on the gitcoin quests page and see the wrong path specified:
![image](https://user-images.githubusercontent.com/50027175/67261082-4d937e80-f49f-11e9-95ee-d8363e58d198.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
6112048462966cbe2679943cfd8357c792c4a0b8
