### ISSUE TITLE
Store txid's off of the bounty object

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#537]
On the bounty object, please add a json blob called `txids`, and in it, record all txids associated with the bounty, and what action that txid performed on it.. example blob:

```
txids = {
   'submit': [ '0xef4277ebbb8efb937970b2d0df121d3a134a9e576293ca3d50c4e662f3b854e1' ],
   'kill': [ ],
   'accept': [ '0xef4277ebbb8efb937970b2d0df121d3a134a9e576293ca3d50c4e662f3b854e1' ],
   'fulfill': [ '0xef4277ebbb8efb937970b2d0df121d3a134a9e576293ca3d50c4e662f3b854e1', '0xef4277ebbb8efb937970b2d0df121d3a134a9e576293ca3d50c4e662f3b854e1' ],
}
```

**Comment by owocki** [comment]
This will need to be added to the `sync_web3` management command

**Comment by kuhnchris** [comment]
Is this still relevant? also throwing in txids is pointless as it can be replaced by the user. (e.a. gas up)
