### ISSUE TITLE
As a gitcoin user I would like to save the state of gitcoin quests

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5372]
**Describe the bug**

RIght now when I create a quest and for accident close the tab, the changes get lost

**To Reproduce**

Create a new quests, insert some data and close the tab

**Expected behavior**

To either alert me that I am closing the tab or saving the changes so I can continue working on it afterwards

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
i think that saving data upon entry to localstorage should probably be the fix here..
