### ISSUE TITLE
When a Gitcoin quest has been created, the link provided is wrong

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5377]
**Describe the bug**

The link provided in the top bar is wrong:
![image](https://user-images.githubusercontent.com/50027175/67519442-2a3b2000-f6a7-11e9-9318-fbfd22489f3a.png)
It has an additional 'https://gitcoin.co'.

**To Reproduce**

Create a gitcoin quest and look at the top bar

**Expected behavior**

Return me a correct link like this(https://gitcoin.co/quests/29/fear-the-openzeppelin-security
) instead of this one: `https://gitcoin.cohttps://gitcoin.co/quests/29/fear-the-openzeppelin-security`

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Browser Version: Version 77.0.3865.120

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
6f5b2d8859e4071421d67578e06499c68943e4b6
