### ISSUE TITLE
As a user, I don't want to see github comment blocks in the bounty detail/description

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#538]
##### Description
The bounty details page currently displays comment blocks in the rendered github issue description.  We should be parsing these out.

##### Possible Implementation
On bounty detail fetching and syncing, we should be cleaning the response to not carry over github comments.  Example:  

```
<!---
This
 -->
```

**Comment by thelostone-mc** [comment]
@mbeacom would it make sense to integrate the maekdown language into our input fields ?
That way everything is ported without any trouble!

A quick google might give us a few good markdown parsers like [remarkable](https://github.com/jonschlinkert/remarkable)

What do you think @Korridzy ?

**Comment by Korridzy** [comment]
Sorry for disappearance. Now I'm back and implementing thelostone-mc's idea. Cause it's definitely better.

**Comment by mbeacom** [comment]
@Korridzy Thanks for the update! Anything I can do to help you with this?

**Comment by rahulpat** [comment]
@mbeacom what's the update on this ? Interested in taking this on.

**Comment by thelostone-mc** [comment]
@rahulpat Ah this has been taken care of ^_^
