### ISSUE TITLE
as a user who just logged in and got hit with 4 modals, im feeling very overwhelmed

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5380]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user who just logged in and got hit with 4 modals, im feeling very overwhelmed

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
bug

### Current Behavior
[comment]: # (Describe what actually happened.)
1. go incognito
2. login
3. this is what you see
![Screen Recording 2019-10-24 at 04 58 PM](https://user-images.githubusercontent.com/513929/67531356-9c980a00-f67f-11e9-9581-087c212dfe5e.gif)
 
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
only one of these modals should appear per page

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

**Comment by frankchen07** [comment]
Here are my thoughts:

1. Hackathons: I think this is fine, it's quite un-intrusive, and it's a nice reminder that it's going on
2. How can we make this page better for you: From Hotjar, we can turn it off. I haven't really seen feedback come in from there.
3. Privacy policy modal: Is it possible to just have that text in the Privacy Policy itself? They can click there if they want.
4. Cookies disclaimer we can keep, as that is also relatively unintrusive and is a GDPR requirement
5. Product updates, we can decrease the frequency to just once per user (once they see it, it's gone, until the next one - is this possible?)

That should leave it to just product updates once, and the top & bottom slim banners.

**Comment by willsputra** [comment]
> Here are my thoughts:
> 
> 1. Hackathons: I think this is fine, it's quite un-intrusive, and it's a nice reminder that it's going on
Agreed.
> 2. How can we make this page better for you: From Hotjar, we can turn it off. I haven't really seen feedback come in from there.
I wonder if we can put this only on pages where a user might experience difficulties, for example: explorer, issue details, advanced payout... So this acts sort of like an 'emergency button' if a user needs help.
> 3. Privacy policy modal: Is it possible to just have that text in the Privacy Policy itself? They can click there if they want.
Agreed. If it's really important, maybe we can put the tl;dr on the Cookies Disclaimer footer too.
> 4. Cookies disclaimer we can keep, as that is also relatively unintrusive and is a GDPR requirement
Agreed.
> 5. Product updates, we can decrease the frequency to just once per user (once they see it, it's gone, until the next one - is this possible?)
I think this is the current behavior. cc @octavioamu 
> 
> That should leave it to just product updates once, and the top & bottom slim banners.

**Comment by owocki** [comment]
agree with having hotjar turned off.. does anyone have the login to do so?  or should we just remove the JS?

> So this acts sort of like an 'emergency button' if a user needs help.

i've been considering adding a "HALP" button to the top navbar that takes users to https://github.com/gitcoinco/web/issues/new/choose

> Agreed. If it's really important, maybe we can put the tl;dr on the Cookies Disclaimer footer too.

im in favor of this too.

@fronk @octavioamu @danlipert should i put this into an upcoming sprint or bounty it?

**Comment by thelostone-mc** [comment]
@owocki / @willsputra / @frankchen07 turned off the hotstar

<img width="1405" alt="Screenshot 2019-10-26 at 10 25 09 AM" src="https://user-images.githubusercontent.com/5358146/67621985-f234f980-f7da-11e9-8736-50810aca640d.png">
