### ISSUE TITLE
Start Work fades screen but does nothing

### ISSUE THREAD

**Issue by dangeross** [gitcoinco/web#5384]
When looking at an issue and wanting to start work, pressing the Start Work button does nothing. It only fades the view like a modal should open. An error is returned in the DevTools console (see screenshot)

**To reproduce** (tested on Desktop Brave & Chrome):
- Go to: https://gitcoin.co/issue/rsksmart/rskj/1043/3576
- Press 'Start Work'

![Screenshot_2019-10-25_at_09_36_20](https://user-images.githubusercontent.com/551697/67552297-10cbbf80-f70b-11e9-952d-a32bd51eaa87.png)

**Comment by owocki** [comment]
https://sentry.io/organizations/gitcoin/issues/1281337579/?project=1398424&query=is%3Aunresolved+modal&statsPeriod=14d&utc=true

```
'Profile' object has no attribute 'hackathons'
```

**Comment by owocki** [comment]
cc @octavioamu looks like this is ur code https://github.com/gitcoinco/web/blame/master/app/dashboard/views.py#L231

**Comment by octavioamu** [comment]
Checking

**Comment by octavioamu** [comment]
yes we changed the model recently profile.hackathons isn't valid anymore, making a hotfix right now

**Comment by octavioamu** [comment]
@dangeross @owocki should be fixed now. Please @dangeross confirm if now is working.
Thanks for the report!

**Comment by dangeross** [comment]
Looking good. Works for me now
