### ISSUE TITLE
Can't login with github account

### ISSUE THREAD

**Issue by TripleSpeeder** [gitcoinco/web#5385]
**Describe the bug**
I always log in to gitcoin with my Github account via OAUTH. Since sometime yesterday any attempt to log in ends in the Error 500 page of gitcoin.

**To Reproduce**
1. Make sure to be logged out
2. Click login button
3. Error 500 page is rendered

Attempt to workaround: 
1. On my github profile i revoked all gitcoin access rights.
2. Click Login on gitcoin.co
3. Approve requested access from gitcoin
4. Again end up in error 500 page :-(

**Expected behavior**
Login should be working fine :)

**Desktop (please complete the following information):**

- OS: Current Arch Linux 
- Browser: Chromium
- Browser Version: 78.0.3904.70 (64-Bit)

**Additional context**
I think this started yesterday when there apparently were changes to the required OAUTH permissions. When logging in yesterday, gitcoin requested new permissions (full control over public and private repos). I initially allowed this, but shortly after revoked as i do not feel comfortable with a thirdparty site having full repo access. 
Since this morning the requested permissions apparently are reduced to:
- Access public repositories
- Read org and team membership, read org projects
- Read all user profile data
- Access user email addresses (read-only)

which i'm happy to grant, but still can't login anymore.

**Comment by TripleSpeeder** [comment]
I asked in slack #community-general channel, at at least one user was seeing the exact same issue there.

**Comment by Solexplorer** [comment]
I confirm the issue from my part, tried to login from incognito mode and received error 500

**Comment by octavioamu** [comment]
Thanks for reporting. Yesterday we changed to full access as needed for a new feature we are working on. 
Since there was people complaining we decided to remove private repos from scope. Login out and login in should solve the problem. Can you confirm if now is solved or still with problems? Also what is your profile on gitcoin?
Thanks

**Comment by octavioamu** [comment]
Also if you keep getting problems try to revoke the app https://github.com/settings/connections/applications/ec7a189f64779a235aa6 on gh side, logout to gitcoin and login again.

**Comment by TripleSpeeder** [comment]
Unfortunately it is not working. I revoked all permissions for gitcoin and tried to login again. On github everything is looking good, the required permissions are created again. But on gitcoin i still end up at the Error 500 page.
This is my profile on gitcoin: https://gitcoin.co/profile/triplespeeder

**Comment by octavioamu** [comment]
@PumpkingWok are you also having it? I see some sentry errors

**Comment by octavioamu** [comment]
Can you guys retry now?

**Comment by PumpkingWok** [comment]
Hi @octavioamu,
I have just tried and it works now for me, thanks a lot !!!

**Comment by octavioamu** [comment]
Yay, sorry was my mistake.

**Comment by octavioamu** [comment]
we are going to invalidate sessions so probably will need to login again. Please let me know if someone have issues.

**Comment by TripleSpeeder** [comment]
Can confirm login is working again! Thanks for the quick fix :+1:

**Comment by octavioamu** [comment]
Yay, feel free to reopen if you get any related issue.
