### ISSUE TITLE
XSS protection causes tags in issue explorer to be inproperly escaped

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#5387]
**Describe the bug**
C#, C++ and anything else with "special characters" is getting stripped.

**To Reproduce**
dashboard->bounties->load more bounties->redirection to explorer

**Expected behavior**
C# and C++ being honored

**Screenshots**
![grafik](https://user-images.githubusercontent.com/761911/67588489-88730c00-f756-11e9-8d4c-a095b35f34e3.png)

![grafik](https://user-images.githubusercontent.com/761911/67588483-8446ee80-f756-11e9-86c0-97ce3905060d.png)

**Comment by danlipert** [comment]
@frankchen07 we should get this in the next sprint
