### ISSUE TITLE
Trying a DAI payout ended up making the issue canceled

### ISSUE THREAD

**Issue by knocte** [gitcoinco/web#5390]
> If it is general support you need, reach out to us at gitcoin.co/slack

Sorry I don't want to use slack.

**Describe the bug**
When trying to click on Payout, I was redirected to a page where I had to choose between Basic and Advanced payout, but I couldn't click on "Basic", it was disabled somehow. So then I tried to click on "Advanced", indicated to pay just one developer (the only one that was marked as approved), and then I clicked "Pay", MetaMask popped up to sign, and then... the result is that the bounty got canceled, wtf?

**To Reproduce**
1. Click Payout.
2. See that only Advanced Payout is available (first bug?)
3. Configure only 1 dev to be paid. Click Pay.

**Expected behavior**
Payout should be sent to dev.

**Current behavior**
Bounty got cancelled.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave
- Browser Version: 0.69.135

**Additional context**
The issue was https://gitcoin.co/issue/nblockchain/DotNetEssentials/1/3540

**Comment by owocki** [comment]
> it was disabled somehow

if theres no submissions you cant use basic payout 

> nd then I clicked "Pay", MetaMask popped up to sign, and then... the result is that the bounty got canceled, wtf?

this info modal on the page details the what/why this happened http://bits.owocki.com/206288e60b2b/Screen%20Shot%202019-10-27%20at%209.46.12%20PM.png

**Comment by knocte** [comment]
> if theres no submissions you cant use basic payout bc theres no submission to accept

I see. Well, there should be a better UX for this case, the submission happened offline between the worker and the funder(me).

Is there a way I can reinstate the bounty on this issue (without paying gitcoin's fee twice), so that I can try a Payout again?

**Comment by owocki** [comment]
there is not; but i can send you a refund..  remind me your tx id?  i can issue refund from there..

**Comment by knocte** [comment]
> remind me your tx id?

Not sure which tx you mean. Anyway I think the last transactions of my MetaMask wallet are all related to this bounty: https://etherscan.io/address/0xeab801021a22c62c4c08471dd518c27b24039d8b

> i can issue refund from there..

After that I can re-post a bounty on top of the cancelled issue?

**Comment by owocki** [comment]
heres your refund! https://etherscan.io/tx/0x3df938e49b65127edfd3e6f277c06c4664f4011d8f8ef34199dad9ef0c4c99a9

> After that I can re-post a bounty on top of the cancelled issue?

i'd recommend creating a new github issue with a clean comment history... its a small pain to copy it over.. but it can save time down the line
