### ISSUE TITLE
Gitcoin user is not able to see his profile

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5392]
**Describe the bug**

A gitcoin user has noticed that he's not able to access his profile: https://gitcoin.co/profile/nionis.
He is not able to access his profile even using:  https://gitcoin.co/nionis.
I know he is registered to Gitcoin because if I go to referred users I can see him:
![image](https://user-images.githubusercontent.com/50027175/67615963-f78e4600-f7d2-11e9-80ff-4daade00f2a1.png)

**To Reproduce**

Go to: https://gitcoin.co/profile/nionis or https://gitcoin.co/nionis

**Expected behavior**

To be able to see his profile

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Mozilla
- Browser Version: 69.0.3

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by nionis** [comment]
thank you @Solexplorer for opening this issue, at the moment both urls work even when I clear cache

**Comment by Solexplorer** [comment]
@nionis maybe you wanted to say they don't work? 😉

**Comment by nionis** [comment]
@Solexplorer works for me, it might be an issue occurring on some people some times. In my experience this looks like an issue with the server cluster, maybe some of the servers are failing.

**Comment by Solexplorer** [comment]
Strange... It doesn't work on my end even if I clear the cache

**Comment by nionis** [comment]
I had "Hide my profile altogether" toggled on!
sorry @Solexplorer haha

**Comment by Solexplorer** [comment]
@nionis Np! 
Since the issue was not gitcoin's fault but the user's fault, I'm going to close this issue.
@owocki What do you think about having a top bar saying that the profile is private ?

**Comment by owocki** [comment]
> @owocki What do you think about having a top bar saying that the profile is private ?

thats a great idea! we could keep it super simple :)  any interest in throwing up a PR? i can tip ya some ETH

**Comment by Solexplorer** [comment]
A [user](https://gitcoin.co/ashleyoyt) has expressed his interest in issuing a PR.
I wasn't able as I keep having issues with the local web repo 😢

**Comment by AshleyOyt** [comment]
Hey guys, I started working on this. Thanks!

**Comment by AshleyOyt** [comment]
hey @owocki , this is what I designed. Any feedback you have would be much appreciated 😃 
![Gitcion](https://user-images.githubusercontent.com/40966461/67669585-e122ee80-f97a-11e9-8408-c79de4c28c0b.png)

**Comment by Solexplorer** [comment]
@AshleyOyt Looks good to me, does it replicate to every page or just the homepage ?

**Comment by AshleyOyt** [comment]
@Solexplorer I didnt implement it yet, I was trying out some designs in the browser to make sure my design fits with the theme of the page. I plan to implement it in a way where it replicates to every page, that way the user doesnt forget that their profile is hidden.
