### ISSUE TITLE
A bounty has open status even if the bounty was paid

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5398]
**Describe the bug**

Check this [bounty](https://gitcoin.co/issue/ethereum/solidity/1802/474), it was created a year ago and the work was submitted and done but it still shows up open somehow.

**To Reproduce**

Go to the link and look at the status of the bounty

**Expected behavior**

Bounty should have status: "Work Done"

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
its status has been overriden to 'open' by @vs77bb

**Comment by Solexplorer** [comment]
oopsie
