### ISSUE TITLE
gitcoin.co requests dangerous permissions from GitHub

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#5399]
**Describe the bug**
`gitcoin.co` want write access to all public repos just for the login.

![image](https://user-images.githubusercontent.com/8781107/67632597-80ca7900-f8b6-11e9-8c88-8f0778821a96.png)

**To Reproduce**
1. Go https://gitcoin.co/requests
2. Press 
![image](https://user-images.githubusercontent.com/8781107/67632607-ab1c3680-f8b6-11e9-878a-463c92f97733.png)

**Expected behavior**

Request bare minimal info required for login.

**Comment by owocki** [comment]
we just put a fix in for this..

**Comment by abitrolly** [comment]
Can not see it. https://github.com/gitcoinco/web/commits/master

**Comment by abitrolly** [comment]
It still asks for full permissions.

**Comment by owocki** [comment]
@octavioamu put a fix in for this this morning..

**Comment by octavioamu** [comment]
https://github.com/gitcoinco/web/commit/6e7690e28785332989ea5fbeb607f525dd8ba475

**Comment by abitrolly** [comment]
Why gitcoin.co needs to know about my repos for login?

Is it possible to request additional permissions only when required?

**Comment by octavioamu** [comment]
Shouldn't ask you anymore for those permissions

**Comment by abitrolly** [comment]
Is it possible to request those permission on the sharing management page where they are actual?

**Comment by thelostone-mc** [comment]
> Why gitcoin.co needs to know about my repos for login?


^ @abitrolly so that was a mistake at our end ! We were building out organisation mgmt into gitcoin and added the extra permissions which weren't really needed !

Like @octavioamu stated -> we removed those after realizing it was not needed!
Sorry about that ^_^

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/68270672-2330ec00-006f-11ea-8271-52909ca98126.png)

Why it still needs access to organization membership and the list of private projects??

**Comment by octavioamu** [comment]
@abitrolly we just need read orgs actually to be able to manage teams of organisations and github scopes are not very flexible https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

**Comment by abitrolly** [comment]
@octavioamu why `public_repo` is not enough?

**Comment by octavioamu** [comment]
@abitrolly we are not currently asking for repo scope private or public, just the org. ['read:user', 'user:email', 'read:org']

**Comment by abitrolly** [comment]
`public_repo` includes `collaborators` - is it not the same?

> That includes read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses for public repositories and organizations.

**Comment by thelostone-mc** [comment]
@abitrolly 
Permissions we are requesting : https://github.com/gitcoinco/web/blob/61bbb8de729dcedd7a27adbc1af38f526ab77ab2/app/app/settings.py#L535

What are you suggesting ?

**Comment by abitrolly** [comment]
I'd suggest documenting how gitcoin.co is managing teams of organisations and what is why collaborators returned by `public_repo` are not the same.

**Comment by octavioamu** [comment]
Closing this as we are not longer using any of the permissions discussed here or doing team managing. Feel free to reopen @abitrolly if you have any questions.
