### ISSUE TITLE
I am not able to find the file "token_dynamics" 

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5400]
**Describe the bug**

I am running locally the web repo but it seems that it doesn't find a [file called "token_dynamics"](https://github.com/gitcoinco/web/blob/9e3940a03b2530b6ccf5211468dcddc3519afc8d/app/dashboard/templates/onepager/send2.html#L28): `<script src="/dynamic/js/tokens_dynamic.js"></script>`

The error is happening in every page that requests that file an example is: `/tip/send/2`

**To Reproduce**

Run the web repo and go to localhost:8080/tip/send/2 and look at the console

**Expected behavior**

No error because of missing file

**Screenshots**

![image](https://user-images.githubusercontent.com/50027175/67632644-71dbca80-f8a6-11e9-9dc7-2010e970c8d9.png)
Missing file ☝️ 

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chromium
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
do you have this line in your URLs.py https://github.com/gitcoinco/web/blob/master/app/app/urls.py#L317

**Comment by Solexplorer** [comment]
I am actually having issues with the local web repo, can anyone tell me if it's having issues with the web repo running locally with docker ?

**Comment by owocki** [comment]
can you post a stack trace of http://localhost:8000/dynamic/js/tokens_dynamic.js pls @Solexplorer ??
