### ISSUE TITLE
Build your avatar in profile redirect to wrong url

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5401]
**Describe the bug**

When I click to build your avatar in the profile section, it redirects to `https://gitcoin.co/onboard/contributor?csrfmiddlewaretoken=<TOKEN>&steps=avatar` , the correct one should be `https://gitcoin.co/onboard/contributor/?csrfmiddlewaretoken=<TOKEN>&steps=avatar`

**To Reproduce**

Go to the profile section and click "build your avatar"

**Expected behavior**

To let me build your avatar

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chromium
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
I will provide the PR with the fix

**Comment by Solexplorer** [comment]
Update, it only happens here:
![image](https://user-images.githubusercontent.com/50027175/67656917-6eebe300-f955-11e9-8a40-3af9756fec7d.png)

**Comment by owocki** [comment]
try now? seems to be working

**Comment by Solexplorer** [comment]
Yup it's working now :)
