### ISSUE TITLE
Gitcoin bot posts reminders incorrectly

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5403]
**Describe the bug**

The gitcoin bot is posting incorrect reminders in this [bounty](https://github.com/kauri-io/Content/issues/85)

**To Reproduce**

Go to the [bounty](https://github.com/kauri-io/Content/issues/85) and look at the wrong posts

**Expected behavior**

Only one reminder instead of 4 reminders

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
it sends 4 reminders (1 per user) .. i agree that could be consolidated into 1 reminder for four users.. but only if each user has gone idle at the same time (or near the same time)

**Comment by Solexplorer** [comment]
I don't get it, the bot is reminding 2 users for 2 times at the same moment:
![image](https://user-images.githubusercontent.com/50027175/67655395-ba4fc280-f950-11e9-9659-7388c73eb2f8.png)

![image](https://user-images.githubusercontent.com/50027175/67655408-c3d92a80-f950-11e9-9d2c-70ec293cc341.png)
