### ISSUE TITLE
Dashboard has wrong data related to my profile

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5404]
**Describe the bug**

I have already submitted work to this bounty but in the dashboard I see that I still have a bounty in progress and I am able to submit work again(tested it and let me submit work again):
![image](https://user-images.githubusercontent.com/50027175/67639431-c5bed180-f8ef-11e9-9cba-1f5a0773dbc5.png)
While in the bounty page I see this: 
![image](https://user-images.githubusercontent.com/50027175/67639451-df601900-f8ef-11e9-8eb3-4435cf59ee00.png)
Which means that I have already submitted work.

**To Reproduce**

Don't know if it's reproducible

**Expected behavior**

Don't show that I have a bounty in progress if I have already submitted work

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by molecula451** [comment]
I can confirm this is happening. I facing this same issue right now. I have work submitted and it still shows I have submitted not any work

**Comment by owocki** [comment]
@molecula451 bounty link?

**Comment by molecula451** [comment]
@owocki I have work submitted on this bounty https://gitcoin.co/issue/validitycrypto/vldy.org/2/3645

It shows I have submitted any work.

![gitcoin](https://user-images.githubusercontent.com/41552663/68358006-8d887180-00ed-11ea-864a-d511c17e5965.png)

![0](https://user-images.githubusercontent.com/41552663/68358024-94af7f80-00ed-11ea-9a93-09d4e1b864ad.png)

**Comment by owocki** [comment]
@octavioamu any update whats up here?

@molecula451 this is with your @molecula451 gitcoin account right?

**Comment by molecula451** [comment]
@owocki Yes awesome Owocki!
