### ISSUE TITLE
Invalid application state preventing users from modifying Job Status

### ISSUE THREAD

**Issue by androolloyd** [gitcoinco/web#5405]
### Who
Users without 3d avatars and users who enter the Job Status update flow through Profile -> Resume -> edit this info
### What 
The user is pushed into the view without the correct context applied, if the user has not setup a 3d avatar, the user can get errors in their console regarding avatar options, furthermore, the view for editing the resume/job status section is not configured to actually generate requests to the backend as the "Done" button has an onClick event handler that just redirects the browser to the /profile endpoint ( onboard/?steps=job) is where it sends the user.

Once set there can be a race condition for `initPlacecomplete`, for setting the locations of where you might be willing to work from

### Why
There are 3 ways to view the "edit" job status section of the application, Manage Settings -> Job Status, Onboarding, Profile -> resume, each loading the same view but supplying a different set of underlying data. 

Onboarding when started from start to finish and Manage Settings are both seemingly working as intended.

**Comment by owocki** [comment]
good find!
