### ISSUE TITLE
As a Gitcoin user, Gitcoin suddenly needs write access to repos, which is intrusive - having opt-in screens when the scope of access is requested is more transparent.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5408]
### User Story

As a Gitcoin user, Gitcoin suddenly needs write access to repos, which is intrusive - having opt-in screens when the scope of access is requested is more transparent.

### Why Is this Needed

We respect the privacy and permissions for our users. It should be read-access only to public repositories.

### Description

The first version of this feature had an opt-in feature, but was removed in favor of simple logic. However, this means the scopes, when asked for, are quite intrusive. 

<img width="599" alt="Screen Shot 2019-10-28 at 11 02 07 AM" src="https://user-images.githubusercontent.com/7516920/67698713-13772080-f968-11e9-9ad8-afe483ad7a83.png">

### Current Behavior

read and write access

### Expected Behavior

ensure that we get explicit consent about public repo scope when a user accesses their settings

granular solution is to ask our users - via an opt-in experience:

<img width="1144" alt="Screenshot 2019-10-29 00 28 57" src="https://user-images.githubusercontent.com/7516920/67698731-225dd300-f968-11e9-9b4c-44aa9c6710d4.png">

### Definition of Done
TBD

**Comment by octavioamu** [comment]
New scopes 
![image](https://user-images.githubusercontent.com/1358093/67705937-b47cd000-f996-11e9-85d2-4b9530edac76.png)
