### ISSUE TITLE
as a new user, how do i update my github username on the funding/new page?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#542]
http://bits.owocki.com/003g3m2P3j2s/Screen%20Shot%202018-03-05%20at%206.53.33%20PM.png

the field is disabled... how do i update it?

(owocki here: i know the answer is to login with github.. but how would a new user know this?)

**Comment by owocki** [comment]
cc @PixelantDesign @KennethAshley

**Comment by PixelantDesign** [comment]
@owocki Great point.
A user would not know how to update this field in the current implementation. My recommendation would be to solve for this with light messaging via tooltip as part of Issue #429. https://github.com/gitcoinco/web/issues/429

**Comment by thelostone-mc** [comment]
Closing this out as the logged in user -> is who created the bounty
