### ISSUE TITLE
[DROP DEAD DATE: NOV 25th] As a user, I want to use the upgraded Multi Collateral Dai token and contracts, so I can continue to use a stablecoin on the Gitcoin platform.

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#5423]
### User Story

As a user, I want to use the upgraded Multi Collateral Dai token and contracts, so I can continue to use a stablecoin on the Gitcoin platform.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The DAI contract is being upgraded and we must support the new contract as the old one is being deprecated: https://github.com/makerdao/developerguides/blob/master/mcd/upgrading-to-multi-collateral-dai/upgrading-to-multi-collateral-dai.md

### Description

MIgration Plan: https://docs.google.com/document/d/1wAwVVPTQIR3LiZBMOgCfj1Maz781lgw-_JNKZK2z3G8/edit

### Current Behavior
[comment]: # (Describe what actually happened.)
DAI works

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
DAI still works on Nov 25th

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Announcement made regarding our upgrade dates
- Nov 18th: Rename DAI to SAI
- By Nov 25th: Deploy Multi-Collateral Dai

**Comment by StatusSceptre** [comment]
Just to upvote - I've migrated Status' bounty SAI to DAI and look forward to having the new token supported.

**Comment by danlipert** [comment]
@StatusSceptre nice! we'll have the new token ready sitewide on Monday
