### ISSUE TITLE
Technical SEO - Remove 404 errors caused by profile pages/

### ISSUE THREAD

**Issue by sharmi** [gitcoinco/web#5424]
**Describe the bug**
Accessing "https://gitcoin.co/profile/<username>" results in 404 errors. 

Too many 404 errors affect Site Authority.

**Expected behavior**
Urls that need authentication, like the one above, should be blocked in robots.txt

**Comment by octavioamu** [comment]
Hi!!
/profile is only for logged users if you are not logged you will redirected to another page. 
Are you getting 404 when logged ?
