### ISSUE TITLE
Gitcoin Quest Kudos images not rendering

### ISSUE THREAD

**Issue by santteegt** [gitcoinco/web#5429]
Hi,

Seems that some kudos illustrations cannot be rendered (broken URL?) both in my [Gitcoin profile](https://gitcoin.co/santteegt/kudos) and within [OpenSea](https://opensea.io/accounts/0x224aba5d489675a7bd3ce07786fada466b46fa0f). If you take a look at the latter link, the ones that cannot be rendered in OpenSea aren't being shown in my profile

**Comment by owocki** [comment]
which ones ? they seem to be loading to me

**Comment by santteegt** [comment]
No 6035 for example, is a kudos I've earned on the `Welcome to Web 3` quest

![image](https://user-images.githubusercontent.com/926341/67901041-c5af1380-fb33-11e9-8804-0199dfde49e1.png)

**Comment by owocki** [comment]
hmmm ok; i dont see any kudos that arent rendering on your gitcoin profile  (the 'web3 advocate one which you note you won for beating 'welcome to web3', for example is rendering fine' http://bits.owocki.com/6ac9fdb69422/Screen%20Shot%202019-10-31%20at%2010.23.29%20AM.png ) - will have to have a chat with the open sea guys and see whats up on their end..
