### ISSUE TITLE
Gitcoin issue stuck on re-load

### ISSUE THREAD

**Issue by notadamking** [gitcoinco/web#5443]
https://gitcoin.co/issue/notadamking/tensortrade/41/3554

I payed out the bounty for the issue, and now the issue won't stop loading/refreshing.

**Comment by owocki** [comment]
i cant reproduce.. can you please fill out the bug issue template? https://github.com/gitcoinco/web/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by thelostone-mc** [comment]
@notadamking looks like the transaction took a bit of time to go through which is why the loading screen probably was persistent 🤔 
The reloading is ugly. Need to figure out a nicer way to handle it

**Comment by molecula451** [comment]
The realoding it's facing some issue. When you just submit a work. It still showing your 'update it's being posted on the ETH network' and it is an unstoppable loop

**Comment by thelostone-mc** [comment]
@molecula451 could you share the bounty where this happens?

**Comment by notadamking** [comment]
@thelostone-mc it has happened to me multiple times on multiple different issues. It resolves itself within an hour usually.

Possibly related to blockchain confirmations, though it definitely takes longer than the initial Metamask confirmation to resolve itself.
