### ISSUE TITLE
Solve a specific quest to be able to apply on a bounty

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#5446]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a hunter I want to be able to pick one or more quests a contributor need to solve first to be able to apply to work on my bounty. So I can be more sure people know about what Im asking for.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Is a good way to confirm people know about some topic on the bounty. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Doesn't exist an association between bounty and quests 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Having a bounty related to one or many quests. 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Having a new section on "new bounty"  with quests I can search and add to my bounty.
Being able to edit add/remove quests from my bounty
Hunters need to solve the queries to be able to "start work"

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by frankchen07** [comment]
love this idea, talked about it previously with ivo too
