### ISSUE TITLE
Bug in the amount of DAI contributed to a project

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5448]
**Describe the bug**

So I decided to test a grant contribution with the minimum amount allowed(0.001 DAI/daily) but the confirmation email of the grant contribution is wrong about the contribution amount.

See the screenshot below.

**To Reproduce**

Contribute to a random grant with 0.001 DAI

**Expected behavior**

To show me the correct amount in the email.

**Screenshots**

![immagine](https://user-images.githubusercontent.com/50027175/68206295-b49b5200-ffcc-11e9-97e6-4e6159278ab5.png)
![immagine](https://user-images.githubusercontent.com/50027175/68206313-bcf38d00-ffcc-11e9-830a-ead0e098293d.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Thanks for that !
^ Fix is ready over at https://github.com/gitcoinco/web/pull/5452
