### ISSUE TITLE
As a Gitcoin operator, we need to migrate certain Metamask calls

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5462]
### User Story

As a Gitcoin operator, we need to migrate certain Metamask calls.

### Why Is this Needed

So Gitcoin doesn't break.

### Description

Summary: https://medium.com/metamask/deprecating-synchronous-provider-methods-82f0edbc874b

Starting Monday, December 16, 2019, all MetaMask provider send() calls will behave asynchronously, just as they do under the hood. They will return Promises, which will resolve directly to RPC method results. We encourage you to take a look at EIP 1102 and EIP 1193 to learn about the new APIs available to you. The new ethereum.send will be live for all other methods in the next couple of weeks, so keep an eye out for that!

owocki: thought about it - an architecture that wont be super complex here: we can just call `web3.eth.getcoinbase` once in the `base.js` code that figures out what network ur on, and store it on `document.coinbase`. This prevents us form having to update code EVERYWHERE on the site.

document for migration: https://docs.google.com/document/d/1eJSV9BQSxBvW2DlmVsJvSA8cIYhBypgN24Ggj4gmTcM/edit#heading=h.5n5wzq6ucg3

### Current Behavior

non-updated code

### Expected Behavior

ensure that the returned results from the updated asynchronous calls don't break calls with the old codebase

### Definition of Done
TBD

**Comment by danlipert** [comment]
The MetaMask update was pushed back 2 weeks, so I'll move this to the next sprint

**Comment by danlipert** [comment]
The MetaMask update has now been pushed back to "Q1 2020"
