### ISSUE TITLE
Can't select an enemy Kudos when creating a new Quest

### ISSUE THREAD

**Issue by rasliche** [gitcoinco/web#5476]
**Describe the bug**

There are no options in the "Enemy Kudos" select form field.

**To Reproduce**

Visit: https://gitcoin.co/quests/new

Try to select an Enemy Kudos

**Expected behavior**

Should be able to select an Enemy Kudos

**Screenshots**

It's an empty select

**Desktop (please complete the following information):**

- OS: OS X 10.13.6
- Browser: Brave
- Browser Version: 0.70.121

**Additional context**

Brave Shields are up, but it doesn't appear to be blocking anything else.

**Comment by owocki** [comment]
7220c813fa604614d03001b73674097fa3970c61 should fix this

**Comment by owocki** [comment]
try now! https://gitcoin.co/quests/new
