### ISSUE TITLE
As a hackathon sponsor, when I market my Gitcoin hackathon bounties, I want to have links that lead directly to my bounties and submissions.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5483]
### User Story

As a hackathon sponsor, when I market my Gitcoin hackathon bounties, I want to have links that lead directly to my bounties and submissions.

### Why Is this Needed

1. Sponsors would like an easily accessible link that leads hackers to their set of bounties on our explorer.

2. On the same coin, sponsors would like filtering of the hackathon results page by their submissions/projects, and be able to share that search instance (generate a new url from the search).

### Description

1. Connor runs Codefund ads specific to sponsors ("Aave has $15k in crypto up for grabs for work on DeFI!") and Ihecan only link to the prize explorer as a whole, or one specific Aave challenge, not all of Aave's challenges/prizes. Being able to link to the page already filtered, showing Aaves 4 bounties would be a great way to share the prizes. The same issue arises when sponsors want to promote their bounties on twitter, through email, etc.

2. Allow filtering projects on the project results page by sponsor, so each individual sponsor can specifically view the projects/submissions for their items only. The filter should generate a unique url with the search results filtered so that can be shared as well.

### Current Behavior

1. no unique url for filtering the prize explorer
2. no unique url or filtering for the project results page

### Expected Behavior

urls for filtered search results for both the prize explorer and results page

### Definition of Done

- [ ] url for filtered prize explorer results
- [ ] filtering and url for filtered project results

**Comment by octavioamu** [comment]
We want to filter into the explorer or create a sponsor page with the bounties like cards to be more visually appealing ?

**Comment by frankchen07** [comment]
on the sponsor page, it looks like filtering is present and the url changes when you filter by sponsor, so that's the intended behavior.

on the explorer, we want the same thing. As an example the explorer url is:

https://gitcoin.co/hackathon/web3-world/

when we filter by rsksmart, the explorer should filter, and the url should change to something like https://gitcoin.co/hackathon/web3-world/rsksmart and going to that url should lead to the already filtered by rsksmart bounties

![Screen Shot 2019-11-18 at 10 55 23](https://user-images.githubusercontent.com/7516920/69081281-79e4e100-09f2-11ea-845e-d4ee0aca1be3.png)
