### ISSUE TITLE
As a Gitcoin hacker & sponsor, there are some low hanging fruit Gitcoin hackathon experience improvements

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5484]
### User Story

As a Gitcoin hacker & sponsor, there are some low hanging fruit Gitcoin hackathon experience improvements

### Why Is this Needed

These are low hanging fruit improvements.

### Some of the problems:

1. The logo on the top of the prize explorer is quite large. For branding purposes, it may also be useful to add "Gitcoin Virtual Hackathon" branding, to indicate the niche & space we're serving. @octavioamu has already mentioned that we can display sponsor logos uploaded in the admin on the explorer as well.

2. Make filling out the project plan for a hackathon submission mandatory (even if they don’t fill out all of the fields). Alternatively we can make the prompt more aggressive. @willsputra for UX effects.

3. One of the problems we've encountered is that the projects results page is not well linked to the prize explorer - so having an obvious way to switch between the two would be helpful.

### Current Behavior
1. large logo, no virtual hackathon branding
2. optional project plan
3. no relational link between prize explorer and project results

### Expected Behavior

fix current behaviors

### Definition of Done

- [ ] smaller logo with virtual hackathon branding
- [ ] mandatory project plan
- [ ] relational link between prize explorer and project results

**Comment by octavioamu** [comment]
Just to be sure was understood, adding sponsors logos to the hackathon explorer is a feature already exist. But agree about the size of the informations are too big and takes a lot of space on the screen.

**Comment by willsputra** [comment]
possible improvements to solve #1. thoughts?
![header](https://user-images.githubusercontent.com/19514207/69256590-a9633b80-0bf4-11ea-9dc3-82984dcab03e.jpg)

**Comment by frankchen07** [comment]
@octavioamu - yes you are correct. Thank you @willsputra for the designs!

**Comment by thelostone-mc** [comment]
@octavioamu / @frankchen07 / @willsputra -> I've updated the UI based on @willsputra design over at https://github.com/gitcoinco/web/pull/5565

**Comment by frankchen07** [comment]
> Just to be sure was understood, adding sponsors logos to the hackathon explorer is a feature already exist. But agree about the size of the informations are too big and takes a lot of space on the screen.

is there anyway to make a fix for this?
