### ISSUE TITLE
There is a bug when using the search function on the hackathon projects page

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5486]
**Describe the bug**

When I try to filter the projects on the hackathon project [page](https://gitcoin.co/hackathon/projects/web3-world/) using a keyword like `aave` and I try to switch to the next page, the filter I put earlier gets cancelled and redirects me to this [link](https://gitcoin.co/hackathon/projects/web3-world/?page=2&order_by=-created_on&filters=) 

**To Reproduce**

Go to the hackathon project [page](https://gitcoin.co/hackathon/projects/web3-world/) put `aave` in the search box and go to the next page

![image](https://user-images.githubusercontent.com/50027175/68708370-dc258800-0593-11ea-8b6a-43c35655127a.png)

**Expected behavior**

To go correctly to the next  page

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome 
- Browser Version: Version 73

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by octavioamu** [comment]
Fixed on 5507fcd13f9730b263eb77b97c0488054a99cf93
