### ISSUE TITLE
As a Gitcoin operator, having the a project's team listed as a first step would help Gitcoin operations.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5488]
### User Story

As a Gitcoin operator, having the a project's team listed as a first step would help Gitcoin operations.

### Why Is this Needed

Having project teams, even unofficially, would help Gitcoin operations when running a hackathon

### Description

Octavio has brainstormed two possible solutions:

![image (1)](https://user-images.githubusercontent.com/7516920/68718460-2ee44d00-055e-11ea-8264-58cd5d1fc71b.png)

![image (2)](https://user-images.githubusercontent.com/7516920/68718461-2ee44d00-055e-11ea-8cc2-910f8f56a71f.png)

### Current Behavior

No team information is provided in the work start / submit for project result modals, and no details of the teams are shown on the workplan in issue details.

### Expected Behavior

1. Team information is collected.
2. Team information is included on the issue details within the workplan.

### Definition of Done

- [ ] Team information is collected.
- [ ] Team information is included on the issue details within the workplan.

### Data Requirements

Which data model would these bounties be a part of? Would it be part of the project results modal data model?

**Comment by octavioamu** [comment]
Fixed on f7f6a0c4a965b17ae13ba1b33a3d21ca65ea2b6e
