### ISSUE TITLE
As a Gitcoin hacker, I'd like to be involved in the judging process, and help the community tide lift all boats

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5489]
### User Story

WORKSHOP - As a Gitcoin hacker, I'd like to have a voice in the project judging process, and help the community tide lift all boats by advocating for projects that I think are useful.

### Why Is this Needed

Gitcoin hackers are our community. Allowing them a democratic voice gives color and opinion to the hard work that is done on hackathon projects. This can be tested as form of viral marketing, as well as another signal for sponsors that can help judging and make the hackathon be a more "involved" process.

This was promised in our email to hackers announcing Global Communities. 

### Workshop

Current proposal is to query ~~all past hackers who have earned a project-for-kudos kudos token in on of our past hackathons~~ all hackers registered for the hackathon and send each of them a Google Form to their email, which will have a single question: “Which project from Global Communities should win best in show?” (they will fill out the question with a URL to the submission).

Some items to spec-out when doing the hackathon voting scheme:

1. Who can vote?

Current proposed set: registrants for global communities

2. How many votes per voter, per bounty, per hackathon? Can I vote for my own project?

1 vote for the whole hackathon, voting for yourself is ok

3. How do we avoid sybil attacks with this voting system?
Need to analyze accounts to ensure sybil accounts aren't created solely for the purpose of voting. @frankchen07 for the approach on this, which we'll need when we get to analyzing the votes to determine a winner. This could just omit any accounts created since the hackathon was announced that did not submit work.

4. What does winning a vote, or coming in 2nd or 3rd offer? What are the benefits?

1st and 2nd prize, ties splits the total pot at the correct winning level.

5. How does the voter benefit?

Be part of the community, have a say with what they think is cool / useful

6. What do the votes decide? 

Votes decide what projects get 1st and 2nd place overall.

7. How are these votes pitted against the actual organization's vote / review of the entries?

Not related.

8. Why is voting restricted to a subset of groups and not the whole community?

Trial run, starting small

9. What is the voting period?

2-3 day voting period

### Current Behavior

no voting system

### Expected Behavior

GForm to proper market segment.

### Definition of Done
- [ ] gform to proper market segment
- [ ] email query (use this as an example in our sql meet)

**Comment by alexvotofuture** [comment]
We ran an experiment for this using a Google Form for the Global Communities hackathon. Only got a few responses back from hackers, making it difficult to select winners (each only got 1-3 votes). Closing this for now, but may be worth re-opening at some point if we hear more demand for this feature.
