### ISSUE TITLE
On the Gitcoin Issue Details page, the popups sometimes don't go away.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5493]
**Describe the bug**

On the Gitcoin Issue Details page, the popups sometimes don't go away.

<img width="1235" alt="Screen Shot 2019-11-13 at 12 13 24" src="https://user-images.githubusercontent.com/7516920/68800477-0bc5a600-060f-11ea-9ff5-e9cd4b0cda2b.png">

<img width="1405" alt="Screen Shot 2019-11-13 at 12 13 37" src="https://user-images.githubusercontent.com/7516920/68800478-0bc5a600-060f-11ea-89cc-361b18e2f73c.png">

**To Reproduce**

gitcoin issue details popups do not extinguish - when scrolling, the popups remain

**Expected behavior**

gitcoin issue details popups over profiles should extinguish when not on it.

frank & connor has a video

**Comment by molecula451** [comment]
This is not only happening with the issue Details but aswell with the notifications and the 'User Panel'

![panel](https://user-images.githubusercontent.com/41552663/68814439-3afc0780-064f-11ea-8a4e-64aff66cb8be.png)

If I click on any other side of the app. It will still there.

The panel only fades out when you reload a new url.route . The same happens with the notifications. IMO, Responsiveness should fade away it when mouse it's not over it.

**Comment by octavioamu** [comment]
@molecula451  can you please submit another ticket? That issue is not actually related to the popover.

**Comment by molecula451** [comment]
@octavioamu I will.
