### ISSUE TITLE
As a user, I would like to view profile bounties, repos, etc in a paginated fashion

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#550]
##### Description
Currently, all bounties and repositories listed on the profile page aren't paginated.  This could get wonky and lead to performance and rendering oddities.

##### Possible Implementation
Add a django template pagination method to step through queryset/list results.

**Comment by cd10012** [comment]
Hi started working on this here going to try to get this done by tonight: [branch](https://github.com/cd10012/web/commit/cdc0fbf2a68b3aeb531ba97bcb0a5189b91ac5e0)

Right now I have a function for paginating only the bounties but I'm going to create a paginator helper function that'll return an object for any queryset /list given. Screenshots to come soon

**Comment by owocki** [comment]
@cd10012 nice!  excited to see that

**Comment by owocki** [comment]
possibly related to https://github.com/gitcoinco/web/issues/656

**Comment by mbeacom** [comment]
@cd10012 Are you still actively pursuing this? If not, we can probably close this in favor of #656 (if you are, though, feel free to raise a PR with what you have and we can determine where to go from there).
