### ISSUE TITLE
Easy bug on the Hackathon page

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5514]
**Describe the bug**

When navigating in the Hackathon page and clicking on join Hackathon on the Open Climate Collabathon, it redirects to the [onboarding page](https://gitcoin.co/hackathon/onboard/open-climate-collabathon/) of that Hackathon, though when clicking on `Start Hacking` it redirects to the hackathon homepage. See the screenshot below.

**To Reproduce**

Go [here](https://gitcoin.co/hackathon/onboard/open-climate-collabathon/) and click `Start Hacking`

**Expected behavior**

To let me join the Hackathon

**Screenshots**

![immagine](https://user-images.githubusercontent.com/50027175/69162525-1a1f3080-0aed-11ea-95e8-b14e4133ed95.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Browser Version: 70.0.1

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Solexplorer** [comment]
Hmm if I use this [link](https://gitcoin.co/hackathon/onboard/open-climate-collabathon/?referer=https://gitcoin.co/hackathon-list) it redirects to the correct page. I think it's missing the `referer` parameter

**Comment by octavioamu** [comment]
It redirect to the page you come from. after registering,  "start hacking" go to the issue explorer
