### ISSUE TITLE
BUIDL - Tribes Organization Page 

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5516]
### User Story

BUIDL - Tribes Organization Page

### Why Is this Needed

Gitcoin Tribes opens a two-way broadcast for highly engaged hackers and funders to continue relationships and do high-leverage work, together. We want to build out a MVP of Tribes to test with our favorite sponsors.

### Description

Funder View:
![Funder View](https://user-images.githubusercontent.com/7516920/69194632-6fa01100-0ade-11ea-95eb-c62c4a10df5e.jpg)

Contributor View:
![Contributor View](https://user-images.githubusercontent.com/7516920/69194645-77f84c00-0ade-11ea-85c1-1e0c3a332725.jpg)

### Expected Behavior

The organization page should have a funder & contributor view that follows the designs above.

Vivek's main two goals for Tribes to solve the problems:
1. start with a list of people who have worked with us (making people who have done bounties is a start)
2. of the people who I've worked with, I need to be able to take action on staying in touch, in varying levels of intensity.

Clarifications:
1. "Join Tribe" is the follow button. 
2. We'll create an admin first "star member" / "promote to tribe leader" feature to indicate tribe members who are "leaders" / beyond a tribe member.
3. The chat button can be left "unconnected" since we don't have the feature up yet <- that's what I meant originally as a "dead" button.
4. Who sees the invite to bounty on the organizations page? What are the rules? Does it have to fetch every open bounty from the organization and then present them? For now, we'll use the same functionality as the user directory.
5. How to populate the core team - no blockers
6. How to populate the tribe members = they have previously finished bounties, or clicked "Join Tribe." there will be a human action of "joining" when we finally release it.

**Comment by owocki** [comment]
im excite for the char portion of this.. particularly if there is a ‘this user is online/offline’ indicator.  i dont see the online/offline indicator in the current spec tho..

is that something we can add to the UI?  seems like @androolloyd says that its queryable...

**Comment by androolloyd** [comment]
Sorry I'm late to this, yes the status of a user is queryable, https://api.mattermost.com
