### ISSUE TITLE
As a hackathon hacker I want invalid URLs to default to the hackathon list

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5528]
### User Story

As a hackathon hacker I want to be able to find the hackathon I'm trying to access myself using the hackathon list, even if I mis-type a hackathon URL or just want to find it at the root URL.

### Why Is this Needed

*Summary*:
Mis-typing a hackathon name or typing the root domain (https://gitcoin.co/hackathon) brings you to the latest hackathon, which is often not what a hacker is interested in participating in.

### Description

*Type*: Bug

### Current Behavior
Invalid "/hackathon/x" URLs or just the "/hackathon" URL leads to the latest hackathon.

### Expected Behavior
Re-route gitcoin.co/hackathon and other ambiguous hackathon links to the hackathon list (https://gitcoin.co/hackathon-list), rather than the latest hackathon.

### Definition of Done
Invalid/root URLs re-route to hackathon list.

### Data Requirements
Continue to track lead sources to the hackathon list, so we can see what people are trying to type

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by frankchen07** [comment]
this is done
