### ISSUE TITLE
As a hackathon hacker I want an obvious way to register for a given hackathon

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5531]
### User Story
As a hackathon hacker I want an obvious way to register for a given hackathon, and know when I'm registered successfully directly on the hackathon page itself.

### Why Is this Needed
*Summary*:
We want to reduce drop-off from people who don't know what action to take when coming to a hackathon, and ensure anyone who comes to the hackathon page can be followed up with through email with more info on participating, even if they don't initially explore prizes or read the hackathon guide thoroughly. We also want people to have piece of mind that they successfully registered for a hackathon.

### Description
*Type*: Feature

### Current Behavior
Registration link is buried within "Hackathon Guide" button and upon starting work on a hackathon prize. Not obvious that you need to read the guide or start work before registering. No way to verify you're registered once you do.

### Expected Behavior
An obvious UI element to allow a user to register (which is common for hackathons), leading them to the guide and Gitcoin profile creation after clicking it. Also a way to visually see which hackathons you're registered for.

### Definition of Done

- UI element to allow registration directly from the explorer
- Ensure this leads to the guide so people know what registration and participation entails
- UI to show when a user is registered for a hackathon already/successfully
- [Maybe] create a way to un-register (opt out from administrative emails for that hackathon, and optionally opt-out of the entire Gitcoin Hackathon Hackers email list]

### Data Requirements
Track registrants who use this button vs just starting work and registering that way.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by Solexplorer** [comment]
Not completely related to this issue but I think Gitcoin shouldn't allow users to start work if they didn't register for that Hackathon. What do you think @alexvotofuture ?

**Comment by frankchen07** [comment]
1. You can't start work if you're not registered. If you try and start work, it will ask you to register before allowing you to start work. That was one of the flows we implemented when we built out the new hacker registration. @octavioamu to confirm. 

2. I'd like to be more specific about the problem statement. The problem story above is "people coming to Gitcoin hackathons are confused about which action to take next." Let's be very specific about which step it is they're coming in at, and which actions they're considering. 

- is the user registered and looking / waiting for prizes?
- is the user registered and not sure how the hackathon works?
- is the user not registered, there are no prizes, and the user doesn't know how to register?
- is the user not registered, there are prizes, and the user doesn't know how to register?
- is the user not registered, there are prizes, and the user doesn't know how the hackathon works?
- is the fact that not having prizes before the hackathon opens confusing in itself?
- is it less confusion, or more needing confirmation on actions taken and next actions?
- is it that the pages we have (onboarding flow, prize explorer, projects results, hackathon lists page, and the potential [hackathon details page](https://github.com/gitcoinco/web/issues/5533) are not linked well together?

**Comment by alexvotofuture** [comment]
> Not completely related to this issue but I think Gitcoin shouldn't allow users to start work if they didn't register for that Hackathon. What do you think @alexvotofuture ?

@Solexplorer we've actually already implemented that feature (preventing "start work" instances without registering first).

**Comment by frankchen07** [comment]
closing - covered by:

https://github.com/gitcoinco/web/issues/5529
https://github.com/gitcoinco/web/issues/5559
https://github.com/gitcoinco/web/issues/5533
