### ISSUE TITLE
As a hackathon hacker I want to know what to do when the prize explorer has no/limited prizes

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5532]
### User Story

As a hackathon hacker I want to know what to do when the prize explorer has no/limited prizes.

### Why Is this Needed

*Summary*:
Before a hackathon hackers are faced with a blank prize explorer, which makes the hackathon appear dead and doesn't make it clear what should happen next (even when they know how the hackathon works through the hackathon guide).

After a hackathon it's not very clear that a hackathon has ended, and that people should either review the projects submitted or check out current/upcoming hackathons to participate elsewhere.

### Description

*Type*: Feature

### Current Behavior
Before hackathon launch, as sponsors are getting onboarded, hackers are met with a blank prize explorer. After a hackathon's deadline has passed prizes still look live.

### Expected Behavior
Some way of knowing that a hackathon has not yet started, and that the hacker should register for updates and check back in later to see prizes and get started.

Some way of knowing that a hackathon has ended officially, and that they can review projects or explore current/upcoming hackathons.

### Definition of Done

- Add a "register now and check back after [launch date]" splash page/banner/etc instead of the empty prize explorer when there are no prizes, or when the hackathon has not yet launched. If we hide the prize explorer, provide an option to show prizes early if we want to give people a head-start.
- A banner telling people to “see final projects & current/upcoming hackathons” once a hackathon ends, with links to the project page for the hackathon and the hackathon list respectively. We still want to show the prizes for funders and hackers checking on prizes and paying out, and for curious onlookers who want to see how prizes did.
- This should all sync with the hackathon start/end dates in admin.

### Data Requirements
Track dropoff once people are encountered with this message (do they come back when the hackathon launches? Any ways to retain them?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by frankchen07** [comment]
closing - covered by:

https://github.com/gitcoinco/web/issues/5529
https://github.com/gitcoinco/web/issues/5559
https://github.com/gitcoinco/web/issues/5533
