### ISSUE TITLE
As a hackathon admin I want a upgraded onboard page that includes editable hackathon details

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5533]
### User Story

As a hackathon admin I want a upgraded onboard page that includes editable hackathon details.

### Why Is this Needed

Without seeing the prize explorer, hackers will want to know, beyond the hackathon instructions, the total amount of prizes, the technologies they might be able to use, and any other larger hackathon details.

### Description

The "prize explorer" currently does not have any high-level information about the hackathon. This information is usually provided on the "landing page" for each hackathon, which users cannot navigate to once they get to the explorer, and some never see because they are linked directly to the prize explorer. Once we restrict the prizer explorer page https://github.com/gitcoinco/web/issues/5559, all hackers will be redirected through our onboard & hackathon details page.

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
Even details page for each hackathon hackathon.

This should be the first page hackers see when they come to a specific hackathon, and they should be directed here upon registering.

### Definition of Done
- Hackathon details page
- Ensure hackathon details page is the first page people see when coming to a hackathon
- Redirect to details from registration
- Should include fields for:
- - Start/end date, hackathon summary description, and sponsors (using the logo tool we already have).

**Comment by frankchen07** [comment]
I'm seeing the problem story here as when hackers are on the prize explorer page, they don't have access to generalized information about the hackathon(s). There is confusion as to where the centralized resources & details of a particular hack are held.

1. Does onboarding not take care of this? The onboard page for each hackathon outlines steps, and the registration button will be different depending on if you haven't registered or if you're already registered and coming back to view the flow. We could add additional information here, but the drawback is the onboard flow will become part of a page that could be viewed frequently, and that muddles our analytics.

2. This is now solutioning mode - If onboarding isn't an option, where exactly does this belong? Is it essentially https://gitcoin.co/hackathon-list with each hackathon having an additional link to a details page? Or maybe the card "flips" like in grants, showing the user the deets before they decide to view prizes or join/onboard.

**Comment by alexvotofuture** [comment]
@frankchen07 Agree with the problem story you provided.

1. "Onboarding" is currently just the "hackathon guide" page that is linked on each explorer. Both the prize explorer and hackathon guide have the hackathon title, logo, and dates on them, but don't have information about the hackathon as a whole. The hackathon guide explains the "how" and "when" for participating, but not the "why". 

The issue with relying on the landing pages (hosted on hackathons.gitcoin.co) for this is that people sometimes flow into this page from other sources (CodeFund, blogs, etc.) directly, rather than through the landing page. So if they come to it cold they have no context on the hackathon as a whole apart from the guide, and they are confronted with a bunch of prizes on a dApp (Gitcoin) they've never encountered before. It "onboards" them functionally, but doesn't "onboard" them in a way that excites them about the theme, sponsors, judges, etc.

2. Your second approach (cards you flip through, starting with the hackathon details/registration/guide and then moving to prizes and projects) is what I had in mind.
