### ISSUE TITLE
The Gitcoin ENS subdomain is not working

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5534]
**Describe the bug**

The [Gitcoin ENS](https://gitcoin.co/ens/#) is not working. It looks like there is a problem with an undefined variable:

![gif ENS](https://user-images.githubusercontent.com/50027175/69415582-2c7bb300-0d15-11ea-8079-877a833a8c8c.gif)

**To Reproduce**

Head over to https://gitcoin.co/ens/# and try to create your own subdomain

**Expected behavior**

To be able to have your own subdomain

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser: Mozilla
- Browser Version: 70.0

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
738ce4970f4a697c1a728d493c99f2cc267b4fe3 fixes this try now

**Comment by Solexplorer** [comment]
Though it doesn't let me check the TOS checkbox, I don't know if I am the only one experiencing this issue

**Comment by owocki** [comment]
i cant reproduce the checkbox issue. do you have more details?

**Comment by Solexplorer** [comment]
I tried both on Mozilla and Chrome but I am getting the same error 🤔 

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/50027175/69440366-ffe18e80-0d48-11ea-88b1-29f49a210ab6.gif)

**Comment by owocki** [comment]
24a2c3d870e17acb4e5770908d79812c4b5ab618 should fix it

**Comment by serejandmyself** [comment]
It seems that the checkbox is actually working - its the graphics side that's not. If you press `register`, it goes onto metamask and checks the box itself

**Comment by Solexplorer** [comment]
It's working! Thanks
