### ISSUE TITLE
When a Hackathon has come to an end, don't let users register or start work on those bounties

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5537]
**Describe the bug**

When a Hackathon ended, a user is still able to register for that one and start work. Gitcoin should not allow new users to register for expired Hackathons nor let the registered ones to start work on those bounties.

**To Reproduce**

If you never participated to `Road To Devcon`, go [here](https://gitcoin.co/hackathon/onboard/road-to-devcon/), register to the Hackathon and start work on this bounty: https://gitcoin.co/issue/ethereum-ts/TypeChain/109/1968 . This should not be allowed imo

**Expected behavior**

Don't allow `Start Work` on expired Hackathon bounties and don't let users register to that Hackathon once it has ended

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
@Solexplorer thanks for the report
Fix ready over at https://github.com/gitcoinco/web/pull/5577

**Comment by octavioamu** [comment]
Not actually a bug (more a feature lol) , we are not pointing to the onboard when the hackathon is done, but as there some cases sponsors had continue with the task open we shouldn't be blocking the registration because that will block this users to work on that postponed issue.

**Comment by octavioamu** [comment]
the "start work" actually should be controlled by the "expire date" of the bounty if that is the case of that bounty, giving the founder flexibility to decide if they want or not block the user at the end of the hackathon

**Comment by thelostone-mc** [comment]
@Solexplorer so I have to close out my fix cause @octavioamu is redoing that page.
@octavioamu it might make sense though that once hackathon has ended , users can start work on the bounty just like a regular bounty (without having to register for the ended hackathon )
