### ISSUE TITLE
inline validations

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#554]
design: http://bits.owocki.com/1n350K0E3w1G/Screen%20Shot%202018-03-06%20at%207.19.14%20PM.png (referenced from https://user-images.githubusercontent.com/238235/36852925-0e56140e-1d3b-11e8-9cb3-31eafafa5538.png ) 

implement jquery.validator (or similar)... in order to do inline validation of the following forms:

* new tip
* new funded issue
* submit work
* accept work
* kill bounty

**Comment by KennethAshley** [comment]
I'll be taking this

**Comment by PixelantDesign** [comment]
this work is already part of another ticket that @kennethaahley is working on.

**Comment by PixelantDesign** [comment]
nvm i saw your note om the other ticket @kennethashley
