### ISSUE TITLE
EPIC - As Joe Lubin, I want #onemilliondevs, because value compounds in the DEFI space + I want to increase the value being created on Ethereum.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5541]
# Stories in the One million devs epic

Check the below tickets to view Gitcoin's one million dev iniatitives

- Epic spec https://github.com/gitcoinco/web/issues/5541
- Gitcoin Quests Roadmap https://github.com/gitcoinco/web/issues/5436
- Gitcoin Pitches https://github.com/gitcoinco/web/issues/5543
- Decentralized Sense Making Thread to share Hypothesis & Observationss - https://github.com/gitcoinco/web/issues/5544
- Decentralized Sense Making Thread - Pitch your product idea https://github.com/gitcoinco/web/issues/5545

# This Story

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
As Joe Lubin, I want #onemilliondevs, because value compounds in the DEFI space + I want to increase the value being created on Ethereum.

### Current Behavior
[comment]: # (Describe what actually happened.)
100k-200k devs

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
1 million devs

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
- [Joe's talk on on million devs](https://media.consensys.net/joe-lubins-full-speech-from-devcon-5-how-we-get-to-a-decentralized-world-wide-web-1f83b35b2a0c)
- [Gitcoin One Million Devs Telegram Group](https://t.me/joinchat/DwEd_xWWAxZLfhw0qHXs5A)

**Comment by GGB6579** [comment]
@owocki ### ****

**Comment by ughojor2007** [comment]
that nice one

**Comment by zyf125197** [comment]
很不错

**Comment by Tranvanlap95** [comment]
0xe4e834fc6808181668501E89a85F1cC40ad941d9
