### ISSUE TITLE
Explorer changes followup

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#555]
##### Description
This issue is to discuss the changes introduced via: #523

Please add relevant issues pertaining to the explorer changes live at:  https://stage.gitcoin.co/explorer

**Comment by owocki** [comment]
Looks like we need comments added on explorer

**Comment by owocki** [comment]
the ’x’s on the buttons up top dont work http://bits.owocki.com/3G203D3p3U3z/Screen%20Shot%202018-03-07%20at%209.34.35%20AM.png

**Comment by owocki** [comment]
hey @thelostone-mc -- any chance you could help us worth through these issues?  not sure if they are in scope for the OG bounty or not.. but happy to tip if not

**Comment by owocki** [comment]
also cc @eswarasai -- whom i think is working on some frontend stuff

**Comment by vs77bb** [comment]
### Issue counts by category do not match
 
- In Stage, we have 50 issues in 'Open' and 4 issues in 'Work Started'. 
- In Prod, we have 21 issues in 'Open' and 29 issues 'Work Started'. 

Not sure where the additional four issues are coming from in Stage (could be examples in stage?)

**Comment by mbeacom** [comment]
@vs77bb When I migrated the DB yesterday, I kept the original staging DB data which has numerous test bounties from me.  That might be it.

**Comment by owocki** [comment]
thanks, i think thats a database issue.. (we need to write a script that auto-restores prod to stage soon)

**Comment by eswarasai** [comment]
@owocki -- Yes. I'll be taking care of the `Search` functionality. I was waiting for the PR to be merged in order to get started.

@mbeacom @owocki -- Is there any easy way to keep track of all the issues at a single place with the status fixed or not? It'd be very difficult to scroll through all the comments and keeping track of them for me as well as @thelostone-mc. Thanks.

**Comment by mbeacom** [comment]
We could move the actionable items into a github project, if that'd be easier.

**Comment by eswarasai** [comment]
@mbeacom -- Makes sense to me. Maybe we can hold off on creating GitHub Project right away as there's still Dev work pending. For now, I'll try to follow the comments and keep a track of them. Once I create a PR, then we can move everything to GitHub Project. Sounds good?

**Comment by owocki** [comment]
@eswarasai afaik the only two live issues are 

* the ’x’s on the buttons up top dont work 
* comment counts on the explorer page

**Comment by thelostone-mc** [comment]
@owocki @eswarasai 
I've got the comment count covered

**Comment by mbeacom** [comment]
@eswarasai Is there anything I can do to help you out with filter `x` buttons?

**Comment by thelostone-mc** [comment]
@owocki Both issues have been take care of! ^_^

**Comment by PixelantDesign** [comment]
For context, this is the outstanding work that exists to complete the explorere https://github.com/gitcoinco/web/issues/412
