### ISSUE TITLE
Cross Chain Foundations: New unpaid bounty state

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5560]
### User Story

Cross Chain Foundations: New unpaid bounty state

### Why Is this Needed

Because bounties will no longer be on-chain, bounties therefore will have a state that is tied to the generation of the payout QR code. 

### Description

If a bounty has not yet been paid out yet, the state of the bounty should be "unpaid", and the bounty information & details should reflect that.

@danlipert - is this an event or a state? I can imagine scenarios where bounties can be in a variety of states (started, submitted, open) and still be unpaid, which means a bounty can have two states. 

### Current Behavior

no unpaid state

### Expected Behavior

unpaid state

### Definition of Done
TBD

**Comment by danlipert** [comment]
In my thinking, this is a separate state that becomes the new default state for newly created bounties - once the fee payment is detected via the backend, then it will be changed to open. Prior to the payment being detected, while the bounty is in the unpaid state it will be hidden from the explorer and elsewhere. If this would cause problems for hackathons, etc., a coupon code can be used to bypass the fee and have the bounty created with the open state, bypassing the unpaid state entirely.

**Comment by frankchen07** [comment]
clarification: this is the bounty fee, not the bounty payout

still to be discussed and have a final decision on: is the fee viable as a cryptoeconomic incentive?

**Comment by danlipert** [comment]
Since we are not using a bounty fee for ETC, this ticket is no longer needed
