### ISSUE TITLE
Cross Chain Foundations: Chain scanner for transaction confirmation (ETC)

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5561]
### User Story

Cross Chain Foundations: Chain scanner for transaction confirmation (ETC)

### Why Is this Needed

In order to show messages confirming payment using a QR code, a chain scanner to detect transaction confirmations must be built for the proper chain (e.g Bisontrails).

@danlipert is this also the right time to think about:

1. gathering data on payments in order to generate 1099s / ensuring tax compliance
2. generating invoices on the spot

Alternatively, this is can also be a separate portion of the product (perhaps in settings).

### Description

The first test case will be for ETC. This will be a good Python project that utilizes a possible bounty source API in order to detect:

1. Has a bounty been paid out?
2. If it has, what's the transaction ID?

Further discussion has brought about if this task is suitable for Celery, but there's agreement on a "not yet" decision, since Celery doesn't yet have the ability to do something on a repeated schedule.

### Current Behavior

no chain scanner, currently in the prototyping process

### Expected Behavior

chain scanner backend

### Definition of Done
TBD

**Comment by danlipert** [comment]
In terms of invoices, etc. and supporting things, I do agree we'll need to build those in appropriately, but its probably a separate task (identifying the etherscan equivalent and adding that appropriately to the invoices, etc.)

**Comment by frankchen07** [comment]
status update:

more work to be done on the payout page: browser keeps pinging the txn scanner on the payout page

more thinking about predicting transaction id (get nonce) or simply scan the blocks (using blockscout)
