### ISSUE TITLE
Cross Chain Foundations: Notifications for verified fee payments

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5562]
### User Story

Cross Chain Foundations: Notifications for verified fee payments

### Why Is this Needed

We will need to design and build the backend for notifying that a QR code payment has passed and is confirmed. This is dependent on https://github.com/gitcoinco/web/issues/5561.

### Description

This ticket encompasses the design and build out of backend transaction notifications that confirms successful payment, both to the contributor and to the funder. These endpoints will also help the eventual front-end notifications we want to implement as well as any email notifications of successful transactions.

Currently, when syncweb3 picks up the bounty, it will send the funder an email, but with ETC we don't have syncweb3, so there needs to be infrastructure set in place that allows us to detect when the fee is paid so that data can be stored and subsequently be used. 

### Current Behavior

no backend infrastructure without syncweb3 and no notification 

### Expected Behavior

successful log of successful payment by infrastructure into our DB

### Definition of Done
TBD

**Comment by danlipert** [comment]
I'm not sure if a separate email notification here is needed, as it will likely happen within seconds, if not just a few minutes from bounty creation.

**Comment by frankchen07** [comment]
no longer using bounty fee - ticket no longer needed
