### ISSUE TITLE
Abstracting Content Primatives from Logic / Code

### ISSUE THREAD

**Issue by e-n-l** [gitcoinco/web#557]
##### Problem: Content workflow interferes with Development workflow 
Currently, GitCoin.co content lives in html files in the same repo as the codebase. Whenever the content needs an update, a content creator / editor has to go through the same process as a developer to make changes, and they share a common commit history. This creates unnecessary noise, conflicts and problems, due to the inherent differences in the processes and stakeholders that work on content vs code.

##### Proposed Solution: Abstract Content into a submodule / separate repo; update build process to use Hugo

Moving the content and static assets out of the repo, into a submodule, would free creative contributors and content contributors to use a simpler workflow, separate from the checks and validation necessary for releasing code.

Static assets like CSS, minified JS, etc. should be removed from the ```web``` repo, and replaced with the source SCSS, etc., such that those assets can be be compiled / processed via their own pipelines, rather than have a hod-podge of pre-compiled / static assets living in the ```web``` repo.

Hugo is a Static Site Generator, which uses templates and magic, to compile assets into static HTML files.

As GitCoin apparently uses WebPack already, perhaps something like a Hugo WebPack boilerplate could serve as the template upon which the content submodule could be built.
 (https://github.com/vseventer/hugo-webpack-boilerplate)

**Comment by mkosowsk** [comment]
Per discussion with @olafghanizadeh, this ticket might be broken out into 2 separate sub-tickets 👍 

0. Front-end using SCSS compiling and linting via current webpack set-up. Unify variables such as colors, button styles, etc. across site to maintain consistency.

1. Separate out marketing into static site generator, managed with markdown or other method. This way you don't have to commit to source repo when changing content (this could live in a submodule). 

This way, people that want to begin to contribute to Gitcoin via things like typo fixes, changes to headers, etc. can get their foot in the door very easily 😀 

Happy to discuss further!

**Comment by razordaze** [comment]
Sub-ticket 0.) is now [up here](https://github.com/gitcoinco/web/issues/560)

Sub-ticket 1.) may  be further split into 2 sub-tickets:
1. Move the "view" (SCSS, HTML, content, creative assets, etc.) into a separate repo to be pulled into the ```web``` docker as a sub-module on build. 
2. Consider using an SSG like Hugo as part of the creative build process.

Personally, I think 1.) may be an elegant means of solving / addressing the issue 0.)

**Comment by kuhnchris** [comment]
Hey there! Since there is no information in here: was there any information how this is going to continue, or did this simply disappear?

**Comment by danlipert** [comment]
This would be nice, but we've got too many other priorities right now
