### ISSUE TITLE
Gitcoin Top Community Members is showing double entries

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5570]
**Describe the bug**

If you go [here](https://gitcoin.co/about#team) and go to the section: `Gitcoin's Top Community Members`, you see double entries. See screenshot below:
![image](https://user-images.githubusercontent.com/50027175/69899573-8fe69000-1368-11ea-815a-d598293f1919.png)

**To Reproduce**

Go to https://gitcoin.co/about#team and go down till you reach the `Community` section

**Expected behavior**

I expect to see single entries for each Top Community Member

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
5b1f583307687e34909f48e8d5d5b8ff72a781b9

**Comment by owocki** [comment]
will be deployed next deploy (prob weds)
