### ISSUE TITLE
DESIGN - As an ETC user, I'd like a user-friendly bounty process, since it will be different than ETH

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5579]
### User Story

As an ETC user, I'd like a user-friendly bounty process, since it will be different than ETH

### Why Is this Needed

Our current plans for cross-chain implementation with ETC involves a different experience when opening a bounty. We need to plan this flow out, iron out the kinks, and make sure the flow makes sense.

### Description

https://docs.google.com/document/d/1S8J4Q2FqwLk7oPZHIyAFEbUhk0ndxLAyoRd8CnDfS5s/edit

For ETC bounties:
:white_check_mark: create bounty
:white_check_mark: approve/reject worker
:white_check_mark: start / stop work
:white_check_mark: submit work
:white_check_mark: kill bounty
:white_check_mark: edit bounty details + increase bounty amount
:heavy_multiplication_x: payout

There are several design items:

1. Fund bounty page that eliminates the proper sections.
2. Combined payout page & payout page renaming (it should just be payout)
3. Edit bounty page (would this just be the funder form?)
4. Metamask flow (skip for ETC, if that's the route we're going down).

**Comment by frankchen07** [comment]
update 2019-12-26: https://github.com/gitcoinco/web/pull/5627

**Comment by willsputra** [comment]
for payout:

either we use a separate payout page (advanced payout but with all the blockchain stuff removed)
![crosschain payout](https://user-images.githubusercontent.com/19514207/71994149-d7671280-326a-11ea-9ee2-23203238d881.jpg)

or a new payout from issue details
![new payout](https://user-images.githubusercontent.com/19514207/71994192-e51c9800-326a-11ea-9ce5-e01a50529127.jpg)

**Comment by willsputra** [comment]
solution #1 is an easier lift since #2 requires a redo of the issue details activity section. which one did we end up deciding on? @frankchen07 

cc @thelostone-mc

**Comment by frankchen07** [comment]
@willsputra I want to say solution 2 had more consensus and excitement behind it, but let's grab a conversation this week!
