### ISSUE TITLE
Re-Using "Sponsor" name in admin causes 500 error with "Hackathon Sponsor" prize explorer logo upload tool

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5582]
Describe the bug
Adding a sponsor twice (using the exact same name) within the "Sponsors" admin tool will cause an error when trying to use either in a new prize explorer with the "Hackathon Sponsor" admin tool, causing the whole prize explorer to crash with a 500 error page.

To Reproduce
Use "Hackathon Sponsors" admin tool for a sponsor with two "Sponsors" entries of the same name.

Reproduced twice by deleting and re-adding an existing sponsor using "Hackathon Sponsors".

Expected behavior
Sponsor logo added to hackathon site, no 500 error.

Additional context
Can be avoided by just using the earlier "Sponsor" entry. Tried this and it worked.

**Comment by thelostone-mc** [comment]
Closing it out as it's fixed ^_^
