### ISSUE TITLE
Hackathon Specific Quests! (MVP --> Global Communities)

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#5583]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a hackathon organizer, I want hackathon specific quests to engage hackathon registrants to learn about new materials in an engaging way, without the lift of having to do a bounty. 

As a funder, I want to know who has engaged meaningfully with my dApp as a 1) filtering mechanism and 2) a means to provide access to Gitcoiners who care about my product / mission. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Gitcoin hackathons are currently centered around prizes. They can be much more. The learning track starts with quests, which provide NFT's to the best of the best, which can be used to filter a smaller list of hackers into more focused meetings with web 3 companies looking to grow their communities. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
V1 Request: 7 quests marked as specific to the Global Communities hackathon, where: 

1) You have to register in the hackathon to take the quest. 
2) The Gitcoin Quests are listed in some fashion on the hackathon explorer (https://gitcoin.co/hackathon/global-communities/)

Here are 4 to start it off + 3 to come. 

- 3Box Quest [https://gitcoin.co/quests/69/3box-a-wormhole-into-the-user-centric-web]
- A Wallet Quest [https://gitcoin.co/quests/16/one-wallet-to-rule-them-all]
- A Web 3 Quest [https://gitcoin.co/quests/52/welcome-to-web-3]
- NFT’s vs You - A Quest [https://gitcoin.co/quests/33/enter-the-world-of-nfts-nonfungiblity-vs-you]
- ETC Quest (Pending)
- Hashgraph Quest (Pending)
- BUIDL Network Quest (Pending

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
- Number of registrants in a hackathon (does this go up significantly when hackers have quests to do, instead of just bounties? 
- Can sponsors meaningfully engage with the learners?
- Can we use the kudos data (on who completes Quests) to create tailored experiences between engaged hackers and companies? 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

A v1 could include a blue (highlighted) button linking to Global Communities quests next to projects / the hackathon guide).

![image](https://user-images.githubusercontent.com/23297747/70012692-c247e700-153a-11ea-8ad2-22b8fed78f2c.png)

**Comment by owocki** [comment]
the 'unlocked' portion could be done pretty simply by adding a condition to `quest.is_unlocked_for`.. as for how to list the quests on the hackathon landing page.. i'd love to hear some ideas.

**Comment by vs77bb** [comment]
the basic MVP idea there is include a 'Explore Quests' Button next to 'Projects' / 'Hackathon Guide' 

Projects goes to: https://gitcoin.co/hackathon/projects/global-communities/
Guide goes to: https://gitcoin.co/hackathon/onboard/global-communities/
Quests could go to: https://gitcoin.co/hackathon/global-communities/quests

with a specific view of the GC quests above (or any hackathon specific quests), where you have to register for the hack before you can do the quests

(similar to how you have to register for the hack before you can start work on a bounty)

**Comment by owocki** [comment]
@vs77bb here https://gitcoin.co/hackathon/global-communities
