### ISSUE TITLE
Implement SCSS Compiling

### ISSUE THREAD

**Issue by e-n-l** [gitcoinco/web#560]
Per @olafghanizadeh and @razordaze and @mkosowsk:

As I GitCoin developer, I would like to have have consolidated styling, so that I can quickly make global styling changes across the app and have reuseable components, variables etc. 

### Background

Current styling in the site is “[is messy and a hassle to edit](https://github.com/gitcoinco/web/issues/135)” 

0. Templates that aren’t reusable across [Dashboard](https://github.com/gitcoinco/web/tree/master/app/dashboard), [Marketing](https://github.com/gitcoinco/web/tree/master/app/marketing), [Retail](https://github.com/gitcoinco/web/tree/master/app/retail), etc.
1. Non reusable variables and components so that it’s difficult to maintain consistency across the site

### Acceptance Criteria
0. Build process that leverages SCSS to consolidate styling across the app
1. Preserve all current functionality (do no harm)

#### Refactoring Steps:
0. Add SCSS compiling and linting to the Webpack tasks
1. Utilize a package manager to include common libraries used (‘bootstrap, animate.css, etc.’)
2. Start by defining common variables (colors, fonts, forms) - @PixelantDesign
3. Include all current CSS files into the build
4. One-by-one refactor and lint those files so that they utilize common & reusable components and variables

Thoughts @owocki @mbeacom @PixelantDesign ?

**Comment by KennethAshley** [comment]
Im all for this!

**Comment by joshmobley** [comment]
I would love to help with this effort. Building component libraries is sadly one of my favorite things to do :)

**Comment by mkosowsk** [comment]
@joshmobley a pared down scope for this ticket is being worked on in https://github.com/gitcoinco/GIPs/issues/6

Please add any feedback you may have to that GIP (Gitcoin Improvement Plan 👍🏻). Once the community reaches a consensus we will put out a new and improved Issue :)

**Comment by PixelantDesign** [comment]
yes! this is great!

**Comment by kuhnchris** [comment]
Was this ever realized on the repo itself?
