### ISSUE TITLE
Unable to claim bounty, transaction dropped

### ISSUE THREAD

**Issue by ItsMajestiX** [gitcoinco/web#5603]
I was told by email support to post my issue here. I am trying to claim a tip that has been sent to me, but the transaction is constantly mining. [I checked the transaction on etherscan, and it was dropped](https://etherscan.io/tx/0x64b1fe2831183bcfaaa6acf8583ff42558fbc39b05e51f6ef14d2230b264cd3e). The tip was for work on [this issue](https://gitcoin.co/issue/ArweaveTeam/Bounties/1/2929), if it's helpful. I was hoping something on the backend similar to issue #2883 could be done. [Here is the link to the redeem page if needed](https://gitcoin.co/tip/receive/v3/QmSU27dVoBc2vvxx9EJxt6s5CnLDFN4HhAahRdxy5jCo9i/0x64b1fe2831183bcfaaa6acf8583ff42558fbc39b05e51f6ef14d2230b264cd3e/mainnet).

**Comment by owocki** [comment]
hey @arweave-sophie it looks to me like the tip transaction was dropped by the ethereum mainnet.. any chance you'd be able to re-issue the tip?

**Comment by ItsMajestiX** [comment]
The transaction seems to be back up again. I was able to redeem it, so I'm closing the issue.
