### ISSUE TITLE
security warning in firefox/linux

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5604]
**Describe the bug**

**To Reproduce**

security warning in firefox/linux

**Expected behavior**

**Screenshots**

![IMAGE 2019-12-05 14:58:04](https://user-images.githubusercontent.com/513929/70277461-ae38fb00-176f-11ea-80a9-993b2da939ff.jpg)

firefox / linux

**Comment by kuhnchris** [comment]
On what subdomain? *.shmoop.com seems to be for a different page.
