### ISSUE TITLE
Submitted work to wrong bounty

### ISSUE THREAD

**Issue by crypto-guys** [gitcoinco/web#5611]
I accidentally submitted the wrong link to this bounty.
https://gitcoin.co/issue/ArweaveTeam/Bounties/19/3704

If you look at the time this happened and the time i submitted my project for ipfs+arweave they are very close because i was in the wrong bounty when i submitted.

Now I can not submit my actual work.
https://github.com/crypto-guys/arweaveNewsPermafeed/

Is there any way to fix this?

**Comment by owocki** [comment]
just updated the submission link on the bounty fulfillment object, which will show on the bounty newsfeed! thanks for letting us know!

**Comment by crypto-guys** [comment]
Its fixed thank you
