### ISSUE TITLE
DESIGN & BUILD - As a Gitcoin operator in CLR Round 4, we need to build a separate view for media grants

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5612]
### User Story

DESIGN & BUILD - As a Gitcoin operator in CLR Round 4, we need to build a separate view for media grants

### Why Is this Needed

For CLR round 4, we need to refresh the Grants page and add an additional section for media grants.

### Description

Time for a Grants page refresh (gitcoin.co/grants)

1. We need a duplicate UI for media grants that runs parallel with the normal technical grants (media grants being grants that are non-technical - tutorials, videos, eth hub newsletters, community boards).

2. At the same time, would it be good to do a UI refresh of the grants page (e.g are the categories still necessary on the grants page, if we have media and also technical grants?)

3. The goal is to have two simultaneous grant instances running. This means two CLR rounds, one by media grants, and one by the normal technical grants. Because we are running CLR on both of those rounds, does the backend need to be duplicated as well?

### Current Behavior

there is only one instance of grants

### Expected Behavior

two instances of grants, one media, one technical, running in parallel

### Definition of Done
- [ ] parallel instance of grants
- [ ] new designs that enable parallel running

**Comment by owocki** [comment]
@frankchen07 we'll likely also need a wayto mark grants as "listed on the OSS marketplace" "listed on media marketplace" or "not listed" in the new grant form.

secondly, we'll need to update the clr code to only compare grants against those who are in the same category.

thirdly, what are the sub categories of media grants similar to the sub categories of OSS grants? https://bits.owocki.com/2NurRwlw

**Comment by owocki** [comment]
also note that this is an ongoing thing https://github.com/gitcoinco/web/issues/5456

**Comment by frankchen07** [comment]
1. @thelostone-mc and I talked about this logic today - I've opened a ticket for it: https://github.com/gitcoinco/web/issues/5616. We'll be shifting priorities over to make sure this is ready for december 17th. It'll be tight though.

2. also talked about this with aditya

3. @ceresstation and I considered just ditching subcategories and just having a cleaner media or tech grants. @willsputra will be designing this so he will also have some UX input

**Comment by willsputra** [comment]
Maybe we could have two-level categories?

![grantscategories](https://user-images.githubusercontent.com/19514207/70645824-a8b44700-1c80-11ea-9730-7bb2fea2ef18.jpg)

**Comment by willsputra** [comment]
@frankchen07 btw will the matching amounts and partners be different for tech and media grants? wondering if I should tweak this part too.
![Screenshot 2019-12-12 01 43 10](https://user-images.githubusercontent.com/19514207/70645909-d0a3aa80-1c80-11ea-8a3e-aaeab9fa2cf7.png)

**Comment by owocki** [comment]
i like the tabs that @willsputra designed!  +1 on having the diff matching amounts listed up top.. would love to have a nice design for this.. but if push comes to shove we can just update the text

**Comment by owocki** [comment]
also note that right now we have two types of grants

- listed on marketplace
- not listed on marketplace

going forward there could be technically 3 categories 

- tech public goods grants
- media public goods grants
- other grants 

we would shove all the unlisted ones into 'other grants'..  then if the grant owner can convince me or @ceresstation that their grant is actually a public good; then they can be included in one of the public goods categories + be eligible for matching

**Comment by willsputra** [comment]
@owocki gotcha, will work towards that!

**Comment by willsputra** [comment]
we could have the amount and sponsors in each tab. I've also added the Unlisted tab which is only visible for admin
![grants](https://user-images.githubusercontent.com/19514207/70759858-bf42c700-1d82-11ea-99a4-02ae07673b8d.jpg)

**Comment by frankchen07** [comment]
oh, that looks nice...I like the clr round match up top as the banner.

I still am a proponent of removing the original filters, I think it'll be cleaner since we already have a sort by function.

does that mean anyone can see the unlisted? then people will ask why they're in unlisted, right? maybe unlisted should be renamed something else (like other) but that's more of a positioning thing.

**Comment by willsputra** [comment]
> I still am a proponent of removing the original filters, I think it'll be cleaner since we already have a sort by function.

hmm I guess it's still useful for people who want to look for or fund specific types of grants, since the sort by function is only by date and amount. 

> does that mean anyone can see the unlisted? then people will ask why they're in unlisted, right? maybe unlisted should be renamed something else (like other) but that's more of a positioning thing.

as a start we'll probably make the unlisted admin-only

**Comment by owocki** [comment]
> hmm I guess it's still useful for people who want to look for or fund specific types of grants, since the sort by function is only by date and amount.

+1 to this

> as a start we'll probably make the unlisted admin-only

ok sounds good
