### ISSUE TITLE
Gitcoin Weekly newsletter has poor formatting on mobile clients

### ISSUE THREAD

**Issue by coderberry** [gitcoinco/web#5634]
**Describe the bug**

Horizontal padding for newsletter emails on mobile appear too narrow on Gmail (mobile) and Front App (mobile).

**To Reproduce**

Open and view the Gitcoin Weekly newsletter in either client. 

**Expected behavior**

There should probably be less horizontal padding so that the content takes up more of the screen space.

**Screenshots**

Front Client (iOS):

![IMG_D820C02B0293-1](https://user-images.githubusercontent.com/12481/70810011-388cea80-1d80-11ea-98fc-6cdd8a60130d.jpeg)

Gmail Client (iOS):

![IMG_B522915F9D2F-1](https://user-images.githubusercontent.com/12481/70810021-3cb90800-1d80-11ea-802f-091f01c4836d.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone Xs Max
- OS: iOS 13.3
- Browser: Email Client
- Version: N/A

**Additional context**

None

**Comment by molecula451** [comment]
<code> newsletter.css</code> Add responsiveness for different widths. @owocki Bountiying out?

![Screenshot_20191213-135835](https://user-images.githubusercontent.com/41552663/70822081-119bdc00-1db3-11ea-97e3-ec86ae59b8ea.png)
![Screenshot_20191213-135846](https://user-images.githubusercontent.com/41552663/70822087-13fe3600-1db3-11ea-9715-60135d4652c8.png)
![Screenshot_20191213-135857](https://user-images.githubusercontent.com/41552663/70822126-2a0bf680-1db3-11ea-8dd2-8d7855c53ec3.png)
