### ISSUE TITLE
Can't edit hackathon project 

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#5641]
**Describe the bug**

https://gitcoin.co/hackathon/projects/global-communities/?q=kickback+cor&sponsor=
I am the owner of the project, but hitting `edit` does nothing. 

Button:
```
<button onclick="projectModal(17662,64);" class="position-absolute btn btn-gc-green btn-sm m-2">edit</button>
```

**To Reproduce**

Any page with this card has the same problem. 

**Expected behavior**

I should go to the project edit page

**Screenshots**

![image](https://user-images.githubusercontent.com/35669742/70872878-10f87680-1f68-11ea-920a-dbef6c2bd913.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: firefox
- Browser Version: 70.0.1

**Comment by octavioamu** [comment]
Thanks for reporting this, I will take a look.

**Comment by octavioamu** [comment]
@NukeManDan now should be fixed (https://github.com/gitcoinco/web/commit/0381c241f87b15b4db99f2f1e2e7b6e3d90e087d) can you please test and tell me if ok now?

**Comment by owocki** [comment]
hey @NukeManDan didnt you tell me at the app alliance thing that you were having perf issues on the gitcoin site? can u open a ticket for that too?

**Comment by NukeManDan** [comment]
@owocki - I did have this, for some reason without any change I can note on my end, the CPU and laggy form issues are not present on the same machine. I will inform if that changes again.

**Comment by NukeManDan** [comment]
@octavioamu yes! fixed now.

**Comment by NukeManDan** [comment]
but... project summary is now limited to 100 chars :cry:

**Comment by octavioamu** [comment]
Yes is limited since that text is showed on the cards in a small space between others projects. 
The idea is you write the complete summary on the PR / repo you provided, where people can read it and you as an owner have more space and options to provide the right explanation.

**Comment by octavioamu** [comment]
closing it for now since the issue seems fixed
