### ISSUE TITLE
Hackathon Landing Page Refresh

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5643]
### User Story

Hackathon Landing Page Refresh

### Why Is this Needed

Refreshing the hackathon landing page.

### Description

A refresh of our current hackathon landing page.

Additional questions:

1. How do we motivate hackers to click on the CTA or participate?

### Current Behavior

Old landing pages.

### Expected Behavior

Designs:

![Sustain_web3-02](https://user-images.githubusercontent.com/7516920/70950250-e87a8600-2014-11ea-9022-0e5ae5530ea9.png)

![btn](https://user-images.githubusercontent.com/7516920/70950256-eb757680-2014-11ea-9faa-28494677c5fa.PNG)

### Definition of Done
- [ ] lock down designs
- [ ] build

### Data Requirements
- [ ] ensure we track the CTA CTR

**Comment by octavioamu** [comment]
Done https://hackathons.gitcoin.co/sustain-web3/
