### ISSUE TITLE
DESIGN & BUILD - Homepage Design Refresh

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5644]
### User Story

DESIGN & BUILD - Homepage Design Refresh

### Why Is this Needed

The homepage needs a design refresh in order to elucidate the problems Gitcoin addresses.

### Description

The main goal of the landing page is to give new users an immediate understanding of how our product suite works together, an opportunity to join our newsletter, and convince the user to sign up for an account

### Current Behavior

gitcoin.co

### Expected Behavior

![home](https://user-images.githubusercontent.com/7516920/70950767-5a9f9a80-2016-11ea-99b7-a2066f6698d3.jpg)

### Definition of Done
@willsputra changes we talked about on 2019-12-16
- [ ] reorder information hierarchy on Gitcoin's mission and problems
- [ ] normalize boxes that contain the CTAs for maintainer and contributor
- [ ] make more obvious the newsletter sign up

### Data Requirements
- [ ] frank to hotjar this once we release
- [x] ensure GA analytics (should be ok already)

**Comment by willsputra** [comment]
tweaked based on yesterday's discussion
![landing](https://user-images.githubusercontent.com/19514207/71006850-fae1e600-2120-11ea-8a98-e6eabba59e79.jpg)
