### ISSUE TITLE
Airdrop transfer in progress

### ISSUE THREAD

**Issue by haikukoten** [gitcoinco/web#5645]
**Describe the bug**

While I was trying to redeem my prize for IPFS Newbie Quest, I was repeatedly warned that an airdrop was in progress and try after 1 to 2 mins, so I tried later (approx 5 mins) for about 6 to 7 times but I was still greeted with the same warning. I checked my wallet to find that last airdrop was done about 25 mins earlier than my first request.

**To Reproduce**

Complete a Quest and try redeeming the reward.

**Expected behavior**

Warning.
![Screenshot (800)](https://user-images.githubusercontent.com/24366687/71005879-6d939700-210a-11ea-9554-86f13558a563.png)

**Screenshots**

![Screenshot (800)](https://user-images.githubusercontent.com/24366687/71005879-6d939700-210a-11ea-9554-86f13558a563.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: Version 79.0.3945.79 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
note that airdrops are limited by sender not receiver..

in any case https://github.com/gitcoinco/web/pull/5606 fixes this.. should be into next release
