### ISSUE TITLE
Choose Persona (Are you Hunter or Funder) model gives Internal Server Error

### ISSUE THREAD

**Issue by pradeepgangwar** [gitcoinco/web#5659]
**Describe the bug**
I tried setting up gitcoin development environment. After creating superuser and logging in I tried going to http://localhost:8000 and found the model below. After clicking on the options in modal I received 500 Internal Server Error (Screenshot attached)

**To Reproduce**
- Setup Development environment.
- Create superuser
- Login as superuser
- Head back to http://localhost:8000 and see the modal.
- Click on any option and notice the error

**Expected behavior**
Should work without errors

**Screenshots**
![Screenshot_2019-12-20 Grow Open Source Get crowdfunding and find freelance developers for your software projects, paid in c](https://user-images.githubusercontent.com/21259802/71267688-47236500-2371-11ea-807f-3d304d46ca0f.png)

<img width="716" alt="Screenshot 2019-12-20 at 9 41 57 PM" src="https://user-images.githubusercontent.com/21259802/71268133-36272380-2372-11ea-90f5-55c639bb27ef.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.6
- Browser: Firefox Developer Edition
- Browser Version: Version 72.0b4

**Comment by pradeepgangwar** [comment]
Someone please confirm if this issue exists. Or let me know if I have to do anything regarding setting up my development environment.

**Comment by owocki** [comment]
@pradeepgangwar im almost sure u might have to auth via github ( not via django super user ) for the system to create a dashboard.Profile off ur user. can u try that?

**Comment by pradeepgangwar** [comment]
@owocki No, it isn't working. This is what I followed today:
- Logged out from django admin
- Registered a new GitHUb OauthApp and token and added it to `app/app/.env` file.
- Restarted the server via docker
- Logged in via GitHub Oauth
- Still that modal appears after logging in and fives the error.

I am not sure why that is happening. Also to bypass that I tries manually setting hunter/funder settings via django admin but the problem persists.

**Comment by pradeepgangwar** [comment]
My supersuer username and github username were same while logging in via OAuth so it assigned random name to me after OAuth. Is that a problem?

**Comment by pradeepgangwar** [comment]
Works perfectly now. I did reset DB and tried again. 🎉

**Comment by pradeepgangwar** [comment]
Will start working on custom theme issue.
