### ISSUE TITLE
[3Box Integration] Add 'Upload to 3Box' button to Avatar Builder

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5660]
from: https://github.com/3box/3box/issues/839#issuecomment-567952717

the scope of this ticket is to have an 'upload to 3box' button on the gitcoin avatar builder at https://gitcoin.co/onboard/profile/?steps=avatar#section-title

button should handle the authentication to 3box and the uploading of the avatar; then post a success msg iff it's done.

**Comment by kuhnchris** [comment]
@owocki is that one still around? I did a PR like a year or two ago that included the upload button to the Settings tab - did 3box finally figure out where to put the avatar so we can cross-nuture it? Last info I had was we should use our own namespace (gitcoin.*) and for the avatar thing they'd come back at us...

**Comment by think-in-universe** [comment]
A solution for this feature has been implemented here: https://github.com/gitcoinco/web/pull/5667

**Comment by owocki** [comment]
@think-in-universe awesome; i'm pumped for this :)
