### ISSUE TITLE
As a hackathon sponsor using the normal "fund a bounty" form for hackathon prizes introduces issues with expiration dates being wrong, bounty types chosen incorrectly (traditional rather than contest), and coupons not being applied

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5668]
### User Story

As a hackathon sponsor using the normal "fund a bounty" form for hackathon prizes introduces issues with expiration dates being wrong, bounty types chosen incorrectly (traditional rather than contest), and coupons not being applied.

### Why Is this Needed

These default mistakes from filling out the regular funder form cause unnecessary overhead for the Gitcoin internal team to administer and fix.

### Description

Because the defaults for the funder form are technically designed for the average bounty funder, having a dedicated funder form that is hackathon specific automatically sets the defaults correctly so it cuts down on both the thinking process for the sponsor, and the managing process for Gitcoin admins.

### Current Behavior

Funder forms are set for a bounty funder default, which causes alot of small mistakes that eat up Gitcoin internal operational time.

### Expected Behavior

We want defaults for the hackathon to be pre-filled and set automatically so the sponsor doesn't have to do anything, and the operational costs go to 0.

### Definition of Done
- [ ] agree on a solution (hackathon specific funder form
- [ ] implement defaults
- [ ] redirect hackathon flow to hackathon funder flows
- [ ] ensure redirect and links do not go to the standard bounty flow

### Additional Information

**Comment by willsputra** [comment]
we could surface this hackathon checkbox at the top and set defaults based on it.
<img width="1013" alt="Screenshot 2019-12-30 21 52 16" src="https://user-images.githubusercontent.com/19514207/71587038-cd4c6200-2b4e-11ea-99de-15fa83113b9f.png">

**Comment by frankchen07** [comment]
@willsputra interesting solution, let's talk today about it in sync.

**Comment by danlipert** [comment]
Yes - I think selecting a hackathon event should automatically populate the coupon code, set the expiration date appropriately (although I'm not sure we have a good answer as to what the default expiration should be) and set the type (hackathon bounties are always contest, right?)

**Comment by PixelantDesign** [comment]
How do we help set defaults?

**Comment by thelostone-mc** [comment]
We can ignore the coupon code for this step .

If a user selects hackathon event -> it automatically sets the fee to 0
But this could be easily misused , any funder could avoid paying fee by just selecting a hackathon event 

Where are we on removing the fee all together ? 
Did we decide not to go down that route @frankchen07 / @PixelantDesign  ?

======

Is the understanding that all hackathon bounties are contest bounties ?
Why is it not possible to have a traditional / co-op bounty ? @frankchen07 

we could update the expiration for the bounty to be the same as the hackathon event they've selected BUT is there a scenario where funder will be able override that ?


It's not a nice experience when funder selects a project type and expiration and when he selects a hackathon event -> we overwrite it 

^ needs to be gracefully done

**Comment by frankchen07** [comment]
octavio's solution: move date and event selection together / message them explaining the day they put, confirming the the date that they put / add the expiration date summary at the end 

aditya's solution: move date and event selection together / block user to post expiration date before the hackathon date, until they change the expiration date, if we mess up the dates, it can be painful

longer fix: separate form for hackathon?

**Comment by alexvotofuture** [comment]
Responses to Frank's clarifying questions:

> To clarify, what is the specific issue with expiration date?
Funders are putting in the wrong expiration date for a few reasons. Sometimes we change the hackathon start date, but they use the old start date. Sometimes they choose a longer end date, for fear they won't be able to judge beyond that date, or because they missed the granular end date calendar module (choosing a pre-set time like 1 month instead).

> are people are submitting after the expiration date?
Yes, although sometimes sponsors offer an extension, so this is OK for now. We advise sponsors not to consider submissions beyond the submission date unless they explicitly communicate an extension to the entire hackathon participant base.

> or just that th expiration date is wrong and it’s confusing?
Hackers have complained that the bounty dates suggested an earlier/later submission deadline, causing early/late submissions in many cases. This is the main reason why we want to fix this.

**Comment by frankchen07** [comment]
should the expiration date always match the hackathon end date or not?

if the expiration date matches the hackathon end date, then sponsors should not be offered an extension on submissions, but if they want an extension then the expiration date cannot match the hackathon end date

people can still submit after the expiration date

do we want people submitting after the hackathon end date? (add message to submission so that the hacker knows explicitly that they're submitting after the end date)

**Comment by frankchen07** [comment]
latest update & conversation - creating a separate hackathon flow with coupon code applied and defaults applied, with the same expiration date functionality as it currently exists

**Comment by PixelantDesign** [comment]
![fund issue hackathon](https://user-images.githubusercontent.com/238235/71993482-2bd7a700-3205-11ea-9577-e05d8d1cc835.png)

**Comment by octavioamu** [comment]
but we didn't agree to create a separate form?

**Comment by PixelantDesign** [comment]
We could go a couple of routes:
1) create a separate form and only provide that URL to hackathon funders
2) create a separate form that funders can access from the fund issue page, they'll just have to select **hackathon form**
3) this route where we priortize hackathons and push some of the most relevant info up top 

Thoughts? @octavioamu

**Comment by thelostone-mc** [comment]
Where is the expiration section ? Is that removed for hackathon ? 
Where does it appear for non-hackathon bounties ?

**Comment by willsputra** [comment]
> Where is the expiration section ? Is that removed for hackathon ?
> Where does it appear for non-hackathon bounties ?

Nope not removed! It's currently under the 'Bounty Settings' section in the fund issue form

**Comment by alexvotofuture** [comment]
Resurfacing this one, as @octavioamu is working on it currently.

**Comment by PixelantDesign** [comment]
#6540
