### ISSUE TITLE
Review Submitted Hackathon Projects

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5669]
### User Story

As a hackathon sponsor it is difficult to find project submissions to review for all of my prizes.

### Why Is this Needed

For a sponsor to payout a prize, they must go, one-by-one, to the prize page in order to individually payout each prize.

### Description

They may also alternatively take the flow of going to the prize explorer and using the prize explorer to get access to the prize explorer in order to payout their prizes. Either way, it's still a one-by-one method of finding the prize and looking at each of the submissions on the issue details page. 

### Current Behavior

As a sponsor, there isn't an easy way to find all of my project submissions for review. They have to go to the prize explorer or memorize all the links (Gitcoin or Github) in order to see their submissions (either on the issue activity page, or on Github itself).

### Expected Behavior

Gitcoin can consolidate this information to one central location (dashboard or other) in order to make submission review a breeze.

### Definition of Done
TBD

**Comment by danlipert** [comment]
We can probably come up with a simple solution that solves the most common use case, but I'd be wary of having lots of options if we put payout in the dashboard or similar

**Comment by PixelantDesign** [comment]
Is this a communication issue @alexvotofuture ?

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/issues/5670#issuecomment-570200819

> would having a table view on the dashboard (like what consensys have) make it easier?

^ that could have the payout button included 
The table would give them a consolidated view and link to the basic / advanced payout

**Comment by alexvotofuture** [comment]
Responding to @frankchen07's summarized clarifying questions:

> Is this more of a communication issue for the existing dashboard?

If "dashboard" is referring to the prize explorer this requires sponsors to keep track of all of their separate prize pages and review submissions within each prize page's activity feed (noting only "submitted work"). They then need to track which have been judged/paid out. Some sponsors have handled this using external spreadsheets they create themselves.

I'm not sure if any of our sponsors have used their Gitcoin profile page's "dashboard" to pay out their prizes. From what I've seen in video calls they tend to use the process I outlined above.

> submissions from the hackathon should show up on their dashboard
> if they were using the dashboard, what’s the problem there?
See above.

**Comment by frankchen07** [comment]
tracking which have been judged/paid out is a separate problem (https://github.com/gitcoinco/web/issues/5670)

when you say difficult to find project submissions to review, can you clarify?

**Comment by frankchen07** [comment]
latest conversation: https://gitcoincore.slack.com/archives/CJTTHP53M/p1576608277011500

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/6735

**Comment by PixelantDesign** [comment]
<img width="1655" alt="Screen Shot 2020-06-15 at 9 26 11 AM" src="https://user-images.githubusercontent.com/238235/84663134-bd50f080-aeea-11ea-855e-b7ae35b4d4cb.png">

<img width="1660" alt="Screen Shot 2020-06-15 at 9 25 58 AM" src="https://user-images.githubusercontent.com/238235/84663161-c641c200-aeea-11ea-994d-fcec0f8755fd.png">

<img width="1672" alt="Screen Shot 2020-06-15 at 9 25 38 AM" src="https://user-images.githubusercontent.com/238235/84663166-c80b8580-aeea-11ea-96ea-784794340e73.png">

**Comment by PixelantDesign** [comment]
<img width="1671" alt="Screen Shot 2020-06-29 at 10 09 01 AM" src="https://user-images.githubusercontent.com/238235/86016389-b77e0380-b9f0-11ea-8298-c3812b6954bb.png">

<img width="838" alt="Screen Shot 2020-06-29 at 10 09 57 AM" src="https://user-images.githubusercontent.com/238235/86016399-b9e05d80-b9f0-11ea-8cf9-9a2de549553b.png">

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/6829
