### ISSUE TITLE
As a Gitcoin operator, there's alot of manual intervention with regards to Discord/Mattermost chat that takes up a good chunk of time

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5671]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by Sirlupinwatson1** [comment]
### Well i guess i was thinking about the same. 1 Thing is sure is there is the time respond that i am sure could be way too short for a security breach.

### Like on Discord, there is no, but almost not at all, any security helper for these case. To me, this should be a major and a priosity work order to set in place. Anyone who is wise enough, or who is not.... could lead to we all know what. 

### Just like a block or extension to report and take measure. But also on the other side, the concerned admin or moderator would need the Alert  

> @frankchen07  comment: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

**Comment by alexvotofuture** [comment]
Chatbot implemented for Mattermost has solved this for the most part. Right now it creates a channel per prize. The next iteration will create a channel per project, and add sponsor usernames and the project teammates' usernames. This was our biggest time-suck.
