### ISSUE TITLE
As a Gitcoin hacker, I want a referral system so I could get rewarded for bringing my friends on board

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5677]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

Referral program??? Get a referral kudos immediately upon a friend registering from a hackathon using your link. $$$ if they submit work / win a bounty? 

Quests is a good example of this already. 

Instead of kudos airdrops where they have to Redeem → can we make sure they get airdropped directly to their wallets? 

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
@frankchen07 check out the share feature that @octavioamu built.

**Comment by octavioamu** [comment]
Why we want to focus on this? As we tested with invite to a bounty we didn't saw to much impact or we did? (also we promise send kudos since this was built)
