### ISSUE TITLE
As a Gitcoin hacker, I want something like "Gitcoin Events", a 15-20 person workshop for registrants who want to learn specific skills

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5678]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by alexvotofuture** [comment]
We are starting to ask all sponsors if they want to do a workshop when they onboard to a hackathon. No product help needed for this right now necessarily, but any product ideas on how to increase attendance (as inviting all registrants by email calendar invite has), incentivizing people to join (bulk send kudos for attending), etc. would be great

**Comment by alexvotofuture** [comment]
We are now offering all sponsors a timeslot to host a workshop for hackers. These should be collected in each hackathon's landing page, or some other place on the hackathon platform for hackers to find and watch them.
