### ISSUE TITLE
As a Gitcoin operator, it is a legal requirement to have verified identities for our sponsors and hackers for hackathons, and across our platform

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5680]
### User Story

As a Gitcoin operator, it is a legal requirement to have verified identities for our sponsors and hackers for hackathons, and across our platform

### Why Is this Needed

Legal pre-requisite requirement for KYC/AML & comparison with OFAC lists before we can get help from companies who specialize in this

### Description

For those who are earning > $599 on our platform or submitting to our hackathons, we need to verify them on our platform. In essence, we should verify anyone who has completed work on our platform. We have an existing manual verification feature, but we need to ensure that we get:

1. name
2. address
3. email address
4. ssn
5. are we missing anything else?

an example of some KYC that Consensys tracks:

![Screen Shot 2019-12-23 at 15 39 19](https://user-images.githubusercontent.com/7516920/71385207-d9f31800-259a-11ea-8ccb-049a3fc4464b.png)

### Open questions

1. Do we need pre-verification for all hackers or simply verification for those who complete work? @alexvotofuture 

2. For those in foreign countries, how is it handled? (development-wise, we can focus in on the U.S first, then branch out).

3. Do we want to use identity services such as Jumio, Onfido, and Trulioo?

### Current Behavior

We currently only have a manual verification system ("gitcoin verified").

Connor is manually verifying the identity of hackers who have completed work.

A 1099 PR is open here: https://github.com/gitcoinco/web/issues/4806

### Expected Behavior
- [ ] auto-verification of those who completed work on Gitcoin, either through bounties or the hackathon
- [ ] handling identification for those outside the United States

### Definition of Done
- Build/deliver  v1 that captures the above information and meets those requirements.
- Focus on U.S Workers initially
- Consider identity services for future iterations but we will not pay to use one at this time.
- Review with squad and pm prior to deploy

### Data Requirements
- [ ] are there any data security requirements for storing this kind of data?

**Comment by frankchen07** [comment]
2019-12-27 - needs light defining of the UX

**Comment by danlipert** [comment]
I have concerns about this, but mostly its my personal feelings around KYC and such... that being said I understand why we have to do this - I only ask that we make sure that for non-US people we can handle whatever edge cases and make sure the UX there is not too onerous. I've used Jumio before and its pretty good but its expensive for sure... does ConsenSys have any kind of partners we can leverage for this?

**Comment by frankchen07** [comment]
@danlipert - I would say we start with U.S folks, and with our current volume, we find a non-hacky way to do KYC, and then as we scale and and get more user volume, consider other identity services. 

Would love to hear your concerns in a separate conversation though, perhaps I'm less privvy on some of the details.

**Comment by PixelantDesign** [comment]
There has been some work started by a contributor on this... how does that impact this ticket?

**Comment by frankchen07** [comment]
I believe the contributor ticket was generating a 1099, but it doesn't necessarily collect the KYC information for the number and category of people we want.

**Comment by willsputra** [comment]
what if people just claim that they're not in the US? how might we deal with that?

**Comment by PixelantDesign** [comment]
**Definition of Done:**

- Need to explore identity service so contributors trust this. 
- Does Consensys have an account we can leverage.
- How much does this cost us if Consensys doens't have one.
- Which services would make sense?
- Outline recommended service ux into Gitcoin

**Comment by thelostone-mc** [comment]
I've got the same concerns as @danlipert !
But if we have to do it 

Building it ourselves would mean adding it onto our onboarding flow right ? ->
- would we explain why we this is being collected ?
- would it be as simple as doing it for all users

Ideally all this information would be collected upfront so that the user doesn't have to deal with it while working on a bounty (it creates friction)

Use a 3rd party service might make our lives easier but I've never used one before so a little clueless here

**Comment by frankchen07** [comment]
not in the bounty flow, needs to be in the onboarding flow (profile settings)

how do we get this to existing users vs new users?

what's the scope of this problem? we can't discount the history we've generated, but moving to cross chain QR codes p2p payments would render us compliant in the future (to confirm)
