### ISSUE TITLE
Grants are getting duplicated when scrolling down using a different sort option

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5694]
**Describe the bug**

In the Gitcoin grants page, if you choose a different sort option than the default one( `weighted_shuffle` ) for example: `sort_option=amount_received` and you scroll down, you see the entries getting duplicated. Here is a screen of what's happening:

![image](https://user-images.githubusercontent.com/50027175/71619218-9d8b7180-2bc3-11ea-90a8-db7077e4108c.png)
![image](https://user-images.githubusercontent.com/50027175/71619234-b3009b80-2bc3-11ea-9297-cf9edc121578.png)

**To Reproduce**

Head over to gitcoin.co/grants and choose a different sort option, for example: https://gitcoin.co/grants/?sort_option=match_pledge_amount_100 and scroll down

**Expected behavior**

Grants entries not being duplicated

**Screenshots**

**Desktop (please complete the following information):**

- OS: Pop!_OS 19.10
- Browser: Chromium
- Browser Version: Version 78.0.3904.97 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by kingjacob** [comment]
This occurs with weighted shuffle as well.

**Comment by Solexplorer** [comment]
Looks like this was solved
