### ISSUE TITLE
Transaction out of gas

### ISSUE THREAD

**Issue by 3esmit** [gitcoinco/web#5695]
Im trying to create a bounty but I am afraid of wasting more gas.

https://etherscan.io/tx/0xd460053dae302d19f601147b1143b25dacaeaa66c7eafcd8cda416bbe52d7cce

I did everything as usual, and the transaction failed.

**Comment by 3esmit** [comment]
Please send back the 2000 SNT, because the service was not provided.

**Comment by owocki** [comment]
does the SNT token use a different amount of gas than most ERC20 for a TransferFrom()? I tried to refund this via the metamask default params and also got an out of gas https://etherscan.io/tx/0x4b64db0adb31508cb9e91e3c403e6bf54a37fef7aeaa189a9b499579dde57ac1

**Comment by owocki** [comment]
trying another tx with higher gas now https://etherscan.io/tx/0x9444d206d1f57a236d4069ccf941ebeaaf177a4e3d641055a065c09f0dcb2070

**Comment by owocki** [comment]
looks like that worked!

**Comment by 3esmit** [comment]
Very strange. Thanks.  I will look forward opening the bounty again when this is solved.
