### ISSUE TITLE
add sorting functionality back to the gitcoin explorer

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#570]
https://github.com/gitcoinco/web/pull/523

this was functionality that existed in the old design. you could sort by difficulty, creation time, and value

**Comment by owocki** [comment]
@thelostone-mc would you be up to take this?  happy to tip you

**Comment by PixelantDesign** [comment]
@thelostone-mc for reference:
<img width="888" alt="screen shot 2018-03-08 at 12 32 25 am" src="https://user-images.githubusercontent.com/238235/37134837-4cd489a4-2268-11e8-8072-01becce487af.png">

**Comment by thelostone-mc** [comment]
Consider it done ^_^

**Comment by thelostone-mc** [comment]
@PixelantDesign  Do we wanna add Tech Stack too ? cause this list could be super long as more and more bounties come in

**Comment by owocki** [comment]
we have a list of tech stacks in the `Keyword` model... to adityas point, i dont know if checkboxes are the right input for that though..

**Comment by thelostone-mc** [comment]
Also wouldn't sort boxes be radio buttons? 
And would the sort function be in descending  / ascending ? Ideally it should provide both 
cause it's a sort filter

@PixelantDesign @owocki

**Comment by PixelantDesign** [comment]
Yeah, not sure why I put that there, since checks suggest ability to select multiple. i’ll move it back where it was. 

The tech stack however I intended to have on the left side connecting it with the search. This was the main driver behind this task since it effects the content that changes on the page.

**Comment by thelostone-mc** [comment]
Moving it back. Any input on how to make it look nicer ? 

![help](https://user-images.githubusercontent.com/5358146/37153170-d70d6c6e-2301-11e8-9927-5c27bf6269d9.gif)

not much of a difference but meh

![help](https://user-images.githubusercontent.com/5358146/37153541-097702ea-2303-11e8-8331-d957af80c880.gif)


cc @eswarasai @KennethAshley
