### ISSUE TITLE
idea - there sholud be a bounty that anyone can do within 15 minutes when they join the site

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5703]
there sholud be a bounty that anyone can do within 15 minutes when they join the site; that shouljd be surfaced to them when they join

**Comment by kuhnchris** [comment]
Like a special "entry bounty" that's worth basically nothing to just play with the platform?

**Comment by PixelantDesign** [comment]
Like this idea. I know it has come up before. Something we generate as a get your feet wet exercise depending on the person's expertise?

One that Anyone can do might be tricky. Unless it doesn't necessarily involve coding. I could also see a simple bounty for different skills like design, front-end, back-end, etc? 

Questions bounty/quest?
