### ISSUE TITLE
Ability to ask open ended questions when building a quest

### ISSUE THREAD

**Issue by GrahamMcBain** [gitcoinco/web#5705]
Hoping to use quests as a means of surveying dapp developers. It would help greatly to be able to ask open ended questions in addition to multiple-choice questions.

**Comment by walidmujahid** [comment]
I disagree with this idea. As far as I understood, "Gitcoin Quests is designed to usher users through their *web3 a-ha moments* in a fun informative way" - /quests. 

It is bad enough that I feel that some of the quests -perhaps one or two at the moment, and I have went through all the quests- that I have come across seemed to be geared towards advertisement or promotion of a product. 

I do not think adding polls/surveys to the quests is what @owocki had in mind for the product. I certainly would not want to see something like that when I am expecting potential "web3 a-ha moments".

Instead, if surveying dapp developers is the goal, then perhaps a "Surveys" product could be added to Gitcoin where people can pay dapp developers for their time in answering survey questions.
