### ISSUE TITLE
Gitcoin Kudos receive message looks weird

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#5706]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/761911/71747107-1530f900-2e6f-11ea-8cf4-958a16e313bc.png)
Huge space between the page header, for some reason a copy right link in the middle, and the kudos marketplace next to it?
...is that the actual footer?

**To Reproduce**
Receive Kudos successfully (for example by using the friday airdrop)

**Expected behavior**
UI design looking fine

**Screenshots**
see above

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Firefox
- Browser Version: latest stable

**Comment by PixelantDesign** [comment]
Thanks @kuhnchris! Wanna help us fix it?

**Comment by kuhnchris** [comment]
do we have an official design how this should look? if yes I can try to adapt it to that.
