### ISSUE TITLE
Sub Menu Items do not show on /onboard/profile?steps=avatar

### ISSUE THREAD

**Issue by emmaodia** [gitcoinco/web#5707]
**Describe the bug**

Sub Menu Items do not show on /onboard/profile?steps=avatar.
When a user redirects to the above page, navigation becomes cumbersome as the sub menu items do not appear.

**To Reproduce**

1. Go to your profile e.g https://gitcoin.co/emmaodia
2. Click on your image to update avatar
3. When you get to https://gitcoin.co/onboard/profile?steps=avatar 
4. Sub menu navigation items do not show.

**Expected behavior**

When a user navigates to /onboard/profile?steps=avatar The sub menu items MUST show.

**Screenshots**

![Alt text](https://raw.githubusercontent.com/emmaodia/gitcoinco-issues/master/with-navigation.png "with navigation")
with sub menu navigation items

![Alt text](https://raw.githubusercontent.com/emmaodia/gitcoinco-issues/master/without-navigation.png "without navigation")
without sub menu navigation items

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 18.04
- Browser: Firefox, Chrome, Brave

**Additional context**
A lack of the sub menu navigation items makes navigation cumbersome.

**Comment by emmaodia** [comment]
@owocki

**Comment by PixelantDesign** [comment]
Thanks for the report @emmaodia. Some menu items were hidden by design so that users aren't distracted and move out of the onboarding flow.
