### ISSUE TITLE
Integrating with the Stellar Network for Funding and Payments 

### ISSUE THREAD

**Issue by ohsix1** [gitcoinco/web#5708]
### Discussion

[comment]: I think the Stellar Network could facilitate the ability for bounties to be funded using any value source (e.g, if it is currency value, then funding can be and available of both fiat and crypto).

As a amazing as Ethereum is from a VM-standpoint and as amazing as Gitcoin is for being a DAPP, I think relying too heavily on a bloated system like Ethereum is a bit --- how to say, an anti-pattern? I think modularity can be introduced by using Ethereum for authentication and simple logic, IPFS or something similar for decentralised backend storage, and the Stellar Network for what it's good at --- payments.

**Comment by walidmujahid** [comment]
My level of familiarity with the Gitcoin backend and codebase is low. However, I sense there is a possibility that Gitcoin is rather integrated with Ethereum.

> a bloated system like Ethereum

Bloated? 

> IPFS or something similar for decentralised backend storage

I had previously assumed that Gitcoin was already using IPFS, however, I may be thinking of bounties and issues I have seen regarding integrating profiles/avatars with 3Box.

> I think the Stellar Network could facilitate the ability for bounties to be funded using any value source (e.g, if it is currency value, then funding can be and available of both fiat and crypto).

I would label myself a fan of the Stellar Network yet I am uncertain as to how Gitcoin could use it. The idea of being able to fund a bounty with any "value source", as you put it, is interesting. 

Outside of Gitcoin, the idea might potentially enable MetaMask -or a MetaMask Plugin- in bringing the ability to recieve or send funds from any "value source" to Ethereum DApps -like Gitcoin. 

The fact that Stellar already provides working infrasturcture oustide of any existing Ethereum protocol/infrastructure experiments is a rather postive point in my opinion

**Comment by kuhnchris** [comment]
Hi there - IPFS is already being used for Kudos, not sure if we also have a IPFS node in use for the bounties, but I doubt it since the data is purely transfered between the standard bounty contract (a eth VM contract). There may be some changes coming tho as we explore more options.

basically, I do not know what Stellar requires, but if it requires another side chain we need to take care about then I doubt it will have much success. Currently most of the things run via Infura which basically abstracts the gETH. With interfaces like that we MAY see a chance to integrate it.

cc @thelostone-mc regarding crosschain topics

**Comment by owocki** [comment]
thanks @ohsix1 do u have any contacts at the stellar foundation we could talk about this with?

**Comment by ohsix1** [comment]
@kuhnchris I don't think Stellar has an equivalent of Infura. Perhaps the closest thing might be this proposal draft: https://galactictalk.org/d/2213-public-node-nodes-funded-by-community

Perhaps more discussion form the Stellar community could shed more light: https://galactictalk.org/d/2263-integrating-stellar-into-ethereum-tron-dapps

@owocki Well, besides the community forum, maybe in touch with someone from the Stellar foundation team might be of help: https://www.stellar.org/foundation/team

I'm afraid I don't specific contacts, though.

**Comment by thelostone-mc** [comment]
Closing this out for now as we don't see moving away from infura. will reopen this if the team decides otherwise
