### ISSUE TITLE
Code showing in text

### ISSUE THREAD

**Issue by AnneConnelly** [gitcoinco/web#5715]
Hi, In my grant description there's code language that's showing up. How can I remove this?

https://gitcoin.co/grants/211/trust-graphic-novel?fbclid=IwAR2zlVif72Zcwzd7UqAqc2IhURrLY4MY_gsZnacbD-r-XmRdq46elMldqq4

![image](https://user-images.githubusercontent.com/16226861/71845949-6ae7ea00-3097-11ea-8337-1a237b0cce11.png)

**Comment by PixelantDesign** [comment]
Thanks for the report @AnneConnelly. We will take a look!

**Comment by danlipert** [comment]
@AnneConnelly what are those query parameters in the URL? Those are causing the issue, just going to https://gitcoin.co/grants/211/trust-graphic-novel?tab=description works as expected

**Comment by molecula451** [comment]
If unintentionally query was mistype. Clean browser history and re-enter to correct address

**Comment by molecula451** [comment]
If unintentionally query was mistype. Clean browser history and cookies and re-enter to correct address
