### ISSUE TITLE
update sync_github management command to sync comments on bounties we care about

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#572]
https://github.com/gitcoinco/web/blob/master/app/marketing/management/commands/sync_github.py#L93-L94

these should be stored as `GithubEvent`s

depends upon https://github.com/gitcoinco/web/pull/458

**Comment by rahulpat** [comment]
Hi @owocki Is there still a bounty on this ? If yes, is it up to date?

**Comment by owocki** [comment]
yes its an active ticket.. no, there is not currently a bounty on it.  you interested in working with us on this?

**Comment by rahulpat** [comment]
@owocki yeah, sure.

**Comment by kuhnchris** [comment]
Did something come out of this?
