### ISSUE TITLE
error in grant creation

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5722]
from john kelleher on email

```
To whom it may concern,

I just created the following grant:

https://gitcoin.co/grants/249/open-raise

See the transaction here:

https://etherscan.io/tx/0xe564a3fe1b7e12d770c33000f65bb2ff15f5750b922aff0b1f6d3bcdcf942964

I am getting the message "Looks like your grant has been created with 0x87C308B70AD9eacbef0Cb43514a104684eDB8A5D. Switch to take action on your grant."

However, I created it with 0x639C52b5475a44c5bb876A7e4E7Ee778A3E2d136, which can be seen in the etherscan link above. I am not sure what caused this.

Best,

John Kelleher
```

**Comment by owocki** [comment]
from john on email: Hey Kevin.  I just realized that the address that is being displayed is from one of the accounts I have on my MetaMask.  I was probably connected to it before switching to the one I ended up using for the transaction.

**Comment by molecula451** [comment]
I suppose this e-mail is coming from @jpkcambridge. 

Lastest grant https://gitcoin.co/grants/249/open-raise

I can see that this user did not even got a [Created Grant] log on the Grant Activity tab

![onlyupdated](https://user-images.githubusercontent.com/41552663/71926631-1a8d8c80-316a-11ea-95d7-6e9ce4f9f6bc.png)

In fact the error it's outputing expected owner address 

Which is the one he stated above <code> 0x87C308B70AD9eacbef0Cb43514a104684eDB8A5D </code>

And it can even be found in the debugging console 

![output](https://user-images.githubusercontent.com/41552663/71927888-dea7f680-316c-11ea-9636-1e28322437ce.png)

And it's also different from the recipient funding grant address <code> 0xd7FE300587d41ed0e8B6A2bEd5a1B2BB4fCdaD9E </code> which is an old activity address (probably from the same user) which had activity on the platform months ago. And  is not even the same as the one he said he created the grant <code> 0x639C52b5475a44c5bb876A7e4E7Ee778A3E2d136 </code>

Where grants behind this one has it's logs .

[Created Grant] and matching addresses 
![matching addresses](https://user-images.githubusercontent.com/41552663/71929304-b8378a80-316f-11ea-99d6-cb4b1289b3dd.png)


![created](https://user-images.githubusercontent.com/41552663/71929095-44957d80-316f-11ea-947d-f6187420823e.png)

Another 

![createdmatches](https://user-images.githubusercontent.com/41552663/71929522-2c722e00-3170-11ea-97ed-ac634da1c288.png)

![matchingadd](https://user-images.githubusercontent.com/41552663/71929538-33993c00-3170-11ea-94fe-caead8c74338.png)

**Comment by jpkcambridge** [comment]
jpkcambridge here.  One other thing: the webpage crashed shortly after I submitted the grant.  Let me know if I can help.  I may create a new grant in the meanwhile.

**Comment by jpkcambridge** [comment]
@molecula451 And the recipient funding grant address is correct, and was intentionally entered.

`0x639C52b5475a44c5bb876A7e4E7Ee778A3E2d136` and `0x87C308B70AD9eacbef0Cb43514a104684eDB8A5D` are both under my metamask.  I suspect I was on the 0x87C one when I initially visiting the grant creation page and then switched to the 0x639 one to submit the application.

**Comment by molecula451** [comment]
I am replicating and I also getting second account on the MetaMask address
![replicate](https://user-images.githubusercontent.com/41552663/71931096-68f35900-3173-11ea-9f00-ed0fbf20f265.png)


<code> 0xB44 </code>
![replicate1](https://user-images.githubusercontent.com/41552663/71931038-44977c80-3173-11ea-8e1a-cb3fb93ab0b6.png)

**Comment by molecula451** [comment]
It seems to me that our web3 provider it's giving us conflict with our grant creations

**Comment by molecula451** [comment]
@jpkcambridge Try to create another grant and have a 3rd MetaMask account. Let us know if it's choosing that new one or first-second

**Comment by jpkcambridge** [comment]
@molecula451 I created a new one but this time I just made sure I was on my intended Metamask account before visiting the new grant page.  This one worked fine: https://gitcoin.co/grants/254/open-raise-2

**Comment by jpkcambridge** [comment]
@molecula451 Let me know if you want me to experiment again.  I didn't try having 2 more Metamask accounts yet.

My suspicion is that your web3 code is picking up the active injected address, and then not getting updated after the user switches account?  Possibly linked to the webpage crashing (or maybe being closed) after submission?  When you reproduced, did you switch accounts?

**Comment by molecula451** [comment]
Your feedback it's extremly helpful. I can see now in the debuggin console your address <code> 0x639C52b5475a44c5bb876A7e4E7Ee778A3E2d136 </code> it's being taken. I asked for 2 more address because I want to dischard after grant creations it's automatically selecting a new account on the web3 provider or not. Please do and let me know @jpkcambridge

**Comment by jpkcambridge** [comment]
@molecula451 Let me just understand the process you are looking for:

1) Create a new Metamask address

2) Leave active Metamask address as new one created in step 1/

3) Go to New Grant page

4) (should I change my metmask address?)

Could you edit the above steps to what you are looking for?  Also, I already have more than 2 metamask addresses set up.

**Comment by molecula451** [comment]
Nice.

1.  Create some New MetaMask Address

2. Switch to the one that you intented to use on the grant

3. Go and create the grant

4. Check to see if the grant chooses the address you intented to use or select a new one

Since you told me you did not created any address. You went ahead and created a new grant https://gitcoin.co/grants/254/open-raise-2   and I am believing you hadn't more address when creating so it went ahead and selected the actual you expected. Isn't it ?

@jpkcambridge

**Comment by jpkcambridge** [comment]
@molecula451 When I created https://gitcoin.co/grants/254/open-raise-2 I did not create new addresses but I already had several other Metamask addresses.  My Metamask had the same number of addresses when I created https://gitcoin.co/grants/249/open-raise.

I was not paying attention the first time, but I suspect my Metamask was initially on the address that became stored as the contract owner, even though I paid for the contract creation with a different metamask address.  The website crashed after I submitted, so this might somehow be related.

The second time I was sure to select the Metamask address I intended to use before visiting the new grants page.  Also, this time the site did not crash after submission.

I will test my theory about what happened again by entering the new grants page while another Metamask address is selected.  If that doesn't reproduce the problem, maybe we should try something else.

**Comment by jpkcambridge** [comment]
@molecula451 I have reproduced the error and it was in line with my suspicion.  Going to enter the details here now.

**Comment by jpkcambridge** [comment]
Steps for reproducing error (I had a Metamask address with ETH and a Metamask address with 0 ETH):

1) Select a Metmask address with 0 ETH
2) Visit https://gitcoin.co/grants/new
3) See the following message:
<img width="1135" alt="Screen Shot 2020-01-07 at 5 45 10 PM" src="https://user-images.githubusercontent.com/874683/71935961-1e271080-3176-11ea-978c-56133fc7a481.png">
4) Select Metamask account to one with ETH
5) See that first metamask address is populated in form (this is wrong!):
<img width="1129" alt="Screen Shot 2020-01-07 at 5 45 32 PM" src="https://user-images.githubusercontent.com/874683/71936004-41ea5680-3176-11ea-9516-8b9e60597f7c.png">
6) Fill in form and paste 3rd address in for "Recipient Wallet Address"
7) Submit (see https://etherscan.io/tx/0x2e6ba19f2f203470e9894b81563a340aaeb8a990e26d0158a41436ca7e53515e)
8) After transaction approved, see this error message: 
<img width="1184" alt="Screen Shot 2020-01-07 at 5 47 38 PM" src="https://user-images.githubusercontent.com/874683/71936111-870e8880-3176-11ea-94d0-9c28ff968907.png">

**Comment by jpkcambridge** [comment]
@molecula451 My guess is that when the "Recipient Wallet Address" form is initially populated, you are also populating a contract owner field with that initial address.  And I suppose the web3 code is not updating that contract owner field when the user switches accounts.

**Comment by jpkcambridge** [comment]
@molecula451 I think this is where the contract owner address is initially set:

https://github.com/gitcoinco/web/blob/f2f9dfdc01def11fb6691f8ea693036bb3b2c210/app/assets/v2/js/grants/new.js#L66

Haven't looked for the code that would handle an account switch by the user, but guessing that something like this line here which sets the contract owner address should be added where the account switch handling is.
