### ISSUE TITLE
Grants "Total Funded" count is incorrect

### ISSUE THREAD

**Issue by markusbkoch** [gitcoinco/web#5723]
**Describe the bug**
The amount displayed in the "Total Funded" field of a grant page doesn't match the amount that was donated.

**To Reproduce**
See https://gitcoin.co/grants/233/ethereumetl?tab=activity  
As of now, it shows total funded is 105 DAI, but that amount takes into account a 25 DAI donation by user rraina. However, that donation never went through. The [approve transaction](https://etherscan.io/tx/0xf04395dce000d1dfd164934d8f1496e2a873d8449129aa8e78143c5437bf8d02) went through, but [the transfer failed](https://etherscan.io/tx/0xdd712a1be2cba3f201cd68a7abc7911b5da7007380e633b744ccafaaa2c2b17c) because the account didn't have enough DAI in it.

**Expected behavior**
I would expect the total funded value to match the sum of the values transferred, not the sums of the values approved.  
I would expect the links to Etherscan next to each contribution to point to the transfer, not the approve transaction.

**Screenshots**
![image](https://user-images.githubusercontent.com/34865315/71920874-7a823400-3166-11ea-8fc1-d667ec5c4276.png)

**Desktop (please complete the following information):**
- OS: Mac OS 10.14.6
- Browser: Google Chrome
- Browser Version: 79.0.3945.88

**Additional context**
Not sure how this might be affecting the CLR match computation. All contributions were in DAI, so this doesn't seem to be related to #4362

**Comment by owocki** [comment]
internal comment -- suggested fix: we should index the activity tab on whether the `transferFrom()` was successful, not just the `approve()`

**Comment by markusbkoch** [comment]
Seems the same thing is affecting the leaderboard too?
![image](https://user-images.githubusercontent.com/34865315/71923012-d484f880-316a-11ea-98fd-2414bb765026.png)
https://gitcoin.co/timdaub
[Approve 1.337e+22 SAI](https://etherscan.io/tx/0x0bdeeb0b78f1c94a7dde2dfc074bc79252f0fe93b5dc714c70ee2d6e5a8888f7)
[Failed transfer](https://etherscan.io/tx/0x1229bf1fded77f3fb1b0d3050b31ee37cc081e4a0b4d4fe9e3027d9d300b8ff1)

**Comment by owocki** [comment]
i put in a fix for the leaderboard :)

heres a root cause fix spec i typed up ... let me konw if u think it looks ok https://github.com/gitcoinco/web/issues/5762
