### ISSUE TITLE
Tribes - Explore Tribes Page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5735]
### User Story

As a Gitcoin contributor I'd like a way to easily explore the top OSS organizations that are currently on Gitcoin.

### Why Is this Needed

As we roll out Tribes, we want to set up an experience that is clear from the Tribes landing page (where they learn about what Tribes is) all the way to a Tribe's Organization page (e.g gitcoin.co/gitcoinco). 

In order for the flow to logically make sense from the Tribe landing page to an organizations page, we want a page that showcases the top open source organizations so contributors / hackers can easily check out a couple of Tribes pages from one location.

### Description

The order of the tribe is based on the organization leaderboard activity.

Each join button should allow the contributor who is viewing the page to join a bunch of tribes at once (click on multiple join tribes buttons as they wish). Clicking the button should yield it to be green (like below):

<img width="556" alt="Screen Shot 2020-02-10 at 3 41 33 PM" src="https://user-images.githubusercontent.com/7516920/74188312-06262f00-4c03-11ea-9e1f-462f48ad3666.png">

Clicking on the name of the tribe and the logo should lead to the organization page.

"Members" should show how many tribe members are in that organization, and should also show the number of bounties and also the value of those open bounties.

Sort filter should allow us to filter the tribes manually if the user desires to do so.

### Current Behavior

There isn't a consolidated page that shows top OSS organizations. The user directory is the closest thing we have, but the experience is jarring if we deposit them from a landing page to a directory that has alot of filters, and has mixed search results with users.

### Expected Behavior

A responsive Tribes exploration page that highlights top OSS projects.

### Definition of Done
- [ ] design sketch built to specifications

### Data Requirements
- [ ] google analytics tracking (page views, funnel & drop-off)

### Additional Information
<img width="368" alt="Screen Shot 2020-02-10 at 3 36 56 PM" src="https://user-images.githubusercontent.com/7516920/74187858-3de0a700-4c02-11ea-8cac-12d5b9d2ee9a.png">

**Comment by octavioamu** [comment]
how someone get into this page?
where is linked?
How we know today about a tribe since every org can be a tribe?
What about the use of this page, like pagination, filters?
What is this page for?

**Comment by PixelantDesign** [comment]
**how someone get into this page? where is linked?**
when the experience is complete, a person can arrive by clicking on top nav or from the landing page. we should hide until end of feb launch.

**How we know today about a tribe since every org can be a tribe?**
Every org = or has a tribe

**What about the use of this page, like pagination, filters?**
These would be great, but are nice to haves for V1. 

**What is this page for?**
- at a glance view/browsing open source web3 tribes/orgs on gitcoin
- view amount bountied by that org
- view # of tribe members
we could expand later

**What is a top org?** 
We could pull from the leaderboard of top orgs, top 100

**What are that metrics?**
Page views/click throughs for each of the orgs

**My recommendation is to create an area for each user with recommendations of orgs to join based on their previews contributions.**
Not sure I follow, could you elaborate?
