### ISSUE TITLE
Grants - Disallow self-funding **especially** during CLR matching

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#5751]
### User Story

As a user I should not be able to fund my own Grants during CLR matching rounds and game the system.

### Why Is this Needed

The CLR matching system is supposed to allocate a pool of money to a different number of grants depending on the interest shown to these grants.

Interest is measured by how much money is donated and by how many individual accounts.

Donating to yourself is gaming the system in order to take more money from the pool and should be prohibited.

It is not a black and white matter and there is various threads of discussion in [this](https://twitter.com/LefterisJP/status/1215026516091908103) twitter thread. But I strongly believe that Gitcoin should prohibit this behavior.

### Description

*Type*: Feature

### Current Behavior

If you visit the Gitcoin page of a grant you created, the UI allows you to fund your own grant.

### Expected Behavior

For the reasons presented in the "Why this is needed" section I would expect to not be able to fund a grant that I have created.

### Definition of Done

When the website disallows (gray out?) the "fund" button if this is a grant you have created yourself.

**Comment by owocki** [comment]
d791b69cba00f5dd15a75b1fc3daeb1efb1c5128 should handle this

**Comment by owocki** [comment]
will get it deployed today
