### ISSUE TITLE
Abridged Grant transition

### ISSUE THREAD

**Issue by OKDuncan** [gitcoinco/web#5756]
### Fixing the DAI --> SAI issue
new grant page: https://gitcoin.co/grants/274/abridged-2

### For the grants

THANK YOUU

**Comment by owocki** [comment]
thanks this is the old one right? https://gitcoin.co/grants/133/abridged

**Comment by owocki** [comment]
@OKDuncan just making sure ^^

**Comment by OKDuncan** [comment]
Yes! Thanks

**Comment by owocki** [comment]
ok just transfered things!
