### ISSUE TITLE
Gitcoin Grant amounts sometimes wonky in CLR round 4

### ISSUE THREAD

**Issue by Jeff-Emmett** [gitcoinco/web#5764]
Hey team!

Browsing grants, I noticed some projects seemed to have amounts carried over from CLR round 1, 2 & 3 that made their contribution levels seem off:

Some mention that funds may have been raised in past rounds:
![image](https://user-images.githubusercontent.com/46964190/72168146-92da9480-339a-11ea-9b83-bfbdc460db34.png)

Others not:
![image](https://user-images.githubusercontent.com/46964190/72168204-b0a7f980-339a-11ea-96bc-98a27994a146.png)

Just seemed like there may be something glitchy going on there.  From a user perspective, I would say the amounts that should be displayed are from current rounds, with perhaps a note of historical raise through previous rounds.  Just my opinion!

Cheers all,

**Comment by thelostone-mc** [comment]
@Jeff-Emmett Ah so only contributions made during the CLR period are considered while calculating it ! The pervious rounds data are present just as an info but don't influence the who the CLR is split 

But yes the UI could be imporved ! 
Thanks for letting us know :)

**Comment by Jeff-Emmett** [comment]
Yes, just commenting on the UI from a user perspective. =)

Cheers!
