### ISSUE TITLE
Difficulty contributing to Commons Stack grant

### ISSUE THREAD

**Issue by Jeff-Emmett** [gitcoinco/web#5767]
Hey team,

In an attempt to fund the CS grant in SAI on a recurring basis (2 x 15 days apart), I get to the metamask screen but am not able to click 'confirm', only 'reject'.

![image](https://user-images.githubusercontent.com/46964190/72169338-eb129600-339c-11ea-9c5d-08e1118cfde8.png)

Any thoughts as to why that might be the case?

Cheers,

**Comment by owocki** [comment]
hmmm... i've never seen this before.. seems like its a metamask issue tho

**Comment by Jeff-Emmett** [comment]
Turns out I'm just a bad blockchain user! No gas in my new wallet, embarrassing!
