### ISSUE TITLE
Do non-DAI contributions trigger CLR matching?

### ISSUE THREAD

**Issue by AlexeyAkhunov** [gitcoinco/web#5770]
Looks like the don't. We got a large contribution in WETH (8.8 WETH), but I did not see the CLR matching amount change at all

**Comment by owocki** [comment]
@danlipert @thelostone-mc i'm pretty sure they do right.. i dont see anything in the CLR code that discounts non DAI transactions

@AlexeyAkhunov note that the CLR module only refreshes every 4 hours.. there is a time esteimate of when it should refresh next on the module.. maybe it just hadn't refreshed immediately..

**Comment by frankchen07** [comment]
@AlexeyAkhunov. WETH contributions should be counted, and there is a refresh time on the calculation.

@thelostone-mc to confirm, but I'm fairly sure.

**Comment by danlipert** [comment]
Any token that we have a conversion rate to USD in our DB does indeed count - tokens that don't have pricing data generally available may not be counted
