### ISSUE TITLE
As a grant admin I want the world to see the true amount of DAI received (so the amount minus fees)

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#5773]
### User Story

A user has created a grant. He has been funded 100 DAI according to the "Total Funded" button in the UI but in reality due to the various choices of fees that funders have chosen he has only 80 DAI in his grant account.

### Why Is this Needed

This is needed in order to be able to show a clear picture of how much the grant has received, and not how much the funders have sent. It's also important for accounting, for the jurisdictions where the grant owner has to file a tax report, having the correct number in the UI would make it easier instead of having to write a script going through all transactions to actually get the right amount.

### Description

"Total Funded" should show the amount minus the fees (and minus all pending and failed transactions).
For the amount + fees perhaps a different UI component could be added? Because both numbers have some significance.

**Comment by owocki** [comment]
@LefterisJP do u have an example of a grant that has the above attributes?  right now i'm thinking the total amount of funds in the grant address are probably the total amount minus
1. gitcoin tips
2. phantom fundings

the following should NOT be included in the total funding amount
3. any failed transactions 
4. ethereum tx fees

**Comment by LefterisJP** [comment]
Hey @owocki 

Yes basically every grant out there.

> right now i'm thinking the total amount of funds in the grant address are probably the total amount minus
>
> 1.gitcoin tips
> 2.phantom fundings

That's exactly what I meant. The total amount funded in the Grants UI should match the actual funds that reached the grant. So the gitcoin 5% fee should be excluded.

I assume this is not yet happening, judging from the grant for the Rotki app where some funds are missing.

![2020-01-13-220715_123x89_scrot](https://user-images.githubusercontent.com/1658405/72292131-13c2b600-3651-11ea-8a80-24df592a0161.png)
![2020-01-13-220706_338x305_scrot](https://user-images.githubusercontent.com/1658405/72292141-17eed380-3651-11ea-9554-41a24477426d.png)

If you don't want to exclude the gitcoin fee, perhaps have two numbers? Total funded net and total funded gross?

**Comment by owocki** [comment]
7c520cac11a6da38b7012fbbe968a2b329b85a96 will seperate out the voucher fundings from the other fundings on the transactions tab... which should make it easier to denote

**Comment by LefterisJP** [comment]
@owocki Perhaps we are not talking about the same thing. Take a look at this tweet to see what I mean:

https://twitter.com/rotkiapp/status/1219981532800176129

The actual amount seen in the recipient address is ~ $1088. The UI says we got funded with $1129.

I want the UI to show the actual amount. For multiple reasons. Examples:

- Taxes. We probably need to pay taxes on this grant and would like to pay taxes on the actual amount.
- Expectations. The community sees that X amount of funds is received and has certain expectations. They should know the actual amount received and not the amount sent. Granted, in the example case of Rotki the difference is small, but as a principle I strongly believe you should show the actual amount.

I assume that the reason the amount differs is the 5% gitcoin fee. That's fine, but it should be shown in the UI.

**Comment by owocki** [comment]
thanks. yeah i agree we should not include the gitcoin fee amount in the total. ill push an update to manage this as soon as i get some cycles.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/5904 should be a strong leap in the right direction here.

**Comment by LefterisJP** [comment]
Yeah that looks better. I do not remember the number in my grant to see if it renders less for me too though. But the individual contributions render fine with the gitcoin contribution
