### ISSUE TITLE
Wrong number of contributors shown in different places

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5775]
**Describe the bug**

The number of contributors is not correct in multiple places. Taking for example the grant published by gitcoin.
1: 
![image](https://user-images.githubusercontent.com/50027175/72206391-aa467a00-348d-11ea-800d-c24640436492.png)
2:
![image](https://user-images.githubusercontent.com/50027175/72206405-c34f2b00-348d-11ea-9b2c-9f09ee62a7c7.png)
3:
![image](https://user-images.githubusercontent.com/50027175/72206416-f5608d00-348d-11ea-905a-ff93f680944e.png)

**To Reproduce**

Go [here](https://gitcoin.co/grants/) and follow the screenshots posted above, I have tested with this grant: `Gitcoin Sustainability Fund` but it happens with multiple ones.

**Expected behavior**

Correct number of contributors

**Comment by owocki** [comment]
oooh i think the front one isnt showing the phantom funds  .. will look into this week

**Comment by owocki** [comment]
895d65829e2b4c1261d857c3de9225b89b3bf643 will fix this
