### ISSUE TITLE
Improved “checkout” experience

### ISSUE THREAD

**Issue by econoar** [gitcoinco/web#5778]
It’s common to give to multiple grants at a time but there is really no UX workflow for this other than going 1 by 1. 

It’d be great to have some type of shopping cart style checkout where you can add multiple grants and what amount you want to each on the same page and then “checkout” and all the txs come in at once.

**Comment by owocki** [comment]
@econoar is your expectation that you only have to issue one tx, or that you'd issue multiple tx's, but all on the same page?

**Comment by econoar** [comment]
If I had 5 grants lined up I’d prefer just 1 “checkout” button. 

It’s fine if all the txs come in 1 by 1 then for me to sign. I’d say a nice to have is they are all batched into 1 :)

**Comment by owocki** [comment]
@willsputra would u be able to whip up some designs for this in the coming weeks?  for round 5 itd be a great UX tweak to have this put together

**Comment by willsputra** [comment]
yep will work on it!

**Comment by owocki** [comment]
any feedback?

![cart](https://user-images.githubusercontent.com/513929/73677874-70275d00-4674-11ea-8280-8c23baadb5d9.jpg)

**Comment by owocki** [comment]
https://twitter.com/owocki/status/1224392893239967745
