### ISSUE TITLE
payment reminder error

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5780]
from a customer:

```
Hello Gitcoin,

I’m writing this email because I just tried to use the “Payment Reminder” button for the issue 
https://gitcoin.co/issue/WalletConnect/walletconnect-monorepo/205/3766 for the second time and it threw and error. It has been 8 days since the issue has expired and almost a month since I submitted the work. I don’t know if this is normal or not since is my first time working with Gitcoin but how is the situation managed if any of the submissions have been paid?

Thank you in advance,
Federico
```

**Comment by owocki** [comment]
@fmiras what did the error say?

@iamonuwa any chance u wanna look into this?

**Comment by iamonuwa** [comment]
Alright

**Comment by fmiras** [comment]
![image](https://user-images.githubusercontent.com/14364153/72277089-0e914700-3610-11ea-96f0-b56124dd9bfa.png)
This is what happens when clicking on "Send Payment Reminder" after accepting the disclosure in the modal. 

Maybe network details helps:
![image](https://user-images.githubusercontent.com/14364153/72277200-4d270180-3610-11ea-87d2-7269d1c455a9.png)

The request response is:
```json
{"success": false}
```

**Comment by owocki** [comment]
@iamonuwa any interest in working on this?

**Comment by iamonuwa** [comment]
Yes, @owocki am investigating it now

**Comment by iamonuwa** [comment]
Initially, I got this error when my network was somewhat not stable, but trying again now, its resolved. Was able to successfully send a payment reminder for this https://github.com/gitcoinco/web/issues/4465

**Comment by iamonuwa** [comment]
cc: @owocki @fmiras

**Comment by thelostone-mc** [comment]
@fmiras was this the first payment reminder you'd sent out ?
Also could you give a shot again (cause @iamonuwa said it did go through )

**Comment by fmiras** [comment]
@thelostone-mc The first time it didn't threw any error, I suppose it worked fine. This error is happening since the second time, and a lot of more times I tried. I just tried again a few minutes ago and It threw the same error again.

**Comment by owocki** [comment]
hmmm seems related to some sort of rate limiter if it only hapens on the second time
