### ISSUE TITLE
As a user, I want to donate/receive grant funds in the form of cDAI

### ISSUE THREAD

**Issue by codyborn** [gitcoinco/web#5781]
### User Story

As a user, I want to donate/receive grant funds in the form of cDAI.

### Why Is this Needed

As a Grant funder, a majority of my DAI assets are represented as cDAI. To donate DAI, Grant funders that hold cDAI have the extra step of converting to DAI. This increases the friction for donations which decreases funders willingness to donate.

Additionally, each cDAI automatically earns interest over time. While Gitcoin funds sit in the custody contract as DAI, they're missing out on earned interest. Assuming the following:

- $100k in grants paid out [monthly](https://gitcoin.co/results)
- Gitcoin grants contract holds custody of these funds for roughly one month
- Compound interest rate is [5.88%](https://loanlist.io/asset/dai/compound)

The amount of interest lost is more than $5,880/year.

### Description

*Type*: Feature

### Current Behavior
cDAI cannot be donated. Donation receivers cannot hold their funds as cDAI.

### Expected Behavior
cDAI should be an option to donate. Funds should be pooled as whatever token (including cDAI) receiver wishes automatically.

### Definition of Done
- cDAI is an option to donate/receive
- Receiver can automatically have donations exchanged into token of choice (including cDAI)

### Data Requirements
- cDAI donation market share
- cDAI receiver conversion percentage

**Comment by markusbkoch** [comment]
There's a form at https://gitcoin.co/submittoken (although I submitted CHAI a few days ago and it hasn't been added yet)

**Comment by owocki** [comment]
can someone submit cDAI through the above form + we can get it listed?
