### ISSUE TITLE
Stuck on funder/contributor

### ISSUE THREAD

**Issue by iamthefastestmanalive** [gitcoinco/web#5783]
Hi Gitcoin,

Something went wrong when creating my account, I reckon. I keep getting asked if I'm a funder or a contributor and hitting the buttons doesn't do anything. (Also my avatar isn't transfered from github and my username has some weird stuff added to it.

![Screenshot 2020-01-13 at 09 42 22](https://user-images.githubusercontent.com/59821625/72242652-3968a480-35ea-11ea-9154-981f5ce10227.png)

I can't fund any grants like this! Thanks in advance for any help!

Barry

**Comment by owocki** [comment]
@iamthefastestmanalive just reset your account. try now?

**Comment by iamthefastestmanalive** [comment]
Yep, that did the trick! Thanks @owocki !
