### ISSUE TITLE
look into bloom for sybill resistence on gitcoin grants

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5784]
bloom https://bloom.co/

If you're going to do the bloom integration can you design it as a standalone thing where if an address gets verified it gets a non-transferable erc721 or something like that?

**Comment by dereksilva** [comment]
Yes, Bloom Share Kit requests contain a nonce. and the sharing proof also contains timestamps. The only potential issue is that the ERC-721 would either go to the Bloom DID ETH public key, or to an address specified by the Gitcoin user. I imagine you'd want the latter, so you could either have the Gitcoin user:

- sign a message linking the fund holding keypair to their Gitcoin account (which you already do), or
- use Share Kit to link a BloomID to their Gitcoin account

Happy to help you work through any other questions you have about this!
