### ISSUE TITLE
Add projects to people profiles

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#5787]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a hackathon hunter I want the projects I made to be listed on my profile. So I can use my profile to show my potential. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Because just one person can submit work for a team and the project is the place where someone can see the team and showing this cards on profile is a really cool thing for org looking for people to work with
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature
### Current Behavior
[comment]: # (Describe what actually happened.)
Projects doesn't show on profile
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Projects cards I participated showed on my profile

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
note there is an existing `/portfolio` tab on peoples profiles when they do bounties.. we could maybe leverage that..
