### ISSUE TITLE
Pricing when funding a bounty is not correct

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5788]
**Describe the bug**

I noticed that in the creation of a bounty the pricing calculated is not corrected, see below:
![image](https://user-images.githubusercontent.com/50027175/72287974-5633c500-3648-11ea-9827-dae1809952eb.png)

**To Reproduce**

Create a bounty and you will see that it says that a bounty with 0$/hr leads to 65% success rate. Realistically this can't be correct.
Don't know if this is because of people not answering questions when submitting work.

**Expected behavior**

Correct data about pricing

**Comment by thelostone-mc** [comment]
This is cause it needs to be min 1 USD worth of ETH for it reflect the right USD
Might need to figure out the cleanest way to fix this

**Comment by Solexplorer** [comment]
We are talking about the success rate right ?

Because this happens also with 1$ of ETH:

![immagine](https://user-images.githubusercontent.com/50027175/72337253-90da4380-36c2-11ea-879e-a7d55580c126.png)

**Comment by owocki** [comment]
yea it should def have a lower success rate..
