### ISSUE TITLE
Two versions of Zero Knowledge Podcast are live in the Grants explorer

### ISSUE THREAD

**Issue by pcowgill** [gitcoinco/web#5791]
**Describe the bug**

One Zero Knowledge podcast instance shows up as active in the media section https://gitcoin.co/grants/38/zero-knowledge-podcast and one instance shows up as active in the tech section https://gitcoin.co/grants/329/zero-knowledge-podcast-2

**Comment by pcowgill** [comment]
[Related Twitter conversation](https://twitter.com/paulcowgill/status/1216863052584407041?s=20)

**Comment by owocki** [comment]
just closed the old grant + moved the activity over to the new one!

**Comment by pcowgill** [comment]
@owocki Thanks!!

**Comment by pcowgill** [comment]
@owocki Did you happen to give the new grant a media label rather than a tech label as well? (Even though the podcast goes pretty deep into tech topics.)

**Comment by thelostone-mc** [comment]
@pcowgill yup it's labeled under media
