### ISSUE TITLE
As a Gitcoin hackathon admin I want to know more about our hackers and what they need

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5792]
### User Story
As a Gitcoin hackathon administrator I want to collect ideas and validating evidence from hackers to inform product/operational improvements, but I currently don't know enough about hackers’ goals and skills coming into a hackathon nor their feedback and ideas coming out of a hackathon to prioritize these improvements effectively.

### Why Is this Needed
So far we have had limited opportunities for interaction directly with hackers to learn about their unique needs, skills, goals, etc., making it hard for us to identify and rank improvements that will impact the hacker experience most.

We want a way to collect information more systematically and increase participation rates so that we can improve hackathon ops/product based on a representative sample of hackers.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
Feature

### Current Behavior
Our old Mailchimp hackathon registration flow used to have a registration form that collected information about what hackers wanted to build and what was motivating them to join the hackathon. This system has since been retired, and we now don't ask hackers any hackathon-specific questions as part of registration (though we do link to peoples' Githubs, giving us a better picture of their past contributions and skills).

From time to time hackers share ideas and feedback via chat, but we have not used chat systematically for this purpose.

More recently we tried using Google Forms at the end of Global Communities (tied in with voting for Best in Show) to collect feedback/ideas for improvement after the event. Included in this survey was a "Net Promoter Score"-type sentiment metric asking hackers to rank their overall hackathon experience. Although there were a few useful entries to this survey (~16) we were expecting far more participation.

### Expected Behavior
A hackathon hacker feedback process that encourages thoughtful ideas, honest feedback, and high participation rates.

### Definition of Done
Learn the following at a minimum for each hackathon:
- How new are people to blockchain development?
- What skills do they have and want to use during the hackathon? (for developers we can likely learn some of this through Github, but people have shared other skills like token economics, design, etc.)
- What do they want to get out of the hackathons? (Money? Learning? Fun? Meeting potential teammates? Building their portfolio?  Investment? Exposure in the blockchain space? Reputation on Gitcoin?)
- What did they think of the hackathon experience overall? (NPS-type score to judge overall delight)
- What would they like to see created or improved in the product (bugs/features) or otherwise (workshops? team formation opps? marketing info? different challenges)

### Data Requirements
We want to track the quantity and quality of responses to ensure we're gathering enough information to make informed product/ops decisions.

For the information itself we may want to use a combination of surveying and automatic data collection (for example, from people's public Github/Gitcoin profile info).

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by alexvotofuture** [comment]
From @octavioamu:

> - From capturing on hackathon registration:
> - Is this feature for sponsors to view something? For us to understand?
> - What we want to do with the data?
> - Is this data collected visible for who?
> - Is a form for each hackathon?
> - Where we want to have this data?  is something we want to store on the system or outside (like a google sheet)?
> - Also we need to figure out legal part of having this data stored/shared with sponsors

**Comment by frankchen07** [comment]
> problem statement

sponsors want operational improvements, but they don't have sufficient information to figure out what they can do from their perspective - we should provide that information

> is this feature for sponsors to view something? For us to understand?

this is a feature that should increase gitcoin's data moat, but gives us the sufficient information help the sponsor

> What we want to do with the data?

present the data to the sponsors in a way that they can make better decisions on their part

> Is this data collected visible for who?

freely visible for gitcoin, but reported to clients/sponsors in a digestible, standardized format

> Is a form for each hackathon?

maybe? it'll be a solution that maximizes response rate

> Where we want to have this data? is something we want to store on the system or outside (like a google sheet)?

internal preferably

> Also we need to figure out legal part of having this data stored/shared with sponsors

What's the legal part for having this data shared? If we anonymize and provide aggregated results, we might be able to skirt the issue

**Comment by alexvotofuture** [comment]
@frankchen07 Sponsors aren't the primary group that will be responding to hackers' feedback - that would mostly fall on us (hackathon ops + product). As such this wouldn't need to be presented in a digestible way for them right off the bat.

We may decide to share some specific insights with sponsors if we think they can do something on their part to improve the experience. We also plan to run retros and provide report cards to sponsors by email after a hackathon, which can help them course-correct for future hackathons.

Just want to make sure the audience for this feedback is clear.

**Comment by alexvotofuture** [comment]
Design team is [working on a mock](https://app.mural.co/t/consensys3989/m/consensys3989/1580313920483/0f2f3e19fa8d5035333816f338bf4335912cd7f0) for this:
<img width="833" alt="Screen Shot 2020-02-19 at 12 15 02 AM" src="https://user-images.githubusercontent.com/8337893/74810592-eea71000-52ac-11ea-859b-eb0dc994d799.png">

**Comment by alexvotofuture** [comment]
Resurfacing this one, as we have yet to put it into the hackathon registration flow.

Suggestion for the skills portion: We should auto-populate skills pulled from Github, but allow hackers to de-select skills they don't want to use during this hackathon and add additional skills like graphic design, cryptoeconomics, medical care, etc.

**Comment by frankchen07** [comment]
so right now, in hackathon registration flow, we have github signup, questions to surface why they're there, but we don't have skills, unless they go through a normal gitcoin.co onboarding (our old onboarding process). 

Might be worth figuring out from a technical perspective if we want to port that over.

**Comment by PixelantDesign** [comment]
@alexvotofuture the registration flow is live and we have the skills feature. cc @octavioamu ^
