### ISSUE TITLE
Integrate Mooni as crypto cash out feature

### ISSUE THREAD

**Issue by pakokrew** [gitcoinco/web#5793]
### User Story

As a Gitcoin contributor, I would like to cash out the payment I receive in cryptocurrencies, so that I can use the money I earn by working on open source project with my fiat bank account. 

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Being able to work from anywhere on opensource project is awesome, but it is still hard to spend cryptocurrencies for everyday living. It would change the game if I could cash out when I want to and being able to get the money that I earn on my bank account. 

*Current state*
[Mooni](https://github.com/pakokrew/mooni) is already a working product where people can come with their web3 wallet and send funds to their bank account. A JS SDK is provided to help any marketplace creator to integrate it into any webapp.

*What I would like to see*
I would like to integrate Mooni into gitcoin, so that users can just click a button on the Gitcoin webapp which open Mooni and let them cash out in minutes.

**Comment by thelostone-mc** [comment]
Closing this out for now as we've got a lot of integrations setup at the moment and we don't see a popular demand from mooni. If we see folks wanting to use it / mooni team reaching out to us cause they see a potential usecase.
Will reopen this then 🙌
