### ISSUE TITLE
Preserve user choices in persistent store

### ISSUE THREAD

**Issue by tjayrush** [gitcoinco/web#5799]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

I participate in the CLR grant matching which means I want to donate to a bunch of different projects. I usually wait to do the granting all at once to 10-15 different projects -- either to those projects that are for my friends, projects I think are interesting, or just random projects (because I want to donate to people who might not get the notice of other people).

When I donate, I go to the grant proposal and click on Donate to this Project. Each time I do that, I have to re-enter the same information -- 10 DAI instead of 5, fast gas price, one time donation.

It seems to me it would be trivially easy for your app to preserve my previous choices so I don't have to reset them each time. It would make donating to multiple projects (10-15 as I mentioned) easier.

Also -- while I'm at it -- a spreadsheet like interface where I can list the 10-15 projects along with amounts and repeating and gas price would be nice. One form -- one transactions -- 10 donations.

Also -- a form that just says "I have XXX DAI, I want to spread it out amongst XX randomly chosen accounts" or "I have XXX DAI, I want to spread it out to the YYY most under-recognized projects" or "...these specific YYY projects evenly".

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
thanks for the feedback @tjayrush !

checkout experience seems similar to eric's idea here => https://github.com/gitcoinco/web/issues/5778
