### ISSUE TITLE
the big 'profile might need a redesign or some bugfixes' thread.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#580]
alignment of profile is messed up at certain resolutions

![image](https://user-images.githubusercontent.com/513929/37187165-3ecd77d2-2306-11e8-8629-072992f9f6c4.png)
https://gitcoin.co/profile/razordaze

**Comment by thelostone-mc** [comment]
Two questions : 
- This page requires a re-design anyways which would also involve code clean up. Do you wanna fix this given that this would be thrown away soon. If this page is on the todo list (like within 2 weeks, I would side with holding off, else this should be fixed asap )
- The profile image alignment is cause of [this](https://github.com/gitcoinco/web/blob/master/app/assets/v2/css/base.css#L954) to get the overlap effect 

We could throw in some code there to remove the margin if there is only author present or remove the `margin-left` all together. Which one ? 

![help](https://user-images.githubusercontent.com/5358146/37196873-7c52ce3e-239e-11e8-954d-04c0b0587f4c.gif)

**Comment by owocki** [comment]
Believe it or not the original design actually has the avatars overlapping purposefully.

> This page requires a re-design anyways which would also involve code clean up

cc @PixelantDesign id be curious if she agrees

**Comment by owocki** [comment]
(on tips) The repos section seems to having extra margin/padding (it's probably a 2 line fix )

From: https://github.com/gitcoinco/web/pull/544

**Comment by owocki** [comment]
<img width="1680" alt="screen_shot_2018-03-08_at_10 32 26_pm" src="https://user-images.githubusercontent.com/513929/37209648-36ac0822-2363-11e8-92d6-2574ad5e0121.png">

this is off center

<img width="1436" alt="screen_shot_2018-03-08_at_11 16 38_pm" src="https://user-images.githubusercontent.com/513929/37209654-3a96c724-2363-11e8-82c6-f6d719333450.png">


those are the people you’ve worked with (your counter parties on gitcoin)
which i guess is not really clear at all from the design..

**Comment by PixelantDesign** [comment]
@owocki totally agree! Would love to redesign the profile!

**Comment by PixelantDesign** [comment]
closing since this is now a duplicate.
