### ISSUE TITLE
Gas price set when funding grant is applied to the "approve" transaction, but not to the "transfer" one

### ISSUE THREAD

**Issue by markusbkoch** [gitcoinco/web#5800]
When I fund a grant, Gitcoin's UI gives me the option to set a custom gas price. Metamask uses the value I set when it asks me to sign the approve transaction. After signing it, Metamask pops up again with a request for me to sign the transaction that actually interacts with Gitcoin's smarcontract, but the gas price is not the same I set in Gitcoin's UI.

**To Reproduce**

- You'll need to do this at a time when gas prices recommended by eg ethgastation or Metamask are high;
- Open a grant details
- Click Fund this grant
- Set a one time contribution
- In the gas settings session, change the gas price to 1 Gwei
- Click "contribute to grant"
- In the Metamask popup, check the gas price value for the "approve" transaction (1 Gwei, as expected)
- Sign the approve transaction
- In the next Metamask popup, check the gas price value (should be 1 Gwei, is not)

**Expected behavior**
Both transactions should be constructed with the gas price I set in Gitcoin's UI

**Desktop (please complete the following information):**

OS: Mac OS 10.14.6
Browser: Google Chrome
Browser Version: 79.0.3945.88

**Comment by LefterisJP** [comment]
@owocki this issue is still open since the last round and is actually rather critical imo. Setting a gas price and the second transaction having a different price is not good.

I also experience this every time I donate.

**Comment by owocki** [comment]
i've got a fix staged. will commit it soon

**Comment by owocki** [comment]
fca7c8cdc363e4b3670e9b22222f164d8b72bca4 fixes this
