### ISSUE TITLE
Fail to create a test grant

### ISSUE THREAD

**Issue by cervoneluca** [gitcoinco/web#5804]
Hi everyone, 
I'm trying to create a test grant but, although my MetaMask is connected, I always see "To Continue You'll need to unlock MetaMask". 

I attach a screenshot.

I'm I missing something? 
<img width="1389" alt="Schermata 2020-01-15 alle 12 55 50" src="https://user-images.githubusercontent.com/3637606/72432022-60fc7000-3796-11ea-97a8-b34f2a62e8c7.png">

**Comment by owocki** [comment]
what are your metamask security settings?  usually you need to 'enable' gitcoin to work on metamask if you've got the more restrictive security settings..

**Comment by cervoneluca** [comment]
Sorry for the late reply. Eventually, I figured out how to make it work. Thank you!
