### ISSUE TITLE
Received tip is not expected amount

### ISSUE THREAD

**Issue by TomAFrench** [gitcoinco/web#5809]
**Describe the bug**

As part of a [bounty](https://gitcoin.co/issue/liquidity-network/liquidity-burner/1/2972) I recently completed I received a community contribution as a 0.01 ETH tip. Of this I received ~0.00001 ETH which appears to be a bug of some kind.

**To Reproduce**

1. Receive tip
2. Claim tip
3. Compare tipped amount to amount received

**Expected behavior**

That I receive 0.01 ETH (or a fraction under that after fees)

**Screenshots**

Tip screen showing the amount to be received
![](http://i.imgur.com/BxRjV5H.png)

Etherscan showing a received tip of ~0.00001 ETH

![](http://i.imgur.com/187eygT.png)

**Comment by owocki** [comment]
hmmm i've never seen this before! dont worry we'll get u your ETH!

mind linking the txid?

**Comment by TomAFrench** [comment]
> mind linking the txid?
 
whoops, sorry I forgot.

[0x462be7871e362bdc5bbc79ea61d821332673fb696ba69e92f906ff51c2551e24](0x462be7871e362bdc5bbc79ea61d821332673fb696ba69e92f906ff51c2551e24)

**Comment by owocki** [comment]
hmmm it looks like whomever sent the tip ( https://etherscan.io/tx/0xe46c9122ecf3d33a90494485ecef57548e88a28bbba5678cf579182445edf5a2 )  only funded it with 0.000034066907406146 ETH even though they selected 0.01 in the UI

@kris30pl i have you listed as the sender .. do u recall if u were hacking the UI or something ? :P

**Comment by TomAFrench** [comment]
@kris30pl is 404ing for me so this might end up being a unsolved mystery.
