### ISSUE TITLE
[Gitcoin Grants] Grant Logo Covers Faces on New Bluesteel Update

### ISSUE THREAD

**Issue by kamescg** [gitcoinco/web#5818]
Amazing job on grants! Fantastic work.

It looks like the recent BLUESTEEL update causes people's faces to be covered by the grant logo.

<img width="772" alt="Screen Shot 2020-01-15 at 10 26 29 PM" src="https://user-images.githubusercontent.com/3408362/72485537-d132e200-37e6-11ea-8388-9b2bb00380f5.png">

**Comment by owocki** [comment]
ffce5193048c615b049c3206f9e24218ea94bc9c
