### ISSUE TITLE
Dropped & Replaced TX Stuck (Bounty Submission)

### ISSUE THREAD

**Issue by mccallofthewild** [gitcoinco/web#5819]
**Describe the bug**
While submitting work for https://gitcoin.co/issue/ArweaveTeam/Bounties/21/,  the [initial transaction](https://etherscan.io/tx/0x377f712d88ee89abf5fb31aa2171189afef771a7cb481dbc49cac51c6fa83993) was taking too long, so I dropped & replaced it with [this transaction](https://etherscan.io/tx/0x5c426b95cbe34d7c2dc3b52ce798e803f5b44f1871d701532024610296d15c42). 
[The bounty page](https://gitcoin.co/issue/ArweaveTeam/Bounties/21/) is now permanently stuck in the "Transaction Processing" view (shown below), and my work has not been submitted. 
Thanks in advance! I appreciate the work you do!

Similar to: https://github.com/gitcoinco/web/issues/5649#issue-539262863

**To Reproduce**
Submit work for a Gitcoin bounty, then drop & replace the pending transaction in MetaMask.  

**Expected behavior**
I expected Gitcoin to recognize the replaced transaction and submit my work.

**Screenshots**

![image](https://user-images.githubusercontent.com/12076557/72498506-c2e7c480-37ec-11ea-9148-5ece9328c4b2.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Opera
- Browser Version: Version:66.0.3515.27

**Comment by owocki** [comment]
shoot looks like you closed this before i got to it!

gitcoin should recognize the new transaction... is that what happened in this case?  IIRC it does take an hour or so though.
