### ISSUE TITLE
[Gitcoin Grants] Link To Grant Submission Activity Doesn't Work

### ISSUE THREAD

**Issue by kamescg** [gitcoinco/web#5820]
**Describe the bug**
The new Gitcoin Grants  activity link doesn't work.

**To Reproduce**
Copy link. Paste in URL.

**Expected behavior**
Work.

**Screenshots**
<img width="1426" alt="Screen Shot 2020-01-16 at 6 29 45 AM" src="https://user-images.githubusercontent.com/3408362/72511258-a158fe00-3829-11ea-977b-22982f481f13.png">

**Comment by owocki** [comment]
whats the link?  where do i find it?
