### ISSUE TITLE
Ask for user to adjust gas price rather than gas limit

### ISSUE THREAD

**Issue by scottrepreneur** [gitcoinco/web#5829]
**Describe the bug**

The grants submission screen suggests to the user to adjust the gas limit rather than gas price.

**To Reproduce**

1. https://gitcoin.co/grants/
2. Fund Grant (on a specific grant)
3. Scroll down to bottom of form for "Set my own gas limit"

**Expected behavior**

The user should be suggested to update the gas price if the network is congested rather than changing the gas limit

**Screenshots**

<img width="627" alt="Screen Shot 2020-01-13 at 6 09 52 PM" src="https://user-images.githubusercontent.com/1778380/72638356-e2840780-3928-11ea-82e2-f2e5e5266b63.png">

**Desktop (please complete the following information):**

- OS: All
- Browser: All
- Browser Version: All

**Comment by thelostone-mc** [comment]
threw it in over at 6fbf2ce7208d74f36ffad2efba35cac32b422871
