### ISSUE TITLE
As a hackathon hacker I want to see how I rank on a hackathon leaderboard

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#5844]
### User Story

As a hackathon hacker I want to see how I rank on a hackathon leaderboard

### Why Is this Needed

Our repeat hackers want to celebrate their success. Sponsors want to know who to reach out to for top-quality hacking. 

### Description
*Type*: Feature

### Current Behavior
No leaderboard.

### Expected Behavior
Leaderboard auto-populating using stats (# projects submitted? # of projects paid out as a winner?)

### Definition of Done
Leaderboard pulling live data

**Comment by Solexplorer** [comment]
I would love to see this!
