### ISSUE TITLE
Deleting grants 

### ISSUE THREAD

**Issue by edlondon** [gitcoinco/web#5845]
Hi 
I created two of the same grants by mistake. The delete transaction isn't letting me click. 
https://gitcoin.co/grants/399/s33d-aloha-pods-cast-2

Also on another grant I had a blockage on my Metamask account so it didn't go through properly, and there is no option to delete, as its not linked to a contract address

https://gitcoin.co/grants/367/s33d-mvp-mobile-app

Any help tidying this up would be much appreciated.

**Comment by thelostone-mc** [comment]
@edlondon I've configured the 399 grant as inactive 
contributions will not be possible on that.

Could you tell me what exactly do you want to do here?
Would you want to cancel the grant / what's the other grant you have in it's place



For the other one could you give me the etherscan link of the transaction for 367
