### ISSUE TITLE
Strange feed entry, 892.02 Any Token, by user who contributed 1 DAI

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#5846]
**Describe the bug**

A user [contributed](https://etherscan.io/tx/0xbdbc27f352dfc9a31057af90f5abf03046adca3e2782e722ad2ea66d152519ee) 1 (0.95) DAI to a grant I am managing. The feed showed it nicely but it also showed a very strange [feed entry](https://gitcoin.co/townsquare?tab=activity:113378)

What is it and is it a bug?

![2020-01-20-135118_1034x355_scrot](https://user-images.githubusercontent.com/1658405/72727741-f7aca080-3b8b-11ea-9a6d-8815311b3c20.png)

**To Reproduce**
No idea

**Expected behavior**
Since there was no other transfer apart from the 1 DAI I would not expect to see the strange entry of `892.02 Any Token` in the activity feed.

**Comment by owocki** [comment]
i think this is the same issue as @androolloyd found with voucher funding feed items, right?

**Comment by LefterisJP** [comment]
Which issue? I can't find any such issue created by @androolloyd in Github: 
https://github.com/gitcoinco/web/issues/created_by/androolloyd

**Comment by androolloyd** [comment]
> Which issue? I can't find any such issue created by @androolloyd in Github:
> https://github.com/gitcoinco/web/issues/created_by/androolloyd

sorry, I didn't create an issue around it, but using voucher funding gives you some strange results as well

**Comment by owocki** [comment]
finally at a point in which i can clean out my inbox after a gnarly few weeks.. 

im happy to put a fix in here.. but my worry is that since we likely wont do voucher funding next round (and since VF is the root issue) it might not be worth the effort from a go forward perspective..

**Comment by LefterisJP** [comment]
If VF is no longer part of the next round I would say as long as you have an idea what and how it was caused (so there is no regression if a similar feature is implemented) then you can close this
