### ISSUE TITLE
Page freezes when trying to contribute

### ISSUE THREAD

**Issue by TimDaub** [gitcoinco/web#5849]
I'm trying to contribute to grants with my account (TimDaub).

But when I open the `/fund` page of a grant, the page never stops loading and one of these errors pop up in my console:

`ReferenceError: tokens is not defined` or
`fund:427 Uncaught ReferenceError: $ is not defined`.

The tokens `select` element is not filled with items and changing from `reoccuring` to `one-time` doesn't update the page.

<img width="975" alt="Screen Shot 2020-01-20 at 16 36 02" src="https://user-images.githubusercontent.com/2758453/72738989-0ce0f980-3ba3-11ea-8d63-f3a1c8e2ecae.png">

**Comment by troggy** [comment]
also token-related problem for me — can't select token

![image](https://user-images.githubusercontent.com/163447/72742533-847f4a80-3bdc-11ea-937f-baf4031bc641.png)

**Comment by thelostone-mc** [comment]
@TimDaub  + @troggy we were having a few issues with the server being overloaded!
We just fixed up stuff 

Could you try once again ?

**Comment by TimDaub** [comment]
> Also mind double checking you're on mainnet before you try it again ?

Worked now. Thx
