### ISSUE TITLE
Kudos was offered but then not available

### ISSUE THREAD

**Issue by ligi** [gitcoinco/web#5851]
I first got offered a Kudos:

![Selection_327](https://user-images.githubusercontent.com/111600/72741767-98a95480-3ba8-11ea-9a84-eb96aac6b7fb.png)

but when trying to redeem I get:
![Selection_328](https://user-images.githubusercontent.com/111600/72741874-d3ab8800-3ba8-11ea-9ccc-1b1fc3086970.png)

**Comment by owocki** [comment]
sorry for the radio silence.. i just tested this and cant seem to reproduce it.. but i did just send you this kudos via https://etherscan.io/tx/0x6e118b7afa91ca58ed486ba305400bc59c0874b752570631aec7215f4ee3fc5f

**Comment by ekram-syed** [comment]
I figured out that it happens when you already own a copy of that Kudos somehow. It seems like a feature now? am I correct? @owocki ?
