### ISSUE TITLE
can not select currency to contribute to grant

### ISSUE THREAD

**Issue by johannbarbie** [gitcoinco/web#5852]
when trying to contribute, i see this:
<img width="832" alt="Screen Shot 2020-01-20 at 5 28 36 PM" src="https://user-images.githubusercontent.com/659301/72742607-5d0f8a00-3baa-11ea-9c3a-05406c04b4d0.png">

and this in browser console:
```
Uncaught ReferenceError: tokens is not defined
    at fund.2d5a0d8ad149.js:262
    at waitforWeb3 (shared.f8a566415143.js:222)
    at wait_callback (shared.f8a566415143.js:225)
    at d (raven.js:445)
```

**Comment by owocki** [comment]
do u have a web3 browser installed? which one / is it unlocked / what network is it on?

**Comment by thelostone-mc** [comment]
@johannbarbie we had a few issues earlier so things went a lil crazy ! 
Could you try once again and make sure you're on mainnet with metamask / web3 browser setup and it should work :)

**Comment by TimDaub** [comment]
Duplicate? Close?
