### ISSUE TITLE
Speeding up tx in Metamask causes tx to be indefinitely "pending"

### ISSUE THREAD

**Issue by TimDaub** [gitcoinco/web#5854]
Try the following:

- contribute to a grant by doing the approve tx first
- then when you call the grants contract to take your DAI, try speeding up the transaction with Metamask ("Speed-up" button to send with more gas).

Now, it looks like gitcoin is not tracking the tx anymore and hence the UI continues to show "(pending)" next to the transaction.

**Comment by owocki** [comment]
yeah this is an issue. still searching for a good API to tell us about replacement txn's.. i dont think the defautl web3 RPC does this correctly...
