### ISSUE TITLE
Contribute to multiple Grants in one single transaction at "checkout"

### ISSUE THREAD

**Issue by santteegt** [gitcoinco/web#5856]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a contributor, I want to split some DAI to multiple grants without spending extra tx fees by having to execute the `approve` method for each contribution

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:

Right now, for each grants contribution, you must execute the `approve` method when using ERC-20 tokens to contribute to a project, which is frustrating as you are spending extra tx fees

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
The `approve` method needs to be executed for each contribution I want to make

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Navigate through Grants projects I'm interested and save them into my `contributor basket`. Then, go to checkout and execute all contributions in one single transaction

**Comment by Solexplorer** [comment]
Related to #5778
