### ISSUE TITLE
As a user who just wants to browse hackathon prizes, I get hit by the project modal everytime I click on a bounty

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#5860]
**Describe the bug**

Join a hackathon and click on a random bounty, the project modal will pop up. See here:
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/50027175/72826438-22285780-3c79-11ea-8395-c54d8734ead4.gif)

**To Reproduce**

Join a hackathon and click on a random bounty, the project modal should popup. This happens also for Global Communities.

**Expected behavior**

The modal should not popup for bounties where I didn't start work

**Comment by thelostone-mc** [comment]
not able to reproduce this at my end ! 🤔

**Comment by Solexplorer** [comment]
I think it might be bacause I've started work on one of the hackathon bounties, though it pops up every time I click on bounties where I didn't start work too

**Comment by octavioamu** [comment]
Thanks @Solexplorer I put a fix for this

**Comment by Solexplorer** [comment]
Super!
