### ISSUE TITLE
Grants - Transaction pending forever

### ISSUE THREAD

**Issue by vrde** [gitcoinco/web#5861]
One transaction is "pending" even if it successfully landed in the main net.

Here is a screenshot from the [transaction page or our grant](https://gitcoin.co/grants/293/planet-a-2?tab=transactions):
![image](https://user-images.githubusercontent.com/134680/72828444-eb544080-3c7c-11ea-8bfc-538c9b722d84.png)

And this is the related transaction:
 -https://etherscan.io/tx/0x3616cd836518270769940ba139c5241c1d691ed37f24eb0489a7795968a846c6

Any idea how to unlock the situation? Thanks!

**Comment by owocki** [comment]
looks like it has completed successfully now!

**Comment by vrde** [comment]
I just checked, unfortunately it still says `(Pending)` on the Gitcoin UI (tried both with my session and a new private session to avoid caching).

![image](https://user-images.githubusercontent.com/134680/72887223-8b58ab00-3d0b-11ea-9186-5ee89879fc83.png)
