### ISSUE TITLE
Integrate wallets that have fiat on-ramps, such as Torus or Portis

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#5866]
During this grant round it was difficult to get non-crypto/non-developer users to donate. There's a lot of hurdles for these users as they have never used tools like MetaMask and GitHub.

This would make getting donations from this category of users much simpler than it currently is by removing the prerequisite to have MetaMask and a GitHub account to donate to grants.

It also fits right in with #5778 and #5856&mdash;at checkout you would instead login with a wallet like Torus or Portis, then use a credit/debit card to complete the donations to all grants.

For bounties, it makes sense to require integration with GitHub, but for users who are only donating to grants this seems less necessary. The one issue with using Torus/Portis instead of GitHub is that it may be less sybil-resistant. (Looks like Portis integration began in #969 and was never finished).

**Comment by iamonuwa** [comment]
@owocki, looking forward to integrating torus to gitcoin for this issue.

**Comment by owocki** [comment]
@iamonuwa how complex do u think doing that would be?  what design tradeoffs do u think we'd need to make to do it well?

**Comment by iamonuwa** [comment]
Focus authenticating other products other than bounties. Or add to bounties as well, but the user will still need to authorize GitHub on Gitcoin behalf. Wdyt @owocki?
