### ISSUE TITLE
Lost Changes (description & photos)

### ISSUE THREAD

**Issue by edlondon** [gitcoinco/web#5868]
Hi I made a lot of changes to the description of the S33D grant we have posted yesterday. Along with the photos you can see below. The vast majority of them were lost today. Is there anyway to see if i can get them back with out re writing and formatting as it took quite some time. Also just reporting this as i figure there must be a bug, and I wouldnt like this to happen to others.(i have attempted to include a photo bellow of the changes, that have no reverted)

Many Thanks 

https://gitcoin.co/grants/?keyword=s33d

Reverted photos and descriptions today 
![547F2F3D-9CB7-43B9-9123-856B7A793250_1_105_c](https://user-images.githubusercontent.com/10546852/72915484-4860fc80-3d38-11ea-9c68-df2a43ce74f8.jpeg)

Changes made last night
![B2632333-8B2A-45E4-88F9-F7AA5FFFBA2A_1_105_c](https://user-images.githubusercontent.com/10546852/72914665-ebb11200-3d36-11ea-82c6-edcf79d3f9fa.jpeg)

**Comment by owocki** [comment]
we'll need reproduction steps to fix this.  did the grant actually save? did you get a green success message after saving it?

**Comment by edlondon** [comment]
I was sure it had because I then reopened them, but perhaps it was just temporary and some didn’t go green. I’am just going to do it again in the ones that didn’t save, and do better 😁 

Thanks I’ll double check i see green this time. 

Have a great evening
