### ISSUE TITLE
subscribe to next N grant rounds

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5873]
letting u subscribe to next N grant rounds instead of next N weeks/days/month for recurring. i wonder if that would be more used than the existing recurring functionality

**Comment by owocki** [comment]
https://twitter.com/owocki/status/1220100489079148544

**Comment by willsputra** [comment]
we could also add it to the Fund Grant form
![clr round](https://user-images.githubusercontent.com/19514207/73558503-46acdc80-448e-11ea-9d25-ec8de97e7163.jpg)
