### ISSUE TITLE
Gitcoin Bounty Hunter Explorer Dashboard

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#588]
*Not ready to be worked on"

As a user I'd ilke an easy way to view the tasks that I'v signed up for so that I know what I need to do next - in Gitcoin"

**Comment by PixelantDesign** [comment]
@kennethashley let me know if you have ideas!

**Comment by mkosowsk** [comment]
Would it make sense to have something like a "My Issues" link in the navbar, perhaps to the right of "Issue Explorer"?

Then this view could show the user's issues in their various states 🤔

**Comment by thelostone-mc** [comment]
@mkosowsk won't that be flooding the navbar ? Not sure if this makes sense but if we redesign the entire profile page, we could accommodate this ( call it a profile dashboard ) into it
Meh , just random thoughts

**Comment by mkosowsk** [comment]
@thelostone-mc hmm good point, makes sense to me for this to live on the Profile page 👍

**Comment by KennethAshley** [comment]
It would be nice if "My Issues" had a low barrier to entry. Maybe the the user drop-down. But if the profile page is going to be redesigned, that might be a good place to put it.

**Comment by owocki** [comment]
i think this is a great idea!

> But if the profile page is going to be redesigned, that might be a good place to put it.

+1

**Comment by PixelantDesign** [comment]
Copying comments from another ticket
@owocki 

As a user, I want a "My Work' module so I can see what work is active / done for me on gitcoin

Should include:

Status
Amount
Next Step (if possible)
Ability for me to set / load comments.

**Comment by owocki** [comment]
could probably be a v2 to https://github.com/gitcoinco/web/issues/1177

**Comment by owocki** [comment]
hey @PixelantDesign -- *crazy* idea -- we reuse the design from https://github.com/gitcoinco/web/issues/1177 but we just list the bounties one has worked on instead of the bounties that they've paid out.  and we change 'top contributors' to 'top projects'

**Comment by PixelantDesign** [comment]
@owocki we could definitely try that, but based on user conversations, contributors are more interested in seeing what projects are in flight, what phases of the project are they in, and how to manage multiple issues that they're juggling. Some things from the funder dashboard are relevant but might not have the same priority.

**Comment by owocki** [comment]
good to know! was just trying to get the convo going... ill let you take the first pass at the designs here.
