### ISSUE TITLE
Underfunded tip transaction

### ISSUE THREAD

**Issue by sigma67** [gitcoinco/web#5887]
Today I got a tip for completing a bounty. Since I had not provided an Ethereum address previously, I went to the web UI to complete the process. A transaction was sent to my address, but it was only funded with a Gas Price of 2 wei. For this reason it is not getting processed on the main Ethereum network

https://etherscan.io/tx/0x60b00475735aa3b27743fd535ad4232bdfd82aa84e2fd777936de6357d04434b

**Comment by owocki** [comment]
2gwei is standard gas price rn.. https://bits.owocki.com/8LuwKJyj - to me that suggests it should be clearing any day now..

**Comment by owocki** [comment]
just issued u a new tx https://etherscan.io/tx/0xfebc2ecf92f00bfa56ae8fb9a08df000e6acdde85de927e29eccfea7e7fe8751

**Comment by owocki** [comment]
https://etherscan.io/tx/0xfebc2ecf92f00bfa56ae8fb9a08df000e6acdde85de927e29eccfea7e7fe8751
