### ISSUE TITLE
Clarification on Grants round 4 match calculation 

### ISSUE THREAD

**Issue by chrisblec** [gitcoinco/web#5899]
My question is regarding the final “ranking” for Media in CLR Matching Round 4. 

![E449CD4C-AA80-4DBE-A75E-BB958FD6D5AB](https://user-images.githubusercontent.com/17037450/73356529-94480000-4268-11ea-948b-75029e1b0c31.jpeg)

Obviously at first glance, all others are ranked by number of contributors. By that logic, I should be number 7.

I did receive 2 x $1000 grants. Even if we remove those, I would still have $975 in contributions and 74 contributors and that would put me at number 8 with what appears to be over $4000 match. 

I’m trying to understand how I landed at number 10 with a $2876 match. It seems that not only were my large contributors excluded from matching, but I was also penalized somehow and received less than I would have without 1 of those large contributions. 

Thanks for helping me and my contributors understand quadratic funding better!

**Comment by owocki** [comment]
@frankchen07 would probably know whats up here (though he was sick yesterday so give him some time :) )

**Comment by frankchen07** [comment]
The rankings shown above are by CLR match, not number of contributions. 

I do see that you have two 1k contributions, but they don't "penalize" you. The match is dependent on the pairwise mechanism that is used to do the calculation, which is not a 1:1 match. I can confirm that the 1k contributions were taken into account when determining your CLR match from looking at the raw data.

The whole point of pairwise matching is to combat the tragedy of the commons. If we had used a 1:1 matching system, it would be easy for whale donors to easily get a matching amount by donating large sums of money between very few people. This doesn't adequately account for the actual "support" across the public that a commonly used grant may have. Another way to think about it is "the more contributions, more match per dollar contributed". This is an intended feature of the mechanism. Projects that can get more people to donate to them represent public goods that serve a larger public, and so tragedy of the commons problems are more severe and hence contributions to them should be multiplied more to compensate.

![photo_2020-01-29 10 42 35](https://user-images.githubusercontent.com/7516920/73386792-535de480-4284-11ea-9792-ee1c0f923c12.jpeg)

Here's a graph showing that exact concept. These are media contributions by high donation (y-axis) on the number of contributions (x-axis) with bubble size being the CLR match amount. While there is a correlation with high donation and bubble size, it's not 1:1 and you can see that number of contributions has a stronger, more readily apparent correlation to CLR match size.

If you are curious, you can check out how our CLR calculations are made in our repo (the code is open source)

**Comment by chrisblec** [comment]
Thanks for the response.

The point that I am most curious about is that if I didn't receive the 2 x
$1000 contributions, I would have had 74 contributions with total of $975.
Based on the chart, I would have ended up between #7 and #8 with a match
(estimated) around $4000-$4200.  That match would have been around $1300
higher than what I actually ended up with.

This means that I would have received a higher total amount (contributions
+ match) if I *hadn't* received one of the $1000 contributions. This seems
a bit counterintuitive. Please let me know if I'm missing anything here.

**Comment by frankchen07** [comment]
Ah, I see what you're saying. I think this is where the CLR estimate could use some improvements on our side - the CLR estimate is in fact an estimate, and I'll go into detail about this after my next comment below.

So just as an experiment, I ran the finishing CLR calculations with both 1k contributions, one 1k contributions, and neither 1k contribution and your CLR matches would've been:

both 1k included: $2876
only 1 1k contribution included: $2647
neither 1k contribution included: $2543

so granted you have more than 1 contribution to your grant, regardless of the size of the donation, it would never result in a lower match amount. 

Back to the point about the estimate. The estimate on our end is a bit difficult to calculate, because:

1. we need sufficient data at all periods of the donation round to give an accurate estimate.
2. everytime we run an estimate, we're creating a permutation of all donor pairs, which is significant calculation overhead in our production systems. Therefore we do an accuracy / speed tradeoff, and this entire issue you opened probably speaks to that. 
3. we totally hear you and we're aware of making it faster & more accurate, so this kind of discrepancy between estimates and actual is far smaller: https://github.com/gitcoinco/web/issues/5897

**Comment by chrisblec** [comment]
Thanks for looking at this further. I'm still confused though.

> both 1k included: $2876
> only 1 1k contribution included: $2647
> neither 1k contribution included: $2543

Without the $1k contributions, my grant would still have more individual contributors and more total contributed than either Ethereum Magicians and ZK Podcast. 

How is it possible in that apples-to-apples scenario for me to come out with a match that is 32% less than Ethereum Magician's $3745?

**Comment by frankchen07** [comment]
In summary, the final CLR match calculator can be summarized as:

for each pair of contributors:

```
LR MATCH for grant X = (square root of the product of each contribution amount to grant X) / (per-pair total across all grants per pair of contributions / threshold + 1)
```

Based on this, depending on the threshold value (calculated at the end of the round), and the amounts, you can see that certain contribution products can be larger, and some can be smaller, so number of contributions and also size of contributions matter, but they all go through the same pairwise calculation. Thus, there are alot of variables and the distribution of the LR match for every pair will be different. 

Here's a comparison of the distribution of yours versus ZK Podcast (as an example). The counts represent the eventual LR match of a pair (instance of the permutation). The point here is that you may have more contributors, which results in more pair permutations (~2k vs ~1.5k), but depending on what other grants the pairs donated to and what amounts (which would affect the per-pair total), that would affect the eventual LR match, thus result in different distribution of LR matches for the permutations (some higher, some lower).

yours:
<img width="1591" alt="Screen Shot 2020-01-29 at 20 34 18" src="https://user-images.githubusercontent.com/7516920/73420328-f8091200-42d6-11ea-9d51-05fc10e25605.png">

zk:
<img width="1600" alt="Screen Shot 2020-01-29 at 20 34 39" src="https://user-images.githubusercontent.com/7516920/73420329-f8091200-42d6-11ea-9fe7-4d1e062944d6.png">

**Comment by chrisblec** [comment]
Thanks again for the followup. 

I can't say that I understand any of this, so I'll just have to trust that it's working as intended!

I hope to become an expert on quadratic funding by the next round - perhaps I can understand it well enough to make a video about it for my YouTube channel. ;)

**Comment by frankchen07** [comment]
Hm, unfortunately that might just mean I need to explain it better. In my own time, I'll dig in and see if I can explain the internals using a simpler example.

In the meantime though, we appreciate the trust you're putting in us, but in the name of transparency, I'll find a way to make it more understandable for you!
