### ISSUE TITLE
Fiction bounty disappears after submitting work

### ISSUE THREAD

**Issue by KiChjang** [gitcoinco/web#5903]
**Describe the bug**

After submitting work for a bounty, the issue details page for it is completely gone.

This is the fulfill bounty transaction: https://etherscan.io/tx/0x461bca98eeda59bf1103958f3794e634167200740c6e02abfcabc5dfbdd58e68.

This is the github issue: https://github.com/ProofSuite/OrFeed/issues/38

This is the broken link to the issue on gitcoin: https://gitcoin.co/issue/ProofSuite/OrFeed/38/3940

**To Reproduce**

1. Get approved to work on a bounty.
2. Submit your work for the bounty.
3. Wait for your fulfillBounty transaction to be confirmed on the block chain.

**Expected behavior**

I should be brought to the gitcoin issue details page after the transaction is confirmed, and it should still exist.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Mozilla Firefox
- Browser Version:

**Additional context**

**Comment by owocki** [comment]
fixed now; thanks for heads up ! https://gitcoin.co/issue/ProofSuite/OrFeed/38/3940
