### ISSUE TITLE
allow gitcoin.co/tips to support sablier style streams (as opposed to instant payment)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#5905]
scope: allow gitcoin.co/tips to support sablier style streams (as opposed to instant payment)

requirements:
1. must work on mobile
2. please add a toggle to existing gitcoin.co/tip flow to allow user to toggle between legacy tips and stream tips
3. if no address is on file for a profile; then no stream can be done.. but the user can send an invite email to that user asking them what their eth address is

**Comment by owocki** [comment]
@PaulRBerg feedback on this?

**Comment by PaulRBerg** [comment]
It'd be nice for us to fund a bounty for this during the Sustain Web3 hackathon.

A few thoughts:

1. Should the stream creator be able to cancel at some later time? If yes, we can make this cross-compatible with pay.sablier.finance
2. Should this be added as a log item in every user's activity? If yes, we can provide this info through our [subgraph](https://thegraph.com/explorer/subgraph/sablierhq/sablier), but I'm not sure if and how you handle GQL

**Comment by owocki** [comment]
1. yes and yes
2. we dont right now.

**Comment by PaulRBerg** [comment]
I wrote a new issue for this and added the bounty description as per your [specs](https://docs.google.com/document/d/1zslZeocJ8soQBAYG0_jwVXaCBxgwpJHO9iofwNPPaYw/edit#):

https://github.com/gitcoinco/web/issues/5914

Adding it to the Sustain OSS hackathon now.
