### ISSUE TITLE
Allow CHAI as currency for grants

### ISSUE THREAD

**Issue by PaulRBerg** [gitcoinco/web#5913]
I wanted to fund a bounty with CHAI, but it seems the token is not available in your interface yet.

<img width="232" alt="Capture d’écran 2020-01-31 à 17 10 13" src="https://user-images.githubusercontent.com/8782666/73550101-a4203980-444c-11ea-81c4-c8a01cd7fff6.png">

**Comment by owocki** [comment]
just enabled CHAI; itll show up in 10 minutes or so when the cache busts
