### ISSUE TITLE
GeoIP download link is broken

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#5920]
The GeoIP download link seems to be broken: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&date=20191231&license_key=7PZQgKNxgqTRhkWy&suffix=tar.gz

`docker-compose up --build` now gives me:

```
--2020-02-03 02:44:07--  https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&date=20191231&license_key=7PZQgKNxgqTRhkWy&suffix=tar.gz
Resolving download.maxmind.com (download.maxmind.com)... 104.16.38.47, 104.16.37.47, 2606:4700::6810:252f, ...
Connecting to download.maxmind.com (download.maxmind.com)|104.16.38.47|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-03 02:44:08 ERROR 404: Not Found.
```

I have a feeling this is something recent as the link was working fine about a week ago -I had not removed the volumes and rebuilt locally until today.

**Comment by thelostone-mc** [comment]
This should fix it up
https://github.com/gitcoinco/web/pull/5924
