### ISSUE TITLE
Banners are not being loaded on the live site

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#5921]
Since around the 31st of January, I have been unable to update my profile's header image. It would seem that `/api/v0.1/banners` is responding with: 

`{"active": "error", "code": 500, "nav": "home", "title": "Error 500"}`

I am recieving the alert: `Failed to load list of banner images. Try refreshing your browser`

![error500](https://user-images.githubusercontent.com/1489224/73622717-3a4c8f00-4608-11ea-9f66-cda37a346bce.png)

----------------
<sup><b>Side Note:</b> I had attempted to debug this and see if I can track the issue to a specific commit, however I am unable to build the containers properly due to: #5920 and I do not wish to manually setup Gitcoin on my machine. Once, or <b>if</b>, I am able to properly debug this, I will update this issue along with making a pull request.</sup>

**Comment by owocki** [comment]
> [Errno 2] No such file or directory: '/home/ubuntu/gitcoin/coin/app/static/wallpapers'

@danlipert i think maybe the new API server needs this dir created... maybe we should add the creation of this dir to the deploy script so we dont need to remember to do it anymore?

**Comment by owocki** [comment]
@walidmujahid try now! i just created that dir on the new server

**Comment by danlipert** [comment]
@owocki good thinking - one less thing to remember! https://github.com/gitcoinco/web/pull/5932/files

**Comment by walidmujahid** [comment]
@owocki That solved the problem.
