### ISSUE TITLE
upgrade: font-awesome 5

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#593]
##### Description

Reasons to upgrade to font-awesome 5

**Upside:** 
- Lighter in size
- More icons 
- Supports tree shaking

Source : [Blog Blog](https://blog.fontawesome.com/the-quest-for-a-lean-and-mean-font-awesome-5-3427a518940d)

**Downside**
- Syntax sort of changes but they've got a way to manage that until we've completely onboarded to v5 [here](https://fontawesome.com/how-to-use/upgrading-from-4). Meh 

This would a lot of tiny changes, rather than doing it one shot ->  I'd like to migrate it small batches.
This could def be a bounty for newbies :D

@mbeacom  @PixelantDesign  Thoughts ?
I know it seems insignificant but it's the little things that matter :P

**Comment by mkosowsk** [comment]
👍 to this :)

**Comment by alysonpaige** [comment]
I'd like to take this upgrade on if it's still open.

**Comment by PixelantDesign** [comment]
Is there a cost associated?

**Comment by thelostone-mc** [comment]
Nope! They have a free version which was what I was planning on using!
They've got a paid version with a few extra fancy icons which we really don't need unless @mkosowsk decided be super generous and buy it for us (even though we wouldn't end up using any of those ) :P

**Comment by mkosowsk** [comment]
@thelostone-mc spend your own money, not mine 😜

Lord knows my baby needs too much money anyway... 10 months old and cries all the time but doesn't pay rent 😤
