### ISSUE TITLE
I can't start work on a gitcoin bounty

### ISSUE THREAD

**Issue by sthorpe** [gitcoinco/web#5939]
I get this message when I try to click "Express interest" on a gitcoin bounty.

"Because a staff member has had to remove you from a bounty in the past, you are unable to startmore work at this time. Please leave a message on slack if you feel this message is in error."

Desktop imac mac os. Google Chrome. Version 79.0.3945.130

**Comment by owocki** [comment]
looks like you were removed from https://github.com/gitcoinco/web/issues/1179 for abandoning the bounty... so thats why the system won't let you start work.

was that under extenuiating circumstances of some sort? i'd hate to remove the block on new start works and to frustrate another funder by this happening again.

**Comment by sthorpe** [comment]
Perfectly understandable. I guess I'd like another shot. Crossing fingers.

**Comment by owocki** [comment]
kewl will remove the flag on ur profile

**Comment by owocki** [comment]
done

**Comment by sthorpe** [comment]
Awesome. Thank you. Excited to actually start work.
