### ISSUE TITLE
Can't cancel grant

### ISSUE THREAD

**Issue by happykennedy** [gitcoinco/web#5949]
I tried to cancel a grant but I'm stuck at the "Are you sure you want to cancel this grant?" modal. The "cancel grant" button in unresponsive.

The grant I'm trying to cancel: https://gitcoin.co/grants/402/defisnap

**Screenshots**
![image](https://user-images.githubusercontent.com/6855274/73852922-02a73800-47fe-11ea-9e8e-0e6d9554c7ce.png)

**Desktop:**
- OS: MacOs Catalina
- Browser: Chrome
- Browser Version: 79.0.3945.117

**Comment by owocki** [comment]
what happens when u click the button? any errors in the console?

**Comment by happykennedy** [comment]
This is what I'm getting.

![image](https://user-images.githubusercontent.com/6855274/73887965-bc23fe80-483a-11ea-98f6-1dc0c69dff49.png)
