### ISSUE TITLE
Redeeing eth1xlivestream2020 kudos is not working for some people?

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#5961]
<sub>I remain uncertain as to how to best describe what is happening but it appears that transactions for redeeming https://gitcoin.co/kudos/redeem/eth1xlivestream2020 is going through -or hanging?- for at least two people. gitcoin.co/ililic -if I am unmistaken- and myself.</sup>

After a couple hours of having redeemed the eth1xlivestream2020 kudos, I am unable to see any changes on etherscan and on the kudos page it appears that, while gitcoin has seemed to have registered all the redeems via the Activity, the marketplace states [(on this page)](https://gitcoin.co/kudos/4033/i_want_you_to_build_on_eth), while they increase, always seem to be behind by some number. 

I have observed that the "Total Minted" has been consitantly two behind when it registered at eight, ten, and then now -at current time of writing- twelve:

![1111](https://user-images.githubusercontent.com/1489224/74067166-988dbf00-49c6-11ea-92ff-c838cb108120.png)

**Comment by owocki** [comment]
@androolloyd would love your help debugging why this celery job never completed .. is there any way to see when it ran and what its exist status was?

**Comment by owocki** [comment]
for my future self https://gitcoin.co/_administrationkudos/kudostransfer/11766/change/
