### ISSUE TITLE
Migrate history of one grant to another (updated ETH address to multisig)

### ISSUE THREAD

**Issue by marsrobertson** [gitcoinco/web#5966]
Posted on Slack: https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1581108355223800

Posting as an issue to keep it organised:

Please end: https://gitcoin.co/grants/346/proof-of-humanity-sybil-attack-resistance-sar?tab=description

Please migrate history: https://gitcoin.co/grants/430/proof-of-humanity?tab=description

At first set up my personal ETH as receiving end, only now created multisig.

**Comment by owocki** [comment]
mgrated!

**Comment by marsrobertson** [comment]
![image](https://user-images.githubusercontent.com/44369284/74515140-e5612080-4f05-11ea-9ff3-a2a3547b76f4.png)

24 DAI is not much but for the admin purposes please have a look.

The ETH address receiving: https://etherscan.io/address/0x85A363699C6864248a6FfCA66e4a1A5cCf9f5567#tokentxns

(no 24 DAI transaction found, there is 23 from `vs77bb`)
