### ISSUE TITLE
Bundle multiple contributions  via DeFiZap.

### ISSUE THREAD

**Issue by nodar** [gitcoinco/web#5967]
### User Story

As a contributor to multiple Gitcoin grants, I want to contribute in a 'Zap' to avoid multiple on-chain transactions.

### Why Is this Needed

Observing UX around Gitcoin contributions, especially during Gitcoin Grants CLR matching rounds, many supporters are contributing to multiple projects. Taking a clear example from [Chric Blec's video](https://twitter.com/ChrisBlec/status/1215734396889620480?s=20), immediate observation is 50% of the time is spent initiating and waiting for separate contribution transactions to confirm. DeFiZap could help supporters anytime they are contributing to 2 or more projects. In addition, CLR matching amounts could be efficiently deployed deployed across grantees (even streamed over time by also plugging Sablier).

### Description

*Type*: Feature

### Current Behavior
Select project 1 - > choose amount -> confirm transactions.
Select project 2 - > choose amount -> confirm transactions.
Select project 3. - > choose amount -> confirm transactions.
[Video.](https://twitter.com/ChrisBlec/status/1215734396889620480?s=20)

### Expected Behavior
Select Project 1,2,3, etc.- > choose amount -> choose allocations(or even split) -> confirm transactions.

### Additional Information
- Do we want to enable contributions in any token or just limit to one? 
- Do projects want incoming contributions to be auto-deployed to chosen, yield generating opportunities in DeFi? E.g. wrapped into CHAI or LP on Uniswap.

**Comment by owocki** [comment]
if we can just do this for DAI it'd be a huge win for round 5

heres a UI for the same courtesy of @willsputra 

![cart](https://user-images.githubusercontent.com/513929/74177684-7af36c00-4bf7-11ea-8837-7295b849a5eb.jpg)
