### ISSUE TITLE
Quest forms present 2 answer fields per question, should be 1

### ISSUE THREAD

**Issue by mohamedhayibor** [gitcoinco/web#5970]
**Describe the bug**

The quest form presents 2 answer fields

**To Reproduce**

Try creating a question on a quest: https://gitcoin.co/quests/new

**Expected behavior**

There should be only one answer field per question.

**Screenshots**
![Screen Shot 2020-02-10 at 11 51 23 PM](https://user-images.githubusercontent.com/11381259/74213393-f809fa00-4c66-11ea-88fe-9d26e0602068.png)

**Comment by owocki** [comment]
i dont understand.. the quests are multiple choice.. thats why theres several possible answers..

**Comment by mohamedhayibor** [comment]
Got it. It makes sense to me know.
