### ISSUE TITLE
Comments with more than one link fails

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#5991]
**Describe the bug**

When post have more than one link the parser is failing into one broken link (when break line, using space works fine)

https://gitcoin.co/townsquare?tab=activity:131978
![image](https://user-images.githubusercontent.com/1358093/74596455-25bbbe00-502e-11ea-90da-b73e4e8e89bf.png)
getting into 
`https://gitcoin.co/issue/pegnet/pegnetd/124/4008%3CBR%3E%3CBR%3Ehttps://gitcoin.co/issue/pegnet/pegnet/355/4009` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by kuhnchris** [comment]
Was the fix sufficient? If yes please close. Thanks
