### ISSUE TITLE
Post input locked on max character limit

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#5996]
**Describe the bug**

When I reached the max character limit while trying to post something using the input field under https://gitcoin.co/townsquare, it got stuck/disabled, seems all keyboard key locked. no way to go back, or remove some character or edit the content. 

**To Reproduce**

1. Visit https://gitcoin.co/townsquare
2. Start typing arbitrary texts on post input until you reach the max limit and texts got red color
3. Now try backspace, or try to edit some text.  

**Expected behavior**

The user is able to edit the text to adjust the max character limit or remove all the text entirely to retype.

**Screenshots**

![Home   Gitcoin](https://user-images.githubusercontent.com/15193297/74627638-bb199800-517d-11ea-9c18-e74ebb19cc23.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro N, 1903
- Browser: Google Chrome
- Browser Version: 79.0.3945.130 (64-bit Official)

**Smartphone (please complete the following information):**
Not Tested

- Device: N/A 
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by cervoneluca** [comment]
The same thing happened to me 

**Desktop:**

- OS: MacOs Catalina 10.15.3 
- Browser: Brave Browser
- Browser Version: 1.2.43

**Comment by owocki** [comment]
i actually put in a fix to this on tsable yesterday.. should be fixed once we deploy and collectstatic!

**Comment by kuhnchris** [comment]
@owocki @octavioamu was this fixed with the deployment?

**Comment by ekram-syed** [comment]
I believe it is. Should I close it or is there any process involved?

**Comment by kuhnchris** [comment]
no, if it is solved you can close it, thanks. :-)

**Comment by ekram-syed** [comment]
Issue fixed, thanks all contributors.

**Comment by owocki** [comment]
@kuhnchris two things

1. you could have tested this yourself instead of asking me.
2. please stop assigning/tagging me on github issues. youre just creating noise.  i dont mean to be harsh, but we do need to change course - the community needs to be able to solve little things like this without my involvement.
