### ISSUE TITLE
Can't fund issue with Brave+MetaMask using a token (DAI)

### ISSUE THREAD

**Issue by knocte** [gitcoinco/web#5997]
**Describe the bug**
I've used Brave+MetaMask many times to find issues on gitcoin, but it seems I cannot do it anymore.
At first I thought it was some recent update from Brave browser because they now embed a cryptowallet by default, however even if I disable it, I still have the problem.

**To Reproduce**
Click on "fund issue" on gitcoin, log-in into MetaMask, fill github URL, then click on the "Denomination" combobox (dropdown).

**Expected behavior**
I don't see DAI in the list. (This works perfectly with Firefox instead of Brave)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Brave
- Browser Version: 1.3.115

**Comment by knocte** [comment]
@owocki hey can you teach your team some github manners? closing an issue without reason is not normal.

And this person has done this already more than once.

**Comment by owocki** [comment]
hes closing old issues out; thats why it was closed.

speaking of github manners, your message is quite aggressive.  you could instead ask "hey why was this issue closed?" maybe.

**Comment by owocki** [comment]
(fwiw - i just tested on brave, and i can fund an issue on the latest release - let us know if you cannot; thanks!)

screenshot of the denominations rendering in brave: https://bits.owocki.com/7Ku8gO4z

**Comment by knocte** [comment]
> you could instead ask "hey why was this issue closed?"

I did that the first time it happened.

> hes closing old issues out; thats why it was closed.

Great, how about a template message such as "this issue is quite old, can you try to reproduce the problem again?" ? just, as the very least. I mean, it's pretty standard. You don't want to deter people from filing bugs I imagine.

**Comment by owocki** [comment]
i agree proactive communication would be better. @thelostone-mc next time u close a batch of old issues is that a possibility?
