### ISSUE TITLE
Townsquare Improvements

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6003]
### User Story

Townsquare improvements

### Why Is this Needed

User-feedback from Gitcoin townsquare!

### Description

**COMPLETED**

~~**how does one find the threads that they've responded to?**~~

~~some are copying the link of the thread and bookmarking it~~

~~possible solution: filters on the left - similar to slack - a "your threads" filter, that might eliminate the need for email updates completely~~

~~possible solution: notification section can maintain another section to track comments with thread link (https://github.com/gitcoinco/web/issues/5943)~~

~~possible solution: pin post like mattermost / slack can be handy / pin work for a individual's session~~

~~solved via my threads on the left hand side~~

~~possible solution: sort filter (sort by trending)~~

~~**no "shift-enter" function on townsquare (ability to make newlines?)** (removed as low priority)~~

---

**IN PROGRESS**

**bug: my threads doesn't show all of the threads I've commented on**

**no edit function on the townsquare** (https://github.com/gitcoinco/web/issues/6010 PR)

show matches when I "@" someone in the comments

ability to block certain users** (pending use case)

**Comment by walidmujahid** [comment]
If no one is working on them, I will start working on issue 2, adding an edit function to the townsquare.

**Comment by frankchen07** [comment]
@walidmujahid - yes! Feel free to start working on that. I can bounty it and reserve that for you.

**Comment by octavioamu** [comment]
this one belongs here also https://github.com/gitcoinco/web/issues/6012

**Comment by developerfred** [comment]
Bug in mention  user with "-"
<img width="359" alt="Screen Shot 2020-02-20 at 16 52 20" src="https://user-images.githubusercontent.com/57037080/74973176-bc5af700-5401-11ea-9863-7d024cc72294.png">

**Comment by octavioamu** [comment]
Yes @developerfred the regex is wrong

**Comment by octavioamu** [comment]
regex was solved will be on prod tomorrow

**Comment by developerfred** [comment]
![95B2F12A-ACB4-499D-AE1D-BCD9D7109CB6](https://user-images.githubusercontent.com/57037080/75007639-ab47cf80-546d-11ea-9b8e-849cd4a5b0a8.jpeg) tipping don’t work in mobile browser, we need other design feature for this on mobile.

**Comment by developerfred** [comment]
Nice feature for Townsquare feed is block user, **I want to block a user and not see anything he posts, do you think this is possible? there is a similar feature on twitter, I can block it for time like I don't want to see anything from this user for a week ...**
