### ISSUE TITLE
as a user, i want the bounties to be indexed by standardbounties id instead of github url, to prevent more edge cases

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#602]
we should drop the indexing of bounties by github url (edited)
and just use standardbounty id just like the bounties network

there have two or three times we’ve had dupe bounties for the same github url and its just a pain because the whole system was desired around the old contracts (indexed by github url)… while the new smart contracts are indexed by id

**Comment by owocki** [comment]
@mbeacom @jasonrhaas either of you have intersted in taking this on?

**Comment by mbeacom** [comment]
@owocki I can snag this one, unless @jasonrhaas is eager to jump on it.

**Comment by kuhnchris** [comment]
to this day we still use the github url + std_bounty_id in the url... 
![image](https://user-images.githubusercontent.com/761911/62303771-03d96000-b47d-11e9-8ffd-c34b03250338.png)
