### ISSUE TITLE
ropsten ETH may be showing up in the tip total

### ISSUE THREAD

**Issue by calchulus** [gitcoinco/web#6021]
**Describe the bug**

https://t.co/WGezBvetQ6?amp=1
Here's the ropsten transaction

**To Reproduce**

tip someone while on ropsten
**Expected behavior**

shouldn't count in total
**Screenshots**

**Desktop (please complete the following information):**

- OS: mac
- Browser: chrome
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
we've shifted to supporting only rinkeby as the testnet
