### ISSUE TITLE
Tips comments are getting duplicated if you deny a transaction

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6022]
**Describe the bug**

I wanted to tip a user in the Townsquare but I had the wrong account connected with metamask so I rejected the transaction, then I sent the tip and I saw that it created duplicate comments.

**To Reproduce**

Pick a random comment in the sweet townsquare and first tip someone and reject the transaction, then tip again and submit the transaction. I fear this might be messing with the MINI-CLR but I am not sure

**Expected behavior**

Only show me one comment and not 2 comments( 1 for the rejected tx and 1 for the successful tip).

**Comment by Solexplorer** [comment]
I used this as a test: https://gitcoin.co/townsquare?tab=activity:134308

**Comment by kuhnchris** [comment]
Maybe connected to #6005 ?
