### ISSUE TITLE
Use Profile Email across everywhere

### ISSUE THREAD

**Issue by eswarasai** [gitcoinco/web#603]
##### Description

Currently, in the system, the email address field is not associated everywhere with that of the `Profile.email`. This breaks having the association between Gitcoin User and Tips/Subscriptions etc.

For example, I've recently updated my primary email address of the GitHub from `eswar.vankayalapati@gmail.com` to `eswarasai.v@gmail.com` and removed the old one completely from my GitHub profile. I'm still receiving the Gitcoin notification to my old email address along with the new one. Ideally, Gitcoin should be sending email to my latest primary email address, as I'm logged in with the same one. There can be scenarios, where GitHub Profile has multiple email addresses associated with the account, not sure how we'd like to approach this scenario though.

##### Possible Implementation

Probably, referencing `Profile` across the system instead of saving `email` as String for `Tips`/`Subscriptions` etc.

##### Environment

* **Browser**:
* **Version**:
* **Subsystem**:

**Comment by owocki** [comment]
this is a good idea

**Comment by owocki** [comment]
we should start on this once https://github.com/gitcoinco/web/issues/312#issuecomment-378942385 is done

**Comment by mbeacom** [comment]
We might want to make use of `user.email` following the merger of #574
