### ISSUE TITLE
Responsive mobile menu bug 

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6031]
-->

**Describe the bug**

just witnessed this bug by accessing gitcoin via cell phone, mobile menu and notifications

**To Reproduce**

Mobile browser click on the bell
![360F5CFD-C278-44F1-BA3D-08C531941DCD](https://user-images.githubusercontent.com/57037080/74901718-a286c900-539b-11ea-89f2-f34833d55b18.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser: 
- Browser Version:

**Smartphone (please complete the following information):**

- Device: iPhone 8 Plus
- OS: iOS 
- Browser: Trust Wallet
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Fixed over at 6c543feab570b16beb42499585c7a94ba4ce0577 + Deployed !
Thanks for the report @developerfred  :D
