### ISSUE TITLE
Bug in quest BATTLE BOTTOSHI Q6

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#6032]
**Describe the bug**

In quest BATTLE BOTTOSHI question 6, not passing with the correct answer based on available options.
The Questions is: What is the hashing algorithm in bitcoin?
Options are:
1) ETHHASH
2) PROGHASH
3) SHA-256
4) IHASH

**To Reproduce**

1. Provide the right answer for all other questions
2. On question 6, go with the possible correct answer, it fails
3. Try all one at a time or altogether or none of the answers, it fails 

**Expected behavior**

Answer 3 seems the right answer, it should pass with that. or "Hashcash" can be added in the options 

**Screenshots**

https://drive.google.com/file/d/1aJD41TEftTryKkjRXBObSQGVG-UQ5pZW/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 80.0.3987.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 1plus7
- OS: Android
- Browser: Google Chrome
- Version: 80.0.3987.117

**Additional context**

**Comment by owocki** [comment]
i just put a fix in for this . try now pls

619435764cd55243d9f229081035c426041e0d12

**Comment by loganbek** [comment]
I just retested this quest and Q6 works correctly.

**Comment by ekram-syed** [comment]
I just give this a try and it works smoothly. approach to closing this ticket. Thanks to all contributors. You guys rocks.
