### ISSUE TITLE
Make the follower box in the profile section darker and show the list of followers

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6038]
**Describe the bug**

In the profile section, the follower box should be darker because it's not easy to see if you have a background like mine:
![immagine](https://user-images.githubusercontent.com/50027175/74940715-21a6ec00-53f2-11ea-89b8-7e658a390578.png)

From what I've gathered from the community, seeing the list of followers would be appreciated.

**To Reproduce**

 Go to your profile and you will see what I'm talking about. You might have a dark background in your profile so the issue might not persist for you.

**Expected behavior**

I can easily see the number of followers that I have and I can click in the box to see who has followed me.

**Comment by owocki** [comment]
IMHO the follower number should go inside the button.  if you just make it darker it then wont show up on darker profile headers.

**Comment by willsputra** [comment]
a quick fix would be to make the box white-on-black instead of white-on-white
<img width="589" alt="Screenshot 2020-02-20 23 51 05" src="https://user-images.githubusercontent.com/19514207/74952914-e9c49680-543b-11ea-8951-457051dfc21a.png">

**Comment by cervoneluca** [comment]
I saw in the current upstream/master that the issue about the background coloro is already fixed. Is anyone working on  creating a tab (in the activity, resume and so on area) to display the list of followers? 

If not, I should some free hours during this week-end and I can work on it. 

Let me know!
