### ISSUE TITLE
an issue recieving a tip

### ISSUE THREAD

**Issue by Glitch-key** [gitcoinco/web#6043]
Hello I had an issue receiving a tip from someone on gitcoin in ETH, I typed in my metamask address, accepted the terms and clicked claim ETH, now its giving me a message in a red box on the top of the screen saying "You are not on the right web3 network. Please switch to mainnet" even though i click on the metamask logo on the top right of my browser and see that i am on the main "ethereum network" and that "The default network for Ether transactions is Main Net." I've unlocked metamask and everything on gitcoin and im wondering what could be wrong at this point and am drawing nothing but blanks, i'm very new to everything so if the solution is obvious please forgive me.

**Comment by kuhnchris** [comment]
Please use the template for reporting bugs - what browser, what OS, etc.

Thanks.
