### ISSUE TITLE
First click on the comment button does not post the comment

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6046]
When posting a new commit, hitting "Enter" to submit works perfectly, but clicking the "Comment" button does post on the first click but posts on the second click.

Here is a recording of the issue: https://youtu.be/kYtsck_GrxE

**Expected behaviour:**

It should post the comment on the first click.

**Comment by sounak98** [comment]
@owocki this happens to me too, would love to work on this.

**Comment by walidmujahid** [comment]
I do not think anyone is working on this. I am actually facing this issue locally when checked, but I did not actively work to debug this issue. You can ask on Townsquare, but I think you free to work on this if you want to @sounak98

**Comment by walidmujahid** [comment]
Having looked at the button's HTML recently, I am left wondering why the button is a link and not an actual button 🤔

**Comment by sounak98** [comment]
@walidmujahid in HTML links can be styled as buttons. This is commonly done because buttons don't have the href attribute.

**Comment by walidmujahid** [comment]
Is it needed in this case @sounak98 ?

**Comment by walidmujahid** [comment]
@sounak98 Were you able to find a solution to this issue?

**Comment by thelostone-mc** [comment]
Ah so i think it's to do with textbox animation bit ! 
The first time you click -> i guess there is an event listener for the animation which blocks the other event listener responsible for submitting the comment. Not sure though
