### ISSUE TITLE
Comment box gets stuck when you click any comment button with an empty input box

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#6055]
**Describe the bug**

Comment input box gets stuck when you click the comment button with an empty input box. Also after inserting something for comment, first mouse click on the comment button will collapse the input box. to post the comment you need to click the button again. [issue 6046]
**To Reproduce**

1. https://gitcoin.co/townsquare
2. click any comment box underneath any post by keeping the comment box empty.
3. you can't comment in that post unless you reload the page again.
**Expected behavior**

1. Clicking an empty box can show an alert or bring focus the comment box.
**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: NA
- OS: NA
- Browser: NA
- Version: NA

**Additional context**

**Comment by PixelantDesign** [comment]
I had this problem too! Thanks for the report.

**Comment by ekram-syed** [comment]
This issue no longer visible in the latest release. I've tested it. thanks to all contributors.
