### ISSUE TITLE
Town square link preview is showing all text and is super long

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#6056]
**Describe the bug**

When pasting a link on the New Post box, the link preview shows all the text inside that link and ends up becoming super long.
<img width="823" alt="Screenshot 2020-02-23 17 11 55" src="https://user-images.githubusercontent.com/19514207/75109582-beba8c80-565f-11ea-9cf6-0a35dacc6026.png">

When you click Post, it shows up correctly.
<img width="794" alt="Screenshot 2020-02-23 17 14 32" src="https://user-images.githubusercontent.com/19514207/75109610-fcb7b080-565f-11ea-8690-f30ca9c6b91f.png">

**To Reproduce**

1. Paste a link of an article to the New Post box on town square
2. Check the generated link preview

**Expected behavior**

It should show exactly how it looks like when it's posted.
<img width="794" alt="Screenshot 2020-02-23 17 14 32" src="https://user-images.githubusercontent.com/19514207/75109610-fcb7b080-565f-11ea-8690-f30ca9c6b91f.png">

**Comment by thelostone-mc** [comment]
@willsputra thanks for the report ^_^
it's fixed over at ff68427b61b372bf466765b9edbd460b81720964

<img width="815" alt="Screenshot 2020-02-24 at 1 08 15 PM" src="https://user-images.githubusercontent.com/5358146/75135298-237cf200-5707-11ea-9112-3b149f180c1f.png">
