### ISSUE TITLE
logged in user does not persist to 'Chat'

### ISSUE THREAD

**Issue by kdm5126** [gitcoinco/web#6057]
Being logged in and clicking on the chat feature in header of the page bring me to a log in page. gives the option to log in via gitcoin (which I already am) clicking button does not load anything. 

**Describe the bug**

**To Reproduce**
Log in
click chat in header

**Expected behavior**
Brings you to the chat page. 
As a user, I expected this to take me to a comment that I just received an email about. I thought this would be where to find it.

- OS:
- Browser: brave
- Browser Version:Version 1.2.42
- OS: macOS mojave 10.14.6

**Additional context**

**Comment by androolloyd** [comment]
Check your shield settings you likely have cookies blocked. 

Chat needs access to cookies to maintain a session.
