### ISSUE TITLE
No link provided to view Followers in myprofile page.

### ISSUE THREAD

**Issue by krajarajan** [gitcoinco/web#6060]
### Discussion

[comment]: #  In profile page (3 Followers) only label  shown  , no link provided to view followers , is't bug or a feature plan to add  ?

Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)

**Comment by PixelantDesign** [comment]
Thanks for bringing this up! I just funded the issue here https://gitcoin.co/issue/gitcoinco/web/6095/4067
