### ISSUE TITLE
UI fix

### ISSUE THREAD

**Issue by coolcryptomaniac** [gitcoinco/web#6063]
**Describe the bug**
UI design the followers tab needs to be adjusted

**To Reproduce**

check the profile page

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: redmi note 8pro
- OS: android
- Browser: brave

- Version:

**Additional context**

**Comment by developerfred** [comment]
Hi! @coolcryptomaniac, can you send a print screen?
