### ISSUE TITLE
Unable to edit / cancel a Reserved Bounty 

### ISSUE THREAD

**Issue by mainnebula** [gitcoinco/web#6071]
**Describe the bug**
A [bounty](https://gitcoin.co/issue/consensys-space/trusat-backend/91/3926) was created and reserved for a specific Gitcoin user and it cannot be updated or edited. The user has not been online to accept or deny the bounty since its creation. The bounty cannot be cancelled and the funds remain in the contract. 

**To Reproduce**
Create a reserved bounty for a non-active user. 

**Expected behavior**
The bounty should be able to be cancelled when it expires. 

**Desktop (please complete the following information):**

- OS: Catalina 
- Browser: Mozilla 
- Browser Version: 73

**Additional context**

**Comment by danlipert** [comment]
@mainnebula I removed the reservation so you should now be able to cancel it - give it a try and let me know how it goes, thanks!
