### ISSUE TITLE
Investigate Browser-Caching Across Gitcoin for Performance Improvements 

### ISSUE THREAD

**Issue by mkosowsk** [gitcoinco/web#609]
Note: this issue is meant for beginners as a first contribution to Gitcoin. As such, if you have previously made contributions to the gitcoinco/web repo please do not work on this issue... don't even try it, @owocki! 💇‍♂️ 

From #592:

Browser-caching is asking visitors to save and reuse the files included in your website. It can dramatically reduce page load times for repeat visitors.

A good place to start learning about this technique is the Browser-Caching section of 

https://medium.freecodecamp.org/a-beginners-guide-to-website-optimization-2185edca0b72

Research different techniques for browser-caching and see how they affect load times for Gitcoin locally on repeated visits. 

Use a tool such as Chrome's Network Analysis (https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#summary) to screen shot performance improvements for different browser-caching techniques.

After your pull request is merged in, we can see via Google PageSpeed the improvements that your changes brought about! Could make a nice bullet point for the resume :)

<img width="490" alt="mobile" src="https://user-images.githubusercontent.com/7970539/37317936-0cb45762-263e-11e8-80ba-29e88357fbf1.png">

<img width="491" alt="desktop" src="https://user-images.githubusercontent.com/7970539/37317938-0f9bbf74-263e-11e8-970f-3dfa8f9312a6.png">

**Comment by owocki** [comment]
i wonder if we could do anything about far-futures expires headers straight away in django or cloudfront

**Comment by mkosowsk** [comment]
@mbeacom should we tweak CloudFront settings?

**Comment by mbeacom** [comment]
One problem I see moving forward are the static assets we reference directly in css.  A lot of our fonts and some `png` files are directly specified.  The max-age for those assets is only `60` versus `315360000` for all hashed assets.  I could see it making sense to modify font caching for sure.
Assets with a low `max-age` from gitcoin.co index page:

```
    https://cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css (expiration not specified)
    https://sumo.com/api/load/ (expiration not specified)
    https://gitcoin.co/static/v2/fonts/Muli/Muli.ttf (60 seconds)
    https://gitcoin.co/static/v2/fonts/futura/font4.ttf (60 seconds)
    https://gitcoin.co/static/v2/images/footer.jpg (60 seconds)
    https://gitcoin.co/static/v2/images/header-bg.png (60 seconds)
    https://gitcoin.co/static/v2/images/light-bg.png (60 seconds)
    https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js (10 minutes)
    https://fullstory.com/s/fs.js (10 minutes)
    https://load.sumo.com/ (10 minutes)
    https://static.doubleclick.net/instream/ad_status.js (15 minutes)
    https://www.googletagmanager.com/gtm.js?id=GTM-M66Q83Q (15 minutes)
    https://connect.facebook.net/en_US/fbevents.js (20 minutes)
    https://connect.facebook.net/…config/539768073058141?v=2.8.12&r=stable (20 minutes)
    https://www.google-analytics.com/analytics.js (2 hours)
```
