### ISSUE TITLE
Hover over black box on tips + matching glitches on townsquare

### ISSUE THREAD

**Issue by calchulus** [gitcoinco/web#6092]
**Describe the bug**

I think it's b/c the box goes over the text box to post, and they are clashing, so it keeps closing it, but the hover logic opens it repeatedly each time b/c the mouse is still over the black box.

**To Reproduce**

just hover over the first one

**Expected behavior**

the tooltip should display
**Screenshots**

**Desktop (please complete the following information):**
mac
- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by PixelantDesign** [comment]
Do you have a screenshot?

**Comment by thelostone-mc** [comment]
Closing as we don't have enough info
