### ISSUE TITLE
Tribes Email Funnel / Content

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6099]
### User Story

Tribes Email Funnel / Content

### Why Is this Needed

When we release tribes, we'll want an email sales funnel that not only introduces useful content, but is persuasive and brings both funders and contributors onboard to the positioning of Tribes.

### Description

I was thinking we can have separate email funnels & content for funders and contributors.

**Funders**

1. email notification of suggested bounty - when someone suggests an idea and/or bounty

    - [ ] show what the idea suggestion is
    - [ ] content around "these are idea suggestions directly from your contributors"
    - [ ] content around "this helps contributors build off of your protocol"
    - [ ] content around "this helps get more submissions for your hackathons"

2. weekly email

    - [ ] current weekly digest design: https://www.figma.com/file/dHVqQVBY1GEWGvOtN4dOPH/Marketing-Emails?node-id=0%3A1
    - [ ] we want a summary section of how their tribe is performing
        - [ ] + followers WoW
        - [ ] + number of ideas & bounties suggested WoW
        - [ ] top organization townsquare comments
        - [ ] other content ideas?

3. email sales funnel - we're grabbing the funder's attention regarding tribes

* the value proposition email (free value) - feature-related solutions we want to touch on:
    - [ ] every organization will have a tribe organization page, we should provide a link to this page, and also embed what they can see without paying, and how that value might be of use to them
    - [ ] the townsquare is where contributors can follow you, and you can view who is following you

* the pitch - feature-related solutions we want to touch on:
    - [ ] suggest a bounty / idea
    - [ ] ability to reach out to your tribe members on-demand
    - [ ] relay your priorities and bounties directly to your tribe

* objection killer email - funders will have objections or questions:
    - [ ] what happens if I don't get good ideas from my tribe?
    - [ ] what happens if I don't get submissions?
    - [ ] what happens if I don't have enough members in my tribe?

* last chance email - tribes won't close but should we generate some demand?
    - [ ] last chance to grow your protocol using gitcoin's network
    - [ ] exclusive deal?

**Contributors**

For contributors, they contribute to Tribes, but aren't the buyers, so their path will probably look a little different.

1. the hook & value proposition email - introduces them to the concept of tribes

    - [ ] what the hell is tribes?
    - [ ] understand that they can follow particular tribes to be exposed to more organization-directed work
    - [ ] how you can optimize your workflow for tribes

2. the action closing email 

    - [ ] follow tribes on the explore page
    - [ ] check out the townsquare tribe filters
    - [ ] suggest an idea or bounty
    - [ ] comment or give clr on townsquare

### Additional Resources (Private Access)

1. Gitcoin Tribes Positioning
2. Funder & Contributor Interview Quotes
3. Tribes v1 Offering
4. Tribes Landing Page

### Current Behavior

- no email funnel content for tribes

### Expected Behavior

- an email funnel for contributors and funders to introduce and persuade for the Gitcoin Tribes product

### Definition of Done
- [ ] designs for the emails
- [ ] content copywriting
- [ ] QA

### Data Requirements
- [ ] standard CTR email impression / email open rate
- [ ] final conversion rates

**Comment by fluffays** [comment]
1st draft has arrived => https://docs.google.com/document/d/1mk9MKlQHRc_9_x-CIwqGwB9q6wl6SfHTzq-gMGq-lWw/edit#

**Comment by frankchen07** [comment]
awesome @fluffays - we'll take a look!

**Comment by PixelantDesign** [comment]
hey guys is this still in progress?

**Comment by frankchen07** [comment]
closed for now
