### ISSUE TITLE
Bounty Life-cycle

### ISSUE THREAD

**Issue by EntityAdam** [gitcoinco/web#61]
Purpose of this issue: Define guidelines and the process of expressing intent, completing work, and claiming bounties.

Intent: Allow operators to express intent, communicate progress with the issuer and other potential bounty hunters as well as allow the issuer to provide acceptance criteria

1. Interest
    - Interested, save this for later (bookmark equivalent)
    - Interested (Discovery, or "I would like a little more information on the project)
    - Your level of experience on this issue
        - Novice
        - Mid level
        - Senior
        - Expert
2. Production
	- Started working on _DATE_
	- Expected to finish on _DATE_
3. Acceptance queue (FIFO)
	- Rejection
		- Completed issue does not meet acceptance tests
		- Product has major deficiencies and is rejected
		- Must be resubmitted, which puts that operator to the bottom of the queue
	- Remediation
		- Completed issue does not meet acceptance tests
		- Product has minor deficiencies and is put in remediation status
		- Remediated does not lose its place in the FIFO queue.
	- Acceptance
		- Passes issuer supplied unit tests (if applicable)
		- Passes issuer supplied acceptance criteria
		- Payment

**Comment by EntityAdam** [comment]
Yeah absolutely. If the "express interest" button adds a list of users to the bounty itself, you can couple the above future functionality to the the users instead of the bounties. Which would provide more isolation and ease development and maintenance.

**Comment by owocki** [comment]
@EntityAdam @mbeylin thoughts on https://github.com/gitcoinco/web/pull/62 as a stopgap?

**Comment by owocki** [comment]
i feel like this work helps solve this... https://gitcoincommunity.slack.com/archives/C55FER6T1/p1517341954000234
