### ISSUE TITLE
Double Tip Notification

### ISSUE THREAD

**Issue by loganbek** [gitcoinco/web#6101]
**Describe the bug**

Receiving received tip notification twice

**To Reproduce**

Receive tip.

**Expected behavior**

Should get 1 notification.

**Screenshots**

<img width="432" alt="Screen Shot 2020-02-29 at 2 07 59 AM" src="https://user-images.githubusercontent.com/9355004/75605509-5709a480-5a98-11ea-9ed7-5cf4b4e1eab6.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Brave 
- Browser Version: Nightly Dev

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

verified other users receiving too.

**Comment by ekram-syed** [comment]
verified using chrome (Version 80.0.3987.122 (Official Build) (64-bit) on windows. for each tip, we are getting duplicate notification.

**Comment by alialiwa2005** [comment]
Verified using Trust Wallet on Android 9.0

**Comment by alialiwa2005** [comment]
I am also getting tip notifications, although not all are duplicate ones, and I don't recieve the tips in my ETH wallet.
