### ISSUE TITLE
0x7F4B0fc7c8BD0fe9e472B9F66e89EEC1BE52089f

### ISSUE THREAD

**Issue by arun0930** [gitcoinco/web#6102]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by developerfred** [comment]
@arun0930 ?

**Comment by arun0930** [comment]
0x7F4B0fc7c8BD0fe9e472B9F66e89EEC1BE52089f
