### ISSUE TITLE
Mint our own token on matching, in addition to ETH

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6110]
### User Story

As a contributor I want the following feature, to get more ETH.

Create an ERC-20 token SOFT.

When GitCoin does CLR (both grants CLR and Mini CLR), mint to the user considered the amount of SOFT tokens numerically equal to the summary value of contributions to the user and GitCoin's matching.

### Why Is this Needed

The philosophy is simple: We are giving not enough ETH to users despite all our attempts. We should give more. If we give them SOFT tokens, they would probably sell it and get some (much or not much, we don't yet know) additional ETH, what is a good thing.

### Description

*Type*: Feature

### Definition of Done

Fully functional distribution of SOFT tokens in production GitCoin.

**Comment by vporton** [comment]
You should match all donations, not only future ones but also all past ones.

**Comment by thelostone-mc** [comment]
This sort of decision would be better be proposed snapshot where the DAO can vote.
