### ISSUE TITLE
In Activity feeds (User or Global), Kudos links are missing

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#6111]
In Activity feeds (User, Global), Kudos are rendered like a clickable element (using <a> tag) but the links don't point to the associate Kudos element (empty href value in the source)

**Describe the bug**

The links should point to the associate Kudos pages or render kudus as non-clickable elements on the activity feed. 

**To Reproduce**

1. Go activity feed page from top nav or user profile.
2. mouse hover any Kudos element
3. clicking will redirect to the same page.

**Expected behavior**

Links should be point to the associate Kudos page.

**Screenshots**

https://imgur.com/aJDmxNm
**Desktop (please complete the following information):**

- OS: all
- Browser: all
- Browser Version: all

**Smartphone (please complete the following information):**

- Device: all
- OS: all
- Browser: all
- Version: all

**Additional context**

**Comment by developerfred** [comment]
I will fix this.

**Comment by developerfred** [comment]
@ekram-syed This is very strange the code is correct and is passing the url, I need to investigate further.

**Comment by ekram-syed** [comment]
I'll update this when the changes roll out to the live system.
