### ISSUE TITLE
Feature: Truly social FREE ads

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6113]
### User Story

As a developer, I want to show ads for free so that good project become big immeditely without waiting years when they raise (if ever) through other means.

### Why Is this Needed

We have a good project without money. It has no donations/upvotes because its page is not visited. It is not visited because it has no donations/upvotes.

### Description

*Type*: Feature

### Expected Behavior

We need truly social _free_ ads: The ads would have up/down buttons. If even a small part of community voted 100% up, the ad should be given the highest priority like a big one showing much of the total percent. Well, need to protect against the case like 1-2 votes only (requires some math statistics calculations).

I propose to show such ads at GitCoin site and in the publisher network (sometimes).

**Comment by vporton** [comment]
It may work even better if we add a button with "double thumb" meaning "like very much" or even better allow the user to select 1-5 stars.

Also clicking on ad link should count like a thumb up.

**Comment by vporton** [comment]
We also should support a search engine finding such ads, with the order of the results being determined by the number of thumbs up (or stars).

**Comment by vporton** [comment]
A related math statistics problem: https://math.stackexchange.com/q/3583587/4876

**Comment by vporton** [comment]
To constrain abuse of the system by posting too many ads by a single user with the purpose to gain more exposure, we could allocate impressions per GitHub organization.

If there will be nevertheless too much spam, think later.

**Comment by vporton** [comment]
Ad links should open in a new tab, to be sure the user can rate the ad afterward.

**Comment by thelostone-mc** [comment]
We did try doing something along these lines with codefund but we weren't able to generate enough traction.
Closing this out now until we decide to revisit ads (will reopen at that point in time)
