### ISSUE TITLE
inconsistency between notifications on tips and actually received tips

### ISSUE THREAD

**Issue by cervoneluca** [gitcoinco/web#6118]
**Describe the bug**
The notify system tells that I received tips but actually I never received them. Also, there is inconsistency between the "tips" section in my profile system and the notify view. 

**To Reproduce**

See the attached screenshot

**Screenshots**
<img width="1675" alt="Schermata 2020-03-03 alle 11 14 51" src="https://user-images.githubusercontent.com/3637606/75766398-61020080-5d41-11ea-9a7b-e535bddc31d0.png">

**Desktop (please complete the following information):**

- OS: macOs 10.15.3
- Browser: Brave Browser
- Browser Version: 1.3.115

**Comment by cervoneluca** [comment]
Happened again.  See attached screenshot

<img width="1211" alt="Schermata 2020-03-04 alle 07 39 26" src="https://user-images.githubusercontent.com/3637606/75852008-52702380-5deb-11ea-8f4b-12cbfffa8697.png">

**Comment by owocki** [comment]
> The notify system tells that I received tips but actually I never received them. 

what does "actually received them" mean? its possible theyre still just pending on -chain but without txids its hard to say

**Comment by cervoneluca** [comment]
Sorry, commas are important. 
I mean that the notify system says that I received tips. However I didn't received them.

**Comment by cervoneluca** [comment]
To be more clear, I mean that I never received tips at my ethereum address, and there seems that transactions for those tips were never created

**Comment by owocki** [comment]
when i look at your ethereum address i see a few inbound tips.  the timestamp of this one, for example, matches a tx on chain. https://gitcoin.co/townsquare?tab=activity:151603

 mind singling out a couple activity posts where you didnt receive the tips and linking them here?

**Comment by cervoneluca** [comment]
Hi Kevin. 
I can't link the posts where I didn't received tips because I'm not able to find them. 

Look at this screenshoot: 

<img width="1675" alt="Schermata 2020-03-03 alle 11 14 51" src="https://user-images.githubusercontent.com/3637606/75766398-61020080-5d41-11ea-9a7b-e535bddc31d0.png">

There are two tips, one from delevoperfred and one from L-KH. 
So, as you can see, tips are reported by the notification system although they are not in the activity feed. 
This means that neither I'm able to see which post the two users tipped, nor I have a transaction in my wallet related to this two tips. 

Of course, I'm not arguing about the two tips, I'm just trying to understand why this happens. 

Also, take a look at this screenshoot:

<img width="1211" alt="Schermata 2020-03-04 alle 07 39 26" src="https://user-images.githubusercontent.com/3637606/75852008-52702380-5deb-11ea-8f4b-12cbfffa8697.png">

In the notifications popup, as you can see, the second and the third notifications are about tips from you. However, actually the two notifications are related to the same tip (https://gitcoin.co/townsquare?tab=activity:151603). 
When you tip me (and only when you tip me) I always receive a double notification about your tip. 

Hope that now the issue is more clear. 
Thank you!

**Comment by thelostone-mc** [comment]
This issue was not reproducible when i tried it recently. Will reopen if this pops up again
