### ISSUE TITLE
Metamask Cant Coneccted to Gitcoin in Mobile version

### ISSUE THREAD

**Issue by Makondor2** [gitcoinco/web#6125]
**Describe the bug**

**To Reproduce**

**Expected behavior**
cant connected to gitcoin...i already open permission for metamask but result still same

**Screenshots**

![Screenshot_20200304-122033](https://user-images.githubusercontent.com/53736312/75847742-99254400-5e12-11ea-8eae-31365cceabe0.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: InfinixX573-LTE
- OS: Hummingbird XOS3.0
- Browser:MainEthereumNetwork
- Version:Metamaskv0.2.13(26)

**Additional context**

**Comment by developerfred** [comment]
I recently saw this bug in other projects, I believe it is an update of  metamask

**Comment by developerfred** [comment]
If you are using your metamask as a mirror of your ledgerwallet I advise you to make a native metamask wallet to interact with DAPPs

https://github.com/iearn-finance/iearn-finance/issues/41

**Comment by owocki** [comment]
root cause : https://github.com/MetaMask/metamask-mobile/issues/1273
