### ISSUE TITLE
https://gitcoin.co/quests/94/newtons-law-of-transaction-and-reaction - has a broken prep link (404).

### ISSUE THREAD

**Issue by loganbek** [gitcoinco/web#6126]
**Describe the bug**

https://gitcoin.co/quests/94/newtons-law-of-transaction-and-reaction - has a broken prep link (404).
**To Reproduce**

Play Quest, click prep link

**Expected behavior**

Should see quest prep but get a 404 error.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Brave
- Browser Version: Nightly Dev

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by developerfred** [comment]
https://docs.dfuse.io/guides/ethereum/tutorials/lifecycle/

**Comment by owocki** [comment]
just fixed this

**Comment by loganbek** [comment]
Retested and the link now works correctly.
