### ISSUE TITLE
status update, attach youtube video doesnt work anymore.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6132]
**Describe the bug**

status update, attach youtube video doesnt work anymore.

**To Reproduce**

put a youtube video in status update form

**Expected behavior**

video preview should show before posting, andn then the video should display inline after posting

**Comment by owocki** [comment]
looks like the API key is over quote

we get this results:

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceeded",
    "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=1064792076301",
    "extendedHelp": "https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=1064792076301"
   }
  ],
  "code": 403,
  "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=1064792076301"
 }
}
```

**Comment by owocki** [comment]
@zoek1 any ideas of what to do here? is the API key in the code one u registered for us?  maybe its worth putting the key into settings.py (where we keep our secrets).

i wonder if someone has stolen the key out of our codebase and is using it for their own reasons..

**Comment by zoek1** [comment]
I checked the dashboard but theres no strange behavior. For the moment i límited the usage to gitcoin.co domain. I'll make the PR to move this key to settings. @owocki

**Comment by zoek1** [comment]
@owocki the key is different from what i provided. @octavioamu could you check the api usage to see if someone stolen the key? One important thing is verify if the key is restricted to gitcoin domain: 
![image](https://user-images.githubusercontent.com/660973/75958322-93b31280-5e81-11ea-8ec2-e75da0f808d4.png)

**Comment by owocki** [comment]
@octavioamu do u have the key dashboard? can u share with me?
