### ISSUE TITLE
try to beat this quest https://gitcoin.co/quests/59/upgrade-or-dai

### ISSUE THREAD

**Issue by hamzaghz** [gitcoinco/web#6135]
if uu played the quest ''Upgrade or Dai'' , when it comes to the last question and selected the right answer, strangely the outcome showed will be that you failed to beat 

**Describe the bug**
 if you take a look at your profile you will find that you beat the quest without obtaining the kudos

**To Reproduce**
just play the quest and see by yourslf
==> https://gitcoin.co/quests/59/upgrade-or-dai

**Expected behavior**
 normally I will be the winner and I should claim the prize/ kudos 

**Screenshots**

==> https://share.getcloudapp.com/7KuRbP6d
==> https://share.getcloudapp.com/JruWq4yL
**Desktop (please complete the following information):**

- OS: w7
- Browser: chrome 
- Browser Version: 80.0.3987.122 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: MI 6X ( I tried on smartphone and i found the same problem)
- OS: android 8.1.0
- Browser: chrome 80.0.3987.119
- Version: 80.0.3987.119

**Additional context**

**Comment by owocki** [comment]
i just put a fix in for this . try now pls

619435764cd55243d9f229081035c426041e0d12
