### ISSUE TITLE
Activity Tags are not working on page refresh - Local Docker

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6136]
Tested as of 18ab994a8f8f7464590d6489a242b69c31d5f358
Docker 2.2.0.3 (42716) Stable
Windows 10 Pro Version 1909
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Bug Description:** 

The `span.num` for comment counts does  not show the comment count and the comment section is automatically hidden.

Video: https://youtu.be/5S3W5OJzAMU

**Update:** This issue includes the tip amount and like count. 

**To Reproduce:**

Build master, at 18ab994a8f8f7464590d6489a242b69c31d5f358, locally in Docker. If on the "Connect" tab, post at least one status update otherwise page stalls -Issue: TBD.  

Comment on the status update, then reload the page. The count will be at 0 and the comment section will be hidden. 

**Update:** New likes will also not show up on page refresh and tip amounts is facing the same issue. 

**Expected behaviour:**

The comment count should show up and the comment section should automatically be open if there are comments.

**Comment by walidmujahid** [comment]
Could the new `refresh_activities` task be causing this? Or a problem with an Activity instance's `cached_view_props`?

**Comment by octavioamu** [comment]
seems is a problem with cache

**Comment by owocki** [comment]
you just need to make sure the web_worker is running. thatll update the comment count

**Comment by walidmujahid** [comment]
@owocki @octavioamu I see. 

The worker container is exiting  with code 2. Doing `docker-compose logs -f worker` gives me: 

``worker_1     | ./bin/celery/worker/run.sh: line 2: $'\r': command not found
: invalid option namecelery/worker/run.sh: line 3: set: pipefail``

The scheduler also seems to be exiting with code 2. The foreground logs show:

``scheduler_1  | ./bin/celery/scheduler/run.sh: line 2: $'\r': command not found
: invalid option namecelery/scheduler/run.sh: line 3: set: pipefail``

**Comment by owocki** [comment]
hmmm.. @androolloyd built that container.. maybe he knows?

**Comment by androolloyd** [comment]
Hmm, are you on windows? Looks like an issue with linebreaks.

is your encoding set to UTF8?

**Comment by androolloyd** [comment]
> @owocki @octavioamu I see.
> 
> The worker container is exiting with code 2. Doing `docker-compose logs -f worker` gives me:
> 
> The scheduler also seems to be exiting with code 2. The foreground logs show:
> 
> `scheduler_1 | ./bin/celery/scheduler/run.sh: line 2: $'\r': command not found : invalid option namecelery/scheduler/run.sh: line 3: set: pipefail`

We're removing the scheduler definition in a future update as we're not using it presently, you can comment it out for now.

**Comment by walidmujahid** [comment]
> Hmm, are you on windows? Looks like an issue with linebreaks.
is your encoding set to UTF8?

@androolloyd Yes, I am on Windows 10 Pro Version 1909.  Yes, I am using UTF8. My editor, Atom, is also set to UTF8.

**Comment by walidmujahid** [comment]
@owocki @androolloyd I fixed this in https://github.com/gitcoinco/web/pull/6175
