### ISSUE TITLE
As a funder, I want to hide submissions and downgrade the status of a bounty

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#614]
##### Description

There is no current way for bounty funders to hide unwanted/unaccepted submissions to update the `gitcoinbot` comments on the Github issue or revert the bounty status out of `work submitted` if all current submissions are invalid.

##### Possible Implementation

- Add attribute to `BountyFulfillment` of something like: `rejected`, `hidden`, 'inactive', `ignored`, or `invalid` and `default=False`
- Surpress or uniquely identify `BountyFulfillments` passed to `bounty_details` that are hidden/inactive.
- Provide an option on the frontend in bounty details for the funder to reject a valid fulfillment that hasn't been accepted.
- Add signal logic to catch updated `BountyFulfillment` where `rejected=True`, notifying the fulfiller, and updating the github submissions comment.

Similar to:  #463 - But we'll want to merely update the `BountyFulfillment` versus removing the impression.

Original request:  https://gitcoincommunity.slack.com/archives/C8E45J5D0/p1520960296000556
<img width="659" alt="screenshot 2018-03-13 13 17 13" src="https://user-images.githubusercontent.com/7315957/37358210-ddafd77e-26c0-11e8-8161-7d00125e81ed.png">

**Comment by owocki** [comment]
@mbeacom your suggested implementation makes sense to me.  the only thing about doing it off chain though is that @mbeylin and the Bounties.Network won't know that the submission has been rejected. 

related https://github.com/Bounties-Network/StandardBounties/issues/27

**Comment by mbeylin** [comment]
I think at this junction it's OK for the rejection to only live on Gitcoin.

In terms of implementing this though, I'd advise you guys to make sure you get the issuer to actually sign a rejection message or something, otherwise people could spoof their address (through the web3 object), and reject other people's submissions off-chain without the issuer even knowing.

**Comment by mbeacom** [comment]
@mbeylin That makes sense 👍 
I'm fine with doing proceeding in that direct.  Just as an additional discussion point, we could check whether or not the user is authenticated as the bounty owner via the GH integration as well (not as nice as signing a rejection message), but it would offer some validation.

**Comment by kuhnchris** [comment]
@thelostone-mc do you know if this is still the case?
