### ISSUE TITLE
My Threads doesn't capture all of my town square activity.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6140]
**Describe the bug**
Clicked on My Threads on Townsquare to see if I got any responses to one of my posts.
That particular post wasn't in My Threads, but it showed on my profile activity.

**To Reproduce**
Post something in townsquare.
Go to My Threads in the left rail - see if it is there.
Go to your Profile, and likely you'll see it there.

**Expected behavior**
All of my Posts in townsquare shows up in My Threads

**Screenshots**
**My Threads Townsquare screenshot**
<img width="1234" alt="Screen Shot 2020-03-04 at 8 26 34 PM" src="https://user-images.githubusercontent.com/238235/75938921-f2af6200-5e56-11ea-96c6-f242630c743e.png">

**Profile screenshot**
<img width="1120" alt="Screen Shot 2020-03-04 at 8 25 56 PM" src="https://user-images.githubusercontent.com/238235/75938974-0e1a6d00-5e57-11ea-99ec-d621465e7da2.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome 
- Browser Version: Version 79.0.3945.130 

**Additional context**

**Comment by developerfred** [comment]
@PixelantDesign Today the Townsquare Threads displays the threads from the last 24 hours, do you want to display them all? I think we can add more information to this filter

**Comment by PixelantDesign** [comment]
Thanks for hopping on this @developerfred 

Let’s display for the last week. And add a button at the bottom to see all- directing the user to profile.

**Comment by PixelantDesign** [comment]
Also currently it says this:

<img width="467" alt="Screen Shot 2020-03-05 at 8 42 00 AM" src="https://user-images.githubusercontent.com/238235/75987066-40f74c00-5ebd-11ea-9609-c5350ad1c38f.png">

Would be great to update the tooltip based on the changes.
