### ISSUE TITLE
Let 'Start Work' activities include the work plan and include link to submitted work in 'Submit Work' activities

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6142]
From: https://gitcoin.co/townsquare?tab=activity:156395

> Request: on the 'Hackathons' Tab -- I'd love if 'Start Work' included the work plan in the Town Square and 'Submit Work' included the link to the submitted work. 
https://imgur.com/a/rZnkdYs

**Comment by walidmujahid** [comment]
I will make WIP PR for this soon.

**Comment by PixelantDesign** [comment]
Love this idea! Thanks @walidmujahid!
