### ISSUE TITLE
prevent users from sending tips to themselves

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6145]
**Describe the bug**

Currently a user can keep tipping himself all the time.

**Expected behavior**

**Screenshots**

<img width="634" alt="Screen Shot 2020-03-05 at 02 11 01" src="https://user-images.githubusercontent.com/57037080/75949993-ba277c80-5e86-11ea-8bd5-7b6e4ad5173e.png">

**Comment by asmerella** [comment]
Hi

**Comment by ekram-syed** [comment]
Should not be a problem I guess. that doesn't keep up with the matching algorithm.
