### ISSUE TITLE
New Comment Email is Busted

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6147]
**Describe the bug**
New comment email looks busted. 
![22725F71-4F3D-496B-BE28-F382FC9EACC6](https://user-images.githubusercontent.com/238235/75969810-79872d80-5e9d-11ea-9fe6-46d3e2a3a48b.png)

**To Reproduce**
Open/view email on mobile
See missing Gitcoin logo
Fonts are not correct

**Expected Behavior**
See a nicely branded email

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: iphone, mail app

**Additional context**

**Comment by PixelantDesign** [comment]
@developerfred @walidmujahid  interested?

**Comment by walidmujahid** [comment]
@PixelantDesign I will add this to my list of things to work on.

**Comment by developerfred** [comment]
hey @walidmujahid you still working on this issue?

**Comment by walidmujahid** [comment]
@developerfred Yes. I added to my list of thinngs to work on 👍

**Comment by PixelantDesign** [comment]
@walidmujahid are you still working on this issue?

**Comment by walidmujahid** [comment]
@PixelantDesign This is still on my task list, but I have yet to start work on it. II want to say I can get to this within the next couple of days this week, but if @developerfred is available and still interested in this, I will step away from this one.

**Comment by PixelantDesign** [comment]
@developerfred, interested?
