### ISSUE TITLE
https://stage.gitcoin.co is 502

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#6148]
**Describe the bug**

I want to test if performance bug is fixed, but can not. :(

https://stage.gitcoin.co

![image](https://user-images.githubusercontent.com/8781107/75980087-e1b42e80-5ef2-11ea-89ac-98fc83c09e55.png)

**Comment by developerfred** [comment]
you can test in a local environment on the branch stage.

**Comment by abitrolly** [comment]
@thelostone-mc was there a decision to decommission https://stage.gitcoin.co/ or you just closing stuff?
