### ISSUE TITLE
Applicants Not Loading on Dashboard

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6151]
**Describe the bug**
Applicants Not Loading on Dashboard

(octavio edit) https://sentry.io/organizations/gitcoin/issues/1248897468/?project=1398424&query=is%3Aunresolved

**To Reproduce**
Go to Gitcoin Dashboard, view issue with applicants. No applicants displayed

**Expected behavior**
Applicants are displayed

**Screenshots**

Bounty URL

https://gitcoin.co/issue/gitcoinco/web/6121/4085

<img width="1114" alt="Screen Shot 2020-03-05 at 9 01 53 AM" src="https://user-images.githubusercontent.com/238235/75989067-93863780-5ec0-11ea-9aff-f104265fd5ee.png">

Clicked View Applicants, nothing loads

<img width="1100" alt="Screen Shot 2020-03-05 at 9 02 01 AM" src="https://user-images.githubusercontent.com/238235/75989071-954ffb00-5ec0-11ea-9f10-6646d6c5cb10.png">
<img width="557" alt="Screen Shot 2020-03-05 at 9 04 49 AM" src="https://user-images.githubusercontent.com/238235/75989075-97b25500-5ec0-11ea-95ba-0ac6e1e99e5a.png">

**Desktop (please complete the following information):**

- OS:Mac
- Browser: Chrome
- Browser Version: Version 79.0.3945.130 (

**Comment by developerfred** [comment]
Hey @PixelantDesign!
I believe it is because the staging server is down.
https://github.com/gitcoinco/web/issues/6148
