### ISSUE TITLE
Add "Share" Post Option

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6164]
### User Story

As a user there will be posts by other people that can be of interest and is worth sharing across the platform.

### Why Is this Needed

Gitcoin currently don't have this function. Instead of copying the link of the post, if there is an ability to share posts, it will be more easier to share information with other users.

### Description: 
Add a "Share" option in the posts/status

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
isnt that what 'copy link' is?

**Comment by dadahaha2020** [comment]
A one click "share" is faster if one intends to share a post just within the platform. Maybe we can replace the "copy link" with "Share".

Once "Share" is clicked, ask two question 1. Share internal - sharing within the platform; 2. Share external - this is where copy link will be so it can be shared outside the platform.

Typically this is the same with Facebook.
