### ISSUE TITLE
Reward issue reports with tips

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6166]
Please automatically send a matched tip (like as in Townsquare) to every bug/feature reporter here in issues.

The tip should not be sent if the issue is deleted during 12 hours after its publication (as an anti-spam feature).

**Comment by owocki** [comment]
i think that github work should absolutely be rewarded.  

donno how plausible sending these tips manually is tho.. maybe a solution like https://sourcecred.io/ can be the answer

**Comment by vporton** [comment]
Note that it should also reward all _past_ issues and comments, not only future ones.
