### ISSUE TITLE
Account not in CLR.

### ISSUE THREAD

**Issue by alialiwa2005** [gitcoinco/web#6168]
### Who
Me, Ali Saleh.

### What 

After the first CLR round, starting from the second CLR round, my account, @alialiwa2005, is not present on the leaderboard nor is it showing status of CLR on/near Gitcoin profile.

### Why

Unsure.

**Comment by owocki** [comment]
In round 1, according to a community report we received, you sybil attacked on the townsquare CLR (donating to himself, making multiple accounts and all donating to each other).

**Comment by alialiwa2005** [comment]
I did not donate to myself, but I did see random accounts donating to mine. (I didn't recieve those tips from random accounts though. https://github.com/gitcoinco/web/issues/6167) 

But I see why you may suspect I was donating to myself. 

If there is a way to further prove I am innocent, please let me know and I will show it wasn't me who manipulated the system.

I don't think I am the only person with the same issue of being tipped/trolled.

**Comment by owocki** [comment]
@danlipert ali pleads not guilty

**Comment by octavioamu** [comment]
@alialiwa2005 you own at least these accounts and used to make tips to your main account
credissimonexo
mapleproject
gitcointranslator

**Comment by alialiwa2005** [comment]
No, these are fake accounts, impersonating me. I do not own any of them, but I have been falsely tipped by them before.

If there is a way for me to prove that I do not own the accounts above, please let me know and I shall prove I have no affiliation with the listed usernames.

**Comment by octavioamu** [comment]
Ok, so can you explain this?
https://etherscan.io/tx/0x62f5ec393c66f0f88785a15e1441455e95bca9177f68644cb3210cb848a53e98

**Comment by octavioamu** [comment]
Any update @alialiwa2005 ? I was waiting some sincerity here to be true. 
I believe you are a valuable community member but you strongly failed doing this. 
Help me to help you man.

**Comment by alialiwa2005** [comment]
Hi.

I've been thinking about this recently, so I decided to visit this issue again.

Yeah, I believe I've made a silly and childish mistake back then, and even lied about it before.

I'm sincerely sorry. It makes sense why I was removed from the CLR rounds.

I won't do this again, on any platform, even if I'm not re-added into future rounds, and I take this as a lesson.

If I discover a bug like this in the future, I will promptly disclose it privately and directly with the developers.

I still use Gitcoin, and I believe it is a great platform.

Looking back, I'm am very lucky to have my main account, @alialiwa2005, not banned, and to be able to continue using Gitcoin and to be a part of the wonderful community (thank you for letting me keep this), and to have had been taught a valuable lesson.

**Comment by alialiwa2005** [comment]
> Any update @alialiwa2005 ? I was waiting some sincerity here to be true. I believe you are a valuable community member but you strongly failed doing this. Help me to help you man.

Hi, yeah... sorry about that. 

Silly thing I've done in the past as a kid.

I've surely learned from my mistake, and I won't do something like this again.

Going forward, I hope to continue doing my part in the Gitcoin community, without doing things like this.
