### ISSUE TITLE
You received a new kudos from owocki' from about 6 hours 

### ISSUE THREAD

**Issue by molecula451** [gitcoinco/web#6171]
**Describe the bug**

 Seen a notification of Owocki sending a kudos and the user being unable to see any transaction.

**To Reproduce**

@walidmujahid 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Blockchayne** [comment]
Phantom Notification - User received phantom notification of ‘New Tip’ (from @owocki) but no transaction can be located in the activity feed nor in the transaction history. In addition, the notifications come in pairs. Two or more duplicates of the same notification.  


Device: IPhone 7 Plus 
iOS 13.3.1
Chrome Mobile 

![Uploading A5223FCC-B5F2-4ACD-905E-EF075FDCC883.jpeg…]()

**Comment by walidmujahid** [comment]
I should have taken screenshots and written down my observations the moment I noticed them, now I do not have screenshots. About a ago, and similarly a few days ago, two separate instances, I recieved a notification 'You received a new kudos from owocki' and I went to check and I saw nothing in the transactions feed. 

Both times I think had gone through a quest, but I already recieved kudos from gitcoinbot, but I am uncertain if this is related. 

For @Blockchayne's issue, the problem might be that a tip notification is sent even though it canceled in MetaMask. I am not sure. If it is, then this PR https://github.com/gitcoinco/web/pull/6115 might solve that as well, but I would have to figure out if the empty tip notifications are indeed a result of cancelation and optimistic UI.

**Comment by Blockchayne** [comment]
@walidmujahid that is an excellent assessment of the issue I experienced. I also experienced the problem with the cancelled transaction/ optimistic UI. Usually I would be in agreement that this was likely the cause, however, I believe these two phantom tips are actually replayed from the previous day when i received two tips from @owocki of similar amounts. My suspicion is that something re-triggered the notifications from the previous day. The best way to determine this is likely to consult with @owocki and see if he recalls any such cancellations. 

![6D863368-2339-4EF1-B0CE-7A0D62CF9162](https://user-images.githubusercontent.com/18696386/76152037-1bb73900-6089-11ea-9b86-52489067ca6c.png)

**Comment by molecula451** [comment]
Oh yeah. It seems I realize today there was also a notification for a suppose Kudos he sent one but it was from February

![l](https://user-images.githubusercontent.com/41552663/76155021-a9604c00-60bc-11ea-9d1f-3d47617fdd25.png)

**Comment by Blockchayne** [comment]
Guys. I am happy to say that I have figured out exactly how to reproduce the error. I believe it’s actually quite simple. The phantom notifications that suddenly appear where there is no corresponding transaction, is actually just old notifications of transactions that have already been completed. The notification seems to be associated with the “Like” button whereas if someone taps the ❤️ Icon on a tip status showing that @owocki sent me a 0.01 ETH tip dated two weeks ago, this action in the current time would trigger a new notification which may cause me to believe @owocki sent me a 0.01 tip just not.  When I’m fact he has not.  This same vulnerability can occur whether it is an eth tip transaction status or even a kudos send status transaction.  I reproduced it on video but I will include the screenshots for simplicity. 😁

![840C66D8-6736-4D3A-85E9-2A728D36449D](https://user-images.githubusercontent.com/18696386/76155731-17594300-60be-11ea-9d16-930907369125.jpeg)
![BE7C4885-27B9-4A73-8562-641A5B82AE77](https://user-images.githubusercontent.com/18696386/76155733-1de7ba80-60be-11ea-8cbf-f253ae0687c8.jpeg)
![1E725B13-0B0D-4ED5-AE49-AD4F27C7645F](https://user-images.githubusercontent.com/18696386/76155735-2d670380-60be-11ea-8978-d5da4bc4e1cf.jpeg)
![B3866C78-F670-4FDE-B423-4B3B634A3FD4](https://user-images.githubusercontent.com/18696386/76155738-3657d500-60be-11ea-8059-425d6482e3d7.jpeg)

**Comment by walidmujahid** [comment]
Wow. Amazing effort in reproducing this. It feels like a post_save signal is causing this somewhere. Perhaps the post_save activity signal that is invoked when referesh_activity happens?

I do not know. I am about to start working with notifications more on another issue, so I will keep an eye out for anything relevant to this.

**Comment by dadahaha2020** [comment]
The same case with email notifications. Everytime I tap Like on a post or a comment, I'd get a repeat email notifications that someone replied even though I have already seen it.
