### ISSUE TITLE
Event / Calendar Tab

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6176]
### User Story
Current UI does not have an event or calendar space. Users only gets to see any events on the main wall / townsquare which most likely to be missed once a user scrolls.

### Why Is this Needed
*Summary*:
Having an Event / Calendar tab visible users can have a single reference to what are the ongoing or upcoming events that might be of interest to them. This will also help gather more interests from people to get involved or join any events.
### Description
Add a Calendar or Events Tab / pane just like ACTIONS that is always visible. 
Admins or advertisers can add events advertisement with reminders on when will it happen, when it is about to happen, and when it is happening. Also allow users to add and create their own events.
These events can be related to bounties or hackathons as reminders.
The events are in short descriptions and will be linked to actual page of the subject.

Sample: 
Event : Bounty X
End Date : xx/xx/2020
More Info tab - for the whole description and other relevant information

Events sections will have blinking or highlighted color for an upcoming event happening in an hour or less just like ACTIONs when they are already available.
 
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by developerfred** [comment]
I like it.

**Comment by dadahaha2020** [comment]
That's just a general concept. Once it is created more ideas will come that can be added to that tab

**Comment by owocki** [comment]
@vs77bb this is the idea i was telling u about on the phone today
