### ISSUE TITLE
CLR rule

### ISSUE THREAD

**Issue by oussema** [gitcoinco/web#6179]
### User Story

I want to make a new CLR rule to restrict new recently github account to tip others.
### Why Is this Needed

Because in this way any one could make a new github account and tip himself

**Comment by molecula451** [comment]
Mmm Github is very handy when it comes about spamming... creating new accounts it could be a very waste of time

**Comment by owocki** [comment]
we've released a feature that allows us to ignore these sybil tips...

**Comment by oussema** [comment]
great work !
