### ISSUE TITLE
as a community member, i want a competitive analysis, so i can know who's who in the OSS funding space

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#618]
do a competitive analysis across any leading crypto project in the OSS / knowledge work space

**Comment by owocki** [comment]
https://docs.google.com/document/d/1aCbbCGz7L0KOJoDGcnHu0L66TUzdqtVT__pgztGfc94/edit

**Comment by mkosowsk** [comment]
@owocki requested access 👍
