### ISSUE TITLE
As a Gitcoin sponsor, having a conslidated location for payout of all my hackathon prizes vastly cuts down on the number of clicks it takes to close out my hackathon.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6198]
### User Story

As a Gitcoin sponsor, having a conslidated location for payout of all my hackathon prizes vastly cuts down on the number of clicks it takes to close out my hackathon.

### Why Is this Needed

[DO WE HAVE VALIDATION?]

### Description

<img width="1106" alt="payout" src="https://user-images.githubusercontent.com/7516920/76352283-ff570e80-62cb-11ea-80b6-d34236981738.png">

From the design above:

A: This consolidated payout screen is different from normal payout in that it's a consolidated view that contains all hackathon prizes and subsequent successfully submitted projects for those prizes in one location. 

This page can be accessed by clicking on [NEEDS DISCUSSION]

B: This shows the organization or individual who has opened all subsequent hackathon issues and the address that they are paying out from.

C: This tab structure allows the funder/sponsor to go through each and every one of their hackathon issues without actually migrated to the hackathon issue itself in order to payout. This vastly cuts down on the number of browser tabs necessary to ensure payout.

D: For each prize/issue, every successful submission is shown, with the team members who participated on that submission. This will be pulled from our existing projects structure.

E: For each submission, the team members will be shown, and there will be an option to payout each team member.

[HOW WILL PAY FROM BOUNTY FUNDS AND/OR PAYING FROM WALLET WORK HERE, FROM OUR EXISTING PAYOUT MECHANISMS?]

F: The sponsor/funder will be able to see updated statuses as to the payout of each team member, from each respective project submission, from each prize. 

### Current Behavior

Currently payout only exists if the sponsor migrates to the prize/issue page itself. It does not account for submissions. 

### Expected Behavior

[TBD] 

### Definition of Done

[TBD]

**Comment by octavioamu** [comment]
I don't understand this screen 100% why a separated screen for this and not handle it like ETC?
