### ISSUE TITLE
Tribes Emails - Contributors #1: Hook & Value Email

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#6203]
@iamonuwa @PixelantDesign 

An email to introduce tribes to contributors.

![Contributors #1 - Hook   Value Email](https://user-images.githubusercontent.com/19514207/76431798-ac24af00-63e4-11ea-9af0-d5aa7a61a9a4.jpg)

**Comment by owocki** [comment]
@willsputra 

is there a spec for this?  i wanna review it, but i'd rather have the spec in the back of my mind when i do.

same question for the other 4-5 emails u just posted

**Comment by willsputra** [comment]
updated design based on Adina's feedback
![Contributors #1 - Hook   Value Email](https://user-images.githubusercontent.com/19514207/76630029-e8d1e100-6571-11ea-8627-de221bd7f6a4.jpg)

**Comment by iamonuwa** [comment]
Looks good. Is this the final copy?

**Comment by iamonuwa** [comment]
Please share sketch files as well so I can update assets
