### ISSUE TITLE
as a user i want gitcoin to warn me that it has no ability to recover standard bounty funds, so i dont lose my private key and expect gitcoin to bail me out

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6241]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user i want gitcoin to warn me that it has no ability to recover standard bounty funds, so i dont lose my private key and expect gitcoin to bail me out

### Why Is this Needed
feedback from a user who lost his pk: The way I would solve this is with the following approach: gitcoin knows your publickey/address being used by MetaMask when you log in, and the publickey/address used to fund previous issues. Therefore it should be easy for gitcoin to show a big warning when these 2 don't match. Something like: "did you change your wallet account? make sure to migrate previous issues first so that you can still cancel or pay them". This would involve a new operation to move the funds to a new address without canceling or paying-out the bounty. If I had seen that warning, I'd probably made sure that I went back to the previous private key (probably I had the seed somewhere accessible by then, but not now), to migrate the funded issues appropriately.

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no warning

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
big warning that lets user know they are responsibile for their funds.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by knocte** [comment]
@thelostone-mc closed because...?
