### ISSUE TITLE
Links in Grant or Profile Status Updates are not Clickable

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6249]
**Describe the bug**

Links in status activities posted from a Grant's page or a user's profile that is not their own profile page turn unclickable.

**Update:**

User handles after '@' also does not appear clickable. Nor do the link metadata cards show up in activities posted from Grants or Profiles.

**To Reproduce**

Post a link from someone's profile -not your own- or from a Grant. The resulting posted activity will contain not contain a clickable link but mere text.

**Expected behavior**

The link should be clickable. 

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by walidmujahid** [comment]
The solution is possibly to simply `urlify` the links in activities posted from Grants and Profiles.

**Comment by thelostone-mc** [comment]
This should be fixed now !
