### ISSUE TITLE
Avatar Images Are Not Showing Up Properly

### ISSUE THREAD

**Issue by Sirlupinwatson1** [gitcoinco/web#6252]
### Issue report about Avatar Images and symbols or letters interference.

**Describe the bug**
Custom Avatar modeling is showing a square written inside  _Image Not Found_

**To Reproduce**

Update your Avatar with **Terminator Bot** with accessories : 

- [Background](https://gitcoin.co/avatar/view3d?mode=preview&ids=bg_2&theme=terminator)
- [Beard](https://gitcoin.co/avatar/view3d?mode=preview&ids=beard_6&theme=terminator)
- [Eyes](https://gitcoin.co/avatar/view3d?mode=preview&ids=eyes_1&theme=terminator)
- [Accessories](https://gitcoin.co/avatar/view3d?mode=preview&ids=accessoire_6&theme=terminator)
- [Hair](https://gitcoin.co/avatar/view3d?mode=preview&ids=hair_4&theme=terminator)
- [T-Shirt](https://gitcoin.co/avatar/view3d?mode=preview&ids=t-shirt_1&theme=terminator)

**Expected behavior**

Expected to not see the red and white rectangle but the brain.

**Desktop:**

- OS: Windows 10 1909 --- 18363.720
- Browser: Chrome 
- Browser Version: 83.0.4088.0 (Build officiel) canary (64 bits)

**Additional context**

Symbols or letters appear anormal. ( Sometimes in Notifications area half of the overall letters or typography is showing up as symbols or letters see screenshot )

EDIT : The symbols or letters that appear anormal is probably related to language preferences in the operating system. 

![GITCOINchina1](https://user-images.githubusercontent.com/55941045/76993240-eaf5c000-6922-11ea-839c-14bcce267515.png)

**Comment by Solexplorer** [comment]
Hmm.. looks like the T-shirt has an issue here, thanks for reporting :)

**Comment by Sirlupinwatson1** [comment]
> Hmm.. looks like the T-shirt has an issue here, thanks for reporting :)

The hair also looks like :)

**Comment by thelostone-mc** [comment]
Tried this a while back and it seems to work fine. Closing it out for now but will reopen if it gets reported again
