### ISSUE TITLE
Quest round 4 leadboard not updating or refreshing

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#6253]
**Describe the bug**

Gitcoin quest leadboard for round 4 not updating with new points for last 48 hours or so. during the time I beat more than 7 new quests. but points not changed accordingly. According to my knowledge, it should reflect updates after a certain interval in a day. In my https://gitcoin.co/quests user's points tag, its showing 320 points. if I subtract round 3 points from it, it should show 320 - 9 = 311, (i' didn't participate any other round other than round 3 and 4.) but it's not updating for last 48 hours.

**To Reproduce**

- beat a new quest.
- wait at least 24 hr
- you'll see new changes not reflecting.
or 
in my profile (https://gitcoin.co/ekram-syed), if you review activities of the last 48 hours. you'll see that I've beaten more than 7 new quests. but the leadboard round 4 points stack at 293 for a long time now.
**Expected behavior**

**Screenshots**

https://imgur.com/wzVWajM

**Desktop (please complete the following information):**

- OS: all
- Browser: all
- Browser Version: all

**Smartphone (please complete the following information):**

- Device:  all
- OS: all
- Browser: all
- Version: all

**Additional context**

**Comment by hamzaghz** [comment]
Yeah, I beat a lot of quests these days (at least 10) and I am strangely in the same #Rank with the same points!!

**Comment by owocki** [comment]
b9c0de7a12de19b3ad378795df5c19037d95cd78 fixes this . updating the leaderboard now

**Comment by 7ada** [comment]
Right, yesterday I was here  https://share.getcloudapp.com/Qwu78EWD

and now it's updated  https://share.getcloudapp.com/xQugRmzD

Thank you @owocki

**Comment by ekram-syed** [comment]
Yes, it seems working perfectly. I already test it. plan to check it another round before closing this issue.
