### ISSUE TITLE
Grants Not ready to accept funding

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6267]
Hi. Created a grant and encountered the following issues :

1. First created a fund but contract creation got pending for number of hours because of gas issue. Tried to create a new one but txn also got stuck because previous one had smaller nonce. Then, tried to increase the gas of the first txn and contract created successfully. However, it showed 2 grants had been created. : 
      - https://gitcoin.co/grants/507/support-for-freelance-community-management-and-con  -> this is the first txn and contract had been created 
      - https://gitcoin.co/grants/508/support-for-freelance-community-management-and-c-2 - > this is the second txn and still pending. Unable to cancel txn in metamask as well as in Gitcoin Grant Tab.

2. Although the first txn (https://gitcoin.co/grants/507/support-for-freelance-community-management-and-con) was successful in contract creation but did not showed up in townsquare that grant have been created. Also, I was notified by willing funder that when they try to Fund the grant they receive and error that the Grant is not yet setup to receive funds / contributions.

Looking forward to your response and resolution. Thank you :)

**Comment by owocki** [comment]
https://gitcoin.co/grants/507/support-for-freelance-community-management-and-con has been updated to include the contract address and can now accept funding

**Comment by dadahaha2020** [comment]
Thank you 😄
