### ISSUE TITLE
Update Hours Dropdown in Funder Form

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#627]
### User Story

As a developer, I want to know how long a task will take so that I can determine whether I have bandwidth to work the bounty.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement to Bounty Creation screen 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently 'Project Length' does not provide valuable insight to the developer taking on the work.

### Actual behavior
[comment]: # (Describe what actually happened.)
Right now, the drop down shows Hours, Days, Weeks, Months - which is open and unclear to the developer. 

### Expected behavior
[comment]: # (Describe what you expected to happen.)
Change the drop-down to include the following values. 

- < 4 Hours
-  5 - 8 Hours
- 8 - 20 Hours
- 21 - 40 Hours
- 40+ Hours

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Implement above hours into the drop-down options. 

### Additional Information
[comment]: # (Any other information that would be useful.)
Review with @PixelantDesign @vs77bb

**Comment by e-n-l** [comment]
I love this idea. 

At some point, I think I'd really want an option for more granularity, that would allow for the following:

0) minutes as atomic unit
1) selected as [ number field ] [ unit select ] 
2) maybe break time expected down per 'skill', 'tool' or field of expertise involved

Examples:
  - '4 days' = 4 days x 8 hrs x 60 min
  - '3 weeks' = 3 weeks x 5 days x 8 hrs x 60 min


This level of specificity might be better delegated to an integration with a 3rd party / internal tool for project planning, along with funnels for both repo-owners and contributors. Through a consistent, simple UX, everyone could iteratively improve project estimation accuracy. IMHO, opacity in that regard is a huge point of friction to the action <=> incentive correlation.

A plug-in ala [Toggl](https://toggl.com/) comes to mind on the contributor side.

**Comment by PixelantDesign** [comment]
Cool thanks for the feedback @frankchen07 ! Closing this issue then!
