### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wizzfile** [gitcoinco/web#6274]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Solexplorer** [comment]
@wizzfile What bug did you encounter?
