### ISSUE TITLE
Need to pay out on a closed bounty with funds still in it

### ISSUE THREAD

**Issue by EtherDotBlue** [gitcoinco/web#6279]
https://gitcoin.co/issue/EtherDotBlue/MythX/2/4122

I was trying to allow more than one person to get paid for this bounty using the Advanced pay out, but after I paid out the first one it closed the bounty and I can't pay the second person.  There should still be 2 ETH int here as well.

Thanks!

**Comment by owocki** [comment]
https://etherscan.io/tx/0x09443e5ed0613c5b3bd468633a7dd005620311f99958c4cea7da09b392296ee4#statechange

looks like the 3 ETH was returned to your address when you used advanced payout. (i think you  had the 'pay using bounty funds' checked ) 

you can use gitcoin.co/tip to tip the remaining users you want to pay

**Comment by EtherDotBlue** [comment]
Got the answer from @owocki - thanks!
