### ISSUE TITLE
Cannot cancel Gitcoin grant

### ISSUE THREAD

**Issue by Kisgus** [gitcoinco/web#6280]
I'm trying to kill the contract for this grant https://gitcoin.co/grants/521/end-to-end-blockchain-ubi-with-10000-kenians-in-ne

When I click the cancel grant nothing happens on Mac / Chromebrowser with Metamask installed

![Screen Shot 2020-03-23 at 11 25 56 AM](https://user-images.githubusercontent.com/18598519/77307675-f9b0ee00-6cf9-11ea-9e79-ea27f4d6b0c8.png)

**Comment by owocki** [comment]
hmm i cant rperoduce on my grants.

do u have a web3 compatible wallet?  are you on the  mainnet in it?    can you show  me a screenshot of your chrome console after u hit the button?
