### ISSUE TITLE
Gitcoin Grants Feature Request: Bundling Grants for Even Distribution of Funds

### ISSUE THREAD

**Issue by Jeff-Emmett** [gitcoinco/web#6282]
Hey team, feature request from Michael Zargham, if you're looking for further grants functionality: 

Wouldn't it would be cool to make gitcoin 'bundles'? Essentially indexes of grants so i could just put say 1000 DAI in a bundle and have it automatically get allocated evenly across say a half dozen grants. I think this would be killer.

**Comment by owocki** [comment]
i like the idea, but i think it really matters who curates a bundle

**Comment by Jeff-Emmett** [comment]
For sure...could be an additional layer to grant curation, with groups (like a curator of the TokenEngineering community, eg) creating bundles to expediate grants to the whole ecosystem, then promoting that bundle rather than a dozen individual grants.
