### ISSUE TITLE
bug: Grant page rolls back after a few minutes of updating it

### ISSUE THREAD

**Issue by fzeoli** [gitcoinco/web#6283]
I updated this page https://gitcoin.co/grants/99/buidler-2

changing url, description and title. Everything looks good, and then after a few minutes the page is back to its previous version. Tried again, and the exact same thing happened.

Chrome on Mac

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
thanks ! well look into it

**Comment by owocki** [comment]
i observed this on prod too.  it rolls back after a minute or two. i wonder if some background job is causing it to refresh...

**Comment by owocki** [comment]
i think maybe the estimate_clr script is running in the background + causing the grant to revert to its old info

**Comment by owocki** [comment]
@fzeoli try now

**Comment by fzeoli** [comment]
seems to be working now, thanks.
