### ISSUE TITLE
Grant info page seems to revert to forget contributions

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#6284]
**Describe the bug**
It seems that somehow the contributions that were made to the Rotki grant, along with the CLR estimations disappeared.

**To Reproduce**

Check the grant page: https://gitcoin.co/grants/149/rotki

**Expected behavior**

See the contributions that the grant has had so far in this round.

**Comment by owocki** [comment]
were looking into the CLR calcs.  do you have a tx ID of the contributions that disappeared?

**Comment by LefterisJP** [comment]
Hmm noo ... I am sorry. Should have taken a screenshot. It went from:

Estimated: 6 DAI Funded: 4140 or something..
to
Estimated: 0 DAI Funded: 4114 .. or something

So it had somehow lost the count of quite a few contributions, also contributions in between the 2 grant rounds.

Now it has a different number. So maybe now it's fine? I can't say for sure since I can't see how much is from this round and how much from the previous one:

![2020-03-23-222325_429x283_scrot](https://user-images.githubusercontent.com/1658405/77364606-eed77700-6d54-11ea-93bf-6155c2f3ee36.png)
