### ISSUE TITLE
Only approve Dai once for grants

### ISSUE THREAD

**Issue by scottrepreneur** [gitcoinco/web#6296]
### User Story

As a user, I want to only approve Dai one time for all grants.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Approving Dai on every grant is a cumbersome user experience. After Dai has been approved, proceed directly with the grant transaction unless the Dai allowance has been met.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently it requires a new approval for every grant even if you've previously given to a grant.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Ask for Dai allowance on the first grant donation. Check for Dai allowance on follow-up grant donations. Ask for additional allowance if initial allowance is met.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Give to 2 grants without having to approve Dai on the second one.

### Data Requirements

Should significantly reduce the number of approval transactions during the grant process.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
this is what i view as the tradeoff here https://twitter.com/owocki/status/1242496137950425088

**Comment by scottrepreneur** [comment]
I do appreciate the security first mindset with allowances, @owocki . If I know I'm going to submit to more than one grant in a _session_ then I'd like to give allowance for the specific amount at one time instead of paying unnecessary gas and waiting unnecessary transaction times.

Maybe this isn't the flow for general users then, and only something that can be adjusted in user settings for more advanced operation, "Dai Allowance," so it can be manually adjust higher for the next XX transactions I'm planning to do in this _session_.

It seems reasonable at least that Gitcoin would respect a manual allowance allocation as mentioned in the quoted tweet, even if it's not giving the option to adjust the allowance directly. cc: @marczeller
