### ISSUE TITLE
Mini CLR not reflecting correct total tips received

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6299]
**Describe the bug**
Noticed that the total amount of tips I received since #4 MINI CLR started has been reduced. Per notifications received, I received a total of $14.24 in tips from 5 contributors. But current dashboard info only shows $8.82 from 5 contributors.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 8
- Browser: Brave
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
thanks. i wonder if some of the txns didnt clear and thats why they are not included

**Comment by dadahaha2020** [comment]
I just noticed when for few days I got around $8 in tips. Then new tips came which reduced the number instead of adding to the existing amount.
