### ISSUE TITLE
User profile page getting a JS Error, $(...).autogrow is not a function

### ISSUE THREAD

**Issue by ekram-syed** [gitcoinco/web#6314]
**Describe the bug**

When you load anyone's profile page including your own, you'll see a JS error in the console.  Probably for that you not able to post anything on a users wall. The post button not working.

raven.js:449 Uncaught TypeError: $(...).autogrow is not a function
    at HTMLDocument.<anonymous> (status.bdadcc8e8abc.js:246)
    at l (jquery.a09e13ee94d5.js:2)
    at c (jquery.a09e13ee94d5.js:2)
    at d (raven.js:445)

**To Reproduce**

1. Browse anyone's profile page
2. View the error console

**Expected behavior**

1. There should no JS error in the console
2. User is able to post in the user's wall using the input box.

**Screenshots**

https://drive.google.com/file/d/1mINK7JDel6IuEobfWOosO6npQJzM3S3W/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Google Chrome
- Browser Version: 80.0.3987.149 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: Not Tested 
- OS: Not Tested
- Browser: Not Tested
- Version: Not Tested

**Additional context**

**Comment by owocki** [comment]
we need to proabably put 
    {% include 'shared/activity_scripts.html' %}

on the profile page.

**Comment by ekram-syed** [comment]
This issue is fixed, no JS error and can post on user's wall as well.
