### ISSUE TITLE
White screen when accessing gitcoin chat.

### ISSUE THREAD

**Issue by ResourceHog** [gitcoinco/web#6323]
**Describe the bug**

Attempting to open gitcoin chat will bring me to the following webpage shows a white screen instead of a chat app

**To Reproduce**

1. Use chrome or brave browser
2. open web chat

**Expected behavior**

Should show some chat app.

**Screenshots**

![image](https://user-images.githubusercontent.com/3767092/77809698-1593f700-704e-11ea-8743-17120d998118.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Brave
- Browser Version: Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by developerfred** [comment]
tries to disable the Brave shield.
<img width="401" alt="Screen Shot 2020-03-29 at 21 24 18" src="https://user-images.githubusercontent.com/57037080/77865312-035bb980-7204-11ea-80dc-497d894ae1e8.png">

**Comment by developerfred** [comment]
Possible solution change the Chat to ipfs-chat
https://ipfs-chat.herokuapp.com/
- https://github.com/orbitdb/orbit
