### ISSUE TITLE
Additional email settings for Grants confirmation and Gitcoin support

### ISSUE THREAD

**Issue by scottrepreneur** [gitcoinco/web#6325]
### User Story

As a user, I would like to be able to turn off "Grant submission confirmation" emails and "Thank you for Supporting Gitcoin" emails.

### Why Is this Needed

*Summary*: It's blowing up my inbox and I'd like to opt out of all emails.

### Description

*Type*: Feature

### Current Behavior

Currently the emails are sent and there is no way to disable them.

### Expected Behavior

Allow the user to disable these types of emails as well.

### Definition of Done

Emails are not sent when this setting is off and after submitting a grant and providing a service payment to Gitcoin.

**Comment by owocki** [comment]
did you try clicking 'dont send me grant emails' in https://gitcoin.co/settings/email/  ?

**Comment by scottrepreneur** [comment]
I was reading these settings as opting into emails. I guess they're the inverse as I had unchecked all attempting to disable all emails. Can't read evidently.
