### ISSUE TITLE
How Does This Work?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#633]
*not ready to be worked on*
As a new user, I want to know what's the fastest way to get started in Gitcoin.

**Comment by e-n-l** [comment]
Ideally, I think we'd want to game-ify the experience, ala CryptoZombies.io... but for an MVP, having a "get started with GitCoin" repo / module including things like tutorials, contribution guidelines, toolchains (linters etc.) and pre-contribution agreements might be a good place to start.

Repo-owners could then fork that project to customize their own contribution kits, lowering friction for their own specific needs.

Multiple branches / modules could be made available to accommodate specific contributor capacities and preferences (e.g., Win10, iOS, *nix) which ideally would integrate with a GitCoin profile creation funnel.

**Comment by mkosowsk** [comment]
Makes a lot of sense to me! One note, I learn best from specific examples so think it could be nice to include specific examples of real contributions made to Gitcoin linked in the tutorial... always good to learn from the real thing 👍

**Comment by e-n-l** [comment]
@mkosowsk definitely! That might be a signal to listen for in the entrance / exit funnel for bounties, so we can continue to identify good examples.

**Comment by owocki** [comment]
> One note, I learn best from specific examples so think it could be nice to include specific examples of real contributions made to Gitcoin linked in the tutorial... always good to learn from the real thing 👍

this is a good insight.. i wonder if we should have a list of recently completed bounties on the landing page or in gitcoin.co/onboard

**Comment by owocki** [comment]
might be worth adding a visual like this to the tool so people know the bounty flow

<img width="613" alt="screen shot 2018-03-18 at 7 05 13 pm" src="https://user-images.githubusercontent.com/513929/37617426-bf30cf8a-2b78-11e8-857e-057e6375735b.png">

**Comment by owocki** [comment]
one other thought: we could have a short 3 minute video that talks about how to get started ...

**Comment by mkosowsk** [comment]
Might also be interesting to have the flow always up on the web app and show changes to where you are as you progress through it 🤔 could be too cluttery tho
