### ISSUE TITLE
[ADD] Gitcoin Community Circles (GCC)

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6335]
### User Story

Currently we only have Tribes for Organizations while individual interactions are all done thru the TownSquare making the section more crowded than it should be.

### Why Is this Needed
It will be more organized and nice if users can have a Group (Circle) where they can share their common interests. Unlike tribes that is focus on org's functionalities and goals, Gitcoin Community Circle will be useful in building connections of people who shares common hobbies, discussion of certain topics, etc that will give opportunity for everyone to connect. 

### Description
1.  Add Gitcoin Community Circles (GCC) to Community Tab.
2.  Anyone start / create a Circle with the following functions / Features: 
      - **Description.** What the Circle is all about
      - **Add Members.** Add participants
      - **Centerspace.** Mini version of TownSquare dedicated to discussions where members can post, like, comment, and deploy polls.
3.  This will be a PUBLIC space so anyone can still see what's happening within the circle
      

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
We did try Circle integration but ended up removing it as we did not see good support / traction from it
