### ISSUE TITLE
Easy Asset Swap Function or Link for Grant Contribution

### ISSUE THREAD

**Issue by dadahaha2020** [gitcoinco/web#6337]
### User Story
Contributors to Grants has to be ready with the assets needed / are accepted. 
### Why Is this Needed
It is time saving to have a function or link to easy swap of assets within the Contribute to Grant's Page.

### Description

-  **Option 1**
    - Add a swap button that links to list of easy swap platforms 

-  **Options 2**
    - Create Gitcoin's own asset swapping mechanism 

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
User has to make sure the assets for contributions are ready in their wallets before heading to Grant Contribution page.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

- For Option 1 : 
     - Hover on the swap button and links to easy swap platform will be shown
     - Once a platform is selected it opens new page and usual swapping procedure
     - User will manually transfer the swapped asset to their wallets or it will be automatically sent to their wallet or the grant wallet itself

- For Option 2 : 
     - Click on Swap button small UI pops up
     - Choose asset needed, amount, and auto fill the address of the grant 
     - Press / Click Enter then auto swap and sending to the grant wallet
    _* Pricing can be taken from list of swap platform with highest value of assets_
    _* Fees can be collected and be added to Developer's Fund_

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
Swapping is not something we are intending to support on Gitcoin out of the box as this is better done by uniswap/metamask etc.
Grant owners can however accept contributions in all ERC20 tokens.

Closing this out for now
