### ISSUE TITLE
MetaMask Android Login

### ISSUE THREAD

**Issue by ThomasFoolery** [gitcoinco/web#6342]
**Describe the bug:**

Unable to log in with GitCoin from MetaMask app on Android.  Receive Error 500 "even the bots aren't sure what happened".  Also seeing drop down error message:  Session value state missing.

**To Reproduce:**

Open MetaMask app for Android
Navigate to Gitcoin (enter address or under Explore -> Earn Crypto)
From menu, select Log in

**Comment by owocki** [comment]
we are waiting on the upstream fix here https://github.com/MetaMask/metamask-mobile/issues/1273
