### ISSUE TITLE
I'd like to know how to connect my wallet to the mainnet

### ISSUE THREAD

**Issue by 7ada** [gitcoinco/web#6344]
Hello Gitcoiner!

My metamask is connected to the mainnet https://share.getcloudapp.com/z8uXjw9O but strangely when I tried to fund a grant or submit a work the bar shows an error (meatmask is locked) https://share.getcloudapp.com/YEuA2vYB

 I want to find a way to connect my wallet 

 the mainnet is selected and metamask is opened but I still cannot tip, fund or submit 

 I tried to connect my metamask using this feature but i failed  https://share.getcloudapp.com/YEuA2dzr

Browser : Brave 
Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by owocki** [comment]
can you unlock metamask?  if you go into settings > connected do you see gitcoin.co in that list? https://bits.owocki.com/2NuBOyXJ

**Comment by molecula451** [comment]
he fixed the issue already and contributed, guess it's safe to close

**Comment by williamchong007** [comment]
I am also encountering random bugs that shows such warning when user's metamask is already unlocked, or limited the token of choice only to ETH but not DAI.
in many cases a few refresh would fix it, but it is very confusing when we are trying to promote new comers to help fund our grant.

**Comment by owocki** [comment]
can you guys help me get reproduction steps here? if i can figure out how to reproduce the issue i can definitely solve it

**Comment by molecula451** [comment]
The issue is with Brave and using MetaMask at the same time. When in Gitcoin or problably another Web3 app 'Brave' expects you to 'Unlock' their native wallet. People still not realize that having MetaMask and Brave it's conflictive. You gotta let know this somehow until Brave development put some update in fixing this back end stuff

**Comment by molecula451** [comment]
Short: MetaMask + Brave = conflictive. Brave wants you to use their native wallet.

**Comment by owocki** [comment]
ah nice, heres the outstanding issue for this https://github.com/gitcoinco/web/issues/6292
