### ISSUE TITLE
When I try to donate my voucher to a grant, MetaMask asks me to transfer my real money

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6356]
**Describe the bug**
When I try to donate my $5 voucher to a grant, MetaMask asks me to transfer my real money instead of donating my voucher.

**To Reproduce**
Select a grant and try to donate it the voucher. Press Reject button in MetaMask to be sure you don't transfer your real ETH money.

**Comment by owocki** [comment]
i cant reproduce this. can you tell me what browser youre using, what grant youre funding, etc?

**Comment by vporton** [comment]
Browser: Firefox for Linux.
Grant: https://gitcoin.co/grants/31/grantops

I switch to "$5 Voucher Funding" tab and try to donate. Hm, maybe I didn't switch to this tab dues to confusing tab colors?
