### ISSUE TITLE
GitCoin Profile Data Loss

### ISSUE THREAD

**Issue by e-n-l** [gitcoinco/web#636]
##### Description

My GitCoin profile ([e-n-l](https://gitcoin.co/profile/e-n-l) and / or [razordaze](https://gitcoin.co/profile/razordaze)) has lost all record of GitCoin related transactions, apparently at some point after 

a) changing my username on GitHub from @razordaze to @e-n-l, and / or 
b) a [Colony issue](https://gitcoin.co/issue/JoinColony/colonyNetwork/174) was started, [completed / accepted](https://etherscan.io/tx/0xca8b67d7d230c222a40bcc1034912b7aada78a76d7573f55c160effa721aedbe) and then was marked **Cancelled**.

**Comment by e-n-l** [comment]
Hrm, the razordaze profile seems to be showing all the right info again, and the Colony issue has been changed to "Done" from cancelled. 

Mysterious!

**Comment by owocki** [comment]
this is def something we need to handle in the future:

> a) changing my username on GitHub from @razordaze to @e-n-l, and / or

**Comment by mkosowsk** [comment]
Hat tip to @e-n-l for taking Gitcoin through its paces!!! 👍
