### ISSUE TITLE
Hackathon Explorer Tabbed View: Prizes Tab

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6361]
### User Story

Hackathon Explorer Tabbed View: Prizes Tab

### Why Is this Needed

The Hackathon Explorer tab view centralizes the hackathon experience so that hackers aren't flying across the entirety of gitcoin.co when they need assets from different locations. The tabs will be organized so all primary and secondary hack materials are just a click away.

### Current Behavior

No tabs on the Gitcoin Hackathon explorer

### Expected Behavior

![prize_tab](https://user-images.githubusercontent.com/7516920/78309789-d3acfa00-7500-11ea-99fa-296c7c2d6620.png)

### Definition of Done
- [ ] migrate similar explorer functionality in a prizes tab for hackathons

**Comment by zoek1** [comment]
Merged  https://github.com/gitcoinco/web/pull/6347

**Comment by PixelantDesign** [comment]
Awesome!!!!
