### ISSUE TITLE
Hackathon Project Flow: Project creation upon start work

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6362]
### User Story

Hackathon Project Flow: Project creation upon start work

### Why Is this Needed

As it currently stands, it's not consistent to have some work instances to have a project card, and others to not, based on whether or not the contributor decides to open a project. This makes tracking submission difficult, and when an instance of started work doesn't have a project card, those interested in joining the project as a team member or looking to view other contributions will find it difficult to effectively search for every instance of a created project.

### Description

When a hacker starts work on a hackathon issue, instead of optional modals, we combine the two modals and ensure that a project card is created with the minimum amount of information. 

### Current Behavior

Two modals, start work which is mandatory, and project creation which is optional.

### Expected Behavior

![start projectnext](https://user-images.githubusercontent.com/7516920/78310971-60a58280-7504-11ea-9211-909bc950d25a.png)

![create project](https://user-images.githubusercontent.com/7516920/78310974-63a07300-7504-11ea-9249-87086bcf5cda.png)

### Definition of Done
- [ ] TBD, slightly more discussion necessary

**Comment by zoek1** [comment]
Partial Implemented: https://github.com/gitcoinco/web/pull/6348

**Comment by PixelantDesign** [comment]
awesome! Thanks @zoek1
