### ISSUE TITLE
Hackathon Explorer Tabbed View: Projects Tab

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6363]
### User Story

Hackathon Explorer Tabbed View: Projects Tab

### Why Is this Needed

The Hackathon Explorer tab view centralizes the hackathon experience so that hackers aren't flying across the entirety of gitcoin.co when they need assets from different locations. The tabs will be organized so all primary and secondary hack materials are just a click away.

There are also several new features to note on this project page. Previously, we've heard feedback from hackers that they didn't exactly know where to find team members to join a team, therefore, rendering most hackers to work alone. Combined with the need to be able to search the available project space (projects being an instance of started work from one prize), we've decided to add the functionality for projects to be mandatorily created from a start work instance (https://github.com/gitcoinco/web/issues/6362). When the project is created, an contributor is able to signify if they are looking for team members, and this will be displayed on the project card on the hackathons project tab.

**Currently out of scope but for consideration:**
- delineating between "your projects" and "other's projects"

### Current Behavior

No tabs on the Gitcoin Hackathon explorer

### Expected Behavior

![project_tab](https://user-images.githubusercontent.com/7516920/78309942-4e761500-7501-11ea-9e32-1c40d7966a26.png)

### Definition of Done
- [ ] project cards are clickable and leads to the project
- [ ] accessing "looking for team" leads to a shared chat room on Gitcoin Mattermost
- [ ] project tab built to design specifications

**Comment by zoek1** [comment]
Merged https://github.com/gitcoinco/web/pull/6347
