### ISSUE TITLE
Hackathon Explorer Tabbed View: Participant Tab

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6364]
### User Story

Hackathon Explorer Tabbed View: Participant Tab

### Why Is this Needed

The Hackathon Explorer tab view centralizes the hackathon experience so that hackers aren't flying across the entirety of gitcoin.co when they need assets from different locations. The tabs will be organized so all primary and secondary hack materials are just a click away.

Specifically, the participants tab helps hackers view who the participants of the hackathon are, and surfaces the power of the user directory. Participants can better visually deduce the profiles of other hackers, and take actions to reach out and chat with other participants. 

### Current Behavior

No tabs on the Gitcoin Hackathon explorer

### Expected Behavior

![participant_tab](https://user-images.githubusercontent.com/7516920/78311048-a2362d80-7504-11ea-91c2-6df3b92d1fbe.png)

### Definition of Done
- [ ] TBD discussion on card format or table format

**Comment by zoek1** [comment]
These feature was implemented here: https://github.com/gitcoinco/web/pull/6396

**Comment by PixelantDesign** [comment]
This is done!
