### ISSUE TITLE
CLR distribution not received

### ISSUE THREAD

**Issue by elliottjobmann** [gitcoinco/web#6367]
Received a notice about the mini CLR distribution but didn't get Dai. Gave it some time in case the distro was time-released but nada. ;)
https://gitcoin.co/townsquare?tab=activity:195487

**Comment by owocki** [comment]
looks like the payout tx failed (0x8d02d4dc5a295c1ba344f5980324a0a6447ade0573af9037ea822dc264cefe2b ). let me mark it to retry during next week's payouts.

**Comment by elliottjobmann** [comment]
Thank you!
