### ISSUE TITLE
Expired Status == Open Status?

### ISSUE THREAD

**Issue by e-n-l** [gitcoinco/web#637]
##### Description
I noticed that [this issue](https://gitcoin.co/issue/codesponsor/web/10?gc2) is showing up in the [Issue Explorer](https://gitcoin.co/explorer?q=Dockerize) when the Open status filter is on, but it's actually expired:

![image](https://user-images.githubusercontent.com/487308/37550598-2a499438-294d-11e8-826f-bec4c98c2b5f.png)

**Comment by thelostone-mc** [comment]
Not sure why this is happening -.- 

Duplicate one : https://gitcoin.co/issue/codesponsor/web/10?gc2
Expired one : https://gitcoin.co/issue/codesponsor/web/10

![screenshot_20180317-113709](https://user-images.githubusercontent.com/5358146/37552292-1e6776e0-29d8-11e8-96fc-e2ff1e272ec8.png)

**Comment by thelostone-mc** [comment]
Could it be because the bounty was republished for a higher amount ?

**Comment by e-n-l** [comment]
Interesting... the [duplicate](https://gitcoin.co/issue/codesponsor/web/10?gc2) still shows as expired, at least for me:
![image](https://user-images.githubusercontent.com/487308/37558270-873e2984-29ce-11e8-96d5-5a3d6b83faea.png)

I'm using FireFox 59.0 at the moment.

**Comment by e-n-l** [comment]
Interesting... the [duplicate](https://gitcoin.co/issue/codesponsor/web/10?gc2) still shows as expired, at least for me:
![image](https://user-images.githubusercontent.com/487308/37558270-873e2984-29ce-11e8-96d5-5a3d6b83faea.png)

I'm using FireFox 59.0.1 at the moment.

**Comment by thelostone-mc** [comment]
@mbeacom any idea why this might be happening  ?

**Comment by mbeacom** [comment]
The dockerize bounty is indeed a recreated bounty.  The original was cancelled. @e-n-l Thanks for reporting this.  The bounties are technically two unique bounties.  Something odd occurred when @coderberry created the first bounty, so he had to cancel and recreate it.

**Comment by owocki** [comment]
just went in and set the old bounty as `current_bounty=False` so hopefully thatll stop it from showing up twice in the future...

not sure if we need a fix it twice here or not. if not, ok to close this issue?
