### ISSUE TITLE
components loading transition on towersquare

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6379]
![8F585CFA-8D5D-4499-87A9-6E0743F53DC3](https://user-images.githubusercontent.com/57037080/78465284-93f63600-76eb-11ea-9681-30d777fdfcb4.png)

we need a smooth transition to load the components in bachgroud without showing data in advance with this in the image

**Comment by thelostone-mc** [comment]
The transition has been smoother over. Closing this out
