### ISSUE TITLE
Unable to Submit Work

### ISSUE THREAD

**Issue by mul1sh** [gitcoinco/web#6381]
**Describe the bug**
When I try to submit work, I get the error message `Could not get bounty details.` on clicking the  `Submit Work` Button.

On inspecting the console I saw the following error
```js
raven.js:1491 POST https://ipfs-2.gitcoin.co/api/v0/add 500 (Internal Server Error)
(anonymous) @ raven.js:1491
request @ ipfs.125d77c35ea5.js:56
ipfs.add @ ipfs.125d77c35ea5.js:68
ipfs.addJson @ ipfs.125d77c35ea5.js:88
ethFulfillBounty @ ETH.17d13cb3b929.js:144
submitHandler @ index.f0654b804543.js:37
d @ jquery.validate.min.93c1dd8416ac.js:4
(anonymous) @ jquery.validate.min.93c1dd8416ac.js:4
dispatch @ jquery.a09e13ee94d5.js:2
y.handle @ jquery.a09e13ee94d5.js:2
d @ raven.js:445
raven.js:58 {"Message":"write /data/ipfs/blocks/4U/put-956603507: no space left on device","Code":0,"Type":"error"}
```

**To Reproduce**
Try to submit work for any bounty/issue it will fail with the above error.

**Expected behavior**
I should be able to easily `Submit Work` as usual.

**Screenshots**
<img width="1668" alt="Screenshot 2020-04-06 at 11 14 45 AM" src="https://user-images.githubusercontent.com/2150634/78537249-d9a02500-77f7-11ea-9199-5e82d4ede34b.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome 
- Browser Version:  80.0.3987.149 (Official Build) (64-bit)

**Comment by danlipert** [comment]
@mul1sh thanks for the report - should now be fixed 👍

**Comment by mul1sh** [comment]
@danlipert awesome thanks.
