### ISSUE TITLE
missing token transfers on gitcoin grant

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6389]
https://gitcoin.co/grants/152/ethereum-for-farsi-speaking-population?tab=description

from our chat trasncript:

```
Hey, just talked to you on NonCon, couldn't find your email handy so this is easier. This is the grant I was talking about, if you look at the transactions tab, there are some DAI and SAI contributions that are not in the recipient address and not sure how those can be accessed:

missing txns:
most of them tbh, like: 30 Oct 2019

b-j-ci
47.5000 SAI
(+2.5 SAI optional tip to Gitcoin)
47.5000 SAI

30 Oct 2019

b-j-ci
4.7500 SAI
(+0.25 SAI optional tip to Gitcoin)
4.7500 SAI

21 Jan 2020

neil-lowry
95.0000 DAI
(+5.0 DAI optional tip to Gitcoin)
95.0000 DAI

```

**Comment by owocki** [comment]
@shayanb

it looks to me like the 50 SAI contribution on oct 30 2019 ; the approve went through 0xd1173386984098ce62fc07fd71ee0c36251ce526e962edb69726fed3cedb353f but not the actual transfer https://etherscan.io/tx/0x8d63e72e566d7a6e4250c986bc4dd8f9e4bbfe6eadd6c2872b87be4b93fb680f

i think our backend is assuming that the transfer worked because its got the txid of the approve().

checked out the 4.7 sai one and i saw the same thing.

Ok looks like the 100 DAI one too.

were actually about to deploy a fix for monitroing the transfers (not just the approve) next week, which should clean it up in the  app (both in your earnings, transactions tab, and totals area)

**Comment by shayanb** [comment]
@owocki thanks for checking on it. 

So in order to fix those it seems that the transfer transaction should be sent from gitcoin grant contract (given that the balance still is available), right? 
Would the patch do that or would it just clear those failed contributions from the app?

**Comment by adrianhacker-pdx** [comment]
@owocki I noticed a similar issue on my grant, there's a donation for which no funds actually appeared:  https://gitcoin.co/grants/487/mkrdaiinfo-community-ran-hub-to-promote-learning-a  should I open another issue, or is this one sufficient?

**Comment by owocki** [comment]
no, i think this issue is sufficient. which txs are you worried about adrian?

> So in order to fix those it seems that the transfer transaction should be sent from gitcoin grant contract (given that the balance still is available), right?

so that contract never actually holds any funds, its just used to manage splitting of funds (for the splitter contract) and subscriptions (in the case of recurring contributions).  unfortunately the only way to get those funds transfered is to contact the contributor and ask them to send them... and given that the contributions (at least the ones from the OP) are several months old i think the window has passed.
