### ISSUE TITLE
Participants Experiments

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6443]
### User Story

As a hackathon participant I'd like to know who is registered for the hackathon and know is interested in teaming up or hacking solo.

### Why Is this Needed
We want hackers to have a great experience, building great stuff and finding people to collaborate with!

### Description

Feature

### Current Behavior
Current participants tab has very limited information

### Expected Behavior
Build these two experiments to see if it helps with team formation.

### Definition of Done
See below

**Comment by ceresstation** [comment]
Looks good! One thing to note, some people usually already "have a team" or "need a team". We should potentially split people accordingly and let people who "have a team" provide a blurb about their idea if they'd like.

It'd also be good, to potentially refine categories to some extent like "hackathon expertise: front end, back end, design". Our tags do a good job there already, so maybe it's just a matter of prompting folks to use those e.g. "we noticed you haven't specified whether you're [full stack, front end, back end, design] focused let us know here"

**Comment by PixelantDesign** [comment]
Need to add a question in registration flow to capture: 

[] alone
[] looking for a team :
message:

**Comment by octavioamu** [comment]
Just bringing some of the discussion on the call today
we have team formation at "start work" level related to a project, that is related to bounty
This will add a "team formation" at registration level. So not related to any specific bounty. 
That can bring some problems on the flows and the user understanding where actually need to look for teams. 
We should unify into one way to request a team. 
First of all my question to think on a solution is "what we want to solve?" "What data we have to see the problem?" 
In this way we can find a solution that will not create new side problems.

**Comment by jschiarizzi** [comment]
you dont pick what you want to build (the bounty) and then find people to work on it.
You find people to work with then *as a team* decide what to build based on everyone's strengths.

Hackers need to find each other way before they click start on a bounty.

**Comment by PixelantDesign** [comment]
@octavioamu

We have start work at project level, but what about the people that register that don't start work? How do we encourage those developers to join a team?

**Comment by walidmujahid** [comment]
> you dont pick what you want to build (the bounty) and then find people to work on it.
> You find people to work with then _as a team_ decide what to build based on everyone's strengths.
> 
> Hackers need to find each other way before they click start on a bounty.

I think this is an interesting point. I think it does make sense to have team formation at registration level. 

Maybe the team formation could be even done both pre-registration -as in before/between hackathons- as well as during a specific hackathon. This way, perhaps the same team can participate in multiple hackathons/prizes across more than one hackathon. 

For now, the mockups are straightforward and I think provides a good solution for connecting with other participants within a specific hackathon for team ups. 

I am curious, how does being a team affect working on a prize? That is, what differences are there for a team to show interest/start work on a prize as opposed to a single person doing so?

**Comment by PixelantDesign** [comment]
Here is a proposed update based on hacker feedback today.

<img width="852" alt="Screen Shot 2020-05-28 at 12 25 45 PM" src="https://user-images.githubusercontent.com/238235/83167756-82734e00-a0de-11ea-8d6e-00ba95256d65.png">

**Comment by PixelantDesign** [comment]
Other expriments we could run:
1) time to value, making it easy for someone to jump into a hackathon
2) quality of content on town square and smooth UX across site
