### ISSUE TITLE
Change of Email not possible

### ISSUE THREAD

**Issue by fabtho** [gitcoinco/web#6458]
**Describe the bug**

I want to change the email-adress https://gitcoin.co/settings/email/. This is not working. Error massage indicate that there is the same email in the database somewhere. (See screenshot) But I don't have a second account. 

**Workaround**

I just delete the whole account on gitcoin and reconnect from github. This worked (As I did not have any data on gitcoin yet)

**To Reproduce**

Add new E-Mail on github, then try to change to the same email in settings on gitcoin.

**Expected behavior**
E-Mail  address to be changed

**Screenshots**

![Email Settings   Gitcoin](https://user-images.githubusercontent.com/15102967/79567809-236cf300-80b5-11ea-8d79-476a7445217e.png)

**Desktop (please complete the following information):**

Linux
Google Chrome V. 81

**Additional context**

Chang to just a different email, not the same as in the github accont,  gives 500 Error. But this is a different bug.

**Comment by owocki** [comment]
just made a change so that its clear to users they should change email on github 5265bdb6a70ea22c42ffa9bb12f70864d4897e27
