### ISSUE TITLE
Cannot submit project for a hackathon

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6469]
**Describe the bug**

When I start work for a hackathon bounty, I'd like to fill the project modal but the submit button doesn't appear if I scroll down. The only way to submit the project would be to use TAB and go to the submit button: 
![Screen Recording 2020-04-18 at 06 41 39 65 PM](https://user-images.githubusercontent.com/50027175/79643727-9c974380-81a4-11ea-9593-135467dd1478.gif)

**To Reproduce**

Go to a hackathon bounty and start work then try to fill the project modal

**Expected behavior**

I can scroll down the `submit project` modal to click the submit button.

**Comment by developerfred** [comment]
https://github.com/gitcoinco/web/issues/6430

**Comment by developerfred** [comment]
to send I inspect the element pick up or send button and put on top of my project name.
