### ISSUE TITLE
New Gitcoin Navigation to Support Tribes

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6477]
### User Story

As Gitcoin, we'd like to make it easy for users to discover and find tribes that they would like to follow, learn about. or contribute to.

As Gitcoin Sponsor, I'd like too easily find my org so that I can engage with hackers on the platform.

As a contributor or hacker on of Gitcoin, I want to easily search and find tribes that I'm interested in learning about or join.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
No space for discoverability 

### Expected Behavior
any of the 3 users above can get in and out of the tribes navigation easily.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
**Authenticated**
<img width="1473" alt="Screen Shot 2020-04-21 at 10 10 06 AM" src="https://user-images.githubusercontent.com/238235/79876006-79dd7880-83b8-11ea-8ea0-21fb27e63ac1.png">

**Unauthenticated**
<img width="1473" alt="Screen Shot 2020-04-21 at 10 10 57 AM" src="https://user-images.githubusercontent.com/238235/79876161-b01af800-83b8-11ea-895f-18a0061c2640.png">

![org specific town square (consensyshealth)](https://user-images.githubusercontent.com/238235/79878324-4e0fc200-83bb-11ea-97db-fbf8b83c617a.png)

**Comment by developerfred** [comment]
@PixelantDesign Is this navbar only for tribes or for the entire project? If it is for the entire project we could do an A / B test and see which users are interacting better.

**Comment by scco** [comment]
working on this

**Comment by scco** [comment]
Here is the Information Structure as i see it for now / as it should be - as a helper to understand gitcoins architecture so far.

<img width="1695" alt="information structure" src="https://user-images.githubusercontent.com/569641/80093845-80f5b980-8565-11ea-9ae5-a6b810bbb71b.png">
