### ISSUE TITLE
Github connection

### ISSUE THREAD

**Issue by kylietramle** [gitcoinco/web#6489]
**Logging into chat from Town Square results in Github Connection error**

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="433" alt="Screen Shot 2020-04-22 at 12 55 25" src="https://user-images.githubusercontent.com/11758605/79945936-22630980-8499-11ea-8fdc-97de1c6e13da.png">

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by developerfred** [comment]
This is happening because the github servers are unstable., We need another login model, as the gitcoin user base increases.
