### ISSUE TITLE
Unable to change email address

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#6491]
**Describe the bug**

When I first registered, my GitHub address has email address A as the only associated email. As a result, this was the one associated with Gitcoin as well. I removed email address A from GitHub and updated it to email address B. This change did not carry over to Gitcoin, and when I try to manually update my email address in Gitcoin to email B it says "mds1 attempting to use an email which is already in use on the platform".

I've never had a second GitHub or Gitcoin account, so I'm fairly certain it can't be in use on another Gitcoin account.

**Screenshots**

![image](https://user-images.githubusercontent.com/17163988/79995303-eebdba80-846b-11ea-8409-59c48d29e104.png)

**Comment by mds1** [comment]
Just realized this is a duplicate of #6458

**Comment by owocki** [comment]
just made a change so that its clear to users they should change email on github 5265bdb6a70ea22c42ffa9bb12f70864d4897e27
