### ISSUE TITLE
database "chat" does not exist on `docker-compose up --build`

### ISSUE THREAD

**Issue by aaayushsingh** [gitcoinco/web#6499]
**Describe the bug**

{"level":"error","ts":1587727833.5781984,"caller":"sqlstore/supplier.go:224","msg":"Failed to ping DB","error":"pq: database \"chat\" does not exist","retrying in seconds":10}
**To Reproduce**

Simply following the setup instructions mentioned [here](https://docs.gitcoin.co/mk_setup/) on a ubuntu 18.04 based webserver

**Expected behavior**

Build completion without error

**Screenshots**
![image](https://user-images.githubusercontent.com/19550852/80208467-e7ee9d80-864d-11ea-9d07-78ceedc043f2.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04

**Comment by aamustapha** [comment]
I got this same error when setting up on Ubuntu 20.04, but going through the installation guide again and seeing this section
>  If you have error while running this it is likely to come from docker and docker-compose.

I ran ```docker-compose up --build``` again and it worked.
