### ISSUE TITLE
Emails with [DEBUG] header in prod

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#650]
http://bits.owocki.com/1n0k0M040P0j/Screen%20Shot%202018-03-19%20at%2010.14.33%20AM.png

per https://github.com/gitcoinco/web/blob/master/app/marketing/mails.py#L49-L50 this should not happen unless in dev.  

i wonder if it's related to https://github.com/gitcoinco/web/pull/359 @mbeacom ?  although when i do the following in prod i dont see that DEBUG flag is on

```

In [1]: from django.conf import settings

In [2]: settings.DEBUG
Out[2]: False
```

**Comment by mbeacom** [comment]
@owocki Did these originate from `stage.gitcoin.co`? That'd be the only reason I could think of for these going out like that.  `DEBUG` is `True` on staging. 🤔 

This doesn't solve the mystery, but maybe we should check `settings.ENV` for notification related handling alternations?

**Comment by owocki** [comment]
i wonder if this has to do with how gmail collapses threads (esp considering i tested this on my own inbox).. when i click 'show original' , it shows the subject as 'New Faucet Request' without the DEBUG
