### ISSUE TITLE
Where are our users located geographically?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#651]
per @vs77bb convo today

**Comment by mkosowsk** [comment]
@vs77bb As everyone knows and despite outrageous claims to the contrary, I am a proud resident of NYC 👍

**Comment by mbeacom** [comment]
https://docs.djangoproject.com/en/1.11/ref/contrib/gis/geoip2/

**Comment by e-n-l** [comment]
Tag this on to profile, as a form field?

**Comment by mbeacom** [comment]
User location data is now accessible via `app.utils.get_location_from_ip`.  We haven't added a location field anywhere other than `UserAction.location_data` at the moment.

Via #657 we can retrieve location data from the user's IP in any request: `loc = get_location_from_ip(get_real_ip(request))` and user language code via: `request.LANGUAGE_CODE`.
