### ISSUE TITLE
Fix it Twice for Grant Cancellation

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#6518]
**Describe the bug**

As discussed with @danlipert we are running into 500 errors when trying to close subscriptions to grants as with cryptomental's grant here: https://gyazo.com/7d862ae8b3ec839375856b2f816c4558

It's possible to get to the confirmation screen, at which point, after signing both transactions and moving to the transaction processing page, the second transaction fails.

In short as Dan mentioned it looks like the contract interaction registered an invalid signature for cancellation.

**To Reproduce**

Create a subscription on say, cryptomental's grant (fuzz testing) and try cancelling, you should run into the same problems as above.

**Expected behavior**

Grant cancellation shouldn't run into any errors.

**Comment by owocki** [comment]
would be great to know what the stack trace of the cancellation 500 is. thatd make it pretty easy to fix

**Comment by owocki** [comment]
still not able to reproduce this..
