### ISSUE TITLE
confusing first user experience for bounties 

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#652]
in the FTUX its hard to understand all the steps associated with getting paid.  it might be worth letting the user know the flow of the issues when they are onboarding

<img width="613" alt="screen shot 2018-03-18 at 7 05 13 pm" src="https://user-images.githubusercontent.com/513929/37617458-cdce4eb4-2b78-11e8-888e-6c5e353cbb63.png">

**Comment by PixelantDesign** [comment]
Maybe this is something that could live on the developer landing page as well.
