### ISSUE TITLE
Nav Update for Tribes Release

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6528]
### User Story

As a Gitcoin operator we need a way for sponsors/developers to know how to get to Tribes

### Description

- Clean up navigation
- Update navigation to include tribes

### Current Behavior
Not clear how to get to Tribes

### Expected Behavior
User can access tribes offerings

### Definition of Done

- [ ] Rename community menu, and move to the left as second menu item
- [ ] Update the nav items - Implement the design attached
- [ ] Users can get to a tribe from Townsquare and Tribes dropdown menu
- [ ] Remove Home Button
- [ ] Clicking Gitcoin logo in the upper left takes user to Home/Gitcoin.co landing page
- [ ] Only display Company menu item in unauth view
- [ ] Interested in Tribe opens contact page

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
<img width="1466" alt="Screen Shot 2020-04-29 at 11 27 17 AM" src="https://user-images.githubusercontent.com/238235/80617741-79745b80-8a10-11ea-9d48-1c774d8c13d7.png">

**Comment by owocki** [comment]
it would be great if strong caching was considered so that this info does not add a database call on every pageload.
