### ISSUE TITLE
As a Grants Round 6 user, I want to have an add to cart/checkout experience so i can more easily contribute to grants

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6529]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Grants Round 6 user, I want to have an add to cart/checkout experience so i can more easily contribute to grants

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
its too slow/cumbersome to contribute to many grants rn

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
single checkout

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
multi grant checkout per these designs 
https://www.figma.com/file/6OqyMtEfRU4vDMlZXO6Y3l/Gitcoin-Grants-Experience-2020?node-id=0%3A1
- one tx issues the ERC20 token transfers to all grants
- all grants are still stored as a subscription/contribution object in the DB
- emails are sent to the grantees as the tx clears (ideally in celery, as there might be a lot to issue on pageload)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
see above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
none

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@willsputra i could use some design thot on the email / on-site UX for this if u can spare it in next 7 days

**Comment by nodar** [comment]
@owocki linking feature we worked on after round 5: https://github.com/gitcoinco/web/issues/5967 let me know if anything else is required on smart contracts we've shared with you.

**Comment by owocki** [comment]
thanks @nodar ; i think @apbendi is going to be working on this.  Ben did you see the smart contracts the DefiZap team provided in telegram?

**Comment by apbendi** [comment]
Hey @owocki, hi @nodar! Indeed I have been diving into this a bit. No, I don't believe I've seen those. Can you point me in the right direction? Thanks!

**Comment by owocki** [comment]
@nodar can u post the latest ones?

**Comment by nodar** [comment]
https://github.com/amateur-dev/gitcoin-defizap @owocki @apbendi

**Comment by PixelantDesign** [comment]
update https://www.figma.com/file/6OqyMtEfRU4vDMlZXO6Y3l/Gitcoin-Grants-Experience-2020?node-id=119%3A981

**Comment by nodar** [comment]
Nice progress! Any other features you wanted to see from smart contract side? As an example i just thought about: we could have Grantors set up preferred holding asset and whenever donation is received that is not in that asset - it is auto-converted into that asset. Contributors would be able to choose any inputs they want to donate, while Grantors would be able to always hold their ONE preferred asset instead of getting a salad of tokens.

**Comment by owocki** [comment]
defer to @apbendi on that ^^
