### ISSUE TITLE
fund a bounty via a smart contract?

### ISSUE THREAD

**Issue by jpritikin** [gitcoinco/web#6536]
### Who

The Maker community needs to [get a smart contract developed](https://github.com/jpritikin/BlackThurs). I created [an issue](https://github.com/jpritikin/BlackThurs/issues/1) to fund the work.

### What 

To minimize trust, we'd like to fund a gitcoin grant using a smart contract as the funder. Specifically, DAI would be transferred to gitcoin using an executive spell like [this one](https://etherscan.io/address/0x3526A5858Aa91C058A7084ae8AB6d323D2BaeBB8#code). Is this possible?

### Why

The goal is to avoid the need to trust an individual to be a custodian for the funds. Suppose DAI is sent to myself. I could disappear instead of funding the gitcoin bounty.

**Comment by owocki** [comment]
is this ticket about gitcoin bounties or gitcoin grants?  those are two different products from our perspective ( http://gitcoin.co/products ) but it seems like you're using them interchangably here.

from reading the context of the ticket im pretty sure you're talking about bounties.

we use standard bounties ( https://github.com/Bounties-Network/StandardBounties/blob/master/docs/documentation_v1.md ) with the gitcoin schema ( https://github.com/Bounties-Network/StandardBounties/blob/master/docs/gitcoinSchemas.md ) 

here is an example of a tool that allows you to fund a bounty programmatically https://github.com/gitcoinco/command_line_standardbounties_funder

**Comment by jpritikin** [comment]
Ah, that looks great! Thanks.
