### ISSUE TITLE
Gitcoin chat not responding Chrome Version 80.0.3987.163 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by cryptonautica** [gitcoinco/web#6538]
**Describe the bug**
Click on 'chat' then 'web chat' then click the CTA button 'gitcoin' produces a blank page (Please see attached). 

**To Reproduce**
Above

**Expected behavior**
Loads gitcoin web chat

**Screenshots**
<img width="788" alt="Screenshot 2020-04-30 at 18 08 42" src="https://user-images.githubusercontent.com/47461733/80739243-05b87880-8b0e-11ea-935f-13d708013501.png">
<img width="988" alt="Screenshot 2020-04-30 at 18 08 57" src="https://user-images.githubusercontent.com/47461733/80739250-081ad280-8b0e-11ea-963a-7d2767f80e4e.png">

**Desktop (please complete the following information):**

- OS: Mac 10.14.5
- Browser: Chrome 
- Browser Version: 80.0.3987.163

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
@cryptonautica does chat.gitcoin.co work?

**Comment by owocki** [comment]
( as opposed to gitcoin.co/chat )

**Comment by cryptonautica** [comment]
Yurp, that works. Thank you good sir.

**Comment by owocki** [comment]
cc @androolloyd  for after he's above water on tribes
