### ISSUE TITLE
DESIGN/VENDOR SELECTION - As a Gitcoin Grants user, I want to contribute in $$$ (not DAI) with a web2 style user experience, so that I can contribute without understanding web3 primatives like Tokens, private keys, tx signing.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6553]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Gitcoin Grants user, I want to contribute in $$$ (not DAI) with a web2 style user experience, so that I can contribute without understanding web3 primatives like Tokens, private keys, tx signing.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
BC 99.9% of the world doesnt know what a DAI is

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Can only contribute in a web3 style UX

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Extend this figma ( https://www.figma.com/file/6OqyMtEfRU4vDMlZXO6Y3l/Gitcoin-Grants-Experience-2020?node-id=0%3A1 ) such that user can checkout with credit cards.
- Update references to DAI on the grants site to USD.
- Figure out a provider that can give us a web2 style checkout experience, but WITHOUT gitcoin having to have custody of the funds to the grantee.
- Integrate said provider such that a checkout can happen with that provider.

**Comment by crazyrabbitLTC** [comment]
We've (@DappHero) been investigating this and come across a few things that end up being rather tricky with this. Providers such as @Wyre take fees, which is to be expected, but can't service all areas (for example- you can't use it if you're in New York City), while traditional players such as Stripe won't allow it as essentially it's a kind of money transfer from $$$ -> Crypto. 

For high-risk payment processors, it's doable- BUT you, (in this case GitCoin) take on the responsibility for chargebacks, which is *horrible* and can potentially financially ruin a company. So far our thinking is that there need to be a few separate pieces for this to work universally, but incremental functionality might be desirable as well. Bank transfers could be potentially attractive but in interfacing with $$$ the risk that in the middle of the night you get cut off and the funds held hostage indefinitely never goes away.

**Comment by owocki** [comment]
npm: mintbase-bridge - the one click integration for credit card payments

**Comment by owocki** [comment]
we might have to do bank transfers... the chargeback risk is a risk i agree.
