### ISSUE TITLE
As a user who does not have a Github account, I want to be able to sign in with Google/Twitter so I can still contribute to Gitcoin Grants

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6554]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user who does not have a Github account, I want to be able to sign in with Google/Twitter so I can still contribute to Gitcoin Grants

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So non devs can participate in Gitcoin Grants

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Only Github accounts can be used as the basis of Gitcoin accounts

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- When user clicks login, they are prompted to create an account by OAuth'ing with Google Twitter OR Github (not just Github)
- User may also create an account with just an email/password/name/photo.
- If user oauth's in with a provider that lists their email as already in the system, then those account sign ins are combined to the same profile.
- Profile model is extended such that if Github data is not present, then Github-dependent features does not fail.
- Username collusions are handled.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
How many accounts are created with these other providers?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
cc @danlipert for initial engineering architecture thoughts. dont know if this will make it into round 6, depends on complexity level

**Comment by calchulus** [comment]
https://3box.io/ is pretty cool and I think pretty easy to use/integrate - it would then allow users to sign in with metamask, and then inside 3box you can link a social media profile like twitter or provide an email to link to your eth address. I think this is a good medium so that users have at least some crypto address + can verify other social medias when relevant

**Comment by owocki** [comment]
3box is great; we actually sync some data to them right now.

**Comment by calchulus** [comment]
I can dig deeper into this later this week and see if we can use the
twitter_proof field inside a 3box profile to do this properly
