### ISSUE TITLE
Funder rank and contributor rank are negative

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6570]
**Describe the bug**

Contributor rank and funder rank are negative and they shouldn't be:
![immagine](https://user-images.githubusercontent.com/50027175/80944877-d2663a00-8dea-11ea-971c-498b87bd674d.png)
![immagine](https://user-images.githubusercontent.com/50027175/80944996-15281200-8deb-11ea-8a8c-f0b608fb1a93.png)

**To Reproduce**

Go to gitcoin.co/solexplorer and you will find a negative rank

**Expected behavior**

Positive rank for funders and contributors

**Comment by owocki** [comment]
there was an errant db entry. deleting it/ rerunning scirp tnow

**Comment by owocki** [comment]
fixed now
