### ISSUE TITLE
"Announcement" header banners appear then quickly disappear

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6575]
**Describe the bug**
Header banners ("Announcements" set in Gitcoin Admin) appear briefly on the Gitcoin homepage, then quickly disappear.

There are no announcements with a conflicting rank (deleted all old ones to prevent this). Deleting and re-creating the announcement did not solve the issue. Never "x'ed" out the banner to dismiss it.

**To Reproduce**
Go to gitcoin.co

**Expected behavior**

**Screenshots**
Just after reload:
<img width="1436" alt="Screen Shot 2020-05-04 at 11 43 18 AM" src="https://user-images.githubusercontent.com/8337893/81001958-55908b80-8dfd-11ea-8b29-e7a112696e72.png">

<1 second later:
<img width="1435" alt="Screen Shot 2020-05-04 at 11 43 39 AM" src="https://user-images.githubusercontent.com/8337893/81001979-60e3b700-8dfd-11ea-9643-51f63a11033a.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: iOS
- Browser: Chrome
- Version:

**Additional context**

**Comment by owocki** [comment]
from slack: 
```
this announcements rank is still 0
https://gitcoin.co/_administrationtownsquare/announcement/14/change/

Owocki  5 minutes ago
if any other announcements have had rank 0, then they could still conflict with that announcement.  im setting this to be rank 99 now to fix that

Owocki  4 minutes ago
if people do not care about the rank feature, we can just make new banners have their own uniqueness
```
