### ISSUE TITLE
Mojibake on Bounty Details Page when submitter name includes non-Latin characters

### ISSUE THREAD

**Issue by msuess** [gitcoinco/web#658]
##### Description
On the bounty details page, under the 'submissions' section, the encoding/display of the submitter name is messed up if the name contains non-Latin characters:

<img width="630" alt="screen shot 2018-03-19 at 15 36 45" src="https://user-images.githubusercontent.com/337886/37623957-1f098ec0-2b8c-11e8-8dcd-b720fcd911dc.png">

It should look like this: Marco Süß

Output of `psql -l`:
```
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
```

##### Possible Implementation
Either fix the encoding, or, if that's not possible, transliterate the characters to ASCII using eg. [ICU](https://pypi.python.org/pypi/PyICU/) or a similar lib, so that "Süß" becomes "Suess".

##### Environment

* **Browser**: Firefox Developer Edition
* **Version**: 60.0b3 (64-bit)
* **Subsystem**: not sure, possibly ui?

**Comment by kuhnchris** [comment]
@danlipert do we still have problems with umlauts and other special characters or is that fixed already? (asking you since I guess it's connected to the database locale)
