### ISSUE TITLE
Hackathon explorer banner re-design

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6581]
### User Story

As a hackathon participant I want more room below the hackathon explorer banner so that I can see more details in each of the tabs, especially chat and Town Square. I also want to be able to see the hackathon title and details without being obstructed by the banner designs.

### Definition of Done
-Shrink banner size to ~50% of current height
-Remove text in front of the banner (hackathon title, time until hackathon start/end) and place it somewhere more visible (right over register button?)

<img width="1365" alt="Screen Shot 2020-05-04 at 11 45 42 PM" src="https://user-images.githubusercontent.com/8337893/81041114-d41f1480-8e61-11ea-9410-6b57e71ad337.png">

**Comment by frankchen07** [comment]
we can design bounty this, or @PixelantDesign or @willsputra

**Comment by willsputra** [comment]
quick design tweak:

![hackathons](https://user-images.githubusercontent.com/19514207/81313860-ff507080-90ba-11ea-9cdf-6a453ad9216c.jpg)

**Comment by alexvotofuture** [comment]
YES. This looks great @willsputra!!!

Love how the register button is easy to see and click, right alongside the relevant information that would tell you it's worth registering.

One suggestion: Maybe we can drop that hackathon icon (in this example, the one with the animal with sunglasses) down just below the banner, so the banner is unobstructed)? Defer to you guys on whether this would look better.

**Comment by willsputra** [comment]
yeah that works too!

![hackathon](https://user-images.githubusercontent.com/19514207/81379247-5138db00-913b-11ea-85e2-09013bc99577.jpg)

**Comment by PixelantDesign** [comment]
Lets try an overlay on the banner to make sure we can read the text.

**Comment by alexvotofuture** [comment]
@PixelantDesign I like Will's solution (putting all that text below) better than bleeding onto the banner.

**Comment by alexvotofuture** [comment]
Fixed this issue with a transparent background.
