### ISSUE TITLE
Hackathon Sponsor Dashboard

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6582]
[@alexvotofuture to spec this and provide a mock]

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
@frankchen07 what has worked so far?

**Comment by frankchen07** [comment]
I think we should draw on some of the research with 2-3 funders who created spreadsheets for themselves to track their contributors. 

the main thing we should suss out is what primary top (three) actions do sponsors want to universally do?

1. opening bounties
2. communicating during bounties
3. submission review
4. payout

which actions are the most frequent and need checking in? 

those are the ones I believe would make the most sense for a sponsor dashboard.

to avoid repeat work, how can we resurface and combine our funder dashboard for this purpose?
