### ISSUE TITLE
Link to team chat channel on hackathon projects

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6583]
### User Story

As a hackathon participant I want to get in touch with an entire project team via Gitcoin chat, rather than DM each team member individually.

### Why Is this Needed
Hackers, sponsors and mentors all need to communicate with teams as a whole. Hackers ask teams if they need help during team formation, and may want an easy way to navigate to their own team's chat channel. Sponsors and mentors want to interact with entire teams working on their assigned projects so they can provide support.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Project page/prize page project modules allow users to DM individual team members, but not the entire team on their project channel.

### Expected Behavior
A button to chat with the project team in Gitcoin Chat on their project channel.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
Please keep the ability to DM team members, as this is also useful.

<img width="383" alt="Project chat" src="https://user-images.githubusercontent.com/8337893/81041749-6d9af600-8e63-11ea-8e21-7cb883eb76de.png">

**Comment by alexvotofuture** [comment]
cc @androolloyd - we'll need to ensure all projects have channels, and that those channel names either don't change or update here so these direct to the right place in GC.

**Comment by frankchen07** [comment]
what have we heard from users about the ability to get reach the entire projects vs DM?

direct messaging still achieves the potential for team formation, so this would be somewhat of an improvement. depending on what else we have in the pipeline, I would put this on a slightly lower priority.

**Comment by PixelantDesign** [comment]
Adding a second menu item to "chat with team" seems like what you're looking for @alexvotofuture?

**Comment by androolloyd** [comment]
we'll have to migrate existing project channels to be public instead of private, and then we can easily add the link to the team group. Lets push this out for now, as we'll have to do some work in the chat db to make this happen and for that we'll want to do proper backup processes.

**Comment by danlipert** [comment]
@androolloyd what do you think about having this ready for May 27th? @PixelantDesign has proposed this as the deploy date

**Comment by PixelantDesign** [comment]
Did we resolve this one @androolloyd ?
