### ISSUE TITLE
Hackathon explorer "About" section

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6584]
### User Story
As a potential hackathon participant I want to know the details of a Gitcoin Hackathon before registering.

As a sponsor I need a place to direct potential hackathon participants so that they can learn about my hackathon.

### Why Is this Needed
We have used landing pages on the hackathons.gitcoin.co landing page and on sponsors' sites to attract new potential hackers to our events. These sites are beautiful and share in-depth details about an event. However, they take considerable time to create for each hackathon, don't pull in relevant real-time data or assets from the event on gitcoin.co, and introduces an extra point of friction for registrants (need to press register on landing, then register again on the real explorer).

### Description
We need an editable portion of the Gitcoin Hackathons explorer that allows us to share an overview of the hackathon, highlight the sponsors that are participating (with their logos), and add other info to persuade people to participate.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:Feature

### Current Behavior
Hackathon info on the guide page (although this was recently removed), and on external static sites.

### Expected Behavior
Editable portion of the hackathon explorer to provide information about the hackathon.

### Data Requirements
Would be great to view impressions on this page and click-through rates for registration.

**Comment by alexvotofuture** [comment]
Thinking that it may be possible to make this "About this hackathon" page the first item in the list of documents on the left hand side of the "Learn" tab. #6445 #6392 @PixelantDesign @willsputra

**Comment by frankchen07** [comment]
currently, it seems like the guide tab leads to the [hackathon]/onboard page, which is more or less a description about the hackathon itself.

example: 
https://gitcoin.co/hackathon/stop-covid/prizes/?tab=hackathon:19 -> https://gitcoin.co/hackathon/stop-covid/onboard (this looks like it serves as the "about" page, has pictures of sponsors, and a description, and then how to participate).

so if we view the hackathon page as an unregistered user they can onboard one of three ways:

1. look at a prize, start work / register -> onboard
2. hit register on the left -> onboard
3. hit "guide" see -> onboard

so to clarify, would the reduced scope here be to simply rename the guide tab, and make potentially smaller changes? this sidesteps the entire conversation about the wordpress pages, and keeps the "about" information contained within the hackathon tabs

**Comment by PixelantDesign** [comment]
Agree with this:

**so to clarify, would the reduced scope here be to simply rename the guide tab, and make potentially smaller changes? this sidesteps the entire conversation about the wordpress pages, and keeps the "about" information contained within the hackathon tabs**
