### ISSUE TITLE
Automatically create gitcoinbot

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6586]
**Describe the bug**

On localhost some operations fail (for example, every quest ends as failed independently on whether answers were correct), because the user `gitcoinbot` is missing.

**To Reproduce**

Install and configure GitCoin on localhost.

Particularly you need the following settings in `.env`:
```
OVERRIDE_NETWORK=rinkeby
KUDOS_NETWORK=rinkeby
```
and merge https://github.com/gitcoinco/web/pull/6585.

Create a quest and answer it correctly. The quest is told to be lost.

**Expected behavior**

`gitcoinbot` user should be automatically created while deploying the Docker container.

**Workaround**
Go to http://localhost:8000/_administrationdashboard/ and create `gitcoinbot` profile manually.

**Comment by owocki** [comment]
this is a good idea. maybe we create a management command that creates gitcoinbot for u?

**Comment by vporton** [comment]
> this is a good idea. maybe we create a management command that creates gitcoinbot for u?

or welcome me to a bounty where I could do it ;-)

**Comment by owocki** [comment]
sure; wanna just do it here? i can tip you? let me know what amount is appropriate

**Comment by vporton** [comment]
I can do after I finish with the bounty I am doing now. I feel that a tip with matching power of $40 would be appropriate. (Keep in mind that I recently left a job and need money.)

Most of the time of this task would go in researching how your Docker settings work, before adding the actual Python code.

**Comment by owocki** [comment]
kewl
