### ISSUE TITLE
Pre-Hackathon Onboarding/Registration Page Fixes

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6590]
### User Story

Pre-Hackathon Onboarding/Registration Page Fixes

### Why Is this Needed

The about/onboarding/registration page is our first impression on hackers, and is the way we get them to start engaging with the hackathon.

### Description

1. The townsquare checklist item should go to the requisite hackathon townsquare tab. 

2. Remove the "+ what you like to build and earn your first Kudos". "Town Square" should also be one word "townsquare". "Introduce yourself on Townsquare" should be the final statement.

3. There’s no way to RSVP for workshops yet. "RSVP to our 3 workshops" should be "Look out for upcoming workshop invites in your email inbox"

4. Sponsors link is dead. Remove this for now?

5. Restore editable section above the guide that was in the original onboarding form.

**Comment by alexvotofuture** [comment]
Screenshot of the page I'm talking about (live right now):
<img width="1309" alt="Pre Hack Registration Confirmation Bugs" src="https://user-images.githubusercontent.com/8337893/81087385-8381d880-8eae-11ea-8462-7cd1c9ef3345.png">

**Comment by frankchen07** [comment]
1-4 I've clarified, and it hopefully is a quick fix. They're essentially portraying correct information.

What was the original intention of number 5?

**Comment by PixelantDesign** [comment]
@walidmujahid is working on adding calendar invites to workshops ^, could we also leverage in this registration flow?

Checkout sponsors - can we link too the hackathon about page?

**Comment by octavioamu** [comment]
working on these fixes also creating the sponsors area with the filled images since we already know the profiles of each hackathon

**Comment by octavioamu** [comment]
Fixed on 90fd1d6861704ecd4fd0b0c75f90d91a679bc631
