### ISSUE TITLE
Org logos are not sync'ing from Github

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6595]
Many hackathon sponsor orgs' logos did not sync from Github, leaving them with gravatars, old logos, etc. on the explorer.

Ex:
-https://github.com/etclabscore
-https://gitcoin.co/issue/etclabscore/containerized-client-metrics-analysis/1/100021649

Shows:
<img width="915" alt="Screen Shot 2020-05-05 at 6 19 47 PM" src="https://user-images.githubusercontent.com/8337893/81130616-4abd2000-8efd-11ea-9433-5f7dbb8b2d9b.png">
Should be:
<img width="416" alt="Screen Shot 2020-05-05 at 6 18 20 PM" src="https://user-images.githubusercontent.com/8337893/81130622-4db81080-8efd-11ea-96d1-65497f198912.png">

**Comment by octavioamu** [comment]
fixed https://gitcoin.co/etclabscore
![image](https://user-images.githubusercontent.com/1358093/81188372-9dddb400-8f8b-11ea-804a-9b99e786d03f.png)
![image](https://user-images.githubusercontent.com/1358093/81188406-a635ef00-8f8b-11ea-907d-9e723be10735.png)
