### ISSUE TITLE
tribes launch: bug list

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#6601]
#### Owocki

- [x] speed up page (right now it's at ~3s while others are btwn 0.5s-1s)
- [x] show default message when there are no suggested bounties
- [x] https://gitcoin.co/gitcoinco/bounties  doesnt work  as you scroll down the page it replaces the currenet bounties, not append the new bounties.  so there will never be more ethan 10 bounties displayed
- [x] if youre on the bounties page and hovering on a bounty, then the infinite scroll/replace happenns the the modal gets pushed to the top left
 - [ ] https://gitcoin.co/gitcoinco does not have a title or card like the regular profile does.  we need to update it to have the same title card that a regular profile does.

#### Alisa

- [x] People tab not loading
- [x] Browse tribes from nav takes me to chat landing page

- [ ] [People View](https://gitcoin.co/gitcoinco/people) > All - can we display results by org members first and then display tribe members? right now it's mixed and unclear what the sort logic is.

**Comment by frankchen07** [comment]
1. keep forgetting what the difference is between tribe members tribe hackers
2. can we make sure we have our whole team on the people page under tribe owners:
<img width="1251" alt="Screen Shot 2020-05-06 at 10 28 14" src="https://user-images.githubusercontent.com/7516920/81208783-70d9d300-8f84-11ea-9778-53636d94f050.png">

also on the left sidebar:
<img width="302" alt="Screen Shot 2020-05-06 at 10 23 09" src="https://user-images.githubusercontent.com/7516920/81208819-7afbd180-8f84-11ea-82db-d4beb32def0b.png">

3. on tribes explore, clicking follow or the +person image yields different, weird results. Also, one is "Following" and the other is "unfollow" which is not consistent.

clicking the add image
<img width="237" alt="Screen Shot 2020-05-06 at 10 20 51" src="https://user-images.githubusercontent.com/7516920/81208894-9cf55400-8f84-11ea-9bdf-ad931b305f39.png">
<img width="241" alt="Screen Shot 2020-05-06 at 10 21 00" src="https://user-images.githubusercontent.com/7516920/81209048-d332d380-8f84-11ea-96f7-816d4c1469c7.png">

clicking the text
<img width="519" alt="Screen Shot 2020-05-06 at 10 21 10" src="https://user-images.githubusercontent.com/7516920/81208950-b0082400-8f84-11ea-8c07-a68b87b24271.png">

4. making sure not everyone has this capability, so people can't spam our users
<img width="224" alt="Screen Shot 2020-05-06 at 10 33 01" src="https://user-images.githubusercontent.com/7516920/81209245-20af4080-8f85-11ea-9367-14b85e234d14.png">

5. why are there non-gitcoin related projects on the project page?
<img width="974" alt="Screen Shot 2020-05-06 at 10 45 47" src="https://user-images.githubusercontent.com/7516920/81210491-cadb9800-8f86-11ea-9216-045f11ec98aa.png">

6. Is this purple pop up on hover over intended?
<img width="279" alt="Screen Shot 2020-05-06 at 10 42 49" src="https://user-images.githubusercontent.com/7516920/81210510-d16a0f80-8f86-11ea-8e76-e6199578a50d.png">
<img width="280" alt="Screen Shot 2020-05-06 at 10 42 57" src="https://user-images.githubusercontent.com/7516920/81210514-d333d300-8f86-11ea-9b36-af171a287dee.png">

**Comment by owocki** [comment]
https://gitcoin.co/gitcoinco does not have a title or card like the regular profile does.  we need to update it to have the same title card that a regular profile does.
