### ISSUE TITLE
Cannot submit a bounty solution

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#6609]
**Describe the bug**

When I try to submit my bounty https://gitcoin.co/issue/fulfill?pk=21601&network=mainnet I get in MetaMask: "ALERT: Transaction Error. Exception thrown in contract code."

And I am asked to pay $16 for gas, that's too much. Apparently, there is an infinite loop in the contract.

**Comment by owocki** [comment]
i've seen this from time to time, when an infura node is out of sync.

the bounty is definitely open though.. can yo utry again
