### ISSUE TITLE
Featured Bounty Carousel doesn't scroll when cllicked on hackathon explorer

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6612]
On Chrome

<img width="282" alt="Screen Shot 2020-05-06 at 5 24 38 PM" src="https://user-images.githubusercontent.com/8337893/81241257-a7ccda80-8fbe-11ea-8fd9-6948d2a65f49.png">

**Comment by x5engine** [comment]
seems it works on
https://gitcoin.co/hackathon/new-york-blockchain-week/prizes/?tab=hackathon:20
