### ISSUE TITLE
Counter View ZERO on New Activity

### ISSUE THREAD

**Issue by molecula451** [gitcoinco/web#6613]
**Describe the bug**
Found the counter view trolling the view data recently

![counter](https://user-images.githubusercontent.com/41552663/81247343-c398a680-8fe7-11ea-80ea-8cc906e87799.png)

**To Reproduce**

Counter view activity got saturated

**Expected behavior**

Normal counting views

**Comment by owocki** [comment]
celery was down. just kicked it + should be updating now

**Comment by molecula451** [comment]
working
