### ISSUE TITLE
TAF - Tribes Advancement Framework

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6616]
# Why

Now that Tribes v0.1 is launched at https://gitcoin.co/gitcoinco we need to come up with away to iterate on it, towards the nirvana state: reaching product market revenue fit with 100 recurring paying customers with low churn.

So how do we decide how to get there? 

> “If we have data, let’s look at data. If all we have are opinions, let’s go with mine.” Jim Barksdale

I propose the following framework for data driving our Tribes work:

# What

We start recording everything that people do on Tribes, so that we can make data driven decisions about how to use it (and perhaps eventually open this data to Tribes customers, so they can see how much value they're getting out of Tribes).

We will expose this data in a new tab entitled "Analytics"

Things to record:

## Generalized Stats
- Tab clicks
- Pageviews

## Per Page Stats
- Bounty Views (similar to townsquare view counts), Bounty Start Works, Submits, etc
- User Views
- Project Views
- likes, comments, ETH sent

## Demographics
What are the skillsets, locations, etc of the above?
What unique users have been reached?

# End State

This ticket will be a success if we can measure increasing traffic to our tribes page, and data drive our decisions about what users want to see.  Future tickets I might write for Tribes include:

1. As a Tribe Member, I want a Tribe Leaderboard, so I can see how I stack up against others in the Tribe and learn who in the Tribe to emulate.
2. As a Tribe Member, I want to see the Grants associated with this Tribe, so I can support others in this Tribe.
3. As a Tribe Member, I want Daily Actions on my Tribe so I can learn over time about the happenings of my Tribe.
4. As a Tribe Member, I want to Subscribe to Email Updates from a Tribe, so I can keep in better touch with my Tribe Memberes.
5. As a Tribe Owner, I want to adminsiter a Mini CLR Round for my Tribe, so I can create a bottoms up cryptoeconomic force to help users stay engaged + self organize + pay it forward.
6. As a Tribe Memer, I want to earn exclusive Tribe Kudos so I can flaunt how Tribey I am.
7. As a Tribe Member, [I want to co-create a Tribes values in a fun gamified way, so I can learn how to connect with other tribe members](https://twitter.com/owocki/status/1258128613733351424)
8. As a Tribe Member, I want exclusive Gitcoin Quests for my Tribe, so I can learn about my Tribe.
9. As a Tribe Member, I want a referral link that will allow me to earn by referring my friends to this Tribe.
10. As a Tribe Member, I want to see the Hackathons this Tribe is participating in, so I can participate too.
11. As a Tribe Member, I want to be appointed to a moderator position so I can help the Tribe owner caretake y tribe.
12. As a Tribe Member, I want Tribe Chat so I can chat with others in this Tribe.
13. A s a Tribe Memer, I want streaks so I can earn points/ETH for being consistent.

As you can see, I've got a handful of ideas I'd want to work through.  We will surely be in a beter place to iterate if we can say with the backing of data which tabs are providing value + contributing to more time on the Tribes page.

We will also be able to show Tribe Owners exactly how people are engaging with their Tribe once we have this tab in place.

**Comment by vs77bb** [comment]
Adding some miscellaneous thoughts for discussion in Staff Meeting today.

Easy emails to all people in your tribe. Ways to access top developers. Find talent for you. Engage with your organization easier. Org (wallet, grantee, hacker, everything) management. Follow page.
