### ISSUE TITLE
Single project page

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#6622]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a contributor I want a single project page with a friendly url so I can link people to my project + have the project "looking for members" flag there.
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Because there is no way to link my project to find new members or people read the full description. 
### Description
The design proposal, still need some additions for:
Links to quick chat with people
"Looking for team area"
Edit button (will open the edit modal used today) 
Post activity need to be posted to the hackathon townsquare. (like kudos, grants etc)
Card metatags need to show the project logo. 
v2:
Looking for team button to request join the team.
![image](https://user-images.githubusercontent.com/1358093/81435848-e12c5400-913e-11ea-956d-5aed936535f8.png)

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
none 
### Expected Behavior
[comment]: # (Describe what you expected to happen.)
url : `https://gitcoin.co/hackathon/[hackathon-slug]/projects/[project-id]/[project-slug]
### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
@octavioamu what is the next step on this ticket?

**Comment by willsputra** [comment]
just an idea - do we want to reuse the grant detail layout? maybe people can convert projects to grants?

![project details](https://user-images.githubusercontent.com/19514207/82576044-de5c4500-9bbb-11ea-891e-ecde6ae64597.jpg)

**Comment by PixelantDesign** [comment]
looking good! how and where does the hacker enter in all of this information?
when will the button - convert to grant appear? who will see and be able to convert it to a grant?

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/6004

**Comment by PixelantDesign** [comment]
- When I come here as a hacker, what are the fields that I see? How do we get to this completed view?
- 
- How do they enter team members/ categories?
- 
- Primary action is to create a project.
- 
- Convert to grant seems like later, but maybe not a primary action.
- 
- What does the townsquare card look like when a project is created?
- 
- Need responsive views

**Comment by willsputra** [comment]
they can enter team members and other fields on the combined Start Work / Create Project form?
https://github.com/gitcoinco/web/pull/6661

**Comment by willsputra** [comment]
Some points discussed:
1. Creating a project still follows the current flow: Go to Issue Details > Start Work > fill in combined start work & project creation form (https://github.com/gitcoinco/web/issues/6444)
2. The only actions you can do here for now are to **edit your project** and **post on the Activity tab**. In future iterations, we could also allow sponsors to assign as winner, owners to convert to grant, etc.
3. Will need to think how to surface the project activity on hackathon townsquare or general townsquare

Summary tab:
![summary](https://user-images.githubusercontent.com/19514207/84413050-aee0ab80-ac42-11ea-9740-aa0321e093b2.jpg)

Activity tab:
![activity](https://user-images.githubusercontent.com/19514207/84413076-b4d68c80-ac42-11ea-9615-8d24660c3851.jpg)

Show edit modal when you click "Edit Project" (same modal as start work/edit modal)
![edit](https://user-images.githubusercontent.com/19514207/84413093-bc963100-ac42-11ea-8939-07e4edc27455.jpg)

**Comment by willsputra** [comment]
also slightly related issue as we're changing the link of the "View Project" button:
https://github.com/gitcoinco/web/issues/6833

**Comment by PixelantDesign** [comment]
Hey @willsputra 
As a hacker participating in this task, how do I see this project page? 
As a sponsor, how do I see this project page?

_Will need to think how to surface the project activity on hackathon townsquare or general townsquare_
We have a townsquare card when a hackathon project has been created.

**Comment by willsputra** [comment]
Both hacker and sponsor can view the project page from the Projects tab in hackathon view. Clicking on the title or "View Project" on each project will bring you to this single project page instead of directly to github. (Example: https://gitcoin.co/hackathon/clarity/projects/?tab=hackathon:20)

![Screenshot 2020-06-22 21 19 38](https://user-images.githubusercontent.com/19514207/85292199-1eba2600-b4ce-11ea-9649-7e11fde7aa9d.png)

They can also go into the Prize Details to see the projects associated with that prize:

![Screenshot 2020-06-22 21 21 09](https://user-images.githubusercontent.com/19514207/85292405-66d94880-b4ce-11ea-854f-2c2a71ab8b60.png)

**Comment by PixelantDesign** [comment]
@developerfred interested in this one? ^

**Comment by developerfred** [comment]
yes @PixelantDesign!

**Comment by willsputra** [comment]
figma file:
https://www.figma.com/file/UEjst33xyuGioTuTpxmney/Gitcoin-Single-Project-Page?node-id=0%3A1

the design is based on the grants detail page (https://gitcoin.co/grants/86/gitcoin-grants-round-7-dev-fund)

**Comment by frankchen07** [comment]
just to organize my brain model - with this single project page, if I end up editing it, the changes are reflected:

1. on the single project page
2. on the projects tab cards
3. on the bounty issue details project section at the bottom

right? Is there anywhere else I'm missing

**Comment by octavioamu** [comment]
Every place where the data is showed

**Comment by PixelantDesign** [comment]
@developerfred are you still working on this one?

**Comment by PixelantDesign** [comment]
@developerfred could we have this by Friday please? otherwise I'll need to bring this in to  complete internally. Thank you!

**Comment by PixelantDesign** [comment]
@developerfred I'll payout for the work you've done. @zoek1 has agreed to finish it up. Thank you!

**Comment by PixelantDesign** [comment]
Is it possible to get comments in  here for filecoin?

**Comment by PixelantDesign** [comment]
Here is the video  @vs77bb @connoroday please review https://www.loom.com/share/8ac34c03beec47e0ae18ae8e7e10aaa6

**Comment by PixelantDesign** [comment]
Just viewed with @vs77bb and @frankchen07 , could we deploy @danlipert

**Comment by zoek1** [comment]
PR for this ticket https://github.com/gitcoinco/web/pull/7169
