### ISSUE TITLE
Installing docker gitcoin web image on Kali Linux 2020 VM fails do to django-autotranslate==1.1.0 package

### ISSUE THREAD

**Issue by federicosan** [gitcoinco/web#6623]
**Describe the bug**

Installing docker gitcoin web image on Kali Linux 2020 VM fails do to django-autotranslate==1.1.0 package**To Reproduce**

Install latest Kali Linux on VirtualBox
Follow Gitcoin docker Install
**Expected behavior**

Installing docker image fails with exit code 1 do to dijango-autotranslate==1.1.0 package. Note not requiring this package fixes the installing issue and the docker images are installed.
**Screenshots**

**Desktop (please complete the following information):**

- OS: Kali Linux (based on Debian)
- Browser: FireFox (not relevant)
- Browser Version: Kali Linux latest Firefox  (not relevant)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

Woudl getting a different package solve the issue, I don't know? Not requiring package does.

**Comment by owocki** [comment]
I think if u us 1.1.1 it should work.

**Comment by owocki** [comment]
* you use

**Comment by federicosan** [comment]
This fixes the issue thanks. deleting the package was no good, build works but the app crashes.
