### ISSUE TITLE
Error installing django-autotranslate==1.1.0

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6629]
**Describe the bug**

Error when installing django-autotranslate 1.1.0

`Collecting django-autotranslate==1.1.0
  Downloading django-autotranslate-1.1.0.tar.gz (8.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nyq05dlb/django-autotranslate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nyq05dlb/django-autotranslate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_hwef0os
         cwd: /tmp/pip-install-nyq05dlb/django-autotranslate/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nyq05dlb/django-autotranslate/setup.py", line 25, in <module>
        requirements = [str(ir.req) for ir in install_requirements]
      File "/tmp/pip-install-nyq05dlb/django-autotranslate/setup.py", line 25, in <listcomp>
        requirements = [str(ir.req) for ir in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip3 install --upgrade -r test.txt' returned a non-zero code: 1`

**To Reproduce**

As of 7021a29e723884141b15a76da60be77e06ba44c5, build docker-compose.

**Notes**

using the next release, django-autotranslate==1.1.1, seems to work fine.

**Comment by owocki** [comment]
if we just need to bump the version number, then lets do that on the master branch

**Comment by walidmujahid** [comment]
requirements bug fixed in version 1.1.1: https://github.com/ankitpopli1891/django-autotranslate/commit/b70215a6a7b17be290fd5f10a437eb3bf77e78ee

PR made @owocki https://github.com/gitcoinco/web/pull/6630
