### ISSUE TITLE
as a user, i want a wall of love, so i can see that others love gitcoin and i can join them

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6639]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a user, i want a wall of love, so i can see that others love gitcoin and i can join them

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
so we can collect all our testimonials in one place

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no wall of love

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
wall of love, where we can display tweets or gitcoin users that have praised gitcoin
just a page that shows alll the testimonials
- each testimonial = a db entry called 'testimonial'
- can either be a tweet link, or (gitcoin_profile, quote) 

users can submit their own testimonials via a link at the bottom of the page, and we can approve them to show on the wall of love

thats it; lets KISS

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
wall of love exemplars
https://www.google.com/search?q=wall+of+love&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiq0eC82a7pAhXNs54KHQsvAFwQ_AUoAXoECA0QAw&biw=1900&bih=877&dpr=2

**Comment by thesachinmittal** [comment]
The expected behavior may also have these features,

When a link is registered in the DB. On the frontend, it should create a thumbnail of the tweet with specific dimensions?
Also, a 'good to have priority feature' which shows the most influential tweets in the first two rows.

**Comment by owocki** [comment]
im thinking maybe well want to just add this to the `/results` page... instead of being its own page.

> When a link is registered in the DB. On the frontend, it should create a thumbnail of the tweet with specific dimensions?

yes i think so

**Comment by thesachinmittal** [comment]
Suggestion:
Came across this. 
https://publish.twitter.com/#

Example:

![Screenshot 2020-05-13 at 4 16 19 PM](https://user-images.githubusercontent.com/22838732/81803979-0c93b200-9536-11ea-8048-414c85860320.png)

We can use this to embed the tweet, by inputting the html code in frontend and maintain the section manually with 20-30 highly influential tweets taking two screens on the page.
