### ISSUE TITLE
Add hackathon history in a Tribe's page

### ISSUE THREAD

**Issue by fluffays** [gitcoinco/web#6642]
### User Story

As a user, I want to see a Tribe Organization's hackathon history so that I can evaluate their mission and contribution.

### Why Is this Needed

*Summary*: 
As a user, I'd like to see information about hackathons in which a funder has been involved, on their tribe's page. 
As a funder, I'd like to see my hackathons added to my organization rank, and promote my activity to contributors visiting my tribe.

### Description

*Type*: Feature

### Current Behavior

At the moment, past hackathons are only viewable in the Hackathons page. Additionally, when viewing the list of bounties for a past hackathon you cannot filter them by funder. 
This makes it harder to see a funder's track record on Gitcoin, their contribution to the community and their overall focus.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
In an organization's tribe page, the number of hackathons in which the funder was involved could be added in the <Organization Rank> section.
![image](https://user-images.githubusercontent.com/39056857/81734352-081abb00-949c-11ea-9ac9-99efcfb4bea9.png)

In an organization's tribe page, a tab displaying past/ closed bounties sponsored by the funder could be added to the navigation.

![image](https://user-images.githubusercontent.com/39056857/81735213-61371e80-949d-11ea-8c2c-513b4cde4194.png)

### Definition of Done

- [ ] Add # of hackathons in <Organization Rank> section
- [ ] [Optional] Add new tab - <Closed Issues> - in page navigation

### Additional Information
Featuring hackathons themselves (or bounties from them) is dependent on whether keeping a complete hackathon archive is doable/ relevant on Gitcoin.

**Comment by PixelantDesign** [comment]
Let's do this on Tribes townsquare since we'll be retiring old orgs. cc @frankchen07

**Comment by willsputra** [comment]
we can put a Hackathons tab to show which hackathons they sponsored

![Hackathons](https://user-images.githubusercontent.com/19514207/85415688-319d2b00-b5a0-11ea-8b2e-7c0a98ab71a8.jpg)

**Comment by frankchen07** [comment]
I feel like the way the sponsor interacts with a hackathon should be by "workspace." 

Sort of like going to each hackathon page allows them to see a bunch of elements related to that hackathon. In a hierarchy sense, I would think that is selected elsewhere, and then the tabs will be for hackathon A, B, C, etc for that sponsor.
