### ISSUE TITLE
Update Twitter Images For Each Hackathon

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6645]
Current State: 
![image](https://user-images.githubusercontent.com/23297747/81747807-be6ba980-9476-11ea-89da-b08b68dd3670.png)

Future State: 
Include the Sponsor branding / the unique hackathon branding in the hyperlinks for all Twitter posts. Like this image :D from --> https://gitcoin.co/hackathon/rl1/

![image](https://user-images.githubusercontent.com/23297747/81747895-e4914980-9476-11ea-8ece-d216642045fe.png)

**Comment by x5engine** [comment]
@vs77bb done and even updated the description too, to show the hackathon description
