### ISSUE TITLE
end_date overlap with hackathon logo

### ISSUE THREAD

**Issue by x5engine** [gitcoinco/web#6651]
This happens on smaller screens like laptops

![image](https://user-images.githubusercontent.com/12363020/81871481-6660a000-9567-11ea-8aab-71c27944b82c.png)

**Comment by androolloyd** [comment]
We'll make some adjustments to the css, is your screenshot just cut off, or is the follow button rendered like so as well @x5engine if you don't mind, what screensize is your machine, so i can emulate it in responsive.

**Comment by x5engine** [comment]
macbook pro 13 inch ;) @androolloyd

**Comment by x5engine** [comment]
i can fix it but the logo should resize depending on the screen size
