### ISSUE TITLE
Submitting a project's new logo does not work

### ISSUE THREAD

**Issue by 3100** [gitcoinco/web#6659]
**Describe the bug**
I'm struggling to submit my project's logo png image on a project edit dialog.
The dialog's logo preview correctly shows the image, but after submitting it, the project logo is broken.

**To Reproduce**
1. Click the edit button on your project in some hackathon page.
2. Select your new logo file on a dialog.
3. Click the submit button.

**Expected behavior**
The hackathon page shows the new logo image.

**Screenshots**
![image](https://user-images.githubusercontent.com/1296276/81947394-747ff080-963b-11ea-85f8-18a2414f83ed.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.4（19E287)
- Browser: Google Chrome
- Browser Version: 81.0.4044.138（Official Build） （64 bit）

**Additional context**

**Comment by x5engine** [comment]
checking this

**Comment by thelostone-mc** [comment]
Is this an issue @3100 ?
