### ISSUE TITLE
Still receiving emails to old address after updating address

### ISSUE THREAD

**Issue by Bobface** [gitcoinco/web#6664]
**Describe the bug**
Updated my email address in the Gitcoin settings a while ago, however still receive most of Gitcoin mails to my old address.

**To Reproduce**
/

**Expected behavior**
Email should be received to the new address.

**Screenshots**
/

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Browser Version: Firefox 76.0.1 (64 Bit)

**Comment by owocki** [comment]
whats the old email? you can email me it (kevin@gitcoin.co) if you dont want to post publicly

**Comment by Bobface** [comment]
@owocki Will send you an email
