### ISSUE TITLE
Avatar does not update

### ISSUE THREAD

**Issue by Ryan-Gordon** [gitcoinco/web#6667]
**Describe the bug**

When I go to update my profile avatar the change is accepted but after an hour the avatar itself has not updated. On the feed it shows the change of avatar and shows this correctly but the avatar doe not update. Have tried to do a hard refresh of the page. 
Possibly related is my profile always shows as offline. When I go to webchat I can set my self to Online and I see the change but the status is not kept after a few page clicks.

**To Reproduce**

I am unsure how to reproduce this.
**Expected behavior**

My profile should update its avatar with the Gitcoin customisable avatar.
**Screenshots**

![image](https://user-images.githubusercontent.com/11082710/82130473-8a202200-97c3-11ea-815b-55e852243455.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Unsure

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
Some more context; on pages such as the page to receive a kudos from a quest and the avatar used in a quest my new avatar shows as expected

**Comment by owocki** [comment]
hmmm for some reason i dont see the 'updated your avatar' entry on https://gitcoin.co/ryan-gordon - did you delete it?

**Comment by owocki** [comment]
also which avatar did u pick

**Comment by Ryan-Gordon** [comment]
Hey @owocki 
Thank you for responding. 
I don't see the updated avatar entry on my profile but when I go to town square and select my threads I can see it there. https://gitcoin.co/townsquare?tab=activity:278990

This was the one I picked but happy to make a new one to test if needed. 
![image](https://user-images.githubusercontent.com/11082710/82242521-e5722180-9935-11ea-894b-34809ef08ab2.png)

**Comment by owocki** [comment]
i see what happened. looks like you deleted your account on 2019-03-02 and the system was still trying to protect your user data by not showing your avatar under any conditions.  

looks like when you re-signed up it wasnt smart enough to override that protection.

**Comment by owocki** [comment]
anyway, try now. its fixed

**Comment by Ryan-Gordon** [comment]
Gave it another go there with another avatar and : 
![image](https://user-images.githubusercontent.com/11082710/82258349-9f2abb80-9951-11ea-87ad-cf9075aea295.png)

Thank you for the help with this @owocki I will close this out as it looks to be resolved.
