### ISSUE TITLE
As a Gitcoin sales lead, I want Grants can now be in multiple grants matching rounds, multiple matching rounds can happen at once, so I can ssell more QF.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6676]
The scope of this ticket is to take the following information 

```
total_clr_pot = 250000
clr_round = 5
clr_active = True
show_clr_card = True
start_date
end_date
round_types = ['media', 'tech', 'health']
round_amounts = [50k, 100k, 100k]
round_scope = [grants_queryset]
```

and store it in the database instead of views.py . ie. Store Match Round Information in the DB, not grants/views.py

We also need frontend changes to run multiple rounds at once, and we need to make it so it's clear in the UI which grants are attributed to which rounds, and which are not.

**Comment by owocki** [comment]
@frankchen07 @thelostone-mc @danlipert any feedback on this ticket?

i want to make this change sooner rather than later as the way sales are going, i have a sense that were going to be running many more grants rounds and the current hardcocded approach is going to stop working soon.

**Comment by owocki** [comment]
guess not?

**Comment by frankchen07** [comment]
sorry did see this ticket, but forget to comment. 

I think from my end it makes sense, it would probably slightly simplify analytical calculations.

**Comment by thelostone-mc** [comment]
lol i totally missed this ! 
Makes sense ! It's not super important right ? 
Also what's `round_scope`?

**Comment by owocki** [comment]
round_scope = standard vitalik style round, or zcash round, or matic round

well have maybe two rounds running at once

````
xxxx   jan feb mar apr may jun july aug sept oct nov dec
eth      x          x               x                 x                                     x
matic                    x                   x              x  
zcash                                                 x                         x
````

**Comment by owocki** [comment]
things that i think we need to fully action this:
1. how does the UI organize multiple rounds?  how do we discover grants that are both matching and not matching? (for ex we hid the health grants during last round)
2. how does the backend know which grant is in which round?
3. for now i recomend a grant not being able to be in multiple match rounds at once.

@vs77bb @PixelantDesign

**Comment by owocki** [comment]
@PixelantDesign @willsputra here is the 'multiple grants round' ticket.  happy to have a call on it this week

**Comment by thelostone-mc** [comment]
^ Do rope me in on this call cause I'd need the entire picture in my head while planning out the architecture 
cc @PixelantDesign / @owocki

**Comment by owocki** [comment]
FROM @PixelantDesign 

```
maybe i need an explanation of how the backend will work?
Shoudl there be separate areas for the customers? How does it impact main explorer?
Will they be run at the same time like our hackathons?
Are they paying for white label?
The funds (pool of money is separate I imageine?)
Maybe worth a call.
```

**Comment by owocki** [comment]
> maybe i need an explanation of how the backend will work?

@thelostone-mc can u bring your architecture doc?

> Shoudl there be separate areas for the customers? How does it impact main explorer?

thats up to the product/design team

> Will they be run at the same time like our hackathons?

yes

> Are they paying for white label?

no white label at this time, although co-branding might be  needed.  @vs77bb can maybe add some context in terms of what happened with the matic deal.

> The funds (pool of money is separate I imageine?)

not sure i understand the question, but there will be pools of funding that can be allocated to different categories or subcategories.  and there can be many going at once, or overlapping.
