### ISSUE TITLE
CORS blocked

### ISSUE THREAD

**Issue by Jack-Works** [gitcoinco/web#6679]
**Describe the bug**:

We send the request from an extension and get blocked by CORS:

> Access to fetch at 'https://gitcoin.co/api/v0.1/grants/634/' from origin '`chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap`' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sebastiantf** [comment]
Can you have a look at https://github.com/gitcoinco/web/issues/6493#issuecomment-631025688 and see if it's helpful?

**Comment by octavioamu** [comment]
notice that error is not from gitcoin is an extension you have installed on your chrome, the name is maskbook https://chrome.google.com/webstore/detail/maskbook/jkoeaghipilijlahjplgbfiocjhldnap and probably is trying to do something on the pages you enter

**Comment by octavioamu** [comment]
closing the issue but feel free to reopen if you think there is some problem on our side

**Comment by Jack-Works** [comment]
Please check out my comment at https://github.com/gitcoinco/web/issues/6493#issuecomment-631218226 and https://github.com/gitcoinco/web/issues/6493#issuecomment-631218558

Gitcoin API doesn't have the correct CORS settings.

**Comment by Tedko** [comment]
@octavioamu @sebastiantf Seems like https://github.com/gitcoinco/web/issues/6493#issuecomment-631218226 & https://github.com/gitcoinco/web/issues/6493#issuecomment-631218558 haven't got response yet.  Can you take a look and try test it out?

**Comment by Jack-Works** [comment]
@owocki hi the cors problem here

**Comment by Tedko** [comment]
is this fixed by gitcoin already?
