### ISSUE TITLE
Submitting Work - Require Link & Change "PR" to "Project"

### ISSUE THREAD

**Issue by connoroday** [gitcoinco/web#6683]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a hackathon participant, I want to ensure I don't forget to include a link to my project with my submission so my work gets considered.

As a hackathon sponsor and moderator, I want to mandate links with submissions so hackers do not forget to include them and so I don't have to manually track them down.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)

*Summary*: Many hackers "submit work" with no link to their project. The field is optional. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature? Sort of a bug?

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently, when submitting work the modal asks for an optional "PR Link" and allows you to submit without including any link. Links are usually for Repos and not PRs anyway, so this may be confusing, or people just forget.  I would like everyone to be forced to include a link, otherwise the submit button throws an error.

### Expected Behavior
[comment]: # (Describe what you expected to happen.) 
Users should be forced to include a project link with their submission.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
"PR Link" changed to "Project Link" and field is no longer optional.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
I'm primarily thinking in the context of hackathons, however I don't see why this shouldn't be mandated across the entire platform.

**Comment by PixelantDesign** [comment]
@zoek1 ^

**Comment by thelostone-mc** [comment]
Closed via https://github.com/gitcoinco/web/pull/6719
