### ISSUE TITLE
Hackathon Events Tab 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6695]
### User Story

As developer on Gitcoin, I'd like to see and add events to my calendar that are related to a specific hackathon in one view.

### Why Is this Needed

No central place to see all the event activities and workshops.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

In admin  - hack ops can add calendar and users can  add events to their calendar (integrate add  event) [https://www.addevent.com/products/add-to-calendar-button](https://www.addevent.com/products/add-to-calendar-button)
### Definition of Done

- [ ] Build events tab  for web
- [ ] Build events tab  for mobile
- [ ] Add ability to set up calendar using add event
- [ ] Add icon association to denote event types
- [ ] Add social proof - number of people registered and who's going

### Data Requirements
- Users signing up for events through our site
- Qualitative feedback

### Additional Info

https://www.figma.com/file/KUmoLfuTXi9loVktdR0Eg1/Gitcoin-Hackathon-H2-2020?node-id=679%3A536

<img width="896" alt="Screen Shot 2020-09-08 at 3 50 28 AM" src="https://user-images.githubusercontent.com/238235/92448415-8d7e5580-f186-11ea-901c-e3ae1f09a3c7.png">

### Future Thinking
V2  - hack ops set up event via gitcoin using an add event button, instead of going to add event.
V3 - sponsors set up on sponsor dash

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/7148

**Comment by PixelantDesign** [comment]
Airmeet + Add Event
Having event prominent on the explorer.
How do we make events and airmeet the new normal?

**Comment by frankchen07** [comment]
@connoroday - when someone adds an event to their calendar, what shows up in our add event account (wrt numbers & tracking)
