### ISSUE TITLE
Scope of task

### ISSUE THREAD

**Issue by GaretWebster** [gitcoinco/web#670]
1) How do I identify if someone is a python user or not? While I realize this is probably out of the scope of this task, if we will never have the ability to tell if someone is a python user then this task will provide no benefit.
2) This seems to me like it should be more of a general improvement to the current landing page than a completely different landing page that has to do with a specific topic. I think the real issue here is finding a way to display relevant issues to anyone on the homepage, regardless of what their tech stack of choice is. I also do think it would be a good idea to show current issues on the homepage, they give a really good idea of what the website is actually about. "help grow opensource" isn't really that clear of a message to me. Solve this open source issue and be paid for it is much clearer.

**Comment by owocki** [comment]
is this related to https://github.com/gitcoinco/web/issues/620 ?

**Comment by GaretWebster** [comment]
Yes, sorry ill move it there.
