### ISSUE TITLE
Invite to Bounty does not work

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#6700]
**Describe the bug**

Tried inviting someone to bounty with the "Invite to Bounty" feature, but it shows me a "The user was not found" error

**To Reproduce**

1. Go to someone's profile, and click Invite to Bounty
<img width="419" alt="Screenshot 2020-05-22 20 14 52" src="https://user-images.githubusercontent.com/19514207/82666765-22f1ea00-9c69-11ea-967f-fa4e7fec6868.png">

2. You'll be redirected to the Users Directory, and got a "The user was not found" error.
![gitcoin co_users_invite=zoek1](https://user-images.githubusercontent.com/19514207/82666794-30a76f80-9c69-11ea-8107-3087360f97ba.png)

**Expected behavior**

I should see the "Invite to Bounty" modal where I can invite someone to a bounty.

**Desktop (please complete the following information):**

- OS: MacOS 10.15.4
- Browser: Brave
- Browser Version: Brave 1.9.72

**Comment by thelostone-mc** [comment]
This was cause the user directory was broken !
It's been fixed and deployed 

Thanks @willsputra for the report

![Untitled](https://user-images.githubusercontent.com/5358146/83529749-63265780-a508-11ea-8852-352a217e6aa7.gif)
