### ISSUE TITLE
Doesn't show my work when i submit a bounty on gitcoin ad instead shows it as it was submitted by funder

### ISSUE THREAD

**Issue by nanspro** [gitcoinco/web#6706]
**Describe the bug**
noticed a weird issue, i submitted work on a bounty and my submission was successful and it even shows up correctly on github but on gitcoin it doesn't show that and instead says that someone else submitted work on that (bounty funder in this case).

**To Reproduce**
For ref look at this https://gitcoin.co/issue/Azure-Samples/bc-community-samples/75/4345 and https://github.com/Azure-Samples/bc-community-samples/issues/75

**Expected behavior**
It should show submitted work in my name and profile.

**Screenshots**
![Screenshot from 2020-05-23 07-35-42](https://user-images.githubusercontent.com/24641089/82747280-f9de7000-9db4-11ea-8df8-c2d3ed70a3c8.png)

![Screenshot from 2020-05-24 11-53-17](https://user-images.githubusercontent.com/24641089/82747305-390cc100-9db5-11ea-9d84-4b00ed5fff12.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.06
- Browser: Brave

**Additional context**
It shows the submitter name and work correctly on github issue but not on gitcoin.

**Comment by Sirlupinwatson1** [comment]
Hi @nanspro 

I might have encounter the same experience lately. Can you double check later on simply by refreshing your browser.

**Comment by nanspro** [comment]
Tried that already, I had this issue 2days back and its still there.

**Comment by Sirlupinwatson1** [comment]
You can look your event viewer at C:\Windows\System32\winevt\Logs\Internet Explorer.evtx
From there scale your desired time period 2 days ago in the saved log file and see if you can view a log. From the source code of gitcoin your should be able to pull this out in a line of code.
This is more a debugging situation here that i would suggest further investigation lol. It could might be the connection from gitcoin to brave and github and policy or token not granted ? I will not start speculating but should be easy to figure .

**Comment by Sirlupinwatson1** [comment]
If you go here, you can view it on your profile : https://gitcoin.co/nanspro/portfolio

**Comment by danlipert** [comment]
Hey @nanspro we've deployed a fix for this but it still seems to be occurring occasionally - will be working on another fix this week
