### ISSUE TITLE
Daily Action in Town Square is Broken

### ISSUE THREAD

**Issue by adrianhacker-pdx** [gitcoinco/web#6711]
**Describe the bug**
Town square daily action is broken

**To Reproduce**
Automatically upon login

**Expected behavior**
Should show a daily action available but says it is available in 2d 22hr

**Screenshots**
![Screenshot at 18-23-00](https://user-images.githubusercontent.com/51737262/82851585-1661d180-9eb5-11ea-9ef9-e2c83f20ef26.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Chrome 
- Browser Version: Version 83.0.4103.61

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
Just happened to notice it

**Comment by danlipert** [comment]
I think we forgot a day in the daily action list - thanks for the report!
