### ISSUE TITLE
Exploration - Hackathon Idea Board

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6712]
### User Story

As a contributor I'd like to easily see ideas that sponsors are intersted in per hackathon prize.

### Why Is this Needed

Engagement Feature
A place to capture Vitalik level ideas

**Hypothesis:**
If contributors had a way to see ideas that funders were interested in having built, it would spark some ideas and give them a starting point when getting started at the hackathon.

If we prompt funders to add these ideas, it helps to steer hackers in a direction and increasing likelihood of making a sponsor happy.

If we add this feature, it encourages sponsors to do other thinigs in Gitcoin to interact with the platform and community after funding the bounty.

### Description

Feature

### Current Behavior
No Idea board

### Expected Behavior
Have idea board

### Definition of Done

- [ ] Display simple description and who posted it
- [ ] Link. to associated bounty
- [ ] Allow for chat 
- [ ] Allow for view on github link
- [ ] Only sponsors can add ideas
- [ ] Contributors can favorite an idea
- [ ] Ideas show up in townsquare after a sponsor posts 

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information

<img width="1008" alt="Screen Shot 2020-05-26 at 2 42 24 AM" src="https://user-images.githubusercontent.com/238235/82868753-2dc3ad80-9efb-11ea-987b-60580ebea762.png">

**Comment by PixelantDesign** [comment]
@ceresstation @thesachinmittal ^

**Comment by ceresstation** [comment]
This looks great, a few possible additions / adjustments:

- As a potential hacker it would be helpful to know in advance what the associated prize is without going to a new page, is there potentially a way to just get a drop down with more prize info if the user clicks on "associated prize" rather than sending them to a new page (this may require having one idea per line vs. two for simplicity)

- If I start work based on an idea, it might be helpful to be able to tag it as my inspiration for building a project and give kudos to the person who came up with it

- As a hacker, I should have the ability if I don't already to remove an idea I posted in case I decide to work on it

**Comment by frankchen07** [comment]
Just noting here to track the results of this experiment - we want to see a shortened time frame on getting a hacker started up on an idea with a funder. I'm still of the camp that a public chat room where all the discussion goes down could be the proving grounds for that, and ensuring responsiveness in the chat. My only concern with an idea board is that it can publicize or expose ideas, but if the funder isn't responsive, we will also think it's a failure, so in some sense, responsiveness trumps everything.

**Comment by PixelantDesign** [comment]
The board its meant for funders to help contributors get started. Decreasing the 3-4 day painpoint/time that it takes hackers to come up with the ideas. 

So an experiment could be, would funders come in the app to fill out the idea board?

**Comment by frankchen07** [comment]
hypothesis would be that an idea board reduces the time to start (time to value?! perhaps). this would tough to determine but we could add impressions onto the idea board like we do on townsquare to see how many times an idea as been viewed. this way we have definitive data on the time it takes for that user to "start work", "join a team", etc, as compared to someone who didn't. 

we can then figure out if it's a significant change, and if not, then there's less evidence to support something like an idea board. 

it's also just a very heavy thing. we could literally just place everything in a spreadsheet too and see how it performs.

**Comment by PixelantDesign** [comment]
>it's also just a very heavy thing. we could literally just place everything in a spreadsheet too and see how it performs.
This is a good test @sachin. and I were talking about this on Friday too...
