### ISSUE TITLE
Creating a hackathon project when starting work fails (possibly when using Authereum only?)

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#6714]
**Describe the bug**
When starting work on a hackathon bounty, the flow fails when the user tries to submit their project for Stellar - Hackathon Get Started bounty

**To Reproduce**
unable to reproduce locally

**Expected behavior**
The project should save as expected

**Screenshots**

![failedprojectsave](https://user-images.githubusercontent.com/869266/82899797-85fbbd80-9f96-11ea-88fa-8ecd7fced66f.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Unknown

Note: the user does not have metamask installed

**Additional context**
Bug report submitted by @tgemayel 
Note the project in fact already exists but for another hackathon - the project as shown in the screenshot does exist in the database. After examining the model, there does not seem to be a unique constraint that would cause failure here. The error message comes from: https://github.com/gitcoinco/web/blob/master/app/dashboard/views.py#L3986 - may be related to chat.

**Comment by owocki** [comment]
@danlipert could be related to one of these sentry issues?  either nullifeid profile or mailchimp issue?

https://sentry.io/organizations/gitcoin/issues/?project=1398424&query=is%3Aunresolved+error+in+record_action&statsPeriod=14d&utc=true

**Comment by octavioamu** [comment]
@Tgemayel seems https://gitcoin.co/karinfdez doesn't exist is that why failing.
@karinfdez login into gitcoin so your team can add you.
