### ISSUE TITLE
Projects View Fetch can take 15 seconds

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6717]
https://app.datadoghq.com/apm/traces?from_ts=1583159505917&index=apm-search&live=true&query=env%3Aprod+service%3Adjango+%40duration%3A%3E%3D1800ms&spanID=4779173695927421529&to_ts=1583160405917&trace=AQAAAXI8zeRKOrL7oAAAAABBWEk4emZrRysvMjFnUmRnenpzbw

or just go to any hackathon thats got a number of projects

**Comment by thelostone-mc** [comment]
Fixed by @androolloyd as told by @PixelantDesign over call
