### ISSUE TITLE
Hacker Engagement & Participation Hypotheses

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6720]
### What

We want to enable hackers to learn, earn, network.

### Why Is this Needed

IF we build these ideas and make it easy for hackers to participate THEN we will see more quality projects created and submitted BECAUSE they'll have all the tools to participate as a team.

**Hacker Journey**

1. Visit landing page
2. Connect Github
3. Select Hackathon
4. Register
5. Registration Flow
6. View Prize
7. Attend Pitch Session
8. Start Work
9. Attend Workshops
10. Do Work
11. Mid Hack Session
12. Do More Work
13. Submit Work
14. Demo Work
15. Get Paid

**Hacker Goals**

- meet other like minded devs
- learn a new language
- learn new skills
- finding what they're naturally interested in
- developing breakthrough ideas with others
- having a seamless coding experience
- make money
- find work

### Hypothesis
The hypothesis is that these solutions/ideas below will make it easy for hackers to get started, let others know about their skills, why they’re participating, build teams, find teams, during Gitcoin hackathons.

<img width="1285" alt="Screen Shot 2020-05-26 at 11 55 02 PM" src="https://user-images.githubusercontent.com/238235/82976174-61aadb80-9fac-11ea-97dc-17fd7227cfd9.png">

### Stories 

As a  potential Gitcoin hacker, I want to know what the hackathon is all about and why I should participate.

As a Gitcoin hacker, I want Gitcoin to tell me what I need to prepare and help me succeed at this Hackathon.

As a Gitcoin hacker, when I register for a Hackathon, I want everyone to get to know me, and what I’m looking to do at the hackathon.

As a Gitcoin hacker, I want my actions broadcasted to everyone on the hackathon so that I can find developers to hack with.

As a Gitcoin hacker, I want a quick way to see all the high level ideas that sponsors are interested in building.

As a Gitcoin hacker, I want a way to clearly see projects I’ve started, prizes, projects to submit, so I can stay on top of my prizes.

As a Gitcoin hacker, I want a way to represent my team across many Gitcoin hackathons.

### Success
% of teams / submissions with  >1 member

**Comment by frankchen07** [comment]
for all of these, I would say these are hypotheses that we want to "test" to enable contributors to learn, earn, and connect. 

Some examples of "learning, earning, and connecting" can include:
1. finding what they're naturally interested in
2. developing breakthrough ideas with others
3. having a seamless coding experience

> As a potential Gitcoin hacker, I want to know what the hackathon is all about and why I should participate.

This is just nailing down our ideal persona, to ensure we're serving the right population.

> As a Gitcoin hacker, I want Gitcoin to tell me what I need to prepare and help me succeed at this Hackathon.

agree with this, but can we purposely simplify and design in a way where the experience or UX eliminates "preparation" and we automatically set them up for success? 

A question that comes to mind is, if I am a seasoned developer, what resources or connections do I need to make to get started on a hackathon? (engineer input might be good here). 

Talking to our own engineers, it seems a hackathon is a very simple process. There's some money, there's some technology, and there's some sponsor guidelines on what they're looking for. Start and end dates, and I get started. Only here on Gitcoin do we have "start" work.

> As a Gitcoin hacker, I want my actions broadcasted to everyone on the hackathon.

I would make this slightly more specific on what kinds of actions broadcasted to what kinds of people. For example, if I'm joining it'll be broadcasted to every project that is looking for a team member.

> As a Gitcoin hacker, when I register for a Hackathon, I want everyone to get to know me, and what I’m looking to do at the hackathon.

I'd shuttle this under the participants tab, and I think there are some elements of team formation that are possible here too.

> As a Gitcoin hacker, I want a way to clearly see projects I’ve started, prizes, projects to submit, so I can stay on top of my prizes.

This one I might modify based on some data (do people work on more than one project?) and perhaps figure out how contributors are interacting with the tools we're giving them (e.g, once I start work, what are the touchpoints on our platform that would make their life easier, or are they simply working off platform, like on github?) Maybe two actionable data points for myself to take a look at.

> As a Gitcoin hacker, I want a quick way to see all the high level ideas that sponsors are interested in building.

When it comes to ideas I feel like there needs to be healthy discussion or discourse. An idea board doesn't necessarily offer that. If I were a sponsor, I would put this in the description of the prize/issue and hold something like an office hours to get feedback.

> As a Gitcoin hacker, I want a way to represent my team across many Gitcoin hackathons.

This is a very interesting concept, I would shuffle it under team formation / getting team formation right first.

**Comment by PixelantDesign** [comment]
@frankchen07 

> for all of these, I would say these are hypotheses that we want to "test" to enable contributors to learn, earn, and connect.

 ^ feels very broad (everything), I was hoping to focus on a subset of problems geared towards the problems we currently have around getting more hackers involved, engaging, and participating in a team.

---

As a Gitcoin hacker, I want Gitcoin to tell me what I need to prepare and help me succeed at this Hackathon.

> agree with this, but can we purposely simplify and design in a way where the experience or UX eliminates "preparation" and we automatically set them up for success?

If we could do everything for hackers, it makes sense but things like reminding them to get the most updated truffle package and setting up npm installers, we can't do that for them automatically. We can only prompt.


> A question that comes to mind is, if I am a seasoned developer, what resources or connections do I need to make to get started on a hackathon? (engineer input might be good here).
Agree ^, talking to hackers helps too.

> As a Gitcoin hacker, I want my actions broadcasted to everyone on the hackathon.
> I would make this slightly more specific on what kinds of actions broadcasted to what kinds of people. For example, if I'm joining it'll be broadcasted to every project that is looking for a team member.
^ Agree, I'll make this specific to hackathon related actions. 

> As a Gitcoin hacker, when I register for a Hackathon, I want everyone to get to know me, and what I’m looking to do at the hackathon.
> I'd shuttle this under the participants tab, and I think there are some elements of team formation that are possible here too.
makes sense

As a Gitcoin hacker, I want a way to clearly see projects I’ve started, prizes, projects to submit, so I can stay on top of my prizes.

> This one I might modify based on some data (do people work on more than one project?) and perhaps figure out how contributors are interacting with the tools we're giving them (e.g, once I start work, what are the touchpoints on our platform that would make their life easier, or are they simply working off platform, like on github?) Maybe two actionable data points for myself to take a look at.
Cool

As a Gitcoin hacker, I want a quick way to see all the high level ideas that sponsors are interested in building.

> When it comes to ideas I feel like there needs to be healthy discussion or discourse. An idea board doesn't necessarily offer that. If I were a sponsor, I would put this in the description of the prize/issue and hold something like an office hours to get feedback.

The idea would link to Github where that conversation would happen. Live interaction is obvi best.
What I've noticed is some sponsors put ideas in the bounty, but it's buried below all of the requirements and technical speces. How we surface just ideas for hackers to get excited?


As a Gitcoin hacker, I want a way to represent my team across many Gitcoin hackathons.


> This is a very interesting concept, I would shuffle it under team formation / getting team formation right first.

yea maybe, when we bucket things too much the experience gets very large
