### ISSUE TITLE
Email speed architecture discussion

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6729]
From my work on https://github.com/gitcoinco/web/pull/6728 I have realized that it takes about 3s to send a daily email.

From profiling the code ( 714b0fdd1174d274f92e71944bc63542f8e3d775 ) I have discoverd that the premailer is the priamry culprit of this issue.

This leads me to a question.. What do we do about making our email sends faster??  Right now it takes about 3s to send a daily email and 2.5s to send the weekly roundup.  at 31k active subscribers itll take 31000*2.5 = 77.5k seconds or 21 hours to send to the entire userbase.

if we can get that down to 0.1 seconds, it take roughly an hour to send to the entire userbase.

so what do we do about this?  I can see two approaches:
1. we pump all the emails through a celery queue and we run the premailer there.  and we can sclae that up horizonatally
2. we refactor the premailer to run at deploy time, instead of running at execution time.  this means that we wouldnt have to run the premailer for every single email send, but instead we'd compute the premailer information as part of the build process.

what does the group think?

**Comment by owocki** [comment]
@gitcoinco/engineers @androolloyd @sebastiantf would love ur feedback on this.

**Comment by owocki** [comment]
here is a very hacky example script that could compile CSS at compile time, but it'd need to be expanded to correctly follow `include` or `extend`s

```
pre = 'retail/templates/'
template = 'emails/template.html'
with open(pre + template, 'r', encoding='utf-8') as myfile:
  data = myfile.read()

from retail.emails import premailer_transform
premailer_transform(data)
```

**Comment by danlipert** [comment]
It seems the biggest win is the premailer optimization. Is there ever I case that we need it to be run per-email? I don't think so. Given that, parallelizing it or offloading the recreation of the same CSS to another box seems like we are doing both refactoring and throwing hardware at it, rather than just doing the proper refactor.

**Comment by owocki** [comment]
i tend to agree. the script above gets us like 20% - 50% of the way there.  will need to close the gap form there.    do we think this work should be done internally or can i bounty an external contributor to look at it?

**Comment by owocki** [comment]
note: daily email is rolled out to 20% of userbase now + takes about 8 hours to run. bumping up to 40% today a849c97e7288a9a3660cd3d8f95d3b0d7cc5e810

**Comment by androolloyd** [comment]
There are a few options for bulk emailing we could consider, SendGrid has a great bulk email delivery api that allows for unique templates. 

https://sendgrid.com/docs/glossary/bulk-email-service/

**Comment by androolloyd** [comment]
There are other options like https://www.dyspatch.io/sendwithus/ that let you leverage your template management outside of the application and just ship data to their api to deliver across whatever platforms you'd like to integrate an api to.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/6762 paralellizes the emails + sends to celery.  

i agree that premailer optimization is probably the best long term thing to do.
