### ISSUE TITLE
Sponsor Experience Hypotheses

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6730]
From talking to sponsors, and observing the end of several hackathons, we've determined what a happy end result is for sponsors.

The lagging measurable outcome for a sponsor is to receive on average, 5-15 high-quality submissions per prize. 

On top of that the implicit need is the ability to follow up, communicate, and mentor these developers during and post hackathon in order to continue the working relationship and enhance hackathon projects into real-world, usable products and companies.

Currently as it stands the sponsor experience looks something like this:

1. agree on doing a Gitcoin hackathon

2. open prizes on Gitcoin's bounty system, which hackathons is built off of.
    - previously we've had members of our operations team fund the issues, but ideally, we want sponsors to be involved with easily funding their own prizes

3. the hackathon begins, and contributors begin streaming in and starting work

4. during the hackathon, there are various methods that we see sponsors interacting with contributors:
    - holding office hours
    - holding workshops
    - comments on github tickets (prizes that they opened)
    - gitcoin chat
    - gitcoin townsquare
    - off platform (slack, discord)

5. post-hackathon, sponsors report that:
    - "there's no central location to know who actually worked on my issues"
    - "I have to record all of the participants in a spreadsheet, who worked on what, and who was paid out"
    - "communication is very disparate and not consolidated on gitcoin"
    - "gitcoin chat was just an initiator, and then most technical questions go to github, no huge difficulties using gitcoin chat though"
    - "github was a pretty good channel"
    - "there were too many different elements to using gitcoin, there was github, chat, gitcoin web, if it was more cohesive and easier to use, that would've been nice"
    - "we lacked a source of truth for which hackers we interacted with, we started with registration, then chats, then emails, then we build an excel spreadhseet to track our own teams, couldn't all of this have been automatically generated?"
    - "we didn't payout the prizes through gitcoin"

6. taking a look at our metrics
    - https://metabase.gitcoin.co/question/693 - how do we 10x this?

---

The hypothesis is that these solutions/ideas below will consolidate and make it easy to follow up, communicate, and mentor developers during and post hackathon.

---

As a Gitcoin sponsor, I want a "communication productivity" tool that combines in all in one interaction experience, with information organized by a prize, project, people hierarchy, and allows me to reach out to all members of a any project at any point.

<img width="1139" alt="Screen Shot 2020-05-27 at 15 20 32" src="https://user-images.githubusercontent.com/7516920/83078160-cce8c200-a02d-11ea-8b21-b0f3c3ab59e1.png">

---

As a Gitcoin sponsor, I want a sponsor dashboard that clearly lays out prizes, projects, relationships, and communications, with all associated actions under those categories.

- https://www.figma.com/file/36SoFKGzm3umgzX5JY6pfR/Gitcoin-Hackathon-Experience-Rehaul?node-id=49%3A4

![Screen Shot 2020-05-26 at 18 07 38](https://user-images.githubusercontent.com/7516920/83076643-c9a00700-a02a-11ea-90db-74c0b168084f.png)

---

~As a Gitcoin sponsor, if I perform a significant hackathon action (new prize, looking for something specific), I want to choose how my request is broadcasted to the gitcoin hacker network.~
- ~on second thought this should be automatic~

---

As a Gitcoin sponsor, I want a running history of everyone who I've worked with, including hackathon details, past projects, prizes, and on platform contact information.

- This is more just the simple spreadsheet version with info that we can display for them. However, it doesn't quite solve the problem of on-platform communication, unless have it in a centralized location enables them to do that.

<img width="976" alt="Screen Shot 2020-05-27 at 15 20 25" src="https://user-images.githubusercontent.com/7516920/83078179-d7a35700-a02d-11ea-9b55-ae23f53a5e43.png">

---

As a Gitcoin sponsor, I want the ability to rate the projects in a hackathon as it proceeds, which exposes my underlying preferences for projects and hackers.

- I was thinking less along the lines of rating, and more an organization method for sponsors to adjust how they view their prizes and projects, but this to me feels more of a v2, v3. Don't necessarily want to over-design just yet.

<img width="1034" alt="Screen Shot 2020-05-27 at 15 20 18" src="https://user-images.githubusercontent.com/7516920/83078194-de31ce80-a02d-11ea-933c-ec38ab4976b7.png">

---

As a Gitcoin sponsor, I want role based access control of my Gitcoin account for my internal team, so hackers can reach every member of my team if necessary.

---

what other ideas?

**Comment by alexvotofuture** [comment]
Love the synthesis of ideas here @frankchen07. Thanks for putting this together.

Given the feedback it seems the highest-leverage place to start is the view you called "Project Management" in your Figma file. Goal would be allowing sponsors to review started/submitted projects for each prize, chat with teams/hackers through clickable icons, mark winners and pay everyone out within a single view. Could show other sponsors' prizes/projects below, in case they are curious.

On comms confusion: Should we make Gitcoin Chat the single channel of hackathon communication? If we move away from hosting prize descriptions on Github that cuts one communication channel contributing to the confusion (also solves the problem of people thinking they can just submit directly on the Github thread). Town Square already pushes old posts down to the bottom, so it's not that different from Gitcoin Chat right now anyway - could cut that too to reduce the number of things sponsors check. Could use Kevin's Gitcoin Chat bulk DM feature with some useful queries that sponsors could choose from ("DM all who started work on your prize"). @vs77bb @connoroday thoughts?
