### ISSUE TITLE
As a hackathon sponsor I want to track who won my prizes (payout)

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6735]
# User Story
As a hackathon sponsor I want to track who won my prizes so I can contact them for ongoing work and share their winning projects publicly.

### Why Is this Needed

Currently no way for sponsors to indicate who won a prize, and no way for them to easily query who won for later use. No way for hackers to know which projects won (besides looking at an individual prize's activity feed and seeing who got paid out a certain amount.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Tracking winners by payment on prize activity feed.

### Expected Behavior
"1st place/honorable mention/etc." tags on hackathon project cards/pages, and ability to search for winning projects.

### Definition of Done
See above

### Data Requirements
- Track how many sponsors go back and contact winners using this.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by PixelantDesign** [comment]
We've talked about this before - and think we have a design for it already.
