### ISSUE TITLE
Participants/project searches broken

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6737]
**Describe the bug**
Cannot search by text for projects/participants on hackathon tabs, even with a 100% matched name.
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Fixed over at `11123a6d8`

![Untitled](https://user-images.githubusercontent.com/5358146/83253198-330a4c00-a1ca-11ea-98f3-a1e56756f939.gif)
