### ISSUE TITLE
Standard Bounties Removal

### ISSUE THREAD

**Issue by alexvotofuture** [gitcoinco/web#6739]
### User Story 
As a hackathon hacker I want to submit my work without paying gas so I don't get stuck at the end of a hackathon unable to make a submission.

### Why Is this Needed
Hackers are unable to submit due to lack of funds, and often aren't made aware of the faucet or are stuck waiting for approvals. Web3 signing issues are a barrier in general here.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Improvement

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
The TLDR on this is that we'll be removing the standard bounties integration and unifying the cross-chain and ETH experience to be more similar to what the cross-chain experience is. Some quick milestones here are:

- Updating Web3 / Integrating Walletconnect
- Removing all the standard bounties frontend and backend code
- Creating a fallback flow (pay via metamask) for users who don't want to use the 2-device flow via wallet connect or QR code.

**Comment by PixelantDesign** [comment]
Plan:
V0 - Initial version based on cross chain flow
Remove ability to create a bounty with standard bounties.
w/o removing metamask
need marketing documentation help messages

V1 - Metamask payout flow - for end of hackathon
Change cross chain flow for contractless ETH bounties to generic web3 focused payout, that also has qr code available.
update hackathon fund bounty form
Metamask focused flow, - primary
Detect wallet, fallback is qr code
Need to support users that have nothing - no wallet

To Do: Clean up issue details following standard bounties removal
