### ISSUE TITLE
Cannot explore all bounties

### ISSUE THREAD

**Issue by karansinghgit** [gitcoinco/web#6740]
The issue explorer doesn't let me see all the bounties. I can only see bounties with the tag of `statusim`. Clicking on the `x` of the tag, doesn't remove it for some reason.

Go to https://status.im/our_team/ and click on `bounties listed on gitcoin`. It will open a page of the gitcoin bounties with the tag of `statusim`. After that, there is no way to look at other bounties. Clicking on the `x`, does not remove the tag and instead reloads the page.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge Dev
- Browser Version: Version 84.0.516.1

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
@karansinghgit thanks for the report!
Fix is ready and here is the demo. Will get it deployed once it's merged in

![Untitled](https://user-images.githubusercontent.com/5358146/83251103-bfb30b00-a1c6-11ea-8fd9-df7502c8ec61.gif)
