### ISSUE TITLE
As Conflux community, I want to let gitcoin support conflux mainnet wallet.

### ISSUE THREAD

**Issue by xiaods** [gitcoinco/web#6749]
### Discussion
Conflux Mainnet,  https://confluxnetwork.org/
An open network for a new world of web3.
Can I bounty a task to let gitcoin to support conflux coin.

I know currently gitcoinco support metamask, also conflux have developed a ConfluxPortal Browser Extension based on metamask, it also support Conflux token/contract(solidity)
https://github.com/Conflux-Chain/conflux-portal

**Comment by owocki** [comment]
if there is an ERC20 token/ token bridge for this project you can submit it here https://gitcoin.co/submittoken

if not email us at founders@gitcoin.co and CC scott.moore@consensys.net and we'll see what we can do

**Comment by xiaods** [comment]
done. thanks @owocki
