### ISSUE TITLE
Bounty increase does not check if fee + increase is viable given user funds.

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#6751]
In https://github.com/gitcoinco/web/issues/6746 we had a report that a user was unable to increase a bounty amount. After investigation, it seems that the user did not have enough funds to cover both the amount increase, plus the fee. We should check if the user has the funds to cover both the amount and the free before conducting the fee transaction.

**Comment by nasehim7** [comment]
@danlipert Hey Dan! I would be interested in taking this up. Do let me know your thoughts?
