### ISSUE TITLE
Links opening in new tab/window open in same target

### ISSUE THREAD

**Issue by michelgotta** [gitcoinco/web#676]
Throughout the platform links opening in new window have target set to "new". Opening several links override the open page. The right way to open links in a new window is:

`<a href="[…]" target="_blank" rel="noopener noreferrer">Foobar</a>`

Read:
https://stackoverflow.com/questions/4964130/target-blank-vs-target-new 
https://mathiasbynens.github.io/rel-noopener/

Will provide a pull request.

**Comment by PixelantDesign** [comment]
Hi @michelgotta, great idea! Are you still working on this?cc:  @thelostone-mc

**Comment by arun1595** [comment]
@PixelantDesign We can close this as it is fixed by https://github.com/gitcoinco/web/pull/677

**Comment by PixelantDesign** [comment]
Thanks @arun1595
