### ISSUE TITLE
Successful Payment not Present in Activity Feed

### ISSUE THREAD

**Issue by theCydonian** [gitcoinco/web#6765]
**Describe the bug**
When a user receives a payment, the payment is not present in the activity feed for the bounty or the user.

**To Reproduce**
1. Bounty is payed out through the bounty network contract.
2. Check gitcoin.co/{username}/earnings
3. Check gitcoin.co/issue/{bounty}

**Expected behavior**
After payment is sent, both activity feeds should include an entry for the payment.

**Screenshots**
![82763057-93a81c00-9db9-11ea-8686-08231da679aa](https://user-images.githubusercontent.com/31706764/83706038-53237c00-a5cb-11ea-8f95-0bcc49ea243b.png)
There should be an entry for the completed payment.

![82763058-9571df80-9db9-11ea-9b33-2b56585344e3](https://user-images.githubusercontent.com/31706764/83706043-561e6c80-a5cb-11ea-857f-82d7d58936b7.png)
There should be a 1 ETH payment somewhere here.

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser: Firefox
- Browser Version: 76.0.1

**Comment by Solexplorer** [comment]
Can you please post the bounty link?

**Comment by theCydonian** [comment]
https://gitcoin.co/issue/gitcoinco/web/6194/4098 @Solexplorer
