### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kvndlgs** [gitcoinco/web#6782]
Hey guys, first of, thank you for all, i've been learning a lot on gitcoin on as well as making some coins. I'd say everything's working fine, except for one thing when browsing bounties. I don't know if i am alone that has experienced that, but the boutines showing were by default only those which i participated in and it felt kinda buggy/unintuitive while trying to have them sorted back correctly.

**Comment by owocki** [comment]
thanks kvn, what was the https://gitcoin.co/explorer link you were taken to when you saw thos ebounties?
