### ISSUE TITLE
Please organize small and easy bounties which do not require coding or developing.

### ISSUE THREAD

**Issue by Saketjee** [gitcoinco/web#6785]
Hello, I would like to suggest that Gitcoin should conduct more small and easy to do bounties such as Kevin Owocki did (related to creation of a quest) so that people with Non Technical/Non Developer background can earn some money out of it.Please, it is very important so that more people could benefit from such bounties and earn some money. Also,the time frequency to conduct these activities should be faster and at least one such bounty should be conducted per week.

Thanks.
Saket.

**Comment by owocki** [comment]
interesting feedback.
