### ISSUE TITLE
Info about Kudos and Gas

### ISSUE THREAD

**Issue by PabloCGL** [gitcoinco/web#6788]
Hi! I´m new here and loving everything so far, but since the daily quest was to give some feedback, here I am :)
One thing that can be a bit confusing for beginners (or at least was for me!) is the process of generating Kudos after finishing a quest.  Suddenly having to pay 0,0114 eth (nearly 3 dollars!) to reward yourself a digital pat on the back is a bit bewildering, and takes away from the experience. I understand that if you are gifting a kudos (which is their original use, isn't it?) the cost expectations may be different... But for someone who is just learning and doesn't have eth it's a bit of a downer.
Anyway, a little question mark/link to the wiki on the redeem page, with an explanation of where the high cost comes from (and if there are ways to avoid or lower it?) would do much good, I think 
Cheers, an keep on the good work!

**Comment by owocki** [comment]
we actually just put in a change where you dont have to pay gas anymore. try now.

**Comment by PabloCGL** [comment]
Wow, great! I just tried doing a quest, and it worked.
When I wanted to claim the Kudos for a quest I had finished some days ago it took me to the old redeeming page though, even after repeating the quest. Is this intended?

**Comment by owocki** [comment]
the system is dumb and tries to re-use old kudos coupoons.  give me the link and ill reset it for u

**Comment by PabloCGL** [comment]
I actually ended up doing a different quest which gave the same reward, so there is no need to. But thanks for the offer!
