### ISSUE TITLE
Tip used for Saving account

### ISSUE THREAD

**Issue by Sirlupinwatson1** [gitcoinco/web#6789]
Hi, i just had this idea, why not using some tip and build saving accounts. That could be great. 
Also, if we can have more Unicorn discussion i would be more than happy. 

Otherwise, i have nothing to say but dark town square is terrorizing me. 

@owocki @danlipert @connoroday @walidmujahid @lawrencelink @Solexplorer 
I tagged all my friend to make sure. Good work with Gitcoin guys.

**Comment by walidmujahid** [comment]
I just saw this @Sirlupinwatson1. I am uncertain as to how a saving account works, I will probably look into that. However, could you go into more detail as to what you are proposing? Also, was this Unicorn discussion part of yesterdays meeting? I still have not reviewed the recording yet, so I will need to do that some time soon.

The darkmode in town square has actually improved for desktop in Google Chrome. I like it. What manner of improvements do you think should be done for the darkmode to be better? If you do not like it, then I could easily think it would be an improvement to make it more readily obvious how to opt-out of the darkmode if that option exists already. If that option does not exist, then maybe it should.

**Comment by Sirlupinwatson1** [comment]
Hi @walidmujahid how are you my friend ?

Town Square is terrorizing when i compare it from Edge to Chrome, i will get used to it i guess, the light i have in my apartments are not that good even when i add some, i personally like as much dark themes as standard one, the benefice for me is the white theme is giving me more light to read and stay awake countless of hours :) 

The idea behind a saving account, was pretty much on the spot, spontaneously in respond to daily action from Gitcoin, but mostly you guys are missing me a bit. I work and study more than 100 hours a week, not that i deserted Gitcoin line a man made deserter, just because the call of <Knowledge is screaming at constantly helping out to reach my goal.  

On a brief and straight forward speculation for a saving account, Tip are really funny, but imagine we could split them, or even i would tip your Saving account up to my discretion within a simple addon on the interface with a button for example, "Tip User" and "Tip User Saving" 

I had personally not the emphasis on my financial reality a good part of my life and having a saving account could have help me to buy critical need during some momentum. I think that it could help other but also at the same time leveraging education for everyone and everyone know that a business perspective in the current world that we live is certainly not something that we should take it easy. Those minimal amount can be even 0,1 penny, who know what can lead to with young engineer and their idea, in the better world we will think out of the box and lead the walk with conditional and useful things like that "That Things" (Amazon would say this)

Tell me what you think. For me, anything educational or with a financial ideology, can help.

**Comment by Sirlupinwatson1** [comment]
I forget to mention the "Unicorn team" , witch i was referencing to you and Gitcoin team, i have include myself of course, to build a Unicorn Team. I am just joking, i like to reference the term Unicorn because after reading the definition i was pretty surprise of what i was able to read on the subject.
