### ISSUE TITLE
Expire time is not the same as the described in the bounty

### ISSUE THREAD

**Issue by pmprete** [gitcoinco/web#6790]
On the web page many times the `expired` showed like it was already expired while the ticket should have been active for a couple more hours

**Comment by owocki** [comment]
out of curiosity, what timezone r u in?

**Comment by pmprete** [comment]
GMT -3. But for example one of the bounties expired at 0 hs EST and gitcoin marked it had expired 4 hours ago when there were 3 more hours for the event to finish, and it wasn't 0 hs in my time zone yet.
