### ISSUE TITLE
Images not being displayed 

### ISSUE THREAD

**Issue by Web3Foundation** [gitcoinco/web#6795]
**Describe the bug**

When Github issues have images in them, they are not being displayed on Gitcoin at all. We ran into this issue already a while ago with previous bounties. 

See issues and Gitcoin pages:
https://github.com/polkadot-js/apps/issues/2892
https://gitcoin.co/issue/polkadot-js/apps/2892/4420

https://github.com/polkadot-js/apps/issues/2891
https://gitcoin.co/issue/polkadot-js/apps/2891/4419

https://github.com/polkadot-js/apps/issues/2890
https://gitcoin.co/issue/polkadot-js/apps/2890/4418

etc.

**To Reproduce**

Create a Github issue and drop images into the text. They are displayed fine on Github but appear as text on Gitcoin. 

**Expected behavior**

Display of images, like on Github. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48550657/83954138-ba993000-a846-11ea-97f1-742a95ac0fb8.png)

![image](https://user-images.githubusercontent.com/48550657/83954141-c1c03e00-a846-11ea-8b0b-0521eda4f8da.png)

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.5
- Browser: Chrome
- Browser Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by thelostone-mc** [comment]
Fixed after updating the issue img from `<img>` to `![]()` format

**Comment by owocki** [comment]
any way we can support the `<img>` format? looks like github uploads now use this format instead of markdown format, so id like to ward off future support requests on this..
