### ISSUE TITLE
Tribes -  Ultimate

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6811]
### User Story

As a hackathon sponsor, I'd like to be able to engage, grow, and seamlessly manage my open source web3 community in order to push my organization/ brand forward.

### Why Is this Needed

We have a V1 and need to think about the next iteration to support customer need and meet our business goals.

IF we build these ideas and make it easy for sponsors to manage their community THEN we will see great projects /active development communities BECAUSE they'll have all the tools to grow  their community from hack --->post hack life cycle.

### Description

Agree on what would make a good Tribes paid experience for users.
Agree on how we will build towards this goal.
Agree on what to call this in terms of sales.
Agree on a timeline for this delivery.

### User Stories

**Management**

- [ ]  As a hackathon sponsor, I'd like a place to see all of the hackathon projects that have been created from sponsoring various hackathons.
- [ ] As a hackathon sponsor, I'd like to see related information in similar tabs.
- [ ] As a hackathon sponsor and tribe owner, I'd like to easily email people in my tribe (without giving the address). Build out mailing platform? Tech approach /evaluation
- [ ] As a hackathon sponsor/tribe owner, I'd like a place to go to see how my prizes are doing during the hackathon.
- [ ] As a hackathon sponsor and tribe owner, I'd like to have access to all of the data from my old orgs on Gitcoin.

**Community**

- [ ] As a hackathon sponsor/ tribe owner, I'd like hackers to engage with my organization easier
- [ ] As a Tribe Member, I want a Tribe Leaderboard, so I can see how I stack up against others in the Tribe and learn who in the Tribe to emulate.
- [ ] As a Tribe Member, I want to see the Grants associated with this Tribe, so I can support others in this Tribe.
- [ ] As a tribe owner, I'd like a way to group chat selected folks in my tribe members list.
- [ ] As a hackathon sponsor/  tribe owner, I'd like a way to write short posts on my tribe wall.
- [ ] As a hackathon sponsor/tribe owner, I'd like a way to highlight rising stars on my tribe.
- [ ] As a hackathon sponsor and tribe owner, I'd like ways to find talent

### Current Behavior
Tribes is light

### Expected Behavior
A compelling enhancement to current tribes offering that we all feel good about.

### Definition of Done
Come to some agreements on the above.

### Data Requirements
- Happy customers that want tribes/revenue go up
- Happy customers using tribe light that want to upgrade to Tribes pro

Open to other ideas from the team.
Related to https://github.com/gitcoinco/web/issues/6812 https://github.com/gitcoinco/web/issues/6616

**Comment by frankchen07** [comment]
What are the exact differences between this ticket and https://github.com/gitcoinco/web/issues/6812?

I added the problem statement on https://github.com/gitcoinco/web/issues/6812, but arguably, there are some here that overlap or are exactly the same. It feels like the true problem we want to solve for is fulfill the basic promise of the ability to easily reach people that sponsors have worked with in the past, and anything that is tangentially related to that.

**Comment by PixelantDesign** [comment]
@frankchen07 

This ticket  = what is in the tribes offering (other features for the next iteration of tribes)?
#6812 = what is in the tribes light? and how do we retire old orgs?

**Comment by frankchen07** [comment]
got it, just want to make sure we're not too focused on terminology. We wanna get hack features for sponsors right, and then we figure out everything that is tribes.
