### ISSUE TITLE
Upgrade Current Orgs to Tribes Light

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6812]
### User Story

As a hackathon sponsor, I'd like to have an updated version of the organization page and baseline functionality so that I can engage with my community.

### Why Is this Needed

We currently have an old orgs page and a tribes page with functionality that exists on one page and not the other.

As Gitcoin Core, we should consider retiring the old orgs and providing a light version of tribes to hackathon customers.

IF we provide sponsors with a light version of tribes THEN they won't be confused at how our orgs work BECAUSE they'll have some tools available as a hackathon sponsor.

https://gitcoincore.slack.com/archives/CAW05FUD7/p1591331256380500

### Description

The primary problem we want to solve for is how do we fulfill the basic promise of the ability to easily reach people that sponsors have worked with in the past?

Additional things we touched on about converted current organizations to "Tribes Light":
1. how to reconcile different data sets (old db / new db discussion with Andrew).
2. sponsors have to log in and go through org onboarding flow, what does this look like?
3. how do we make sure that sponsors really "own" this page?

Agree on what would make a good Tribes light experience for users.
Agree on how to move from old orgs to Tribes light.
Agree on how to communicate this to sponsors.
Agree on how we will build towards this goal.
Agree on what to call this in terms of sales.
Agree on a timeline for this delivery.

### Current Behavior
No Tribes light

### Expected Behavior
Tribes light or some lower tier version.

### User Stories for Tribes Light

- [x] As a Gitcoin operator, we need a consistent way to represent organizations so that sponsors are not confused about how to use our community tools.
- [x] As a hackathon sponsor and tribe owner, I'd like to be able to customize my brand to represent my organization.
- [x] As a hackathon sponsor and tribe owner, I'd like to be able to communicate with my community publicly.
- [x] As a hackathon sponsor and tribe owner, I'd like to be able to chat with my tribe.
- [x] As a hackathon sponsor and tribe owner, I'd like to have basic follow functionality.
- [x] As a hackathon sponsor and tribe owner, I'd like to see who has worked with me/participated in my hackathons.
- [ ] [As a hackathon  sponsor and tribe owner, I'd like to see the my organization's kudos in the tribes light  view.](https://github.com/gitcoinco/web/issues/7092)
- [ ] housekeeping items

https://github.com/gitcoinco/web/issues/6974

### Data Requirements

- Happy customers using tribe light
- Happy customers using tribe light that want to upgrade to Tribes pro

### Additional Information
Please provide comments here team!
Related to #6811 https://github.com/gitcoinco/web/issues/6616

**Comment by PixelantDesign** [comment]
allow core team management.

**Comment by ceresstation** [comment]
This all seems directionally correct to me, some other features that we should really try to figure out are around organization level bounty / wallet management I know at one point we had tickets for shared management but I'm not sure where they went.

**Comment by frankchen07** [comment]
key difference here is managing the relationship is different from managing the hackathon

this ticket sets that in motion, and I think it comes first before my pitch about the "amazon x-ray rolodex" that follows someone around the gitcoin site

**Comment by thelostone-mc** [comment]
@ceresstation So bounty level + wallet mgmt is something I've got a few thoughts on how we should go about this !

@PixelantDesign  + @frankchen07 Could you guys rope me in on this conversation before making decisions on how + when

**Comment by PixelantDesign** [comment]
Step 1 Roll out old orgs site wide
Step 2 Remainiing enhancements

**Comment by PixelantDesign** [comment]
Closing  since Kevin put this in...
- Enables ANY profile to be a tribe
- makes tribes pages load in 0.3s instead of 2s
https://github.com/gitcoinco/web/pull/7080

**Comment by PixelantDesign** [comment]
reopen because hackathon customers need to be able to see their kudos
