### ISSUE TITLE
Add Images to Hack Registration Questions

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6818]
### What 

Add Images to Hack Registration Questions

- [ ] - Allow admins to add  the images in the admin panel
- [ ] -  Add selector to each question so the admins can associate one image to the question
- [ ] - The image associate with each question should be displayed at the top of the modal

### Why

If we add these images, then hackers will have a better experience (more delightful experience) as they are entering in their information.

<img width="1401" alt="Screen Shot 2020-06-09 at 8 06 27 PM" src="https://user-images.githubusercontent.com/238235/84280193-f3fec380-ab04-11ea-8350-6847c568e0ca.png">

**Comment by PixelantDesign** [comment]
@zoek1 could you link PR?

**Comment by zoek1** [comment]
https://github.com/gitcoinco/web/pull/6778
