### ISSUE TITLE
Add # of Bounties Completed Dynamic Counter

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#682]
Add # of bounties completed as a dynamic counter on the landing page  and maybe issue explorer.

![Screen Shot 2018-03-21 at 8.18.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f26b7191a370f113234f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae74a52ad1b3465e1742431.png)

**Comment by owocki** [comment]
good idea

**Comment by mdew192837** [comment]
Seems cool, is there already a variable that we have that keeps track of this? Or a column in a db row that states whether a bounty is completed? @owocki

**Comment by owocki** [comment]
yes the `idx_status` column of the bounty table is updated when a bounty is completed.  

if were gonna put this information on the landing page we'd probably want to create a seperate (performant) place to store the data instead of querying the bounties table every landing page view.

**Comment by kziemianek** [comment]
@owocki ready for this ?

**Comment by owocki** [comment]
yes!
