### ISSUE TITLE
TornadoCash didn't receive SNT tokens

### ISSUE THREAD

**Issue by rstormsf** [gitcoinco/web#6821]
![image](https://user-images.githubusercontent.com/9360827/84306332-2f52bf80-ab10-11ea-8824-e35a70f8b54f.png)

https://gitcoin.co/grants/198/tornadocash?tab=transactions

15 May 2020

3esmit
10,165.0000 SNT
(+535.0 SNT optional tip to Gitcoin)
10,165.0000 SNT

but there are no tokens in multisig: https://etherscan.io/address/0xDD4c48C0B24039969fC16D1cdF626eaB821d3384

also there are so many txs that don't have etherscan txs links.

**Comment by rstormsf** [comment]
Or maybe the website shouldn't have shown those txs?

**Comment by 3esmit** [comment]
This is related to #6663

I did broadcasted both the transactions, however the Gitcoin website had a fixed gas limit which caused the transaction to fail, as SNT (MiniMeToken) uses a higher gas cost to transfer, specially to accounts it never received before due initialization of storage on EVM.

The transaction that failed is `ethereum:tx-0xb9ad303f0a86a6783615f1d1e2d4e08d4a10568df63535695668097d8e5e3586`. 

I tried to manually change the gas on a retry of transaction through MetaMask, however MetaMask have a bug which prevented me from doing so. 
Also MetaMask does not allow me to access the data field of new transaction, so I couldn't craft the transaction manually. 
Also the Gitcoin:Grants contract is not verified on Etherscan, which would had enabled me to access manually the function in Etherscan Dapp interface.

I will try those 3 options again to see if any of them work now.

**Comment by 3esmit** [comment]
Metamask still didn't fixed the bug in the retry transaction... See the behavior here https://www.youtube.com/watch?v=AvV99ybSU7U&feature=youtu.be

**Comment by 3esmit** [comment]
MyCrypto.com does not recognize Metamask web3, but I managed to manually recreate the transaction using MyEtherWallet.com

The succeeding transaction is: `ethereum:tx-0x9e6a02768fd422e59ab63271c406e51ef960ab8504c426f1b8839db394e4c762`. Please, update it on the DB.

**Comment by owocki** [comment]
> Or maybe the website shouldn't have shown those txs?

Totally fair. I just put a PR in for this so well do better in round 6 https://github.com/gitcoinco/web/pull/6825
