### ISSUE TITLE
update the grants checkout email to be multi-grant checkout

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6822]
before: https://bits.owocki.com/bLujJ2Gy
after: https://bits.owocki.com/eDu1opL1

**Comment by sebastiantf** [comment]
Yeah I think I could

**Comment by sebastiantf** [comment]
@owocki I'm not sure I understand the requirements fully. Can you be a bit more descriptive, please?

Should I fully remove the `thank you email` and replace it with the `contribution success email`?

**Comment by owocki** [comment]
@sebastiantf thanks for asking.  thanks right!

**Comment by sebastiantf** [comment]
> Should I fully remove the `thank you email` and replace it with the `contribution success email`?

Forgive me for asking again. But is this correct?

**Comment by owocki** [comment]
> thanks right!

sorry i meant 'thats right'

> Forgive me for asking again. But is this correct?

yes thats right.
