### ISSUE TITLE
Batching Multi-Payout Transactions

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6826]
As a funder, I'd like to payout an arbitrary number of bounty hunters with one transaction. 

This allows me to consider many different types of bounties, including survey's like [this one](https://gitcoin.co/issue/gitcoinco/skunkworks/155/4169), without having to deal with a) high gas costs and b) taking an hour to payout builders.

**Comment by owocki** [comment]
maybe we could take the scopelift work on the bulk payouts that @apbendi did and transpose it to bounties afterwards :)

**Comment by owocki** [comment]
@vs77bb i do have a server side script i can do this for you in the meantime tho

**Comment by vs77bb** [comment]
That’d be awesome, yes.. maybe a good next todo after grants wraps up if it makes sense to continue working together :)
