### ISSUE TITLE
Organize Townsquare By Top Posts

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6828]
As an information consuming user, I want a town square which has curated, relevant, and useful content that rises to the top and a default view which doesn't show me *any* content which is low-quality. Curation matters! 

Taking inspiration [from this post](https://twitter.com/mikaelcho/status/1270743622619717632) by @ceresstation in Slack, organize our Town Square by the top 10 posts of the week. 

Reddit / Dev / Twitter all organize their feeds in this manner. 

One step further -- we could consider *only* showing the top 10 posts, with the 'see more' option only if you want to see it later. 

Reduces 'infinite scrolling', which can [be considered a dark pattern.](https://medium.com/simple-human/7-reasons-why-infinite-scrolling-is-probably-a-bad-idea-a0139e13c96b) 

Design wise, I wonder if our Townsquare would be better as a forum (where we encourage people share longer form ideas), rather than posts (some of which are quite low value ATM).

**Comment by PixelantDesign** [comment]
Recall this from brainstorm too. @vs77bb what are you thinking on the logic to determine the top 10 posts?

**Comment by fluffays** [comment]
@PixelantDesign & @vs77bb , regarding ranking mechanism for posts you could factor in these indicators:

- views (not 100% accurate, but hard to ignore)
- comments & likes
- tips
- author

For "author", I'd also suggest adding a visual cue to signal messages from verified & popular authors:
- Gitcoin team
- Tribe
- members with high rank and/or verified status

Also adding some Townsquare content type suggestions:
- weekly surveys (general topics/ news-based/ random fun) - some random examples:
    - favorite kudos
    - favorite hackathon 
    - favorite tribe
    - hack ideas
    - best thing on gitcoin
    - best programming language/ framework
    - best superhero ever
    - favorite game ever
    - best music for coding
    - how would you save the world (serious/ funny)
    - Twitter flags: cool/ not cool
    - freedom of speech - untouchable or should be paired with responsibility
    - the biggest challenge as an open source coder is…
- Kernel updates - cool quotes from workshops, profile mentors, profile Kernel fellows
- share updates by other Tribes
- share workshop videos
- promote Gitcoin blog posts
- announcements (hacks, grants, events, releases)
- push feedback surveys (when they’re sent out)
- share blogposts published by Tribes/ sponsors
- share new quests

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/pull/5863
