### ISSUE TITLE
A Submissions View: Gitcoin Judging / Payout

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6829]
As a funder / hackathon sponsor, I want a simple flow which includes ways to a) see all of my submitted hackathon projects and b) pay out / take action on these, in bulk. 

This would replace the need for each sponsor (and us) to create spreadsheets [like this one.](https://docs.google.com/spreadsheets/d/1Q_4nupKLU1SUMqLNo5x-9-TtZpMPJx8PNEHW84DH8hg/edit#gid=1891116124)

And it would feed information into a) hackathon wrap up posts like in #6769 and b) maybe other views! 

*Open to UX ideas to solve this user story* CC @willsputra 🤔

**Comment by willsputra** [comment]
feels like this would somehow tie-in with the org/shared management and funder dashboard idea...

**Comment by vs77bb** [comment]
The dashboard seems to also be merging with the Tribes v2 view ideas.. I think it’s best if we can send people to one place with all of these things
