### ISSUE TITLE
Error On Grant Creation

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6840]
Sachin's screenshots of errors submitting from: https://gitcoin.co/grants/new. Here's what the app returns. 

![image](https://user-images.githubusercontent.com/23297747/84501174-081cff00-ac84-11ea-8549-4ccc52f3fb3e.png)

![image](https://user-images.githubusercontent.com/23297747/84501186-0d7a4980-ac84-11ea-997e-dcd0ccafb400.png)

**Comment by owocki** [comment]
@vs77bb can you fill out the bug report template? things like browser, web3 browser state, etc are important

**Comment by thesachinmittal** [comment]
Sure @owocki 🙂, 

**Here are the Desktop stats:**

- OS: MacOS mojave
- Browser: Chrome
- Browser Version: 83.04

**Comment by owocki** [comment]
exception stack trace https://bits.owocki.com/v1uemXnv
