### ISSUE TITLE
Other Things Included In MiniCLR (Bounties, Hack Projects, Other Things)?

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6842]
As a builder on Gitcoin, I want my work on the platform to be represented in MiniCLR. 

Right now, the MiniCLR takes into account mostly *posts* on the town square / the tips that come on top of that. How could we build it in a way that other things are included in the MiniCLR as well? What would encourage more deeply researched content pieces / even stronger conversation on the site/

**Comment by Solexplorer** [comment]
Actually, in the first month, the miniclr was designed to include every tip in the platform but then we decided to only include tips coming from the town square. The reason for that is simply because if someone got paid for a bounty he did not "really help the community". Tho I agree on finding a way to encourage stronger conversations

**Comment by ivanmolto** [comment]
I fully agree that is necessary to build the MiniCLR in a way that other things are included and tipped.
In my opinion, this will help to make a wider distribution of the MiniCLR and so add new community members to get a share of it.

I loved the mid-hack pitch day for some hackathons with tips. 
Maybe a solution would be something similar with mini tips for the MiniCLR: demos, videos of the last hacks, and research papers to be tipped.

On the other hand, maybe with a sponsor/auction for the MiniCLR other actions could be tipped: as sharing the content of the sponsor through Twitter, product sign-ups and other mini actions.

It’s key that if there is a wider audience in the MiniCLR, the MiniCLR distribution needs to be larger to get people engaged and rewarded. And so maybe a sponsor makes sense.
