### ISSUE TITLE
as a user, i want to ahve an 'in alpha' badge on alpha tools, so i can know which tools aren't yet GA

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#685]
we should have some sort of “in alpha” badge on alpha tools like the leaderboard, profiles, and offchain explorer.. that way we don’t lose credibility when something is not quite 100% on those pages

https://gitcoin.co/tools

**Comment by sethmcleod** [comment]
Here is an orange tinted version. In my opinion the pink version matches our theme better, but red tones are usually used for errors whereas orange is used for warnings.

![image](https://user-images.githubusercontent.com/7340187/37788279-640f9a6c-2dd7-11e8-9231-2ec4444ea0a6.png)

**Comment by mkosowsk** [comment]
@sethmcleod Looks great to me! I like the orange for the reason you mentioned but I do not have a designer's eye 🤔

**Comment by e-n-l** [comment]
How about an icon, something less language dependent? 

I'm thinking a hex shape, like the stickers, with a Greek Alpha character on it.

**Comment by sethmcleod** [comment]
In my opinion text makes more sense here. Icons are great for concepts that most people are familiar with, like a heart for _like_ or hamburger for _menu_, but this concept isn't something you see often and I'm not sure most people would even relate this to the Greek character.

**Comment by owocki** [comment]
i think text is fine for the tools page.  the users should maybe know already that the tools on the /tools page are in alpha bc they are listed under a heading that says 'tools in alpha'.

i should have been more clear when writing up this ticket.. i was looking for a badge i could put on each of these pages

https://gitcoin.co/profile/
https://gitcoin.co/faucet
https://gitcoin.co/offchain
https://gitcoin.co/leaderboard

that would signify that these tools are in alpha.  i feel like a user could find themselves on any of the above pages and not know they are alpha (whereas on /tools its a little more clear bc of the header)

**Comment by sethmcleod** [comment]
Ahh that makes sense. In that case, my first thought would be to have a similar tag that fixes to the bottom left or right corner of the page as the user scrolls. When hovered over, you could add a tooltip that explains a bit more.

**Comment by mbeacom** [comment]
How about something like the "fork me on github" ribbon..?
https://github.com/simonwhitaker/github-fork-ribbon-css

**Comment by sethmcleod** [comment]
Yeah! I was thinking along the same lines, though I'm turned off by how much screen space those ribbons take up.

**Comment by mbeacom** [comment]
@sethmcleod Yeah... I just tried this out and it looks kind of meh.

**Comment by owocki** [comment]
![under_construction_graphic](https://user-images.githubusercontent.com/513929/37803285-8d2e1146-2df3-11e8-94fe-f69e5981b7e9.gif)
![giphy](https://user-images.githubusercontent.com/513929/37803287-8d42116e-2df3-11e8-891d-4cef6d9f2562.gif)
![200](https://user-images.githubusercontent.com/513929/37803288-8d52fe5c-2df3-11e8-9898-19013f225c2e.gif)

**Comment by mkosowsk** [comment]
Web 3.0 starting to look a lot like Web 1.0... time is a flat circle? 🤔

**Comment by mbeacom** [comment]
<img width="1022" alt="screenshot 2018-03-22 19 12 12" src="https://user-images.githubusercontent.com/7315957/37803408-f33710b2-2e04-11e8-8422-21e5f93b550a.png">

**Comment by mbeacom** [comment]
@sethmcleod Yeah, I'm not a big fan either. 😂

**Comment by sethmcleod** [comment]
I think that's definitely a step in the right direct @mbeacom I just wish they wouldn't have gone with a 45 degree angle 🙄

**Comment by mkosowsk** [comment]
Honestly that looks like an arm band of mourning or protest to me...

**Comment by mbeacom** [comment]
I feel like I need to don a band of mourning for github fork ribbon. 😢

**Comment by e-n-l** [comment]
![image](https://user-images.githubusercontent.com/487308/37804162-50f2196e-2df0-11e8-8715-ca7a1cc536f6.png)

**Comment by mkosowsk** [comment]
![strong_branding 2](https://user-images.githubusercontent.com/7970539/37804485-e1d28b2a-2e0a-11e8-94a1-315d21222d89.png)

Think this might be the one guys... could be a real game changer. Thoughts? 🤔

**Comment by e-n-l** [comment]
Maybe something along the top bar instead?

![image](https://user-images.githubusercontent.com/487308/37804959-632639fe-2df4-11e8-8577-5c30dfe5ed12.png)

**Comment by owocki** [comment]
sorry guys, i was kidding when i suggested 'under construction' themed images

**Comment by jakerockland** [comment]
Coming at this from another angle, could have a modified "alpha" logo for pages that are in alpha or reflect alpha parts of the project.

I can see not wanting to due this due to it introducing some potential for branding inconsistency, but I think there are ways to do it that are subtle enough that mitigate that and it is something that seems to be consistently present across all pages.

Perhaps something like this?

![sketch](https://user-images.githubusercontent.com/8602661/37805661-da151216-2df8-11e8-9ef2-1883da00a803.png)

**Comment by e-n-l** [comment]
:shrug: TBH, I'd already made up that hex icon before your 90s flashback... 

I was just playing with ideas that could visually convey "alpha." (those are actually GitCoin colors)

**Comment by PixelantDesign** [comment]
Lots of fun ideas here! From a brand perspective, I recommend that we keep the label a healthy distance away from the Gitcoin logo to 1) avoid the confusion that the entire Gitcoin product is in the alpha stage and 2) avoid confusion that label is at all part of the logo.

**Comment by owocki** [comment]
i wonder if it'd make sense for each tool to have it's own 'alpha' below under it's 'logo' (or subheader, if we dont want to have the overhead of making a logo for each tool)

**Comment by willsputra** [comment]
@owocki it might work if each tool's 'logo'/'title' position is consistent 😄

![685_leaderboard](https://user-images.githubusercontent.com/19514207/37920130-a05bcba6-3158-11e8-9323-2899c65f15e6.png)
![685_bountiesuniverse](https://user-images.githubusercontent.com/19514207/37920178-bef7d6f4-3158-11e8-84af-ad352c09e8ec.png)

**Comment by owocki** [comment]
i like what you did there.. @PixelantDesign what do you think?

**Comment by owocki** [comment]
81e04b710f8ff04ac1cdbb1d9145f67db8ba94f5 commits a simialr badge to what @willsputra suggested.  check it out => https://gitcoin.co/tools (and then click to each alpha tool)

**Comment by PixelantDesign** [comment]
@willsputra I think the concept works if the headers are consistent across the board. The tags are little hard to read, could you try darkening the type color or go black type on yellow?

**Comment by willsputra** [comment]
@PixelantDesign black type looks good too!

![685_bountiesuniverse](https://user-images.githubusercontent.com/19514207/37946117-58716bb2-31b6-11e8-92f0-5b05539da17d.png)
![685_leaderboard](https://user-images.githubusercontent.com/19514207/37946118-589d77de-31b6-11e8-8b53-397c23817e87.png)

**Comment by PixelantDesign** [comment]
The Alpha tags are much easier to read @willsputra. Will you be helping us implement these changes (Headers and Alpha badge)?

**Comment by willsputra** [comment]
@PixelantDesign I'm still new to this whole committing code to open source so it might take some time. If someone else would like to help implement it, please go ahead. 🙂

**Comment by mkosowsk** [comment]
@willsputra I've got some cycles so am ready to help if you want a hand making a Pull Request to Gitcoin :)

Main steps:

0. Fork Gitcoin to your own repo
1. Make your changes and commit them there
2. Create a pull request from your fork via https://help.github.com/articles/creating-a-pull-request-from-a-fork/
3. Address feedback as needed 👍 

I defer to the excellent @thelostone-mc for guidance for comments and corrections. Good luck!

**Comment by willsputra** [comment]
@mkosowsk wow thanks a lot! I'll give it a try in this couple of days.

**Comment by mkosowsk** [comment]
@willsputra let me know if you need a hand :) Pretty confusing to start but very powerful once you get the hang of 👍🏻

**Comment by willsputra** [comment]
@PixelantDesign I'm seeing 3 different font styles currently for the headers:
https://gitcoin.co/leaderboard (Muli)
https://gitcoin.co/gas (Futura)
https://gitcoin.co/universe (Futura - bolder)

Should we make these header fonts consistent? If so, which font should we use?

**Comment by mkosowsk** [comment]
@willsputra I believe Muli is the standard now but defer to @PixelantDesign 👍

**Comment by thelostone-mc** [comment]
@willsputra Ah we've picked the Muli family  and we are migrating it slowly as the pages are getting updates 

I believe we will still keep Futura but i doubt they pages where the tag will be used wont be one of those ! @PixelantDesign can answer this better 

For the badges stick to Muli !!

Also since you are new to open source , me and @mkosowsk are at your service. Reach out to us on slack any time :)

**Comment by willsputra** [comment]
@mkosowsk @thelostone-mc thanks! I've added the badges in Muli without making changes to the header fonts. is this alright? screenshots:

![alphabadge](https://user-images.githubusercontent.com/19514207/38099862-43b43070-33ae-11e8-9764-a7250fd60a01.jpg)

**Comment by owocki** [comment]
i like this

**Comment by mkosowsk** [comment]
@willsputra looking sharp! 👍

**Comment by thelostone-mc** [comment]
@willsputra looking solid \m/

**Comment by thelostone-mc** [comment]
Oh you might wanna check up the alpha tag on the top earners page - mobile , seems out of place

**Comment by willsputra** [comment]
thanks all for the feedback! lemme know if this one's alright :)
![alphabadge](https://user-images.githubusercontent.com/19514207/38202017-ddf71d34-36cc-11e8-97b5-e4e5b8accd82.jpg)

**Comment by willsputra** [comment]
oops so sorry for the many commits.

**Comment by owocki** [comment]
follow up ticket => https://github.com/gitcoinco/web/issues/792
