### ISSUE TITLE
Can't get ENS Subdomains 500 code

### ISSUE THREAD

**Issue by aturX** [gitcoinco/web#6850]
**Describe the bug**

when I want to get a ENS Subdomains I found a bug . I can not get success . I got a Response of 500 code 

**To Reproduce**

**Expected behavior**

visit it : [ENS](https://gitcoin.co/ens#)
**Screenshots**

![](https://ftp.bmp.ovh/imgs/2020/06/0660c55e2e5ced76.png)

![](https://ftp.bmp.ovh/imgs/2020/06/88e5d72ab1ad2e55.png)
**Desktop (please complete the following information):**

- OS:
- Browser:   web of Chrome
- Browser Version: 

**Smartphone (please complete the following information):**

- Device: 
- OS:   Mac OS
- Browser:  Chrome 
- Version:

**Additional context**

**Comment by aturX** [comment]
![](https://ftp.bmp.ovh/imgs/2020/06/52d2aace8d9579d5.png)

**Comment by octavioamu** [comment]
@aturX Thanks for the report. 
Can you show me the last part on that screen? Seems some data is missing on the request.

**Comment by aturX** [comment]
https://github.com/gitcoinco/web/issues/6850#issuecomment-643622311  

I can see it

**Comment by aturX** [comment]
API show 500  for this  :    https://gitcoin.cn/ens  @octavioamu

**Comment by owocki** [comment]
we should just remove the ens functionality. its horribly out of date. when we built it it was novel, but nowadays there is software that can manage subdomain delegatoin out of the box.

**Comment by aturX** [comment]
The image data source may not be loaded due to network reasons  @octavioamu    

<img width="819" alt="2" src="https://user-images.githubusercontent.com/34887700/84847125-ee642900-b082-11ea-8dda-9f6ce3ab9b13.PNG">

<img width="943" alt="1" src="https://user-images.githubusercontent.com/34887700/84847133-f3c17380-b082-11ea-9627-9cc3ca2777bf.PNG">


just response a HTML page  but no reload.
