### ISSUE TITLE
Gitcoin.co marketing site fixes

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6853]
**- change color of looking for devs from green to yellow ##FFCE08**
<img width="1724" alt="Screen Shot 2020-06-02 at 12 25 24 PM" src="https://user-images.githubusercontent.com/238235/84601927-c2159600-ae51-11ea-951f-e2da7c5a3bc9.png">

**change get started link destination** from townsquare to tribes page at this url
https://gitcoin.co/tribes/explore
<img width="1716" alt="Screen Shot 2020-06-02 at 12 26 39 PM" src="https://user-images.githubusercontent.com/238235/84601958-05700480-ae52-11ea-852b-4d689ffb4d4f.png">

**Comment by qasimy123** [comment]
@PixelantDesign I would like to help with this.

**Comment by PixelantDesign** [comment]
great! let me know when pr is ready! happy to tip @qasimy123
