### ISSUE TITLE
'Invite To Bounty' Issues

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6861]
Shows as 'undefined' in the preview -- also doesn't update with contributors I've worked with recently... these folks are all inactive for the last 6 months.  

To reproduce: http://gitcoin.co/new
On Chrome, Version 83.0.4103.97

![image](https://user-images.githubusercontent.com/23297747/84658547-0c475780-aee4-11ea-8336-9a485520ecdf.png)

**Comment by owocki** [comment]
@zoek1 @iamonuwa @sebastiantf anyone want? :P

**Comment by sebastiantf** [comment]
@owocki I could take a look.

**Comment by sebastiantf** [comment]
I have a PR up for this @owocki @vs77bb: #6886
