### ISSUE TITLE
Task Completion Widget

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6862]
### User Story

As an operator of Gitcoin, I'd like a task completion widget that I can apply across many tasks in our system to help guide users and act as reminders as well as a helper in order to accomplish tasks.

As a developer  on Gitcoin, I'd like to be reminded and guided on the things that I need to do in the system so that I feel a sense of accomplishment and the system can learn about me as a unique individual.

### Why Is this Needed

Read about [endowed progress effect here](https://medium.com/@davidteodorescu/design-perfect-ux-tasks-the-endowed-progress-effect-7461ca20076c) [and here](https://uxplanet.org/the-magic-behind-good-ux-2-e89809c0a63e)

*Summary*: Build a task completion widget that can be applied to many tasks on the site.

Examples:

Onboarding
Hackathon Progress
Profile Completion
KYC Setup

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
No widget/reminder/guide

### Expected Behavior
Built widget

### Definition of Done

- [ ] Get feedback on the tech approach with Gitcoin core engineering team
- [ ] Build the backend of the widget
- [ ] Track and display when a user completes a step/task and allow the user to move forward  to the next step.
- [ ] Start the progress indicator at step 2
- [ ] Track and display when a user moves backward, cancels/undo a task.
- [ ] Consider what happens when a user clicks the back button on the browser
- [ ] Add analytics/tracking to each step - possible in Admin
- [ ] Implement the front end in the Gitcoin hackathon experience 
- [ ] The widget should collapse/expand
- [ ] post a video on the pr
- [ ] Review with product team

**In the context of hackathon completion**

Display this on the  upper right of the screen ( should be the same place on every screen)

- [ ] give a check for completing registration quesioins
- [ ] Introduce yourself in townsquare - display a check if registration question was completed
- [ ] When user click start work/joins a project - display a check
- [ ] If  user attends a workshop (add calendar invite) - provide a check icon 
- [ ] if  user uploads a demo link at submit work step
- [ ] If  user submits work   - submit url as a link

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information

How do we improve:
1) time to value, making it easy for someone to jump into a hackathon

<img width="925" alt="Screen Shot 2020-08-10 at 10 39 44 PM" src="https://user-images.githubusercontent.com/238235/89854765-bf3dd580-db62-11ea-94b4-b6b3fdf090ab.png">

**Comment by fluffays** [comment]
Adding some ideas for Hackathon Townsquare content, which might contribute to both onboarding & general experience throughout the event:

- welcome message (i.e. “welcome to the hackathon! what projects are you keen to work on?)
- share hackathon launch blog post
- connections thread - i.e. “looking for a sidekick for a specific project? share the project and the skills you’re looking for here”
- time counter updates - ex. ”1 week left - get your engines fired up and submit, submit, submit!”)
- invite organizing Tribes to post their own updates

**Comment by willsputra** [comment]
> Have a profile completion component

With the integration of the skills screen (https://github.com/gitcoinco/web/issues/6885), would we have all we need from hackathon participants? What else do we need them to complete to participate in hackathons?

> Add places in the app to get into hackathons

One idea is to put hackathons on town square

![townsquare](https://user-images.githubusercontent.com/19514207/85413897-ff8ac980-b59d-11ea-86ce-5aaa5f0f9626.jpg)

**Comment by willsputra** [comment]
We can also make use of the right rail on the Hackathon Townsquare to guide people on next steps. Thoughts @PixelantDesign ?
![hackathon townsquare](https://user-images.githubusercontent.com/19514207/85587581-7c887280-b674-11ea-9fe5-4490c4da6118.jpg)

**Comment by PixelantDesign** [comment]
Cool!

I played around with somethiing like thiis @willsputra 
<img width="706" alt="Screen Shot 2020-06-24 at 1 54 54 PM" src="https://user-images.githubusercontent.com/238235/85727600-27c11800-b6c5-11ea-944a-e635d5dc8332.png">

<img width="1586" alt="Screen Shot 2020-06-24 at 1 31 54 PM" src="https://user-images.githubusercontent.com/238235/85727649-34457080-b6c5-11ea-8110-e29a49b114d4.png">

This is another thing that could help

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/6870
