### ISSUE TITLE
Removing grant from cart resets all tokens to ETH

### ISSUE THREAD

**Issue by dmihal** [gitcoinco/web#6867]
**To Reproduce**
1. Add multiple grants to cart
2. Enter donations in Dai or other token
3. Click garbage can to remove a grant
4. All tokens are reset to ETH

**Comment by owocki** [comment]
oh snap!  

@apbendi @mds1 u want ?

**Comment by mds1** [comment]
So I think this is just a visual issue with what the token selection dropdown is displaying, though I'm not yet sure why

@dmihal If you go to local storage > `grants_cart`, can you confirm that the `grant_donation_currency` field is still what you'd expect it to be (e.g. DAI)?

**Comment by dmihal** [comment]
@mds1 Yes this appears to be just a visual issue. The total at the bottom of the page still shows the total in Dai.

If I want to actually send ETH, I have to change ETH -> Dai -> ETH

**Comment by mds1** [comment]
Thanks! This should be resolved once #6881 is merged
