### ISSUE TITLE
Protect Your Privacy Hackathon Kudos

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#6869]
### User Story

Protect Your Privacy Hackathon Kudos Tracker

### Drafts

- [X] pyp general - READY for minting

<img width="80" alt="Screen Shot 2020-06-15 at 11 19 06" src="https://user-images.githubusercontent.com/7516920/84692084-2429d600-aefa-11ea-94f9-1c62fd9b7911.png">

- [X] pyp winner - READY for minting

<img width="80" alt="Screen Shot 2020-06-15 at 11 19 13" src="https://user-images.githubusercontent.com/7516920/84692089-2724c680-aefa-11ea-9c9c-7ce406a98672.png">

- [X] eec - READY for minting

<img width="80" alt="Screen Shot 2020-06-16 at 14 54 29" src="https://user-images.githubusercontent.com/7516920/84832029-52ceac00-afe1-11ea-8f15-66f98cf393c6.png">

- [X] makerdao - READY for minting

<img width="80" alt="Screen Shot 2020-06-12 at 12 15 58" src="https://user-images.githubusercontent.com/7516920/84692161-4b80a300-aefa-11ea-84d7-0b444b503161.png">

- [X] raiden - READY for minting

<img width="80" alt="Screen Shot 2020-06-15 at 11 24 34" src="https://user-images.githubusercontent.com/7516920/84692516-d792ca80-aefa-11ea-9469-7721f9006615.png">

- [X] status/keycard - READY for minting

<img width="80" alt="Screen Shot 2020-06-16 at 14 55 54" src="https://user-images.githubusercontent.com/7516920/84832233-bbb62400-afe1-11ea-9145-92cc0d5c8314.png">

- [X] nucypher - READY for minting

<img width="80" alt="Screen Shot 2020-06-15 at 11 24 29" src="https://user-images.githubusercontent.com/7516920/84692535-e0839c00-aefa-11ea-9f8d-1aa398981782.png">

- [X] ocean protocol - READY for minting

<img width="80" alt="Screen Shot 2020-06-12 at 12 16 13" src="https://user-images.githubusercontent.com/7516920/84691676-66064c80-aef9-11ea-997d-314805bff8d2.png">

- [X] keep - READY for minting

<img width="80" alt="Screen Shot 2020-06-16 at 14 55 48" src="https://user-images.githubusercontent.com/7516920/84832255-c375c880-afe1-11ea-8bb5-4e46805c92d8.png">

- [X] near - READY for minting

<img width="80" alt="Screen Shot 2020-06-12 at 12 15 29" src="https://user-images.githubusercontent.com/7516920/84691843-aebe0580-aef9-11ea-8c8c-4de1375c4a89.png">

### Finalized & Created & Links Disseminated

- [x] pyp general
- [x] pyp winner
- [x] makerdao
- [x] raiden 
- [x] status/keycard
- [x] nucypher
- [x] ocean protocol
- [x] eec
- [x] keep
- [x] near

**Comment by MladenPetronijevic** [comment]
![2550x2550_NoBg (1)](https://user-images.githubusercontent.com/41165756/84701402-308f4c80-af55-11ea-9415-92e7982d7f45.png)
ECC version 2

**Comment by owocki** [comment]
coming along nicely!

**Comment by MladenPetronijevic** [comment]
![2550x2550_NoBg (1)](https://user-images.githubusercontent.com/41165756/84745161-77605f00-afb4-11ea-9eee-bf9154ce9ec2.png)
@frankchen07 i've fixed the ones with feedback

**Comment by frankchen07** [comment]
done
