### ISSUE TITLE
after sending tip, blue alert that should have had a success message in it said 'undefined'

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#687]
i suspect it was being generated here https://github.com/gitcoinco/web/blob/master/app/assets/yge/youvegoteth/send.js#L243

http://bits.owocki.com/3L2v393t2p1f/Screen%20Shot%202018-03-22%20at%201.00.45%20PM.png

**Comment by kziemianek** [comment]
I'll take a look at it.

**Comment by owocki** [comment]
yay it works!  thanks @kziemianek 

just tested by sending you a tip.  meta! http://bits.owocki.com/1g1N473F212g/Screen%20Shot%202018-03-26%20at%2012.36.45%20PM.png
