### ISSUE TITLE
Allow shopping cart users to click the name of a grant to open a new tab with the Grant description

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#6871]
### User Story

As a grant user that has a shopping cart, I want to be able to click to the grants in my cart so that i can see their description and if they made any updates.

### Why Is this Needed

Things change, I want to be able to stay updated on the gran'ts progress

### Description

Feature

### Current Behavior
I can't click the name of a grant

### Expected Behavior
I can click the name of a grant and IN A NEW TAB I get to see the description of the grant

**Comment by owocki** [comment]
@zoek1 or @apbendi want this?

**Comment by zoek1** [comment]
Sure @owocki

**Comment by owocki** [comment]
was coding something else and ended up hacking this up ddd38626e3b4053dd8659aa674b2d108543486fd

**Comment by GriffGreen** [comment]
Nice :-D
