### ISSUE TITLE
SHOWCASE GRANTS I DONATED TO IN RD 6

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6873]
As a Grant Donor, it'd be freaking awesome if this page included info on all of the grants that I funded so I can screenshot it and explain to people why I donated to these projects.

It'd be even more awesome if someone could take *my cart* and make it the starting point to their own cart!!!

![image](https://user-images.githubusercontent.com/23297747/84699266-3bc78580-af1f-11ea-90a5-c0b53f8b54a6.png)

**Comment by owocki** [comment]
related: 
https://github.com/gitcoinco/web/issues/6643
