### ISSUE TITLE
Gitcoin Grant activity update should confirm before posting when you press enter

### ISSUE THREAD

**Issue by pcowgill** [gitcoinco/web#6875]
### User Story

As a user with an active Gitcoin Grant for my project, I want for activity updates to be confirmed before posting when you press enter.

### Why Is this Needed

*Summary*: I keep accidentally sending updates before they're done.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Activity updates are sent immediately when you press enter.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Activity updates are sent immediately only when I click send manually. After I press enter, there should be a confirmation modal before it is sent.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Anything that makes it harder to accidentally send activity updates for Gitcoin Grants.

### Data Requirements
Fewer updates posted and then deleted immediately.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
n/a

**Comment by owocki** [comment]
ooh good idea!

**Comment by pcowgill** [comment]
And it's possible I was pressing shift + enter rather than enter. I'm not sure. In some apps shift + enter is a send and enter is newline, and in other apps it's vice versa

**Comment by owocki** [comment]
@PixelantDesign what do you think here?
