### ISSUE TITLE
metamask popup when you come to the site is back

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6876]
https://twitter.com/LefterisJP/status/1272636875317149704

For issues. The metamask popup when visiting the website seems to be back again. And this time 2 popups even. Some kind of regression must have happened.

Expected Result: No metamask popup unless u ask for it

**Comment by nightwolf3** [comment]
I was going to post the same issue, even if I disconnect or not, metamask pops up twice to connect.
And the address shows up twice in the metamask dropdown; I think it's present to all users when I asked on slack. I thought it was some sort of feature at first
![Capture](https://user-images.githubusercontent.com/16582619/85231280-75582f00-b3fe-11ea-91ec-30c139ceb3dd.PNG)

**Comment by octavioamu** [comment]
We just deployed a fix for the Metamask popup, but depending on your local state you will need to hard refresh the page or just connect disconnect Metamask for the last time, after that the popup should be gone 🙌

**Comment by nightwolf3** [comment]
> 
> 
> We just deployed a fix for the Metamask popup, but depending on your local state you will need to hard refresh the page or just connect disconnect Metamask for the last time, after that the popup should be gone 🙌

hey, the popup is gone but why are there two instances of the same address showing up any clue?
thank you
