### ISSUE TITLE
Bounty Loading Screen Missing

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#6879]
When posting a bounty, the loading screen / indication of tx pending outside metamask seems to be missing: https://gyazo.com/2de287a25b86d3277339551b36d22d7c

OS: Windows 10
Browser: Chrome, latest
Screen Size: 15 inch

**Comment by developerfred** [comment]
@ceresstation  Believe it is not showing up because we recently implemented Web3Modal. I Will check this.
