### ISSUE TITLE
Grants Tweaks

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6883]
<img width="1792" alt="Screen Shot 2020-06-15 at 11 10 19 PM" src="https://user-images.githubusercontent.com/238235/84730450-33de0480-af64-11ea-9603-a2fd655c5ec2.png">

When I completed funding of a grant, this screen should have a button for me to fund another grant. I'm left here after tweeting about the grant.

-----------

Needs some clean up so the message doesn't seem scary/warning like.
<img width="1792" alt="Screen Shot 2020-06-15 at 11 00 48 PM" src="https://user-images.githubusercontent.com/238235/84730051-33913980-af63-11ea-8ea1-52eb9b99a68b.png">

<img width="414" alt="Screen Shot 2020-06-16 at 12 24 31 AM" src="https://user-images.githubusercontent.com/238235/84731728-cf24a900-af67-11ea-87fa-5694acda08a1.png">

-----------

Phone number verification screen:
When I entered my phone number, it didn't recognize that it's a U.S.A number and the flag stayed on another country. Number also messed up when I changed the flag to U.S.A

-----------

<img width="567" alt="Screen Shot 2020-06-15 at 11 53 07 PM" src="https://user-images.githubusercontent.com/238235/84730136-663b3200-af63-11ea-90be-491640e493ae.png">
Change font color to Gitcoiin green #25E899 to highlight the amount this round.

**Comment by PixelantDesign** [comment]
@developerfred ?

**Comment by developerfred** [comment]
@PixelantDesign added to my to-do list for today.

**Comment by developerfred** [comment]
Status
- [x] Change font color to Gitcoiin green #25E899 to highlight the amount this round.
- [x] When I completed funding of a grant, this screen should have a button for me to fund another grant. I'm left here after tweeting about the grant.
- [ ] Phone Number Modal
- [ ] Phone number verification screen:

**Comment by PixelantDesign** [comment]
@owocki thoughts on above?

**Comment by owocki** [comment]
👍

**Comment by PixelantDesign** [comment]
Thank you @developerfred!
