### ISSUE TITLE
Integrate Skills Screen in Hackathon Registration Flow

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6885]
### Who
If we updated the skills screen, then we'd have a better understanding of who our hackers were, and be able to use this to power the cerebro.

### What 

![Frame 9](https://user-images.githubusercontent.com/238235/84732223-19f2f080-af69-11ea-9a18-468d91e7fd3f.png)

Take this screen and make it part of a seamless hackathon onboardding/registration flow.

**Comment by willsputra** [comment]
hackathon onboarding flow with skills @PixelantDesign 
![1](https://user-images.githubusercontent.com/19514207/85290415-8c188780-b4cb-11ea-86cc-b1c1537868b7.png)
