### ISSUE TITLE
Contributions to a grant don't show up at all.

### ISSUE THREAD

**Issue by moshemalawach** [gitcoinco/web#6887]
**Describe the bug**
Example tx: https://etherscan.io/tx/0x0d40f7d70891d1a134607335acacbaeb31471cf36f1da696daba68a568fbaaf6

Someone funded our grant (https://gitcoin.co/grants/461/alephim-decentralized-open-source-cloud-platform) and it didn't appear at all.

**To Reproduce**
Not sure, contribute to a grant?

**Expected behavior**
It should appear in the grant page and use profile

**Comment by moshemalawach** [comment]
Using firefox on linux with a ledger connected to metamask apparently?

**Comment by owocki** [comment]
hmmm without knowing their setup, it may be hard to reproduce.. 

i knwo that sometimes people send random tokens to grantees... but this looks like a multisend like on our checkout page

**Comment by moshemalawach** [comment]
Yeah it was from your checkout page. Setup: Linux with ledger on firefox metamask.

**Comment by owocki** [comment]
got it; do you know the username of the contributor? ill backfill the contrib into the DB.

and make a note to test on linux.  you dont happen to know the flavor of linux do you?
