### ISSUE TITLE
Make a currency dropdown that changes all the currencies in the cart to the same currency

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#6891]
### User Story

# As a shitcoin maximalist, I want to change all my grants in my shopping cart to my fave shitcoin so that I don't have to go 1 by 1 to change the coin.

### Why Is this Needed

Lot's of people will be donating PAN this round, as there is extra matching for it... and there are likely others that would donate more of the coin they have a lot of... if that was easy, then i bet people would donate more

### Description

*Type*: Feature

### Current Behavior
To make many donations, all of the same token, you have to go 1 by 1 to change the currencies

### Expected Behavior
Pick a default currency and apply it to all... When that default currency is not accepted by a grant, be aware of that and don't change it for that grant

^^^ This is the big trick here, some grants only accept ETH or DAI or whatever... so we have to figure out a nice solution for that common edge case.

**Comment by mds1** [comment]
Related to #6890. These two should probably be tackled together because of the edge case mentioned:

> When that default currency is not accepted by a grant, be aware of that and don't change it for that grant

For that case, we should fallback to ETH since that is the only currency accepted by all grants

**Comment by owocki** [comment]
i think #6890 is the way to go probably
