### ISSUE TITLE
cannot contribute to grant

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6897]
@zherring cannot contribute to this grant

https://gitcoin.co/grants/819/dapptivism

MM / Firefox 77.0.1 (64-bit)

<img width="873" alt="Screen Shot 2020-06-16 at 2 49 29 PM" src="https://user-images.githubusercontent.com/513929/84826943-f4a1c900-afe0-11ea-9043-fca6459cae50.png">

**Comment by owocki** [comment]
<img width="873" alt="Screen Shot 2020-06-16 at 2 49 29 PM" src="https://user-images.githubusercontent.com/513929/84827008-11d69780-afe1-11ea-9119-22f83b4a027a.png">

**Comment by atfornes** [comment]
![Screenshot_20200617_122619](https://user-images.githubusercontent.com/7475584/84888075-05ad1180-b097-11ea-9320-6ae11e48fdd2.png)
It seems to be because the interface only allows integer values

**Comment by mds1** [comment]
@atfornes @zherring What happens if you try to check out, is there an error message?

It seems only Firefox has the restriction of warning you about decimal values—Chrome and Brave don't—so I think checkout may succeed anyway

**Comment by atfornes** [comment]
It works despite the error message,

I think it should be fixed though, because the current user experience prevented us to finish our donations
