### ISSUE TITLE
Donate To #CryptoForBlackLives One Click

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6903]
Could we add a 'one click' donate to the matching pool button on the site which collects donations to our official donation matching address? On this view: https://gitcoin.co/grants/crypto-for-black-lives/

Crypto For Black Lives: 0xc544BEbE22563CEB78D597c1bd0B8Cf2DC858B13

**Comment by owocki** [comment]
we had this several rounds ago and it was not ever used.

**Comment by ceresstation** [comment]
I agree with Vivek that it may prove more useful in this case.
