### ISSUE TITLE
LoopringPay for grants contributions

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6905]
## Use case

I made a contribution of 0.95 Dai, but paid 1.42 usd fee, using the loopring protocol we could eliminate that fee.  It is an idea that accepts better proposals ...

other user
![IMG_5164](https://user-images.githubusercontent.com/57037080/84934134-49ab1100-b0ad-11ea-9067-9f083047bfaf.jpg)

## Possible solution 
Layer 2 payments zkRollup
https://twitter.com/loopringorg/status/1269371253023965184?s=21

**Comment by thelostone-mc** [comment]
we have zksync for now ! closing this out for now
