### ISSUE TITLE
Feature request: display time since last update on the grant summary page

### ISSUE THREAD

**Issue by NelsonMcKey** [gitcoinco/web#6907]
### User Story

As a grant funder, I want to see the time since last update of the project page, so I can ensure I am giving to an active project.

### Why Is this Needed

*Summary*: It's difficult to tell if a project is newly submitted, energised and is seeking funds, or momentum has petered out, the page is no longer being updated and the funds might not be put to any further use on the project. Similarly, where a project has existed for a few rounds and is seeking further funds, they should be encouraged to update on progress and define clearly how an additional round of funds will be used.

### Description

*Type*: Feature

### Definition of Done
Time since last update is visible for all projects seeking grants.

### Additional Information
Discussion: https://twitter.com/owocki/status/1273062251906207745

**Comment by owocki** [comment]
this went live today. check it out !
