### ISSUE TITLE
Gitcoin Grants Contribution Not Showing Up 

### ISSUE THREAD

**Issue by 0xLucas** [gitcoinco/web#6914]
**Describe the bug**
Made a round of Gitcoin Grants donations for 10 DAI each and the DAI was taken out of my Metamask but no contributions are shown on Gitcoin's end.

**To Reproduce**
Added 3 Projects to cart and followed the normal flow. 

**Expected behavior**
 My dondations to show up on Gitcoin.

**Screenshots**

TX Hash: https://etherscan.io/tx/0xecfac7a5ecbfb0f84020ec0a510ea4a0de6a3ab0e54ad307385fe0dc2a790efd

![image](https://user-images.githubusercontent.com/49569597/84943223-0f903e00-b0b2-11ea-9cea-28a3a21246fa.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave
- Browser Version: N/A

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

Grants were for 10 DAI each to Bankless, Our Network, and The Defiant

**Comment by developerfred** [comment]
@0xLucas https://github.com/gitcoinco/web/issues/6911
