### ISSUE TITLE
Gitcoin Grants Checkout Modal

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6915]
**Describe the bug**

Modal does not work on Microsoft Edge

**To Reproduce**

Fund some Grants and then see the modal
**Expected behavior**

Get to click the button
**Video**
https://share.getcloudapp.com/ApuAkD96

**Screenshots**

<img width="1440" alt="Screen Shot 2020-06-17 at 17 36 28" src="https://user-images.githubusercontent.com/57037080/84947803-3d30b380-b0c1-11ea-95b5-0658448af46e.png">

**Desktop (please complete the following information):**

- OS: MacOs Catalina 10.15.2
- Browser: Microsoft Edge
- Browser Version: Version 83.0.478.45 (Official build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
@developerfred do u know the JS error?  mind submittin ga PR?

**Comment by developerfred** [comment]
hey @owocki! I made a new contribution to simulate and get the information from the console, this time the button appeared but the modal is not with the proper behavior.

<img width="1440" alt="Screen Shot 2020-06-17 at 20 16 42" src="https://user-images.githubusercontent.com/57037080/84960298-a7ece980-b0d7-11ea-8163-ad7cefe59b95.png">
 
<img width="1439" alt="Screen Shot 2020-06-17 at 20 15 11" src="https://user-images.githubusercontent.com/57037080/84960312-afac8e00-b0d7-11ea-8857-9013db6e9f24.png">

<img width="418" alt="Screen Shot 2020-06-17 at 20 16 11" src="https://user-images.githubusercontent.com/57037080/84960309-ade2ca80-b0d7-11ea-884c-401c365285b6.png">

**Comment by developerfred** [comment]
@owocki  I think the problem is occurring because of the html id which is not unique.

**Comment by developerfred** [comment]
@owocki I found it, I will send the PR
