### ISSUE TITLE
brainstorm - where do we put job board requests?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6925]
Owocki  10:22 AM
this guy sent me his CV. no idea if hes any good
PDF 
resume.pdf

Scott Moore  11:29 AM
Hmm I mean maybe we can have him in one of our hacks?

vivek  12:49 PM
he hacks often
12:49
built pooltogether x aave hack last time

Scott Moore  12:51 PM
oh nice

Owocki  12:54 PM
i wonder how to channle these requests down a happy path
12:54
post to town square with hashtag jobs, then we’ll basically have a time series job board… (edited) 
12:55
maybe even feature those posts and heavier on town square than others..

Scott Moore  1:14 PM
I think we could make a "Job board" work well
1:14
it would probably need to pair with the user directory though
1:14
a list of people to join your tribe that you could schedule an interview with
1:15
we already have the jitsi integration so I suppose we're doubling down on this idea in some ways already

Owocki  1:18 PM
i mean given how active our community is “looking for work” “looking for devs” seem like an easy acceleratant to the flywheel.. we’d just need to figure out how to thread it into the app (edited) 
:heavy_plus_sign:
1

**Comment by octavioamu** [comment]
Yes I been always wanting this are on gitcoin:

`/jobs => list of all jobs`
`/{org handle}/jobs/  => list of orgs jobs posts `
`/{org handle}/jobs/{id} => single job page 
`
- every org can post jobs descriptions
- contributors can just apply with one click (maybe also open an email box in case they need to change their email for job contact)
- Companies access gitcoin profile of the candidates to check activity and others networks links (github, linkedin, etc) 
- Attach activity comments on single jobs pages (create interactions, answer general questions)
- new job posted => townsquare post (as bounties or grants)

**Fields an org need to fill** 
- Title (Free text field "looking for JS developers"
- Skills (use the keywords)
- Level (select with level:  junior, senior...) 
- Description (WYSWYG area)

When someone applies, orgs can see the candidates on the job description and also receive an email with the profile links.

**Comment by owocki** [comment]
my one request is that we fiund a way to work this into a nav or town square. we dont need another area of the site for people to have to remember to check.
