### ISSUE TITLE
BLZ Tokens failing

### ISSUE THREAD

**Issue by Bluzelle-Team** [gitcoinco/web#6926]
**Describe the bug**
We sent a tip to the developer. However, when he clicked "claim BLZ", nothing happens. (attached screenshot)

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_at_2020-06-18_11-19-00 (1)](https://user-images.githubusercontent.com/56818278/85088427-af64dd80-b212-11ea-8bbc-7d8594c4925d.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by developerfred** [comment]
the user has no gas to be able to receive the token, yesterday the network was very congested

**Comment by octavioamu** [comment]
still a problem or was solved? in last case what are the sender and receiver of the tip?

**Comment by Bluzelle-Team** [comment]
Resolved thanks! The developer received the rewards.

**Comment by octavioamu** [comment]
Glad to hear that @Bluzelle-Team 🙂
