### ISSUE TITLE
MetaMask Authentication

### ISSUE THREAD

**Issue by cryptoislife003** [gitcoinco/web#6931]
**Describe the bug**

When I go to create a grant, the page loads faster than my MetaMask can sync with the page. Thus, the page ends up saying "you need to sync with MetaMask to continue, please refresh page" shortly before my MetaMask syncs.

I refresh the page and then have the same problem, as the page loads faster than the MetaMask sync.

**To Reproduce**

Turn MetaMask on for site -> create a grant page

**Expected behavior**

The expected behavior for the site page to wait so my MetaMask has time to sync before telling me I need to refresh

**Screenshots**

![image](https://user-images.githubusercontent.com/39505607/85138641-1d100a00-b211-11ea-98c2-760957eeb352.png)

![image](https://user-images.githubusercontent.com/39505607/85138588-079ae000-b211-11ea-9f02-916ffa77a2ba.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Browser Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

On desktop

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by octavioamu** [comment]
thanks, will be fixed on https://github.com/gitcoinco/web/pull/6952

**Comment by octavioamu** [comment]
Closing this as was deployed already, feel free to reopen or ping me here if still a bug for you
