### ISSUE TITLE
Combine Grants Donation TS Posts

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6933]
As a user, I want to see what multiple people are donating towards / have less scrolling to see donations. 

Combine all donations from one donor into one card on TS.

'Caleb donated to ZapperFi, Origin, Black Girls Code, and 6 other projects.' Have an easy preview of the 6 others. 

![image](https://user-images.githubusercontent.com/23297747/85199011-839d3280-b2ba-11ea-8f90-5441472b621f.png)

**Comment by Solexplorer** [comment]
Wouldnìt this just spam the TS? Or are you talking about the grants wall.
Wanna keep the general TS clean if possible

**Comment by developerfred** [comment]
@Solexplorer and @vs77bb I thought of a single post when there are multiple donations.
##### like this: 
 1 - Name Grants - amount
 2 - Name Grants - amount
 3 - Name Grants - amount
 4 - Name Grants - amount
