### ISSUE TITLE
When someone creates a grant they are getting duplicated

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6935]
**Describe the bug**

When someone create a grant, it gets duplicated. more here: https://gitcoincore.slack.com/archives/CAXQ7PT60/p1592305974051300
For whoever doesn't have access ^, Here is an example: https://gitcoin.co/grants/856/kernel and https://gitcoin.co/grants/855/kernel
**To Reproduce**

Create a grant and it will get duplicated

**Expected behavior**

No duplicated grants
**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
i wonder if they are double clicking the new grant form. need to stop the user from double clicking

**Comment by danlipert** [comment]
@mds1 can yall take a look at this one?

**Comment by mds1** [comment]
@Solexplorer Is there any additional info about this in that slack channel? I don't have access, so if there is more info there would you mind pasting it here?

**Comment by Solexplorer** [comment]
Actually, in that slack message, there are only links to duplicated grants that I've came around, there aren't infos on why this is happening, pasting here the content of that thread:

https://gitcoin.co/grants/840/ethereumdevio-from-deploying-your-first-smart-cont and https://gitcoin.co/grants/841/ethereumdevio-from-deploying-your-first-smart-co-2

https://gitcoin.co/grants/842/dao-governed-eips-and-eth-20-spec and https://gitcoin.co/grants/843/dao-governed-eips-and-eth-20-spec-2

![image](https://user-images.githubusercontent.com/50027175/86046211-20936480-ba4d-11ea-94cf-a3f5c5ca8aeb.png)

**Comment by owocki** [comment]
i think this might fix the root cause acf01dedded3f9a874eafa693142eebb7f62a263

**Comment by mds1** [comment]
I was able to reproduce this on 6b94199ec3c17df96d83c5b80fc027e7c48705e0 (the commit immediately before acf01dedded3f9a874eafa693142eebb7f62a263), but was not able to reproduce after acf01dedded3f9a874eafa693142eebb7f62a263

So I agree you fixed it with that commit and this can be closed (which I don't have permission to do)
