### ISSUE TITLE
Issue when changing username

### ISSUE THREAD

**Issue by nightwolf3** [gitcoinco/web#6938]
Hello
I've been using Gitcoin for a while now and in love with the platform.
I stumbled upon a minor issue where I get redirected to an error 500 when I changed my github username. I could not login to my account on gitcoin even after changing my display name and Github on my profile. 
If you need any help figuring it out feel free to ping me I'd be happy to give it a go

**Comment by molecula451** [comment]
You should paste some screenshots on what's really happening

**Comment by nightwolf3** [comment]
I did that a while ago and then simply reverted to my old github username to not have any errors.
The issue arises when a user changes his github username linked to gitcoin, after waiting for a couple of minutes as suggested when changing a username, logging in to gitcoin directs to an error 500 page.

**Comment by octavioamu** [comment]
if you change your username you should logout from gitcoin and login again, that will update your username to the new one on our db. 
I'm not sure if you just reverted your username on github or still without being able to access gitcoin, please if that the case send the old and new usernames so we can check.

**Comment by nightwolf3** [comment]
Hello
Sorry for the late reply. Yes I simply reverted to the old username and have been active on gitcoin so far, just thought I should point out.
It happened around a month ago and I immediately reverted so it's all good now thank you

**Comment by octavioamu** [comment]
good to know I coded something time ago but need to log out and in again and the system should take the new username, but not sure is working since I did it time ago.

**Comment by nightwolf3** [comment]
I'll check the issue another time I dont wanna test it out at the moment because Im working on some bounties.
I'll close the issue now and if it arises again we'll check up on the code
