### ISSUE TITLE
Donate in Gitcoin Grant without login. 

### ISSUE THREAD

**Issue by agnelvishal** [gitcoinco/web#6941]
I understand that authentication is required to avoid Sybil attack in gitcoin grant. But I would be happy if I can donate on a grant without signing up and logging in even if there is no additional match.

Even if this feature is not being used frequently, it may respect users who need high privacy. Also removing the need to signup will reduce the friction to donate.

**Comment by owocki** [comment]
you can donate by sending tokens to grant address directly, but they wont be matched.

quadratic funding requires sybil resistence so some identity info is going to be needed (github or otherwise).  sorry, but it just does.

**Comment by agnelvishal** [comment]
> you can donate by sending tokens to grant address directly, but they wont be matched.
> 
> quadratic funding requires sybil resistence so some identity info is going to be needed (github or otherwise). sorry, but it just does.

Fine then.
