### ISSUE TITLE
Email tribe that a sponsor is participating in a Hackathon

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6942]
### User Story

As a sponsor, I want my tribe members to automatically be notified that that I'm sponsoring a hackathon so that they can participate.

### Why Is this Needed

**IF we engage with developers already interested an org, then sponsors will have a great hackathon turnout, because developers will participate in the sponsored hackathon.**

**IF we do this, it'll Increase number of hackers registering for a hackathon.**

### Description

If a **sponsor signs up for a hackathon**, email to current **tribes members** and let them know that x sponsor has signed up for a hackathon, register to participate/ checkout the prizes!

### Current Behavior
[comment]: # (Describe what actually happened.)
no automatic email

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
automatic email sends out as soon as we know the sponsor is sponsoring.
1 week prior? 3 days prior?

### Definition of Done

- [x] write copy
- [x] design email (web & responsive views)
- [ ] build email

### Data Requirements
increase in number of registered hackers per hackathon

**Comment by fluffays** [comment]
Copy draft - https://docs.google.com/document/d/1labYieckMI2y17phjZ3n2OkWcR4JRXTqWklBcZXwJps/edit?usp=sharing

**Comment by danlipert** [comment]
@PixelantDesign based on today's conversation regarding hackathon prize setup and when participants register, this should probably be a manual process triggered through the admin or something similar - since different sponsors have different timelines for when they post prizes and such, we dont want to direct potential participants to an empty hackathon.

**Comment by willsputra** [comment]
design draft. will update the header with the latest one by Octavian!
![hackathon (1)](https://user-images.githubusercontent.com/19514207/85402481-5ab4c000-b58e-11ea-804e-f5c8c3a0758c.png)

**Comment by PixelantDesign** [comment]
Another email could display the prizes @willsputra after the hackathon has started. What do you think?

**Comment by willsputra** [comment]
@PixelantDesign yea I think that's a good idea! will mock this up

**Comment by willsputra** [comment]
what do you think?
![blockstack](https://user-images.githubusercontent.com/19514207/85852050-73b5af00-b7e2-11ea-8992-c38b7f98ebf0.jpg)

**Comment by PixelantDesign** [comment]
> design draft.
> ![hackathons](https://user-images.githubusercontent.com/19514207/85405022-64d8bd80-b592-11ea-8be3-10a687a482e5.png)

@sebastiantf @developerfred are either of y'all interested in this one?

**Comment by sebastiantf** [comment]
@PixelantDesign I'm interested

**Comment by PixelantDesign** [comment]
**Email Details**

- This should populate using send grid
- Build email so that it works by manual population of information through the Gitcoin Admin
- Email body should be editable and have an editable title for each section.
-  An admin should be able to upload an image where the Hackathon image is displayed
- There should be a join button that allows users to join
- Must be responsive

Design coming soon. cc  @willsputra

**Comment by willsputra** [comment]
Build ticket: https://github.com/gitcoinco/web/issues/7020
