### ISSUE TITLE
Create Sponsor Onboarding How to Checklist

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6944]
### User Story

As a hackathon sponsor, I want to know how to do basic things on the platform.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

From RenVM Call - Sponsors are confused on where to go to get basic information.

IF we create this one sheet, then sponsors will have a good experience nagivating our platform because they'll have aa quick reference on how to get around our system.

This is also a good test on what we could build into the product.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Marketing Doc

### Current Behavior
Limited info provided

### Expected Behavior
Quick tips 1 sheet

### Definition of Done
Provide a 1 sheet with the following info:

- Here is how you list your prize
- Here is where the prizes show up
- Here is where u go to see whos working on your prizes
- Here is where u go to see the projects
- Here is where you go to pick winners
- Here is how you pay out
- Here are ways you can contiinue working iwth these people
- Maybe a tips & tricks section on how to have a great hackathon experience

### Data Requirements
- happy sponsors
- less confused sponsors on how to do basic things

**Comment by fluffays** [comment]
1st draft for this doc => https://www.figma.com/file/MxZWbPIbBu4JrV4QClxE4y/Sponsor-hackathon-quick-guide?node-id=0%3A1
