### ISSUE TITLE
I funded 33 grants in 1 transaction, but only 26 recorded on gitcoin

### ISSUE THREAD

**Issue by frdra** [gitcoinco/web#6947]
## Describe the bug
I funded 33 grants in 1 transaction, but only 26 recorded on gitcoin.

Etherscan transaction: https://etherscan.io/tx/0x0e3bd37010ef2c371f26a6059e1cd22f7fbc9e009dc01896ce97ad636d914202

Gitcoin account: https://gitcoin.co/frdra/grants

## To Reproduce

Expected behavior

## OS

- OS: Windows 10
- Browser: Google Chrome 
- Browser Version: 83.0.4103.106

**Comment by developerfred** [comment]
@frdra your transactions will appear is that the script checks all transactions simultaneously
