### ISSUE TITLE
Gitcoin issue status changed back to Open from Work Started

### ISSUE THREAD

**Issue by zheli** [gitcoinco/web#695]
##### Description

https://gitcoin.co/funding/details?url=https://github.com/ethereum/web3.py/issues/666
The issue I was working on returned to Open status, even though there are 11 months left in expiration days. Is it a bug?

##### Environment

* **Browser**:
* **Version**:
* **Subsystem**:

**Comment by owocki** [comment]
The system will remove you from the issue if you have not been active in several days.

Here is a screenshot of some of the warning emails we sent out about this: http://bits.owocki.com/3t3c061r2F1z/Screen%20Shot%202018-03-26%20at%209.20.17%20AM.png

Here is a screenshot of a final 'weve removed you' email we sent out on 3/16: http://bits.owocki.com/1O251V2T1h1O/Screen%20Shot%202018-03-26%20at%209.19.58%20AM.png

**Comment by owocki** [comment]
cc @vs77bb since i think you commented on the github thread about this

**Comment by zheli** [comment]
@owocki thanks for looking into this. Actually I have added two comments after I got the email, did I miss something in my comments?

**Comment by owocki** [comment]
hey @zheli -- im sorry, maybe im just missing it, but i dont see any other comments from you on this thread?

**Comment by zheli** [comment]
I meant those comments in the thread https://ibb.co/eKNfVS.

**Comment by PixelantDesign** [comment]
Is this still a bug? @mbeacom

**Comment by thelostone-mc** [comment]
We've updated the stop working policy where the bot doesn't remove the user on its own ! 
I believe this has been taken care of ^_^
