### ISSUE TITLE
Grant contribution issue

### ISSUE THREAD

**Issue by L-KH** [gitcoinco/web#6954]
**Describe the bug**
I contribute yesterday to two grants in gitcoin. and I confirm the transaction in metamask and all steps are correct. but after some hours I check etherscan and I get that there is no transaction from my wallet, even the fee of the transaction doesn't show.
you can check this status: https://gitcoin.co/townsquare?tab=activity:303961
and also this one: https://gitcoin.co/townsquare?tab=activity:304104
you can check etherscan of my wallet here:  0x1426FBd146942e153653863cbe633780c17268DA

ps: I contribute using DAI

**To Reproduce**
-

**Expected behavior**
everyone will contribute with 100dai or more, and the balances will still the same

**Screenshots**
I don't know what screen should I post

**Desktop (please complete the following information):**

- OS: windows10
- Browser: chrome
- Browser Version: 83.0.4103.116 

**Additional context**
let me know if you need more information about it

**Comment by L-KH** [comment]
Should I re-contribute and screenshot as a video ?

**Comment by L-KH** [comment]
here is the video
![Enregist-2020-06-23-14-05-23-284](https://user-images.githubusercontent.com/12660772/85426177-07cd0f80-b572-11ea-8d41-cd7d520d6d22.gif)

**Comment by owocki** [comment]
the grants txn validator should catch this.  it makes sure tokens have actually been xfr'd

**Comment by L-KH** [comment]
Oh cool. so I will close it. THanks
