### ISSUE TITLE
Gitcoin should monitoring issue pull request as well

### ISSUE THREAD

**Issue by zheli** [gitcoinco/web#696]
##### Description
In addition to github issue page, gitcoin should also tracking the conversation on pull request. since the work discussion usually take place there, especially for larger issue.

Here is an example: https://github.com/ethereum/web3.py/issues/666#issuecomment-375901199

##### Environment

* **Browser**:
* **Version**:
* **Subsystem**:

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/458

**Comment by owocki** [comment]
this is done!
