### ISSUE TITLE
grant triggers 4 calls to 'get_amount' everytime a cart item is updated

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6960]
https://bits.owocki.com/z8u86rwg

can we get this down to 1? or for DAI, lets just not even make the call to the server, its wasteful. 1 DAI = $1 aand the frontend can know that.

or maybe we get the conversion rate ONCE per page load and just use it multiple times

**Comment by developerfred** [comment]
@owocki I'm going to start working on it, I liked the solution of making a call just once.

**Comment by developerfred** [comment]
This way you will only call the API if it is a currency other than DAI
`let amount = (currency === 'DAI') ? rawAmount  : await this.valueToDai(rawAmount, currency);`

it is a solution to decrease requests.
