### ISSUE TITLE
"feature bounty" is selected have one bug when we try to finance a bounty

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6962]
**Describe the bug**
When a funder tries to fund a bounty and add the featured feature he is unable to submit the request.

**To Reproduce**

1 - Go to https://gitcoin.co/funding/new
2-  Fund any github Url and then check "feature bounty"
3 - Try to send the form

**Expected behavior**

Having no problems submitting the form

**Screenshots**

https://share.getcloudapp.com/ApuAYpvK

**Desktop (please complete the following information):**

- OS:
- Browser: chrome/brave
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
https://gist.github.com/developerfred/6b3e4ec5ccfc28a5da22d15cc49d5938

**Comment by octavioamu** [comment]
Thanks ! Solved here 897e1f6f8e749264b0322b2da93a3eb5ee2156e9
