### ISSUE TITLE
Grant Donation Bug (Decimals)

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#6968]
**Describe the bug**

"Cannot read properly decimals of undefined" 
![image](https://user-images.githubusercontent.com/23297747/85493987-e128cc00-b5a5-11ea-9cc5-9559d9e04655.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Additional context**

**Comment by vs77bb** [comment]
![image](https://user-images.githubusercontent.com/23297747/85554151-a39e6000-b5f2-11ea-8aa5-da809eb8aa06.png)

**Comment by danlipert** [comment]
@octavioamu was the fix you were working on going to solve this? Also im wondering if these folks have a web3 wallet enabled at all - i dont see metamask or anything in their browser. @vs77bb

**Comment by octavioamu** [comment]
yes, that error is because the wallet was ignored, now if there is not wallet connected the function will not run and instead will ask you to connect a wallet (prompt the modal)
