### ISSUE TITLE
As a funder who wants to issue 1099s on the the platform and interact with only KYC'd or geofenced users, I want the ability to both , so I can satisfy my compliance department of my local jurisdiction.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6972]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a funder who wants to issue 1099s on the the platform and interact with only KYC'd users, I want the ability to both , so I can satisfy my compliance department of my local jurisdiction.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Scott has a customer on the line that requires it.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No KYC and 1099 ability

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
1. add the ability to KYC people on the platform (+ collect tax info like SSNs + addressess) in the settings.
2. for hackathon sponsors, add the ability to geofence bounties on the platform (and make them KYC'd users only), on the new bounty form.  anyone can apply, but they must KYC before their application will go through.
3. issuing 1099s via the platform.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
how many people on the platform are KYC'd?  how much does it cost?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
Pricing is over at https://passbase.com/pricing/

The solution we build out -> would be generic so that it can be wrapped around any feature (bounties being one of them)

Stuff to figure out within passbase

![image](https://user-images.githubusercontent.com/5358146/86260029-616cb400-bbda-11ea-8882-8708eed8f509.png)
