### ISSUE TITLE
TownSquare new feature “looking for project”  is broken 

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#6973]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![D69891A0-DD80-4F09-A56A-26B8E7212BD9](https://user-images.githubusercontent.com/57037080/85603671-f5f97400-b626-11ea-86dd-6bc854998a4c.jpeg)

**Desktop (please complete the following information):**

- OS: 

- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: iphone 
- OS: iOS 
- Browser:Safari 
- Version:

**Additional context**

**Comment by PixelantDesign** [comment]
Thanks @developerfred, want to help us fix ?

**Comment by developerfred** [comment]
I'll investigate!

**Comment by developerfred** [comment]
#6980
