### ISSUE TITLE
Tribes: Convert Orgs --> Tribes Light

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#6974]
### Description

Update orgs --->tribes light

### Current Behavior
Old orgs

### Expected Behavior
Gitcoin Sponsors all get tribes light

### Definition of Done

- Address performance issues
- Make it so that all sponsors get tribes light

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
https://github.com/gitcoinco/web/issues/6812

**Comment by owocki** [comment]
>  remove this check, dashboard/views.py on or around line 2886 if profile.is_org and profile.handle.lower() in ['gitcoinco']: and remove the remainder of the view code below the TemplateResponse including 'tribes-vue'

note that my PR ( https://github.com/gitcoinco/web/pull/7080/files ) makes this into a DB field. so u can check it off!

**Comment by PixelantDesign** [comment]
nice!
