### ISSUE TITLE
When the cart is over 40 items, it should be split into 2 transactions, when the cart is over 80 items, it should be split into 3 transactions.

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#6981]
<img width="372" alt="Screen Shot 2020-06-25 at 2 42 42 PM" src="https://user-images.githubusercontent.com/14945613/85722277-68835600-b6f2-11ea-873e-109a52d1d43a.png">
Wow! Thats a lot of gas... and because it's such a huge transaction, I am going to need to pay a lot higher gas price to get it thru... it would be nice to get it to be in smaller pieces :-D

Ideally this tx would be 3 of them

**Comment by developerfred** [comment]
@GriffGreen Yes it is necessary to do this split

**Comment by GriffGreen** [comment]
well it turns out that the actual gas used was much less... here is the actual tx: https://etherscan.io/tx/0xeeef487c7f2e8390635321634260c9bf952fb6e96d1fdeb900106fa23b58cf58

Only 2.6 mil... so maybe just the gasLimit Estimator you are using needs to be turned down a bit

**Comment by owocki** [comment]
i know @mds1 is working on the gas estimator in another PR!

**Comment by mds1** [comment]
Related PR here: https://github.com/gitcoinco/web/pull/6961

It's been merged so should be deployed soon, though it will only improve the situation about 75% of carts based on the selected tokens. Looking at your tx @GriffGreen, in your case it would not have helped unfortunately

**Comment by mds1** [comment]
It wouldn't be tough to make the logic a bit smarter to handle cases like yours. That way gas estimates for Dai can be reduced even when the cart is not 100% Dai
