### ISSUE TITLE
My 90 grant donation isnt showing up on any grants :-(

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#6988]
https://etherscan.io/tx/0xeeef487c7f2e8390635321634260c9bf952fb6e96d1fdeb900106fa23b58cf58

I donated to a bunch of grants... but i guess i canceled the donation the first time and then recreated the transaction and now the canceled on is showing up but on every other grant... its showing up on the UI as failed
<img width="894" alt="Screen Shot 2020-06-25 at 8 19 10 PM" src="https://user-images.githubusercontent.com/14945613/85776657-350bf000-b721-11ea-9224-42b3a5c2361a.png">
<img width="735" alt="Screen Shot 2020-06-25 at 8 18 47 PM" src="https://user-images.githubusercontent.com/14945613/85776665-36d5b380-b721-11ea-818a-9f0d708f21b0.png">
<img width="1092" alt="Screen Shot 2020-06-25 at 8 18 32 PM" src="https://user-images.githubusercontent.com/14945613/85776670-376e4a00-b721-11ea-9a4b-9b348f8812ac.png">

It's the same for all 90 grants.... but the transaction succeeded and the money went out to all the grants! So I just want to ensure that the funds are being counted towards the totals... it was over $2000 worth of funds :-P

Btw... GREAT MULTISEND!!! :-D 

Much Love, 
Griff

**Comment by owocki** [comment]
just tweaked the contribution validator + its now validating the cad cad txn
