### ISSUE TITLE
Let hackathon projects creators delete their projects

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#6989]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user, I would like to delete my project during the hackathon without having to ask an admin to do that for me because maybe I want to create a new one or I'm not participating in the hackathon anymore.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description
Right now, I'm not able to remove a project, I can only edit it. I feel like this is an important feature for a hackathon

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
The user is not able to delete a project and has to ask an admin to do that for him.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
He can be able to delete a project on his own discretion.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Ability to delete a project.

**Comment by Solexplorer** [comment]
@PixelantDesign What do you think about this, should be relatively easy

**Comment by thelostone-mc** [comment]
Closing this out as this was never picked up!
might be worth bringing this up when we do revamp for hackathons as a requirement 
cc @frankchen07
