### ISSUE TITLE
Transaction failed but no funds received back. Two possible problems reported here

### ISSUE THREAD

**Issue by p4u** [gitcoinco/web#6990]
**Describe the bug**

From https://gitcoin.co/grants/202/vocdoni-decentralized-anonymous-voting?tab=transactions

There are two transactions on the list of contributions which are not accounted

First one from myself

https://etherscan.io/tx/0x80ee2b25724b3b3b180ef5d923b39a48558c0724bd0a0d4ee3f199dc2f5dba9c

Second from @griffgreen

https://etherscan.io/tx/0xeeef487c7f2e8390635321634260c9bf952fb6e96d1fdeb900106fa23b58cf58

Not sure if there is some relation between both problems.

I managed to donate to other projects and there was no problem at all.

**To Reproduce**

I don't know how to reproduce it.

**Expected behavior**

Transactions should be accounted correctly in the Project contributions list.

**Comment by owocki** [comment]
> but no funds received back

wait why would you expect funds back? if the tx failed then you didnt send any funds, thereby none need to be sent back

> I don't know how to reproduce it.

what browser / web3 wallet did you use?

**Comment by p4u** [comment]
> wait why would you expect funds back? if the tx failed then you didnt send any funds, thereby none need to be sent back

No, I don't want a refund nor something like that. I am just reporting that for some reason I cannot understand the TX failed.

I am using Brave + Metamask 7.7.9

**Comment by p4u** [comment]
I saw that the @griffgreen donation also failed and I asked him for details. He told me to report it here.

As said, I am not sure if the error is related or not.

**Comment by p4u** [comment]
But you are right, I did not send any token on that TX.  I don't know what happened, but GitCoin interface got somehow messed.

https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f?a=0xd310ae66193833e7028a6680e19a7d073df01e05

So I'll just repeat the TX.

However, why the other transaction appears as Failed if the tokens have been actually transfered?

`From 0x839395e20bbb182fa440d08f850e6c7a8f6f0780To Gitcoin Grants: Vocdoni For 495 ($494.77) Dai Stableco... (DAI)`

https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f?a=0xd310ae66193833e7028a6680e19a7d073df01e05

thanks @owocki

**Comment by p4u** [comment]
So now Griff contribution seems fine. Either someone fixed the bug, or it was just a matter of time. 

Closing.

**Comment by owocki** [comment]
i made an update to the transaction validator, and i think thats what did it.  thanks again for the ticket!
