### ISSUE TITLE
squashed Kudos display

### ISSUE THREAD

**Issue by DreadKnight** [gitcoinco/web#6992]
The new `Artist of x Kudos` feature displays the hexagons squashed by having 1:1 ratio, which is inaccurate.
https://gitcoin.co/profile/dreadknight/kudos

**Comment by DreadKnight** [comment]
Also the spacing is bad, there should be an empty line between the displayed Kudos and the following text.

**Comment by thelostone-mc** [comment]
Fixed. Closing now
