### ISSUE TITLE
Grant is showing funding, even when funder has not signed the transfer tx.

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/web#6999]
**Describe the bug**
Grant is showing funding of $$, even when grant owner has not received the funds in his wallet. And most probably reason behind this is, that grant funder has only signed the approve tx, and not signed the **transfer** tx.
https://gitcoin.co/grants/792/kernel-my-contributions?tab=description

**Expected behavior**
Grant should only show the funding when the funder has signed the transfer tx.

**Screenshots**
![Screenshot 2020-06-26 at 2 19 31 PM](https://user-images.githubusercontent.com/22838732/85839169-3805ef80-b7b8-11ea-8891-f90aa3e2e8ce.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Chrome
- Browser Version: 83.0.4103

**Comment by owocki** [comment]
the validator should catch this + mark the txn as failed fwiw.

**Comment by thesachinmittal** [comment]
@thelostone-mc here is the issue page. :)
