### ISSUE TITLE
make ONE post per grants checkout instead of N where N is the number of cart items

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7002]
we should make ONE post per grants checkout instead of N where N is the number of cart items

bc:
- reliability, it crushes our servers when someone checks out with 90 grants
- just in case one HTTP request gets lost, filterd by the load balancer
- i want to store the entire POST request in the DB in case there is some sort of 500 error upon contribution creation, so we dont lose the grant contribution creation

**Comment by mds1** [comment]
Handler for current endpoint: https://github.com/gitcoinco/web/blob/master/app/grants/views.py#L782-L850
