### ISSUE TITLE
As a developer, I'd like to know the latest happenings on Gitcoin

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7014]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I'd like to know the latest happenings on Gitcoin

continued from https://github.com/gitcoinco/web/issues/6870

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: As users in town square (especially new users) might not be aware of Gitcoin products and events, we would like to add a module in town square to display the latest happenings on Gitcoin: hackathons, grants round, workshops, events, and more.

By doing this, we would also bring more people into our hackathons/grants round, which will be beneficial for us and sponsors.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No module on the latest happenings on Gitcoin (a basic v1 is built on https://github.com/gitcoinco/web/issues/6870)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Display in right rail of townsquare

![85852133-93e56e00-b7e2-11ea-828d-e9194839b414](https://user-images.githubusercontent.com/19514207/86016333-3efd5e00-ba55-11ea-9720-845bdc2884ca.jpg)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Build the module on townsquare, right rail above referal link
• Show max 3 events in "Happening Now" and 3 events in "Upcoming"
• "View more events" brings you to a dedicated event page with a complete list of events sorted chronologically
• Different types of events will have different labels and CTA:
- "Hackathon" CTA: "Join Hackathon" which brings you to the hackathon onboarding
- "Grants" CTA: "View Details" which brings you to the grants homepage
- "Workshops": TBD
- Other events?

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
Track clicks of these events and conversion rates.

**Comment by developerfred** [comment]
@willsputra The Latest Bounties feature, are the bounty that the user applies or the last bounty's that were added to the platform?

**Comment by willsputra** [comment]
@developerfred it will be the recent bounties that were added to the platform. the idea is for users to know what bounties are available!

**Comment by developerfred** [comment]
Thanks!

**Comment by developerfred** [comment]
I have some doubts about where to get this data.

Endpoint status: 
- [ ] module Upcoming 
        - Workshop endpoint (Google calendar ?)
        - Next Round (calendar endpoint)
- [x] module Latest Bounties [ endpoint ok]
