### ISSUE TITLE
Checkout for grants doesn't recorded in gitcoin.co (but transactions saved in blockchain)

### ISSUE THREAD

**Issue by alfinal** [gitcoinco/web#7018]
How to reproduce it:

1. Install [Metamask add-on in Firefox](https://addons.mozilla.org/es/firefox/addon/ether-metamask/) (we tested with Firefox 60.5.1esr, that maybe is a little bit old but is in our community library computers)
2. Create or connect an ETH & DAI account with some coins in both
3. Create a new user in [github.com](https://github.com)
4. Login with this user in [gitcoin.co](https://gitcoin.co)
5. When pop-up about connect your Gitcoin account to your wallet through Metamask accept it
6. Go to the grant you want to fund and "Add to cart" a quantity (for instance new user @grizlda add to cart 24DAI for [Vocdoni grant](https://gitcoin.co/grants/202/vocdoni-decentralized-anonymous-voting?tab=transactions))
7. Check out
8. Go to "Adjust" and in "Custom" go down to 0%
9. Click on "Fund 1 item"
10. Approve 2 transactions via Metamask (you see a congrats page and that's all you have to do in gitcoin.co web)
11. After some little moment take a look and see that your transaction is made in etherscan ([for instance 24DAI from your ETH account to "Gitcoin Grants: Vocdoni"](https://etherscan.io/tx/0x5563ae9614ca10160cd66b27087e5932044044c2ecafa61049a6ccea0798e935)) 
12. Take a look anywhere in Gitcoin.co web, [you cannot see the transaction](https://gitcoin.co/grants/202/vocdoni-decentralized-anonymous-voting?tab=transactions).

_Extra info and/or issues:_
- Some moments after the user made transaction [Github experienced a important incident](https://www.githubstatus.com/incidents/d60fmldlvw48)
- As a new user in Github and in Gitcoin don't customize any in gitcoin.co frontend. I don't know if is related to this but is "ugly" if you go to Dashboard (after execute the Funding) you see it just empty (top and bottom without anything in between):
![photo6039457087945290456](https://user-images.githubusercontent.com/5018007/86038611-79f59680-ba41-11ea-8f66-c67e21bbee80.jpg)

**Comment by owocki** [comment]
hmmmmm; i i need to figure out how to reproduce this issue.

meantime, what is the user who was logged in for this txn? i can ingest it from the backend.

**Comment by alfinal** [comment]
@grizlda (example is real and you can see her snapshot)

I realize that this issue maybe is related to #7017 , but in this case the transactions is not in the list you made it to ingest.

**Comment by alfinal** [comment]
Same: #7034

**Comment by grizlda** [comment]
Hello there! I would like to do a follow up on this issue. I am one of the users (I know one more) who made two different transactions from Ethereum this day (29 June 2020) and then they didn't appear on the related Gitcoin project's pages, so we opened this issue. 

Here you can see my transaction were recorded on the blockchain: 

https://etherscan.io/address/0xb7fb2185d6d0a91a1d523a19ae15c53cbc049813

But they don't appear on my gitcoin profile: 

https://gitcoin.co/grizlda

Neither on the related Gitcoin's project page (Vocdoni):

https://gitcoin.co/grants/202/vocdoni-decentralized-anonymous-voting

So, the DAI I donated I don't have them anymore, but they are not received by/reflected into the projects where they were transferred to. 

Could you please check this to help me understand what went wrong? 
Thanks
