### ISSUE TITLE
[BUILD] As a tribe member, I want to know the prizes from the tribe when participating in a hackathon

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7021]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a tribe member, I want to know the prizes from the tribe when participating in a hackathon

As a sponsor, I want my tribe members to automatically be notified the prizes available when I'm sponsoring a hackathon so that they are interested ot participate

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

IF we engage with developers already interested an org, then sponsors will have a great hackathon turnout, because developers will participate in the sponsored hackathon.

IF we do this, it'll Increase number of hackers registering for a hackathon.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

If a sponsor signs up for a hackathon, email to current tribes members and let them know that the prizes offered by X sponsor in a hackathon

### Current Behavior
[comment]: # (Describe what actually happened.)

No automatic email

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Automatic email sends out as soon as a hackathon starts

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Build email

### Data Requirements

Increase in number of registered hackers per hackathon

![85852050-73b5af00-b7e2-11ea-8992-c38b7f98ebf0](https://user-images.githubusercontent.com/19514207/86129442-4ab05980-bb15-11ea-9238-bc995ab36a85.jpg)

**Comment by willsputra** [comment]
**Email Details**

- This should populate using send grid
- Build email so that it works by manual population of information through the Gitcoin Admin
- Email body should be editable and have an editable title for each section.
- An admin should be able to upload an image where the Hackathon image is displayed
- Prizes will be pulled in from that specific sponsor and that specific hackathon
- 'Join Hackathon' goes into the hackathon onboarding page
- 'View Prize' goes into each prize detail page
- Must be responsive

**Comment by PixelantDesign** [comment]
@sebastiantf ^

**Comment by sebastiantf** [comment]
Hey @PixelantDesign, @willsputra I think I'm a bit confused rn. Which email should be built? Because the designs shown on #6942 and here #7021 are different but requires to be sent when an org signs up for a hackathon. Can you please clear this up?

**1 or 2 or Both**

**1.**
![](https://user-images.githubusercontent.com/19514207/85405022-64d8bd80-b592-11ea-8be3-10a687a482e5.png)

**2.**
![](https://user-images.githubusercontent.com/19514207/86129442-4ab05980-bb15-11ea-9238-bc995ab36a85.jpg)

**Comment by willsputra** [comment]
@sebastiantf  
https://github.com/gitcoinco/web/issues/7020 is sent when the hackathon is announced

https://github.com/gitcoinco/web/issues/7021 is sent when the hackathon starts (cos usually prizes are shown when the hackathon starts)

what do you think @PixelantDesign ?

**Comment by sebastiantf** [comment]
Thanks @willsputra. If you don't mind, I would like some more clarifications:

1.
    * In #6942 @PixelantDesign says 
    > * This should populate using send grid
    * In #7020 (here) @willsputra says 
    > * This should populate using Mailchimp

    Which one should be used? I've seen how sendgrid is being used to send the Daily and Weekly Emails, but I haven't figured how Mailchimp API is actually used to send emails, other than using it to keep a list of Hackers. Maybe someone from @gitcoinco/engineers can shed some light?
2. > * Build email so that it works by manual population of information through the Gitcoin Admin
    > * Email body should be editable and have an editable title for each section.
    > * An admin should be able to upload an image where the Hackathon image is displayed

    Do these emails really have to be manual? All the dynamic data that's to be included in the emails (Org name & image, Hackathon name & image, etc. ) seems like they could be fetched automatically, along with some static text (_"As a member of their tribe..."_) and would be similar to how Daily Emails are automatically populated and sent. So does it actually need the manual population via the Django Admin, like how the body for the Weekly Email is populated?
