### ISSUE TITLE
Bug Donate not showing in the grant

### ISSUE THREAD

**Issue by matimaone1** [gitcoinco/web#7034]
Hello, 
I ask my brother to donate to my grant(Last night) . and he do but I don't know why it doesn't appear(show) in the grant. but the transaction was done in etherscan!
https://etherscan.io/tx/0xbd79f723f84439e80ec4bc1da89f5b1b5068d46f3c22f1c0e2870c5e8a198fc4

**Comment by owocki** [comment]
can you please fill out the template, what account, what browser, what web3 wallet,etc

**Comment by matimaone1** [comment]
My account : https://gitcoin.co/matimaone1
Brother account: https://gitcoin.co/hakiminho
Grant link : https://gitcoin.co/grants/911/1-minute-learning
OS: Windows 10
Browser: Google chrome
Wallet :Metamask wallet
Transaction on etherscan :  https://etherscan.io/tx/0xbd79f723f84439e80ec4bc1da89f5b1b5068d46f3c22f1c0e2870c5e8a198fc4

**Comment by owocki** [comment]
hmm i can ingest this txn manually, would be great to figure out the root cause for this tho 🤔

**Comment by owocki** [comment]
hmm are you certain that this txn was broadcast from metamask?   the from address for the txn is diff from the txns 

https://etherscan.io/tx/0xbd79f723f84439e80ec4bc1da89f5b1b5068d46f3c22f1c0e2870c5e8a198fc4

**Comment by owocki** [comment]
hmmm i dont think this a gitcoin checkout txn, https://etherscan.io/tx/0xbd79f723f84439e80ec4bc1da89f5b1b5068d46f3c22f1c0e2870c5e8a198fc4 goes to 0xbd79f723f84439e80ec4bc1da89f5b1b5068d46f3c22f1c0e2870c5e8a198fc4 which is not the splitter contract we use

**Comment by matimaone1** [comment]
Yeah sure it from metamask. here is the wallet of my brother:
https://etherscan.io/address/0x427215ee94f0e0ea312f007c421db1cda6b20a80
you can see an out transaction to the grant smart contract. but there is no
transaction in the gitcoin grant !!

Le mer. 1 juil. 2020 à 20:13, Kevin Owocki <notifications@github.com> a
écrit :

**Comment by svenrenhoek** [comment]
Same issue here:

donor account: https://gitcoin.co/svenrenhoek
grant account: https://gitcoin.co/grants/835/octanolabs
OS: Win10
Browser: Chrome - Version 83.0.4103.116 (Official Build) (64-bit)
Wallet: MEW CX
Tx: https://etherscan.io/tx/0x7cfef210d0b61865024f1a3655326cb2eaa6adc0eba9e4d41f6aa6555e511061

Not showing up in https://gitcoin.co/grants/835/octanolabs?tab=transactions

**Comment by matimaone1** [comment]
Hey @owocki,
Did you find any solution to this issue?
Thanks

**Comment by owocki** [comment]
no, i still need reproduction steps.

we can ingest those grant trasnactions before we calculate the final match amounts. but i need to pin down the repro steps to solve the root issue.

**Comment by owocki** [comment]
Just ingested those txns.  Stilll looking for a root cause, on the issue.. but we've rewritten the txn ingester for round 7 so im hopeful that it wont be an issue in the future.
