### ISSUE TITLE
“Prize explorer” link is broken on all hack pages

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7044]
Example: https://gitcoin.co/hackathon/unitize/onboard

![image](https://user-images.githubusercontent.com/23297747/86393987-d0deb400-bc6b-11ea-8f21-c2d5f7db89e6.png)

**Comment by developerfred** [comment]
I fixed this issue @vs77bb

**Comment by thelostone-mc** [comment]
This has already been fixed in live ! 
https://gitcoin.co/hackathon/unitize/onboard
