### ISSUE TITLE
I've redeemed a tip and the transaction was sent to me with 12.4 Gwei

### ISSUE THREAD

**Issue by CrystalPony** [gitcoinco/web#7050]
Hi, I've redeemed a tip and the transaction got sent to me with 12.4 Gwei gas price. The current standard fee is 40 Gwei, and safe fee is 30 Gwei according to https://ethgasstation.info/ 

https://etherscan.io/tx/0xc1043bc19e32aad9ea66f97125297d94739b7732e0ef70aa0200e2c70008e811

**Comment by artob** [comment]
@CrystalPony Did you ever receive your tip? I'm in the same situation, though my transaction has only been stuck for 2 days as yet.

**Comment by CrystalPony** [comment]
@artob Yes, I posted in Townsquare in gitcoin chat and someone contacted me and helped me.

**Comment by artob** [comment]
@CrystalPony OK, glad to hear :+1: I shall endeavor to reach someone.

**Comment by owocki** [comment]
sigh; we need to move the tips architecture to L2 :P

@artob whats your tip link ? I can probably unlock it for u

**Comment by artob** [comment]
@owocki Thanks for looking. The link "tip received" link is https://gitcoin.co/townsquare?tab=activity:357898 and the ETH transaction is https://etherscan.io/address/0x6fb2773c2f4a924cb13c6d053f963df8ce5a2c65

**Comment by owocki** [comment]
ah shoot yeah that txn has been pending for "2 days 6 hrs ago";  looks like it was spent with 0.00000004 Ether (40 Gwei) - we might have to contact the issuer and have them re-issue

**Comment by artob** [comment]
@owocki Do you need any action from my side, or you are handling it?

**Comment by owocki** [comment]
you can either wait for the gas fees to come down so the txn clears or you need to contact the issuer and let them know they need to speed up the txn.   sounds like u want to do the latter

@arweave-sophie would you mind resubmitting the tx ? thanks!

**Comment by artob** [comment]
@owocki I contacted @arweave-sophie and there's nothing she can do from her end. From their end the transaction has been confirmed: https://etherscan.io/tx/0x64cb6a21766d16a1d6121ae328c28bb84362f20ffe2c8e61ea2c8fc078f443db

**Comment by owocki** [comment]
oh shoot; sorry i thought that the txn arweave sophie sent was the pending one, but instead its ur redemption txn.

ok i just reset your tip redemption link ( https://gitcoin.co/tip/receive/v3/QmU3ejuB9cpDwyzxQ4vhzMGSW3RMvi48GLcAZbPXaaxNAj/0x64cb6a21766d16a1d6121ae328c28bb84362f20ffe2c8e61ea2c8fc078f443db/mainnet ) and added more gas to the proxy account. try now!

**Comment by artob** [comment]
@owocki Thanks a bunch, that cleared the bounty payment! All sorted now.
