### ISSUE TITLE
Bulk Create (Hackathon) Bounties

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7053]
### Who

As a hackathon funder with multiple bounties to post, I'd like the ability / experience to fund 2-10 bounties in one go. 

Now, with no standard bounties, we'll be able to do so without any on chain tx's. 

### What 
Bulk Create bounty experience - Maybe test with Hackathon customers first. 

### Why
Less time consuming for power users. 

@willsputra @PixelantDesign curious your thoughts here

**Comment by PixelantDesign** [comment]
agree with this! I was just mentioning this to @octavioamu and @willsputra on Friday.

**Comment by thelostone-mc** [comment]
- Would it be applicable for just hackathon bounties 
- Would it be wise to take this decision after letting hackathon sponsors use the new hackathon form as it's been rolled out
  AKA let them use the new flow and get comfortable with it before asking them these questions.

**Comment by octavioamu** [comment]
I believe even without std bounties limitations the process of creating a bounty involve a lot of data and attention form the sponsor side to understand, really I don't see a bulk create helping sponsors and actually complicating a lot the UI and validations needed on that page. IMO that will actually make the experience of creating a bounty hard again and not sure how much people need to create multiple bounties at once, also each bounty is unique with his own issue link, and data.

**Comment by PixelantDesign** [comment]
We do know that sponsors generally fund multiple bounties. It'd be nice to be able to fund it one time. Would require a very elegant ux given what @octavioamu mentioned above. 

Agree with @thelostone-mc on lettiing the new hack form run for a bit.
