### ISSUE TITLE
as a user, i want upvotes / downvotes on tool page, so i can cast my vote on gitcoin's tool direction

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#706]
# Description
as a user, i want upvotes / downvotes on tool page, so i can cast my vote on gitcoin's tool direction

this could perhaps allow us to see which tools have the community's buy in and which do not.

# bounty

## backend

1. move the tools from hardcoded dict in the views to having its own model
2. create a new model called 'toolvote' which can be direction == ('up', 'down') and a fk to profile

## frontend

1. create an upvote and downvote bottom in the tool module [(example)](http://bits.owocki.com/0s1B0Y1a0F0t/Screen%20Shot%202018-03-27%20at%204.50.13%20PM.png)
2. hook it up via ajax to record `ToolVote`s.  user must be logged in to record a toolvote and may only vote once per tool.  
3. if a user votes a tool up and then votes it down, or visa versa, the latest vote will be recorded for each.
4. each tool module will show the score between the upvote / downvote buttons

**Comment by kziemianek** [comment]
Would You mind if I take care of it ?

**Comment by owocki** [comment]
pls do!

edit: whoops. commented after the PR was submitted :P

**Comment by mbeacom** [comment]
Moving forward, maybe we can implement a flow for populating tools for voting based on a GH issue label or something, so we can ping the community on different product ideas and get feedback regarding usefulness before we begin dev.

**Comment by abitrolly** [comment]
https://gitcoin.co/tools

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.17 ETH (117.66 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/706/553).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
