### ISSUE TITLE
Tribes Feature: Contest + Cooperative Bounties

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#7068]
### User Story

As a Tribe maintainer, I want there to be no limits on how I interact with hackers that are part of my tribe.

### Why Is this Needed

Given that we are deprecating contest and cooperative bounties, we need a way to ensure that Tribes customers can still access these features in full. 

### Description

@octavioamu has created a new bounty form, which is where sponsors/tribes paying customers will go to open their bounties. As far as I know, if they're a paying tribe member, they're most likely doing a hackathon with us, so this form is the starting point. e.g (https://gitcoin.co/hackathon/clarity/new)

@thelostone-mc has removed contest and cooperative bounties on the form, but it seems like part of the ask is that for paying tribes customers, those options remain available for the regular explorer. Essentially, non-paying customers won't have access to all the types listed on this page: https://gitcoin.co/hackathon/clarity/new

### Definition of Done
- [x] New Bounty Form  - https://github.com/gitcoinco/web/pull/7086
- [x] Prevent spam attacks by removing access to contest and cooperative bounties for non-verified posters (Tribes maintainers) - https://github.com/gitcoinco/web/pull/7112
- [ ] Hackers who are part of a given Tribe should still always be able to apply to bounties within that Tribe
- [ ] If a poster is not verified (a Tribe maintainer) they may only review a maximum of 5 applicants on their bounties

**Comment by owocki** [comment]
from the slack convo about this ( https://gitcoincore.slack.com/archives/CNTH3RSF6/p1595010700182900 ) the path forward:

feature spec:
- make the main bounty form more feature limited / free (no contest bounties, no coop bounties).
- add an explainer that if you want PRO features (contest, cooperative, many applicants, featured bounties) to contact scott
- remove the fee from the main bounty form
