### ISSUE TITLE
^register_hackathon/ endpoint should validate whether a user has already registered for a event

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#7070]
**Describe the bug**

Duplicate `HackathonRegistration`  instances created when multiple requests are sent to the ^register_hackathon/ endpoint.

**To Reproduce**

In my local docker build, I create a hackathon event, then I go to the onboarding page and click "Join Now". I continue to click and each click sends new request. 

**Expected behavior**

There should not be duplicate `HackathonRegistration` for the same user under the same hackathon. 

**Solutions** 

The `hackathon_registration` should check if there is aleady an `HackathonRegistration` instance for the user under the given hackathon event and if so then an error should be returned or nothing should happen.

Furthermore, on the user frontend, any only a single POST request should be sent to ^register_hackathon/ and the page should either refresh, redirect somewhere else, or show a success alert. For example, on the hackathon onboarding page, it may be prudent to disable the "Join Now" button after the first click and the page should show a success alert, redirect to the prize page, refresh to onboarding page, or a combination such as: disable button, show success alert, then automatically redirect to prize page after a few seconds if applicable, otherwise refresh the page.

**Comment by PixelantDesign** [comment]
Thanks @walidmujahid! Are you interested in helping us with this one?

**Comment by walidmujahid** [comment]
> Thanks @walidmujahid! Are you interested in helping us with this one?

Yes. I will be working on this unless someone had grabbed it. I should have posted yesterday my intention.
