### ISSUE TITLE
Participants Experiment fixes

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7084]
- [ ] Put in a default message in the input field for users that don't enter a message during registration. 
"I'm a new hacker! Great meet you all!"
- [ ] Remove #intro  button from prizes view
- [ ] Remove background image on the participant card - makes it difficult to read. Leave top bar design.
- [ ] Profile picture should be centered in the circle
<img width="1109" alt="Screen Shot 2020-07-10 at 10 00 55 AM" src="https://user-images.githubusercontent.com/238235/87184225-9d2c0b80-c2b5-11ea-93de-dacbd6889d43.png">

follow up  to #6443

**Comment by PixelantDesign** [comment]
@developerfred @sebastiantf ^ ?

**Comment by sebastiantf** [comment]
I can look into this @PixelantDesign 👍🏻

**Comment by developerfred** [comment]
@PixelantDesign my WIP in https://github.com/gitcoinco/web/pull/7088

**Comment by PixelantDesign** [comment]
@developerfred thanks! I removed the second bullet from the ticket. No need to worry about that. Will you please share a video of all of the changes?

**Comment by developerfred** [comment]
@PixelantDesign Sure!

**Comment by PixelantDesign** [comment]
@developerfred adding one more thing to the list

some participants cards show which hackathon the person is participating in, and some cards don't. Could we fix so that all cards show which hackathon the registrants is part of?

<img width="821" alt="Screen Shot 2020-07-12 at 1 58 08 AM" src="https://user-images.githubusercontent.com/238235/87240280-378b6c80-c3e6-11ea-8e28-2d26f126d3f5.png">

**Comment by developerfred** [comment]
@PixelantDesign  yes! I'll investigate why is this happening?

**Comment by developerfred** [comment]
@PixelantDesign 
- [x] show hackathon tags a6b07088e...987a9abb3

**Comment by PixelantDesign** [comment]
awesome!
