### ISSUE TITLE
As a Gitcoin hackathon operator, I want to consolidate comms and data collection so it's not a crazy scramble at the beginning of every hack.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#7090]
### User Story

As a Gitcoin hackathon operator, I want to consolidate comms and data collection so it's not a crazy scramble at the beginning of every hack.

### Why Is this Needed

Let's reduce operations overhead.

### Description

1. hackathon order form
    - sign order form
2. data collection
    - fund & post prizes
    - add token & conversion rates if not present
    - promotional typeform
        - what is success for them
        - logo 1
        - logo 2
        - style guidelines
        - description for kudos request
        - quest article example
        - daily action example
3. hackathon start comms
    - internal promo push pre-hack announcement/blog post
    - internal promo push hack start announcement/blog post
    - internal promo push gitcoin community push
    - internal promo push gitcoin newsletter #X
    - sponsors onboarding call & meet and greets
    - sponsor workshop scheduled through calendly
    - sponsor announcement tweets
    - sponsor livestream
    - external promo push - reddit, discord, dev groups, etc
    - email to full 4.5k hacker list
    - email to registrants on launch day
    - hackers team formation call
4. hackathon mid comms
    - gitcoin chat check ins
    - gitcoin chat weekly / mid-hack check ins 
    - email to registrants denoting weekly & halfway mark
    - email to warn 48/72 hours until deadline
5. hackthon end comms
    - send submission links
    - ping on judging/winners
    - demo day webinar
    - airdrop kudos
    - retro blog post/showcase
    - send retro report
    - send retro interview
6. hackathon scramble
    - scramble plan bulk inviting hackers
    - scramble plan gitcoin users directory
    - scramble plan person reachouts

### Current Behavior

Our current state of affairs with regards to hackathon start, middle, and end communications and actions that our operations team has to take.

### Expected Behavior

1. hackathon order form
    - sign order form
2. data collection
    - fund & post prizes
    - add token & conversion rates if not present
    - promotional typeform
        - what is success for them
        - logo 1
        - logo 2
        - style guidelines
        - description for kudos request - `ideally Mladen has access to kudos uploads and mints Kudos`
        - quest article example - `ideally sponsor creates own quests`
        - daily action example - `ideally sponsor creates own actions`
        - specific text you would like announced 
        - best 2 days for onboarding workshop - `ideally we set up a calendar, sponsor comes & signs up for slots`
        - best 2 days for sponsor <> hacker meet and greets - `ideally we set up a calendar, sponsor comes & signs up for slots`
        - best 2 days for workshops - `ideally we set up a calendar, sponsor comes & signs up for slots`
        - best 2 days for sponsor livestream  - `ideally we set up a calendar, sponsor comes & signs up for slots`
        - best 2 days for demo day webinar - `ideally we set up a calendar, sponsor comes & signs up for slots`
3. hackathon start comms
    - sponsor onboarding workshop - `sponsor & gitcoin show up on agreed date`
    - internal promo push pre-hack announcement/blog post - `use template w/ sponsor specific text`
    - internal promo push hack start announcement/blog post - `use template w/sponsor specific text`
    - internal promo push gitcoin community push - `use template`
    - internal promo push gitcoin newsletter #X - `use template`
    - sponsor announcement tweets
    - sponsor <> hacker meet and greets - `sponsor & gitcoin show up on agreed date`
    - sponsor workshop - `sponsor & gitcoin show up on agreed date`
    - sponsor livestream - `sponsor & gitcoin show up on agreed date`
    - external promo push - reddit, discord, dev groups, etc
    - email to full 4.5k hacker list
    - email to registrants on launch day
    - hackers team formation call
4. hackathon mid comms
    - gitcoin chat check ins
    - gitcoin chat weekly / mid-hack check ins 
    - email to registrants denoting weekly & halfway mark - use template
    - email to warn 48/72 hours until deadline - use template
5. hackthon end comms
    - send submission links 
    - ping on judging/winners
    - demo day webinar - `sponsor & gitcoin show up on agreed date`
    - airdrop kudos
    - retro blog post/showcase
    - send retro report
    - send retro interview
6. hackathon scramble
    - scramble plan bulk inviting hackers
    - scramble plan gitcoin users directory
    - scramble plan person reachouts

Changes under expected behavior have more to deal with sponsors giving us as much data to reduce the back and forth, so all Connor & Justin have to do is focus on low-level personal touchpoints that can't be automated, and spend less time back and forthing trying to get scheduling done.

### Definition of Done
TBD

**Comment by frankchen07** [comment]
@connoroday - would this new typeform be of help to you? I've tried doing more data collection on it, but if it's not useful we'll have to revisit where the bottlenecks here would be for you: https://admin.typeform.com/form/NE7oDkwT

- added best 2 days for workshop dates so you don't have to back and forth as much
- added best 2 days for demo day
- added best 2 days for livestream
- fixed some image assets
- clarified some questions

**Comment by jdorfman** [comment]
LGTM, I would love to eventually have confirmed dates automatically create events in [AddEvent](https://www.addevent.com/documentation/events-api). We use them to create this:

![image](https://user-images.githubusercontent.com/398230/88816750-96384080-d171-11ea-8a02-ed57240eabc5.png)

**Comment by frankchen07** [comment]
@connoroday - should I be up to date with AddEvent or do you already have coverage there?

Is this a feature of AddEvent, or something we have to do?

**Comment by jdorfman** [comment]
@frankchen07 I think @connoroday got it working by syncing Google Cal with AddEvent so we are good there for now. @connoroday please correct me if I'm wrong.
