### ISSUE TITLE
Wrong link in email footer

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7091]
**Describe the bug**
In the footer of the Weekly email, "New Wallet? Click here to update Payout Address." links to http://link.codefund.io/ls/click?... instead of https://gitcoin.co/settings/account

**Comment by simeon4real** [comment]
There are other links there that redirects to ethicalAds

**Comment by owocki** [comment]
this was something that got messed up when @coderberry shut down codefund on friday.  we have since fixed the issue in our sendgrid settings.. and should not be an issue go forward

**Comment by thelostone-mc** [comment]
Closing as this is now resolved
