### ISSUE TITLE
Add Kudos Tab to Tribes Light

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7092]
### What 
- [ ] Port over Kudos tab from old org to tribes light
- [ ] Must be responsive

### Why
Our customers will not be able to see their Kudos

**Comment by owocki** [comment]
is it easy to just port over all existing tabs? 🤔

**Comment by PixelantDesign** [comment]
can't do this just yet since we don't have a concept of shared kudos wallet.

**Comment by owocki** [comment]
neither does the org model.. and that has a kudos tab
