### ISSUE TITLE
Tribes V2 - Next Iteration  09/11

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7098]
### Why

**For sponsors**, Tribes is a one stop shop where sponsors can manage their open source brand, stay connected with hackers, see all of the great hackathon projects that developers have created, understand the open grants associated with their company and more! All on Gitcoin!

Incorporate and connect more of the core features to make it useful.

**For hackers/developers**, Tribes is a one stop shop on Gitcoin to learn about an organization, understand what the organization is about, communicate with sponsors, see all of the great people contributing to this org, see all of the great projects being built, find meaningful open source work (bounties or hack) that they can contribute towards, and more!

### What

In  the next iteration of Tribes, we would like to improve the following to ensure sponsors have a good experience to do the above.

- [x] **Tab Organization**  - Combine tabs (Projects & Grants)
- [ ] **Projects**  - Add truncation to each project showing  3 lines of copy, add ability to show more/show less
- [x] **Projects** - Display projects that have been converted to grants.
Left rail filter: DisplayProjects with Grants and Hackathon  Projects.
- [x] **Projects** - Build Convert to Grant Flow
- [x] **Projects** -  Denote Grants with a grant badge in the upper right hand corner for hack projects that have been converted.

Nice to have  if time permits
Break Townsquare related into a new PR
- [ ] **Tribe Townsquare** - Rename tab to Tribe Wall
- [ ]  **Tribe Townsquare** - Improve feed sorting, HMW surface top 10 posts on an org? Ideas: number of likes in the last  7 days

Not on here is improvements to people  tab. Sending a message would be ideal  but we should reconcile  with what we  are doing on user directory.

### Additional Materials

<img width="860" alt="Screen Shot 2020-07-14 at 2 58 48 AM" src="https://user-images.githubusercontent.com/238235/87394588-f7f78880-c57d-11ea-9e64-345544e6c677.png">

Convert to grant flow WIP
![Slice 1](https://user-images.githubusercontent.com/19514207/87412921-2b78f800-c5fc-11ea-9509-91e40793edde.jpg)

**Comment by willsputra** [comment]
Convert to grant flow WIP
![Slice 1](https://user-images.githubusercontent.com/19514207/87412921-2b78f800-c5fc-11ea-9509-91e40793edde.jpg)

**Comment by willsputra** [comment]
longform post
![longform](https://user-images.githubusercontent.com/19514207/87567607-0c12c580-c6f7-11ea-956d-5acc60959c77.jpg)

**Comment by octavioamu** [comment]
can we show the open story on a modal? 
something like that? kind of "zend mode" where you just focus on the story and also can like it everywhere out of gitcoin?
Something like a medium post, but also without taking all the towsquare space. 
![image](https://user-images.githubusercontent.com/1358093/87698140-75cbb780-c769-11ea-9bed-4a5fd29891bc.png)

**Comment by PixelantDesign** [comment]
>can we show the open story on a modal?
Yes, when  we get to this feature @octavioamu

**Comment by sanchaymittal** [comment]
Setting up the ETA for time one 3-7 days.

**Comment by PixelantDesign** [comment]
@sanchaymittal could we leverage the quality filter on tribe townsquare that @owocki has implemented on main townsquare?

**Comment by PixelantDesign** [comment]
**Convert to Grant**

Who can create a grant? Winner, sponsor, Gitcoin admin

When project is converted to a grant - what happens to the project?
- Preserve activity
- Note on activity when the project was converted too a grant
- Note who converted to a grant

**Comment by PixelantDesign** [comment]
Per discussion last week with @danlipert and @octavioamu on tech approach, we will route users from the single project page and take them to the grant page to create a new grant repopulating the fields with project info. From there users will create the grant. The grant will then exist like a normal grant on Gitcoin Grants product.
