### ISSUE TITLE
Hacker Profile Update - DRAFT

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7099]
### User Story

As a sponsor I'd like a simpler, more organized view of a hacker profile.

### Why Is this Needed

There is a lot of information on the profile currently that can be organized to focus on answering the core questions of a hackathon sponsor.

### Description

Enhancement

### Current Behavior
Old Orgs page

### Expected Behavior
Updated Orgs Page

### Definition of Done

- [ ] Re organize the content on the orgs page
- [ ] Make CTAs clear
- [ ] Add related devs module 

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

This design is WIP
Needs reviews, trust, skills, experience section and responsive view

<img width="836" alt="Screen Shot 2020-07-14 at 3 21 25 AM" src="https://user-images.githubusercontent.com/238235/87396641-2165e380-c581-11ea-9e4e-4c7af781615e.png">

**Comment by developerfred** [comment]
Like Github Profile Awesome!
