### ISSUE TITLE
User Directory Improvements

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7104]
### User Story

~~Use Case 1: As a Gitcoin operator, I'd like to be able to send cohorted communications and DMs based on specific user characteristics.~~

Use Case(s) 2: As a hacker, I'd like an easy way to find hackers that have similar or relevant interests to me within a given hackathon. I'd also like sponsors to be able to find me and know what I'm all about. 

As a sponsor, I'd like an easy way to see the characteristics of hackers who have joined my hackathon.

### Why Is this Needed

~~Use Case 1: Target communications and email marketing for specific cohorts. As of 2020-08-04, we will stop any work related to this use case, and instead look into possible marketing platforms instead, in order to avoid rebuilding the wheel.~~

Use Case 1: Finish elastic search and CSV download capabilities on the user directory query.

Use Case 2: For the Filecoin hack, use case #2 has been upped in priority, as this use case serves more as a virtual rolodex that assists in the mingling of hack sponsors <> hackers and hacker <> hacker.

### Description

Use Case 1: Enhancement to https://gitcoin.co/users for elastic search & csv downloading.

Use Case 2: Finalization of the participants tab

### Current Behavior

The user directory is just registrants with the old user directory card, or a greyed out participants tab if the hackathon has not yet started.

### Expected Behavior

use case 1:
- [ ] elastic search
- [ ] csv download capability

use case 2:
- [ ] if registered, show up in the participants tab
- [ ] exclude Gitcoin core team members
- [ ] sort by (TBD)

surface relevant information from their registration questions:
- [ ] skills
- [ ] hackathon specific interests from the registration questions
- [ ] bounty type specialization? (TBD)
- [ ] bounties/hack bounties completed? (TBD)
- [ ] contact & follow

### Data Requirements
- [ ] increased impressions on this tab
- [ ] track clicks on this page
- [ ] lagging metric: increased number of relationships

### Additional Information

<img width="1479" alt="Screen Shot 2020-07-28 at 12 35 27 AM" src="https://user-images.githubusercontent.com/238235/88619854-841faa80-d06a-11ea-951c-85f630ed019d.png">

**Comment by owocki** [comment]
what does @connoroday think of gitcoin.co/users ? 🤔

**Comment by octavioamu** [comment]
Why winners are more relevant for the one filtering?
I think need to be based on bounties en general, being that bounties from hackathons or not
Also a good opportunity to onboard contributors who never participated on a hackathon.

Originally also this list of users should show on the first rows the contributors who already worked with me (seems is broken).

**Comment by owocki** [comment]
> I think need to be based on bounties en general, being that bounties from hackathons or not


you could generalize this by saying "earners of X"  where X is 
- all
- bounties
- hackathon
- grants
- tips
- kudos

easy to do with the dashboard.models.Earnigns model too

**Comment by frankchen07** [comment]
ill add that we want the tool to be as useful as https://metabase.gitcoin.co/question/690

as a place where we're compiling all metrics for users

**Comment by owocki** [comment]
@frankchen07 how validated is the query results to that metabase?

i've been using complicated JOIN querys for my sybil protection work and  i like it a lot. i could see using a JOIN query as the basis of a future revamp of product oriented gitcoin.co/users ; but only if the juice is worth the squeeze (this is all the info that potential users want)

**Comment by frankchen07** [comment]
I'd say pretty validated, it won't be horrendously wrong (>90%). It's quite a big query with joins because I'm pulling for a ton of tables from prod, and appending information to each user.

If you're going to use it, I think it's worth some QA time on my end to really give you a good answer in confidence.

**Comment by owocki** [comment]
i'd need to discuss with @gitcoinco/engineers if thats event the direction they want to go

**Comment by owocki** [comment]
hmmmmm actually this query is too slow (~ 10 seconds to load) to use as the user directory.  maybe we could build it & cache it once per night though..

**Comment by PixelantDesign** [comment]
**Messaging**
- Add ability to send custom freeform message in user directory
- Change invite to bounty button to contact
- Add guardrail for when user tries to contact twice in short period of time

**Filters**
- Fix leaderboard ranking numbers, why is it a comma? 1-5? Need to be able to select all.
- How do I filter top 25 ppl on Gitcoin on Leaderboard?
- Change tribe input and make it auto complete tribe name.
    - Need to be able to remove people manually

**Other ideas**
- Hook up Franks metaphase query and make It the heart of user directory

**Comment by owocki** [comment]
> Hook up Franks metaphase query and make It the heart of user directory

i think if were going to do this way, we should start from here.  the `dashboard.views.users_fetch` code would need to be completely gutted to do this, and we could do the remaining of the work on top of this in the new architecture.

curious what @gitcoinco/engineers thinks tho

**Comment by PixelantDesign** [comment]
For Filecoin:

- Updating the modeling using Franks engine
- updating the card display
- change invite to bounty to send a message

<img width="1470" alt="Screen Shot 2020-07-28 at 9 37 10 AM" src="https://user-images.githubusercontent.com/238235/88673008-1dc07980-d0b6-11ea-8ec2-fe29e9792fe4.png">

<img width="1461" alt="Screen Shot 2020-07-28 at 9 37 18 AM" src="https://user-images.githubusercontent.com/238235/88673029-244ef100-d0b6-11ea-8248-fbb068869f0f.png">

<img width="1466" alt="Screen Shot 2020-07-28 at 9 37 25 AM" src="https://user-images.githubusercontent.com/238235/88673044-27e27800-d0b6-11ea-868a-f70edd3a8abe.png">

<img width="1465" alt="Screen Shot 2020-07-28 at 9 37 38 AM" src="https://user-images.githubusercontent.com/238235/88673066-2d3fc280-d0b6-11ea-9a1a-fdb9a51c49ac.png">

**Comment by owocki** [comment]
@PixelantDesign @danlipert @gitcoinco/engineers i spoke to @vs77bb yesterday + we decided that I can YOLO something out for user directory, but my ask for @gitcoinco/engineers and product is that they do the onboarding data ingestion.  ie i wont be building product features to ingest profile info, but i will be building the search/filter/contacting pipeline.

does that work for everyone?

**Comment by owocki** [comment]
my suggestion was is having a download csv
