### ISSUE TITLE
Matic Grants Bug Report

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7106]
Bug Report for the Matic Grants Creation Page: https://gitcoin.co/grants/matic/new

- No confirmation when adding project logo (I didn't know [it was succcessful ](https://gitcoin.co/grants/994/test-project) until the grant was live. 
- Adding team members was greyed out at first. Then, eventually worked once I connected my wallet. Might not want to tie those flows together. 
- Listed as Grant Type Matic / unhidden, but not showing up in the Matic section [of Grants Explorer](https://gitcoin.co/grants/matic?). 

![image](https://user-images.githubusercontent.com/23297747/87582320-3c7f4300-c6a8-11ea-85c3-e87bc0ef01d2.png)

**Comment by danlipert** [comment]
@vs77bb Can you tell me more about the project logo bug? When you add a logo it should update the place where you clicked to add it:
![Screen Shot 2020-07-20 at 7 43 57 PM](https://user-images.githubusercontent.com/869266/87929459-6d54e300-cac1-11ea-8624-48c61fe2b100.png)

It may be the file itself, can you upload the image you used?

**Comment by danlipert** [comment]
@vs77bb ah nevermind it only happens if your wallet is disconnected

**Comment by danlipert** [comment]
Fixed the issues - if you didn't use a web3 wallet to connect when creating a grant previously, then you'd see the issues @vs77bb described, including the grant being hidden as the network field was not set. It now defaults to mainnet
