### ISSUE TITLE
Created Gitcoin Issue with No Funding

### ISSUE THREAD

**Issue by Graeme-Code** [gitcoinco/web#7108]
**Describe the bug**

Hi there, I created Gitcoin issue: 

https://gitcoin.co/issue/gnosis/conditional-tokens-docs/17/100023355

This page was generated without the transaction to fund the issue. I have an invoice asking me to pay the funding but I have no idea how as there is no links or instruction on how to do this once the issue has been created. 

**To Reproduce**

1. Create an issue
2. I'm gonna be honest with you, I don't remember tapping on anything, just re-entering the github issue URL. 
3. Get redirected to gitcoin issue page. 

**Expected behavior**

I expected to be required to fund the issue before it was generated or at least have a link on the bounty options dropdown menu to fund the issue. 

**Desktop (please complete the following information):**

- OS: Mac 10.14.6
- Browser: Chrome
- Browser Version:  83.0.4103.116

**Comment by octavioamu** [comment]
@Graeme-Code Actually this is not a bug, we are moving out from standard bounties contract to make the things more flexible and more friendly for funders and contributors. 

As a sponsor on a hackathon your bounty (prize)  is not required to be funded on creation anymore. 
Once you get people submitting work (they also will not need to pay gas to submit), when you decide the winners then you will get a button to do the payment(s). 

Ping me if you have more questions.

**Comment by Graeme-Code** [comment]
Oh, its a feature! 

Awesome, could do with a bit of info/context regarding new process would help, but sure you guys are on it.

**Comment by octavioamu** [comment]
Yes I already informed to the internal team about communicate this to hackathon Sponsors since some of you are already familiar with the old process of funding a bounty. 
Thank you!!!

**Comment by octavioamu** [comment]
Also please feel free to give any feedback about the new process. 
I hope the experience get a lot better from funding to payout.
