### ISSUE TITLE
DAI grant donation not showing up in wallet

### ISSUE THREAD

**Issue by DreadKnight** [gitcoinco/web#7109]
I've opened up a grant a while ago https://gitcoin.co/grants/916/ancient-beast
I've received a DAI donation (did added the cryptocoin type in my metamask before making the campaign), but never seen it in my wallet, thought I would getting after a while or campaign/round end.
Today I've received another ETH donation and it showed up in my wallet in no time, so what about the DAI?
The contributors number shows up as 1 in the tab and such, but it lists both...
Though in transactions it shows that DAI one as failed, was that guy a scammer/spammer just to draw attention to his thing?
Or is there something bad going on with gitcoin or on my end?
Also, if I have the grant to accept any ERC20 token, is it enough to have Metamask or do I need to do anything special, like add each coin? I'm new to this stuff overall, so I'm still trying to figure things out. Thanks for any help!

I've had plenty of bad experience with BAT and I'm not too keen about crypto volatility, so was considering of getting a lot of DAI to fund bounties for my main game project (Ancient Beast), switching away from IssueHunt, but want to make sure I understand things properly and that they actually work.

**Comment by owocki** [comment]
per the transactions tab it looks like the donation failed https://bits.owocki.com/X6uo1pjw

**Comment by DreadKnight** [comment]
@owocki I've noticed that. But don't really know what it means, as there's not a reason/error at all...
Hence questions: how does it actually get to fail? anything I did wrong? how can I fix? If the sender needs to do something, it's probably not going to happen, oh well...

**Comment by owocki** [comment]
looks like the txn ran out of gas https://etherscan.io/tx/0x0e32d726f32b84dd8e77b2eccbc8a65f9c7f031137372906d392344038b19015

maybe @hexpumptseth3 will recontribute

**Comment by DreadKnight** [comment]
Well, I doubt he will, guess I got unlucky. At least it wasn't way more xD
It's a tad strange to need ETH to be able to send DAI around. Would expect just to charge a bit more DAI instead to make sure the whole operation goes smoothly.
