### ISSUE TITLE
Build Organization Permission on Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7110]
### User Story

As a sponsor of gitcoin hackathons, I'd like an easy way to mange my organization's permissions and people.

### Why Is this Needed

Org permissions is working in a funky way.
In order for the org to show on the profile, the org's people tab, user must be set to public

managing ownership of the people
even though we pull gh api info, we're not getting all of it because people are 
listed as private on organizations, and we can't force them to say public

### Description

Build a way to manage privileges on Gitcoin

### Current Behavior
Doesn't exist

### Expected Behavior
Make it work :)

### Definition of Done

- [ ] come up with a tech approach, run by core engineering team
- [ ] implement approved approach
- [ ] post demo/video

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information

api.github.com/users/[user] 
api.github.com/users/[user]/orgs
    data we get from github
    octavio has 4 orgs on github, but only 1 on the api
    in order for the org to show on the profile, the org's people tab, user must be set to public

managing ownership of the people
even though we pull gh api info, we're not getting all of it because people are 
listed as private on organizations, and we can't force them to say public
    - we can manually add core team members to an organization though

another problem, when are we taking actions as 
    - action as an organization
    - action as a user

administrator privileges on github is different than administrator privileges on gitcoin
    - might not be best to reflect github permissions in gitcoin

ideally, disconnecting from orgs
    - people create profile - connect github if they want
    - organizations can create a profile and add people they want
    - organization can grant people 

=========================

    1. org permissions will be added manually on the admin, org creation is still via github - exists already.
    2. org admins can add new people to owners (we then give gitcoin organization privileges (toggle organizations / members)) - (we need to build, remember these privileges are different from github!)

**Comment by PixelantDesign** [comment]
@merwane

**Comment by danlipert** [comment]
I'm wondering if the ideal first step here is to have a wireframe or rough idea of the user behavior before we start implementing the backend and data modeling aspects of this ticket. Most of the backend and data model is probably already there essentially, so if we can reuse what we have that would be great. 

As a rough first step, would we say the need here is: "For a user in a Gitcoin org, they should be able to add and remove other Gitcoin users to/from their org"? Who can do do this, org members, or org admins, and/or org core members? Are we basically replicating the functionality that already exists within the django admin or are we adding some new category of permissions/membership?

**Comment by thelostone-mc** [comment]
I'd lean towards setting up CRUD around a new table organizations
This does set us back a little in terms of feature but helps us build out a stable foundation 

- I'd say we first build out the ability to create org + add folks to them
- Then building the UI for this 
- Write scripts to shift data from profile tribes to the new table 
Build functionality around it 

The end state being 
You have multiple users on the platform (aka Profiles)
and You have organizations (each organization being a collection of Profiles)

**Comment by PixelantDesign** [comment]
I put together the original ticket with @octavioamu and we thought getting the backend set up was first step. But I'm open.

**Comment by danlipert** [comment]
Posting here for posterity from a DM w/ @PixelantDesign :

"So I took another look at this ticket and the comments, I think we can go either way on this, but its likely something we’ll need to kind of circle around on via a few iterations to get it right because there isn’t really a solid spec yet in terms of what the users can do and how they do it. We can probably come up with a cruddy UI that allows people to search for and add/remove a user from an org, then go back into the design and figure what that should actually look like and how it works in terms of permissions, etc."
