### ISSUE TITLE
Top Orgs Leaderboard displaying non-orgs

### ISSUE THREAD

**Issue by jdorfman** [gitcoinco/web#7122]
**Describe the bug**

When I was on Twitter I was excited to see this tweet: https://twitter.com/oceanprotocol/status/1285159529207013376

When I got to the leader board I saw 2 "orgs" that looked like spam accounts (first impression). 

**To Reproduce**

Go here: https://gitcoin.co/leaderboard/orgs?cadence=monthly&keyword=all&product=all

See **@n4k3pj0t9iw & @blog**

**Expected behavior**

**Screenshots**

<img width="1109" alt="Image 2020-07-20 at 1 40 23 PM" src="https://user-images.githubusercontent.com/398230/87984292-97d97880-ca8e-11ea-9d22-f8f1e0547604.png">

**Desktop (please complete the following information):**

- OS: macOS latest
- Browser: Chrome 
- Browser Version: Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

If companies are proud to be on the leaderboard, only show organizations that are actually verified orgs. =)

**Comment by PixelantDesign** [comment]
@developerfred ^?

**Comment by jdorfman** [comment]
This seems to have been resolved. Closing.
