### ISSUE TITLE
For round 7 calcs, make it so that we DONT re-use the Round 6 calcs anymore.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7128]
For round 7 calcs, make it so that we DONT re-use the Round 6 calcs anymore.

Per Vitaliks request.

**Comment by danlipert** [comment]
Something we should remove permanently or should we just "turn it off" for round 7?

**Comment by owocki** [comment]
i think just turn it off; then if vitalik doesnt want it again for round 8 i think we can deprecate it entirely

**Comment by owocki** [comment]
@thelostone-mc @frankchen07 can i mark this as done :P ?

**Comment by frankchen07** [comment]
@owocki, yes you may, aditya removed it when he was making data structure changes
