### ISSUE TITLE
DESIGN - As a round 7 admin, I want incentivized flagging system, so that I can be sure that users are incentivized to do the work of finding frauds.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7129]
From Vitaliks Round 6 wrap up post:
>  One could even imagine incentivized reporting: anyone can lay down a deposit and flag a project as fraudulent, triggering an investigation; if the project turns out to be legitimate the deposit is lost but if the project turns out to be fraudulent, the challenger gets half of the funds that were sent to that project.

Spec:
```
anyone can flag and account putting in a deposit, and then you (gitcoin) go through and manually check in decreasing order of amount staked, and depending on the result:

* Is a sybil: all money donated by that project is confiscated, and the flaggers share 50%
* Is probably not a sybil: no result, deposits returned
* Is definitely not a sybil: deposits are confiscated, and put into the round's matching pot
```

**Comment by danlipert** [comment]
What happens to the other 50%?

**Comment by owocki** [comment]
goes back to pool

**Comment by owocki** [comment]
@apbendi idea: maybe grant owenrs could stake their own funds when they post a grant to show that its not fraudulent.

**Comment by owocki** [comment]
chatted with a few people about this; and we'd need a staking infrastructure/governance infrastructure to do this correctly. so pushing it back to round 8
