### ISSUE TITLE
Using docker to setup and got "localhost refused to connect" error, and ReadMe file is outdated

### ISSUE THREAD

**Issue by sunxivincent** [gitcoinco/web#713]
##### Description
I followed the readme to setup gitcoinco using docker approach however failed, there are multiple issues
1) after I tried to Navigate to http://0.0.0.0:8000/, it shows not able to connect, connection refused. Examined the log, found the following errors, I am not sure if I need to do something about the 
PostgreSQL or docker yaml file update ?

pgweb_1    | Connecting to server...
pgweb_1    | Server runs PostgreSQL v10.1
pgweb_1    | Checking database objects...
pgweb_1    | Starting server...
pgweb_1    | To view database open http://0.0.0.0:8081/ in browser
pgweb_1    | Pgweb v0.9.11 (git: c32784e8aebec35c1f68e11bc004f45dedbda283)
pgweb_1    | Connecting to server...
pgweb_1    | Error: dial tcp 172.18.0.2:5432: getsockopt: connection refused
pgweb_1    | Pgweb v0.9.11 (git: c32784e8aebec35c1f68e11bc004f45dedbda283)

2) In readme, there is a "setup database" section, should I do this before running in docker?

3) also seems there is no "local_settings.py" file which mentioned in readme, I can only find "./app/app/settings.py"

##### Environment

* **Browser**:
* **Version**:
* **Subsystem**:

**Comment by mbeacom** [comment]
@sunxivincent Thanks for bringing this to our attention.

Can you please check the updated setup documentation for docker at:  https://github.com/gitcoinco/web/blob/master/docs/RUNNING_LOCALLY_DOCKER.md

Feel free to ping me directly on [Slack](https://gitcoin.co/slack) or comment back here with any questions.

**Comment by sunxivincent** [comment]
would be better to point out if using docker-machine,  the url for accessing gitcoin website is the [docker machine host ip]://8000
docker machine host ip could be retrieved through `docker-machine env`
in DOCKER_HOST
