### ISSUE TITLE
As a Ethereum social media influencer, I want to curate & proudly show "collections" of grants, so that people can contribute to the grants I've put together.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7130]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Ethereum social media influencer, I want to curate & proudly show "collections" of grants, so that people can contribute to the grants I've put together.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
To make more people contribute to more grants.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No collections (though we do have bulk checout)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- When you checkout you can choose to "save a grant checkout as a collection"
- Those collections are saved to your {profile}/grants on you rprofile at the top
- There are "featured' collections on the /grants landing page.
- Check you click a collection you can browse them just like any other category.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
What are the most popular collections?  How many grants checkouts are generated by collections?

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
Would be dope to generate some kind of cool image people can share along with the link, or dynamically generate the Twitter preview for each collection link

**Comment by owocki** [comment]
who wants to build an image collage tool :) shouldnt be hard with PIL :) :) :) :)

**Comment by owocki** [comment]
@PixelantDesign @willsputra

**Comment by willsputra** [comment]
brainstormed a bit on this. thoughts?

additional page that's not here yet:
• a section on someone's Profile that shows their grants collections
• a button in Cart that allows people to add "all grants in this cart to collection"

![grants collections](https://user-images.githubusercontent.com/19514207/89757579-4154dc80-db18-11ea-876d-4db4b88e7984.jpg)

**Comment by owocki** [comment]
thanks for taking a stab!

some thoughts:
1. on the grants index page, there should def be a 'see all collections' filter.
2. lets not bother with 'add grant to your collection'. i think the add to cart functionality + 'save cart as collection' functionality should give us all of the tools we need to create groups of grants; without duplicating space on the UI (or code on the backend)

**Comment by willsputra** [comment]
@owocki noted! another stab:

'Save Cart as Collection' flow
![save collection](https://user-images.githubusercontent.com/19514207/89914851-35584000-dc28-11ea-9951-87216a8bf8f1.jpg)


'View Collections' filter on grants index
![filter](https://user-images.githubusercontent.com/19514207/89914989-60db2a80-dc28-11ea-8196-7f26bababc79.jpg)


On profile
![profile](https://user-images.githubusercontent.com/19514207/89914807-22457000-dc28-11ea-949b-24e85ef5c8b0.jpg)

**Comment by owocki** [comment]
this looks great to me!  👍 from me; @PixelantDesign ?

**Comment by PixelantDesign** [comment]
looks great! Does clicking on the title take the user to (grants profile) to see the list of  grants in the collection?

**Comment by willsputra** [comment]
hmm yea ideally we could have a "collection detail" page where you can see the list of grants and related stats. or we could also display the list of grants when you hover over the cards.

**Comment by willsputra** [comment]
@owocki @PixelantDesign when we have cross-chain, say if I have Eth grants and Zcash grants added to cart - should "Save as Collection" save only one chain (the active tab) or both chains? what do you think?

**Comment by willsputra** [comment]
figma file ("Grants Collection" page):
https://www.figma.com/file/GLvOGLbovtU8scAnIHochM/Grants-Round-7?node-id=1%3A3

**Comment by owocki** [comment]
active tab makes most sense to me

**Comment by owocki** [comment]
@zoek1 u wanna pick this one up?

**Comment by owocki** [comment]
@zoek1 are you taking this one still? u are assigned.  if not pls lmk so i can reassign it

**Comment by zoek1** [comment]
what happens when the user click on the share button? When ther user paste the collection url in his browser
1. The collection will have a collection detail view or 
2. It will be displayed lonely in the grants view 

At this moment we don't have a details page for collection in the mockups
@owocki

**Comment by willsputra** [comment]
@zoek1 the collection url for now could just be the grant cart url with all the grants in the collection (example: https://gitcoin.co/grants/cart/bulk-add/238;2;283,500;2;283,567;2;283,149;2;283,191;2;283,:willsputra).

we could do the collection detail view in future iterations :)

**Comment by owocki** [comment]
> what happens when the user click on the share button? When ther user paste the collection url in his browser

i think taking the user to the cart is a big presumptious + we should take them to the grant explorer with the collection filled in.   they can then click 'add all to cart' if they want

**Comment by willsputra** [comment]
> > what happens when the user click on the share button? When ther user paste the collection url in his browser
> 
> i think taking the user to the cart is a big presumptious + we should take them to the grant explorer with the collection filled in. they can then click 'add all to cart' if they want

ah yea good point! this would be better
