### ISSUE TITLE
Batch up the "thanks for contributing" emails from 2 emails per grant to 1 email per whole checkout.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7131]
Batch up the "thanks for contributing" emails from 2 emails per grant to 1 email per whole checkout.

Need design for the checkout email.

**Comment by owocki** [comment]
@PixelantDesign is there a design for this somewhere

**Comment by mds1** [comment]
Hey @zoek1, just saw you were able to tackle #7126, so figured I'd check if you could handle this one as well. I think this should be an easy one for you. The emails are sent when sending a POST request to the `/grants/bulk-fund` route, which happens in the `postToDatabase` function of `cart.js

**Comment by mds1** [comment]
Hey @PixelantDesign, just wanted to follow up on Kevin's comment to see if there's a design for this?

**Comment by owocki** [comment]
design for this https://github.com/gitcoinco/web/issues/6822 should work

**Comment by owocki** [comment]
@zoek1 any chance u can take this one?

**Comment by zoek1** [comment]
Sure, lets do it!

**Comment by owocki** [comment]
@zoek1 i just added a stopgap commit to stop sending 2 emails in 436a1f81c4254ba540ed88bb88fea410e321c5c5 ; if u could put the new email in thatd be 💯
