### ISSUE TITLE
Design - Mentors area for onboarding page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7139]
### User Story

As a potential hackathon participant I'd like to see who the list of mentors are that will be participating in this hackathon

### Why Is this Needed

If we display mentors then hackers will register because hackers want to learn from mentors they admire/want to work with.

### Description

feature

### Current Behavior
no mentor section

### Expected Behavior
mentor section designed and implemented

### Definition of Done

- [ ] get list of mentors
- [x] design
- [x] implement on onboarding  page

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
A couple of questions : 
- Is this a new feature all together ?
- Could I get some documentation on how this flow works ? Does a team created first & then they get a mentor ?
- How does this flow work at this point ? Once teams are created -> do they reach out to mentors not via gitcoin ?
- Is the mentor the same as the sponsor team / someone else 
- Does the mentor have a separate flow all together ?

And Finally, how would we ensure a supply of mentors (just curious)

**Comment by PixelantDesign** [comment]
@thelostone-mc.  This is not a new feature. This is a design task that we'd create an image to upload in the Wisywig editor that @octavioamu built in the hack onboarding page. To answer your question in most cases sponsors are the mentors.

**Comment by PixelantDesign** [comment]
getting  list of mentors  from Vivek
