### ISSUE TITLE
'accepted' time is wrong on bounty

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#714]
screenshot: http://bits.owocki.com/1Y1M2g333Y2a/Screen%20Shot%202018-03-27%20at%207.48.26%20AM.png
issue: https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/608

i just accepted the work now.  the submission was 15 hours ago.  the 'work accepted' activity on the timeline should show that it was done just now.

**Comment by kziemianek** [comment]
Looks like contract needs to be changed. `struct Fulfillment` lacks acceptance date, then this date can be displayed in a row.

**Comment by owocki** [comment]
we dont need to modify the smart contract.  only how were storing the information in the `Bounty` and `BountyFulfillment` objects

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/729/

**Comment by kziemianek** [comment]
Yes, seems like i've deleted my comment seconds before You wrote yours.
