### ISSUE TITLE
Email tribe members about hackathon prizes

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7140]
### User Story

As a tribe member/follower, I'd like to know when an organization iii participating in a Hackathon 

### Why Is this Needed

no email notification exists

If we build this email, developers will be notified and sign up, then sponsors will have more registrants and hackers working on their hackathon prizes.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: feature

### Definition of Done
Email Details

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a tribe member, I want to know the prizes from the tribe when participating in a hackathon

As a sponsor, I want my tribe members to automatically be notified the prizes available when I'm sponsoring a hackathon so that they are interested ot participate

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

IF we engage with developers already interested an org, then sponsors will have a great hackathon turnout, because developers will participate in the sponsored hackathon.

IF we do this, it'll Increase number of hackers registering for a hackathon.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

If a sponsor signs up for a hackathon, email to current tribes members and let them know that the prizes offered by X sponsor in a hackathon

### Current Behavior
[comment]: # (Describe what actually happened.)

No automatic email

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Automatic email sends out as soon as a hackathon starts

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Build email below
- [ ] ensure email  is responsive (see other emails for example)
- [ ] the image displayed "clarity hackthon"  will be dynamic based on the hackathon the sponsor  is part of.
       note the image should leverage the same image from the hackathon onboarding page.
- [ ] join button should take users to  the  specific  hackathon's  onboarding /landing page.
- [ ] this email should trigger  for  all  hackathon sponsors 3  days prior to hackathon starting
- [ ] view prize should  go  to specific prize page
- [ ] add ability to fire this from admin

### Data Requirements
Increase in number of registered hackers per hackathon

### Additional Information

![85852050-73b5af00-b7e2-11ea-8992-c38b7f98ebf0](https://user-images.githubusercontent.com/19514207/86129442-4ab05980-bb15-11ea-9238-bc995ab36a85.jpg)

**Comment by PixelantDesign** [comment]
@sebastiantf ^

**Comment by sebastiantf** [comment]
On it @PixelantDesign 👍🏻

**Comment by PixelantDesign** [comment]
Thanks @sebastiantf would it be possiible too have  before the weekend? our  next  deploy is monday.  Thanks!

**Comment by sebastiantf** [comment]
I shall complete it before the weekend @PixelantDesign

**Comment by PixelantDesign** [comment]
Thanks @sebastiantf. I just added a few more details around the email in the description. Let me know if you have any questions!

**Comment by sebastiantf** [comment]
@PixelantDesign is that header image already in the codebase? Has it been already used? If not, where can I get it?

<img width="652" alt="Screenshot 2020-07-24 at 8 55 53 AM" src="https://user-images.githubusercontent.com/36922376/88358157-7c6eb600-cd8b-11ea-87f3-c453e8363d3e.png">

**Comment by sebastiantf** [comment]
@PixelantDesign It would be better if you could share the figma.

**Comment by PixelantDesign** [comment]
@willsputra could you link figma please? thank you!!

**Comment by willsputra** [comment]
@sebastiantf figma file https://www.figma.com/file/4loBptZh91m3r1S0WjXbSD/Gitcoin-Hackathon-Email?node-id=0%3A1

**Comment by sebastiantf** [comment]
@PixelantDesign I have a PR up at #7146

**Comment by PixelantDesign** [comment]
create another email that is general without prizes.

**Comment by sebastiantf** [comment]
@PixelantDesign Can you comment on https://github.com/gitcoinco/web/pull/7146#issuecomment-664857341
