### ISSUE TITLE
Tribes Light Housekeeping

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7143]
This is part of the [Tribes Light](https://github.com/gitcoinco/web/issues/6812) release ticket.

### User Story

As a hackathon sponsor, I'd like to have an updated version of the organization page and baseline functionality so that I can engage with my community.

### Why Is this Needed

We currently have an old orgs page and a tribes page with functionality that exists on one page and not the other.

As Gitcoin Core, we should consider retiring the old orgs and providing a light version of tribes to hackathon customers.

IF we provide sponsors with a light version of tribes THEN they won't be confused at how our orgs work BECAUSE they'll have some tools available as a hackathon sponsor.

https://gitcoincore.slack.com/archives/CAW05FUD7/p1591331256380500

Why have  we not released this? The items below need to be fixed to ensure a baseline experience for sponsors.

**For Filecoin Hackathon**

1) Current bounties tab was only viewable if user follows the tribe.    Change bounties tab is default for tribe. 
- [x] Fix bounties tab display - make it viewable not only by follow

2) The organization rank logic isn't working properly. It is displaying 0 on some orgs.
- [ ] Check organization rank logic  

3) The  current All sort order includes people from the Gitcoin core team and mix of other sponsors. Not sure what the logic is.
- [x] All People view (people who follow the tribe) - Fix All view sorting to be top hacker (contributor rank, then funder rank)
next iteration show  winners, contributors' etc

4) To be engaging and dynamic, the follow module not he left rail of tribe townsquare could be more useful displaying a combination of org members to follow, interesting hackers of that org to follow. And once a person is followed, they should disappear from the list.
- [x] Townsquare module - follow - people who have been followed, dont display in sidebar

5) Related to above
 - [x] Follows should be notable based on Top hackers on this org (show top hackers below core team)
Top hackers = members (people who submitted Hackathon projects and paid out).

6) To solve for performance, improving the loading of projects page so that sponsors aren't waiting or think  that tab is broken.
- [ ] [project tab currently loads slowly, how can we speed this up?](https://github.com/gitcoinco/web/issues/7094)
       checkout what @androolloyd did on the integrated hackathon view to speed up the project tab there.
       lets list projects associated with organization/sponsor

7) This is a nice to have so that we can help sponsors troubleshoot.
- [x] If I’m an admin of gitcoin, I should also see admin view of Zcash (so core team can help)

**After Filecoin Hackathon**

We could better utilize the real estate and make it relevant to the information present if the sidebars could be dynamic.
- [ ] [refactor sidebar to be dynamic based on the tab being  viewed](https://github.com/gitcoinco/web/issues/7095)

**Comment by PixelantDesign** [comment]
**Orgs Rank**
What are the basis of the org  rankings? $ amount funded
Some tribes aren't ranked, what do we do here?  @androolloyd could you advise?
Org ranking doesn't make sense.

**Comment by owocki** [comment]
> What are the basis of the org rankings? $ amount funded

its just a pagerank algoritthm run ( https://github.com/gitcoinco/web/blob/master/app/dashboard/management/commands/create_pagerank.py ) on which orgs are marked in the bounty/tip/grant.

i dont feel strongly that this is the way things need to be though; OrgRank may have outlived its usefulness

**Comment by thelostone-mc** [comment]
> Current bounties tab was only viewable if user follows the tribe.  Change bounties tab is default for tribe. 

^ Is there a clean message on which tells the user that if they follow the tribe and they'd be able to access more info.
If we are to hide them -> we oughta give them a sneak peak to encourage them to follow 

>  refactor sidebar to be dynamic based on the tab being viewed

Do we have enough information which is unique to every tab ?
Could we share some document with what + why for each tab. If not whitespace is always clean and neat 

> What are the basis of the org rankings? $ amount funded

If this needs to be done -> let it be done with @owocki means. no on-demand calculation


> The current All sort order includes people from the Gitcoin core team and mix of other sponsors. Not sure what the logic is.

Screenshot of what it is and we'd like it to be. if there is segregation of users

**Comment by sanchaymittal** [comment]
> ^ Is there a clean message on which tells the user that if they follow the tribe and they'd be able to access more info.
If we are to hide them -> we oughta give them a sneak peak to encourage them to follow

@thelostone-mc  For now, I have made the bounties tab default but I do agree we need some incentive to encourage them to follow the tribe.

> If this needs to be done -> let it be done with @owocki means. no on-demand calculation

I agree it's surely gonna take some time to create a new org rank logic. But the issue onhand is that some of the organisation are showing 0 rank which is strange. Here are some examples: https://gitcoin.co/zcash, https://gitcoin.co/gnosis.

> Screenshot of what it is and we'd like it to be. if there is segregation of users

![Screenshot 2020-07-28 at 11 32 43 PM](https://user-images.githubusercontent.com/31698676/88703739-bee91780-d12a-11ea-9114-2ba4bdb535da.png)

Only Core Team -> Core Team + Hackers + Community Members
@PixelantDesign

**Comment by PixelantDesign** [comment]
**Org rank ideas**; based around community management, communication with  devs, incentives for community, #of hackathons they've been doing, etc?
