### ISSUE TITLE
Need a dedicated page listing dates and times of main hackathon events

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7148]
For each hackathon we need a dedicated page listing dates and times of main hackathon events (start, end, bounty submission times, meetings, presentation, etc.)

**Comment by PixelantDesign** [comment]
Great suggestion! Where would you expect to see this @vporton?

**Comment by vporton** [comment]
@PixelantDesign

Prizes
Townsquare
Projects
Chat
Participants
Showcase
Guide
**Timeline**

**Comment by PixelantDesign** [comment]
what about this @vporton https://github.com/gitcoinco/web/issues/6695?

**Comment by vporton** [comment]
@PixelantDesign Yes, that what I want.
