### ISSUE TITLE
As a user, I want a new error page, so I can feel okay when I hit an error condition

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#715]
Current error page:
![screencapture-gitcoin-co-sdfsdfds-2018-03-27-08_50_11](https://user-images.githubusercontent.com/513929/37975153-e7fc25b2-319b-11e8-85a7-78defec185ef.png)

This page is displayed for 404, 500, 403, but in general any 4** or 5** level page page

# Inspiration

* Airbnb - https://cdn.mos.cms.futurecdn.net/f3c74e859861f2d3b0fa34c31f862cf7-650-80.jpg
* Github - https://cdn.mos.cms.futurecdn.net/e367d7d75457eb45ee5e332486afbfe1-650-80.jpg
* https://www.behance.net/gallery/10286437/404-Pages
* https://www.behance.net/gallery/11635233/Error-404

# Bounty

* deliver a design for the error page 
* design should be responsive
* design should handle any 400 or 500 level http status code

**Comment by owocki** [comment]
this could be an option if we don't want to just do a static landing page => https://github.com/gitcoinco/web/issues/716

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.25 ETH (173.03 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/715/594).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by kuhnchris** [comment]
is that html5 game idea still floating around? (hint: hackathon)
