### ISSUE TITLE
Adding team members does not work

### ISSUE THREAD

**Issue by nya-elimuai** [gitcoinco/web#7151]
How to reproduce:
- Add new team member to existing team.
- Press "Submit".

"Error trying to save project"

```
  | (anonymous) | @ | raven.min.js:2
-- | -- | -- | --
  | send | @ | jquery.a09e13ee94d5.js:2
  | ajax | @ | jquery.a09e13ee94d5.js:2
  | submitProject | @ | hackathon-projects.c096f4272218.js:20
  | (anonymous) | @ | hackathon-projects.c096f4272218.js:55
  | dispatch | @ | jquery.a09e13ee94d5.js:2
  | y.handle | @ | jquery.a09e13ee94d5.js:2
  | d | @ | raven.min.js:2
```

Response:
```
{"error": "Error trying to save project"}
```

<img width="812" alt="Screenshot 2020-07-27 at 14 27 02" src="https://user-images.githubusercontent.com/15718174/88541597-9a683f00-d047-11ea-909d-df9ddf97aee6.png">

**Comment by octavioamu** [comment]
seems there is a "uploading 0%" there can you check the network tab to see what the server is saying? could be some problem uploading the project image.

**Comment by thelostone-mc** [comment]
closing this out ! if it still happens -> please reopen with more information like what @octavioamu had asked

**Comment by nya-elimuai** [comment]
@octavioamu The bug is perhaps caused by the fact that you are trying to add GitHub usernames of people that have not created a Gitcoin account?
