### ISSUE TITLE
As a staff member, I want to make all staff_only modules on the site yellow background, so that I know which items are staff only.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7153]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a staff member, I want to make all staff_only modules on the site yellow background, so that I know which items are staff only.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
So that I know which items are staff only and dont have to ask the engineers.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
None

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
All staff items are background yellow so that people know which items are staff only and dont have to ask.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- New bounty form
- click to view in admin links on each bounty,hack,kudos, are applied here
- anywhere else

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@willsputra @PixelantDesign is yellow the right color?

**Comment by PixelantDesign** [comment]
sure or the light purple that we've been using in the system also works.
<img width="1434" alt="Screen Shot 2020-07-31 at 8 29 42 AM" src="https://user-images.githubusercontent.com/238235/89034956-01b41680-d308-11ea-8f0c-348ca4ec76c3.png">

**Comment by aamustapha** [comment]
@PixelantDesign after changing most of the controls, it kinda looked off and I undid most of them except the links. Take a look at what checkboxes look like vs when bg applied. Do you think we should still apply the light purple background to them regardless?
 
![gitcoin](https://user-images.githubusercontent.com/14205064/103640999-501daf00-4f51-11eb-90e1-6962da3b7df0.png)
cc: @owocki

**Comment by PixelantDesign** [comment]
seems ok for now since users won't see it.
