### ISSUE TITLE
DESIGN - As a cross-chain ecosystem partner, I would like to have cross-chain grants, so that I can take advantage of the QF goodness + accelerate my ecosystem in a decentralized way.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7154]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a cross-chain ecosystem partner, I would like to have cross-chain grants, so that I can take advantage of the QF goodness + accelerate my ecosystem in a decentralized way.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
We have lots of ecosystem deals in the hopper.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No cross chain grants

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
We need a way to 
- navigate gitcoin grants that are ETH vs Celo vs Zcash on `/grants`
- during checkout, a way to checkout with cross chain (which likely involves QR code checkouts, 'send to addresses', etc)
- in the header, list which grants rounds (+ amounts) are active NOW + coming soon, and let peole click through to them

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
@willsputra @PixelantDesign @vs77bb @danlipert @thelostone-mc heres the cross-chain grants ticket from this mornings call; any feedback welcome

**Comment by thelostone-mc** [comment]
Before we jump into design :

We should agree on the flow + requirements 

**Question which we'd need to sync on**

- Can a grant accept payments in only one chain / multiple?
   if multiple -> showing CLR is available on a certain token might be tricky 
- Would the cross chain grants payout happen via cart ? Do remember this is not a one-click process
- Is it alright to add ETH + cross chain Grants onto the same cart (think payout)
- Would we skip the Gitcoin Fee ?
- Today we have GrantType -> media / matic / tech.. all these are ETH 
- Would we new GrantType like ZCash_media / Zcash_tech which would list all grants which accept in ZCash 
   OR 
   Would they be  all under the same GrantType ? 

**Flow**

- User creates a Grant & states which chain of payments they'd like to accept
- They would be asked to provide the recipient address where those funds would end up
- Once a grant has been created -> it would visible and another user can fund the grant by adding it to cart (if we do a cart)
- Gitcoin Maintainer Fee is deducted and if there are 6 grants -> there would be 6 +1 QR codes which would have to be scanned as each address is different ( This is an unpleasant experience )

**Comment by willsputra** [comment]
Some thought: if the matching sponsors, CLR round timing, categories are different for each chain - maybe it'll be more intuitive if we have separate pages for each chain (for example: /grants/eth, /grants/zcash, /grants/celo) since putting all kinds of grants into one page might be confusing.

**Comment by owocki** [comment]
https://docs.google.com/document/d/1xnLH1dnYWNICH2q4YNjpZo9hll5wD3H5Fzf4kV84xPs/edit
