### ISSUE TITLE
<!-- A clear and concise description of what you expected to happen. -->

### ISSUE THREAD

**Issue by Kennydoneit** [gitcoinco/web#7155]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Kennydoneit** [comment]
iPhone

**Comment by thelostone-mc** [comment]
Do reopen this more information
