### ISSUE TITLE
Error when click  on prize button on hackathon  list page

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7157]
**Describe the bug**

**To Reproduce**
Go to hackathon list page

**Expected behavior**
Get to prize explorer

**Screenshots**
<img width="1407" alt="Screen Shot 2020-07-28 at 9 22 01 AM" src="https://user-images.githubusercontent.com/238235/88671209-07b1b980-d0b4-11ea-8b66-7ee9e629fc88.png">
<img width="554" alt="Screen Shot 2020-07-28 at 9 20 01 AM" src="https://user-images.githubusercontent.com/238235/88671216-08e2e680-d0b4-11ea-8412-1f3d8d1af556.png">
<img width="683" alt="Screen Shot 2020-07-28 at 9 19 06 AM" src="https://user-images.githubusercontent.com/238235/88671223-0bddd700-d0b4-11ea-9d1e-64620f896190.png">

**Desktop (please complete the following information):**

- OS:
- Browser: Chrome
- Browser Version: Version 84.0.4147.89 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by developerfred** [comment]
@PixelantDesign I reproduced in opera and chrome but it worked normally.
https://share.getcloudapp.com/xQuLK6rb

**Comment by PixelantDesign** [comment]
yes it was  fixed  this am! thanks for checking @developerfred
