### ISSUE TITLE
Submissions View Bugs

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7158]
**7/29/20 - Need to fix**

- [ ] As a hackathon sponsor when I view the spreadsheet - the expand/collapser arrow does not flip ( doesn't work properly). See implementation on townsquare modules.

- [x] As a hackathon sponsor when I click the name of my prize - the prize details should open in a new tab.
<img width="518" alt="Screen Shot 2020-07-29 at 9 45 11 PM" src="https://user-images.githubusercontent.com/238235/88871054-e7354c80-d1e4-11ea-9da1-24cdad88be89.png">

- [ ] As a  hackathon sponsor when I click on the Project link, the link should not 404. It should open the project link iii a new tab.
<img width="198" alt="Screen Shot 2020-07-29 at 9 48 54 PM" src="https://user-images.githubusercontent.com/238235/88871345-aa1d8a00-d1e5-11ea-8b72-fc2e6c343c51.png">

- [ ] As a hackathon sponsor when I click on the GitHub cat - the GitHub project should open in a new tab

- [ ] As a hackathon sponsor when I hover over the prize values, nothing should happen. Please remove hover states
<img width="521" alt="Screen Shot 2020-07-29 at 9 46 46 PM" src="https://user-images.githubusercontent.com/238235/88871131-18158180-d1e5-11ea-8b61-a087d298d536.png">

- [ ] As a Hackathon sponsor when I mark a winner - the winner flag should display on the project card  in the Projects tab of the hackathon view. Hmmm - what do you think here @connoroday? will this feature update ruin any surprise announcements? Does hackopps prefer to be notified somehow through this feature?

- [ ] when I enter in a note and click out of the box. the display should go back to preview.

- [ ] when I delete a note, and click out of the input area,  It should return to  + Add note link should display.

- [x] clicking on  profile link should open in a new tab  for the sponsor

- [ ] as a Hackathon sponsor when  I mark a winner - the pay button should appear next to the winner column. Clicking pay takes the sponsor to the normal payout flow in a new tab.
Once sponsor's transaction goes through, then the view should update as paid with date on the submission  view. See mockup.
<img width="532" alt="Screen Shot 2020-07-29 at 9 58 21 PM" src="https://user-images.githubusercontent.com/238235/88871759-acccaf00-d1e6-11ea-866d-8897cc06868d.png">

- [ ] clicking chat icon opens the chat window but it's displaying 404.  Chat doesn't open the conversation with that user.
<img width="512" alt="Screen Shot 2020-07-29 at 9 42 39 PM" src="https://user-images.githubusercontent.com/238235/88870889-8574e280-d1e4-11ea-9a16-b5e0ef7ba809.png">

- [ ] check participants count logic for when a Hackathon started 
<img width="663" alt="Screen Shot 2020-07-29 at 10 20 05 PM" src="https://user-images.githubusercontent.com/238235/88873056-c6bbc100-d1e9-11ea-89d8-b075ba5987f5.png">

**7/28/20 - Completed**
Let's capture bugs here as we QA the submissions view today!

- [x] funded issue for the hackathon
       it is showing as 7 different submission entries, but all are for the same bounty
       https://gitcoin.co/hackathon/dashboard/privacy
- [x] When hackathon has ended, the data disappears, data should stay in the view. See past hackathon.
- [x] sponsor dashboard is failing (404) cc
![image (21)](https://user-images.githubusercontent.com/238235/88699452-5a4f9d80-d0d5-11ea-948e-5e03d864830f.png)
![image (20)](https://user-images.githubusercontent.com/238235/88699461-5d4a8e00-d0d5-11ea-8b99-fa53c54b5f9c.png)

**Comment by octavioamu** [comment]
I made 2 fixes on this one was the project logo serializer and the other tofixed() d8aeb8a5ac623f1b633a4dbf1a0c480c15879502

But seems there are some problems with the biz rules here. Since the query is_funder is checking only for the owner of a bounty. that means other org members are not going to be able to see the dashboard data.

Here are some of my suggestions on the rules
- is_founder need to check if the profile.orgs is on the hackathonevent.sponsors instead of check the bounties
- Bounty.objects.filter need to be based on sponsors + owner because the right use is to them use the a org repo but sometimes they do it in random repos (not orgs ones)
