### ISSUE TITLE
Take the Gitcoin Product Video and make it into an HTML5 game

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#716]
# Reference Links

Video: https://www.youtube.com/watch?time_continue=28&v=DJartWzDn0E
Creative Vector Assets: https://github.com/gitcoinco/creative

# What

At 28 seconds into the [product video](https://www.youtube.com/watch?time_continue=28&v=DJartWzDn0E), there is a scene where the main character is busting rocks coming from outer space.  Here is what it looks like: 

![screen recording 2018-03-27 at 08 56 am](https://user-images.githubusercontent.com/513929/37975598-e810b1a2-319c-11e8-8d26-3ed751679f1d.gif)

# Bounty

I would like for this product video to be made into an HTML5 game.  How the game works:

* Player is in the center of the screen in a fixed area.
* The game throws 'rocks' at the player.  
* Player can swing their fists to bust the rocks. (either clicking the mouse or pressing space bar will swing fists)
* If player hits a rock, they get 100 points and the rock is destroyed.
If a player misses a rock, it hits them, and they lose health.   If the player gets hit 3 times, it's game over.
* Game speeds up over time as the player destroys more rocks.
* Game should be full screen (the entire browser window).  It should be embeddable.
* music in the game should match music from video
* light sound effect when the rocks are smashed pls
* game should degrade gracefully in mobile/tablet

**Comment by owocki** [comment]
audio: http://bits.owocki.com/1J0j0c09443S/audiojungle-19473039-80s-synth-pop.zip

**Comment by PixelantDesign** [comment]
Are you thinking this would be used when a user is in a long waiting state?

**Comment by owocki** [comment]
@PixelantDesign i was thinking it would make a good error (404, 500) page https://github.com/gitcoinco/web/issues/715

**Comment by owocki** [comment]
@PixelantDesign but only if you feel like we can bounty it and have someone in the crowd BUIDL it in a way that doesnt neglect our core UX

**Comment by owocki** [comment]
@mbeacom xactly.

**Comment by stevenwritescode** [comment]
This looks like it would be fun to build, but I'm having a hard time finding the vector assets from the video in here: https://github.com/gitcoinco/creative

Is there a subfolder I should be looking in?

**Comment by stevenwritescode** [comment]
That would be great, I think seeing how it's animated in keyframes will help me visualize what I need to do in code as well.

**Comment by owocki** [comment]
here ya go https://github.com/gitcoinco/creative/tree/master/video/karot/karot_gitcoin_092917_deliver%20folder

**Comment by stevenwritescode** [comment]
Awesome, thanks!

This will be a bit of a learning project for me, so I'm not sure on time frame yet. If someone else wants to do this and it seems like I'm taking a long time, don't let me get in your way.

**Comment by owocki** [comment]
@stevenwritescode are you still interested in this?

**Comment by stevenwritescode** [comment]
Its been in the back of my mind, unfortunately I just haven’t had the time to start coding it out yet. Work, school, and looking for a new job have kinda gotten in the way of my attempts to contribute to open source stuff. I still think it would be a fun project if I can find the time. Sorry for the radio silence.

**Comment by owocki** [comment]
@stevenwritescode okie dokie.. let us know when priorities shift and you can work on it again!
