### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#717]
*not ready to be worked on yet*

### User Story

As a developer, I'd like to be able to leverage a design system so that I can quickly and consistently build features or ideas and have access to existing components and patterns in one place.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:  Gitcoin currently has many stylesheets in the code, an inconsistent front-end, and developers currently need to rebuild a lot of components. 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: A Design System

### Definition of Done
[comment]: # (Any other information that would be useful.)

### Additional Information
[comment]: # (Any other information that would be useful.)

notes:
It'd be great to have standard views for lists, tables, buttons, nav, etc.

I'd love to get to a point where we don't even need designs for a landing page. We could have contributors start with an existing template and plug in information because these design patterns will be established.

This is a good example of a design system that works:

https://www.lightningdesignsystem.com/

**Comment by joshmobley** [comment]
Related to: https://github.com/gitcoinco/GIPs/issues/6
