### ISSUE TITLE
Grants Landing page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#718]
*not ready to be worked on yet*

Why does Gitcoin have grants? What is the purpose? There are different parameters to the way grants are constructed. What is Gitcoin's? How does it work? How does one qualify? Is it everyone applies, gets one? Does the person need to pay it back? Just basic information.  Examples of grants that Gitcoin would approve/sponsor? Users need to be introduced to the grants program.

We can address some of this by adding a section above the tiles on the landing page design.

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/380

**Comment by PixelantDesign** [comment]
@owocki Is this still needed?

**Comment by owocki** [comment]
yes probably

inspiration https://staketree.com/
