### ISSUE TITLE
General onboard

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#7185]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I want to have an onboard where I can understand what is the products proposal
As a costumer user (org owner) I want to have an onboard where I can understand what is the products proposal

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Is needed because people is confused about the tools we offer them and we cannot offer a simple experience without understanding their products interests. 

### Problem
User
- What is Gitcoin?
- What can I do here?

System
- Which persona is this user?
    - Is this a buyer or a user?
    - Is this a funder or contributor?
    - Is this a job seeker or a freelancer?
    - etc
- When should I email this user? About which interests?
- Collect data from the sign up.

## V1
Setup user preferences/settings & foundational data collection.

## V2 (future)
Change experience (e.g Townsquare) based on preferences.

## V3 (future)
Email marketing based on collected preferences and data. 

## Hypothesis

- A proper onboard experience can help users understand what they can do on the site and help the system be smarter based on those preferences.

Adding this onboard will decrease the dropoff of new users and increase the number of active users as the TTV (time to value) will be shorter. 

With the correct user data, we can do better segmentations and targeting via email campaigns to boost our email open rates, and consequently, Gitcoin's long-term retention.

## Solution

From the first experience on the site as logged user you choose your preferences (interests) in a modal (as this can be open in any part of the site).

Based on your selections, Townsquare will present unique details relevant to your data selections.

You can access your data and change it anytime from your settings.

The primary onboarding experience is focused on developers, and secondarily on costumers (organization owners). Depending on what they select (if they select "organizations" as an example), different options will be presented for them and because we have the data on a funder/sponsor, we can open the door to possible sales opportunities.

*NOTE: The first modal screen will be changed when we add login options (detached from Github) to include all the signup/signin options / email - password.*

# Prototype:
https://www.figma.com/proto/S7yxF6zdY4BQLi90twugH4/onboarding?node-id=61%3A1591&viewport=1472%2C-1793%2C0.8214154243469238&scaling=min-zoom
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
no onboard

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
prototype implemented and new data fields added.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
We are measuring new users dropoff after and before implementation.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Prototype:
https://www.figma.com/proto/S7yxF6zdY4BQLi90twugH4/onboarding?node-id=61%3A1591&viewport=1472%2C-1793%2C0.8214154243469238&scaling=min-zoom

**Comment by vs77bb** [comment]
Categories: Open Finance / DeFi,  Non-Fungibles & Gaming,  Marketplace, Token Economics, Infrastructure / Research, Community Building, DAO's & Governance

**Comment by octavioamu** [comment]
Agreements 
- add short bio
- Add interests keywords

**Comment by frankchen07** [comment]
+ possible third modal (at the suggestion of octavio)

**Comment by vs77bb** [comment]
Should we invite the avatar builder as optional in this flow as well?

**Comment by frankchen07** [comment]
What subsets of blockchain do you have experience in, or are you most interested in right now?
- Decentralized Finance
- Non-Fungibles & Gaming
- Marketplaces
- Token Economics
- Infrastructure & Research
- Community Building
- DAO's & Governance

2. The bio / introduction can take the format of something like this:

![Screen Shot 2020-08-10 at 15 54 51](https://user-images.githubusercontent.com/7516920/89839139-e4f6ba80-db21-11ea-99e3-e5f8bded11ee.png)

3. > avatar builder

I think we should leave this out of the onboarding in this iteration.

4. one more standard question that we ask during hackathons is their level of expertise, but I feel like that is slightly less important to know.

**Comment by frankchen07** [comment]
post interview notes: https://gist.github.com/frankchen07/e516dc8fc7a8e867eba3b30fe320814b

**Comment by frankchen07** [comment]
final prototype build underway: https://www.figma.com/proto/S7yxF6zdY4BQLi90twugH4/onboarding?node-id=318%3A5284&viewport=1472%2C-1793%2C0.8214154243469238&scaling=min-zoom
