### ISSUE TITLE
make upcomingdates into a townsquare calendar widget

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7192]
the hackathons dates on the townsquare are not the only dates people should know about

anything in the townsquare.models.UpcomingDate objecvt should show there.

**Comment by thelostone-mc** [comment]
I think we should show just upcoming hackathon as opposed to current + completed hackathons !
The goal is to get more users before the event starts -> once started i doubt folks would want to hop on (unless it's a really long hackathon)

RIght now logic is show 5 hackathons which hackathons team wanted was 

- Any upcoming hackathons which start in. 10 days
- Running hackathons
- Hackathons which ended less that 10 day ago

**Comment by owocki** [comment]
why just hackathons though?  lets list all *upcoming* events?
