### ISSUE TITLE
Community Hackathons Explorer - for communities intending to organise hackathons around the world

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/web#7197]
## Discussion

Hi Fam,

Have been sitting on this idea for a while now. Here it goes:

Have a separate hackathon explorer for community hackathons where organisers can request us to create a hackathon and use Gitcoin as a platform. (No customise service)

### Who are these organisers?

We will run campaigns from BD side to invite different communities, and will host 3-5 community hackathons per month. (A cap is necessary to avoid dilution)

### Efforts involved from the team?

- Product changes - Create a nested explorer to host `n` hackathons. 
- BD - Run the campaign, will help us gauge our target audience as well. 

### Added Benefits?

-  Inbounds from our target community
- Experimenting traditional hackathon models on gitcoin. (other than design prompts// bounties)
- Providing gitcoin as a platform, to all the organisations who can not host such events due to lockdown. 
- and you know. 😅  

What do you guys think @owocki @vs77bb @ceresstation ?

**Comment by PixelantDesign** [comment]
Bringing offline communities online, not thread as an exclusive Hackathon. Allow the communities to manage themselves through a nested explorer.
