### ISSUE TITLE
daily email v2

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7201]
things to update:

- Save The Date” is way too long and confusing. I suggest remove “Start” and “End” and consolidate it into object
- justin needs a way to update Add Event Code ( https://bits.owocki.com/OAuqRYGX)
- avoid ways to show OPs multiple times ( https://bits.owocki.com/o0u8k5Zb )
- show only high engagement town square posts
 - Make the links blue in announcement section
- move up the 'save the date' section above townsquare

**Comment by jdorfman** [comment]
@owocki don't forget #7183

**Comment by owocki** [comment]
@zoek1 any interest in this one?
