### ISSUE TITLE
great gitcoin bakeoff - make integration of a L2 checkout self service.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7232]
we get approached here & tehre by L2s that want their tech in gitcoin grants.

the goal of this ticket is to make that self service.

scope - come up with a readme.md that 
1. describes how to integrate your L2 checkout into gitcoin
2. inclusive of checout experience + validator
3. completely self serve

**Comment by owocki** [comment]
@mds1 how does this look?

**Comment by mds1** [comment]
Looks good. Some others things to cover:

- Account for what tokens are supported, e.g. all tokens, a whitelist, etc.
- If there's a delay between deposit to L2 and when you spend, consider what to do with that delay, such as email reminders when deposit is complete (if user has to re-visit site to finalize), or saving things in browser storage or DB

Will add more comments here as I think of things
