### ISSUE TITLE
Include Social Proof Info in Hack Onboarding

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7241]
### User Story

As a developer, I'd like to know out of the people I know are participating in a Gitcoin hackathon.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.) No info on this

### Expected Behavior
[comment]: # (Describe what you expected to happen.) Display this info

### Definition of Done

- [ ] Decide on the logic/business rules
- [ ] Decided where this information should be present
- [ ] Review with team
- [ ] Implement

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
Need more context. Closing this out for now
