### ISSUE TITLE
grants - cant checkout on mobile

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7243]
the cart view doesnt load on mobile
![2020-08-15 13 53 04](https://user-images.githubusercontent.com/513929/90407791-22989d80-e064-11ea-8432-3775d5b296da.png)

**Comment by owocki** [comment]
@developerfred @zoek1 any interest in this one

**Comment by thelostone-mc** [comment]
![Screenshot_20200818-171613](https://user-images.githubusercontent.com/5358146/90509237-9f1ba100-e176-11ea-9a6b-19e475a04d17.jpg)

Seems to be loading for me!

Did you have items on the cart ? 
Also which browser?

**Comment by owocki** [comment]
yes i have items in cart
browser is iphone XS +  opera

**Comment by developerfred** [comment]
Hey @owocki, I will check and correct, I can do the tests on an iphone.

**Comment by thelostone-mc** [comment]
@developerfred any update on this?

**Comment by developerfred** [comment]
> @developerfred any update on this? 

I checked and the error occurs because the opera has a new feature to block cookies and JavaScript for greater user security.  I'll need to find a way around this for the cart script to work

**Comment by developerfred** [comment]
![image](https://user-images.githubusercontent.com/57037080/91284668-97ee2780-e762-11ea-9da5-3ea7c6d1a854.jpeg)


need to investigate why gitcoin does not recognize the opera wallet

**Comment by developerfred** [comment]
@thelostone-mc I found some problems, opera blocks google tag manager and has 12 issues of samesite-cookies alert
https://web.dev/samesite-cookies-explained/?utm_source=devtools

<img width="913" alt="Screen Shot 2020-08-27 at 19 10 47" src="https://user-images.githubusercontent.com/57037080/91500165-501dec00-e899-11ea-8be2-6e8457f66de3.png">
<img width="1041" alt="Screen Shot 2020-08-27 at 19 11 17" src="https://user-images.githubusercontent.com/57037080/91500167-51e7af80-e899-11ea-9be4-b44446faf0cd.png">

**Comment by molecula451** [comment]
@owocki I am able to reproduce this locally & on desktop. I can't see on that screenshot whether you have web3 wallet connected or not
![grants-bug](https://user-images.githubusercontent.com/41552663/91673130-97f27c80-eb00-11ea-93b4-5892204ef2c0.gif)

@developerfred screenshot shows that has not web3 wallet connected and couldn't load the view & It looks like @thelostone-mc is indeed on the web3 connected pretty 1337 like and it loads the view. Connecting the wallet before trying to render the cart shall load the view

![grants-bug-bug](https://user-images.githubusercontent.com/41552663/91673526-8dd17d80-eb02-11ea-8775-20df53dc30f8.gif)
