### ISSUE TITLE
Quests [Other Things?] That Lead To Access To Different Communities

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7247]
As a user, if I do ____ quests or otherwise prove myself, I should get access to specific communities / for the work I do. 

Same with kudos. The trust that I get allows me to build better relationships within my community.

**Comment by owocki** [comment]
i like the idea of creating a "IFTTT" strucutre thatadmins can configure.  as an admin i should be able to say

If people do X and Y OR Z, then they get AZ.

**Comment by owocki** [comment]
such a pattern could be generalized to be completely configurable

**Comment by owocki** [comment]
configurable === no engineering work required to add a new IFTTT
