### ISSUE TITLE
Connect All Interests / Themes Across Gitcoin System

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7249]
- Gitcoin Grants Categories
- Project Subcategories
- Individual users and interests 

So that we can tie them together.

**Comment by owocki** [comment]
i dont understand what this ticket is intended to mean (?)  

I'd strongly recommend writing tickets in the "As a <user type>, I want to <task> so that <goal>" format, so that people can grok the who,what,why when writing tickets.  Cuts back on back/forth.
