### ISSUE TITLE
coding -  /mentors page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#725]
ticket moved to https://github.com/gitcoinco/web/issues/963

**Comment by HectorZarate** [comment]
Hello just commenting that I am still working on this issue. Since good software development depends on good communication, I'll use this thread to communicate updates and any questions. Thanks!

**Comment by HectorZarate** [comment]
https://github.com/HectorZarate/web/tree/mentor
Getting comfortable with the code base, its very high quality! So I forked and started a new branch for this issue, work has been started on it and anyone can check it out there for collaboration or comments. 
Btw I am @hector_z on slack, ill shoot over some questions if necessary.

**Comment by mbeacom** [comment]
Thanks @HectorZarate !

**Comment by HectorZarate** [comment]
I'd like to stop work on this due to time constraints on my side (classes/work), I'll follow along and help whoever takes up the task. Next time I'll be more mindful of time when taking on an issue ✌

**Comment by kziemianek** [comment]
Well... got few spare evenings...

**Comment by kziemianek** [comment]
Organization and skills offered fitlers are hardcoded or dynamically created based on existing mentors ?

If dynamically then these lists can get really long. Does 'More' only expands ? If yes, then searching thru long list might be problematic. Maybe replace these filters with search term? There would be only 'Experience' filter.

**Comment by owocki** [comment]
@kziemianek they are in the `Keyword` dataobject.. i can get you a DB dump if you need

I agree with replacing it with a search term

**Comment by owocki** [comment]
moving ticket to https://github.com/gitcoinco/web/issues/963

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.35 ETH (242.24 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/725/554).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
