### ISSUE TITLE
Chat showing offline & online at the same time

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7257]
**Describe the bug**
Chat showing offline & online at the same time
<img width="1590" alt="Screen Shot 2020-08-19 at 1 56 36 PM" src="https://user-images.githubusercontent.com/238235/90672321-f297f880-e223-11ea-8640-584f9ddef74e.png">

**To Reproduce**
Go to Gitcoin, logged in, checkout the nav.

**Expected behavior**
Profile chat icon displays online if chat Icon is showing online.

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Version 84.0.4147.105 

**Additional context**

**Comment by androolloyd** [comment]
Looks like its got to do with the poll for active status, this might be removable now that users connect to the chat via a websocket when authenticated.

**Comment by androolloyd** [comment]
#7283 reported as well
