### ISSUE TITLE
Display # of Grants in Grant Cart

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7258]
### User Story

As a Gitcoin Grants user I'd like a more noticeable notification when I have something in my Grant cart.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The original notification design was not designed to account for showing an item count related to how many actions are pending. If we displayed a count and improved color contrast with the nav, users might be more likely to take action.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)
<img width="171" alt="Screen Shot 2020-08-19 at 2 19 02 PM" src="https://user-images.githubusercontent.com/238235/90674313-f4af8680-e226-11ea-89a2-cbb5f6475d81.png">

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
<img width="700" alt="Screen Shot 2020-08-19 at 2 18 18 PM" src="https://user-images.githubusercontent.com/238235/90674332-fbd69480-e226-11ea-9a9f-14dbf78ea81a.png">

The scope of this ticket is to update the grant count on Gitcoin Grants Cart.
Nice to have - If we are able to update the other two notifications (chat and bell).

### Definition of Done

- [ ] Update green dot to display a count.

### Data Requirements
Users who take action and checkout

### Additional Information

https://www.figma.com/file/GLvOGLbovtU8scAnIHochM/Grants-Round-7?node-id=57%3A379

![Notification_Count](https://user-images.githubusercontent.com/238235/90674704-7e5f5400-e227-11ea-9ce2-9cdf93611e49.png)

**Comment by owocki** [comment]
i LOVE this!

**Comment by PixelantDesign** [comment]
@zoek1 are you still working on this?

**Comment by thelostone-mc** [comment]
This is live!
