### ISSUE TITLE
Hours worked field doesn't support decimal values

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#7261]
**Describe the bug**

When posting a bounty the hours worked must be an integer, otherwise you get the error "unable to create bounty please try again later"
![image](https://user-images.githubusercontent.com/1358093/90818661-3d3d7180-e305-11ea-80c4-e068b1fdf090.png)

**To Reproduce**

Try creating a bounty with a non-integer value in that field.

**Expected behavior**

Either the field should have validation or non-integer values should be allowed.

**Cause**

Probably related to:

```
https://sentry.io/organizations/gitcoin/issues/1850523990/?project=1398424&query=is%3Aunresolved
ValueError: invalid literal for int() with base 10: '0.5'
```

**Comment by owocki** [comment]
anyone want? @gitcoinco/engineers @zoek1 @developerfred

**Comment by developerfred** [comment]
@ceresstation I will change the model to accept float values

**Comment by octavioamu** [comment]
I feel the better solution will be just work with integers on that value since we don't want people submitting 1.05 hours. 
So probably just a front end validation to avoid decimals.

**Comment by Anoof** [comment]
Found a similar issue while submitting bounty as well. The hours worked field allows decimal input, but on submission the bounty doesn't get accepted. Console error says hours worked is missing, and there is no prompt to the user saying decimal values are not allowed.

**Comment by molecula451** [comment]
I think the input it's fine to work only with intengers.

Can't reproduce what @Anoof says as the input is already invalidating any decimal value

![input](https://user-images.githubusercontent.com/41552663/91689259-b7ee6400-eb31-11ea-809d-f3d33b519149.gif)

**Comment by Anoof** [comment]
I was referring to the bounty submission form, where this validation is not present. I think this same validation needs to be there as well.

![bounty-float-bug](https://user-images.githubusercontent.com/8438198/91693013-029acb00-eb88-11ea-8fe7-978873a5c1b1.png)

**Comment by thelostone-mc** [comment]
@aamustapha would you be able add that logic to the bounty submission as well ?

**Comment by aamustapha** [comment]
Sure
