### ISSUE TITLE
allow a grant to opt out of matching, so they dont partciipate in QF

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7272]
allow a grant to opt out of matching, so they dont partciipate in QF

this is a requirement i got from the YAM finance community; apparently they dont want any QF money since they hav ea business model for their project.. and dont want to be accused of trying to shill us a non public good on a public good platform.

doing htis would enable them to still use grants

**Comment by thelostone-mc** [comment]
I've already built this out https://github.com/gitcoinco/web/pull/8607
