### ISSUE TITLE
Add XRT token into web/app/economy/fixtures/tokens.json

### ISSUE THREAD

**Issue by akru** [gitcoinco/web#7287]
### User Story

I want to fund issues by [XRT](https://etherscan.io/token/0x7de91b204c1c737bcee6f000aaa6569cf7061cb7) token:
* https://www.coingecko.com/en/coins/robonomics-network
* https://etherscan.io/token/0x7de91b204c1c737bcee6f000aaa6569cf7061cb7
* https://robonomics.network
* https://twitter.com/AIRA_Robonomics

### Why Is this Needed

The team wants to fund GitHub issues by XRT but can't find it in available Gitcoin tokens.

**Comment by thelostone-mc** [comment]
Fill out https://gitcoin.co/submittoken and submit it ! 
And it'll be approved after review and added

**Comment by akru** [comment]
@thelostone-mc got it, thank you
