### ISSUE TITLE
Release 1.65.0 QA

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7291]
- [x] hackathon-list page; if there are no sponsors pls dont show a broken 'sponsored by' https://bits.owocki.com/eDuB5dNq

- [x] why do grants show ‘monthly recurring’ ? we dont even have a monthly recurring option anymore 
also it says “round” without a round number.
it should say “all time funding” if thats what were showing

- [ ] can we add a 50% opacity background here? rn it looks super broken https://bits.owocki.com/4gu9KomY

- [x] matic grants show "final CLR match" instead of 'estimated CLR match' when the matic round is ongoing https://bits.owocki.com/mXuyYe5q

**Comment by thelostone-mc** [comment]
> why do grants show ‘monthly recurring’ ? we dont even have a monthly recurring option anymore
it should say “all time funding” if thats what were showing

This is a remnant of what it was even before !
Makes sense to remove it -> thanks for the catch 

> also it says “round” without a round number.

Well only if it's been part of a round in the admin -> will it show a value 
Once we activate matic round -> it would look  like
![image](https://user-images.githubusercontent.com/5358146/91424682-be51b700-e877-11ea-8603-f1b3227e8bbb.png)


> matic grants show "final CLR match" instead of 'estimated CLR match' when the matic round is ongoing https://bits.owocki.com/mXuyYe5q

^ I was given to understand Matic isn't live yet -> once the CLR round it set to active it admin
It should reflect
