### ISSUE TITLE
gmail newsletter display issues

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#730]
user clicked a link from newsletter ([this one](https://consensys.us11.list-manage.com/track/click?u=947c9b18fc27e0b00fc2ad055&id=acf28028fe&e=3ed65f5886) , which leads to the faucet page) and its all jumbled on the gmail iphone app:

![screenshot_20180327-155759](https://user-images.githubusercontent.com/513929/38041221-70787382-326e-11e8-9cc0-5a2efe42662a.png)

**Comment by kuhnchris** [comment]
@owocki do you know if this is still the case? anyone got an iphone to test/help us out here?
