### ISSUE TITLE
bug: tribe sorting 

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7310]
#### Description

https://github.com/gitcoinco/web/pull/7171 introduced sorting of participants by their rank but this doesn't work as it attempts to sort within a paginated result.

Ideally, the sort has to be done on the backend and all the frontend changes added needs to be removed.

There is a revert PR if this cannot be addressed 
https://github.com/gitcoinco/web/pull/7295

**Comment by PixelantDesign** [comment]
@sanchaymittal could you take a look at this?
