### ISSUE TITLE
"Circle Townsquares" posts dont show up in homepage post filter

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#7311]
**Describe the bug**
There is a filter on the home page townsquare that is no longer applicable to hackathons with circle integration:

![Screen Shot 2020-09-01 at 7 41 30 PM](https://user-images.githubusercontent.com/869266/91840377-92756d80-ec8b-11ea-9838-259b1427d0c2.png)

**To Reproduce**
Enable circle for a hackathon

**Expected behavior**
Not sure what we want to do here @PixelantDesign @sanchaymittal 

**Screenshots**
See above

**Comment by sanchaymittal** [comment]
@danlipert Right, the convos happening for apollo hackathon will break but it won't give any errors.
For solutions, I can put the screenshots of the previous conversation in the circle and let people know of it. Something like: New Apollo New Townsquare. and describing them the changes.
CC: @PixelantDesign

**Comment by thelostone-mc** [comment]
same was highlighted before we had to deploy the PR 
https://github.com/gitcoinco/web/pull/7262#pullrequestreview-475383732

It's just a matter of adding an if check to avoid it as opposed to leaving it there.

@PixelantDesign / @sanchaymittal
