### ISSUE TITLE
[Bug] Tribes Project Page Displaying Incorrect Results

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7317]
**Describe the bug**
Tribes/Orgs Project Page Displaying Incorrect Results

**To Reproduce**

1. Visit this Tribe page https://gitcoin.co/tellor-io/projects
2. See the projects that are displaying (showing projects associated for other tribes)

**Expected behavior**
Only display projects associated with that tribe. In this example Tellor.

**Screenshots**
<img width="1411" alt="Screen Shot 2020-09-02 at 9 17 00 AM" src="https://user-images.githubusercontent.com/238235/91988796-b40f3d00-ecfd-11ea-9beb-f65d0bcbff63.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Version 84.0.4147.105
**Additional context**

@danlipert to provide approach on displaying/improving the logic.

**Comment by danlipert** [comment]
To fix this, I believe we need to filter down to only include projects that are for bounties created by an org as well as projects for hackathons that are sponsored for an org. So something like `Projects.objects.filter(bounty__bounty_owner_github_username=tribe_name)` and `Projects.objects.filter(bounty__event__sponsors__in=tribe)`.. maybe there are some other cases where we include as well, and we can use a Q object to combine the queries easily. https://docs.djangoproject.com/en/3.1/topics/db/queries/#complex-lookups-with-q-objects

**Comment by PixelantDesign** [comment]
@thelostone-mc was this fixed? I'm checkin' out Aarweave and their page still displays other sponsors projects. https://gitcoin.co/arweaveteam/projects

**Comment by aamustapha** [comment]
@PixelantDesign I'll take a look at this right away.

**Comment by thelostone-mc** [comment]
synced up with @aamustapha ! we'll have a fix ready by Thursday

**Comment by PixelantDesign** [comment]
hey guys how is this one going?

**Comment by thelostone-mc** [comment]
fixed it via 4ad725e6327a76018267ebbd1125ce6d3ec54ecf
cc @aamustapha
