### ISSUE TITLE
[Bug ] Tribes Project Page Loads Slowly

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7318]
**Describe the bug**
Tribes project page loads slowly.

**To Reproduce**

1. Visit this page https://gitcoin.co/tellor-io
2. Click on Projects - see the page loading

**Expected behavior**
Projects load quickly

**Screenshots**
<img width="1969" alt="Screen Shot 2020-09-02 at 9 25 32 AM" src="https://user-images.githubusercontent.com/238235/91989445-8b3b7780-ecfe-11ea-925b-69d40842b7df.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Version 84.0.4147.105

**Comment by danlipert** [comment]
there are a couple of approaches here, and we can probably do all of them to eke out every bit of performance, but the big wins are a) ensuring the query feeding this data is only ORM query, with prefetching all related objects, etc. and/or caching this data and invalidating the cache when a project is saved to the database using a post save hook
