### ISSUE TITLE
bounty: increase timeline + request increase of funds

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#732]
### Why Is this Needed?

![0 jcx5uczfsmu8bdey](https://user-images.githubusercontent.com/5358146/38042827-031d5ea0-32d3-11e8-9555-5068552b7ec8.gif)

Feature/Scope creep happens in every project. It’s unavoidable.

Would be nice if gitcoin would let me :

- request for an increase in timeline as a bounty hunter  and provide the ability to ask for a raise of bounty to the owner with justification
- ability to increase the timeline as a bounty issuer ?

**Comment by mbeacom** [comment]
Scope creep...  or progressive elaboration?! 🤔 

Jokes aside, a formal action for requesting the funder to "add contribution" to the bounty could make sense and our ability to reflect changes to the scope of a bounty could be a good idea if we plan to aggregate bounty turnaround data.

**Comment by owocki** [comment]
> request for an increase in timeline as a bounty hunter and provide the ability to ask for a raise of bounty to the owner with justification

We actually just released the ability for a funder to increase the amount of funds in an issue (the butotn will only appear if ur the funder though).  Theres no current way for the bounty hunter to formally request more funds though.

> ability to increase the timeline as a bounty issuer ?

We put in a fix so that the expiration date isn't a hard stop anymore.. Now people can pay out after the expiration date.  Not sure if thats what you were looking for or not!?

> Scope creep... or progressive elaboration?! 🤔

lol

**Comment by thelostone-mc** [comment]
I believe we should 
We've already encounters where folks weren't able to submit expired bounties.

And increase payout is not something which everyone would be comfortable asking , having a button => sort of makes the user understand it's okay to request for more if they have a valid justification

**Comment by thelostone-mc** [comment]
I'll do a rough prototype via popup box ( like the start work ) to get things rolling ?

**Comment by mkosowsk** [comment]
@thelostone-mc I definitely agree with the increase in timeline but am unsure about a button to ask for more funds, think it may introduce some wonkiness into the platform. Think it may have introduce some moral hazard into having the Funders being okay without fulling scoping their tickets to start 🤔

Will be interested to see the data on use of the button if/when it's added! 👍🏻

**Comment by kuhnchris** [comment]
@thelostone-mc did you ever come around to do the prototype?
