### ISSUE TITLE
Profile Issues 

### ISSUE THREAD

**Issue by xBruceTheGoose** [gitcoinco/web#7323]
**IBroken Profile*

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Same problem in every browser I attempt. currently using Opera GX
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
please provide more details; "broken profile" doesnt help our team figure out what your issue is.
