### ISSUE TITLE
I can't apply to new bounties

### ISSUE THREAD

**Issue by yacare555** [gitcoinco/web#7327]
**Describe the bug**
Hi guys, I completed this bounty a month ago the owner changed it to Done and I got paid for it as well but it keeps appearing as active and

It prevents me to apply to new bounties because of the limit of active bounties.

bounty: https://gitcoin.co/issue/vue-polkadot/apps/82/4509

Thanks!

**To Reproduce**
Go https://gitcoin.co/issue/vue-polkadot/apps/82/4509.

**Expected behavior**
- It should appear in the portfolio tab and not as active, and 
- It should not count in the limit of active bounties.

**Comment by thelostone-mc** [comment]
This is on the bounty flow ! 
While we look into this , I've increased the number of bounties you can work on to unblock you 

Thanks for the report
