### ISSUE TITLE
Should send money back when canceling a bounty

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7338]
**Describe the bug**
I canceled a bounty that I funded.

I was told nothing about that my money could be sent back to me.

**To Reproduce**
Create a bounty and cancel it.

**Expected behavior**
Should offer to send the money back to the funder.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Brave
- Browser Version:

**Comment by thelostone-mc** [comment]
This is taken care in the new flow !
On the older flow -> cancelling a bounty does return the funds to the address
