### ISSUE TITLE
Quick access/quick pay to developers I frequently work with

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7342]
### User Story

As a funder/sponsor using Gitcoin, I'd like Gitcoin to know who I work with often so that I don't have to rely on search to quickly send tips or pay the people I work with regularly.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: So that funders don't have to think /do work to access great contributors.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Doesn't exist

### Expected Behavior
Quick access to people

### Ideas

- Quick access dropdown of favorite people with primary actions (contact & tip)
- It would be great if Gitcoin was smart and automatically saw that I work with X a lot, and put them in the list for me.

### Data Requirements
Interactions between funder and dev goes up

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
This would pop up on the invite section on the creation flow
