### ISSUE TITLE
Subcategory switches when you publish a grant

### ISSUE THREAD

**Issue by lorelei1** [gitcoinco/web#7345]
**Describe the bug**

I created a grant and selected "community" as the subcategory, then when I published it showed "security" as the subcategory. Created it again and this time it published as "Defi" being the subcategory 😅 Also tried to cancel the first grant but the cancel button doesn't work

**To Reproduce**

Just create a grant, category tech, subcategory community.

**Expected behavior**

Subcategory is a random one that you didn't choose

**Screenshots**

<img width="822" alt="Screen Shot 2020-09-08 at 2 35 47 PM" src="https://user-images.githubusercontent.com/38163206/92530409-9f1a3880-f22c-11ea-86a6-9b71004b766b.png">
<img width="816" alt="Screen Shot 2020-09-08 at 2 36 01 PM" src="https://user-images.githubusercontent.com/38163206/92530412-a0e3fc00-f22c-11ea-989b-e6e606a4a613.png">

**Desktop (please complete the following information):**

- OS: Mojave 10.14.6
- Browser: Google chrome
- Browser Version: 85.0.4183.83

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
These are the 2 grants I created: https://gitcoin.co/grants/1128/commons-stack-community-fund-panvala-league-2
https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league
Regardless of what it takes to fix this bug it would be great if y'all could just fix the category for me on this one grant :)

**Comment by GriffGreen** [comment]
Please use https://gitcoin.co/grants/1128/commons-stack-community-fund-panvala-league-2 and delete the 1127 one

We are linking to the 1128 one everywhere.

**Comment by owocki** [comment]
@thelostone-mc this seems like a bug with the new category models?  cc @zoek1 in case he wants to take a look

**Comment by GriffGreen** [comment]
There are 2 issues here... we also couldn't cancel the grant probably related to #7223

**Comment by zoek1** [comment]
I'll be able to tackle this until friday

**Comment by alexander-morris** [comment]
We are experiencing this issue as well with our grant here: https://gitcoin.co/grants/1116/weteachblockchain-free-decentralized-education-2 

We clicked 'Education' for the subcategory, but ended up with 'Reddit'

**Comment by owocki** [comment]
@zoek1 any luck

**Comment by thelostone-mc** [comment]
I wasn't able to reproduce this locally but it does seem to happen in live 
I've updated the grant subcategory @alexander-morris  + @lorelei1 to unblock you

**Comment by GriffGreen** [comment]
> Please use https://gitcoin.co/grants/1128/commons-stack-community-fund-panvala-league-2 and delete the 1127 one
> 
> We are linking to the 1128 one everywhere.

Not sure what happened here... but somehow 1128 got canceled and 1127 is now our live grant... :-( 

" More work?"

![more work?](https://user-images.githubusercontent.com/14945613/93114708-3400b400-f6bb-11ea-9fa5-496131e5f0af.gif)
