### ISSUE TITLE
round7 bus

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7352]
#### Fixed

- fixed decimal point and added , separator to values
- fixed up logic to show right info when clr is active / not , when grant is part of clr or not , grant is eligible for clr or not
- fixed grant title overflowing to multiple lines
- fix up card view for grants
- show contribution button only if user has logged in
- fix up banner overflowing search field
- update icons for My Contributions + Fav button
- hide browse grants button if data is available
- reload banner + sponsor when switching btwn  categories
- highlight only selected subcategories 
- fix issue of grant category not loading and failing randomly https://share.vidyard.com/watch/SN8r1DEuCsAUetHAAB3tLc?
- Pagination not working
- Unable for admin to switch btwn mainnet & rinkeby bounties
- Show sybil info on cardview
- the 'all time funding' field doesnt seem to work https://bits.owocki.com/E0unNxBL
- lets remove the 'browse grants' button; it is not needed
- none of the grants show the match estimates for the current round.
- activity view no longer works https://bits.owocki.com/8LuPWXXo
- count is correct but not all grants are being fetched (due to some weird additional filter being applied)
[SEE HERE](https://user-images.githubusercontent.com/5358146/92828527-c3267700-f3f0-11ea-87f5-66dfea564b24.png)
- responsive design is messed up on the list view https://bits.owocki.com/7KuLwDrr
- http://localhost:8000/grants/tech?network=rinkeby The network param doesn't get applied when entered via URL
- My Grants doesn't work
- can u pls reverse the coloring of these filters? https://bits.owocki.com/E0unNxNL
- Grants Cart info + tokens list is missing
[image](https://user-images.githubusercontent.com/5358146/92933048-5c8e7100-f463-11ea-8f72-9eb218f3e769.png)
- https://github.com/gitcoinco/web/issues/7319

**Comment by octavioamu** [comment]
> Grants Cart info + tokens list is missing

seems now is fixed 
![image](https://user-images.githubusercontent.com/1358093/92947365-4914e300-f42e-11ea-8028-09cf1dcda6d8.png)

**Comment by octavioamu** [comment]
> team member removed on edit description #7319 (Yet to verify)
Seems worked fine for me
