### ISSUE TITLE
Discover Great Projects on Gitcoin

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7355]
### User Story

As a developer/sponsor I'd like a way to discover great projects that are results of hackathons  on Gitcoin.

### Why Is this Needed

We have a ton of amazing projects that have come out of various hacks, but we don't have a single page for people to see these success stories (per Scott).

- We want to showcase all of the amazing projects
- Community engagement 
- Great for Bd conversations

### Current Behavior
- No central location to discover great projects on Gitcoin

### Expected Behavior
- go to gitcoin.co/projects

### Definition of Done

- Add link to projects in thee top nav
- Build as separate page
- Build page as shown below (maybe use best flag idea if this is a simple way to build it)
- Display all hackathon winners sort by when the project was created on Gitcoin so latest projects come up on top
- V1 = Show all results
- build responsive view
- each project card clicks through to project details 

Nice to have
- V1.1 =  Ability to have a search filter, search by project name
- V1.5 = Add like for a project, surface comments
### Data Requirements
- increase in hack participation/start/submit work
- qualitative feedback
- hack renewals/upsells

### Additional Information

Consider making a repeatable pattern for projects or tribes.

<img width="792" alt="Screen Shot 2020-10-13 at 12 27 34 AM" src="https://user-images.githubusercontent.com/238235/95816429-168c2d80-0ced-11eb-893d-571c6a959519.png">

<img width="950" alt="Screen Shot 2020-10-13 at 12 32 58 AM" src="https://user-images.githubusercontent.com/238235/95816399-03795d80-0ced-11eb-8fef-e93b98295a67.png">

**Comment by PixelantDesign** [comment]
**Potential Approaches**

- A dedicated page to showcase projects with a filter by hackathon projects, grants projects, or projects associated grants.
- Display on gitcoin.co/results and re-use the hackathon project page.. just have a ‘best’ flag that we set to true for anyone we want to show up on /results

**Comment by aamustapha** [comment]
@octavioamu What do you think?

**Comment by PixelantDesign** [comment]
Updated based on our discussion @thelostone-mc , am I missing anything?

**Comment by frankchen07** [comment]
1. Do we have customer feedback as to how they would use this page? Is the they in this case, sponsors specifically? What has Scott actually heard from customers?

2. If they do use it, how would they use it in relation to how it's filtered? What would they like it filtered on? Otherwise it's just one big smattering post of past and present hackathon projects.

3. Do we showcase a larger featured section that holds winners of past hackathons?

**Comment by PixelantDesign** [comment]
yep customers and developers, they like the page, the categories, and the trending information specifically but we took it out for V1.

**Comment by ceresstation** [comment]
I would say that we can even, for a first pass, avoid letting people search the page and just list 10-20 top projects we think are really cool statically. I'd also advocate for making each card slightly bigger and have fewer per row, we really just want to show what the most interesting things are that hackers have built.

**Comment by ceresstation** [comment]
I would also advocate for *not* mixing grants with hackathon projects, as these are very different products with different users. Maybe at one point they'll overlap more but I think the audience is distinct.

**Comment by PixelantDesign** [comment]
its not a mix. it denotes grants associated.

**Comment by PixelantDesign** [comment]
> I would say that we can even, for a first pass, avoid letting people search the page and just list 10-20 top projects we think are really cool statically. 

This is a possibility that @thelostone-mc and I have discussed.

**Comment by aamustapha** [comment]
> just list 10-20 top projects we think are really cool
What are the criteria for "Cool"?

**Comment by PixelantDesign** [comment]
@aamustapha I think we'd have to go by this as previously discussed with @thelostone-mc and defined in the story:

_Display all hackathon winners sort by when the project was created on Gitcoin so latest projects display at the top_

**Comment by zoek1** [comment]
ETA November 11, 2020

**Comment by PixelantDesign** [comment]
@zoek1 didd you start this?
