### ISSUE TITLE
Invoice totals not displaying correctly

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#7357]
**Describe the bug**

Currently on invoices with multiple payouts the total displayed only includes one payout. Example here: https://gyazo.com/a45661af2565f81e5b2c350e5d80a7ee

**To Reproduce**

Create a bounty and hence invoice with more than one line item and review the total at the bottom of the PDF. 

**Expected behavior**

Some $x times N should be $x*N.

**Comment by sanchaymittal** [comment]
Not reproducible in local testing env, it is not fetching data for local.
IMO, code looks correct, it might be a data issue.

Here, Line 1424 is taking care of the total amount.
![Screenshot 2020-09-16 at 6 07 51 PM](https://user-images.githubusercontent.com/31698676/93411880-b5259a00-f8b9-11ea-8eb9-38d4a339b807.png)

**Comment by thelostone-mc** [comment]
resolved + code fix deployed
