### ISSUE TITLE
Need exact dates of payments

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7361]
For bookeeping purposes, I need _exact_ dates for each payment I send/receive through GitCoin!!

There is no UI for that now.

**Comment by owocki** [comment]
https://gitcoin.co/settings/account

can u export ur earnings ?

**Comment by vporton** [comment]
> https://gitcoin.co/settings/account
> 
> can u export ur earnings ?

Yes I can. But it is unnoticeable in the UI and presents no GUI to view. These are misfeatures.

**Comment by thelostone-mc** [comment]
Could you open up a new issues with more details on what the issue / possible solution. We can then check out if this is something which needs to be done / bountied out / pursued at a later point in time
