### ISSUE TITLE
change bounty form does not present correct bounty amount as a prefill

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7366]
https://gitcoin.co/issue/gitcoinco/web/7363/100023697

when i go to edit this issue, a very small number gets prefilled into the bounty details page https://bits.owocki.com/2NuyZjgE

It should prefill with the bounty amount (currently 30 ETH)

**Comment by vbeffa** [comment]
I'm unable to reproduce this. I'm not sure how to navigate from the first link to the edit page, but if I go directly to https://gitcoin.co/bounty/change/23697 I see this:

![Screen Shot 2021-01-27 at 2 34 30 PM](https://user-images.githubusercontent.com/6473744/106050795-81684580-60df-11eb-8efe-03455cca944d.png)

CC @Kweiss

**Comment by thelostone-mc** [comment]
This was fixed a few days after the report ! thanks for checking up on this @vbeffa
