### ISSUE TITLE
I need recurring bounties

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7373]
I want to pay some sum to person(s) every week (or not every week, if I am unable to pay in a given week) for doing recurring work.

Please add such a feature to Gitcoin.

While there is no such special feature, how can I do this with Gitcoin now? I am afraid that if I post a bounty every week, this would be like spam. What to do?

**Comment by thelostone-mc** [comment]
You could ask the user to open up a grant and fund them via that
