### ISSUE TITLE
Unable to verify twitter account

### ISSUE THREAD

**Issue by lu-calm** [gitcoinco/web#7379]
Tried to verify my account going through the process and tweeting the required info ([https://twitter.com/lu_calm/status/1305639938717749248](https://twitter.com/lu_calm/status/1305639938717749248))

But it didn't seem to work

**Comment by willsputra** [comment]
@lu-calm could you send us the link to your grant? thank you! :)

**Comment by thelostone-mc** [comment]
You'd have to verify from the twitter link of the Grant!
In your case -> both were supposed to be the same 
It has been verified now :D

@lu-calm will make a note to update the UI to let folks know to use thier personal twitter account if they don't have a dedicated one for their grant
