### ISSUE TITLE
Not sure how to verify my grant?

### ISSUE THREAD

**Issue by chloethedev** [gitcoinco/web#7380]
I am having an issue verifying my grant: https://gitcoin.co/grants/902/the-marma-j-foundation. I tweeted the given statement, but I am not getting any indication I have done it correctly, and it still seems unverified.

**Comment by owocki** [comment]
@chloethedev u have to click 'verify' on the modal after the tweet is out so it can go fetch the tweet.

@zoek1 maybe we could clean up the UI here/make it more claer?

**Comment by chloethedev** [comment]
When I clicked the verify button it gave me a red status text saying to not remove the inform " I verify that I own XYZ Grant” I had to leave the house so I left that open but it's been open for about 20 minutes so far.

**Comment by chloethedev** [comment]
@owocki by the way, thank you very much for the quick response.

**Comment by willsputra** [comment]
@chloethedev looks like there's no twitter account associated to your grant when you created it, so the verification didn't work. we're working on a fix so you can add a twitter account when you edit your grant - will keep you posted! :)

**Comment by chloethedev** [comment]
@willsputra Thank you for the update. Just trying to make sure I am doing everything correctly. Thanks for all the great work you all do!

**Comment by thelostone-mc** [comment]
@chloethedev could you point us to the tweet as well you make from your account ?

**Comment by chloethedev** [comment]
@thelostone-mc the link to is is here: https://twitter.com/Chloethedev/status/1305644788331483138?s=19

**Comment by thelostone-mc** [comment]
@chloethedev grant is now verified :)
Have a good CLR round <3 

Closing this out now
