### ISSUE TITLE
Grant Verification

### ISSUE THREAD

**Issue by JTraversa** [gitcoinco/web#7381]
Looking for a hand with my grant verification. much appreciated as always!

Grant: https://gitcoin.co/grants/1103/the-defihedge-protocol 

Twitter Post: https://twitter.com/TraversaJulian/status/1305636668729417728

**Comment by owocki** [comment]
whats the issue u r having ?  maybe @zoek1 can help?

**Comment by JTraversa** [comment]
When clicking "verify" i get the message,

" Don't remove the intent "I am verifying my ownership of The DefiHedge Protocol on Gitcoin Grants at https://gitcoin.co/grants/1103/the-defihedge-protocol." "

Am I missing something and there is there another step?

**Comment by willsputra** [comment]
@JTraversa   looks like there's no twitter account associated to your grant when you created it, so the verification didn't work. we're working on a fix so you can add a twitter account when you edit your grant - will keep you posted! :)

**Comment by JTraversa** [comment]
Woopsies, makes sense hah apologies for the spam!
