### ISSUE TITLE
kevins grants deploy day QA

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7382]
showstoppers
- [x] cant checkout with zksync due to CORS issue (dmed matt about this)

major issues
- [x] default number when i add to cart is 0 DAI https://bits.owocki.com/6quel2AX - it should default to 5 DAI
- [x] each grant card says "last clr match round" instead of 'clr match round 7' or 'infra match round'
- [x] theres no way to browse by infra tech vs app tech in the UI - how do i know which round my grant is in?
- [x] the cards say 'final clr match' instead of 'estimated clr match' https://bits.owocki.com/Jru6RLYJ
- [x] the list view showstoal amount raised + not amount in round https://bits.owocki.com/4gu9q9DE
- [x] when you scroll down the page, then the infinite scroll grnats get inserted at random places
- [x] change the order on Grant Types (order by clr amount)
- [x] migrate grants from dapp -> infra tech  
- [x] rename media to community
- [x] fix image https://gitcoin.co/grants/?keyword=octavio
- [x] verification call dates should be in local times https://bits.owocki.com/6quelnGv

other
- [x] no way to edit my twitter account info; or my funding info, on the grants detail page
- [x] need to mark current matching partners as current 
- [x] this matching module shows past sponsors when current sponsors are selected https://bits.owocki.com/12uJYJ4E
- [x] community round shows that its completed, but really its active https://bits.owocki.com/6queler4 **[ NEED TO ADD MATCHING PARTNER**]

**Comment by willsputra** [comment]
- grants cart not loading (stuck at "Fetching cart data"), also saw this 404 for brightid, could it be the reason?
![Screenshot 2020-09-15 at 10 10 29 AM](https://user-images.githubusercontent.com/19514207/93156997-e2e4d480-f73b-11ea-8d48-9a7b6dd1f3b6.png)
![Screenshot 2020-09-15 at 10 10 33 AM](https://user-images.githubusercontent.com/19514207/93156999-e4ae9800-f73b-11ea-82b2-7829810c1e38.png)

**Comment by mds1** [comment]
@willsputra Were there any other errors in the console when you saw that?

**Comment by willsputra** [comment]
> @willsputra Were there any other errors in the console when you saw that?

@mds1 saw this one too. Brave V1.13.86 btw.
<img width="534" alt="Screenshot 2020-09-15 at 9 03 32 PM" src="https://user-images.githubusercontent.com/19514207/93213873-00935780-f797-11ea-8d81-8a7bc77ffa93.png">

**Comment by willsputra** [comment]
@mds1 I just tried it again. this happens when my Metamask is locked. after I unlock Metamask and refresh the page, it works!

**Comment by mds1** [comment]
From your screenshot, it looks like the cause of the issue is that you don't have a wallet connected, which makes sense because the error message says `Cannot read property eth of undefined`. It should prompt you to connect a wallet on page load though

**Comment by willsputra** [comment]
hmm I didn't seem to get any prompt, just stuck at fetching cart
https://share.vidyard.com/watch/Y92SB1MvUZ3Z6CY3KfiTDt?

**Comment by mds1** [comment]
Hey @octavioamu, any idea why the wallet connection prompt isn't showing up? `needWalletConnection()` is called in `cart.js` so that should display the prompt

**Comment by owocki** [comment]
verification call dates should be in local times https://bits.owocki.com/6quelnGv

**Comment by owocki** [comment]
it shouldnt show 'last CLR round' when no round is active' https://bits.owocki.com/6quegKwE

**Comment by thelostone-mc** [comment]
@owocki cause two of those are Grant Type -> change and the community one has been marked in DB as not eligible for CLR
