### ISSUE TITLE
Grant Verification

### ISSUE THREAD

**Issue by zawadilabs** [gitcoinco/web#7385]
We did not include our twitter handle when posting the grant. How do we get verified? I cannot find an option to add the twitter account.

**Comment by willsputra** [comment]
@zawadilabs Hi! You can go to your Grants page and click "Edit Info" to add your twitter handle. Let me know if you're still facing any problems :)

**Comment by octavioamu** [comment]
@zawadilabs you should be able to add your twitter username now

**Comment by thelostone-mc** [comment]
Closing this now ! Do reopen if you continue to face the issue
