### ISSUE TITLE
Repace double @@ on twitter URLs

### ISSUE THREAD

**Issue by Mitchellpkt** [gitcoinco/web#7386]
The text box prompt for creating a grant suggests an `@` in the handle, see below:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/21246742/93155043-64981c00-f6c2-11ea-9d9e-e4543deb49ca.png">

I submitted in this format `@InsightObservatory`, and posted the [verification tweet](https://twitter.com/InsightObserva1/status/1305682826096832512). Unfortunately, the Verify button does not work because it seems to append an additional `@` and it naturally cannot locate a tweet at `twitter.com/@@InsightObservatory`

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/21246742/93155201-c48ec280-f6c2-11ea-99fd-e924054b523c.png">

**Comment by Mitchellpkt** [comment]
Actually, I'm not sure what's going on... I nuked the first grant, and made a second one, being very careful to leave off the `@` suffix during registration. But I am encountering the same verification failure.

**Comment by Mitchellpkt** [comment]
Here is the grant: https://gitcoin.co/grants/1164/observatory-netsec-dashboard-api-and-research-da-2

And the post: https://twitter.com/InsightObserva1/status/1305685763179208704

**Comment by thelostone-mc** [comment]
It looks like your handle is incorrect !
It should be `InsightObserva1`

**Comment by thelostone-mc** [comment]
@Mitchellpkt you should be able to edit the twitter link as well! we just rolled this out

**Comment by Mitchellpkt** [comment]
Oops, closing because PEBCAK :- P
