### ISSUE TITLE
Tooltip doesn't show up on hover of Verified logo on Grants cards

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7387]
**Describe the bug**

Tooltip doesn't show up on hover of Verified logo on Grants cards.

On Grid view, tooltip blinks and doesn't show up properly on hover.
On List view, the tooltip doesn't show up at all on hover.
https://share.vidyard.com/watch/KjXpFRa8F1DBxR4NyYxSaQ?

**To Reproduce**

Go to https://gitcoin.co/grants and hover on the blue checkmark on Grants card

**Expected behavior**

Tooltip shows up on hover.

**Comment by willsputra** [comment]
On Grants details page, the tooltip doesn't appear long enough for me to click "Learn more"
https://share.vidyard.com/watch/zcuk1hyA6ouhVNHZkGcgAm?

**Comment by AnkitSingh-zm** [comment]
I will work on this.
