### ISSUE TITLE
Can't edit Twitter link

### ISSUE THREAD

**Issue by lucadgtrip** [gitcoinco/web#7388]
In the Twittter field I inserted https://twitter.com/tripscommunity instead of tripscommunity.
Now it links to https://twitter.com/https://twitter.com/tripscommunity
and there seem to be no way to fix it.
Edit My Info shows an empty field, when I add tripscommunity, it doesn't change it.

I can't verify my Twitter account as a result.

![gitcoin twitter bug](https://user-images.githubusercontent.com/34341206/93165655-49122d00-f725-11ea-9d37-1beff25a0f13.png)

**Comment by lucadgtrip** [comment]
never mind, I launched a new grant and cancelled this one

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by thelostone-mc** [comment]
This has been rolled out ! You should be able to edit the twitter link
