### ISSUE TITLE
Unable to add twitter account post grant creation to then verify

### ISSUE THREAD

**Issue by lu-calm** [gitcoinco/web#7389]
I am having issues with the twitter verification process.

I have realised it might be because I didn't submit a twitter account when I first submitted the grant proposal.

I am unable to see the location for a twitter account to be added when I click the edit button.

Gitcoin Grant Page - [https://gitcoin.co/grants/1119/eth-ter-i-die?tab=contributors](https://gitcoin.co/grants/1119/eth-ter-i-die?tab=contributors)

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by willsputra** [comment]
@lu-calm we're working on a fix! :)

**Comment by zoek1** [comment]
Hi @lu-calm, thanks for your patience. The option to add/edit the twitter account was added, can you add your twitter account to your grant and repeat the verification process. Let me know if it works for you! :smiley:

**Comment by thelostone-mc** [comment]
Closing this out as the grant has now been verified
