### ISSUE TITLE
Verifying Twitter fails

### ISSUE THREAD

**Issue by ErikBjare** [gitcoinco/web#7390]
> Warning: This grant has not verified their ownership of the twitter account listed. 

So, a few things:

 1. I don't see a Twitter account listed? (and no way to set it)
 2. Trying to verify the Twitter account we have (@ActivityWatchIt) fails.
 3. The account is empty (see attached image).

The grant: https://gitcoin.co/grants/383/activitywatch-open-source-automated-time-tracker

The tweet: https://twitter.com/ActivityWatchIt/status/1305764224510169089

![image](https://user-images.githubusercontent.com/1405370/93177013-6a2d4a80-f732-11ea-81b3-2a1a9792898d.png)

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by willsputra** [comment]
@ErikBjare  looks like there's no twitter account associated to your grant when you created it, so the verification didn't work. we're working on a fix so you can add a twitter account when you edit your grant - will keep you posted! :)

**Comment by zoek1** [comment]
Hi @ErikBjare, thanks for your patience. The option to add/edit the twitter account was added, can you add your twitter account to your grant and repeat the verification process. Let me know if it works for you! :smiley:

**Comment by ErikBjare** [comment]
Wow, you guys work fast! Works perfectly, thanks.
