### ISSUE TITLE
Verify my grant 

### ISSUE THREAD

**Issue by coolcryptomaniac** [gitcoinco/web#7392]
Kindly verify my grant 

Already tweeted with twitter id @cryptocyclops but it's not working.

**Comment by thelostone-mc** [comment]
@coolcryptomaniac could you share the grant link + twitter link ?

**Comment by coolcryptomaniac** [comment]
Grant link - https://gitcoin.co/grants/362/cryptomaniac-crypto-blog-with-media-and-entertain

Tweet link - https://twitter.com/cryptocyclops/status/1305782470948712448?s=20

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by willsputra** [comment]
@coolcryptomaniac looks like there's no twitter account associated to your grant when you created it, so the verification didn't work. we're working on a fix so you can add a twitter account when you edit your grant - will keep you posted! :)

**Comment by coolcryptomaniac** [comment]
Ok np, there was no option back then to add twitter account when I created the grant. Still this time very great changes has been made I am liking the design and over all feel , will try to give suggestions after few days ☺️👍

**Comment by zoek1** [comment]
Hi @coolcryptomaniac, thanks for your patience. The option to add/edit the twitter account was added, can you add your twitter account to your grant and repeat the verification process. Let me know if it works for you! :smiley:

**Comment by thelostone-mc** [comment]
Closing as grant is now verified
