### ISSUE TITLE
Grant Verification Issue

### ISSUE THREAD

**Issue by hernandezema** [gitcoinco/web#7394]
Can you kindly verify me

I already tweeted with twitter id @digiwills_io but it's not working.

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/pull/7384 should allow you edit twitter field !
Could you also share your grant link so that we can verify ?

**Comment by octavioamu** [comment]
@hernandezema I don't see your verification tweet on your twitter account https://twitter.com/digiwills_io
You should tweet from that account and press the verify button.

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by willsputra** [comment]
@hernandezema could you share your grant url? thanks! :)
