### ISSUE TITLE
Not able to edit my twitter handle at Gitcoin Grant

### ISSUE THREAD

**Issue by tarun1475** [gitcoinco/web#7395]
Hey Team, 

I have created a gitcoin grant and entered the twitter handle incorrectly by mistake. 
How can i edit that as it is showing cannot verifying your twitter account. 

https://gitcoin.co/grants/1099/parcel

Thanks

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/pull/7384 will be rolled out in a few hours!

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by thelostone-mc** [comment]
This has been rolled out ! You should be able to edit it
