### ISSUE TITLE
Cannot Verify BCComparison Twitter profile for grant

### ISSUE THREAD

**Issue by jrmr92** [gitcoinco/web#7396]
![image](https://user-images.githubusercontent.com/37453027/93206084-2568da00-f759-11ea-81c4-0d46965219a4.png)

**Comment by owocki** [comment]
@zoek1 can u help here? seems a lot of ppl are having issues verifying their grant.

**Comment by willsputra** [comment]
@jrmr92 could you share your grant link here? thanks! :)

**Comment by jrmr92** [comment]
Hi William,

Thanks for getting back so quickly.

Here's the link:
https://gitcoin.co/grants/1173/blockchain-comparisoncom-1-support-to-help-you-gro

William S. Goi <notifications@github.com> schrieb am Di., 15. Sep. 2020,
18:16:

**Comment by zoek1** [comment]
Hi @jrmr92, thanks for your patience. It seems twitter short the name of your grant due twitter detect it as a URL. Now it should be fixed, could you repeat the verification process and let us know if it works?

**Comment by jrmr92** [comment]
Fantastic, it worked. Thanks for the magic 😄

Miguel Angel Gordián <notifications@github.com> schrieb am Di., 15. Sep.
2020, 23:17:
