### ISSUE TITLE
Grants/zkSync checkout: what happens if deposit tx fails?

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7397]
**Describe the bug**

When my deposit tx (Step 3) failed (https://etherscan.io/tx/0x6858b7f3ae7e497c7401aba9b469e67c7b47bae90d249d77a77fa305dbb5ded3), the modal still says Processing although "View transaction" still brings you to the failed tx.

The "X of 10 confirmation" still continues but I was stuck at the "Waiting for deposit to be confirmed with zkSync". My DAI didn't seem to get transferred anywhere too. 

https://share.vidyard.com/watch/32mEgi4ndiTeRcPMRG83qw?

**To Reproduce**

1. Checkout with zkSync
2. Finish Step 1
3. Finish Step 2
4. Do Step 3, but transaction failed
5. Tried closing and reopening the modal, still doesn't work
6. Tried refreshing the page and reopening the modal, still doesn't work

**Expected behavior**

It should notify me that my tx failed and maybe submit a new tx?

**Comment by owocki** [comment]
@mds1

**Comment by willsputra** [comment]
@mds1 an update on this one:

I don't think I've ever resolved this tx. When I go back to cart, I got the "Complete zkSync Checkout" modal but stuck at "Step 3: Confirm Donation Transaction"

![Screenshot 2020-09-19 at 2 41 34 PM](https://user-images.githubusercontent.com/19514207/93660916-421d4e80-fa86-11ea-90e6-d448f4b3c0d9.png)

"View transactions" doesn't show me any transfer transaction. Tried depositing DAI directly to https://wallet.zksync.io/ but still doesn't work.
https://zkscan.io/explorer/accounts/0x63b265D170f35d6bb724A6c00b4DcC822EA97867

**Comment by mds1** [comment]
Thanks for the reminder! I fixed the underlying cause here but forgot to handle the failed transaction case. I will take a look at this on Monday, sorry for the delay!

**Comment by willsputra** [comment]
no prob at all. thanks! :)

**Comment by mds1** [comment]
Resolved by #7489
