### ISSUE TITLE
Twitter verification failure

### ISSUE THREAD

**Issue by cranders1** [gitcoinco/web#7398]
Error:
Don't remove the intent "I am verifying my ownership of Pandemic Pods &amp; Distance Learning on Gitcoin Grants at https://gitcoin.co/grants/1198/pandemic-pods-distance-learning."

Verification tweet
https://twitter.com/AmwFund/status/1305886270611009536?s=20

**Comment by willsputra** [comment]
@cranders1 could you try this:
1. Go to your Grants page
2. Click "Edit Info"
3. Remove the "@" from your twitter handle
4. Verify again?

Thank you! Let us know if you're still facing any problems :)

**Comment by cranders1** [comment]
Thnx @willsputra 
Updated the Twitter user name to AmwFund w/o the @. Still failing.
Error:
Unable to verify tweet from AmwFund. Is the twitter post live? Was it sent from AmwFund?
 Tweet
https://twitter.com/AmwFund/status/1305980553313677312?s=20
Much thanks.

**Comment by owocki** [comment]
@zoek1 is it maaybe a casing issue?  im noticing the fialiures all have upper case letters in them

**Comment by zoek1** [comment]
No @owocki, twitter escape the characters, in this case '&' in "Pandemic Pods & Distance Learning". This should be fixed in https://github.com/gitcoinco/web/pull/7414

**Comment by cranders1** [comment]
thnx @owocki and @zoek1 
happy to change '&' to 'and' as nec
gotta run. will check back tonight for guidance.
cheers.

**Comment by thelostone-mc** [comment]
@cranders1  the fix has been deployed ! could you try once again ?

**Comment by cranders1** [comment]
cheers @thelostone-mc
