### ISSUE TITLE
can't verify my twitter for my grant

### ISSUE THREAD

**Issue by DeFiDude** [gitcoinco/web#7399]
![image](https://user-images.githubusercontent.com/59237470/93229279-090a7480-f73c-11ea-98e6-82ef61b94329.png)

grant is for archivenode.io

**Comment by DeFiDude** [comment]
Here's the tweet: https://twitter.com/ArchiveNode/status/1305886982120366080

and the grant: https://gitcoin.co/grants/1101/archivenodeio-the-public-access-ethereum-archive-n

**Comment by willsputra** [comment]
@DeFiDude could you try this:
1. Go to your Grants page
2. Click "Edit Info"
3. Remove the "@" from your twitter handle
4. Verify again?

Thank you! Let us know if you're still facing any problems :)

**Comment by DeFiDude** [comment]
Just tried it again doing that and it didn't work @willsputra 

I also tried removing the tweet and redoing the entire process to no avail with the @ removed

**Comment by willsputra** [comment]
@DeFiDude gotcha. we're investigating now, will update you soon!

**Comment by owocki** [comment]
just verified this grant manually since defidude is a known entity

**Comment by zoek1** [comment]
It seems twitter short the "ArchiveNode.io" fragment of your grant due twitter detect it as a URL. Now it should be fixed.
