### ISSUE TITLE
Grants: As a grant donor, I would like to know why some grants are "Not Eligible for CLR"

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7400]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a grant donor, I would like to know why some grants are "Not Eligible for CLR"

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Some grants on https://gitcoin.co/grants/ are showing as "Not Eligible for CLR", and as a grant donor I'd like to understand why this is so.
<img width="377" alt="Screenshot 2020-09-15 at 11 12 31 PM" src="https://user-images.githubusercontent.com/19514207/93229335-101b9c00-f7a9-11ea-9830-50fef8cef0b1.png">

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No explanation on "Not Eligible for CLR"

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Have a question mark next to "Not Eligible for CLR" and display an explanation on hover

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Have a question mark next to "Not Eligible for CLR" and display an explanation on hover

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thelostone-mc** [comment]
Oh that was a request for vivek like ensure grants like personal grant / kernel don't get listed !
I don't think it's applicable for public grants in general

**Comment by thelostone-mc** [comment]
Looks like we've updated the text to state -> not part of a particular round instead of not eligible !
