### ISSUE TITLE
Verify and Remove Old Grant

### ISSUE THREAD

**Issue by WestCoastWalker** [gitcoinco/web#7401]
I have shared my Twitter comment, but the UI is not allowing me to "verify".

Also, I have two grants created. I am trying to delete the one that uses the moneygames_info Twitter handle. However, everytime I delete it, it does not get removed. Please remove the moneygames_info grant, but leave the moneygames.info grant.

Thanks!

**Comment by willsputra** [comment]
Hi @WestCoastWalker , was there any error that you encountered when you tried to "Verify"? cc @zoek1

**Comment by WestCoastWalker** [comment]
Yes, nothing happened. It was like the verify button was dead or disabled.

**Comment by willsputra** [comment]
@WestCoastWalker I see... could you share your grant link here? will take a look. thanks!

**Comment by WestCoastWalker** [comment]
Thanks!

https://gitcoin.co/grants/1067/moneygamesinfo-2

**Comment by zoek1** [comment]
Hi @WestCoastWalker, thanks for your patience. It seems twitter short the name of your grant due twitter detect it as a URL. Now it should be fixed, could you repeat the verification process?

**Comment by thelostone-mc** [comment]
@WestCoastWalker I'd also recommend canceling the other grants as well so that you get max clr match possible

**Comment by WestCoastWalker** [comment]
Thanks, I was able to verify!

Aditya, I am not able to cancel the first grant I made moneygames.info (had
wrong twitter).... I want to keep the moneygamesinfo one but cant delete
the other one.

Thanks!
