### ISSUE TITLE
CORS issue with zkSync API prevents giving money

### ISSUE THREAD

**Issue by sembrestels** [gitcoinco/web#7403]
**Describe the bug**

On the grants cart page, when donating to a grant and clicking on Checkout with zkSync, I get the following error in the console:

![Screenshot from 2020-09-15 18-24-24](https://user-images.githubusercontent.com/931684/93237681-b99a6780-f780-11ea-810b-bee23af0d494.png)

**To Reproduce**

Add a grant in the cart, go to https://gitcoin.co/grants/cart and click on `Checkout with zkSync`.

**Expected behavior**

The call to zkSync API that sends the following info `{id: 1, jsonrpc: "2.0", method: "account_info", params: ["<my-address>"]}` should work, but returns a 504 error:

![Screenshot from 2020-09-15 18-33-38](https://user-images.githubusercontent.com/931684/93238836-4134a600-f782-11ea-8c5e-6c04189ba86c.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Brave
- Browser Version: 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by owocki** [comment]
working on this with the zksync team

**Comment by thelostone-mc** [comment]
This should be fixed by now
