### ISSUE TITLE
Can't verify grant as no project twitter account was specified

### ISSUE THREAD

**Issue by Jeff-Emmett** [gitcoinco/web#7404]
Hello there,

I'd like to verify the following grant: https://gitcoin.co/grants/1141/conviction-voting-cadcad-model-feature-improvement

But I'm not able to as a "project twitter account" was not specified in the grant creation process, and I am not able to add one after the fact.

Plz help!  Thank you kindly =)

Jeff

**Comment by willsputra** [comment]
@Jeff-Emmett we're working on a fix! :) you should be able to add your twitter account once the fix is live. will keep you posted!

**Comment by zoek1** [comment]
@Jeff-Emmett the option to add your twitter account is now available for your grant. Let us know if it works!

**Comment by thelostone-mc** [comment]
@Jeff-Emmett Could you tweet from your own account and get the grant verified ?

**Comment by Jeff-Emmett** [comment]
Changed and verified! Thanks for your help!

Jeff
