### ISSUE TITLE
Grants/BrightID Event timezones

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7406]
It's not clear which timezone the BrightID events are in. We should show the timezone or better, show it in the user's timezone.
<img width="492" alt="Screenshot 2020-09-16 at 12 53 18 AM" src="https://user-images.githubusercontent.com/19514207/93240726-11ec5c00-f7b7-11ea-84ca-3c0ea567c27b.png">

**Comment by thelostone-mc** [comment]
![image](https://user-images.githubusercontent.com/5358146/93288383-5a2c6e00-f7f9-11ea-9226-fa0c105b6882.png)

Pushed into stable + will deploy later
