### ISSUE TITLE
twitter verification for buidler-deploy grant

### ISSUE THREAD

**Issue by wighawag** [gitcoinco/web#7407]
Hey I saw warning message telling the twitter account associated with grant was not verified
So I tried to verify via twitter but then after posting the following message : https://twitter.com/wighawag/status/1305912672857337857 and clicking "verify" it tell me that I do not have a twitter account associated with my account
So not sure what to do if anything 
Thanks

**Comment by willsputra** [comment]
@wighawag could you share your grant link here? will take a look. thanks!

**Comment by wighawag** [comment]
The link is in the tweet :)  https://gitcoin.co/grants/972/buidler-deploy
Thanks!

**Comment by zoek1** [comment]
It seems you don't have a twitter account in your grant. Can you added and repeat the verification process? Let us know if it works for you!

**Comment by wighawag** [comment]
Hi @zoek1 as mentioned in my tweet replies, I have no idea how to do it 
the reason I started the process was that I got a warning on the website telling me to verify my twitter account. which is weird if never associated it

**Comment by zoek1** [comment]
Ok, here is a video about how to verify your gitcoin grant. 
https://www.loom.com/share/651db889ec8e4f21817843b808aae8f7

**Comment by thelostone-mc** [comment]
Looks like this grant is now verified ! closing this out
