### ISSUE TITLE
Grant verification failed

### ISSUE THREAD

**Issue by realChainLife** [gitcoinco/web#7409]
Just created a new grant for our #Kernel project [Porium](https://github.com/porium), tried using a listed [personal twitter account](https://twitter.com/realChainLife) to verify [the grant](https://gitcoin.co/grants/1209/porium) by sending out a [tweet](https://twitter.com/realChainLife/status/1305947126103502853) but so far verification has failed. 

Kindly help me troubleshoot this.

**Comment by zoek1** [comment]
It seems you don't have a twitter account in your grant. Can you add your twitter account clicking in the edit info button? after that save your changes and repeat the verification process. Let us know if it works for you!

**Comment by thelostone-mc** [comment]
I've changed the twitter handle to your account @realChainLife and your grant is now verified :)

**Comment by realChainLife** [comment]
Thank you @thelostone-mc
