### ISSUE TITLE
How do I add a twitter handle for a grant?

### ISSUE THREAD

**Issue by aliatiia** [gitcoinco/web#7410]
<img width="496" alt="Screen Shot 2020-09-15 at 3 43 19 PM" src="https://user-images.githubusercontent.com/42751398/93257097-5bfb2080-f76a-11ea-8796-329c919b3b2d.png">

**Comment by owocki** [comment]
@zoek1 working on a PR

**Comment by aliatiia** [comment]
Thanks @owocki meanwhile could you guys manually tie up this grant to this twitter handle `aliatiia_`? Or should I just delete and start a new grant?

**Comment by owocki** [comment]
done

**Comment by aliatiia** [comment]
The [tweet is live](https://twitter.com/aliatiia_/status/1305959408342634496?s=20) but I don't think the system is picking it up

<img width="1275" alt="git" src="https://user-images.githubusercontent.com/42751398/93259645-26583680-f76e-11ea-9d41-f13a76fdc25d.png">

**Comment by owocki** [comment]
hmmm @zoek1 any idea?

**Comment by zoek1** [comment]
Sure, it seems twitter escape the characters `& -> &amp;`. It should be fixed in https://github.com/gitcoinco/web/pull/7414

![image](https://user-images.githubusercontent.com/660973/93268339-a08aba00-f772-11ea-87c5-1c51769c0efd.png)

**Comment by thelostone-mc** [comment]
@aliatiia the fix has been deployed ! could you try once again ?

**Comment by thelostone-mc** [comment]
Closing and the grant has is twitter verified :) Have a good CLR round ^_^
