### ISSUE TITLE
Whitelist links to yEarn forum

### ISSUE THREAD

**Issue by aliatiia** [gitcoinco/web#7411]
### User Story

URLs of https://gov.yearn.finance/ in the `Activity` section of the grant become clickable, just like those to e.g. github.com or ethresear.ch

### Why Is this Needed

The yEarn goverance forum is currently serving as a research hub as well. For convenience of funders, links to this forum should be clickable.

### Description

*Type*: feature

### Current Behavior

Links are plain text, not clickable

### Expected Behavior

Links are clickable

### Definition of Done

Links to https://gov.yearn.finance become clickable

### Data Requirements

Number of clicks

**Comment by thelostone-mc** [comment]
Closing as i don't have enough indfo in terms of reproduction steps.
Do reopen with the grant and the comment on activity so that's easier to check out
