### ISSUE TITLE
Gitcoin wants me to verify Twitter account but won't let me add Twitter account to my grant

### ISSUE THREAD

**Issue by BobTheBuidler** [gitcoinco/web#7413]
Gitcoin wants me to verify my Twitter but I am unable to add a Twitter account to my existing grant. 
I specified my Twitter account during the grant creation process but did not specify a twitter account for the project as one does not exist. 
Unsure how to proceed, am I just missing something obvious here?

**Comment by owocki** [comment]
@zoek1 can u help

**Comment by zoek1** [comment]
Hi @BobTheBuidler, the option to add the twitter account for your grant is now enabled.  Click on the "Edit info" button, add the twitter account for your grant and save the changes. After that you'll be able to verify your grant. Let us know if it works!

**Comment by BobTheBuidler** [comment]
Wow, that was quick! Thanks for the help
