### ISSUE TITLE
ZKsync transactions not showing in interface

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#7415]
**Describe the bug**

I donated 10 DAI to Chainsafe a little while back but I'm noticing that my ZKSync tx, although it's showing up in the [summary](https://gyazo.com/3bec1aa24f1140864a71e7777c4da7d9), isn't showing up in the transactions tab [here](https://gyazo.com/e0141f091e2c274bf028ca8d7ab65392). It's worth noting as you can see in the first link that it also shows up twice, but that's less confusing.

I'm not sure if this is also impacting the matching calculation since I'm the first one to donate to this grant but it looks like it could be an issue in cases with more than one donation too.

Relevant grant here: https://gitcoin.co/grants/79/lodestar-ethereum-20-client?tab=description

**To Reproduce**

1) Make a donation to a grant via ZKSync
2) Wait a couple of hours for it to process
3) View the transactions tab on a grant / the grant card

**Expected behavior**

Everyone should be able to see the txs made both on L1 and L2 ideally so that we can get a full picture of the activity taking place in the round.

Let me know if I'm missing something / feel free to ping me for more info!

**Comment by owocki** [comment]
hmmm it shouldnt take a few hours to show up . should show up within a minute or two

@ceresstation what browser were you using? i wonder if this is related to the zksync intermittent 503 issues we were seeing today

**Comment by owocki** [comment]
i think i just found the issue. processing your txn; youll receive an email for it

**Comment by ceresstation** [comment]
Awesome @owocki looks like they're showing up now but we're getting duplicates:

https://gyazo.com/391d2e1209bb9b76c06cfb7f381e8896

LMK if this is being tracked elsewhere / if I should create a separate issue.

**Comment by owocki** [comment]
here is fine; @mds1 any idea why the grant donations are being duplicated?

**Comment by mds1** [comment]
@ceresstation Do the duplicates happen with L1 checkouts too?

@octavioamu @thelostone-mc Any idea why this might be happening? I'm not sure which portion of the codebase handles/triggers this so would have to spend some time looking around
