### ISSUE TITLE
Verified twitter but states unverified for granters and unable to see matching CLR numbers 

### ISSUE THREAD

**Issue by anubhavgirdhar** [gitcoinco/web#7419]
**Describe the bug**
We verified our twitter account but granters are seeing the need for us to verify the ownership of the twitter account. 
Moreover, Grants have not been matched yet on the grants page.

**To Reproduce**
Link to our grant : https://gitcoin.co/grants/1099/parcel

**Screenshots**
![photo6271725285770635917](https://user-images.githubusercontent.com/54765143/93280131-812d7480-f7e6-11ea-99c6-a6bbed9fb30d.jpg)

**Comment by thelostone-mc** [comment]
@anubhavgirdhar looks like the grant has bene verified 
![image](https://user-images.githubusercontent.com/5358146/93287080-42071f80-f7f6-11ea-88e2-f22d0946481e.png)

Also it doesn't show a match as the transaction hasn't been validated by our validator ! Once that gets picked up -> the amount should be reflected

**Comment by thelostone-mc** [comment]
Closing as the values are now updated 
![image](https://user-images.githubusercontent.com/5358146/93349075-a6f16280-f854-11ea-9720-5f5a950874bc.png)
