### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by mrarashel** [gitcoinco/web#7420]
### Who
Rahimuddin Alrashel
### What 
Twitter Verification failed
### Why
Sorry, we couldn't get the last tweet from @https://twitter.com/btc258

**Comment by thelostone-mc** [comment]
![image](https://user-images.githubusercontent.com/5358146/93287375-fc972200-f7f6-11ea-9889-47902f8bd3cb.png)
It's been verified now ^_^ thanks for the report
