### ISSUE TITLE
zkSync fixes

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#7421]
Batching these into one issue since they are related and will all be fixed in the same PR. Strike throughs indicate they are resolved in another PR

1. ~~On some checkouts, the final zkSync transfer (the donation to Gitcoin) fails. This happens because insufficient balance remains.~~ Resolved in https://github.com/gitcoinco/web/issues/7421

2. ~~POST request to save data is not sent until after all transactions, so if the donation tx fails this does not get logged and we don't have the contribution data for matching. Move this POST request to be sent after L1 tx (if applicable) and before the L2 txs are sent.~~ Resolved in https://github.com/gitcoinco/web/issues/7421

3. ~~One user was unable to get a "send deposit tx" prompt when they had both ETH and DAI in their cart. But it worked after removing ETH. This is the same bug as number 6~~ Resolved in https://github.com/gitcoinco/web/issues/7421

4. ~~When there is too little balance in the zkSync wallet to complete the final transfer back to the nominal wallet, the overflow bug happens so it's marked as incomplete. See image below.~~  Resolved in https://github.com/gitcoinco/web/issues/7421

![image](https://user-images.githubusercontent.com/17163988/93286098-37fc0700-f78b-11ea-8809-e4993f872337.png)

5. ~~When you set the donation amount to zero, it naively tries to send a 0 DAI donation to Gitcoin, and the zkSync fee estimator seems to fail when you specify a zero value transfer. Source: https://twitter.com/YahsinHuang/status/1306238719104413697?s=20~~ Resolved in https://github.com/gitcoinco/web/issues/7421

6. ~~"Returned values aren't valid. Did it run out of gas". See: https://twitter.com/BlockchainJames/status/1306025629733666816?s=20~~ Resolved in https://github.com/gitcoinco/web/issues/7421

**Comment by owocki** [comment]
...; looks like theres a handful of txns that failed validation the last few hours

many of them hav ethe validator comment ‘zkSync only’ in them, and when i look up those txns on zkscan they actually succeeded

0x5b4E39e6649A9c0aFd39F068F7076f0ea3125e8a is an example

i think itd be useful for debugging if the validator left more precise commetns like “zksync, to address did not match” or “zksync, amount did not match” or something.

there are 44 of them in this case… im going to manually override them now; but well have to figure it out i think 😕

**Comment by mds1** [comment]
Lots of fixes ready for review in https://github.com/gitcoinco/web/issues/7421

Next up is tx validator issue @owocki mentioned

**Comment by mds1** [comment]
Just saw this on gitcoin.co: `Error: fractional component exceeds decimals (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.0.7)`
