### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by aj07** [gitcoinco/web#7422]
Hello,

BuidlIn has tweeted about the verification process but on gitcoin that is still in pending state. 
https://twitter.com/buidlin/status/1306070390817452033
Is there any manual operation required for twitter verification ?

**Comment by willsputra** [comment]
@aj07 hi! it seems like you have the full link "https://twitter.com/buidlin" on your twitter field in grants page. could you edit it to just "buidlin" and try verifying again? let me know if you still face any issue. thanks :)

**Comment by thelostone-mc** [comment]
@aj07 I've gona ahead and done it for you ! The grant is now verified 
Thanks @willsputra  ^_^
