### ISSUE TITLE
Navigation bar in certain pages expanding vertically when hovering over "Town Square" because of bottom border expansion.

### ISSUE THREAD

**Issue by Unlimiter** [gitcoinco/web#7426]
**Describe the bug**
See the issue title.
I've only witnessed this at [the hackathon list page](https://gitcoin.co/hackathon-list/) which has a different navigation bar design than the rest of the site.

**To Reproduce**
Go to https://gitcoin.co/hackathon-list/ and hover over "Town Square" on the navigation bar at the top.

**Expected behavior**
The navigation bar's size should stay the same when hovering over navigation links.

**Personal solution**
Maybe make the bottom border size 3px and transparent in a non-hover state, and 3px and white in a hover state to make things consistent.

**Desktop (please complete the following information):**
- Browser: Chromium
- Browser Version: 84.0.4147.105

**Comment by octavioamu** [comment]
good catch seems some css styles are wrong 
cc @zoek1 @androolloyd as seems related to the vue-hackathon styles introduced to style the nav tabs.

**Comment by jamiehewitt15** [comment]
The navigation bar seems to stay the same size when I hover over the text, has this issue been fixed already? The text seems to move up though on hover, is that the issue you are referring to?

**Comment by Homz8** [comment]
...

**Comment by Unlimiter** [comment]
The problem was fixed months and nobody closed the issue.
