### ISSUE TITLE
Static Maintenance / Failover page

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#743]
### User Story

As a user, I want to see a static Gitcoin page if the site is undergoing maintenance or not responsive.

### Why Is this Needed?

*Summary*:
We should implement a static page to be used for dns failover with gitcoin branding (use existing base template) and a message explaining the website is currently undergoing maintenance. 

### Description

*Type*: Feature

### Current Behavior

Currently, if a user makes a request against https://gitcoin.co during a maintenance window or outage, they are greeted by a `This site can't be reached` error.
<img width="300" alt="screenshot 2018-03-29 08 54 12" src="https://user-images.githubusercontent.com/7315957/38089865-d81d0104-332e-11e8-9e86-ddbabfc413b2.png">

### Expected Behavior
A user requests https://gitcoin.co during a maintenance window or outage and is greeted with a gitcoin branded maintenance/outage page.

### Definition of Done

- Static page based on the `index.html` template.

### Additional Information
The core team will handle initial deployment and tooling to automatically update this static page following merging to `master`

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/715

**Comment by hrithik-jha** [comment]
Hi I'd like to work on this.

**Comment by owocki** [comment]
got a portfolio you can show off?

@mbeacom is this a design ticket or a coding ticket?

**Comment by hrithik-jha** [comment]
If this is a coding ticket, then I can make a front end on based on index.html

**Comment by mbeacom** [comment]
My original intent here was to replicate the `index.html` with the exception of dynamic navbar items and data.  Aligning with the existing design should be fine.

**Comment by spiegeleixxl** [comment]
So basically you want to save the HTML, pull all the css content into the HTML and create a 1-page static page for maintenance purposes - or do you want a "real" static page generator like django-distill? https://www.staticgen.com/django-distill

**Comment by bhaveshAn** [comment]
@owocki Since, this hasn't been assigned to anyone. I would like to work on this. Can you tell exactly what should be mentioned in this static page.

**Comment by kuhnchris** [comment]
@danlipert since this seems to (also) be a topic regarding fail-over, infrastructure, etc. - is this still something that does happen? or do we upgrade instances one after another so this is basically moot?

Thanks!

**Comment by danlipert** [comment]
Yeah IMO its moot - the way we do deploys right now there shouldn't ever be a moment where the load balancer is completely dead
