### ISSUE TITLE
Re: Verified w/ Tweet but Gitcoin Not Showing

### ISSUE THREAD

**Issue by wmpea** [gitcoinco/web#7432]
### Who

I'm William Peaster, creator of the grant for the DeFi Arts Intelligencer. 

### What 

I've verified my grant on Twitter with a tweet, but my Gitcoin dashboard is still saying it's unverified and to contact support.

### Why

I'm interested in how to proceed. Thanks kindly for your help and consideration!

**Comment by owocki** [comment]
@zoek1 any idea here?  @wmpea can u link your tweet and grant pls?

**Comment by owocki** [comment]
@wmpea did you click 'verify grant' in the modal?

**Comment by octavioamu** [comment]
@wmpea I didn't find your verification tweet on https://twitter.com/WPeaster can you try again?

**Comment by thelostone-mc** [comment]
Closing this out ! Do reopen if this is still an issue
