### ISSUE TITLE
Failed transaction status; it actually seemed to have worked. 

### ISSUE THREAD

**Issue by TrustlessState0x** [gitcoinco/web#7436]
Hello!

I donated 200 DAI to the following grant: 

https://gitcoin.co/grants/1225/teach-kids-about-ethereum-with-virtual-reality

Here's the transaction: 

https://etherscan.io/tx/0x63128b6ca632a0f440981d6419b0500c4e70d90cbbed2c7f0fbd978817c2117f

The grant shows 0 transactions, but when I click on the transaction, it shows 3
![image](https://user-images.githubusercontent.com/30753490/93370414-a4b3e780-f805-11ea-8ede-c344f93422b2.png)

![image](https://user-images.githubusercontent.com/30753490/93370473-ba291180-f805-11ea-8797-141f39d41b84.png)

also the grant card shows that 0 people have donated:

![image](https://user-images.githubusercontent.com/30753490/93370507-c7460080-f805-11ea-8371-c276dc61c15b.png)

Thank you for your attention!

**Comment by owocki** [comment]
1b73bc49c03e0fd55efe20226dae8c46fd107777 will fix this; gonna deploy in a sec
