### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7438]
I can't verify my grant https://gitcoin.co/grants/177/crypto-reward-courts :

> Unable to verify tweet from vporton. Is the twitter post live? Was it sent from vporton?

I sent a Tweet indeed: https://twitter.com/victorporton/status/1306285330182672385

**Comment by owocki** [comment]
vporton != victorporton

**Comment by vporton** [comment]
> vporton != victorporton

In my opinion, it makes no any sense to require Twitter handle to be string-equal to GitHub handle. They have two independent of each other registration systems and therefore comparison for equality makes no sense.

**Comment by owocki** [comment]
your twitter handle input on the grant has to equal your actual twitter handle

https://bits.owocki.com/Z4uk0or5
https://bits.owocki.com/04uq4A5E

**Comment by vporton** [comment]
Oh sorry, I just mistyped the handle.
