### ISSUE TITLE
Small Grants Bugs

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7441]
'Community' project (see the bottom left) but says 'Dapp Tech' matching. Not sure if we're seeing this across other grants? 

[Link here](https://gitcoin.co/grants/855/kernel-panvala-league). 

![image](https://user-images.githubusercontent.com/23297747/93379366-57df0980-f823-11ea-9b05-b28168c3e6f2.png)

**Comment by thelostone-mc** [comment]
This was a data issue! fixed that up 🙌
