### ISSUE TITLE
Donation not registering in match

### ISSUE THREAD

**Issue by AnneConnelly** [gitcoinco/web#7442]
**Describe the bug**
Our grant received a 15DAI donation yesterday, sept 15 at approximtely 1pm EST. It is not showing in the matching box, which still stands at zero.

**To Reproduce**
Go to: https://gitcoin.co/grants/211/trust-graphic-novel 
view donation made and zero in the matching box.

**Expected behavior**
The donation would have shown up in the matching box

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
@frankchen07 @thelostone-mc any idea on this one? i see the cleared txn in the db but its not applied to matching, perhaps we need at least 2 donations to generate a matching amount?

**Comment by frankchen07** [comment]
@owocki yes I believe that's right. If it's just one donation, it won't be paired with anything.
