### ISSUE TITLE
I can't claim for a tip

### ISSUE THREAD

**Issue by yacare555** [gitcoinco/web#7444]
**Describe the bug**
Hi guys, a few days ago I received a tip and I can't claim for it, this is the email I received: 

"Nice work @ 0x5a919ed0e22e6902accaaa27b4fdf0acd92ba210! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page."

But there is no option to "Claim Tip" in the site, I have received another tips before with no problems.
Let me know if you need any other info.

I think this is the transaction:
0x1472613a437f5763f0c03c080274c647f5f42cbd5b0681cc3c4d48aed24ccc33

Thanks in advance

**Comment by owocki** [comment]
looks like that tip was sent to @jppade
 - is that your account?

**Comment by yacare555** [comment]
Hi @owocki, that's the account I've worked for, my gitcoin account is @yacare555.

A bit more of info:
- The ETH address that appears in the email is the mine one.
- In the gitcoin activity of @jppade appears the tip sent to my ETH address but the small profile picture in the bottom is not mine.
<img width="1074" alt="Screenshot" src="https://user-images.githubusercontent.com/67239493/93402428-18341400-f85b-11ea-8423-bc52fc60a60f.png">

- The email I received: 

>A tip worth 100.00000 USDC (100.0 USD @ $1.0/USDC) has been granted to @0x5a919ed0e22e6902accaaa27b4fdf0acd92ba210 for this issue from @jppade. ⚡️
Nice work @0x5a919ed0e22e6902accaaa27b4fdf0acd92ba210! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page.

@jppade may be you can claim for the tip?

**Comment by jppade** [comment]
Hi @owocki .
I did not receive 100USD, but I sent them through gitcoin tip send, as can be seen on etherscan:
https://etherscan.io/tx/0x1472613a437f5763f0c03c080274c647f5f42cbd5b0681cc3c4d48aed24ccc33
I don't see how I could reclaim that tip.
Any help appreciated.

**Comment by owocki** [comment]
@jppade click 'redeem tip' in the top right of the nav; or go to https://gitcoin.co/tip/receive/v3/QmW4i61QxSwufgAKSqkAwSR588HAYcPuNzVHT5mv8PC27p/0x1472613a437f5763f0c03c080274c647f5f42cbd5b0681cc3c4d48aed24ccc33/mainnet to claim it

**Comment by jppade** [comment]
@owocki Worked. Thanks!

**Comment by yacare555** [comment]
Thank you  @owocki , I'll close it.
