### ISSUE TITLE
BrightID verification not working

### ISSUE THREAD

**Issue by lpfloyd** [gitcoinco/web#7448]
**Describe the bug**
BrightID verification on Gitcoin seems to not work. 
Unfortunately, it just says **Failed to load BrightID Status**` after authenticating BrightID on the app.

**To Reproduce**
Download BrightID. 
Sign up. 
Scan QR code on Gitcoin. 
Wait for verification on BrightID. 
Successful verification.
Gitcoin doesn't seem to know that it successful.

**Expected behavior**

Gitcoin Trust Bonus should say that BrightID has been integrated (or smth similar i guess)

**Desktop (please complete the following information):**

- OS: MacOS Catalina 10.15.6
- Browser: Chrome
- Browser Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by owocki** [comment]
@apbendi @adamstallard any idea about this one

**Comment by apbendi** [comment]
hey @lpfloyd, we'll look into it! In your BrightID app, does it say "verified" under your name on the main screen. Also, is this the GitHub account you use for Gitcoin, I assume? Thanks!

**Comment by apbendi** [comment]
@lpfloyd the issue should be resolved now, if you navigate back to the Trust Bonus tab in your profile it should show you as connected 👍

**Comment by lpfloyd** [comment]
Thanks guys! Awesome stuff.
