### ISSUE TITLE
Got donations but total in Grant Page shows zero

### ISSUE THREAD

**Issue by lucadgtrip** [gitcoinco/web#7449]
**Describe the bug**
Two donations were made but are not reflected in the grant page.
We see them in the comments below

![Screenshot 2020-09-17 at 05 35 57](https://user-images.githubusercontent.com/34341206/93413479-0af14680-f8a8-11ea-9d3f-39bb65871b85.png)

in https://etherscan.io/address/0x2C5FF0Be38115Fe6E37ACce8e94F86186c3D73dF
and 
https://zkscan.io/explorer/accounts/0x2C5FF0Be38115Fe6E37ACce8e94F86186c3D73dF

but not here (this is the bug)

![Screenshot 2020-09-17 at 05 36 02](https://user-images.githubusercontent.com/34341206/93413546-2bb99c00-f8a8-11ea-8715-8342da445415.png)

**To Reproduce**
Look at the grant
https://gitcoin.co/grants/1166/open-reviews-a-web2-to-web-3-replication-protoco-2

**Expected behavior**
You will see the comments below and 0 DAI on the top right part of the page.

**Desktop (please complete the following information):**

- OS: Os x 10.14.6
- Browser: Brave/FF/Chrome
- Browser Version: last

**Comment by owocki** [comment]
i seem to be able to udpate the numbers manully here

```
from grants.models import *
from grants.tasks import *

grant = Grant.objects.get(pk=1166)
update_grant_metadata(grant.pk)

```

which will solve the OP; but we need to find the root cause for whyt he queues arent running

**Comment by lucadgtrip** [comment]
getting closer, I see 1 out of 2 donations and no match at the moment

![Screenshot 2020-09-17 at 19 55 55](https://user-images.githubusercontent.com/34341206/93502926-13856380-f920-11ea-9a8b-b9162b225618.png)

**Comment by lucadgtrip** [comment]
Also, what does Pending mean?
![Screenshot 2020-09-18 at 06 14 48](https://user-images.githubusercontent.com/34341206/93551409-7570b800-f976-11ea-9c1c-2eb5b570a1b7.png)
