### ISSUE TITLE
Admin grants categories don't match interface categories

### ISSUE THREAD

**Issue by ceresstation** [gitcoinco/web#7454]
**Describe the bug**

Grants such as https://gitcoin.co/grants/798/a-hitchhikers-guide-to-token-engineering appear to be listed as "dapp tech" grants. However, when [viewing the grant in admin](https://gyazo.com/78a04a00181f6e12df4da041ac9f3e5f) it clearly shows as "media". 

Is it possible that there are now hardcoded values for categories that can't be overridden / changed by users or admins?

**Comment by owocki** [comment]
we should probably add a ‘bust cache’ button to admin, or a psave hook that updates the active cateogry

@thelostone-mc when an admin updates the category; is there any code in place that will change which active_clr_rounds they are in ? i dont see any such code rn
