### ISSUE TITLE
Cart keeps loading forever

### ISSUE THREAD

**Issue by zkeducation** [gitcoinco/web#7458]
**Describe the bug**
<The cart loading icons keep cycling forever, everything else is working as normal.-->

**To Reproduce**

**Screenshots**
<
![Screen Shot 2020-09-17 at 2 16 08 PM](https://user-images.githubusercontent.com/57240194/93529215-65ae9080-f8f0-11ea-8cfe-6a19d0a5ae8b.png)
-->

**Desktop :**

- OS: Mac OS 10.14.5
- Browser: Brave
- Browser Version:0.63.55

**Comment by owocki** [comment]
heya @zkeducation do you see any errors in your console?  @mds1 mind trying to reproduce this?

**Comment by mds1** [comment]
Hey @zkeducation! Right now this can happen if (1) you don't have a wallet connected, or (2) if you're using MetaMask but it's locked. We're deploying a fix for both of those today.

If those aren't the cause in your case, like @owocki said any additional details you can provide to help reproduce it would be helpful!

**Comment by RockmanR** [comment]
Hi @mds1 ,

I'm facing the same issue here. Regarding:
1. my wallet is connected
2. I tried both, metamask add-on extension and the Wallet Connect (with MetaMask mobile)
but still face the issue.

Here are screenshots from the console as suggested by @owocki 

<img width="1305" alt="Screen Shot 2020-09-25 at 12 46 40 AM" src="https://user-images.githubusercontent.com/34535049/94198833-f248e800-fec8-11ea-975b-5efbacbe807c.png">

<img width="1302" alt="Screen Shot 2020-09-25 at 12 46 51 AM" src="https://user-images.githubusercontent.com/34535049/94198846-fb39b980-fec8-11ea-99da-c06b52fa3c30.png">

<img width="1306" alt="Screen Shot 2020-09-25 at 12 47 07 AM" src="https://user-images.githubusercontent.com/34535049/94198875-0856a880-fec9-11ea-80fb-2ebffbdaceb3.png">

I was working fine for the first check-out. Then the next day the issue popped up. 

Let me know if you need any extra info.

Thanks guys

**Comment by mds1** [comment]
@RockmanR Hmm, that's odd. I'll have to figure out how to reproduce this. You could try clearing the cart and re-adding them from the grants page. I believe there was a very recent upgrade to how cart items were handled so I'd guess this would fix it. It's possible you already had items in your cart, then the changes were deployed, putting things in a weird state

**Comment by RockmanR** [comment]
Maybe what you said is true. Probably it started when I clicked on Banteg's shared cart in twitter (https://twitter.com/bantg/status/1307707668409319426?s=20). I saw the list once, then the issue started the moment I added stuff to it (maybe). I'll try to clear it out and and add the projects again :(

**Comment by mds1** [comment]
I just tried adding Banteg's items to my cart and it seemed to have worked, so that's good. Also as a sanity check make sure MetaMask is unlocked and on mainnet!

**Comment by mds1** [comment]
One more thought — you could also try a hard refresh of the browser to make sure nothing is being cached since we just pushed that update

**Comment by octavioamu** [comment]
Can you click on share cart and paste the link here?

**Comment by octavioamu** [comment]
also are all the grants on your cart to dai? or is one with a diff token?

**Comment by RockmanR** [comment]
Ok, I think I know how to reproduce the issue. 
1. Go to the below cart link
2. delete one item
3. refresh the screen
4. (fetching cart data issue)

https://gitcoin.co/grants/cart/bulk-add/888;10;283,200;10;283,1122;10;283,170;10;283,1093;10;283,223;10;283,224;10;283,308;10;283,24;10;283,25;10;283,13;10;283,1127;10;283,1211;10;283,275;10;283,17;0.02639541574883473;3,149;10;283,:banteg

**Comment by RockmanR** [comment]
> also are all the grants on your cart to dai? or is one with a diff token?

They are in Dai and Eth. as you will see from the link

**Comment by GriffGreen** [comment]
having the same issue... Its tragic too cause i made a bunch of comments in all the grants :-(
<img width="1253" alt="Screen Shot 2020-09-29 at 1 05 13 AM" src="https://user-images.githubusercontent.com/14945613/94494777-4a952800-01f0-11eb-8eba-eef64fa5730e.png">

<img width="537" alt="Screen Shot 2020-09-29 at 1 06 45 AM" src="https://user-images.githubusercontent.com/14945613/94494784-4e28af00-01f0-11eb-95dd-dd227cf6e3d4.png">
<img width="544" alt="Screen Shot 2020-09-29 at 1 06 36 AM" src="https://user-images.githubusercontent.com/14945613/94494786-4ec14580-01f0-11eb-8c32-76e1ea10faa0.png">

**Comment by GriffGreen** [comment]
It definitely is happening when you delete grants from a preloaded cart

**Comment by mds1** [comment]
Hey @GriffGreen sorry for the late response here. And sorry that all your comments are lost 😕 

Can you elaborate a bit on the cause you found and how to reproduce this?

**Comment by octavioamu** [comment]
I replicated the steps without luck the first time, but a second time gave me the error, I wonder if depends the grant you delete.

**Comment by octavioamu** [comment]
@mds1 seems the problem is with the exchange calculation , as still trying to fetch data for something that doesn't exist
![image](https://user-images.githubusercontent.com/1358093/94716963-0a37c600-0326-11eb-9940-458b26dca2ca.png)


**TO REPRODUCE THIS ERROR**
Go to https://gitcoin.co/grants/cart/bulk-add/888;10;283,200;10;283,1122;10;283,170;10;283,1093;10;283,223;10;283,224;10;283,308;10;283,24;10;283,25;10;283,13;10;283,1127;10;283,1211;10;283,275;10;283,17;0.02639541574883473;3,149;10;283,:banteg
  request go `get_amount?denomination=DAI,ETH`
  localstorage showing the 0 to 15 grant (the last one is rotki) 
Remove "brownie" grant (need to be that one) 
without reloading keep an eyes on rotki the last one now without token informations
![image](https://user-images.githubusercontent.com/1358093/94717859-43bd0100-0327-11eb-948e-f8173ece6602.png)
without reload you will see the problem happening exchange trying to fetch `get_amount?denomination=DAI,ETH,` 
/sync
Reload the page and the card will never load again until you clear it.

So the problem is on the removal is removing the grant but also data from the last one.

**Comment by octavioamu** [comment]
Ok @GriffGreen @RockmanR  @zkeducation   I have a quick dirty snipped if you not cleared your cart and want to recover the data. this code will just remove the last one you had on your cart.  

Open console, paste this and hit enter:
```
var test = JSON.parse(window.localStorage['grants_cart'])
test.pop()
window.localStorage['grants_cart']=JSON.stringify(test)
```
Reload window.

**Comment by GriffGreen** [comment]
> Hey @GriffGreen sorry for the late response here. And sorry that all your comments are lost 😕
> 
> Can you elaborate a bit on the cause you found and how to reproduce this?

I was trying to take out the DAI grants in this cart in a brave browser:

If you delete 1 or 2 of them the front end looks fine... I think, but delete the third and then the grant still just sits there.

And even if i just delete 1 of them, and then try to share the cart... the cart wont load... it keeps loading forever.


https://gitcoin.co/grants/cart/bulk-add/1127;2000;316,899;1000;316,539;1000;316,277;1000;316,1155;1000;316,308;1000;316,1141;1000;316,798;800;316,522;800;316,816;800;316,795;800;316,517;800;316,1262;600;316,1297;600;316,524;600;316,191;600;316,63;600;316,184;500;316,213;500;316,1086;500;316,86;500;316,347;40;283,1093;400;316,237;400;316,1198;400;316,1118;400;316,1158;400;316,143;400;316,1325;400;316,500;300;316,329;300;316,366;200;316,40;100;316,1278;100;316,1139;100;316,855;1000;316,615;400;316,484;100;316,1110;200;316,936;200;316,711;200;316,540;200;316,490;200;316,296;20;283,275;10;283,274;500;316,246;100;316,235;50;283,202;800;316,149;300;316,159;300;316,224;400;316,1173;200;316,1166;300;316,1005;200;316,961;300;316,565;500;316,238;100;316,223;100;316,198;1000;316,285;200;316,281;5;283,444;1000;316,943;200;316,775;10;283,1174;500;316,12;300;316,211;100;283,543;20;283,864;300;316,827;500;316,1296;300;316,1211;200;316,779;30;283,1101;500;316,270;100;316,1052;200;316,212;1000;316,1143;500;316,1183;300;316,515;200;316,1250;1000;316,231;500;316,1170;400;316,845;500;316,1175;200;316,1167;400;316,1071;400;316,1310;300;316,1031;200;316,1114;400;316,1266;500;316,618;50;283,:griffgreen

**Comment by octavioamu** [comment]
wow that is a lot of grants, probably is the same problem, something on the function to delete grants is not working properly.

**Comment by mds1** [comment]
Fix ready in https://github.com/gitcoinco/web/pull/7573!

@GriffGreen If you haven't cleared your cart, the page will now load and the buggy cart entries will default to 0.001 ETH, and all your comments will be saved

**Comment by octavioamu** [comment]
@GriffGreen @RockmanR @zkeducation fix was deployed, just tested and is working fine!!! Sorry for the inconvenience.
