### ISSUE TITLE
I cancelled my zksync tx and now it wont prompt it again

### ISSUE THREAD

**Issue by zkeducation** [gitcoinco/web#7460]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac Mojave 10.14.5
- Browser: Brave
- Browser Version: 0.63.55

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hey! If you can provide some more details to help us figure out the issue that would be great! Some specifics that would help:
- Any L1 or L2 addresses / transaction hashes (you can DM me on Twitter @msolomon44 if you don't want to post it here)
- What exactly do you mean by "cancelling" it? I'm guessing you closed the page at some point? Or maybe you just closed the modal?
- Did you already have funds in zkSync or were you using funds from L1?
- What prompt are you expecting?
