### ISSUE TITLE
Sped up the zkSync transaction and the new one is not registered by gitcoin

### ISSUE THREAD

**Issue by penandlim** [gitcoinco/web#7461]
**Describe the bug**
After approving the deposit, I sent out zkSync donation [transaction.](https://etherscan.io/tx/0x14f4d6320df49195ebbf07e4e99df4b5d7d4f5b877e858db48364fc06876e773)
Due to high gas prices, [I sped up the transaction which resulted in a second one](https://etherscan.io/tx/0xb7bf081d958cb75d0a26653b6a494e97b8b5fbcac74dcae7528462ff8a80c4de)

However gitcoin thinks my transaction did not go through yet.

**To Reproduce**
1. Send donation via zkSync option
2. Speed up the transaction.

**Expected behavior**
The new transaction is recognized.

**Screenshots**
![image](https://user-images.githubusercontent.com/4276174/93562231-9ecc1c80-f953-11ea-97a7-0dce6647739b.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Browser Version:  85.0.564.51 (Official build) (64-bit)

**Additional context**
[the transaction in zkSync explorer](https://zkscan.io/explorer/transactions/b7bf081d958cb75d0a26653b6a494e97b8b5fbcac74dcae7528462ff8a80c4de)

**Comment by owocki** [comment]
@mds1 any thots on this one?

**Comment by mds1** [comment]
I will investigate and get a fix in!

**Comment by mds1** [comment]
Hey @penandlim, you should be able to visit the cart page now at https://gitcoin.co/grants/cart to complete checkout!

**Comment by penandlim** [comment]
Thanks @mds1! I was able to confirm the transaction and it looks like it went through successfully! Thanks for the quick fix :)
