### ISSUE TITLE
grant contribution amount not updating

### ISSUE THREAD

**Issue by Daft-Wullie** [gitcoinco/web#7462]
**Describe the bug**
My grant is not showing updated figures both in terms of contributors and amount donated in the grant card.
The transaction tab shows 2 transactions/contributors and while one is marked as pending/failed the donor confirmed to me it was succesdfull on chain and provided me the following etherscan link
https://etherscan.io/tx/0x88d6169687b6d7be4d8e821975afedd789175cd8539753ea8143307b118eac5c
**To Reproduce**
visit https://gitcoin.co/grants/1151/fuzzing-home-helping-find-bugs-in-eth-20-clients
**Expected behavior**
the grant card showing contribution figures should be updates to reflect the actual number of contributions and amounts.
**Screenshots**
![incorrectamount](https://user-images.githubusercontent.com/37898858/93567038-46664080-f98e-11ea-83be-0374827f01f7.JPG)
![contributions](https://user-images.githubusercontent.com/37898858/93567048-4b2af480-f98e-11ea-8938-8183b05bf827.JPG)
![txid](https://user-images.githubusercontent.com/37898858/93567326-c2608880-f98e-11ea-9111-6f3c399e8a7f.JPG)

**Desktop (please complete the following information):**
- OS: Win 10
- Browser: Chrome
- Browser Version: 85.0.4183.10

**Comment by owocki** [comment]
looks like the validator incorrectly marked it as failed (we got an invalid response from the alethio api). i just marked it as success + am re-running the job to update the amount
