### ISSUE TITLE
zkSync fail

### ISSUE THREAD

**Issue by cranders1** [gitcoinco/web#7470]
Trying to bulk grant checkout with PAN via zkSync but keep getting errors.
PAN token not accepted
Same error even for ETH & DAI - not accepted.
I have zkSync layer 2 loaded with ETH & PAN
user: cranders1
wallet: 0x6FB8479a3bBB7a4Ed8395Af47916D9A51B7BA038
Help much appreciated. Cheers.

**Comment by cranders1** [comment]
Success. Not sure if it was your magic fingers or just crap on my end. 
thnx

**Comment by mds1** [comment]
Glad you got it working! A fix for this should be deployed soon in https://github.com/gitcoinco/web/pull/7473

In case you experience this again you can workaround it by refreshing the page after you connect your wallet
