### ISSUE TITLE
Community Matching

### ISSUE THREAD

**Issue by ggabriel8** [gitcoinco/web#7475]
Hello,

I just launched my first grant. I am very excited. I noticed that community match doesn't seem to enabled on my grant. How can I fix this?

Thanks,

Gabriel

**Comment by owocki** [comment]
grant link?

**Comment by thelostone-mc** [comment]
@ggabriel8 it's matched to it !
https://gitcoin.co/grants/1264/talking-crypto-with-gabriel

It usually takes a a while to get mapped to the right CLR round!
Just pushed in a fix to make an instant https://github.com/gitcoinco/web/commit/f680b2c61a678e9c0a188323e5b5208ac8930085

Have a happy CLR round ^_^
