### ISSUE TITLE
Trouble with verification 

### ISSUE THREAD

**Issue by YalorMewn** [gitcoinco/web#7476]
Won't verify our grant https://twitter.com/Meta_Cartel/status/1307298104782315520 using Twitter https://gitcoin.co/grants/1139/metacartel-builder-awards-panvala-league

**Console data** 

`7[Intervention] Slow network is detected. See <URL> for more details. Fallback font will be used while loading: <URL>
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ inpage.js:1
raven.js:58 MetaMask: We will stop injecting web3 in Q4 2020.
Please see this article for more information: https://medium.com/metamask/no-longer-injecting-web3-js-4a899ad6e59e`

**Comment by owocki** [comment]
@YalorMewn what browser r u on? where exactly in the flow does it fail?

i just manually verified your ownership for now

**Comment by YalorMewn** [comment]
Apologies for the delay, was using Chrome. Copy and pasted the Tweet, fail happened when I clicked `verify` button. Red error message popped on screen, tried refreshing multiple times with no avail. Thanks for the manual verification though
