### ISSUE TITLE
Contribute not working even though transaction has already been sent

### ISSUE THREAD

**Issue by sselecaf** [gitcoinco/web#7477]
**Describe the bug**
I try to grant 7 projects and checkout with zkSync. Unfortunatelly the last step - Confirm donation transaction is keep showing "Processing", even though my tx has already sent successfully.
I also cannot see any grant activities on my profile: https://gitcoin.co/sselecaf

**To Reproduce**
I am not sure whether this can be reproduce...

**Expected behavior**
The contribute occurs successfully and I can see them on project / my profile pages.

**Screenshots**
![gitcoin co_grants_cart](https://user-images.githubusercontent.com/65448755/93669967-220f7e80-faca-11ea-85d6-560ef386649c.png)
<img width="498" alt="Screen Shot 2020-09-19 at 21 19 47" src="https://user-images.githubusercontent.com/65448755/93669971-2b98e680-faca-11ea-9cc7-277646466990.png">

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Browser: Chrome
- Browser Version: 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

**Comment by mds1** [comment]
Hey @sselecaf, do you mind sharing the transaction hash from step 3 so I can look into what happened? If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4

Also, if you can open the browser's console there should be some zkSync info written there. Can you send a screenshot of the last ones it shows when stuck?

**Comment by mds1** [comment]
Hey @thelostone-mc / @octavioamu — worked with @sselecaf offline to get this resolved so we can close this one!

**Comment by sselecaf** [comment]
Thanks Matt!
