### ISSUE TITLE
zkSynyc checkout does not recognise when transaction gets dropped/canceled.

### ISSUE THREAD

**Issue by hegedis-andor** [gitcoinco/web#7479]
**Describe the bug**

I wanted to checkout with zkSync, funding multiple projects but later i recognised the advenced option which enable to deposit to zkSync. So i decided to cancel the ongoing transaction. Now when i want to check out again it recognises the dropped transaction and cannot create a new one.

**To Reproduce**

1. Put something into the cart.
2. Go to checkout
3. Choose checkout with zksync
4. sign in
5. approve erc20 token
6. confirm donation tx
7. cancel donation tx (replace by fee)
8. start again from step 3. 
-> the tx which was created at step 6. and dropped by the network is still recognised as valid tx and does not offer to confirm a new tx.

**Expected behavior**

After i canceled the tx i should be able to make a new tx with the same items in the cart.

**Screenshots**

**Desktop (please complete the following information):**

- OS: win 10
- Browser: chrome
- Browser Version: v85.0.4183.102 

**Additional context**
metamask

**Comment by willsputra** [comment]
Seems like a similar case with https://github.com/gitcoinco/web/issues/7397. We're on it!

**Comment by mds1** [comment]
Hey @hegedis-andor, can you provide the address you donated with and the transaction hash that you cancelled and we can resolve this for you?

If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4

**Comment by hegedis-andor** [comment]
> Hey @hegedis-andor, can you provide the address you donated with and the transaction hash that you cancelled and we can resolve this for you?
> 
> If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4

I do not think the tx would be needed to solve this issue on your end.

**Comment by mds1** [comment]
@hegedis-andor There is a PR that should resolve this once it's merged and deployed. Until then we would need the transaction hash so we can fix it manually for your specific case.

The PR is here if you'd like to follow the status: https://github.com/gitcoinco/web/pull/7489
