### ISSUE TITLE
Adding matching categories to my grant

### ISSUE THREAD

**Issue by davis-ramsey** [gitcoinco/web#7480]
Hello,

I just created https://gitcoin.co/grants/1296/poolsvision but doesn't look like it got assigned any categories for matching. When I go to edit I can't add any it seems. 

I think Community, Devex, Education, Usability would be appropriate categories but open to feedback.

Thank you!

**Comment by owocki** [comment]
looks like its in matching now.

we def should make it show that immediately upon creation of the grant @gitcoinco/engineers

**Comment by thelostone-mc** [comment]
@davis-ramsey updated the categories to Community, Devex, Education, Usability
@owocki grants will be mapped to active clr on creation via commit f680b2c61a678e9c0a188323e5b5208ac8930085
