### ISSUE TITLE
It seems possible to send a kudos for free

### ISSUE THREAD

**Issue by cvonkleist** [gitcoinco/web#7488]
**Describe the bug**

When sending a kudos, it is possible to set the value of the transfer to 0, yet the kudos still gets sent. Is it the case that the kudos system is just in testing right now? I was able to send myself two kudos, each apparently with a price of 0.001Ξ, for free (except for gas).

Maybe I'm just misunderstanding what is supposed to happen when sending a kudos.

**To Reproduce**

Send yourself a kudos. When the transaction pops up in MetaMask, set the transaction's value to 0. (Also unexpected: The transaction initially has a value much greater than the value of the kudos for some reason, 0.296513Ξ.)

**Expected behavior**

I guess I expect a kudos to cost me whatever its listed price is.

**Screenshots**

* * * * *
Kudos costs 0.001Ξ:
<img width="466" alt="ss1" src="https://user-images.githubusercontent.com/20558/93775215-5743da00-fc4c-11ea-89b8-b150093ed953.png">
* * * * *
Initial value in MetaMask is too high for some reason:
<img width="472" alt="ss2" src="https://user-images.githubusercontent.com/20558/93775251-5f037e80-fc4c-11ea-9446-d2631cf704f5.png">
* * * * *
Setting the value to 0:
<img width="472" alt="ss3" src="https://user-images.githubusercontent.com/20558/93775248-5e6ae800-fc4c-11ea-9e6f-5792568214fa.png">
* * * * *
Sending kudos:
<img width="465" alt="ss4" src="https://user-images.githubusercontent.com/20558/93775244-5e6ae800-fc4c-11ea-95a1-0c901dddd2fb.png">
* * * * *
Claiming kudos:
<img width="333" alt="ss5" src="https://user-images.githubusercontent.com/20558/93775242-5d39bb00-fc4c-11ea-8695-9193d6a08925.png">
<img width="295" alt="ss6" src="https://user-images.githubusercontent.com/20558/93775236-5ca12480-fc4c-11ea-90e5-281e9a42b013.png">
* * * * *
Transaction on Etherscan (with transaction value of 0):
<img width="1273" alt="ss7" src="https://user-images.githubusercontent.com/20558/93775232-5c088e00-fc4c-11ea-8952-06d8aef51e8c.png">
* * * * *
I have the kudos on my profile:
<img width="1219" alt="ss8" src="https://user-images.githubusercontent.com/20558/93775444-9b36df00-fc4c-11ea-85f4-121971bcf2ca.png">

**Comment by owocki** [comment]
thanks; you are correct that the system thinks the kudos is sent.  we have a txn validator that will check if the txn succeeded + later remove the kudos from the users profile. its an optimistic system; i bet we could improve it by making it more cautious tho
