### ISSUE TITLE
unreadable text in the **funder** page

### ISSUE THREAD

**Issue by chartreuse-man** [gitcoinco/web#7491]
**Describe the bug**
Unreadable text on the **funder** page

**To Reproduce**
follow to the link https://gitcoin.co/bounties/funder

**Screenshots**
![image](https://user-images.githubusercontent.com/71655469/93827511-119a0800-fc72-11ea-8540-da9448e7d82f.png)
![image](https://user-images.githubusercontent.com/71655469/93827944-01365d00-fc73-11ea-884f-e8f79bbc03b5.png)

**Desktop (please complete the following information):**

- OS: ubuntu 18.04
- Browser: firefox
- Browser Version: 80.0.1 (64-bit)

**Comment by jamiehewitt15** [comment]
As far as I can see it looks like this issue is fixed already? I have tested it on Chrome, Firefox and Edge and it seems like the text font color has changed to make it readable

**Comment by acolytec3** [comment]
Likewise, not seeing any issues.  @chartreuse-man are you still seeing this anywhere?  If not, @thelostone-mc, this one might be able to be closed.

Though, there is a spelling issue in the comment from Dan Finlay. :sweat_smile: 
On Ubuntu 20.04 on desktop, here's screenshots:
In Brave:
![image](https://user-images.githubusercontent.com/17355484/105719909-d3974400-5ef0-11eb-926e-a9dbb0da5cb7.png)

In Firefox:
![image](https://user-images.githubusercontent.com/17355484/105719968-e01b9c80-5ef0-11eb-8ccb-af29649e9b6e.png)

On Android 10, Brave:
![Screenshots_2021-01-25-09-40-16](https://user-images.githubusercontent.com/17355484/105720853-e9593900-5ef1-11eb-8427-9b6f4224f1bb.png)

**Comment by LuvKriptoz** [comment]
> **Describe the bug**
> Unreadable text on the **funder** page
> 
> **To Reproduce**
> follow to the link https://gitcoin.co/bounties/funder
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/71655469/93827511-119a0800-fc72-11ea-8540-da9448e7d82f.png)
> ![image](https://user-images.githubusercontent.com/71655469/93827944-01365d00-fc73-11ea-884f-e8f79bbc03b5.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: ubuntu 18.04
> * Browser: firefox
> * Browser Version: 80.0.1 (64-bit)

You are right. I could feel the same
