### ISSUE TITLE
Grant says it will accept all tokens but once in cart only allows Eth

### ISSUE THREAD

**Issue by amsos** [gitcoinco/web#7494]
**Describe the bug**

Grant reads that it should accept all tokens but when I go to specify the amount to donate it only gives me options in Eth.

**To Reproduce**

1.  Go to https://gitcoin.co/grants/484/depo-dao-decentralized-politics-dao
2.  Add to cart
3.  Choose the token type

**Expected behavior**

Allows you to choose a token other than Eth

**Screenshots**

![Screen Shot 2020-09-21 at 5 10 00 PM](https://user-images.githubusercontent.com/31267818/93853078-08a43900-fc68-11ea-855a-793670822e69.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Firefox
- Browser Version: 80.0.1 

**Additional context**

**Comment by mds1** [comment]
Hey @thelostone-mc, it seems the cause here is that this grants has a value of `""` for it's `grant_token_symbol`. Can you update this to say `Any Token` it should resolve the issue

**Comment by amsos** [comment]
Hey team - wanted to check on the status of this.

**Comment by octavioamu** [comment]
Seems also there is another error about the clr, but if you remove your grant for the cart and add it again now the problem with tokens should be gone. 
We are working on a fix for "Not Eligible for CLR" that happens when you add the grant from the grant details page. if you do it from the grant list then works ok.

**Comment by amsos** [comment]
Awesome! I just checked and it does now show the ability to donate in all tokens!  Much thanks.

I'm not 100% sure I'm following the second one.  Is it just a UI issue or is it how it's tagged on the backend as well.

**Comment by octavioamu** [comment]
now everything is fixed :)
