### ISSUE TITLE
Transaction state pending

### ISSUE THREAD

**Issue by 78carla** [gitcoinco/web#7495]
### Who
Transaction list 

### What 
Hi, my transaction in the transaction list in Gitcoin (ref. project Open Reviews: A Web2 to Web 3 Replication Protocol) remains in pending state (made on September 20th). 

The transaction in etherscan (transaction hash is 0x635b22b8a888f6e26702aeabf617a5b8f02e7e6a773625a2c5f68af28e3c46ec is "success". 

![Image Pasted at 2020-9-22 10-24](https://user-images.githubusercontent.com/45719918/93878167-e6e39a00-fcd9-11ea-83f6-8be38f373aa1.png)

**Comment by MysticRyuujin** [comment]
We also have a number of (pending) transactions under our funding page, some of them are failed too. It really throws off our numbers when 1 of those (pending) transactions for 3,000 DAI failed. The user re-submit and now we show almost 2x the donations we've actually received.

https://gitcoin.co/grants/1101/archivenodeio-the-public-access-ethereum-archive-?tab=transactions

**Comment by 78carla** [comment]
For your reference, my pending transaction is in this project:
https://gitcoin.co/grants/1166/open-reviews-a-web2-to-web-3-replication-protoco-2

**Comment by 78carla** [comment]
Hi,
any update for this? My transaction on gitcoin is still pending.

Regards,

**Comment by owocki** [comment]
hey i dont see 0x635b22b8a888f6e26702aeabf617a5b8f02e7e6a773625a2c5f68af28e3c46ec in the database; is that a dropped/replaced tx id? EDIT - found it - 0x2e05164cb5b6ab1b8d840ab0f26fe90defb5c9913f8ea4cce37d14f922604049 and marked it as successful
