### ISSUE TITLE
Sped up bounty payment transactions are not verified by sync_pending_fulfillments cronjob

### ISSUE THREAD

**Issue by nickfarrow** [gitcoinco/web#7503]
**Describe the bug**
 I paid out a [bounty](https://gitcoin.co/issue/nickfarrow/niceBit/2/100023720#) but had to speed up the [transaction](https://etherscan.io/tx/0xdbee52619ce6a02d0289ddf71bfc1158c8310843944cab4cad09a4dcb4ed72ee). The replacement tx has confirmed, but it is still waiting for verification on the bounty page.

**To Reproduce**
Pay a bounty with a low gas price, then replace the transaction with a gas price high enough to be confirmed.

**Expected behavior**
The transaction status should be updated by this [sync_pending_fulfillments cronjob](https://github.com/gitcoinco/web/blob/fbdb456657a7157e0772b8ccef781f455a7c857b/scripts/crontab#L16).

I ran a local copy of [app/dashboard/sync/eth.py](https://github.com/gitcoinco/web/blob/288ad71741a893135ff9d6d7f5854b330d6df487/app/dashboard/sync/eth.py) and everything worked as expected.

So I believe the bug would be in [management/commands/sync_pending_fulfillments.py](https://github.com/gitcoinco/web/blob/8a8e86a814027d36f4420b5007978f929a47ba23/app/dashboard/management/commands/sync_pending_fulfillments.py) or the cronjob.

**Screenshots**
![screenshot](https://i.imgur.com/TUmuFyA.png)

**Desktop (please complete the following information):**

- OS: arch btw
- {'User-Agent': 'Mozilla/5.0 ...'}

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/7490 should help here!
