### ISSUE TITLE
zkSync checkout not working

### ISSUE THREAD

**Issue by jo-tud** [gitcoinco/web#7504]
**Describe the bug**
When trying to check out a basket with over 40 contributions using zkSync I get a spinner that never disappears. After a while an error message is shown.

**To Reproduce**
Check out a basket with zkSync (I reproduced it in chrome and firefox)

**Expected behavior**
checkout works.

**Screenshots**
![image](https://user-images.githubusercontent.com/1543640/93997734-03dca380-fd94-11ea-91a8-96c19bdfe94e.png)

**Desktop (please complete the following information):**

- OS: fedora
- Browser: chrome, firefox
- Browser Version: up to date

**Comment by mds1** [comment]
Hey @jo-tud, zkSync has been having some server issues and is working on a fix. I'd recommend trying again in a few hours and hopefully it's resolved by then

**Comment by jo-tud** [comment]
Okay, thanks. Now it's on and off, sometimes working, sometimes not.

**Comment by mds1** [comment]
#7511 adds a message to inform the user of this problem, so closing this issue
