### ISSUE TITLE
collections v1.1

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7513]
- [ ] PIL image for grant collections https://github.com/gitcoinco/web/issues/7512
- [ ] I’m thinking that a widget for collections would be great so social media influencers could embed it in their sites
- [ ] add ability to edit grant collections desc/title
- [ ] add ability to add "team members" to your collection; other ppl who can add/remove from collection

**Comment by owocki** [comment]
- [ ] ability to fund matching rounds for your collection :)

**Comment by thelostone-mc** [comment]
- [ ] having a counter to show how many people have clicked the add a collection
Gives us a means of sorting by popularity 
300 users -> had added sybil collection to their cart

**Comment by ceresstation** [comment]
- [ ] ability to add grants to a collection via the main grants page vs. only upon checkout
