### ISSUE TITLE
Tribe Management Tab Busted

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7521]
**Describe the bug**
Text editor area for tribe management is not displaying/working

**To Reproduce**

- Go to this tribe https://gitcoin.co/celo-org/manage
- Click Manage Tab
- See missing input area to enter in  information

**Expected behavior**

Text Editor should be there

**Screenshots**

<img width="1668" alt="Screen Shot 2020-09-23 at 11 42 14 PM" src="https://user-images.githubusercontent.com/238235/94098521-c826f580-fdf6-11ea-8b42-1d2ce3a3d0c9.png">

**Desktop (please complete the following information):**

- OS: MAC
- Browser: CHROME 
- Browser Version: ersion 84.0.4147.105

**Additional context**

**Comment by thelostone-mc** [comment]
53dd86a0c0f26cc2087e03796ebea297a6a88cb2
