### ISSUE TITLE
Verify Grant Issue: Nifty Ink

### ISSUE THREAD

**Issue by azf20** [gitcoinco/web#7531]
### Who
https://gitcoin.co/grants/1162/nifty-ink

### What 
We still have the warning about not having verified twitter ownership, but we tweeted here: https://twitter.com/NiftyInk/status/1305881939614879744
Let me know if I did something wrong there.

**Comment by thelostone-mc** [comment]
@azf20 It's verified ^_^

**Comment by azf20** [comment]
Thanks so much!
