### ISSUE TITLE
I can add my own grant to my cart - create a collection w/ your grant included

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#7533]
**Describe the bug**
I have added my own account to my cart, to create a collection to promote more than just my grant to my community:
https://gitcoin.co/grants/collections?collection_id=28

I used to see an error when I tried to add my grant, there seems to be no issue now...

![image](https://user-images.githubusercontent.com/35669742/94213964-1c7cb480-fe8d-11ea-8d3a-ea894ccb1f46.png)

Then all the way to checkout I am not given any issue form the UI....

**To Reproduce**
1. Signed in as a user that has control (can edit/cancel) a grant
2. add to cart
3. checkout
4. (NOT TESTED) actually submit a tx (zk or regualr)

**Expected behaviour**

I need a way to *create* a collection that includes my grant, but ALSO prevents me from funding it myself.

**Comment by DeFiDude** [comment]
Hey - just want to chime in here, I just realized this myself and actually tested it out - it does indeed work, however it does not show me as a contributor, nor does it show on the recent transactions.

@owocki - sorry for any trouble this may have caused but I donated 5 DAI to my own grant, can you nullify the matching for that specific donation (if it matched it, I wasn't paying attention to the total amount, or matched amount - so I'm not sure)?

I tried it out to see if it was possible, came here to open an issue, and see @NukeManDan already did.

**Comment by owocki** [comment]
yeah we re -added the abilityto add your own grant to cart so that ppl  could create collections with their own grants.  

the clr match wont be granted for those contributions tho.

**Comment by NukeManDan** [comment]
Got ya. what I suspected - I was gonna post an issue suggesting that before I noticed I could do it already!

Would be good to block the user from funding their own grant, matched or otherwise to save dat gas (like @DeFiDude ran into) 🙏🏼

**Comment by GriffGreen** [comment]
I am very very happy about this feature. thx gitcoin!
