### ISSUE TITLE
Get updates on a grant I've contributed to

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7538]
### User Story

As a funder of a grant, when there are changes or updates to a grant,  I'd like to receive updates on the grant project.

### Description

Create an email that goes out to grant funders of changes to a project on grants I've previously funded.

### Current Behavior
[comment]: # (Describe what actually happened.)
No update

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Receive email update for project updates, activity update.
When there are changes, send max one email per grant  per day after change occurs.

### Definition of Done

- [ ] Design email web & responsive
- [ ] Build email

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment]
doesnt the 'email funders' functionality already sort of handle this tho?
