### ISSUE TITLE
Grant Categorization Issue?

### ISSUE THREAD

**Issue by JTraversa** [gitcoinco/web#7542]
I created a grant ~3 weeks ago: https://gitcoin.co/grants/1103/the-defihedge-protocol

I just noticed today that I am unable to actually find it when searching through the grant round.

That said I just tried creating a new grant: https://gitcoin.co/grants/1354/the-defihedge-protocol-2

The second shows up, not sure what I did differently, perhaps categorized it wrong initially? Regardless thought I would figure out what I did wrong the first time around to ensure it shows up properly for the next round, or if it wasn't an issue on my end report the bug with my first grant.

Thanks for the help as always.

**Comment by thelostone-mc** [comment]
This should be fixed now
