### ISSUE TITLE
Evaluate features & Integrate Circle into Paying Tribes

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7546]
### User Story

As  an organization owner who is interested in cultivating an open source community on Gitcoin, I'd like to have basic community functionality to interact with my community.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

- Decide which features of circle we should integrate into Tribes.
- Work with  Sanchay to implement

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by willsputra** [comment]
@thesachinmittal
