### ISSUE TITLE
Contributing Link in README.md doesn't work

### ISSUE THREAD

**Issue by Sabihashaik** [gitcoinco/web#755]
Contributing Link in README.md doesn't work
### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
It is important to direct new users to the right CONTRIBUTING.md Link

### Description
On clicking the link provided in first bullet point (link for guidelines) under heading **On Github**, it takes the user to 404 Not found page.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: 
- [ ] Change the link to the correct link for CONTRIBUTING.md.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
* Replaced with new link
### Additional Information
<img width="960" alt="2018-03-31 09_18_31-" src="https://user-images.githubusercontent.com/21033484/38159934-b54ec71a-34c4-11e8-9c96-eb249951f129.png">

I'd like to fix this tiny issue 😄

**Comment by thelostone-mc** [comment]
@Sabihashaik Ah can't believe we missed this! -.- 
Thanks for this !
PS: welcome to the gitcoin family ^_^
