### ISSUE TITLE
[DESIGN+BUILD] Tribe Projects Section - Surface Great Projects

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7550]
### User Story

As  a  sponsor of a Gitcoin Hackathon/Tribe customer, I'd like a way to showcase great projects on my tribe.

### Why Is this Needed

Could be more clear.

### Description

- Find ways to surface great projects
- Display winners at the top of thee projects or add filter ability
- Update information on the cards
- Consider default states

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [x] Simplify card design (https://user-images.githubusercontent.com/19514207/94554255-664e0c00-028c-11eb-80cf-fdba6dd3238e.jpg)
- [x] Remove "View Project", "View Bounty", "Chat", "Sponsored by", "Looking for Team Members" from cards (only on Tribes view! let's keep these for Hackathons for now)
- [x] Sort cards by winners first (@sanchaymittal has a PR that solves this)
- [x] Remove right sidebar
- [x] Keep left sidebar, make it hidden by default

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by willsputra** [comment]
@PixelantDesign what do you think of simplifying the cards design? since we're removing a lot of stuff from the cards (View Bounty, Sponsored by, Looking for Team Members...)

![projects](https://user-images.githubusercontent.com/19514207/94554255-664e0c00-028c-11eb-80cf-fdba6dd3238e.jpg)

In the future we can add the Likes & Comments features too, when we're building the project discoverability feature.
![v2](https://user-images.githubusercontent.com/19514207/94554423-a44b3000-028c-11eb-95c3-2a73cfec0db6.jpg)

**Comment by PixelantDesign** [comment]
yes! I like simplifying the cards, this also follows the new project view designs.
We should see existing winner  badge though, or update it everywhere so it's consistent. Check Projects V2 ticket.

**Comment by PixelantDesign** [comment]
@sanchaymittal is there anything we can do to remove the right rail on the projects view? It takes up a whole column  where we could be showing projects. Maybe we need another ticket to refactor right rail @willsputra

**Comment by PixelantDesign** [comment]
Let's hide filters by default, and sort by winners at the top?

**Comment by sanchaymittal** [comment]
> @sanchaymittal is there anything we can do to remove the right rail on the projects view? It takes up a whole column where we could be showing projects. Maybe we need another ticket to refactor right rail @willsputra

We can remove the right sidebar, but we need to put the filters somewhere.

**Comment by willsputra** [comment]
@sanchaymittal figma file here. note I've updated the Winner badges:
https://www.figma.com/file/9jouLUCmEqY4B6Hnhoji26/Gitcoin-Tribes-2020?node-id=4%3A2

**Comment by sanchaymittal** [comment]
@willsputra Should I place the grant-tag at right-hand side of the project card?

**Comment by willsputra** [comment]
@sanchaymittal yes please!
