### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by seichris** [gitcoinco/web#7557]
Set up a grant 10 minutes ago. Trying to verify. Getting an error: `Sorry, we couldn't get the last tweet from @https://twitter.com/chriscyber2000`

### Who
https://twitter.com/chriscyber2000/status/1310875501888708608

### What 
https://gitcoin.co/grants/1382/ipfs-social-bookmarking

### Why
May be because I sent two tweets with the grant link?
May be because I need to wait a bit?

**Comment by thelostone-mc** [comment]
It's verified now ^_^

**Comment by owocki** [comment]
but do we know the root cause!|?
