### ISSUE TITLE
zkSync payment issue

### ISSUE THREAD

**Issue by louisdm31** [gitcoinco/web#7558]
Hello everybody,

Yesterday, I tried to make a contribution to Turbo-Geth on gitcoin.
The gitcoin system supposedly failed to proceed my transaction, despite my zkSync account was successfully debited.
Here is the exact path I followed : 
- logged in, added a 0.01 ETH contribution to cart, then tried to pay with zkSync.
- I managed to complete the first two steps. I encountered some hurdle though. I had to refresh the page twice to make it work.
- I tried to make the last step. I signed the zkSync transaction. 
- After some time, zkSync confirmed the transaction. The tx hash is c91754eae22a59ed1f5a17113c2f3708ae55ae3f82b6c1ab77b4c1e818165493
- In the gitcoin interface, the step 3 was still "processing", and was apparently stuck, even hours later.
- I refreshed the page again. Since then, my failed contribution completely disappeared. It is not even listed in the "transaction" tab.

My config : firefox on linux.
I hope that will help ...

**Comment by Kryp0rd** [comment]
I am having the same issue but with windows.

**Comment by owocki** [comment]
@mds1

**Comment by mds1** [comment]
Hey @louisdm31—I'm not 100% certain of this without additional information, but I believe the transaction that you see is actually an intermediary transaction we use to improve UX, and not the actual donation to Turbo-Geth

We should be able to complete your checkout with the following steps:
1. If the grant is still in your cart, great! If not, re-add it and for the same amount
2. Let me know once step 1 is complete, and I'll make a change on the backend
3. Afterwards, revisit the cart page and you will be prompted to finish checkout

---

Hey @Kryp0rd, if you can provide me with any transaction hashes / addresses / console errors, I can help you out as well. If you don't want to share the transaction hash publicly feel free to message me on Telegram @msolomon4 or Twitter @msolomon44

**Comment by louisdm31** [comment]
Hi @mds1 , thanks for your answer. I've just re-added my contributions to the cart.

**Comment by mds1** [comment]
Awesome, thanks. Now visit the cart page again and let me know if things work as expected!

**Comment by louisdm31** [comment]
Problem solved. Thanks a lot !

**Comment by mds1** [comment]
No problem!
