### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by Criptodiana** [gitcoinco/web#7562]
### Who
My gitcoin grant account

### What 
Already sent the tweet for verification from my account and it's not working

### Why
I don't know. Help!

**Comment by thelostone-mc** [comment]
Could you share the
Grant Link 
Tweet Link

@Criptodiana

**Comment by Criptodiana** [comment]
Of course. Here https://gitcoin.co/grants/1332/the-blockcode

**Comment by Criptodiana** [comment]
What seems to be the issue?

**Comment by owocki** [comment]
can you pls share the tweet link?  what browser are you on + where does it fail?

**Comment by Criptodiana** [comment]
Of course, here is the tweet: https://twitter.com/TheBlockCode/status/1309511868793458688?s=20
 I'm in Google Chrome. The failure is that after the tweet and pushing the Verification button, my account remains unverified.

**Comment by Criptodiana** [comment]
Hello?

**Comment by owocki** [comment]
@Criptodiana please allow 24 hours for a response.

**Comment by owocki** [comment]
grant is now verified
