### ISSUE TITLE
Deploy 9/30 QA Ticket

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7568]
# Hackathons

### Events Tab

deployed, working fine.

### Participants Tab

- waiting on a deploy
### Projects V2

- waiting on deploy to test @zoek1 

# Tribes

### Tribes Email to Followers

- waiting on fix from @sebastiantf 

### Convert to Grant

- [ ] - add link from grant project back to hackathon project, [display hackathon project  name](https://www.figma.com/file/xyjOr7GkRv6M1BF4muPoWI/Gitcoin-Tribes-Pro?node-id=3%3A885), use [font awesome lightning bolt](https://fontawesome.com/icons/bolt?style=solid).

### Onboardinig

- [ ] when user completes the tasks, a check should display in each circle. 
<img width="371" alt="Screen Shot 2020-10-01 at 11 16 58 PM" src="https://user-images.githubusercontent.com/238235/94884775-5d9c3800-043c-11eb-9b89-676c662a0149.png">

# Other

### Notification Count

- [ ] - lorem ipsum
- [ ] - lorem ipsum

**Comment by melvinalvarez** [comment]
the edge of `#sponsor_sidebar` `<li>` items get cut off on 1440 x 900px screens (screenshot attached below)

<img width="1440" alt="Screenshot 2020-10-02 at 12 47 57 AM" src="https://user-images.githubusercontent.com/6550846/94840086-76abe580-044a-11eb-97bd-1ab674497c76.png">

`.ml-4, .mx-4 {
    margin-left: 1rem!important;
}` might be pushing `<li>` items past edge of screen

**Comment by jdorfman** [comment]
The add to calendar links have the right date.

![image](https://user-images.githubusercontent.com/398230/94870149-ada6da80-03fb-11eb-8895-8766a9b25298.png)

**Comment by melvinalvarez** [comment]
On Grants page, the collapse/expand button for some of listed categories are not displayed inline on 1440 x 900 px screens

<img width="248" alt="Screenshot 2020-10-02 at 9 57 41 AM" src="https://user-images.githubusercontent.com/6550846/94880997-31fa6b80-0497-11eb-9f74-908cd919737a.png">

**Comment by PixelantDesign** [comment]
@zoek1 are you able to fix @jdorfman feedback? see above
