### ISSUE TITLE
EXPERIMENT: Integrate Circle into ETC Labs Hack

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7569]
### Why
As Gitcoin we'd like to know if integrating  circle will encourage idea formation and collaboration/communication between hackers.

### What

- [x] Integrate circle into ETC labs Hack
- [x] Turn off Circle notifications (since it doesn't sync with ours)

### Additional Comments

- all of the information stays in the circle, doesnt sync back with main townsquare. 
- when hackers are filling out their participant info, intros will display into  participants tab, and won't get synced back into hack townsquare.

**Comment by sanchaymittal** [comment]
@PixelantDesign Pr is merged for this issue.
