### ISSUE TITLE
user directory v1.1 feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7579]
continued from https://github.com/gitcoinco/web/issues/7334

HIGH PRIORITY
- [x] can we add copy/paste-able links to the directory?  for example, i serach for foo=bar and foo1=bar1 and i get gitcoin.co/user_directory?foo=bar&foo1=bar1 in the URL bar. when someone loads that search they'll be taken to that page
- [x] this list should be de-duped https://bits.owocki.com/8LurQKWp
- [ ] this list should be sorted in descendding order by prevalance https://bits.owocki.com/8LurQKWp
- [ ] can we please only export contact info (email) if the user is an admin? i dont want to leak everyones emails to non-admins, when this goes GA.
- [ ] can we get weekly onboarding cohort tags in the user directory. i'd like for the new user directory to allow me to filter onboarding cohorts + easily see how many of them are capturing the above milestones "eg i can lookup the "2020_week_33_conversions" cohort in it.  this will relaly really help with onboarding

ATTENTION TO DETAIL STUFF
- [ ] can you put in a fix for [boolean](https://bits.owocki.com/OAuJzem0)/date filters, [foreign key](https://bits.owocki.com/p9uwxmgW) inputs, which still dont seem to be working?
- [ ] after i've done a few searches, the filters on the left hand side stop working. can we make the left hand filters work even after a few uses?  

OTHER ASKS
- [ ] the ability to 'remove user' from a query is something i know @vs77bb has asked for
- [ ] add a 'sort by' option so that i can sort by a specific filter (either ascending or descending). is it easy to do this for all filters?
- [ ] default remove folks who explicitly say "do not contact" to ensure we don't piss people off

DESIGN
- [ ] can we get a rev on the aesthetic design of this tool pls?
- [ ] something needs to be done about the discoverability of filters on the left hand side.  (maybe suggested filters, or 'example searches'?

**Comment by connoroday** [comment]
I get a lot of duplicate entries for tags, seems like they're case sensitive but also there are repeats with the same cases:
<img width="249" alt="Screen Shot 2020-10-06 at 4 47 58 PM" src="https://user-images.githubusercontent.com/7794646/95271865-d6601300-07f3-11eb-921a-73476acfdbfc.png">

**Comment by androolloyd** [comment]
when chosing multiple keywords, we're currently subject to only OR matches, a good method of selecting AND's into the query set is a must.
