### ISSUE TITLE
Problem with zkSync at checkout

### ISSUE THREAD

**Issue by josjo80** [gitcoinco/web#7580]
**Describe the bug**
I had an issue with using zkSync at checkout.  I got to the final confirmation button and submitted the transaction but it seems like it never went through.  I believe that I sped up the second transaction via Metamask so I'm not sure if that caused a problem.

**To Reproduce**
I got to the zkSync checkout, submitted the first transaction successfully, but the second transaction was taking a long time.  I think that Metamask used too low of gas, so I sped it up.  That transaction appeared to go through.  I clicked on the last button, the confirmation button but it just kept spinning (never completed).  I now get a "Cannot read property 'status' of null
" red bar at the top of the screen when I go to check out again.

**Expected behavior**
I would expect the final transaction to complete.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Browser Version:  Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
I spoke to Kevin Owocki about this over Twitter DM.

**Comment by hegedis-andor** [comment]
I think it is a duplicate:
[https://github.com/gitcoinco/web/issues/7479](#7479)

**Comment by mds1** [comment]
Hi @josjo80, transactions that are sped up are not currently picked up, so we have to update this manually. If you provide me with both transaction hashes I can get this resolved for you! If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4
