### ISSUE TITLE
Contradictory information in a hackathon

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7588]
In the screenshot 
![Screenshot from 2020-10-02 12-00-40](https://user-images.githubusercontent.com/2900574/94906339-fbc4e800-04a6-11eb-8798-7602cb946ab2.png)
you see that there is 1 prize but the prizes list is empty.

**Comment by PixelantDesign** [comment]
Good catch @vporton Thanks!

**Comment by octavioamu** [comment]
@vporton can you give us steps to reproduce?
entering on https://gitcoin.co/hackathon/arweave-owf/? seems is showing the bounty without problem for me 
![image](https://user-images.githubusercontent.com/1358093/97005078-4e2c7e00-1514-11eb-9f94-326ed4c7bd34.png)
Also if you have any console error will be helpful

**Comment by octavioamu** [comment]
I see your print probably is older than the issue date right? Because there is a rule on the hackathon prize that hide the prizes if the hackathon didn't start yet. That will explain the situation.
