### ISSUE TITLE
Bounty details screen on mobile not responsive

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#759]
Bug: bounty details page display problem on mobile, buttons are not placed correctly.

![image](https://user-images.githubusercontent.com/1838338/38175613-a02ae708-35df-11e8-8937-6e0047db2d33.png)

**Comment by thelostone-mc** [comment]
@kziemianek Thanks for pointing that out !  ^_^

**Comment by kziemianek** [comment]
@owocki seems like this issue is fixed, shall we close ?

**Comment by mbeacom** [comment]
Thanks everyone!
