### ISSUE TITLE
Contribution made with zksync not reflecting in the UI

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#7591]
**Describe the bug**

 https://gitcoin.co/neozaru has contributed to 27 grants but its contributions are not showing up in the UI, this is the [cart](https://gitcoin.co/grants/cart/bulk-add/1175;1;283,237;1;283,143;1;283,461;5;283,938;10;283,142;1;283,500;1;283,821;1;283,184;1;283,1069;1;283,711;1;283,1110;1;283,296;1;283,1268;1;283,351;1;283,149;1;283,199;1;283,961;1;283,886;1;283,795;1;283,413;1;283,798;1;283,1147;1;283,1162;1;283,277;1;283,12;1;283,946;32;283,:neozaru) he used to contribute  and here is the zksync account from which he made the tx: https://zkscan.io/explorer/accounts/0x92A0b2C089733beF43Ac367D2CE7783526AEA590 
TX hash: https://zkscan.io/explorer/transactions/d66b36b67fb2f58448018985ad7e69698c99bef0424d2c1090644e8d1d331b5c

Additionnal info : I used the zkSync with DAI that I had loaded previously. It was my third round of grants. Also my Metamask might have been connected to another network than mainnet on another window when I signed, but the UI didn't complain and I can see the tx on zkScan so I imagine it went through

Here is the conversation with the user: https://chat.gitcoin.co/gitcoin/pl/h6ihx7asq38xf8dmxe7s418giw
**To Reproduce**

Idk if it's reproduceable

**Expected behavior**

Show the contribution in the grants UI

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hey @neozaru, thanks for all the details. This happens occasionally so we'll manually get your contributions added to the database so they show up + get matched

**Comment by carlaj-de** [comment]
Hello! Sorry for jumping on this feed. I am also having a similar issue but I have been unable to submit a log.

I have tried to donate to a grant but they haven’t received the donation. It’s gone through on the etherscan. 

Is it possible for someone to follow up my transaction? Thank you!

**Comment by mds1** [comment]
Hi @carlaj-de, can you please share your transaction hash so I can look into this? If you don't want to share it publicly feel free to message me on Twitter @msolomon44, or Telegram @msolomon4
