### ISSUE TITLE
Unable to Verify Grant - Twitter

### ISSUE THREAD

**Issue by gravenp** [gitcoinco/web#7602]
### Who
@gravenp, https://gitcoin.co/grants/1403/the-geo-web
### What 
Unable to verify grant with Twitter account via the provided method
### Why
Receive an error: "Sorry, we couldn't get the last tweet from @https://twitter.com/thegeoweb"
Tweet: https://twitter.com/thegeoweb/status/1312187005594292224?s=20

**Comment by thelostone-mc** [comment]
Done!
