### ISSUE TITLE
improper email about inactivity

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#761]
*Type*: bug

### Current Behavior
Recived email about inactivity, but commented github issue today.
![image](https://user-images.githubusercontent.com/1838338/38175928-44cb7840-35e5-11e8-816c-8aaecd65641c.png)

### Expected Behavior
Github activity should be detected.

**Comment by owocki** [comment]
🤔 i wonder if since this issue ( https://github.com/gitcoinco/web/issues/506 ) has so many comments, its not getting the most recent ones because of pagination...

**Comment by kziemianek** [comment]
My suggestion is to add request parameter `since`. If we are interested in comments from last 3 days, there is no need to fetch older.

https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/458
