### ISSUE TITLE
Unsure if donation counted towards matching

### ISSUE THREAD

**Issue by 4-1-3-X** [gitcoinco/web#7611]
I'm unsure whether this donation was included towards matching: https://gitcoin.co/townsquare?tab=activity:383123

I say this because I noticed the Grant's DAI amount go up then go back down again. So I checked etherscan and the donation transaction was accidentally submitted twice (the second one failed because of USDC approval)

Successful txn: https://etherscan.io/tx/0xd3c696109c30e46833c8fc354c20bae97cefbb7750dad4b3fe4b57c9ccc01b84
Failed txn: https://etherscan.io/tx/0x6487116dcd2bf30084b9839c9beb1453120ca908b1bc42e7ce021e53d2e4be84

If you could please check on this I'd appreciate it. Thanks!

Sincerely,
ETH Memes

**Comment by owocki** [comment]
yes it counted!  the reason it went back down is once the round meets saturation (100% matching rounds allocated), donations basically become a zero sum game wherein contributions to other grants incrase the match amounts of their own grants + thereby reduce the matching amounts of other grants.

**Comment by 4-1-3-X** [comment]
Ah yes, I understand that but it was the Non-matching number that went down so I thought maybe the failed transaction screwed something up.

Thanks for the help Owocki!
