### ISSUE TITLE
sms/brightID refactor

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7616]
#### Description

- Pull SMS verification into it’s own component
- Pull BrightID aspect into it’s own component
- Review + Merge all other trust verification integrations

At this point SMS verification flow has it's own place during the checkout process
while BrightID has everything setup in profile trust bonus tab

Ideally we'd want to shift all verification means into the trust bonus tab of the user profile as opposed having to spread apart

@apbendi

**Comment by willsputra** [comment]
we should also put a banner somewhere on the checkout flow, explaining people can get bonus matching and link to trust bonus tab

**Comment by thelostone-mc** [comment]
Google: https://github.com/gitcoinco/web/pull/7631
Idena: https://github.com/gitcoinco/web/pull/7646
POAP: https://github.com/gitcoinco/web/pull/7682

@apbendi

**Comment by willsputra** [comment]
@thelostone-mc @apbendi 

>we should also put a banner somewhere on the checkout flow, explaining people can get bonus matching and link to trust bonus tab

thoughts? this will also replace the "Verify my number" link we have at the top of the cart

![verify](https://user-images.githubusercontent.com/19514207/98245714-4f49ba80-1fac-11eb-8cbc-20d42a8400b3.jpg)

**Comment by thelostone-mc** [comment]
Yup! LGTM
