### ISSUE TITLE
Have to cancel bounty several times ànd stays visible as active 

### ISSUE THREAD

**Issue by krrisis** [gitcoinco/web#7625]
### Who

Canceled [this github bounty](https://gitcoin.co/issue/aragon/aragon-monthly/284/1850) today, although I could swear having done this before. 
After scrolling back in my activity, I see I indeed did this before, [namely 5 months ago, as you can see here.](https://gitcoin.co/townsquare?tab=activity:270068)
So after doing this again today ([successfully it seems this time](https://etherscan.io/tx/0x8b353195b2ea2c327648af6b79a494287343c824d72ed9654a37d7e00cfb5972)) the bounty [still stays visible as active on my profile as you can see here.](https://gitcoin.co/krrisis/active)

**Comment by krrisis** [comment]
edit: I see it disappeared as an active one now, will still leave this issue here & let you close it, because it is strange that I had to cancel it twice (as you can trace above), maybe a bug worth looking into.

**Comment by thelostone-mc** [comment]
@krrisis Hmm not able to reproduce this but we've moved onto a much more smoother experience in the bounty flow.
So the next time a bounty created -> it would be a seamless experience
