### ISSUE TITLE
Tribe People Tab Showing Wrong People

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7628]
**Describe the bug**
People Tab in Tribe Showing Wrong People
It's displaying some of our core team members first - that likely did not participate in their hackathons.

**To Reproduce**
Go to a Tribe like Sia https://gitcoin.co/nebulouslabs/people
Click Tribe Hackers 
This is what is shown 
<img width="1861" alt="Screen Shot 2020-10-06 at 1 42 51 PM" src="https://user-images.githubusercontent.com/238235/95240069-e10dae80-07d9-11eb-8a70-01d0cfd69d69.png">

**Expected behavior**
Show Top Hackers for this tribe. Sort by winners, then all hackathon participants

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Browser Version: Version 84.0.4147.105

**Additional context**
@sanchaymittal was this part of Tribes Light fix?

**Comment by sanchaymittal** [comment]
@PixelantDesign With tribes light, we are ordering the users in people tab based on their contributor's rank.


- Do we want to sort the users based on their participation in tribes hackathon?
- Sort by Winner: Are we considering the user's winning status in tribes hackathon or all-around number of hackathons won by user.
- There are hackathons with multiple sponsors, Do we want to sort based on the participation in sponsor's bounty or hackathon( possibility of not being involved in sponsor's bounty.
