### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by claberus** [gitcoinco/web#7632]
Hi,

I verified my OpenEthereum grant:

https://gitcoin.co/grants/1415/openethereum-ex-parity-client

https://twitter.com/OpenEthereumOrg/status/1313755100767281153

but it still shows not verified.

Thanks!

**Comment by thelostone-mc** [comment]
Looks like it did get verified 
![image](https://user-images.githubusercontent.com/5358146/95477691-3d252e00-09a6-11eb-8b48-81b28577e7d8.png)
