### ISSUE TITLE
Verify Grant Issue - Twitter verification not responding

### ISSUE THREAD

**Issue by peterVG** [gitcoinco/web#7635]
### Who

https://gitcoin.co/grants/1416/pygate
https://gitcoin.co/grants/1417/deplatformr

### What 
Verify Grant Ownership via Twitter is not responding. Clicking on the "Send Verification Tweet" is not generating a verification tweet. There are no notifications appearing in the linked Twitter account. Have tried it from both Firefox and Chrome.

<img width="468" alt="Screen Shot 2020-10-07 at 7 16 03 AM" src="https://user-images.githubusercontent.com/672121/95343107-00a1e700-086d-11eb-930c-2b3c8f65c8a2.png">

### Why

We don't have project Twitter accounts. We just have a personal Twitter account registered on the grant profiles. Could this be the issue?

**Comment by thelostone-mc** [comment]
@peterVG there are 2 ways to go about this

- either create a twitter account for the grant and add that into grants and verify 
- update the grant twitter to your personal twitter id and tweet + verify from it

![image](https://user-images.githubusercontent.com/5358146/95477418-f20b1b00-09a5-11eb-97d9-c6c499959f56.png)
