### ISSUE TITLE
Update server side deployment steps in docs

### ISSUE THREAD

**Issue by mul1sh** [gitcoinco/web#7662]
**Describe the bug**
Right the gitcoin [docs](https://docs.gitcoin.co/) are very detailed and exhaustive when it comes to explaining the gitcoin dApp locally and this is awesome 😃👌. However they are lacking the same clarity on how to deploy the dApp on the server side i.e. in Amazon EC2 or Digital Ocean which is not ideal. 

An update on the docs giving another detailed explanation on how to do this would be very much appreciated. It would make debugging the dApp much easier especially for cases where `ssl/https` is a must i.e. https://github.com/MetaMask/metamask-mobile/issues/1273

**To Reproduce**
Go to https://docs.gitcoin.co/  and you'll see its lacking clear instructions on how to deploy the gitcoin dApp on a server.

**Expected behavior**
https://docs.gitcoin.co/ should bee clear on the server-side deployment steps so as to help with debugging.

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: Chrome
- Browser Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

Any help on this will be much appreciated 🙂

**Comment by thelostone-mc** [comment]
>Go to https://docs.gitcoin.co/ and you'll see its lacking clear instructions on how to deploy the gitcoin dApp on a server.

It's a traditional django app so you'd have it run it as such to get it hosted on AWS / DC
It would work as. long as the ENV variables are set.
