### ISSUE TITLE
As a user being onboarded, I want the daily emails to be optimized around "where im at in onboarding" so they are maximially valuable in my getting value out of Gitcoin

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7665]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user being onboarded, I want the daily emails to be optimized around "where im at in onboarding" so they are maximially valuable in my getting value out of Gitcoin

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Gitcoin is a big complex place, with many different value propositions.
Emails meet me where I'm at, every day.

Exhibit A; our email trend
<img width="793" alt="Screen Shot 2020-10-12 at 2 32 15 PM" src="https://user-images.githubusercontent.com/513929/95788354-9dfb8180-0c98-11eb-91b0-f2e6f28bd7f1.png">

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
- A Dailiy Email that does a lot of things right; but still needs tweaking https://gitcoin.co/_administration/email/new_bounty_daily
- Daily email is not onboarding aware
- A bunch of other random emails that no one really tracks; updates; or knows about https://gitcoin.co/_administration/email/

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- i would love to add a ‘complete your profile’ widget in the daily email; or more broadly speaking, to make the daily email more onboarding-aware 
- to  actually push them down the product path with each product after they select a product in the onboarding flow (in daily email) 
- consolidate any other onboarding emails or misc emails into the daily/weekly
- a data dashboard that shows me for the last cohorts where we're losing peoiple along this funnel "landing page visit (#) => conversions to email capture (#) => read my emails  (#) => click my emails (#) "
- for the new user directory to allow me to filter onboarding cohorts + easily see how many of them are capturing the above milestones "eg i can lookup the "2020_week_33_conversions" cohort in it

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See above; I just put some ideas that would help me push forward; but others probably have good ideas too.

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)
See above

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)
Onboarding (getting people into a virtuous cycle where they are more engaged => putting more data in the system => coming back to gitcoin) is very very important.   Lets findt he key levers in our user psycology + push the virtous cycle foreward!

**Comment by owocki** [comment]
@frankchen07 @jdorfman @octavioamu feedback pls.  @androolloyd

**Comment by frankchen07** [comment]
Two main email upgrades would help here:

1. include profile completion widget in the daily email if the user hasn't completed it
2. depending on what products they selected, include "next" actionable steps. So we program statements A, B, C, D, and E for each product respectively (and also if they onboarded an organization), and then include them in a product welcome email that helps them onboard to the next step - this will most likely be for new users

===

3. fix pop-up modal / figure out why people aren't clicking it for new users

**Comment by jdorfman** [comment]
@owocki we still have these opened

#7186 
#7183

**Comment by owocki** [comment]
hopefully this helps us grok our email revamp too https://gitcoin.co/_administration/email/

**Comment by owocki** [comment]
we should also fold in some of these ideas https://blog.palabra.io/great-onboarding-plain-text
