### ISSUE TITLE
Tribe Discoverability in Grants

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7666]
### **Why**
- When a hackathon/grants customer does not currently have a running Gitcoin Grant round, there isn't an easy way to manage/discover all of the grant projects associated with the organization.
- The current implementation of a CLR round like Matic is not scalable, requires a lot of dev time to spin up.
- We believe that successful hackathon projects > successful grants projects are one of the core elements of our NSM
- sponsor engagement on the platform

### 1) When I want to know which grantees are utilizing my technology, I want to be able to see it, so that I can confirm that all of the projects are building on my tech.

- Add left nav to surface orgs/tribes list and way into experience
- Add sub nav under Matic header so it's easy to get to CLR when there is a running clr
- build out Org clr page to surface all of the projects building on that stack
- Add link to request to be part of collection/featured
- Add feature section (not a must for V1)

<img width="386" alt="Screen Shot 2020-10-12 at 11 47 30 PM" src="https://user-images.githubusercontent.com/238235/95813222-6830ba00-0ce5-11eb-9d97-fc84f688f1ef.png">

### 2) When I want to curate the top grant projects utilizing my technology, I want to be able to highlight it, so that I can showcase the top grants building on my tech.

- Using collection to organize all of the grants related to that org
- Add ability to be notified if there is a request
- Add ability to mark which grants display in featured area (nice to have)

<img width="383" alt="Screen Shot 2020-10-12 at 11 51 23 PM" src="https://user-images.githubusercontent.com/238235/95813455-ed1bd380-0ce5-11eb-9833-08a6cecd261a.png">

<img width="377" alt="Screen Shot 2020-10-12 at 11 49 13 PM" src="https://user-images.githubusercontent.com/238235/95813310-957d6800-0ce5-11eb-8e23-3197f4d585f7.png">

### 3) When I have selected a grant project utilizing my technology, I want to let them know that I have highlighted it, so that I can showcase the top grants building on my tech.

- Notify grantee that they've been added to an org's collection

<img width="300" alt="Screen Shot 2020-10-12 at 11 50 37 PM" src="https://user-images.githubusercontent.com/238235/95813378-c2ca1600-0ce5-11eb-9255-336f4a7dda92.png">

### 4) When I’m building utilizing a companies technology, I want to be featured in their collection, so that I can be highlighted to sustain my project.
<img width="383" alt="Screen Shot 2020-10-12 at 11 51 23 PM" src="https://user-images.githubusercontent.com/238235/95813455-ed1bd380-0ce5-11eb-9833-08a6cecd261a.png">

### 5) When I’m building utilizing a companies technology, I’d like to know when the company will accept my request to be featured in their grant collection.

- Accepted to be in the collection

<img width="300" alt="Screen Shot 2020-10-12 at 11 50 37 PM" src="https://user-images.githubusercontent.com/238235/95813486-fefd7680-0ce5-11eb-8983-23598b469d29.png">

### 6) When I’m opening a grant on a custom company page, I want my grant to be included in the organization’s collection, so that they are aware of my project which increases my chances of sustained funding.

- When a grantee is opening a grant on an org specific grant form, we should associate the grant with that org.

<img width="402" alt="Screen Shot 2020-10-12 at 11 53 32 PM" src="https://user-images.githubusercontent.com/238235/95813575-2c4a2480-0ce6-11eb-93f4-2c6886dafe6d.png">

### 7) When I’m opening a grant on a Gitcoin Grant page, I want to let the system know that I’m building on an organization’s tech, so that they are aware of my project which improves my chances of sustained funding.

- When a grantee is opening a grant on a standard grant form, we should ask in the form which organization to associate the grant to.

<img width="396" alt="Screen Shot 2020-10-12 at 11 54 09 PM" src="https://user-images.githubusercontent.com/238235/95813608-3f5cf480-0ce6-11eb-9945-f4a79a463578.png">

**Open Questions**

- Is there a simpler way to solve the problems outlined above?
- Thoughts on reuse of collections architecture?
- What is the proper way to connect organizations + projects data model in our system?
- Does having a feature area for an organization go against the idea behind grants/influence car support?
- What are we not thinking of?

**Other Related Ideas** 

- How do we open communication for grantees to seek help from grant donors?
- How do we allow orgs to turn on/off their own CLR rounds?

**Comment by thesachinmittal** [comment]
I loved the design, especially using collections @PixelantDesign 

Few ideas of my own,

1. Just created an issue to address my [views on engagement and information management](https://github.com/gitcoinco/web/issues/7668) for Gitcoin community as a whole, and the tribes.

2. What is the most useful structure for Org(s) - Is it **community voting**? for eg. _Matic CLR._
    - Then we should have an end result, where every organization hosts all its ecosystem projects on their tribe page. Another aspect of org(s) i understand is, its always a pain for them to update their project page. And i see 3,4,5 points mentioned above, making it happen. 

3. If we want to make it oriented towards community, we should have **like** & comment feature + funding + theme of the project mentioned. 

4. How do we open communication for grantees to seek help from grant donors? 
 - Encouraging Top Donors + feedback on the grant page. 

5. How do we allow orgs to turn on/off their own CLR rounds?
- @thelostone-mc can tell this better. :p 


6. By using Circle, I can give moderator access to people from organisation, which will help in maintaining the tribe.

**Comment by thelostone-mc** [comment]
I'm not very clear on why we'd want to have a tie up btwn Grants and Tribe and a self service CLR.

- Having a custom grant create page doesn't seem to give us a benefit apart from the artwork. There is a likely scenario where a grant want to be part of multiple tribes. I'd learn towards having a new field instead of categories which simply allows the grant creator to tag multiple tribes 
This would allow us to show the grants in relevant tribes improving discoverability 

- Assume we do have this built out,  right now -> creating a CLR round is controlled by us, and funds are sent to Gitcoin to make the payout which means we
   - tweak the threshold for every round
   - ensure payouts are made
   - verify the legitimacy of grants being created
This is a slightly complex thing to build out and I would not want us to build a self-service CLR unless we have at least a dozen rounds coming in

- How would we handle scenarios where a grant is part of  CLR active rounds using the same chain -> how do we decide which tribe pays what CLR match (or we force a grant to be in only tribe). If so what happens if the tribe wants to reject the grant  

- Collections are nothing more than a personalized curated list of grants. There is not an Tribe which has an association with maintaining a collection but instead an individual 

Also I would want us to discuss building out an organization / adding team members and stuff + team mgmt as opposed to accommodating this to the existing tribes data model. 



> The current implementation of a CLR round like Matic is not scalable, requires a lot of dev time to spin up.

It actually isn't! It took 30min to spin one up for filecoin

**Comment by frankchen07** [comment]
> CLR round like Matic is not scalable

Just a note that right now we're not yet looking to scale this. Manually, it takes about 15 min - 30 min to create a specific CLR round.

> asking and accepting a request

This is quite heavy for the first build. My recommendation is getting the organization's repo right on the Grants creation page if we want to be able to filter on a technology. This means you would add the project URL / Github, and also the technology's Github / repo when opening a grant, if we want that association. A problem would still exist as we would have to figure out how to backfill current grant "technology repositories". Those technology repositories map to an organization in our DB, and then it's a matter of adding a filter. This way we sidestep the heaviness of asking and accepting requests.

>  building out an organization / adding team members and stuff + team mgmt

this is also a consideration we should think about, to build out this scaffolding before we integrate organizations across other products.

**Comment by owocki** [comment]
> The current implementation of a CLR round like Matic is not scalable, requires a lot of dev time to spin up.

i'd challenge this, the dev setup is fairly easy after the refactoring that aditya made.  seems that where we fall down is on marketing these grants rounds (apollo and matic both had very little marketing success once we had put in the dev effort to set them up)

>7) When I’m opening a grant on a Gitcoin Grant page, I want to let the system know that I’m building on an organization’s tech, so that they are aware of my project which improves my chances of sustained funding.

i wonder if we could integrate withs omething like stackshare (justin dorfman used to work there, and i know the founder) as a way of integrating this info

> Thoughts on reuse of collections architecture?
love it

> What is the proper way to connect organizations + projects data model in our system?
defer to engineering

> How do we allow orgs to turn on/off their own CLR rounds?
my vision is to use the https://gitcoin.co/grants/matching-partners/new form + enable people to set a date range for their own CLR rounds (and fund either a part of our taxonomy OR their own collection) all self service

**Comment by PixelantDesign** [comment]
Thanks for the comments all!

**Grant Management**
There is still the issue of When a customer is not running a CLR round. Where is the best place for them to go to see/manage their grants. From Muskan at Matic is using the CLR page to manage all of the open grants. All of the categorization is in her head right now, she is the source of truth... in terms of where these projects are this is how they think about them:
"Live on testnet
Live on mainnet
No of transactions on mainnet 
On these specifications we categorize them"
There is also funding stages and marketing stages.

per @thelostone-mc this can be done via Admin

"This can still be done but someone vivek/sachin will have to work with them to add new categories and label which grants map to which one via admin"

**CLR Page/Custom page spin up:**
I was under the impression that it was a lot of effort to spin up a page like Matic Build & Earn. If not then that is good to know.

Per @thelostone-mc spinning up CLR

- These are the steps for New CLR Round for a  sponsor
- Ask them when + name of round + amount
- Ask them what is Categories should be listed under that CLR
- Sync up with design team for banner
- Set up CLR round via admin with the above collected details (30 min)

Then there is ongoing support of when they ask
disable a certain grant (5 seconds) if it not eligible for some reason
extend the round (5 seconds)
update saturation speed (5 seconds)

if the goal is to simply having the ability to filter grants ->
the could go to the grant matic clr page and filter by sub category
If they want to have additional filters -> that would be something which can be added or they could reuse grant subcategory (this was asked beforehand and they didn't give us a list so we just put the same subcategory in tech )
https://gitcoin.co/grants/clr/MATIC/?type=matic&category=devEx
shows grant of type matic and category devX

There is some work we can do to connect the organization and the grants...
Creating a true tribe data model 

Tribes data modal doesn't exist at this point in time.
Currently a tribe is a user with a glad which says it's a tribe.
If we are serious about it -> we need build tribes as a feature where you can create /maintain tribe

**Comment by PixelantDesign** [comment]
@merwane is picking this up! https://github.com/gitcoinco/web/issues/7110

**Comment by vs77bb** [comment]
> I'd learn towards having a new field instead of categories which simply allows the grant creator to tag multiple tribes

Agree with this comment from Aditya from a design perspective. 

> asking and accepting a request. This is quite heavy for the first build.

I agree, maybe no ask / accept. In the Matic version we did it manually. 

Generally I'm quite bullish on these user stories to create really high stickiness on our platform both for grant owners and grant creators.

**Comment by zoek1** [comment]
ETA November 16, 2020
