### ISSUE TITLE
post-bounty completion stats

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#767]
(not ready to be worked on)

after a bounty is completed, get feedback from both parties about how it went. 

* how long did it take?
* were there any snags along the way?
* did you get what you wanted out of the relationship?

**Comment by PixelantDesign** [comment]
Similar to the idea on #660

**Comment by owocki** [comment]
a data point: right now.. we email folks asking for feedback.

**Comment by jakerockland** [comment]
Yeah personally I didn’t mind providing feedback via email because I think this project is super rad, but I have a general disdain for email so having it be integrated into the UX of submitting a bounty is something that feels like an improvement to me.

**Comment by kuhnchris** [comment]
This was (probabbly) already implemented in the wake of the Funder Feedback Form. Closing this one (let me know if I got that wrong)
