### ISSUE TITLE
As a hackathon project buidler, I want to know that I can convert my project to grant

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/web#7671]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a hackathon project buidler, I want to know that I can convert my project to grant

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: We're going to have the convert to grant feature soon, and we would like to let hackathon project buidlers know they can convert their projects to grant through a one-time announcement email.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No email

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Email to hackathon project builders
![convert to grant email](https://user-images.githubusercontent.com/19514207/95875230-611cb100-0da4-11eb-8f06-c72ffc50630a.jpg)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- [ ] Email template built

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by willsputra** [comment]
cc @PixelantDesign

**Comment by PixelantDesign** [comment]
cool! should we outline the steps accompanied with 3 small images?

Step 1  click _Convert to Grant_ 
Step 2  complete details about your grant
Step 3  click submit and once approved, you'll have a Gitcoin Grant

also, maybe we start with a responsive view of the email?

@sebastiantf are you interested in working on this one?

**Comment by sebastiantf** [comment]
@PixelantDesign I shall pick this up.

**Comment by sebastiantf** [comment]
@willsputra Can you please share the header image and that screenshot image being used in the email content?

**Comment by willsputra** [comment]
@sebastiantf we can keep the existing header!

screenshot:
![screenshot](https://user-images.githubusercontent.com/19514207/95990366-fe87eb80-0e5d-11eb-8f82-29563df8c3dc.jpg)

**Comment by sebastiantf** [comment]
Thanks @willsputra

**Comment by sebastiantf** [comment]
@PixelantDesign @willsputra Is this fine?

![wip2_convert_project_grant](https://user-images.githubusercontent.com/36922376/95994266-b6f96380-0e4d-11eb-9b03-1d1253e6f089.jpg)

**Comment by willsputra** [comment]
Looks good to me! @PixelantDesign what do you think?

**Comment by sebastiantf** [comment]
@PixelantDesign PR up at #7703
