### ISSUE TITLE
Make possible to join two grants into one

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7673]
Sometimes two goals happen to be solved by the same project.

So, please make possible to join two grants into one grant with their contributions being summed.

**Comment by danlipert** [comment]
@vporton would this be where the same project has two different grants, or two grants are solving the same issue? Because we definitely want to support multiple people working on the same thing - reopen if I'm misunderstanding

**Comment by vporton** [comment]
> @vporton would this be where the same project has two different grants, or two grants are solving the same issue? Because we definitely want to support multiple people working on the same thing - reopen if I'm misunderstanding

I meant two projects joining into one (yes, it is possible only if they solve the same issue).
