### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by maurycyp** [gitcoinco/web#7675]
### What 
Hello, I'm unable to verify the Twitter for my grant (Kchannels - https://www.kchannels.io/ )

https://gitcoin.co/grants/1429/kchannels

There are no instructions (or no button?) to send out a tweet, so I'm not sure what to do at Step 2.

`Step 2: Click to send the verification tweet from the grant account (@kchannelsio)`

So when I click on "Verify", I get an error because no tweet has been sent.

I am using Firefox.

**Comment by octavioamu** [comment]
you need to share the tweet with kchannelsio twitter account then press verify.
