### ISSUE TITLE
Issue with Gitcoin Grant Application Submission Form

### ISSUE THREAD

**Issue by gokulsan** [gitcoinco/web#7687]
**Describe the bug**

Unable to submit the Gitcoin Grant Submission Form

**To Reproduce**

Issue is in the following form submission 
https://gitcoin.co/grants/matic/new

**Expected behavior**

Expected to proceed to the submission page

**Screenshots**

[(https://drive.google.com/file/d/1kuxUR3rbdkel2pgwtC8LX28sP2QUQvcN/view?usp=sharing)]

![Gitcoin_GrantApplicationForm_Issue_2020Oct](https://user-images.githubusercontent.com/4141694/96224232-dd81e080-0fac-11eb-9cef-bc5e98e27e6c.png)

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Safari
- Browser Version:

**Additional context**

**Comment by thelostone-mc** [comment]
Could you try and let us know if there are any errors in console ?
