### ISSUE TITLE
Feature Grant/telegram

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/web#7688]
### I want to reach out the owner of a grant quickly, via telegram.

 (As a community manager, I want to ping grant owners for general reachouts.)

### Description

Asking grant creator for telegram id, which should be visible on grant page later. So, reaching out to grant creator is easy.
*Type*:

**Comment by thelostone-mc** [comment]
Q for product : 
- would grant creators be alright with this data being shown publically?
- grant creators already add in their twitter handles -> wouldn't that suffice?
- additionally, we do have gitcoin chat/discord 

I'm trying to understand the need for us to 
- create a new data field in the DB
- adding an extra field for the grant owner while creating a grant

**Comment by thesachinmittal** [comment]
Answers to @thelostone-mc 

* would grant creators be alright with this data being shown publicly?
- We can keep it optional

* grant creators already add in their twitter handles -> wouldn't that suffice?
- people generally dont use twitter DMs

* additionally, we do have gitcoin chat/discord
- people dont use gitcoin DM, how can I contact through discord?

### Need for doing it?

* Request from Matic (Sponsor)
* If we can make the reachouts easier, it will give greater exposure to projects.

**Comment by thelostone-mc** [comment]
> We can keep it optional

I'd say sync up and figure out if we need that.
I still think having this exposed to isn't smart cause folks might get spammed.
I'd lean towards collecting this info and then sending it out to sponsor on need to need basis

**Comment by thelostone-mc** [comment]
@thesachinmittal ^ 

Also question for you over here
https://github.com/gitcoinco/web/pull/7820#discussion_r520528510

If you can help us clarify on this -> we can rework the PR and get it in.
Will keep it open until then 🙌

**Comment by thesachinmittal** [comment]
>I'd say we should sync up with product and figure out if we need that.
I still think having this exposed to isn't smart cause folks might get spammed.
I'd lean towards collecting this info and then sending it out to sponsor on need to need basis

Totally, Can we discuss this in the next product sync @PixelantDesign ?
