### ISSUE TITLE
Clone/ Fork the Project

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/web#7690]
### User Story

As a user, I want to clone a project created by another user. 

### Why Is this Needed

Avoid reinventing the wheel, and letting devs with ideas to experiment freely by cloning/forking projects they want to work further on. 

### Inspiration

![image](https://user-images.githubusercontent.com/22838732/96260312-809e1e80-0fdc-11eb-95ae-1d8f7103e623.png)

### Benefits
It increases engagement and gives meaning to the projects hosted on Gitcoin.

**Comment by PixelantDesign** [comment]
Cool idea! It would be nice to have a GIVE BACK button - to share some winnings/tip for allowing to use the idea!

**Comment by octavioamu** [comment]
we had some problems on the past on users copying others submissions on hackathons and submitting as their own ideas, I wouldn't encourage that, the main idea of a project is to be original on the proposal.

**Comment by thesachinmittal** [comment]
@octavioamu this feature will be only applicable to **Showcase Projects.**

For projects in WIP, we will not encourage this.
