### ISSUE TITLE
Subit work error for non integer hours worked. ".5"

### ISSUE THREAD

**Issue by NukeManDan** [gitcoinco/web#7695]
**Describe the bug**
On submitting work I get a very non-intuitive error: "Unable to fulfill bounty. Please try again later" as a popup when all fields are completed. 

I stumbled around trying to figure the issue out, and only **after looking in the console did I find a hint**:
`error: bounty fulfilment failed with status: 400 and message: error: missing hoursWorked`

I tried again with "1" for hours, and it processed fine. 

**To Reproduce**
1. submit work for bounty with all fields complete, hours worked as non integer (with no leading 0 -- ".5"

**Expected behavior**
non-integer values for time worked actually work, or user MUST bet an error message in GUI that makes sense. 
(could be I needed a leading 0?)

**Comment by rpruizc** [comment]
I believe it's not about a leading zero, but a non-integer number. In my case, I got the same error while using '2.5'

**Comment by octavioamu** [comment]
Thanks for the report, should be fixed now, let me know if not.

**Comment by NukeManDan** [comment]
worked for a different submission - thanks @octavioamu 🙇🏼
