### ISSUE TITLE
Email heading messed up on mobile resolutions

### ISSUE THREAD

**Issue by rajatkapoor** [gitcoinco/web#77]
The email heading stating "New Funded Issue Alert" is messed up on mobile resolutions
![screenshot_20171205-005226](https://user-images.githubusercontent.com/1975189/33571702-e282610c-d956-11e7-905b-fae04c072010.jpg)

**Comment by owocki** [comment]
should fix this 013fdd6b8927ae3db317b9264f57bc6e3af6359a
