### ISSUE TITLE
do we want to fold Gitcoin Universe into the Issue Explorer?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#770]
gitcoin.co/universe
gitcoin.co/explorer

do we want to fold Gitcoin Universe into the Issue Explorer?

# pros
1. one interface to send bounty hunters to
2. we could add a radio dialogue to the left sidebar allowing users to toggle bounty type

# cons
1. does having the universe bounties on the same explorer as the on-chain bounties dillute the on-chain bounties?

**Comment by owocki** [comment]
@PixelantDesign @mbeylin @vs77bb curious if you have any thoughts here

**Comment by thelostone-mc** [comment]
A unified Issue Explorer with powerful filters would be soo much more easier !
Jumping between explorers is something which I did not enjoy as a user

> does having the universe bounties on the same explorer as the on-chain bounties dilute the on-chain bounties?

As of now -> we've got the gitcoin/universe which looks very different from the issue explorer but at it's core does the exact same thing 

This means  -> Less maintenance + new features don't need to be replicated on both pages

We could easily add a way identify off chain bounties if needed ( something subtle ) along with the search filters

**Comment by mbeacom** [comment]
I agree that external bounties should be handled in the same manner as internal bounties. The current state is a bit jarring.  A visual identifier associated with external bounties would probably make the most sense.  This would allow the user to discern between internal vs external.  I think it's a step towards making browsing bounties less cumbersome and might unify the experience a little better than the separate implementations and designs.

**Comment by PixelantDesign** [comment]
As noted by above comments, I agree that the visual differences between the two products is an obvious one that needs to be reconciled.

My question would be, what does off chain bounties solve for our users (if they are here to build skills and develop on web3). I wonder of the two together would be distracting/competing?

**Comment by vs77bb** [comment]
I also tend to agree... though integrating it with our explorer is probably non-trivial, eh? It doesn't seem easy to track external bounties through stages from 'Open' --> 'Work Done' in our same format. 

Perhaps we start by including the external bounties **only** during the 'Open' state? That, plus @mbeacom's suggested visual identifier / perhaps a checkbox filter so people can choose to keep the external bounties / remove them from their view?

**Comment by owocki** [comment]
> My question would be, what does off chain bounties solve for our users (if they are here to build skills and develop on web3). 

it gives them access to 100x more bounties than are available on the bounties network / standard bounties.

it makes gitcoin the one stop shop for searching for bounties.. like searching kayak.com instead of southwest.com and united.com and frontier.com, but for bounties instead of airlines.

> I wonder of the two together would be distracting/competing?

its certainly a customer communication challenge

**Comment by vs77bb** [comment]
I think the trickiest part isn't posting it, but having our brand associated with fulfillment. Ultimately, if we do this, I think it should be **only** at the end of the open section as an MVP... perhaps separated by a divider? And we don't follow the bounty through fulfillment, just send the hunter to the appropriate website. 👇🏼


![kapture 2018-04-04 at 22 07 25](https://user-images.githubusercontent.com/23297747/38345432-c7caa2b8-3854-11e8-848a-d7969a7efcf9.gif)

**Comment by PixelantDesign** [comment]
Another way to decide could be to create a quick survey to see if users want this in the explorer.
