### ISSUE TITLE
Self Service Hacks Stories

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7707]
### User Story

As a Gitcoin Hackathon customer, I'd like to be able to do basic set up and management myself because the platform should be easy to figure out.

As a Hackathon operator, we need a way to allow customers to manage their own hackathons from start to finish with limited interaction from hack ops in order to scale.

### Why Is this Needed

- Parts of the customer flow have been designed to be self serve. We'd like to make all of it self serve.
- We would like to scale.

### Description/User Stories

- How do organizations manage their teams on Gitcoin
- How do organizations opt into self service?
- How do organizations manage self service/settings?
- How do organizations learn about how this all works?
**P0** [- How do organization set a start/end date of their hackathon and details?](https://github.com/gitcoinco/web/issues/7761)
- How do organizations specify details of their hackathon + brand mgmt?
- How do organizations get their prizes up?
- How do organizations encourage ensure quality hackers will join?
**P0** - [How do organizations announce/promote the start of their hackathons?
](https://github.com/gitcoinco/web/issues/7762) (Email communication throughout the event.)
- How do orgnizatons monitor and stay up to date on their Hackathons?
**P0** [- How do organizations set up events/office hours?](https://github.com/gitcoinco/web/issues/7763)
- How do organizations manage payout?
- How do organizations announce winners/complete showcase?
- How do organizations get hackers to come back for future hacks?
- How do we set up organizations to take hack projects to the next stage?

### Current Behavior
Limited self service features

### Expected Behavior
Full self service hackathon

### Definition of Done

- [ ] Identify user stories needed for an end-to-end self service hackathon experience.
- [ ] Identify squad members/interested contributors
- [ ] Brainstorm/concept test Ideas 
- [ ] User test
- [ ] Create final designs & specs
- [ ] Plan tracking
- [ ] Create build tickets

### Data Requirements

- Hack ops time saved
- Happy customers using self service features
- Increase NPS

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by thesachinmittal** [comment]
Shouldn't we set up a user guide or something? We can host this on Circle which will be much easier to manage. And we can simplify the onboarding using Airtable forms.

**Comment by PixelantDesign** [comment]
P0 - How do organization set a start/end date of their hackathon and details?
P0 - How do organizations announce/promote the start of their hackathons?
(Email communication throughout the event.)
P0 - How do organizations set up events/office hours?

Per conversation with @danlipert we are able to move forward on the above tickets without organization setup. cc @thelostone-mc @octavioamu

**Comment by danlipert** [comment]
Let me know why this is a bad idea @thelostone-mc @octavioamu seems fine to me
