### ISSUE TITLE
zcash fixes

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#7715]
- cart
  - ethereum tab
    - - [x] show the right total
    - - [x] check the ethereum checkout
    - - [x] on payout remove only ethereum grants
  - zcash tab
    - - [x] disable button when is done
    - - [x] ui small fixes based on states
    - - [x] Populate right tokens
    - - [x] clr matchings tokens and value
- index 
  - - [x] populate the right tokens on side cart
  - - [x] show the right clr data
  - - [x] ensure contributor count + amount is updated
  - - [x] test CLR flow
  - - [x] remove apply all
- form
  - - [x] add teams
  - - [x] validate if categories
  - - [x] disable submit

**Comment by mds1** [comment]
- [ ] Successful Ethereum checkout clears Zcash grants also
