### ISSUE TITLE
chat consolidation product work

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7720]
1. remove gitcoin chat from the site, and in general
2. retire the gitcoin community slack
3. go all in on discord again + have yalor spearhead it. 
4. retire telegram chat
5. bring back the ‘enter your discord handle when you start work/signup’ featture

**Comment by thesachinmittal** [comment]
This is awesome, related ticket on Types of interaction in Gitcoin: https://github.com/gitcoinco/web/issues/7709
cc: @disruptionjoe

**Comment by owocki** [comment]
@connoroday @Solexplorer @disruptionjoe @vs77bb @ceresstation any feedback?

**Comment by octavioamu** [comment]
do we need dms there or we want to try dms on discord? IMO I prefere to centralize everything in one place.

**Comment by PixelantDesign** [comment]
6. update sponsor dashboard chat icon to dm the person who started work instead of the whole group.

<img width="396" alt="Screen Shot 2020-11-02 at 8 27 09 PM" src="https://user-images.githubusercontent.com/238235/97936725-730dc600-1d4a-11eb-9dd8-a60cc22dfeda.png">

**Comment by PixelantDesign** [comment]
@danlipert are we able to turn #5 back on or do we need a design?

**Comment by danlipert** [comment]
I don't think we need a design @PixelantDesign

**Comment by ceresstation** [comment]
@danlipert @thelostone-mc do you think we can remove Telegram from the footer by EOW?

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/7856

**Comment by danlipert** [comment]
@ceresstation removed here: https://github.com/gitcoinco/web/commit/d4c72d6eb45840a67b037d8bc22f5f74819b9c57 will go out in next deploy
