### ISSUE TITLE
Grant Detail Clean Up

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7726]
### User Story

As a grant donor, I'd like a page that is easy to understand so that I can see the information I need to make decisions on whether I should fund a grant

As a grantee, I'd like a page that is clean/tidy so that I can build trust with the community and properly represent my project.

As an operator of Gitcoin Grants, I'd like a cleaned up grant detail page for consistency as it builds trust with users.

### Why Is this Needed

This page has been iterated on by many people. It's time for  clean up.

### Description

Design refresh of grant detail 

### Current Behavior
Existing grants detail

### Expected Behavior
Updated per mockups

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- [ ] Decide on areas to improve for R8
- [ ] Update any outstanding ux
- [ ] Get these into Vue components where it makes sense
- [ ] Build it

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

<img width="1610" alt="Screen Shot 2020-10-21 at 8 44 53 AM" src="https://user-images.githubusercontent.com/238235/96721196-c7dc3480-1379-11eb-99dd-dcb37a3e00db.png">

<img width="1607" alt="Screen Shot 2020-10-21 at 8 45 06 AM" src="https://user-images.githubusercontent.com/238235/96721207-cc085200-1379-11eb-9b9a-a91914b94560.png">

<img width="826" alt="Screen Shot 2020-10-21 at 8 31 01 AM" src="https://user-images.githubusercontent.com/238235/96719738-cf024300-1377-11eb-96c2-c74a524ac5ca.png">

**Comment by wildmolasses** [comment]
Can you assign this to me? :)

**Comment by thelostone-mc** [comment]
A few things to keep track of : 

- rewrite page in vue 
- remove inline-edit and shift to modal
- ensure cancel grant works as expected 
- update as per new design layout
