### ISSUE TITLE
No unsupported network alert on bounty funding

### ISSUE THREAD

**Issue by Korridzy** [gitcoinco/web#773]
*Type*: Bug

### Current Behavior
In case metamask is switched on unsupported network (e. g. ropsten) user can see a red alert in upper-left corner of Issue Explorer page or Issue Details page. But on Tools -> Fund Issue there are no any tests if the network supported. When user fills NewBounty form and pushes "Fund Issue" button the page is just reloading without any messages. So for user it looks like he can't fund for some unknown mystical reason.

### Expected Behavior
Probably the same unsupported network alert need to be added on Fund Issue page. Or at least an error message after submitting the form.

**Comment by mkosowsk** [comment]
Interesting find, I attempted to fund this issue (fan of meta 😂) via Tools -> Fund Work while connected to the Rinkeby Test Net.

![gitcoin co_funding_new](https://user-images.githubusercontent.com/7970539/38223414-c1f7980c-36b8-11e8-9140-e7e58bee8ca9.png)

It looks like the transaction actually went through:

![gitcoin co_funding_details__url https___github com_gitcoinco_web_issues_773](https://user-images.githubusercontent.com/7970539/38223436-e46d3842-36b8-11e8-945c-e997a7217edc.png)

But issue cannot be found on Explorer:

![gitcoin co_funding_new](https://user-images.githubusercontent.com/7970539/38223443-f0cc9baa-36b8-11e8-973c-d4adff818cc8.png)

Beyond testing in Development, is there a reason for a User to be able to fund an issue if he or she is connected to Rinkeby Test Net? @owocki @mbeacom @thelostone-mc

**Comment by thelostone-mc** [comment]
I don't think so! I've used it only in the dev environment !

**Comment by Korridzy** [comment]
@mkosowsk There is no issue in explorer in your case because of auto 'mainnet' filter. It looks like good enough solution for real usage.

**Comment by mbeacom** [comment]
We've been discussing limiting the live environment to only allow the creation of `mainnet` bounties, but as it sits currently, that's not the case.

@owocki Think we should pull the trigger on this and limit bounty creation to environment specific networks?

**Comment by owocki** [comment]
its worth a conversation... I can't say I have a strong opinion one way or another.. maybe worth a convo in the architecture weekly or the priv-contributes channel?

**Comment by mkosowsk** [comment]
Per @mbeacom in the Slack

> @here Would anyone like to weigh in on the conversation at: https://github.com/gitcoinco/web/issues/773 ? Specifically, the question:  `Think we should pull the trigger on this and limit bounty creation to environment specific networks?` - For example, if you're browsing `https://stage.gitcoin.co`, you would be able to create `Rinkeby` bounties only. Whereas `https://gitcoin.co` would only allow you to create bounties for `mainnet` and `local` would allow either anything or `testrpc` and `rinkeby`.

I give a 👍 to this... even Ethereum pros like @owocki have burned ETH on testnets, and I was confused why I could seemingly fund an issue Production via Rinkeby even tho it didn't go through. Think it's best to put the guardrails up in different environments to limit confusion for **Users** :)

**Comment by eswarasai** [comment]
@mkosowsk -- Is the reason behind you couldn't find the issue on the explorer is due to the `mainnet` filter already applied on top of your search text? Probably the created issue is attached to `rinkeby` network filter maybe?

Either way, definitely funding of an issue on production should be restricted to `mainnet`. It doesn't make sense to support testnets on production environment.

@mbeacom -- I do agree with your proposed solution for having environment specific network. At the same time, we also need to check the domain url so that, if I run gitcoin on local with `env=production` but on `localhost:8000`, I'd still be using testnet and not the mainnet. I'm sure you might've already thought about this. Just wanted to highlight this as well.

**Comment by mkosowsk** [comment]
@eswarasai I think that was probably the case, had the filter applied and didn't realize it 😂

**Comment by owocki** [comment]
i fixed this

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.01 ETH (6.92 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/773/565).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
