### ISSUE TITLE
Vitalik vision for round 8

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7732]
Some quick ideas on what we could do for round 8:

*Have two major categories, "tech" and "community". ( # 7745 )
* Within "tech", have any subdivisions be just a UI layer, so it's all just one big lump of things. That is, from an economic standpoint the subdivisions are collections, from a UI standpoint the subdivisions are categories, if that makes sense.
* Within community, have a hard split: 1/2 "general", 1/2 "regional", split equally between: North Am + Oceania, Lat Am, Europe, Africa, Central Asia, East Asia, Southeast Asia
* Try to make it more egalitarian at the top by changing the shuffling algorithm so that once a project gets over $5000 matching, from a shuffling PoV it's treated as though it has just $5000 matching

**Comment by owocki** [comment]
per call today; further work needed to massage this into an actual product spec

**Comment by thelostone-mc** [comment]
Closing this out as it's been broken down into smaller tickets
