### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by nandit123** [gitcoinco/web#7739]
### What 
I am unable to verify the grant for twitter account, i am stuck on step 2 (Click to send the verification tweet from the grant account (nanditmehra) . There is no button to click. 
Grant link - https://gitcoin.co/grants/1419/byte-box

**Comment by owocki** [comment]
@zoek1 there are a handful of twitter verification issues on the issue board. could you look into them pls?

@nandit123 could you give a screencap?  are there any errors in your console?

**Comment by nandit123** [comment]
Hi  I am able to do it on chrome, had problem on firefox as a script wasnt loading there
