### ISSUE TITLE
ZEC contribution feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7741]
looking at this page rn and typing this up: https://bits.owocki.com/7Ku8Q510

how can i be sure my contribution went through?  

from a UX standpoint; do we want to do any of the normal things we did in the EF round?
1. clear cart, show user the viral modal to encourage them to share
2. ~increment/update match amount~
3. ~i didnt get a confirmation email (and it looks like the grant owner didnt either) and there is no new activity feed item on https://gitcoin.co/grants/1465/first-zcash-grant~
4. ~(are the clr estimates even running for ZEC round rn? should we start them so we can verify its working?~
5. ~my contribtuion is not marked as 'success' in the db https://gitcoin.co/_administrationgrants/contribution/49855/change/~

**Comment by owocki** [comment]
ETH checkout regresssions after ZEC deploy.

<img width="1836" alt="Screen Shot 2020-10-22 at 10 56 36 AM" src="https://user-images.githubusercontent.com/513929/96905137-4bb71f00-1455-11eb-87d5-08d44a7d0049.png">
 'apply to all' button no longer works 

standard checkout no longer works
<img width="1890" alt="Screen Shot 2020-10-22 at 10 57 24 AM" src="https://user-images.githubusercontent.com/513929/96905199-638ea300-1455-11eb-92fd-cecdc655d704.png">

why is the system logging a bunch of info about USDT when i only have DAI in my grants cart?
<img width="1886" alt="Screen Shot 2020-10-22 at 10 57 54 AM" src="https://user-images.githubusercontent.com/513929/96905271-7903cd00-1455-11eb-8f54-e5466ee9db2f.png">

**Comment by owocki** [comment]
ok i restarted my browser and i can checkout again with standard checkout (the apply to all button no longer works still tho)

**Comment by thelostone-mc** [comment]
> (are the clr estimates even running for ZEC round rn? should we start them so we can verify its working?

They aren't ! I've checked it in local a few time so I'm confident it in working but defer to @danlipert / @octavioamu

**Comment by owocki** [comment]
```
zcash community (electric coin company) feedback:
- how do we do the matching of the zcash t-address with the transaction?  daira hopwood from the zcash community has this question. they suggest using the txid instead of the account address.  "this solves two problems, it solves the de-shielding problem for funding from z-addresses, and it solves the "which t-address did this come from"" question
- UI should let u know u cant put a z-addr in there.
- they are pretty privacy conscious; would like an option to not show the grant contribution identity publicly, so we dont dox / do a timing attack.
- they wnat the ability to fund via ETH (in addition to ZCash).  "can we allow people with ETH to checkout?"
- disable SMS numers for zcash round (they said "maybe" they want to do it.
- allow anyone to create a zcash grant; not just anyone through a secret link
```

**Comment by owocki** [comment]
https://bits.owocki.com/ApuLeGmG

'apply to all' messes up the ZEC grants contributions so that they turn to ETH / a random number
