### ISSUE TITLE
chore: Fix (or majorly triage) the issue where the system doesnt know about a contribution + we have to manually ingest them.

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7744]
#### Description 

**Part1**
As the title states, figure out root cause and fix up missing contributions so as to avoid manual adding them in db

@mds1 

**Part2**

See if UI/UX improves needed now that for bulks checkout we move user to zksync site 

sample app which does it:
https://zksync.curve.fi/

**Comment by mds1** [comment]
1. Latest status in this thread: https://gitcoincore.slack.com/archives/C01FQV4FX4J/p1607993366053700
2. Next step: Can we check Round 7 sentry logs and see if `network=undefined` was also the reason for those failures?
3. If so, is it safe to assume that was the original cause? If so:
    1. Move JSON store backups to occur after the save contribution POST request, and configure all frontend requests to retry on failure
    2. Determine why `network=undefined` even though user is able to checkout
4. If we can’t get to the root of it, build an admin panel so others can handle manual ingestion

**Comment by mds1** [comment]
In the round 9 project board @owocki created a note that duplicated this issue. I deleted that note and am pasting the text here for reference:

> Dont lose contributions anymore.
> 
> Either (1) ask people their specs / reproduction conditions across all the existing tickets and actually figure out the root cause or (2) make an admin panel that anyone (not just kevin) can ingest contributions that we failed to capture.
