### ISSUE TITLE
feat: auto-fill grant/new form

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7746]
#### Description

- prefill grant type and grant subtype via URL as shown below http://gitcoin.co/grants/new?category=matic&subcategory=test&clr=matic
 - - category -> what populates the category field
- - subcategory -> what populates the subcategory field (this can be an array)
- - chain (selects which chain to prefill -> ETH / Zcash)

---
For showing a custom logo on grant creation form
- Add an image field to Grant Type model
- The logo on the grant creation form should change based on the category set (If logo is not available -> use default logo)

---

- [ ] Design
- [ ] Development

**Comment by willsputra** [comment]
>category -> what populates the category field
subcategory -> what populates the subcategory field (this can be an array)

1. Would users be able to override this? Might be confusing if we're displaying a specific Grant CLR logo/header at the top and then let users change the defaults.
2. Would chain info be prefilled too?

**Comment by thelostone-mc** [comment]
> Would users be able to override this? Might be confusing if we're displaying a specific Grant CLR logo/header at the top and then let users change the defaults.

I think we can update them based on the selection!
Defer to you on this though

> Would chain info be prefilled too?
Updated this as well

**Comment by aamustapha** [comment]
Cool

**Comment by aamustapha** [comment]
- [ ] Allow autofill input fields
- [ ] Allow autofill radio
- [ ] Allow autofill select 
- [ ] Allow autofill select multiple
- [ ] Allow autofill image

**Comment by aamustapha** [comment]
>clr -> pk for Grant CLR (this will be used to add a logo instead at the top of the form)
@thelostone-mc can you please explain this a little better?

**Comment by thelostone-mc** [comment]
I think we cleared this up on the call but will drop it here as well!

- [ ] Add a image field to Grant Type which an admin can set image via django admin
- [ ] When the grant create page loads, fetch all the GrantType Banners along with it 
- [ ] If a grant type is auto filled/ user selects the grant type  which has a GrantType banner -> switch the default image on the form. If it doesn't -> show the default image

Reason being : when you load gitcoin.co/grants/new?type=matic
sponsor would want their logo to show up on the form as form of marketing / advertisement

**Comment by aamustapha** [comment]
All these are already implemented.
