### ISSUE TITLE
chore: send mail only when contribution is successful

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7748]
#### Description

ensure successful contribution mail is sent to user only after the contribution has cleared in DB

This has been done for zcash!

Discuss with  @mds1 + @owocki before building

**Comment by owocki** [comment]
kewl i see you assigned me on this one.  let me know what you need from me!

**Comment by mds1** [comment]
@apbendi can help out here if needed

**Comment by thelostone-mc** [comment]
I think we would not want to this cause we wanted to revert this behavior in zcash 
based on the conversation on slack with @owocki 

Will bring this up on call and we can close it out after that

**Comment by owocki** [comment]
IMO a optimistic UX is better than a pessimistic one; but something in the middle that manages the state from `cart -> pending -> success/fail` would be even better. can jam on the weekly checkin if you want

**Comment by thelostone-mc** [comment]
Closing this out as we are happy with what we have
