### ISSUE TITLE
feat: redo grant landing page

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7749]
#### Description 

When you switch from one category to another on the left sidebar -> 
If you are on tech category tab and switch to matic category -> the banner + grants should update without a page reload

The grants already are AJAX calls so the data is already present.
Just need to ensure the banners on the top also update as a user switches

This means you would have to fetch all the banners upfront to allow loading the right banner 
cc @octavioamu for more questions  

Also the sync up with @owocki / @PixelantDesign on what the banners are and get them added as well

**Comment by willsputra** [comment]
> Revisit Left sidebar to show only CLR instead of Grant Type

to include in spec: what happens when there's no active CLR round?

**Comment by PixelantDesign** [comment]
https://www.figma.com/file/GUnBaAsN9k6XQi5RNHnxyK/Grants-R8?node-id=10%3A12

**Comment by thelostone-mc** [comment]
> to include in spec: what happens when there's no active CLR round?


that would be empty (we wouldn't show anything)

**Comment by thelostone-mc** [comment]
Closing this out and moving it to #7781
