### ISSUE TITLE
document: how to maxmize (blog/wiki)

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7753]
#### Description 

people reach out to me at the start of the round to ask how they can maximize their grant, and we dont have a "how to promtoe your grant" guide to give them. as a result, people who have played the game the longest + have insider knowledge rise to the top.

#### Steps

- Prepare document
- Preferably add it to a blog 
- Design an email with a blog link to when Grant is created mail

(@zoek1 the last one is piece where a code change would be needed )

**Comment by thelostone-mc** [comment]
@owocki we will be using blog as opposed to pdf cause it's easier to add in updates

**Comment by owocki** [comment]
![jb268vM](https://user-images.githubusercontent.com/513929/97464769-f07aa600-1906-11eb-80d1-53175a273dcd.gif)

**Comment by PixelantDesign** [comment]
https://docs.google.com/document/d/1II6IaPYL0RcP5Ilq2nd2A41r3_hnH297B3MkO2VXiok/edit?usp=sharing

**Comment by frankchen07** [comment]
dope, commented. HMU if you need any copy surrounding how QF works, or if you need a proofreader

**Comment by nglglhtr** [comment]
@frankchen07 can you proof-read the content in the above link, I updated a few things!
