### ISSUE TITLE
Consolidate emails so that user who checks out gets only 1 email not n emails for n contributions.

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#7755]
@apbendi will tackle this one

**Comment by apbendi** [comment]
@corydickson is going to take a pass at this issue. I've brought him up to speed on the context and the task at hand!

**Comment by owocki** [comment]
@apbendi @thelostone-mc @corydickson r u all aware of this one? https://github.com/gitcoinco/web/pull/7567

**Comment by corydickson** [comment]
I was not 😬 maybe we can converge on some changes. Since this other PR has styling changes, we may just want to make sure the celery task that processes the grant is successful before kicking off the email job.

**Comment by mds1** [comment]
I could be wrong, but if I recall correctly this issue is not complete, so I'm reopening it and adding to the grants round 9 scope
