### ISSUE TITLE
Cannot register for a Matic grant. The submit button leads to a "Grant failed to save" error.

### ISSUE THREAD

**Issue by porobov** [gitcoinco/web#7759]
**Describe the bug**
I'm trying to register for a Matic grant. After I press "Register your DApp" button I get an alert asking to triple check the provided ethereum adders. After clicking OK nothing happens. **Console shows a "Grant failed to save" error.**

**To Reproduce**
1. Go to https://gitcoin.co/grants/matic/new
2. Fill all the fields
3. Press "Register your DApp" button
4. Press OK in the alert window.
5. Console shows a "Grant failed to save" error.

**Expected behavior**
Should confirm successful registration.

**Screenshots**
![screenshot](https://i.imgur.com/dtfvqQK.png)
![console](https://i.imgur.com/h0c0Sva.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 18
- Browser: Chrome, Brave
- Browser Version: Latest

**Comment by foxreymann** [comment]
My team faces the same issue. I could paste exactly the same screenshot.

Error we get from POST HTTP call is:

`{"status": 400, "message": "error: eth_payout_address/zcash_payout_address is a mandatory parameter"}`

**Comment by danlipert** [comment]
@porobov @foxreymann Thanks for the bug report, I've just released a fix for the issue so please try again and let me know if you encounter the same or any other issues. Thanks!

**Comment by foxreymann** [comment]
@danlipert works now. thank you!

**Comment by porobov** [comment]
@danlipert yep, works for me as well.
