### ISSUE TITLE
Allow Organizations to Set Hackathon Start and End Date

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7761]
### User Story

As a Gitcoin Hackathon customer, I'd like to be able to set my own start and end date for a hackathon.

### Why Is this Needed

Sponsors should be able to do this in order for our platform to become self service.

### Description

To move towards a self service model, we will create the hackathon but allow sponsors to select start and end dates of the hackathon.

### Current Behavior
No ability to do this

### Expected Behavior
Sponsors are able to create start and end dates

### Definition of Done

- [ ] Document business rules around this
- [ ] Create an ux for this
- [ ] Share with a sponsor for feedback
- [ ] Iterate & Build

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
Seems fine to me - wherever this lives will probably be the new start of a "hackathon configuration" page thats user-facing, so we should plan for this design to be extendable from this feature forward rather than jam this control on the hackathon page.
