### ISSUE TITLE
Allow organizations to do in app promotion of a hackathon to developers

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7762]
### User Story

As a Gitcoin Hackathon customer, How do organizations announce/promote the start of their hackathons?

### Why Is this Needed

Our customers have mentioned competitors allow emailing of hackers in app (since we do not want to share emails). In order to maintain competitive edge, this is something we should consider.

### Description
Create a way for customers to be able to send in app emails to market their hackathons to hackers.

### Current Behavior
No way to do this

### Expected Behavior
Allow customers to do this

### Definition of Done

- [ ] Discuss with team
- [ ] Concept test
- [ ] Design
- [ ] Build

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
Yup good idea in general. I think we can stick with plain text for now where we provide a generic template with sponsor/hackathon logo and header, and the hackathon org can put whatever they want for the email Subject and Body Text

**Comment by PixelantDesign** [comment]
Thanks @danlipert! Is there an open source in app messaging plugin we should try to use? Or should we try to build this in on User Directory @owocki ?

**Comment by danlipert** [comment]
Nah we'll just create the form ourselves I think.
