### ISSUE TITLE
Allow Customers to Set up Events

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7763]
### User Story

As a Hackathon Customer, I'd like to be able to set up and manage events/office hours related to my prizes.

As a Gitcoin Hacakthon operator, I'd like to free up some of Connor's time so that he can focus on other areas of the hackathon.

### Why Is this Needed

To move towards a self service model, we'd like to allow a way for customers to do this.

*Summary*:

Create a way for customers to doo this

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Gitcoin core team creates events (see events V1)

### Expected Behavior
Customer is able to create an event

### Definition of Done

- [ ] Understand business rules/document
- [ ] Concept test new experience
- [ ] Share with customer for feedback
- [ ] Iterate/Build

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by danlipert** [comment]
This ticket implies that we will connect with the event service we are currently using? I can't remember the name of the service but I remember looking at the API for an integration like this several weeks back.
