### ISSUE TITLE
BUILD - Submit n Number of Projects Per Person per Prize

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7772]
### User Story

As a sponsor of a Gitcoin Hackathon, I'd like to maximize the number of ideas that I'm able to receive from a hacakthon participant. 

### Why Is this Needed

**Customer Request**

"We don't want to restrict a developer to a single idea - if they have multiple ideas they want to build we want to encourage that - the more the better"  --Manasi at Nebulous Labs/Sia:

As a hackathon participant, I'd like to be able to submit many ideas per prize.

Related: https://github.com/gitcoinco/web/issues/7180

### Description

This enhancement will allow hackers to create multiple projects per hackathon prize keeping the same bounty business rules.

### Why
Hackathon customers care about all ideas regardless of code completion state.

### Definition of Done

- [x] Start Work - No Change to button behavior or display
- [x] Start Work - Once a hacker has started work, **Add Another Project** Button should display next to Stop Work.
- [x] Start Work - When more than one project has started, display the projects nested under the hacker. General layout /display will need to change to accommodate ability to nest projects. (see mockup)
- [x] Start Work - Applicants Section - Include wallet information for the person who started work (see mockup)
- [x] Start Work - Applicant's Section - Modify the current project card displayed on issue details to follow the mockup attached.
- [x] Start Work - Applicant's Section - If a user starts another project days later, nest it with the first project and record time stamp.
- [x] Start Work - For the hacker that started the project  display **edit details** (takes user to edit the project form) and **view project** (takes user to see the project details) button on project card.
- [x] Start Work - Applicants Section - For any roles other than the person who started work, they should only see the View Project button.
- [x] Start Work - Applicant's Section - Each time a project is added, the user should see the project confirmation notification at the top of the screen. Follow existing paradigm.

- [x] Stop Work - Display tooltip that stop work stops all projects (see mockup)
- [x] Stop Work - No change to activity section treatment

- [x] Submit Work - Submitt work button should display tooltip on hover describing that submit work submits all projects. (see mockup)
- [x] Submit Work -  Allow submit work only once, but user is able to submit **multiple project per prize per person** on Submit Work form (see mockup)
- [x] Submit Work - Update submission section and allow edit submission on **issue details** (see mockup)
- [ ] Submit Work - Add ability to remove a pr on pr submission view on issue details.
- [ ] Submit Work Form - Display a blank pr form field per project start.  (see last mockup)
- [ ] Update **submitted work email** to show multiple submissions make dynamic based on count.
- [x] Sponsor Hackathon sponsor submission view no change, but please show multiple entries by the same person.
- [x] Remove Projects Section at the bottom of the current issue details and combine with then Applicants. (see mockup)
- [x] Follow current responsive grid

- [ ] Tooltip - use same tooltip from the project form.

- [ ] Show off how each part of the spec is reflected in the PR/demo video

### Current Behavior
Hackers are able to submit one project per person, per prize

### Expected Behavior
Hackers are able to submit many projects, per person, per prize

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

## **Show one submit work with tooltip**
<img width="1241" alt="Screen Shot 2020-10-26 at 2 51 06 PM" src="https://user-images.githubusercontent.com/238235/97215572-ff444a00-179a-11eb-94ea-827eeba1a958.png">

## Show one stop work with tooltip 
<img width="1263" alt="Screen Shot 2020-10-26 at 2 50 55 PM" src="https://user-images.githubusercontent.com/238235/97215510-eb004d00-179a-11eb-9e19-bb33cc40a441.png">

## **Show nested projects per start work**
<img width="1481" alt="Screen Shot 2020-10-26 at 2 50 21 PM" src="https://user-images.githubusercontent.com/238235/97215465-da4fd700-179a-11eb-938f-46a1f951b250.png">

## **Allow editing of the submitted work**
<img width="1169" alt="Screen Shot 2020-10-26 at 10 52 44 PM" src="https://user-images.githubusercontent.com/238235/97251357-17898880-17de-11eb-9b8e-2be3d4e15aab.png">

## **Submit Work Form**
<img width="782" alt="Screen Shot 2020-10-27 at 8 19 57 AM" src="https://user-images.githubusercontent.com/238235/97300767-44b15780-182d-11eb-8873-ff5ca2d64ead.png">

**Comment by PixelantDesign** [comment]
Should we set a max number of projects per prize to maintain quality? I'm not sure how hackers would have time to submit more than 10 projects per hackathon. What do you guys think @octavioamu @frankchen07 ?

**Comment by danlipert** [comment]
This looks pretty complex but the spec looks solid as well! Will need a lot of solid testing and documentation of that testing before it gets merged, lets make sure to show off how each part of the spec is reflected in the PR/demo video.

**Comment by PixelantDesign** [comment]
Should this be delivered in multiple prs?

**Comment by zoek1** [comment]
ETA October 16 2020

**Comment by PixelantDesign** [comment]
looking good!

**Comment by PixelantDesign** [comment]
@zoek1 could we have an ETA on this one?
