### ISSUE TITLE
Applied to single bounty two times

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7774]
Clicked Next button two times quickly, got applied two times. Should not allow apply second time.

![Screenshot from 2020-10-27 21-08-20](https://user-images.githubusercontent.com/2900574/97349842-a3f88180-1898-11eb-8886-81fd94244f6b.png)

**Comment by thelostone-mc** [comment]
This should be fixed now ! Closing this out but will reopen if it pops up again
