### ISSUE TITLE
grants: avoid reloading page  when switching btwn categories 

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7781]
#### Description 

When you switch from one category to another on the left sidebar -> 
If you are on tech category tab and switch to matic category -> the banner + grants should update without a page reload

The grants already are AJAX calls so the data is already present.
Just need to ensure the banners on the top also update as a user switches

This means you would have to fetch all the banners upfront to allow loading the right banner 
cc @octavioamu for more questions  

Also the sync up with @owocki / @PixelantDesign on what the banners are and get them added as well

![image](https://user-images.githubusercontent.com/5358146/98248624-3553ac00-1f9b-11eb-92a4-3d3e98dfbf3f.png)

https://www.figma.com/file/GUnBaAsN9k6XQi5RNHnxyK/Grants-R8?node-id=10%3A12

Include the header by category on the json request and change it based on filters without need to reload the page 

1. on the first request include json with all the banners / informations as there is an area showing the current actives clrs.
field image and some others style fields need to be added so we can remove the spaghetti here:  
![image](https://user-images.githubusercontent.com/1358093/98249559-221ded80-1f55-11eb-97f3-fb70232a6daf.png)

![image](https://user-images.githubusercontent.com/1358093/98249047-8f7d4e80-1f54-11eb-9169-b15416ca312a.png)
![image](https://user-images.githubusercontent.com/1358093/98249062-94420280-1f54-11eb-8d07-a2f20c2c9cdf.png)

2. Users on images on the last banner clr were part of the image and not from matchpledge (we are discussing what will be the best) for now just use an image.

**Comment by aamustapha** [comment]
Hey @octavioamu Have you started working on this?
