### ISSUE TITLE
video intros

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7785]
- Add the ability to do video intros 
- upload a video intro to your grant.

This should be added to both 
- Grant Creation Flow
- Grant Edit form 

---

> @owocki would video link work ?
> If not -> maybe push it to next round?
a youtube video embed is fine.

**Comment by thelostone-mc** [comment]
cc @octavioamu + @PixelantDesign who said having a video link might me cleaner as opposed to doing the whole video upload ! I agree with them on this

**Comment by owocki** [comment]
ya we dont wnat to handle video uploading/hosting. lets just use youtube

**Comment by thelostone-mc** [comment]
Use quill and enable video addition
