### ISSUE TITLE
Grants edition - Unable to change the field 'github repo link' when editing the Grant's info

### ISSUE THREAD

**Issue by levalleux-ludo** [gitcoinco/web#7788]
**Describe the bug**

I've created a Grant (for Matic Build'n Earn program).
After creation I've noticed the field 'github repo' is set to 'undefined'.
Then I was trying to change it and set the correct link to my GH repo, but when clicking 'Edit Info' button, I can't still modify this field

**To Reproduce**

Create a GRANT
Then, click 'Edit Info' and try to change github repo (should be set b default as 'undefined').

**Expected behavior**

When editing Grant's info, I shall be able to modify the field 'github repo link'

**Screenshots**

![2020-10-29 10_40_36-Window](https://user-images.githubusercontent.com/7184124/97557922-57fe2780-19d3-11eb-98c7-0cd3517edceb.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave 
- Browser Version: 1.16.68

**Smartphone (please complete the following information):**
N/A

**Additional context**

The same problem has been reported by other users.

**Comment by foxreymann** [comment]
I've exactly the game issue. It is OS/browser/project independent.
