### ISSUE TITLE
avatar_url is wrong

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#779]
https://gitcoin.co/issue/MetaMask/metamask-extension/3621
![screencapture-gitcoin-co-issue-metamask-metamask-extension-3621-2018-04-03-16_26_17](https://user-images.githubusercontent.com/513929/38279042-ced852b6-375b-11e8-8a13-1c4a6937b289.png)

The avatar at the bottom is the avatar of the github repo of the bounty, not the avatar of the bounty.

I expect that the avatar_url for the funder is the avatar of the funder, not the avatar of the bounty.

# Proposed Fix

1. Take the bounty github URL avatar and move it up top near the title
2. Show the funder avatar if available, and [this avatar](https://gitcoin.co/funding/avatar?repo=https://github.com/Self) if its not available.

**Comment by owocki** [comment]
cc @PixelantDesign and @eswarasai since i believe yall worked on the new bounty detail page... and @vs77bb since it's his smug mug that's getting replaced with the firefox fox

**Comment by thelostone-mc** [comment]
> Take the bounty github URL avatar and move it up top near the title

@owocki Did not understand this 😅 

@mbeacom  we are using `avatar_url` from the API response which brings up the orgs avatar url, is this something we need in our API ? Thoughts?

**Comment by owocki** [comment]
> @owocki Did not understand this 😅

[here is a visual mockup of what im talking about](http://bits.owocki.com/1N1001202W3q/Screen%20Shot%202018-04-04%20at%2010.41.10%20AM.png)

**Comment by thelostone-mc** [comment]
Oh :P gotcha

**Comment by vs77bb** [comment]
As cool as it would be for my head to be the MetaMask fox... I understand why we need to fix this 😆
