### ISSUE TITLE
a/b test of the sorting method on the main  page.  even pk users = weighted shuffle (which maxes the weight at $5000), odd pk users; = random shuffle (not weighted).  we'll then report the data to blockscience to see how thisi changes the rich get richer.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7792]
MZ - suggestoin - a/b test of the weighting mechanism; weighted_shuffle vs inverse weighted_shuffle

i can do this - @owocki

**Comment by thelostone-mc** [comment]
looks like this was the same as https://github.com/gitcoinco/web/issues/7822
