### ISSUE TITLE
 As a tribe owner, I want to be able to add another tribe owner to my tribe, so I can control access to my organization’s presence on Gitcoin.

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#7793]
### User Story

“As a tribe owner, I want to be able to add another tribe owner to my tribe, so I can control access to my organization’s presence on Gitcoin.”

### Why Is this Needed

Currently, we define an org/tribe’s user admins via the organization’s admins within Github. This data works well if the organization is public, but there are edge cases where an organization's membership on Github is private, the user doesn’t want to great the appropriate OAuth permissions, or a specific admin’s membership is private. In order to mitigate this cases, we will allow a tribe’s admins to select a Gitcoin user and make them an administrator. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Currently no such functionality exists. The user must go to Github and adjust the org membership there and wait for the data to sync via backend cronjob.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Ability to select any user on Gitcoin and add them as an owner to a tribe or organization.
- Ability to select one of these users and remove them as an owner to a tribe or organization.

What this DOES NOT include:

- Removing a tribe owner that is an owner because of their administrator privileges on Github.
- Mass adding of tribe owners.
- Adding Gitcoin users to my tribe in some other capacity (hacker, member) as this is determined by the users’ actions.
- An “Invite system” wherein a user that is added as an Admin has to accept this role via an email/invite management page.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Backend Changes:
- A new endpoint is added to dashboard/views.py that allows the ownership status for a given profile to be set. This endpoint takes in a profile id, organization id, and boolean to set the status for that given relationship. As such, the `profile.organizations_fk` list is set appropriately. See dashboard/views.py:users_fetch(). 

Frontend Changes:
- The user list shown at /org/people (aka the user directory) is written in Vue, and so we will add a control for each user card that allows demotion or promotion of the user to/from the tribe owner list via calling the backend method described above and updating the Vue data appropriately based on the success of calling the backend method. The page should not refresh, it should update via setting the Vue data. The promotion/demotion control should change dynamically, both visually and logically. 

### Additional Information
https://github.com/gitcoinco/web/issues/7110

**Comment by PixelantDesign** [comment]
Is this a pre-req to self service hacks? Per our convo last week, it didn't seem like a blocker.

**Comment by danlipert** [comment]
Not a pre-requisite, but I'm sure there will be at least one customer who will run into trouble trying to do self-service and unable to add the right folks on Gitcoin because of how their Github is set up
