### ISSUE TITLE
Empty page instead of a grants collection

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7813]
At https://gitcoin.co/grants/collections I click to "Science" by `vporton` and get empty page:
![Screenshot from 2020-11-03 00-00-08](https://user-images.githubusercontent.com/2900574/97923999-a448bf00-1d67-11eb-93e7-8c59235771f3.png)

**Comment by thelostone-mc** [comment]
This should be resolved by now! We had a few issues with collections during the last round
