### ISSUE TITLE
Tell Us About You Bugs

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#7816]
**Describe the bug**

**User Feedback per Scott Moore**

 "..when I just made a Gitcoin account, it was a really frustrating experience. A "tell us about yourself" popup kept coming up, but wouldn't let me click the "next" button even after I'd filled out all the details. When it popped up the seventh time or so, I entered some random info and clicked "next," and then it worked. But now I'm stuck with a profile that says "test" as my description and see no edit option to change it."

It was the "tell us about yourself" modal with activities, programming languages, and job search stuff. Providing a clear "edit" option to make changes to the profile after information is entered would also be good."

**To Reproduce**
Go to TUAY screen

**Expected behavior**

- Not have the screen pop up many times
- Be able to edit in profile

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Additional context**

**Comment by PixelantDesign** [comment]
https://github.com/gitcoinco/web/issues/7817

**Comment by Az111z2** [comment]
Azdd
