### ISSUE TITLE
As a new user, I find the new onboarding model extremely annoying, and I would like for it to show up every visit, not every pageload.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#7817]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a new user, I find the new onboarding model extremely annoying, and I would like for it to show up every visit, not every pageload.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Customer feedback

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Modal shows/ can be dismissed once per pageload

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Modal shows/ can be dismissed once per VISIT; or when user clicks it in the nav/profile completeness tab.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by nglglhtr** [comment]
Wondering if work has already been started on this? Considering taking this as a test to go through a developer's experience of contributing to Gitcoin

**Comment by owocki** [comment]
@octavioamu made it sound like it was  apretty small change; idk if hes started on it tho

**Comment by octavioamu** [comment]
I didn't yet. I'm ok if you want to take it.

**Comment by nglglhtr** [comment]
@octavioamu my idea is to use the `window.sessionStorage` in onboarding modal display

**Comment by octavioamu** [comment]
@nglglhtr was fixed on friday here is the commit 393984c

**Comment by owocki** [comment]
tyty @octavioamu
