### ISSUE TITLE
Try to make it more egalitarian at the top by changing the shuffling algorithm so that once a project gets over $5000 matching, from a shuffling PoV it's treated as though it has just $5000 matching

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7822]

**Comment by owocki** [comment]
vitalik spec 

shuffling algorithm from the POV of some user gives 2x higher score if project is in the same category as the user; doesnt do that if theyre in the oposite .

then measure what magnitude of effect we have in affecting views for a grant

**Comment by owocki** [comment]
@thelostone-mc this is done @ a58db65547fc587bc8893ef5dadb1931b62d7406
