### ISSUE TITLE
Funded issues are shown up as expiring in search results

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#783]
On the screenshot below at least https://gitcoin.co/issue/jhoenicke/mempool/14 is completed/funded and should not be listed as expiring in search results.

![image](https://user-images.githubusercontent.com/8781107/38285606-a78e43fa-37c9-11e8-9e2c-c2ea5162b884.png)

### User Story

As a gitcoin user, I want to see the status for all issues that are funded by certain account in search results to see if there is anything that needs to be done for this account.

**Comment by thelostone-mc** [comment]
@PixelantDesign This makes sense! Shall we add this in ?

**Comment by owocki** [comment]
while we're at it, should we consider adding the bounty status somewhere in each results row?  could be useful for 'any' searches

**Comment by owocki** [comment]
i mean the [bounty status](http://bits.owocki.com/0v3m3X2e0k3R/Image%202018-04-04%20at%2011.38.35%20AM.png)

**Comment by PixelantDesign** [comment]
Makes sense in the **Any** filter to see what each item is. We could add that info using the same treatment as  level and expired.

In other views, we can rely on the top header and left rail filter the user selected.

**Comment by abitrolly** [comment]
#785 looks good. Maybe it worth to color code the status, marking Done items as green and the rest as yellow?

**Comment by thelostone-mc** [comment]
That would work. 
Deferring the design to @PixelantDesign

**Comment by abitrolly** [comment]
> i mean the bounty status
> <http://bits.owocki.com/0v3m3X2e0k3R/Image%202018-04-04%20at%2011.38.35%20AM.png>
>
It appears there is also Killed status.

>

**Comment by thelostone-mc** [comment]
@owocki aren't killed and cancelled the same ?

**Comment by owocki** [comment]
yes

**Comment by owocki** [comment]
this seems related https://github.com/gitcoinco/web/issues/824

**Comment by owocki** [comment]
@PixelantDesign looks like @thelostone-mc handled this above!  thanks aditya!
