### ISSUE TITLE
Grant campaign page not loading, perhaps related to description length

### ISSUE THREAD

**Issue by Mitchellpkt** [gitcoinco/web#7845]
I posted a [GitCoin grant](https://gitcoin.co/grants/1513/zcash-observatory-netsec-dashboard-api-and-researc), and received a notice (see below) out of band that the page was not loading correctly in Brave (displaying rather than rendering the code.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/21246742/98450638-69de7980-20fb-11eb-9358-e40ff0d69dc7.png">

I could not reproduce the exact bug described in Brave, however I did observe that while the original page loaded fine in Firefox (my main browser) it would not load reliably in Chrome. When I shortened the description length, the issues in both Brave and Chrome were  resolved. I saved a copy of the original description (which caused the bug) here: [https://docs.google.com/document/d/1JdzMyJpP0Rm6mXqiQmIAZ_pArvw5iQns8jfmGxA4Nqo/edit?usp=sharing](https://docs.google.com/document/d/1JdzMyJpP0Rm6mXqiQmIAZ_pArvw5iQns8jfmGxA4Nqo/edit?usp=sharing)

**Describe the bug**
The page was not loading content for me in Chrome, and was reported to display rather than render code in Brave.

**To Reproduce**
The bug occurred upon attempting to load the original version of the [Zcash observatory grant](https://gitcoin.co/grants/1513/zcash-observatory-netsec-dashboard-api-and-researc). (I have since shortened the description so that the page works during the matching window)

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Browser Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36

**Comment by danlipert** [comment]
Yes thanks for the report @Mitchellpkt appreciate all of the info. @thelostone-mc @octavioamu @owocki its interesting because there is an image in the grant description still but it is loading fine.  It loads fine in both Chrome and Brave now. I'm wondering if there must be some kind of byte limit rather than binary image/no image as the original description here had multiple images

**Comment by octavioamu** [comment]
Thanks, we are redesigning this page I will test with long content also to be sure is not a problem anymore .
