### ISSUE TITLE
Cannot fill "Project Team members" field

### ISSUE THREAD

**Issue by Vladkuz100** [gitcoinco/web#7849]
**Describe the bug**
When trying to create new grant for application on https://gitcoin.co/grants/matic/new is is impossible to add links to team github accounts in "Project Team members" field. The result is always "Results not found" despite of all the accounts are active and real.

**To Reproduce**
Add one of the accounts to the form "Project Team members" on the "https://gitcoin.co/grants/matic/new": 
https://github.com/laumiqv 
https://github.com/Ameize4
https://github.com/TepNik 

**Expected behavior**
It is possible to add team members using their GitHub accounts and they are successfully added

**Screenshots**

<img width="706" alt="Снимок экрана 2020-11-09 в 17 37 42" src="https://user-images.githubusercontent.com/26791130/98578134-fc367700-22cd-11eb-8005-b01264330969.png">
<img width="691" alt="Снимок экрана 2020-11-09 в 17 38 37" src="https://user-images.githubusercontent.com/26791130/98578136-ff316780-22cd-11eb-9d73-288230fa7cd1.png">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Opera
- Browser Version: 72.0.3815.211

**Additional context**

**Comment by owocki** [comment]
try using the team member's username (not the url)

**Comment by owocki** [comment]
(note the user must be a gitcoin user, and i dont think the user you  listed was)
