### ISSUE TITLE
My kudos are transferred but still have not received it to my wallet 

### ISSUE THREAD

**Issue by jhanlew** [gitcoinco/web#7850]
I'm using the metamask wallet. I'm searching for the eth guru kudos. I was notified by the Gitcoin bot that 4 of them have already been transferred.

**Comment by owocki** [comment]
hi; i've just re-issued your eth guru  kudos.  https://etherscan.io/tx/0xb68256fb0d1066d7c29063ca1412eee5b5fccd7760b6216a23278fbd2dcb877b

**Comment by jhanlew** [comment]
I only received two of them

**Comment by owocki** [comment]
checkout the blog post => https://gitcoin.co/blog/the-future-of-gitcoin-kudos/ to see how you can view your kudos in wallet
