### ISSUE TITLE
Bounty platform fee paid, but bounty does not appear

### ISSUE THREAD

**Issue by jppade** [gitcoinco/web#7860]
I have an issue I need help with. I wanted to put up another bounty on my profile. The page crashed after I paid the platform fee (which I apparently did twice for the same bounty). Here are the txn hashes:

0xefa408db15b7df5702a722faaa7dee24d5a1bbe38326fbf02682c80e07e6ec5b
0x4b871066124109fe5f3470a55ba94cec8b3cb75f61e503acdecb00cddb1162d0

However, the bounty does not appear on my dashboard. When I hit "fund issue" again, it tells me "Please verify forms errors and try again ".
Many thanks in advance.

**Comment by thelostone-mc** [comment]
Is this sill a problem @jppade ? Did the bounty end up getting created ?

**Comment by jppade** [comment]
@thelostone-mc I don't think it did, but I can't even remember what bounty it was. Worst case consider it as a donation from DIAData :) Thanks for getting back to me anyway.
