### ISSUE TITLE
Cannot update Project GitHub URL

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7861]
https://gitcoin.co/grants/1531/zon-directory

"Project GitHub URL" is `undefined` and I can't change it (even after pressing `Edit Info`).

**Comment by developerfred** [comment]
We need to investigate this model @Solexplorer

**Comment by thelostone-mc** [comment]
Fixed and tested this in live a while back!
Tested this in live once again and it worked 

Thanks @vporton + @developerfred for the report
