### ISSUE TITLE
zkSync checkout stuck on  "Preparing transfer 0 of 2"

### ISSUE THREAD

**Issue by miguelmota** [gitcoinco/web#7865]
**Describe the bug**

Checking out with zkSync gets stuck on Step 3 "Confirm donation transaction". It says " Preparing transfer 0 of 2" and shows " Processing" spinner indefinitely.

![Screenshot from 2020-11-11 16-11-49](https://user-images.githubusercontent.com/168240/98878870-e7c2bd80-2438-11eb-9040-739fe6f58bd1.png)

**To Reproduce**

1. login
2. connect Authereum wallet
3. checkout with zkSync (using ETH)
4. sign in to zkSync via Gitcoin (step 1 in modal)
5. confirm donation transaction  (step 3 in modal)
6. wait for deposit transaction to be confirmed 
7. notice last step hangs  
 
**Expected behavior**

zkSync transfer goes through.

**Screenshots**

**Desktop (please complete the following information):**

- OS: any
- Browser: Firefox
- Browser Version: 82

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

deposit transaction
https://etherscan.io/tx/0x13eccd53b0aac5afc5195839b038d835fcea87a8c79c9321d250718495e3e354

**Comment by miguelmota** [comment]
zksync signature error after clicking "Sign in to zkSync directly"

![Screenshot from 2020-11-12 05-30-26](https://user-images.githubusercontent.com/168240/98946530-da451c00-24a8-11eb-9ae5-7c0bdc4de464.png)

**Comment by miguelmota** [comment]
Possibly related to https://github.com/matter-labs/zksync/issues/254

**Comment by owocki** [comment]
@mds1 any ideas?

**Comment by mds1** [comment]
Hey @miguelmota! Based on the error shown and the issue you linked, I'd guess that is the correct cause. Once Matter Labs resolves that issue, you should be able to visit https://gitcoin.co/grants/cart and follow the "Complete zkSync Checkout" prompt shown
