### ISSUE TITLE
Fixed heights in tips list

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#787]
### Description
*Type*: Bug

### Current Behavior
Makes comments overflow other elements.
![image](https://user-images.githubusercontent.com/1838338/38313531-91109a96-3824-11e8-91ff-87cef9b38872.png)

### Solution
Maybe remove fixed heights ?

**Comment by kziemianek** [comment]
Sorry, didn't notice profile revamp #656, possible duplicate.

**Comment by owocki** [comment]
my 002 wei: its worth having this done as a stopgap in the meantime before #656 happens

**Comment by kziemianek** [comment]
![image](https://user-images.githubusercontent.com/1838338/38603698-a407af32-3d6e-11e8-9072-6e0c2ddf98ad.png)

Fixed in #825
