### ISSUE TITLE
admin: add cache burst command to GrantCLR

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7903]
Allow admins to bust the GrantCLR cache (so they have confidence in the admin is working)

Have an button within 
https://gitcoin.co/_administrationgrants/grantclr/
which runs 

```
        create_grant_type_cache()
        create_grant_clr_cache()
        create_grant_category_size_cache()
        create_grant_active_clr_mapping()
```

which is defined in create_page_cache
code link: https://github.com/gitcoinco/web/blob/master/app/perftools/management/commands/create_page_cache.py#L387-L390

reason for doing this :
when admin changes certain data in grants CLR -> they have to wait for page cache to run for the UI to be updated
having an option there -> makes it quicker / less panicky for admin to make changes

**Comment by owocki** [comment]
note that those create_page_cache methods are bulk (for all grants), u might want to  add an individual cache buster (eg `grant.calc_clr_round()` ) too
