### ISSUE TITLE
Grant Comments with a Comma (,) Get Scrambled After Checkout

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#7917]
**Describe the bug**

I donated to three grants in a single cart transaction. I added comments to each of those grants. One comment contained a comma ',' and the output comments got scrambled. This also happened when I donated yesterday. The result is I had to manually edit the individual comments to correct them.

**To Reproduce**

Add multiple grants to your cart with ETH denomication. Write a comment for each. In one of the comments, include a comma ',' followed by more text.
Adjust share paid to Gitcoin pool to 1%.
Check out using Standard Checkout.
After checkout, look at your grant comments to see if they got scrambled.

**Expected behavior**

Grant comments should not get scrambled.

**Screenshots**

Cart with original grant comments:
![image](https://user-images.githubusercontent.com/56145569/99853935-be8ce600-2b38-11eb-8469-a33dcb3c6800.png)

Published scrambled comments:
![image](https://user-images.githubusercontent.com/56145569/99854057-f7c55600-2b38-11eb-8215-7b5cf35dedff.png)
![image](https://user-images.githubusercontent.com/56145569/99854074-00b62780-2b39-11eb-88dd-52f967b220ce.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave with shields down
- Browser Version: Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)

**Comment by thelostone-mc** [comment]
@BTCAlchemist ah thanks for the detailed reproduction steps ! this helped me debug and find the bug and fix it up
Just deployed this a few hours back 

Would you be open to testing it out and seeing if it works solid at your end as well ?

**Comment by BTCAlchemist** [comment]
@thelostone-mc Appreciate you fixing this! I can test it the next time I donate to grants, possibly over the next month or two. Cheers.
