### ISSUE TITLE
alpha tag confusion

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#792]
the `ALPHA` tag makes it seem like Colony is in alpha, not the profile feature. I wonder if the placement could be changed so it’s not confusing?
![screen_shot_2018-04-04_at_11 21 50_am](https://user-images.githubusercontent.com/513929/38328036-0dfa87f6-3807-11e8-8499-a7f9c3dace8c.png)

**Comment by owocki** [comment]
yes i agree that could work

**Comment by thelostone-mc** [comment]
@willsputra wanna throw in the fix ? :D

**Comment by mbeacom** [comment]
#827 has been merged - This issue should be good to close!
