### ISSUE TITLE
as a community member who provides a lot of value to gitcoin, i want to be able to apply for moderator status, so i can help grow the community

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#793]
as a community member who provides a lot of value to gitcoin, i want to be able to apply for moderator status, so i can help grow the community

possible responsibilities:
* approving faucet requests  ?
* some amount of bounty budget ? 

possible implementation
* django admin
* slack admin

**Comment by kuhnchris** [comment]
I assumed this evolved into the ambassador program. closing.
