### ISSUE TITLE
Match amount does not show as 0 when contributing to your own grant

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#7943]
I created the Umbra grant, but you can see a match still shows up. This is from the live gitcoin.co site. Is there an easy way in `cart.js` to check if the logged in user is on the team for a given grant, that way we can set the CLR match estimate to zero in that case?

I believe we want to keep the functionality of donating to your own grant because it makes it simpler to create collections, and since it won't count for matching anyway there's no benefit to preventing this

![image](https://user-images.githubusercontent.com/17163988/100294526-e4046000-2f3b-11eb-9347-a3ee8ad524da.png)

**Comment by mds1** [comment]
cc @octavioamu @thelostone-mc

**Comment by thelostone-mc** [comment]
Ah that is an annoying UX bug!
Yup folks can fund their own grants, it just won't be counted for CLR estimates 

well there is a util function called 
https://github.com/gitcoinco/web/blob/grants-round-8/app/grants/utils.py#L84
which is passed to frontend via `repr` here 
https://github.com/gitcoinco/web/blob/grants-round-8/app/grants/models.py#L789

We just need to pass that info to the cart checkout page from landing / grant detail page 

@mds1
