### ISSUE TITLE
Projects external urls broken Grants Page

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#7953]
**Describe the bug**

if a user writes a URL without HTTPS they should automatically put it in Grants

**To Reproduce**

![3D5BBFF2-34A9-4A69-A725-BD070EE2CF25](https://user-images.githubusercontent.com/57037080/100483566-566a7100-30f1-11eb-9e69-d1760170a5cd.png)

![C100FAE6-9B87-4B40-9DD5-1FC8EA306098](https://user-images.githubusercontent.com/57037080/100483574-5e2a1580-30f1-11eb-8a04-3d0ddb2cb9b7.png)

**Expected behavior**

Redirect external url page

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by octavioamu** [comment]
Closing as this was already solved on the form validation (new/edit)  probably the user didn't update his grant yet.
