### ISSUE TITLE
Paid Bounty Says "Pending Verification"

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#7959]
**Describe the bug**

Bounty was paid (with tip, total of 133.33% paid) and confirmed, but the bounty page still says "Pending Verification."
Please see SUBMISSIONS section at https://gitcoin.co/issue/Meme-of-the-Day/meme-of-the-day-filecoin/19/100024038
Transaction confirmation at https://etherscan.io/tx/0x504a1e9e07cf32ba741a9cb81cf9c7027c403b371f51951d6476de2028d1b025

**To Reproduce**

Create a bounty. After a submission is made, on the bounty page, click on that submission to pay it out. Note that my payment included a tip for a total of 133.33% payout. Confirm the transaction.

**Expected behavior**

Bounty Submission should be confirmed and the bounty closed.

**Screenshots**

![image](https://user-images.githubusercontent.com/56145569/100526003-f10e9280-3179-11eb-8d1f-e014653b82f8.png)

![image](https://user-images.githubusercontent.com/56145569/100526012-08e61680-317a-11eb-8b5a-9802ba6fbf91.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave (shields down)
- Browser Version: Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)
Also shows "Pending Verification" on Edge browser.

**Comment by BTCAlchemist** [comment]
My dashboard funder page still shows that I need to pay out this bounty:
![image](https://user-images.githubusercontent.com/56145569/100534182-e62b2080-31c0-11eb-87ef-b50b8a47a2dd.png)

**Comment by g-r-a-n-t** [comment]
We are having the same issue here: https://gitcoin.co/issue/ethereum/fe/38/100024013

See the payout transaction here: https://etherscan.io/tx/0xce3e14cb79644284824544162db8887497b03f3992200a14bba279f0f3a82fb7

The transaction was replaced and the UI seems to be waiting on the original, which will of course never compete.

It looks like we are having a slightly different issue than @BTCAlchemist in that his bounty details page points to a completed  transaction, whereas ours does not.

**Comment by thelostone-mc** [comment]
@BTCAlchemist Hey soo looks like one of our cronjobs had conked off! ran it manually and it worked !
It should be good to close now 🙌 


@g-r-a-n-t Ah yeah we've been rate limited by blocknative and that seems to be affecting our ability to picked up replaced transactions ! We're looking into that but approving it backend for now to unblock you

**Comment by BTCAlchemist** [comment]
Thanks, @thelostone-mc! Closing this out.
