### ISSUE TITLE
Grants have multiple URLs

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7966]
Grants have multiple URLs with the same content:

* https://gitcoin.co/grants/1531/zon-directory
* https://gitcoin.co/grants/1531/zon-directory?tab=description

This reduces GitCoin Google rank.

The right way to solve is to add `canonical` `<meta>` tag to the page.

**Comment by thelostone-mc** [comment]
It's been switched over to have same URL and ajax calls to populate data ^_^
