### ISSUE TITLE
UX display bug

### ISSUE THREAD

**Issue by Tedko** [gitcoinco/web#7971]
Take a look of https://gitcoin.co/grants/159/mask-networkmaskbook-the-portal-to-the-new-open-i?tab=transactions

<img width="1486" alt="Screen Shot 2020-12-01 at 04 29 48" src="https://user-images.githubusercontent.com/6687437/100661094-ecbac300-338d-11eb-9201-ad17cb18541f.png">

**Comment by thelostone-mc** [comment]
should be fixed now ! thanks for the report ^_^
