### ISSUE TITLE
Transfer Kudos to Metamask and Opensea

### ISSUE THREAD

**Issue by phantohm** [gitcoinco/web#7983]
**Describe the bug**
Kudos are not showing in Metamask on Ethereum mainnet and on xDai Chain. I am looking to sell some Kudos on Opensea and have no way of doing so at the moment. Opensea also only accepts Ethereum Main net transactions.

**Comment by owocki** [comment]
you can re-issue your kudos via the /kudos tab in your profile.

we cannot guarantee a mainnet kudos in every case.

**Comment by Hyakymaru** [comment]
HI i have this problem whem i try to transfer one kudo

**Comment by Hyakymaru** [comment]
![unknown](https://user-images.githubusercontent.com/74867709/101220492-24f72580-365c-11eb-8432-2fd77f803c8d.png)

**Comment by Hyakymaru** [comment]
Am I doing somenthing wrong?

**Comment by owocki** [comment]
without knowing what account youre using or what kudos youre transfeirng, it looks like you dont have sufficient funds to purchase that kudos.
