### ISSUE TITLE
Grant Category

### ISSUE THREAD

**Issue by kitartoan** [gitcoinco/web#7988]
Hi! I just created my first grant here: https://gitcoin.co/grants/1614/banklessru I screwed up by picking a bunch of extra categories like Education and Blog, while I was aiming to list the grant only in the Media collection. I can't fix this in the Edit menu, so I was wondering if this can be altered from your side, or should I close this grant and create one from scratch? Thanks.

**Comment by thelostone-mc** [comment]
Hey @kitartoan ! 
We had renamed media to Community. This was a UI bug we had forgotten to fix.
Just rolled out a fix for that

The blue -> Grant Category -> Every Grant can select 1 at time of creation and to change it -> we ask them to reach out to us 
The green -> Grant SubCategories -> This you can edit after grant creation 
 
![image](https://user-images.githubusercontent.com/5358146/100829653-e4df4980-3487-11eb-8d1b-347b8a084d29.png)

**Comment by kitartoan** [comment]
Thank you for response, @thelostone-mc. However, It seems I still can't opt-out from subcategories in Edit menu. Here is how it looks like for me. I tried different browsers, but the results are the same. Would you kindly change this? I just wanted to be in the same category with the Bankless fam. :)

![image](https://user-images.githubusercontent.com/36260333/100842207-27515800-3481-11eb-8206-5bd10e785b63.png)
