### ISSUE TITLE
Can't paste a long Git repo URL into a grant description

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7993]
I can't paste a long Git repo URL into a grant description:
https://github.com/vporton/algebraic-general-topology

Increase the field length.

**Comment by thelostone-mc** [comment]
Just pushed in a fix to increase the project URL length ! Could you check and confirm ?

**Comment by vporton** [comment]
> Just pushed in a fix to increase the project URL length ! Could you check and confirm ?

It works now.
