### ISSUE TITLE
Visual glitch in design

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7994]
"Feedback" is over other elements of the page:
![Screenshot from 2020-12-02 16-39-32](https://user-images.githubusercontent.com/2900574/100886900-07d82080-34bd-11eb-97eb-52955cc8c640.png)

**Comment by thelostone-mc** [comment]
Design has been tweaked !
So this should work ^_^

![image](https://user-images.githubusercontent.com/5358146/101372586-11ed8b00-38d2-11eb-8f53-22db097fd157.png)
