### ISSUE TITLE
Becoming a matching partner should be easier

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#7998]
Becoming a matching partner should be easier: make the process completely automated instead of querying a human at GitCoin.

This will increase the number of matching partners by making it easier to contribute small sums by small matching parners.

**Comment by owocki** [comment]
this exists https://gitcoin.co/grants/matching-partners/new

**Comment by thelostone-mc** [comment]
<img width="1680" alt="Screenshot 2020-12-03 at 4 07 17 PM" src="https://user-images.githubusercontent.com/5358146/101030781-6c6bac00-359f-11eb-8b53-516cb83e5b61.png">

Also visible on the landing page
