### ISSUE TITLE
Grants Round 8 Feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8000]
Lets use this thread to capture feedback from users on Grants Round 8.

Similar to https://github.com/gitcoinco/web/issues/7408 for round 7

**Comment by owocki** [comment]
tracking initial bug list here https://github.com/gitcoinco/web/issues/7947

**Comment by owocki** [comment]
my thinking is that the sybil resistence compounds (not grows linearly) when you very more accounts.  so 1.05 * 1.05, not 1.05 + 1.05

we should maybe just show your current trust bonus on the tab .

**Comment by owocki** [comment]
android display issues https://twitter.com/Freddmannen/status/1334225847197327361

**Comment by owocki** [comment]
https://bits.owocki.com/BluQBNyP

8000 ETH donation, is it possible to fool the system with the amount put in. will the validator catch the amount diff?

**Comment by owocki** [comment]
S galaxy note 9
Metamask version
0.2.14
Android 10

Get this 502 on mm mobile and trust doesnt store the github authkey on login. Would love a nice mobile env would scroll and be more active


https://twitter.com/futjrn/status/1334354368418766849

**Comment by owocki** [comment]
@apbendi my `https://gitcoin.co/owocki/trust` page just took 20s to load in prod.

would it be possible to move `get_brightid_status` into an asyncronous call?  upon profiling the page, it looks like that is what was holding up the pageload.

**Comment by owocki** [comment]
the 'anonymize my contribution' functionality only anonymizes the activity feed item and not the contribution tab + the contributors tab.

we should make it so that the transaction tab + contribution tab are both anonymized too.  but the CLR.py code should still be aware of who the unqiue contributors are.

**Comment by owocki** [comment]
Connor O'Day Has anyone looked into whether Grants donations could be tax deductible? From what I understand, I think the recipient would have to be a registered non-profit, but I’m not entirely sure. It might be worth looking into how we can encourage grantees to register as such and if we can provide some type of tax friendly receipt to donors in the future. Especially if we’re entering another bull market year, this could be a good selling point. I’d rather donate more to public goods of my choosing and pay less to federal public goods aka our military..

**Comment by owocki** [comment]
we should verify how old a twitter account is during twitter verification too.  ppl are making fake twitter accounts to verify their grants https://twitter.com/GitcoinDisputes/status/1338478651248050177

**Comment by apbendi** [comment]
> we should verify how old a twitter account is during twitter verification too. ppl are making fake twitter accounts to verify their grants https://twitter.com/GitcoinDisputes/status/1338478651248050177

We validate min account age of 6 months and min 100 followers for the Trust Bonus, so this should be straightforward to add for Grants as well:

https://github.com/gitcoinco/web/blob/e40589978c7a96952c935ce03e46b0f0f321b29a/app/dashboard/views.py#L3102-L3103

**Comment by frankchen07** [comment]
add all to cart is potentially dangerous when you just click on it on the gitcoin.co/grants page. I did it and added 628 grants to my cart, and almost crashed my computer.

luckily, there's a "clear cart" button.

**Comment by owocki** [comment]
if a grant owner sets their address as an ENS name it breaks checkout for anyone who tries to checkout with that grant in cart.  need better validation

**Comment by owocki** [comment]
the new matching partner form email is too spammy rn

set a minimum of 10k on the new matching partner form, dont actually trigger an email to admins until the funds are sent.

maybe also an auto follow up if the funds arent sent asking if they have any questions

**Comment by owocki** [comment]
in viewing the sybil scores + risk scores for some of the top rounds, a lot of the accounts (particularly in east asia) are brand new to gitcoin.  we need a way to "background checK" new accounts + figure out if they are sybil or not.  otherwisse we just have no data to go on

**Comment by owocki** [comment]
- sybil verification howto videos

**Comment by owocki** [comment]
Stop being zksync sandbox, as seems we are the biggest users and always trap on the bugs they introduce on their side

**Comment by owocki** [comment]
from a friend:
- so alternative funding is something i think we should add to the data model + the market should start considering i think
- matching rounds getting saturated screws up the whole thing and basically makes it a zero-sum game where people feel like their matching is getting "stolen"
- there are too many projects on Gitcoin now that aren't strictly "public goods" anymore and dont need gitcoin to sustain themselves

**Comment by owocki** [comment]
V: Also, "liftoff" and "Apollo" are terrible category names; need something that explains what they actually are

**Comment by owocki** [comment]
make it clear in the UI that https://github.com/gitcoinco/web/issues/new is where you go for help.  hopefully people will stop DMing me everywhere for support if we do this.

**Comment by owocki** [comment]
ok this is a weird one - i've gotten two seperate reports from diff users saying their grants rounds were marked as final + then revereted back.  here is a screenshot:

![amWl1ZIy](https://user-images.githubusercontent.com/513929/102386260-167a0980-3f8c-11eb-94ba-f55d463ad0f6.png)
![aIFIIQo2](https://user-images.githubusercontent.com/513929/102386255-1548dc80-3f8c-11eb-8139-7c7d321057dd.jpg)

**Comment by owocki** [comment]
https://bits.owocki.com/nOuD50J8
https://bits.owocki.com/qGulReBR

twilio API errors.

both of these should gracefully degrade in the frontend but they dont rn https://twitter.com/j_schwartzz/status/1339238816956231681 "nothing happens after that"

**Comment by owocki** [comment]
sybil improovement ideas
- sybil ranks over time
- TLS signatures
- fingerprintjs.com 
- on chain analysis
-

**Comment by owocki** [comment]
zksync: seemed like 25-30 cart items was where i topped out

**Comment by owocki** [comment]
A/b test results
Whats the gini coefficient of the grants round?  How concentrated was grants round 8 vs  round 7?
Zoe questions: are people being strategic about how they get matching - or are they just messing around?
Andreas:  the flow was very confusing by i realized eventually “More people funding =  number go up”
Vitalik: Diversity of how you interface with Gitcoin grants, maybe more interfaces.

also todo: add the feedback from panelists from wrapup last night @vs77bb @ceresstation

**Comment by WeAreFLIX** [comment]
Thanks Gitcoin! We really liked that we didn't have to pay gas to deploy the grant this round and how the contributions went directly into our wallet. Very smooth and enjoyable experience!

**Comment by lucadgtrip** [comment]
thanks Gitcoin!
I would make it a bit clearer how matching works.
- donors see stuff like "1 DAI contribution + 6 DAI match" which is a 6x.
- grantees see the same but then the Match is much lower (at least that was our experience during the grant).
At the end this is pretty confusing:

![Screenshot 2020-12-23 at 10 09 25](https://user-images.githubusercontent.com/34341206/102974309-fa83e400-4506-11eb-92c9-a5cdd5e9b6ea.png)

how did the match pass from a 6x to 0,5x when the average donation is about 1 Dai?
I'm sure it make sense in the backend, just pointing out it doesn't in the frontend.
====
Also note, it still shows "Estimated match" after the round is closed (will claim soon and see if it changes).

**Comment by Onebotband** [comment]
> Lets use this thread to capture feedback from users on Grants Round 8.
> 
> Similar to #7408 for round 7

There was a bit of a hiccup with somebody flagging our grant, but the community reenabled it after evaluation, much thanks.

**Comment by LefterisJP** [comment]
there is a bug in the frontend. Total earned seems to show the total amount including match. While it should only show the donated amount. (wish we had taken this match in this round)

![2020-12-23_01-01](https://user-images.githubusercontent.com/1658405/103024725-b0275500-4550-11eb-9b28-a328fd147dbf.png)

Also would the contribution being given like this count normally in the API you guys made before or will it be double counted? (have not tested yet -- but I am just asking to make sure it's taken into account there)

![2020-12-23_01-06](https://user-images.githubusercontent.com/1658405/103024763-bfa69e00-4550-11eb-8aa2-8480c87e195d.png)

**Comment by owocki** [comment]
the grants cart should reflect the CLR estimate upon the time of the VIEWing of the cart, not the ADD to the cart.

**Comment by owocki** [comment]
Better Dispute resolution mechanism by @disruptionjoe https://www.notion.so/Research-a-better-grant-dispute-decision-mechanism-for-pre-decentralization-rounds-03399b215a874e5b8342679086a5cc28

**Comment by owocki** [comment]
planning GR9 scope here => https://github.com/gitcoinco/web/projects/53
