### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by solsista** [gitcoinco/web#8009]
### Who
New grant created: this grant could not be verified https://gitcoin.co/grants/1638/electric-circus-proudly-presents-impact-pirates

### What 
Unable to verify tweet

### Why
not sure, tweet is live: https://twitter.com/freeel_io/status/1334243043176747009?s=20 I did not change anything, it is the automatically generated tweet, made sure to remove special characters from grant title and retried, same problem.

**Comment by owocki** [comment]
@thelostone-mc @zoek1 any idea what went wrong on this one?  IIRC the verification tweets have emoji in them, but this tweet does not

**Comment by developerfred** [comment]
@solsista Your twitter does not have the url of your grants.
<img width="600" alt="Screen Shot 2020-12-03 at 09 10 59" src="https://user-images.githubusercontent.com/57037080/100988308-7e216500-3547-11eb-91b8-2d4b71004414.png">


Ex: My grant verification Twitter https://twitter.com/codingsh/status/1307014901785915392?s=20
<img width="604" alt="Screen Shot 2020-12-03 at 09 10 33" src="https://user-images.githubusercontent.com/57037080/100988329-82e61900-3547-11eb-82ab-dc0067015fb6.png">

**Comment by thelostone-mc** [comment]
Ah nice catch ! thanks @developerfred for catching that

**Comment by octavioamu** [comment]
Closing as seem the first time the tweet was changed that why failed, now is verified.
![image](https://user-images.githubusercontent.com/1358093/101018921-f3426980-354a-11eb-97fb-fe5ea6c3f4d1.png)

**Comment by ClimateFutures01** [comment]
Thanks everyone for the swift help! Our twitter feed from gitcoin was shortened for some reason and didn't have a link.

**Comment by developerfred** [comment]
> Thanks everyone for the swift help! Our twitter feed from gitcoin was shortened for some reason and didn't have a link.

#8027
