### ISSUE TITLE
Removing sub categories from the grant 

### ISSUE THREAD

**Issue by kitartoan** [gitcoinco/web#8013]
Hi! I hope you're well.
I've been told, that user can edit sub categories of the grant after the recent UI fix, but it seems like it's not possible in my case. Please, see the attached screenshot. 
Kindly asking if you could remove them, so that BanklessRU grant could be moved to the same Community category as BanklessHQ and BanklessFR. I think that would make a lot more sense. 
Thank you for assistance. 
Cordially,
Alex 

![изображение](https://user-images.githubusercontent.com/36260333/100976403-220b1080-3548-11eb-807d-3825bbcde4cc.png)

**Comment by thelostone-mc** [comment]
Yup this was a feature we should have added! 
Looking into this but for now I'll update it for you

**Comment by thelostone-mc** [comment]
could you share details on grant + what are sub categories you would want to shift it to ?

**Comment by kitartoan** [comment]
Aha, I see. Here is the link https://gitcoin.co/grants/1614/banklessru
I wanted to remove Education and Blog in order to show up only in Ethereum State Media collection. Or who gets there and who isn't is up to Kevin's discretion? I only just thought this might be the case. 😅
