### ISSUE TITLE
Bug: z-index Web3Modal/Navbar Gitcoin

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#8014]
**Describe the bug**
NavBar Gitcoin has a higher z-index than web3Modal
[z-index: 2 Web3Modal](https://github.com/Web3Modal/web3modal/blob/c17015b8160c7d28e3443b9f048692a1df880bb2/src/components/Modal.tsx#L38)

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1114" alt="Screen Shot 2020-12-03 at 08 59 25" src="https://user-images.githubusercontent.com/57037080/100987356-567dcd00-3546-11eb-98f9-394bc1916a7d.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser:Chrome
- Browser Version: 86.0.4240.198 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by octavioamu** [comment]
👀   https://github.com/gitcoinco/web/pull/7089/files#diff-9756330c755da609ead281873d9f9be2841b85838f0c9c8a52a1aa3ef7010885R24
Fixing this now on stable
