### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by wighawag** [gitcoinco/web#8016]
My grant twitter verification is not working, here is the tweet : https://twitter.com/wighawag/status/1334429118289620993

**Comment by thelostone-mc** [comment]
It looks like it did get verified. Closing this out 
![image](https://user-images.githubusercontent.com/5358146/100992514-45e74a00-357a-11eb-9fb7-1cf170340b8f.png)

**Comment by wighawag** [comment]
Could you reopen? you are linking to the wrong grant. the tweet refers to :  https://gitcoin.co/grants/1588/jolly-roger

the following shows on my side even after reload :

![Capture](https://user-images.githubusercontent.com/790580/100994079-20444b80-354e-11eb-84c7-5ce366f536d6.PNG)
