### ISSUE TITLE
Changing details did not save 

### ISSUE THREAD

**Issue by Buttaa** [gitcoinco/web#8019]
We have changed the URLs in the text on our grant ( https://gitcoin.co/grants/258/beaconchain-open-source-eth2-blockchain-explorer ) , as seen in the screenshot, however it never applied those changes

![image](https://user-images.githubusercontent.com/26490734/101039596-2d782f00-357c-11eb-9dc8-bb617cec4e83.png)

**Comment by owocki** [comment]
thanks @Buttaa ; to be clear, you used the edit grant functionality + it said it saved, but it never did?

**Comment by owocki** [comment]
ok, the race condition is fixed now.  we fixed it when we fixed the performance issues last night.

@Buttaa  unfortunately we lost your edits though.  im sorry. throwing a few DAI your way to say sorry.

**Comment by thelostone-mc** [comment]
Closing this out ! 
@Buttaa sorry about the issue and thanks for the report and being patient with us :)
