### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by ClimateFutures01** [gitcoinco/web#8020]
### Who
Climate Futures is having trouble using your verify feature. 

https://gitcoin.co/grants/1651/1planet-access-carbon-markets-fight-the-climate-c

### What 
The verify tweet goes out but it will not get picked up/verified by Gitcoin. We've left it on our account for now. We tried last night and today, still the same problem. 

Can you pleas verify our twitter account and grant manually?

### Why
Because our grant proposal looks like a scam until we get it verified. :) Thanks!

**Comment by developerfred** [comment]
@ClimateFutures01  look https://github.com/gitcoinco/web/issues/8009

**Comment by developerfred** [comment]
@ClimateFutures01  The message needs to be the one that the Gitcoin grants page generates for you
ex: https://twitter.com/realcodecamp/status/1334572427637125122?s=20
