### ISSUE TITLE
Improvements on Message Verify Twitter

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#8027]
### Who
I am a Grant Founder and I would like to verify my account but I am having difficulties because of the length of my Grants name.

### What 
In this Round, we have a lot of problems with checking Twitter, I propose to add a **url shortener** in grants, or make a handle url for grants eg: **`gitcoin.co/grants/@futurebank`** With limited characters in the handle.

It would also be interesting to educate the community to write their projects with few characters:
**_ex slogan: FutureBank is Lego Bank_**

This will prevent the message from breaking before it reaches twitter.

Ref https://github.com/gitcoinco/web/issues/8026#issuecomment-738301404

### Why
#8026 #8020 #8012

**Comment by developerfred** [comment]
@octavioamu @thelostone-mc

**Comment by thelostone-mc** [comment]
yeah having a URL shortener might do the trick !
@chibie 's hunch on the twitter length cutting it out was right from the looks of it

**Comment by chibie** [comment]
the bug was caused by the special character '@'

pr #8031 fixes it

**Comment by octavioamu** [comment]
> the bug was caused by the special character '@'
> 
> pr #8031 fixes it

special character "&"

**Comment by octavioamu** [comment]
Just to everyone knowledge url length doesn't count on the twitter character limit, and urls get auto shortened.  
![image](https://user-images.githubusercontent.com/1358093/101202399-f2dbc880-3647-11eb-9241-37469e0691e5.png)
