### ISSUE TITLE
Grant should be cancelled but still active

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#8030]
https://gitcoin.co/grants/541/cic-covid-19-kenyan-crisis-aid

<img width="1159" alt="Screen Shot 2020-12-04 at 6 11 25 AM" src="https://user-images.githubusercontent.com/14945613/101157083-daf54c00-3629-11eb-96c6-b1f135c31b40.png">

**Comment by owocki** [comment]
@gitcoinco/engineers i just tried to cancel this via the edit grant functionality + it immediately reverted back

i seem to be able to update it via the admin

**Comment by thelostone-mc** [comment]
the cancel feature is not enabled for admin @owocki ! That is an allowed action for the grant owner/team member 
We need to hide that cause we don't want admin activity to turn up on the grant feed

Also @GriffGreen the cancel grant was broken 2 months ago and guess this was caught in that 
it does work now if you own a grant. thanks for the report 🙌

**Comment by thelostone-mc** [comment]
Closing this out but do reopen if we still have questions ^_^
