### ISSUE TITLE
Change funding address for round 8 grant Catnip

### ISSUE THREAD

**Issue by ryanberckmans** [gitcoinco/web#8033]
Hi! Hopefully, I'm doing this correctly :)

Can you please update the funding address for round 8 grant https://gitcoin.co/grants/1698/catnip from the current address of ryanb.eth to the new address of catnip.eth ?

Thank you!

**Comment by owocki** [comment]
@yashnaman
@bendavidow

is this ok with you?

**Comment by ryanberckmans** [comment]
@owocki thanks! It looks like Yash thumbs-up'd your question. I have pinged Ben.

**Comment by BenDavidow** [comment]
Fine by me too, thanks

**Comment by ryanberckmans** [comment]
@owocki someone reached out to us and let us know that donating on Gitcoin to the current funding address of ryanb.eth errored while using metamask:

![image](https://user-images.githubusercontent.com/299324/101286574-d9a25b80-37b0-11eb-9911-b3579480f5f9.png)

Might be that ENS isn't supported somewhere?

If this is an ENS incompatibility, would it be possible for the new funding address to be the ETH address to which catnip.eth resolves, instead of catnip.eth itself? That'd be **0x45e4B9b6bd6FCfb6B4f7c391744BAECFc9E04326** and can be seen https://etherscan.io/address/catnip.eth or https://app.ens.domains/name/catnip.eth.

**Comment by thelostone-mc** [comment]
I don't think we support ENS right now ! I'm setting it to 
0x45e4B9b6bd6FCfb6B4f7c391744BAECFc9E04326 for now

**Comment by ryanberckmans** [comment]
Thanks!
