### ISSUE TITLE
Says I've created 110 grants

### ISSUE THREAD

**Issue by DeFiDude** [gitcoinco/web#8035]
Hi, I was checking my funder info and it says I've created 110 grants, but I've only created 1.

Maybe I funded 110, I'm not sure.

![image](https://user-images.githubusercontent.com/59237470/101232566-ee2f0880-3677-11eb-9b59-340d85dad5f3.png)

**Comment by owocki** [comment]
hmm i think it should say 'grants funded' ; looks like uve funded about that many grants per your profile

**Comment by thelostone-mc** [comment]
yup it's supposed to be grants funded !pushed in a fix for that
