### ISSUE TITLE
I can't perform a normal checkout on chrome or firefox.

### ISSUE THREAD

**Issue by qu0b** [gitcoinco/web#8038]
**Describe the bug**
When I try to do a standard checkout it for a grant nothing happens when I press the checkout button. There are no errors and the console does not help either.

**To Reproduce**
Either try firefox + metamask or chrome + walletconnect with a metamask app on your phone and checkout a grant with sandard checkout. Thats the two options I tried.

**Screenshots**
<img width="683" alt="Screenshot 2020-12-06 at 12 50 32" src="https://user-images.githubusercontent.com/22667037/101279349-01e68600-37c2-11eb-932a-bdb9779a7702.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Chrome 
- Browser Version: Version 87.0.4280.88 

**Additional context**
Please at least show an error message.

**Comment by qu0b** [comment]
I finally manged to get it to work with the metamask browser on iOS. I guess is it might also have been rate limited.

**Comment by thelostone-mc** [comment]
@qu0b could you try this once again on chrome but scroll up and check if there are console errors which happen on page load ? I'm trying to reproduce but I've got no luck

**Comment by qu0b** [comment]
It still does not work I see a rate limit error:

```
========= NOTICE ========= raven.js:58:31
Request-Rate Exceeded  (this message will not be repeated) raven.js:58:31
<empty string> raven.js:58:31
The default API keys for each service are provided as a highly-throttled, raven.js:58:31
community resource for low-traffic projects and early prototyping. raven.js:58:31
<empty string> raven.js:58:31
While your application will continue to function, we highly recommended raven.js:58:31
signing up for your own API keys to improve performance, increase your raven.js:58:31
request rate/limit and enable other perks, such as metrics and advanced APIs. raven.js:58:31
<empty string> raven.js:58:31
For more details: https://docs.ethers.io/api-keys/ raven.js:58:31
==========================
```

**Comment by qu0b** [comment]
The errors from page load:
<img width="1386" alt="Screenshot 2020-12-08 at 13 29 24" src="https://user-images.githubusercontent.com/22667037/101484099-64be5580-3959-11eb-9d20-62c75cc0e1c0.png">
