### ISSUE TITLE
Verify Grant Issue - Gaia GIVETH

### ISSUE THREAD

**Issue by Danibelle** [gitcoinco/web#8040]
-->
### Who: Dani at Giveth updating a spin-off project grant from Giveth:
https://gitcoin.co/grants/1262/gaia-giveth-funding-portal

### What: Twitter verification not working
![image](https://user-images.githubusercontent.com/39466970/101284745-300a9c80-37a7-11eb-9eac-814867219618.png)

**Comment by thelostone-mc** [comment]
manually verified this for now ! yup we don't allow multiple grants to use the same twitter id ! something we will have to make room for in the future rounds. thanks for the feedback 🙌

**Comment by thelostone-mc** [comment]
Closing this out for now ! Have a good round 8 ^_^
