### ISSUE TITLE
Cannot load cart

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#8041]
**Describe the bug**

I have one item in my cart and wanted to check it out but when I go to the cart page(https://gitcoin.co/grants/cart) it keeps showing the animation that is fetching the data, this one: 
![image](https://user-images.githubusercontent.com/50027175/101289463-ee0c4580-37fc-11eb-9a91-5790ef92e647.png)
I do have an error in my console: 
```
raven.js:58 TypeError: Cannot read property 'includes' of undefined
    at cart.8e3a7d8e4a4c.js:79
    at Array.filter (<anonymous>)
    at a.grantsByTenant (cart.8e3a7d8e4a4c.js:78)
    at fn.get (vue.c107ca5cd927.js:6)
    at fn.evaluate (vue.c107ca5cd927.js:6)
    at a.grantsByTenant (vue.c107ca5cd927.js:6)
    at a.render (eval at Ya (vue.c107ca5cd927.js:6), <anonymous>:3:3505)
    at a.e._render (vue.c107ca5cd927.js:6)
    at a.r (vue.c107ca5cd927.js:6)
    at fn.get (vue.c107ca5cd927.js:6)
    at fn.run (vue.c107ca5cd927.js:6)
    at un (vue.c107ca5cd927.js:6)
    at Array.<anonymous> (vue.c107ca5cd927.js:6)
    at qe (vue.c107ca5cd927.js:6)
```
Just to note, this seems to happen to me on Opera, on Chrome it did work
**To Reproduce**

If you have opera, try to go to the cart, it should keep fetching

**Expected behavior**

I should be able to load the grants in my cart

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Opera
- Browser Version: 72.0.3815.400

**Comment by octavioamu** [comment]
wasn't able to reproduce with the same opera version I guess there is a grant on your cart with broken data can 
are you able to click share cart on that page and paste the url?

**Comment by octavioamu** [comment]
Actually I think I know what is going on with opera, the problem is not opera is you cart data was old there, and after this round we didn't have tenants so the data on opera (from localhost)  is trying to be displayed on the html and one of the rules is split by tenants (and that old data doesn't have it)
**A way to solve this could be press share cart paste that on the same opera tab browser search and press enter, the new data for those grants will be fetched, now with tenants field**

**Comment by Solexplorer** [comment]
Octavio is right, time to close the issue

**Comment by ncerovac** [comment]
I'm experiencing the same issue. Tried to copy the link from the 'share chart' with no luck. 

Macbook pro 2014
OS: OS X El Capitan
Browser: Chrome
Browser Version: 87.0.4280.88

**Comment by octavioamu** [comment]
Please share your share cart link here

**Comment by ncerovac** [comment]
hey @octavioamu I literally now managed to fix the issue.

so I cleared the cart (sadly no link from the previous one) and added projects again, checked after each one can I check out and see the cart and it worked.... 

so if anyone is experiencing still an issue after trying all that was suggested, try clearing the cart and start it again.
