### ISSUE TITLE
Cannot payout bounty

### ISSUE THREAD

**Issue by samajammin** [gitcoinco/web#8042]
**Describe the bug**

Eventually (by logging out & logging back in) I was able to complete this but I had issues trying to pay out this bounty:
https://gitcoin.co/issue/ethereum/ethereum-org-website/1447/100023708

**To Reproduce**
- Went to https://gitcoin.co/issue/ethereum/ethereum-org-website/1447/100023708
- Clicked "Payout Bounty" button
- Selected DAI amount
- Clicked "Payout" button
Nothing happens. Here's the browser console error:
```
raven.js:58 TypeError: Cannot read property 'utils' of undefined
    at payWithWeb3 (web3_modal.5ba9a7a5c92d.js:21)
    at wn.payWithExtension (bounty_details2.83f7d6b5561b.js:406)
    at click (eval at Ya (vue.c107ca5cd927.js:6), <anonymous>:3:25435)
    at He (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.n (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.Yr.o._wrapper (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.d (raven.js:445)
```

**Expected behavior**
Expected some sort of explanation in the app. Also expected refreshing the page to potentially solve this issue.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Brave
- Browser Version: 1.15.75

**Comment by thelostone-mc** [comment]
Hmm it looks like the web3 might have not been init !
@octavioamu any idea when this happens ?

**Comment by samajammin** [comment]
I suspect it might have something to do with initially loading the page without being logged in to Metamask?

If that's the case, the app should add logic to react to that event.

**Comment by chiro-hiro** [comment]
Related to #8076

**Comment by thelostone-mc** [comment]
We rolled out a fix for this ! This should be resolved now
It happens cause wallet connect is not connected and the user attempts to payout
The modal should popup asking the user to connect their web3 wallet now
