### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by WeTeachBlockchain** [gitcoinco/web#8044]
### Who 
https://gitcoin.co/weteachblockchain

### What 
My grant still will not verify Twitter. 3 Days ago, my grant did not verify Twitter either but the issue was briefly resolved thanks to solutions provided by your team. However, it quickly reverted to not being verified. 

### Why 
1.My grant's twitter account will not verify. This happened previously (3 days ago). I was provided a solution.

2.I followed the instructions for this solution by shortening the title of the grant. **I shortened the title from "#WeTeachBlockchain Decentralized Education." to "Decentralized Education".

3.I was told this is to allow space for the auto-generated gitcoin message and emojis, which is necessary for it to verify. I was told I could change the name back to its original longer name afterwards also. According to @zoek1 who said "you can back to the previous title in the meantime I create a patch for this."

4. This solution worked, because the grant was marked as verified when I refreshed the tab on the grant page. I did not change the name back. I preferred the new shortened name.

5. I then clicked the auto-generated URL you provide within the verification tweet, to test whether I could reach the grant page from twitter through this URL you provide.

6. The grant page appeared, but the title had reverted to the original long title "#WeTeachBlockchain Decentralized Education." and the page is no longer marked verified!

7. I went back to the original tab, with the verified grant page and the shortened "Decentralized Education" name. When I refreshed this tab, the grant name changed to "#WeTeachBlockchain Decentralized Education." and was once again unverified.

 

In the previous ticket @zoek1  said: 
      

     "Also, @thelostone-mc seems the user is trying to verifiy a different grant :)
                        1. https://gitcoin.co/grants/1643/weteachblockchain-decentralized-education
                        2. https://gitcoin.co/grants/1129/weteachblockchain-free-decentralized-education"

I had entered an OLD grant's URL which was from round 7 on accident. I was not trying to verify it, it was already verified. That was just a silly mistake. I am aware that you can't verify 2 grants. @octavioamu 

So how can fix this?

**Comment by octavioamu** [comment]
Please don't reopen a new issue write this on the origi al ticket so we can follow
