### ISSUE TITLE
Box selection at gitcoin.co/hackathon/golem/new

### ISSUE THREAD

**Issue by disruptionjoe** [gitcoinco/web#8048]
<!--
User said in telegram chat
"ps. the box selection today is hella buggy
i need to select the opposite box, deselect, then select the one i want"

**Desktop (please complete the following information):**

- OS:
- Browser:   Chrome
- Browser Version:

**Additional context**

MP from Golem team reported in Telegram chat - We could get more info from her.

**Comment by thelostone-mc** [comment]
Closing this out ! Please reopen with more description
