### ISSUE TITLE
All contributions coming from @gitcoinbot

### ISSUE THREAD

**Issue by 4-1-3-X** [gitcoinco/web#8050]
Hello Gitcoiners,

The latest contributions are all coming from the @gitcoinbot account. It is affecting the matching amount.

Thank you.

![Screenshot 2020-12-07 131645](https://user-images.githubusercontent.com/37280397/101406591-7f77c800-388e-11eb-8b4e-acc6f8e2c919.png)

**Comment by owocki** [comment]
hey ; i think this is just users using the 'anonymize my contribution' functionality. the match will still come form the contributor who contributed tho

**Comment by 4-1-3-X** [comment]
Hey Kevin, I don't think so, it's happening to every grant, starting from about 20 hours ago.

**Comment by owocki** [comment]
@thelostone-mc i mentioned this to you on the internal slack channel last night + you claimed it was working as desired. but for some reason a ton of contributions DID switch over to being gitcoinbot after the most recent deploy .. any reason why?

**Comment by thelostone-mc** [comment]
Yeah ! looks like we had a bug in our code which was defaulting contribution for 20 hours!
We hot patched the fix and rolled it out
The activities created during those 20 hours were defaulted to gitcoinbot 

If you check , the latest contribution in https://gitcoin.co/grants/366/eth-memes-twitter is fine.
@4-1-3-X just to re-iterate what owocki said, internally when we calculate we take into account the contribution from the actual contributor. so you're CLR match will not be affected.

Sorry about the confusion ! 😅

**Comment by thelostone-mc** [comment]
Closing this out for now ! But do reopen if you have any more questions
