### ISSUE TITLE
Can't connect twitter

### ISSUE THREAD

**Issue by LuukDAO** [gitcoinco/web#8051]
Hey! 

I'm trying to connect [THIS Twitter](https://twitter.com/Cura_DAO) to [THIS Grant](https://gitcoin.co/grants/1325/kolektivo-regenerative-economy-in-curacao), but it doesn't seem to work. 

I gave up last round, but would love to connect this time!

Could you help me out? Thanks!

Cheers

**Comment by octavioamu** [comment]
Edit your twitter to just the username and try again please

**Comment by thelostone-mc** [comment]
it's been verified now @LuukDAO ! ^_^ 

![Uploading image.png…]()
