### ISSUE TITLE
Request to move my grant from Category for the GR8

### ISSUE THREAD

**Issue by dievardump** [gitcoinco/web#8054]
This is a request to change my Grant Category for the GR8

### What 

My grant is https://gitcoin.co/grants/1530/beyondnft

### Why

I created my Grant for the Matic Build'n'Earn round 2, however the Matic Build'n'Earn round 2 is done and my Grant fall in the Dapp category of GR8 so I would like for it to be moved to this category while it's still early in the GR8.

**Comment by porobov** [comment]
Same here https://gitcoin.co/grants/281/upala-price-of-forgery-digital-identity

**Comment by thekidconnect** [comment]
same i need to move my category https://gitcoin.co/grants/982/future-modern-x-panvala-league-grant. this should be easier or just not necessary in the first place

**Comment by levalleux-ludo** [comment]
Hi !
Please could you do it for my grants as well:
https://gitcoin.co/grants/1492/defi-venture

**Comment by thesachinmittal** [comment]
> This is a request to change my Grant Category for the GR8
> 
> ### What
> My grant is https://gitcoin.co/grants/1530/beyondnft
> 
> ### Why
> I created my Grant for the Matic Build'n'Earn round 2, however the Matic Build'n'Earn round 2 is done and my Grant fall in the Dapp category of GR8 so I would like for it to be moved to this category while it's still early in the GR8.

I have moved it to Dapp tech @dievardump

**Comment by thesachinmittal** [comment]
> Same here https://gitcoin.co/grants/281/upala-price-of-forgery-digital-identity

Moved this grant to dapp tech.

**Comment by thesachinmittal** [comment]
> same i need to move my category https://gitcoin.co/grants/982/future-modern-x-panvala-league-grant. this should be easier or just not necessary in the first place

Which category would you like your grant in, you can check here. https://gitcoin.co/grants/

**Comment by thesachinmittal** [comment]
> Hi !
> Please could you do it for my grants as well:
> https://gitcoin.co/grants/1492/defi-venture

Changed it to Dapp tech round. @levalleux-ludo

**Comment by levalleux-ludo** [comment]
> > Hi !
> > Please could you do it for my grants as well:
> > https://gitcoin.co/grants/1492/defi-venture
> 
> Changed it to Dapp tech round. @levalleux-ludo

Thanks a lot @thesachinmittal !

**Comment by thekidconnect** [comment]
> > same i need to move my category https://gitcoin.co/grants/982/future-modern-x-panvala-league-grant. this should be easier or just not necessary in the first place
> 
> Which category would you like your grant in, you can check here. https://gitcoin.co/grants/

community, if that works

**Comment by dievardump** [comment]
Thank you very much, I can close now.
