### ISSUE TITLE
Gitcoin grant metamask fail - cannot read property '0' at undefined

### ISSUE THREAD

**Issue by jought6** [gitcoinco/web#8059]
**Describe the bug**

Gitcoin grant metamask fail - cannot read property '0' at undefined on any token when trying to fund a grant
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: chrome
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by jought6** [comment]
On standard checkout.

Getting similar error messages when attempting zk sync as well

**Comment by jought6** [comment]
Cannot read property 'zkSyncBatchCheckout' of undefined

**Comment by thelostone-mc** [comment]
this has been fixed and deployd !thanks for the report @jought6
