### ISSUE TITLE
Integrate BUSD for bounties and hackathons

### ISSUE THREAD

**Issue by chibie** [gitcoinco/web#8062]
### Why Is this Needed

*Summary*:
This integration is to allow users on the platform use the BUSD token for 
* Bounties 
* Hackathons

### Description

*Type*: Feature

Sequel to #7730 

### Current Behavior
No existing implementation. Users cannot pay with BUSD

### Expected Behavior
Refer to #7730 

### Definition of Done
One or more successful BUSD bounties, yea?

### Additional Information
* Binance chain explorer to sync payouts:
**Mainnet:** https://bscscan.com/
**Testnet:**  https://testnet.bscscan.com/

* Binance Wallet:
**API:** https://docs.binance.org/smart-chain/wallet/wallet_api.html
**Extension:** https://docs.binance.org/smart-chain/wallet/binance.html

**Comment by chibie** [comment]
BUSD token => https://bscscan.com/token/0xe9e7cea3dedca5984780bafc599bd69add087d56

**Comment by frankchen07** [comment]
binance bounties bug deadline / integration finish 1/19 - 1/21
demo with clients 1/21 - 1/23
staff flag 1/23
release date 1/25 is ideal, 1/28 last call
put up issues 1/25 or 1/28 to 1/31
hackathon start 2/1 - 2/21

===

regression on 1/8 and deploy on 1/11

**Comment by chibie** [comment]
here's a gist concerning the pending binance issue -> https://gist.github.com/aamustapha/3cd028879b4721693d120d6224f8f944 

the discussion is based on the error below,

![image](https://user-images.githubusercontent.com/6025509/105052523-46776980-5a70-11eb-8a89-bcd54b263363.png)
