### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by RallyCreatorCoins** [gitcoinco/web#8071]
### Why - It says the emoji code isn't there, but it is... 

https://i.imgur.com/eOsHfC3.png
https://i.imgur.com/GzDJt0O.png

Please verify our grant :)

Thanks!

**Comment by thelostone-mc** [comment]
Could you share tweet link + grant link ?

**Comment by RallyCreatorCoins** [comment]
It's been fixed, thanks!
