### ISSUE TITLE
Payout doesn't work

### ISSUE THREAD

**Issue by spape** [gitcoinco/web#8076]
**Describe the bug**
Clicking on "Payout" (bounty) does nothing.

**To Reproduce**
Go to resolved bounty, click "payout bounty", select amount, try to click on "Payout"

**Expected behavior**
Expect meta mask to open so that I can payout.

**Screenshots**
<img width="1488" alt="Screen Shot 2020-12-10 at 09 14 57" src="https://user-images.githubusercontent.com/851393/101756664-885ada80-3ad6-11eb-896c-7dc686b7711e.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave
- Browser Version: 1.17.75. Chromium

**Additional context**

Metamask

**Comment by thelostone-mc** [comment]
Could you make sure 
- you are connected to mainnet 
- wallet is unlocked & connected 

A screenshot of the navbar would help also

**Comment by thelostone-mc** [comment]
We rolled out a fix for this ! This should be resolved now
It happens cause wallet connect is not connected and the user attempts to payout
The modal should popup asking the user to connect their web3 wallet now
