### ISSUE TITLE
Logo width is incorrect

### ISSUE THREAD

**Issue by sethmcleod** [gitcoinco/web#808]
### User Story

As a user I can view the logo in it's correct size.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: It looks like the logo is being squeezed into it's container, which is messing up the proportions. One way to fix this would be to remove the `max-width: 100%` rule for that element, as shown in the video recording below.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior

Logo img width is incorrect.

### Expected Behavior

Logo img width is correct.

### Reproduction &  Solution

https://www.useloom.com/share/93c2ba1e3f5a465da324669265c071fe

### Definition of Done

Logo is not stretched on desktop or mobile.

**Comment by mkosowsk** [comment]
@sethmcleod nice find! Want 0.05 ETH for your discovery and documentation of a bug on the platform per #760? Doing a pilot studying on incentivizing the community to bug hunt and improve the platform :)

**Comment by sethmcleod** [comment]
Thanks @mkosowsk! I think your bug bounties model is spot-on, but save the ETH for the next someone who finds a _real_ bug. I feel like this is too simple to warrant a payout ;)

**Comment by mkosowsk** [comment]
@sethmcleod sure bet, but the pilot study ends Tuesday at midnight... if not all bounties are claimed by then there's 0.05 ETH with your name on it :)

**Comment by mbeacom** [comment]
Resolved via #807
