### ISSUE TITLE
Move Grant to Different Category

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#8081]
### Who/What/Why
Per @thesachinmittal, I am opening this issue to change the grant category for Meme of the Day. We were previously in the Matic Build-N-Earn category, but that round ended and we would like to be in the APOLLO round. Active grant link: https://gitcoin.co/grants/1413/meme-of-the-day

I previously created two other grants that I closed without any funding. This was before I knew the best practice is to continue with a single grant by changing the category.

Would you please also delete the following inactive grants so they do not show up in Gitcoin searches?:
https://gitcoin.co/grants/1533/meme-of-the-day
https://gitcoin.co/grants/1593/meme-of-the-day

Thank you in advance!

**Comment by thelostone-mc** [comment]
https://gitcoin.co/grants/1413/meme-of-the-day -> shifted to apollo (this takes an hour to reflect)


https://gitcoin.co/grants/1533/meme-of-the-day -> deleted
https://gitcoin.co/grants/1593/meme-of-the-day -> deleted

**Comment by BTCAlchemist** [comment]
@thelostone-mc Thank you for working on this. For some reason, my grant account did not receive the CLR match from the Matic round (closed on December 6) before changing to APOLLO round. From what I recall, there were ~300 DAI from the Matic grant round that should have been matched. How may we recover those matched funds from the previous round?

**Comment by BTCAlchemist** [comment]
Also, for some reason, I do not see the [zkSync transactions](https://zkscan.io/explorer/accounts/0x2a14cac750aaf659d3617487E0629D57242E4C71) from Dec. 1 and Dec. 15 in my [grant wallet](https://etherscan.io/address/0x2a14cac750aaf659d3617487e0629d57242e4c71#tokentxns). Is zkSync supposed to clear after 10 minutes?

**Comment by BTCAlchemist** [comment]
@thesachinmittal @thelostone-mc Per the two comments above, would you please re-open this issue and help my grant team recover the lost CLR match from the Matic round?
