### ISSUE TITLE
Failed Grant Donation Assumed Successful

### ISSUE THREAD

**Issue by AlphaSerpentis** [gitcoinco/web#8084]
**Describe the bug**

Sending a failed transaction still shows up on your "Spent" panel under your profile. It doesn't appear the website waits for the transaction to successfully be executed and confirmed.

Without such a check, it sent out to the Gitcoin website showing I had donated to their grant, but unfortunately, that transaction on the network actually failed. 

**To Reproduce**

1.) Select grants to donate to. (9 were chosen @ $1/grant and 15% donation)
2.) Use the standard checkout option (non-L2).
3.) To force a failure, set the gas limit to where an "out of gas" error will be thrown. (For some reason, MetaMask auto-set the gas limit to around 89k).

**Expected behavior**

A failing transaction shouldn't appear under the "spent" section of a user's profile. For example, a failing transaction donating $9 shouldn't show up as me spending $9. 

**Screenshots**

Screenshot showing two transactions, although one of them had failed: https://i.imgur.com/UNbsgYn.png

**Desktop (please complete the following information):**

- OS: Windows 10 Home Build 19042
- Browser: Brave
- Browser Version: V1.18.70

**Additional context**
Two transactions that are added to the spent amount:
- Failed transaction: https://etherscan.io/tx/0x1d0efda17e72a7ee1518e1c7824db07763290565995c26b5eb388378bfcab30a
- Successful transaction: https://etherscan.io/tx/0x6642e80cb42280b628ed484ad99af6ef427cb0e21e0b135004ab4d05aefc11d0

**Comment by owenshen24** [comment]
I've also encountered this issue when a transaction ran out of gas. It still shows up on my feed as a donation, even though it did not go through.
