### ISSUE TITLE
The Bot Took The Credit

### ISSUE THREAD

**Issue by ryanchrypto** [gitcoinco/web#8085]
**Describe the bug**

A few days ago (Dec 7th), the Gitcoin bot was sneaking the credit for other people's contributions, and now that credit is still not showing up in their profiles (including mine). It seems to have only been a short spree of credit theft because I was able to receive credit for my contributions today (3 more) and I received credit for all other contributions that I have made this round.

Please see screenshot below from a few days ago (Dec 7th) for two contributions that I made that the Gitcoin bot took credit for.

**To Reproduce**

Seems to be working alright today...

**Expected behavior**

I believe I should have received credit for these contributions if my ETH was used...

**Screenshots**

![Screenshot from 2020-12-07 16-34-49](https://user-images.githubusercontent.com/12519942/101856934-2ff9fc00-3b1b-11eb-9a94-69c1e1e30e42.png)

**Desktop (please complete the following information):**

- OS: Linux/Ubuntu
- Browser: Brave
- Browser Version: Latest

**Comment by danlipert** [comment]
Hey Ryan -

Sorry about that! We had an temporary issue where some grant contributions were being marked as "anonymous" aka Gitcoinbot during that time when they shouldn't have been. I went ahead and fixed the contributions data so it should now show up in your profile correctly. Let me know if you encounter any other issues and thanks for your bug report.

**Comment by ryanchrypto** [comment]
Still not showing up after hard refresh.... https://gitcoin.co/ryanchrypto

The two contributions from the screenshot above are still missing. Let me know if you see otherwise.

**Comment by ryanchrypto** [comment]
@danlipert Thanks for the info. Not a big deal but the information is still not showing up so might still be an open issue / bug.
