### ISSUE TITLE
User not able to create a grant 

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#8088]
**Describe the bug**

https://gitcoin.co/darkmasta reported that he is not able to create a grant and is being asked to "Enable your organization profile".
He is having this issue in the console: `DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`
Apparently nothing happens when you click save

**To Reproduce**

@darkmasta might know

**Expected behavior**

Able to create a grant

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
just tested out the flow and it seems to work !
Closing this for now but @darkmasta do let us know if you still can't create a grant
