### ISSUE TITLE
Banner has old information & needs updating

### ISSUE THREAD

**Issue by disruptionjoe** [gitcoinco/web#8095]
Pretty straight forward. Banner on a page needs update:

https://share.getcloudapp.com/2Nu0qdk9

Looks like they were on:  /grants/524/clrfund

Got this from Hotjar!

**Comment by thelostone-mc** [comment]
![image](https://user-images.githubusercontent.com/5358146/102357610-84e2ba00-3fd4-11eb-9da1-01a9226536bf.png)
