### ISSUE TITLE
Fat finger donation.

### ISSUE THREAD

**Issue by dvncan** [gitcoinco/web#8105]
Hello, 

Yesterday while contributing to the Blockchain Education Network grants I double donated the same amount twice to the contract. Only 1 of the donation amounts has been associated with my profile.

Here are the transactions:

https://etherscan.io/tx/0x7d40df9a57a4384acc795e2f5c026e02f2df5eafece3204f7ebc4e7affd7006f

https://etherscan.io/tx/0xee231518643ab0e47f2aa4d8fb4edfdaa24c48deb2559531b0e43a44ec37a660

![image](https://user-images.githubusercontent.com/44993570/102027813-7c337f00-3d5b-11eb-9055-01c5f2de2d7d.png)

**Comment by dvncan** [comment]
https://etherscan.io/address/0x66aa8bee5366b6b48811ae0dac9fe5e1eefe1621#internaltx

![image](https://user-images.githubusercontent.com/44993570/102305777-ab8deb80-3f15-11eb-84e6-31a4e486c07b.png)

**Comment by dvncan** [comment]
My wallet is

0xf3e4D421E826a03848254095455ce818Ace25AF6

**Comment by Kweiss** [comment]
Hey there - can you add the missing Tx here?
https://gitcoin.co/grants/add-missing-contributions

Please re open this if you run into problems.

**Comment by dvncan** [comment]
The two transactions are:

0x02ca23326cf9407498216b147b575db864ea5de344ff6a190f3c0023b159da38

0xeb01e2fab174b073178724d203732db458ed65b462b02e63a224177155364003

I am unable to submit the form…

My wallet is 0xf3e4d421e826a03848254095455ce818ace25af6

*Duncan Brown ( https://www.linkedin.com/in/duncan-brown-023791116/ )
*
Solutions Engineer

M: +1 (647) 901-8681

*Botpress Technologies, Inc.*
Making machines understand humans
175-2480 ch. Sainte-Foy
Québec (Québec) G1V1T6 Canada

( https://botpress.com/ )

Linkedin ( https://www.linkedin.com/company/botpress ) | Github ( https://github.com/botpress/botpress ) | Twitter ( https://twitter.com/getbotpress ) | Website ( https://botpress.com/ )

( https://botpress.com/download?utm_source=gmail&utm_medium=email&utm_campaign=team )

Sent via Superhuman ( ***@***.*** )

**Comment by dvncan** [comment]
Hey,

Have you seen this email?

duncan

*Duncan Brown ( https://www.linkedin.com/in/duncan-brown-023791116/ )
*
Solutions Engineer

M: +1 (647) 901-8681

*Botpress Technologies, Inc.*
Making machines understand humans
175-2480 ch. Sainte-Foy
Québec (Québec) G1V1T6 Canada

( https://botpress.com/ )

Linkedin ( https://www.linkedin.com/company/botpress ) | Github ( https://github.com/botpress/botpress ) | Twitter ( https://twitter.com/getbotpress ) | Website ( https://botpress.com/ )

( https://botpress.com/download?utm_source=gmail&utm_medium=email&utm_campaign=team )

Sent via Superhuman ( ***@***.*** )
