### ISSUE TITLE
Contributed to three grants of $10 Dai apiece in one checkout transaction and it is not showing up in my funding history

### ISSUE THREAD

**Issue by LawrenceOfDaniel** [gitcoinco/web#8106]
Here is the transaction hash that confirms the transaction. 0x691275baf90951126f56755b5f0876dedb7a519461af15d31c298570e6e678da

I made two separate $10 dai donations that went through and appear in my funders history right before the transaction above along with two smaller gitcoin dev fund support transactions.  The last transaction however is not appearing in my funders history.  I also did not get an email confirmation on it as well.

However roughly $30 dai was spent and confirmed on chain.  Just want to make sure I get credit for this transaction.  I should have a total of 7 gitcoin grants supported.

Thanks

LawrenceOfDaniel
0x072938db4dd5c5f25b77d11fbecdb35a0f14e022

**Comment by xmaysonnave** [comment]
Same issue here. Submitted 10 dai.transaction confirmed. Got an error message like unable to submit pledge. Thanks to confirm. Transaction hash:
0xfb836becd6d605833166a7e29b69dc147c4000965113b1217b955c201289d257

**Comment by mds1** [comment]
@xmaysonnave Your transaction hash is not a contribution via Gitcoin, it is simply a regular DAI transfer. Perhaps you pasted the wrong transaction hash?

@LawrenceOfDaniel Can you clarify a bit more? Your transaction hash only shows 3 contributions, but you say there should be 7. Are the three from that transaction hash the only ones not appearing on the site?

**Comment by mds1** [comment]
@LawrenceOfDaniel Contributions have been ingested for the transaction hash you've shared
