### ISSUE TITLE
Checkout not completed after zksync transfer page closed

### ISSUE THREAD

**Issue by GWintery** [gitcoinco/web#8109]
**Describe the bug**

After completing transfer on the zksync page and pressing the close button. the gitcoin page does not reflect the checkout.

**To Reproduce**

after transfer is done, press the close button on the zksync checkout page

**Expected behavior**

gitcoin page says checkout completed

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Browser Version: Version 88.0.4324.41 (Official Build) beta (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hey @GWintery! Can you send me your transaction hash so I can look into this? Feel free to message me on Twitter at @msolomon44 or Telegram at @msolomon4 if you don't want to share it publicly

**Comment by thelostone-mc** [comment]
@GWintery bumping this up ! Could you share the deets @mds1 asked above and we can check it out

**Comment by mds1** [comment]
@thelostone-mc Details were sent on telegram! We’ll be ingesting these contributions manually once the round ends

**Comment by mds1** [comment]
Contributions have been ingested!
