### ISSUE TITLE
seperate repo owners / developers earlier in the landing page

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#811]
have a clear CLA on the landing page to browse site as a repo owner or a developer. this would break them up into seperate landing pages
1. for developers
2. for repo owners

per dean ramadan call

**Comment by owocki** [comment]
cc @PixelantDesign -- this came up on the dean call today

**Comment by thelostone-mc** [comment]
Eventually it'd be something along the lines off 

0. A default generic one to direct them to repo / dev ? 
1. for repo owners
2. for devs
   a. for every tech stack 

Feels a lil overwhelming!!
Has this been done in other products ?

**Comment by owocki** [comment]
yep thats the plan

**Comment by mkosowsk** [comment]
@thelostone-mc looks like Upwork just goes for the finding of freelancers angle on their main page. For Gitcoin, that would be the repo owner perspective... not saying it's correct, just another data point 🤔
