### ISSUE TITLE
Request to move my grant from Category for the GR8

### ISSUE THREAD

**Issue by jacekv** [gitcoinco/web#8111]
Hi there :) 
I would like to know if it is possible to combine two grants?
I created on grant fo the Matic Build'n'Earn round 2, however, the Matic Build'n'Earn round 2 is over.
In order to participate in the GR8 I created a new grant and have already 2 contributors. 

Is it possible to combine those two grants?

What
The Matic Build'n'Earn round 2 grant is: https://gitcoin.co/grants/1490/git3
The GR8 grant is: https://gitcoin.co/grants/1712/git3

**Comment by thelostone-mc** [comment]
At this point @jacekv ! it isn't possible -> we force grants to pick one grant category 
This is something we would like try and support to in the upcoming rounds where a grant can have multiple categories

**Comment by jacekv** [comment]
Alright, thanks for the info :)
