### ISSUE TITLE
Out of Gas During Donation

### ISSUE THREAD

**Issue by owenshen24** [gitcoinco/web#8112]
I tried to donate 3 Badger to Snapshot, and I got the following Out of Gas error [here](https://etherscan.io/tx/0x44e081d059a4880920598bc5a80fa90048db0dcd52bd4bb192668afc77308c24).

I'm fairly sure this was the gas estimation provided by the UI. It went through after I resubmitted with a higher gas limit.

**Comment by mds1** [comment]
Closed by #8119
