### ISSUE TITLE
Donated, metamask transfer is success, gitcoin has no transaction/donation

### ISSUE THREAD

**Issue by Gacisan** [gitcoinco/web#8113]
Hey, 

about 24h ago i have donated to 2 project, paid with ETH with my metamask, payment went thru (success on etherscan), and gitcoin but i dont have it in gitcoin that ive actually contributed anything, nor in transaction.

Here is hash: 0x6aeecb71ea43e8fee0e476beba85dd0539db293306c3d586629145bfdc379e08 

What should i do? 

Thank you and best regards

**Comment by mds1** [comment]
Hey @Gacisan, we'll look into this! Your transaction did go through, and we'll make sure the contributions get matched, but you may not see an update in the UI until after the round

**Comment by mds1** [comment]
Contributions have been ingested!

**Comment by Gacisan** [comment]
Hey, im opening this thread again, i missed the Badger airdrop because of this hiccup. 
Contribution was matched, but you have missed the data on the snapshot you provided to the badger team. 

Can we do something?
