### ISSUE TITLE
Trying to donate to 98 grants with zksync doesnt work

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#8114]
I put the deets into their github cause it's their issue... but wanted to keep you in the loop

https://github.com/matter-labs/zksync/issues/266

**Comment by thelostone-mc** [comment]
Thanks @GriffGreen ! We'll hit zksync up from our side as well

**Comment by mds1** [comment]
Hey @GriffGreen thanks for the heads up, and for creating an issue on their repo. 

Once we learn more about the limitation we should account for this on the Gitcoin side also, e.g. by limiting the number of items in your cart if you use zkSync checkout

**Comment by thelostone-mc** [comment]
For anyone else who ends up on the issue, the limit is 50
https://github.com/matter-labs/zksync/issues/266#issuecomment-745754273

we'll add some changes before the next round to handle this elegantly
