### ISSUE TITLE
My zksync won't check out--seems my cart is stuck

### ISSUE THREAD

**Issue by DeFi-Dad** [gitcoinco/web#8118]
Hi all, I have problems with both Standard and zkSync checkout atm for the wallet under defidad.eth. I am trying to donate to these folks but I've got 2 issues.

See the 2 screenshots: i) for zksync and ii) for standard checkout

I've been donating daily but this just happened last 24 hours.
<img width="1164" alt="zksyncissue" src="https://user-images.githubusercontent.com/56087134/102225429-368ac980-3eb5-11eb-8e24-33e811ef705c.png">

<img width="534" alt="Screen Shot 2020-12-15 at 9 09 27 AM" src="https://user-images.githubusercontent.com/56087134/102225548-59b57900-3eb5-11eb-8cee-0c3629253b75.png">

Lastly, here's the txn ID for me setting my spend limit on standard checkout: 0xdded4fb7640975fbc518ac332361cfe2c70524407375d147035a20b57c84fe54

https://gitcoin.co/grants/cart/bulk-add/1403;1;283,1749;1;283,1277;1;283,294;1;283,1167;1;283,811;1;283,152;1;283,1594;1;283,467;1;283,759;1;283,49;1;283,156;1;283,840;1;283,845;1;283,1129;1;283,1204;1;283,1213;1;283,1219;1;283,1210;1;283,1225;1;283,1249;1;283,1250;1;283,1379;1;283,1554;1;283,1692;1;283,1701;1;283,1716;1;283,1719;1;283,1751;1;283,1732;1;283,1724;1;283,1754;1;283,202;1;283,765;1;283,1047;1;283,934;1;283,159;1;283,1657;1;283,1541;1;283,1592;1;283,1534;1;283,1162;1;283,207;1;283,:defi-dad

**Comment by owocki** [comment]
@mds1 any idea here?

**Comment by owocki** [comment]
@DeFi-Dad you on chrome/metamask on mac?  if not what browser combo u on?

**Comment by mds1** [comment]
Hey @DeFi-Dad! Based on the error it looks like you were donating to this grant, is that correct? https://gitcoin.co/grants/1754/the-three-cryptograces-2-blockchain-ladies

The issue here is that the grant receiving address is set to `rtbynelly`, which is an invalid address. I'm guessing this is supposed to be `artbynelly.eth`, which resolves to 0x91e03CA709C1950e621060e64ddEbdc3B7C6deDE.

@owocki @octavioamu @thelostone-mc Can one of you confirm with the grant creator that this is the desired address, and if so update that in the grant

**Comment by makoto** [comment]
Same for me but different error message.

https://twitter.com/makoto_inoue/status/1338799579505053697
https://etherscan.io/tx/0x500c13ab9deee79537e5ed123f0db279682ca3700ed0d1682122b4dde5a29f9d

I already unlocked and deposited, but still shows "Deposit" button with incorrect amount (0.27 DAI even though I deposited nearly 50 DAI).

<img width="528" alt="Screenshot 2020-12-15 at 15 28 51" src="https://user-images.githubusercontent.com/2630/102235474-440e7680-3eea-11eb-8491-55a9377d3f7e.png">

**Comment by mds1** [comment]
@makoto Most likely gas costs have risen since you made the deposit, so you’re now 0.279 DAI short as a result. As an alternative to a second deposit, you can reduce the amounts in your cart slightly so you have additional DAI available for fees

**Comment by owocki** [comment]
@mds1 just updated that grant.  if @DeFi-Dad @makoto can remove/re-add that grant to cart, i think they should be good.

@mds1 can we add validation to the addr field so that if someone enters an invalid addr this doesnt block checkout?  i think @octavioamu maybe added some validation at some point in the past, not sure. but seems this is still an active issue

**Comment by makoto** [comment]
It magically fixed by itself!

**Comment by owocki** [comment]
```
select 
	t1.id,
	grants_grant.id,
	t1.admin_address,
	grants_grant.admin_address
from (
select 
	regexp_matches(admin_address, '^0x[a-fA-F0-9]{40}$', 'g'), 
	id,
	admin_address 
	from grants_grant 
) t1 right join grants_grant on t1.id = grants_grant.id
where t1.id IS NULL;
```

looks like theres some other live grants that have invalid ethereum addresses. im going to be setting these grants as inactive 

```
18
19
948
1024
1062
1085
1124
1144
1231
1269
1270
1465
1466
1468
1476
1477
1478
1479
1481
1484
1486
1489
1491
1500
1501
1504
1513
1532
1560
1562
1567
1586
1603
1623
1627
1741
1750
1765
1788
1806
```

**Comment by owocki** [comment]
```
1806 True
1788 True
1765 True
1750 False
1741 True
1627 False
1623 False
1603 True
1586 False
1567 True
1562 True
1560 True
1532 True
1513 True
1504 True
1501 True
1500 True
1491 True
1489 True
1486 True
1484 True
1481 False
1479 True
1478 True
1477 True
1476 True
1468 True
1466 False
1465 True
1270 True
1269 False
1231 True
1144 True
1124 True
1085 True
1062 True
1024 True
948 True
19 True
18 True
```

grants.pk + whether they were active at the time of me running a script that sets them as inactive

**Comment by DeFi-Dad** [comment]
fixed guys! yes just that one grant was being the problem.
