### ISSUE TITLE
Stuck on "Fetching Cart Data"

### ISSUE THREAD

**Issue by johnx25bd** [gitcoinco/web#8122]
**Describe the bug**
I try to load my cart to check out and fund Gitcoin grants in Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
 - and the page gets stuck on the `.rhombus-spinner`  "Fetching cart data". I checked in with @gitcoin on Twitter, was advised to deactivate the ad blocker - which I did, and still ran into issues. 

**To Reproduce**

For me: Add grants to the cart, then go to https://gitcoin.co/grants/cart in Google Chrome (though probably my computer - can't imagine this is happening on all Google Chromes).

**Expected behavior**

Should load the cart and give me a chance to review the items, and - most importantly - send in the funds!

**Screenshots**

<img width="1680" alt="Screen Shot 2020-12-15 at 5 27 14 PM" src="https://user-images.githubusercontent.com/41551283/102250607-a623a780-3efb-11eb-8b76-053676d396e2.png">

**Desktop (please complete the following information):**

- OS: OS High Sierra 10.13.6
- Browser: Google Chrome
- Browser Version: Version 87.0.4280.88 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Sounds like the same issue as https://github.com/gitcoinco/web/issues/8041. Can you try the solution listed there, which is: 

> A way to solve this could be press share cart, paste that on the same tab's search bar, and press enter, the new data for those grants will be fetched, now with tenants field

**Comment by johnx25bd** [comment]
I didn't work :/
