### ISSUE TITLE
Change payout address - grants 

### ISSUE THREAD

**Issue by anettrolikova** [gitcoinco/web#8127]
I would like to change payout / receiver address for [Ethereum Magicians grant](https://gitcoin.co/grants/223/ethereum-magicians). We created a new multisig account for managing funds. New address 0xB35cD25e91B376EAfbA79AbE71D78814dEC3401a

Thank you Gitcoin team 🙏 ✨

**Comment by developerfred** [comment]
@thelostone-mc @Solexplorer

**Comment by thelostone-mc** [comment]
Done @anettrolikova ! 
Haha thanks for the tag @developerfred 

![image](https://user-images.githubusercontent.com/5358146/102356671-865fb280-3fd3-11eb-9842-d50c2a05f673.png)

**Comment by anettrolikova** [comment]
Thank you so much @thelostone-mc ! 🤗
