### ISSUE TITLE
Unlink Inaccessable BrightID Account and Link New One (GR8)

### ISSUE THREAD

**Issue by lemogras** [gitcoinco/web#8128]
### Who

I'm owner of DeFi Library grant.

### What 

I want to unlink previously linked BrightID account of mine and to link new verified BrightID of mine.

### Why

I had linked my BrightID account in the past and not got verified. Then I deleted the app. Recently I re-download and create new account in BrightID app. However, since I have linked old account to Gitcoin, there is no option to delete that link and generate new link btw gitcoin account and new BrightID account.

**Comment by thelostone-mc** [comment]
Did this get resolved @lemogras  ? I know @Solexplorer was helping someone with this exact request

**Comment by Solexplorer** [comment]
@thelostone-mc Yes, I was helping him, please close this issue
