### ISSUE TITLE
User cancelled grant but it wasn't cancelled

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#8130]
**Describe the bug**

So @graham-u cancelled this grant: https://gitcoin.co/grants/1069/feel-the-yearn but it wasn't cancelled, something must be gone wrong at cancellation stage because you can still donate to it. At this point he prefers to have the grant open but he just want s to be sure that he will receive the clr matching. @octavioamu What do you think? :)

**To Reproduce**

Don't know how to reproduce

**Expected behavior**

The grant should have been cancelled

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Comment by graham-u** [comment]
Link to cancel event: https://gitcoin.co/townsquare?tab=activity:451665

**Comment by thelostone-mc** [comment]
We did have a few issues with edit flow 2 weeks ago and I'm guessing this got caught in that !
It should work now @graham-u if you wanna cancel it 

The grant is open -> aka it will continue to receive funds and will be eligible for the CLR match ^_^ (as long as you don't cancel it )
