### ISSUE TITLE
CLR Matching Amount (GR8)

### ISSUE THREAD

**Issue by lemogras** [gitcoinco/web#8132]
We have 104 contributors so far with 1 DAI = 10 DAI Matching so far. However it seems like our matching amount is lower than expected and lower than grants with same statistics.

I might be missing a point about quadratic matching but i think contributor numbers should tell something. I would be glad if you check any bugs etc. If I'm wrong, sorry for your precious time.

My grant :

https://gitcoin.co/grants/1219/defi-library

Compared with :
https://gitcoin.co/grants/1311/cryptoouf-a-blog-about-defi
https://gitcoin.co/grants/668/fightpandemics
https://gitcoin.co/grants/1264/talking-crypto-with-gabriel
https://gitcoin.co/grants/1577/ethcc-by-ethereum-france-panvala-league

**Comment by thelostone-mc** [comment]
@lemogras the code shouldn't be an issue here

contributor numbers does influence the pot distribution but other attributes like the amount contributed by each contributor, 
The contributor's history  aka how they've contributed to other projects wrt to other contributors also influence the match pot. I'm guessing that's why you see the matching amount lower than the projects you listen below 

The code we use is over at https://github.com/gitcoinco/web/blob/master/app/grants/clr.py

**Comment by octavioamu** [comment]
Probably is due to trust level you can increase your on the trust tab in your profile https://gitcoin.co/profile/trust

**Comment by lemogras** [comment]
> Probably is due to trust level you can increase yours in the trust tab on your profile https://gitcoin.co/profile/trust

I've verified myself with all trust option except POAP.

**Comment by lemogras** [comment]
> @lemogras the code shouldn't be an issue here
> 
> contributor numbers does influence the pot distribution but other attributes like the amount contributed by each contributor,
> The contributor's history aka how they've contributed to other projects wrt to other contributors also influence the match pot. I'm guessing that's why you see the matching amount lower than the projects you listen below
> 
> The code we use is over at https://github.com/gitcoinco/web/blob/master/app/grants/clr.py

I see, so contributor history and profile quality are factors in QF. I didn't know that. Thanks for the info.

**Comment by lemogras** [comment]
Still thinking that CLR amount should be at least 9*119 for this state. Because +9 DAI is the output of the CLR calculation after consideration of contributors profile.

![Ekran Resmi 2020-12-17 21 17 00](https://user-images.githubusercontent.com/9808986/102526975-8207c800-40ad-11eb-9e93-ed85233ea29c.jpg)

**Comment by lemogras** [comment]
At final stage: CLR amount is almost 1:1.5 for 122 different contributors even if it says 1 = 9 (+8). It feels like there is something wrong.

![Ekran Resmi 2020-12-18 11 17 08](https://user-images.githubusercontent.com/9808986/102591209-b4074180-4122-11eb-921f-cc29004e03cd.jpg)

**Comment by thelostone-mc** [comment]
@lemogras So like @octavioamu mentioned -> even the contributors need to verify themselves on a contribution 
If i contribute 100 DAI and I'm not verified -> my match could equate to 50 DAI 
and if you contribute 100 DAI but you are verified -> your match could equate to 60 DAI
