### ISSUE TITLE
remove the bounty 10% fee + just make the main bounty explorer free of charge

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8134]
remove the bounty 10% fee + just make the main bounty explorer free of charge
- no fee collection
- contest/cooperative bounties remain gated + only for gitcoin pro
- anything else @ceresstation ?

**Comment by GriffGreen** [comment]
YAY!!! NICE!

**Comment by thelostone-mc** [comment]
Do we want to 
- keep the code in (aka revisit later) / purge it entirely ? (code + data)
- What about the feature your bounty

**Comment by Kweiss** [comment]
- Feels like we can remove the code as we will have a commit we can reverse if we need it in the future, right?
- The "feature your bounty" should still be paid.

**Comment by thelostone-mc** [comment]
sounds good to me 🙌

**Comment by Kweiss** [comment]
@thelostone-mc - Let's sync before we deploy this change please. We need to ensure communication is in place.
