### ISSUE TITLE
When people open the link to my LARGE cart, it says the CLR round is over

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#8135]
Sorry, in a rush so sorry for the lack of deets...

Here is the link:

https://gitcoin.co/grants/cart/bulk-add/347;1000;316,238;500;316,152;2000;316,539;9000;316,1052;100;316,63;500;316,1700;100;316,1183;100;316,1595;1000;316,1657;100;316,565;100;316,143;1000;316,622;2000;316,1415;500;316,308;3000;316,1634;100;316,437;100;316,1561;200;316,191;500;316,275;1000;316,149;1000;316,500;1000;316,551;100;316,237;300;316,1632;200;316,1101;100;316,1093;300;316,12;100;316,524;1000;316,13;1000;316,855;100;316,160;500;316,1134;200;316,1577;100;316,711;300;316,1240;100;316,1636;100;316,1592;100;316,795;5000;316,517;2000;316,1297;500;316,1141;500;316,1663;500;316,1127;9000;316,277;3000;316,668;1000;316,1609;1000;316,798;1000;316,1155;1000;316,1638;500;316,899;100;316,1118;300;316,1573;400;316,1732;1000;316,1424;300;316,1635;300;316,1643;100;316,1151;500;316,1122;100;316,1158;1500;316,775;500;316,1219;100;316,331;3000;316,1620;100;316,202;2000;316,285;500;316,816;500;316,902;300;316,231;300;316,159;1000;316,779;1000;316,235;300;316,1691;100;316,184;1000;316,590;100;316,207;100;316,515;100;316,1041;200;316,1143;100;316,1175;400;316,1250;500;316,738;200;316,1266;200;316,1403;100;316,514;300;316,1262;1000;316,806;100;316,949;300;316,1210;300;316,1554;400;316,1464;200;316,1618;300;316,848;1000;316,1574;300;316,1641;500;316,1374;500;316,1379;3000;316,1499;400;316,:griffgreen

Check the screen shots:
<img width="1273" alt="Screen Shot 2020-12-16 at 4 24 47 PM" src="https://user-images.githubusercontent.com/14945613/102408584-1e6a9580-3fee-11eb-8244-38dc75299c25.png">

**Comment by octavioamu** [comment]
deploying a fix for this, thanks for let us know. Will post when ready

**Comment by octavioamu** [comment]
@GriffGreen ok now should be working again if you click your share cart link
