### ISSUE TITLE
Improve Gitcoin grants UX to be better for non-nerds (with one specific example)

### ISSUE THREAD

**Issue by A2be** [gitcoinco/web#8136]
### User Story

[comment]: # As a non-nerd user, I want to have a chance to grok esoteric concepts so that I don't run away screaming from crypto, like most of my family and friends have.

### Why Is this Needed

"CLR" on the Gitcoin Grants round 8 checkout cart is an unexpanded, and unexplained, acronym.  Let's make crypto work for regular ppl.

*Summary*:

### Description

[Feature]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
Expand the acronym.  With a mouseover, or jsut spell it out.  Maybe a link to where one goes to read about "CLR": # (Describe what you expected to happen.)

### Definition of Done
When you can have noobs go through your user flow, and not encounter esoteric concepts, programing or front end/back end concepts, and (using your interface) explain to you what some of the esoteric stuff means; then you are starting to get there.  More of "what would Steve Jobs do?"  Less TLA (three letter acronyms): # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by A2be** [comment]
Closing my input on this UX flow bug.  The bug is real, and should be addressed by the design/UX side of the Gitcoin team to be better in round 9.

Changing browsers, and being forced to use MetaMask rather than a h/w wallet or my smart contract wallet, did provide an acceptable one-time workaround for today.

**Comment by octavioamu** [comment]
will be addressed for grants round 9 pr https://github.com/gitcoinco/web/pull/8500 live in a few days and more work will come in the next weeks also.

**Comment by thelostone-mc** [comment]
Yup like @octavioamu said ! 
This feedback was taken in and we spent the next 3 months revamping the UI to make it less confusing
I forgot to throw in the comment but this feedback was taken into account for this round.
