### ISSUE TITLE
test out autotranslate

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#814]
https://github.com/ankitpopli1891/django-autotranslate

after https://github.com/gitcoinco/web/pull/810 is merged, we should try testing out auto translate in a few target languages and see what end users think.  

for each translation?
is it accurate?  is it usable?  is it helpful?

**Comment by mbeacom** [comment]
One thing I noticed while testing is the formatting around `%(some_var)s` can come out spaced incorrectly, so after you run something like:
`python3 manage.py translate_messages -l 'pl'`
The subsequent `.po` will throw a few errors during: `python3 manage.py compilemessages` on specific lines that you need to manually go in and adjust which doesn't take a whole lot of time (I think there were 8 when I ran the above).

**Comment by owocki** [comment]
@mbeacom one workaround would be to move the pythonic vars out of the strings before we commit to a largetranslation..
