### ISSUE TITLE
Matching missing on Grants

### ISSUE THREAD

**Issue by cryptoA2Z** [gitcoinco/web#8140]
I just threw like 135 dai at gitcoin. payed 0.113 eth in gas. then went to clam badger....hunt. only to be find the message "no BADGER to be claimd".. after witch i made sure the airdrop was still ongoing. it was.

im not sure how this matching is supposed to work. but im missing some easy to follow instructions. please cosider that dyslexia is a growing problem together with ADHD and make things more intuitive.

**Comment by cryptoA2Z** [comment]
can you please help me out?

**Comment by thelostone-mc** [comment]
@cryptoA2Z Could you share the txn hash of your grant contribution ?

**Comment by Solexplorer** [comment]
@cryptoA2Z The badger will be available to claim once the grant round ends, please check this blog post by Badger: https://badgerdao.medium.com/badger-dao-to-distribute-badger-tokens-to-gitcoin-round-8-donors-ce10fdbe98af

The round will end today at 12PM EST
