### ISSUE TITLE
Grant Issue 

### ISSUE THREAD

**Issue by JDamian420** [gitcoinco/web#8141]
Contributed to 4 Grants, was charged for them, but they don't show up anywhere.
Tx ID# 0x0eec3c64aa10d186fd23346b62bf1fb4ca5c6c7d246f2db6e8d3dbde4f44f3c0

**Comment by thelostone-mc** [comment]
Can you share the list of grants and did you use zksync checkout ?

**Comment by JDamian420** [comment]
I did, but I have sorted it out. Thanks

**Comment by thelostone-mc** [comment]
sure thing ^_^
