### ISSUE TITLE
Checkout failing, funds stuck in zkSync, "API code 300; Error communicating core server"

### ISSUE THREAD

**Issue by neil-lowry** [gitcoinco/web#8143]
**Describe the bug**
Trying to check out a large Gitcoin grant cart. zkSync got to the "Step 2. Transfer" stage but then fails repeatedly (5+ times now) with this error: "TxBatch failed. Reason: zkSync API response error: code 300; message: Error communicating core server". My funds are still locked in zkSync so I seem to be unable to fall back to standard checkout.

**To Reproduce**
I'm not sure you can reproduce it. I have 77 items in the cart.

**Expected behavior**
I expected to make a successful payment.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 87.0.4280.88

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by mds1** [comment]
Hey @neil-lowry, can you try doing two separate zkSync checkouts of about 39 items each? zkSync only supports up to 50 transactions in one batch (we will make this more clear from the Gitcoin cart)

**Comment by neil-lowry** [comment]
I'm happy to do that, but right now my funds seem to be trapped in zkSync.

**Comment by StanislavBreadless** [comment]
> I'm happy to do that, but right now my funds seem to be trapped in zkSync.

If the funds have been successfully deposited to zkSync you can simply open the checkout again. (You won't have to re-deposit them)

**Comment by neil-lowry** [comment]
So remove 39 items from my cart and then check out, and the funds should still be spendable from zkSync? That seems fine if safe, I'll try that.

**Comment by StanislavBreadless** [comment]
> So remove 39 items from my cart and then check out, and the funds should still be spendable from zkSync? That seems fine if safe, I'll try that.

Yep. If want to check the funds that you have on zkSync, you can log in to zkSync [primary wallet](https://wallet.zksync.io) and you'll see the assets that you have in zkSync.

**Comment by neil-lowry** [comment]
Now, with 39 items in my cart, "Step 1: Setting things up" pauses for about 20 seconds, then fails with this message: "Failed to estimate batch transaction fee. Reason: Error: Network Error. The error above makes it either impossible to proceed to checkout or prevents the opener page from recording that you completed the checkout. You should leave the page."

I have tried this a few times, plus closing and restarting from the cart page.

**Comment by neil-lowry** [comment]
Wait, I shut my browser and restarted, and now it gets past step 1. Stay tuned.

**Comment by neil-lowry** [comment]
OK that worked. So I'm probably OK. I'll try the other 37. (There were actually 40 items in my cart.)

It looks like 5% was subtracted from each and allocated to the dev fund - probably I just neglected to uncheck that option this time through. (I was already directly donating to the dev fund.) Don't worry about it.

I'll update on the other 37 shortly.

**Comment by neil-lowry** [comment]
OK, the other 37 worked. And I see now that I did indeed neglect to set the default 5% back to 0% for the previous 40. (I had set it to 0% for the original batch of 77, but forgot to repeat that for the batch of 40.)

I do think you should highlight the 50 limit, and probably block checkout from proceeding. Anyone who's bothered to add >50 items to their cart is going to end up in a sticky situation, especially if they're doing this a few minutes before noon.

But anyway, thanks very much for the prompt help here, I'm all set.

**Comment by mds1** [comment]
Thanks for the updates, and glad to hear you're all set! Agreed with you that we should highlight the limit and prevent checkout 🙂
