### ISSUE TITLE
Failed zkSync Check out with 137 Grants in Cart

### ISSUE THREAD

**Issue by DeFi-Dad** [gitcoinco/web#8146]
I'm trying to do one last donation to 137 projects with 1 DAI each + 15% going to Gitcoin Fund.

My zkSync checkout page is showing this error.
<img width="705" alt="Screen Shot 2020-12-17 at 10 13 56 AM" src="https://user-images.githubusercontent.com/56087134/102506146-d2047180-4050-11eb-8a97-a78831643301.png">

<img width="1767" alt="Screen Shot 2020-12-17 at 10 14 11 AM" src="https://user-images.githubusercontent.com/56087134/102506177-db8dd980-4050-11eb-8771-6ebf2b7d3167.png">

It's under my DeFi-Dad account on Gitcoin, using defidad.eth wallet.

**Comment by DeFi-Dad** [comment]
Oh and here's my cart: https://gitcoin.co/grants/cart/bulk-add/1619;1;283,194;1;283,668;1;283,437;1;283,482;1;283,1700;1;283,1668;1;283,238;1;283,1556;1;283,524;1;283,1602;1;283,1426;1;283,1636;1;283,1809;1;283,1578;1;283,1151;1;283,202;1;283,1464;1;283,1543;1;283,1211;1;283,1534;1;283,285;1;283,1658;1;283,1530;1;283,1219;1;283,1413;1;283,1034;1;283,543;1;283,816;1;283,392;1;283,1273;1;283,1654;1;283,277;1;283,358;1;283,972;1;283,1653;1;283,1112;1;283,1166;1;283,1490;1;283,590;1;283,1090;1;283,1736;1;283,1761;1;283,1598;1;283,1102;1;283,1618;1;283,49;1;283,1753;1;283,1638;1;283,1509;1;283,1826;1;283,738;1;283,1143;1;283,1693;1;283,1183;1;283,1728;1;283,152;1;283,759;1;283,1250;1;283,1824;1;283,1528;1;283,1665;1;283,454;1;283,1799;1;283,1714;1;283,1573;1;283,389;1;283,1298;1;283,467;1;283,938;1;283,1099;1;283,1299;1;283,562;1;283,646;1;283,934;1;283,1047;1;283,1723;1;283,1554;1;283,1732;1;283,815;1;283,1262;1;283,1147;1;283,622;1;283,1424;1;283,156;1;283,1621;1;283,1676;1;283,1730;1;283,386;1;283,1707;1;283,1633;1;283,1197;1;283,1624;1;283,1552;1;283,840;1;283,1639;1;283,1267;1;283,1744;1;283,383;1;283,1781;1;283,1813;1;283,1695;1;283,1772;1;283,1518;1;283,232;1;283,1677;1;283,1719;1;283,968;1;283,1810;1;283,988;1;283,772;1;283,1140;1;283,1710;1;283,1091;1;283,234;1;283,1731;1;283,1694;1;283,1758;1;283,1642;1;283,1651;1;283,177;1;283,1785;1;283,999;1;283,1709;1;283,1662;1;283,1733;1;283,1659;1;283,626;1;283,845;1;283,1225;1;283,1237;1;283,1243;1;283,1279;1;283,1306;1;283,1445;1;283,1487;1;283,1580;1;283,:defi-dad

**Comment by owocki** [comment]
@mds1 can you tag the matterlabs team here?

**Comment by mds1** [comment]
This is expected, sorry! We need to convey this on the cart page better. There's a PR for it here: https://github.com/gitcoinco/web/pull/8145

Unfortunately you'll have to split this up into batches of 45 cart items at a time.

More context: https://github.com/matter-labs/zksync/issues/266

**Comment by mds1** [comment]
Actually it seems zkSync is having some issues at the moment—you'll still need to do things in batches of 45, but just a heads up the checkouts still may fail unfortunately

**Comment by DeFi-Dad** [comment]
Shoot any chance the deadline can be extended? I'll do that but it'l take me an hour to manually add/delete these :)

**Comment by mds1** [comment]
I think zkSync is back up now so give it a try! But I'll have to defer to @owocki on any deadline extensions

**Comment by DeFi-Dad** [comment]
FWIW, after batching it by 25-30 and getting it through, my final 30 asked for more ETH. I wonder if i didn't have enough ETH on L2 to do all 137 and that was my problem from the start. Hope it helps!

**Comment by mds1** [comment]
Did it only ask for a very small amount of ETH? Most likely gas prices have risen since you first deployed funds (seems they've been rising for the last few hours!), and as a result transaction fees went up, leaving you slightly short for the final 30 donations.

The solution in that case is to either do another deposit (which is pricey), or simply edit your cart to reduce the value of the items slightly so you have enough leftover for gas. There is a limit of about 50 donations either way, so I don't think that was the original cause! 🙂
