### ISSUE TITLE
add mautic js to site

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#8148]
### User Story

As a Gitcoin marketer, I want the mautic JS added to the site, so we can more effectively segment users

### Why Is this Needed

Right now segmenting is done on a self-selecting basis - vis-a-vis the new onboarding work, we can segment automatically based on the users' behavior

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
No mautic JS

### Expected Behavior
mautic js added

### Definition of Done
mautic user info shows up in campaign builder, etc. in mautic

**Comment by thelostone-mc** [comment]
Closing as it's in the done section
