### ISSUE TITLE
Add Acquia to list of email providers

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#8149]
### User Story

As a Gitcoin marketer, I want mautic integration to sync our user profile information, so that we can create effective communication with users without having to build custom templates, logic, etc. within Django

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Currently, we have a lot of emails where the logic, design, copy, etc. is done within the Django codebase, which is difficult for non-devs to work on. Moving this to mautic will allow more people to work on it directly, and the first step is to do this base integration.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
User emails and profiles only synced to mailchimp, sendgrid

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
User emails and profiles synced to mautic as well (removal of mailchimp and sendgrid in the future, as we deprecate their use, outside the scope of this ticket)

### Definition of Done
user info is synced with mautic

**Comment by frankchen07** [comment]
closing - irrelevant
