### ISSUE TITLE
Link Killed status to actual transaction

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#815]
https://gitcoin.co/issue/btcsuite/btcd/1089

### User Story

As a person who created bounty, I want to find the transaction that killed the bounty so that I can see that the funds are actually returned.

### Solution

It will help to link the status Killed to the actual transaction that made it
![image](https://user-images.githubusercontent.com/8781107/38397572-13783566-3947-11e8-9105-a568afa703d1.png)

**Comment by thelostone-mc** [comment]
@pixelant this is needed !!

**Comment by owocki** [comment]
we should probably have txids logged to the database for *each* status mutation, not just killed bounties

**Comment by abitrolly** [comment]
I like that idea.

**Comment by kuhnchris** [comment]
Did we ever implement that @thelostone-mc  ?
