### ISSUE TITLE
Missing gitcoin history for contribution

### ISSUE THREAD

**Issue by coincashew** [gitcoinco/web#8150]
Similar issue as https://github.com/gitcoinco/web/issues/8113

zkSync transaction via metamask completed but no record on gitcoin.
All Txn hashs created at 
2020-12-17 03:02:53 UTC for account 
https://zkscan.io/explorer/accounts/0x0232f3fb1a4d648e6cff207d933642fda39655bb
were affected.
Exactly:
https://zkscan.io/explorer/transactions/698acba15b2e76b4253f1f856edc1684ef74dac1859ebc4de221771fe7ddf49c
https://zkscan.io/explorer/transactions/5a50f8228e4872f4c36fd00e932114a0e5ded7e077eafa8ec6ee129f6a96e641
https://zkscan.io/explorer/transactions/fd4cef0bb989664072bbcd5173e6e0229624581f58222702446d570827219910
https://zkscan.io/explorer/transactions/f0c0fe37b038456b925ccca7ebe9c062b710e493ea0d9731e7381635199ad2eb
https://zkscan.io/explorer/transactions/13d6b36a2ee2b0c3816c33bd89f17625b394343b42372068bff255c8fb3fedea
https://zkscan.io/explorer/transactions/a6efcc888e52d70dba27b6b2c6eca0a3bca88cc84c556f77ac5a1ff29016a92d
https://zkscan.io/explorer/transactions/7c0ae69465007417784260526206533ba090b377ab79985ba0ffc193f841e573
https://zkscan.io/explorer/transactions/53922fc08eb14b4606759a9a7e8dfab7a3ab3aaaee92f5272205f9dcd200a42c
https://zkscan.io/explorer/transactions/c347549fdc23551240cf88ba7641dc59e23095ee1c420cd8ddb76a3a8fa31589
https://zkscan.io/explorer/transactions/9baa43afad6298143a9f9ff341c78ee2404579ffda11834554b7118a4256e5e6
https://zkscan.io/explorer/transactions/1096d2898bec24e84a040337b21d5c9502cffe746bcd175c4f97c0784bbd3aad
https://zkscan.io/explorer/transactions/3eae404e941a24458a1b4050eb212d4db5ebe4284747eb9eb3152a2cd7b7400d
https://zkscan.io/explorer/transactions/00da2cd020bd4044b2a55cd4aec11837e4ea08c8e41ab01c7411e831d3a3883d
https://zkscan.io/explorer/transactions/22d682b4fb25126cfb4753628c58acf1daaa80d40235158d3d33936c7aa58dce
https://zkscan.io/explorer/transactions/3cc69fdbd66e4879ad7d90dccdfc6522d94b71c45a4a0972219453f4c53c25b5
https://zkscan.io/explorer/transactions/5a7260e494ae215b89c2bf7cb8a1177230c07303b1e786aaba8d7d121dde8935
https://zkscan.io/explorer/transactions/e7558acc73720775674a497b1b620aaa43d5b48b41ca44d0605669db670dadfa
https://zkscan.io/explorer/transactions/6af70d93d3c4fe2a222dd5ce1badc4afc22cd04a5129bb15c700be2a2fb663d8
https://zkscan.io/explorer/transactions/0c7d68b138cb0964253285d57059cd338dd1171b6b1979b90e6b84d212fe5751
https://zkscan.io/explorer/transactions/b14b7594735dc2a298e1046551b57dfd57f66eddb53adb4564de2774019ad0d6
https://zkscan.io/explorer/transactions/25ef78a3b35024dbfb68969c70923a29dceb7b60516f4f4c052599a1f43fa4e0
https://zkscan.io/explorer/transactions/b088a71bbefab741247a68d92974f682e14d8c7cf3745320e263b12762398c6a

Please ensure these contributions are properly matched. Thank you!

**Comment by mds1** [comment]
We will make sure these get accounted for, thanks for reporting!

**Comment by mds1** [comment]
Contributions have been ingested!
