### ISSUE TITLE
Can't connect MetaMask to check out - "Cannot read property '0' of undefined" error

### ISSUE THREAD

**Issue by simonlapscher** [gitcoinco/web#8152]
When clicking "Standard Checkout" button in Gitcoin Grants, my MetaMask wallet doesn't pop up and I get a "Cannot read property '0' of undefined" error.

<img width="1440" alt="Screen Shot 2020-12-17 at 5 02 46 PM" src="https://user-images.githubusercontent.com/26410621/102561973-e9f8e700-408a-11eb-8f05-d22fa6f5d0fa.png">
<img width="618" alt="Screen Shot 2020-12-17 at 5 11 50 PM" src="https://user-images.githubusercontent.com/26410621/102561995-f715d600-408a-11eb-9cdf-9d04db901aed.png">

**Comment by thelostone-mc** [comment]
could you make sure 
- metamask is unlocked
- connected to mainnet
- you have enough balance

**Comment by Kweiss** [comment]
Going to close this. Let us know if this is still occuring!
