### ISSUE TITLE
Grant transaction done, but was not recognized

### ISSUE THREAD

**Issue by alterisa** [gitcoinco/web#8156]
**Describe the bug**
something did not work yesterday with the Grant checkout (https://gitcoin.co/grants/cart)

**To Reproduce**
1. enter the form to donate 5 DAI to https://gitcoin.co/grants/202/vocdoni-decentralized-anonymous-voting
2. select "💪 keep up the great work" as comment
3. leave as is the 5% for Gitcoin Maintainer Grant
4. click "Include this contribution to CLR matching"
5. click "Standard Checkout"
6. metamask popup appears, accept the transaction
7. transaction took a bit but is completed after 22 minutes: https://etherscan.io/tx/0x20ef6c907a12485072c1d96ffd5878568ecf0d31c51b22d7f726e1a7a83a9cb2

**Expected behavior**
I expect to see an empty "Grants Cart" and my contribution of 5 DAI (4.75DAI) accredited on Vocdoni
Instead, the "Grants Cart" is still full, as if the transaction was never done.

**Desktop (please complete the following information):**

- OS: Debian 10.2
- Browser: Chromium 
- Browser Version: Version 87.0.4280.88 (Official Build) for Linux Mint (64-bit)

**Comment by mds1** [comment]
Your contribution was successful, but is just missing from the database. We will ingest it manually by early next week!

**Comment by alterisa** [comment]
cool, thanks a lot! i'll close the issue then, and in any case i'll simply reopen it
