### ISSUE TITLE
Grants don't seem to have gone through

### ISSUE THREAD

**Issue by raphael-mazet** [gitcoinco/web#8157]
I made 12 grants with L2 checkout. The funds have left my account, zksync indicated they were paid, but my cart is still indicating that I haven't checkedout and none of them have been registered on the website.

**Comment by mds1** [comment]
Can you please provide your address and any transaction hashes so we can look into this? Feel free to message me on Twitter @msolomon44 or Telegram @msolomon4 if you don't want to share it publicly

**Comment by willyogo** [comment]
I ran into this same issue with this address on 12/17:
https://zkscan.io/explorer/accounts/0x05A1ff0a32bc24265BCB39499d0c5D9A6cb2011c
