### ISSUE TITLE
Document and check all possible status values

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#816]
### User Story

As a gitcoin developer, I'd like to know about all possible bounty statuses to make interfaces that don't miss any info.

### Why Is this Needed?

Because Killed status is still visible as Expiring after this commit https://github.com/gitcoinco/web/pull/785/files With a graph of possible statuses, it is easier to cover all cases.

**Comment by thelostone-mc** [comment]
Ah that's a good catch!
Will throw in a fix for that

**Comment by owocki** [comment]
does this screenshot from the side bar ( http://bits.owocki.com/0F1W211g3a0N/Screen%20Shot%202018-04-06%20at%208.04.58%20AM.png ) help?

how about this visual one? http://bits.owocki.com/0k3S1n111v1c/Screen%20Shot%202018-04-06%20at%208.06.00%20AM.png

**Comment by abitrolly** [comment]
Visual one is better.

**Comment by abitrolly** [comment]
Although Kill/Cancel action/status wants to be consistent. It is not always clear that it is the same.
