### ISSUE TITLE
Changing grant ownership

### ISSUE THREAD

**Issue by HsingFan** [gitcoinco/web#8164]
### Who
Furucombo's [grant](https://gitcoin.co/grants/711/furucombo) on Gitcoin
### What 
Please help me 

1. change Furucombo’s grant owner from [me](https://gitcoin.co/hsingfan) to [hsuantingchu](https://gitcoin.co/hsuantingchu)
2. change wallet from 0xCC9354e76bC27bc846934d22DF6e1eFA77B6A80D to Hsuanting.eth

### Why
Because he's the CEO. 
Thanks, appreciate it :p

**Comment by thelostone-mc** [comment]
- change Furucombo’s grant owner from me to hsuantingchu. This can be done
- grants doesn't support ENS right now. I can switch it over to the address `0x132cd02e566c36976efb327a4301a605747f4b78`
Could you please confirm this @hsuantingchu ?
https://etherscan.io/enslookup-search?search=hsuanting.eth

Additionally could I get comment from @hsuantingchu saying he's good with this change

**Comment by thelostone-mc** [comment]
Closing this out ! Do reopen if this is still a needed request

**Comment by hsuantingchu** [comment]
Sorry about replying late - confirmed. :)
