### ISSUE TITLE
Email address not updating from Github on "Email Preferences" tab

### ISSUE THREAD

**Issue by gravenp** [gitcoinco/web#8167]
**Describe the bug**
The email address associated to my account isn't updating after changes made in Github

**To Reproduce**
-Navigate to Manage Settings > Email
-View current email address listed
-Use link to navigate to Github profile & change your public email (delete old email if desired)
-The email address on Gitcoin does not update (waited several days)

**Expected behavior**
The email shown in a Gitcoin profile should be updated when a user changes their email in Github. Alternatively, allow users to manually update their email.

**Comment by sergejmueller** [comment]
Can confirm.

**Comment by gravenp** [comment]
Maybe I can disconnect and reconnect my Github account under Manage Account > Account to force an update? I'm hesitant due to the unknown consequences with my account data/identity trust.
