### ISSUE TITLE
new landing

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#8171]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I want to have the landing to reflect the changes on the file 
https://www.figma.com/file/iei7gMlPETQEkaLcZpLfPQ/Gitcoin-Onboarding-2021?node-id=0%3A1

for inspect design go to https://www.figma.com/file/iei7gMlPETQEkaLcZpLfPQ/Gitcoin-Onboarding-2021?node-id=1%3A8
### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Landing primary area with ctas for each product 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by frankchen07** [comment]
note: this ticket should be released alongside #8172
