### ISSUE TITLE
hackathon guide - user case 1

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#8172]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a non logged-in user I want an explanation on how hackathons work, so that I can understand how Gitcoin can allow me to earn and give.

### Why Is this Needed

We’re proposing a directed, step-wise onboarding experience that addresses the confusion revolving around how to earn / give on Gitcoin.

### Description
This ticket is to develop the design of the modal, trigger the modal to appear, and prevent the modal from appearing via the checkbox selection.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
No guide exist 

### Expected Behavior

If a non-logged in user arrives at the hackathon list page, a modal pops up automatically with a guide on Gitcoin hackathons. This happens regardless of how they arrived at the page. It will always pop up at this page until the user checks the box.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- Guide implemented on hackathon list page
- Modal open when a logged-out user access hackathon list page
- If user click on the modal checkbox a cookie is created and the modal doesn't open anymore. 

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

- Qualitative: A new user has less confusion once he/she selects a specific path under earn/give that Gitcoin has provided.
- Qualitative: A new user has a strong understanding how Gitcoin can help provide value under the specific path they have chosen, and chooses to authenticate with us.
- Quantitative: 75% of new users who complete the new onboarding end to end will have performed a major product action within 3 days of joining, compared to 50% previously.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

https://www.figma.com/file/iei7gMlPETQEkaLcZpLfPQ/Gitcoin-Onboarding-2021?node-id=0%3A1

for inspect design go to https://www.figma.com/file/iei7gMlPETQEkaLcZpLfPQ/Gitcoin-Onboarding-2021?node-id=1%3A8

![image](https://user-images.githubusercontent.com/1358093/103012740-c9adaa00-451a-11eb-9a74-39c11e1a3273.png)

**Comment by frankchen07** [comment]
note: this ticket should be released alongside #8171
