### ISSUE TITLE
Airdrop Reward From Badger

### ISSUE THREAD

**Issue by Drew0776** [gitcoinco/web#8175]
Even Though I donated to multiple projects during round 8. I have yet been able to claim my Badger reward airdrop.
My personal wallet address is ~ 0xb28bD15737B87051490A99bfFb9158302447EEDC
Thank You
~ Andrew N

**Comment by LeanBitC** [comment]
In my case, the same as Andrew. I couldn't claim the airdrop. My adress wallet is 0x7901A56eB5f5989095eA42781B90810ca8B13CDE . Thank hoy.

**Comment by Drew0776** [comment]
Also not trying to sound like i am complaining either.
~Merry Christmas to everyone. 🎅🎄

**Comment by darmony121** [comment]
Also cant claim airdrop

**Comment by Drew0776** [comment]
I did some digging guys and the airdrop has not happened yet.  All info need is on Discord Channel https://discord.gg/7W65B35M ~ I hope this helps ease some minds. I didn't donate on the point of personal gain I donated to projects that I truly felt were ahead of the game in Defi. I will admit that the Badger airdrop was an added bonus.
