### ISSUE TITLE
Onboarding V2 (epic ticket)

### ISSUE THREAD

**Issue by danlipert** [gitcoinco/web#8177]
### User Story

As a Gitcoin user, I want to understand how Gitcoin works and how Gitcoin specifically addresses my needs.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Software developers that come to Gitcoin for the first time do not understand how to earn or give money through Gitcoin. This manifests as a navigation problem and the lack of a holistic understanding on how Gitcoin works and how Gitcoin specifically addresses their need.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Epic

### Current Behavior
[comment]: # (Describe what actually happened.)
Previously, after onboarding completion, the user would be dropped off at Townsquare with the profile completion widget. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
With specific onboarding paths, the user is instead funneled to the right product.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
See the individual tickets for atomic milestones.

### Data Requirements

Onboarding conversion rate (complete the onboarding end to end)
Onboarding performance (complete onboarding and complete major product action within 3 days)
% of users who drop off at each step

Qualitative: A new user has less confusion once he/she selects a specific path under earn/give that Gitcoin has provided.
Qualitative: A new user has a strong understanding how Gitcoin can help provide value under the specific path they have chosen, and chooses to authenticate with us.
Quantitative: 75% of new users who complete the new onboarding end to end will have performed a major product action within 3 days of joining, compared to 50% previously.

### Additional Information
https://docs.google.com/document/d/1JpEJodLkVRGXVhO6PjYQ53YW57DdOmCVlQ4bPWMflPw/edit
https://www.figma.com/file/iei7gMlPETQEkaLcZpLfPQ/Gitcoin-Onboarding-2021?node-id=0%3A1

**Comment by danlipert** [comment]
Related tickets:

- Changes to landing page from Figma https://github.com/gitcoinco/web/issues/8171 
- Add modal hackathon guide https://github.com/gitcoinco/web/issues/8172

**Comment by aamustapha** [comment]
@danlipert Is this ready to commence work? [The document](https://docs.google.com/document/d/1JpEJodLkVRGXVhO6PjYQ53YW57DdOmCVlQ4bPWMflPw/edit) states otherswise.

**Comment by frankchen07** [comment]
I believe this ticket is ready: https://github.com/gitcoinco/web/issues/8172

not sure if the "not approved" on the brief is actually waiting for @Kweiss or if things are slipping through the cracks. Following up here so we can get a response and get 8172 started.

**Comment by aamustapha** [comment]
Cool. Keeping my fingers crossed

**Comment by frankchen07** [comment]
@aamustapha & @chibie this should be ready to go - hit me up if you have any questions!

**Comment by aamustapha** [comment]
Will get on it right away. Would revert back with questions

**Comment by aamustapha** [comment]
closed by #8243
