### ISSUE TITLE
BadgerDao Payout Round 8

### ISSUE THREAD

**Issue by gthreadgill** [gitcoinco/web#8180]
Just checking if all payout was processed. I did not receive mine and I could not claim anything when I went to the BadgerDao site. I am super excited about the BadgerDao token Airdrop and more. 2020 "The Year of Great Success!!!" My address is 0x90815418a4c89cED62437bE836B8d3Aa120372b4

**Comment by developerfred** [comment]
@gthreadgill there was a deadline to finance grants and thus enter the badger's whitelist, did you do that?

**Comment by Kweiss** [comment]
The airdrop has not yet happened. The round was finalized recently and we will have Badger share details on the airdrop soon!
