### ISSUE TITLE
grants/crosschain - Binance

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#8193]
### Description

Frontend
- [ ] Add chain to grant creation form (staff flag)
- [ ] Add changes to ensure grant detail page renders right
- [ ] Set default amount and currency while adding to cart
- [ ] Build out the cart checkout flow 
- [ ] Ensure tab is shown only if grants are visible 

Backend
- [ ] Make changes to `/v1/contribute` endpoint 
- [ ] Add in chain sync logic
- [ ] Update cron to rety pending txn

**Comment by frankchen07** [comment]
binance bounties bug deadline / integration finish 1/19 - 1/21
demo with clients 1/21 - 1/23
staff flag 1/23
release date 1/25 is ideal, 1/28 last call
put up issues 1/25 or 1/28 to 1/31
hackathon start 2/1 - 2/21

===

regression on 1/8 and deploy on 1/11

**Comment by frankchen07** [comment]
closing duplicate: https://github.com/gitcoinco/web/issues/8191
