### ISSUE TITLE
Deleting a user takes to a 500 error

### ISSUE THREAD

**Issue by nglglhtr** [gitcoinco/web#8195]
**Describe the bug**

Deleting a user from the administration gives a 500 error 

**To Reproduce**

Select a user, delete their profile, confirm

**Expected behavior**

should correctly delete the user

**Screenshots**
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/10832414/103547377-5583e680-4eca-11eb-8155-66d0a4e41897.png">

**Comment by owocki** [comment]
https://github.com/Suor/django-cacheops/issues/387

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/8296

**Comment by owocki** [comment]
https://github.com/Suor/django-cacheops/issues/387#issuecomment-772175478

working with the upstream maintainer worked!
