### ISSUE TITLE
Problem on claimming a issue

### ISSUE THREAD

**Issue by ernaneluis** [gitcoinco/web#82]
I'm trying to claim a issue and Metamask is not broadcasting the transaction. 
Besides the transaction to claim is costing almost $2, quite high I think thought. 

<img width="337" alt="screen shot 2017-12-05 at 00 26 53" src="https://user-images.githubusercontent.com/1398769/33582531-fb5904f2-d955-11e7-901d-035f74f0bd27.png">

<img width="330" alt="screen shot 2017-12-05 at 00 32 01" src="https://user-images.githubusercontent.com/1398769/33582541-0309556c-d956-11e7-886d-aa8fde468e41.png">

**Comment by owocki** [comment]
thanks @ernaneluis -- ethereum network is bogged down today (we all think its due to cryptokitties but idk)...

nonetheless, this issue shouldnt be happening.  let me see if i can repro it while gas prices are still high

**Comment by owocki** [comment]
btw wwhich issue are you trying to claim

**Comment by ernaneluis** [comment]
@owocki the one from leaderbord

**Comment by owocki** [comment]
out of curiousity, does it work if you try 11 gwei as the gas price?

**Comment by ernaneluis** [comment]
metamask problem is still happening
https://github.com/MetaMask/metamask-extension/issues/2661

Several issues were created. The cryptoKitties are clogging their nodes.

**Comment by owocki** [comment]
looks like your claim went through!  will accept it once we merge the PR

**Comment by ernaneluis** [comment]
I tried using another RPC node. The infura is till a problem. The gas is now 61 gwei 👎

**Comment by owocki** [comment]
@ernaneluis fwiw it seems network conditions have calmed down a bit.

**Comment by owocki** [comment]
lmk if still having issues
