### ISSUE TITLE
new matching partner form updates

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8211]
the new matching partner form email is too spammy rn

set a minimum of 10k on the new matching partner form, dont actually trigger an email to admins until the funds are sent.

maybe also an auto follow up if the funds arent sent asking if they have any questions

**Comment by owocki** [comment]
this should perhaps be a sales intake form instead of something that actually tries to transfer the ETH.

@Kweiss i know u have feedback here

**Comment by Kweiss** [comment]
We plan to handle this with Acquia - Going to close this as this is one of the first forms that @octavioamu is going to be building out (replacing)
