### ISSUE TITLE
Grants UI / Nav Feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8212]
TODO - intake from Kyle/Scott

**Comment by owocki** [comment]
hey @Kweiss during gr8, @ceresstation setup a great call where we got grants UI feedback from his designer friend.  where is the output of that?  can we get it in ticket form so its actionalbe?

**Comment by owocki** [comment]
Note:  we'll also have to fold in the feedback from VB https://gist.github.com/owocki/ef1ea12bb6c1fe122e49efb7e8936953

**Comment by owocki** [comment]
from @ceresstation 

too much happening above the fold, consolidate sections
filters / options for managing the discovery feature (e.g. search, add to cart) should move with the user as they browse the site
a few places where there's no feedback that something is loading on the site, e.g. Metamask pop up, adding to cart
cart itself could include a bit more detail on what's there
grants pop out from the left which is a bit jarring / unexpected, it'd be better if the pop-out came from the middle / top
when you refresh a pop-out it disappears / doesn't persist
clear way to find collections / to surface collections to users more easily
checkout + total should be one section, shouldn't need to scroll down to checkout

**Comment by Kweiss** [comment]
Though we appreciate the feedback, we are not going to action all of these. These are one persons opinion without research to validate either the problem, or the proposed solution.
