### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#8218]
https://github.com/gitcoinco/creative/issues/312

<img width="1607" alt="Screen Shot 2021-01-08 at 1 45 35 AM" src="https://user-images.githubusercontent.com/238235/103983573-7874fb80-5153-11eb-9fd8-fd8919f14080.png">

**Comment by aamustapha** [comment]
@octavioamu I guess we'll be building this into acquia right?

Or is it plain HTML?

**Comment by disruptionjoe** [comment]
We need to build the daily digest and weekly mint into Django.

I will build the design into the Acquia in parellel. 

We have exceptionally high open and interaction numbers for these two emails. I'm not willing to move them without being able to bring them back if there are issues. 

Please update Weekly Mint & Daily Digest to new designs in Django and share an expected completion date when we have it.
