### ISSUE TITLE
What do I have to do to receive ETH in my (Coinbase) wallet?

### ISSUE THREAD

**Issue by sqykly** [gitcoinco/web#8228]
### Who

Anyone who is not already a crypto wizard with an ETH wallet (in Coinbase).  (This problem clearly exists for many different wallet types)

### What 

There is no easily accessible information available through the Gitcoin website on how to connect my Gitcoin to a (Coinbase) wallet (or any other).  The four choices are presented opaquely to the user with no explanation of what they are or what needs to be done.  There is no help page on the wiki or the site for the issue of collecting payment.  I can find no forum here to discuss this issue or ask for help.  There is no option to use PayPal, a perfectly good API for receiving payments that everybody and their grandmother knows how to use without a PhD in cryptocurrency.

### Why

I can see the argument that issues like this are not specifically within the scope of Gitcoin's responsibility to document because it is a general issue to cryptocurrency, not a Gitcoin feature.  However, the four individual services' web presences also do not provide documentation related to collecting payment (and certainly no guidance on how to connect their services to Coinbase).  As far as I can tell from their documentation, 3/4 appear to be APIs that service web apps, not end users who want to collect payment, and the other one, WalletConnect, further limits its support to a number of (non-coinbase) wallet services.  I recognize that the crypto ecosystem is vast and under-standardized, which is part of the problem, but when Gitcoin offers only a very limited set of wallet connection methods, some of which are just APIs that I would have to build an app to use, **it is simply not accurate to claim that Gitcoin is an app that pays developers for working bounties until there is at least SOME form of support in this matter**.

I am obviously not a crypto wizard.  I use crypto to the extent that I need it to receive payments.  I am waiting to buy into it until it faces my standardization and stability concerns.  I thought I had solved the problem of how to receive cryptocurrencies such as ETH when I created a (Coinbase) wallet to receive funds on previous projects, which worked just fine.  For what reason that this doesn't work for Gitcoin is a total mystery to me.  Why you cannot use PayPal is also beyond my understanding.  All I'm really asking for, though, is some technical support in navigating the limited options Gitcoin provides.  It should be clear from the beginning that not all ETH wallets can receive funds, and the steps one must take to remedy issues like this should be readily available.

Also, can you please tell me how to connect my Coinbase wallet?

**Comment by castroed47** [comment]
> 
> ### Who
> 
> Anyone who is not already a crypto wizard with an ETH wallet (in Coinbase).  (This problem clearly exists for many different wallet types)
> 
> ### What 
> 
> There is no easily accessible information available through the Gitcoin website on how to connect my Gitcoin to a (Coinbase) wallet (or any other).  The four choices are presented opaquely to the user with no explanation of what they are or what needs to be done.  There is no help page on the wiki or the site for the issue of collecting payment.  I can find no forum here to discuss this issue or ask for help.  There is no option to use PayPal, a perfectly good API for receiving payments that everybody and their grandmother knows how to use without a PhD in cryptocurrency.
> 
> ### Why
> 
> I can see the argument that issues like this are not specifically within the scope of Gitcoin's responsibility to document because it is a general issue to cryptocurrency, not a Gitcoin feature.  However, the four individual services' web presences also do not provide documentation related to collecting payment (and certainly no guidance on how to connect their services to Coinbase).  As far as I can tell from their documentation, 3/4 appear to be APIs that service web apps, not end users who want to collect payment, and the other one, WalletConnect, further limits its support to a number of (non-coinbase) wallet services.  I recognize that the crypto ecosystem is vast and under-standardized, which is part of the problem, but when Gitcoin offers only a very limited set of wallet connection methods, some of which are just APIs that I would have to build an app to use, **it is simply not accurate to claim that Gitcoin is an app that pays developers for working bounties until there is at least SOME form of support in this matter**.
> 
> I am obviously not a crypto wizard.  I use crypto to the extent that I need it to receive payments.  I am waiting to buy into it until it faces my standardization and stability concerns.  I thought I had solved the problem of how to receive cryptocurrencies such as ETH when I created a (Coinbase) wallet to receive funds on previous projects, which worked just fine.  For what reason that this doesn't work for Gitcoin is a total mystery to me.  Why you cannot use PayPal is also beyond my understanding.  All I'm really asking for, though, is some technical support in navigating the limited options Gitcoin provides.  It should be clear from the beginning that not all ETH wallets can receive funds, and the steps one must take to remedy issues like this should be readily available.
> 
> Also, can you please tell me how to connect my Coinbase wallet?

New Login from: IP 175.176.72.203, Philippines

**Comment by sqykly** [comment]
> New Login from: IP 175.176.72.203, Philippines

Nice area, but no, I'm not from the Philippines.  Why does that matter?

**Comment by Kweiss** [comment]
Hi @sqykly - Can you join our discord for support? We would love to talk you through the problems you are having there 👍 

https://discord.gg/zMEm7vwtRP

**Comment by molecula451** [comment]
@sqykly Gitcoin currently does not support Coinbase for your web3 connection you have to either download MetaMask or any of the other options. Additionally you may only save a preferred wallet on settings where you want to receive Kudos/tips etc
