### ISSUE TITLE
leaderboard not updated in a month

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8246]
looks like the leaderboard hasn't been udpated in a month

when i go to run it on the cronbox, it eventually dies (see below).

```
scripts/run_management_command.bash: line 23:  2401 Killed                  ./manage.py $1 $2 $3 $4 $5 $6 $7 $8 $9
```

i think its running out of memory

**Comment by Kweiss** [comment]
This is referring to the Quests Leaderboard: https://gitcoin.co/quests

**Comment by owocki** [comment]
sorry no https://gitcoin.co/leaderboard is what its referring to @Kweiss
