### ISSUE TITLE
Stuck in 'Pending verification' mode.

### ISSUE THREAD

**Issue by theoryshaw** [gitcoinco/web#8247]
I have paid out a bounty to a contributor, but the payment has been 'Pending verification' for a full day now. Is there a means to unstick the verification?
https://gitcoin.co/issue/OpeningDesign/OD_Library/6/100024583

---

I noticed on the following address that the Ethereum transaction was dropped. 
https://etherscan.io/tx/0x2f597ecdaf28ae7c742539d5735f64a9e90793cbf8d5cce859f1ee7c17eb6489

If so, is there a way to reset the 'payment' on this gitcoin bounty so I can try again?

**Comment by ChaituVR** [comment]
+1

I have a similar issue with https://gitcoin.co/issue/Ideamarket/gitcoin-bounties/3/100024356
The transaction is Dropped and Replaced but still stuck in 'Pending Verification'

**Comment by ChaituVR** [comment]
My issue is solved now, Thanks! 👍 

> +1
> 
> I have a similar issue with https://gitcoin.co/issue/Ideamarket/gitcoin-bounties/3/100024356
> The transaction is Dropped and Replaced but still stuck in 'Pending Verification'

**Comment by thelostone-mc** [comment]
Hey @theoryshaw + @ChaituVR 
Sorry about that! We are still trying to figure out a reliable way to find out if txn are dropped and replaced but nothing useable has turned up yet 
I manually updated the txn id -> and the backend validated the txn and approved it
