### ISSUE TITLE
Address autofill fails with no Binance wallet extension installed

### ISSUE THREAD

**Issue by chibie** [gitcoinco/web#8249]
**Describe the bug**
Address autofill fails when a user doesn't have binance wallet extension installed.

**To Reproduce**
* Disable binance wallet extension (if already installed)
* Navigate to gitcoin.co/new
* Select Binance as bounty chain

**Expected behavior**
there's two cases:

**case 1:** user doesn't have binance wallet extension or extension is disabled => show user a modal with instructions to either download extension or enable installed extension.

**case 2**: user doesn't have binance wallet extension or extension is disabled => allow user manually enter binance address, disable autofill.

**N.B**: binance addresses are exactly same as eth addresses (0x...xxx..xxx) so it's not possible to validate the binance address.

As discussed in Slack, case 2 is simpler and cleaner, a disclaimer will be added so people make sure they double-check they are using the right address.

**Screenshots**
![image](https://user-images.githubusercontent.com/6025509/104761929-e331c280-5763-11eb-8be6-957ff67344e6.png)

cc: @PixelantDesign @Kweiss

**Comment by PixelantDesign** [comment]
IF we don’t know if they don’tt havee the wallet extension or it is disabled, we have to give the user the opportunity to connect it. The options would be connect OR if they don’t have it, then they can enter in the information.  Which at that point we’ll provide a disclaimer.

**Copy for Case 2**
User doesn't have binance wallet extension or extension is disabled => allow user manually enter binance address, disable autofill.

Looks like you don't have the Binance Wallet Extension or the extension is disabled. 
Please enter your Binance Wallet address. We are unable to validate a Binance address. Please confirm that you are using the correct Binance address.

< Display Input Field>
we'll probably need to see a video or screenshot to confirm the right information is there.

**Comment by chibie** [comment]
@PixelantDesign here's a screenshot

![image](https://user-images.githubusercontent.com/6025509/104974691-0aed8880-59f9-11eb-87d3-8034643c070c.png)
