### ISSUE TITLE
If Github Issue Gets Closed, Notify Funder Gitcoin Bounty Still Open

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#826]
*Not ready to be started*

Notify funder that Gitcoin Bounty is still open * even if they have closed Github issue.

Need to communicate to the funder what their options are.

**Comment by xiaods** [comment]
i suggest add another option, if the bounty fee have been send finished, it should be auto close bounty or add a tip on issue explorer list on gitcoin. i found i surf the gitcoin issue list, this close bounty is very annoy
