### ISSUE TITLE
When I go to gitcoin.co/quests, the images don't load

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8264]
### User Story

When I go to gitcoin.co/quests, the images don't load

### Description

frank - chrome browser, yes adblock - images load after 15 seconds
kyle - brave browser, no adblock - images never load

**Comment by frankchen07** [comment]
@thelostone-mc is there a linked PR for this?

**Comment by thelostone-mc** [comment]
This does load in live right now ! We did have an issue and I did remember a fix coming in for this 
Check the video I just recorded 

![Untitled](https://user-images.githubusercontent.com/5358146/109297411-f69e7600-7857-11eb-82ea-ec39b3a1c38e.gif)
