### ISSUE TITLE
The user's expression is not break line after submit 

### ISSUE THREAD

**Issue by thanhlmm** [gitcoinco/web#8270]
**Describe the bug**
If I input the expression with a line break and then submit it, it gathers all the content to the same line

**To Reproduce**
1. Click on Express Interest
2. Input some content with line break
3. Then submit

**Expected behavior**
The content showing should break the line same as users input it

**Screenshots**
![Screen Shot 2021-01-19 at 22 39 18](https://user-images.githubusercontent.com/9281080/105057327-b0f7cc00-5aa7-11eb-9bb4-853e304d986c.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Edge
- Browser Version: 87

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thanhlmm** [comment]
I also can support to fix it :p

**Comment by thelostone-mc** [comment]
Please do raise a PR if you can figure out a good fix for this @thanhlmm ^_^
