### ISSUE TITLE
Landing Page Bug Fixes Round 2

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8277]
#### Fixes

1. Let's align the buttons here:

<img width="1442" alt="Screen Shot 2021-01-20 at 15 26 43" src="https://user-images.githubusercontent.com/7516920/105253234-f2ce5400-5b33-11eb-8286-c890d5f6bddc.png">

2. Let's keep the capitalization consistent: earn -> Earn

3. Add a comma here -> ("learning new technologies and..." -> "learning new technologies, and ...")

<img width="711" alt="Screen Shot 2021-01-20 at 15 26 07" src="https://user-images.githubusercontent.com/7516920/105253298-12657c80-5b34-11eb-89a9-61a97da5d224.png">

4. can we also explore the possibility of bringing the buttons up so that we can immediately see them when we land on the landing page?

![Screen Shot 2021-01-26 at 11 53 37](https://user-images.githubusercontent.com/7516920/106049342-e0f03200-609a-11eb-9c19-b4c279a8538f.png)

5. Add a small login (like what we have at the right top hand side of gitcoin.co/grants when one logs out) to the landing page, which leads to our github authentication flow

<img width="1309" alt="Screen Shot 2021-01-27 at 12 28 58" src="https://user-images.githubusercontent.com/7516920/106049664-493f1380-609b-11eb-831e-2d60d71e55c6.png">

@PixelantDesign please backfill any other changes you see on this ticket.

**Comment by PixelantDesign** [comment]
<img width="1430" alt="Screen Shot 2021-01-22 at 9 34 44 AM" src="https://user-images.githubusercontent.com/238235/105503886-1eb51b00-5c95-11eb-899c-4ae55cf730e7.png">
