### ISSUE TITLE
Bug big

### ISSUE THREAD

**Issue by cdmullins69** [gitcoinco/web#8278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**
I never received my bounty

**Comment by owocki** [comment]
please fill out detailed info + we can re-open from there

**Comment by cdmullins69** [comment]
Its over

**Comment by cdmullins69** [comment]
Will do, thanks!

**Comment by cdmullins69** [comment]
I'm missing all of money

**Comment by owocki** [comment]
where is the ticket with details?

note: gitcoin never has custody of your funds, so whatever the issue is with your ETH wallet likely you'll want to contact your wallet provider
