### ISSUE TITLE
500 error when previewing roundup emails

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/web#8294]
**Describe the bug**

When trying to preview a round up email (the weekly mint) I get a 500

**To Reproduce**

Preview a roundup email in the admin

**Expected behavior**

**Screenshots**

https://cloudup.com/cUKE3SVfhhN

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment]
i just fixed it by changing the kudos field from

```
{"id": 26296, "airdrop": "https://gitcoin.co/kudos/redeem/44842565520935967215"}
```

to 
```
[{"id": 26296, "airdrop": "https://gitcoin.co/kudos/redeem/44842565520935967215"}]
```

you were missing the curly brackets on the end (which makes it an array not an object)

try now at https://gitcoin.co/_administration/email/roundup
