### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by dorukismen** [gitcoinco/web#8295]
### Who 
My twitter account: https://twitter.com/dorukismen

### What 
I sent the verification tweet, but when I pushed the "Verify" button, it won't verfiy my grant. Here is the verification tweet: https://twitter.com/dorukismen/status/1352926577055723521?s=20

### Why
Verification grant could not be completed. Thank you in advance for your help.

**Comment by Kweiss** [comment]
It looks like the Tweet you sent doesn't match the text we asked you to post:
https://cloudup.com/ca3jlWgGgnm

Do you mind trying again and following the workflow? Reopen the issue and please let us know if that doesnt work.

**Comment by dorukismen** [comment]
https://twitter.com/dorukismen/status/1354458027315912712?s=20 it did not work :(
