### ISSUE TITLE
Error 500 when trying to access account settings

### ISSUE THREAD

**Issue by beepidibop** [gitcoinco/web#8297]
**Describe the bug**
User cannot access the Manage Settings page, it returns a 500 error.

**To Reproduce**
Clicking "Manage Settings" on the top right menu

**Expected behavior**
Going to the settings page

**Screenshots**
![image](https://user-images.githubusercontent.com/63800471/105646734-60d98a80-5e56-11eb-9765-a0aed57267c5.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 87.0.4280.141 (64bit)

**Comment by beepidibop** [comment]
Relogging prompts the profile setup, but another error shows up preventing it from saving.
![image](https://user-images.githubusercontent.com/63800471/105758721-70afa800-5f04-11eb-8057-1ff76f8bb909.png)

**Comment by aamustapha** [comment]
Thanks for reporting this @beepidibop, my first instinct would be that your account is being created everytime you login which isn't supposed to be so.
I've been trying to reproduce this with zero luck.

**Comment by beepidibop** [comment]
I've revoked my github access and re-enabled it, it's still showing the same errors. Maybe I should try it with another github account and see if it's a problem with my PC or something else.

**Comment by beepidibop** [comment]
I just tried registering with a new github account and it worked. The issue appears to be account related. Also, I noticed my username has "adf993cda5a043b9" attached at the end of it, whereas my github is just "beepidibop".

Is there a way for me to delete beepidibopadf993cda5a043b9 so I can start over?

**Comment by aamustapha** [comment]
Thanks for this extra context, I'll try reproducing.

**Comment by aamustapha** [comment]
I'm still finding it hard to reproduce.

**Comment by octavioamu** [comment]
@beepidibop this is generally related to some username change on github then it create a hash to avoid collitions, I will fix your user on our side

**Comment by octavioamu** [comment]
@beepidibop can you try again please? should be fixed now and you should be able to control your account again https://gitcoin.co/beepidibop

**Comment by beepidibop** [comment]
@octavioamu It's working now. Thank you very much!
