### ISSUE TITLE
Localstorage on cart.

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#8299]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I want to keep my cart updated with the latest grant data so I can be aware of what the grant state.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Today we create a localhost grant obj with the cart, will all the needed grant data. That is not ideal as if something change then the cart never get updated. 
This situation created a lot of problems and bugs reports.

Share cart page is a page to just fetch the grants data by id array params and save them to localstorage and then redirect the user to the cart page to populate the data with localstorage.

If the url from cart accepts ids then the share cart can be unified with the normal cart, both using the same approach
shared urls will look like `https://gitcoin.co/grants/cart?grants=1,2,3,4`

Data on grants/cart will be always been a fetch of grants ids served by params or localstorage or a combination of both.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feateure
### Current Behavior
[comment]: # (Describe what actually happened.)
when someone add a grant to cart the data get saved and never updated

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
- Save only grants id on localstorage
- when cart is pinged fetch localstorage ids and request data from the server to populate the screen.
- cart url to accept ids as a parameters so we can fetch those ids and deprecate share cart page
- Fix add to cart to avoid the request on click and just add the grant id to localstorage instead of requesting all the grant data again to save it.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by mds1** [comment]
As discussed with @octavioamu, just sharing some extra details about the exact changes I plan to make:

1. In localStorage we'll save an array of objects, such as `[ {grantId: 1, grantName: '...', amount: 5, token: <addressOrSymbol>}, {...} ]`. In other words, for now localStorage will still store all grant information
2. When `/grants/cart` is loaded, we read the grantIds from localStorage and ping the backend to get the most recent grant data, this way any stale data in localStorage is updated
3. Update `/grants/cart` so it can accept grant ID parameters, which will let us deprecate the existing `/grants/cart/bulk-add/` endpoint (see `bulk_add_to_cart.html` for info on how it works)
