### ISSUE TITLE
Can not kill the bounty

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#830]
@owocki Hi Kevin. I am trying to kill bounty as requested in https://github.com/btcsuite/btcd/issues/1089#issuecomment-372536109 using this interface https://gitcoin.co/funding/details?url=https://github.com/btcsuite/btcd/issues/1089

First, it showed me some Transaction error in Metamask
![image](https://user-images.githubusercontent.com/8781107/38474560-e32f996c-3ba8-11e8-81d0-cd8e905f5925.png)
Now there is an error on Etherscan https://etherscan.io/tx/0x26d924963e056dde951b295418a452875fb286384cbc6a013124939d6fb70e80
and "Please wait" screen won't go away.

**Comment by abitrolly** [comment]
At the very least https://gitcoin.co/legacy/funding/clawback?source=https://github.com/btcsuite/btcd/issues/1089 should not propose to kill the bounty if it is already killed,

**Comment by owocki** [comment]
> At the very least https://gitcoin.co/legacy/funding/clawback?source=https://github.com/btcsuite/btcd/issues/1089 should not propose to kill the bounty if it is already killed,


this for the feedback; we are working on this here https://github.com/gitcoinco/web/issues/445

**Comment by owocki** [comment]
hey @abitrolly - the reason for the error is that the [bounty has already been killed](https://gitcoin.co/issue/btcsuite/btcd/1089)
