### ISSUE TITLE
New grant address still not working

### ISSUE THREAD

**Issue by RexShinka** [gitcoinco/web#8307]
For Grant issue https://github.com/gitcoinco/web/issues/8201 SoloExplorer changed my grant address.  The grant still refers to the old address and I get "You do not have a preferred payout address on file. Click here to set a Payout Address. " when I get grants, in the email.  I clicked to change the address but nothing happened.  Also I don't see the new grants anywhere in either address.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thesachinmittal** [comment]
Sorry for the inconvenience, Rex! As per your request, I have updated the grant with a new payout address you shared with me. Feel free to close this issue. :)
