### ISSUE TITLE
Research + discovery of existing CSS

### ISSUE THREAD

**Issue by mds1** [gitcoinco/web#8308]
# Outline

- CSS Summary
- Current Architecture
- Path Forward
  - Development Approach
      1. Utility Classes
      2. Sass over CSS
      3. Mixins and Extend
  - Next Steps
    - Design Resources
    - Implementation
  - Open Questions

# CSS Summary

FIrst I analyzed the CSS of https://gitcoin.co/grants CSS using [CSS Stats](https://cssstats.com/). I recommend checking out the full results [here](https://cssstats.com/stats/?url=gitcoin.co/grants). A brief summary is below, which indicates that the CSS is pretty messy right now:

- 8,275 rules; 9,791 selectors; 13,115 declarations
- Margins, paddings, widths, heights, and shadows are declared hundreds of times
- 132 unique colors, 609 total color declarations
- 221 unique background colors, 535 total background colors
- 86 unique font sizes, 263 font size declarations
- 11 unique font families
- 13,115 total declarations, 6,995 unique declarations

The bounties issue explorer page is [similar](https://cssstats.com/stats/?url=gitcoin.co/grants). Some of these numbers are clearly unnecessarily large and there's definitely room to reuse classes better and clean things up. 

Having a clean foundation and approach will give a slight improvement in site performance by reducing the size of the stylesheets loaded by the browser. It will also make the redesign work significantly easier to implement, easier to maintain, and reduce development time and decisions.

# Architecture

Throughout the whole codebase (excluding the `app/static` directory which I believe is autogenerated) there are 113 `.css` files and 25 `.scss` files. This gives 138 total stylesheet files and definitions to maintain across the site. Of these, there are 10 grants-specific stylesheets located in `app/assets/v2/css/grants`.

Below summarizes the overall grants architecture, such as what stylesheets are used and where inline styles are present. The tree starts from the root grants HTML file and contains all grants `index.html` and lists all files that are imported (non-grants HTML imports are excluded)

- `index.html` imports 7 stylesheets, 8 `style=` declarations, 4 inline CSS definitions between `<style>` tags
  - `active_clr_round.html` has 4 `style=` declarations
  - `grant_thanks_modal.html` has no custom styling ✅
  - `landing_activity.html` has no custom styling ✅
  - `landing_announce.html` has 13 `style=` declarations
  - `landing_grants.html` has no custom styling ✅
    - `card.html` has 10 `style=` declarations
      - `clr_estimate.html` has 1 `style=` declaration
    - `collection.html` has 3 `style=` declarations
  - `landing_hero.html` has 2 `style=` declarations
  - `landing_navbar.html` has 1 `style=` declaration
  - `landing_subnav.html` has no custom styling ✅
  - `nav.html` has 1 `style=` declaration
  - `shared_scripts.html` has no custom styling ✅
  - `side-cart.html` has 4 `style=` declarations
  - `sidebar_search.html` has 1 `style=` declaration
  - `template-grant-details.html` has 6 `style=` declarations, 19 inline CSS definitions between `<style>` tags

The stylesheets used are:
- `v2/css/kudos/styles.css`
- `v2/css/grants/card.css`
- `v2/css/grants/collection.css`
- `v2/css/activity_stream.css`
- `v2/css/sidebar_search.css`
- `v2/css/grants/side-cart.css`
- Bootstrap classes seem to be used throughout also

# Path Forward

Here I've laid out an initial proposal for a path forward to serve as a starting point for discussions. This is split into a few sections:
- Development Approach covers a suggested design/development philosophy
- Next Steps lays out what potential next steps would be for this proposal

### 1. Utility Classes

We should always use *utility classes*, as opposed to *semantic CSS*. Each of these CSS approaches, their tradeoffs, and why I prefer utility classes, are all well described in [this article](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/). Another good article is [here](http://nicolasgallagher.com/about-html-semantics-front-end-architecture/).

The summary is that utility classes are classes such as `.text-center` to center text, `.bg-white` for a white background, or `.my-4` for margin in the y-direction. This is in contrast to "Semantic CSS" where styles are in classes such as `.grant-item` or `.clr-prediction`.

While this decision is partly personal preference (and I'm happy to be swayed), I prefer utility classes for the reasons described in the linked article. We currently use a mix of both—we use Bootstrap classes which are utility classes, and there's also semantic CSS such as the `.grant-item` class. The mixing of both types leads to lots of duplicate definitions and copy/pasted color codes, font sizes, etc.

Quoting from the article:

> One of the biggest benefits of using small, composable utilities is that every developer on your team is always choosing values from a fixed set of options.
> 
> How many times have you needed to style some HTML and thought, "this text needs to be a little darker," then reached for the `darken()` function to tweak some base `$text-color`?
> 
> Or maybe, "this font should be a little smaller," and added `font-size: .85em` to the component you're working on?
> 
> It feels like you're doing things "right", because you're using a relative color or a relative font size, not just arbitrary values.
> 
> But what if you decide to darken the text by 10% for your component, and someone else darkens it by 12% for their component? Before you know it you end up with 402 unique text colors in your stylesheet.

If you have multiple elements that need the same combination of classes, either:
1. Create a descriptively named class such as `.btn-primary` for primary buttons and `.btn-secondary` for secondary buttons, that uses mixins to combine multiple utility classes
2. Extract things into a Vue component, such as `<gc-button-primary>` for primary buttons and `<gc-button-secondary>` for secondary buttons.

### 2. Sass over CSS

It seems a mix of CSS (`.css`) and Sass (`.scss`) source files are used, but I'd recommend only using Sass since it's more powerful and flexible:

1. Base definitions of things like colors should all be variables
2. Easy to use mixins (expanded on below)
3. Importing files lets us keep individual files smaller and more manageable

### 3. Mixins and Extend

As hinted at above, a big part of maintainability is using mixins. The current codebase only has one `@mixin` and no `@extend`s. Using mixins allows us to reuse the simplest, lowest level utility classes without explicitly re-declaring the style definitions each time.

In addition to `@mixin`, there's also `@extend`, but as explained in [this article](https://csswizardry.com/2014/11/when-to-use-extend-when-to-use-a-mixin/), using `@extend` is only preferable when classes are semantically related, because otherwise the size of compiled stylesheets can quickly get very large.

## Next Steps

This section describes what the next steps would be to implementing this plan.

### Design Resources

The summary here is that we want a fixed set of approved colors, fonts, etc. from the designers. We then specify these in utility classes, and only layout HTML with those utility classes.

Here's a first pass at what we'd need from the designers:
1. Do we want, or do we plan to support, dark mode? If so this would be good to know upfront so we can start accounting for it now
2. Colors
   1. Primary colors: 7–10 shades of the primary Gitcoin purple (light shades for tinted backgrounds, darker shades for text, etc.)
   2. Accent color: 7–10 shades of the accent Gitcoin green
   3. Reds, yellows, greens: 7-10 shades of red, yellow, green for things like error, warning, and success banners
   4. Neutrals: 7–10 shades ranging from the lightest background color to the darkest text, with greys in between
   5. Note: we may not use all of these shades, but it's helpful to have a fixed, sufficiently large color palette upfront that contains all colors we may need
   6. If we do plan to support dark mode, we'd need a second color palette set with dark mode versions of the above
3. Fonts
   1. Font names, font files, and general guidance on when each should be used
   2. ~10 font sizes, in rem or px units, scaling from smallest captions to largest headers. 
4. Container widths: Elements currently use all sorts of hardcoded widths and heights to define dimensions. We should instead use a fixed set of widths (along with flexbox, rows, etc.)
5. General guidelines such as what colors and sizes buttons, links, text, etc. should be. 

Other notes:
- Feel free to specify font sizes, widths, heights, etc. based on screen width to ensure the design is responsive
- A suitable answer for some of these is "pull them from Figma" if the Figma mockups use the desired fonts and colors that we want. For example, I can pull out all the font names and font sizes used in the new mockups if that would be helpful and save time.
- Also, I have some color palettes that I typically use for reds, yellows, greens, and various shades of neutrals—let me know if it'd be helpful to share those those.

### Implementation

1. Create base Sass files in a new folder called `app/assets/v3/css` that defines the variables, colors, fonts, base utility classes, etc. 
2. Go through the Grants codebase and update styling to *only* use what's defined in these base files + Bootstrap
   1. Replace manual color codes, font sizes, `style=`, etc. with the new utility classes
   2. All margins and paddings should use the Boostrap defaults
   3. Replace Vue conditional styles with conditional classes
   4. Remove classes that are only used one-time, such as `.grants-description`, and replace them with just utility classes
   5. Classes that are used multiple times can be rolled up into a bigger utility class such as `.btn-primary`, which is defined by mixins of utility classes
   6. Do remaining changes "piece-wise" to ensure consistency, e.g. first update all fonts, then update buttons, etc.
3. Delete existing stylesheets once we are sure they're no longer needed/used

## Open Questions

1. Feedback on this plan is welcome! This is just a first draft
2. We'll have the new stylesheets existing simultaneously with the old ones. To avoid class naming conflicts, should we temporarily prefix all new classes with something unique such as `ngs-` (new Gitcoin styles)? It should then be easy to remove that prefix through the codebase when updates are complete
3. We currently have both Bootstrap 4 and Bootstrap-Vue. I don't use Bootstrap often so I'm not too familiar with these—do we need both of those? Do they have conflicting definitions at all?
4. Do we want to stick with Bootstrap for things like spacing classes, e.g. `py-4`, rows/flexbox, etc., or do we want to look into alternatives? Since I haven't used Bootstrap much so can't comment on it's pros/cons
5. Will Django let us import `.scss` files directly, or do they need to be compiled first? If the latter, what does this development process look like?

**Comment by thelostone-mc** [comment]
we've attempted sass -> css compiler a few times in django but have had no luck with it!
If you can figure out how -> I would def favour this 

---

Utility > Semantic. Works for me 

---
Buttons -> I would love for this to work but we'd need 
### Button Type 
 - Primary 
 - Secondary
 - Danger
 
### Button Size 
 - small
 - medium
 - large

**Comment by octavioamu** [comment]
Nice
The thing about components keep in mid we use bootstrap-vue so instead gc classes can be created to overwrite those keeping the functionality and just changing styles. Actually we are already using btn-gc-blue on those to apply our button styles.

**Comment by mds1** [comment]
> we've attempted sass -> css compiler a few times in django but have had no luck with it!
> If you can figure out how -> I would def favour this

@thelostone-mc Ah interesting, so what's the deal the 25 `.scss` files then? Are those not used? 

Also, do you have any links to issues/documentation with details on the previous attempts? I think it's worth taking another shot to see if we can get it working with Django—it's definitely better than CSS, and both it + Django are popular enough that I'd be surprised if we can't get them working together!

> Buttons -> I would love for this to work but we'd need...

@thelostone-mc The bootstrap buttons @octavioamu mentioned already have small, medium, and large sizes, and all we'd have to do (like it seems we're already doing) is define classes for the different appearance, so this shouldn't be a problem

> The thing about components keep in mid we use bootstrap-vue so instead gc classes can be created to overwrite those keeping the functionality and just changing styles. Actually we are already using btn-gc-blue on those to apply our button styles. ex
> <b-button class="btn btn-gc-blue px-4 font-body"></b-button>

@octavioamu So if I'm understanding correctly, right now are all buttons supposed to be a bootstrap `<b-button>`, using the `btn-gc-*` classes? That approach seems good to me. 

Also, what are thoughts on questions 3 or 4 above? You are definitely more familiar with Boostrap than me so curious to hear your input!

**Comment by octavioamu** [comment]
the problem with precompilers is we don't have a pipeline to compile it, I created the version of kudos with scss but then people edited the css generated I upladed and not the scss so got deprecated very quickly. 
So not precompilers for us, as for using it 2 things are needed, build them on deploy time and build them on development time, so >  run node as a part of pipeline.

**Comment by octavioamu** [comment]
> So if I'm understanding correctly, right now are all buttons supposed to be a bootstrap <b-button>, using the btn-gc-* classes? That approach seems good to me.
no because not all code is vue. some will be just the class with normal html not a component.

**Comment by mds1** [comment]
> the problem with precompilers is we don't have a pipeline to compile it, I created the version of kudos with scss but then people edited the css generated I upladed and not the scss so got deprecated very quickly.
So not precompilers for us, as for using it 2 things are needed, build them on deploy time and build them on development time, so > run node as a part of pipeline.

Hm, I'm not quite following why we can't use Sass. How did you implement it with the Kudos .scss file?

I haven't spent much time looking into it, but it seems we could integrate Sass [like this](https://github.com/jrief/django-sass-processor) or [this](https://www.ronaldlangeveld.com/using-sass-django). Would these work, and If not, curious as to why?

------------------------

> no because not all code is vue. some will be just the class with normal html not a component.
> 
> So in general the idea is to abuse css variables even to overwrite bootstrap, that being used on vue components or normal html.
> 
> Utilities classes are already there from bootstrap.

I did a bit of reading and comparing of bootstrap and bootstrap-vue to try to better understand what we do with them, and here's what I found plus some specific questions I have. 

There are 4 bootstrap files in the repo:
1. `app/assets/v2/css/bootstrap.min.css`
2. `app/assets/v2/css/bootstrap-vue.min.css`
3. `app/assets/v2/js/lib/bootstrap.min.js`
4. `app/assets/v2/js/lib/bootstrap-vue.min.js`

From a high-level I'm trying to understand which of these 4 we primarily use, are there any we don't use much, when is each used, have they been modified, etc. Some info that I've found and some questions:

1. Why do we need two button types such as `<button>` and `<b-button>`? Similarly it seems we use `<input>` and `<b-form-input>`.  Do these different types affect styling? I think some docs on why we use different HTML elements for the same type of element, their differences, and when to use each would be helpful for better understanding the current architecture

1. From what I gather, Bootstrap is written with Sass, and customizing options, colors, etc. requires doing so in Sass. So how exactly do we "abuse CSS variables even to overwrite bootstrap"? I'm not sure where that happens

2. Given the above, it seems the best way to implement this whole design refactor might be to modify Bootstrap's Sass source to use our own color codes, etc., then compile it to a minified CSS file, and use that as our `bootstrap.min.css` file. Even if we have to do this setup/compilation as a one-time step external to the codebase (i.e. not in the build pipeline), it will make things significantly easier to maintain since all our core colors and settings will be auto-generated with utility classes defined in Bootstrap! Does this seem like a good approach? Is this that we've currently done for theming buttons, etc.?

3. Bootstrap CSS files: For styling, is having both `boostrap.min.css` and `bootstrap-vue.min.css` redundant? It seems the two have some small differences in class definitions, so it's not clear which is actually being used. Can we get rid of one of these, and if so which one?

4. Bootstrap JS files: My understanding is that Bootstrap Vue is a third-party library (not by the Bootstrap team) that doesn't change anything about the CSS, but modifies their JS to remove jQuery and instead rely on native Vue functionality for reactivity. I'm guessing this is why we need both—jQuery version for non-Vue files and non-jQuery version for Vue files? What JS bootstrap functionalities do we use? Is this things like tooltips or also reactive styles?

Thanks!

**Comment by PixelantDesign** [comment]
Thanks for putting together this plan @mds1 

>Do we want, or do we plan to support, dark mode? If so this would be good to know upfront so we can start accounting for it now

The only page that has dark mode is townsquare. I think it's a nice to have but not a priority at this time. Curious what @Kweiss thinks. I'd prefer we focus on improving the base experience first.

Could we go through the styles (colors, fonts, etc)  on a call next week?

>Also, I have some color palettes that I typically use for reds, yellows, greens, and various shades of neutrals—let me know if it'd be helpful to share those those.

Would like to look at these

**Comment by mds1** [comment]
Hey all, @apbendi and I came up with a specific plan for implementation of a redesign. Let's discuss this, make any changes, and start executing as soon as we can!

------------------------

- [Setup](#setup)
  - [Code Setup](#code-setup)
  - [Workflow Setup](#workflow-setup)
- [Execution](#execution)
  - [Guidelines](#guidelines)
  - [Main Execution](#main-execution)
  - [Final Steps](#final-steps)
- [Questions](#questions)

## Setup

### Code Setup

1. Obtain color palettes, fonts, font sizes, and any other assets from designers
1. Try to  integrate Sass [like this](https://github.com/jrief/django-sass-processor) or [this](https://www.ronaldlangeveld.com/using-sass-django). If it doesn't work, document why in an issue for future reference
1. Create `app/assets/v3/sass` (or `css`) folder. We'll assume Sass for the rest here, but can update accordingly if Sass doesn't work
1. In the `sass` folder, create the following files:
   1. `variables.scss` defines everything from step 1 in variable names
   1. `classes.scss` uses the variables to define all base utility classes. For example, if the purple color palette has 10 shades we should have `z-text-purple-1` through `z-text-purple-10` for text colors, and `z-bg-purple-1` through `z-bg-purple-10` for background colors. We prefix *every* `v3` class we create with `z-` to avoid naming conflicts, since there are currently no classes that use that convention (some current ones do start with `g-`)
   1. `wrappers.scss` is where wrapper classes like `.btn-primary` will live. These should be kept to a minimum and only used for site-wide components like buttons, form fields, alerts, etc.
   1. `index.scss` imports all of the above files
1. Keep the old `app/assets/v2/css` files around for now

### Workflow Setup

1. Create a `redesign` branch off the staging branch
2. Someone is responsible for rebasing `redesign` against `master` (or `stable`?) every day
3. Branch off `redesign` and submit PRs back to that branch
4. First branch off `redesign` should be some initial global changes discussed later + above code setup
5. Be sure to keep your own branch rebased against the latest `redesign`

## Execution

### Guidelines

As you go through the execution steps below, follow these guidelines:
1. **DO NOT** use inline styles with `style=`. If you see those, replace them with classes
1. **DO NOT** use Vue conditional styles. If you see those, replace them with conditional classes
1. **DO NOT** define classes that are very specific or only used once or twice, such as `.grants-description`. Replace them with the appropriate utility classes 
1. **DO NOT** use any of Bootstrap's colors or classes that use colors
1. **DO NOT** use Bootstrap-Vue's `<b-button>` or other special elements. Because of the Vue vs. non-Vue mix, this makes things harder to maintain by introducing inconsistency between different parts of the codebase
1. **DO** use bootstrap's existing utility classes when appropriate for things like margin, padding, and text-alignment. Because code is a mix of Vue and non-Vue, always use regular Bootstrap classes, not Vue ones
1. **DO** prefix every class you create with `z-`
1. **DO** search for an applicable Bootstrap class before creating your own
1. **DO** use mixins to avoid declaring a style more than once

### Main Execution

1. Implement code setup from above on `redesign` branch
2. Implement global changes to fonts, colors, nav, etc. on `redesign` branch (this should be done by the same person as step 1)
3. Triage: Make each page look good enough to be "shippable". Each person is responsible for certain pages. PRs are made to `redesign` branch. 
   1. The goal is to make things presentable to users, but you don't necessarily have to meet the full refactoring standards—hacky solutions are ok for now
   2. Pages do not need to look exactly like the final design
4. PR step 3 into `master` and ship to staging/production
5. Make each page meet the style guide and look like the final design
   1. Now the goal is to make pages look exactly like the final design
   2. Other developers adding features to `stable` or `master` should use the new styles that were merged in step 4


### Final Steps

1. Remove `bootstrap-vue.min.css`
1. Try updating Bootstrap from v4.3.1 to v4.6.0. If this causes a lot of changes, just stick with v4.3.1
2. Remove old `app/assets/v2/css` files/classes that are not used
3. Update `CONTRIBUTING.md` to explain the new style guides so contributors can easily follow it

## Questions

1. Dark mode: Do we (1) build this in now, (2) port over the existing partial implementation on Town Square, or (3) ignore this entirely for now and revisit later. I learn towards (3) because we have a tight timeline, and the refactor will make it much easier to add dark mode later
2. Large changes to `stable` during the redesign can make it difficult to keep rebasing due to conflicts—what will be the status of the rest of the codebase while we do the redesign? Are there currently any long-running features/branches that we should coordinate with?
