### ISSUE TITLE
Update Sentry Python SDK

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8309]
### Who
As an internal team member

### What 
let's make sure to update our Sentry Python SDK

### Why
so we can take advantage of the new SDK's stability, performant capabilities, and the ability to send transactions.

### Description
Luckily, this only takes a few lines of code:

```
import sentry_sdk
sentry_sdk.init("your DSN",
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,
)
```

but here's the [documentation](https://learn.sentry.io/e2t/tc/DVttwpCmZqW1ZJd1h69KWn6W58c1_74mhzPfN8JCsD73lGmwV1-WJV7Cg-JCVWXJKz3lSCZ8W4qJG-b1hX4WJW8Ggy4y2wt9GVW1zW4gk7pCgpwW3FG0Cf2G0Y8DN2fsDpV4sly7N1lLnT0W1MDTW7wC5gk5gQ8t_W17WlYn2NdwFFMjGRNHj06c5W5m6pQH2mqyChW1L095z1MX8s0W1RCmLT3YFV1QW32L5fw6D-31fW35v5G18QwrX5V5D8M_4_SC6BW67rJ1V6mHdtqW8VDHCR4YSXFJW24qwT37cWwbtW83ZLjh42Skp934Nv1) too.

**Comment by gdixon** [comment]
@frankchen07 What would be a sensible traces_sample_rate for the expected load?
