### ISSUE TITLE
Revert gas price vs confirmation time

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#831]
https://gitcoin.co/gas right now looks like this:

![image](https://user-images.githubusercontent.com/8781107/38474641-fe901762-3ba9-11e8-8bb9-71258754f22a.png)

Which doesn't seem too informative to me. How about switching axis?

(as a bonus points)
* make graph scale
* use historical data to measure realistic max gas price on axis

**Comment by owocki** [comment]
hehehe.. when the ethereum network is doing really really well (operating fast and effectively), then the gitcoin.co/gas graph looks bad..  

i'd almost advocate for not showing the graph if conditions are such that you can confirm a tx for < 1 gwei in < 1 minute.  just say "the ethereum network is operating at peak performnance"  then a subtitle "there is no tradeoff between speed and price right now.  please use 1gwei for a cheap, fast, tx"

**Comment by abitrolly** [comment]
Placing a button to rotate the axis would solve the problem for me. The price can also be < 1gwei, right?

**Comment by mkosowsk** [comment]
@abitrolly I don't think so, I thought 1 gwei was the atom that couldn't be split for a tx? 🤔

**Comment by thelostone-mc** [comment]
We could use a charting library that renders the scale based on the values ! Might solve the problem

**Comment by owocki** [comment]
> @abitrolly I don't think so, I thought 1 gwei was the atom that couldn't be split for a tx? 🤔

you can def do 0.1 or 0.2 gwei gas in metamask.  not sure about other clients 

the data is gathered from here https://ethgasstation.info/predictionTable.php

**Comment by owocki** [comment]
would something like this help? 90ca798c19a58b2fb8b47176739c269b99d0b4b9

[screenshot](http://bits.owocki.com/3w352B3R0U0r/Screen%20Shot%202018-04-09%20at%201.42.53%20PM.png)

**Comment by eswarasai** [comment]
@owocki -- Any ideas about using this or working on top of it maybe? -- https://eswarasai.github.io/gasprice/

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/38536427-d386a124-3c91-11e8-9418-f3e504ab487b.png)
I can read this graph much easier.

**Comment by PixelantDesign** [comment]
@abitrolly I think that does help make it clearer. Would be great if the chart knew how to scale based on the data available. I do think it's helpful to have values on x and y axis for the points in between.

**Comment by owocki** [comment]
> Would be great if the chart knew how to scale based on the data available. 

we can do this!  in fact, its what https://github.com/gitcoinco/web/commit/90ca798c19a58b2fb8b47176739c269b99d0b4b9 was meant to do

**Comment by owocki** [comment]
example of the above commit at work (gas chart scaling) https://gitcoin.co/gas

**Comment by abitrolly** [comment]
Graph is strange on Firefox.

![image](https://user-images.githubusercontent.com/8781107/39096465-1db01f98-4659-11e8-9ac2-5572b179447e.png)

**Comment by kuhnchris** [comment]
@owocki you played around but never commit this, no? :-)
