### ISSUE TITLE
Text in a grant is not looking good

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#8310]
**Describe the bug**

This grant: https://gitcoin.co/grants/1923/doruk-ismen is not looking good as the text is overlaying the card in the right:
![immagine](https://user-images.githubusercontent.com/50027175/106024154-c54f5080-60c7-11eb-87ff-ede8ccb18bb7.png)

**To Reproduce**

Check the grant I linked above

**Expected behavior**

Text should not be overlaying

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by gdixon** [comment]
On Firefox? It looks like we need to add `width: 100%;` to `.grant-data`.

**Comment by Solexplorer** [comment]
Exactly, it's on firefox
