### ISSUE TITLE
Kudos problem 

### ISSUE THREAD

**Issue by lardboi69** [gitcoinco/web#8319]
### Why
Hi I'm having. Problem with my kudos I received one but don't know how to claim it to my wallet

**Comment by amalnathsathyan** [comment]
Same here. It says the kudos has been sent to the given address on xDai. But when verifying the TX hash, it all goes to same address :- 0x2aEa4Add166EBf38b63d09a75dE1a7b94Aa24163

**Comment by owocki** [comment]
what is your wallet addr?  can you check your kudos tab in your profile + see if the tx are linked to any xdai block explorer urls?

**Comment by owocki** [comment]
just re-issued some of your kudos on xdai, can you try now?

**Comment by lardboi69** [comment]
So I found out that my xdai has been going to a contract address instead of
a wallet address. Here is my wallet
address. 0xe03dff0e3DdcFEC4a49A0C8A0F666a253B4802bb.

The 2a .4163 address isn't valid but I have 3 hundreds and somewhat xdai
that's been going to there.

**Comment by owocki** [comment]
@lardboi69 i just reissued your kudos.  check https://gitcoin.co/lardboi69/kudos to see the txid; they should show up in your wallet now. 

check https://gitcoin.co/blog/the-future-of-gitcoin-kudos/ to see the wallet address + instructions on how to connect ot metamask
