### ISSUE TITLE
PR previews

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#832]
As a PR reviewer I want to see automative previews of PR so that I don't have to install everything and test locally.

For example, to click through links on https://github.com/gitcoinco/web/pull/829

**Comment by kuhnchris** [comment]
Is this even possible @danlipert ? (from a backend view of things...)

**Comment by abitrolly** [comment]
It is posssible, yes. https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/
