### ISSUE TITLE
Can someone verify my account? 

### ISSUE THREAD

**Issue by litanas93** [gitcoinco/web#8332]
### Discussion

[comment]: # (What conversation would you like to facilitate?)

Hello, 

Can someone verfiy my account? I signed up with you a week ago, but I can't pick up the kudos because the account is too new.

**Comment by nsxnx** [comment]
I would love to get verified as well. Not a fan of BrightID and don't have a twitter account, hoping I can collect kudos too

**Comment by Kweiss** [comment]
Hey there - you can do this in the profile page here: https://gitcoin.co/litanas93
