### ISSUE TITLE
Sync db to mautic

### ISSUE THREAD

**Issue by octavioamu** [gitcoinco/web#8338]
### Task
We need to run an script to sync users data to mautic

#### Query
Fetch user table join profiles at least active in the last **1 year**
query the email pref for each user.

Result headers and info need to be a csv file following format:

email | github_handle | last_active | new_bounty_notifications | welcome_mail | roundup | important_product_updates | general | quarterly | grant_recontribute
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------

The fields:
new_bounty_notifications | welcome_mail | roundup | important_product_updates | general | quarterly | grant_recontribute
match the email settings names on our db and need to be the opposite !Boolean

**Comment by octavioamu** [comment]
@frankchen07 I will be focus on the new styles I asked @thelostone-mc a help with this, to generate the csv file.

**Comment by thelostone-mc** [comment]
last_active seems is a boolean called active. not sure if that's what you're looking for
Additionally could you share an example row so that I can check to see the data format
@octavioamu @frankchen07 

https://gist.github.com/thelostone-mc/17120a467a07026afd39ac9ef2b0c58c
