### ISSUE TITLE
Support for Multi-payee bounties

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#834]
It'd be fairly easy for us to enable bounties that are paid to multiple payees

We'd just have to change [this line](https://github.com/Bounties-Network/StandardBounties/blob/master/contracts/StandardBounties.sol#L201) this line in standardbounties to `total_funding_amount/total_payees`... and probably update the bounty detail / funding_new forms to account for the fact that there can be several payees

**Comment by kuhnchris** [comment]
was it that easy?
