### ISSUE TITLE
How to receive matched funds from special round?

### ISSUE THREAD

**Issue by seichris** [gitcoinco/web#8340]
**Describe the bug**
[Our grant](https://gitcoin.co/grants/1464/kontextapp-social-bookmarking-on-filecoin-ethereu) is part of the Filecoin APOLLO matching round, which should have ended mid January.

I just wanted to claim the matched donations, but am not able to do so. I am logged in with the grant receiver Eth address.

**To Reproduce**

1. Auth Metamask with receivers address
2. No claim button

**Expected behavior**

1. Auth Metamask with receivers address
2. Claim button appears?!?

**Comment by BTCAlchemist** [comment]
I also experienced a delay with received matching grant funds from the APOLLO category. Yesterday (Feb. 17), I did receive a payout; however, that payout of 740 DAI was lower than the 1,086 USD final match displayed on the grant page for this round (screenshot below). How may I receive the 346 DAI difference?

![image](https://user-images.githubusercontent.com/56145569/108433907-9b3b0b00-71fb-11eb-9f74-ffab8f530b6b.png)

**Comment by BTCAlchemist** [comment]
@thelostone-mc My team is still missing ~350 DAI from our APOLLO round matching award from January. Could you help sort this out or point me toward the right person?

**Comment by Kweiss** [comment]
Hey there - Just an FYI we are looking into this. We have bene radio silent for a bit and that is not our intention. Let me get back to you with a few questions we have @BTCAlchemist 

@seichris - Let us know if you do not see the claim button for the matching funds and we can look into that too

**Comment by seichris** [comment]
@Kweiss My issue was resolved, and the grant paid out manually. Just keeping this issue open for @BTCAlchemist

**Comment by BTCAlchemist** [comment]
@Kweiss I appreciate your reply. Here is the link to my grant with the above-referenced issue: https://gitcoin.co/grants/1413/meme-of-the-day

**Comment by BTCAlchemist** [comment]
@Kweiss @thelostone-mc Gitcoin Grants Round 9 started today, and I'd like Gitcoin to change my grant category to GR9, but I also don't want to lose the APOLLO matched funds. What is the update on this issue, and should we change the category now or after you send the missing 346 DAI?

**Comment by owocki** [comment]
@BTCAlchemist 
https://etherscan.io/tx/0x720bf163443a4dcca852e8dd4da91083c86763ec19900f61c6110e6aeef8f092 the APOLLO grants payout for this grant has already been paid on 2/17

@seichris your payout is 0xd011b266a4aafecf33f59fe60469598a6aa46a80de4bacfcca9a31d3002533a4

**Comment by seichris** [comment]
@BTCAlchemist closing this issue. Feel free to open a new one

**Comment by owocki** [comment]
> however, that payout of 740 DAI was lower than the 1,086 USD final match displayed on the grant page for this round (screenshot below). How may I receive the 346 DAI difference?

please open up a new issue for this
