### ISSUE TITLE
gpg - navigation / main nav

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8367]
### Circumstances

Using our new atomic design foundations, update the homepage navigation of gitcoin.co

### Description

Figma: https://www.figma.com/file/JTzaUKVxnGEmlaD3L8KsSm/Gitcoin-Design-System---WIP-020221?node-id=53%3A748

### Product Requirements Document

https://docs.google.com/document/d/1Ez9XF4zuMYVRB0bG2mWF7Cz_Fa0nAkMR3Yef1-eyU5c/edit#

TLDR PRD:

- applying our new design components
- adding the "what's possible" dropdown to the current nav, replacing "townsquare"
- move "townsquare" into the "community" dropdown
- keep the "products" tab as it currently exists
- remove "looking for developers"

**Comment by frankchen07** [comment]
nav feedback on staging:

looks like the earn and fund "purple" hover overs have different sizes:

![Screen Shot 2021-04-08 at 15 39 03](https://user-images.githubusercontent.com/7516920/114104993-c13a6e80-9880-11eb-8e71-1317d033490e.png)
![Screen Shot 2021-04-08 at 15 39 10](https://user-images.githubusercontent.com/7516920/114104997-c26b9b80-9880-11eb-9a36-cfe891282e17.png)

**Comment by Kweiss** [comment]
I would love @PixelantDesign 's feedback. I gave this to Graham:

One minor nit for feedback on the new menu - I love seeing it... I wonder if we can have the purple only show on the text, and not the icon as well? The purple is a bit much...
![Screen Shot 2021-04-08 at 8 01 59 PM](https://user-images.githubusercontent.com/1017776/114118516-2b193f00-98a6-11eb-8ec8-5847136cc819.png)

on the products section, it is nice as it doesn't consume the whole section... then on the new section, the icons being colored on hover is too much (IMO)
![Screen Shot 2021-04-08 at 8 02 06 PM](https://user-images.githubusercontent.com/1017776/114118535-31a7b680-98a6-11eb-983c-b884428d2674.png)

Does the design show the whole thing being purple?

**Comment by PixelantDesign** [comment]
I had originally intended to the menu items to follow the link color set in the design system but also don't what exists In the products menu as Kyle mentioned above since that was implemented in the first version of this new nav.

**Comment by octavioamu** [comment]
the button is all the area so hover should be in the area of the element IMO

**Comment by gdixon** [comment]
Hi Alisa, please see below for all variations of how this feedback could be interpreted:

<img width="1102" alt="Screenshot 2021-04-12 at 13 40 13" src="https://user-images.githubusercontent.com/5897836/114399548-f274b080-9b98-11eb-8dc1-45193000375e.png">

I've seen that you've updated the figma to show the hover state for one item - should I follow the design system or figma? In the design system a link should be purple (which darkens and becomes underlined when it is hovered) - if this is what we want to go with, should it be applied to every link in the nav (including all of the links in the products menu too)? This would mean that nearly all of the text in the menu is purple, is that the intention?

**Comment by PixelantDesign** [comment]
Hey @gdixon are we able to do something like this where it's a subtle text color change?

States:
Normal ---keep it gray 500
Hover --- default purple
Click --- dark purple 

<img width="1561" alt="Screen Shot 2021-04-12 at 11 08 37 AM" src="https://user-images.githubusercontent.com/238235/114418041-22fc2080-9b80-11eb-8053-9b93a356bcce.png">

 I realize it's custom from the system, but it's a more subtle solution and aesthetically cleaner/less bulky/ more open feel.

**Comment by gdixon** [comment]
Should this same set of rules be applied to the _Products_ and _Company_ menus too?

**Comment by willsputra** [comment]
seems like the Learn and Earn icons are mixed up (Earn should be the eth icon)
![Screenshot 2021-04-13 at 9 03 45 PM](https://user-images.githubusercontent.com/19514207/114556977-ce4dc800-9c9b-11eb-805e-db3bb300fca1.png)

**Comment by frankchen07** [comment]
> should same set of rules apply

I would think that's the purpose of having standardized design components, but I believe final call is @PixelantDesign.

**Comment by gdixon** [comment]
> > should same set of rules apply
> 
> I would think that's the purpose of having standardized design components, but I believe final call is @PixelantDesign.

I think the message I replied to was deleted - @PixelantDesign suggested we use the standard link colors and effects - but we've spoke since then and have settled on the compromise which is currently on staging 👍

**Comment by PixelantDesign** [comment]
Yes! We've rev'd on many parts of the nav on the fly in gather. It's looking awesome.

Wanted to capture a few things here around the company menu:

In the company menu could we order the menu items as follows-
Left side:
About
Mission
Results
Products

Right side:
Blog
Jobs
Wiki

We will have mission, about and home when the new pages roll out. We combined/simplified vision and mission. So no vision menu item is needed. The current content is outdated anyway.

The company icons are looking great!
Could we switch out the building under mission, for a [rocket](https://fontawesome.com/icons/rocket?style=light)?

Thanks @gdixon!
