### ISSUE TITLE
Gitcoin.co/townsquare page not loading properly.

### ISSUE THREAD

**Issue by PiotrNap** [gitcoinco/web#8369]
**Describe the bug**
After logging in and redirecting to https://gitcoin.co/townsquare from the homepage, it looks like the browser
cannot access some of the .js and .css resources, which causes the page to look very odd.

**To Reproduce**

1. Go to https://gticoin.co
2. Log in with your Github account
3. Land on the next page ...

**Expected behavior**
A site to looks as expetced(?)

**Screenshots**

![image](https://user-images.githubusercontent.com/59693946/107125637-677eed80-68ab-11eb-8a39-581e25d51c05.png)

**Desktop (please complete the following information):**

- OS:
- Browser: Brave Dev / Chrome
- Browser Version: 1.21.45 / 88.0.4324.146

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/issues/8370#issuecomment-774909493
