### ISSUE TITLE
Duplicate "Funds Paid" email being sent

### ISSUE THREAD

**Issue by jakerockland** [gitcoinco/web#837]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
I received two identical "Funds Paid" emails after having my completed bounty accepted.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
I should only receive one of these emails.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
I believe that this could be recreated by creating a dummy bounty and then completing that bounty but I'm sure there is a better way to test this in sandbox--just not familiar enough with the codebase here yet to outline that in detail.

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*: Not quite sure without looking into this in detail 😓 

### Additional Info
Emails were both sent to my `jakerockland @ gmail.com` email.
Emails were both sent to me from `founders @ gitcoin.co` email.
Emails were both sent at `Monday, Apr 9, 12:06 PM MST`.

**Comment by owocki** [comment]
just put in a fix for this https://github.com/gitcoinco/web/commit/9f209627a9ecfe2efa0e54679fa5a27bcb712ddd
