### ISSUE TITLE
CORS issues on stylesheets

### ISSUE THREAD

**Issue by Solexplorer** [gitcoinco/web#8370]
**Describe the bug**

If you clear browsing data in chrome or you go in incognito and you login, the interface doesn't show the css correctly because there's some cors issues on https://s.gitcoin.co/static/v2/css/bootstrap.min.92af3981f106.css
![image](https://user-images.githubusercontent.com/50027175/107127410-3ce66200-68b6-11eb-951e-927d12fa8f70.png)

Console error:
`Access to CSS stylesheet at 'https://s.gitcoin.co/static/v2/css/bootstrap.min.92af3981f106.css' from origin 'https://gitcoin.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**To Reproduce**

Go in incognito mode, login and you will see exactly what I posted above

**Expected behavior**

The resource should be loaded and no cors errors should pop up

**Screenshots**

**Desktop (please complete the following information):**

- OS:Mac OS
- Browser: Chrome
- Browser Version: Mac Version 88.0.4324.96 (Official build) (x86_64)

**Comment by PiotrNap** [comment]
I have already posted it -> check here https://github.com/gitcoinco/web/issues/8369

**Comment by gdixon** [comment]
Hey, thank you @PiotrNap & @Solexplorer! We have a PR going in today that will close this, that particular resource is being loaded with crossorigin="anonymous", and the login process is passing a 302 header that doesn't seem to be playing well with the CORS settings. 

#8360 will drop the crossorigin attribute, and will therefore allow us to load that resource without checking the CORS origin. In the meantime, if you do a hard refresh (cmd-shift-r), all of the resources will be fetched again and the page will load correctly.

**Comment by gdixon** [comment]
Fixed in: #8373
