### ISSUE TITLE
missing donation to my chosen grant project

### ISSUE THREAD

**Issue by SirPepeNerd** [gitcoinco/web#8371]
Hello Gitcoin

today i checked with the Pepemon project:
https://gitcoin.co/grants/1805/pepemon-degen-battleground

and it seems they never got my donation.
while the TXID clearly shows my donation to Gitcoin..
made it from the project site to my cart.
hence i dont have the funds anymore and it was a good donation for them, i wish to know where it went and if they can still get the donation. Because they deserve all they can get to help them further. the project

Transaction hash: 0x95777c7ac79242121b8bfe2173c0a074d622c05794c0c8b1620f09f7b1c8c626

its a 0.15 $eth donation mend to be donated to the Pepemon project stated above..

please find out what happend to my donation and why the project did not get. these funds

sincerely,  SirPepeNerd, owner of wallet id: 0x3977a17ea19bf3f99f15c199225052593085a031

**Comment by Kweiss** [comment]
Hey there - Can you add the Tx details here?

https://gitcoin.co/grants/add-missing-contributions

thanks so much! 🙏
