### ISSUE TITLE
Replaced transaction was not reflected on bounty page 

### ISSUE THREAD

**Issue by frostiq** [gitcoinco/web#8372]
I've replaced a bounty payout transaction with another one with higher gas price, but it was not reflected on Gitcoin
Link to the bounty: https://gitcoin.co/issue/frostiq/cryptomedia-subgraph/9/100024685

Original transaction (dropped): https://etherscan.io/tx/0x8ed04756e7b61f3c783fd794881ad0849ff0c2c8daf2901f4ae3e5ba1c6274f2

Replacement transaction (mined): https://etherscan.io/tx/0x94c7ab30fb01a4292a1c36efd03c5177cf5d8d7f9d3907a5875bd8b28a8f4af6

**Comment by frostiq** [comment]
Could you please change tx hash in the database, @thelostone-mc ?

**Comment by frankchen07** [comment]
@frostiq - thanks for logging this issue, it's been resolved, you can check it on the bounty page!

**Comment by frostiq** [comment]
@frankchen07, thanks!
I see that the bounty is in Submitted state. Can you please suggest how can I complete it?

**Comment by frankchen07** [comment]
Since the bounty is already paid, I've updated the status to done for you!

Best,

Frank Chen
Product @ Gitcoin
