### ISSUE TITLE
zkSync checkout failure

### ISSUE THREAD

**Issue by DMats** [gitcoinco/web#8376]
**Describe the bug**
zkSync checkout failure. Failed to fetch your Ethereum balance. Reason: [object Object].

**To Reproduce**
1. Navigate to the shopping cart
2. Enter DAI amount, 5% Contribute to Gitcoin Grants Development Fund
3. Select **Checkout with zkSync**
4. Select **Proceed** on dialog box
5. Metamask is detected, public wallet address appears on screen
6. Select **Login**
7. Metamask opens and asks me to sign. Select **Sign**
7. New tab opens. Background shows "Step 1. Setting things up". Foreground dialog says "Fatal error
Failed to fetch your Ethereum balance. Reason: [object Object]. The error above makes it either impossible to proceed to checkout or prevents the opener page from recording that you completed the checkout. You should leave the page.
8. Select **Close the page**
9. Tab closes, returns to Gitcoin Cart tab. Error message displays "Checkout not complete: User closed the zkSync page. Please try again"

**Expected behavior**
Not 100% sure, but I think when the new tab opens, the zkSync setup should complete successfully.

**Screenshots**
This is a screenshot where the zkSync tab detected my metamask address without me having to select the wallet type. It corresponds to step 6 in the **To Reproduce** seciton above. The zkSync setup failed shortly after selecting **Login** and then **Sign** in my metamask wallet.
![image](https://user-images.githubusercontent.com/2530913/107529172-9ab1cd00-6b88-11eb-8096-0cd85f4854d4.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Browser Version: Version 1.19.92 Chromium: 88.0.4324.152 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N/A

**Additional context**
The weirdest thing.  It seems to work now, but the process appears different.

When the zkSync tab opens, it now no longer autodetects my metamask address.  Instead, it asks me to select my wallet.  I select metamask from the options (wallet connect... etc), it asks me to sign, I sign, and then the zkSync setup page appears with a spinning progress indicator, and eventually the progress stops and I'm presented with a screen where I can deposit more DAI into zkSync.  I presume this to be the appropriate flow.

**Comment by Kweiss** [comment]
Hey there - we know zkSnc was having some issues a little while ago. I am going to close this knowing that it seems to working now. thanks for the patience! 🙏
