### ISSUE TITLE
Expired bounty invalid days ago counter

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#839]
### Description
*Type*: Bug

### Current Behavior
Time left counter shows incorrect information. 

### Expected Behavior
Maybe it should be orange and there should be information that bounty is expired. At least 'days ago' should be gone if there are no days left.

### Reproduction
Go to https://gitcoin.co/issue/gitcoinco/web/506

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/840
