### ISSUE TITLE
Newsletter Unsubscribe Does Not Unsubscribe as Expected

### ISSUE THREAD

**Issue by Mike-E-angelo** [gitcoinco/web#8393]
**Describe the bug**
Unsubscribe does not work as expected.

**To Reproduce**
I am encountering an issue with unsubscribe not working at all.  For instance, visiting the "Unsubscribe" link at the bottom of an email takes me to the following URL:

`https://engage.gitcoin.co/email/unsubscribe/<id>/<email>/<id>`

1. To start with, the email field is not filled out, even though it is in the URL, so I have to fill it out.
1. Secondly, the "product" requires a selection.  Does the <blank> (first) mean all?  It is not clear.
1. Lastly (whew 😉), filling out an email, selecting a product, and clicking `Submit` appears to do nothing, and the button is simply left on `Please Wait...` without an update and/or confirmation.

In my case, I happened to subscribe several emails in attempting to fix #6561, but now I cannot seem to unsubscribe any of them.  It would be very helpful if someone could assist my issue here.  I am currently getting four emails for every send on your side.

**Expected behavior**
It would be nice to unsubscribe as denoted by the link that I clicked to unsubscribe. :)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 88

**Additional context**

Thank you for any assistance!

**Comment by lthrift** [comment]
Hi @Mike-E-angelo Thanks for taking the time to make this detailed report. The issues with unsubscribe have been fixed.
