### ISSUE TITLE
An image does not show

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#8397]
https://c.gitcoin.co/logo512.png - Access Denied

I've uploaded this file as the logo for a https://gitcoin.co/issue/binancex/Grant-projects/17/100024656 project. The UI looks broken.

**Comment by Kweiss** [comment]
Hey Victor - We recently went through and created new hashes for images and redesign how those images were being compressed. Can you try pulling the image URL again? Let me us know if that doesn't resolve things.
