### ISSUE TITLE
maybe gitcoin grants sync state error？

### ISSUE THREAD

**Issue by icepy** [gitcoinco/web#8415]
**Describe the bug**

Gitcoin Grants sync state error ? 

![WX20210219-090045](https://user-images.githubusercontent.com/3321837/108441882-fd921b00-7290-11eb-81d0-35574ef2aa42.png)

![WX20210219-084807](https://user-images.githubusercontent.com/3321837/108441084-58c30e00-728f-11eb-9f47-1d6e86ae4b34.png)

Grants

- [https://gitcoin.co/grants/2001/simthunder-sim-racing-assets-marketplace-by-simra](https://gitcoin.co/grants/2001/simthunder-sim-racing-assets-marketplace-by-simra)
- [https://gitcoin.co/grants/1998/carti-a-decentralized-cartesi-machines-package-ma](https://gitcoin.co/grants/1998/carti-a-decentralized-cartesi-machines-package-ma)
- [https://gitcoin.co/grants/86/gitcoin-grants-round-8-dev-fund](https://gitcoin.co/grants/86/gitcoin-grants-round-8-dev-fund)

Transaction Details

- [https://cn.etherscan.com/tx/0x3a4bc8582005753467c4ac867611896887a76ded748214d869f81001a3e8eb65?locale=zh-CN&utm_source=imtoken](https://cn.etherscan.com/tx/0x3a4bc8582005753467c4ac867611896887a76ded748214d869f81001a3e8eb65?locale=zh-CN&utm_source=imtoken)
- [https://cn.etherscan.com/tx/0x5baceb32065c08b60e473cbbf4aea344f6d15e1fdaf28e88ceb71366ace26800?locale=zh-CN&utm_source=imtoken](https://cn.etherscan.com/tx/0x5baceb32065c08b60e473cbbf4aea344f6d15e1fdaf28e88ceb71366ace26800?locale=zh-CN&utm_source=imtoken)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 11.2
- Browser: Chrome 
- Browser Version: 88.0.4324.150

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Kweiss** [comment]
The pending state happens when a transaction doesn't complete (gas fees are too low, etc.). If the transaction completed and is missing, do you want to add it here:
https://gitcoin.co/grants/add-missing-contributions

Please re open this if you are still running into problems after it back 🙏
