### ISSUE TITLE
Donation tx not recorded on Gitcoin dashboard

### ISSUE THREAD

**Issue by pakaplace** [gitcoinco/web#8420]
**Describe the bug**
I sent a donation to become a matching partner and it didn't appear on my profile. I think it may be because I double clicked and set up two transactions- one of which I rejected and one of which I approved. 
Tx hash: https://etherscan.io/tx/0x51e697551e7263ab36ab76dad33b61bbb9ec950956910fcd05b17965e180dc1b
Amount: $20
My username: @pakaplace

I'd like it to appear on my profile so I can keep track of ongoing donations. 

**To Reproduce**

1. Went to gitcoin grant form.
2. Completed form
3. Tx teed up by gitcoin. I rejected the first one, and confirmed the second one (buggy metamask double click). 
4. No Tx history shown in gitcoin although tx is confirmed

- OS:
- Browser: Chrome/Metamask

**Comment by Kweiss** [comment]
Do you mind adding the Tx details here: https://gitcoin.co/grants/add-missing-contributions

Please re open if this doesn't resolve the issue :)

Thanks for donating!
