### ISSUE TITLE
gpg - crosschain/xinfin/bounties

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8422]
#### Frontend
- [x] Add chain to bounty creation + hack form form (staff flag)
- [x] Funder should be able to create bounty with edgeware
- [x] User should be able to start / stop / submit work with edgeware
- [x] Funder should be able to payout using web3

#### Backend
- [x] Make changes to `/v1/contribute` endpoint
- [x] Add in chain sync logic
- [x] Update cron to rety pending txn
- [x] testing

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/pull/8421
