### ISSUE TITLE
Run script to connect unsubscribed Django to Acquia

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8432]
### Description

Connect unsubscribed folks from Django to Acquia using a script that Aditya wrote

**Comment by thelostone-mc** [comment]
Ran this yday and octo picked up the csv from the server
<img width="968" alt="Screenshot 2021-02-25 at 11 31 06 PM" src="https://user-images.githubusercontent.com/5358146/109297540-29486e80-7858-11eb-9c9e-eb7d1421e3f0.png">
