### ISSUE TITLE
veification brightID

### ISSUE THREAD

**Issue by ndbbo2** [gitcoinco/web#8434]
**Describe the bug**
 hi i'm new member, i don't know why but with discord or airmeet i can't verify my identity

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by SM4st3r** [comment]
I am having the same issue, I want to contribute to the community. Came here from Voskcoin's channel.

**Comment by Kweiss** [comment]
Hey there - thanks for the feedback, can you detail more of the problem you are running into?

It looks like you are brightID verified now @ndbbo2 - is that not right?

Please re open the ticket if you still need support :)
