### ISSUE TITLE
Invoice feature 500 Error

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#8435]
**Describe the bug**

**To Reproduce**
Go to this bounty and click download invoice
https://gitcoin.co/issue/andyruwruw/chess-web-api/11/100024780

**Expected behavior**
Display/download invoice

**Desktop (please complete the following information):**

- OS:
- Browser: 
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

![image-3](https://user-images.githubusercontent.com/238235/109041525-1e95aa00-769d-11eb-9bfc-c832c51ad727.png)

<img width="1460" alt="Screen Shot 2021-02-24 at 12 31 16 PM" src="https://user-images.githubusercontent.com/238235/109041435-01f97200-769d-11eb-9626-9a21cf5b7ba8.png">

**Comment by thelostone-mc** [comment]
Fixed via https://github.com/gitcoinco/web/commit/5ce47f42c66f72bb63ca6b881133a7cfb380d752
