### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by pkdoddamani** [gitcoinco/web#8436]
Hi Team,

I am still not able to see my Kudos toke that I can see here in my Gitcoin account in my Metamask Wallet. I followed the steps mentioned in video https://www.youtube.com/watch?v=dATfnx1sKUA&feature=emb_rel_end and still I can't see any Kudos token in my account.

Request you to please let me know if I should have certain amount of Xdai in my account to pay for gas fee to get token or does it get credited even if we have 0 Xdai token? How do I get those tokens in my Metamask account? or can i have those in my Trust Wallet?

Thank you

**Comment by owocki** [comment]
what is your wallet addr?  can you check your kudos tab in your profile + see if the tx are linked to any xdai block explorer urls?

**Comment by owocki** [comment]
just re-issued some of your kudos on xdai, can you try now?
