### ISSUE TITLE
Grants Not Showing In My Profile

### ISSUE THREAD

**Issue by LRoddd** [gitcoinco/web#8443]
### Who

Grants Not Showing 

When the transactions went through. Gitcoin gave me a tweet to tweet 
https://twitter.com/leroyrowland/status/1362976563252383749

My profile is not showing the grants I funded
https://gitcoin.co/lroddd
### What 

https://gitcoin.co/grants/1998/carti-a-decentralized-cartesi-machines-package-ma
https://gitcoin.co/grants/2001/simthunder-private-content-and-nfts-marketplace-f
https://gitcoin.co/grants/2003/creol-environments-carbon-credits-infrastructure-

### Why

I dont know why. Hopefully I can get some help. Thank you

**Comment by Kweiss** [comment]
Hi @LRoddd - do you mind adding the Tx details here: https://gitcoin.co/grants/add-missing-contributions

Let us know if they don't show up after using that page.

**Comment by LRoddd** [comment]
It is not letting me add the Tx details. Says "Please enter a valid transaction hash"

https://zkscan.io/transactions/sync-tx:354b55e153a975b6d57f3a8d4104501effbcc2347fe88962754ddb1e4fc18ef4
https://zkscan.io/transactions/sync-tx:fc6587e773b8749063875c7472b55f59eb781401ce0f6c06d79a91fae06bdd5c
https://zkscan.io/transactions/sync-tx:922b86c9920bd3577878cc068ea99e7084bab49a2f33aa5bfdfd21a69c063687
https://zkscan.io/transactions/sync-tx:d00feda5a31ba63fa5b25ef8a0a8227e00e7803e743aa18d77c289baba31b633
https://zkscan.io/transactions/sync-tx:fed0fc5d3a2d4bc5a6504d3b39ff7abadc8a70ab47199a140696f10403b13017
https://zkscan.io/transactions/sync-tx:16cd413fb9032abf105a44c3d5190a1d4d8eb66a97fc6e88cc2f034c63f08f52
