### ISSUE TITLE
Your github profile is too new. Cannot receive kudos. 

### ISSUE THREAD

**Issue by worldofibra** [gitcoinco/web#8444]
Full error reads as:

"Your github profile is too new, so you cannot receive kudos. Please verifiy your profile on BrightID and/or Twitter to proceed."

Getting this error when trying to redeem quest rewards. I've entered my twitter username to my profile but i dont see anywhere to link BrightID.

**Comment by Kweiss** [comment]
You should be able to set up your trust bonus and verify your Twitter here: https://gitcoin.co/worldofibra/trust

Please re open if you are running into problems :)
