### ISSUE TITLE
Hackathon Earn Modal Doesn't Scroll

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#8447]
**Describe the bug**
Hackathon Earn Modal Doesn't Scroll

**To Reproduce**

1. Go to https://gitcoin.co/hackathon-list/ in an incognito window.
2. Accept the cookie disclaimer at the bottom of the modal
3. Make your browser height half the size of the modal height to see that the modal does not scroll.
This is also the case on mobile.

**Expected behavior**
The page scrolls when necessary (depending on browser height).
See example on Gitcoin Grants https://gitcoin.co/grants/new

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome 
- Browser Version:Version 88.0.4324.192

**Smartphone (please complete the following information):**

- Device: iPhone x
- OS: Mac
- Browser: safari
- Version:

**Additional context**

earn modal
<img width="893" alt="Screen Shot 2021-02-25 at 11 39 46 PM" src="https://user-images.githubusercontent.com/238235/109255867-cb1d7c00-77c2-11eb-89e9-dbcaa8c4d6f6.png">

grant modal
<img width="1070" alt="Screen Shot 2021-02-25 at 11 40 43 PM" src="https://user-images.githubusercontent.com/238235/109255923-e5eff080-77c2-11eb-8524-98b615584313.png">

**Comment by gdixon** [comment]
Hey @PixelantDesign, thank you! 

This was caught yesterday: #8441 - the PR has been merged and will be released with the next deploy

**Comment by PixelantDesign** [comment]
<img width="612" alt="Screen Shot 2021-02-26 at 7 36 59 AM" src="https://user-images.githubusercontent.com/238235/109303490-e27f5800-7808-11eb-9e5f-20e746701821.png">
 
@gdixon could one of y'all take a look at this bug? I clicked on Agree but but it didn't do anything. This was on the responsive view. Seems like a conflict between the Cookies banner and join community toaster?

When I clicked Join community banner. it let me proceed. The cookie banner disappeared. 

cc @thelostone-mc

**Comment by octavioamu** [comment]
in that case @PixelantDesign that issue is not related to the original, sumo toaster is not even controlled by us I think you and a few others have access to sumo.
About cookie banner is not an issue, that is when you are on the site for the first time and you need to agree to use the site. 
If you still want to discuss this other topics please open a new issue explaining.
