### ISSUE TITLE
Failing currency persistence on bounty form

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8453]
### Circumstance

There’s a bug where if you are posting a bounty, select ETH as the network, pick DAI or another ERC20, then go back up and make selections for the other details, the token resets from DAI to ETH. It’s caused a decent amount of 1000 ETH sized bounties in hackathons and also for anyone with tribes (it doesn’t cause an issue for regular traditional bounties because the 10% fee alerts them, only when the fee is waived does this become a headache).

AFAIK it happens on multiple browsers.

**Comment by octavioamu** [comment]
solved on https://github.com/gitcoinco/web/commit/c185db7620ad30cf7123cc2d51975aa5bb9881ed will be deployed soon
