### ISSUE TITLE
New Components regression

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/web#8464]
### GR9 Scope items to address

[] Placeholder

**Comment by willsputra** [comment]
listing down my findings, in no particular order:

- [ ] Text on Follow button on hackathon explorer not visible
![Screenshot 2021-03-02 at 9 10 22 PM](https://user-images.githubusercontent.com/19514207/109655290-13131900-7b9e-11eb-8fae-acfbf9ce50f4.png)

- [ ] Clicked Join Hackathon button from hackathon onboard but got 401 error 
![Screenshot 2021-03-02 at 9 13 22 PM](https://user-images.githubusercontent.com/19514207/109655339-21613500-7b9e-11eb-92ae-1cc54de61a4f.png)

- [ ] Change all light blue links to the new design system violet colour
![Screenshot 2021-03-02 at 9 19 19 PM](https://user-images.githubusercontent.com/19514207/109655399-34740500-7b9e-11eb-9116-0e61216f9162.png)
![Screenshot 2021-03-02 at 9 19 19 PM](https://user-images.githubusercontent.com/19514207/109655413-363dc880-7b9e-11eb-8335-790c611c47de.png)

- [ ] Change all the old blue colour to the new design system violet colour
![Screenshot 2021-03-02 at 9 21 24 PM](https://user-images.githubusercontent.com/19514207/109655514-4e154c80-7b9e-11eb-9828-e11d9f48d07c.png)

![Screenshot 2021-03-02 at 9 20 56 PM](https://user-images.githubusercontent.com/19514207/109655460-448be480-7b9e-11eb-9640-ec7401f98f70.png)

- [ ] Hover state on grants sidebar filter looks odd (like there are double text)
![Screenshot 2021-03-02 at 9 22 36 PM](https://user-images.githubusercontent.com/19514207/109655549-5bcad200-7b9e-11eb-8e55-2e169932420a.png)

- [ ] Buttons on https://stage.gitcoin.co/products are not visible
![Screenshot 2021-03-02 at 9 26 42 PM](https://user-images.githubusercontent.com/19514207/109655564-61281c80-7b9e-11eb-9bd7-bec94bf45e7f.png)

**Comment by Kweiss** [comment]
More here:

- [ ] this color scheme is broken (perhaps update the logo to a new logo and font color to a new font color on "jobs") - https://bits.owocki.com/RBu4zX2g

- [ ] dark mode in town square doesn't apply to nav (Not sure if it should, or if we have a design done yet?) https://bits.owocki.com/E0u9mEQE

- [ ] mobile view not updated (double header / menu) https://bits.owocki.com/kpu7Rm2B

**Comment by owocki** [comment]
the on-hover animated logo is gone.  https://bits.owocki.com/xQunQKRx

any plans to bring it back? i think it shows a lot of attention to detail + imbues some joy to have this effect in the logo.

**Comment by owocki** [comment]
broken style here https://bits.owocki.com/BluYq7qw (also on any other page that has this style header, like results page)

**Comment by owocki** [comment]
line height on this page is slightly awkward on the p text https://bits.owocki.com/p9u8Bg44

**Comment by owocki** [comment]
wiki has old nav on it https://stage.gitcoin.co/wiki/

as does the blog https://gitcoin.co/blog/

**Comment by PixelantDesign** [comment]
- button hover looks blue, can we confirm it's the darker color purple as defined?

- logos are broken in the profile modal
- tags not styled
- dropdown not the right color
<img width="890" alt="Screen Shot 2021-03-03 at 4 18 03 AM" src="https://user-images.githubusercontent.com/238235/109783593-2a6ef800-7bd8-11eb-86dc-16d408424f0d.png">

- font in search should be plain, is thick and hard to read
<img width="292" alt="Screen Shot 2021-03-03 at 4 42 25 AM" src="https://user-images.githubusercontent.com/238235/109786270-fea14180-7bda-11eb-888e-21eeaebbfc5d.png">

- funded a grant not showing up in my contributions
<img width="1251" alt="Screen Shot 2021-03-03 at 4 46 54 AM" src="https://user-images.githubusercontent.com/238235/109786853-9e5ecf80-7bdb-11eb-870c-b0b7293d924d.png">

- would be great to make the banner on the button purple with white text when we have a whit background uploaded. Not technically broken but nice to have.
<img width="1654" alt="Screen Shot 2021-03-03 at 4 19 44 AM" src="https://user-images.githubusercontent.com/238235/109783906-7a4dbf00-7bd8-11eb-915c-e17181b839b5.png">

- tip checkbox still blue in cart
<img width="705" alt="Screen Shot 2021-03-03 at 4 28 04 AM" src="https://user-images.githubusercontent.com/238235/109784295-f1835300-7bd8-11eb-80f6-c9b86abf43df.png">

- successful confirmation on grant wall but the message did not come through in the feed.

- when Im in a grant detail, I can't click the browser back button. 

- font size too large in accordion on Quickstart
<img width="989" alt="Screen Shot 2021-03-03 at 5 02 49 AM" src="https://user-images.githubusercontent.com/238235/109788950-d5ce7b80-7bdd-11eb-9a74-b3f53338d714.png">

**Comment by PixelantDesign** [comment]
clicking products >explore kudos doesn't return anything 
<img width="1658" alt="Screen Shot 2021-03-03 at 5 08 34 AM" src="https://user-images.githubusercontent.com/238235/109789746-a409e480-7bde-11eb-937a-895b472ce58f.png">

**Comment by PixelantDesign** [comment]
<img width="812" alt="Screen Shot 2021-03-03 at 5 04 07 PM" src="https://user-images.githubusercontent.com/238235/109879291-655a4580-7c43-11eb-9b37-7d6bc0f9b7c9.png">


<img width="1944" alt="Screen Shot 2021-03-03 at 5 06 51 PM" src="https://user-images.githubusercontent.com/238235/109879333-70ad7100-7c43-11eb-8ea9-5c9544ba39f0.png">


<img width="2045" alt="Screen Shot 2021-03-03 at 5 06 18 PM" src="https://user-images.githubusercontent.com/238235/109879336-71460780-7c43-11eb-92b3-6e785682eb7a.png">


<img width="1892" alt="Screen Shot 2021-03-03 at 5 07 28 PM" src="https://user-images.githubusercontent.com/238235/109879362-74d98e80-7c43-11eb-8109-39795e59271d.png">


<img width="382" alt="Screen Shot 2021-03-03 at 5 03 29 PM" src="https://user-images.githubusercontent.com/238235/109879224-507db200-7c43-11eb-87df-de5dc27905ab.png">

**Comment by willsputra** [comment]
- [ ] Got error when trying to verify trust bonus with twitter
![Screenshot 2021-03-04 at 8 36 27 PM](https://user-images.githubusercontent.com/19514207/109965126-7f6e5380-7d29-11eb-8581-92c10378e922.png)

- [ ] Mobile/hackathon list: when I'm on "Happening Now", tab overflows to two rows
![Screenshot 2021-03-04 at 8 40 00 PM](https://user-images.githubusercontent.com/19514207/109965363-d411ce80-7d29-11eb-9dc0-8d5888d5ba0d.png)

- [ ] Mobile/hackathon explorer: there should be more spacing between tabs
![Screenshot 2021-03-04 at 8 42 08 PM](https://user-images.githubusercontent.com/19514207/109965607-26eb8600-7d2a-11eb-99aa-5e6bffe828f8.png)

- [ ] Mobile/hackathon explorer: background is somehow behind this bar
![Screenshot 2021-03-04 at 8 43 29 PM](https://user-images.githubusercontent.com/19514207/109965708-4e425300-7d2a-11eb-90c3-d5f981df3cf8.png)

- [ ] Mobile/hackathon explorer: on participants tab, user cards are obstructing "Show Filters"
![Screenshot 2021-03-04 at 8 43 54 PM](https://user-images.githubusercontent.com/19514207/109965756-5dc19c00-7d2a-11eb-98f4-4c542636c8d8.png)

**Comment by willsputra** [comment]
- [ ] Grants: after creating a new collection, I was redirected to https://stage.gitcoin.co/grants/collections?collection_id=3 which brings me to my empty profile (correct link should be https://stage.gitcoin.co/grants/explorer/?collection_id=3 )
- [ ] Mobile/Grants homepage: main banner looks off on mobile
![Screenshot 2021-03-04 at 9 53 34 PM](https://user-images.githubusercontent.com/19514207/109974069-248e2980-7d34-11eb-91ec-8d0c7ee90cd5.png)
- [ ] Mobile/Grants explorer: main banner got cut off
![Screenshot 2021-03-04 at 9 54 42 PM](https://user-images.githubusercontent.com/19514207/109974202-45ef1580-7d34-11eb-8258-0ca46c9aea53.png)
- [ ] Mobile/Grants explorer: eth icon floating on the wrong place
![Screenshot 2021-03-04 at 9 55 59 PM](https://user-images.githubusercontent.com/19514207/109974388-7931a480-7d34-11eb-9a90-816355d69341.png)

**Comment by Kweiss** [comment]
The Hackathon details page bar (on the right) of the Hackathon has the text missing on the button.

![image](https://user-images.githubusercontent.com/1017776/110014740-62616280-7ce0-11eb-8ee2-1dccf10ce5a8.png)
