### ISSUE TITLE
when I try to verify my gitcoin grant on twitter it says that the tweet doesn't exist even though I have sent the verification tweet.

### ISSUE THREAD

**Issue by brudda5** [gitcoinco/web#8473]

**Comment by Kweiss** [comment]
A few tips to try:
1 - make sure the tweet is the most recent Tweet you composed
2 - Do not modify the Tweet text at all
3 - you may need to wait up to 30 seconds to verify this as Twitter's API may have up to a 30 second delay in returning the Tweet.

Let us know if that doesn't resolve the issue if you try again.
