### ISSUE TITLE
Change grant receiver address

### ISSUE THREAD

**Issue by seichris** [gitcoinco/web#8475]
Could you please change the receiving address for [this grant](https://gitcoin.co/grants/1464/kontextapp-social-bookmarking-on-filecoin) to 0xB7De690a60A968FC844148d75bFfF9716382b145

**Comment by thelostone-mc** [comment]
Updated ^_^

**Comment by seichris** [comment]
Thanks @thelostone-mc , but it still uses the old address as receiver 🤔
