### ISSUE TITLE
Grant Funding Not Showing In mMy Profile

### ISSUE THREAD

**Issue by LRoddd** [gitcoinco/web#8476]
Who
Grants Not Showing

When the transactions went through. Gitcoin gave me a tweet to tweet
https://twitter.com/leroyrowland/status/1362976563252383749

My profile is not showing the grants I funded
https://gitcoin.co/lroddd

What
https://gitcoin.co/grants/1998/carti-a-decentralized-cartesi-machines-package-ma
https://gitcoin.co/grants/2001/simthunder-private-content-and-nfts-marketplace-f
https://gitcoin.co/grants/2003/creol-environments-carbon-credits-infrastructure-

Why
I dont know why. Hopefully I can get some help. Thank you

I got this message from https://github.com/Kweiss
Hi @LRoddd - do you mind adding the Tx details here: https://gitcoin.co/grants/add-missing-contributions
Let us know if they don't show up after using that page. I Am going to close this ticket and feel free to reopen **:)**

It is not letting me add the Tx details. Says "Please enter a valid transaction hash". Here are the transactions. 

https://zkscan.io/transactions/sync-tx:354b55e153a975b6d57f3a8d4104501effbcc2347fe88962754ddb1e4fc18ef4
https://zkscan.io/transactions/sync-tx:fc6587e773b8749063875c7472b55f59eb781401ce0f6c06d79a91fae06bdd5c
https://zkscan.io/transactions/sync-tx:922b86c9920bd3577878cc068ea99e7084bab49a2f33aa5bfdfd21a69c063687
https://zkscan.io/transactions/sync-tx:d00feda5a31ba63fa5b25ef8a0a8227e00e7803e743aa18d77c289baba31b633
https://zkscan.io/transactions/sync-tx:fed0fc5d3a2d4bc5a6504d3b39ff7abadc8a70ab47199a140696f10403b13017
https://zkscan.io/transactions/sync-tx:16cd413fb9032abf105a44c3d5190a1d4d8eb66a97fc6e88cc2f034c63f08f52

Hopefully I can get some help with this.

**Comment by LRoddd** [comment]
Here is what I'm trying. I tried every possible combination too. 

![Capture](https://user-images.githubusercontent.com/76719813/109722328-c877a980-7b69-11eb-98a0-7097cfed8586.PNG)

**Comment by thelostone-mc** [comment]
@LRoddd could you add only the txn has and not the entire URL and give it a shot ?

**Comment by LRoddd** [comment]
I tried and I'm getting the same result  "Please enter a valid transaction hash" 

![grant](https://user-images.githubusercontent.com/76719813/109831053-500df880-7bfc-11eb-9706-f4bfd93aff5a.PNG)
![grant1](https://user-images.githubusercontent.com/76719813/109831056-500df880-7bfc-11eb-8d18-17416a53f175.PNG)

**Comment by LRoddd** [comment]
Tried it this way too. Same result 
![grant2](https://user-images.githubusercontent.com/76719813/109831292-85b2e180-7bfc-11eb-8b25-15978632d3d4.PNG)

**Comment by mds1** [comment]
It looks like you checked out with zkSync, so you can leave the transaction hash blank and only fill in your address (0x212...A9E)? Let me know if that works

The "Transaction Hash" field is only for L1 (Standard Checkout) transactions to the Gitcoin BulkCheckout contract. Since you checked out with zkSync and did not use that contract, that is likely why it says the transaction hash is invalid.

I tried to make this clear in the instructions, but perhaps I did not do a good job! Any feedback you can provide on how to make the instructions more clear / what you found confusing would be appreciated 🙂

**Comment by LRoddd** [comment]
Ok it worked. I read the instructions but was following the directions from this thread. My bad. 

![Capture](https://user-images.githubusercontent.com/76719813/109881272-3dfc7c00-7c35-11eb-8ca8-1ad74ee9843b.PNG)

Not sure how this works from here but thank you

**Comment by mds1** [comment]
No problem, apologies for the frustration, but glad you got it working!

From here the backend now has your contributions, and they should be visible in the "All Activity" section of your profile at https://gitcoin.co/LRoddd (you may need to click "Show More" to see them)

**Comment by thelostone-mc** [comment]
@mds1 we could tweak it by

- adding client side validation which ensure both fields aren't populate  
- or a step ahead by introducing a step -> which asks users if they want to add a standard checkout / or zk sync checkout and show only that field instead of both of them
