### ISSUE TITLE
Your github profile is too new, so you cannot receive kudos. Please verifiy your profile on BrightID and/or Twitter to proceed.

### ISSUE THREAD

**Issue by Havok-LA** [gitcoinco/web#8489]
Got that notification after I finished a quiz.  Can't figure out where to verify using Twitter in my profile.  I saw a closed thread that said someone could mark me as Trusted.  Can anyone assist with this?  Thanks.

**Comment by thelostone-mc** [comment]
You should be able to do it by navigating to 
https://gitcoin.co/Havok-LA/trust
