### ISSUE TITLE
rsk bugs

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8493]
- [x] can we rename R-BTC to RBTC?
- [x] use a sharper logo please (hit up frank for an .ai file)

**Comment by thelostone-mc** [comment]
Are we sure ?

https://developers.rsk.co/rsk/rbtc/

their docs + token name is kept as R-BTC which is why we stuck to that

**Comment by frankchen07** [comment]
responded on Slack - apparently they're switching all R-BTC to RBTC in the documentation (currently in progress).
