### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by adenu2** [gitcoinco/web#8501]
# ❤️ I'm using Gitcoin
Thank you Gitcoin for a wonderful opportunity like this.
If you (or your company) are using Gitcoin - please let us know. We'd love to hear from you!

If you would like to help Gitcoin - any of the following is greatly appreciated.

- [x] Give the repository a star ⭐️
- [ ] Help out with issues
- [ ] Review pull requests
- [ ] Blog about Gitcoin
- [ ] Give talks
- [ ] Do a bounty
- [ ] Support us on [Gitcoin Grants](https://gitcoin.co/grants/86/gitcoin-sustainability-fund)

Thank you!
The Gitcoin team

**Comment by adenu2** [comment]
Feeling happy

**Comment by thelostone-mc** [comment]
thanks for the love and support ^_^
