### ISSUE TITLE
Easy access of web 3 services

### ISSUE THREAD

**Issue by adenu2** [gitcoinco/web#8502]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by adenu2** [comment]
Tutorial on web 3

**Comment by thelostone-mc** [comment]
@adenu2 could you open this issue with more details on what the bug / doc need is
