### ISSUE TITLE
Unable to edit grant. Please try again

### ISSUE THREAD

**Issue by vporton** [gitcoinco/web#8503]
When I click Save when editing https://gitcoin.co/grants/1591/science-of-the-future-the-100-years-forward-plan I get `Unable to edit grant. Please try again`.

**Comment by thelostone-mc** [comment]
You should be able to do it now ! looks like one of the required param was null in DB

**Comment by vporton** [comment]
> You should be able to do it now ! looks like one of the required param was null in DB

Now it does not work with https://gitcoin.co/grants/1585/see-the-truth
