### ISSUE TITLE
I want to modify my grant eth address

### ISSUE THREAD

**Issue by liushooter** [gitcoinco/web#8509]
### Who
https://gitcoin.co/liushooter

### What 
I want to modify [my grant](https://gitcoin.co/grants/1870/rebase-community-rebase) eth address。

The first time，I filled out eth address with `0x000....000`。  😭

**Comment by Kweiss** [comment]
Heya - What's the new address you want to use?

**Comment by liushooter** [comment]
@Kweiss 

my new address is `0x4247269401bCb49d8455e275d70c25bE9e2F9285`，thank you ！

**Comment by thelostone-mc** [comment]
updated 
![image](https://user-images.githubusercontent.com/5358146/110509627-50405380-8128-11eb-976a-ba8d2c121d15.png)

**Comment by liushooter** [comment]
thank you @Kweiss  @thelostone-mc
