### ISSUE TITLE
Change grant receiver address

### ISSUE THREAD

**Issue by seichris** [gitcoinco/web#8513]
Could you please change the receiving address for [this grant](https://gitcoin.co/grants/1464/kontextapp-social-bookmarking-on-filecoin) to 0xB7De690a60A968FC844148d75bFfF9716382b145

@thelostone-mc recently tried to change, but it didn't work. See issue #8475 .

**Comment by thelostone-mc** [comment]
Hmm looks the update had failed !
Trying it again and updated

![image](https://user-images.githubusercontent.com/5358146/110434809-4a228680-80d8-11eb-92af-b2f33684d774.png)

Could you confirm and close this issue if it's all good ?

**Comment by seichris** [comment]
Thanks a lot @thelostone-mc! The change now shows in the UI
