### ISSUE TITLE
Grants Round 9 Deploy QA ticket

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8516]
Comment below if you find anything during QA

Testing plan can be found here: https://docs.google.com/document/d/1LyCvzlLq5blbcw4el_4sSocXpOKiDW0P8e-l_hSgAGs/edit#

**Comment by owocki** [comment]
looks like the grants routing policies are not set up + the QF rounds are not active yet. 

i think for testing it’d be good to have them up so we can test. then we can shift the start date forward wehn were done testing

**Comment by Kweiss** [comment]
Testing plan can be found here: https://docs.google.com/document/d/1LyCvzlLq5blbcw4el_4sSocXpOKiDW0P8e-l_hSgAGs/edit#

**Comment by owocki** [comment]
did the "contribute to n grants, get only 1 email' PR not get merged?  these are the emails im getting after contributing to grants https://bits.owocki.com/eDu8D6NA

**Comment by Kweiss** [comment]
Looks like the "add to collection" is not working on the Grants detail page.
![image](https://user-images.githubusercontent.com/1017776/110510618-9feb3480-80c0-11eb-9fd0-0c1efc65b39a.png)

**Comment by Kweiss** [comment]
- [ ] The Dollar amounts should be removed:

![image](https://user-images.githubusercontent.com/1017776/110510921-eb9dde00-80c0-11eb-9597-1b933cafef7a.png)

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/commit/6bcfe083469bda34d95771088c464ef588d5092e#diff-99da7bec02ad1d22feb4d41f83d3048b392f7da53958cf6e3adbef6a84324dd8R97

if im reading the code correctly its just removing the grant from each CLR round in the cache creator

**Comment by ceresstation** [comment]
- [ ] Some parts of the site say $475k some say $500k we should really just increase infra by $25k so it's a nice round number: https://gyazo.com/3329c86599de48064e48266c8f89ff78?token=c20469ee4d5325ddb78ee81331f3a5ee

- [ ] grainy imagery on collections images: https://gyazo.com/59396388bc8edafbec73d5739ac89b31

- [ ] why do we need both of these QF matching pool sections, they duplicate the same information: https://gyazo.com/78eb5a3f20580f3d93849158b10be54d

**Comment by vs77bb** [comment]
- minor thing: getting like a 2s load time on all the individual matching pages (not sure if it's just me) 
- when i sorted by 'Match Estimate', grants didn't load. a refresh then worked for me to re-load 
![image](https://user-images.githubusercontent.com/23297747/110648145-75fc4580-8186-11eb-9521-c4c553cec082.png)
- do we feel like match estimates are a bit small?
![image](https://user-images.githubusercontent.com/23297747/110648420-b360d300-8186-11eb-8033-12030e22b423.png)

**Comment by willsputra** [comment]
- [ ] should sort by Match Estimate show just this round, or other past rounds as well? seems like now it's showing grants from other rounds too (but there's no matching info so it's a bit confusing)
<img width="776" alt="Screenshot 2021-03-10 at 11 53 26 PM" src="https://user-images.githubusercontent.com/19514207/110657556-e1ccc580-81fb-11eb-8ecb-49539cd60c6c.png">
