### ISSUE TITLE
Unable to Edit Grant

### ISSUE THREAD

**Issue by A-Jagodin** [gitcoinco/web#8518]
Hello,

I have been trying to update my grant which is StayBit but it shows error whenever I try.

What could be the cause?

**Comment by Kweiss** [comment]
Hi there - Can you share the details on the error?

**Comment by zashton** [comment]
i have the same issue for keep3r.live

![image](https://user-images.githubusercontent.com/17747090/110561428-9f1ad700-8182-11eb-99d4-bdb03e076838.png)
![image](https://user-images.githubusercontent.com/17747090/110561713-1cdee280-8183-11eb-9403-e49a6c3a1657.png)

**Comment by thelostone-mc** [comment]
This should be fixed now ! You should be able to edit it now

**Comment by zashton** [comment]
did a hard refresh and still getting the same error 

> This should be fixed now ! You should be able to edit it now

**Comment by zashton** [comment]
> @zashton which grant ?

https://gitcoin.co/grants/1541/keep3rlive

thanks  :)

**Comment by thelostone-mc** [comment]
could you check now @zashton

**Comment by A-Jagodin** [comment]
Thanks. It works now
