### ISSUE TITLE
GitCoin Grant for Giveth.io displaying incorrectly

### ISSUE THREAD

**Issue by Danibelle** [gitcoinco/web#8519]
**Describe the bug**
A picture says 1000 words..  this is how the Grant displays.. the text is in a narrow column down the left, that keeps going.. and going..  with a big blank space center and right:
**To Reproduce**
Go to the url: https://gitcoin.co/grants/795/givethio
Or the original url (we changed the title today): https://gitcoin.co/grants/795/giveth-20

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/39466970/110550048-d4261b80-80e7-11eb-991d-f09d61b544c7.png)

![image](https://user-images.githubusercontent.com/39466970/110550128-f9b32500-80e7-11eb-8704-adb51f21c869.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome 
- Browser Version: Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by gdixon** [comment]
Hey, thank you for the report!

I've just pushed a fix (1aa2974), we will get this deployed asap! :)

**Comment by thelostone-mc** [comment]
fix has been rolled out @Danibelle ! 
Closing this out.  Have a gr8 round 9 ^_^

![image](https://user-images.githubusercontent.com/5358146/110649960-1df22d00-81e0-11eb-9889-e3f1cafb0d7d.png)
