### ISSUE TITLE
Stuck on zkSync checkout page - "Please wait until all the necessary information is fetched..."

### ISSUE THREAD

**Issue by nopslip** [gitcoinco/web#8528]
**Describe the bug**
When trying to checkout for grants with zkSync option. It pops into a new window the URI https://checkout.zksync.io/  and gets stuck on:

"Please wait until all the necessary information is fetched..."

I waited for awhile and nothing happens. Then checked console to see the error below. Gitcoin.co page has a zkSync popup that says this meanwhile: "IMPORTANT: Do not close this tab or the zkSync tab until your transfers are complete!" 

So I'm stuck in a bit of a dead end. 

**To Reproduce**
Add a few items to your grants cart and checkout with ZkSync. 

**Expected behavior**
Checkout process moves past Step 1 of checkout.zksync.io 

**Screenshots**
![signal-2021-03-10-093132_002](https://user-images.githubusercontent.com/1734015/110663958-39c7e580-8184-11eb-9d80-2ded54ba67b8.png)
![signal-2021-03-10-093132_001](https://user-images.githubusercontent.com/1734015/110663972-3cc2d600-8184-11eb-84f9-75221ed575a5.png)

Error from console on checkout.zksync.io:
![Signal 2021-03-10 09-35-13](https://user-images.githubusercontent.com/1734015/110664097-5b28d180-8184-11eb-9572-a09c37cf61dc.png)

- OS: Linux
- Browser: Firefox 
- Browser Version: ESR 78.8.0

**Additional context**
Initially browser was set to Strict privacy settings. I set it to Standard and walked back through checkout and am still experiencing the same issue/error.

**Comment by thelostone-mc** [comment]
@mds1 any idea why this happens ?

**Comment by nopslip** [comment]
This issue appears to have been resolved/fixed.
