### ISSUE TITLE
Change grant receiver address

### ISSUE THREAD

**Issue by spolrot** [gitcoinco/web#8530]
Hi, I would like to change the grant receiver address of [this grant](https://gitcoin.co/grants/1693/eu-crypto-initiative-educating-policy-makers-on-d) to 0x4273A8E57a1Fab8cB5F7cf2D68ad16bEd061520a. Thank you!

**Comment by gdixon** [comment]
Hey Simon,

Thanks for reaching out, that's now been updated. :)

<img width="1245" alt="Screenshot 2021-03-10 at 20 58 54" src="https://user-images.githubusercontent.com/5897836/110697167-dcfc1780-81e3-11eb-9d8b-8cfb9de8c98c.png">
