### ISSUE TITLE
I can't see my action on gitcoin.

### ISSUE THREAD

**Issue by dvdinh307** [gitcoinco/web#8535]
https://etherscan.io/tx/0x486ff35daee924c16be729a87e997dc6f82ab0b707927170b7e75a3447b74429
This is my transaction, It done ?
I can't check it done or not and i can't see it in my action list.
Please help me check
Thanks.

**Comment by mds1** [comment]
Try using the tool linked below and pasting in your transaction hash of 0x486ff35daee924c16be729a87e997dc6f82ab0b707927170b7e75a3447b74429

https://gitcoin.co/grants/add-missing-contributions

**Comment by dvdinh307** [comment]
Oh I can see them. 
Many thanks and good job team.
