### ISSUE TITLE
Grants Cart Always Empty

### ISSUE THREAD

**Issue by rrm1991** [gitcoinco/web#8537]
**Description**
No matter what I do, my grants cart is always empty. If I add some proyects to grant, the cart icon on the top of the screen shows correctly the number of proyects I've added, but when I click it it says "Your cart is empty" and I can't chekcout or grant any projects.

**To Reproduce**
This has started happening after trying to checkout using zksync. Zksync page bugged out, took some money from my wallet (about 0.01 ETH) and never took any DAI whatsoever to fund the grants. After seeing that the withdrawn money from my wallet was not appearing in zksync for several minutes, I decided to close both the cart and zksync.

Now I lost .01 ETH (not a big deal) but I can't fund any grant because my grants cart is bugged (BIG DEAL :( )

**Expected behavior**

**Screenshots**
I add a grant to the cart:
![image](https://user-images.githubusercontent.com/73843491/110775380-23428c80-825f-11eb-8291-990ec90df290.png)

Cart icon displays right number:

![image](https://user-images.githubusercontent.com/73843491/110775489-42411e80-825f-11eb-8c2e-cef2907925f5.png)

Cart says it is empty:

![image](https://user-images.githubusercontent.com/73843491/110775599-61d84700-825f-11eb-9fd8-5b8d9a705b54.png)

**Desktop (please complete the following information):**

- OS: Windows 10 &4 bits
- Browser: Google Chrome
- Browser Version: 89.0.4389.82

**Additional context**

I have tried deleting all items from my cart, disconnecting my metamask wallet, loging out and in again, but nothing seems to work.

**Comment by aflinfo** [comment]
Same issue here! https://github.com/gitcoinco/web/issues/8538#issuecomment-796743035

**Comment by thelostone-mc** [comment]
this should be resolved now ! we had issues with our server and now this has been resolved.
Do a hard refresh and it should work

Additionally if you can't find your txn, do head over to https://gitcoin.co/grants/add-missing-contributions
and get em added here.
It should work

**Comment by gdixon** [comment]
I'm closing this out - but please feel free to reopen if your problem hasn't been resolved!
