### ISSUE TITLE
empty cart 

### ISSUE THREAD

**Issue by NYusmc81** [gitcoinco/web#8538]
adding grants its showing them in the cart on the top but when going to check out getting a empty cart notification

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 
- Browser: chrome 
- Browser Version:Version 89.0.4389.82 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by aflinfo** [comment]
I can add Grants to shopping cart but when I click on the shopping cart icon it shows empty :( hence cannot contribute.
![grants](https://user-images.githubusercontent.com/77820748/110796002-790a3b00-8245-11eb-9ea1-d5110abe7462.png)

Device: Lenovo T1
OS: Windows 10
Browser: Brave
Version: 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)

**Comment by thelostone-mc** [comment]
this should be resolved now ! we had issues with our server and now this has been resolved.
Do a hard refresh and it should work
Closing it out now but do reopen if you still face this issue

**Comment by NYusmc81** [comment]
Thank you it worked for me the other day after emptying the cart and redoing the adds
