### ISSUE TITLE
Empty cart and log out issures

### ISSUE THREAD

**Issue by Qloun** [gitcoinco/web#8541]
**Describe the bug**

When I add Grant to cart, title shows that it is empty. At the same time, when I try to log out, page reloaded and nothing nothing else happens

**To Reproduce**

Add some grant in cart and then press cart icon in the upper right corner of the page
To log out just press log out button in popup menu in the upper right corner of page

**Expected behavior**

Menus shoud work properly. When I add any grant to cart, it should be showen in such a menu. When I press Log Out button, system have to log me out

**Screenshots**

![image](https://user-images.githubusercontent.com/35996623/110779673-dbc6fb00-8274-11eb-881b-fcb95e97664f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 88.0.4324.190

**Comment by aflinfo** [comment]
Same issue here!
OS: Windows 10
Browser: Brave (Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit))

**Comment by thelostone-mc** [comment]
this should be resolved now ! we had issues with our server and now this has been resolved.
Do a hard refresh and it should work
Closing it out now but do reopen if you still face this issue
