### ISSUE TITLE
Cart showing empty after adding grants 

### ISSUE THREAD

**Issue by Kryptickerry** [gitcoinco/web#8543]
I wanted to donate for grant 9 but it's always saying my cart is empty

**Comment by aflinfo** [comment]
same here! :(

**Comment by jbradach** [comment]
I thought it was just me. I was trying to make a few donations last night with MetaMask on my phone and each time I tried to log in I encountered a GitHub error. This morning, I tried again in my browser and put 41 grants in my cart. However, each time I try to visit to pay it shows my cart is empty. Even on the cart page showing empty, the cart icon at the top shows 41.

**Comment by owocki** [comment]
can you try now!?  we had a server that went offline for about 3-4 hours this morning, and i suspect that might have been the root cause.

**Comment by Kryptickerry** [comment]
Now i can't even log in

**Comment by thelostone-mc** [comment]
This should be resolved now ! Could you do a hard refresh and try again @Kryptickerry @aflinfo

**Comment by thelostone-mc** [comment]
Closing it now ! Do reopen if issues exists
