### ISSUE TITLE
I contributed 11 grants. I sent fund by zkrollup but gitcoin not shown me last 11. only shows me 1 contrıbuted last time.

### ISSUE THREAD

**Issue by mydearcode** [gitcoinco/web#8545]
I contributed 11 grants. I sent fund by zkrollup but gitcoin not shown me last 11. only shows me 1 contrıbuted last time.
https://zkscan.io/explorer/accounts/0x84c0190af5e489a7537e9011e8dfc38cb39cc6c6

**Comment by InsideTheSim** [comment]
I also have a contribution that's not showing (5 donations).
https://zkscan.io/explorer/accounts/0xAf8FBF59e221D27b55DC3ADc2366F9230bCf5096

**Comment by aflinfo** [comment]
I also have 16 donations that's not showing up despite they are successfully
https://zkscan.io/explorer/accounts/0x45c1ea6125f7cd54d5d01abff2e043e009434d4b

**Comment by InsideTheSim** [comment]
@mydearcode @aflinfo I was able to fix my issue using this tool: https://gitcoin.co/grants/add-missing-contributions

**Comment by pinguinman0** [comment]
Same problem here with 4 donations
https://zkscan.io/explorer/accounts/0xd9568eD6884Ec48D30E485a0CA00f5A8F1973486
@InsideTheSim I Tried your link, its says that my contributions have been added succesfully but doesn't change anything on gitcoin.

**Comment by InsideTheSim** [comment]
It took mine a few minutes to actually show - I tried the link a few times. Eventually they populated in.

**Comment by owocki** [comment]
@mds1 any thoughts on this one?

**Comment by mds1** [comment]
Seems this is the same issue we need to fix from #7744. Until that's closed, the https://gitcoin.co/grants/add-missing-contributions page is the way to resolve this manually

**Comment by mydearcode** [comment]
> @mydearcode @aflinfo I was able to fix my issue using this tool: https://gitcoin.co/grants/add-missing-contributions

Yes. It solved my issue shortly. Thank you! The community is amazing!

**Comment by aflinfo** [comment]
Thanks after trying 2 - 3 times the URL fixed the issue ;)
