### ISSUE TITLE
running on local machine - npm start problem

### ISSUE THREAD

**Issue by judabne** [gitcoinco/web#8548]
Hello
I am trying to run this repo on my local machine in an attempt to solve an issue. This is among my first attempts. I am trying to run this using npm start but apparently it isn't working. Does anyone have a solution?
Thanks

**Comment by gdixon** [comment]
Hey @judabne, 

Thanks for helping out... We use docker on our local environments and have quite a comprehensive getting started guide [here](https://docs.gitcoin.co/mk_setup/), but if you see any holes in our documentation or anything that we could explain more clearly, please let us know and we can get them updated. 👍 Thanks again!

**Comment by judabne** [comment]
Thank you! I will try to get back to you soon

**Comment by gdixon** [comment]
That's awesome! Welcome to the community! 😄 

I'm closing this out - but feel free to reopen this issue if you have any problems getting started 👍
