### ISSUE TITLE
Change ETH address associated with grant

### ISSUE THREAD

**Issue by stephenreid321** [gitcoinco/web#8551]
### Who

https://gitcoin.co/grants/564/dandelion

### What 

Please change the associated ETH address to 0x84a57c709482d44cE49511adac7ED7F1Db299455

### Why

We're changing our wallets

**Comment by thelostone-mc** [comment]
Has been updated 
![image](https://user-images.githubusercontent.com/5358146/111148026-2a480280-85b1-11eb-8866-05b514a3476b.png)
