### ISSUE TITLE
Invalid length of transaction hashes array

### ISSUE THREAD

**Issue by MysticRyuujin** [gitcoinco/web#8564]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8877131/110964443-d0c5a680-8318-11eb-8f63-d766183c591f.png)

And all of my contributions are nowhere to be found.

**To Reproduce**
I don't know, I used MetaMask + Ledger on Brave (Linux Mint). I checked out inside the zkSync tab, everything went smoothly there. I got a big'ol complete checkbox and then I clicked the exit button once it was all done, came back to the gitcoin tab and found this error waiting for me.

**Expected behavior**
It works

**Screenshots**
See above

**Desktop (please complete the following information):**

- OS: Linux Mint 20
- Browser: Brave
- Browser Version: `Version 1.21.74 Chromium: 89.0.4389.72 (Official Build) (64-bit)`

**Additional context**

Ethereum Address: `0x338E2DEB1e65238d1475E0c8b3d1B3cdfA5656cc`

**Comment by testingoblin** [comment]
yep, same issue here.

**Comment by nopslip** [comment]
Thank you for the info. This is a known issue and a fix is actively being worked.  That said, if you got this far it's likely your donation transactions did get broadcast on the zkSync network. If that is the case, we have  tool you can use to trigger Gitcoin to process the orphaned donations and push them to the Gitcoin DB. 

[https://gitcoin.co/grants/add-missing-contributions](https://gitcoin.co/grants/add-missing-contributions)

If you used zkSync you just need to put the address you donated from into the form and sign a transaction (from that account/address) to initiate the process. 

Please let us know if that doesn't work and thanks for your patience!

**Comment by MysticRyuujin** [comment]
That worked for me!

**Comment by mds1** [comment]
Also just want to note two things about the link @nopslip shared:

1. Sometimes it may take a few minutes for the backend to process, so your contributions may not show up in your profile immediately
2. If the zkSync network is backlogged / lots of usage, your transaction may not have been confirmed yet. In that case, just try that page again in a few hours
