### ISSUE TITLE
Change Grant Category

### ISSUE THREAD

**Issue by michaelis** [gitcoinco/web#8568]
### Who
Grant: Simthunder - https://gitcoin.co/grants/2001/simthunder-private-content-and-nfts-marketplace-f
User: michaelis
### What 
I'm trying to change grant category but don't see any option for that, it's not possible?
### Why
I'm trying to change grant category to benefit from Gitcoin Grants R9

**Comment by thelostone-mc** [comment]
I've updated it ! 
![image](https://user-images.githubusercontent.com/5358146/111147664-bc9bd680-85b0-11eb-9d7f-6b0ed4107069.png)
