### ISSUE TITLE
Funding not credited with Argent smart contract wallet without zkSync

### ISSUE THREAD

**Issue by mmatous** [gitcoinco/web#8575]
**Describe the bug**
After successful transaction grants remain in card, funding doesn't appear in grant list of funding. I don't know whether the sent ETH got credited to grant total. My profile says "No Grants Funded."

**To Reproduce**
 Try to fund grants with Argent over WalletConnect WITHOUT using zkSync checkout. 

**Expected behavior**
Cart is emptied and funding appears in the grant funding list.

**Desktop (please complete the following information):**

- OS: Gentoo Linux
- Browser: Mozilla Firefox
- Browser Version: 86.0.1

**Smartphone (please complete the following information):**

- Device: Moto Z Play (addison)
- OS: Android 8.0.0. (stock)

**Additional context**
TX [0xc571168e05fa0b488b80d009f7f1c6524476288aa1ac4c0329936587bfd44b0c](https://etherscan.io/tx/0xc571168e05fa0b488b80d009f7f1c6524476288aa1ac4c0329936587bfd44b0c)

**Comment by mmatous** [comment]
I just found out that https://gitcoin.co/grants/add-missing-contributions exists. Tried it out with TX hash but kinda unsurprisingly it doesn't work because relayers. "Sender of the provided transaction does not match connected wallet address".

**Comment by mds1** [comment]
Ahh, yes that makes sense. Someone from Gitcoin will need to ingest on your behalf. I'm hoping to add that functionality in the next day or two, and will let you know + close this issue once your contributions are in the database!

**Comment by mmatous** [comment]
Hi, is there something I should do or someone I should contact now? With GR9 closing soon I'd like to make sure that my contribution goes through with appropriate CLR matching.

**Comment by mds1** [comment]
@thelostone-mc @Kweiss Can we get PR https://github.com/gitcoinco/web/pull/8621 merged today? It's been ready for a while now, and we need it to ingest @mmatous's contributions + any other users with Argent wallet having this issue

**Comment by mds1** [comment]
Hey @mmatous, I've ingested these contributions for you, which you can see by checking the "All Activity" section of https://gitcoin.co/mmatous

**Comment by mmatous** [comment]
Great, thank you!
