### ISSUE TITLE
granted but not showing at dashboard at gitcoin

### ISSUE THREAD

**Issue by bigbrodfids** [gitcoinco/web#8576]
### Discussion

Hi, i've successfully granted ETH to some projects on Gitcoin from my metatask wallet (through zksync), but there's nothing in the dashboard in Gitcoin (nothing here: https://gitcoin.co/grants/profile), can anyone tell me what is the problem there?

Thank you very much!

Jim
![20210313221741](https://user-images.githubusercontent.com/80559120/111032987-f7372f00-8449-11eb-8fc8-b233ebc203f1.png)

**Comment by thelostone-mc** [comment]
I do see it here 
https://gitcoin.co/bigbrodfids/grants

Could you double check and confirm ?

**Comment by bigbrodfids** [comment]
Hi,  Yes I can see the grants on dashboard now. Thank you!

By the way, when I register my account at Gitcoin, I wrote my role as
Contributor by mistake, how can I change to Funder now? I'm just registered
to fund those potential projects.
How can I improve my funder rank?

Thanks!

Jim

Aditya Anand M C ***@***.***> 于2021年3月15日周一 下午7:34写道：

**Comment by thelostone-mc** [comment]
You should be able to set that in https://gitcoin.co/settings/account

**Comment by bigbrodfids** [comment]
excellent!
