### ISSUE TITLE
Change Grant Category to #GR9 (category: NFT)

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#8578]
### Who
Meme of the Day grant: https://gitcoin.co/grants/1413/meme-of-the-day

### What 
Please update grant category to Grant Round 9 with subcategory NFT. However, we don’t want to lose matched funds from APOLLO grant round that were not yet paid out. See #8340.

### Why
We don’t want to miss the chance for GR9, and also don’t want to lose earned matching funds, so could you please help?

**Comment by thelostone-mc** [comment]
Give us 24 hours and we'll get back with a solution.
We can switch the grant over to NFT by then and figure out what to do with regrading apollo payout

**Comment by owocki** [comment]
https://etherscan.io/tx/0x720bf163443a4dcca852e8dd4da91083c86763ec19900f61c6110e6aeef8f092

the APOLLO grants payout for this grant has already been paid on 2/17

**Comment by thelostone-mc** [comment]
^ based on info shared. I've updated the category to NFT and this grant should be able to take part in round 9
