### ISSUE TITLE
Please add my 1st round grant contribution made at 2021-3-13 08:43 UTC to Gitcoin profile.

### ISSUE THREAD

**Issue by Jeanchen27** [gitcoinco/web#8580]
**Describe the bug**

The PAYMENT ERROR was popped up when I paid my 1st round of 30 grants contribution with zkSync at the time of 2021-3-13 08:43 UTC. There is no grant record on my Gitcoin profile page but this batch of transactions was finalized. It is still not working when I tried https://gitcoin.co/grants/add-missing-contributions 8 hours later.

Attention: I made my 2nd round of 28 grants contribution at the time of 2021-03-13 10:29:59 UTC and it succeeded. Be sure not to confuse the 2nd round with the 1st round. 

Gitcoin ID: Jeanchen27
Wallet address: 0xd48cd53b24e1fFb9fCf83e7eEAeDCB1bA73Ee02C
zkSync tx hash: https://zkscan.io/explorer/transactions/b5d0fc8e91a663bcfb1ece243079dcb2a9f37a33d525048e2a26d1fe9e7833d9

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1440" alt="截屏2021-03-13 16 43 27" src="https://user-images.githubusercontent.com/40049512/111037913-37ee7280-8461-11eb-8297-95631a228323.png">
<img width="1440" alt="截屏2021-03-13 23 17 42" src="https://user-images.githubusercontent.com/40049512/111037921-40df4400-8461-11eb-998a-e0d301c47f4c.png">
<img width="1378" alt="截屏2021-03-13 23 18 28" src="https://user-images.githubusercontent.com/40049512/111037924-43da3480-8461-11eb-9199-c97e4a4e84ee.png">

**Desktop (please complete the following information):**

- OS: MacOS Big Sur v. 11.2.3
- Browser: Chrome
- Browser Version: 89.0.4389.82

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by Kweiss** [comment]
Can you share the transaction details for the first batch please so we can confirm they were completed?

**Comment by Jeanchen27** [comment]
This the first tx of my first batch: https://zkscan.io/explorer/transactions/0xb0c6bb9e9cca0e6332d38c314d4d2a6988f11b6867c8eef770669178b79a184e

This is the last tx of my first batch: https://zkscan.io/explorer/transactions/b5d0fc8e91a663bcfb1ece243079dcb2a9f37a33d525048e2a26d1fe9e7833d9

You can see all txs of my first batch in this block height: https://zkscan.io/explorer/blocks/12164

My GitHub/Gitcoin ID: Jeanchen27
My wallet address: 0xd48cd53b24e1fFb9fCf83e7eEAeDCB1bA73Ee02C

Thank you very much!

**Comment by mds1** [comment]
Hi @Jeanchen27, the error in your first screenshot of `Cannot read property 'toLowerCase' of undefined` was a zkSync bug that should be fixed now. Either way, if your transactions were successful, you can use https://gitcoin.co/grants/add-missing-contributions to make sure your contributions are counted by Gitcoin

Two quick notes on that link:
1. Sometimes it may take a few minutes for the backend to process, so your contributions may not show up in your profile immediately
2. If the zkSync network is backlogged / has lots of usage, your transaction may not have been confirmed yet. In that case, just try that page again in a few hours

Closing this issue, but feel free to re-open if that does not solve your problem
