### ISSUE TITLE
can not log in with github!

### ISSUE THREAD

**Issue by suntopo** [gitcoinco/web#8585]
**Describe the bug**
can not log in with github. It is emergency and big bugger no just for me, many people had encountered this problem.

**To Reproduce**
no matter what page i click the log in button, it will have this problem. 

**Expected behavior**
log in correctly

**Screenshots**
![Screenshot from 2021-03-14 12-58-26](https://user-images.githubusercontent.com/5196122/111057819-38b8f000-84c5-11eb-974a-b6c662f58c02.png)

**Desktop (please complete the following information):**

- OS: ubuntu 20.04
- Browser: chrome
- Browser Version: Version 89.0.4389.72 (Official Build) (64-bit)

**Additional context**
emergency!

**Comment by suntopo** [comment]
https://gitcoin.co/complete/github/?code=9fdb4b47f017dcdf3242&state=V16y0jaoYNtJQ621d6PixLnJeNYKDOlP

**Comment by suntopo** [comment]
username: suntopo

**Comment by Kweiss** [comment]
Another user also reports

![e2](https://user-images.githubusercontent.com/1017776/111079762-02797180-84c1-11eb-85d4-68bdb1c9865a.png)

**Comment by Kweiss** [comment]
More error - 
![e3](https://user-images.githubusercontent.com/1017776/111082164-753c1a00-84cc-11eb-84cb-7936b24b630c.png)
