### ISSUE TITLE
Adding more payment methods For Gitcoin Donations

### ISSUE THREAD

**Issue by Killrbit** [gitcoinco/web#8588]
Hey i think we should really consider adding a few more payment options for making gitcoin donations. 
Fees on the Ethereum chain seem to be a big issue and it is pretty disappointing to pay more in network fees than the actual donation.

Saving on network fees would most likely result in larger contributions to projects that could do a lot more with the money.

Consideration really need to be made to adding the BSC network or the Solano network as a valid payment method for donations

**Comment by gdixon** [comment]
Hey @Killrbit, we currently support around 9 chains (as well as a layer2 solution for ethereum) and we're constantly working to integrate new ones, we even support BSC! It's up to each Grant's creator to select the chain that they are willing to accept contributions on. Hopefully in the future more Grantees will opt for different chains and we will be able to provide a more diverse selection for you to contribute to.

I hope this helps, and thank you for support and contributions! 😄
