### ISSUE TITLE
I contributed to DADA grant, but Gitcoin doesn't show it

### ISSUE THREAD

**Issue by mlibty** [gitcoinco/web#8589]
Hi! I made a grant to DADA: https://gitcoin.co/grants/2248/dadas-invisible-economy, but it doesn't appear anywhere.
Here is the transaction:
https://zkscan.io/explorer/transactions/sync-tx:255aa7ce561dbb6057d44a688864afe55fc16af32143901865835f3c56adf8af
And this is the part that went to Gitcoin: https://zkscan.io/explorer/transactions/sync-tx:10376e6fd7fa765633373d4ddf7345adccc43518e98c6ecbaf7e36dfd22761a1

After that I funded MetaGame, the same way, and it's showing:  (https://gitcoin.co/grants/213/metagame) 
My address: 0x9eEC0B5Bd8A48047f0Dcc61E98B4b92951480F98

Could you please tell me what happened?
Thank you

**Comment by thelostone-mc** [comment]
Hmm it seems like we don't have record of the txn being made ! Could you submit those txn on https://gitcoin.co/grants/add-missing-contributions
