### ISSUE TITLE
Funded grants via ZKSync (transactions confirmed) but my Gitcoin cart is still showing the items

### ISSUE THREAD

**Issue by MightyMantis** [gitcoinco/web#8590]
**Describe the bug**
I used ZKSync to pay for the grants that I selected.  It took a few hours for the transactions to complete but I can see them as successful in the ZKCheckout Mainnet Explorer.  However when I come back to Gitcoin Grants, my cart is still full as if I didn't pay for the items.  Here are the successful Tx hashes: 0x0ceda75ed70367dfc37af9608a670c66cece3d839642277bd5d4a673eea61ff0, sync-tx:a3ea5da36f0d0bc42e488c1bb85c6a8967605868ec6b37e2029b2b3e8a539a57, sync-tx:3427ca9990e3c21f1f877b651c3ed5591d4c922314ea323e2d9a8f7455374bab, sync-tx:fb67cc81de9c1a5b928f59a9d3a94b5d28cd74fa433628834da83e526dfef6bc, sync-tx:0af33e0ebef2e3ccf4203fcf0a024e7fdc683692b7aa578e2971c76d11ed5b52, sync-tx:23ef58480ca656951d492d3929d18b976ac9152cbcf0aa5a4d63cd0578a7d134, sync-tx:362f792471860bcbb6595ad744474857ab4e47663b88ab6518a747d71b21ab12

**To Reproduce**
1. Add different grants to your cart and go to checkout
2. At the funding step, select the ZKSync option
3. Connect your metamask wallet
4. Sign the transaction and transfer the funds to Zksync along with gas fees, etc.
5. note: (during this process I accidentally clicked the "sign" button twice because the first click didn't seem to be working) -- this resulted in a 2nd set of transactions for the same cart items but these transactions all show as rejected in the ZKSync mainnet explorer
6.  Funds have been deducted from my metamask wallet
7.  Finally see the initial transactions as successful in the Mainnet Explorer
8. Go back to Gitcoin Grants page and items are still in the cart

**Expected behavior**
Cart items should show as paid for and account should be credited for those purchases

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 64 bit
- OS:
- Browser: Google Chrome
![zksync errors gitcoin grant](https://user-images.githubusercontent.com/80591110/111071753-0223ab00-84ae-11eb-80a7-98d15fe5d780.PNG)
![transaction completed_ZkSync](https://user-images.githubusercontent.com/80591110/111071767-1071c700-84ae-11eb-9dab-06cbe44999ae.PNG)
![list of successful transactions_ZkSync](https://user-images.githubusercontent.com/80591110/111071772-1798d500-84ae-11eb-8b12-3bdd9adcd59f.PNG)
![Gitcoin cart still shows the items1](https://user-images.githubusercontent.com/80591110/111071777-1d8eb600-84ae-11eb-8916-39ca48b59bb1.PNG)
![Gitcoin cart still shows the items2](https://user-images.githubusercontent.com/80591110/111071782-21bad380-84ae-11eb-8109-24e1691b44cc.PNG)

- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Icecolala** [comment]
I have the same problem TAT

**Comment by thelostone-mc** [comment]
Could you add the txn via https://gitcoin.co/grants/add-missing-contributions ? 
cc @mds1

**Comment by mds1** [comment]
The error in your first screenshot of `Cannot read property 'toLowerCase' of undefined` was a zkSync bug that should be fixed now. The link shared by @thelostone-mc should solve your problem, but feel free to reopen this issue if it does not.

Two quick notes on that link:
1. Sometimes it may take a few minutes for the backend to process, so your contributions may not show up in your profile immediately
2. If the zkSync network is backlogged / has lots of usage, your transaction may not have been confirmed yet. In that case, just try that page again in a few hours
