### ISSUE TITLE
Why I cannot find my contributions? My wallet shows that I had 16 transactions were successful.

### ISSUE THREAD

**Issue by Icecolala** [gitcoinco/web#8593]
4 days ago, I chose 16 Grants Carts and donated  through the zkSync. My zkWallet  shows that  my 16 transactions were successful, but I cannot find any contributions on Gitcoin, and the webpage was just kept  loading, what's wrong??? Have I finished???
![image](https://user-images.githubusercontent.com/80458897/111100802-8431d380-8583-11eb-8309-22b3fd7fb4b8.png)

![image](https://user-images.githubusercontent.com/80458897/111100786-7aa86b80-8583-11eb-8843-12e2c958ce24.png)

**Comment by mds1** [comment]
Hey @Icecolala, sorry about that! You can se use https://gitcoin.co/grants/add-missing-contributions and enter your wallet address, and that will make sure your contributions are counted by Gitcoin
