### ISSUE TITLE
gr9 feedback

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8597]
list feedback below

**Comment by owocki** [comment]
community suggests having data on whether a project is VC funded or not

**Comment by owocki** [comment]
community suggesting privacy preserving analytics over GA /hotjar/adroll https://twitter.com/TokenBrice/status/1370721434637582344

**Comment by owocki** [comment]
a few users reporting that their computer fan really starts blowing on the cart page / performance issues

**Comment by owocki** [comment]
unhandled QA from https://github.com/gitcoinco/web/issues/new

**Comment by owocki** [comment]
a few issues im aware of/triaging:
- large donations for which the user never follows through by broadcasting txn
- small spammy txns ( at least 4 ppl have reported https://gitcoin.co/qun1425165 to me )
- QF calculation scales o(n^2) and when we have more contributions, we need more compute to calculate QF match amounts
-

**Comment by owocki** [comment]
a handful of zksync transaction questions/bugs.  maybe a better way to QA that flow before the round.

**Comment by owocki** [comment]
at the end of the round, i could see us going to the community and being like “we are pretty sure, but not certain, that the community has figured out how to sybil attack the platform.

here are 3 sets of numbers

1. if we just accept the current numbers
2. if we remove all users with a sybil score of 4 or higher
3. if we remove all userswith a sybil score of 0 or higher

and we could look at the delta between the numbers on a grant by grant basis, it would inform a conversation about which grants benefitted most from sybil.

**Comment by owocki** [comment]
if i try to checkiout on the wrong network, the site should fail gracefully instead of just failing ungracefully . per https://gitcoincore.slack.com/archives/CAXQ7PT60/p1615489252100600

**Comment by owocki** [comment]
i think there should be something on the product that says “FYI you are showing only active grants. click [Show Idle Grants] if you want to see grants that have not been updated in 3 months”.

**Comment by owocki** [comment]
optimistic ux vs pessimistic ux https://github.com/gitcoinco/web/issues/8570#issuecomment-799492905

**Comment by owocki** [comment]
governance proposal about how to ratify + administer rounds https://twitter.com/stellarmagnet/status/1370835930160959490?s=12

**Comment by owocki** [comment]
It would be really nice if we could show them the total amount that is going to be donated + the total of clr matching estimated

**Comment by owocki** [comment]
the matching amount on cart is from when u added to cart, not current data - it should be the current match amoutn

**Comment by PixelantDesign** [comment]
>i think there should be something on the product that says “FYI you are showing only active grants. click [Show Idle Grants] if you want to see grants that have not been updated in 3 months”.

There is a tooltip that displays on hover over "show idle grants" 
Based on the GA data < 1% of clicks are using the sidebar in general.

**Comment by owocki** [comment]
cart flashes "no items in cart" before loading. it should not mislead the user into thinking it has no items in it when really its just loading

**Comment by PixelantDesign** [comment]
grant owner asking if we can dock **add to cart** at the bottom of the screen on mobile.

**Comment by PixelantDesign** [comment]
discord feedback on grant image sizes

"is there a way to create an adaptative grant image, logo, header and icon. So we forget about unwanted resizes unproportional. solve it by upload different images"

Example:
<img width="1149" alt="Screen Shot 2021-03-17 at 6 58 21 AM" src="https://user-images.githubusercontent.com/238235/111457200-4a311080-86ee-11eb-92e3-2dc7713d86b6.png">

**Comment by owocki** [comment]
Resourcing issue for round 10 - Who holds the accountability to ensuring valid/secure use of the system.   Who owns trust & ssafety?

**Comment by owocki** [comment]
joe: A lot of bad grants include gitcoin or other orgs as a team member which makes them look more official. Would it make sense to have people verify that they are team members before being shown on the grant page?

**Comment by PixelantDesign** [comment]
When I want to know if I've received the grant funds, I want to understand how the grant funds are being processed, so that I know when to expect the funds.

“I cant easily trace contribution
When I checkout a cart, do I make a direct payment to the destination?
Or does it get proxy through a gitcoin managed contract?”
“ My user expectation, I’m trying to match the UI I”M seeing to the ON Chain interactions”
“This donation that came in today, am I supposed to get this now, or two weeks from now?”
Maybe I get this end of period
“Let me look at other peoples grants —and I find that they are using a different system”

^ From @ceresstation

**Comment by PixelantDesign** [comment]
When I want to confirm if I've received a grant contribution,  I want to  clearly see information that explains this, so that I can understand if I received the grant contribution.

“I also don’t know if it’s actually pending” “If I go on chain, I don’t see any of these”

from @ceresstation

**Comment by PixelantDesign** [comment]
Feedback from discord community - have the ability to add a team member on the team module, vs clicking edit to add.

**Comment by PixelantDesign** [comment]
"The contribution system is complex"
" When I clicked on the donate button it forced me to join Github and I did, so but now I get this form that I don't understand anymore."
"Is there any other way to make donations?"

User is confused why we show a profile modal after Github authentication.

https://gitcoincore.slack.com/archives/CCL5Q0G5S/p1616018331003200

**Comment by owocki** [comment]
live widget of contributions coming in that anyone cna put on their site https://beaconcha.in/

**Comment by owocki** [comment]
nonprofit vs vc funded
https://twitter.com/AdamScochran/status/1374046131936763913

**Comment by owocki** [comment]
Idea: featured projects page for projects that have gone from "Project with a Grant" to "Funded Business", as a way for projects to remove themselves from Grants but still receive exposure on Gitcoin.  Could be used as examples of projects that have been successful (even partly) because of Gitcoin Grants and QF.
I want to remove my project from Grants but still want exposure.  Bit of a selfish interest :stuck_out_tongue_winking_eye:
I love the platform and I dont want to take away from unfunded projects that need it more than I do, like I did back when I was unfunded

**Comment by owocki** [comment]
> One important form of passive security is making some form of unique-human verification no longer optional, but instead mandatory.

one key takeaway from vitaliks post for GR9

**Comment by owocki** [comment]
simona suggestion: more proactive governance at start of the round

- trustrequirement vs trustbonus
- ratify round sizes + params ahead of time

**Comment by owocki** [comment]
matching payouts on noncustodial contract cost a lot - 3x this https://bits.owocki.com/12uAEAeA

**Comment by owocki** [comment]
more feedback on vitalik thread https://twitter.com/LefterisJP/status/1378077203343216645

**Comment by owocki** [comment]
for next round, we might save $5k by paying out via a merkle airdrop https://twitter.com/boredgenius/status/1378057588495970306?s=12

**Comment by lardnicus** [comment]
Great round! I learned a lot and it really contributed to our project. Maybe not necessarily in capital but in support and proof of our ideas...

Will be better prepared for next round.

**Comment by lardnicus** [comment]
Question...
If our Match payout is lower the the gas fee, can I just leave that sitting there until next round/until gas fees come down?
Either that or it would be great to get a zkSync option...

**Comment by jugalvaidya** [comment]
It was my first experience with Gitcoin Grant... i have also the similar question if Match payout is lesser than Gas price could we leave it there till the next round...???

**Comment by dogracer** [comment]
Also my first Gitcoin Grant as well, and just got peanuts donated.  hopefully will do better next round.  will Match payout hang out?

**Comment by owocki** [comment]
some ideas for how to fix this:

1. rollover balances round over round
2. next round, payout via zksync
3. open to other ideas..

**Comment by lardnicus** [comment]
1. rollup all the tx's like all of the rest of the payments?

**Comment by owocki** [comment]
set a minimum payment amount https://www.notion.so/gitcoin/Octopus-Andrew-Pendlan-on-Optimizing-the-collusion-strategy-and-matrix-ization-of-the-CLR-algorith-0469297212534f33a5332a3335587cbb
