### ISSUE TITLE
Verify Grant Issue problem with twitter

### ISSUE THREAD

**Issue by freedumbs00** [gitcoinco/web#8598]

**Comment by chibie** [comment]
@freedumbs00 what's your grant link?

**Comment by freedumbs00** [comment]
https://gitcoin.co/grants/2305/a-dashboard-for-daos

@chibie

**Comment by thelostone-mc** [comment]
Could you share the tweet link @freedumbs00

**Comment by SpillChek2** [comment]
I’m having the same issue

**Comment by freedumbs00** [comment]
https://twitter.com/tecmns/status/1371509026299777024.   @thelostone-mc @chibie

**Comment by freedumbs00** [comment]
I've edited the grant to be my personal twitter account and resent the verification link and still cannot verify.   @thelostone-mc

**Comment by thelostone-mc** [comment]
![image](https://user-images.githubusercontent.com/5358146/111808309-e54a0600-88f9-11eb-9f14-df0a9eac182a.png)

**Comment by freedumbs00** [comment]
Thank you
