### ISSUE TITLE
I have acquired some ETH from my grant but it is not being deposited into my wallet

### ISSUE THREAD

**Issue by brudda5** [gitcoinco/web#8606]

**Comment by owocki** [comment]
pls check the l2 provider https://zkscan.io/

**Comment by brudda5** [comment]
It says the transaction was completed but I don't see it in my wallet

**Comment by owocki** [comment]
what wallet are you using? http://wallet.zksync.io/ is the wallet for zksync

**Comment by brudda5** [comment]
metamask
