### ISSUE TITLE
Payment 

### ISSUE THREAD

**Issue by Milot-R** [gitcoinco/web#8609]
Hello. I recently contributed to some grants using the zsync and after I was told successful and all, I Dont think it has reflected

**Comment by gdixon** [comment]
Hey @Milot-R, sorry about that! Can you enter you wallet address here: https://gitcoin.co/grants/add-missing-contributions this will manually ingest your tx's and update our database with the correct values.

I'm going to close-out this issue, but please feel free to reopen it if this fails to solve your issue. 

Thank you for your support and understanding! 😄

**Comment by Milot-R** [comment]
Hello.. Thanks, at least someone is willing to help.. I have tried this
means but to no end result. This is my address
0xDFD2492E0Da678C72F2cc6Ba3eEd56D909e88F18... Thank you
