### ISSUE TITLE
Issue: Coinbase and Gitcoin grant funding.

### ISSUE THREAD

**Issue by ethanchiasson** [gitcoinco/web#8610]
**Describe the bug**
I used Coinbase ETH address as the receiving address for the Gitcoin grant. No ETH payments have been received, yet it seems like _some_ DAI is coming in from external addresses. The address on my ETH wallet changed, but that is common with exchanges and Coinbase specifically states in the settings page that the address will always work as long as I have an active coinbase account ( which I do ); thus, the change in the address is not the issue.

I double checked the the address listed in my CB settings matches the one on the Gitcoin grant, and it does, so we can rule out me using the wrong address.

When viewing the address on ETH scan, nothing relevant seems to come up ( nor do I expect it too, as this wallet is on an exchange ).

I am not too sure what could be going on here other than Coinbase not funding my wallet or the transactions being stuck. Any ideas ?

I will try to make a transaction from MetaMask to the wallet and post an update here.

**Comment by ethanchiasson** [comment]
Update: I sent 2 ETH payments via MetaMask to the address listed on The Gitcoin Grant page, as well as the address listed on Coinbase and It worked. I received both payments.

Maybe a front end issue with Gitcoin? Maybe my grant page was showing other people's grants under my grant and changing the UI. That would make me believe I have not received ( lost ) people's donations ( because they are not showing up on my end ), when in reality that grant number is actually for another user(s)'s grants and everything is fine.

I will keep this thread updated if anything changes.

**Comment by disruptionjoe** [comment]
There was a bug with new UI that should be fixed now, but here is what we need to get it to show properly. Fill out this form: https://gitcoin.co/grants/add-missing-contributions

**Comment by ethanchiasson** [comment]
> There was a bug with new UI that should be fixed now, but here is what we need to get it to show properly. Fill out this form: https://gitcoin.co/grants/add-missing-contributions

What exactly do I fill out here ? I am using CB so I don’t see any pending transactions or anything.

**Comment by gdixon** [comment]
We optimistically include all contributions in our calculations, this allows us to accurately display the best case scenario - however we have noticed quite a few contributions have been sent with a really low gas fee which has caused them to fall out of the mempool and they are eventually dropped. We are constantly monitoring the chains for updates and allow up to 24hrs for these contributions to either go through or fail before we rollback the totals in our db.

You should be able to see any true/cleared contributions on Etherscan/Zkscan(L2) at the address you gave when setting up your Grant 👍 If you provide us with your Grants details, I can double check that this is the case.

Sorry for any confusion this might have caused but you can rest assured that any true contributions will find their way to you asap.

I'm going to close out this issue, but if this doesn't settle your concerns - feel free to reopen it and we can investigate further.

Thank you for your support and understanding!
