### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by mirco-wu** [gitcoinco/web#8617]
why i can't open the grant website? when i open it, it falls down to the end.e-mail:308008418@qq.com

**Comment by gdixon** [comment]
Could you elaborate on this please? What action did you take, what happened, and what did you expect to happen?

**Comment by mirco-wu** [comment]
it is the chrome web,when it's open ,it skip to the end .
other bower havn't the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcoinco/web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcoinco/web] can't open (#8617)





 
Could you elaborate on this please? What action did you take, what happened, and what did you expect to happen?
