### ISSUE TITLE
Carts won't open

### ISSUE THREAD

**Issue by tommy8997** [gitcoinco/web#8624]
every time I try to open my car or do anything that has to do with my card I can't check out can't do nothing my card just sits there and says it's fetching data it won't load won't do nothing

**Describe the bug**
 will not load cart

**To Reproduce**

**Expected behavior**
 I want my car to load so I can check out my stuff

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: Note 10
- OS: Android
- Browser: Chrome
- Version:89.0.4389.86

**Additional context**

**Comment by gdixon** [comment]
Could you perform a hard reload (cmd/ctrl+alt+r) and see if that fixes things please?

**Comment by tommy8997** [comment]
How do I do a hard reload on a phone

**Comment by gdixon** [comment]
Ahh sorry, I missed that detail, you can try to clear the browsing data for gitcoin.co:

1. Open gitcoin.co then the Chrome menu, and tap on the "i" icon
2. Tap "Site settings"
3. Tap the trashcan icon
4. Tap "clear all"

Let us know if you run into any problems.

**Comment by JTraversa** [comment]
Ah just referenced in a similar issue #8647 . Its specifically just an issue with tokenDetails. Ill clear my cache.

**Comment by tommy8997** [comment]
My phone does not have a trash can icon I have a Galaxy 10

**Comment by tommy8997** [comment]
Need help connecting wallet so I can get my kudos to my wallet I'm having
trouble receiving my kudos to my wallet

**Comment by thelostone-mc** [comment]
This should be fixed now
