### ISSUE TITLE
Missing matched grant funds from APOLLO round (ended Jan. 2021)

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#8630]
APOLLO grant round payout of 740 DAI was lower than the 1,086 USD final match displayed on the grant page for this round (screenshot below). Grant is for [Meme of the Day](https://gitcoin.co/grants/1413/meme-of-the-day). Here is the [transaction link](https://etherscan.io/tx/0x720bf163443a4dcca852e8dd4da91083c86763ec19900f61c6110e6aeef8f092) for the payout made on Feb. 17. What caused this difference, and how may we receive the 346 DAI difference?
Issue previously mentioned in #8340. Tagging @kweiss and @owocki.
Thanks in advance.

![image](https://user-images.githubusercontent.com/56145569/111693365-c3635d00-87ed-11eb-8e24-e3e354f3446a.png)

**Comment by owocki** [comment]
on what day was that screenshot taken?

im looking for the history of this CLR calculation in our DB and trying to figure out what happened. the last history i see in https://gitcoin.co/_administrationgrants/grantclrcalculation/?all=&grant=1413 for the APOLLO round is $740, but it looks like this grant was in the MATIC round too for $346.   i think thats what accounts for the difference as 346 + 740 = 1086

**Comment by BTCAlchemist** [comment]
I believe that screenshot was from Feb. 18, 2021, the day I posted in #8340.
@owocki The 346 DAI difference could make sense since my team did not receive the matching funds from the MATIC round (to my knowledge). I don't see a 346 DAI transfer to that wallet address here: https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f?a=0x2a14cac750aaf659d3617487e0629d57242e4c71

**Comment by owocki** [comment]
i cant seem to find a record of your matic payout either, but the rest of the round was paid.. hmm..  

anyway, ill contribute 346 DAI to your grant now to make it right

**Comment by BTCAlchemist** [comment]
That's kind of you; thank you. Closing out this issue.
