### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by elbaratonr** [gitcoinco/web#8636]
Please help I made the contributions and paid and it still charges me

**Comment by gdixon** [comment]
Could you elaborate on this please? What action did you take, what happened, and what did you expect to happen?

**Comment by elbaratonr** [comment]
Please help I made the payment of the grant contributions and the deposit
was collected but the shopping cart remains the same as if I did not pay
anything I leave you the proof of payment
0x07b4e38861f9e7abc7a4ca5562e191b1529ef489d31914ad9d72ef0c0ab28f2f

**Comment by thelostone-mc** [comment]
If you don't see your contirbutions reflected ! Do get them added at https://gitcoin.co/grants/add-missing-contributions

**Comment by elbaratonr** [comment]
I keep seeing the full cart

**Comment by thelostone-mc** [comment]
Do reopen if the contributions cannot be added by the above link
