### ISSUE TITLE
zkSync issue

### ISSUE THREAD

**Issue by artofkot** [gitcoinco/web#8637]
I want to support grants, and zkSync at the last step throws out this error:
<img width="587" alt="Screen Shot 2021-03-18 at 11 41 03 PM" src="https://user-images.githubusercontent.com/7935676/111728634-a5c0e280-8843-11eb-8a6d-d54f3efd8d8d.png">

I have 100usd in zkSync fresh to send, please help.

**Comment by thelostone-mc** [comment]
This should work ! I'm assuming zksync was down during that time
