### ISSUE TITLE
BrightID  verify

### ISSUE THREAD

**Issue by mnthawk** [gitcoinco/web#8639]
# ❤️ I'm using Gitcoin

Dear gitcoin team:
My account of gitcoin is linked for a missing BrightID, but it joined many projects  Grant  
However,the BrightID isn't verified.
Now,I wishes to remove it so that I will relink to an already authenticated BrightID。

Thank you!
The Gitcoin team

**Comment by mnthawk** [comment]
Anyone help me  to  solve it! thanks!

**Comment by mnthawk** [comment]
User  connected  a lost Bright  account, but it  cann't  to remove.
I think that is the most unreasonable design.

**Comment by lthrift** [comment]
If you’re still having this issue please contact support@gitcoin.co
