### ISSUE TITLE
clearly label rinkeby bounties as not real ETH

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#864]
From a community member:

I think you can just do 2 things to improve the clarity that rinkeby bounties are not real mainnet bounties
Firstly you can make a small description on the bottom of the page or on top saying that this is Rinkeby Eth and not real Eth
like when people tag it as Rinkeby or not main net it'll automatically display that description or warning on the page
secondly, maybe change Eth to Rink Eth or Rinkeby Eth
http://prntscr.com/j3x5st
https://image.prntscr.com/image/WRH8LfM8RJ2oQgNiYITeUQ.png
Cause I instinctively look at the bounty price first, is it said 0.0001 Rinkeby Eth then I'd understand
The first one seems to be the better option as it's easier to implement

**Comment by owocki** [comment]
or we can just get rid of rinkeby bounties on prod => https://github.com/gitcoinco/web/issues/773#issuecomment-379814406

**Comment by mkosowsk** [comment]
I agree with @mbeacom and think it's best to limit bounty creation to environment specific networks per https://github.com/gitcoinco/web/issues/773#issuecomment-379844200
