### ISSUE TITLE
Buttons overlap in collection list view

### ISSUE THREAD

**Issue by Shammah** [gitcoinco/web#8661]
**Describe the bug**

The grant card in the collection list view is not tall enough. Because of this, some buttons may overlap such as provided in the screenshot below.

**To Reproduce**

You can see a few of them in my collection:
https://gitcoin.co/grants/explorer/collections?collection_id=1204

1. Create a new collection.
2. Add a grant whose logo / image is not very tall, like in my case Nethermind. Others that show the same problem are EthHub, Lighthouse and Ethers.js
3. View your collection in 'List' view

**Expected behavior**

The 'Remove from collection' button should not overlap with 'Add to Collection'.

**Screenshots**

![image](https://user-images.githubusercontent.com/1854439/112053239-63094e00-8b54-11eb-87b3-7191566bb1e7.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Browser Version: 1.21.77, Chromium 89.0.4390.90

**Additional context**
It seems that the card's height is determined by the height of the logo / image. You might want to set a `min-height` such that all buttons will fit in the card instead. Noticed you use Bootstrap instead of Flexbox which I'm familiar with, so I can't make any recommendation on fixing this the Bootstrap way.

**Comment by gdixon** [comment]
Hey @Shammah, thank you for your report!

We have a fix for this that I've just merged into stable (#8638) - would you like to be notified when that fix goes in to production so that you can check?

I'm going to close this out, but thanks again for reporting, this is a very well put together issue and we really appreciate you taking the time to send us it 😄

**Comment by Shammah** [comment]
No problem! It's a low priority issue so no need for notification, I'll see it sometime in the future
