### ISSUE TITLE
Can't view Ancient Beast grant page stats

### ISSUE THREAD

**Issue by DreadKnight** [gitcoinco/web#8669]
**Describe the bug**
Can't view stats page of my grant, as it will redirect to the main view right away.

**To Reproduce**
1. Go to https://gitcoin.co/grants/916/ancient-beast
2. Scroll down to stats
3. Click to view stats

**Expected behavior**
See the stats of my grant page when I click that tab instead of getting redicted.

**Desktop (please complete the following information):**

- OS: Linux KDE Neon
- Browser: Google Chrome
- Browser Version: Version 89.0.4389.90 (Official Build) (64-bit)

**Additional context**
Do people actually donate to these grants? T_T

**Comment by thelostone-mc** [comment]
It reloads the page and the data is present 
![image](https://user-images.githubusercontent.com/5358146/122175241-1b6b3780-cea1-11eb-8097-c37069e2f0de.png)

**Comment by DreadKnight** [comment]
It doesn't work for me. It shows the stats for a split second when I click the button, then it reloads and I'm back to the original view again...
