### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by bgok** [gitcoinco/web#8671]
### Who
https://gitcoin.co/grants/2390/generative-art-nft-factory

### What 
Can't verify account. I verified that the verification tweet was sent from the right account (unless the twitter handle is case sensitive). It can't find the tweet, I guess.

### Why
🤷 Here's a link to the tweet: https://twitter.com/GashaponFun/status/1374464389126836227?s=20

Thanks!

**Comment by thelostone-mc** [comment]
Looks like it did get verified
