### ISSUE TITLE
Update Bounties Payment wallet Address on April 1

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/web#8673]
### Who
GPG

### What 

When we spin out, we will need to update the Eth Address that the Bounties payments are made to. We need to use this Eth address:
`0x88c62f1695DD073B43dB16Df1559Fda841de38c6`

Please confirm the wallet address when making the change with @Kweiss

**Comment by thelostone-mc** [comment]
is it just for bounties @Kweiss?

right now we use 
0x00De4B13153673BCAE2616b67bf822500d325Fc3

and we've got that address hardcoded for
- gitcoin grant donations 
- avatar_builder

There are also other stuff which are related to payout like : 
- tip payout address
- grants payout address which seems to use the same public address

**Comment by Kweiss** [comment]
Let's use that address for Bounties fees - `0x88c62f1695DD073B43dB16Df1559Fda841de38c6`

This for Grants development fund (linked to the Grant - I can do this after the round closes) - `0xd08Fe0c97c80491C6ee696Ee8151bc6E57d1Bf1d`

Avatar Builder, Tip Payout, Kudos donation (basically any misc. revenue) can all use - `0xAD278911Ad07534F921eD7D757b6c0e6730FCB16`

**Comment by octavioamu** [comment]
Ok about changing the maintainer address, we need to be sure all the points that could be affected
Running CLRs seems to be a blocker as we need to payout first
Tips on TIS (indirect send)
Kudos on KIS (indirect send)
Fees when creating bounties ( I think will be ok as are done when creating a bounty)
Old bounties using bounties network contract (not sure if will affected by this)
Grant when this get deployed then we can change our grant address if not probably cron jobs for grants will not count that contributions on the activity
mini clrs ?
stats on joe_dominance_index seems are counting those for Kevin probably will mess with the stats data.
Another topic is having diff address for each of those diff things is something we need to check the code and see if something will fail, as some logic is on js side and other on django side.
Many of the address are env variables so probably also we need to check the instances keys and do the changes.
Im missing / wrong some point here ?

**Comment by frankchen07** [comment]
> having a different address for each

Are you asking if it's not recommended to have a different address for each, or you just have to check to make sure that implementing these changes won't cause something to fail down the line?

> old bounties

Do we have an idea of how many of these bounties still exist? Perhaps it's time to begin asking folks to close / cancel the bounties.

> mini-clr

How do we feel about deprecated mini-clr or turning it off for now, now that Townsquare is also being hidden in new nav and homepage work?

**Comment by Kweiss** [comment]
The Grants checkout correctly displays the marking pool as the donation source. The backend no longer seems to be funding the correct Eth address though.

![Screen Shot 2021-06-16 at 12 00 46 PM](https://user-images.githubusercontent.com/1017776/122269479-7e0d0500-ce9a-11eb-8473-bb818fa7e56b.png)

This should go to: 0xde21F729137C5Af1b01d73aF1dC21eFfa2B8a0d6

These are currently going to: 0xd08Fe0c97c80491C6ee696Ee8151bc6E57d1Bf1d

**Comment by octavioamu** [comment]
@Kweiss 320f9d1917841d9326d398ee779341422530d661
