### ISSUE TITLE
contributed to grants but cannot see records in my wallet

### ISSUE THREAD

**Issue by fpning** [gitcoinco/web#8679]
**Describe the bug**

contributed to grants but cannot see records in my wallet
**To Reproduce**

**Expected behavior**

can you help check the wallet address which i payed for the grants
**Screenshots**

**Desktop (please complete the following information):**

- OS:mac
- Browser:chrome
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
could you add your contributions here
https://gitcoin.co/grants/add-missing-contributions
