### ISSUE TITLE
This is a test bounty for demo purposes

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#868]
This is a test bounty for demo purposes

### User Story

This is a test bounty for demo purposes

### Why Is this Needed?

To show off bounties via Video 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:  Feature

### Current Behavior
No demo video

### Expected Behavior
Demo Video

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by mkosowsk** [comment]
This is a test comment for attention-seeking purposes 😂

**Comment by owocki** [comment]
![download](https://user-images.githubusercontent.com/513929/38644886-5f898aa2-3d9f-11e8-8bfb-0fb0b4b41405.jpg)

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/868/589).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
