### ISSUE TITLE
Verify Grant Issue - down.social

### ISSUE THREAD

**Issue by MadGraph** [gitcoinco/web#8680]
Hello Gitcoiner!

### Who

https://down.social
We're a team of entrepreneurs creating games, apps, websites etc.. and have a project with our $down token to create a community to achieve our dreams and support our projects.

### What 

We're having an issue with the twitter verification. Twitter is suspending a lot of accounts right now for no apparent reason. We're trying to get it unsuspend at the time but there process is a pain

### Why

Is there any other way to verify a grant?

**Comment by thelostone-mc** [comment]
It seems like https://twitter.com/down_social is not blocked ! You should be able to verify the grant now
