### ISSUE TITLE
check for non-ETH crosschain addresses before submitting if a crosschain address is required

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8685]
### Circumstance

When opening a bounty and also submitting a bounty, many people are still erroneously inputting their ETH addresses for crosschain (non-ETH) bounties.

### Description 

Let's create some crosschain bounty address checks and make sure that folks are inputting the correct address given the chain / currency. Do not allow the user to proceed if the error has been thrown.

![Screen Shot 2021-03-23 at 16 42 50](https://user-images.githubusercontent.com/7516920/112233114-090d9480-8bf7-11eb-8559-f1d21b4b8eb9.png)
![Screen Shot 2021-03-23 at 16 43 08](https://user-images.githubusercontent.com/7516920/112233115-09a62b00-8bf7-11eb-86f4-097bb3b0e2ad.png)

```
// These chains seem similar to ETH address format 
- etc
- celo
- rsk
- binance
===
// no distinct format but does not start with 0x
- polkadot 
- ksm
- bitcoin 
====
// has a distinct way to identify
- harmony (starts with one)
- xinfin (starts with xdc)
- filecoin (starts with fil)
- zilliqa (starts with zil)

Polkadot addresses always start with the number 1.
Kusama addresses always start with a capital letter like C, D, F, G, H, J...
Sia Coin addresses are really long
```

**Comment by thelostone-mc** [comment]
This has been done for submit work in 
https://github.com/gitcoinco/web/pull/8723

Do we need this for bounty creation as well ?

**Comment by frankchen07** [comment]
> bounty creation

ideally yes, we want to limit the number of incorrect addresses we add, but depending on workload I would place it to be lower priority. Perhaps a question because I forget, if I paste an incorrect address in the funder address section, am I forced to payout from that address? That may help to determine priority.
