### ISSUE TITLE
when a hackathon issue is done (for contest & cooperative), I want the issue to be closed so gitcoin admins don't have to remind them and/or do it.

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8688]
### Circumstances

When a hackathon issue is done (for contest & cooperative), I want the issue to be closed so gitcoin admins don't have to remind them and/or do it.

### Description

Possible solutions discussed:

- Re-expose close bounty / override admin to administrators of the bounty. This at the very least makes it so admins (either sponsor-side or Gitcoin) can easily close the bounty without going into Django.
- Automatic closure is most likely not possible due to the contest/cooperative nature of a bounty.

### UX

Under which circumstances do we prompt the sponsor to close the bounty?

**Comment by thelostone-mc** [comment]
> Re-expose close bounty / override admin to administrators of the bounty. This at the very least makes it so admins (either sponsor-side or Gitcoin) can easily close the bounty without going into Django.

^ this has been done via https://github.com/gitcoinco/web/pull/8697
