### ISSUE TITLE
Aggregate view of all time donations

### ISSUE THREAD

**Issue by dominikclemente** [gitcoinco/web#8692]
### User Story

So I've donated for the first time, but I see that each donation is treated as a separate event in the activity tab. I tried to find a dashboard-like view of all contributions I've made, but it was nowhere to be found. I think that it would be a good addition to have a view site where you could see an aggregation of all the donations done to each project.

### Why Is this Needed

Currently, there is no easy way to see how much you contributed in total and how much to each individual project. We should be able to have an easy way to see all of this since it is a core feature of Gitcoin.

### Notes

I'm sorry if this isn't the way I should suggest a feature correctly, if I'm missing something or have bad issue styling, please let me know.

**Comment by Kweiss** [comment]
Does the page on your profile offer that view?

https://gitcoin.co/dominikclemente/grants

This is where I go to see this info :) This is helpful feedback that this can be better though! I am going to close the ticket, and let us now if that link helps at all :)
