### ISSUE TITLE
I received an error 400 when I tried to sign in

### ISSUE THREAD

**Issue by branberrybrad** [gitcoinco/web#8707]

**Comment by lthrift** [comment]
If you’re still having this issue please contact support@gitcoin.co

**Comment by branberrybrad** [comment]
﻿Lindsey, this happened so long ago. I tried contacting customer service many times already. I don’t care if I ever get my gitcoin back, all because the company’s stupid Sybil software was wrongfully banning IP addresses. Also y’all ip banned me right before gitcoin did there air drop and I got nothing.
