### ISSUE TITLE
[MISSING FUNDS] Double donation which was only counted for 1

### ISSUE THREAD

**Issue by dvncan** [gitcoinco/web#8715]
<!--
Hello Gitcoiner!

This issue relates to this issue [#8105 ](https://github.com/gitcoinco/web/issues/8105)

The webform linked in the comments would not submit any of my information.

While contributing to the Blockchain Education Network grants I double donated the same amount twice to the contract. Only 1 of the donation amounts has been associated with my profile.

Here are the transactions:

https://etherscan.io/tx/0x7d40df9a57a4384acc795e2f5c026e02f2df5eafece3204f7ebc4e7affd7006f

https://etherscan.io/tx/0xee231518643ab0e47f2aa4d8fb4edfdaa24c48deb2559531b0e43a44ec37a660

![image](https://user-images.githubusercontent.com/44993570/112735083-25ffdb80-8f07-11eb-92f3-dbfba725557e.png)

![image](https://user-images.githubusercontent.com/44993570/112735087-2c8e5300-8f07-11eb-8718-6804fa78c083.png)

0xf3e4D421E826a03848254095455ce818Ace25AF6

@Kweiss Please help and do not close this issue until it is fixed.

**Comment by dvncan** [comment]
While contributing to the Blockchain Education Network grants I double donated the same amount twice to the contract. Only 1 of the donation amounts has been associated with my profile.

Here are the transactions:

https://etherscan.io/tx/0x7d40df9a57a4384acc795e2f5c026e02f2df5eafece3204f7ebc4e7affd7006f

https://etherscan.io/tx/0xee231518643ab0e47f2aa4d8fb4edfdaa24c48deb2559531b0e43a44ec37a660

Screen cap of my contributions on the gitcoin page.,  Only showing 1 of the funding contributions
![image](https://user-images.githubusercontent.com/44993570/112735138-8000a100-8f07-11eb-9f1b-9904937bfc78.png)


Screen cap of my etherscan wallet. showing 2 transactions to the same wallet w the same amount

![image](https://user-images.githubusercontent.com/44993570/112735163-93ac0780-8f07-11eb-9942-f1e1fc0bfbaf.png)


**My wallet is

0xf3e4D421E826a03848254095455ce818Ace25AF6**


Please help @Kweiss

**Comment by dvncan** [comment]
@Kweiss the link you gave me in #8105 did not accept my wallet address or transaction ID but both are posted above.

**Comment by thelostone-mc** [comment]
You should be able to add it via https://gitcoin.co/grants/add-missing-contributions
