### ISSUE TITLE
How to Pause Gitcoin Grant

### ISSUE THREAD

**Issue by fluxresearch** [gitcoinco/web#8717]
CryptoArtNet had a successful fundraising campaign during Round 9 and we'd like to pause our campaign.

Should I just shut it down or what should I do?

Thanks!

**Comment by gdixon** [comment]
Hey @fluxresearch,

If you go to your Grant and click on 'Edit Grant' - there is a new option in there which will allow you to 'opt-out of CLR funding'. This will still allow you to receive contributions, but those contributions will not be considered for CLR funding. Is this what you had in mind?
