### ISSUE TITLE
I recieve message donate fail

### ISSUE THREAD

**Issue by dvdinh307** [gitcoinco/web#8721]
### Discussion
When i donate to project, I get response. I fail this donate action ?
Please confirm to me.
I attach file notificaiton.
[
![123](https://user-images.githubusercontent.com/4903373/112800622-182e8f80-909a-11eb-9c88-b4601bfe1920.PNG)
](url)

**Comment by thelostone-mc** [comment]
Could you paste the txn link and the activity link ?

**Comment by lthrift** [comment]
If you’re still having this issue please contact support@gitcoin.co
