### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by D4vid-UK** [gitcoinco/web#8722]
### Who

Hello - I am contacting you from the team at Multisend.org

### What

We are having issues verifying our twitter account due to a suspended account 

### Why

Please can this be changed to - https://twitter.com/multisend1   - or the account verified in a different way

Thanks

**Comment by gdixon** [comment]
Hi @D4vid-UK,

You're able to modify the twitter handle associated with the Grant yourselves via the "Edit Grant" button on the grant details page, this needs to be done by the Gitcoin user who created the Grant.

I'm going to close this out, but please reopen if you have any issues changing these details yourself and we will take a look for you.
