### ISSUE TITLE
Dear colleague, I have tried so many times to connect my account with BrightID but it always leads me to the site to join the verification party, which I have already done. Is there any other method or you can help me connect these two accounts mannually? Many thanks.

### ISSUE THREAD

**Issue by ezionsun** [gitcoinco/web#8724]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by Kweiss** [comment]
Please try again, I just reset your Bright ID settings
