### ISSUE TITLE
Need Donation Amounts and Matching Amounts for 15 Grants for this round

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#8728]
### User Story

As the manager of this grant: https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league
I would like to know the total funds raised (donations and matching amounts) by 15 Grants so I can distribute the funds my Grant raised to them as a bonus.

The 15 grants I need Donation and Matching amounts are:

Token Engineering Commons
cadCAD
ArtDAO
Commons Stack: Iteration 0
Crypto Commons Gathering 2021
Token Engineering Academy
Giveth.io - PAN League
A Dashboard for DAOs
Tokenlog
GivethTrace
Commons Simulator: Level Up
Trust Graphic Novel & Motion Comic
Trustlines Venezuela Community
Trueblocks
NFT Education

### Why Is this Needed

I would think every grant needs to know how much they raised that round in the UI... But i need it for the reason i mentioned above

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
Both?

### Definition of Done

I can go to any Grant and see how much they raised and how much matching they are getting in round 9

### Additional Information
I assume you are dealing with sorting out the various attacks right now and will add the amount raised by each grant this round on each of their grant pages soon... but i wanted to mention it to you just in case...

**Comment by GriffGreen** [comment]
@thelostone-mc :-D

Hey!

I need this data again... for round 10 i need these groups:


Commons Stack: Iteration 0
cadCAD
Crypto Commons Gathering 2021
Giveth.io - PAN League
Token Engineering Academy
Token Engineering Commons
Bloom Network
Trustlines Venezuela Community
NFT Education
A Hitchhiker's Guide to TE
Commons Swarm: ABC model
MyCrypto
GivethTrace
1hive
Commons Simulator: Level Up

For Round 11 I need these groups:


Crypto Commons Gathering 2021
Commons Stack: Iteration 0
Giveth.io - PAN League
Token Engineering Academy
Token Engineering Commons
Incubating Governauts
1hive Gardens
MetaGov - DAO Governance Research Group
NFT Education
cadCAD
Trustlines Venezuela Community
Govbase - DAO Database
GivethTrace
Grassroots Economics
Tokenlog


Any chance you can hook me up again :-D

**Comment by frankchen07** [comment]
this is done, pending sending results to griff

**Comment by GriffGreen** [comment]
THANK YOU!
