### ISSUE TITLE
The cart won’t open

### ISSUE THREAD

**Issue by panda-fu** [gitcoinco/web#8729]
The cart won’t open
![微信图片_20210330111928](https://user-images.githubusercontent.com/81399747/112928814-dc530300-9149-11eb-9f3f-efb468fa0722.png)

windows7  
chorme

**Comment by gdixon** [comment]
Hi @panda-fu,

Could we ask you to run this command in your devtools console and let us know what you have in your cart please: `localStorage.getItem('grants_cart')`

This will help us to fix the underlying issue, afterwards you can either wait for us to get a fix in, or clear your cart manually  (`localStorage.setItem('grants_cart', '[]')`) and add the grants again. 

Thank you for your patience and understanding! 😄

**Comment by thelostone-mc** [comment]
Closing this out cause we didn't hear back and we're assuming it;s solved
Do reopen if the issue has not been resolved
