### ISSUE TITLE
Hello I recently funded an issue and the gas went through but the bounty was never posted.

### ISSUE THREAD

**Issue by 420tiesto** [gitcoinco/web#8735]
I recently funded an issue and the gas/tx went through but the bounty was never posted.

tx id:
0xf9df7dc1c9b806977621733e3b35398cc1fb860bfcdc7d5263726a95b3bc7071

$12 premium posting
0x12911477fd64d1a827365ea7cc864de6ba41c8bcd3daaf9f39667a080a62f3a5

**Comment by thelostone-mc** [comment]
Could you ping us the github issue ?

**Comment by 420tiesto** [comment]
https://github.com/PrntNft/PrntPlace-main/issues/2

**Comment by thelostone-mc** [comment]
Bounty : https://gitcoin.co/issue/PrntNft/PrntPlace-main/2/100025374
