### ISSUE TITLE
Cart page stays in loading forever

### ISSUE THREAD

**Issue by aminlatifi** [gitcoinco/web#8738]
**Describe the bug**

When I visit https://gitcoin.co/grants/cart page, view stays in loading forever

**To Reproduce**

My wallet address is 0xF23eA0b5F14afcbe532A1df273F7B233EBe41C78
**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/5684607/113507186-3bf04a80-955e-11eb-9a61-058bb8598479.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Browser Version: 89

**Additional context**
This error shows up in browser console:
```
raven.js:58 TypeError: Cannot read property 'includes' of undefined
    at cart.87c1adbde14a.js:103
    at Array.filter (<anonymous>)
    at a.grantsByTenant (cart.87c1adbde14a.js:102)
    at fn.get (vue.c107ca5cd927.js:6)
    at fn.evaluate (vue.c107ca5cd927.js:6)
    at a.grantsByTenant (vue.c107ca5cd927.js:6)
    at a.render (eval at Ya (vue.c107ca5cd927.js:6), <anonymous>:3:2127)
    at a.e._render (vue.c107ca5cd927.js:6)
    at a.r (vue.c107ca5cd927.js:6)
    at fn.get (vue.c107ca5cd927.js:6)
    at fn.run (vue.c107ca5cd927.js:6)
    at un (vue.c107ca5cd927.js:6)
    at Array.<anonymous> (vue.c107ca5cd927.js:6)
    at qe (vue.c107ca5cd927.js:6)
```

**Comment by octavioamu** [comment]
Thanks for the report we are going to investigate and try to replicate, is hard to create the situation as some grant data seems broken.
if you can, will be a big help to us analise what you have on your cart. You can run this command on the console and paste here the result `localStorage.getItem('grants_cart');` 
To help you unblock the issue you can clear your cart running this command 
`localStorage.setItem('grants_cart', JSON.stringify([]));`
You will need to add the grants to the cart again.

**Comment by aminlatifi** [comment]
> Thanks for the report we are going to investigate and try to replicate, is hard to create the situation as some grant data seems broken.
> if you can, will be a big help to us analise what you have on your cart. You can run this command on the console and paste here the result `localStorage.getItem('grants_cart');`
> To help you unblock the issue you can clear your cart running this command
> `localStorage.setItem('grants_cart', JSON.stringify([]));`
> You will need to add the grants to the cart again.


```
> localStorage.getItem('grants_cart')

"[{"grant_id":"1127","grant_slug":"commons-stack-community-fund-panvala-league","grant_url":"/grants/1127/commons-stack-community-fund-panvala-league","grant_title":"Commons Stack Community Fund - Panvala League","grant_contract_version":"2","grant_contract_address":"0x0","grant_token_symbol":"","grant_admin_address":"0x1251A94b6d800979d2d933b8Bd5914b892772Ac6","grant_token_address":"0x0000000000000000000000000000000000000000","grant_logo":"https://c.gitcoin.co/grants/99bba16fa4b930635fcfe21ab57c9f19/panvala_commons_stack_logo.jpg","grant_clr_prediction_curve":[[0,420.391792867242,0],[1,299.195829567051,2.18925883476356],[10,302.658953264526,5.65238253223799],[100,309.164901046255,12.1583303139677],[1000,317.53686318196,20.5302924496727],[10000,324.448887123524,27.4423163912368]],"grant_image_css":"","is_clr_eligible":true,"token_local_id":3,"uuid":"57e796c3-8c4e-42fe-9157-6678e51e4cdb","grant_donation_amount":0,"grant_donation_currency":"PAN","grant_donation_num_rounds":1,"grant_donation_clr_match":0,"is_on_team":false},{"grant_id":"2154","grant_slug":"givethtrace","grant_url":"/grants/2154/givethtrace","grant_title":"GivethTRACE","grant_contract_version":"2","grant_contract_address":"0x0","grant_token_symbol":"Any Token","grant_admin_address":"0x97222B6eD77C17CD6CFC288eA363a688F57FB242","grant_token_address":"0x0","grant_logo":"https://c.gitcoin.co/grants/53bd0280cce690c970d4372a1aa80137/Giveth_Banner_for_GitCoin.png","grant_clr_prediction_curve":[[0,4.66620684476406,0],[1,4.14529812570121,0.238694509206732],[10,4.48505359999212,0.578449983497647],[100,5.07126875448472,1.16466513799024],[1000,5.80966077472917,1.90305715823469],[10000,6.45859801069531,2.55199439420084]],"grant_image_css":"","is_clr_eligible":true,"clr_round_num":"GR9 - dApp","tenants":["ETH"],"zcash_payout_address":"0x0","celo_payout_address":"0x0","zil_payout_address":"0x0","polkadot_payout_address":"0x0","harmony_payout_address":"0x0","binance_payout_address":"0x0","kusama_payout_address":"0x0","rsk_payout_address":"0x0","token_local_id":283,"uuid":"c739e0ff-8add-4611-936a-d33be0f6603f","grant_donation_amount":500,"grant_donation_currency":"PAN","payment_status":"waiting","txnid":null,"grant_donation_num_rounds":1,"grant_donation_clr_match":"1.12","is_on_team":true}]"

```

**Comment by aminlatifi** [comment]
> `localStorage.setItem('grants_cart', JSON.stringify([]));`

Thanks @octavioamu that worked

**Comment by octavioamu** [comment]
Thanks to you @aminlatifi 
Looking into the data seems you got 2 grants into your cart
https://gitcoin.co/grants/1127/commons-stack-community-fund-panvala-league
https://gitcoin.co/grants/2154/givethtrace
But the data for commons-stack-community-fund-panvala-league was corrupted with the wrong "tenant" probably you added that grant a lot of time ago when we didn't have that data yet on each grant and the code changed and was looking for something that didn't exist on your data. 

Closing for now but feel free to comment any other information/confirmation or if the problem get recurrent.

Thanks a lot for informing us
