### ISSUE TITLE
as a new user, i want a gitcoin slack intro bot, so i can know what i need to know to be a part of the community

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#874]
shoudl hang out in the community-intros channel and tell people hi as they join

the message we have been using so far:
```
Welcome to :gitcoin:! Curious to know more about you and what brings you here. Check out gitcoin.co/onboard to get rolling and don't…
```

**Comment by PixelantDesign** [comment]
This is a nice approach to slack onboarding. <img width="1366" alt="screen shot 2018-04-12 at 4 53 24 pm" src="https://user-images.githubusercontent.com/238235/38842658-36fc4e76-41b9-11e8-8918-75277c59851b.png">

**Comment by owocki** [comment]
@vs77bb if you can hit me up with some copy i can probably code something up real quick

**Comment by PixelantDesign** [comment]
I like that Bloom keeps it very short and sweet. 

Now thinking about it, calling the FTUX isn't a good idea since we won't know yet whether the user is a funder or contributor.

**Comment by owocki** [comment]
```
Welcome to Gitcoin! :gitcoin:

Gitcoin's mission is to *Grow Open Source*.

A few quick facts:
- We aren't an ICO.  There is no Gitcoin token.
- We are a community of blockchain developers.
- We are mission driven.  Check out our mission: https://gitcoin.co/mission

Here's how to get started in the community
- Say hey :wave: in #community-intros
- Join the community livestream every Friday at 5pm EST: https://gitcoin.co/livestream

We believe that a great way to build new skills is to learn by doing, and Gitcoin's core product (Bounties) supports that.

Here's how to get started with bounties:
- Check out the open bounties at https://gitcoin.co/explorer
- Post a bounty of your own at https://gitcoin.co/new
- Send a tip to any github username at https://gitcoin.co/tip

If you have any feedback for the team, or just want to say hi, this is them:
- @owocki, @vivek, @Pixelant, @mbeacom, @coderberry, @justin-bean

See you around! :spock-hand: 
Welcome_bot (and the Gitcoin Team)
```


<img width="904" alt="screen shot 2018-04-27 at 5 29 36 pm" src="https://user-images.githubusercontent.com/513929/39388899-cdaea820-4a40-11e8-8dc7-f7542f5cd311.png">

**Comment by owocki** [comment]
PR is open => https://github.com/gitcoinco/web/pull/1012

**Comment by kuhnchris** [comment]
@owocki is this still relevant? I see the PR connected to this is merged...
