### ISSUE TITLE
Why not recognize my donation ?

### ISSUE THREAD

**Issue by gonegolds88** [gitcoinco/web#8740]
I donate at grant Force DAO 0.5eth for gitcoin .

But admin Force DAO say :"you were not on the list gitcoin gave us" . Why ? Why not recognize my donation ?

My Wallet eth :
0xE37689CFf507cB199f55eaA23338181C9a63a748

Transaction Hash:
0x5b9bd6a09f35452a3c21db2c4b39d0627677918d4c98f1150e919d4a16d41008

https://etherscan.io/tx/0x5b9bd6a09f35452a3c21db2c4b39d0627677918d4c98f1150e919d4a16d41008

**Comment by Kweiss** [comment]
Hey there, it looks like your donation shows up on your profile here - Not sure why it was missed. You can point them to your profile: https://gitcoin.co/gonegolds88/grants

Hopefully this helps.

**Comment by gonegolds88** [comment]
Update my wallet erc20 in list donate gitcoin , pls .

Vào 02:19, T.3, 6 Th4, 2021 Kyle Weiss ***@***.***> đã viết:
