### ISSUE TITLE
Grant detail 404 for /grants/2449/daoswap

### ISSUE THREAD

**Issue by Davidliu027** [gitcoinco/web#8742]
**Describe the bug**
Hi my grant (/grants/2449/daoswap) was approved but detail page still showing 404, any idea why? Appreciated your help.

**To Reproduce**
Go to https://gitcoin.co/grants/2449/daoswap

**Expected behavior**
Can view detail page

**Screenshots**
![image](https://user-images.githubusercontent.com/19386653/113645111-d8c6fb00-96b8-11eb-9c94-3d75938c8ce6.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by thelostone-mc** [comment]
@Davidliu027 it loads now !
https://gitcoin.co/grants/2449/daoswap
