### ISSUE TITLE
I made a donation. How come there's no robot commenting on my success

### ISSUE THREAD

**Issue by jeky138** [gitcoinco/web#8744]
<!--
Hello Gitcoiner!
I made a donation. How come there's no robot commenting on my success？ 
![520](https://user-images.githubusercontent.com/79683717/113673860-142eed00-96ec-11eb-9ce5-08c73e5e100b.png)

**Comment by gdixon** [comment]
This feature was added here: https://github.com/gitcoinco/web/pull/8614

The contributions you made happened before this PR made it into stable, any contributions you make in the future will be commented on by gitcoinbot.

I hope this helps! I'm going to close out this issue, but if you need any more assistance please feel free to reopen this issue. Thanks 😃
