### ISSUE TITLE
How to delete gitcoin account 

### ISSUE THREAD

**Issue by ghost** [gitcoinco/web#8746]
How to delete gitcoin account? I am getting many call every day I haven’t signed up for. Not interested to be here anymore.

**Comment by gdixon** [comment]
Hi there, as you have deleted your github profile, I presume you no longer need support with this issue - but just incase:

You can suppress emails by visiting this page: https://gitcoin.co/settings/email/
And if you really want to remove your account, you can do so here: https://gitcoin.co/settings/account/

We're sorry to see you go! 

I'm going to close out this issue, but if you do see this and would like support with anything else, please don't hesitate to get in touch via email: support@gitcoin.co!
