### ISSUE TITLE
Change wallet address for Gitcoin Grant

### ISSUE THREAD

**Issue by SonOfIshtar** [gitcoinco/web#8749]
### Why: Build Finance DAO
https://gitcoin.co/grants/1906/build-finance-dao

### Why: Costly to operate the existing wallet.
Current wallet is for is the DAO treasury. We have decentralised the access to it. Hence, it's now only accessible via onchain governance, which is costly (gas plus dev time), 

We, however, have a multisig wallet for daily ops needs, which easier to operate (See below). Please replace the wallets.
0x39198bC9956AC06b1CbE9f6B186460BEA19C05B9

**Thanks for all your hardwork!**

**Comment by Solexplorer** [comment]
Done, issue can be closed now
