### ISSUE TITLE
Wrong Gitcoin avatar v. GitHub avatar. Duplicated Gitcoin profiles.

### ISSUE THREAD

**Issue by QYuQianchen** [gitcoinco/web#8750]
**Describe the bug**

- [ ] Avatars for user on Gitcoin doesn't match those on GitHub. It is not possible to change avatars either.
- [ ] Avatars for organization on Gitcoin doesn't match those on GitHub. It is not possible to change avatars either.
- [ ] Duplicated Gitcoin accounts for the same GitHub account (after changing GitHub handle)
- [ ] All the created bounties are linked with my old GitHub handle but not the current one.

I've created three bounties for my organization. None of them has correct avatars for both my own user profile and for my organization. 
Bounties are
- https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429
- https://gitcoin.co/issue/hoprnet/hopr-analytics/3/100025429
- https://gitcoin.co/issue/hoprnet/hoprnet/1431/100025428

![image](https://user-images.githubusercontent.com/10935300/113839380-ebf8ca00-978f-11eb-8656-205989e74b97.png)

1. The lower avatar is current GitHub handle and avatar. However, under the bounty history (the upper one), it shows my old GitHub handle and old avatar. FYI, my GitHub handle was changed around 2 months ago.

2. At the same time, all those created bounties are associated with my old GitHub handle (https://gitcoin.co/chenchenyo) but not my current one (https://gitcoin.co/qyuqianchen). The former profile shouldn't exist because it's an obsolete GitHub account after the update in GitHub handle.

![image](https://user-images.githubusercontent.com/10935300/113841138-b48b1d00-9791-11eb-8d28-1e0d86c9622c.png)

3. HOPR association - the organization for which I created bounties, only has a default avatar (https://gitcoin.co/hoprnet), in contrary to our GitHub avatar (https://github.com/hoprnet)

**To Reproduce**

Follow the standard step to open a bounty using a GitHub account whose handle gets changed a few months ago.

**Expected behavior**

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Brave
- Browser Version: 1.22.67

**Comment by QYuQianchen** [comment]
Hey there. Do you have any update on this issue?

**Comment by octavioamu** [comment]
Fixed!! sorry for the delay

**Comment by rymnc** [comment]
Hi, I'm having the same issue with duplicated accounts. see here -

https://gitcoin.co/rymnc
https://gitcoin.co/aaryamannchallani

I changed my username a couple months back.

It isn't letting me submit bounties, as they were indexed with my previous username

**Comment by rymnc** [comment]
Hi, I'm having the same issue with duplicated accounts. see here -

https://gitcoin.co/rymnc
https://gitcoin.co/aaryamannchallani

I changed my username a couple months back.

It isn't letting me submit bounties, as they were indexed with my previous username

**Comment by JitrZ** [comment]
Hi, My problem too. Duplicated accounts. Changing github username lead to two accounts on gitcoin and I have all works I've done linked to old account and I can't submit any work.

**Comment by JitrZ** [comment]
@octavioamu you just mentioned avatars. There is a problem when change github username too.

**Comment by lthrift** [comment]
Hi everyone, we’ve done work to correct duplicated accounts and changing of connected GitHub accounts. If you’re still experiencing issues, please contact support@gitcoin.co
