### ISSUE TITLE
gpg - homepage

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8754]
### Circumstances

Redesign and rebuild of our homepage/landing page (essentially, gitcoin.co)

### Description

The landing and the homepage are the same page. 

===

**For the homepage:**

For the hypothetical solution we discussed, I would suggest removing the row of 4 CTAs at the top of the homepage. The hypothesis here is that this prevents CTA overload on the homepage, and allows new users to scroll, READ, and understand Gitcoin better in order to have the context to click on the four CTAs that exist as we scroll down.

- [x] copy change - we're keeping the 4-row JTBD CTAs, let's ensure the copy is finalized by Matt (comment for the JTBD landing pages here: https://github.com/gitcoinco/web/issues/8658
- [x] figure out the gradients

===

**For the 4 CTAs from scrolling down on the homepage:**

Clicking on these CTAs will lead to the respective JTBD landing pages, regardless of whether or not a user is logged in. So, for a new user, they hit the homepage, scroll down, read about earn, and say "yes, this is what I want." They click "Earn" on the homepage, and it takes them to the Earn JTBD landing page. At this point, they HAVE NOT yet authenticated on Github. 

The three CTAs at the bottom of the JTBD landing pages (Bounties, Hacks, & Grants), if clicked on, will lead to Github Authentication. This ensures that the user READS and fully understands the context of what's possible for the JTBD they clicked on. They continue to one of the products using the CTAs at the bottom of the JTBD landing pages.

After successful authentication, the user will be dropped off at the respective product page they selected.

- [x] copy change (Matt): each of the CTAs on the homepage for each job as the user scrolls down - let's ensure the copy here is informational, inspirational, and hooks the user to go to the JTBD landing page.

- [x] copy change (Matt): The homepage CTA text (in the buttons), I will leave up to content and Alisa to ensure that the user isn't surprised by connecting to Github.

===

We're solving for a lot of problems. I'll list out the problem and hypothetical solution so we're clear on why we're taking the actions we're taking.

- too many CTAs on the homepage -> let's remove the top row of CTAs

- new users, based on previous research, want more than a 1-liner of context before giving up their Github login -> removing the top row of CTAs, and moving Github login to the CTAs on the JTBD landing pages

- users being confused on what they can do on Gitcoin -> the combination of homepage hook CTA and the respective JTBD landing page provides clear guidance and direction on which action to take next

- incomplete data collection -> it's an imperfect solution, but we still will have adequate data to understand if our JTBDs will work. GA can be used to suss out homepage -> JTBD connections, and once a user has authenticated on Github, we will know if they go and complete the action that they were dropped off at, post-login.

- Graham's nav work has already moved townsquare to the community tab, and we will not be redirecting users to townsquare anywhere from the homepage because that has shown to create problems, not solve them.

===

Engineering is ready to build when the foundations for the page are set in stone.

Build spec: https://www.figma.com/file/pOEKRzmB6pcbQzBp04S0l4/Gitcoin.co?node-id=541%3A11490 (lower right frame gitcoin.co)

because our JTBDs and new homepage serves as the start of a new onboarding flow, we'll want to disable our old until we re-think the deeper parts of that experience
- [X] disable profile modal
- [X] disable hackathon onboarding modal

we are also disconnecting the townsquare redirect
- [X] remove the behavior that gitcoin.co redirects to gitcoin.co/townsquare
- [X] townsquare can still be accessed by direct URL or navigation ONLY

**Comment by frankchen07** [comment]
adding misplaced scope from the JTBD landing ticket:

https://github.com/gitcoinco/web/issues/8658#issuecomment-817490585

**Comment by PixelantDesign** [comment]
Final design 

![Gitcoin co_home](https://user-images.githubusercontent.com/238235/114745166-69868200-9d1c-11eb-849b-e3a963451058.png)
