### ISSUE TITLE
`make fix` stylelint error

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#877]
```
make fix
```

yields
```
sh: stylelint: command not found
```

**Comment by owocki** [comment]
@mbeacom is do you get this too?

**Comment by mbeacom** [comment]
Looks like you need `stylelint` - `npm install -g stylelint`

**Comment by owocki** [comment]
oic.. i just figured that that was managed in the docker container... but i guess i was wrong 

should that be added to some of the contributing / readme docs if it's local?

**Comment by thelostone-mc** [comment]
If we are doing that, might as well add `npm install -g eslint` too!
