### ISSUE TITLE
grant

### ISSUE THREAD

**Issue by izombiecrypto** [gitcoinco/web#8773]
<!--
Hello Gitcoiner!

i contributed to many grants round 9 but they diden't show in my dashboard i've paid with eth using zksync

**Comment by thelostone-mc** [comment]
do reopen this with a few more details

**Comment by izombiecrypto** [comment]
hello i did participate in 8 grants round 9 but the dont show up in my
dashboard i did pay with zksync

Eth addres
0x73C864786FB940aeea5C0731E8c8265f371ca1E5

Ss


Le mar. 13 avr. 2021 3:36 PM, Aditya Anand M C ***@***.***> a
écrit :
