### ISSUE TITLE
Implement DDoS protection

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8780]
### Circumstance

As we scale, we want to think ahead and make sure are prepared for DDoS attacks.

### Description

Are we adequately protected against DDoS attacks?

1. pay for something like Cloudflare
2. integrate Cloudfare and setup DNS
3. setup alerts, reports, and basic defense for small and large attacks
4. test integration to ensure protection is working

**Comment by thelostone-mc** [comment]
Ended up using AWS + WAF as opposed to  cloudflare for now
