### ISSUE TITLE
I can't pay a bounty in RBTC with my wallet connected via WalletConnect 

### ISSUE THREAD

**Issue by brunocalmels** [gitcoinco/web#8796]
**Describe the bug**
When trying to payout a bounty in RBTC via Wallet Connect, the page is stuck, and errors are displayed in browser console.

**To Reproduce**
1- Visit a bounty you can payout.
2- Connect your wallet via Wallet Connect. I am using [Defiant](https://defiantapp.tech/) wallet due to it being the only one (that I know of) with support of WC for RSK.
3- The dapp confirms the connection. It can read my RSK mainnet address.
4- Click on "Payout Bounty".
5- Input an amount. Confirm. Page with correct sender and receiver addresses is shown. Amount is also correct.
6- Click on Payout.
7- Page is stuck.

**Expected behavior**
I should receive a message in my mobile wallet, asking me to approve/sign the transaction.

**Screenshots**
![Captura de pantalla de 2021-04-16 15-56-41](https://user-images.githubusercontent.com/8678464/115071796-1273df00-9ecd-11eb-8a26-8c902676c176.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20
- Browser: Chrome
- Browser Version: 87.0.4280.88

**Smartphone (please complete the following information):**

- Device: Samsung S8
- OS: Android
- Wallet: Defiant 
- Version: 1.1.1+129

**Comment by thelostone-mc** [comment]
Hey @brunocalmels ! 
The rsk integration involves using nifty wallet / another browser extension 
https://chrome.google.com/webstore/detail/nifty-wallet/jbdaocneiiinmjbjlgalhcelgbejmnid?hl=en

As opposed to using walletconnect. This would require you to ensure your eth extensions are disabled and only nifty wallet is active

**Comment by brunocalmels** [comment]
Is it too much of a hassle to enable WalletConnect for RSK also? There are quite some dapps that already allow it (Sovryn, Money on Chain...)

**Comment by thelostone-mc** [comment]
I've passed this along to RSK.
Once it's supported -> turning it on at our end should be pretty straightforward 
Closing this out for now.
Once we know it's supported -> we'll update it our end
