### ISSUE TITLE
Active wallet address appears twice 

### ISSUE THREAD

**Issue by nopslip** [gitcoinco/web#8802]
**Describe the bug**
When you've connected your wallet to Gitcoin.co the wallet drop down shows your active address twice. 

**To Reproduce**
Open gitcoin.co, login, connect to metamask (probably the same with other wallet providers but I haven't checked)

**Expected behavior**
Only display the address once. 

**Screenshots**
<img width="1615" alt="Screen Shot 2021-04-20 at 5 48 50 AM" src="https://user-images.githubusercontent.com/1734015/115391571-da0a2480-a19c-11eb-8ba9-e2c68afcd92e.png">

**Desktop (please complete the following information):**

- OS: OSX BigSur 11.2.3
- Browser: Firefox 87

**Additional context**
RE: QL regression testing

**Comment by sonshine518** [comment]
Mine does that too, however I am using Brave
