### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by DropMagnet** [gitcoinco/web#8818]
### Who

I have already tweeted from @DropMagnet to verify ownership. Please look into it. Thanks.

https://twitter.com/DropMagnet/status/1384234889210327051

**Comment by gdixon** [comment]
It seems this issue is resolved so I'm going to close this ticket out. Thank you for your patience!

<img width="485" alt="Screenshot 2021-04-28 at 21 16 09" src="https://user-images.githubusercontent.com/5897836/116467128-3fc67280-a867-11eb-8304-8bc7d941a2ba.png">
