### ISSUE TITLE
Grant Round 9 contribution not received

### ISSUE THREAD

**Issue by biancasama** [gitcoinco/web#8827]
Hi Gitcoiners.

After the end of **Grant Round Match 9**, for a while, I could not make the claim for the matching contribution because the button 'claim match' was gone, but I only managed now. However, on the wallet address now ([https://etherscan.io/address/0xb1b4Fd7EA1a74b6e5652a2BCf794224fd79544f5](url)) only the match appears (~0.60 DAI) and not the contributions from our grant supporters (~80 DAI) as in zkSync [https://zkscan.io/explorer/accounts/0xb1b4Fd7EA1a74b6e5652a2BCf794224fd79544f5](url). 

Did we lose those contributions? How can we retrieve them?
Thank you for your help.

Best,
biancasama

**Comment by Kweiss** [comment]
You should be able to withdraw the funds in zkSync using the following link:
https://withdraw.zksync.io/

Let us know if you need any more help.
