### ISSUE TITLE
Cannot submit work

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#883]
### Description
*Type*: Bug

### Current Behavior
I try to submit work but metamask shows information that contract code throws exception.

### Expected Behavior
User should be able to submit work.

### Reproduction
https://gitcoin.co/issue/gitcoinco/web/506

### Additional Information
![image](https://user-images.githubusercontent.com/1838338/38738463-8676426a-3f32-11e8-9298-c8bb235b967d.png)

Github issue linked to bounty is closed, might it be the reason ?
Submited work for another bounty 5 minutes ago without a problem.

**Comment by owocki** [comment]
this is likely because the bounty is expired

https://github.com/gitcoinco/web/pull/870

this issue will help with the UX

**Comment by owocki** [comment]
@kziemianek -- once the PR is merged, @ me back and ill pay you out directly via your ETH address ( i will also mark the bounty as done so you get credit for it on your profile )
