### ISSUE TITLE
Grant contribution disappeared

### ISSUE THREAD

**Issue by ellsworthjh** [gitcoinco/web#8836]
### Why

I had set up a Gitcoin account on Feb 13 (possibly Feb 14) and contributed 0.35 ETH to the Delta Prize Grant on Feb 14. However, the contribution does not appear on my Gitcoin account.

TxID : 0x3a52b235f26f4cc5b41da997e18251830618d4b47e621484cd7304ad44e8b0ef

My username is ellsworthjh.

Just wondering if that can be fixed?

Thank you

**Comment by gdixon** [comment]
Hey @ellsworthjh,

We've ingested that contribution on your behalf:

<img width="971" alt="Screenshot 2021-05-05 at 07 33 28" src="https://user-images.githubusercontent.com/5897836/117104606-5f343280-ad74-11eb-849e-36f7b2829189.png">

I'm going to close out this issue, but please feel to reach out if we can help with anything else 😄
