### ISSUE TITLE
missing contributions in the gitcoin grants UI

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8852]
### Circumstance

when gitcoin grants r9 was in progress, contributors were seeing diffs between the grants UI and on-chain transactions, which prompted a stopfix solution (missing contributions link).

### Description

- [ ] what was the exact problem why contributions weren't showing up? (gas prices? zksync issue?)
- [ ] zksync failures 
- [ ] transaction always pending, 
- [ ] transaction dropped or replaced 

### Discussion

@frankchen07 @thelostone-mc @mds1 to sync up and clarify the problem

possible solution suggestion is to not show contributions as complete until they post on the etherscan and are successful

**Comment by mds1** [comment]
For reference, the latest known details / potential causes / things to investigate are listed here: https://github.com/gitcoinco/web/issues/7744#issuecomment-754823192

**Comment by thelostone-mc** [comment]
@mds1 I'm not clear on the root cause -> any thoughts on how we can go about 
- reproducing this
- how to fix this
