### ISSUE TITLE
Refresh organization logo (kodadot)

### ISSUE THREAD

**Issue by yangwao** [gitcoinco/web#8861]
### User Story

As an organization https://gitcoin.co/kodadot I would like to refresh our logo on Gitcoin from recent [Github/kodadot](http://github.com/kodadot)
We've changed it a long time ago and we would like to keep up to date everywehre.

### Why Is this Needed
Would be nice to add some click button to "pull the new logo from Github" probably like is in the account setting?

*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
Old logo of an organization

### Expected Behavior
The logo should change on action or whenever organization on GitHub updates their logo for a new one

### Definition of Done
New logo for the organization

### Additional Information
Love your work! :)

**Comment by connoroday** [comment]
This has been updated! But I agree it would be nice if users had a button to do this themselves :)

**Comment by yangwao** [comment]
How we can refresh the organization description and website?
Since that has changed.

**Comment by thelostone-mc** [comment]
> How we can refresh the organization description and website?
 
If you are an owner of the github org -> you should be able to edit it via https://gitcoin.co/kodadot/manage

Closing this out now ! do reopen if that doesn't work

**Comment by yangwao** [comment]
Not sure what is wrong, no errors in the console, only warns.

![image](https://user-images.githubusercontent.com/5887929/122187462-58c6c980-ce8f-11eb-9deb-00a4668ec291.png)
