### ISSUE TITLE
Update wallet address for Gitcoin Grant

### ISSUE THREAD

**Issue by Shammah** [gitcoinco/web#8864]
When signing up for a grant I've accidentally used a temporary Ethereum address instead of my hardware wallet. I'd like to change it to `0x71df067D1d2dF5291278b7C660Fd37d9b6272b4C` please. My grant can be found at https://gitcoin.co/grants/2544/grandiose.

**Comment by gdixon** [comment]
Hey Roy,

I have updated that address for you!

<img width="737" alt="Screenshot 2021-05-11 at 03 01 32" src="https://user-images.githubusercontent.com/5897836/117746966-3c3ad000-b205-11eb-8dfd-9c267b9fd9f6.png">

I'm going to close out this issue, but please get in touch if there is anything else we can do to assist you further! 😃
