### ISSUE TITLE
add pagination to the Gitcoin Grants API

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8868]
### Circumstance

> So we wanted to finally start properly using the api you implemented here: https://github.com/gitcoinco/web/issues/6493
It's for our gitcoin grant support in rotki: https://github.com/rotki/rotki/issues/692

> Unfortunately the grant query seem to raise a 504 after some time: https://gitcoin.co/api/v0.1/grants/report_real/?eth_address=0x9531C059098e3d194fF87FebB587aB07B30B1306

> What is the actual API endpoint? It's probably we are missing the api endpoint that would return all contribution details for an address and the one for all the contributions a grant has received.

===

> Was checking, seems with less data works https://gitcoin.co/api/v0.1/grants/report_real/?eth_address=0xeDa95eD3e3436C689376889F9eD0a8f4bA23E866&format=json but the endpoint is missing some pagination logic and for some reason is not very performant, we will need to invest some time on this and do it better.  As your address probably has a lot of data the request is failing. 

===

> What we need is to have an endpoint to query grant history as per the linked issue. The user case is: A user is a grant owner and wants to get all of the data of each donation in each round made to them by both on-chain transactions and zksync. Net donations (without the gitcoin %). 

### Description

- [ ] add appropriate API endpoints / restructure API as needed
- [ ] add pagination so we don't query a shit-ton of data at once and have a timing out issue

**Comment by yabirgb** [comment]
If it helps I believe one big bottleneck could be how Django and Django REST makes and process the queries. It has been a lot of time since I last used django but using something like [select_related](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#select-related) could improve a lot the queries. 

For more info: https://levelup.gitconnected.com/dealing-with-the-n-1-problem-optimising-django-part-4-f02010c7931d

**Comment by LefterisJP** [comment]
Both yabir and I work in rotki so we would love to see this solved. Let us know if there is any way we can help push this forward.

**Comment by yabirgb** [comment]
Hello @thelostone-mc Is this deployed? By querying the API it doesn't seem so. Could you give me an expected date for it?
