### ISSUE TITLE
Gitcoin Bounties Bugs

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8898]
### Circumstance

When I am funding a bounty on Gitcoin, I am concerned about my privacy so when I see that my funder email (from Github) is shown, I want it hidden, so my privacy is preserved.

When I am cancelling my bounty on the cancel bounty form, there is a typo.

![image](https://user-images.githubusercontent.com/7516920/118155768-6e972980-b3cd-11eb-9da3-2f28d21c7ea4.png)

### Possible Solutions

- [ ] the "show email publicly button is available on the bounty creation form, is there a way to make it more prominent?
- [ ] fix typo on bounty cancellation page

**Comment by thelostone-mc** [comment]
typo fixed via commit : 763978593d6b8a4c722eaf3c9363376a91db0d59
