### ISSUE TITLE
Increase backend test coverage

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#89]
# Backend Testing and Coverage
- Travis and Codecov integrations are now live.
- Testing coverage for the backend code is currently at:  [![codecov](https://codecov.io/gh/gitcoinco/web/branch/master/graph/badge.svg)](https://codecov.io/gh/gitcoinco/web)

If you're interested in contributing to the initiative to increase our percentage, you should familiarize yourself with `django` and `pytest` test writing.

## Useful documentation

- Django: https://docs.djangoproject.com/en/2.0/topics/testing/
- pytest: https://docs.pytest.org/en/latest/
- pytest-django: http://pytest-django.readthedocs.io/en/latest/tutorial.html

Additional information on testing Django with pytest: 
- https://stackoverflow.com/questions/36446585/how-to-test-a-django-model-with-pytest
- http://engineroom.trackmaven.com/blog/using-pytest-with-django/

## Considerations:

- Implement factories for easy test data generation (possibly `factory-boy` http://factoryboy.readthedocs.io/en/latest/)
- Mock: https://docs.python.org/3/library/unittest.mock.html

*Please break up your test coverage pull requests by app/file when possible.*

### Example implementation:
If you intend on writing test coverage for `dashboard/views.py`, you **could**:

- Create `dashboard/tests/` directory.
- Add `__init__.py` file to `dashboard/tests`
- Add `test_views.py`
- If factories will be used, add the `dashboard/tests/factories.py` file to define the factories to be used.

***

- [x] Implement automated testing and coverage reports

**Completed in #102:** The goal of this discussion is to build consensus around an approach to backend/django testing.
We'll want to make use of the Django testing suite and probably implement further testing functionality via:

- `pytest`

Following successful implementation of a base testing suite, I assume we will want to automate test builds and coverage testing with something like:

- [x] https://travis-ci.org/ (Testing)
- [x] https://codecov.io (Coverage)

Feel free to disagree with any of the above suggestions, they are merely to get a discussion going.

**Comment by owocki** [comment]
this is enough of an organizational priority i am happy to throw some bounty money at it once we have specced it

**Comment by thelostone-mc** [comment]
travis \m/
@mbeacom if you need help in setting this up, I'm here. (Never done it before, so expect annoying pings if you agree to this )

**Comment by owocki** [comment]
do we still need this live now that codecov/ travis are integrated?  might be a good oppy to change issue title to 'increase test coverage'

**Comment by PixelantDesign** [comment]
@mbeacom do we still need this issue?
