### ISSUE TITLE
hello , why I can't move my 0,007 ETH ?

### ISSUE THREAD

**Issue by supermario2021** [gitcoinco/web#8901]
why I can't move my 0,007 ETH ?
![Screenshot_3](https://user-images.githubusercontent.com/74507981/118340207-f5095380-b512-11eb-8800-4daf574a6110.jpg)

**Comment by thelostone-mc** [comment]
Could you post a screenshot of which network you are present on ?

**Comment by supermario2021** [comment]
Hi . I don't understand how are you?

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
В 7 июн. 2021 г., 11:27, Aditya Anand M C написано:
