### ISSUE TITLE
![image](https://user-images.githubusercontent.com/67705248/118314851-3afaf300-b4e4-11eb-90cc-9d944bfb61fb.png)

### ISSUE THREAD

**Issue by DSBUGAY2** [gitcoinco/web#8902]
![image](https://user-images.githubusercontent.com/67705248/118314851-3afaf300-b4e4-11eb-90cc-9d944bfb61fb.png)
![image](https://user-images.githubusercontent.com/67705248/118314878-49e1a580-b4e4-11eb-9ecd-8a6219b99c38.png)
submitting both
thanks

_Originally posted by @RobGA3 in https://github.com/gitcoinco/web/issues/8710#issuecomment-841432609_

**Comment by DSBUGAY2** [comment]
> ![image](https://user-images.githubusercontent.com/67705248/118314851-3afaf300-b4e4-11eb-90cc-9d944bfb61fb.png)
> ![image](https://user-images.githubusercontent.com/67705248/118314878-49e1a580-b4e4-11eb-9ecd-8a6219b99c38.png)
> submitting both
> thanks
> 
> _Originally posted by @RobGA3 in [#8710 (comment)](https://github.com/gitcoinco/web/issues/8710#issuecomment-841432609)_

**Comment by thelostone-mc** [comment]
Sweet designs! I believe these would have to raised as a PR and not an GitHub issue. Closing this out now
