### ISSUE TITLE
I can't submit the payout address.

### ISSUE THREAD

**Issue by EzLemon** [gitcoinco/web#8907]
**Describe the bug**
I cannot upload my work, because it tells me to put a valid address, however the address is valid and I have contacted the creator of the reward and he has told me that he cannot fix it.#### ### Your title here...
**To Reproduce**

Submit a work with a valid CELO addres.

**Expected behavior**

Would let me submit it.
**Screenshots**
![image](https://user-images.githubusercontent.com/33668627/118521638-80652d80-b73b-11eb-9b3a-ef8cdba77dd9.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge
- Browser Version:

**Comment by thelostone-mc** [comment]
This should be fixed now. Rolled out a fix for this 12 hours back. Do reopen is this persists
