### ISSUE TITLE
increase grant bulk checkout limit

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8916]
### Circumstances

When using bulk check out on grants during round 9, there were grant contributors who had to manually record grant names in order to manually batch their checkout since the cart was limited to only 40 grants, which was a headache for contributors who contributed to more than 40+ grants.

### Description

- [ ] explore the possibility of increasing cart size to 200 (AT RISK - this relies on zkSync fixing the limit)
- [ ] we remain with zksync checkout capped at 40 grants, communicated through a tooltip (above the checkout button), if the zksync team can increase the cart size, then it's a 1/2-line change to set and communicate the new cart limit
- [ ] ensure mainnet checkout has no cap on the cart. this provides a better user experience and doesn't purposely block the user

### Decision Context

- If we cap both carts, we need a new UX to solve batching. We're also adding friction & pessimism, and risk more rework when/if zksync increase the limit
- Capping the limit in the side-cart also limits the number of grants that can be made part of a collection, which would cause problems for clrs based on collections

**Comment by thelostone-mc** [comment]
The reason for limiting was due to zksync ! 
Are you talking about paginating the data also?

**Comment by gdixon** [comment]
I think @mds1 was saying that zksync has increased their limit to 200?

**Comment by mds1** [comment]
Latest on our zkSync checkout limit decision can be found here: https://gitcoincore.slack.com/archives/C01FQV4FX4J/p1615920355000200?thread_ts=1615808276.024000&cid=C01FQV4FX4J

**Comment by thelostone-mc** [comment]
Syncing with team -> we will know in a week if we can increase the limit to 90 or remove it all together based on what zksync team tells us
