### ISSUE TITLE
email rollup for standard transactions on gitcoin grants

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8917]
### Circumstance

Using bulk checkout allows for an email rollup, we should do the same for standard checkout so folks who donate to more than 40+ grants don't get bombarded with hundreds of grant emails.

### Description

- [x] implement email rollup according to cart size
- [x] how do we rollup for standard checkout (where I believe the problem exists)

for grant owners:
- [ ] have an email sent out every cron job interval
- [ ] on the email itself, there will be no actual contributor or individual contribution details, instead, we will add aggregate metrics and link them to their grant activity feed
- [ ] "in the last 6 hours your grant has earned approximately $$$ from XXX users,  please click here to see more"

**Comment by thelostone-mc** [comment]
I'm not clear on the flow here. Checkout can be done it 2 ways
- Zksync Bulk checkout
- Standard Bulk checkout 

And AFAIK -> we do email rollup for both. Could you clarify more on this ?

**Comment by frankchen07** [comment]
to confirm, for both versions of checkout, we do bulk emails for both? (sent to a contributor)?

how about for grant owners?

**Comment by thelostone-mc** [comment]
for contributor ->  that was solved here: https://github.com/gitcoinco/web/pull/8258
for grant owners -> this wouldn't apply cause we won't be able to group them cause the trigger point is from the contributor

**Comment by frankchen07** [comment]
> for grant owners -> this wouldn't apply cause we won't be able to group them cause the trigger point is from the contributor

so are you saying the grant owner does or doesn't receive emails based on someone contributing to their grant?

**Comment by thelostone-mc** [comment]
the grant owner does receive emails based on someone contributing to their grant!

**Comment by frankchen07** [comment]
gotcha, and are those also rolled up?

I believe this we still have to discuss, right? I recall Graham saying they are not and there's an exception to why that is the case.

**Comment by thelostone-mc** [comment]
might be worth hoppin on a call and discussing this !
Rollups don't happen on funder cause they get contributions from people randomly at a different point in time.
The solution which is being proposed by @gdixon is not sending out emails asap when a funder gets a contributions and group them up and send them once a day / every 6 hours (whatever we deem fit)


I don't think this is super needed right now but if we want to pull this off.
A couple of things which might need to be discussed :
 - this might need a email redesign (not sure cause you're giving a summary report) as opposed to instant updates
 - we have sign off from team cause this means you WILL NOT get an email immediately  when you receive a contribution 
 - engineering-related : finally see if it can be done without adding a new column to contribution / subscription table.  maybe each time the command is run
- finally what do we do about contributions that are in pending / failed when this rollup email thing is sent out

**Comment by willsputra** [comment]
maybe something like this? @frankchen07 @thelostone-mc 
![grants_grant-owner](https://user-images.githubusercontent.com/19514207/121227488-33015980-c8be-11eb-989c-05c7a7a65c75.png)

**Comment by willsputra** [comment]
@frankchen07 cc @PixelantDesign updated based on feedback + responsive view
![Slice 1(1)](https://user-images.githubusercontent.com/19514207/121353569-95ab3180-c960-11eb-9410-df5e960c1333.png)
