### ISSUE TITLE
error in the quest

### ISSUE THREAD

**Issue by GidKirill** [gitcoinco/web#8926]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by gdixon** [comment]
Hi there,

I'm closing this out because there is not enough detail here for us to work from. 

If you are facing problems could you please follow our issue template so that someone on the team can assist you.

Many thanks,
Graham
