### ISSUE TITLE
as a submitter, i want to link my github PR when i submit work, so i can show off what i did

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#893]
### User Story

as a submitter, i want to link my github PR when i submit work, so i can show off what i did

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

helps us link the work that was done to the actual issue itself

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
feature

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
- add this element to the submit work form
- record it in the DB for the submission

**Comment by mbeacom** [comment]
Addressed in #900
