### ISSUE TITLE
Image for ql-lore is out of date and needs to be updated

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/web#8933]
### What 
on the Gitcoin lore page, the image for the comicbook is out of date and should be:
https://cloudup.com/ctT4ZKjwv-G

Can we please replace the preview image of the comic book?

**Comment by octavioamu** [comment]
kyle can you send the actual image instead of the screenshot ? some colors been changed by the print

**Comment by octavioamu** [comment]
nevermind found my way into the channel

**Comment by octavioamu** [comment]
done on stable will be on prod when the last changes get deployed
