### ISSUE TITLE
Impossibility to access fund from the grant

### ISSUE THREAD

**Issue by Soleauchain** [gitcoinco/web#8937]
### 0xAB1163a7c620fa460b63Fb66B7AC2229dE187350, Soleauchain receive a great fund from @liugod8
https://gitcoin.co/grants/2143/fund-for-nft-art-protection  

Unfortunately I can't see it on zkscan. Could you please give a hand ?  https://zkscan.io/explorer/accounts/0xAB1163a7c620fa460b63Fb66B7AC2229dE187350

**Comment by thelostone-mc** [comment]
@Soleauchain it looks the contributions made by luigod8 was on rinkeby 
https://rinkeby.etherscan.io/tx/0x2442177293e5b74045929bfaf906bf79fe3ec102a9a97011001a2ae92478223f

It was done via zksync mainnet
