### ISSUE TITLE
gr10 countdown banner

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#8938]
### Circumstance

just to reiterate the problem we're facing:

1. it wasn't clear on when exactly the next round starts
2. it wasn't clear when a round ends
3. showcase who sponsors the round on the grants homepage

### Description

solution:

pre-round: countdown banner to start of round (with or without sponsors logos, will need to confirm with Scott)
during round: countdown banner to end of round with sponsor logos
post round: no countdown, just sponsor logos

- [ ] current design on the homepage: https://github.com/gitcoinco/creative/issues/353#issuecomment-844072441

**Comment by octavioamu** [comment]
Dates 
2021-06-16 15:00:00 UTC (9am MST time) to
2021-07-02 00:00:00 UTC (6pm MST 7/1)
