### ISSUE TITLE
As a funder, I want to test the ability for a funder to be able to 'tip' Gitcoin, so I can see what kind of revenue would be gneerated.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#894]
### User Story

As a funder, I want to test the ability for a funder to be able to 'tip' Gitcoin, so I can see what kind of revenue would be gneerated.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Revenue Testing.. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
None payment to gitcoin during bounites

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
During payout, optional 3% suggested donation to Gitcoin.

### Repr

**Comment by kuhnchris** [comment]
I guess this resulted into the platform fee?
