### ISSUE TITLE
GTC unable to sign txn for personal voting weight

### ISSUE THREAD

**Issue by kdm5126** [gitcoinco/web#8947]
hi frens! thanks and congrats!!!!

after selecting the %'s of how i would vote the metamask prompt popped for me to sign, could click sign but it never kicked off the process for my hardware wallet to confirm

before claim, after answering questions. chose to disable delegation, pick your % and attempt to sign txn via metamask with a hardware wallet connected (trezor)

2nd prompt to actually sign the txn with my keys?

sorry no screenshots. i delegated to trent to bypass...

- OS: big sur
- Browser: brave 
- Browser Version: Version 1.24.86 Chromium: 90.0.4430.212 (Official Build) (x86_64)

**Comment by frankchen07** [comment]
@kdm5126 please submit a help ticket here: https://support.gitcoin.co/home/
