### ISSUE TITLE
if a GTC distribution does not exist, then user should not be able to go https://gitcoin.co/quadraticlands/mission/receive

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#8948]
https://gitcoin.co/quadraticlands/mission/receive

go here without a claim

you can go through the flow

expect results:
1. you cannot go through the flow or if you can it should give you an error at the top of proof of use before it hits the ESMS

**Comment by ojide** [comment]
Not bad but still I discovered those who are active has am high Amount of Gtc received
