### ISSUE TITLE
As a funder, I want to have a PM assigned to my Gitcoin account, so I can know that they have my authorization to manage my bounties.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#895]
### User Story

As a funder, I want to have a PM assigned to my Gitcoin account, so I can know that they have my authorization to manage my bounties.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

someone who is (0) knowledgeable about the Gitcoin project, (1) has the Project Management skills to groom out issues to make them digestible to the community, (2) has the Software Engineering skills to identify what is and isn't doable by the community and how to provide the best info possible to the Developer, and (perhaps most importantly) the communication skills necessary to enable communication across all parties, whether they're technical or not. 

does this mean holding the hand of all projects that use gitcoin and walking through every issue they have with a fine-toothed comb? no, and that wouldn't scale anyway. however, i think by providing initial gitcoin customers with the skillset of how to go to about using the Gitcoin platform does scale and while there would be an initial start-up cost the dividends would be great as more and more projects reach "critical mass". that is, providing new projects with resources and a bit of personal direction on how to groom tickets, how to communicate and how frequently to communicate with Contributors on issues, how to appropriately price issues for the community, etc.

(Thanks Mitch for the above)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: 
Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
No PM functioality

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
TODO -- need to spec this out

**Comment by PixelantDesign** [comment]
This came up in today's research session. Need to validate to what extent this would be helpful.
