### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Grownline945** [gitcoinco/web#8963]
Hi i have been completing quests to earn kudos on your platform but 1/2 times every time i successfully complete a quest and try to redeem  my kudos i get an error 403. i have went back and tried to claim it many times but it keeps giving me the same message.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by gdixon** [comment]
We were experiencing some infrastructure issues around this time, is this still a problem for you?

**Comment by thelostone-mc** [comment]
Closing this out as we're assuming it was resolved. If not -> do reopen with more screenshot/videos
