### ISSUE TITLE
Problem with singing POAP Badges

### ISSUE THREAD

**Issue by SinaEyzed** [gitcoinco/web#8969]
**Describe the bug**
I tried to sign my POAP badges but I'm getting an error that is in the screenshot. I tried both Ethereum and xDai chain but didn't work. I'm using Trezor T HW connected to my metamask.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/12483581/120039332-40802f00-bff4-11eb-9a4d-e19499cf49c9.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 90.0

**Additional context**

**Comment by gdixon** [comment]
Hi there,

Thank you for reaching out, could you please try again for us? We have recently deployed #8905 which should resolve this issue.

Many thanks,
Graham

**Comment by SinaEyzed** [comment]
I just tried and it worked. Thank you

**Comment by gdixon** [comment]
Brilliant, I'll close this out!

Thanks again, please let us know if you run in to any other problems!
