### ISSUE TITLE
as an admin, i want to spin up a gitcoin geth node, so i can use it for gitcoin stuff

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#901]
for https://github.com/gitcoinco/web/pull/509#discussion_r181842114 , we will need a local `geth` node that's guaranteed to be up to date with the most recent version of the blockchain

**Comment by mbeacom** [comment]
I can set this up on the k8s cluster, if that's cool with you.

The only downside is it's going to take a while to fully sync versus spinning up a ridiculous GPU instance, syncing, tearing it down, and attaching the volume to another instance.

If we can wait a bit, I can spin it up on k8s in the typical fashion and just wait for it to update **or** we can spin up a gigantic GPU instance, sync it, destroy the instance (keeping the volume) and attach the volume to the geth deployment.

**Comment by owocki** [comment]
> spinning up a ridiculous GPU 

i dont think we want to spec this to be GPU-bound.  we only need our node to have nice GPU abilities if were going to be mining (which we are not).

> I can set this up on the k8s cluster, if that's cool with you.

yes pls.  

i recall that last time i did this, i had a hard time keeping the node synced if i used micro/nano instances.  i believe that a medium/large instance was able to keep synced.  IIRC the node was mostly memory and disk bound. 

make sure when you start syncing the node you use [fast sync](https://ethereum.stackexchange.com/questions/1161/what-is-geths-fast-sync-and-why-is-it-faster)!  and youll also want to enable RPC, but only internal to our own IP addresses, not to the public range

**Comment by mbeacom** [comment]
@owocki Oh, no. I didn't mean we'd use the GPU instance indefinitely. It's much faster to fully sync a geth node with a beefy GPU instance.  Then you can drop the ec2 instance, keep the volume, and attach it to the normally sized node.

I'll see what's up with the kub helm recipe for geth and see if we can get this spun up.

**Comment by owocki** [comment]
ah got it.. thx

**Comment by owocki** [comment]
@mbeacom whats the effort level on this you think?  from chatting with @scottydelta it seems like its the thing standing in between us and testing / shipping

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/pull/509/files#r182538500

**Comment by mbeacom** [comment]
@owocki Node currently performing a fast sync on our k8s cluster under the `gc-web-prod` namespace.

**Comment by owocki** [comment]
neato . any quick and dirty way to get an ETA forecast for full sync?

**Comment by owocki** [comment]
@mbeacom let me and @scottydelta know pls so we know when we can schedule the testing of https://github.com/gitcoinco/web/pull/509/files#r182538500

**Comment by owocki** [comment]
@mbeacom let us know !

**Comment by mbeacom** [comment]
This is completed.

**Comment by owocki** [comment]
now we just gotta have monitoring if it goes out of sync!
