### ISSUE TITLE
Me Menu QA

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#9018]
Lookin' great @gdixon! Could we update the following areas?

- [x] Under hackathons, could we change the word participating to In Progress so that it covers both hackers and funders?
- [x] Under Hackathons menu(same location as on bounties) add a link to Created by, link to this filter in bounties: created, open, mainnet, organization name. Bounties created by the funder.

Please remove menu items that aren't relevant to funders
 - [x] Under Hackathons, Remove _projects_ 
- [x] Under Bounties, remove _reserved for me_ 

Kevin Request
- [x] for the ‘my grants’ menu it should go to ?idle=true for each of the items so i can see my idle grants

**Comment by frankchen07** [comment]
can you clarify - "Under Hackathons menu(same location as on bounties) add a link to Created by, link to this filter in bounties: created, open, mainnet, organization name"? I believe it's just a link to see which hackathon bounties have been created by the funder, if I'm not mistaken.

The others seem sane. These changes definitely bring up the thought that our app doesn't handle the distinction between contributors and funders very well. I sense there is a larger solution at hand.

**Comment by PixelantDesign** [comment]
>can you clarify - "Under Hackathons menu(same location as on bounties) add a link to Created by, link to this filter in bounties: created, open, mainnet, organization name"? I believe it's just a link to see which hackathon bounties have been created by the funder, if I'm not mistaken.

Yes it...that was an example of the filter terms @frankchen07 
<img width="264" alt="Screen Shot 2021-06-09 at 12 32 29 PM" src="https://user-images.githubusercontent.com/238235/121393954-db470a80-c91e-11eb-91ff-cbf55d35f723.png">
