### ISSUE TITLE
BrightID connection with Gitcoin

### ISSUE THREAD

**Issue by L-KH** [gitcoinco/web#9045]
<!--
Hello Gitcoiner!

I scan my gitcoin brightID QR code in my phone and lose it. so I install it in my new one and get verified by BrightID application but can't get verified on Gitcoin because I lose my first QR. is there a way to verify my gitcoin brightID ?

more information:
here is the screen when I click verify of BrightID on Gitcoin:
![image](https://user-images.githubusercontent.com/12660772/121752928-26247600-cb09-11eb-839e-a2cd25ebaf58.png)
my gitcoin profile is: https://gitcoin.co/l-kh/

**Comment by L-KH** [comment]
weird I submit description for this issue :/

**Comment by L-KH** [comment]
Hey,
I want to get more trust bonus but I lose my old BrightID first QR code.
I now have BrightID application verified so just need a new QR code to connect it with my application.
I hope I explain the problem well.
Here is my profile: https://gitcoin.co/l-kh/

**Comment by gdixon** [comment]
Hey, we have some PR's going in this week which will fix the BrightID flow!

Would you like us to manually reset this to allow you to authenticate sooner?

Many thanks,
Graham 😃

**Comment by L-KH** [comment]
> Hey, we have some PR's going in this week which will fix the BrightID flow!
> 
> Would you like us to manually reset this to allow you to authenticate sooner?
> 
> Many thanks,
> Graham 😃
Thanks for your support.
the QR code is back now. but I have another issue. here is the screen
![gitciss](https://user-images.githubusercontent.com/12660772/122139222-6739c480-ce40-11eb-9514-8113a2d7bccc.png)
is there a way to fix it?

**Comment by gdixon** [comment]
Can you try now, I've reset your BrightID uuid 👍

**Comment by L-KH** [comment]
> Can you try now, I've reset your BrightID uuid 👍

Yeeeap. its works perfectly :) Thanks a a lot.
I will close this issue

**Comment by Nemeswat** [comment]
![Screenshot_2021-06-23-14-21-45-023_org brightid](https://user-images.githubusercontent.com/64239422/123103948-66032b80-d42e-11eb-9bf3-0a8e2bb61116.jpg)

Please reset your BrightID uui too

**Comment by Nemeswat** [comment]
> ![Screenshot_2021-06-23-14-21-45-023_org brightid](https://user-images.githubusercontent.com/64239422/1103948-66032bd42e-11eb-9bf3-0a81116.jpg)
> 
> Please reset your BrightID uui too

No response yet... Wow
