### ISSUE TITLE
404 after logout at profile page

### ISSUE THREAD

**Issue by kziemianek** [gitcoinco/web#905]
### Description
*Type*: Bug

After logging out user is redirected to same page, which might result in 404 page.

### Expected Behavior
User should be redirected to home page ?
Also accessing https://gitcoin.co/profile/ without being authorized should result in 401 page, not 404.

### Reproduction
Logout at profile page or access https://gitcoin.co/profile/ being not logged in.

**Comment by mbeacom** [comment]
@kziemianek This was my bad. I didn't modify the way we handle fetching profile information via `/profile` - Originally, we required a username to follow `profile` or default to the current user and 404ing if they don't exist or they don't have a profile... not so much an unauthorized situation.

Pushing in a fix for this now to redirect to home.
