### ISSUE TITLE
Reset your Bright ID UUID .

### ISSUE THREAD

**Issue by Nhocqstyle** [gitcoinco/web#9052]
<!--
Hello Gitcoiner!

Please use the template below for bugs found within Gitcoin.

Hey,
I want to get more trust bonus but I lose my old BrightID first QR code.
I now have BrightID application verified so just need a new QR code to connect it with my application.
I hope I explain the problem well.
Here is my profile: https://gitcoin.co/nhocqstyle
**Additional context**

**Comment by thanklee** [comment]
request that reset  Bright ID UUID
