### ISSUE TITLE
Request that reset  Bright ID UUID

### ISSUE THREAD

**Issue by dunghung** [gitcoinco/web#9056]
Describe the bug

I can not link brightID with Gitcoin. Clicked on the Link and it directed me to Gitcoin, then nothing happened.Please reset my BrightID to connect with Gitcoin!

To Reproduce

Expected behavior

Screenshots

Desktop (please complete the following information):

OS:
Browser: Chrome
Browser Version: 
Smartphone (please complete the following information):

Device: iPhone 12 Promax
OS: ioS
Browser: Safari
Version:
Additional context

**Comment by Lerog1724** [comment]
Requesting to reset my Bright ID #9506
OPPO F1s
 Model: A1601
Browser: Chrome
91.0.4472.101
