### ISSUE TITLE
UX when an issue is kicked back to open

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#906]
(not ready to be worked on)

From Seiron on chat:

> What about the issues where someone started working but they got reopened due to lack of progress? They have usually an unrealistic rest period of time to finish them. Is there a solution to add some more time to it? There are some issues with only some days left. What happens with this issues? Gone forever? (edited)

**Comment by owocki** [comment]
heres another one where (as of today 4/18) there was no good sign of whether it was abandoned or not https://gitcoin.co/issue/gitcoinco/web/259

**Comment by PixelantDesign** [comment]
We could prompt the funder if there are any details they’d like to update:

Extending time frame and learnings from the progress made. 

Once updates are made we remarket as a new issue.

**Comment by owocki** [comment]
yeah its probably worth sending the funder an email.  if someone gets me copy i can code it in

**Comment by kuhnchris** [comment]
Was there any design for his, that we could start implement? I'll tag it as ungroomed for now - let me know.

Thanks
