### ISSUE TITLE
bug: Incorrect facebook API keys on staging and production

### ISSUE THREAD

**Issue by gdixon** [gitcoinco/web#9085]
**Describe the bug**

The Facebook API keys are expired or incorrect on staging and production

**To Reproduce**

Attempt to verify with Facebook on staging/production

**Expected behavior**

The user should be able to verify with Facebook

**Screenshots**

_N/A_

**Desktop (please complete the following information):**

_N/A_

**Smartphone (please complete the following information):**

_N/A_

**Additional context**

These (_FACEBOOK_CLIENT_ID_, _FACEBOOK_CLIENT_SECRET_) need to be regenerated in http://developer.facebook.com/ by someone with access to the GetGitcoin facebook account

**Comment by thelostone-mc** [comment]
This was working the last round ! Did the keys expire?

**Comment by DreadKnight** [comment]
It doesn't work for me now and it didn't work in last round or before either.
Really looking to increase my trust score for the upcoming GR10...

**Comment by owocki** [comment]
i see this in the facebook developer center for this app https://share.getcloudapp.com/WnuxBlm8

whomever fixes this add me here ( https://www.facebook.com/kevinowocki ) and ill add u as a fb admin here ( https://developers.facebook.com/apps/118275288856850/fb-login/settings/ )

**Comment by owocki** [comment]
@thelostone-mc added u as an admin at https://developers.facebook.com/apps/118275288856850/roles/roles/
