### ISSUE TITLE
Change grant receiving address

### ISSUE THREAD

**Issue by Mettodo** [gitcoinco/web#9103]
### Who
Grant creator of [Njombe Innovation Academy](https://gitcoin.co/grants/2687/njombe-innovation-academy-panvala-league)
### What
I would like to change the receiving address of the grant to the one dedicated to this project: 0x308Fd8FB79379dEAD5A360FFb6Dd2D1AFf9F5EE4
### Why
I created the grant before creating a multisig wallet

**Comment by gdixon** [comment]
Hey Mettodo,

We've updated that address:

<img width="823" alt="Screenshot 2021-06-15 at 20 58 46" src="https://user-images.githubusercontent.com/5897836/122115679-a48c5b00-ce1c-11eb-95c4-3042d50b4155.png">

I'm going to close out this issue, but please get in touch if theres anything else we can do! 😄
