### ISSUE TITLE
at the end of the new FTUX, should we let users know about our social accounts?

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#911]
see [this example](http://bits.owocki.com/1o2o3o1S0j0A/Screen%20Shot%202018-04-17%20at%204.11.42%20PM.png) from dock.io

**Comment by owocki** [comment]
@vs77bb this could feed into the viral loops we talked about with dean last week

**Comment by mkosowsk** [comment]
This makes a lot of sense to me!

**Comment by PixelantDesign** [comment]
It is a possibility.

The contributor Ftux ends with a user on the issue explorer with recommended bounties filtered. @owocki where did you envision the social CTAs being shown?

 If I remember correctly, we do invite users to join our social media channels in the drip campaign that follows their initial onboarding.

**Comment by owocki** [comment]
i suppose it could be an optional last step or 2nd to last step.  ideally we would a/b test this to figure out if it creates any friction (and if it creates any results)

**Comment by PixelantDesign** [comment]
Agree on the testing piece. I think we should prioritize getting users through the flow of Ftux plus the new avatar builder. The more screens we inject into the sequence creates more opportunities for drop off.

**Comment by PixelantDesign** [comment]
Hmm, I didnt close this issue. That is strange!

**Comment by thelostone-mc** [comment]
@PixelantDesign Should I throw in a dummy screen along with the FTUX ? ^_^

**Comment by PixelantDesign** [comment]
Currently the last step is the Issue explorer. I think we need to find a good place to introduce social. We can maybe beef up the mentions in the drip campaign that follows a user joining.

**Comment by kuhnchris** [comment]
@thelostone-mc did you ever get an answer to this?
