### ISSUE TITLE
Reset my BrightID

### ISSUE THREAD

**Issue by hehoho01** [gitcoinco/web#9112]
Hello Gitcoiner!

BrightID verify display used by another user before.I didn't have a certified BrightID to work with before.Please reset BrightID verify.thank you.
![dde2abce86c0729e2bd1](https://user-images.githubusercontent.com/80500833/122518749-cdd70200-d03b-11eb-905f-5b4cbaf9646d.jpg)

**Comment by lehoangha45335** [comment]
request that reset  Bright ID
Hi admin, I lost QR code gitcoin, I don't links app Bright ID, give me the QR code again, thanks a lot.
