### ISSUE TITLE
Migrate avatar storage and static to S3

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#912]
As a staff member, I want all avatars and static assets stored in S3, so we can reduce load against the web application and ensure asset availability/redundancy.

The current implementation of `avatar` uses local file storage.  If we proceed with k8s/dockerized workloads, we'll need to provide a persistent shared volume cross-pods to allow sharing of these avatar resources.

Likewise, static file handling is currently being handled at the app level via Whitenoise, which works fine, but would allow us to offload that entirely using S3 storage backend.

This will be handled internally.

Ref #902

**Comment by kuhnchris** [comment]
@danlipert can you check if this is there? but as far as I know everything static is served from s.gitcoin.co - so I'm preemtively closing it.
