### ISSUE TITLE
GR10 category pages do not filter grants

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#9121]
**Describe the bug**

GR10 category pages do not filter grants

**To Reproduce**

Click on a GR10 category, such as DAPP https://gitcoin.co/grants/clr/ethereum/10/gr10-dapp or Community https://gitcoin.co/grants/clr/ethereum/10/gr10-community
Grants listed are not filtered for the category.

**Expected behavior**

List of grants should filter for that GR10 category.

**Screenshots**

![image](https://user-images.githubusercontent.com/56145569/122261454-46499180-ce89-11eb-9fba-6b1839093486.png)

![image](https://user-images.githubusercontent.com/56145569/122261529-59f4f800-ce89-11eb-9e9c-a72431ca424c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Browser Version: Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)

**Comment by gdixon** [comment]
Hi @BTCAlchemist,

Thanks for the report! We've got this fixed now, can you confirm it's working correctly on your end?

**Comment by BTCAlchemist** [comment]
@gdixon Looks good now. Thanks!
