### ISSUE TITLE
Update Grant Address

### ISSUE THREAD

**Issue by mohamedmansour** [gitcoinco/web#9122]
Hello, I would like to update my grants address here:
https://gitcoin.co/grants/1709/ethereum-2-educational-grant

To another address, how do I do that? It is currently locked.

**Comment by thelostone-mc** [comment]
Please drop in the new address here and we can update it

**Comment by mohamedmansour** [comment]
How do you verify the grant is owned by me?  

The new address is 0x1C6F6dae4e19B80Eb42801cDE0Ba873Ad5Ff2E2d

**Comment by mohamedmansour** [comment]
@thelostone-mc  any update on this?

**Comment by nonseodion** [comment]
@mohamedmansour pls has your address been updated?

**Comment by Solexplorer** [comment]
> How do you verify the grant is owned by me?
> 
> The new address is 0x1C6F6dae4e19B80Eb42801cDE0Ba873Ad5Ff2E2d

We verify that github issue author is the same as the grant creator, anyways I've updated it

**Comment by lthrift** [comment]
If you still need help with your grant address, please contact support@gitcoin.co
