### ISSUE TITLE
Saving e-mail settings does not work - Error 500

### ISSUE THREAD

**Issue by nya-elimuai** [gitcoinco/web#9126]
**Describe the bug**
Changing the e-mail settings at https://gitcoin.co/settings/email and pressing the "Save" button results in Error 500.

**To Reproduce**
  1. Go to https://gitcoin.co/settings/email
  1. Select/unselect a check-box
  1. Press "Save" button

**Expected behavior**
- Settings should be saved.

**Screenshots**

<img width="987" alt="Screen Shot 2021-06-16 at 8 00 51 PM" src="https://user-images.githubusercontent.com/15718174/122269544-fea52300-cee5-11eb-876b-aa531d65d442.png">

**Desktop (please complete the following information):**

- OS: 
- Browser: Brave
- Browser Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by nya-elimuai** [comment]
@frankchen07

**Comment by gdixon** [comment]
Hi @nya-elimuai,

Thanks for the report, we'll get this fix deployed ASAP!! 😄

**Comment by gdixon** [comment]
Fix is in, please try again @nya-elimuai 👍

**Comment by nya-elimuai** [comment]
@gdixon It works now, thanks 🙂
