### ISSUE TITLE
Unable to Disconnect Google  in Trust Bonus Tab

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#9128]
**Describe the bug**
Unable to Disconnect Google  in Trust Bonus Tab 
Confirmed with 2 other users

**To Reproduce**

- Go to Trust Bonus Tab
- Disconnect Google
- Click yes, disconnect
- see green confirmation that Google was disconnected
- Go back to the Google tile, the verified is still present and google still connected
- % on Trust meter also doesn't decrease

**Expected behavior**

- Google is disconnected after confirmation
- Trust bonus decreases

**Screenshots**
![image (48)](https://user-images.githubusercontent.com/238235/122279550-29778300-ceb6-11eb-9397-cfb125885039.png)

**Desktop (please complete the following information):**
- MAC Catalina 10.15.5
- Browser: CHROME
- Version: Version 90.0.4430.212

**Comment by willsputra** [comment]
same here! seems successful but Google is not disconnected

browser console:
<img width="1556" alt="Screenshot 2021-06-17 at 3 21 56 AM" src="https://user-images.githubusercontent.com/19514207/122279971-3d090500-cf1b-11eb-8d57-1a944d3a53f6.png">

**Comment by GuistF** [comment]
yes, the same happens to me 
![image](https://user-images.githubusercontent.com/48440062/122281039-bc79e280-cee1-11eb-8870-71180752183d.png)
Windows 10 Home 
Browser: Edger
Version 91.0.864.48
