### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by RGhadamian** [gitcoinco/web#9147]
### Who
Upside Competitions

### What
We have two grants

The one we want to keep: https://gitcoin.co/grants/1091/upside-is-a-premium-content-platform-aimed-at-a-g
The duplicate one: https://gitcoin.co/grants/2786/upside-is-a-creator-monetisation-platform-aimed-a

### Why
I created the duplicate one because we couldn't get the original one verified, then both got verified. But we have some conributions going to the duplicate and we want to combine the contributions into the original grant so we can get the matching algorithm optimised and not have any confusion

**Comment by thelostone-mc** [comment]
Looks like the other one has been closed!
