### ISSUE TITLE
Gitcoin/BrightID verification

### ISSUE THREAD

**Issue by Nemeswat** [gitcoinco/web#9170]
Hello support!

I have been verified on BrightID but I am having issues linking my BrightID account to gitcoin. I keep getting this error message each time I try since after my verification.

"Failed to link your account in gitcoin to your BrightID. The contextid............. is used by another user before"

Please help me reset my BrightID verification

**Comment by Nemeswat** [comment]
No response yet... 

This is useless

**Comment by Nemeswat** [comment]
![Screenshot_2021-06-23-14-21-45-023_org brightid](https://user-images.githubusercontent.com/64239422/123106707-c5fad180-d430-11eb-8847-215fd384d9cb.jpg)

Please reset my BrightID uui

**Comment by blockchaindude108** [comment]
you got a solution?

**Comment by Nemeswat** [comment]
Nothing yet... GitHub sucks
