### ISSUE TITLE
BrightID cannot be authenticated

### ISSUE THREAD

**Issue by 100000003** [gitcoinco/web#9185]
I downloaded BrightID a few days ago and linked a Gitcoin account. BrightID was later uninstalled. Today I re-downloaded BrightID and passed the conference BrightID account authentication. But I found that I could not connect my Gitcoin account. Can you cancel the previous unauthenticated association for me?
![IMG_20210621_145618](https://user-images.githubusercontent.com/80445568/123051813-b2516a00-d434-11eb-89cb-ca83bd8b2f5b.jpg)

**Comment by zhenboshi** [comment]
me too！

**Comment by Kweiss** [comment]
Can you explain why you created a new BrightID user? You have the ability to log back in to the same user (on BrightID) and should have done that. Further, once you are verified on Gitcoin, uninstalling the app will not break your verification. IT looks like you are no longer verified... Did you happen to change something to unverify your account?

**Comment by zhenboshi** [comment]
This BrightID cannot add friends! So I want to change to a new BrightID, if
possible, can you help me unbind the current BrightID, thank you!


In Christ

Mark



Kyle Weiss ***@***.***> 于2021年6月25日周五 上午9:18写道：

**Comment by 100000003** [comment]
> 
> 
> 您能解释一下您创建新 BrightID 用户的原因吗？ 您可以重新登录到同一用户（在 BrightID 上）并且应该这样做。 此外，一旦您在 Gitcoin 上通过验证，卸载该应用程序不会破坏您的验证。 看起来您不再经过验证...您是否碰巧更改了某些内容以取消验证您的帐户？

Because I downloaded BrightID APP on Huawei mobile phone for the first time, and scanned the QR code on Gitcoin. I didn't understand either. Later, two mobile phones were required for BrightID conference certification. Easy to scan QR code. At that time, I used a Huawei mobile phone to participate in the meeting. Another Apple mobile phone downloaded BrightID certification and passed the review. After passing the review, I uninstalled the BrightID APP on the Huawei mobile phone. So it needs to be reset. Because the reviewed new BrightID account cannot be associated with Gitcoin. I still have many GR10 projects that I have not donated. I am very anxious now. can you help me?
