### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by thadguidry** [gitcoinco/web#9193]
### Who
OpenRefine 
https://gitcoin.co/grants/3043/openrefine
### What
We need support help to verify Twitter account managed by our @magdmartin 
### Why
So we can have the Gitcoin grant linked to our Twitter to run a successful funding campaign.

Does @magdmartin just need to login to Gitcoin on our grants page and create an account and then needs to be added to the team?

**Comment by thelostone-mc** [comment]
Looks like it's been verified
