### ISSUE TITLE
Grant approval email sent has typo (avoid crypto lingo when possible on Grant stuff)

### ISSUE THREAD

**Issue by thadguidry** [gitcoinco/web#9194]
**Describe the bug**
HTML email sent has typographical spelling mistake.

Subject: **Your Grant on Gitcoin Grants has been approved**
...
Get ready to **buidl** and push forward open source!
...

**To Reproduce**

**Expected behavior**

Get ready to **build** and push forward open source!

**Screenshots**
![image](https://user-images.githubusercontent.com/986438/123194858-ca44e000-d46c-11eb-967c-062727523373.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**
Since funding and granting is sometimes wider than the blockchain system itself, it might be wise to avoid crypto customs with language, lingo, and name conventions within the Gitcoin ecosystem where it makes sense, especially messaging.  This would also help ease translations to allow them to be understood a bit more universally instead of transliterated as evidenced in a few language files where it could be avoided completely: https://github.com/gitcoinco/web/search?q=Get+ready+to+buidl

**Comment by lthrift** [comment]
Thanks for your feedback! I’ve captured this in a place where we’re synthesizing similar feedback for consideration.
