### ISSUE TITLE
Find funded issues by specific address

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#92]
I miss clickable link to find all issues funded from specific ETH address.

Like from https://gitcoin.co/funding/details?url=https://github.com/open-eid/linux-installer/issues/13 I want to see all other issues funded from that address.

**Comment by owocki** [comment]
hey @abitrolly you can use the search functionality to do this https://gitcoin.co/explorer?q=0X63B7608B7F47DE1C0D1F94F85FFCB260FBCB4890

**Comment by abitrolly** [comment]
Yea, I tried to enter my GitHub nickname and email, and it didn't work. I guess making a link should be easy now. But there might be two - one for search and one for Etherscan. )

**Comment by owocki** [comment]
@abitrolly  is https://gitcoin.co/profile/abitrolly what you were looking for per chance?

**Comment by abitrolly** [comment]
Yea. There are two proposals.
1. First, it would help to provide a link to profile instead of email on issue page https://gitcoin.co/funding/details?url=https://github.com/open-eid/linux-installer/issues/13
2. I still would like to see issues funded from specific address

**Comment by PixelantDesign** [comment]
I think when implement views by org this will help!
