### ISSUE TITLE
Verify Grant Issue nombre educacion integral

### ISSUE THREAD

**Issue by mikyR** [gitcoinco/web#9209]
Para apoyar mi proyecto educacion Integral
Hello Gitcoiner!

Please use the template below for issue ideas or bugs found within Gitcoin.
If it is general support you need, reach out to us on [Discord](https://discord.gg/gitcoin)

Provide a general summary of the issue in the title above and use relevant fields below to define the problem.

-->

**Comment by thelostone-mc** [comment]
Please reopen with more information

**Comment by mikyR** [comment]
Holá muchas gracias por toda la colaboracion que me puedan prestar
