### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by SLRead** [gitcoinco/web#9217]
### Who
The Platform grant: https://gitcoin.co/grants/3116/the-platform

### What
We posted the Tweet on our Twitter account, but the 'Verify' doesn't appear to be able to see it?

### Why
So that the grant can show as being verified!

**Comment by SLRead** [comment]
Here is a link to the tweet: https://twitter.com/the_platf0rm/status/1409566956001374214?s=20

**Comment by thelostone-mc** [comment]
![image](https://user-images.githubusercontent.com/5358146/123960004-6f5f3b80-d9cc-11eb-8ec4-54b8213ffda3.png)
Looks like it's been verified
