### ISSUE TITLE
Request to reset Brightid uuid

### ISSUE THREAD

**Issue by ZeUs0666** [gitcoinco/web#9221]
Sir, 
I have getting error this context of is previously used by other user. 
Previously I have tried to connect my unverified Brightid with gitcoin, but due to lack of knowledge, now I am not able to recover that id

But now I have varified my Brightid and it won't connect to gitcoin and getting error of already used context id please help me, by any other ways you can.
![Screenshot_20210628-012446](https://user-images.githubusercontent.com/79089220/123783627-30f64d80-d8f4-11eb-886e-73f12243dd6b.png)

**Comment by blockchaindude108** [comment]
got the same problem. a steward said i shoud contact an admin to delete the entry in the database on gitcoin. before gitcoin said, ask bright id, bright id said, ask gitcoin. please, can any admin delete my entry in the db? especially before the grantround is done? btw. love these project. its amazing.

**Comment by hanyusheng** [comment]
I got the same issue also, please help.
