### ISSUE TITLE
Provide more information in grant report endpoint

### ISSUE THREAD

**Issue by yabirgb** [gitcoinco/web#9222]
### User Story

As a user who wants a report of donations to report gains in taxes it's needed to verify the transaction

### Why Is this Needed

In the contributions report #8883 some information is provided but only related to amounts and dates. To make it possible the verification of this transactions we need at least the transaction hash and zksync hash. Also the status of the transaction (if it failed or not) depending if failed transactions are included

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

### Current Behavior
This information is not provided

### Expected Behavior
Information to verify the transaction should be provided for each donation

### Definition of Done
The API returns the current fields + at least the transaction hash or zksync hash

### Data Requirements
A request to the API should return this information

### Additional Information

This can be done as in here https://github.com/gitcoinco/web/blob/201dc8a631b9de96b78a0a84ce1773dc84ced825/app/grants/models.py#L1682 this information is provided and is consumed by this serializer https://github.com/gitcoinco/web/blob/40ca8952a0c56545df6c2cb59737a8520e61ad05/app/grants/serializers.py#L57 at the moment of generating the report

**Comment by thelostone-mc** [comment]
This has been deployed !
