### ISSUE TITLE
I want to design a NFT project, looking for a partner.

### ISSUE THREAD

**Issue by sebimale** [gitcoinco/web#9241]
I want to develop a user free personal NFT project, I need to find partners, my English is not very good, I did not understand technology, but I have a special ability of innovation and market planning. We can start to discuss how to design the NFT, understanding and familiar with each other, in order to establish long-term close relations of cooperation. 
我想开发一个供用户自由发布个人NFT的项目，我需要寻找合作者，我的英文不太好，技术也不懂，但我有非凡的创意和市场策划能力。 我们可以先一起探讨怎么设计这个nft开始，相互认识和熟悉，以便建立长久的密切的合作关系。

**Comment by thelostone-mc** [comment]
I'd say dropping this on https://discord.com/invite/gitcoin might be a good place to start!
