### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by yoammontes** [gitcoinco/web#9252]
I can't claim to connect my trus wallet to claim a prize, I use safari browser, can anyone help me?

**Comment by que1414** [comment]
> Tôi không thể kết nối ví trus của mình để nhận giải thưởng, tôi sử dụng trình duyệt safari, có ai có thể giúp tôi được không?

**Comment by yoammontes** [comment]
I could not either, but finally I got it, in the above address you must put who you rule the prize, and in the second you must put yours, I'm still waiting to receive my award.

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: que1414 ***@***.***>
Enviado: Saturday, July 3, 2021 6:48:43 PM
Para: gitcoinco/web ***@***.***>
Cc: yoammontes ***@***.***>; Author ***@***.***>
Asunto: Re: [gitcoinco/web] Problem (#9252)


Tôi không thể kết nối ví trus của mình để nhận giải thưởng, tôi sử dụng trình duyệt safari, có ai có thể giúp tôi được không?
