### ISSUE TITLE
Provide grant start date in grant API

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#9253]
As a follow up to https://github.com/gitcoinco/web/issues/9222 I think it would be really great if there was a way for an api consumer to get the start date of a grant.

The reason for this is that otherwise you are forcing the consumer to make many unnecessary calls to your servers since you limit the api calls to a period of 31 days. I don't understand why do this, since you already include pagination.

With the current way the api endpoint is implemented an api consumer like rotki is forced to start from the `GITCOIN_FOUNDING_DATE` for each grant query, and start querying forward in time making one api call for every 31 days until it reaches today, in order to get all data. I think this is not a very good design as it forces the consumer to make too many unecessary calls to your server which is not something you want.

You already have a pagination system in place and in combination with a sensible (not too strict please) rate limiting and a back-off mechanism it should be enough.

Anyway if you insist on keeping this mechanism I would like to ask two things:

1. What value should go to `GITCOIN_FOUNDING_DATE`? When was gitcoin grants started? When was the first grant created?
    In our test code we got something probably way too early.
    
    ```python
    GITCOIN_START_TS = 1506297600  # 25/09/2017 -- date of first blog post. Too early probably
    ```

2. For each grant in the metadata response also add the grant creation date. This way with your current system the api consumer can do the first query in a random date, get the start date, and then start querying from there. It's not nice, not elegant but would help with reducing queries to gitcoin server.

**Comment by thelostone-mc** [comment]
For now we'd like to keep it way it works and we can remove the date param after internally discussing it.
What I've done is added created_on to metadata  to help tell you when it was created.
![image](https://user-images.githubusercontent.com/5358146/124493289-13812200-ddd3-11eb-87d8-777b6c38a95e.png)

This was on my local btw

**Comment by LefterisJP** [comment]
I see.

The created_on will definitely help us with making a lot less queries to your servers. As we can know the start of each grant.
