### ISSUE TITLE
Gitcoin grants contribution API, return event assets by address of the token

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#9266]
When using the gitcoin API, the assets per event are shown by symbol. Example.

```
 {'asset': 'aDAI', 'timestamp': '2020-03-26T16:16:56.795760Z', 'amount': '1900000000000000000', 'usd_value': None, 'tx_hash': '0
x1930a92ccef9c4a957521e1bdcece79dd1c75d34cfa296b4bef2a83a5c59447c'}
```

It would be really beneficial if the asset can be more accurately specified by the address of the token. Because for example there is multiple `aDAI`, multiple `PAN` tokens etc.

**Comment by thelostone-mc** [comment]
makes sense sending this information!  Internally tracking this at GITC-191

https://github.com/gitcoinco/web/issues/9266

**Comment by thelostone-mc** [comment]
https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=149&from_timestamp=2020-09-04&to_timestamp=2020-09-08&format=json

Also returns token_address now ^_^
