### ISSUE TITLE
Gitcoin grant contribution api, some transaction ids point to approval and not donation

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#9271]
Using this endpoint:

https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=149&from_timestamp=2020-09-04&to_timestamp=2020-09-08&format=json

we get the following transaction:

```
{"asset":"DAI","timestamp":"2020-09-04T12:03:49.720013Z","amount":"47500000000000000000","usd_value":47.49999999999999,"tx_hash":"0x8337431e38f6f485aa3857cd4496b99239659ddd78810ed21ca2dc6817fb4add"}
```

The tx_hash that is linked to it is that of an approval by a user and not of an actual donation: https://etherscan.io/tx/0x8337431e38f6f485aa3857cd4496b99239659ddd78810ed21ca2dc6817fb4add

**Comment by thelostone-mc** [comment]
Yup thanks for pointing this out !

This should fix that up:
https://github.com/gitcoinco/web/pull/9269/commits/f71eb448439c965b21241efba87d5363c393b1b5
