### ISSUE TITLE
Gitcoin grant contributions api returns 0x0 tx hash, 0 amount and everything else transaction

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#9280]
This call

https://gitcoin.co/api/v0.1/grants/contributions_rec_report/?id=490&from_timestamp=2021-01-28&to_timestamp=2021-02-24&page=1&format=json

contains this entry
```
{"asset":"ETH","timestamp":"2021-02-19T12:54:01.022804Z","amount":"0","usd_value":0.0,"tx_hash":"0x0","token_address":"0x0"}
```

which is most probably some kind of bug. Also I thought that token address was supposed to be `0x0000000000000000000000000000000000000000` for ETH and not `0x0`.

**Comment by Kweiss** [comment]
Closing this, let me know if we should reopen :)

**Comment by LefterisJP** [comment]
@Kweiss Why are you closing this? What has been done to solve this?

The issue is still there. You just need to click the link to perform the API call to confirm that.

This and a lot of other issues are still open and are blocking us and anyone who is trying to use rotki and the gitcoin API from actually calculating income gained from grants for tax purposes.
 
 I have talked with @thelostone-mc about all of them extensiviely via discord and asked for prioritisation of these issues. He said you guys are all busy.
 
I don't know what else to do guys. These issues with the API they all need to be solved. They are **really important** to us and all other gitcoin API users. Without them there is no good way to calculate income from a grant in a given period and as such can't make a proper tax report.

**Comment by LefterisJP** [comment]
Adding insult to injury the api got worse today as you started rounding amounts again which creates an accumulated error in the hundreds of dollars for big grants: https://github.com/rotki/rotki/issues/3434
