### ISSUE TITLE
Can not pay for a list cart which has only one grant in it

### ISSUE THREAD

**Issue by JinNguyen96** [gitcoinco/web#9303]
**Describe the bug**
I can not see the grant I picked in the card list and can not integrate with the wallet to pay, if the list has more than one, then I can start my payment, but I only want to donate for one grant

**To Reproduce**
select a random grant, only one, and go to check you cart

**Expected behavior**
seeing the grant and being able to pay

**Screenshots**
![image](https://user-images.githubusercontent.com/43945984/126144795-bc713f47-05da-4d4b-b5bc-254177054358.png)

**Desktop (please complete the following information):**

- OS: MacOS Big Sur 11.3
- Browser: Chrome
- Browser Version: Version 91.0.4472.114

**Additional context**
I believe this is just a frontend logic

**Comment by thelostone-mc** [comment]
I'd say clear your local storage + cache and do a hard reload and it should work

![image](https://user-images.githubusercontent.com/5358146/127809880-c01c9264-b6e2-46ee-89f5-9961a4e163b9.png)
