### ISSUE TITLE
Bounty Payment stuck at "Pending Verification"

### ISSUE THREAD

**Issue by bernardoaraujor** [gitcoinco/web#9318]
**Describe the bug**
I paid out a bounty but the payment got stuck for a few days:
https://etherscan.io/tx/0x07a7053017992250323d1bd31ff94efadf59d40d7771d1e1db26e07c9bf90b89

I did the "speed up" function on MetaMask and then it got through:
https://etherscan.io/tx/0x90a60eec192aa4f07af2741deb7fb23a7a6d0e090d2f7a0fb78ec14e32ccb8e4

The bounty payment remains as "Pending Verification":
https://gitcoin.co/issue/NFTletter/letter/1/100026089

**To Reproduce**

Check https://gitcoin.co/issue/NFTletter/letter/1/100026089

**Expected behavior**

I'd expect the Bounty payment status to resolve.

**Screenshots**

![](https://i.imgur.com/QBjvhtr.png)

**Desktop (please complete the following information):**

- OS: Debian 10
- Browser: Mozilla Firefox 
- Browser Version: 78.8.0

**Comment by thelostone-mc** [comment]
I've updated the txn ID! The checks should run through and it should show fulfilled in a bit

**Comment by thelostone-mc** [comment]
It's updated !
