### ISSUE TITLE
Request form walletconnect error

### ISSUE THREAD

**Issue by Bayramalikaplan** [gitcoinco/web#9343]
the address part in the form cannot be filled in despite connecting to the site via walletconnect on the money request screen.

![Screenshot_2021-08-06-23-12-32-567_com android chrome](https://user-images.githubusercontent.com/88409193/128567221-6214c4e5-7f32-440e-8e6a-ec72e1637493.jpg)

**Comment by thelostone-mc** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 3 months from now.
Please review their action plans below:


**1) [shitzu-mc](http://localhost:8000/shitzu-mc) has started work.**

Provide an action plan and any initial questions you have for this ticket.  Provide an action plan and any initial questions you have for this ticket.  Provide an action plan and any initial questions you have for this ticket.

Learn more [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/9343/100023791).

**Comment by thelostone-mc** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 0.001 ETH  has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/9343/100023791)
* Want to chip in? Add your own contribution [here](http://localhost:8000/issue/gitcoinco/web/9343/100023791).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $755,622.38 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by Bayramalikaplan** [comment]
When I tried again 1 day after writing to you, the problem was fixed, thank
you

11 Ağu 2021 Çar 16:39 tarihinde Aditya Anand M C ***@***.***>
şunu yazdı:
