### ISSUE TITLE
Trust Verification Via SMS Not Working

### ISSUE THREAD

**Issue by stackaccount1** [gitcoinco/web#9344]
**Describe the bug**
Trust verification at https://gitcoin.co/profile/trust the send verification code button was not working for me

**To Reproduce**
go to https://gitcoin.co/profile/trust
click SMS verify
enter phone number
click send verification code

**Expected behavior**
no code sent or execution of code sent on page notification

**Screenshots**
![verifywith](https://user-images.githubusercontent.com/61128114/128654443-376dd6e3-a53d-4cdd-bc88-9f8b2612c5e8.png)

**Comment by Kweiss** [comment]
I believe we got this fixed. Let us know if you have any issues :)
