### ISSUE TITLE
Unable to verify Twitter of cryptodrinks247

### ISSUE THREAD

**Issue by benjaminchodroff** [gitcoinco/web#9352]
**Describe the bug**
Attempting to verify Twitter cryptodrinks247 for grant https://gitcoin.co/grants/3350/crypto-drinks-community is failing 

**To Reproduce**
Click grant
Click verify
Sorry, we couldn't get the last tweet from @cryptodrinks247

**Expected behavior**
Either show more time is necessary or verify it 

**Screenshots**
![image](https://user-images.githubusercontent.com/4411206/129426089-47648e17-61d6-41c7-b0a9-2c74044bbb8c.png)

**Smartphone (please complete the following information):**

- Device: Apple 12 max pro
- OS: iOS latest 
- Browser: safari
- Version: latest 

**Additional context**

**Comment by Kweiss** [comment]
Looks like you got verified.
