### ISSUE TITLE
How to apply for a grant?

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#9355]
I want to resurrect https://github.com/Praqma/docker-linkchecker for checking links in CI. How to know if there is anybody interested in sponsoring this activity?

**Comment by Kweiss** [comment]
You can make a Grant here and advertise to your community.
https://gitcoin.co/grants/new

**Comment by abitrolly** [comment]
@Kweiss what do you mean? Usually you apply for a grant, and the grant is created by the party with money https://ec.europa.eu/international-partnerships/grants_en
