### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by DSBUGAY2** [gitcoinco/web#9364]
### Who
Grant https://gitcoin.co/grants/3357/buidltxn
Tweet https://twitter.com/buidltxn/status/1427377523705458689?s=20

### What
Receiving an error on verification `Sorry, we couldn't get the last tweet from @buidltxn`

### Why?

__Originally posted by @aquiladev in https://github.com/gitcoinco/web/issues/9363__

**Comment by Kweiss** [comment]
This looks to be resolved.
