### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by andogro** [gitcoinco/web#9366]
### Who

Grant https://gitcoin.co/grants/3364/blockscout
Tweet https://twitter.com/blockscoutcom/status/1427671538459938821

### What

Receiving an error on twitter verification

**Comment by ulyanas** [comment]
Upd. Issue still persists. Grant is not verified 
Ulyana S., Blockscout PM

**Comment by Kweiss** [comment]
This has been verified, thanks for pinging us 🙏
