### ISSUE TITLE
How much does Bounty Cancel cost?

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#937]
![image](https://user-images.githubusercontent.com/8781107/39099382-f7b25f3e-4682-11e8-8871-c133d69e9d08.png)

### User Story

As a funder, I want to check how much bounty cancel costs, so that I can ensure that I have sufficient funds to do it.

### Solution

*Summary*: Show total cost in ETH (maybe with USD recalculation) and my current balance.

**Comment by owocki** [comment]
would could maybe round to an extra few digits on the [metamask gas preview module](http://bits.owocki.com/1r0B3U3L0b2j/Screen%20Shot%202018-04-23%20at%203.02.34%20PM.png)

**Comment by kuhnchris** [comment]
Is this still relevant? I think it's pretty easy to see the "real" value on MetaMask.
