### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by JeremiahKamama** [gitcoinco/web#9370]
**Who**

Grant: https://gitcoin.co/grants/3363/kamama-a-blog-about-crypto
Tweet: https://twitter.com/JeremiahKamama/status/1427908451854848003

**What**

Receiving an error on twitter verification

 Why

**Comment by DSBUGAY2** [comment]
- [ ]

**Comment by Kweiss** [comment]
This has been verified, thanks for pining us :)
