### ISSUE TITLE
Cannot claim matching for my grant.

### ISSUE THREAD

**Issue by porobov** [gitcoinco/web#9375]
**Describe the bug**
- Got the letter "ACTION REQUIRED - Your Grants Round 10 Distribution of 2282.8 DAI"
- Followed the instructions in the letter ([my grant page](https://gitcoin.co/grants/281/upala-price-of-forgery-digital-identity-panvala-l)).
- Couldn't find the Claim Match button.

**To Reproduce**
- Go to your grant page
- Login with the wallet specified as the Ethereum Payout Address (in profile settings) or with the address that shows up on the grant page.
- Try to find Claim Match button. There's none! 

**Expected behavior**
- A pressable Claim Match button appears after login and the Match can be claimed.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.5 LTS
- Browser: Brave
- Browser Version: Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)

**Additional context**
I remember seeing this button a couple of weeks ago. Probably I even clicked on it but rejected the transaction. 

[Ethereum Payout Address](https://etherscan.io/address/0x0230c6dd5db1d3f871386a3ce1a5a836b2590044) as specified in the profile settings.
[Grant page](https://gitcoin.co/grants/281/upala-price-of-forgery-digital-identity-panvala-l)

**Comment by porobov** [comment]
Managed to withdraw directly from the GR10 Matching contract using Etherscan - https://etherscan.io/address/0x3ebaffe01513164e638480404c651e885cca0aa4

"Read contract" first to see which address is qualified - https://etherscan.io/readContract?m=normal&a=0x3ebaffe01513164e638480404c651e885cca0aa4&v=0x3ebaffe01513164e638480404c651e885cca0aa4#readCollapse4

Then "Write contract" from the address and specifying the recipient - https://etherscan.io/writecontract/index.html?m=normal&v=21.1.2.0&a=0x3ebaffe01513164e638480404c651e885cca0aa4&n=mainnet&p=#collapse1

I guess there's some conflict between the grant recipient address and the grant owner address. Those are different in my case.

**Comment by nomebahi** [comment]
0x64cc7ed01fa6b6d3e587e9c89da04ddbebe07580

**Comment by Kweiss** [comment]
Glad to see you could claim these. Yes you are correct that when the two addresses do not match, we do not allow a user to claim. Interacting with the contract directly is a great solution here!
