### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by robin-rrt** [gitcoinco/web#9376]
### What
Verifying via twitter is not working. I uploaded the automated tweet on my profile but upon clicking verify, the Gitcoin grant page says that it cannot find the last tweet from my account. 
twitter: https://twitter.com/uncryptd/status/1428686523046662146?s=20
![image](https://user-images.githubusercontent.com/66296664/130229469-a8ff2286-e603-4400-8832-c21de2ccbae5.png)
### Why
Not sure why.

**Comment by Kweiss** [comment]
Got you verified. Thanks!
