### ISSUE TITLE
Add reason while killing bounties

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#938]
### User Story

As a funder, I want to notify people why I am killing bounty so that they won't hold grudge for me.

Current form doesn't provide such field.

**Comment by kuhnchris** [comment]
Are we sending a mail when the bounty is cancelled? I'll add this to the product idea board for now - may need a bigger definition.

For example:
How do we notify the participants? Do we send a mail? Do we offer them different bounties?

Thanks!
