### ISSUE TITLE
Ripped

### ISSUE THREAD

**Issue by Tranvanlap95** [gitcoinco/web#9384]
# ❤️ I'm using Gitcoin

If you (or your company) are using Gitcoin - please let us know. We'd love to hear from you!

If you would like to help Gitcoin - any of the following is greatly appreciated.

- [x] Give the repository a star ⭐️
- [x] Help out with issues
- [x] Review pull requests
- [ ] Blog about Gitcoin
- [x] Give talks
- [x] Do a bounty
- [x] Support us on [Gitcoin Grants](https://gitcoin.co/grants/86/gitcoin-sustainability-fund)

Thank you!
The Gitcoin team

**Comment by Tranvanlap95** [comment]
0xe4e834fc6808181668501E89a85F1cC40ad941d9

**Comment by Kweiss** [comment]
Thanks for the feedback <3
