### ISSUE TITLE
Reset my Bright ID UUID

### ISSUE THREAD

**Issue by Nemeswat** [gitcoinco/web#9387]
I accidentally pressed done in Brightid gitcoin verification, can I fix it,. i want to reconnect the QR code
Describe the bug

Reset my Bright ID UUID :

Screenshots
![Screenshot_2021-08-25-17-23-51-863_org brightid](https://user-images.githubusercontent.com/64239422/130828343-1e3a3857-1683-46cc-8f93-feea30f80870.jpg)

Smartphone (please complete the following information):

Device: Redmi Note 9 Pro
OS: Android 10, MIUI 11
Browser: Chrome
Version: 92.0.4515.159

**Comment by lthrift** [comment]
https://github.com/gitcoinco/web/issues/9247

**Comment by lthrift** [comment]
If you’re still having this issue please contact support@gitcoin.co
