### ISSUE TITLE
Duplicate entries for the same bounty on my profile

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#939]
This is a continuation of bogus https://github.com/gitcoinco/web/issues/366

![image](https://user-images.githubusercontent.com/8781107/39099919-b890b7ee-468a-11e8-8661-890fae3f84c2.png)

Both of these bounties on my [profile page](https://gitcoin.co/profile/abitrolly) lead to the same page, but they have different titles and one says `killed` and another `submitted`.

**Comment by owocki** [comment]
i can't seem to repro but i did put in a fix that might help ( https://github.com/gitcoinco/web/commit/1e17e9580e3b780c86550b9efc9dec59bd579633 ) -- mind trying now?

**Comment by abitrolly** [comment]
Yes, looks better. What is the difference between cancelled and killed?

**Comment by kuhnchris** [comment]
This seems to be fixed - if it still comes up let us know in a new ticket - thanks!
