### ISSUE TITLE
small first bounty

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#940]
question thats on my mind as i do the data exploration here… is there a tipping point in an end users relationship with gitcoin that will keep them coming back?  we get so many people signing up for the mailing list, but only like 1% of them actually follow through with doing a bounty.  

facebook famously figured out that if they could get a user to have 20 friends on facebook, they’d keep coming back.  whats the equivilent focal point with gitcoin?  basically the question i’m asking is: how do we engineer the economics here so that members of the network don’t unsubscribe, ignore the important work in OSS we’re supporting, or otherwise go dark?

from @mbeylin : Something tells me the key metric is about getting new users to earn their first $20 (or something) doing a low hanging fruit bounty that they get enjoyment out of

**Comment by dolebas** [comment]
Daily sponsored ~0.01 eth (or fun-coin) try-it-out-bounties could perhaps trigger more interaction in general?

I think the network effect is also an important factor. The 20 friends hurdle can account for different random events with low probability, expected to take place over a certain period of time. Enabling crowdfunding as outlined in gitcoinco/web#1023 could possibly leverage existing network connections which are already strong in the open source community.
