### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by matiaszabal** [gitcoinco/web#9400]
### Who
https://gitcoin.co/grants/3337/boske-web3-learning-free-relevant-and-high-qualit

### What
cant verify with twitter

**Comment by Kweiss** [comment]
Got this verified 🙌

**Comment by matiaszabal** [comment]
thanks!
--
*Matías Zabaljáuregui*
https://ar.linkedin.com/in/zabaljauregui
