### ISSUE TITLE
Uniswap sub-category. 

### ISSUE THREAD

**Issue by Oluwacaleb** [gitcoinco/web#9405]
### Discussion

[comment]: # (What conversation would you like to facilitate?)
Please help me add the Uniswap sub-category/tag to my Grant.

**Comment by happiness4life** [comment]
Please help me add the Uniswap sub-category/tag to my Grant.

**Comment by Kweiss** [comment]
Thanks for the request - @Oluwacaleb and @happiness4life 

Can you please include a link to your grant so we know which grant to add this to?
