### ISSUE TITLE
I use gitcoin for new topics,ideas,a d and to earn 

### ISSUE THREAD

**Issue by kayloc88** [gitcoinco/web#9408]
# ❤️ I'm using Gitcoin

If you (or your company) are using Gitcoin - please let us know. We'd love to hear from you!

If you would like to help Gitcoin - any of the following is greatly appreciated.

- [x] Give the repository a star ⭐️
- [x] Help out with issues
- [ ] Review pull requests
- [x] Blog about Gitcoin
- [ ] Give talks
- [x] Do a bounty
- [x] Support us on [Gitcoin Grants](https://gitcoin.co/grants/86/gitcoin-sustainability-fund)

Thank you!
The Gitcoin team

**Comment by Kweiss** [comment]
Thanks for the feedback! <3
