### ISSUE TITLE
Grants sort 'Amount Raised (All time)' top results $0

### ISSUE THREAD

**Issue by zach-is-my-name** [gitcoinco/web#9427]
![Screenshot from 2021-09-03 13-45-10](https://user-images.githubusercontent.com/16063092/132046956-7651ecba-9ee1-4cff-a0e7-46f95fd79513.png)

**Comment by Kweiss** [comment]
Thanks, we are working to resolve this one. Appreciate you letting us know.

**Comment by zach-is-my-name** [comment]
Where can I track it if it's closed?
