### ISSUE TITLE
Issue explorer don't show issue in case gas price has been changed

### ISSUE THREAD

**Issue by 21xhipster** [gitcoinco/web#945]
This is [transaction](https://etherscan.io/tx/0x0e3319ed25c5f3d38af828a0338b3136151ce0b6962301f2d44672e54e340e96) proof

**Comment by owocki** [comment]
hey @21xhipster the system does a sweep of all actiev bounties in web3 every hour.  you'll see it show up within an hour :)

**Comment by 21xhipster** [comment]
Thanks :-)
