### ISSUE TITLE
changing payout address

### ISSUE THREAD

**Issue by ciciaran** [gitcoinco/web#9457]
### Who
I have a gitcoin grant that I'm updating. My account is ciciaran. The original grant was contributed to by myself and christina, with the account name aredehel. Christina has now left the project and I have two co-founders I'd like to do a grants round with.

### What
The payout address cannot be changed. We want to use a new, multisig address but we can't because there is no option to change the payout address.

### Why
Maybe it is a conscious decision, if so I can cancel my existing grant page and make a new one.

**Comment by gcc20** [comment]
you can submit a ticket @ https://support.gitcoin.co to have your payout address changed

**Comment by chibie** [comment]
you can submit a ticket @ https://support.gitcoin.co to have your payout address changed
