### ISSUE TITLE
Search doesn't work for certain projects

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#9460]
**Describe the bug**

It is hard to find "Cyber Academy" (https://gitcoin.co/grants/3169/cyber-academy) from https://gitcoin.co/grants/explorer/

**To Reproduce**

1. Go to https://gitcoin.co/grants/explorer/
2. Enter "cyber a"
3. Wait 5 seconds
4. Add "c" to make "cyber ac"
5. Wait 5 seconds
6. See no results

Or

1. Go to https://gitcoin.co/grants/explorer/?page=1&limit=6&me=false&sort_option=weighted_shuffle&network=mainnet&state=active&profile=false&sub_round_slug=false&collections_page=1&grant_regions=&grant_types=&grant_tags=&tenants=&idle=true&tab=grants&keyword=cyber+academy
2. Wait for Cyber Academy to appear
3. Erase "emy" from search string
4. Wait 5 seconds
5. Add "emy"
6. Wait 5 seconds
7. See no results

Also it is not in the list if you just type "academy".

![Screenshot 2021-09-09 at 11-55-16 (💰$900k Match LIVE ) Grants](https://user-images.githubusercontent.com/8781107/132661166-33ef7128-b02e-4cf4-838e-c1b1123cc227.png)

**Expected behavior**

1. (optional) Spinner that shows which phrase if being searched for
2. Find Cyber Academy page no matter how its name is typed
3. Have it in top results if the search string matches title

**Desktop (please complete the following information):**

- OS: Fedora 34
- Browser: Firefox
- Browser Version: 91.0.2

**Comment by octavioamu** [comment]
Thanks for the detailed report, there are 2 things here, one is our search index full words and the other is the search box is with a lazy property. 
For a quick fix I will change the lazy search to be just debounced, is not a full fix but at least will request the new query 100% of the times.

**Comment by abitrolly** [comment]
@chibie can we leave it open until it is fixed?
