### ISSUE TITLE
[Design] Funder Feature: Reach Out To Top Bounty Hunters 

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#947]
*Not ready to be worked on*

### User Story

As a Funder, I want to easily reach out to bounty hunters who may be interested in my issue so that I can generate interest on my repo. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Once I fund an issue, I would like to be presented with Gitcoin / Github profiles who might be able to solve my issue (based on tags, etc.). From there, I'd like to be able to click a button to e-mail them with a canned message of interest which I can modify slightly, if needed. 

### Additional Information
[comment]: # (Any other information that would be useful.)
Designing this feature is in-scope for this issue. Code will be considered only after the Design issue is completed. 

### Reviewers
@vs77bb @PixelantDesign

**Comment by owocki** [comment]
great minds think alike!   i just came up with this idea this weekend, i was going to call it 'Gitcoin Suggest'

**Comment by owocki** [comment]
one way i was thinking we could do this would to build the ability to filter leaderboard by keyword.  that way the funders can reach out to those who are already active bounty hunters

**Comment by vs77bb** [comment]
Interesting. I think that could make sense... it's also like AngelList's Top Talent model where they intro the top 1% of dev's to paying customers

**Comment by vs77bb** [comment]
@PixelantDesign This is a dup of #2200... although another feature to consider for v1.1 might be:

> Once I fund an issue, I would like to be presented with Gitcoin / Github profiles who might be able to solve my issue (based on tags, etc.)

Instead of you having to 'invite' yourself... there are some pre-populated people to invite (top bounty hunters, etc.). cc @willsputra for reference
