### ISSUE TITLE
Successfull Contributes ETH at Grants but using Smartchain RPC

### ISSUE THREAD

**Issue by onekill0503** [gitcoinco/web#9474]
**Describe the bug**

I yesterday thrust a few grants, when checkingout using standard checkout I forget that the RPC in Metamask is using an RPC SmartChain and I have confirmed the transaction, after that the Gitcoin website is a transaction that is not a transaction in ETH, the grants that I have contributed to The transaction is registered in my profile using ETH. But on the Gitcoin Bot of the Grants transaction is marked as a pending transaction. My screenshot is Taru at the bottom.

**To Reproduce**

After selecting the Grants in Gitcoin, I checked out using standard checkout, but forgot to replace the METAMASK RPC to the Ethereum network and accidentally depressed the transaction confirmation. After that the website records the transaction as a real transaction.

**Expected behavior**

My expectations after the transaction is confirmed, should fail because the transaction is noted not on the Ethereum network.

**Screenshots**

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/25810659/133062976-25ca1969-fd4d-478f-b676-b70547aa0433.png)
![image](https://user-images.githubusercontent.com/25810659/133064444-6e365d13-5240-4d75-b1ea-449054b72ac6.png)

- OS: Windows 10
- Browser: Brave Browser
- Browser Version: Version 1.29.79 Chromium: 93.0.4577.63

**Comment by chibie** [comment]
@onekill0503 i've been unable to reproduce this error.

here's what i did

* added a grant to cart
* ensured metamask is on smartchain rpc
* clicked "standard checkout"

the confirmation request didn't pop but rather it errored out.

am i missing something here?

**Comment by onekill0503** [comment]
> @onekill0503 i've been unable to reproduce this error.
> 
> here's what i did
> 
> * added a grant to cart
> * ensured metamask is on smartchain rpc
> * clicked "standard checkout"
> 
> the confirmation request didn't pop but rather it errored out.
> 
> am i missing something here?

sorry if my explanation is convoluted. 
The confirmation request is pop up, and i click confirm on metamask confirmation request and i forget if my metamask using smartchain rpc. After that,  not an error that appears but instead the message "contribution grants success". I'm confused because I use rpc smartchain but contribute using ETH. like the picture above that unreasonable contributions are actually recorded in the system and the gitcoin bot marks the transaction as "pending"
