### ISSUE TITLE
Twitter verification bug

### ISSUE THREAD

**Issue by eornzhdls** [gitcoinco/web#9487]
![화면 캡처 2021-09-15 192716](https://user-images.githubusercontent.com/88010685/133419365-83f9d802-2185-4eb0-9f20-9102524d6e1b.png)
![화면 캡처 2021-09-15 193132](https://user-images.githubusercontent.com/88010685/133419371-5dd57109-bea2-4941-b24e-8d157060f88c.png)

Before payment, Twitter verification was definitely completed and reached 150%, but after payment, the verification disappeared.

**Comment by lthrift** [comment]
If you’re still having this issue, please contact support@gitcoin.co
