### ISSUE TITLE
Please reset my BrightID verify

### ISSUE THREAD

**Issue by Samjii** [gitcoinco/web#9498]
**Describe the bug**
BrightID verify display used by another user before.I didn't have a certified BrightID to work with before.Please reset BrightID verify.thank you.
![20210920155019](https://user-images.githubusercontent.com/30919626/133971030-ce6867c7-bfce-4a0d-b575-3001d9184dad.jpg)

**Comment by chibie** [comment]
hey, kindly submit a ticket at https://support.gitcoin.co
