### ISSUE TITLE
Reset/cancel validation my Brightid

### ISSUE THREAD

**Issue by deva1999** [gitcoinco/web#9500]
### Why
Please help me to cancel validation my Brightid

**Comment by thelostone-mc** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (0.36 USD @ $362.6/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/9500/100023793).
* Want to chip in? Add your own contribution [here](http://localhost:8000/issue/gitcoinco/web/9500/100023793).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $755,622.38 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by thelostone-mc** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [shitzu-mc](http://localhost:8000/shitzu-mc) has applied to start work _(Funders only: [approve worker](http://localhost:8000/issue/gitcoinco/web/9500/100023793?mutate_worker_action=approve&worker=shitzu-mc) | [reject worker](http://localhost:8000/issue/gitcoinco/web/9500/100023793?mutate_worker_action=reject&worker=shitzu-mc))_.**

Provide an action plan and any initial questions you have for this ticket.  Provide an action plan and any initial questions you have for this ticket.

Learn more [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/9500/100023793).

**Comment by thelostone-mc** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 0.001 ETH  has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/9500/100023793)
* Want to chip in? Add your own contribution [here](http://localhost:8000/issue/gitcoinco/web/9500/100023793).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $755,622.38 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by deva1999** [comment]
Please help me to cancel validation my Brightid
I made mistake

**Comment by lthrift** [comment]
If you’re still having this issue, please contact support@gitcoin.co
