### ISSUE TITLE
Spelling error on website

### ISSUE THREAD

**Issue by Lollerlol** [gitcoinco/web#9510]
-->
### Who
On my profile, at "reliability: **medium**", when clicking the information button.
### What
When clicking on the information button, there is a spelling error. It says:
"For a good review**s**" instead of "For a good review"
### Why
This should be changed. I hope it helps you develop the website further, to make it look more professional.
My profile in Gitcoin is @lollerlol, my eth address is: 0x94f15A1393DA1BC91d838EBBb87A3Ea6Ff9f9c18

**edit** uploaded screenshot
![Screenshot 2021-09-22 195842](https://user-images.githubusercontent.com/91019322/134397960-ac44a897-dcbe-4435-84a4-d3b69ff8129b.png)

**Comment by Kweiss** [comment]
Thanks! Just got this fixed in the code, will update and deploy soon
