### ISSUE TITLE
Grants website does not load comments, takes too long to load and other problems.

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#9512]
Since the start of GR11 I have have been unable to load comments, website it too slow to load (minutes or timeout), stuff jumping around and completely unable to comment.

Clicking on stuff some times takes me to the top of the page instead of expanding, trying to click on the chat box to comment does nothing, I get lots of Warning sign images etc.

Opened an issue as [instructed in Twitter](https://twitter.com/frankchen07/status/1440751314015715334)

https://user-images.githubusercontent.com/1658405/134405043-3c9a1213-8e67-4750-ad79-8a2fd7077036.mp4

**Comment by frankchen07** [comment]
Thank you @LefterisJP - I've collated this ticket along with additional Twitter feedback into our internal JIRA as well, and will be talking to our engineering team to see what we can do immediately in the next sprint.

**Comment by LefterisJP** [comment]
It seems to depend on time. For example in Europe mornings (07:45 UTC), when I actually wanna do a round of comments/thanks on our contributors it's the worst.

The comments right now won't even load no matter how much time I wait.


https://user-images.githubusercontent.com/1658405/134471224-32ae78f2-38b9-4d28-939d-6b0cc013240d.mp4

**Comment by thelostone-mc** [comment]
This should be resolved now ! We had a few issues with our servers which was what causing the failures / delay to happen

**Comment by LefterisJP** [comment]
> This should be resolved now ! We had a few issues with our servers which was what causing the failures / delay to happen We've got a few changes in place to ensure this doesn't happen again
> 
> Thanks for the report @LefterisJP

Hehe yeah after the round ends the problem goes away. This problem was not new. Had it in a lesser extent in previous round too.

I will hold you to this for the next round.
