### ISSUE TITLE
make gitcoinbot status indicator into an image

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#952]
change 

![screen_shot_2018-04-23_at_5 15 30_pm](https://user-images.githubusercontent.com/513929/39160786-9a0e9840-472a-11e8-83d6-7413a3b9619b.png)
per  this image
<img width="611" alt="39156027-bb5891ae-4711-11e8-9856-8665e30213c0" src="https://user-images.githubusercontent.com/513929/39160793-9f66a5b2-472a-11e8-8ec6-2366c0c2964c.png">

makes it cleaner to see

followup to https://github.com/gitcoinco/web/pull/948

**Comment by owocki** [comment]
at the top of gitcoinbot comments (like in the above screenshot)

**Comment by PixelantDesign** [comment]
It's a little confusing that we're introduced another set of terms/flows into the mix. Specifically "You" and "Recipient" seem unclear  (looking at it from a funder's standpoint).

![Screen Shot 2018-04-23 at 9.41.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a83295aa5cc6700136b4bc8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a371f1162a4f5e585ecc3c4a4356bcbbd671f3e57862804e0ebcd73c5c22953910afb9864aee01ba24df4fd4b0e9821ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44fe44e51a5103062e6702431.png)

This doesn't match 100% either but follows the paradigm we've set up in the system.
Issue Funded > Open: Work Available  > Started: Work Begun > Submitted: Work In Review Done: Funds Paid

**Comment by thelostone-mc** [comment]
The terms used are confusing. I agree with @PixelantDesign on that 

Also the graphics would be a lot cleaner if it did not have the color transition. It should be either green/ blue / solid color when completed and the rest should be grey / dull solid color

**Comment by owocki** [comment]
i dont see where the terms 'you' and 'recipient' are being introduced?  on second glance, the first image in the issue desc was just meant to show the design (and compactness) of such an image, was not meant to be taken as new copy for our explorer.  sorry for not making that clear in the original ticket.

> Issue Funded > Open: Work Available > Started: Work Begun > Submitted: Work In Review, Done: Funds Paid

i can update the text in the latest PR to match this if you'd like 

https://github.com/gitcoinco/web/pull/948

**Comment by PixelantDesign** [comment]
@owocki Yes, the top image is what was confusing to me. Sounds good.

What happens in the cases where a person drops off, another person joins, or the issue is cancelled?

**Comment by owocki** [comment]
> What happens in the cases where a person drops off, another person joins, or the issue is cancelled?

i was thikning that the boldness would just switch back and forth from "Started" and "Open.  I dont see a need to overly complicate the UX by doing something like

> Open Started Open Started Open Started Open Started Open **Started** Submitted Done

Do you?

**Comment by collinvine** [comment]
Sorry, probably my bad with the image confusion. That was actually a screenshot from the Transferwise payment flow, intended to be used as an example of how a visualization of the state of the workflow could be more helpful than simply copy and formatting.

**Comment by PixelantDesign** [comment]
@owocki I agree sinple is best.
