### ISSUE TITLE
About the 11th round of donations

### ISSUE THREAD

**Issue by wakywu86** [gitcoinco/web#9522]
Hello administrator:
I participated in the 11th round of donation activities, but now there is no record of the donation on the website, and I have not received an email to complete the donation.
I filled in the link to the appeal, but it did not solve the problem. I didn’t find my wallet address in the published list of a project I donated this morning, so I was more worried.
Hope to help me check my donation record and solve the problem, thanks!
My wallet address is **0x21BC65637Dd6e7b171F2F78a1845F9807BbE3148**，and i use zKSync to pay.

**Comment by gududefengzhong** [comment]
I have the same problem

**Comment by Kweiss** [comment]
Hey there - can you add the contribution using this form?
https://gitcoin.co/grants/add-missing-contributions

**Comment by wakywu86** [comment]
I have add the contribution using this form,but it did not solve the problem.

**Comment by wakywu86** [comment]
> Hey there - can you add the contribution using this form?
> https://gitcoin.co/grants/add-missing-contributions



> Hey there - can you add the contribution using this form?
> https://gitcoin.co/grants/add-missing-contributions

I have add the contribution using this form,but it did not solve the problem.
