### ISSUE TITLE
Switch Grant Address

### ISSUE THREAD

**Issue by amsos** [gitcoinco/web#9595]
### Who:  
For this grant - https://gitcoin.co/grants/365/govrn

### What:  
Change the recipient address to: 0xB8E52105A4B58943714dFfBf79F8aeE24B9f8D40

### Why:  
From this address: 0x58f123BD4261EA25955B362Be57D89F4B6E7110a

**Comment by lthrift** [comment]
If you would still like to make this change, please contact support@gitcoin.co
