### ISSUE TITLE
Jobs v2 - Experiment with charging for a job board premium placement

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#960]
https://github.com/gitcoinco/web/issues/958

this is a spec for a 'premium' job post for the above issue.  

not ready to be worked on yet

**Comment by owocki** [comment]
i think that codefund is working on this.. so it might subsume gitcoins work here

**Comment by kuhnchris** [comment]
I assume this is what we now have with the User Directory - maybe this is a premium within that? Like the "premium bounties"?
