### ISSUE TITLE
Requesting change on grant's beneficiary address

### ISSUE THREAD

**Issue by EibrielInv** [gitcoinco/web#9604]
### Who
Hi! I'm the creator of this grant: https://gitcoin.co/grants/1511/soappunk-universe

### What
I would like to change the beneficiary address from `0x05C351382dB8D770207F319D96ac1184c3717edE` to `0xCF10CD8B5Dc2323B1eb6de6164647756BAd4dE4d`

### Why
The current address is not properly secured, and I could loose control of it at any time

Thanks!

**Comment by chibie** [comment]
hey! please submit a ticket at https://support.gitcoin.co
