### ISSUE TITLE
Supporting members of Gitcoin

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#961]
(not ready to be worked on yet)

idea: support gitcoin monthly with a subscription:

https://github.com/ethereum/EIPs/issues/948

or via a dev grant

https://github.com/gitcoinco/web/issues/380

**Comment by thelostone-mc** [comment]
Aka Creating a grant for gitcoin ?

**Comment by kuhnchris** [comment]
We have selected grants for selected people in the community now.
