### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by joigno** [gitcoinco/web#9611]
### Who

Me, the grant Creator.

### What

I want to change my Ethereum address for the Grant to

0xB6873d28915059e32A78A4632B984dBA15513bB6

### Why

The current address is not compatible with zkSync. This one will be:

0xB6873d28915059e32A78A4632B984dBA15513bB6

**Comment by joigno** [comment]
Any updates @thelostone-mc  on this? This is the correct ETH address with zkSync, thanks!:

**0xB6873d28915059e32A78A4632B984dBA15513bB6**

**Comment by joigno** [comment]
@thelostone-mc @owocki @gdixon the incorrect addres is `0xD5508273E15310217cf795F5BB7758827C76014c`

the correct one is `0xB6873d28915059e32A78A4632B984dBA15513bB6`

Grant: https://gitcoin.co/grants/3737/hyperhyperspace-protocol-fund

**Comment by lthrift** [comment]
Hi @joigno if you’re still trying to change your address please contact support@gitcoin.co
