### ISSUE TITLE
Revenue Idea: add premium schwag to your avatar

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#962]
https://github.com/gitcoinco/web/issues/813

We could perhaps monetize the sale / exchange of premium schwag to an avatar in the future

(not ready for working on yet -- just a stub)

**Comment by owocki** [comment]
first step => https://github.com/gitcoinco/web/issues/2781

**Comment by kuhnchris** [comment]
This was already implemented - the "premium" avatar items. - Closing this one. :-)
