### ISSUE TITLE
Change the address to receive funding in Grants

### ISSUE THREAD

**Issue by nelruk** [gitcoinco/web#9658]
### What

I'm asking to change my address to receive fund in my grant.

The grant is https://gitcoin.co/grants/2491/la-hora-cripto-v2
The new address will be 0x794314b2A7Ed4B8336C7bB5EB66B5F78D5c50bc5

### Why

Change the address for several reasons, mostly convenience.

**Comment by Solexplorer** [comment]
Updated, issue can now be closed
