### ISSUE TITLE
Opening links on profile page in a new window

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#966]
I want to open links to my bounties in a new tab, so that I can check each one more easily.

![image](https://user-images.githubusercontent.com/8781107/39165256-42da4238-478c-11e8-9c71-dc43498390e9.png)

For some reason I can not open entries on https://gitcoin.co/profile/ in a new tab/window with keyboard shortcuts in Firefox - it only follows a link in current tab, and the right click menu is empty.

**Comment by thelostone-mc** [comment]
Ah it's probably Jquery click! 
We are getting that page redone. Should turn out in a few weeks
@abitrolly Should we wait it out  / throw in a fix ? 

Issue: https://github.com/gitcoinco/web/issues/920
New Design : https://github.com/gitcoinco/web/issues/656#issuecomment-380634796

**Comment by abitrolly** [comment]
@thelostone-mc if there is simple fix for that, then I'll be happy not to wait some weeks for new design.

**Comment by kuhnchris** [comment]
I think we re-created that page a couple of times now - so I'm closing this one - if the problem still shows up let us know in a new Issue - thanks!
