### ISSUE TITLE
Uniswap Tag

### ISSUE THREAD

**Issue by zatracking** [gitcoinco/web#9662]
# ❤️ I'm using Gitcoin
please add UNISWAP Tag to My Grant

If you (or your company) are using Gitcoin - please let us know. We'd love to hear from you!

If you would like to help Gitcoin - any of the following is greatly appreciated.

- [x] Give the repository a star ⭐️
- [x] Help out with issues
- [x] Review pull requests
- [x] Blog about Gitcoin
- [x] Give talks
- [x] Do a bounty
- [x] Support us on [Gitcoin Grants](https://gitcoin.co/grants/86/gitcoin-sustainability-fund)

Thank you!
The Gitcoin team

**Comment by thelostone-mc** [comment]
If you are the owner of the grant -> you should be able to set it yourself
