### ISSUE TITLE
Unable to Claim GR11 Matching

### ISSUE THREAD

**Issue by AlphaSerpentis** [gitcoinco/web#9666]
**Describe the bug**
Unable to find and click the supposed 'Claim' button on the grant page

**To Reproduce**
1) Signed into Gitcoin under the appropriate account
2) Log into the Ethereum account via MetaMask. Said account is a **Trezor**.
3) Check the grant page for a claim button (in which there won't be one)

**Expected behavior**
The ability to see this Claim button

**Desktop (please complete the following information):**

- OS: Windows 10 Home 21H1
- Browser: Brave 
- Browser Version: 1.31.88 64-bit

**Comment by mariorz** [comment]
I have the same issue. Gitcoin bot reports the CLR matching has been transferred but there is no "Claim" button when logged in with the correct account and wallet.

**Comment by PaigeEve** [comment]
The claim button isn't responding, please help

**Comment by thelostone-mc** [comment]
Could you share more info regarding which grant you're talking about here?
Ideally if you're logged into your wallet , it should show the claim 

- assuming the contract has funds allocated for the grant
- part of the team which owns the grant 


The other option would be to head over to etherscan and claim the funds from the contract directly https://etherscan.io/address/0x0EbD2E2130b73107d0C45fF2E16c93E7e2e10e3a#writeContract

![image](https://user-images.githubusercontent.com/5358146/143664820-735d02c4-7664-41b2-b2fe-c0cd03d17f93.png)

**Comment by mariorz** [comment]
Hi @thelostone-mc 
This is my grant https://gitcoin.co/grants/2983/revert
The claim button has not appeared for two rounds now, had to claim directly from etherscan both times (including this one). Please let me know if I can help with anything else to debug the issue. Thanks.

**Comment by AlphaSerpentis** [comment]
Latest claim seems to work for me
