### ISSUE TITLE
Unable to login with auto-generated username (GitHub OAuth)

### ISSUE THREAD

**Issue by paulmreese** [gitcoinco/web#9670]
**Describe the bug**

When I attempt to login to GitCoin, I receive an error "Unable to save your profile. Please login again." at the top of the screen. This accompanies the inability to access any profile-related pages(500 error), with the exception of logging out. I have contacted GitHub to verify that my OAuth credentials are valid. Additionally, I have cleared my cache, restarted and updated Chrome, and restarted my computer. Behind the scenes, it looks like a failed authentication is causing forbidden access. (I am editing this to add that the issue persists on mobile as well)

The one clue I think I'm finding is that my GitHub username (paulmreese) has a unique identifying string appended to it on Gitcoin:  paulmreese3347d4d8dacf4296 . Is the code perhaps assuming that my Gitcoin username will necessarily match my GitHub username?

**To Reproduce**

Any login attempt or visit to the site after login will generate the error message "Unable to save your profile. Please login again." Any click on a link under the "My Account" tab will lead to a 500 Error page(except logout).

**Expected behavior**

Successful login.

**Screenshots**

![Error500ScreenShot](https://user-images.githubusercontent.com/14267058/140944556-39917963-0122-4861-b376-3bb88165cc1b.png)
![500to401Error](https://user-images.githubusercontent.com/14267058/140945627-4526ce68-f720-4111-98c2-93271e20e8ce.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.6
- Browser: Chrome
- Browser Version: 95.0.4638.69 (Official Build) (x86_64)

**Additional context**
Have contacted support with the same issue. Nearly 2 weeks without a successful login

**Comment by the-kote** [comment]
Same problem! Версия 96.0.4664.45 (official), (64 bit)
code 500/405 https://gitcoin.co/api/v1/mautic_profile_save/
code 401 https://gitcoin.co/api/v0.1/profile/the-kote with content {"active": "error", "code": 404, "nav": "home", "title": "Error 404"}
