### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ilievski-david** [gitcoinco/web#9674]
**Describe the bug**

Few months ago i created a gitcoin account to explore the website, and since i didn't use it i deleted it as i usually do to non active accounts. This week i tried to login again with the same github account and the bug showed up. Every page shows error 500 and says to login again.

**To Reproduce**

- Sign in to gitcoin
- Delete the account by clicking "My account" -> "Settings" -> "Account" -> "Delete my account"
- Sign in again with the same github account
- Username gets scrambled from "ilievski-david" to "ilievski-david9ca4cc2083bc4678"
- Error 500 on every page

**Expected behaviour**

To be able to sign as a new account

**Screenshot:**

<img width="300" alt="Screenshot 2021-11-08 at 07 59 12" src="https://user-images.githubusercontent.com/59334044/140997093-49fe217e-e262-4da2-8527-b45ad63fa261.png">

**Desktop :**

- OS: macOS
- Browser: Chrome,Safari

**Smartphone (please complete the following information):**

- Device: Samsung S20
- OS: Android
- Browser: Chrome

**Additional context**

These don't work
- reset the browser cache shift+command+r 
- tried on a new unused browser
- revoking gitcoin access from github and signing in again

**Comment by gdixon** [comment]
Hey @ilievski-david,

Could you try again now please 👍

**Comment by ilievski-david** [comment]
yes it works now
