### ISSUE TITLE
Username changed on Github does not update on GitCoin

### ISSUE THREAD

**Issue by yolantis** [gitcoinco/web#9683]
Describe the bug
When changing my username on Github, my username on Gitcoin remains the same. I tried hard refresh. I tried restarting my laptop. I tried disconnecting my Github from GitCoin and re-connecting it.

To Reproduce
Sign up on Gitcoin with your Github account. Change your Github username.  https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/changing-your-github-username 

Expected behavior
The expectation is that the username on Gitcoin would update to match Github.
I would like my Gitcoin URL to be https://gitcoin.co/yolantis and username to be @yolantis

Desktop (please complete the following information):

OS: Mac Monterey
Browser: Chrome
Browser Version: Version 95.0.4638.69 (Official Build) (x86_64)
Additional context
When I signed up for Gitcoin, my Github username was @jessicasams. I have since changed my username on Github to @yolantis because this now matches my ETH domain.

Here is a link to my Github: https://github.com/yolantis
Here is a link to my Gitcoin (connected to my Github): https://gitcoin.co/jessicasams

I have tried revoking access and reconnecting my Github to Gitcoin. It is possible that Gitcoin was designed to lock usernames at creation? I tried looking for a way to delete my GitCoin account and re-make a new one, but couldn't find that either. Please clarify and thanks for the help.

**Comment by thelostone-mc** [comment]
It's been updated! Could you try logging in and checking ?

**Comment by yolantis** [comment]
Thank you, that worked and even my avatar and quest status is the same. Thanks. Now I have a match between URL and username. OK to close ticket.
