### ISSUE TITLE
1

### ISSUE THREAD

**Issue by SanguineHum** [gitcoinco/web#9684]
Hello. I made a transaction for donate to grant to "Rekt.news" and it was completed successfully, but the bot wrote in the comments below it that it failed. Can you check it? My money has already been sent. 

Hash: 0x2126c7a6e18ad50434a2d0b171f416f0ff7021679637e6f84efb7591365c5d4b

**Comment by Combot80** [comment]
Hello apology for the delay has your issues been resolved yet
