### ISSUE TITLE
Duplicate Accounts Due To Github Username Change

### ISSUE THREAD

**Issue by ethdaily** [gitcoinco/web#9691]
**Describe the bug**
There are duplicate Gitcoin accounts that have been created due to me changing my username on Github. Both duplicate Gitcoin accounts are linked to one Github (https://github.com/ethdaily), but I only have access to one Gitcoin account (https://gitcoin.co/inethereumpod). When I signed up for Gitcoin, my Github username was @inethereumpod. I recently changed my Github username to @ethdaily. When I sign into Gitcoin via my Github account (https://github.com/ethdaily), it takes me to https://gitcoin.co/inethereumpod instead of https://gitcoin.co/ethdaily.

The https://gitcoin.co/ethdaily account was automatically created when I changed my Github username. However, I am unable to access this account on Gitcoin. It is linked to https://github.com/ethdaily because it shows the same profile picture.

**To Reproduce**

1. Sign up for Gitcoin with Github
2. Change Github username
3. There are now to Gitcoin accounts linked to the same Github

**Expected behavior**
I expected for my Gitcoin account to simply update with the new username. However, there are now two accounts. One with the old username and one with the new username. Both are linked to one Github account.

**Desktop (please complete the following information):**

OS: Windows 10
Browser: Chrome
Browser Version: 95.0.4638.69

**Additional context**
I would like to have access to https://gitcoin.co/ethdaily and have data from https://gitcoin.co/inethereumpod transferred over or have the accounts merged into one.

**Comment by thelostone-mc** [comment]
Could you try clearing your cache and logging in once more ?

**Comment by ethdaily** [comment]
Awesome, account directs correctly now. Thanks for the prompt help!
