### ISSUE TITLE
Change the address to receive funding in Grants 

### ISSUE THREAD

**Issue by hollygrimm** [gitcoinco/web#9702]
I'd like to change wallet address for:
https://gitcoin.co/grants/2292/nfdao-panvala-league

The new address is:
0x09203487A637b28D8D5CfDFE0BCE8F7A815a8c48

Thank you!

**Comment by Combot80** [comment]
Hello apology for the delay has your issues been resolved yet

**Comment by luisblancoach** [comment]
All set

**Comment by hollygrimm** [comment]
Can you please update this ASAP? This wallet was compromised.

**Comment by hollygrimm** [comment]
contacted support via email and this was resolved
