### ISSUE TITLE
Duplicated account on Gitcoin - previously deleted

### ISSUE THREAD

**Issue by snowdot** [gitcoinco/web#9710]
**Describe the bug**

Deleted my Gitcoin account and created a new one and now I have multiple accounts under the same handle.
This creates a conflict that doesn't allow my current profile avatar to get updated.

**To Reproduce**
Delete Gitcoin account and create a new one.

**Expected behavior**
The old deleted Gitcoin account isn't actually deleted thus causing issues. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39951422/142740992-7cfb0bd4-eed4-4f06-afff-62d80f45e56e.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Google Chrome
- Browser Version: 95.0.4638.69 (Official Build) (64-bit)

**Comment by lthrift** [comment]
Hi @snowdot if you are still having this issue please contact support@gitcoin.co
