### ISSUE TITLE
as a repo owner, i want different bounty work schemes, so i can choose the right bounty type for the job

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#973]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a repo owner, i want different bounty work schemes, so i can choose the right bounty type for the job

`approval_scheme` could be one of
* `approved_workers_only`
* `any_workers`

`num_workers` could be 
* `1_workers`
* `2_workers`
* `n_submitters`

`bounty_type`
* `single` - only 1 worker
* `contest` - only 1 worker gets paid out of `n` who may start work
* `cooperative` -- all workers up to `n` from above get paid out

### Why Is this Needed?

theres too much confusion in the legacy flow about how many workers there can be at once

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

#### New Bounty Form.

Please add a section on the gitcoin.co/new form such that a new bounty funder can enter
* approval_scheme (default = any)
* num_workers (default = 1)
* bounty_type (default = single)

This information should be saved in IPFS upon submission, and then during `sync_geth` it should be loaded onto the `Bounty` object.

#### Bounty Details Page

Show the 'bounty_type' field on the bounty details page.  There should be some hover text explaining what it is.

Only allow up to `num_workers` to click 'start work' on an issue

If the `approval_scheme` is 'approved workers only' please modify the start work flow such that it includes a 'pending' `Interest` object, and the funder must be notified that they must approve the worker or not.  (a new UI is needed for 'approvals').

#### Gitcoinbot

Gitcoinbot's copy will need to be updated to reflect the approval_scheme and bounty_type

**Comment by owocki** [comment]
@danieljoonlee is interested in working on this

**Comment by danieljoonlee** [comment]
Work is in progress, if anyone wants to help / jump in let me know

**Comment by owocki** [comment]
great @danieljoonlee  -- hit us up with a WIP PR when you have a chance :)

**Comment by danieljoonlee** [comment]
heyo i haven't started on the issue yet.  planning on starting it tomorrow if you're not in a rush

**Comment by owocki** [comment]
no rush. its more important that its done well :0

**Comment by danieljoonlee** [comment]
@owocki hey sorry i think i need to pull off from this issue since i'm a blocker.  i've gotten a lot of requests for side gigs, so i'm pretty swamped right now

**Comment by owocki** [comment]
thanks for letting us know @danieljoonlee !

**Comment by owocki** [comment]
heres the UI i came up with for the ‘work scheme’ stuff http://bits.owocki.com/08421t3J3m10/Screen%20Recording%202018-05-07%20at%2004.54%20PM.gif

**Comment by PixelantDesign** [comment]
For approved workers - we should allow for approved by default but in two scenarios:
Passive Rejection and Intentional Rejection (48 hrs window).

Bc Open Source Project - Anyone can make a PR

Thoughts?

**Comment by owocki** [comment]
v1 is shipped

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.1 ETH (69.21 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/gitcoinco/web/973/658).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
