### ISSUE TITLE
Quest - User not prompted to claim rewards after the message announcing the user won the quest

### ISSUE THREAD

**Issue by Sifou13** [gitcoinco/web#9739]
**Describe the bug**
When winning a quest, a number of controls get rendered so that the user can take actions such as claiming the reward for this quest (Kudos NFTs), however this seems to not be for some of the quests, so it could be intermittent but I believe there is an "obvious" and logical explanation to this (non defined javascript variable referenced).

**To Reproduce**
Win a quest - However, while I can see the bug on the source code (JS), it seems that a roll back of some sort may have happened in the past couple of hours since it seems to be back on now.

**Expected behavior**
User should be able to complete the quest by claiming their reward and be provided with a number of options upon winning the Quest..

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Brave
- Browser Version: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

Upon debugging the js in the browser, there is a "span" variable, and its only intended usage seems to have a mis-typed $ in front, which breaks js since "$span" does not exist.

**Comment by Sifou13** [comment]
Closed, in line with Pull Request (see above)

**Comment by gdixon** [comment]
Thank you @Sifou13!!
