### ISSUE TITLE
to be defined - interoperability with https://kauri.io

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#974]
kauri is bounties for documentation.. theres probably an interoperability oppy there.

hopefully they build on standardbounties soon

**Comment by abitrolly** [comment]
https://kauri.io

**Comment by PixelantDesign** [comment]
Yesss!!! Agree

**Comment by kuhnchris** [comment]
Did anyone follow up on this? They seem to also have an ambassador program, so it may make sense to reach out to them to at least see if we can leverage some synergy.
