### ISSUE TITLE
fix sms trust verification

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#9747]
### Description

As a grant contributor who is gaining trust bonus by verifying by SMS, I want SMS verification options that work and are not broken. 

### Notes

We’ve been receiving a lot of tickets for “offline verification”, which is an option in the SMS verification process.

The reason that we’re receiving a lot of these tickets is because the normal “online” SMS authentication seems to be done. The users never receive a text.

Because “online” verification never sends them a text, and we don’t do “offline” verification, we need to make sure we either fix both, or remove both forms of verification.

Frank verifies that both online and offline SMS do not work (2021-10-15).

For the engineer that picks this up, please ping Frank Chen for twilio creds for investigation.

- twilio service doesn’t work well with chinese customers, we just get an exception (tough to handle)
- exhausted our bandwidth on twilio and have to pay more money
- mostly about increasing the plan on twilio

<img width="805" alt="Screenshot 2021-10-15 at 09 51 12" src="https://user-images.githubusercontent.com/7516920/143794343-b13457e2-ac35-4e95-ae3c-fd861475d4fc.png">

![Screenshot 2021-10-12 at 11 08 50](https://user-images.githubusercontent.com/7516920/143794348-71852b09-8050-467c-8300-03060ec22309.png)

**Comment by nfrgosselin** [comment]
@gdixon can we close this story given your fix? #9977 

cc: @thelostone-mc

**Comment by ksolo** [comment]
@nfrgosselin I think so. Chase needed to give the final ok on it.

**Comment by gdixon** [comment]
Ahhh - no - I linked to the wrong issue! I should have linked to #9742! My bad, sorry!

**Comment by nfrgosselin** [comment]
@gdixon just catching up on this — do you mean that this story should have been linked to #9742? If so, does that mean that this can be closed?

**Comment by nfrgosselin** [comment]
After chatting with @gdixon and @thelostone-mc, I'm closing this ticket. We know that there are a couple of issues with this integration, specifically for Chinese users, but will likely explore deprecating the SMS trust bonus instead of trying to troubleshoot this integration.
