### ISSUE TITLE
Add the polygon tag to this grant: Mintbot | Polygon NFT Minter

### ISSUE THREAD

**Issue by stevegachau** [gitcoinco/web#9775]
grant link: https://gitcoin.co/grants/2754/mintbot-polygon-nft-minter

**Comment by thelostone-mc** [comment]
I'd recommend heading over to discord and reaching out to support and they'd be able to help you out 🙌

**Comment by stevegachau** [comment]
I was following instructions posted here https://gitcoin.co/blog/polygon-creating-ecosystem-match-pool-for-gr12/
