### ISSUE TITLE
Global search bar does not find some grants

### ISSUE THREAD

**Issue by wmitsuda** [gitcoinco/web#9785]
I reported it on discord, replicating it here.

I can't find my own grant (https://gitcoin.co/grants/3224/otterscan) by searching using the top level search button:

<img width="195" alt="Screen Shot 2021-12-01 at 04 14 34" src="https://user-images.githubusercontent.com/28685/144189318-3a707928-ce01-43cc-b49b-f67c31d0597e.png">

<img width="588" alt="Screen Shot 2021-12-01 at 04 03 15" src="https://user-images.githubusercontent.com/28685/144189403-9ddfc60b-c42e-44c0-8b9b-31648275b572.png">

But I can find it by searching on the explorer grants page:

<img width="1223" alt="Screen Shot 2021-12-01 at 04 12 39" src="https://user-images.githubusercontent.com/28685/144189428-dc3f8662-56dd-4039-8e3a-74125fabd5d6.png">

This is very confusing and directly impacts grant reachability, since the only the global search is visible from any gitcoin.co page and it is certain the first place anyone will use to search for grants.

**Comment by frankchen07** [comment]
@thelostone-mc from a user perspective, I am concerned that this search bar is commonly mixed up with the search scope of the grants search bar. I would recommend that we address this so that mix-up doesn't occur, since that affects user discoverability of our grants.

cc @nfrgosselin

**Comment by wmitsuda** [comment]
> @thelostone-mc from a user perspective, I am concerned that this search bar is commonly mixed up with the search scope of the grants search bar. I would recommend that we address this so that mix-up doesn't occur, since that affects user discoverability of our grants.
> 
> cc @nfrgosselin

totally agree, I've been getting much less donations during GR12, I'm afraid this issue may be affecting it, users don't find my grant and give up!

I would suggest disabling the global search while this is not addressed so some grants don't have a "discoverability advantage" over others.

**Comment by frankchen07** [comment]
thanks for this feedback @wmitsuda! We've added these to the priorities of the internal team. Also be on the lookout as well - in the coming weeks we're looking to make more of what our internal team is doing more open to the public.

**Comment by wmitsuda** [comment]
hi, is anyone looking at this? We are ~1 month from GR13 and still not working!

**Comment by tjayrush** [comment]
@grankchen07 Just bumping this issue. I'm seeing this same behavior for other grants (not my own), but yes for Otterscan and one or two others. Can't remember which. You should make this a priority, though. It's not really fair.

**Comment by lthrift** [comment]
This issue has been fixed. If you have any other support issues in the future, please report via support@gitcoin.co or #create-a-ticket in discord so we can be sure to address it promptly.
