### ISSUE TITLE
Switch a Gitcoin grant from coinbase wallet to non-contract wallet

### ISSUE THREAD

**Issue by sbutler-gh** [gitcoinco/web#9793]
### Who

I'm Sam, and one of the team members for this grant:

https://gitcoin.co/grants/4061/a-game-for-coordination-solidarity-and-realizing-

### What

Can you update the wallet on this grant to the following address?

0x0EFD0B2daB774756c04671B5D909c07F4B61EFB8

### Why

The wallet for the grant is currently configured as a coinbase ETH wallet.  After interacting with Gitcoin team members, I understand that it's better to go with a non-contract general purpose wallet like Metamask than Coinbase.

**Comment by annikalewis** [comment]
Done
