### ISSUE TITLE
fix "could not pull back remote response" when inputting github issue url

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#9801]
### Description

When creating a bounty the error: "could not pull back remote response" appears now and again for funders when they input their github issue URL. 

Aditya comment in L2 thread: "that's cause we make a call to github API to fetch those details and sometimes that call fails (could be cause of network issue), might be worth having a refresh button to try to pull that again / just keep pulling until we have that data"

![bountyerror](https://user-images.githubusercontent.com/7516920/144339900-23be0e91-2ce2-4f5d-9c7e-e830b892f6de.png)

### Acceptance Criteria

a refresh button to try to pull that again / just keep pulling until we have that data

**Comment by bobjiang** [comment]
what's the plan to fix this issue?

I have the same issue. 

or do we have work around?

![image](https://user-images.githubusercontent.com/1224604/145409471-46a0f6d8-ff93-478f-b157-fe0df2c44397.png)
