### ISSUE TITLE
Grant ETH address replacement

### ISSUE THREAD

**Issue by aderidwan98** [gitcoinco/web#9822]
Hello this is aderidwan98 as a founder Little Things. 
I would like to ask if it is possible to change the grant ETH address, which where recently used for Gitcoin GR-11.

Little Things grant link: [](https://gitcoin.co/grants/3647/little-things-indonesian-crypto-community)
Old ETH address: 0xD5F048143AC7284B13A55C16A48288cDc251749B
New ETH address: 0x8B600c7Ef1D97225860a7996b63c5b8b116182d5

Thank you in advance!
-Liitle Things

**Comment by annikalewis** [comment]
Looks like this has been updated!

**Comment by gdixon** [comment]
Awesome, thanks @annikalewis!
