### ISSUE TITLE
Checkout issue (zksync and polygon)

### ISSUE THREAD

**Issue by defiyield** [gitcoinco/web#9823]
**Describe the bug**
After choosing a project and adding to the card I click "Checkout" and get the error message.
![image](https://user-images.githubusercontent.com/70277594/144591526-7c5e02c4-a663-462c-a583-0df1e27ef631.png)
After cleaning cashes I get this error.
![image](https://user-images.githubusercontent.com/70277594/144591637-7d358945-c7e6-4e85-a573-1b4757d9d435.png)
No further actions happen. 

**To Reproduce**
Clock "Add to card" and proceed to checkout.

**Expected behavior**
I should have a possibility to pay the contribution.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Browser Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by lthrift** [comment]
Hi @defiyield these errors are related to grants wallet addresses being incompatible with the selected L2. We’ve updated error messaging and the checkout experience to improve this
