### ISSUE TITLE
Change the address to receive funding in Grants?

### ISSUE THREAD

**Issue by leeduckgo** [gitcoinco/web#9831]
I'd like to change wallet address for:
https://gitcoin.co/grants/3891/web30-dapp-dev-camp

The new address is:
0x73c7448760517E3E6e416b2c130E3c6dB2026A1d

Thank you!

**Comment by leeduckgo** [comment]
> Sure - can you send us a DM to the Gitcoin account from @Web3dAppCamp please? Just to verify that you are indeed the grant owner. Comment here when you've done that, and I will update thereafter. Thanks!

Thx a lot! I DM you at twitter by @Web3dAppCamp ~

**Comment by annikalewis** [comment]
Done!
