### ISSUE TITLE
reset BrightID verify. Thank you.

### ISSUE THREAD

**Issue by xwy705** [gitcoinco/web#9832]
Hi Gitcoier,

BrightID verify display used by another user before. I didn't have a certified BrightID to work with before. Please reset BrightID verify. Thank you.

"Failed to link your account in Gitcoin to your Bright ID. The Contextld : c463ab86-05e6-4406-90c5-41e7d6be0473 is used by another user before."

**Comment by 0xPr0f** [comment]
@xwy705 hello,  we will no longer be able to reset your incomplete BrightID verification. Resetting Bright IDs when they are not fully verified opens up the ability for users to sybil attack us. If you get successfully verified with your current pending account, then you can disconnect and restart the process of verification and connecting. So, please do not request to reset your BrightID. Thank you for your understanding.
