### ISSUE TITLE
My fund/account management interface

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#984]
As a Gitcoin user, I need an interface for my Gitcoin ETH address, so that I can inspect what happened with my funds, which funds were sent to other people from bounty contract, which are returned, which are received as a tip, and which are don't come from Gitcoin.

### Why Is this Needed?

This is needed, because in Etherscan interface this information is not accessible for non-proficient users (#968).

### Description

*Type*:  Feature

### Current Behavior
Currently, to audit Gitcoin account, I need to look into Metamask and guess, or into two tabs on Etherscan and guess too, because neither of these interfaces drill down to specific functions that Gitcoin performs.

### Expected Behavior
Timeline, like a commit tree in version control system, which shows transaction over time, and ideally draws lines between when issue was open and closed, mark issues that were refunded, mark tips, mark external transactions that don't belong to Gitcoin and filter them.

### Solution

I thing can draw it with a graphics / visualization designer by my side.

### Definition of Done
Monthly / weekly / yearly report as a timeline with summary and detailed activities that occurred in this period. Can be extensible, i.e. include people information into the result etc.

**Comment by kuhnchris** [comment]
I assume this was resolved with the "new" profile page. Closing this one in favor of that.
