### ISSUE TITLE
"zkSync checkout not supported due to the use of the token BNB" Bug

### ISSUE THREAD

**Issue by GabrelyanG** [gitcoinco/web#9851]
**Describe the bug**
So, the bug is that we got two types of possible payments, ETH and BNB. And everyone who adds our grant to their cart getting this "zkSync checkout not supported due to the use of the token BNB" and they can not pay, even if they are in Ethereum network.

**To Reproduce**
Go to https://gitcoin.co/grants/3637/moni-talks and just add this grant to the cart and you will get the bug.

**Expected behavior**
Obviously an opportunity to make a payment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29570977/145170571-8a74b021-f221-4e55-ae88-c0ce9fca713d.png)

**Desktop (please complete the following information):**

- OS: MacOS Big Sur
- Browser: Mozilla Firefox

**Comment by gdixon** [comment]
Hey @GabrelyanG,

Unfortunately BNB is not currently supported by zksync, see here for a full list of tokens which are supported: https://api.zksync.io/api/v0.1/tokens

I'm going to close this out, but please let us know if there is anything else we can help with.

**Comment by GabrelyanG** [comment]
But I didn't choose BNB to pay :) 
I know that BNB is not supported by zksync
