### ISSUE TITLE
Send tip tool fails to forward tip to github user

### ISSUE THREAD

**Issue by dolebas** [gitcoinco/web#986]
### User Story

As a tip tool user, I want the receiver of my tips to get the tips.

### Description

Used the tip tool to send a tip to myself but didn't get notified about the tip after the ui confirmed that I had been notified. No instructions for how to collect the tip has been received.

Tx: 0xbf867647b43bbc03f9e26b61cf170417cb6a15e52bd4b62b8017fde0d206b056

### Reproduction

Use the tip tool (without any "advanced" form fields), env specified below.

### Additional Information

| Software         | Version(s) |
| ---------------- | ---------- |
| Wallet          | MetaMask
| Browser  | Firefox
| Operating System | Android

**Comment by owocki** [comment]
Thanks for the bug repoert @dolebas -- looks like we failed to pull your email address off of your github profile, and thats why you didn't get any notification.  maybe it has to do with your privacy settings!?

if you go to gitcoin.co and login, and click on the menu in the top right (by your avatar), you will see a link to redeem your tip

as for how we 'fix it twice', im open to suggestions here

**Comment by dolebas** [comment]
Ok, will try that login then =) This is my current email preferences:

![image](https://user-images.githubusercontent.com/27515901/39310836-c125562e-496b-11e8-9e1f-30ee0dd2421f.png)

The "Keep my email address private" checkbox is not set so maybe there's a way to fetch the email, even if it is not publicly displayed on the profile.

![image](https://user-images.githubusercontent.com/27515901/39310980-117e4a22-496c-11e8-873b-d6a53c0ee774.png)

I will take a quick look at the github api and see if the email can be fetched somehow, with the current preferences.

**Comment by dolebas** [comment]
It looks like the email visibility must be set to public in order to pull it without explicitly requesting permission for viewing it. Maybe @mentions can be used instead when there's no public email?

**Comment by dolebas** [comment]
Regarding the claim tip tool, there seems to be some trouble with it too. After logging in and clicking the menu link for claiming, I am stuck at this box:

![image](https://user-images.githubusercontent.com/27515901/39312772-9cbcc6b4-4970-11e8-8dff-02101f1d0bb8.png)

**Comment by owocki** [comment]
hey @dolebas did you resubmit the tx in metamask by any chance? 

the txid i see in our admin ( https://etherscan.io/tx/0x925dc4f27b3fea0e34d728d04fe08e159e8d207354b347e2b8db25ba8f9a55fe ) does not match the txid that you posted above ( 0xbf867647b43bbc03f9e26b61cf170417cb6a15e52bd4b62b8017fde0d206b056 )  -- which is why the system thinks its 'waiting for transaction to be mined'

**Comment by dolebas** [comment]
Yes, I did, just to mess things up a little :)

But MetaMask suggested that I would, so I guess it could happen more times.

**Comment by owocki** [comment]
> Yes, I did, just to mess things up a little :)

you chaos monkey you! :)

let me noodle on a 'fix it twice' for the product here.  if we don't have the right txid, its hard to know that the tip is ready to be received.  not a big deal when gas prices are 1 gwei, but it is when the network is throttled at 20 gwei

**Comment by dolebas** [comment]
Update: The "redeem your tip" link is now gone, as well as the ether I sent.

A simple warning message that says: you will loose your ether if you resubmit the tx, would be helpful.

**Comment by owocki** [comment]
did you claim your tip after our exchange 21 days ago?  DM me on slack and i can give you a link to claim your ether if not

**Comment by owocki** [comment]
reaching out on slack now

**Comment by dolebas** [comment]
got your link on slack, seems to be some problem with the gas price estimation

![image](https://user-images.githubusercontent.com/27515901/40193547-de2d5008-5a07-11e8-91d8-e58aa261a873.png)

![image](https://user-images.githubusercontent.com/27515901/40193601-062f0da8-5a08-11e8-8609-d5759af19dfb.png)

https://etherscan.io/tx/0x3847fc8094402c4fc5d59d4443b601c4ddad0894f5076c575d1b494d56898d4d

**Comment by dolebas** [comment]
got lost again

![image](https://user-images.githubusercontent.com/27515901/40194351-6923760e-5a0a-11e8-8449-e3610eae276d.png)

**Comment by kuhnchris** [comment]
@dolebas did you happen to ever try that again to see if this still happens?

Let me know, thanks!
