### ISSUE TITLE
contribution are missing in polygon（matic）

### ISSUE THREAD

**Issue by wucisheng** [gitcoinco/web#9874]
One question, sir. I completed my donation in polygon,The message shows a successful transaction. But there is no record on the personal record. My address is ：0x7a65395f7E7dbBc83dB4537e20EB4a9510C32503
Hash of one of the transactions：
0xb7342a079057324bed9045665f0b96a8d61b726faca2a99767cf1bc5706521c9
![275C98BA-BA9E-441D-9FE5-ECB352824318](https://user-images.githubusercontent.com/85994805/145724933-4d5346c9-a2f8-498f-8d48-f3690ef18325.png)
![3F9E0A54-A9F9-4203-9724-F6BA1BDAF247](https://user-images.githubusercontent.com/85994805/145724936-d1863d46-6e9f-47f3-bfb9-3eb07e7872b7.png)

**Comment by lthrift** [comment]
If this issue has persisted, please contact support@gitcoin.co
