### ISSUE TITLE
Change address for the Giveth Grant

### ISSUE THREAD

**Issue by GriffGreen** [gitcoinco/web#9880]
We have a new Gnosis Safe that is a better place to collect funds than our old DAOstack DAO! 

Please change this grant

https://gitcoin.co/grants/795/giveth-20

To have the recipient be:

0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd

This is easy to verify as it is
giv.eth
giveth.eth
give.eth
donation.eth
...
revolution.eth

:-D

**Comment by annikalewis** [comment]
Done!

**Comment by GriffGreen** [comment]
@annikalewis... 

Annika. 

You are my hero. Thank you
