### ISSUE TITLE
Intermittent 503 errors on gitcoin.co

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#990]
![image 5](https://user-images.githubusercontent.com/513929/39316753-28d52af4-4937-11e8-8cd3-cce4aced9e15.png)

A few users have reported 503 errors on gitcoin.co.  It seems to go away when they delete their cookies. 

@mike.seese @owocki have reported this

**Comment by seesemichaelj** [comment]
I want to say I haven't visited the site on the machine that produced this error in several months; perhaps the cookie had an invalid value that was causing some path to a 503 error

**Comment by mbeacom** [comment]
Do we have any information on the times the users are encountering this?  It could be a matter of the time it takes for them to clear their cookies and refresh for the service to respond again (or would it persist for an indefinite amount of time until they clear cookies?).

We're aware of an issue during deployments at the moment.

**Comment by seesemichaelj** [comment]
I'm not quite sure what your scale of indefinite is, and I didn't wait several minutes to delete my cookies. I tried refreshing several times around 11:47AM EDT today. I tried refreshing by clearing the cache, still no response, took the above screenshot, cleared the cookies, refreshed, and it worked (while it was still 11:48AM EDT)

My gut feeling as it would occurred indefinitely until I cleared my cookies. I apologize for not saving my cookies before deleting them!

**Comment by mbeacom** [comment]
@seesemichaelj All good! I appreciate the information you've provided!

I'm going to look into this and try to spot possible issues in the logs.  If you had a stale session locally and haven't hit the site from that machine recently, it could be related to either session data or even the DNS/CDN flow changes we pushed out last week.

**Comment by kuhnchris** [comment]
This has been solved by the new load balancer so this "should" not happen anymore. If it does please make a new issue! Thanks
