### ISSUE TITLE
Please update my grants payout address

### ISSUE THREAD

**Issue by paulrberg** [gitcoinco/web#9911]
### Who

Paul Razvan Berg, username on Gitcoin "paulrberg".

### What

Please change the grant payout address on the following grants:

- https://gitcoin.co/grants/1657/paulrberg-open-source-engineering
- https://gitcoin.co/grants/943/create-eth-app

To this wallet address:

- 0x0298F4332e3857631385b39766325058a93e249f

### Why

I am trying to centralize my Ethereum activity in one wallet.

**Comment by paulrberg** [comment]
Can someone take a look at this?

**Comment by paulrberg** [comment]
Hey @owocki, could you talk to someone from the team to take a look at this?

**Comment by lthrift** [comment]
Hi @paulrberg please contact support@gitcoin.co to make changes to your grant

**Comment by paulrberg** [comment]
Hi @lthrift, I'm sorry, but I have already contacted `support@gitcoin.co` and they are the ones who sent me here.

**Comment by lthrift** [comment]
@paulrberg i’m so sorry - I’m closing this loop with support now

**Comment by lthrift** [comment]
I have confirmed with support that this is being worked out through the support ticketing flow.
