### ISSUE TITLE
0xd1b5AF7A6CD1f98Da5b8Ac247F839047254663A5

### ISSUE THREAD

**Issue by duongsky96** [gitcoinco/web#9915]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Browser Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by duongsky96** [comment]
0xd1b5AF7A6CD1f98Da5b8Ac247F839047254663A5

**Comment by Kaktus259** [comment]
@janus
