### ISSUE TITLE
avatar v2 (not ready to be worked on yet)

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#995]
(not ready to be worked on yet)

things we want in avatar v2:
- reset avatar
-  ability to make it your gitcoin profile image
- ability to add a 'gitcoin' watermark
- ability to make it your twitter, github, profile picture,
- random avatar
- non unicolor backgrounds (stripes, polka dots, etc)
- For Avatar Characteristics with more than 9 options, show persistent scrollbar to denote to users
that there are more than 9 options.

**Comment by owocki** [comment]
@vs77bb @mbeacom @PixelantDesign i am starting to spec the v2 avatar stuff here.. pls feel free to comment

**Comment by owocki** [comment]
sub tasks 

https://github.com/gitcoinco/web/issues/1051
https://github.com/gitcoinco/web/issues/1052

**Comment by owocki** [comment]
https://github.com/gitcoinco/web/issues/1053
https://github.com/gitcoinco/web/issues/1054

**Comment by owocki** [comment]
diff background colors
	keep my github username
	gitcoin watermark

**Comment by kuhnchris** [comment]
Prolly needs redefinition again. Closing this one as most of the tasks / points described above are resolved/done.
