### ISSUE TITLE
[spike] Setup our PR Workflow to prevent merging on failing Builds

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/web#9961]
We should not be promoting code when we have a failing build.

Update the PR workflow to prevent merging/deploying PRs with failing builds.

Consider moving flaky (intermittently failing tests) into a new build that does not block the team until they can be stabilised.

**Comment by nfrgosselin** [comment]
**Background context**
As part of revamping our [path to production](https://miro.com/app/board/uXjVOcEP-dM=/?invite_link_id=49959949653), we want to make sure our workflow doesn't allow us to promote code when we have a failing build. We need to update our PR workflow to allow us to move safely and nimbly.

**Definition of done**
- Updated PR workflow prevents us from merging/deploying PRs with failing builds.
- Our PR workflow allows us to move flaky tests into a new build that does not block the team while they are stabilized.

**Comment by schultztimothy** [comment]
@chibie has a functioning workflow going! It should be as easy as placing protections on master/staging once the new pipeline is functional.

it will be interesting to see if cypress functions better in the github environment. If not [cypress provides support](https://docs.cypress.io/guides/continuous-integration/github-actions) to help minimize resource consumption within github actions. As a last resort we can make the cypress step optional for merge.

**Comment by schultztimothy** [comment]
@kevinrolsen @nfrgosselin I created this ticket to restrict merging until there is a green build: https://github.com/gitcoinco/web/issues/10075. Just lmk if I can do anything else for this.

I attempted to update the setting but it doesn't look like I ahve the right permissions.

**Comment by nfrgosselin** [comment]
Thanks @schultztimothy! I just added it to our backlog and assigned @thelostone-mc and @kevinrolsen

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/web/issues/10075#issuecomment-1031319695
