### ISSUE TITLE
chore: add fixtures for grants claim

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#9984]
update to include fixtures

**Description**
After the last round of fixes on the claims experience, we need to add backend tests to the claims page to ensure good test coverage. 

**Acceptance Criteria**
Backend tests written for claims page

**Comment by ksolo** [comment]
@nfrgosselin I added a fair amount of tests for the claim route when working on GITC-715. It's not merged yet but we can review what additional coverage is needed

**Comment by nfrgosselin** [comment]
Thanks @ksolo —> tagging @thelostone-mc in here as well. Aditya, can you take a look and think about what additional coverage you're looking for?

**Comment by ksolo** [comment]
@thelostone-mc Here are the tests - https://github.com/gitcoinco/web/blob/e17d9636123e4c6a7c66137f3fbd890546b815e2/app/grants/tests/views/test_clr_matches_view_function.py

**Comment by thelostone-mc** [comment]
Oh solid this is perfect.
We still need to add fixtures for this as well for those tables but i guess this is alright


@schultztimothy brought up the point on having fixutres (dummy data) and I it makes sense
