### ISSUE TITLE
Kill centralized /quadraticlands and forward to DAO-owned page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#9987]
**User Story:**
As a Gitcoin user
I want to only see the decentralized version of the Quadratic Lands site
So that I am only seeing the correct, community-owned information

**Acceptance Criteria**
GIVEN that I am on gitcoin.co
WHEN I try to visit https://gitcoin.co/quadraticlands
THEN I am sent to http://decentralized.quadraticlands.com/

**Product & Design Links:**
we no longer should be maintaining this portion of the site.  it is now managed by the DAO per https://gitcoin.co/issue/gitcoinco/skunkworks/239/100026286

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
Ported over from https://gitcoin.atlassian.net/browse/GITC-348?atlOrigin=eyJpIjoiMGUyMWM0MmVmZDliNGYyYThjNDhlMDNiY2UwNWE3N2MiLCJwIjoiaiJ9

**Comment by schultztimothy** [comment]
@nfrgosselin @thelostone-mc While looking into #10016 I ran into an error here: https://gitcoin.co/profile/trust where the trust bonus is trying to access the profile's players. Which looks like is located in the quadraticlands model https://github.com/gitcoinco/web/blob/dc3acc5453d1db5b3fdef990ab8b438f99b45413/app/quadraticlands/models.py#L214.

Thanks!

**Comment by thelostone-mc** [comment]
Ah this is the quad diplomacy which was a fun experiment we had built out.

I would lean towards removing this as 
- it was never marketed + only staff enabled 
- we have only test data in live

https://gitcoin.co/_administrationquadraticlands/game/

**Comment by schultztimothy** [comment]
Awesome thanks for the clarification!
