### ISSUE TITLE
Update zkSync Tx Hash flow

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#9990]
User Story:
As a grant donor
I want to know when it's safe to close my cart
So that my contribution will count towards my chosen grant(s) matching funds

Acceptance Criteria
GIVEN that I am on gitcoin.co/grants/cart and have selected checkout with zkSync
WHEN I click "Proceed" on the zkSync modal
THEN a new tab is opened with the zkSync checkout experience
AND I see the "Confirming transaction..." modal on the Gitcoin cart tab

GIVEN that I am checking out grant contributions on zkSync and my transaction has confirmed
WHEN I click "Close"
THEN the zkSync tab closes
AND my Gitcoin tab redirects to gitcoin.co/grants/explorer/
AND I see the "Thank you for contributing..." modal

Product & Design Links:
Figma Link: "[Ready for Dev: Tx Hash](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=48%3A5246)" -> "Tx Hash (zkSync)"
Product Brief: [Streamline donor checkout experience](https://www.notion.so/gitcoin/Streamline-donor-checkout-experience-4c70c5926a044facbdb65105d1316a44)

Tech Details:

Open Questions:

Notes/Assumptions:

**Comment by nfrgosselin** [comment]
Looks good to me

**Comment by EmHsiehGitcoin** [comment]
👀. 👍  🙆. ✔

**Comment by nfrgosselin** [comment]
@chibie FYI I pulled this back — the design file is updated, LMK if you need anything else

cc: @EmHsiehGitcoin @thelostone-mc
