### ISSUE TITLE
Delay wallet connect modal

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/web#9991]
**User Story:**
As a grant donor
I want to see the wallet connect overlay only when I absolutely have to
So that I have a smoother checkout experience

**Acceptance Criteria**
GIVEN that I have grants in my cart and I do not have a wallet connected
WHEN I arrive on gitcoin.co/grants/cart
THEN I do not see the wallet connect overlay

GIVEN that I am on gitcoin.co/grants/cart and I do not have a wallet connected
WHEN I click a checkout option
THEN I see the wallet connect overlay

GIVEN that I am on gitcoin.co/grants/cart and I do have a wallet connected
WHEN I click a checkout option
THEN I see my wallet transaction overlay

**Product & Design Links:**
Figma: "[Ready for Story: Checkout](https://www.figma.com/file/8QjqOzDBd4HiE37YqcocK7/GR13?node-id=133%3A5208)" Section 2: Delay modal
Product Brief: [Streamline donor checkout experience](https://www.notion.so/gitcoin/Streamline-donor-checkout-experience-4c70c5926a044facbdb65105d1316a44)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

**Comment by nfrgosselin** [comment]
This doesn't seem to be working for me @gravityblast. I'm on staging, don't have a wallet connected, and I see the wallet connect overlay as soon as I land on the cart.

**Comment by gravityblast** [comment]
@nfrgosselin I'm not sure when it was deployed, but it was merged when I was away, I see it now in staging. 
When I open the `/grants/cart` page I don't see the modal until I start the checkout. Can you try again now please? or please DM me in case you can't still see the changes.

**Comment by EmHsiehGitcoin** [comment]
hmmm, I see the staging refreshed but I also still see the modal popping up when I first land at cart

**Comment by nfrgosselin** [comment]
@EmHsiehGitcoin I just cleared my cache and it worked for me. This is good from my end if it works for you!

Thanks @gravityblast 🙏
